### ISSUE TITLE
CMake Linux FMU compilation failing with SUNDIALS errors

### ISSUE THREAD

**Issue by Zbm1996** [OpenModelica/OpenModelica#10021]
@AnHeuermann Hi, recently, I tried to compile OpenModelica on Linux OS and still met the same problem. 
I used 
```
cmake -S . -B build_cmake -DCMAKE_BUILD_TYPE=Release -DOM_USE_CCACHE=OFF -DOM_ENABLE_GUI_CLIENTS=OFF
```
and then "make -j40 install -Oline" to compile the project. The tested mo was still the same mo as below:
```mo
model Van
  Real y_1 (start=2);
  Real y_2 (start=0);
  parameter Real eta=1000;
 
equation
  der(y_1)= y_2; 
  der(y_2)=-y_1 + (1 - y_1*y_1)*y_2*eta;
end Van;
```

and the tested mos file was also the same as below:

```mo
cd("/home/myname/workspace/test/testcases/model/VanDerPol"); getErrorString();
loadFile("Van.mo"); getErrorString();
setCommandLineOptions("--fmiFlags=s:euler"); getErrorString();
// This turns on CMake based FMUs and tells them to pack all dependencies inside the FMU.
setCommandLineOptions("--fmuCMakeBuild=true --fmuRuntimeDepends=modelica"); getErrorString();
buildModelFMU(Van, version="2.0",  fmuType="cs", platforms={"dynamic"}); getErrorString();
```

The error log is showed below:
[linux_error.txt](https://github.com/OpenModelica/OpenModelica/files/10357855/linux_error.txt)

My Ubuntu version is 18.04 and there was no error showed in cmake process. Can you reproduce this problem yourself or are there any error in my working process?

_Originally posted by @Zbm1996 in https://github.com/OpenModelica/OpenModelica/issues/9635#issuecomment-1373201392_

**Comment by AnHeuermann** [comment]
Works for me (Ubuntu 20.04.5 LTS, omc v1.21.0-dev-182-ga48ec07d98-cmake, default CMake build options for omc).

I don't have the C source file for CVODE (`FMU/sources/simulation/solver/cvode_solver.c`) in my FMU.
You should have
```cmake
# CVODE needed
set(NEED_CVODE FALSE)
```
in your `FMU/sources/CMakeLists.txt`.

Maybe try updating your OpenModelica repository and build again.

**Comment by Zbm1996** [comment]
> Works for me (Ubuntu 20.04.5 LTS, omc v1.21.0-dev-182-ga48ec07d98-cmake, default CMake build options for omc).
> 
> I don't have the C source file for CVODE (`FMU/sources/simulation/solver/cvode_solver.c`) in my FMU. You should have
> 
> ```cmake
> # CVODE needed
> set(NEED_CVODE FALSE)
> ```
> 
> in your `FMU/sources/CMakeLists.txt`.
> 
> Maybe try updating your OpenModelica repository and build again.

Thanks for help. After I set the env path of OPENMODELICAHOME in Linux system, the bug was fixed. I could find this requirement in MSYS/MinGW related configuration documents, but there was no such kind of information in 
https://github.com/OpenModelica/OpenModelica/blob/master/README.cmake.md 
or 
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md.

Sorry for bothering, but I still have a problem to consult. After I add  
-DOM_ENABLE_GUI_CLIENTS=OFF
to disable gui function on MSYS cmaking process, I couldn't generate fmu successfully but everything was right on Linux. 

My CMake command is showed below:
cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DOM_USE_CCACHE=OFF -DOM_ENABLE_GUI_CLIENTS=OFF
The cmake process ran successfully, but when I used omc.exe to generate fmu from the Van.mo mentioned above. I received the error below:
[linux_error.txt](https://github.com/OpenModelica/OpenModelica/files/10379667/linux_error.txt)

![image](https://user-images.githubusercontent.com/25106682/211480536-dc50a18a-d5a8-4d32-9647-fffdba18fa09.png)
This was similar to the error in which I couldn't resolve api-ms-win-core-apiquery-l1-1-0.dll. However, I ldd the related dll and the result was showed below.
![image](https://user-images.githubusercontent.com/25106682/211481010-c267945f-f307-4e52-aad5-c88b3e8186a2.png)
Actually,  libgcc_s_seh-1.dll could be found and accessed through the given path "/mingw64/bin/libgcc_s_seh-1.dll" in MinGW shell.

Can you reproduce this problem or are there any hint for this? 
Sorry for continously bothering and sincerely thanks for help.

**Comment by AnHeuermann** [comment]
> After I set the env path of OPENMODELICAHOME in Linux system, the bug was fixed.

You don't need `OPENMODELICAHOME` on Linux systems (I don't have it set). But of course the bin directory of omc has to be in your `PATH` to use it. Maybe it was something else you changed which fixed your issue.
But your issue seems to be resolved, so I'll close this issue.

@Zbm1996 you can open a new issue about your Windows question so we have one problem per issue.
