### ISSUE TITLE
Bug in plot legend

### ISSUE THREAD

**Issue by andreamarino7** [OpenModelica/OpenModelica#10044]
### Description

In the plot legend appear the items of quantities of an object plotted previously no longer plottable after the removal of the object in the model

### Steps to Reproduce

1. Create a model (i.e. electrical) and run it (Fig.1);
2. Plot some quantities (i.e. current on current sensor). Don't close the plot windows, (Fig.2);
3. Remove from the model one object from which you have plotted before (in this case the current sensor) and restore the connection between the objects and simulate the update model (Fig.3);
4. Open plots section and observe that the plot legend has permament items which is impossible to remove (Fig.4). If you plot something on these plot windows the new plots have the same color of the removed one (Fig.5).
5. To have a clean plot legend you have to open a new window.

### Expected Behavior

I expect that the plot legend items of a removed object is removed from the old windows because they are no longer plottable or visible.

### Screenshots

The following screenshots follow the step to reproduce the bug

![1](https://user-images.githubusercontent.com/68420380/212299141-7990eb27-9c6b-405b-99f7-0a533fc07088.png)
![2](https://user-images.githubusercontent.com/68420380/212299147-19acfa2d-da67-4dcc-9440-c192d75efa04.png)
![3](https://user-images.githubusercontent.com/68420380/212299148-b7757641-a0de-4c71-ad2d-2be8095ce999.png)
![4](https://user-images.githubusercontent.com/68420380/212299149-9a812bee-1084-448e-acd3-79e21ac7243f.png)
![5](https://user-images.githubusercontent.com/68420380/212299150-5f3b318f-b964-4874-8e5d-fbc7a0ab2222.png)

### Version and OS

 - OpenModelica Version: OpenModelica v1.18.0 (64-bit)
 - OS: Windows 11, 64 bit
 - Versions of used Modelica 3.2.3

**Comment by andreamarino7** [comment]
This bug is still present in OpenModelica v1.20.0 (64-bit).

**Comment by casella** [comment]
Thanks for reporting, @adeas31 will look into it ASAP.
