### ISSUE TITLE
Parameter with HideResult annotation can not be modified for resimulation

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10054]
### Description

If you have a model that contains a parameter with a ```HideResult=true``` annotation, the parameter cannot be changed to resimulate the model with the modified parameter.

### Steps to Reproduce
e.g. if your model contains a parameter
```modelica
parameter Real a = 1.0 annotation(HideResult = true);
```
And you restart the simulation with:
```
simulate(MyTestModel,simflags="override=a=2.0")
```
This has no effect to the simulation results

### Version and OS

 - OpenModelica Version: 
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
The idea is to modify the parameters with the `-override` simulation flag. The current logic of the runtime apparently prevents that, probably because HideResult=true set the `isModifiable` attribute to false. This should be corrected.

@perost, I saw `this commit` with a simple Google search, is that relevant?

**Comment by perost** [comment]
> @perost, I saw `this commit` with a simple Google search, is that relevant?

If it's one of my commits, then probably not. But it seems your link was lost somehow.

**Comment by casella** [comment]
Here it is, sorry: [58ea53d](https://trac.openmodelica.org/OpenModelica/changeset/58ea53d9fe3091aea58df89086df9c981e2e19a1/OpenModelica)

**Comment by perost** [comment]
> Here it is, sorry: [58ea53d](https://trac.openmodelica.org/OpenModelica/changeset/58ea53d9fe3091aea58df89086df9c981e2e19a1/OpenModelica)

That's about deciding which variables should be protected when creating record constructors. There just happened to be a function called `isModifiable` earlier, which was not at all related to the `isModifiable` attribute you're talking about.

**Comment by casella** [comment]
OK, just tried 😅

**Comment by adeas31** [comment]
I think the attribute is called `isValueChangeable` and not `isModifiable`.

**Comment by casella** [comment]
If I understand correctly, isValueChangeable is set [here](https://github.com/OpenModelica/OpenModelica/blob/a9f36c021fdb70ed479f8a352ec85057dfd0c53c/OMCompiler/Compiler/SimCode/SimCodeUtil.mo#L9898) by a function call that ultimately calls [isProtectedVar()](https://github.com/OpenModelica/OpenModelica/blob/a9f36c021fdb70ed479f8a352ec85057dfd0c53c/OMCompiler/Compiler/BackEnd/BackendVariable.mo#L1573), that treats `annotation(Hide = true)` the same as `final`.

I'm not sure if this attribute is only used to determine what can be changed with the `-override` simflag, or also to determine what can be changed in OMEdit when resimulating. @adeas31 can you please comment on that?

**Comment by adeas31** [comment]
> I'm not sure if this attribute is only used to determine what can be changed with the -override simflag,

I have no idea. Maybe someone from runtime developers can tell.

> or also to determine what can be changed in OMEdit when resimulating.

Yes, OMEdit uses this to allow what can be changed.

**Comment by casella** [comment]
> If I understand correctly, isValueChangeable is set [here](https://github.com/OpenModelica/OpenModelica/blob/a9f36c021fdb70ed479f8a352ec85057dfd0c53c/OMCompiler/Compiler/SimCode/SimCodeUtil.mo#L9898) by a function call that ultimately calls [isProtectedVar()](https://github.com/OpenModelica/OpenModelica/blob/a9f36c021fdb70ed479f8a352ec85057dfd0c53c/OMCompiler/Compiler/BackEnd/BackendVariable.mo#L1573), that treats `annotation(HideResult = true)` the same as `final`. This is not really required by the MSL, [Section 18.3](https://specification.modelica.org/maint/3.5/annotations.html#annotations-for-code-generation), which only talks about "showing results", not changing parameter values.
> 
> I'm not sure if this attribute is only used to determine what can be changed with the `-override` simflag, or also to determine what can be changed in OMEdit when resimulating. 

@AnHeuermann can you please comment on that?

**Comment by AnHeuermann** [comment]
I'm not so sure what the Backend is doing here. Probably @kabdelhak or @phannebohm know this.

**Comment by kabdelhak** [comment]
It's this function
```
public function isProtectedVar
 "Returns the DAE.Protected attribute, overridden with HideResult annotation"
```
It treats `hideResult=true` as `protected` which results in it being  `isValueChangeable=false`. Can i just remove this behavior or is there something to be aware of?

**Comment by kabdelhak** [comment]
Besides the broken userguide build (which i assume is not my doing and a server hickup) i could push it, fixes the problem and doesn't break tests. Any objections?

i just removed the "hide result implies protected" rule.

**Comment by casella** [comment]
LGTM. The point was precisely that we still want to be able to modify stuff which is hidden, but not protected.

**Comment by casella** [comment]
@niklwors please check with your applications and reopen if something's still wrong.

**Comment by niklwors** [comment]
Thank you very much, it works now.
