### ISSUE TITLE
The class loader may end up in an endless loop if libraries have indirectly incompatible dependencies

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10055]
### Description
Save this package in a file
```modelica
package P
  model M
    parameter Real p = 1;
  end M;
  annotation(uses(PowerGrids(version="1.0.2"), ScalableTestSuite(version = "2.0.3")));
end P;
```
and try loading it with OMEdit. Since the two used packages use an incompatible version of the MSL (3.2.3 vs. 4.0.0), OMedit enters an endless loop loading and unloading the MSL, but it doesn't tell the end user what the problem is.

### Expected Behavior
The class loader should first scan all the dependencies and figure out if they are satisfiable with backwards compatibility constraints. If not, it should clearly explain why.

Related to #9996, keeping @ceraolo in the loop.

**Comment by sjoelund** [comment]
Command-line seems to work fine, so it's probably an OMEdit issue

**Comment by casella** [comment]
Thanks @sjoelund!

This is the command-line outputs with the MWE of this ticket: if I start with MSL 4.0.0 loaded, I get this message:
```
loadFile("d:/temp/OMEdit/P.mo");getErrorString()
true
"Notification: Automatically loaded package PowerGrids 1.0.2 due to uses annotation from P.
Warning: PowerGrids requested package Modelica of version 3.2.3. Modelica 4.0.0 is used instead which states that it is only compatible with a conversion script. Use convertPackageToLibrary(PowerGrids, Modelica, \"4.0.0\") to run the conversion script or proceed with potential issues as a result.
Notification: Automatically loaded package ScalableTestSuite 2.0.2 due to uses annotation from P.
```
if I start with no MSL loaded I get this message
```
Notification: Automatically loaded package PowerGrids 1.0.2 due to uses annotation from P.
Notification: Automatically loaded package Modelica 3.2.3 due to uses annotation from PowerGrids.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation from Modelica.
Notification: Automatically loaded package ScalableTestSuite 2.0.2 due to uses annotation from P.
Warning: Requested package Modelica of version 4.0.0, but this package was already loaded with version 3.2.3. There are no conversion annotations for this version but 4.0.0 is newer than 3.2.3. There is a possibility that 3.2.3 remains backwards compatible, but it is not loaded so OpenModelica cannot verify this.
```
So, the command-line loader just issues a warning that there are incompatibility issues in both cases. 

I'm not 100% sure what is the logic that OMEdit uses, but I guess as soon as it detects that a different version of a loaded library is required, it proposes to unload everything and restart the loading process. This simple logic works fine to solve the issue of unloading the default loaded MSL in case the loaded library uses a different one, but then assumes that all the dependencies are consistent.

One easy option to handle the case of this ticket is that we maintain the same logic on the first load attempt, but in case there are still problems when reloading the library, we show the notifications and warnings, and then cancel the operation.

@ceraolo, would that be OK for you?

**Comment by adeas31** [comment]
> One easy option to handle the case of this ticket is that we maintain the same logic on the first load attempt, but in case there are still problems when reloading the library, we show the notifications and warnings, and then cancel the operation.

@casella #10061 tries to fix as you suggested above. However, instead of canceling the operation OMEdit loads in the second attempt. This is now same as what we can do from command line. Let me know what you think. We can of course change it to cancel the operation and not load anything.

**Comment by casella** [comment]
Loading MSL 4.0.0 instead of 3.2.3 (or the other way round) means that most models, which use SI units, are going to be broken. IMO there's no point doing it in the GUI. People will probably ignore the warning and then get annoyed that nothing works.

I would recommend that we cancel the operation instead. 

Additionally, I agree with @ceraolo that we should pass more information about which libraries are causing the conflicts, so the user can act appropriately, e.g. updating them to more recent versions.

**Comment by adeas31** [comment]
> Loading MSL 4.0.0 instead of 3.2.3 (or the other way round) means that most models, which use SI units, are going to be broken. IMO there's no point doing it in the GUI. People will probably ignore the warning and then get annoyed that nothing works.
> 
> I would recommend that we cancel the operation instead.

OK. #10061 does this now.

> 
> Additionally, I agree with @ceraolo that we should pass more information about which libraries are causing the conflicts, so the user can act appropriately, e.g. updating them to more recent versions.

This is more complicated. OMEdit doesn't have much information. We should do this in the class loader so the command line users can also benefit from it.

Also if one look at the current messages then one can see that which library is loading which other library and version. For example this case `PowerGrids 1.0.2` needs to be updated to use `Modelica 4.0.0`. So its bit hard to say what more can be improved. Maybe we can also issue a message that `Modelica 4.0.0 is available, update PowerGrids 1.0.2 to use it`.

**Comment by max-privato** [comment]
> Also if one look at the current messages then one can see that which library is loading which other library and version.

I don't understand this. I tried with @casella's example and got:
![image](https://user-images.githubusercontent.com/37046832/213168487-8cd37399-5f8b-4a32-8f0b-aa8d2cc4e4b4.png)

So, where do I find "which library is loading which other library and version"?

**Comment by adeas31** [comment]
> > Also if one look at the current messages then one can see that which library is loading which other library and version.
> 
> I don't understand this. I tried with @casella's example and got: ![image](https://user-images.githubusercontent.com/37046832/213168487-8cd37399-5f8b-4a32-8f0b-aa8d2cc4e4b4.png)
> 
> So, where do I find "which library is loading which other library and version"?

With #10061 OMEdit try once to resolve the dependencies issue and show the message box as above. If you click on `Unload all & Reload` then you will be able to load everything correctly in most cases but if it fails again then OMEdit will cancel the loading operation and show errors in the messages browser like this,

![image](https://user-images.githubusercontent.com/4007231/213171263-912e5a54-d4e7-456d-85e8-081561f6ed8f.png)

There you can see that PowerGrids caused the loading of old Modelica version.
