### ISSUE TITLE
Alignment of text objects in icon is inverted

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#10062]
### Description

Having a text object defined in icon annotation with an alignment attribute (e.g. 
`Text(
          fontName="Bosch Sans",
          extent={{420,-100},{160,-60}},
          visible = true,
          textColor={0,0,0},
          horizontalAlignment=TextAlignment.Left,
          textString="m=100")`
it will appears as textalignment.right after instanciation into new diagram layer.

### Version and OS

 - OpenModelica Version :OpenModelica v1.21.0-dev-177-g115eb96484 (64-bit)
 - OS:  Windows 10, 64 bit

### Additional Context

Same behavior with and without --NAPI start

**Comment by adeas31** [comment]
See #8236

**Comment by abuntrock** [comment]
This ticket is fixed with the current nightly (v1.23.0-dev-257-gcfdfeb87e5). Probably as a result of #11691.
Thanks a lot.
