### ISSUE TITLE
Connects of constrainedby baseclasses raises errors while opening

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#10088]
### Description

With the new api errors will be raised during parsing of replaceable Model declarations.
All connections made in the constrainedby class seems to be parsed multiple times.
Minimal example works fine with old api.

Error msg:
Connection connect(gainD.u, realExpressionD.y) already exists.
Example (.mo instead of txt):
[TestOMC.txt](https://github.com/OpenModelica/OpenModelica/files/10479045/TestOMC.txt)

### Version and OS

OpenModelica Version :OpenModelica v1.21.0-dev-177-g115eb96484 (64-bit)
OS: Windows 10, 64 bit

**Comment by abuntrock** [comment]
I tested this with a nightly from last week (v1.22.0-dev-178-gabbf3e40b3 (64-bit)) and it seems fixed by some other updates during the last months regarding the new API.
@sbaetzing you can close this then
