### ISSUE TITLE
Unnecessary popup window for the "Check Model" action.

### ISSUE THREAD

**Issue by achary** [OpenModelica/OpenModelica#10100]
### Description
This is not strictly a hard bug, but rather annoying UI behaviour that disturbs a workflow when using OMEdit on a [tiling windows manager](https://en.wikipedia.org/wiki/Tiling_window_manager) (I'm using i3 on Ubuntu).

### Steps to reproduce

1. Use a tiling windows manager.
2. Launch OMEdit and load an example model (like Modelica.Blocks.Examples.Filter).
3. Press "Check Model" button.
4. An annoying window pops-up only to tell:
   
```    
Check of Modelica.Blocks.Examples.Filter completed successfully.
Class Modelica.Blocks.Examples.Filter has 34 equation(s) and 34 variable(s).
14 of these are trivial equation(s).
```

5. On a **tiling window manager**, this window occupies half of the screen, effectively resizing the main window to half its size. It requires an extra step of closing it before the work can be continued.

### Screenshots

"Check Model" popup window on a tiling windows manager (like i3) looks like this:

![image](https://user-images.githubusercontent.com/1964880/214551435-baf8c269-06a6-47b8-a917-c8c480481197.png)

### Expected behavior

In general, most of other dialog windows in OMEdit are proper "dialog" windows, which do display correctly an an small-sized overlapps on tops of main window without resizing it. 
The "Check Model" action opens a "regular" window, which is then laid upd by whatever window manager does with regular windows.

Also, I would argue, the ergonomics of having this "Check Model" window in the first place is questionable. I suggest **removing** this window, and display the few lines of a message in the Message Browser panel, just like the twin button/action "Check All Models"  does; it just writes the messages to the Message Browser text box without any windows opened. This is much less distractive and does not require closing the window manually.

### Version and OS

Connected to OpenModelica 1.20.0
Connected to OMSimulator unknown-linux

Ubuntu 20.04 for x86_64 with i3 window manager

**Comment by ceraolo** [comment]
You taught me today that this window can be cancelled jut by hitting ESC, which is very fast.
So, I don't dislike seeing the outcome of a check action in a window in the foreground, which can be cancelled just hitting ESC.
But I'm also not against putting the same information in the Messages Browser.

**Comment by adeas31** [comment]
It will be either in the Messages Browser or in a separate window but not both.

Normally, the output of check model is not too much so it makes sense to just display it in the Message Browser.

**Comment by ceraolo** [comment]
> It will be either in the Messages Browser or in a separate window but not both.
Yes, I meant this
