### ISSUE TITLE
Do not automatically rescale plots  in these cases (enhancement)

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10118]
### Description
In many cases OMEdit rescales zoomed diagrams, while it would be better to leave the zoom level (i.e. min and max values on the horizontal and vertical axes) unchanged. 
If OMEdit rescales, it may need many mouse and keyboard operations to reach a previously determined display window (min and max values).
If it does not rescale, if this is what the user wants rescaling will just require a click on "Fit in View" button.

In the following cases OMEdit unzooms, 
- when toggling signs (see #8877)
- when re-simulating 
- when using Setup menu (e.g. just changing the line width now rescales)

This ticket is to request OMEdit not to rescale in these cases.

### Expected Behavior
OMEdit should not rescale in the cases listed above

### Version and OS
OM 1.20.0

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
This is because the `Auto Scale` option (top left button in each plot toolbar) is on by default. You can disable it by clicking on the icon, then the zoom is retained no matter which operations are done on the plot.

If you don't like `Auto Scale` to be on by default, you can change the setting in Tools | Options | Plotting | General.

**Comment by ceraolo** [comment]
aha,
maybe I was not enough concentrated when issuing this ticket.

**Comment by ceraolo** [comment]
Ipve made today further checks. I could only do it on: 
    1.22 beta6, 
and
    1.23.0~dev-151-g8fef40a
(the latest linux available version)

I saw that toggling sign reset scales even if autoscale is unckecked.
Steps:
1. plot a curve (it is plotted with autoscale)
2. zoom. Now you want to toggle sign, and therefore you unckeck auto scale
3. toggle sign => the plot is unzoomed (it shouldn't).
