### ISSUE TITLE
libSimulationRuntimeC.dll修复

### ISSUE THREAD

**Issue by lxjiayou** [OpenModelica/OpenModelica#10110]
### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
Unfortunately there is no actual description of what the issue is. @lxjayou please add it, then we can reopen it.
