### ISSUE TITLE
Partitioning in the NB scales badly

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10122]
Please check the [newInst-newBackend report of ScalableTestSuite](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/ScalableTestSuite.html). The backend time of the `DistributionSystemModelicaIndividual` models scale very badly with the the system size. In particular, the Partitioning method called after Causalize scales like this:

| N | Time|
|--|--|
|10| 0.9|
|20| 18|

Now, the model with N = 20 has four times as many components, variables, and equations as the one with N = 10, but it takes more than 16 times as much, so the method scales as O(N_eq)^2.

This is not a critical issue, because these models with many instances of the same model should be handled by first merging them into arrays, using `-d=mergeComponents` in the NF. Maybe once that stuff is moved into an array, this problem will be solved automatically. I'll check that by putting that flag in LargeTestsSuite.

**Comment by casella** [comment]
Hopefully fixed by #10264.

**Comment by casella** [comment]
After #10264, the Partitioning method called after Causalize on `DistributionSystemModelicaIndividual` scales [like this](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/ScalableTestSuite_NB.html):

| N | N_eq| Time|
|--|--|--|
|10| 2100| 0.013|
|20| 8200|0.624|
|40| 32300 |9.251|

The new implementation is 30 times faster than the old one, which is good, but still scales as O(N_eq^2). This makes it impossible to go above 100,000 equations for this kind of models.

What is strange is that the [OB performance of DistributionSystemModelicaIndividual](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) scakes as O(N_eq). Why should the NB have worse scaling properties than the OB?

**Comment by phannebohm** [comment]
There is a small subtlety in the implementation of the disjoint-set forest we use for partitioning in the new backend, namely a node rank for merging. I skipped that because I thought it was unnecessary, but I can put that in and we'll see if that fixes it already.

**Comment by casella** [comment]
Thanks @phannebohm! I'll run the test again and check.

**Comment by casella** [comment]
Ops, I didn't check that. No problem

**Comment by casella** [comment]
I only see [the one that I started](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/6205/). Still running.

**Comment by casella** [comment]
I checked the [latest report](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/ScalableTestSuite.html) now, and unfortunately the second Partitioning call still scales as O(N_eq^2).

**Comment by casella** [comment]
@mahge, could you please carry out some profiling analysis similar to what you did in #11302, so that @phannebohm could try to fix this issue as well?

**Comment by casella** [comment]
I checked again the performance of the Partitioning method after Causalize on the [DistributionSystemModelicaIndividual](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/files/ScalableTestSuite_ScalableTestSuite.Electrical.DistributionSystemDC.ScaledExperiments.DistributionSystemModelicaIndividual_N_20_M_20.err) of [ScalableTestSuite](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/ScalableTestSuite.html). These are the results:

| N | N_eq| Time|
|--|--|--|
|10| 2099| 0.004288|
|20| 8189|0.02178|

Unfortunatetly the N = 40 model blows up the process because it doesn't use the sparse solver, before it had a chance to dump the information. In any case, from the first two instances it seems that the problem has been resolved in the meantime.

**Comment by phannebohm** [comment]
Nice! Probably due to a more accurate adjacency matrix. The steps are proportional to the number of edges in the graph.

**Comment by casella** [comment]
Update about the performance of the Partitioning method after Causalize on the `DistributionSystemModelicaIndividual` with the heavy-tests [ScalableTestSuite_NB](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/ScalableTestSuite_NB.html) job.

| N | N_eq| Time|
|--|--|--|
|10| 2099| 0.001481|
|20| 8189|0.009447|
|40| 32369|0.05031|

Looks pretty good.

Unfortunatetly the N = 40 model blows up the process because it doesn't use the sparse solver, before it had a chance to dump the information. In any case, from the first two instances it seems that the problem has been resolved in the meantime.
