### ISSUE TITLE
Wrong display of inherited start attribute choice

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10139]
### Description

The OMEdit GUI has problems when selecting start values for variables in instantiated classes. If the default start value in the original class definition has `fixed=false` and the checkbox is clicked once in the instance the description string is changed from `inherited: (false` to `inherited: (true`. This problem occurs with the old and new API. Since nothing is added to the modelica text it appears to be a sole GUI bug.

### Steps to Reproduce

1. Create a class with a variable that has no _fixed=true_ modifier. An example could be:
```modelica
  Modelica.Units.SI.Velocity v(displayUnit="mm/s", start=0.0) "Velocity" 
  annotation (Dialog(showStartAttribute=true, group="Initialization", tab="Initialization"));
```
2. Instanciate this class and open its parameter dialog. 
3. Click on the checkbox next to the variable `v.start`. There the last choice is `inherited: (false: start-value is only a guess value)` as depicted in the first screenshot.
4. Select either the true  or inherited choice and click on the checkbox again. Now the last choice now reads `inherited: (true: start-value is used to initialize)` as depicted in the second screenshot. 

### Expected Behavior

The display of the inherited choice next to the start value of a variable does not depend on the selection of any of those choices.

### Screenshots

Will be added by @niklwors in a comment because I am not allowed to upload them from my work computer.

### Version and OS

 - OpenModelica Version: 1.21-dev
 - OS: Windows 10, 64 bit

Thanks for looking into it
Aaron Buntrock - Bosch rexroth

**Comment by niklwors** [comment]
Picture 1:
![image001](https://user-images.githubusercontent.com/12269776/216350517-e6a1955d-e873-45ff-8aa9-2cb33bc96a95.png)


Picture 2:
![image002](https://user-images.githubusercontent.com/12269776/216350502-3bc94ada-0fc2-4cee-93b2-fda8d3741444.png)

**Comment by abuntrock** [comment]
@adeas31 I checked this with today's nightly and it now works as expected. Thanks a lot.
