### ISSUE TITLE
Wrong colors in animation of fullRobot

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#10144]
### Description

The animation of fullRobot shows the wrong colors.

### Steps to Reproduce

Run the animation of `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` in OMEdit.

### Expected Behavior

The correct colors should be show as defined in dxf file.

### Screenshots

OMEdit

![image](https://user-images.githubusercontent.com/4007231/216375121-4958228d-b29d-4437-bc96-c22cb0c705a9.png)

Dymola

![image](https://user-images.githubusercontent.com/4007231/216374971-75a745d2-89ce-4032-bd1f-9a6187860d41.png)

**Comment by casella** [comment]
@adeas31 I'm not sure vwaurich can help with that. @anotheruserofgithub could also consider fixing this.

**Comment by vwaurich** [comment]
I had a look on it and the colors are set correctly in the color assignment for the mesh. Not sure if something changed in OpenSceneGraph. I'm holding on.

**Comment by adeas31** [comment]
PR #10164 fix the problem reported in this issue so we can merge and close this. And you can continue the surface work for further improvements.

**Comment by vwaurich** [comment]
@anotheruserofgithub thanks for investigating the issue and fixing it. A remark on the uv-maps of tesselated shapes as in dxf and stl files: These file formats do not support uv-maps and there is no clear way to add them in a generic fashion. If you want to add textured CAD-geometry, I would go for the  .obj format. Btw. any idea why the stl file import is not working anymore?
