### ISSUE TITLE
Selected string choices in the parameter dialog change when the dialog is reopened

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10147]
### Description
String choices cannot be set correctly in some cases in OMEdit with the new instantiation-based UI. Please see also  #10145.  
String choices parameters that change a Boolean parameter depending on their selection in the parameter dialog are reset to their original value when the parameter dialog is opened again. 

### Steps to Reproduce
Load the package ```Rexroth_ElectricDrives/package.mo```
Drag and drop the component ```Rexroth_ElectricDrives.GenericRotationalDrive``` onto a new sheet.
Open the paramter dialog and select  this combination in the parameter dialog:

picture 1:

<img width="619" alt="StringChoiceProblem-changeSetting-1" src="https://user-images.githubusercontent.com/12269776/216570495-8f5894f9-3685-4fbe-9046-aa0fd3c0ef6c.png">

Changes to this setting when closing and reopening:
picture 2:
<img width="570" alt="StringChoiceProblem-changeSetting-2" src="https://user-images.githubusercontent.com/12269776/216570521-e70d8489-46b5-4b26-903f-c7842d2e29ba.png">

### Expected Behavior

The parameter settings should not change when reopening.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-215-gfbc4a47daf
 - OS:Windows 10, 64 bit
 -MSL 4.0.0
-BRSL 2.2.1

**Comment by adeas31** [comment]
This should work fine with #10187
