### ISSUE TITLE
Missing API call for ClassIsReplaceable

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10143]
### Description

There is no API call to find out if a class has a replaceable prefix. This is only possible via getModelInstance. However, in this case the result has to be parsed to get the information regarding the replaceable prefix. When calling `getClassInformation` information regarding final, partial, and encapsulated prefixes are displayed. There are also separate API calls like `isPartial` `isProtectedClass`. This is why I assume that it should be possible to either add the replaceable prefix to getClassInformation or t provide a new API call like `isReplaceable`. For components the `getComponentsTest` API call also delivers information about the replaceability of the component. 

### Expected Behavior
1. Create a class in the following manner:

```modelica
model TestClass

  replaceable model ParameterSet = ReplaceableModel annotation (Dialog(group="Configuration parameters"));

end TestClass;
```

2. There is now no API call to check if `TestClass.ParameterSet` is replaceable or not.

### Expected Behavior
Provide an API call with a boolean output indicating whether a class is replaceable or not.

### Version and OS

 - OpenModelica Version: OMEdit 1.21-dev
 - OS: Windows 10, 64 bit

Thanks for looking into it
Aaron Buntrock - Bosch rexroth

**Comment by perost** [comment]
It turns out that we actually already had a `isReplaceable` API call, but it wasn't documented and confusingly was used like `isReplaceable(Some.Class.Path, "ClassName")`. In #10661 I replaced it with a new call which just takes a single path as argument (`isReplaceable(Some.Class.Path.ClassName)`), and also works for both classes and components.

**Comment by abuntrock** [comment]
Thanks @perost. I will check this out with an upcoming nightly
