### ISSUE TITLE
error "Failed to autoconf OMSens_Qt" while building OMCompiler in WSL

### ISSUE THREAD

**Issue by albert-mathews** [OpenModelica/OpenModelica#10151]
### Description
I was following the instructions here: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README-Windows-WSL.md
when i hit the missing submodules error, i opened this PR https://github.com/OpenModelica/OpenModelica/pull/10150

then i got another error. 

### Steps to reproduce
just follow the instructions with fresh clone of repo, and submodules init&update. 
the next error i get is when running this: 

`./configure CC=clang CXX=clang++ --without-omc --with-cppruntime`

the error is:

`checking if cppruntime is requested... yes
checking for CORBA... none
configure.ac:260: warning: AC_LANG_PROGRAM(Fortran): ignoring PROLOGUE: []
../../lib/autoconf/lang.m4:224: AC_LANG_SOURCE is expanded from...
../../lib/autoconf/lang.m4:241: AC_LANG_PROGRAM is expanded from...
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2672: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2689: AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2698: AC_TRY_LINK is expanded from...
configure.ac:260: the top level
/usr/bin/m4:configure.ac:12: cannot open `common/m4/pre-commit.m4': No such file or directory
/usr/bin/m4:configure.ac:14: cannot open `common/m4/ombuilddir.m4': No such file or directory
/usr/bin/m4:configure.ac:15: cannot open `common/m4/ax_cxx_compile_stdcxx_11.m4': No such file or directory
/usr/bin/m4:configure.ac:30: cannot open `common/m4/qmake.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
configure: error: "Failed to autoconf OMSens_Qt"
albert@MSI:~/git/OpenModelica$`

### Expected behavior
no error

### Screenshots
![image](https://user-images.githubusercontent.com/80334291/216644648-947d4385-2dda-4beb-824c-2e684d89d18e.png)

### Version and OS
 - OS: Windows 10, 64 bit, WSL
not sure if this helps:
`albert@MSI:~$ echo deb http://build.openmodelica.org/apt `lsb_release --short --codename` nightly | sudo tee -a /etc/apt/sources.list.d/openmodelica.list
[sudo] password for albert:
deb http://build.openmodelica.org/apt focal nightly
albert@MSI:~$ echo deb-src http://build.openmodelica.org/apt nightly contrib | sudo tee -a /etc/apt/sources.list.d/openmodelica.list
deb-src http://build.openmodelica.org/apt nightly contrib
albert@MSI:~$ wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
OK`

### Additional context
none

**Comment by albert-mathews** [comment]
I checked my autoconf installation and doesn't look like that's the problem.
```
albert@MSI:~/git/OpenModelica$ sudo apt-get install autoconf
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-11.1).
0 upgraded, 0 newly installed, 0 to remove and 155 not upgraded.
```

**Comment by albert-mathews** [comment]
Hello @AnHeuermann , thanks for the help. 

the main [Readme](https://github.com/OpenModelica/OpenModelica#working-with-the-repository) seems to be only about git repo. anyway, i did all the steps there to clean/pull/update/etc. 

Then I went to [README.Linux.md](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md) and followed [these instructions](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md#debianubuntu-compile-cheat-sheet-or-read-on-for-the-full-guide), so NOT the "all from source" . however, it's not clear whether this is building all of OpenModelica, or only the OMCompiler. For one, the README is in the OpenModelica/OMCompiler directory, but all references to building "something" in the README.Linux.md "something" is "OpenModelica" and not "OMCompiler".
Further, there are some hints about "omc" like "only compile the base omc executable" or "./configure --with-cppruntime --without-omc", but it's just a guess this is related to OMCompiler. 

I only want to build OMCompiler, in case I wasn't clear about that. 

the lines below are the end of the process. does this mean the build was successful?
`make[3]: Leaving directory '/home/albert/git/OpenModelica/OMEdit/OMEditGUI'
make[2]: Leaving directory '/home/albert/git/OpenModelica/OMEdit'
cp -p ./OMEditLIB/Resources/nls//*.qm /home/albert/git/OpenModelica/build/share/omedit/nls/
if [ "" = ".app" ]; then mkdir -p /home/albert/git/OpenModelica/build/Applications/ ; cp -rp bin/OMEdit /home/albert/git/OpenModelica/build/Applications/ ; else cp -p bin/OMEdit /home/albert/git/OpenModelica/build/bin/; fi
make[1]: Leaving directory '/home/albert/git/OpenModelica/OMEdit'`

thanks again for help.

**Comment by AnHeuermann** [comment]
> after that, for fun i tried make test -j4, and it looks like a bunch of tests are running. e.g. i see this:
Running all  tests
cd testsuite/partest && ./runtests.pl -with-txt
Could not load MLDBM module, falling back to nodb mode.
12 threads
[DewPointTemperatureDerivativeCheck_amb.mo:1] [EnzMM.mos:10] [valve_test.mos:13] ...

If you see mostly green tests that indicates you have a working omc.
To pass all tests you need to build additional stuff, but it's probably not important for you.

>albert@MSI:~/git/OpenModelica/build/bin$ ./omc RLC.mo

There is no direct command line interface for `omc`. You can however use MOS scripts together with the [scripting api](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html).

So you would usually do something like this:
Create a file `test.mos`

```
loadFile("RLC.mo"); getErrorString();
simulate(RLC); getErrorString();
```

```bash
$ omc test.mos
```

Alternatively you can use OMPython / OMJulia to interact with the compiler from Python / Julia language.
And finally OMEdit is just a graphical way to interact with the compiler, which is doing API calls in the background for you.

Hope this helps.

**Comment by AnHeuermann** [comment]
Hey @albert-mathews. We are leaving the scope of the original issue here. You can open a new [question in our discussion](https://github.com/OpenModelica/OpenModelica/discussions/new?category=q-a) section for this and you may want to read the manual: [OpenModelica User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.20/introduction.html#system-overview)

**Comment by albert-mathews** [comment]
yeah good idea. https://github.com/OpenModelica/OpenModelica/discussions/10185

should we leave this issue open until the readme's are updated? I opened a [PR](https://github.com/OpenModelica/OpenModelica/pull/10150#issuecomment-1416025502) to update the WSL readme, obviously, that can be closed ight?

**Comment by AnHeuermann** [comment]
By the way it could be easier for you to build OpenModelica using CMake, see [README.cmake.md](https://github.com/OpenModelica/OpenModelica/blob/master/README.cmake.md).

That's what I'm usually doing on both WSL and native Linux (and Windows as well).

**Comment by albert-mathews** [comment]
hmm, thanks, why doesn't the README for Linux recommend the CMake process? oh, looks like you've suggested that here https://github.com/OpenModelica/OpenModelica/pull/10150. thanks

**Comment by AnHeuermann** [comment]
I'll remove the WSL Readme. The Linux Readme has the informations relevant for WSL.

I guess in the end the problem for this issue was some missing `--recursive` in the original git clone or something similar.
