### ISSUE TITLE
[OMEdit] Collection of issues with CAD files

### ISSUE THREAD

**Issue by anotheruserofgithub** [OpenModelica/OpenModelica#10165]
- [x] Loading CAD files:
  - https://github.com/OpenModelica/OpenModelica/issues/5440
  - https://github.com/OpenModelica/OpenModelica/discussions/9373
  - https://github.com/OpenModelica/OpenModelica/discussions/9547
  - https://github.com/OpenModelica/OpenModelica/issues/9503
  - https://github.com/OpenModelica/OpenModelica/pull/9649
  - https://github.com/OpenModelica/OpenModelicaSetup/pull/34
  - https://github.com/OpenModelica/OpenModelica/pull/10296
  - https://github.com/OpenModelica/OpenModelica/issues/11067
  - https://github.com/OpenModelica/OpenModelica/pull/11073
  - https://github.com/OpenModelica/OpenModelica/discussions/14617
  - https://github.com/OpenModelica/OpenModelica/issues/14637
  - https://github.com/OpenModelica/OpenModelica/pull/14634

- [x] Broken picker of STL shapes:
  - https://github.com/OpenModelica/OpenModelica/pull/10163

- [x] Broken colors of DXF shapes:
  - https://github.com/OpenModelica/OpenModelica/issues/10144
  - https://github.com/OpenModelica/OpenModelica/pull/10164

- [x] Wrong naming of CAD shapes:
  - https://github.com/OpenModelica/OpenModelica/pull/10183

- [x] Wrong scaling of CAD shapes:
  - https://github.com/OpenModelica/OpenModelica/issues/5593
  - https://github.com/OpenModelica/OpenModelica/pull/10204

- [x] Further improvements for CAD shapes:
  - https://github.com/OpenModelica/OpenModelica/pull/10331
  - https://github.com/OpenModelica/OpenModelica/pull/10359
  - https://github.com/OpenModelica/OpenModelica/pull/10360
  - https://github.com/OpenModelica/OpenModelica/pull/10377

**Comment by rehlm-gse** [comment]
I can confirm that I am still having issues loading STL/DXF files when using `modelica://` referenced paths similar to #9503 when running OpenModelica v1.22.0-dev-263-gfae4e4871e (64-bit) on Windows 10. 

I have tested this by trying to run the Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot model with animation. When doing so, I get the following error type for all 7 CAD shapes that are in the model:

[1] 10:13:58 Scripting Error
Could not find the file .

[8] 16:01:50 Error
Failed to lookup URI (is the package loaded?) modelica://C:/development/.openmodelica/libraries/Modelica 4.0.0+maint.om/Resources/Data/Shapes/RobotR3/b0.dxf

In the Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.Utilities.MechanicalStructure submodel that is referenced by the FullRobot example, the custom shapeType for the above file is specified as follows:

```
Modelica.Mechanics.MultiBody.Parts.BodyShape b0(
    r={0,0.351,0},
    shapeType="modelica://Modelica/Resources/Data/Shapes/RobotR3/b0.dxf",
    r_shape={0,0,0},
    lengthDirection={1,0,0},
    widthDirection={0,1,0},
    length=0.225,
    width=0.3,
    height=0.3,
    color={0,0,255},
    animation=animation,
    animateSphere=false,
    r_CM={0,0,0},
    m=1)
```

It looks like this gets correctly translated to an absolute file path and stored in the FullRobot_visual.xml file except for the fact that the `modelica://` part doesn't get converted to `file://`:
```
<shape>
      <ident>mechanics.b0.shape1</ident>
      <type>modelica://C:/development/modelica/RobotR3/Resources/Data/Shapes/RobotR3/b0.dxf</type>
      <T>
...
</shape>
```
 When the xml file is parsed by Visualization.cpp it sees the `modelica://` in the absolute file path and tries to convert it again which is when the error gets raised.
