### ISSUE TITLE
Warnings regarding Classes including outer definition

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10161]
### Description

When opening a class (e.g from Modelica.Mechanics.MultiBody.Forces.WorldTorque) that includes an outer component, one gets two warnings and one notification for basically the same thing: The missing inner declaration (with the new API). These warnings are in essence correct. However, one Notification including the diagnostic message defined in the outer element in the GUI log should be enough. This is especially true when you open a package where every class has an outer declaration. Then you get a lot of log elements from the missing inner declaration and might miss an important non outer related message. The three messages even appear when you create a new class, instantiate the needed inner declaration first and then the class with the outer component.

### Steps to Reproduce

1. Open the package Modelica.Mechanics.MultiBody.Forces from the library browser. You get 18 messages in the GUI log (12 warnings and 6 notifications) regarding the missing inner Modelica.Mechanics.MultiBody.World. When clicking on any of the 12 classes inside this package the three messages appear again since every class has an outer multibody world. This would suggest that there should be 36 log messages when opening the package in the first place (12 classes*3 messages).

2. Create a new modelica class. Instantiate the multibody world Modelica.Mechanics.MultiBody.World. Then instantiate a component with an outer multibody world component, e.g. Modelica.Mechanics.MultiBody.Forces.WorldForce. The two warnings and the notification with the missing inner message appear in the GUI log.

### Expected Behavior

Regarding number 1. in section above: Our ideal behavior would be that a message regarding the missing inner declaration only appears when checking a class since the classes are intentionally designed without an inner declaration. At least, the two warnings and one notification should be summarized into one GUI message.

Regarding number 2. from section above: Those warnings are wrong in our opinion since the needed inner declaration already exists when instantiating a class after the multibody world. 

### Version and OS

 - OpenModelica Version: 1.21-dev new API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

## Additional information
This issue is important for our rexroth BRSL development because there every class has an outer world declaration. As a result, the user gets flooded with warnings in the GUI log when browsing the library and opening classes even if all those classes are designed according to Modelica specification.

Thanks for looking into it.
Aaron Buntrock- Bosch rexroth

**Comment by perost** [comment]
> @perost The warnings when opening a package do not appear anymore with todays nightly (v1.21.0-dev-253-g9bf056631b). Was this intended?

Yes, we had some error messages enabled to debug some other BRSL issues but disabled them again once that was fixed. The user doesn't need to know that a class requires an inner world declaration when just browsing the library, they're only useful when actually using the class.

**Comment by casella** [comment]
I guess this fixes the issue then. Please reopen if there is anything left to do.

**Comment by abuntrock** [comment]
@casella Could you reopen this please. There are no warnings when opening packages anymore, which is really great. However, there are still warnings when I instantiate a component from the BRSL after instantiating the needed inner defintion world. The warning regarding the missing inner world declaration should however only appear when I instantiate the outer before the inner declaration.

**Comment by casella** [comment]
This is weird, but I guess it may be an OMEdit issue. Does this happen with `NAPI = true`?

**Comment by abuntrock** [comment]
Yes it only happens when NAPI = true.

**Comment by adeas31** [comment]
> 1. Open the package Modelica.Mechanics.MultiBody.Forces from the library browser. You get 18 messages in the GUI log (12 warnings and 6 notifications) regarding the missing inner Modelica.Mechanics.MultiBody.World. When clicking on any of the 12 classes inside this package the three messages appear again since every class has an outer multibody world. This would suggest that there should be 36 log messages when opening the package in the first place (12 classes*3 messages).

Browsing the library browser doesn't produce any such error message now as mentioned by @per in https://github.com/OpenModelica/OpenModelica/issues/10161#issuecomment-1429538283.

However, opening `Modelica.Mechanics.MultiBody.Forces.WorldTorque` still produces 2 warnings and 1 notification.

> 2. Create a new modelica class. Instantiate the multibody world Modelica.Mechanics.MultiBody.World. Then instantiate a component with an outer multibody world component, e.g. Modelica.Mechanics.MultiBody.Forces.WorldForce. The two warnings and the notification with the missing inner message appear in the GUI log.

This is not valid now. I don't get any messages when I created a new model and dragged components `Modelica.Mechanics.MultiBody.World` and `Modelica.Mechanics.MultiBody.Forces.WorldForce`.

**Comment by abuntrock** [comment]
@adeas31 Same for me. When dragging the world before the worldforce onto the diagram (also tested in our BRSL context), nothing appears in the GUI log as expected. 
For the other way around (worldforce before) world something needs to be printed to the GUI log. Our wish would be that this would only be one message (since there is only one root cause). However, this is not of high priority to us, since the user should can just start the modeling with the world to avoid those notifications/warnings.

**Comment by casella** [comment]
> However, this is not of high priority to us, since the user can just start the modeling with the world to avoid those notifications/warnings.

OK. I'll keep the ticket open but remove it from the DFD list.

**Comment by abuntrock** [comment]
That sounds reasonable. The main pain points are definitely solved

**Comment by abuntrock** [comment]
@perost I checked this issue again with today's nightly and one sub-point, which was solved previously (maybe only with the old API), now appears again: When **double-clicking on a class** with an outer definition (any class from BRSL or from `Modelica.Mechanics.MultiBody`) in the library tree, two warnings and one notification (as written above for the same root cause) are printed to the log. From our point of view this is not helpful in this case, since I the class is only opened and not used. And only for the usage, the inner definition is needed. This behavior fills up the log when the user is just browsing the library and opening classes to get more information. This probably happens because `getModelInstance` is called when double-clicking a class as well as when instantiating it.

To clarify our desired behavior: We only expect a warning/notification (one and not three if possible) during the following two scenarios. During these scenarios the OMEdit already behaves as expected, but as written above the warning appears in other circumstances as well.
1. Checking a class with an outer defintion. 
2. Instantiating a class with an outer definition when the inner class was not instantiated beforehand.

**Comment by casella** [comment]
> You won't get the warnings when adding a component with an outer definition to a class that doesn't have a corresponding inner though, but I think we need a better solution for that anyway since just printing errors doesn't let OMEdit know where the issue is. Ideally I think OMEdit should instead ask the user if they want to add the appropriate inner in that case, but that will require some work to implement.

I don't think we should bother users while they are _building_ a model by dragging components in it. One may legitimately add the inner component at the end of the process, instead of at the beginning. This makes perfect sense, the GUI normally doesn't need any information from the inner object, and if it did (e.g. because there are default parameters that influence conditional connectors) it can use the default inner declaration.

Only when you check or compile you should get a warning that you should not really rely on the default inner, but rather drag it in explicitly.

So, as I understand, #10817 should solve this issue for good, and probably many other as well.

**Comment by abuntrock** [comment]
It looks really good with today's nightly. Thanks a lot. From our side this ticket can be closed then.
