### ISSUE TITLE
Jacobian evaluation at runtime scales badly

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10178]
Consider the ScalableTestSuite.Elementary.SimpleODE.ScaledExperiments.CascadedFirstOrder_N_XXX models. They contain a cascaded connection of first-order linear low-pass systems, so the Jacobian is bi-diagonal, with O(N) non-zero elements.

If you compare the runtime performance of [CascadedFirstOrder_N_12800](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/files/ScalableTestSuite_NB_ScalableTestSuite.Elementary.SimpleODE.ScaledExperiments.CascadedFirstOrder_N_12800.sim) and [CascadedFirstOrder_N_25600](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/files/ScalableTestSuite_NB_ScalableTestSuite.Elementary.SimpleODE.ScaledExperiments.CascadedFirstOrder_N_25600.sim), the computation time of the ODE Jacobian (for just one Jacobian computation) roughly increases fourfold. Given that the number of NZ elements is O(N), it should just grow twofold.

The situation doesn't change with old vs. new backend, nor with numerical vs. symbolic jacobian.

The Jacobian should have only 2 colours, one for the odd states and one for the even states. Preliminary analysis by @phannebohm shows that this is indeed the case. So, the computation time should really scale as O(N), not O(N^2). Besides, the Jacobian is constant, so it should really be just computed once, but that is another story 😅 

Apparently, there is something inefficient in how the sparse jacobian is traversed, or something. This probably is particularly bad since the computation of the individual elments is totally trivial.

**Comment by casella** [comment]
This issue is ubiquitous, and not only limited to CascadedFirstOrder. For example [OneDHeatTransferTT_FD_N_20480](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/files/LargeTestSuite_NB_LargeTestSuite.Thermal.HeatConduction.OneDHeatTransferTT_FD_N_20480.sim) takes 10 seconds computing 36 jacobians, while [OneDHeatTransferTT_FD_N_40960](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/files/LargeTestSuite_NB_LargeTestSuite.Thermal.HeatConduction.OneDHeatTransferTT_FD_N_40960.sim) takes 42 seconds for 37 jacobians.

**Comment by phannebohm** [comment]
For the sparse jacobian the bottleneck appears to be this line
https://github.com/OpenModelica/OpenModelica/blob/b2954cbc749575ba8cfe5a1dd880cacdca17565e/OMCompiler/SimulationRuntime/c/simulation/solver/ida_solver.c#L1840

I'm not sure why adding two sparse matrices scales so badly, unless of course they are not both sparse.
In any case the purpose of `idaData>tmpJac` seems to be to subtract `cJ` times the identity matrix, which we should probably do in the numerical/symbolical functions directly. @AnHeuermann what do you think?

**Comment by AnHeuermann** [comment]
We need to double check that we use the correct sparse (or actually banded in this case) version of SUNMATRIX.
If that isn't the problem we should update SUNDIALS and if that is still not solves the issue open an issue upstream.

Also tOr maybe a different Matrix operation is better suited in this case.

In addition SUNDIALS provide a lot of different APIs for parallelization. So we could use pThreads or OpenMP to improve matrix operations further.

**Comment by kabdelhak** [comment]
@phannebohm and I looked into the function and it just scales badly because it is the most general form of sparse matrix addition. It checks first if the sparsity patterns match (which already scales N^2) and then it creates a new matrix with the combined sparsity pattern (which again scales N^2).

Since we know that the matrix we are adding is a diagonal matrix, there should be a way to do it with O(N). 
1. create new (sparse matrix) array with size(matrix) + N
2. Traverse the sparse matrix once, identify the diagonal elements and sub tract lambda
3. Track if we skipped a place where a diagonal element should have been. Missing diagonal elements should just be -lambda (maybe tricky for last element)
4. truncate (sparse matrix) array to correct size

We were not quite sure if we need to update meta information for this to work but this should be the general plan.

Ultimately we should try to get this function as A+lambda*I in sundials but it will sit in our c runtime for now.

**Comment by casella** [comment]
OK, LGTM.

Maybe you could open a ticket for SUNDIALS and point out this problem, but I guess normally people use IDA as a proper DAE solver, not as an ODE solver, so that's not needed, right?

**Comment by casella** [comment]
Great! I'll start a LargeTestSuite_NB job right away to test it.

**Comment by casella** [comment]
@phannebohm, this looks good now, [CascadedFirstOrder_N_12800](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Elementary.SimpleODE.ScaledExperiments.CascadedFirstOrder_N_12800.sim) takes 0.03 s computing Jacobians, while [CascadedFirstOrder_N_25600](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Elementary.SimpleODE.ScaledExperiments.CascadedFirstOrder_N_25600.sim); since there are twice as many NZ elements in the Jacobian in the second case, and also 50% more Jacobian evaluations, this seems to scale correctly.

The [LargeTestSuite_NB](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html) `CascadedFirstOrder` models still scale badly at runtime, but that's because I switched to dopri45, which is not good because of increasing stiffness of the system with increasing size. I'll switch back to ida there as well, so we can see what happens with 1M+ equations systems.

**Comment by casella** [comment]
I have a new round of results for [LargeTestSuite_NB](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html). HeatExchanger models confirm that the Jacobian evaluation is scaling as expected, we can manage models up to 320.000 equations, and we'll get to 640.000 at the next iteration by allowing for a bit more simulation run time.

Also CascadedFirstOrder models are scaling fine on this front. The overall simulation time still scales badly, but that's because the model is fed by a sharp step change, so the number of steps also increases with the models size, to simulate the initial very fast transient with the required accuracy. I'll try to use a filtered input so we can go up more with the size without incurring in this problem.

Problem solved 👍
