### ISSUE TITLE
Instances of deleted classes are not marked in the new API

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10172]
### Description
Instances of deleted classes are not marked with a red X in the diagram layer anymore like in the old API

### Steps to Reproduce

1. Open the following package and look at the diagram layer of the class `DeletedClassMarking.ClassWithInstance`: 
[DeletedClassMarking.txt](https://github.com/OpenModelica/OpenModelica/files/10675205/DeletedClassMarking.txt)
2. Delete/unload the class `DeletedClassMarking.ClassToDelete` in the library browser.
3. Open the diagram layer of the class `DeletedClassMarking.ClassWithInstance` again. With the new API it looks exactly like before deleting in step 2. With the old API the icon of the `DeletedClassMarking.ClassToDelete` instance is marked with a red X.

### Expected Behavior

Instances of deleted classes are still marked with a red cross in the diagram layer with the new API.

### Version and OS

 - OpenModelica Version: 1.21-dev
 - OS: Windows 10, 64 bit

Thanks for looking into it.
Aaron Buntrock - Bosch rexroth

**Comment by adeas31** [comment]
See also #9673

**Comment by casella** [comment]
This should now work with the new instance-based API, see, e.g., this simple test case: [P.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11139282/P.mo.txt).

@abuntrock please double-check with your cases of interest and reopen if something's still wrong.
