### ISSUE TITLE
A very minimal correction: just to avoid a mouse movement and click 

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10194]
### Description
When one checks a model a window appears with the check result. The window contains an "OK" button, which  is not pre-selected. Therefore, to close the window, one has to go with the mouse point on the button and click.

A very tiny, but significant, improvement, is to have the OK button pre-selected , so that the user can avoid to abandon the keyboard and close the window hitting the enter button

### Version and OS
OM 1.20.0

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
See #10100. There is a suggestion about not showing the window for check model result but instead show the output in the Messages Browser.

I will still keep this issue open. We can add this improvement to instantiate model window.

**Comment by adeas31** [comment]
We use the same window for check and instantiate model so PR #10203 fixes this issue.

FYI, you can also close the window by pressing the `Esc` key.

**Comment by ceraolo** [comment]
> We use the same window for check and instantiate model so PR #10203 fixes this issue.
> 
> FYI, you can also close the window by pressing the `Esc` key.

Aha, I didn't know. Thanks
