### ISSUE TITLE
setElementModifierValue fails to set the modifier value

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#10190]
### Description

`setElementModifierValue` sets the modifier correctly first time but fails to set it the second time. Infact it actually removes the modifier that was set before.

### Steps to Reproduce

Run the following script,

```
loadString("within ;
package TestOMEdit
  model ClasswithReplaceable

    replaceable TestOMEdit.Internal.ClassA testClass annotation(choices(
      choice(redeclare TestOMEdit.Internal.ClassA testClass \"A\"),
      choice(redeclare TestOMEdit.Internal.ClassB testClass \"B\")));
    replaceable parameter TestOMEdit.Internal.recordA testrecrod;

    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end ClasswithReplaceable;

  package Internal
    model ClassA
      parameter Real A = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end ClassA;

    model ClassB
      parameter Real B = 2;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end ClassB;

    record recordA
      parameter Real a = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end recordA;

    record recordB
      parameter Real B = 1;
      annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
            coordinateSystem(preserveAspectRatio=false)));
    end recordB;
  end Internal;
end TestOMEdit;

model M
  TestOMEdit.ClasswithReplaceable classwithReplaceable annotation(
    Placement(visible = true, transformation(origin = {-56, 24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
end M;");
getErrorString();
getClassNames();
getErrorString();

setElementModifierValue(M, classwithReplaceable.testClass, $Code((redeclare TestOMEdit.Internal.ClassB testClass "A")));
getErrorString();
list(M);
getErrorString();

setElementModifierValue(M, classwithReplaceable.testClass, $Code((redeclare TestOMEdit.Internal.ClassB testClass "B")));
getErrorString();
list(M);
getErrorString();
```

Outputs,

```
true
""
{TestOMEdit,M}
""
Ok
""
"model M
  TestOMEdit.ClasswithReplaceable classwithReplaceable(redeclare TestOMEdit.Internal.ClassB testClass \"A\") annotation(
    Placement(visible = true, transformation(origin = {-56, 24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
end M;"
""
Ok
""
"model M
  TestOMEdit.ClasswithReplaceable classwithReplaceable annotation(
    Placement(visible = true, transformation(origin = {-56, 24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
end M;"
""
```

Note that modifier is set properly with the first call of `setElementModifierValue` but is removed after the second call `setElementModifierValue`.

### Expected Behavior

`setElementModifierValue` should set the element modifier value correctly.

**Comment by perost** [comment]
#10196 fixes the issue, previously we just threw the modifier away if the old one was a redeclare. I don't think the solution is complete though, but since there's no documentation on how `setElementModifierValue` should work I don't really know what it needs to handle. But just replacing a redeclare with another modifier should at least work now.

**Comment by casella** [comment]
> since there's no documentation on how `setElementModifierValue` should work

@adeas31 can you elaborate on that?

**Comment by adeas31** [comment]
> > since there's no documentation on how `setElementModifierValue` should work
> 
> @adeas31 can you elaborate on that?

As the name suggests it should set the modifier on the element. I don't know the details. The API is added by @adrpo https://github.com/OpenModelica/OpenModelica/commit/99a56f35fd0

The changes done by @perost works for me so I think its good for now.

**Comment by casella** [comment]
> > > since there's no documentation on how `setElementModifierValue` should work
> > 
> > 
> > @adeas31 can you elaborate on that?
> 
> As the name suggests it should set the modifier on the element. I don't know the details. The API is added by @adrpo [99a56f35fd0](https://github.com/OpenModelica/OpenModelica/commit/99a56f35fd0)

I checked https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html but I didn't find it there. Aren't we reporting all API functions there? @adrpo maybe you can add a minimum of documentation to it?

**Comment by adeas31** [comment]
A lot of API's are not documented since they are part of `Interactive.mo`. Only the once listed in `ModelicaBuiltin.mo` are documented automatically.

**Comment by casella** [comment]
Is there any reason not to also document functions in `Interactive.mo`? If not, I would definitely add them to the API manual.
