### ISSUE TITLE
Protected variables are written to the simulation results file

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10206]
### Description
In the simulation result file also protected variables are written, this makes the mat file for some models of our BRSL library very large. e.g. 2.5GB in comparison with other tools it would be only 50MB. We want to use the file for another purpose afterwards the simulation. Unfortunately, this is not possible with very large mat files then.  Together with #9203 the file becomes even larger.
We assume that this also makes the simulation slower in such a case. 

### Steps to Reproduce

Load this model in OMEdit.
```modelica
package ResultsOutputTest
  model ResultsOutputTopModel
  protected 
    Real a(start=0.0);
    ResultsOutputSubModel resultsOutputSubModel
      annotation (Placement(transformation(extent={{-60,-10},{-40,10}})));
  equation 
    a=1.0;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end ResultsOutputTopModel;

  model ResultsOutputSubModel

            Real b(start=0.0);
    ResultsOutputSubSubModel resultsOutputSubSubModel
      annotation (Placement(transformation(extent={{-18,4},{2,24}})));
  equation 
    b=2.0;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end ResultsOutputSubModel;

  model ResultsOutputSubSubModel

            Real c(start=0.0);
  equation 
    c=3.0;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end ResultsOutputSubSubModel;
end ResultsOutputTest;
```
Conver the mat file to csv with this command:

```
filterSimulationResults("ResultsOutputTopModel_res.mat", "ResultsOutputTopModel_res.csv", readSimulationResultVars("ResultsOutputTopModel_res.mat"))

```
The csv file include all variables 
```
time,"a","resultsOutputSubModel.b","resultsOutputSubModel.resultsOutputSubSubModel.c","time",nrows=502
0,1,2,3,0
0.002,1,2,3,0.002
0.004,1,2,3,0.004
...
```
### Expected Behavior

The csv file shoud be empty
### Version and OS

 - OpenModelica Version: v1.21.0-dev-253-g9bf056631b
 - OS: Windows 10, 64 bit
 - MSL 4.0.0
 - ### Additional Context

**Comment by casella** [comment]
However, this MWE works as expected:
```
model TestProtected
  Real x = sin(10*time);
protected 
  Real y = 2*x;
end TestProtected;
```
I guess there is still some problem with protected _components_ which are not simple variables but rather model instances. @perost, what do you think?

**Comment by perost** [comment]
> I guess there is still some problem with protected _components_ which are not simple variables but rather model instances. @perost, what do you think?

I don't really know how the backend and/or simulation runtime selects which variables to write, but they're all protected in the flat model at least.

**Comment by niklwors** [comment]
@casella  In your example, all variables are also included in the mat file. In the OMEdit plot browser y is  not visible but in the mat file the protected variable y is also included.  Here is a snippet of the generated csv file from the mat file TestProtected_res.mat:
```
time,"time","x","y",nrows=502
0,0,0,0
0.002,0.002,0.0199986666933331,0.0399973333866662
0.004,0.004,0.0399893341866342,0.0799786683732683
0.006,0.006,0.0599640064794446,0.119928012958889
```

**Comment by adrpo** [comment]
This is from `simulation_input_xml.c`:

```C
  if (!omc_flag[FLAG_EMIT_PROTECTED] && 0 == strcmp(findHashStringString(v, "isProtected"), "true") && 0 == strcmp(findHashStringString(v, "hideResult"), "true")) \
    { \
      infoStreamPrint(LOG_DEBUG, 0, "filtering protected variable %s", info->name); \
      out[j].filterOutput = 1; \
    } \
```

and for alias variables:

```C
   if (!omc_flag[FLAG_EMIT_PROTECTED] && 0 == strcmp(findHashStringString(*findHashLongVar(mi.rAli,i), "isProtected"), "true") && 0 == strcmp(findHashStringString(*findHashLongVar(mi.rAli,i), "hideResult"), "true"))
    {
      infoStreamPrint(LOG_DEBUG, 0, "filtering protected variable %s", modelData->realAlias[i].info.name);
      modelData->realAlias[i].filterOutput = 1;
    }
```

This seems wrong. It will filter protected variables only if `isProtected = true` in the Model_init.xml **and** it has annotation `hideResult=true`.

**Comment by adrpo** [comment]
I would probably change:

```C
if (!omc_flag[FLAG_EMIT_PROTECTED] && 
    0 == strcmp(findHashStringString(v, "isProtected"), "true") && 
    0 == strcmp(findHashStringString(v, "hideResult"), "true")) 
```
to:

```C
if (!omc_flag[FLAG_EMIT_PROTECTED] && 
    (0 == strcmp(findHashStringString(v, "isProtected"), "true") || 0 == strcmp(findHashStringString(v, "hideResult"), "true")))
```

So if either `isProtected=true`  **or** `hideResult=true` or **both**. 
Should I do that?

**Comment by adrpo** [comment]
Nah, it seems more complicated than this :)
We need to somehow merge these two cases as otherwise we would ignore `FLAG_IGNORE_HIDERESULT`:
```C
    if (!omc_flag[FLAG_EMIT_PROTECTED] && 0 == strcmp(findHashStringString(v, "isProtected"), "true") && 0 == strcmp(findHashStringString(v, "hideResult"), "true")) \
    { \
      infoStreamPrint(LOG_DEBUG, 0, "filtering protected variable %s", info->name); \
      out[j].filterOutput = 1; \
    } \
    else if (!omc_flag[FLAG_IGNORE_HIDERESULT] && 0 == strcmp(findHashStringString(v, "hideResult"), "true") && 0 == strcmp(findHashStringString(v, "isProtected"), "false")) \
    { \
      infoStreamPrint(LOG_DEBUG, 0, "filtering variable %s due to HideResult annotation", info->name); \
      out[j].filterOutput = 1; \
    }
```

I will play with this and make a PR.

**Comment by adrpo** [comment]
Ok, I changed the check to be like this, in phases so we can display what is going on so the user understand the filtering:
- we filter if isProtected
- we filter if HideResult=true
- we emit (remove filtering) if emitProtected && isProtected
- we emit (remove filtering) if ignoreHideResult && HideResult=true

```C
#define setFilterOuput(v, s, n) \
{ \
  int ep = omc_flag[FLAG_EMIT_PROTECTED]; \
  int ihr = omc_flag[FLAG_IGNORE_HIDERESULT]; \
  char *ipstr = findHashStringString((v), "isProtected"); \
  char *hrstr = findHashStringString((v), "hideResult"); \
  int ipcmptrue = (0 == strcmp(ipstr, "true")); \
  int hrcmptrue = (0 == strcmp(hpstr, "true")); \
  if (ipcmptrue) \
  { \
    infoStreamPrint(LOG_DEBUG, 0, "filtering protected variable %s", (n)); \
    (s).filterOutput = 1; \
  } \
  if (hrcmptrue) \
  { \
    infoStreamPrint(LOG_DEBUG, 0, "filtering variable %s due to HideResult annotation", (n)); \
    (s).filterOutput = 1; \
  } \
  if (ep && ipcmptrue) \
  { \
    infoStreamPrint(LOG_DEBUG, 0, "emitting protected variable %s due to flag %s", (n), omc_flagValue[FLAG_EMIT_PROTECTED]); \
    (s).filterOutput = 0; \
  } \
  if (ihr && hrcmptrue) \
  { \
    infoStreamPrint(LOG_DEBUG, 0, "emitting variable %s with HideResult=true annotation due to flag %s", (n), omc_flagValue[FLAG_IGNORE_HIDERESULT]); \
    (s).filterOutput = 0; \
  } \
}
```

I will make a PR with this.

**Comment by adrpo** [comment]
Should be fixed by PR #10571.

**Comment by casella** [comment]
Thanks @adrpo, I'll check it tomorrow on the nightly build. @niklwors you can check it too.

**Comment by casella** [comment]
When PR #10206 is merged, that is 😅

**Comment by niklwors** [comment]
With the version of today, unfortunately, nothing has changed yet. For example, for the model ```Rexroth_BRSL_Test.Rexroth_Pumps_Test.AxialPistonUnits.CCUnitsWithCtrlAndBC.A4VG_EP_CCTest_TC01``` the mat file is 600MB, the same size as before. With Dymola it is 30MB.

**Comment by casella** [comment]
> With the version of today, unfortunately, nothing has changed yet. For example, for the model `Rexroth_BRSL_Test.Rexroth_Pumps_Test.AxialPistonUnits.CCUnitsWithCtrlAndBC.A4VG_EP_CCTest_TC01` the mat file is 600MB, the same size as before. With Dymola it is 30MB.

As you can see, PR #10206 is still open, so not in the master branch.

**Comment by adrpo** [comment]
This seems to be more problematic than I realized. I need to open additional tickets.

**Comment by adrpo** [comment]
See: #10578. Even with my filtering the protected elements are not marked as such when building with NF.

**Comment by adrpo** [comment]
Fixed via #10571.

**Comment by casella** [comment]
@niklwors please check with tomorrow's nightly and report.

**Comment by niklwors** [comment]
Thank you very much, it is working now
