### ISSUE TITLE
Dropdown of enumeration parameters

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10211]
### Description

Consider a class with an enumeration parameter. When instantiating this class and opening its parameter dialog the enumeration parameter can be selected via a dropdown menu. However, this dropdown menu displays the names of the different enumeration types and not the corresponding description strings (comments). This happens with the old and new API.

### Steps to Reproduce

1. Create the following package
```modelica
model EnumPackage
  model ModelWithEnum
  
  parameter EnumPackage.EnumClass enumParam = EnumPackage.EnumClass.FirstChoice "Enum parameter";

  end ModelWithEnum;

  type EnumClass = enumeration(
      FirstChoice
      "Description of first choice",
      SecondChoice
       "Description of second choice") "This is an enumeration";

end EnumPackage;
```
2. Create a new modelica class and instantiate `EnumPackage.ModelWithEnum`.
3. Open the parameter dialog of the created instance and open the dropdown menu of parameter `enumParam`.
4. The dropdown menu includes the two entries _FirstChoice_ and _SecondChoice_ instead of the expected _Description of first choice_ and _Description of second choice_ respectively.

### Expected Behavior

The enumeration comments and not the enumeration names are displayed in the dropdown menu.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-253-g9bf056631b (64-bit) (old and new API)
 - OS: Windows 10, 64 bit

Thanks for looking into it.
Aaron Buntrock - Bosch rexroth

**Comment by adeas31** [comment]
> The dropdown menu includes the two entries FirstChoice and SecondChoice instead of the expected Description of first choice and Description of second choice respectively.

I don't agree that display of description is expected. Is it written somewhere in the specification?

We show the description as tooltip of the item. So if you hold the mouse over `FirstChoice` you will see `Description of first choice` in the tooltip.

**Comment by abuntrock** [comment]
I could not find it in the specification. So my expectation just come from the look in Dymola and SimulationX. However, in our view the description string is more informative in many cases since you are not limited by the Modelica naming conventions. For example: We have an enumeration that describes different output ranges, where the description string is `[4 mA, 20 mA]` and the name is `Ampere420`. 
Nevertheless, the issue is not of outmost importance to us and the tooltip significantly limits the problem. So if you do not see the benefit of displaying the description string first, you can close this issue.

**Comment by adeas31** [comment]
We should definitely try to improve user experience. What I saw in Dymola is actually confusing for me. It shows the descriptions in the drop down and when you select it then you see the value. Also is confusing if you have a mix of descriptions and values something like this,

```
model EnumPackage
  model ModelWithEnum
  
  parameter EnumPackage.EnumClass enumParam = EnumPackage.EnumClass.FirstChoice "Enum parameter";

  end ModelWithEnum;

  type EnumClass = enumeration(
      FirstChoice
      "Description of first choice",
      SecondChoice) "This is an enumeration";

end EnumPackage;
```

Maybe we can show something like `value (description)` and when you select it you only see the value.

@casella what is your opinion on this?

**Comment by casella** [comment]
I think we can have `value description` without parentheses, where description is the content of the comment string of each enumeration value. Same as with replaceable classes. This gives all the available information in a nice form.
