### ISSUE TITLE
During the installation of dependencies the wrong jdk directory name is created

### ISSUE THREAD

**Issue by InformationOcean** [OpenModelica/OpenModelica#10218]
### Description

Using the "sudo port install cmake ccache qt5 qt5-qtwebkit autoconf boost OpenSceneGraph openjdk11" command the wrong directory name is created for openjdk11.  Here are the commands I used in Terminal.  /It is on MacBook Air 2020 with the newest OS, Venturra 13.1 

### Steps to Reproduce

```sh
/Volumes/Home/janos
janos@Dads-MacBook-Air ~ % cd /Volumes/Apps/OpenModelica 
janos@Dads-MacBook-Air OpenModelica % git clean -ffdx
janos@Dads-MacBook-Air OpenModelica % git submodule foreach --recursive git clean -ffdx
Entering 'OMCompiler/3rdParty'
Entering 'OMOptim'
Entering 'OMOptim/common'
Entering 'OMSens'
Entering 'OMSens_Qt'
Entering 'OMSens_Qt/common'
Entering 'OMSimulator'
Entering 'OMSimulator/3rdParty'
Entering 'OMSimulator/OMTLMSimulator'
janos@Dads-MacBook-Air OpenModelica % sudo port install cmake ccache qt5 qt5-qtwebkit autoconf boost OpenSceneGraph openjdk11
Password:
--->  Computing dependencies for cmake
--->  Cleaning cmake
--->  Computing dependencies for ccache
--->  Cleaning ccache
--->  Computing dependencies for qt5
--->  Cleaning qt5
--->  Computing dependencies for qt5-qtwebkit
--->  Cleaning qt5-qtwebkit
--->  Computing dependencies for autoconf
--->  Cleaning autoconf
--->  Computing dependencies for boost
--->  Cleaning boost
--->  Computing dependencies for OpenSceneGraph
--->  Cleaning OpenSceneGraph
--->  Computing dependencies for openjdk11
--->  Fetching archive for openjdk11
--->  Attempting to fetch openjdk11-11.0.18_0+release+server.darwin_22.arm64.tbz2 from https://packages.macports.org/openjdk11
--->  Attempting to fetch openjdk11-11.0.18_0+release+server.darwin_22.arm64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/openjdk11
--->  Attempting to fetch openjdk11-11.0.18_0+release+server.darwin_22.arm64.tbz2 from http://mirror.fcix.net/macports/packages/openjdk11
Error: reinplace: couldn't read file "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_java_openjdk11/openjdk11/work/jdk-11.0.18-ga/make/autoconf/lib-ffi.m4": no such file or directory
Error: Failed to patch openjdk11: reinplace sed(1) failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_java_openjdk11/openjdk11/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.

```
### Expected Behavior

Looking the mentioned error message from above I see that it is not finding the jdk-11.0.18-ga directory inside the work directory.  Checking the work directory in my machine I see this:

```sh
janos@Dads-MacBook-Air OpenModelica % ls -l /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_java_openjdk11/openjdk11/work 
total 0
drwxr-xr-x  17 macports  wheel  544 Jan 10 03:32 jdk11u-jdk-11.0.18-ga
```

So, somehow the name of the directory received a "jdk11u-" prefix and that is the reason it cannot find the jdk-11.0.18-ga directory

### Version and OS

Latest OpenModelica downloaded a week ago.
Latest OS on the MacBook Air M1 2020, Ventura 13.1

### Additional Context

 Should I just rename that directory and try the command again?  I guess if the whole command is the guilty one then the wrong directory name will be recreated, so it might be futile.  I read somewhere as I tried to find what the problem might be, that Oracle changed opnejdk on January 18th.  Maybe that is the root of the problem.

**Comment by mahge** [comment]
This looks like a `macports` issue and probably has nothing to do with OpenModelica. @InformationOcean you should first try to install  openjdk11 alone (to make sure nothing else is interfering with it) and then report this to the macports people following the instructions at https://guide.macports.org/#project.tickets

**Comment by mahge** [comment]
I am closing the ticket. If this turns out to be OpenModelica related, let us know and we will investigate.
