### ISSUE TITLE
OMEdit fails to display diagram if parameter Real x[:]; is declared

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#10217]
The following model does not show the integrator in the diagram view:
```modelica
model Test
  parameter Real x[:];

 Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(visible = true, transformation(origin = {14, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

end Test;
```
while the following does:
```modelica
model Test
  parameter Real x[2];

 Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(visible = true, transformation(origin = {14, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

end Test;
```
This was tested with OMEdit 1.21.0~dev-256-g56379c0 on Linux, with `OMEdit --NAPI=true Test.mo`

**Comment by casella** [comment]
@mwetter I guess the first model you posted is invalid because the frontend cannot determine the size of the parameter, so it stops the instantiation.

Dealing with partially valid models is one issue that hasn't been fully resolved yet, thanks for posting another instance of it.
