### ISSUE TITLE
Dropdown of replaceables with constrainedby 

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10212]
### Description

Consider a replaceable declaration with the constrainedby keyword. No explicit choices are defined. The dropdown choices of this replaceable declaration in the parameter dialog are very long and contain the path to the class as well as the redeclare statement. Our desired element shown in the dropdown menu would be the class comment in accordance to other modelica tools.

### Steps to Reproduce

1. Load the package `Rexroth_Generic\package.mo`
2. Drag and drop the component `Rexroth_Generic.BRSL_World` onto a new sheet and open its parameter dialog. 
3. Open the dropdown menu for the `fluid1` parameter (with the old API in tab fluid1, with the new APi wrongly in tab general)
4. The dropdown choices are named `redeclare <PathToClass>`. The desired behavior would be the description string of the choice classes. In case of the `BRSL_World.fluid1` dropdown this would be `HLP46, HLP32, HFC`. 

### Expected Behavior

The description string of the choice class is displayed in the dropdown menu instead of the redeclare statement.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-253-g9bf056631b (64-bit) with old and new API
 - OS: Windows 10, 64 bit

Thanks for looking into it
Aaron Buntrock - bosch rexroth

**Comment by adeas31** [comment]
> Open the dropdown menu for the `fluid1` parameter (with the old API in tab fluid1, with the new APi wrongly in tab general)

It is shown correctly in tab `fluid1`. Maybe fixed sometime ago.

With PR #13264 we display the `redeclare <PathToClass> - <description>`

![image](https://github.com/user-attachments/assets/9dd1f76d-9b5e-4a83-96c1-3e3e8618b4f7)

AFAIR we decided on this name convention sometime ago in some other ticket.

**Comment by abuntrock** [comment]
The tab problem was solved some time in the past. 
Since you actively decided on this naming convention I will close this ticket

**Comment by abuntrock** [comment]
Looks as described by you in today's nightly. Thanks a lot.
