### ISSUE TITLE
Optionally disable Jacobian generation in the NB

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10232]
When dealing with very large models, sometimes explicit solvers can be used. In this case, the potentially large amount of time spent generating the Jacobian sparsity structure, analyzing it, and possibly generating analytic Jacobians is totally wasted. This is for example the case with the HarmonicOscillator test cases in [LargeTestSuite_NB](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html).

It would be nice to have a flag to suppress ODE Jacobian generation from the entire backend-simcode toochain in these cases.

**Comment by rfranke** [comment]
When exporting an FMU, the debug flag `disableFMIDependency` does this.

**Comment by casella** [comment]
OK, we should have something like that for the C runtime as well. I would suggest a flag name such as `--explicitODESolverOnly` with explanation "Disables generating code that is not needed for explicit ODE solvers". Whatever that is 😄 

We shoudn't use debug flags for functions that are needed in production, not for debugging.

**Comment by rfranke** [comment]
The problem solved with `disableFMIDependency` was that the file `modelDescription.xml` of an FMU had grown to about 100MB in size, despite of array preservation during code generation. Most of this space was for scalar dependencies in `modelDescription.xml`. In this case the FMU just contained an algorithm, not even an ODE.

**Comment by casella** [comment]
If we want to go above 1M equations well'have to consider this kind of issues carefully.

**Comment by phannebohm** [comment]
@kabdelhak and myself looked at all the compiler flags for Jacobians, they are a bit of a mess currently. For the NB we are discussing a more systematic set of flags in https://github.com/phannebohm/OpenModelica/commit/ee7b207cac9df108491824c48f5740804d8aac52.

For the OB [`--postOptModules-=symbolicJacobian`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-postoptmodules) should do what you want and porting that behavior to the NB should be easy.

**Comment by casella** [comment]
> For the OB [`--postOptModules-=symbolicJacobian`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-postoptmodules) should do what you want and porting that behavior to the NB should be easy.

OK. For the OB, I don't care much. The interesting thing is boosting the size of models that can be simulated with explicit algorithms, using the NB.

**Comment by casella** [comment]
@phannebohm this is another low-hanging fruit like #12981 that we should fix ASAP. Thanks!

**Comment by phannebohm** [comment]
> The problem solved with `disableFMIDependency` was that the file `modelDescription.xml` of an FMU had grown to about 100MB in size, despite of array preservation during code generation. Most of this space was for scalar dependencies in `modelDescription.xml`. In this case the FMU just contained an algorithm, not even an ODE.

As I understand it, this issue is about not generating code that is needed only for implicit ode solvers. The `modelDescription.xml` has nothing to do with that, right?

**Comment by phannebohm** [comment]
In order to not have more and more flags, I suggest changing 
```
--generateSymbolicJacobian = true | false
```
into
```
--generateODEJacobian = "none" | "numeric" | "symbolic"
```
and keeping `"numeric"` as default so it is backwards compatible. @casella what do you think?

**Comment by casella** [comment]
I like the idea, but I don't like the flag name. I would find it very confusing that --generate**ODE**Jacobian also generates the Jacobian for **DAEs** in daeMode 😃 

We really need to find a good nomenclature to distinguish Jacobians of algebraic equations (as found in initial equations and in causalized ODE systems with algebraic loops in the original formulation) from Jacobians of dynamic equations, to be used by implicit ODE **and DAE** solvers. An then, use it consistently. 

Maybe we should seize the moment and clean up this mess now.

Currently we have flags named:
- calculateStrongComponentJacobians
- symbolicJacobian
- LSanalyticJacobian
- NLSanalyticJacobian
- forceNLSanalyticJacobian
- generateSymbolicJacobian
- debugAlgebraicLoopsJacobian
- dumpExcludedSymJacExps
- symJacConstantSplit
- symjacdump
- symjacdumpeqn
- symjacdumpverbose
- symjacwarnings

which is a bloody mess, as it is often not clear which Jacobian is involved. Also, we are still mixing "symbolic" and "analytic" with the same meaning, we should stick to "symbolic" consistently. Finally, it is not clear if the flags regarding Jacobians of dynamic equations are also relevant for daeMode, since only ODEs are mentioned in the documentation. This should also be updated.

Maybe "algebraic" and "dynamic" are the right kewords? That would give us `--generateDynamicJacobian=none | numeric |symbolic`

But then, I would suggest we update the names of the other flags:
- calculateStrongComponentJacobians -> calculateAlgebraicJacobians
- symbolicJacobian -> symbolicDynamicJacobian
- LSanalyticJacobian -> LSsymbolicJacobian (here, it is clear we refer to algebraic equations)
- NLSanalyticJacobian -> NLSsymbolicJacobian (ditto)
- forceNLSanalyticJacobian -> forceNLSsymbolicJacobian (ditto)
- generateSymbolicJacobian -> generateDynamicSymbolicJacobian
- debugAlgebraicLoopsJacobian -> debugAlgebraicJacobian
- dumpExcludedSymJacExps -> dumpExcludedDynSymJacExps (is it dynamic? or algebraic?)
- symJacConstantSplit -> ?? algebraic or dynamic ??
- symjacdump -> symDynJacDump (why not always using camel case?)
- symjacdumpeqn -> seems dead, can remove?
- symjacdumpverbose -> symDynJacDumpVerbose
- symjacwarnings -> symDynJacWarnings

This would cause some non-backwards compatibility, but I won't be too worried about that, as these flags are mostly used for debugging and advanced testing. We can write about it in the release notes. Deprecating all these flags but keeping them alive would be a mess.

@phannebohm what do you think?

**Comment by phannebohm** [comment]
I agree with all you said. A few comments on your suggestions:

>     * generateSymbolicJacobian -> generateDynamicSymbolicJacobian

Again, here I'd say we make it generateDynamicJacobian and have the options: none, numeric, symbolic.

>     * dumpExcludedSymJacExps -> dumpExcludedDynSymJacExps (is it dynamic? or algebraic?)

Both I think. It is used here only
https://github.com/OpenModelica/OpenModelica/blob/d750806bd021f332d0f995bb0a6829d2944147c1/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo#L3199-L3216

>     * symJacConstantSplit -> ?? algebraic or dynamic ??

This really shouldn't be an option. It should just be done always, for both algebraic and dynamic Jacobians.

>     * symjacdumpeqn -> seems dead, can remove?

It is used in one function in the old backend. But I guess we can remove it if the description says so.
https://github.com/OpenModelica/OpenModelica/blob/d750806bd021f332d0f995bb0a6829d2944147c1/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo#L2561-L2603

>     * symjacdumpverbose -> symDynJacDumpVerbose

Not sure if this is for dynamic Jacobian only...

>     * symjacwarnings -> symDynJacWarnings

This one isn't used anywhere, so I guess we can just remove it.

**Comment by casella** [comment]
Agreed on all the line. Please go ahead with it

**Comment by casella** [comment]
Works fine, thanks!
