### ISSUE TITLE
Unable to enlarge Libraries Browser in some cases

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10235]
### Description
The recent addition of buttons on the Welcome perspective
has a nasty side effect: in come cases e cannot enlarge Libraries Browser horizontally

### Steps to Reproduce
I'm not sure whether the reproducibility of this issue depends on the screen resolution. On one of my PCs (with 1920x1080 resollution) it can be reproduced as follows:
- open OMEdit, and resize in Welcome perspective to a size that Modelica to a size that leaves all buttons fully visible (up to install library), but with a short margin right of "Install Library" button, as follows:
![image](https://user-images.githubusercontent.com/7373030/220045987-fd70deee-06b6-4e5d-940a-1b6be68f57f0.png)
- run a model of choice so that at the end OMEdit switches to Plotting perspective
- try to enlarge horizontatly the Libraries Browser: it results impossible, for some reason blocked by the buttons in the Welcome perspective 

### Expected Behavior
The library browser should be free to be enlarged at will.
A possible solution to this issue is to use icons with hints in the welcome buttons, which would reduce their horizontal size dramatically.
Another solution is to keep the horizontal libraries browser size free, when out of the Welcome perspective (or perhaps even when in the welcome perspective).

### Version and OS
OM 1.20.0

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
I would suggest to use double-height buttons, splitting the text:
- Create New\nModelica Class
- Open Model\nLibrary File(s)
- System\nLibraries
- Install Library

This will reduce the constraint on the minimum size of the central pane of OMEdit enough (I guess), unless you are really using an old screen with a lousy resolution, without otherwise altering the current design.

**Comment by adeas31** [comment]
I put the buttons in a scroll area so it should be possible to resize now.

**Comment by adeas31** [comment]
Ported this to 1.22.1 #11655
