### ISSUE TITLE
MS Visual Studio not usable for simulation (and FMU)

### ISSUE THREAD

**Issue by Bluescreenix** [OpenModelica/OpenModelica#10236]
### Description

Any attempt to run a simulation with one of the MSVC versions failes. 
c:\openmodelica\modelica.mechanics.multibody.examples.elementary.doublependulum\doublependulum_15syn.c(11): error C2440: '=': cannot convert from 'void *' to 'BASECLOCK_DATA *'
c:\openmodelica\modelica.mechanics.multibody.examples.elementary.doublependulum\doublependulum_15syn.c(11): note: Conversion from 'void*' to pointer to non-'void' requires an explicit cast

### Steps to reproduce
Open one of the examples - e.g. mechanics/double Pendulum and try to simulate that using OS Windows and a MSVC compiler.

### Expected behavior
If I can select the MS compilers I would expect them (or at least one of them) to work.

### Version and OS
OS: Windows 10 
Open Modelica Version 1.21 stable and OpenModelica v1.21.0-dev-259-g3b600d55cc (64-bit)
Compiler - different MS VC

### Additional context
I read somewhere MSVC support seems to be broken quite a while now and we should switch to linux and gcc.

I totally get it that this is a open source project and I can not complain. I also completely understand that there is Linux and GCC. But to make use of OpenModellica sometimes it is necessary to go to Windows and use proprietary compilers. E.g. to make FMU available for use in other Windows Simulation software. 
Only because there is a sophisticated section where I can select between different compilers in options setup I had hope that selecting one of them would make sense. If no longer Windows / MS VC support is provided maybe it would be good to explain this on the project doku and remove the selection from options dialog.

If there will be further MS VC suport for Simulation and FMU export clearly that would be good news! 
:-)

**Comment by casella** [comment]
@adeas31 @adrpo I think @Bluescreenix is right. Should we remove this (at least temporarily) from the GUI?

**Comment by adeas31** [comment]
Fixed with #12950 and ported to maintenance/v1.24 with #12952
