### ISSUE TITLE
OMEdit does not show selection of replaceable package (such as for media)

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#10248]
### Description

In the model below, double-clicking the instance `myComponent` in `MyFluidSystem` does not show the replaceable media. This feature is important to support for fluid flow modeling.

```modelica
package Test

  model MyComponent
    replaceable package Medium1 = Modelica.Media.Water.StandardWaterOnePhase
      constrainedby Modelica.Media.Interfaces.PartialMedium
      annotation(choicesAllMatching=true);

        replaceable package Medium2 = Modelica.Media.Interfaces.PartialMedium
      "Medium in the component"
        annotation (choices(
          choice(redeclare package Medium = Modelica.Media.Air.SimpleAir "Dry air"),
          choice(redeclare package Medium = Modelica.Media.Air.MoistAir "Moist air")));

  end MyComponent;

  model MyFluidSystem

    MyComponent myComponent
      annotation (Placement(transformation(extent={{-10,-10},{10,10}})));
  end MyFluidSystem;
  annotation (
    uses(Modelica(version = "4.0.0")));

end Test;
```

### Steps to Reproduce

Double click the instance `myComponent` in `MyFluidSystem`.

### Expected Behavior

Two entries to select the respective media.

### Screenshots

![image](https://user-images.githubusercontent.com/1329080/220719183-3b1743c6-4fe6-4fd6-aa2d-25e01b0cb245.png)

### Version and OS

OpenModelica 1.21.0~dev-268-g59d7f9f
on Linux.

**Comment by casella** [comment]
@mwetter did you test this with `OMEdit --NAPI=true`?

**Comment by adeas31** [comment]
This is a known issue. See #10140

**Comment by mwetter** [comment]
@casella : Yes, this is with `OMEdit --NAPI=true`.

**Comment by adeas31** [comment]
This is already fixed. Please test and reopen if needed.
