### ISSUE TITLE
noEquidistantTimeGrid simulation flag from vendor annotation is ignored by OMEdit when using gbode

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10258]
Please run this model with OMEdit:
```modelica
model TestNoEquidistantTimeGrid
  Real x(start = 1, fixed = true);
equation
  der(x) = -x;
annotation(experiment(StopTime = 5, Interval = 1),
           __OpenModelica_simulationFlags(s = "gbode", gbm = "esdirk3",
                                          noEquidistantTimeGrid = "()"));
end TestNoEquidistantTimeGrid;
```

OMEdit runs this command
```
d:\temp\OMEdit/TestNoEquidistantTimeGrid/TestNoEquidistantTimeGrid.exe -port=52464 -logFormat=xmltcp -override=startTime=0,stopTime=5,stepSize=1,tolerance=1e-06,solver=gbode,outputFormat=mat,variableFilter=.* -r=d:\temp\OMEdit/TestNoEquidistantTimeGrid/TestNoEquidistantTimeGrid_res.mat -w -lv=LOG_STATS -gbm=esdirk3 -inputPath=d:\temp\OMEdit/TestNoEquidistantTimeGrid -outputPath=d:\temp\OMEdit/TestNoEquidistantTimeGrid
```
which unfortunately does not include `-noEquidistantTimeGrid`, and in fact the results has only 5 grid points, as mandated by `stepSize = 1`. If I check the Additional Simulation Flags field in the Simulation Setup window, I only see `-gbm=esdirk3`. So, it seems that the flag is lost somehow, when being transferred from the `__OpenModelica` annotation to the Additional Simulation Flag field.

However, if I re-simulate and add `-noEquidistantTimeGrid` to the simulation flags, I get the expected behaviour.

@adeas31 can you please check why this happens and fix it?

**Comment by adeas31** [comment]
The `Equidistant Time Grid` option is only enabled for `dassl` and `ida` solvers. The same goes true for `DASSL/IDA options` group that contains root finding, restart after event etc.

**Comment by casella** [comment]
OK, then you should also enable it for the gbode solver, that also handles this option. I guess that would solve this issue.

**Comment by adeas31** [comment]
Shall I also enable `root finding`, `restart after event`, `Initial Step Size`, `Maximum Step Size` and `Maximum Integration Order`?

**Comment by AnHeuermann** [comment]
I'm not sure if GBODE will do anything with `root finding`, `restart after event`, `Initial Step Size`, `Maximum Step Size`.
@bernhardbachmann do you know how to handle these simulation flags in GBODE?

`Maximum Integration Order` doesn't make to much sense for GBODE, the order is fixed for each method.

**Comment by casella** [comment]
> I'm not sure if GBODE will do anything with `root finding`, `restart after event`, `Initial Step Size`, `Maximum Step Size`. 

In principle it should, since it supports variable step-size with error control and event handling. Not sure if @bernhardbachmann actually used those flags to set the values.

> `Maximum Integration Order` doesn't make to much sense for GBODE, the order is fixed for each method.

Absolutely.

**Comment by adeas31** [comment]
@bernhardbachmann ?

**Comment by casella** [comment]
@bernhardbachmann is somebody else than you in charge of replying to @adeas31 on this? :)

**Comment by bernhardbachmann** [comment]
The flags `-maxStepSize` and `-initialStepSize` are now utilized in GBODE (see #10334). In addition, `-noEquidistantTimeGrid` is already used and it would be nice, if these flags could be activated through the OMEdit GUI. Furthermore, `-noRestart` as well as `-noRootFinding` will be made available in future GBODE versions. Maybe, we should generate new tickets for each of it.

**Comment by casella** [comment]
@adeas31, please add support for` -noEquidistantTimeGrid`, `-maxStepSize` and `-initialStepSize` to the `gbode` solver in OMEdit, so we can proceed with the 1.21.0 beta release. Thanks!

**Comment by casella** [comment]
@bernhardbachmann see #10340 and #10341 for future enhancements.

**Comment by casella** [comment]
@bernhardbachmann @AnHeuermann something's still wrong with -initialStepSize, see [comment](https://github.com/OpenModelica/OpenModelica/pull/10334#issuecomment-1460055303).

**Comment by casella** [comment]
Also please update the [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-initialstepsize) of these flags, currently it only mentions dassl and ida.
