### ISSUE TITLE
Issue with gbode solvers and ConceptualPowerSystem model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10260]
Please run the three test models of this package:

```modelica
package TestConceptualPowerSystems
  model DASSL
    extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
    annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
               experiment(StopTime=200, Tolerance=1e-7, Interval = 0.05),
               __OpenModelica_simulationFlags(s = "dassl"));
  end DASSL;
  
  model RADAU
    extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
    annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
               experiment(StopTime=200, Tolerance=1e-7, Interval = 0.05),
               __OpenModelica_simulationFlags(s = "gbode", gbm = "radauIIA2"));
  end RADAU;
  
  model ESDIRK
    extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
    annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
               experiment(StopTime=200, Tolerance=1e-7, Interval = 0.05),
               __OpenModelica_simulationFlags(s = "gbode", gbm = "esdirk4"));
  end ESDIRK;
end TestConceptualPowerSystems;
```

DASSL gives the following execution statistics:
```
solver: dassl
 2745 steps taken
 3163 calls of functionODE
   71 evaluations of jacobian
   42 error test failures
    0 convergence test failures
```
ESDIRK4 gives the following execution statistics:
```
solver: gbode
 2148 steps taken
205212 calls of functionODE
24125 evaluations of jacobian
  267 error test failures
    0 convergence test failures
```
The number of steps is slightly lower, but on the other had the number of functionODE calls is two orders of magnitude, which is ludicrous; ditto for the nuber of jacobian evaluations, which grows to 71 to over 24000(!).

I guess there is something wrong in those jacobians that is causing a lot of iterations and jacobian recomputations at each step. Please investigate.

RADAU gives the following statistics:
```
solver: gbode
93764 steps taken
5106326 calls of functionODE
163950 evaluations of jacobian
  149 error test failures
```
which are even worse, now there are 30X as many steps, and three orders of magnitude more RHS and Jacobian computations. Probably same root cause.

@bernhardbachmann please investigate

**Comment by bernhardbachmann** [comment]
By default the numerical calculation of  the Jacobian is used. If you set the simulation flag -jacobian=coloredSymbolical, the symbolical Jacobian is used (You can doe this in OMEdit). The result for esdirk4 is then:

|                 | |       | | | 2148 steps taken
|                 | |       | | | 24176 calls of functionODE
|                 | |       | | | 24125 evaluations of jacobian
|                 | |       | | |   267 error test failures
|                 | |       | | |     0 convergence test failures
|                 | |       | | | 0s time of jacobian evaluation

These numbers are reasonable, since one has to calculate for each step about 4 Jacobians and if you have 2-3 Newton steps to solve the nonlinear system, you have round about 24125 Jacobian calculations. and about the same number of calls of functionODE.

The numbers above for functionODE calls are due to the fact, that for the numerial Jacobian, one has to call functionODE, which overall counts to the total number of calls of functionODE.

**Comment by casella** [comment]
> By default the numerical calculation of the Jacobian is used. If you set the simulation flag -jacobian=coloredSymbolical, the symbolical Jacobian is used (You can do this in OMEdit). 

I'm confused. I understood that in order to get symbolic jacobians for the ODE you had to enable them with the _compiler_ flag `--generateSymbolicJacobian`, and then it would be used automatically at runtime. Do I miss something?

The result for esdirk4 is then:
> 
> | | | | | | 2148 steps taken | | | | | | 24176 calls of functionODE | | | | | | 24125 evaluations of jacobian | | | | | | 267 error test failures | | | | | | 0 convergence test failures | | | | | | 0s time of jacobian evaluation
> 
> These numbers are reasonable, since one has to calculate for each step about 4 Jacobians and if you have 2-3 Newton steps to solve the nonlinear system, you have round about 24125 Jacobian calculations. and about the same number of calls of functionODE.

This is what you get if you use the Newton algorithm proper. Efficient codes such as DASSL try to avoid recomputing the Jacobian all the time and do it only when convergence starts to be affected. Dassl manages to do that 71 times on a transient. That's a lot of times less than 24125, even considering that DASSL is a multi-step algorithm, so it has one "stage" per step compared to the four stages of esdirk4.

Q1: could you consider using the same Jacobian for the N stages of gbode solvers?
Q2: could you consider re-using the same Jacobian for multiple steps, and monitor convergence to determine when it's time to recompute it?

Otherwise, the integration will always be a lot more inefficient than with DASSL/IDA, because of all the Jacobian computations.

**Comment by casella** [comment]
@bernhardbachmann please try this other test cases from the package [ConceptualPowerSystem.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10856007/ConceptualPowerSystem.mo.txt).

`ConceptualPowerSystem.Experiments.StepChange_N_16_M_4_EsdirkSingleRate`:
```
solver: gbode
  290 steps taken
64087 calls of functionODE
 1747 evaluations of jacobian
    3 error test failures
    0 convergence test failures
```
`ConceptualPowerSystem.Experiments.StepChange_N_16_M_4_EsdirkMultiRate` (same as above with `-gbratio=0.3`)
```
inner integration call statistics:
number of steps taken so far: 6723

outer integration call statistics:
number of steps taken so far: 813
```
There is obviously something going wrong here: when going multirate, the number of outer steps is 3 times the number of steps of single rate, and the number of inner steps becomes 20X bigger.

Going to `-gbratio=0.1` gives:
```
inner integration call statistics:
number of steps taken so far: 2081

outer integration call statistics:
number of steps taken so far: 577
```
which is slightly better, but still much, much worse than single-rate.

**Comment by casella** [comment]
This ticket is a mess, @bernhardbachmann already spun off two specific issues, I'll spin off a couple more and then close it.

**Comment by casella** [comment]
Split issues in separate tickets.
