### ISSUE TITLE
Make the new instance-based GUI available via Tools | Options | General menu

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10272]
The work on the new instance-based GUI has been going on for a year, see #8425. The feature is at a good stage of development, but still not good enough to become the default in v. 1.21.0.

Currently, it is activated by running OMEdit with a command line flag OMEdit --NAPI=true. This is a bit inconvenient if we want more people to test it in the forthcoming 1.22.0 nightly builds.

@adeas31 can you please add an option to set this flag from the Tools | Options | General menu? Please try to make it in a way that won't get users stuck with the old GUI once the new one will become default in 1.22.0.

**Comment by AnHeuermann** [comment]
@adeas31 While you are on it, can you also add a clear/easy way for a user to check if OMEdit is using the new API or not?
Currently I have to search for some specific string in the `omeditcommunication.log`.

**Comment by adeas31** [comment]
> @adeas31 While you are on it, can you also add a clear/easy way for a user to check if OMEdit is using the new API or not? Currently I have to search for some specific string in the `omeditcommunication.log`.

After we change from command line to option then you can simply go in options and see if the option is checked or not.
