### ISSUE TITLE
Docker FMU build fails with external c functions

### ISSUE THREAD

**Issue by jcramer-bc** [OpenModelica/OpenModelica#10279]
### Description
When building an FMU using docker (w/ CMake or autoconf), external c functions cause the build to fail.  As @AnHeuermann observed in https://github.com/OpenModelica/OpenModelica/issues/9331#issuecomment-1447924577: 

- Suitability of multiarch/crossbuild: CMake version is too old.
- Adding external libraries locations to Docker container.
- Cross-Compilation for external libraries that don't provide the correct binary for OS inside Docker.

### Steps to reproduce
Create script `run.mos`:

```
loadString("
model externalCall
  Real x(start=1, fixed=true);
  Integer s = Modelica.Math.Random.Utilities.automaticGlobalSeed();
equation
  der(x) = -0.5*x;
end externalCall;"); getErrorString();
setCommandLineOptions("--fmuRuntimeDepends=none"); getErrorString();
setCommandLineOptions("--fmuCMakeBuild=true"); getErrorString();
buildModelFMU(externalCall,"2.0","cs","<default>",{"x86_64-linux-gnu docker run --pull=never multiarch/crossbuild"},true); getErrorString();
```
Running `omc run.mos` produces:

with cmake:
```
-- Linking ModelicaExternalC-NOTFOUND
-- Configuring incomplete, errors occurred!
```

without cmake (by commenting out the cmake related lines in run.mos):
```
/usr/bin/ld: cannot find -lModelicaExternalC
collect2: error: ld returned 1 exit status
```
### Expected behavior
FMU should build.

### Version and OS
 - latest OM / docker

### Additional context:
This question was originally posed here: https://github.com/OpenModelica/OpenModelica/issues/9331#issuecomment-1447344885, and @AnHeuermann asked to open a new issue.

**Comment by AnHeuermann** [comment]
I don't know how to get the SimCode object in CevalScriptBackend.mo. The rest should be easy to do.

**Comment by jcramer-bc** [comment]
@AnHeuermann thanks for the direction.  I will give it a shot if I can find some time.

**Comment by AnHeuermann** [comment]
Check out https://github.com/AnHeuermann/OpenModelica/tree/issue-10279
It has a rough framework, but the new Docker `cp` command is not working yet.

**Comment by AnHeuermann** [comment]
@jcramer-bc this should now be working. One remaining issue is, that the Docker image used to cross-compile (multiarch/crossbuild) has an ancient CMake . To fully utilize the capabilities of the Docker compilation one needs to use 
```
setCommandLineOptions("--fmuRuntimeDepends=modelica"); getErrorString();
setCommandLineOptions("--fmuCMakeBuild=true"); getErrorString();
```
to copy the C libraries into the FMU `binaries/` directory.
