### ISSUE TITLE
Activate replaceable support by default in OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10282]
After @perost's miracle cure in #10273, I think there is no reason why we shouldn't always activate replaceable support. That option is very confusing for people that happen to have OMC installed for some time and keep the default-off option.

I would then remove that item entirely from the Tools | Options | General menu and make sure this option is always enabled in 1.21.0

@adeas31 can you please take care of that before we branch off 1.21.0 beta? Thanks!

**Comment by adeas31** [comment]
I agree. We should also completely remove the option `Enable new frontend use in the OMC API (faster GUI response)`. I talked yesterday with @perost about it. He said the option can be a default on now without any problems and I don't see any usecase where you actually want to disable it. The flag was simple added for development purpose.

**Comment by perost** [comment]
> I agree. We should also completely remove the option `Enable new frontend use in the OMC API (faster GUI response)`. I talked yesterday with @perost about it. He said the option can be a default on now without any problems and I don't see any usecase where you actually want to disable it. The flag was simple added for development purpose.

#10289 turns the flag on by default in the compiler, so OMEdit can just forget that the flag exists. If a user for any reason want to disable it there's still the option to set the flag manually.

**Comment by casella** [comment]
Very good, thanks!
