### ISSUE TITLE
Activate simulation flag '-jacobian=coloredSymbolical' in gbode, if compiler flag '--generateSymbolicJacobian' is set.

### ISSUE THREAD

**Issue by bernhardbachmann** [OpenModelica/OpenModelica#10286]
I'm confused. I understood that in order to get symbolic jacobians for the ODE you had to enable them with the _compiler_ flag `--generateSymbolicJacobian`, and then it would be used automatically at runtime. Do I miss something?

_Originally posted by @casella in https://github.com/OpenModelica/OpenModelica/issues/10260#issuecomment-1448596187_

**Comment by casella** [comment]
Thanks Bernhard!
