### ISSUE TITLE
Improve jacobian calculation in gbode (only update, if necessary)!

### ISSUE THREAD

**Issue by bernhardbachmann** [OpenModelica/OpenModelica#10287]
Q1: could you consider using the same Jacobian for the N stages of gbode solvers?
Q2: could you consider re-using the same Jacobian for multiple steps, and monitor convergence to determine when it's time to recompute it?

Otherwise, the integration will always be a lot more inefficient than with DASSL/IDA, because of all the Jacobian computations.

_Originally posted by @casella in https://github.com/OpenModelica/OpenModelica/issues/10260#issuecomment-1448596187_

**Comment by bernhardbachmann** [comment]
The default settings already were as such, that kinsol updates the jacobian, if necessary. But, there is in addition a scaling routine for the residuals, which is called each time, when a/the nonlinear system has to be solved. This routine produces an extra calculation of the jacobian. Since, this is a performance issue even for the algebraic loops, one needs a general solution for this.

**Comment by casella** [comment]
> The default settings already were as such, that kinsol updates the jacobian, if necessary.

OK, good.

> But, there is in addition a scaling routine for the residuals, which is called each time, when a/the nonlinear system has to be solved. This routine produces an extra calculation of the jacobian. Since, this is a performance issue even for the algebraic loops, one needs a general solution for this.

Of course there is no need to do that. For initialization, the idea was to compute it only once with start values. Maybe computing the scaling only once during simulation is questionable, but I would say that the scaling usually doesn't change during the simulation - values can change, but the order of magnitude remains the same. So, we could only compute it once with the values found at initialization. Alternatively, we could recompute them every time the Jacobian is computed, not sure if that is really necessary.

Is that what you did in #10318?

**Comment by bernhardbachmann** [comment]
No, now the scaling should work like before, but, instead of calculating the Jacobian each time, I use the Jacobian stored in kinsol data, which should be up-to-date during the whole simulation time.

**Comment by casella** [comment]
> No, now the scaling should work like before, but, instead of calculating the Jacobian each time, I use the Jacobian stored in kinsol data, which should be up-to-date during the whole simulation time.

Sounds good!
