### ISSUE TITLE
RedHat 8 : missing packages for installation

### ISSUE THREAD

**Issue by angmarion** [OpenModelica/OpenModelica#10292]
Hello,
On RedHat 8.2 and 8.7, OpenModelica 1.19 and nightly cannot be installed.
I followed the instructions on https://openmodelica.org/download/download-linux/, until the installation line.
```
dnf install openmodelica-1.19
```
Three libraries are missing and cannot be installed:
- lapack-devel
- boost-static
- libstdc++-static

Trying to install it seperately fails, as no compatible version can be found. Could you provide these files?

Thank you!

**Comment by casella** [comment]
Does it work with 1.20.0? Is there any reason why you'd like to stick to an older version?

**Comment by angmarion** [comment]
The issue is the same with 1.20 and with nightly release.

**Comment by casella** [comment]
OK. @sjoelund and @mahge will look into it ASAP.

**Comment by sjoelund** [comment]
Seems to require:
yum config-manager --set-enabled powertools

Which el7 and el9 don't need

**Comment by angmarion** [comment]
I tried this line but powertools was not recognized as a package. I did some digging on the internet and found a solution.

```
sudo subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
dnf install postgis30_12
```

This last command failed, but still made some installations. I then managed to install OpenModelica with the traditional
```dnf install openmodelica-nightly```

However another issue appeared during export of FMU, but I will open another ticket for that matter.
Thanks for your help!

**Comment by angmarion** [comment]
See https://access.redhat.com/discussions/5417621 (ticket opened in RedHat, useful to resolve this issue).

**Comment by casella** [comment]
@sjoelund should we mention this in the [Linux installation guide](https://openmodelica.org/download/download-linux/)?

**Comment by sjoelund** [comment]
https://github.com/OpenModelica/www.openmodelica.org/commit/765a75abc4c2ce67bd081d78c7474f9902f9e897
