### ISSUE TITLE
RadauIIA2 gbode algorithm takes too many steps in ConceptualPowerSystem model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10293]
Please check this MWE package:
```modelica
package TestConceptualPowerSystems
  model RADAU
    extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
    annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
               experiment(StopTime=200, Tolerance=1e-4, Interval = 0.05),
               __OpenModelica_simulationFlags(s = "gbode", gbm = "radauIIA2"));
  end RADAU;
  
  model ESDIRK
    extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
    annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
               experiment(StopTime=200, Tolerance=1e-4, Interval = 0.05),
               __OpenModelica_simulationFlags(s = "gbode", gbm = "esdirk4"));
  end ESDIRK;
end TestConceptualPowerSystems;
```
The simulation with esdirk4 returns:
```
solver: gbode
  637 steps taken
```
while the simulation with radauIIA2 returns
```
solver: gbode
 9389 steps taken
```
Both algorithms are implicit, single-step, and fourth-order accurate. I am a bit surprised that radau needs 15 times as many steps to achieve the same precision.

@bernhardbachmann is this reasonable, or is there some problem in the radau implementation?

Originally reported in #10260, with somewhat different solver parameters.

**Comment by bernhardbachmann** [comment]
The integration method radauIIA is third-order accurate. Unfortunately, the embedded RK-scheme is first-order accurate. Therefore, the error estimation is first-order and the step size control is rather conservative, comparable with the implicit euler method. 

There is a work-around:
One can turn on the Richardson extrapolation method, which produces a fourth-order approximation. This ends up with a third-order error estimation and the step size control acts as expected.

`model RADAU
  extends ScalableTestSuite.Power.ConceptualPowerSystem.ScaledExperiments.PowerSystemStepLoad_N_2_M_4;
  annotation(uses(Modelica(version="4.0.0"), ScalableTestSuite(version = "2.2.0")),
             experiment(StopTime=200, Tolerance=1e-4, Interval = 0.05),
             __OpenModelica_simulationFlags(s = "gbode", gbm = "radauIIA2", gberr = "1", jacobian = "coloredSymbolical", lv = "LOG_STATS"));
end RADAU;`

Result:
`gbode (single-rate integration): radauIIA2
### STATISTICS ###
timer
events
solver: gbode
  229 steps taken
 7054 calls of functionODE
 1635 evaluations of jacobian
   45 error test failures
    0 convergence test failures
0s time of jacobian evaluation
The simulation finished successfully.`

**Comment by casella** [comment]
OK, the question is, how do we make this user-friendly. It's good to have a fully configurable solver for power users, but we can't expect "normal" users (who do not have a PhD in numerical analysis) to be aware of all the details of the implementation of the algorithm in order to get decent performance. 

I wonder if we should pick a few combinations that are useful for certain classes of models and give them a unique name, then leave "gbode" to advanced users that know how to set up all the extra flags.

Another possibility (which is not necessarily mutually exclusive with the previous one) is that each gbode method could have method-specific settings; for example, the default gberr should be "1", not "0" for gbm=radauIIA2.

What do you think?

**Comment by bernhardbachmann** [comment]
That is also my opinion. We should have default settings for each integration method. Even the dense output is not yet default, if available. Maybe, this should be collected in a new ticket/discussion.

**Comment by casella** [comment]
Will do ASAP
