### ISSUE TITLE
OMSens Sensitivity Optimization Tool Error: Doesn't run under any configuration

### ISSUE THREAD

**Issue by DiscoWolf99** [OpenModelica/OpenModelica#10308]
### Issue Moved to OMSens Repo
https://github.com/OpenModelica/OMSens/issues/25#issue-1609043411

### Description
Cannot run any Sensitivity Optimizations. Error is quite long. See attached image.
Fresh install of OM 1.20. Windows 10. Python path points to OM install folders ../Modelica/tools/msys/mingw64/bin/python.exe (default)
Most of the errors seem to point to python scripts within the OMSens folder. 
I have attempted installing and running a different Python; provides a different error (probably because the default path is what I should be using)
Nonetheless, I would really like to know how I can get Sensitivity analysis to run. 

The issue is model independent. I observed it on both custom models/packages and also built in models such as the PID controller example. 

### Steps to reproduce
Given all the defaults and the fresh install, I really cant say. I open 

### Expected behavior
I assume it to behave like the example documentation shows. I really don't know because I have never got it to run. (I am a new user)

### Screenshots
<img width="1916" alt="OMSens_error" src="https://user-images.githubusercontent.com/126837733/222609406-e1b33e14-475b-4b6e-9d4f-bc0fa433268a.PNG">
<img width="1923" alt="OMSens_error2" src="https://user-images.githubusercontent.com/126837733/222610623-de445146-1968-49f3-a6b9-30bf4cd802e9.PNG">

Image 1 and 2 differ by some Sensitivity Analysis parameter/variable selections

### Version and OS
 - OpenModelica Version 1.20 64bit (installed via stable build .exe on official website)
 - OS: [e.g. Windows 10, 64 bit]
 - Installed mode CurrentUser
 - tested install with Admin and without.

### Additional context
I haven't been able to find any further information about this particular error. Maybe my search terms are not getting traction. 
This is the first major issue I have run into with OM. And since it is only occuring with OMSens, I think the issue is localized there and among the python scripts, etc. 

I have a feeling that maybe the Python.exe in OM install needs to be added to PATH?

Any thoughts on this, Void?

**Comment by DiscoWolf99** [comment]
<img width="1914" alt="OMSens_error_docs" src="https://user-images.githubusercontent.com/126837733/222612975-3e2ea1e4-2084-4052-8adb-c88a93d67b10.PNG">

And here are the more detailed errors for the first image in the OG post

**Comment by casella** [comment]
@DiscoWolf99, could be because of OpenModelica/OMSens#13. We need to work on that. In any case, please open a ticket on the [OMSens issue tracker](https://github.com/OpenModelica/OMSens/issues).

**Comment by DiscoWolf99** [comment]
Thank you for the quick response! Moving this post to OMSens issue tracker

**Comment by AnHeuermann** [comment]
Continued in https://github.com/OpenModelica/OMSens/issues/25
