### ISSUE TITLE
BackendDAECreate.lowerVar failed

### ISSUE THREAD

**Issue by Rajanrudani96** [OpenModelica/OpenModelica#10337]
### Description

BackendDAECreate.lowerVar failed for connector Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_b Real T; flow Real Q_flow; end Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_b; pS_PassiveSystem.controlBus.heat_lowerleftarm "virtual variable in expandable connector";

**Comment by casella** [comment]
@Rajanrudani96 can you please provide a bit more information? If you are trying to compile a connector by itself, of course it doesn't make sense because the model is incomplete, so the compiler fails. Otherwise, if you have a test model, please post it.

**Comment by AnHeuermann** [comment]
Closing this, because no information is provided on how to reproduce the issue.
