### ISSUE TITLE
ScalableTestGrids_N_4_M_4 no longer initializes successfully

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10347]
Model [ScalableTestGrids.Models.Type1_N_4_M_4](https://libraries.openmodelica.org/branches/v1.20/ScalableTestGrids_noopt/files/ScalableTestGrids_noopt_ScalableTestGrids.Models.Type1_N_4_M_4.sim) used to work in version 1.20. Then, something got wrong somewhere and now the model fails at initialization.

@mahge, would you mind running the script in [#7917](https://github.com/OpenModelica/OpenModelica/issues/7917#issuecomment-924895206) and see where this happened? Then, we can try to fix it for 1.21.0.

Thanks!

**Comment by mahge** [comment]
https://libraries.openmodelica.org/branches/history/master/2023-03-02%2022:43:15..2023-03-04%2000:08:48.html

However, I am not sure which commit is to blame. The model is supposed to use kinsol so maybe 9dd29eec7f? I am checking.

**Comment by casella** [comment]
The version on [master](https://libraries.openmodelica.org/branches/master/ScalableTestGrids_noopt/files/ScalableTestGrids_noopt_ScalableTestGrids.Models.Type1_N_4_M_4.sim) now also runs successfully again. Thanks @bernhardbachmann for the quick fix!
