### ISSUE TITLE
Old OMC API call only correct with instance based API

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10365]
### Description

During BRSL development we noticed a peculiar new issue with OMEdit nightlies from this week regarding the API call _getInheritedClasses_. For the component _Rexroth_Generic.Hydraulics.Cylinders.DoubleRodCylinder_ this API call only works correct if the new instance based API is enabled. 

### Steps to Reproduce

1. Open OMEdit with the new instance based API. 
2. Double click _Rexroth_Generic.Hydraulics.Cylinders.DoubleRodCylinder_. No errors appear in the log.
3. Call _getInheritedClasses_ in the CLI. The result _Rexroth_Generic.Hydraulics.Cylinders.SingleRodCylinder_ is correct.
4. Open OMEdit with the old API. 
5. Double click _Rexroth_Generic.Hydraulics.Cylinders.DoubleRodCylinder_. The following error appears in the log:
_[Rexroth_Generic.Hydraulics.Cylinders.DoubleRodCylinder: 13:3-13:153]: [extends Rexroth_Generic.Hydraulics.Cylinders.SingleRodCylinder causes an instantiation loop.]_
6. Call _getInheritedClasses_ in the CLI. The result _Rexroth_Generic.Hydraulics.Cylinders.DoubleRodCylinder.SingleRodCylinder_ is wrong.

### Expected Behavior

The model should be opened without errors in the old API. The old API call _getInheritedClasses_ should still work when opening the OMedit with the old API.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-325-g80a6d30bb4 (64-bit)
 - OS: Windows 10, 64 bit
 - Modelica 4.0.0, BRSL2.2.1

Thanks for looking into it
Aaron Buntrock - Bosch Rexroth

**Comment by perost** [comment]
I can replicate the issue, and I assume it has something with #10275 to do. But I can't replicate it by just calling `getInheritedClasses` in a script, there must be some other call that causes the environment to be messed up somehow.

**Comment by abuntrock** [comment]
Thanks for looking into it. To clarify: I called getInheritedClasses from the OpenModelica CLI supplied with the OMEdit under the Tools tab. Do you have sufficient information to look into this, or do you need more information from our side?

**Comment by perost** [comment]
> Thanks for looking into it. To clarify: I called getInheritedClasses from the OpenModelica CLI supplied with the OMEdit under the Tools tab. Do you have sufficient information to look into this, or do you need more information from our side?

It's fine, since I can replicate the issue myself I don't need anything more from you.

**Comment by perost** [comment]
The issue should be fixed in #10372. Unfortunately I wasn't able to make a test case for it since I don't know what actually triggers the issue.

**Comment by abuntrock** [comment]
It works as expected for me again as well with today's nightly build. Thanks a lot.
