### ISSUE TITLE
GBODE solver gets into event chattering

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10387]
There are several model in the MSL that fail with gbode because of event chattering:
- https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SynchronousMachines.SMEE_Rectifier.sim
- https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Electrical.PowerConverters.Examples.ACAC.Dimmer_RL.sim
- https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SynchronousMachines.SMPM_Braking.sim
- https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot.sim

The corresponding simulations using dassl are successful. This probably highlights some issues with event handling.

**Comment by bernhardbachmann** [comment]
WIth the current master, chattering is gone for:
Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SynchronousMachines.SMEE_Rectifier
Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SynchronousMachines.SMPM_Braking

**Comment by casella** [comment]
Good! I guess you refer to master on your PC.

Let's wait until the [new test report](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html) is out, then we can close this ticket as well.

**Comment by casella** [comment]
Works fine now.
