### ISSUE TITLE
GBODE solver sometimes fails by generating NaNs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10381]
The number of successful simulation models in MSL 4.0.0 [using gbode](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html) is about 40 less than [using dassl](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html). 

Several models are failing in the same way. Take, e.g., [Modelica.Clocked.Examples.SimpleControlledDrive.ClockedWithDiscreteTextbookController](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Clocked.Examples.SimpleControlledDrive.ClockedWithDiscreteTextbookController.sim) or [Modelica.Electrical.Analog.Examples.SwitchWithArc](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Electrical.Analog.Examples.SwitchWithArc.sim), they all fail with
```
assert            | debug   | division leads to inf or nan at time 0, (a=-nan) / (b=1), where divisor b is: if switch2.off then switch1.Goff else 1.0
```
Not sure where the NaN comes from, but the same models work fine on master. We should investigate where the NaN comes from in these cases.

**Comment by bernhardbachmann** [comment]
This has been most probably been fixed with #10370. At least, I could simulate the above mentioned models with the current master.

**Comment by casella** [comment]
Excellent, we are making very good progress these last two weeks. Let's see the next [report](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html).

**Comment by casella** [comment]
Very good results, looking at MSL 4.0.0 results now we have [497/512 success ratio](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html) with gbode vs [504/514 success ratio](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) with dassl. 

In fact, gbode is performing better than cvode, which stands at [486/514](https://libraries.openmodelica.org/branches/cvode/Modelica_4.0.0/Modelica_4.0.0.html). Maybe we should have a closer look at that as well.
