### ISSUE TITLE
Symbolic Jacobian generation unecessarily fails in PowerGrids model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10392]
Symbolic jacobians in daeMode are proven to work successfully for power grid simulations using daeMode, see e.g. the results of the ScalableTestGrids_noopt job, where the models set the `--daeMode` flag in the annotations, and the `--generateSymbolicJacobian` flag is set by the CI script.

However, there is still something going wrong with `--daeMode` and `--generateSymbolicJacobian` as demonstrated by the IEEE14bus examples in the [PowerGrids symbolic jacobian test report](https://libraries.openmodelica.org/branches/master/PowerGrids_symb_jac/PowerGrids_symb_jac.html). These models used to work fine since 2019, but are now broken in the testsuite because we added `--generateSymbolicJacobian` to the testing setup.

The Differentiate module of the old backend [fails](https://libraries.openmodelica.org/branches/master/PowerGrids_symb_jac/files/PowerGrids_symb_jac_PowerGrids.Examples.IEEE14bus.IEEE14busGen2Disconnection.err) with:
```
[/var/lib/jenkins/ws/OpenModelicaLibraryTestingWork/OpenModelica/OMCompiler/Compiler/BackEnd/Differentiate.mo:267:5-267:157:writable] Error: Derivative of expression "algorithm
  GEN1.AVR.limiterWithLag.satON := pre(GEN1.AVR.limiterWithLag.satON);
  $whenCondition16 := pre($whenCondition16);
  $whenCondition15 := pre($whenCondition15);
...
  if not GEN1.AVR.limiterWithLag.useLag then
    GEN1.AVR.limiterWithLag.satON := true;
  end if;
" w.r.t. "dummyVarA" is non-existent.
Error: Internal error SymbolicJacobian.deriveAll failed
```
I understand this is another case of the issue discussed in #9690, #8658, and elsewhere, that have not yet been properly addressed.

The bottom line is:
- it is OK to differentiate discontinuous equations for the sake of generating symbolic jacobians of the RHS of ODEs (or DAEs in daeMode); these jacobians will be used during continuous-time simulation - discontinuities will be managed by event handling
- the above case is already handled by numerical differentiation (the cited PowerGrids model work just fine if `--generateSymbolicJacobian` is removed) so there is no reason to abort the symbolic differentiation when discrete variables are involved. The derivative of a discrete variable outside events is zero; event handling takes care of the discontinuity
- it is not OK to differentiate discontinuous equations when index reduction is involved, because this makes the solution invalid across discontinuities. In this case it is OK to fail the differentiation procedure. An even better solution would be to still go ahead with it, but generate an assertion that aborts the simulation when the event is triggered.

**Comment by casella** [comment]
I summarized the issue in this MWE package:
```modelica
package DiscontinuousDifferentiation
  model M1 "This model should work"
    Real x(start = 0, fixed = true);
    discrete Real w(start = 0, fixed = true);
  equation
    der(x) = -w*(x + 1);
    when sample(0, 1) then
      w = pre(w) + 1;
    end when;
    annotation(
      experiment(StartTime = 0, StopTime = 4, Tolerance = 1e-06, Interval = 0.008),
      __OpenModelica_commandLineOptions = "--daeMode --generateSymbolicJacobian");
  end M1;
  
  model M2 "This model should work"
    Real x(start = 0, fixed = true);
    discrete Real w(start = 0, fixed = true);
  equation
    der(x) = -w*(x + 1);
  algorithm
    when sample(0, 1) then
      w := w + 1;
    end when;
    annotation(
      experiment(StartTime = 0, StopTime = 4, Tolerance = 1e-06, Interval = 0.008),
      __OpenModelica_commandLineOptions = "--generateSymbolicJacobian");
  end M2;
  
  model M3 "This model should fail"
    Real x(stateSelect = StateSelect.never);
    Real y(stateSelect = StateSelect.always);
  equation 
    der(x) = 1;
    y = mod(x,0.5);
  annotation(
      experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-06, Interval = 0.008),
      __OpenModelica_commandLineOptions = "--generateSymbolicJacobian");
  end M3;
  
  model M4 "This model should fail"
    Real x(stateSelect = StateSelect.never);
    Real y(stateSelect = StateSelect.always);
  equation 
    der(x) = 1;
    y = if x > 0.5 then 2*x else x;
  annotation(
      experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-06, Interval = 0.008),
      __OpenModelica_commandLineOptions = "--generateSymbolicJacobian");
  end M4;
end DiscontinuousDifferentiation;
```
In fact, these MWEs work as expected, even though M4 fails because of event iterations rather than complaining of index reduction involving a discontinuous equation. Not sure why [PowerGrids.Examples.IEEE14bus.IEEE14busGen2Disconnection](https://libraries.openmodelica.org/branches/master/PowerGrids/files/PowerGrids_PowerGrids.Examples.IEEE14bus.IEEE14busGen2Disconnection.err) fails instead, maybe the structure of the equations is a bit more convoluted there, and not captured by the very simplistic MWEs.

**Comment by casella** [comment]
I have updated the test configuration to split enemies. After it will have run, we should get two reports
- [PowerGrids](https://libraries.openmodelica.org/branches/master/PowerGrids/PowerGrids.html) using the default settings
- [PowerGrids_symb_jac](https://libraries.openmodelica.org/branches/master/PowerGrids_symb_jac/PowerGrids_symb_jac.html) using `--generateSymbolicJacobian`

**Comment by phannebohm** [comment]
Thanks for the MWEs. I'm on it. :+1:
