### ISSUE TITLE
Build OM error 

### ISSUE THREAD

**Issue by lijunliangTG** [OpenModelica/OpenModelica#10390]
### Description
When I use this command `make -j 6  install -Oline`  I meet the error   
make: *** [Makefile:171: all] Error 2

 Version and OS
 - OS: Windows 10, 64 bit

Here are the comman line output
[comman line output.txt](https://github.com/OpenModelica/OpenModelica/files/10949869/comman.line.output.txt)

**Comment by mahge** [comment]
Discussion already started in https://github.com/OpenModelica/OpenModelica/discussions/10374. Please continue there inorder to have everything in one place.
