### ISSUE TITLE
Final modifier for parameter dialog of redeclared classes

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10394]
### Description

Thanks to #10375 we are now able to see the parameter dialogue of redeclared classes via the new edit button. We are aware that setting modifiers in the parameter dialogue of the redeclared class does not work yet (#10349). During testing we encountered another issue. Since we where not sure if @adeas31 included the issue in his list of things that need be fixed in #7826, we open this ticket.
It seems that final modifiers in the replaceable component declaration are not propagated correctly to the parameter dialogue of the redeclared class.

### Steps to Reproduce

1. Load the BRSL 2.2.1.
2. Open a new Modelica class.
3. Instantiate `Rexroth_Generic.BRSL_World` and then `Rexroth_Valves.ProportionalValves.Rexroth_2WRCE_4X`.
4. Open the parameter dialogue of the valve and open the parameter dialogue of the replaceable component `valve` with the new edit button.
5. All the parameters modified with final in the replaceable component declaration shown below should neither be editable nor shown in the parameter dialogue of the redeclared class but they are.
```modelica
replaceable Rexroth_Valves.Internal.Database.DB_22.Rexroth_2WRCE32S1K1L_4X_H valve(
final internalUsage = false,
final InputRange = InputRange,
final fluidIndex = fluidIndex,
final spoolPosStart = spoolPosStart,
final showName = showName,
final showParameters = showParameters,
final showPortDescription = showPortDescription)
```

### Expected Behavior

A `final` modifier in the replaceable component declaration removes the parameter from the parameter dialogue of the redeclared class. 
The modification of parameters in the replaceable component declaration already works as expected. If I change `final fluidIndex = fluidIndex,` to `fluidIndex = 2,`, fluidIndex equals 2 in the parameter dialogue of all redeclared classes, which is great.

### Version and OS

 - OpenModelica Version: 1.21.0-dev-342-gcfdfe6e76e (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0, BRSL2.2.1
 
Thanks for looking into this.
Aaron Buntrock - Bosch rexroth

**Comment by casella** [comment]
@abuntrock, if you click the Instantiate Model button in the toolbar (two buttons to the right of Check model), you get the flat model output. Look, e.g., for the declaration of parameter `valve.internalUsage`. Does it have the `final` prefix? If so, then it's a GUI issue, otherwise it is a frontend issue.

**Comment by abuntrock** [comment]
The flat model output includes the following:
`final constant Boolean rexroth_2WRCE_4X_1.valve.internalUsage = false "Parameter for internal components icon and warning";`
So it should be a GUI issue.
Thanks for clarifying this @casella. Next time I will look at the flat model directly to provide a clearer picture from the start.

**Comment by adeas31** [comment]
This is actually same as #10349

**Comment by abuntrock** [comment]
Thanks for clarifiying. I wasn't sure if the root cause was the same

**Comment by casella** [comment]
BTW, if it is a constant it shouldn't show up in the parameter dialog, regardless.

**Comment by abuntrock** [comment]
That is already working correctly. I posted the wrong example here, sorry for the confusion. But I checked with all other (actual) parameters and they are listed as final in the flattened model as well.

**Comment by casella** [comment]
OK, then it's a GUI issue.

**Comment by casella** [comment]
@abuntrock #10349 has been fixed now, so this issue should be resolved. Please double-check and reopen if necessary.

**Comment by niklwors** [comment]
The problem has not been solved yet.

**Comment by casella** [comment]
@niklwors @abuntrock please double-check with tomorrow's nightly.

**Comment by abuntrock** [comment]
@casella I checked it with today's nightly. It works just as expected. Thanks a lot
