### ISSUE TITLE
Bad allocation exception in OMEDit with the new API

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10421]
### Description
When selecting and instantiating a large model in OMEdit library explorer, a std::bad_alloc exception is shown in the output window after a longer loading time. E.g. for the model ```Rexroth_BRSL_Test.Rexroth_MobileControls_Test.ControlBlocks.RCS35.DynamicModels.RCS35_B_section_Dyn_TC01``` from our BRSL library

### Steps to Reproduce
Load the package ```Rexroth_BRSL\package.mo```
Load the package ```Rexroth_BRSL_Test\package.mo```
Double click the model ```Rexroth_BRSL_Test.Rexroth_MobileControls_Test.ControlBlocks.RCS35.DynamicModels.RCS35_B_section_Dyn_TC01```
After about one minute the error ```getModelInstance failed. std::bad_alloc```is shown in the output window.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-362-g41016710b7
 - OS: Windows 10, 64 bit
 - BRSL 2.3.0

**Comment by casella** [comment]
@niklwors could you zip the omeditcommunication.log you find in OMEdit's temporary directory and post it here? I guess it should contain useful information.

**Comment by casella** [comment]
> It works but omc is taking way too much memory ~20GB. 

I guess we need to investigate why that happens. There no justification for omc gobbling up that much memory on normal-sized models, as I believe all models from the BR library are.

**Comment by perost** [comment]
After #10440 the size of the JSON is greatly reduced, so this isn't an immediate issue anymore. The actual issue isn't solved though, so it could still happen with a large enough model. But I don't know of such a model, so fixing this is probably not so urgent anymore.

**Comment by casella** [comment]
I'll close this for the sake of DFD accounting. @adeas31 please open another one where you collect ideas to avoid this kind of issues with even larger models.
