### ISSUE TITLE
Too many warnigns for the same issue are displayed in the OMEdit output window.

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#10426]
### Description
For models of our BRSL Mobile Controls library too many warnings are displayed for the same problem in the OMEdit output window, so that the maximum output limit  is reached after a short time and the log file becomes very large. This makes it impossible to read other problems from the output window. E.g. for the model ```Rexroth_BRSL_Test.Rexroth_MobileControls_Test.ControlBlocks.RS12.RS12Q_TC01```  there are several thousand times this  output mesages:
```
Failed to solve linear system of equations (no. 9002) at time 0.000010. Residual norm is 0.0001220703125.
The default linear solver fails, the fallback solver with total pivoting is started at time 0.000010. That might raise performance issues, for more information use -lv LOG_LS.
Failed to solve linear system of equations (no. 9002) at time 0.000010. Residual norm is 0.0001220703125.
The default linear solver fails, the fallback solver with total pivoting is started at time 0.000010. That might raise performance issues, for more information use -lv LOG_LS.
```
### Steps to Reproduce
Load the package ```Rexroth_BRSL\package.mo```
Load the package ```Rexroth_BRSL_Test\package.mo```
e.g. simulate the model ```Rexroth_BRSL_Test.Rexroth_MobileControls_Test.ControlBlocks.RS12.RS12Q_TC01```

### Version and OS

 - OpenModelica Version: v1.21.0-dev-362-g41016710b7
 - OS: Windows 10, 64 bit
 - BRSL 2.3.0

**Comment by casella** [comment]
@niklwors what is the solution that you suggest?

**Comment by niklwors** [comment]
It would be good if the warning only showed once that for system 9002 the linear solver fails and not a thousand times. Otherwise you can't see other messages.

**Comment by casella** [comment]
We can think about it. However, this would require to keep a list of all messages that pop up, which could add some overhead.

Maybe we could just do it in OMEdit, not in the actual runtime. @adeas31 what do you think?

**Comment by ceraolo** [comment]
I don't know how OM deals with messages intenally, but in principle a list is noT needed.
To avoid the same row warning-writing code to re-write, at least with some code structures,  it should be sufficient to activate a flag around that row.

**Comment by bilderbuchi** [comment]
Putting emitted messages (or a hash of them to conserve space) into a unordered set/hashmap should be fast, and the lookup/membership check ("have we emitted that message before?") time complexity should be on average O(1), so I'd hope that the overhead should remain small.

**Comment by adeas31** [comment]
> Maybe we could just do it in OMEdit, not in the actual runtime. @adeas31 what do you think?

That would be an overkill. I think the runtime has all the information there is no need to implement something new in omEdit to handle this. With minimum effort we can fix this in the runtime.

**Comment by casella** [comment]
@AnHeuermann what do you think?

**Comment by AnHeuermann** [comment]
I'm not sure if we really want to disable these warnings. Is disabling `-w` an option for @niklwors?
It's quiet the difference if a linear system failed a few or a thousand times.

That said, we could easily add a counter on how many times each system failed and after some number stop printing that warning.
Changing this in e.g. in [linearSolverKlu.c#L314-L319
](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/linearSolverKlu.c#L314-L319) and in  [linearSystem.c#L670](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/linearSystem.c#L670) shouldn't be hard. Of course we need to add this for all linear and non-linear solvers.

I would suggest to add `numberOfFailures` to the struct

```C
typedef struct LINEAR_SYSTEM_DATA
{
  [...]
  /* statistics */
  unsigned long numberOfCall;          /* number of solving calls of this system */
  unsigned long numberOfJEval;         /* number of jacobian evaluations of this system */
  unsigned long numberOfFailures;      /* number of times solving calls of this system failed */
  double totalTime;                    /* save the totalTime */
  rtclock_t totalTimeClock;            /* time clock for the totalTime */
  double jacobianTime;                 /* save the time to calculate jacobians */
} LINEAR_SYSTEM_DATA;
```

add do something like

```C
if ((isnan(residualNorm)) || (residualNorm>1e-4)) {
  systemData->numberOfFailures++;
  if (systemData->numberOfFailures < 100) {
    warningStreamPrint(LOG_LS, 0,
        "Failed to solve linear system of equations (no. %d) at time %f. Residual norm is %.15g.",
        (int)systemData->equationIndex, data->localData[0]->timeValue, residualNorm);
  } else if (systemData->numberOfFailures == 100) {
    warningStreamPrint(LOG_LS, 0,
        "Failed to solve linear system of equations (no. %d) at time %f.\n"
        "Too many warnings, stop emitting warnings for this linear system.",
        (int)systemData->equationIndex, data->localData[0]->timeValue);
  }
  success = 0;
}
```

I don't have time to implement this at the moment, though.

**Comment by niklwors** [comment]
@AnHeuermann ````-w``` flag does not work here.

**Comment by adeas31** [comment]
This will still print the warning 100 times for each failed system. Can't we use a flag instead of counter so we only report the warning once?

**Comment by AnHeuermann** [comment]
> @AnHeuermann -w flag does not work here.

Oh sorry, it's the other way around: `-w` is already active. The default in OMEdit is to print all warnings, even if the specific log flag is not active. So by removing `-w` (its the tick in `Enable All Warnings` in Simulation Options in OMEdit) the warnings should disappear.

![grafik](https://user-images.githubusercontent.com/38031952/228235115-23d52962-6c73-403c-8b84-48ef4de11a0d.png)

**Comment by AnHeuermann** [comment]
> This will still print the warning 100 times for each failed system. Can't we use a flag instead of counter so we only report the warning once?

Sure. It can be any value you think is suitable, doesn't have to be `100`. So having it to be `1` will print it only once. And of course we can add a simulation flag to specify a value for it.

**Comment by niklwors** [comment]
> > @AnHeuermann -w flag does not work here.
> 
> Oh sorry, it's the other way around: `-w` is already active. The default in OMEdit is to print all warnings, even if the specific log flag is not active. So by removing `-w` (its the tick in `Enable All Warnings` in Simulation Options in OMEdit) the warnings should disappear.
> 
This does unfortunately also not help, the warning are still there

**Comment by niklwors** [comment]
The problem is then that you don't see any warnings anymore, which is not so good.

**Comment by niklwors** [comment]
> How important is this for you? I can add the changes we discussed in [#10426 (comment)](https://github.com/OpenModelica/OpenModelica/issues/10426#issuecomment-1486651356), but currently I don't have a lot of time to work on OpenModelica.

It does not have a high priority.

**Comment by AnHeuermann** [comment]
I updated the warning messages to stop displaying after reaching some limit. What is a good default value for that limit? 100 and make it changeable by the user with some simulation flag `-lv_warning_limit=10`?

<details>

<summary>Rexroth_BRSL_Test.Rexroth_MobileControls_Test.ControlBlocks.RS12.RS12Q_TC01.log</summary>


```
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9002) at time 0.000010. Residual norm is 0.0001220703125.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000010. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9002) at time 0.000010. Residual norm is 0.0001220703125.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000010. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9002) at time 0.000010. Residual norm is 0.0001220703125.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000010. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9598) at time 0.738610. Residual norm is 0.00012756884098053.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.738610. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 8864) at time 0.740654. Residual norm is 0.000102654099464417.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.740654. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9598) at time 0.741030. Residual norm is 0.000135129317641258.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.741030. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 8864) at time 0.742157. Residual norm is 0.00010344386100769.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.742157. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9598) at time 0.742532. Residual norm is 0.000105662271380424.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.742532. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_LS            | warning | Failed to solve linear system of equations (no. 8864) at time 0.743659. Residual norm is 0.000167123973369598.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.743659. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9439) at time 0.847856. Residual norm is 0.000125274062156677.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.847856. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9439) at time 0.848392. Residual norm is 0.000142529606819153.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.848392. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9439) at time 0.849464. Residual norm is 0.000124037265777588.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.849464. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9156) at time 0.888656. Residual norm is 0.000100078279501759.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.888656. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9156) at time 0.888656. Residual norm is 0.000100104793091306.
LOG_LS            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.888656. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9156) at time 0.898280. Residual norm is 0.000142792472615838.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.898280. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9711) at time 5.971000. Residual norm is 0.000130319887881758.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 5.971000. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9711) at time 5.971444. Residual norm is 0.000116795710462414.
LOG_LS            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 5.971444. That might raise performance issues, for more information use -lv LOG_LS.
LOG_LS            | warning | Failed to solve linear system of equations (no. 9711) at time 5.971533. Residual norm is 0.000122442873391915.
stdout            | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 5.971533. That might raise performance issues, for more information use -lv LOG_LS.
stdout            | info    | Too many warnings, reached display limit of 3 for this warning.
LOG_SUCCESS       | info    | The simulation finished successfully.
```
</details>

**Comment by bilderbuchi** [comment]
I would think 1, or maybe 5 would be a good limit. hHw much additional information/context do you get by seeing the same message being repeated 10 or 100 times?

**Comment by casella** [comment]
If it's really the same message, I guess three is enough.

**Comment by ceraolo** [comment]
When stopping outputting messages will something like "suppressing further warning messages of the same tipe..." will be issued?
I think it is important to know that more than just three instances of that message are internally generated

**Comment by casella** [comment]
> When stopping outputting messages will something like "suppressing further warning messages of the same tipe..." will be issued? I think it is important to know that more than just three instances of that message are internally generated

Absolutely!
