### ISSUE TITLE
Allow turning on solver logs for a single system only

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10455]
Modelica models often lead to implicit systems of equations, whose solution can fail. -lv flags such as LOG_LS, LOG_LS_V, LOG_NLS, LOG_NLS_V are currently the only means to look into the details of the solution process, to figure out what is going wrong. Of course, the toughest problems concern non-trivial systems with many equations and large implicit systems.

Most of the time such problems are found during initialization, so the corresponding log file is quite big, but the size is still manageable. However, if the problem takes place during simulation, turning on those flags can generate humongous log files, with multi-GB size. One can simulate until a certain time, then start a new simulation importing the initial conditions, this time with the flags turned on. However, this is quite clumsy and, most importantly, changes the solution process in a way that can cause the failure to occur at a different point in time. This is typically the case for failures due to poorly conditions systems, which tend to have a highly erratic neature.

Simulation failure errors notify the number of the system that fails. It should be possible to turn on logging for that system only, in order to get reasonably sized log files that only contain the relevant information.

I would suggest to add a flag `-lv_system=xxx` that only enables LOG_LS, LOG_LS_V, LOG_NLS, LOG_NLS_V for system number xxx. This should be very straightforward, and it would be very useful to me right now 😅

**Comment by AnHeuermann** [comment]
Did you try [`-lv-time`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-lv-time) to only log a small (but relevant) time intervall?

**Comment by casella** [comment]
No, I missed that, I'll try that out. Thanks!

**Comment by casella** [comment]
The description of the flag is a bit obscure. "Interval" should probably be "value", or alternatively "Value" should be "Interval". You still get hundreds of megabytes, but it's manageable. I think also having the system select feature would be nice, though it's not critical.

**Comment by casella** [comment]
Thanks @phannebohm, this is very useful for debugging. @matteodepascali, please take note.

One last thing, the flag [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-lv-system) reads:

> List of equation indices for which solver logs are shown

This is not very clear. Do you mean "Value is a comma-separated list of equation indices for which solver logs are shown"? If so, could you please update the documentation string? Thanks!

**Comment by casella** [comment]
Great, thanks!
