### ISSUE TITLE
Disable change of drop-down list items via scroll-wheel action in OMEdit

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#10458]
### Description

Currently one can very easily change the values in the options menus when scrolling down and up when the mouse accidentally catches the focus of an option field. that can be changed via drop-down choices.
This causes accidental changes that the user might not even be aware of

### Steps to Reproduce

In OMEdit, go to Tools -> Options. 
Using the scroll wheel of the mouse scroll down any of the option pages and whilst doing so move your mouse above one option field that has dropdown or integer values. Now the value got changed accidentally.

### Expected Behavior

Scrolling should only move the options page but not react on the option fields themselves.

**Comment by casella** [comment]
I agree, this happened to me a few times. You can always Cancel, though 😅

**Comment by dietmarw** [comment]
Unfortunately, it is not always obvious that one has changed a value accidentally.

**Comment by perost** [comment]
There doesn't seem to be an easy solution, it's a "feature" of Qt. There's some discussion about it on [KDE's bug tracker](https://bugs.kde.org/show_bug.cgi?id=399324).

Another issue with OMEdit in particular though is that every view in the options is the same size, so e.g. Options->Fill Style is still scrollable even though there's no need for it to be.

**Comment by adeas31** [comment]
> Another issue with OMEdit in particular though is that every view in the options is the same size, so e.g. Options->Fill Style is still scrollable even though there's no need for it to be.

This is how its suppose to be. Otherwise switching between different settings will change the size the dialog which will be vey annoying.

**Comment by perost** [comment]
> > > Another issue with OMEdit in particular though is that every view in the options is the same size, so e.g. Options->Fill Style is still scrollable even though there's no need for it to be.
> > 
> > 
> > This is how its suppose to be. Otherwise switching between different settings will change the size the dialog which will be vey annoying.
> 
> Is the size of the dialog really tied to the size of the scroll area? It doesn't seem like that, since the scroll area is larger than the dialog by default and OMEdit also remembers the size of the dialog if you change it.

To answer myself, the issue is that the QStackedWidget used for the pages has a fixed size and is put into a scroll area. It would probably be better if each page instead was a scroll area and the stacked widget just expanded to the available space. But it's probably not that easy, it rarely seems to be with Qt.

**Comment by adeas31** [comment]
> To answer myself, the issue is that the QStackedWidget used for the pages has a fixed size and is put into a scroll area. It would probably be better if each page instead was a scroll area and the stacked widget just expanded to the available space. But it's probably not that easy, it rarely seems to be with Qt.

I put each page into the scroll area instead of the stacked widget. So now you will only see scrollbars for the pages that actually require it.
