### ISSUE TITLE
Disabling stdout and assert log in simulation setup

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#10467]
### Description

In #10426 I wanted to disable all warnings as well as the `stdout` log in OMEdit.
I noticed, that the `Logging` section of the `Simulation Setup->Simulation Flags` doesn't show that `stdout` and `assert` are always active and you can't deactivate them by removing a tick (there is none, see attached screenshot).

I had to add `-lv=-stdout` to disable `stdout` log, but then got a warning, that `-lv` was specified twice:

```
stdout            | warning | Command line option 'lv' specified again. Value has been overriden from 'LOG_STATS' to '-stdout'. 
```

### Steps to Reproduce

Open any model in OMEdit and open  `Simulation Setup->Simulation Flags`.

### Expected Behavior

- Mark `stdout` and `assert` as active with a tick.
- When removing the ticks add simulation flags `-lv=-stdout` or `-lv=-assert`.

### Screenshots

![grafik](https://user-images.githubusercontent.com/38031952/228523812-1bd98243-a350-422b-a310-15096a49a2ed.png)

### Version and OS

 - OpenModelica Version: v1.21.0-dev-318-gd7cb3a8558 (64-bit)
 - OS: Windows 11

**Comment by casella** [comment]
@rfranke this does not affect the 1.21.0 release, right?

**Comment by rfranke** [comment]
Yes, hopefully only a short living nuisance in the 1.22 dev branch.

Btw. internally the C runtime uses the same syntax with `LOG_` prefix also for stdout and assert. Just the command line options have been changed to lower case and without prefix.
https://github.com/OpenModelica/OpenModelica/blob/92b6780f6a1e2c6395d739b33d93f0ba0e7a609c/OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp#L143-L151

The C++ runtime would understand `--log-settings all=error` to suppress anything but error messages.

**Comment by adeas31** [comment]
@AnHeuermann can you fix the stdout and assert logs to use the `LOG_` prefix like others?

**Comment by AnHeuermann** [comment]
You mean instead of `-lv=assert` using `-lv=LOG_ASSERT`?

**Comment by adeas31** [comment]
Yes

**Comment by AnHeuermann** [comment]
@rfranke the location in the C runtime where we check if we have `-` in front of the log flags: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp#L179-L183

I guess you can add something similar for the C++ runtimein OMCFactory.cpp (I think).

**Comment by rfranke** [comment]
The above commits and 8006f5b6e470a2898a402f4dfe71d30af59d59bf fix it. Thank you @AnHeuermann and @adeas31.
