### ISSUE TITLE
UniformNoise issue

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10475]
### Description
I don't know whether this is a known issue or not.
In this case uniformNoise in a submodel gives erroneous results.

### Steps to Reproduce
1. Open Test1.mo: [Test1.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11115858/Test1.mo.txt)
2. open and run M
3. plot ports[1].genRand.y and  ports[2].genRand.y  I expect the two signal to be different, and to have varied values (not just 0 and 1) while they are the same. See screenshots below.

### Expected Behavior
The two signals should be different and have vrious values.

### Screenshots
This is what I get from Dymola (it seems right)
![image](https://user-images.githubusercontent.com/7373030/228956224-0bb97a69-baa4-4047-8ae6-63855d9dbfe5.png)

 This is what I get from OM (they are identical patterns, and values are only 0's and 1's):
![image](https://user-images.githubusercontent.com/7373030/228956250-651d4926-64de-47cc-9940-d70c9a4e12f9.png)

### Version and OS

OM 1.20.0 Win 64 bit
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by bilderbuchi** [comment]
I think you inadvertantly plotted the _outputs_ of `toArrivals`, which are indeed boolean, so that is not a surprise.

What I _can_ reproduce is that the two random outputs are identical, although they should **not** be as per the docstring of `RandomNoise`:
![image](https://user-images.githubusercontent.com/327442/229039240-739f5f7e-6417-4669-a37b-c1be4589fbb1.png)
I see a TranslationWarning that might be connected?
> [1] 08:18:43 Translation Warning
[Modelica.Math.Random: 1057:5-1146:31]: [Pure function ‘Modelica.Math.Random.Utilities.initializeImpureRandom‘ contains a call to impure function ‘Modelica.Math.Random.Utilities.initializeImpureRandom.setInternalState‘.](omeditmessagesbrowser:///Modelica.Math.Random?lineNumber=1057)

**Comment by ceraolo** [comment]
> I think you inadvertantly plotted the _outputs_ of `toArrivals`, which are indeed boolean, so that is not a surprise.

Yesss!
In fact the original issue regarding the fact that the two patterns are equal (and shouldn't), then I stumbled into this mistake

**Comment by perost** [comment]
> I see a TranslationWarning that might be connected?
> 
> > [1] 08:18:43 Translation Warning
> > [Modelica.Math.Random: 1057:5-1146:31]: Pure function ‘Modelica.Math.Random.Utilities.initializeImpureRandom‘ contains a call to impure function ‘Modelica.Math.Random.Utilities.initializeImpureRandom.setInternalState‘.

Probably not, it's just that the MSL doesn't always follow the rules for impure functions ([reported here](https://github.com/modelica/ModelicaStandardLibrary/issues/3857). But I don't think that actually affects anything.

**Comment by casella** [comment]
The issue is demonstrated by this MWE:
```modelica
package TestRandom
  model Scalar
    Modelica.Blocks.Noise.UniformNoise gen1(samplePeriod = 0.1, y_min = 0, y_max = 1) annotation(
      Placement(transformation(origin = {56, 66}, extent = {{-92, -72}, {-72, -52}})));
    Modelica.Blocks.Noise.UniformNoise gen2(samplePeriod = 0.1, y_min = 0, y_max = 1) annotation(
      Placement(transformation(origin = {56, 30}, extent = {{-92, -72}, {-72, -52}})));
    inner Modelica.Blocks.Noise.GlobalSeed globalSeed(useAutomaticSeed = false)  annotation(
      Placement(transformation(origin = {50, -8}, extent = {{-10, -10}, {10, 10}})));
  end Scalar;
  
  model Array
    Modelica.Blocks.Noise.UniformNoise gen[2](each samplePeriod = 0.1, each y_min = 0, each y_max = 1)  annotation(
      Placement(transformation(origin = {56, 66}, extent = {{-92, -72}, {-72, -52}})));
  inner Modelica.Blocks.Noise.GlobalSeed globalSeed annotation(
      Placement(transformation(origin = {26, 0}, extent = {{-10, -10}, {10, 10}})));
  end Array;
annotation(
    uses(Modelica(version = "4.0.0")));
end TestRandom;
```
The `Scalar` model has two independent scalar instances of `UniformNoise`, and correctly produces two different random output, while the `Array` model has an array of `UniformNoise` models, which all produce the same output. I'll investigate more.

**Comment by casella** [comment]
The flattened Scalar model contains these initial equations:
```modelica
  gen1.localSeed = if gen1.useAutomaticLocalSeed then 1113895404 else gen1.fixedLocalSeed;
  gen2.localSeed = if gen2.useAutomaticLocalSeed then 1647889986 else gen2.fixedLocalSeed;
```
while the flattened Array model contains these ones:
```modelica
  gen[1].localSeed = if gen[1].useAutomaticLocalSeed then 1311208821 else gen[1].fixedLocalSeed;
  gen[2].localSeed = if gen[2].useAutomaticLocalSeed then 1311208821 else gen[2].fixedLocalSeed;
```
The source code is found in [Modelica.Blocks.Interfaces.PartialNoise](https://github.com/modelica/ModelicaStandardLibrary/blob/402662a9c90c1410209699237fbd0c286e61214c/Modelica/Blocks/Interfaces.mo#L1342):
```modelica
  localSeed = if useAutomaticLocalSeed then automaticLocalSeed(getInstanceName()) else fixedLocalSeed;
```
where `automaticLocalSeed()` is defined in [Modelica.Math.Random.Utilities](https://github.com/modelica/ModelicaStandardLibrary/blob/402662a9c90c1410209699237fbd0c286e61214c/Modelica/Math/Random.mo#L996) as:
```modelica
function automaticLocalSeed
  "Creates an automatic local seed from the instance name"
  extends Modelica.Icons.Function;
  input String path
    "Full path name of the instance (inquire with getInstanceName())";
  output Integer seed "Automatically generated seed";
algorithm
  // Generate a hash value from the instance name
  seed := Modelica.Utilities.Strings.hashString(path);
end automaticLocalSeed;
```
It seems there is something wrong with `getInstanceName()` returning the same string and hence the same seed.

**Comment by casella** [comment]
The root cause is discussed in #11600, once that is fixed this issue should be automatically resolved.

**Comment by casella** [comment]
@perost, see Modelica/ModelicaSpecification#3444

**Comment by casella** [comment]
Problem solved:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/80b67e33-3528-4d97-ad39-ecb4e6700232)
