### ISSUE TITLE
Displaying of string parameters in icon is not possible

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#10478]
### Description

If you have a base class for the icon with a string parameter that you want to display in the icon, it is not possible to overwrite this modifier with another string parameter when extending the class.

Also tried out with constants and different approaches but all without success. Imo that should be possible.

For non string parameters the approach described in the top and in the minimal example works as expected.

### Steps to Reproduce
Load this package and instancate both classes.
```

within ;
package TestIconExtend

  partial model MyBasicIconClass
    parameter String MyCostumString = "TobeShownInIcon";
    parameter Real nonString = 1;
  equation

 annotation (Icon(graphics={Rectangle(extent={{-98,98},{102,-98}}, lineColor={28,108,200}), Text(
            extent={{-72,32},{270,-20}},
            textColor={28,108,200},
            textString="%MyCostumString"),                                                     Text(
            extent={{-168,-38},{174,-90}},
            textColor={28,108,200},
            textString="%nonString")}));
  end MyBasicIconClass;

  model MyClass
    extends TestIconExtend.MyBasicIconClass(MyCostumString="TestStringmanuel");
  equation

  end MyClass;

  model MyClass2
    parameter String MyStringParameter = "Wont be shown in icon";
    extends TestIconExtend.MyBasicIconClass(MyCostumString=MyStringParameter,
                                            nonString = 2);
  equation

  end MyClass2;
end TestIconExtend;
```

### Version and OS

 - OpenModelica Version: 1.22 nightly from 30.03.2023
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
@adeas31 did you try it with the new instance-based API?

**Comment by sbaetzing** [comment]
We are aware that the tools all behave the same here, but we don't see any use case where the current behavior would make sense (for parameters of type Strings, it is different for Reals e.g.).
What added value has the simulator, if he knows that this string parameter was overwritten with another string parameter. He is interested in the final value or in this case string in our opinon. Maybe its more like an change request instead of a bug. Specification does not say much about that topic.

 
During testing we discovered another issue. It is not possible to show attributes from instanziated classes.

```
model test
MyClass myClass annotation(
    Placement(visible = true, transformation(origin = {-22, 12}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

annotation(
    Icon(graphics = {Text(origin = {-23, 2}, extent = {{-59, 24}, {59, -24}}, textString = "%{myClass.MyCostumString}")}));
end test;
```

Seems like new api is not able to handle the brackets correct.

**Comment by AustraleanPerson** [comment]
Dymola uses very simple approach:

- if you want to show value (can be expression) of parameter you should write **textString="%MyCostumString"** 
This is consistent with the specification:
 > %par and %{par} replaced by the value of the parameter par

- when you want to show evaluated value of parameter you can use **textString=MyCostumString**
no replacement take place in that case, so you should see the literal value of MyCostumString

Both methods are useful. OpenModelica does not support static expression evaluation for now.
