### ISSUE TITLE
Issues with statically linked libs in OMC created source-code FMUs

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#10485]
#### Background: 
In our lab we have a [dSPACE MicroAutoBox III](https://www.dspace.com/en/inc/home/products/hw/micautob/microautobox3.cfm) which supports the import of CS source code FMUs. Unfortunately, we had issues trying to get those FMUs to run even with the simplest models. We verified this by testing a Dymola exported FMU from the same simple model. At the same time, we could verify that both the OMC-created and the Dymola-created FMU could be compiled by FMPy without issues. This is where we contacted dSPACE support and provided the FMU in question based on the following Modelica code:

```mo
model SinSource
parameter Real amp=1 "Amplitude";
parameter Real freq=1 "Frequency";
Modelica.Blocks.Interfaces.RealOutput y; // annotation(...)
protected
Modelica.Blocks.Sources.Sine sine(amplitude = amp, f = freq); // annotation(...)
equation
  connect(sine.y, y); // annotation(..)
end SinSource;
```
from which OMC created the following source-code FMU:
[SinSource_OpenModelica.zip](https://github.com/OpenModelica/OpenModelica/files/11122380/SinSource_OpenModelica.zip) (rename zip to fmu after download).

#### Diagnoses by dSPACE's support team:
The dSPACE team did a thorough diagnosis and was so kind to allow me to share it here: 

> The problem with the OpenModelica FMU is based on the mode which we used
 > with ConfigurationDesk. The conflict with the error message one gets
 > when compiling the generated code deals with target hardware. The source
 > code FMUs we can deal with ConfigurationDesk and the SCALEXiO system is
 > based on creating statically linked compiler libraries. I assume that
 > the check with FMPy aims at dynamically linked FMUs. The OpenModelica
 > FMU does not assign respective macros, which enables a creation of
 > static compiler libs. Please find the contents which I refer to in the
 > FMU specification 2.0 in chapter 2.1.1, which explains this kind of use
 > case. Therefore, we recommend asking the 3rd party supplier for
 > OpenModelica how to configure the respective FMU to create a statically
 > linked lib.
 >
 > We know that the failed compiling is caused by undefined and unspecific
 > function call. This causes the Falling error message during the compile
 > process like
 >
 > SinSource_mdlfunctions.cpp:(.text+0xc): undefined reference to
 > `SinSource_fmi2FreeInstance'
 >
 > The prefix SinSource is essential and is missing in this FMU.

### Expected Behavior

The source-code FMU as exported by OMC should have the libraries linked statically in order that the FMU can be used with the dSPACE hardware. 

### Version and OS

 - OpenModelica Version: 1.21.0~dev-397-ga7cd739
 - OS: Windows and Linux

### Additional Context

n/a

**Comment by casella** [comment]
More very low-level issues to get FMUs going...

**Comment by Arinomo** [comment]
@dietmarw you could try to modified `SinSource_FMU.c` inside your FMU, add `#define FMI2_FUNCTION_PREFIX SinSource_` , save and update (repackage) the FMU. I've been using this work-around on my FMUs, maybe it will help you

**Comment by sjoelund** [comment]
> Used as prefix for FMI functions if the functions are provided in C source code or in static libraries, but not if the functions are provided by a DLL/SharedObject.

And that's the C source code we use to create a shared object. But it seems something was fixed for this in FMI 2.0.4:
> [New in FMI 2.0.4:] Using the standard-supplied version of “fmi2Functions.h”, the same effect can be achieved by defining the “FMI2_OVERRIDE_FUNCTION_PREFIX“ precompiler macro prior to the inclusion of the `fmi2Functions.h` header, for example using precompiler command-line flags.]

So we would need to update to the 2.0.4 headers and by default use FMI2_OVERRIDE_FUNCTION_PREFIX to compile shared objects...

**Comment by sjoelund** [comment]
I do believe you could just set -DFMI2_FUNCTION_PREFIX=SinSource in the compiler flags in the old FMU as a work-around.

**Comment by dietmarw** [comment]
@sjoelund Just to be clear I understand you correctly. Do you mean it should be set in "Additional Translation Flags" field (I need to rely on how to do this in OMEdit since that is also the use case here) when _generating_ the FMUor do you mean it needs to be set in where the FMU is then _compiled_? In my case dSPACE ConfigurationDesk (where I'm not sure I can do that).

**Comment by sjoelund** [comment]
It would have to be in dSPACE since there are no configuration flags or anything in an FMI2 source-code FMU...

**Comment by Arinomo** [comment]
@dietmarw you can set the macro when building the rta. Under  `Build -> Default Build Configuration Set -> Preprocessor -> Macros to be define`  and just put `FMI2_FUNCTION_PREFIX=SinSource_`

**Comment by AnHeuermann** [comment]
I'm not sure if I have understand section 2.1.1 Header Files and Naming of Functions of the FMI Standard 2.0.4.
If the FMU is shipped with a DLL/shared object we have to use

```C
// FMU is shipped with DLL/SharedObject
#include "fmi2Functions.h"
< usage of the FMU functions >
```

and if we ship the FMU with source code we should do

```C
// FMU is shipped with C source code, or with static link library
#define FMI2_FUNCTION_PREFIX SinSource_
#include "fmi2Functions.h"
< usage of the FMU functions >
```

I was not aware that static compiled FMUs are a thing.

We usually export dynamic FMU binaries (`.so`, `.dll`). I added a OpenModelica compiler flag to compile the FMU binaries into a static library (`.a`, `.lib`) and this defines `#define FMI2_FUNCTION_PREFIX SinSource_` as well.

Usage would look something like
```modelcia
setCommandLineOptions("--fmuCMakeBuild=true --fmiStaticExport=true --fmiFlags=s:cvode"); getErrorString();
buildModelFMU(SinSource, version="2.0", fmuType ="cs"); getErrorString();
```

With that the naming convention should be correct:
```
$ nm -C SinSource.a | grep "fmi2GetReal"
0000000000007d90 T SinSource_fmi2GetReal
```

Problem is, we don't have a tool to test static compiled FMUs in our CI. Otherwise it is easy to build static libraries.
Of course one needs to have `libsundials_cvode.a` for this to work. This is not true for (all?) installed versions of OpenModelica. But we could add it to the installations.

**Comment by dietmarw** [comment]
> @dietmarw you can set the macro when building the rta. Under `Build -> Default Build Configuration Set -> Preprocessor -> Macros to be define` and just put `FMI2_FUNCTION_PREFIX=SinSource_`

Today I could finally test this and it works, thanks @Arinomo. 
So this would then hopefully mean that   #10509 fixes this and one does not need to provide the flag anymore. One issue is that dSPACE's ConfigurationDesk builder does not like `.`  in file names (will report this also to dSPACE). It will simply fail then. So one has to either export models from top-level class or put a different name inside the FMI options (which has issues, see #10524).

**Comment by dietmarw** [comment]
We just tested this and creating an source-code FMU and trying to compile this with dSPACE's ConfigurationDesk one still has to define `FMI2_FUNCTION_PREFIX` in the build configuration. But that was the part that the PR should have taken care of right?

**Comment by AnHeuermann** [comment]
Are you using CMake to compile?
If you use some tool, e.g. dSPACE's ConfigurationDes, it needs to use our CMakeLists.txt. There are a lot of things happening in there, e.g. linking of libraries. So simply compiling all C files that are listed in the sources will not work.
Otherwise you have to provide `FMI2_FUNCTION_PREFIX` during your compilation process and do all the linking yourself.

**Comment by dietmarw** [comment]
So the issue here was originally about two things:
 1. source-code FMUs need to be statically linked
 2. the need to have `FMI2_FUNCTION_PREFIx` defined in addition.
I was under the impression that the objective was to fix both of those two things. So that FMUs generated by omc can be universally be used (just like the ones generated by other tools, e.g., Dymola, SimX).

**Comment by Arinomo** [comment]
> Does `FMI2_FUNCTION_PREFIX` need to be defined in the generated C _sources_ of the FMU, not (only) in the build configuration?
> 
> FMI 2.0.4 section 2.1.1 has this passage:
> 
> > An FMU C file must include at the beginning a #define of FMI2_FUNCTION_PREFIX as the `modelIdentifier` attribute defined in `<fmiModelDescription><ModelExchange>` or `<fmiModelDescription><CoSimulation>`together with _ at the end (see sections 3.3.1 and 4.3.1).

I think, it must be included in FNU C file. At least in this use case with dSPACE, if `modelA.fmu` and `modelB.fmu` are used, one should make sure that `FMI2_FUNCTION_PREFIX=modelA_` and `FMI2_FUNCTION_PREFIX=modelB_` are defined in `modelA.fmu/sources/modelA_FMU.c` and `modelB.fmu/sources/modelB_FMU.c` respectively. If so, this step:  

> @dietmarw you can set the macro when building the rta. Under `Build -> Default Build Configuration Set -> Preprocessor -> Macros to be define` and just put `FMI2_FUNCTION_PREFIX=SinSource_`

is not needed anymore. At least that is a workaround that worked for me when integrating FMUs from OM in dSPACE env.

**Comment by dietmarw** [comment]
Yes, I fear the solution of this issue was somewhat sidetracked by the whole cmake conversion which was probably not really related. As I said the FMU source-code needs to be statically linked (which is fixed as far as I can see) **AND** needs to define `FMI2_FUNCTION_PREFIX=<modelIdentifier>_`. So that this no longer needs to get defined in the build configuration. 

Current status with 872d6a98087d66482f67ea156c0d532f9b5a9e59 applied is that the FMUs can be compiled successfully as long as `FMI2_FUNCTION_PREFIX` specified in the build configuration. And that last part should not be necessary but should be already defined in the exported c-sources (as far as I understand).

**Comment by AnHeuermann** [comment]
I think we need to update our FMI2 header files to the 2.0.4 version, always add `FMI2_FUNCTION_PREFIX` to the C file and define `FMI2_OVERRIDE_FUNCTION_PREFIX` if we build non-source-code FMUs.

**Comment by bilderbuchi** [comment]
Regarding the build instructions part, i.e. the need to use CMake, https://github.com/OpenModelica/OpenModelica/issues/10485#issuecomment-1508135835, it might be sufficient to add a `documentation` directory with a short file containing a link to the CMakeLists.txt, and ideally the build instructions.

Section 2.3 says
> An exporting tool should give documentation on how to build an executable, either via a documentation file and/or via a template makefile for a particular platform, from which a user can construct the makefile for his/her target platform. This documentation should be stored in the “documentation” directory, possibly with a link to the template makefile (stored in the “sources” directory). [As template makefile, CMake (www.cmake.org), a cross-platform, open-source build system might be used.]

So it seems that FMU-using tools might be expected to be able to deal with the presence of a CMake file correctly (if pointed to in the `documentation` files?

**Comment by AnHeuermann** [comment]
> Alternatively, to reduce additional work when FMI3 support is being added, start using buildDescription.xml already, as that has been backported to 2.0.4?

Good idea. I opened https://github.com/OpenModelica/OpenModelica/issues/10548 for it.

**Comment by AnHeuermann** [comment]
@dietmarw can you try again with the next nightly build?
The Makefile and CmakeList.txt now contain `FMI2_OVERRIDE_FUNCTION_PREFIX`  and the C sources contain `FMI2_FUNCTION_PREFIX`. So now it should work without extra flags (I hope).

**Comment by dietmarw** [comment]
Thanks @AnHeuermann, I will check it on Monday when I'm back in the lab.

**Comment by dietmarw** [comment]
@AnHeuermann So we tested the FMUs and now one no longer needs to specify the `FMI2_FUNCTION_PREFIX` in dSPACE's ConfigurationDesk. It also works for CVODE now. :-)

**Comment by Arinomo** [comment]
@dietmarw OOT questions:
1) How do you define the stop time of an fmu, when integrating it in dSPACE env? by default OM set the stop time to 1 and it always stop my rta from running. Regardless  if i set the stop time to arbitary number, it always stop. Have you experience similar behaviour?
2) Have you work with "tunable parameter" in your fmu with dSPACE?

**Comment by dietmarw** [comment]
@Arinomo 
1. You can simply define the stop time in OMEdit and save the settings in the experiment annotations. That way you can also set the time to something ridiculously large.
2. What information we got from dSPACE, you would need to use ControlDesk for this. My student is currently investigating this.
