### ISSUE TITLE
OMEdit crashes during copy-paste of graphical component (and error report crashes too)

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#10481]
### Description

OMEdit crashes when copy-paste a graphical instance in the schematic model editor.

### Steps to Reproduce

Open Modelica Buildings Library, and open a model such as `FMUZoneAdapterZones1` (crash also happened with other models).
Select a component and then ctrl-copy followed by ctrl-paste.
This crashes OMEdit and brings up the window to send a report.
Sending the report also fails.

### Screenshots

![image](https://user-images.githubusercontent.com/1329080/229118182-3a8343c1-1c23-4c0c-a688-61821a4dc714.png)

**Comment by adeas31** [comment]
Seems same as #10442 
Try the latest build.

**Comment by mwetter** [comment]
That seems to be the same issue. If I am not mistaken this is not yet available in the latest nightly build on https://build.openmodelica.org/apt/dists/focal/nightly/binary-amd64/:
![image](https://user-images.githubusercontent.com/1329080/229128330-73802277-5e84-44eb-81ce-0b1828908ae4.png)

I can try next week if this is still in the build pipeline.

**Comment by casella** [comment]
@mwetter the fix to this problem (#10465) is actually already contained in the [1.21.0 beta release](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.21) branch. I'm not sure why you don't get it with the nightly. Did you check the output of `omc --version` to see which hash it corresponds to?

**Comment by casella** [comment]
Hmm. As you can see in the [commits page](https://github.com/OpenModelica/OpenModelica/commits/master), the commit of PR #10465 comes _after _ a7cd739, so of course it doesn't work.

Probably something was stuck in the APT toolchain. Now the latest [nightly/binary-amd64](https://build.openmodelica.org/apt/dists/focal/nightly/binary-amd64/Packages)is 1.22.0~dev-7-g9b17ddc-1, which corresponds to the first commit of Apr 3 and includes the required fix 😅

**Comment by casella** [comment]
@mwetter the fix to this problem (#10465) is actually already contained in the [1.21.0 beta release](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.21) branch. I'm not sure why you don't get it with the nightly. Did you check the output of `omc --version` to see which hash it has?

**Comment by mwetter** [comment]
I confirm that this is fixed in 
OpenModelica 1.22.0~dev-17-g88d7b96
and can be closed.
