### ISSUE TITLE
NB tests should report number of equations

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10480]
Tests performed on the CI report the number of equations before the start of backend, [e.g.](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_OB/files/ScalableTestSuite_OB_ScalableTestSuite.Electrical.DistributionSystemAC.ScaledExperiments.DistributionSystemLinearIndividual_N_10_M_10.err):
```
Notification: Model statistics after passing the front-end and creating the data structures used by the back-end:
 * Number of equations: 6556
 * Number of variables: 6556
```
Unfortunately, the NB [doesn't](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/files/ScalableTestSuite_NB_ScalableTestSuite.Electrical.DistributionSystemAC.ScaledExperiments.DistributionSystemLinearIndividual_N_10_M_10.err).

Please add that information in the NB as well. It would also be nice to get a final count of equations and initial equations after all backend optimizations.

**Comment by kabdelhak** [comment]
This is done now, the full `-d=backenddaeinfo,stateselection,discreteinfo` is available now. Everything about clocked variables is missing still since the new backend cannot handle them yet.

I changed the reporting to a (in my opinion) more compact dump. Feel free to reopen this ticket if anything does not work or you have suggestions on how to improve the provided information.

**Comment by casella** [comment]
OK, I guess it should be fine. I started a newInst-newBackend library testing job, and another LargeTest testing job, let's see what comes out of that.

Thanks!

**Comment by casella** [comment]
Hmm, there is still something not quite right in this feature. If I check successfully running models from [Modelica 4.0.0 testing](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/Modelica_4.0.0.html), there are many that report unmatching variable and equations count, e.g.:
- [Modelica.Blocks.Examples.BusUsage](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Blocks.Examples.BusUsage.err) 12 equations, 14 variables
- [Modelica.Blocks.Examples.CompareSincExpSine](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Blocks.Examples.CompareSincExpSine.err) 3 equations, 4 variables
- [Modelica.Blocks.Examples.Noise.Densities](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Blocks.Examples.Noise.Densities.err) 11 equations, 14 variables
- [Modelica.Electrical.Analog.Examples.OpAmps.Comparator](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Electrical.Analog.Examples.OpAmps.Comparator.err) 55 equations, 61 variables
- [Modelica.Thermal.FluidHeatFlow.Examples.IndirectCooling](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Thermal.FluidHeatFlow.Examples.IndirectCooling.err)

**Comment by kabdelhak** [comment]
Should be fixed with #11528 

i reported the equations/variables before creating binding equations, so those equations were missing in the count. I moved the report until after they are created and it works for all examples you gave.

Feel free to reopen if there are further issues with this.

**Comment by casella** [comment]
Thanks! I just triggered a new ScalableTestSuite job, so we can see the correct number of equations there.

**Comment by casella** [comment]
Checked this [regression report](https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/Modelica_4.0.0.html), NB equation counting seems fine to me now.
