### ISSUE TITLE
Variable was found in an enclosing scope but is not a constant translation error

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#10531]
Translation of a model with version 1.22 generates `[Modelica_Debug_testing: 90:5-90:98]: Component ‘density_ss304‘ was found in an enclosing scope but is not a constant.` error message.  

`Get:20 https://build.openmodelica.org/apt focal/nightly amd64 omedit amd64 1.22.0~dev-17-g88d7b96-1 [2971 kB]
`
### Steps to Reproduce

The error can be reproduced by simulating the InsulatedPipe model in this code.

```
package Modelica_Debug_testing
  record Cooler "Record containing cooler properties"
    extends Modelica.Icons.Record;
    Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
  end Cooler;

  model InsulatedPipe "Test of scope"
    type Density = Modelica.Units.SI.Density;
    Density pipe_wall_density = Cooler.density_ss304 "Density of the pipe wall material (kg/m^3)";
    Real x;
    equation
      x = pipe_wall_density - der(x);
  end InsulatedPipe;

end Modelica_Debug_testing;
```

### Expected Behavior

This sample code runs fine with OpenModelica version 1.18.1 on Windows 10 but fails with an error with version 1.22.

### Version and OS

I am running Ubuntu version 1.22.0 under Windows Subsystem for Linux (WSL)

`Get:20 https://build.openmodelica.org/apt focal/nightly amd64 omedit amd64 1.22.0~dev-17-g88d7b96-1 [2971 kB]
`

### Additional Context

Is this error a problem with version 1.22, does my code have an error that is only now being reported, or is there something else going on?  

Is there a straightforward way to fix this problem so that my code continues to run without density_ss304  being declared a constant in the record?

Thanks, Michael

**Comment by perost** [comment]
The error message is wrong, but the model is also invalid.

The reason why the model is invalid is because name lookup inside non-packages is restricted to encapsulated elements (which only classes can be), see [5.3.2](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup). So you're not allowed to access `Cooler.density_ss304` since `Cooler` isn't a package, and if it were then it wouldn't be allowed to contain a non-constant variable.

So I can check why that particular error is issued since it's not really the correct error message, but other than that I'm afraid you'll have to fix your model if you want to use newer version of OM or other Modelica tools.

**Comment by mjschuh** [comment]
@perost, Thank you for helping me understand that I need to change my model to use newer versions of OM and other Modelica tools.  I read the [5.3.2](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup) page and I did not find where it says that the records entries needed to be constant.  Perhaps that is what the '_[The package-restriction ensures that global name lookup of component references can only find global constants.]_' text is saying in section [5.3.3](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#global-name-lookup), but that is not clear to me.  Once I understood that I needed to change my model, I did find the error messages helpful because the messages told me which variables were involved and that they needed to be a constant.

Out of curiosity and wanting to better understand the history and future of OpenModelica, is there a reason that the newer versions have made what used to work no longer acceptable?

I changed over a 100 lines of code in my model and now my model runs with OM version 1.22.  Thanks again for the help and for replying so quickly.

**Comment by perost** [comment]
> @perost, Thank you for helping me understand that I need to change my model to use newer versions of OM and other Modelica tools. I read the [5.3.2](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup) page and I did not find where it says that the records entries needed to be constant. Perhaps that is what the '_[The package-restriction ensures that global name lookup of component references can only find global constants.]_' text is saying in section [5.3.3](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#global-name-lookup), but that is not clear to me. Once I understood that I needed to change my model, I did find the error messages helpful because the messages told me which variables were involved and that they needed to be a constant.

Record entries do not need to be constants, but entries in packages do. I was referring to the last point in 5.3.2 which states that lookup inside a class will find all elements if the class is a package, otherwise it's restricted to encapsulated elements. Since `Cooler` in this case is a record you're only allowed to look up encapsulated elements in it, and `density_ss304` can't be encapsulated since only classes can have that prefix.

There's also a now deprecated feature that classes that satisfy the requirements for a package (i.e. only contain constants and classes) are considered packages for this purpose, but that doesn't apply in this case since `density_ss304` isn't a constant.

> Out of curiosity and wanting to better understand the history and future of OpenModelica, is there a reason that the newer versions have made what used to work no longer acceptable?

We simply didn't check this restriction before, so we accidentally allowed it. In some cases it worked fine, but in other cases it could lead to some odd behaviour since it wasn't really meant to work. We try to be as standards compliant as we can and continuously improve our error checking, and although we try to avoid breaking user models if we can it's unfortunately unavoidable sometimes.

**Comment by mjschuh** [comment]
@perost Thank you for explaining more about what the issue was with using `record` and pointing out that a `package` has different restrictions.  I change my code to use `package` rather than `record` and it works without `density_ss304` being declared a `constant`.  Additionally, I am able to use `parameter` with `pipe_wall_density` in my model which will be helpful because I will be able to run with different values without having to recompile the model.  Is my usage of `package` supposed to work and should continue to work in the future?  If so, I will switch to using `package` rather than `record`.  This will work much better for me than using `constant` for the `record` entries.

```
package Modelica_Debug_testing

  package CoolerPackage
    extends Modelica.Icons.Package;
    Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
  end CoolerPackage;
  
  model InsulatedPipePackage "Test of scope"
    type Density = Modelica.Units.SI.Density;
    parameter Density pipe_wall_density = Cooler.density_ss304 "Density of the pipe wall material (kg/m^3)";
    Real x;
    equation
      x = pipe_wall_density - der(x);
  end InsulatedPipePackage;

end Modelica_Debug_testing;
```

Thank you again for all of the help.

**Comment by casella** [comment]
As a final note, we are aware that in some cases a stricter implementation of the Modelica standard will break formerly running models. However, we are strongly committed to supporting the standard. Otherwise, people would develop OpenModelica models (or Dymola models, or System Modeler's models, etc.) rather than Modelica models, and we'd end up with a chaos of multiply-incompatible dialects that hamper portability. That's not the idea of Modelica.

The whole point of a standard is to be strict, so you get actual portability, otherwise it's not really that useful. This comes with a cost, but I believe it is a cost worth paying.

**Comment by perost** [comment]
> 



> @perost Thank you for explaining more about what the issue was with using `record` and pointing out that a `package` has different restrictions. I change my code to use `package` rather than `record` and it works without `density_ss304` being declared a `constant`. Additionally, I am able to use `parameter` with `pipe_wall_density` in my model which will be helpful because I will be able to run with different values without having to recompile the model. Is my usage of `package` supposed to work and should continue to work in the future? If so, I will switch to using `package` rather than `record`. This will work much better for me than using `constant` for the `record` entries.
> 
> ```
> package Modelica_Debug_testing
> 
>   package CoolerPackage
>     extends Modelica.Icons.Package;
>     Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
>   end CoolerPackage;
>   
>   model InsulatedPipePackage "Test of scope"
>     type Density = Modelica.Units.SI.Density;
>     parameter Density pipe_wall_density = Cooler.density_ss304 "Density of the pipe wall material (kg/m^3)";
>     Real x;
>     equation
>       x = pipe_wall_density - der(x);
>   end InsulatedPipePackage;
> 
> end Modelica_Debug_testing;
> ```
> 
> Thank you again for all of the help.

That's odd, as I mentioned you're not allowed to have non-constants in packages. I suspect you might have made some mistake in your testing, because if I fix your example (the package is named `CoolerPackage` but you're still using `Cooler` in the model) then the compiler correctly gives an error message:
```
Error: Variable density_ss304 in package CoolerPackage is not constant.
```
I'm not sure why you'd want `density_ss304` to not be a constant, Modelica doesn't really allow accessing non-constants through classes since that would cause all sorts of issues.

**Comment by mjschuh** [comment]
Thanks @casella for the additional explanation.  I definitely agree that having all of the tools closely follow the standards is the best practice.  I want my models to run with any Modelica tool set.

@perost thank you for looking at my second code sample.  I messed up with the sample code I gave you above and missed changing `Cooler` to `CoolerPackage`.  Sorry about that.  I try really hard to give simple clear examples that work or fail as expected so as to not waste your valuable time.  I missed doing so above.  I am sorry about that.

You asked for the reasoning behind what I want to do.

Here is some code that shows what I would like to do.  For some reason, it works under v1.22 but I suspect that my model code is noncompliant and the compiler will eventually reject it.  I would like to be able to change `density_parameter` in my `InsulatedPipeVariableSimple` model at runtime without recompiling.  This will let me easily study the effect of changing one of the aspects of a particular cooler design without recompiling my code.  I am trying to fully define my coolers in `CoolerTypes` and then study what happens when I change one or more of these parameters.

 ```
package Modelica_Debug_testing
  package CoolerTypes "Cooler geometry and characteristics"
    extends Modelica.Icons.MaterialPropertiesPackage;

    record Cooler "Record containing cooler properties"
      extends Modelica.Icons.Record;
      String name = "Chamber name";
      Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
      Modelica.Units.SI.Length length = 2.0 "Length of the cooler (m)";
    end Cooler;

    record Deposition "Properties of deposition chamber"
      extends CoolerTypes.Cooler(name = "Deposition Chamber",
        length = 3.3);
    end Deposition;
  end CoolerTypes;

  model CoolerModel "Model of the cooler"
    CoolerTypes.Cooler cooler = CoolerTypes.Cooler();
    // There are equations for the cooler in my full system model
  end CoolerModel;
  
  model InsulatedPipeVariable "Test of scope"
    type Density = Modelica.Units.SI.Density;
    parameter Density density_parameter = 8000.0 "Density value that I would like to change at runtime";
    CoolerModel cm(cooler = CoolerTypes.Deposition(density_ss304 = density_parameter, name = "Variable density cooler")) "Works using v1.18 and v1.22";
    // If the next line of code is uncommented, I get the error message
    //     Component ‘density_ss304‘ was found in an enclosing scope but is not a constant.
    // Changing density_ss304 to be declared a constant in CoolerTypes.Cooler fixes this error message but breaks the "CoolerModel cm()" above.
    //parameter Density pipe_wall_density = CoolerTypes.Deposition.density_ss304 "Density of the pipe wall material (kg/m^3)";
    Real x;
    equation
      x = density_parameter - der(x);
  end InsulatedPipeVariable;
  
end Modelica_Debug_testing;

```

As I understand it, the record values in `CoolerTypes.Cooler` should all be `constant`.  Because of this, it seems like the code above should not work.  Am I missing something?

Thanks, Michael

**Comment by perost** [comment]
@mjschuh: That looks fine to me. Instead of accessing the record fields directly through `Cooler` you declare a component `cooler` and access them through that, which is how records are supposed to be used. It might potentially make sense to declare e.g. `density_ss304` to be a parameter instead if it's supposed to be constant during the simulation but you want to be able to change it without recompiling though.

**Comment by casella** [comment]
This was sometimes confusing to me when I started using Modelica: you can't access a record definition directly, but you can do it if you just instantiate it.

**Comment by mjschuh** [comment]
Thank you @perost and @casella very much for the help.  I was very surprised that @perost  said that what I had `looks fine to me`.  This was very helpful as was @casella's response.  I took a FORTRAN77 class in college a while back.  I have learned several languages including Modelica by reading books.  I still have a lot to learn about software engineering and appreciate it when people take the time to help me understand and fill in some of my knowledge gaps.

After rereading all of your posts some more, I thought about what I am trying to do and found a solution that works.  I show it below in case it might help someone else who finds this thread.  By adding a new `CDepMaterials` record with constant variables, I can use these variables in my models and in other records such as the `Cooler` record definition.  Using `CDepMaterials` is better than what I was doing before in my much larger cryogenic CO2 removal model because I am now only defining `density_ss304` in one place that is specifically for material properties rather than defining `density_ss304` in `Cooler` and other places.

Thank you again for all of the help.
```
package Modelica_Debug_testing

  record CDepMaterials "Properties for materials used in the CDep project"
    extends Modelica.Icons.Record;
    constant Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
  end CDepMaterials;

  package CoolerTypes "Cooler geometry and characteristics"
    extends Modelica.Icons.MaterialPropertiesPackage;

    record Cooler "Record containing cooler properties"
      extends Modelica.Icons.Record;
      parameter String name = "Chamber name";
      parameter Modelica.Units.SI.Density density_ss304 = CDepMaterials.density_ss304 "Density of Stainless Steel 304 (kg/m^3)";
      constant  Modelica.Units.SI.Density density_ss304_constant = 8025.0 "Density of Stainless Steel 304 (kg/m^3)";
      parameter Modelica.Units.SI.Length length = 2.0 "Length of the cooler (m)";
    end Cooler;

    record Deposition "Properties of deposition chamber"
      extends CoolerTypes.Cooler(name = "Deposition Chamber",
        length = 3.3);
    end Deposition;
  end CoolerTypes;

  model CoolerModel "Model of the cooler"
    CoolerTypes.Cooler cooler = CoolerTypes.Cooler();
    // There are equations for the cooler in my full system model
  end CoolerModel;

  model InsulatedPipeVariable "Test of scope"
    type Density = Modelica.Units.SI.Density;
    parameter Density density_parameter = 8000.0 "Density value that I would like to change at runtime";
    CoolerModel cm(cooler = CoolerTypes.Deposition(density_ss304 = density_parameter, name = "Variable density cooler")) "Works using v1.18 and v1.22";
    // Creating a parameter and directly using density_ss304 from CDepMaterials is straight forward
    parameter Density pipe_wall_density = CDepMaterials.density_ss304 "Density of the pipe wall material (kg/m^3)";
    // If defining a separate record like CDepMaterials is undesirable, a constant record variable can be
    // used to initialize a parameter variable by first instantiating an
    // instance of CoolerTypes.Deposition and then use its density_ss304_constant member
    parameter CoolerTypes.Cooler coolerMain = CoolerTypes.Deposition(density_ss304_constant = 8100.0, name = "Defined in main model");
    parameter Density pipe_wall_density_from_coolerMain = coolerMain.density_ss304_constant "Density of the pipe wall material (kg/m^3)";
    
    // The above usage of defining constants in CDepMaterials fixes my original problem.
    // My original problem came from trying to access a parameter value in CoolerTypes.Cooler.  The line below fails
    // in v1.22 and works in v1.18 of the OpenModelica translator.  It fails in v1.22 with the error message
    //   Component ‘density_ss304‘ was found in an enclosing scope but is not a constant.
    //parameter Density pipe_wall_density_from_prameter = CoolerTypes.Cooler.density_ss304;
    
    // Seeing that error message, I tried changing all of the CoolerTypes.Cooler entries to be constant and that caused
    // the CoolerTypes.Deposition density_ss304_constant argument to fail with the error message
    //   Function argument density_ss304_constant=density_parameter in call to
    //     Modelica_Debug_testing.CoolerTypes.Deposition has variability parameter which is not a constant expression.
    //CoolerModel cm2(cooler = CoolerTypes.Deposition(density_ss304_constant = density_parameter, name = "Variable density cooler"));
    
    Real x;
    equation
      x = density_parameter - der(x);
  end InsulatedPipeVariable;

end Modelica_Debug_testing;
```

**Comment by perost** [comment]
@mjschuh: Using `CDepMaterials.density_ss304` will work for now, but accessing constants in a non-package like that is as I mentioned deprecated. But from the code you've shown I can't really see any reason for why `CDepMaterials` needs to be a record rather than a package.

Another common design is to have a record and then a package with constant instances of that record in order to define multiple different materials. See for example `Modelica.Media.IdealGases.Common.SingleGasesData`.

**Comment by mjschuh** [comment]
@perost: Thank you for the additional feedback.  I changed `CDepMaterials` to a package from a record and my sample code runs find.  Good to know that using a package is the best way to do what I have been trying to do.  The code for `Modelica.Media.IdealGases.Common.SingleGasesData` shows this.  Thanks for the reference.

 ```
 package CDepMaterials "Properties for materials used in the CDep project"
    extends Modelica.Icons.Package;
    constant Modelica.Units.SI.Density density_ss304 = 8030.0 "Density of Stainless Steel 304 (kg/m^3)";
  end CDepMaterials;

```

**Comment by casella** [comment]
Nice, thanks @perost!
