### ISSUE TITLE
OMEdit Diagram View connector icon not displayed

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#10539]
### Description

In OMedit Diagram View the icons of connector classes are not shown correctly. It displays only a grey square with the name in it.
In the Icon view and the package browser on the left the correct blue square is displayed.

In Dymola and older versions of OpenModelica (tested v1.19.0) this is is displayed correctly.

### Steps to Reproduce

```modelica
package MWE
  connector Pin
    annotation(
        Icon(graphics = {Rectangle(lineColor = {0, 0, 255}, fillColor = {0, 0, 255}, fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}})}));
  end Pin;
  model M
    MWE.Pin p annotation(
      Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation
  end M;
end MWE;
```

![grafik](https://user-images.githubusercontent.com/38031952/231717746-8a582a13-973e-4f01-86be-636d6f2d6c9e.png)

### Expected Behavior

Display the same icon as in the icon view.

![grafik](https://user-images.githubusercontent.com/38031952/231723005-91e2147e-c58c-42b0-be22-3b0d116f6877.png)
(From OpenModelica v1.19.0)

### Version and OS

 - OpenModelica Version: v1.22.0-dev-16-g8afd6ca4f9 and OpenModelica v1.21.0-dev.beta.1
 - OS: Windows 11, 64bit

**Comment by casella** [comment]
Some tools used/use the Diagram extent annotation also for the Icon layer, if that was missing. But that's not what the specification says.

**Comment by adeas31** [comment]
> It looked different in older versions of OpenModelica and is handled different in Dymola.

Yes because we used the icon annotation if the diagram annotation is missing but now we are more specification compliant.
