### ISSUE TITLE
Mangled diagram in Buildings with new instance-based GUI because of conditional components

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10543]
### Steps to Reproduce

Open `Buildings.Fluid.Movers.FlowControlled_m_flow` in Buildings 9.1.0 with the instance-based API enabled. The diagram is broken on the upper part:

![immagine](https://user-images.githubusercontent.com/4233148/231888514-bebf44b9-8a73-4ff7-9fe0-17ffed08d045.png)

### Expected Behavior

The diagram should look like this (image taken with the old API interface active)
![immagine](https://user-images.githubusercontent.com/4233148/231887932-976b66d1-1bff-467c-9f90-f2d48c6cd33b.png)

### Version and OS

 - OpenModelica Version: v 1.22.0-dev-27-g2380f7ac32 (64-bit)
 - OS: Windows 10, 64 bit

**Comment by perost** [comment]
There are a few errors in the JSON that I will look into, but I'm not really seeing anything that would cause those elements to not be drawn. They're there in the JSON and have graphical annotations and everything. So this might be an OMEdit issue, or some mismatch between what OMEdit expects and the instance API gives.

**Comment by perost** [comment]
#10551 gets rid of the errors about components containing replaceable partial classes and incorrect uses of conditional components. It doesn't actually fix anything, just gets rid of some unnecessary noise.

**Comment by casella** [comment]
OK, then I'll pass this to @adeas31, at his earliest convenience.

**Comment by casella** [comment]
@adeas31 comments that in fact the shown diagram is ok, since the missing components are actually conditional ones that are disabled. Connections are shown anyway.

The question is, how should we handle this case?

**Comment by casella** [comment]
Proposal:
- disabled conditional components in _icon_ layers should not be displayed (-> conditional connectors)
- disabled conditional components in _diagram_layers maybe should be displayed as grayed out, so we know they're potentially there
- ditto for connection to/from these disabled components

**Comment by adeas31** [comment]
With #10559 we will get,

![image](https://user-images.githubusercontent.com/4007231/232494864-8d2dd831-123e-433d-b596-1085d2ccea66.png)

Notice that the greyed out components doesn't have any connectors. @perost we decided not to dump information of the conditional components but we might to change that now.

**Comment by casella** [comment]
Having greyed connectors would be better, but this is already much nicer than the previous result.

**Comment by casella** [comment]
I guess this is now good enough for the BR DFD.

**Comment by adeas31** [comment]
Closing this issue. Reopen if needed.
