### ISSUE TITLE
Add CMake 3.21 to build-deps Docker images

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#10556]
### Description

While working on https://github.com/OpenModelica/OpenModelica/pull/10542 I noticed that my draft PR https://github.com/OpenModelica/OpenModelica/pull/10542 is failing, because the CMake version is too old. PR https://github.com/OpenModelica/OpenModelica/pull/10353 will update the images, but the CMake version is still too old. I need at least 3.21 to add runtime dependencies to FMUs.

```bash
$ docker run --rm docker.openmodelica.org/build-deps:v1.21.1 cmake --version
cmake version 3.16.3
```

Should we add CMake 3.21 (or newer) to the build images?
Maybe with something like

```dockerfile
# Install cmake 3.21.7
RUN wget https://cmake.org/files/v3.21/cmake-3.21.7-linux-x86_64.sh
RUN mkdir -p /opt/cmake-3.21.7
RUN sh cmake-3.21.7-linux-x86_64.sh --prefix=/opt/cmake-3.21.7 --skip-license
ENV PATH="${PATH}:/opt/cmake-3.21.7/bin"
```

### Version and OS

 - OS: Test server infrastructure used by Jenkins

**Comment by bilderbuchi** [comment]
The current Ubuntu long-term-support release, 22.04, has cmake 3.22.1, so it might be an option to upgrade straight to there instead of to 20.04?

**Comment by AnHeuermann** [comment]
Conclusion from today's developers meting:

- We won't update the CMake version anytime soon. We need to support OS like el9 for a long time, where CMake is 3.20.2. See https://openmodelica.org/developersresources/devdocumentation/.
