### ISSUE TITLE
After filtering protected elements by default we should enable them back when -d=visxml is enabled

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#10579]
### Description

3D Visualization will need the protected elements from the shape classes to be able to animate the 3d objects.
After fixing #10578 and #10206 the protected elements will not be added to the .mat file by default so we need to enable them when compiling for visualization (-d=visxml). 
I guess we could do this in OMEdit automatically (if not already done so) but maybe is better to do it in omc, basically set `isProtected=false hideResult=false` for all variables when -d=visxml is on.

**Comment by casella** [comment]
According to [this comment](https://github.com/OpenModelica/OpenModelica/issues/10578#issuecomment-1515953009) by @perost, it seems that the NF already does that, i.e. it turns protected parameters to public. Do I get it right?

**Comment by adrpo** [comment]
This seems to already happen with NF, so we can close this ticket!
