### ISSUE TITLE
HideResult annotation doesn't work if the trigger parameter is not evaluated

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#10588]
The following MWE reproduces the issue:
```modelica
model HideResultTest
  parameter Boolean hide = true;
  Real x annotation(HideResult = hide);

equation
  x = time;

end HideResultTest;
```

If you run the model the following warning is shown:
```
[2] 10:44:11 Translation Warning
The hideResult annotation could not be evaluated, probably due to missing annotation(Evaluate=true). It is removed.
```
and the variable x is shown in the results tree, despite the annotation HideResult has the value = true.

In the Modelica Specification 3.5, §18.2 the annotation `Evaluate=true` is not mentioned as mandatory for the `HideResult`.

OpenModelica v1.21.0-dev-379-gd68dfe00aa (64-bit)
Sysop: Windows 11 Pro - 64 bit

**Comment by casella** [comment]
@AndreaBartolini did you try this with the new instance-based GUI?

**Comment by AndreaBartolini** [comment]
Yes, it doesn't work in the following nightly built with the Enable instance API selected:

OpenModelica v1.22.0-dev-88-g4a0f29c3c8 (64-bit)
Sysop: Win 11

**Comment by perost** [comment]
The [specification](https://specification.modelica.org/master/annotations.html#modelica:HideResult) defines the syntax for `HideResult` as:
```
 "HideResult" "=" ( false | true ) 
```
So non-literal values shouldn't really be allowed at all. But if this is something you really need we can of course discuss extending omc to allow it anyway. Regardless we should probably change that error message though, since it's not really correct either way.

**Comment by AndreaBartolini** [comment]
> So non-literal values shouldn't really be allowed at all

does it mean that I cannot use a parameter to set the HideResult property?

**Comment by perost** [comment]
> > So non-literal values shouldn't really be allowed at all
> 
> does it mean that I cannot use a parameter to set the HideResult property?

Yes, as the specification is currently written the value must be exactly `true` or `false`, and I've never seen anyone use anything else. But if you have a good use case for using a parameter you can always suggest a change [in the specificiation](https://github.com/modelica/ModelicaSpecification), and we can probably do a test implementation in OM.

**Comment by casella** [comment]
The use case is that we have models with some auxiliary variables, which are only computed if certain parameters are set, otherwise they are given a dummy value of zero. In this case, it is better to hide the result to avoid confusion. MWE:
```modelica
package TestHide
  model M
    parameter Boolean compute_phase;
    Complex z;
    Real phase annotation(HideResult = compute_z);
  equation
    z = Complex(1, time);
    if compute_phase then
      phase = Modelica.ComplexMath.arg(z);
    else
      phase = 0;
    end if;
  end M;
  
  model Test
    M m1(compute_phase = true);
    M m2(compute_phase = false);
  end Test;
end TestHide;
```
But I guess the best way to handle this is to use conditional components, such as in this MWE:
```modelica
package TestConditional
  model M
    parameter Boolean compute_phase;
    Complex z;
    Real phase = Modelica.ComplexMath.arg(z) if compute_phase;
  equation
    z = Complex(1, time);
  end M;
  
  model Test
    M m1(compute_phase = true);
    M m2(compute_phase = false);
  end Test;
end TestConditional;
```
@AndreaBartolini do you agree?

**Comment by AndreaBartolini** [comment]
I partially agree, the proposed second solution works only if the problem can be expressed in terms of binding equations, if the auxiliary variables are the solution of  an implicit non-trivial system (for example a trascendental equations system) the binding equations cannot be used.

**Comment by casella** [comment]
> I partially agree, the proposed second solution works only if the problem can be expressed in terms of binding equations, if the auxiliary variables are the solution of an implicit non-trivial system (for example a trascendental equations system) the binding equations cannot be used.

In that case, the nontrivial equation system could still be contained in a conditional component. "Parking" the variables with dummy variables is a bit of a hack, I prefer the idea of removing them outright when they are not needed.

In any case, the process of changing the Modelica Specification is non-trivial. If there is another way to handle our use case, I would not bother.

**Comment by AndreaBartolini** [comment]
> The [specification](https://specification.modelica.org/master/annotations.html#modelica:HideResult) defines the syntax for `HideResult` as:
> 
> ```
>  "HideResult" "=" ( false | true ) 
> ```
> 
> So non-literal values shouldn't really be allowed at all. But if this is something you really need we can of course discuss extending omc to allow it anyway. Regardless we should probably change that error message though, since it's not really correct either way.

Looking at Modelica specification §18.7 I saw that also the `enable` graphical annotation is defined as `(false|true)`, but it can be set by a boolean parameter.
It is a bit confusing... it seems that the same definition has different behavior. Maybe I'm wrong.

**Comment by perost** [comment]
> > The [specification](https://specification.modelica.org/master/annotations.html#modelica:HideResult) defines the syntax for `HideResult` as:
> > ```
> >  "HideResult" "=" ( false | true ) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So non-literal values shouldn't really be allowed at all. But if this is something you really need we can of course discuss extending omc to allow it anyway. Regardless we should probably change that error message though, since it's not really correct either way.
> 
> Looking at Modelica specification §18.7 I saw that also the `enable` graphical annotation is defined as `(false|true)`, but it can be set by a boolean parameter. It is a bit confusing... it seems that the same definition has different behavior. Maybe I'm wrong.

I can't find that `enable` is defined as `(false|true)`, only that it's defined as a `Boolean` in the `Dialog`-record with no further restrictions in the text. So any Boolean expression should be fine in that case.

**Comment by AndreaBartolini** [comment]
Ok, thanks, the syntax in the modelica spec is still a bit obscure for me....

**Comment by perost** [comment]
> Ok, thanks, the syntax in the modelica spec is still a bit obscure for me....

Yeah, the annotation chapter is quite inconsistent. Sometimes it defines annotations using lexical grammar, sometimes with Modelica code, and sometimes it doesn't define the type at all but just gives an example of how it's used.

**Comment by casella** [comment]
> I can't find that `enable` is defined as `(false|true)`, only that it's defined as a `Boolean` in the `Dialog`-record with no further restrictions in the text. So any Boolean expression should be fine in that case.

Exactly. It is set to true by default, but otherwise defined as a generic Boolean.

HideResult is defined instead in [Section 18.4](https://specification.modelica.org/maint/3.6/annotations.html#annotations-for-simulations) among simulation annotations, which are all expected to be literals (e.g., also StartTime, StopTime, etc.)

**Comment by casella** [comment]
> > I can't find that `enable` is defined as `(false|true)`, only that it's defined as a `Boolean` in the `Dialog`-record with no further restrictions in the text. So any Boolean expression should be fine in that case.
> 
> Exactly. It is set to true by default, but otherwise defined as a generic Boolean.
> 
> HideResult is defined instead in [Section 18.4](https://specification.modelica.org/maint/3.6/annotations.html#annotations-for-simulations) among simulation annotations, which are all expected to be literals (e.g., also StartTime, StopTime, etc.)

Not sure if this is by design or just happened to get written like that, though. Maybe we can open a ticket and start the discussion.
