### ISSUE TITLE
Wrong parameter variability lets whole diagram layer disappear

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10602]
### Description

Thanks to #10173 instantiating a class with an error does not let the whole diagram layer disappear anymore. However, I can trigger the same symptom with another kind of error in a current nightly: Assigning a value with the wrong variability to a parameter via the parameter dialogue. 

### Steps to Reproduce

1. Create a new modelica class
2. Instantiate any component  (in my example `Modelica.Blocks.Sources.Constant` from the MSL).
3. Instantiate any other component  (in my example `Modelica.Blocks.Sources.Constant` from the MSL again).
4. Assign a value to a parameter with the wrong variability. In my example `k=time` via the parameter dialogue.
5. Close the parameter dialogue. An error regarding the wrong variability occurs, which we very much like as a direct response to the user. However, both instantiated components disappear from the diagram layer. The text layer still has all the information though:

```modelica
model Test
  Modelica.Blocks.Sources.Constant const annotation(
    Placement(visible = true, transformation(origin = {-50, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Constant const1(k = time)  annotation(
    Placement(visible = true, transformation(origin = {10, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

annotation(uses(Modelica(version = "4.0.0")));
end Test;
```

### Expected Behavior

Nothing is removed from the diagram layer if there is an error in the parametrization.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-51-ge506fbc068 (64-bit) with instance based API
 - OS: Windows 10, 64 bit
 - MSL 4.0

Thanks for looking into this,
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
Ouch. @perost, do you think you can also relax that?
