### ISSUE TITLE
Unable to install openmodelica after linux update

### ISSUE THREAD

**Issue by vtnate** [OpenModelica/OpenModelica#10610]
### Description
Installing fails due to dependency conflict

### Steps to reproduce
1. Update Ubuntu 22.04 using the standard Software Updater
2. Follow installation instructions https://openmodelica.org/download/download-linux/
3. Meet dependency conflict when installing openmodelica
    - I'm using Arm64 and jammy
    - I get the same error no matter which version I attempt - release, stable, or nightly

### Expected behavior
Installation to work as explained in the installation docs

### Screenshots
Terminal output:

```
$ sudo apt install openmodelica
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libobjc-11-dev : Depends: gcc-11-base (= 11.3.0-1ubuntu1~22.04) but 11.3.0-1ubuntu1~22.04.1 is to be installed
                  Depends: libgcc-11-dev (= 11.3.0-1ubuntu1~22.04) but 11.3.0-1ubuntu1~22.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Version and OS
 - ~OpenModelica Version [run `omc --version` or check `Help->About OMEdit` from OMEdit]~
 - ~Versions of used Modelica libraries if applicable~
 - Host OS: MacOS 12.6.5
 - VM OS: Ubuntu 22.04
 - Processor: Apple M1 Max

### Additional context
The install used to work fine until I updated Ubuntu.

**Comment by casella** [comment]
@sjoelund any idea?

**Comment by vtnate** [comment]
I installed a new Linux VM, 22.04.2, and was then able to install openmodelica as expected again. Perhaps earlier I got caught part way through some update by dumb luck? Regardless, this is no longer a problem for me and I will close this issue this Friday if nobody else does it.

**Comment by sjoelund** [comment]
> @sjoelund any idea?

I guess it was just some broken upstream package resolved by the normal system upgrades

**Comment by casella** [comment]
I'll close it now, please reopen if necessary.
