### ISSUE TITLE
Wrong Parametric plot values 

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10634]
### Description
When doing a parametric plot in some common cases the numerical values displayed are badly wrong

- Run [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11358928/Test.mo.txt), and plot resisor power vs voltage
- look at the values hovering the cursor: they are one order of magnitude larger than expected.

### Screenshots
![image](https://user-images.githubusercontent.com/7373030/235298104-5f18b5ec-0fa4-4342-9683-20e8541756f1.png)
![image](https://user-images.githubusercontent.com/7373030/235297938-21b039b7-7f45-45ec-8a15-5baccef64a2a.png)

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by ceraolo** [comment]
I'll close it ffor now. Maybbe I'll reopen a few days later

**Comment by ceraolo** [comment]
Now I reopen this ticket. 
The issue is real.

**Comment by bilderbuchi** [comment]
Weird, this should have been fixed a while ago by @adeas31, see https://github.com/OpenModelica/OpenModelica/issues/9950#issuecomment-1404907900

**Comment by ceraolo** [comment]
Ok.
I found the issue with OM 1.20.0.
Now I checked with 1.22.0-dev-110 and, as you mention, it has gone.
I'm going to close this again.
