### ISSUE TITLE
Use the following command in centos7：cmake --build build_cmake --parallel <Nr. of cores> --target install

### ISSUE THREAD

**Issue by dephat** [OpenModelica/OpenModelica#10639]
### 
-- Build files have been written to: /openm/OpenModelica/OMSimulator/3rdParty/FMIL/build/linux
gmake[2]: *** [OMSimulator/src/OMSimulator_external-stamp/OMSimulator_external-configure] 错误 2
gmake[1]: *** [CMakeFiles/OMSimulator_external.dir/all] 错误 2
gmake[1]: *** 正在等待未完成的任务....

### centos7

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by dephat** [comment]
[log2.txt](https://github.com/OpenModelica/OpenModelica/files/11361386/log2.txt)
[log1.txt](https://github.com/OpenModelica/OpenModelica/files/11361387/log1.txt)

**Comment by mahge** [comment]
Hi @dephat. Did you manage to get around the issue or is it still happening?
