### ISSUE TITLE
iterationVars flag is not applied in OMEdit

### ISSUE THREAD

**Issue by angmarion** [OpenModelica/OpenModelica#10654]
### Description

This is following the issue #9222 : Whether setting the global or local translation flag ```-d=iterationVars```, the list does not appear in the log file.

### Steps to Reproduce

I tried with the same model provided in the original issue, following all the techniques mentioned in the original issue.

### Version and OS

 - OpenModelica Version: 1.21.0
 - OS: Ubuntu 20.04

**Comment by casella** [comment]
@adeas31 would you mind checking this out?

**Comment by angmarion** [comment]
Hi @adeas31 !
Is there any news on the topic?

**Comment by casella** [comment]
@angmarion please check with the latest 1.22.0-dev nightly build. We are going to release 1.22.0 beta 1 ASAP.

**Comment by angmarion** [comment]
@casella No, it still does not work. Is the list supposed to be in the log file?

**Comment by adeas31** [comment]
It works as expected. The list will be shown in the `All` tab of `Messages Browser`.

**Comment by angmarion** [comment]
@adeas31 My mistake, I looked in the files in the working directory, but I did not think about checking the "All" tab.
