### ISSUE TITLE
Wrong GUI visulization of nested replaceable components

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10659]
### Description

Thanks to #7826 we are able to set modifiers of replaceable components via the parameter dialogue using the current nightly. This even works in principle for nested replaceable components, which is great. However, the GUI does not show the selection of nested replaceable components correctly after closing the parameter dialogue. I tested this with the BRSL 2.2.1 which should be available for you.

### Steps to Reproduce

1. Create a new class and instantiate `Rexroth_Generic.BRSL_World` and then `Rexroth_Pumps.AxialPistonUnits.VariableUnits_OpenCircuit.A4VSO`. 
2. Open the parameter dialogue of `a4vso_1` and select any choice for `axialpstonUnit` (in our case the first one).
3. Step into the parameter dialogue of `axialPistonUnit` using the new edit button.
4. Select any choice for the nested replaceable component `controller` (in our case the second one). The selected choice is displayed correctly in the parameter dialogue of `axialPistonUnit` as shown in the first screenshot. The nested replaceable redeclaration is correctly written to the text layer, which looks as follows.
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_Pumps.AxialPistonUnits.VariableUnits_OpenCircuit.A4VSO a4vso_1(
  redeclare Rexroth_Pumps.Internal.AxialPistonUnits.Database.A4VSO.A4VSO40_1x axialPistonUnit(
  redeclare Rexroth_Pumps.Internal.AxialPistonUnits.Database.A4VSO_Control.A4VSO40_1x_FR controller "A4VSO40FR___/1x (flow control)")  "A4VSO40_______/1x")  
  annotation(Placement(visible = true, transformation(origin = {-20, 14}, extent = {{-18, -10}, {10, 10}}, rotation = 0)));

annotation(uses(Rexroth_Generic(version = "2.2.1"), Rexroth_Pumps(version = "2.2.1")));
end Test;
```
5. Close all parameter dialogues.
6. Open the parameter dialogue of `a4vso_1` again and step into the parameter dialogue of `axialPistonUnit` using the new edit button.
7. The selected choice for `controller` is no longer shown in the GUI even if its still written in the text layer. For this look at the second screenshot.

### Expected Behavior

The selected choice for nested replaceable components is shown when I reopen the parameter dialogue.

### Screenshots

My colleague @niklwors will add the two screenshots as a comment.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: Windows 10, 64 bit
 - MSL 4.0.0 and BRSL 2.2.1

Thanks for looking into this.
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
Picture 1:
![image001](https://user-images.githubusercontent.com/12269776/236780844-8940ab5d-0978-41d9-86b2-8f0e4974d313.png)
Picture 2:
![image002](https://user-images.githubusercontent.com/12269776/236780890-93518c57-caa9-42f8-ab46-0854dfb41561.png)

**Comment by adeas31** [comment]
Looks like an OMEdit issue.

**Comment by abuntrock** [comment]
I tested this with today's nightly (v1.22.0-dev-97-g721e7e1a28) and it looks as expected. Thanks a lot
