### ISSUE TITLE
Modfiers of replaceable classes are  written as modifers of replaceable components

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10652]
### Description

Thanks to #7826 we are able to set modifiers of replaceable components via the parameter dialogue using today's nightly with the instance API. 
However, this does not work for replaceable classes. This has probably the same root cause as #10651 but since this other ticket is without the instance API and our error picture is different, I think opening this ticket might be helpful in finding a solution.
I tested this with the BRSL 2.2.1 which should be available for you.

### Steps to Reproduce

1. Create a new Modelica class by dragging the world and an electric motor on the diagram as follows. Then select one choice for the replaceable class `Motor.`
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_ElectricDrives.RexrothRotationalDrives.SynchronousRotationalDrives.KSM02.KSM02 ksm02_1(
    redeclare record Motor = Rexroth_ElectricDrives.Internal.Database.KSM02.KSM02p1B_041C_42N_xx_xx2_xx_xx_xx_xxxxx "KSM02.1B-041C-42N-__-__2-__-__-__-_____")  
    annotation(Placement(visible = true, transformation(origin = {-8, 16}, extent = {{-14, -10}, {14, 10}}, rotation = 0)));

annotation(uses(Rexroth_Generic(version = "2.2.1"), Rexroth_ElectricDrives(version = "2.2.1")));
end Test;
```
2. When clicking on the Edit symbol next to `Motor`, I already receive the first error message `[: 1:0-1:14]: No viable alternative near token: dummyredeclare`
3. When I click on the edit symbol next to Motor and change a parameter like `P_0_0004` to 100 I get the following error message `[Rexroth_ElectricDrives.RexrothRotationalDrives.SynchronousRotationalDrives.KSM02.KSM02: 23:13-37:35]: [Invalid redeclaration of class Motor as component.]` 
The text layer now looks like this 
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_ElectricDrives.RexrothRotationalDrives.SynchronousRotationalDrives.KSM02.KSM02 ksm02_1(
    redeclare  Rexroth_ElectricDrives.Internal.Database.KSM02.KSM02p1B_041C_42N_xx_xx2_xx_xx_xx_xxxxx Motor(P_0_0004 = 100) "KSM02.1B-041C-42N-__-__2-__-__-__-_____")  
    annotation(Placement(visible = true, transformation(origin = {-8, 16}, extent = {{-14, -10}, {14, 10}}, rotation = 0)));

annotation(uses(Rexroth_Generic(version = "2.2.1"), Rexroth_ElectricDrives(version = "2.2.1")));
end Test;
```
It looks as if OMEdit treats `Motor` internally as an replaceable component once I change a modifier even if its a replaceable class. The syntax `redeclare record Motor = Rexroth_ElectricDrives.Internal.Database.KSM02.KSM02p1B_041C_42N_xx_xx2_xx_xx_xx_xxxxx` is changed to `redeclare  Rexroth_ElectricDrives.Internal.Database.KSM02.KSM02p1B_041C_42N_xx_xx2_xx_xx_xx_xxxxx Motor`.

In addition, as reported in previous tickets like #10602 for other errors, this error lets everything I have on my diagram layer disappear.

### Expected Behavior

The textual representation should look like this in the end, without any errors thrown:
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_ElectricDrives.RexrothRotationalDrives.SynchronousRotationalDrives.KSM02.KSM02 ksm02_1(redeclare record Motor = Rexroth_ElectricDrives.Internal.Database.KSM02.KSM02p1B_041C_42N_xx_xx2_xx_xx_xx_xxxxx (P_0_0004=100))
    annotation(Placement(visible = true, transformation(origin = {-8, 16}, extent = {{-14, -10}, {14, 10}}, rotation = 0)));

annotation(uses(Rexroth_Generic(version = "2.2.1"), Rexroth_ElectricDrives(version = "2.2.1")));
end Test;

```

### Version and OS

 - OpenModelica Version: v1.22.0-dev-91-gc254033131 (64-bit) with instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0 and BRSL 2.2.1

Thanks for looking into this
Aaron Buntrock - Bosch rexroth
@niklwors

**Comment by perost** [comment]
For the issue that the diagram disappears, we've previously dealt with that by relaxing error checks when using the instance API. We could do the same thing here and just ignore the redeclare, but not all errors can be ignored. Maybe OMEdit should just keep the old model structure if the instance API fails so the diagrams don't just disappear?

**Comment by casella** [comment]
> For the issue that the diagram disappears, we've previously dealt with that by relaxing error checks when using the instance API. We could do the same thing here and just ignore the redeclare, but not all errors can be ignored. Maybe OMEdit should just keep the old model structure if the instance API fails so the diagrams don't just disappear?

@perost, I'm not sure I get this. As I understand, there's nothing wrong in the Test model posted by @abuntrock. What would be the "error" in this case?

**Comment by perost** [comment]
> > For the issue that the diagram disappears, we've previously dealt with that by relaxing error checks when using the instance API. We could do the same thing here and just ignore the redeclare, but not all errors can be ignored. Maybe OMEdit should just keep the old model structure if the instance API fails so the diagrams don't just disappear?
> 
> @perost, I'm not sure I get this. As I understand, there's nothing wrong in the Test model posted by @abuntrock. What would be the "error" in this case?

The model is correct to being with, but as described OMEdit then inserts invalid modifiers which makes the model incorrect. And at that point the whole diagram disappears because the instance API fails, which makes it harder for the user to correct the issue.

So my proposal was that instead of trying to make the instance API failproof, which isn't really possible, OMEdit should just keep the old diagram when the instance API fails instead of just throwing everything away.

**Comment by abuntrock** [comment]
In this case the problem of the disappearing diagram layer is not of foremost importance to us. Since this is an error, which is not created by the user but rather by OMEdit, I do not think that something needs to be relaxed if the root cause error is fixed. The error is the wrong redclare statement automatically created by OMEdit.

**Comment by abuntrock** [comment]
@perost From my naive perspective keeping the old diagram layer sounds like a good idea. However, as I said this ticket is mainly for fixing the problem that OMEdit changes the type of the redeclare statement to a wrong one when setting any modifier of the replaceable class.

**Comment by perost** [comment]
> @perost From my naive perspective keeping the old diagram layer sounds like a good idea. However, as I said this ticket is mainly for fixing the problem that OMEdit changes the type of the redeclare statement to a wrong one when setting any modifier of the replaceable class.

Absolutely, @adeas31 will take a look at the actual issue when he is able to. I'm just focusing on the disappearing diagram layer since that's kind of my area. It might be something that needs its own ticket, but we'll see.

**Comment by casella** [comment]
I guess we should not worry too much about the NF being resilient to errors introduced by OMEdit. We should rather fix them :)

**Comment by adeas31** [comment]
#10662 handle the case of replaceable classes. I am still not sure why the error message `[: 1:0-1:14]: No viable alternative near token: dummyredeclare` is showing up. I will debug this more.

**Comment by perost** [comment]
> #10662 handle the case of replaceable classes. I am still not sure why the error message `[: 1:0-1:14]: No viable alternative near token: dummyredeclare` is showing up. I will debug this more.

In some cases when we want to parse a modifier like `(x = 1, y = 2)` we prefix it with "dummy", because the parse function we have for modifiers expects the form `elementName(x = 1, y = 2)`. So if we try to parse e.g. `redeclare Real x` instead of `(redeclare Real x)` we'd get `dummyredeclare Real x`.

I'm not sure where this error message comes from though, I couldn't replicate it with e.g. `modifierToJSON`.

**Comment by adrpo** [comment]
@perost you can trigger this bug with:
[rpl.zip](https://github.com/OpenModelica/OpenModelica/files/11423558/rpl.zip)

```
adrpo33@ida-0030 MINGW64 /c/Users/adrpo33/Downloads
# omc -d=showStatement rpl.mos
...
Evaluating:   > getModelInstance(TestOMEdit.Internal.recordB, "redeclare record testRecord = TestOMEdit.Internal.recordB", false)
"{\"name\":\"TestOMEdit.Internal.recordB\", \"restriction\":\"record\", \"annotation\":{\"Icon\":{\"coordinateSystem\":{\"preserveAspectRatio\":false}}, \"Diagram\":{\"coordinateSystem\":{\"preserveAspectRatio\":false}}}, \"elements\":[{\"$kind\":\"component\", \"name\":\"B\", \"type\":\"Real\", \"modifiers\":\"1\", \"value\":{\"binding\":1}, \"prefixes\":{\"variability\":\"parameter\"}}], \"source\":{\"filename\":\"<interactive>\", \"lineStart\":43, \"columnStart\":5, \"lineEnd\":47, \"columnEnd\":16}}"
Evaluated:    < 0.0092675 / getModelInstance(TestOMEdit.Internal.recordB, "redeclare record testRecord = TestOMEdit.Internal.recordB", false)
Evaluating:   > getErrorString()
"[<internal>:1:0-1:14:writable] Error: No viable alternative near token: dummyredeclare
"
Evaluated:    < 0.0001076 / getErrorString()
```

**Comment by abuntrock** [comment]
@adeas31 I can now set modifiers of replaceable classes successfully even if they are nested. Thanks a lot.
