### ISSUE TITLE
Opening parameter dialog of replaceable component throws wrong missing inner warning

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10653]
### Description

Thanks to #10161 no warnings regarding a missing inner declaration (in our case the BRSL_World) are thrown anymore when I instantiate the world first and then a class which has an outer definition of the world.
However, the warning regarding the missing inner declaration appears when opening the parameter dialogue of a replaceable class even if the inner world is already initialized.
I tested this with the BRSL 2.2.1, which should be available to you.

### Steps to Reproduce

1. Instantiate the BRSL_World as an inner class. Then instantiate a Rexroth_Pump. No warnings regarding a missing inner world are thrown thanks to #10161. The modelica text looks like this. 
```modelica
model Test
  inner Rexroth_Generic.BRSL_World bRSL_World 
    annotation(Placement(visible = true, transformation(origin = {-66, 88}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Rexroth_Pumps.AxialPistonUnits.VariableUnits_OpenCircuit.A4VSO a4vso_1 annotation(
    Placement(visible = true, transformation(origin = {-16, 26}, extent = {{-18, -10}, {10, 10}}, rotation = 0)));

annotation(
    uses(Rexroth_Generic(version = "2.2.1"), Rexroth_Pumps(version = "2.2.1")));
end Test;
```
2. Open the parameter dialogue of `a4vso_1` and click on the edit button next to `axialPistonUnit`. The one notification and the two warnings regarding the missing inner declaration are thrown even if the inner declaration exists. For information: The replaceable class `axialPistonUnit` also has an outer definition of the BRSL_World.

### Expected Behavior

No warnings regarding a missing inner declaration are thrown if this inner class is already initialized no matter what I do in a parameter dialogue. 

### Version and OS

OpenModelica Version: v1.22.0-dev-91-gc254033131 (64-bit) with instance API
OS: Windows 10, 64 bit
MSL 4.0.0 and BRSL 2.2.1

Thanks for looking into this
Aaron Buntrock - Bosch rexroth
@niklwors

**Comment by perost** [comment]
@adeas31: The issue is that OMEdit calls `getModelInstance` on e.g. `Rexroth_BRSL.Rexroth_Pumps.Internal.AxialPistonUnits.Database.A2F.A2FMN028_70` (or something similar, I only have BRSL 2.3), which has an outer world declaration. So the error message is completely correct in that case.

I could just suppress that error message, but I'm not sure if there are cases when we do want to show it?

**Comment by abuntrock** [comment]
@perost You are right that the class of the replaceable component has an outer world definition itself as well. But the corresponding inner declaration is instantiated beforehand. So I would assume that the message only appears when I do not initialize the inner declaration beforehand

**Comment by abuntrock** [comment]
@perost I checked this specific issue again with a nightly from last week (v1.22.0-dev-157-g56167bf5f1 (64-bit)) and to me it seems fixed.
If I instantiate the BRSL_World first and then select a replaceable class, which has an outer world defintion, no warnings appear. Only if the world is not yet instantiated, a warning appears when the replaceable class is selected in the dropdown, which is corrected. So this ticket can be closed from my side
