### ISSUE TITLE
Modelica.Blocks.Continuous.Integrator

### ISSUE THREAD

**Issue by whl5627445** [OpenModelica/OpenModelica#10687]
### Description
After the Modelica.Blocks.Continuous.Integrator model is copied as a separate model, the result of the getInheritedClasses function is wrong

### Steps to reproduce
Copy the model Modelica.Blocks.Continuous.Integrator into a separate model, name it Integrator, execute the getInheritedClasses(Integrator) command on the command line compiler, and return the {Integrator.SISO} result

### Expected behavior
{Interfaces.SISO}

### Screenshots
![image](https://github.com/OpenModelica/OpenModelica/assets/40535668/71586c88-b961-46f5-b98c-c48f8fe42599)
![image](https://github.com/OpenModelica/OpenModelica/assets/40535668/eb86a857-353e-4d3b-960b-592976a08db0)
![image](https://github.com/OpenModelica/OpenModelica/assets/40535668/861e366d-2d9e-472f-a4a4-cb20d1a3c360)
![image](https://github.com/OpenModelica/OpenModelica/assets/40535668/e09031e8-da30-43be-aa42-bea00ad8be1d)

### Version and OS
 - OpenModelica Version [OpenModelica v1.21.0 (64-bit)]
 - Modelica 4.0.0
 - OS: [e.g. Windows 11, 64 bit]

**Comment by casella** [comment]
@whl5627445 this is (unfortunately) a well-known problem, see #5346. We should finally be able to tackle it later this year.
