### ISSUE TITLE
Integrator issue on DASSL solver

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#10698]
### Description

When using a integrator on large simulations (50.000 seconds) with DASSL solver the following error raises and stop simulation:

<img width="1121" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/f20193cb-4679-4651-9787-3b483f41d07c">

### Steps to Reproduce

Get the .txt file attached and change extension to .mo
Open the library with OpenModelica and execute ShipSIM.Examples.Electrical.Consumers with the following configuration:

<img width="883" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/4747cd83-5bc9-4661-ab2b-5d9d2e5d7dfe">

The simulation stops at 17996 seconds with the above error.

### Expected Behavior

The same simulation on Dymola with the same solver settings (DASSL) ends OK.
This simulation works with CVODE solver, but fails with DASSL.

### Screenshots

See above

### Version and OS

 - OpenModelica Version: v.1.21.0 (64-bit)
 - OS: Windows 10 64 bit
 - Versions of used Modelica libraries if applicable: MSL 4.0.0 and MSL 3.2.3

### Additional Context

[ShipSIM4.txt](https://github.com/OpenModelica/OpenModelica/files/11477814/ShipSIM4.txt)

**Comment by BasilioPV** [comment]
The setting pasted is report on each second (one per second)

**Comment by casella** [comment]
OK, can you try with IDA, then? This is supposed to be the modern version of DASSL, same algorithm but with modular linear solvers and a C implementation (DASSL is written in FORTRAN).

**Comment by BasilioPV** [comment]
I have tested IDA with the same result of DASSL and experimented with different time steps as follows:

- 0.1/0.25/0.5 sec:  Error -22 integrator failed at T=2249.5 sec
- 0.7/0.75/0.76/0.79 sec: Result OK!!
- 0.8/1.0/2.0: Error -22 integrator failed at T=17996 sec

Only the band of 0.7-0.79 terminates the calculation.

NOTE: I have this trouble in the past with other models, always when the MSL "integrator" component is used:
 
<img width="181" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/75c8c754-ed9e-400d-ad06-d280a1436f68">

But it's strange that Dymola DASSL handles well the situation and terminate simulation. It would be great that these solvers (IDA and DASSL) terminate the simulation without issues.

(On a side note, if IDA is the modern DASSL, do you reccomend them for default general purpose?)

**Comment by casella** [comment]
> NOTE: I have this trouble in the past with other models, always when the MSL "integrator" component is used:
> <img alt="image" width="181" src="https://user-images.githubusercontent.com/93596576/239165395-75c8c754-ed9e-400d-ad06-d280a1436f68.png">

Weird. This integrator is just a stupid differential equation with an event-triggered reinit, no big deal.

> But it's strange that Dymola DASSL handles well the situation and terminate simulation. It would be great that these solvers (IDA and DASSL) terminate the simulation without issues.

I agree, I'll try to have a look.
 
> (On a side note, if IDA is the modern DASSL, do you reccomend them for default general purpose?)

Good question. In principle the answer is yes. In practice, it seems that the way we use IDA is slightly less robust than the way we use dassl, so in general it performs a bit worse. I thought we had some tests for that on the CI to compare the solver performance on the whole library testsuite, but I actually see none now, so we should probably run this comparison now. 

I would definitely recommend using ida when you have more than a couple hundred state variables. In this case, using a sparse solver for the BDF formula can have a huge benefit, compared to DASSL using a dense solver, which scales as O(N^3).

**Comment by casella** [comment]
@AnHeuermann, I'd be grateful if you could give a look at this, I think this is due to how we use dassl to process events. Here are some excerpts from the log obtained turning on LOG_EVENTS and LOG_SOLVER_V:
```
call solver from 17994 to 17995 (stepSize: 1)
finished solver step 17995
...
call solver from 17995 to 17996 (stepSize: 0.999999999989086)
finished solver step 17996
time event at time=17996
...
offset value for the next step: 0.9999999999890861
call solver from 17996 to 17996 (stepSize: 1.09139364212751e-11)
The code has encountered trouble from which it cannot recover.
can't continue. time = 17996.000000
finished solver step 17996

DASKR-- TOUT (=R1) TOO CLOSE TO T (=R2) TO START INTEGRATION                           In above,  R1 =   1.7996000000000E+04   R2 =   1.7996000000000E+04 
```
It loos like event handling tried to restart a simulation after an event _very_ close to a reporting point, with a step length of 1e-11, and this causes DASKRT to fail because it can't handle a 1e-11 time value increment over 17000 elapsed seconds, that delta is too close to machine eps.

I guess we should put some check to skip steps shorter than, say, `1e-12*max(abs(StartTime), abs(StopTime))`, and move straight to the next step.

What do you think?

**Comment by AnHeuermann** [comment]
We had a similar issue with CVODE (for FMUs) in https://github.com/OpenModelica/OpenModelica/issues/9113.
I'll check what step size DASSL uses after events. We already have a test to check if the step size is too small, but maybe we are missing such a test for the event case.

**Comment by BasilioPV** [comment]
Any news on this issue?

**Comment by AnHeuermann** [comment]
I forgot about this. A quick debugging reveals, that the step size is `1e-11`, but `DASSL_STEP_EPS=1e-13`. I implemented something similar to @casella's suggestion.

If the PR passes fine, otherwise I'm not sure if I have the time to finish this soon.

**Comment by casella** [comment]
@AnHeuermann's PR passed, I just merged it in. @BasilioPV please try with tomorrow's nightly build and report if it still doesn't work for you.

**Comment by BasilioPV** [comment]
Work as expected, solved! 
Thanks for the support

**Comment by casella** [comment]
Great! Thanks for reporting!
