### ISSUE TITLE
Load big .mat results files (5-10 GB) on OMEDIT

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#10706]
### Description

On large simulations a .mat file of 5-10 GB is produced. Then, this file is not imported into OMedit.

### Steps to Reproduce

Open the attached file (rename .txt to .mo) and execute with EULER.
[ShipSIM.txt](https://github.com/OpenModelica/OpenModelica/files/11507499/ShipSIM.txt)

After the simulation finishes, there is no data loaded into OMEDIT (Plotting variables are empty)

### Expected Behavior

The mat file shall be loaded and displayed on OMEDIT.

NOTE: When the .mat file is opened with MC's PLOTXY software, the data is ok inside:
http://ceraolo-plotxy.ing.unipi.it/default.htm

### Screenshots

N/A

### Version and OS

OpenModelica Version: v.1.21.0 (64-bit)
OS: Windows 10 64 bit
Versions of used Modelica libraries if applicable: MSL 3.2.3

### Additional Context

N/A

**Comment by BasilioPV** [comment]
Issue closed, duplicated from #8766

**Comment by casella** [comment]
@ceraolo it seems that your plotxy tool can handle .mat files above 2 GB. I thought that was a limit of the file format, but maybe I'm wrong here. Can you comment on that?

**Comment by ceraolo** [comment]
I'm very proud of PlotXY for many if its features, but it is not intended for huge files.
So I did not make any attempt to break the 2 GB barrier, and therefore cannot help on this.
Sorry.

**Comment by BasilioPV** [comment]
Dear @ceraolo, PlotXY is an awesome piece of software and we don't have the intention to support files larger than 2 GB, just don't block them from loading. After a message saying that it is not intended to be used with files over 2GB, try to load them. I have loaded successfully with your PlotXY files over 6GB with an outstanding loading time and performance. For this reason I believe that your excellent software can handle the most usual situations.

**Comment by casella** [comment]
Awesome, isn't it? 😄

**Comment by casella** [comment]
That said, I think that results files above 2 GB should not really be recommended. 99% of their content will be completely useless, it's just a huge waste of storage space. 

When you tackle large simulations, you should have a strategy to select the values that are important for post-processing, and avoid saving everything else. There are various ways to deal with this: variable filters, making sub-models protected, etc.

**Comment by BasilioPV** [comment]
You are right for final simulations... But when I need to check and debug simulations with extended simulation time is useful. 🙂

**Comment by ceraolo** [comment]
Thank you @BasilioPV  for your words on PlotXY.

The program uses  dynamic allocation of memory nearly everywhere inside. So in principle it can allocate space of any size given enough availability of memory (physical or virtual) and enough addressing space.
I use 32-bit variables (in the search for speed and low memory footprint), and never checked whether Qt (my developping platform) used 32-bit or 64-bit addresses for 32-bit arrays. Your words are a clear indication that it uses 64 bit. Good news! 
In case this works on some cases and does not in other., feel free to tell me privately: I could see if with a reasonable amount of time I can solve possible issues.


In recent years I added capability to read Dymola and Openmodelica files, but I don't manage aliases yet.
Therefore with my students I use it for modelica postprocessong (to make fourier bar plots) _reading curves saved with the save button of omedit_. In this way I have files with a few variables, which are very well manageable.

You are the first guy mentioning PlotXY in a modelica related context.
If it gets used from enough people for modelica output postprocessing, I could implement aliases to make selection of variables much easier. 
Implementing it in a memory-wasting fashion (allocating space for all aliases) is very easy indeed. A smarter implementation, using internal pointers, would require much more effort.
In the first case (allocating space for all aliases), the result would be acceptable for relatively small files, awful for the largest.

**Comment by ceraolo** [comment]
@BasilioPV I have two questions for you:
1. what model inside ShipSIM should I run to get a hige output file that can be reqd with PlotXY?
2. Your models seem very interesting. I've been thinking to use Modelica for ships for several years; I'd gladly analyse your models, and possibly do some joint work with you on electric ships. Do you have a paper or some other source of info describing your models? Are you interested in some form of colalboration with my university?

**Comment by BasilioPV** [comment]
Hi @ceraolo 
1. Please execute with EULER integration and default simulation parameters ShipSIM.Examples.Electrical.Consumers. This produce a 3.5 GB file. Please find attached the library:

[ShipSIM.txt](https://github.com/OpenModelica/OpenModelica/files/11529272/ShipSIM.txt)

2. Regarding collaboration, all help is welcome! By now, I'm using this development for my PhD Thesis, but the only description of the models are the HTML documentation of the library. You can see here the references used for develop them. I'm interested on collaborate on electric ships, so you can write me by email (basiliopuentevarela gmail com) in order to organize the work. Thanks for contact with me!

**Comment by ceraolo** [comment]
A very simple file that creates a mat file 2.3 GB in sizse, that cannot be read by OMEdit:
```
model test
  Modelica.Blocks.Sources.Sine sine[1000](each f = 50) annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.FirstOrder firstOrder[1000] annotation(
    Placement(visible = true, transformation(origin = {42, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(sine.y, firstOrder.u) annotation(
    Line(points = {{11, 0}, {29, 0}}, color = {0, 0, 127}));
  annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime = 0, StopTime = 100, Tolerance = 1e-06, Interval = 0.001),
    Diagram(coordinateSystem(extent = {{-20, 20}, {60, -20}})),
    version = "");
end test;

```
OMEdit complains that the data file is corrupt, while it should not, as it is correctly ready by PlotXY:
http://ceraolo-plotxy.ing.unipi.it/default.htm

The code PlotXY uses to read modelica mat files is here:
https://github.com/max-privato/PlotXY_OpenSource/blob/master/CSimOut.cpp

at rows 116-391 (unfortunately comments are in Italian language)

**Comment by casella** [comment]
See: https://www.mathworks.com/help/matlab/large-mat-files.html
