### ISSUE TITLE
respect XDG base directory specification

### ISSUE THREAD

**Issue by lucas-mior** [OpenModelica/OpenModelica#10737]
Openmodelica creates and uses a directory ".openmodelica/" under $HOME, which gets on the way of the user.
I suggest to follow this: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
It can be done that if "$HOME/.openmodelica/" already exists, use it. Instead, create/use "$XDG_DATA_HOME/openmodelica/"
so that it doesnt break any existing configuration.
I can write pull request for this, if you are willing to accept it.

Additional information:
https://wiki.archlinux.org/title/XDG_Base_Directory

Thanks.

**Comment by casella** [comment]
@sjoelund what do you think?

**Comment by lucas-mior** [comment]
Any news?

**Comment by adrpo** [comment]
Sure, make a PR and we can review it.

**Comment by lucas-mior** [comment]
Closing as the following is enough for me. If anyone is interested:
```
diff --git a/OMCompiler/Compiler/runtime/settingsimpl.c b/OMCompiler/Compiler/runtime/settingsimpl.c
index 36cc61d7e5..6ced6bd0fc 100644
--- a/OMCompiler/Compiler/runtime/settingsimpl.c
+++ b/OMCompiler/Compiler/runtime/settingsimpl.c
@@ -179,7 +179,7 @@ char* Settings_getHomeDir(int runningTestsuite)
   }

 #if !(defined(_MSC_VER) || defined(__MINGW32__))
-  omc_userHome = getenv("HOME");
+  omc_userHome = getenv("XDG_DATA_HOME");
   if (omc_userHome == NULL) {
     omc_userHome = getpwuid(getuid())->pw_dir;
   }
```
