### ISSUE TITLE
FMI should also be tested with some other tool than OMSimulator in the library testsuite

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10752]
The https://libraries.openmodelica.org/branches/master-fmi/ reports contain the results of CI testing with FMI. In fact, the output of such tests is the combined result of two conceptually independent stages

- FMU code generation by OMC
- FMU code simulation by OMSimulator

Simulation failures could either be due to something going wrong in the generated code, or to something going wrong in OMSimulator. As far as I can see, the only way to tell these two apart is to setup another test job that uses a different FMI engine to run the FMUs, e.g. PyFMI, so that we can compare the results and try to infer if the problem is with code generation or with FMU simulation.

**Comment by pstelzig** [comment]
Since a lot of people working with FMUs in Python now use [FMPy](https://github.com/CATIA-Systems/FMPy) this might be a very good candidate, too, for what you suggest.

**Comment by casella** [comment]
We may actually try more than one alternative, and by doing that also indirectly provide a service to the Modelica+FMI+Python community. When OMC's own FMUs are reliable enough, that is 😅

**Comment by adrpo** [comment]
Now we added FMPy to the mix:
https://libraries.openmodelica.org/branches/overview-fmi.html
There are still some kinks to work out, but is getting there.

**Comment by adrpo** [comment]
I'll close this one.
