### ISSUE TITLE
DAEMode: Division by zero when equation order and type (algebraic/differential) are mixed in a if

### ISSUE THREAD

**Issue by rosiereflo** [OpenModelica/OpenModelica#10787]
### Description

With the overly simplified model below (which does not represent anything physical and is just used to illustrate this issue):
```modelica
model test
 Boolean running(start =true);
 Real a(start = 2);
 Real b(start = 10);
equation

  if (running) then
    a = time + 2;
    der(b) = -1;
  else
    b = 0;
    a = 0;
  end if;
  
  when (time > 10) then
    running = false;
  end when;
  
  annotation(__OpenModelica_commandLineOptions = "--daemode");
end test;
```

I obtain a  a division by zero error in OMEdit:
![image](https://github.com/OpenModelica/OpenModelica/assets/47146813/b8f4ac9f-6989-4cba-a287-a432501cb533)

When checking the source code generated we can see that this division by zero was expliciitely generated by the backend:

```
/*
equation index: 9
type: SIMPLE_ASSIGN
a = (-(if running then -2.0 - time else b)) / (if running then 1.0 else 0.0)
*/
...
```

When I swap the 2 equations in the else branch of the 'if' the division by zero disappears.

### Version and OS

 - OpenModelica Version: 1.20.0
 - OS: Ubuntu 20

**Comment by casella** [comment]
@rosiereflo technically speaking your example is a variable index problem, or in other terms a system with structural variability. These systems are characterized by a variable number of state variables, and/or by algebraic constraints among state variables that change at runtime, e.g.
```modelica
model M
  Real x,y,z;
equation
  der(x) =z;
  der(y)  = 1 - z;
  if time < 1 then
    x = y;
  else
    z = y - x;
  end if
end M;
```
Current Modelica tools cannot handle variable-structure systems, so they end up in some kind of singularity (e.g. division by zero or singular Jacobian) when the structure changes at runtime. There's been a lot of research on this topic, see e.g. the MOSILAB project, Dirk Zimmer's PhD thesis, and more recently John Tinnerholm PhD work. But it's still unclear to me if and when this will become mainstream.

For the time being, you can handle this situation by "parking" the differential equations, e.g.
```modelica
equation
  if (running) then
    a = time + 2;
    der(b) = -1;
  else
    der(b) = 0;
    a = 0;
  end if;
  
  when (time > 10) then
    running = false;
  end when;
```

**Comment by rosiereflo** [comment]
OK, many thanks for your answer!
