### ISSUE TITLE
Bad behaviour with unrecognised fontname

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#10797]
### Description
When a fontname is not recognised the entire icon is not drawn.

MS 3.6 sect. 18.6.5.5 regarding record Text says:
"If possible the correct font should be used – otherwise a reasonable
match, or treat as if fontName was empty."

Consider the two models:
```
model TestFont1
equation
annotation(
    Icon(graphics = {Rectangle(fillColor = {255, 255, 255}, 
fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}), 
Text(origin = {3, 3}, extent = {{-69, 23}, {69, -23}}, textString = "text")}));
end TestFont1;
```
```
model TestFont2
equation
annotation (
    Icon(graphics={  Rectangle(fillColor = {255, 255, 255},
    fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}),
     Text(origin = {3, 3}, extent = {{-69, 23}, {69, -23}},
     textString = "text",fontName = MS)}));
end TestFont2;
```

Their icon is a simple square and some text. OMEdit does not recognise the fontname of TestIcon2 and does not draw the icon at all

### Steps to Reproduce
see  description above

### Expected Behavior
the icon should be displayed. Here the square and the string with some substitute (or default) font.
Moreover, when a font is not found a warning should be issued (now an error is shown)

### Screenshots
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/e2430d8d-afa2-416b-addc-9f2d21a09ece)

### Version and OS
OM 1.22.0-dev 111

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by bilderbuchi** [comment]
Isn't what is going on here that this is an error because, as the error says, the *variable* `MS` does not exist?
If I use a *string* for the font name, I get a rendered icon:
```modelica
model TestFont2
equation
annotation (
    Icon(graphics={  Rectangle(fillColor = {255, 255, 255},
    fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}),
     Text(origin = {3, 3}, extent = {{-69, 23}, {69, -23}},
     textString = "text",fontName = "MS")}));
end TestFont2;
```

**Comment by ceraolo** [comment]
yeah, you're perfectly right @bilderbuchi.
I received the file form a PhD student of mine, and assumed that the annotation was created by some good Modelica tool. It resulted that it was not.

This ticket was therefore invalid.
