### ISSUE TITLE
Wrong visualization of parameters which are modfied multiple times in extend statements

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10811]
### Description

The OMEdit parameter dialog does not show the last modified value of a parameter in its dialog when the parameter value is modified multiple times in different extend statements. 

### Steps to Reproduce

1. Consider the following modelica package
```modelica
package RecordModVis
   
record RecordToBeReplaced
    parameter Real[:, 2] A = [-14.0, 40; 14.0, 40];
    parameter Boolean A_tableOnFile = false;
  end RecordToBeReplaced;

  record BaseRecord
    replaceable parameter RecordModVis.RecordToBeReplaced replParam;
    parameter Real realParam = -14.0;
  end BaseRecord;

  record RecordLevel1
  extends RecordModVis.BaseRecord(
    replParam(A=[-15.0, 50; 15.0, 50]),
    realParam=-15.0);
  end RecordLevel1;

  record RecordLevel2
  extends RecordModVis.RecordLevel1(
    replParam(A=[-16.0, 60; 16.0, 60]),
    realParam=-16.0);
  end RecordLevel2;
end RecordModVis;
```
2. Create a new modelica class.
3. Instantiate `RecordModVis.RecordLevel1` and open its parameter dialog. The default value for `realParam` is correctly shown to be -15, which equals the modification in the extend statement.
4. Instantiate `RecordModVis.RecordLevel2` and open its parameter dialog. The default value for `realParam` is wrongly shown to be -15 and not -16. It seems that the second modification of `realParam` (and also `replParam` to give another more complicated example) in `RecordLevel2` is not handed to the GUI correctly. Instead, the first modification in `RecordLevel1` is still shown in the parameter dialog.

### Expected Behavior

The last modification, which occurs at the highest level of a possible "extend ladder", is shown in the parameter dialog.

SideNote: In this minimum example `RecordLevel2` could directly extend `BaseRecord`. However, in our actual use case the above situation occurs because this leads to a better object oriented code.

### Version and OS

 - OpenModelica Version: OpenModelica Version: v1.22.0-dev-157-g56167bf5f1 (64-bit) with instance based API
 - OS: Windows 10, 64 bit

Thanks for looking into this.
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
I see the expected behavior. I get `-16` for `realParam` for an instance of `RecordModVis.RecordLevel2`

![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/5ca920e8-54dd-4920-b02e-c6432d2c00f5)

**Comment by abuntrock** [comment]
I tested this again with today’s nightly (v1.22.0-dev-164-g35b2943a7c (64-bit)) and it still looks wrong for me.
***@***.***
Do you have the instance API activated since you do not have the edit button next to replParam?


​

**Comment by adeas31** [comment]
Eeeehhh......yes I deactivated the instance API. I was testing something else.

I can reproduce this now. Will try to fix this asap.

**Comment by abuntrock** [comment]
@adeas31 I checked this again with today's nightly. And on the level from yesterday's picture it looks good now (parameter dialog of `recordLevel2`). But when clicking the edit button next to `replParam` (parameter dialog of `recordLevel2.replParam`) parameter _A_ is visulaized with [-14.0,40;14.0,40] and not the correct modified [-16, 60; 16.0, 60]. 
Should I open a new ticket for this?
