### ISSUE TITLE
Visualization of modified defaults inside replaceable classes

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10833]
### Description

#10811 fixes the problem of visualizing the defaults of parameters which where modified multiple times in extend statements. However if the default of a parameter inside a replaceable class is change, it is not correctly visualized in the parameter dialog of the replaceable class.

### Steps to Reproduce

1. Consider the following modelica package
```modelica
package RecordModVis
   
record RecordToBeReplaced
    parameter Real[:, 2] A = [-14.0, 40; 14.0, 40];
    parameter Boolean A_tableOnFile = false;
  end RecordToBeReplaced;

  record BaseRecord
    replaceable parameter RecordModVis.RecordToBeReplaced replParam;
    parameter Real realParam = -14.0;
  end BaseRecord;

  record RecordLevel1
  extends RecordModVis.BaseRecord(
    replParam(A=[-15.0, 50; 15.0, 50]),
    realParam=-15.0);
  end RecordLevel1;

  record RecordLevel2
  extends RecordModVis.RecordLevel1(
    replParam(A=[-16.0, 60; 16.0, 60]),
    realParam=-16.0);
  end RecordLevel2;
end RecordModVis;
```
2. Create a new modelica class.
4. Instantiate `RecordModVis.RecordLevel2` and open its parameter dialog. The default for `replParam.A` is correctly shown to be [-16, 60; 16.0, 60], thanks to #10811. 
5. Open the parameter dialog of the replaceable parameter `replParam` via the new edit button `(recordLevel2.replParam)`. The default for parameter `A` is wrongly shown to be  [-14, 40; 14.0, 40], which is the original default from `RecordModVis.RecordToBeReplaced` and not the modified one from `RecordModVis.RecordLevel2`.

### Expected Behavior

The parameter dialog of the replaceable class shows the modified default. In this case  [-16, 60; 16.0, 60] for parameter `A`.

### Version and OS

 - OpenModelica Version: OpenModelica Version: v1.22.0-dev-172-g52f1c262fd (64-bit) with instance based API
 - OS: Windows 10, 64 bit

Thanks for looking into this.
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
#10835 should fix this issue. Please test and let me know.

**Comment by abuntrock** [comment]
Thanks a lot for the fast fix. I will test it with tomorrows nightly build

**Comment by abuntrock** [comment]
I checked this with today's nightly and it looks perfect with our more complicated as well.
