### ISSUE TITLE
Not possible to rename Plot Tabs in OMEdit 

### ISSUE THREAD

**Issue by JKRT** [OpenModelica/OpenModelica#10834]
### Description
Currently, it is not possible to rename tabs when working in OMEdit.
This means it can be hard to remember what each plot is representing if one is simulating different subsystems at the same time during development.

### Steps to Reproduce
N/A
### Expected Behavior
When right-clicking a tab in the plot pane of OMEdit it should be possible to rename it using a `rename` action.

### Version and OS

All

### Additional Context
This is not a bug report per see, rather it describes a new feature for OMEdit.

**Comment by JKRT** [comment]
This feature was implemented in PR: https://github.com/OpenModelica/OpenModelica/pull/10806

**Comment by casella** [comment]
Thanks @JKRT!
