### ISSUE TITLE
ConstrainedBy baseclass is not shown in dropdown menu

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#10860]
### Description

If the class after the constrainedBy keyword in a replaceable declaration is not the default as well, it is not shown in the dropdown menu of the replaceable declaration if "the choicesAllMatching=true" annotation is present.

### Steps to Reproduce
1. Consider the following MWE package.
```modelica
package ConstrainedByDropdown
    model ModelWithReplaceable
  
    replaceable record replRecordType = ConstrainedByDropdown.UserRecord1 
    constrainedby ConstrainedByDropdown.BaseRecord
    annotation(choicesAllMatching = true);
    
    replaceable parameter ConstrainedByDropdown.UserRecord1 replRecordInst
    constrainedby ConstrainedByDropdown.BaseRecord 
    annotation(choicesAllMatching = true);
    
    replaceable model replModelType = ConstrainedByDropdown.UserModel1 
    constrainedby ConstrainedByDropdown.BaseModel
    annotation(choicesAllMatching = true);
    
replaceable ConstrainedByDropdown.UserModel1 replModelInst
    constrainedby ConstrainedByDropdown.BaseModel 
    annotation(choicesAllMatching = true);
    
  end ModelWithReplaceable;

  record BaseRecord
  parameter Real realParam = 0;
  end BaseRecord;

  record UserRecord1
  extends ConstrainedByDropdown.BaseRecord(realParam=1);
  end UserRecord1;

  record UserRecord2
  extends ConstrainedByDropdown.BaseRecord(realParam=2);
  end UserRecord2;

  model BaseModel
  parameter Boolean boolParam = true;
  end BaseModel;

  model UserModel1
  extends ConstrainedByDropdown.BaseModel(boolParam=false);
  end UserModel1;

  model UserModel2
  extends ConstrainedByDropdown.BaseModel(boolParam=false);
  end UserModel2;
end ConstrainedByDropdown;
```
2. Create a new class, instantiate `ConstrainedByDropdown.ModelWithReplaceable`, and open its parameter dialog.
3. Each of the four replaceables in the parameter dialog should have three dropdown entries (Base, User1, and User2) but all four have only two entries (User1, and User2).

Side Note: The four different replaceable declaration types are only added to this MWE to highlight the fact, that this issue is not related to a special replaceable declaration type. 

### Expected Behavior

The class after the constrainedBy keyword is shown in the dropdown menu when "choicesAllMAtching=true" and if the class is not partial. In this MWE this would mean that `ConstrainedByDropdown.BaseRecord` and `ConstrainedByDropdown.BaseModel` are shown in the respective drop-downs.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-178-gabbf3e40b3 (64-bit) with instance API (nightly from last week)
 - OS: Windows 10, 64 bit

Thanks for looking into it
Aaron Buntrock - Bosch rexroth

**Comment by adeas31** [comment]
Talked with @perost about it. He will push a fix for `getAllSubtypeOf` API so that it includes the constraining class as well.

**Comment by adeas31** [comment]
Tested this successfully with #10877.

**Comment by abuntrock** [comment]
@adeas31 I tried to check this with today's nightly but I am only able to download the nightly from two days ago (https://build.openmodelica.org/omc/builds/windows/nightly-builds/64bit/). Is there currently something wrong with the download page?

**Comment by abuntrock** [comment]
I checked this with today's nightly and it looks as expected. Thanks a lot
