### ISSUE TITLE
Modifiers applied to components of an extended model are not shown in the parameter dialog

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10864]
### Steps to Reproduce

- open the attached [InitBlocks.zip](https://github.com/OpenModelica/OpenModelica/files/11798007/InitBlocks.zip) package

- open` InitBlocks.Examples.Tests.WaterHeater.TestWaterHeaterStepForward` in OMEdit
- the model contains the following code:
```modelica
  extends BaseTests.BaseTestWaterHeater(
    initBlockOptions(mode = InitBlocks.Blocks.Options.BlockMode.SimulationOpenLoopOnDesign, normalization = true),
    outputBlock(y_norm = 380));
``` 
However, if I double-click on the salmon-hued `outputBlock`, `y_norm` is displayed with its default inherited value `y_des`. If I now type in another value, e.g. 400, this is correctly inserted in the modifier, but the parameter editing window still displays `y_des`.

I guess this is a problem with OMEdit, not with the API, but I'm not sure. @adeas31, @perost, could you please check?

Keeping @matteodepascali in the loop

Thanks!

**Comment by casella** [comment]
Thanks @adeas31! @matteodepascali, please check that you can now use your library with the latest nightly build. If there are any issues, please report them here.

**Comment by matteodepascali** [comment]
Thank you, @adeas31!
I tried this morning with the last nightly and #10865 seems has been solved in every case. This issue instead is still there when multiple model extensions are present. In fact, if I extend one more time the model of this issue, the same behavior appears: when I modify a parameter, it is not updated in the parameter editing window.
Here is the new [InitBlocks.zip](https://github.com/OpenModelica/OpenModelica/files/11865952/InitBlocks.zip) with the new model ```InitBlocks.Examples.Tests.WaterHeater.TestWaterHeaterStepBackward```.
Thanks for the help!

**Comment by casella** [comment]
Here is an updated MWE:
```modelica
package TestInheritedParameter
    model M
    parameter Real p = 1;
    parameter Real q = 10;
  equation

  end M;

  model S1
  M m(p = 2, q = 20)  
annotation(
  Placement(visible = true, 
  transformation(origin = {-10, -2}, extent = {{-10, -10}, {10, 10}},
  rotation = 0)));
  equation

  end S1;

  model S2
    extends TestInheritedParameter.S1(m(p = 3, q = 30));
  equation

  end S2;

  model S3
    extends TestInheritedParameter.S2(m(p = 3));
  equation

  end S3;
end TestInheritedParameter;
```
When double-clicking on m in S3:
- the modified parameter values are not shown
- the shown default refer to the base class S1, not the the parent class S2

@perost, I guess this information should arrive to OMEdit straight from the instantiation API, can you please check that?

Thanks!

**Comment by casella** [comment]
Thanks @adeas31! @matteodepascali please check with tomorrow's nightly build.

**Comment by matteodepascali** [comment]
Thank you @adeas31, I confirm the new nightly is fine and the bug is solved!
