### ISSUE TITLE
Issues with expandable connectors in VehicleInterface

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10895]
After @tobolar's [last commit](https://github.com/modelica/VehicleInterfaces/commit/756a4b72c6efbb342eee9aac4e7a615f025306b5) to the VehicleInterface library, most models in the library no longer pass the frontend. The [reported error](https://libraries.openmodelica.org/branches/master/VehicleInterfaces/files/VehicleInterfaces_VehicleInterfaces.Examples.ConventionalAutomaticVehicle.err) is:
```
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/VehicleInterfaces 2.0.1-master/DriverEnvironments/DriveByWireAutomatic.mo:39:3-42:22:writable]
Error: Cannot connect expandable connector driverEnvironment.driverBus with non-expandable connector 
driverEnvironment.controlBus.driverBus.
```

@perost, could you please check if this is a library issue or a NF issue?

Thanks!

**Comment by tobolar** [comment]
I detected that definition in `VehicleInterfaces.Interfaces.ControlBus` by chance and change it according to definition of other busses (e.g. `VehicleInterfaces.Interfaces.BrakesBus`), i.e. empty bus definitions, and signal definition in inherited classes (e.g. `VehicleInterfaces.Brakes.Internal.StandardBus`).
In Dymola, both the original and changed definition works fine, but after my last commit, the arranging of the pop-up menu when connecting a signal to the controlBus takes longer.

I'm curious how this will be resolved.

**Comment by casella** [comment]
@tobolar, if you don't mind, maybe it's best to revert the commit, since it apparently also worsen the performance with Dymola, somehow.

We can of course take care of this in OMC, but that will take some time and it seems to me there is no compelling reason to support this feature right away.

Thanks!

**Comment by tobolar** [comment]
Reverted: https://github.com/modelica/VehicleInterfaces/pull/119

**Comment by casella** [comment]
[All fine again](https://libraries.openmodelica.org/branches/history/master/2023-06-29%2022:27:09..2023-06-30%2012:56:22.html), thanks @tobolar!

**Comment by tobolar** [comment]
> The issue is that we don't support augmenting an expandable connector with an expandable connector yet, which I guess is legal on account of not being explicitly forbidden in the specification. I've been trying to implement it with little success so far, but I might have an idea about how to do it now. But it will take a bit of time to implement.

I wonder if there is some progress on this topic.
@perost @casella

**Comment by perost** [comment]
> > The issue is that we don't support augmenting an expandable connector with an expandable connector yet, which I guess is legal on account of not being explicitly forbidden in the specification. I've been trying to implement it with little success so far, but I might have an idea about how to do it now. But it will take a bit of time to implement.
> 
> I wonder if there is some progress on this topic. [@perost](https://github.com/perost) [@casella](https://github.com/casella)

Yes, I'm currently in the process of rewriting our expandable connector handling, with fixing this issue as one of the goals.

**Comment by tobolar** [comment]
> Yes, I'm currently in the process of rewriting our expandable connector handling, with fixing this issue as one of the goals.

This is a great news! Looking forward for this new feature.

**Comment by casella** [comment]
Please follow #13067
