### ISSUE TITLE
Obfuscated save total json file should contain the full paths

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10897]
### Description

The mapping.json file of obfuscated Save Total only contain variable names

### Steps to Reproduce

Do Save Total on Modelica.Blocks.Examples.Filter, with obfuscation. The FilterTotal_mapping.json file only contains the last part of the fully qualified names:
```
{
  "ModelicaServices": "n0",
  "Modelica": "n1",
  "Icons": "n2",
  "Package": "n3",
  "Machine": "n4",
  "eps": "n5",
  "small": "n6",
  "inf": "n7",
  "Integer_inf": "n8",
  "Blocks": "n9",
  "Units": "n10",
  "SI": "n11",
  "Examples": "n12",
  "ExamplesPackage": "n13",
  "Filter": "n14",
  "Example": "n15",
  "order": "n16",
  "f_cut": "n17",
  "Frequency": "n18",
  "filterType": "n19",
...
}
```
### Expected Behavior

The fully qualified names of variables, parameters, functions etc. should be shown instead.

Keeping @AndreaBartolini in the loop.

**Comment by perost** [comment]
The obfuscation is done on a string basis, so e.g. `Modelica = n1` and `Icons = n2` gives `Modelica.Icons = n1.n2`. So there should be no need to list all fully qualified names, it would just make the JSON much larger without adding any information.

**Comment by casella** [comment]
Sure, sorry :)
