### ISSUE TITLE
Strange behaviour at lambda = 0

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10920]
We are facing a strange problem while trying to initialize a fairly complex fuel cell model in steady-state. The actual initialization problem is a very large, coupled, strongly non-linear system with many hundreds of unknowns. However, clever simplifications by homotopy (in particular, fixing the temperature value used to compute equilibrium constants) allows to break down the solution in a sequence of much smaller systems. We tried this in Dymola and it worked flawlessly, as expected.

When we try this in OMC, two strange things happen. The first is that the initialization problem has a huge strong component for initial-lambda0 (equation 5181, with 159 unknowns and 27 iteration variables), that should instead be broken down into several, much smaller problems. The second is that such a system turns out to be singular (and takes a very looong time to fail in the original version of the model, which had more volumes than the one we're using for debugging).

During today's webmeeting, @kabdelhak pointed out that very likely the culprit here is the pre-balancing optimization being carried out a-priori, _without taking into account the lambda = 0 simplifications_, which is the same issue as in #10497.

I'm not 100% sure about that, but I would ask @kabdelhak and @phannebohm to please investigate. I'll send them the model separately, as it is still not public, and coming up with an MWE is out of the question.

**Comment by phannebohm** [comment]
@kabdelhak and I looked at the model. Our findings are:

1. On our machines the simulation succeeds (alas with many asserts during simulation).
2. The whole system is not under/overdetermined so balancing has no influence (omc and dymola should do the same thing).
3. No index reduction takes place, so again no changes on the structure of the initial system.
4. As far as we could see, the SCCs for $\lambda=0$ don't seem to contain any complicated constructs (function calls, algorithms, array equations, reductions, ...) for which the adjacency module could misbehave, just purely algebraic expressions. Is that correct?
5. We couldn't find your exact SCC (equation 5181, with 159 unknowns and 27 iteration variables) instead we found a system with 138 internal and 29 residual variables. Is that the one you are referring to?

As soon as #10938 is merged you can observe the system using `-d=dumpLoops`. Search for the header "Algbraic Loops (Initialization Lambda=0 (Homotopy)):"

I guess analyzing a system of this size by hand is out of the question. Any suggestion on how to proceed?

**Comment by casella** [comment]
@phannebohm we'll look into that as soon as we return from the IFAC WC in Japan next week. Thanks!

**Comment by casella** [comment]
Adding @matteodepascali to the loop

**Comment by casella** [comment]
> I guess analyzing a system of this size by hand is out of the question. Any suggestion on how to proceed?

I re-ran the model today, and it still doesn't work. Strange that you can get it to run. 

Anyway, the crux of the story is that we get a large, coupled system at lambda = 0, that should not be coupled at all in the first place. Maybe implementing the dump we suggested in #10994 could help figuring out which equation(s) are causing the coupling?

Thanks!

**Comment by casella** [comment]
@matteodepascali will send you an updated version of the package where we verify we actually get a failure. Maybe something went wrong with that.

**Comment by phannebohm** [comment]
I ran the simulation with `-lv=LOG_INIT_HOMOTOPY` and it seems the lambda=0 system runs fine. But no matter how small I choose the lambda increments, the first step with lambda > 0 fails solving a nonlinear system and tries to calculate a bunch of invalid roots e.g.,

```
$ ./<MODELNAME> -lv=LOG_INIT_HOMOTOPY                     
LOG_INIT_HOMOTOPY | info    | Model contains homotopy operator: Use adaptive homotopy method to solve initialization problem. To disable initialization with homotopy operator use "-noHomotopyOnFirstTry".
LOG_INIT_HOMOTOPY | info    | Global homotopy with equidistant step size started.                                                                                                                                    
LOG_INIT_HOMOTOPY | info    | The homotopy path will be exported to <MODELNAME>_equidistant_global_homotopy.csv.
LOG_INIT_HOMOTOPY | info    | homotopy process                                                                                                                                                                       
|                 | |       | ---------------------------                                                                                                                                                            
LOG_INIT_HOMOTOPY | info    | homotopy parameter lambda = 0                                                                                                                                                          
LOG_INIT_HOMOTOPY | info    | homotopy parameter lambda = 0 done                                                                                                                                                     
|                 | |       | ---------------------------                     
LOG_INIT_HOMOTOPY | info    | homotopy parameter lambda = 0.333333        
LOG_ASSERT        | debug   | <MODELNAME>_functions.c:244: Invalid root: (-0.516734)^(-0.14874)
LOG_ASSERT        | debug   | <MODELNAME>_functions.c:244: Invalid root: (-3.36044)^(-0.14874)
[...]
LOG_ASSERT        | debug   | <MODELNAME>_functions.c:244: Invalid root: (-13.7997)^(-0.14874)
LOG_ASSERT        | debug   | <MODELNAME>_functions.c:244: Invalid root: (-10.2523)^(-0.14874)
LOG_ASSERT        | debug   | Solving non-linear system 2401 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.
LOG_ASSERT        | error   | Failed to solve the initialization problem with global homotopy with equidistant step size.
LOG_ASSERT        | debug   | Unable to solve initialization problem.
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization
```

Maybe Tearing throws away the good start values delivered by the lambda=0 system?

**Comment by casella** [comment]
Hi @phannebohm, I'm back to work on this (though from a nice Caribbean island, hehe).

As we understand, something bad happens with structural analysis at lambda = 0, so that the system is much larger than it ought to be (and possibly wrong? we don't know), so it converges successfully at a solution that is physically meaningless. As soon as the actual expression is computed, even though it is multiplied by a very small lambda, it contains invalid computations such as -0.53^(-0.14).

The root problem is, the initial-lambda0 problem does not have the right structure.

**Comment by casella** [comment]
@phannebohm we continued the analysis and concluded that the whole BLT during initialization is bogus, both initial-lambda0 and initial. Let's get more specific.

Regarding initial-lambda0, this is the expected sequence of computations, that we actually see in Dymola.
- currents `pen.i` are computed first, based on a linear system. This actually happens, see linear system 4945
- based on the currents, all the oxygen flow rates `wO2` can be computed explicitly via Faraday equation
- hence, all the flow rates at the module boundaries can be computed explicitly and sequentially by mass balances
- for each module in 1:3
  - first the outlet compositions fluidOut.fluid.X[:] are computed by a nonlinear system (partial mass balances + temperature-independent reaction rates) with 5 iteration variables
  - then all the temperatures are computed by another nonlinear system (energy balances +heat exchanges) with 5 iteration variables 
- end for

OMC instead couples all the above-mentioned equations in a big system 5748, with 53 iteration variables.

We tried to figure out what are the bogus couplings that OMC takes into account so as to be forced to solve them together. However, we stumble right away in a weird situation: the oxygen flow rates wO2 are defined in the initial and regular sets, but not in the initial-lambda0 set, _though the are used in the initial-lambda0_ set. This makes no sense, and could lead to the generation of code that receives bogus zero (or worse, uninitialized) values for that variable.

This needs to be investigated.

Furthermore, we should investigate why, e.g., the computation of the iteration variables fuelCell.module[2].anodeChannel.fluidOut.fluid.X[1:5] gets coupled with all the other 48 iteration variables, since instead it should be possible to compute them in a single strong component.

My wild guess is that if we have arrays containing arrays there is something going badly wrong with indexes (e.g. their order is swapped, or something). Maybe we could have an online session next week to discuss this in person.

We could possibly try to reduce the number of equations by having less chemical species (reducing the size of the X arrays), though this won't be a trivial task. The minimum number of modules for the model to make sense is three, so this is pretty much the smallest MWE we can produce 😅. The actual model has a lot more modules, but this is irrelevant for structural debugging.

For sure the old backend does really weird stuff in this case, and we can't leave this thing unaddressed, as it may be affecting other non-trivial user models.

**Comment by phannebohm** [comment]
We were comparing the two versions of the library @matteodepascali sent to me. The old version simulated while the new didn't. Looking at the diff we observed a lot of noise coming from the fact that you changed `SOSModels.FuelCell.N` from 2 to 3. We changed that back to see what else changed, but now it simulates! Then we changed `N` to 3 in the old version and that also fails during initialization. Maybe that can steer us in the right direction?

**Comment by casella** [comment]
@phannebohm the fact that the example model simulates with N = 2 or N = 3 is not significant. When the size of the model is reduced, even with a bogus lambda = 0 initialization the solver may somehow manage to find a solution (not necessarily a meaningful one, mind you). Unfortunately, it really doesn't work when N is large enough (e.g. 10) to provide an accurate enough representation of the 1D distribution of all the physical variables in the fuel cell.

We should really focus on the bogus structural handling, regardless of the fortuitous numerical outcome in some cases. From this point of view
- the homotopy simplifications were made to break down the initial-lambda0 problem into many smaller independent problems. This is essential for the success of initialization when using large enough N. We should figure out why OMC doesn't do that
- the causalization in the initial-lambda0 phase clearly fails the define-before-use rule of causalized equations. This should also be fixed.

Regarding N = 2 vs. N = 3, it could be that N = 2 is really too small to be structurally meaningful, so we switched to N = 3 because of that. What happens with N = 3 is that some computations of the last module (i = 3) are correctly carried out independently by OMC, while all the previous ones (i = 1, i = 2) are coupled, for some reason. Of course you can't see this difference with N = 2, so probably N = 3 is the smallest MWE that replicates all the structural issues we observed.

**Comment by casella** [comment]
After an analysis session, we recognized that wO2 is indeed handled correctly - the assignment of wO2 in the initial-lambda0 case is done by an alias equation (a regular equation, that has the same structure), which is not shown in the "Defines" window. I will open a specific ticket about that.

**Comment by casella** [comment]
Regarding the bogus large initial-lambda0 strong component, it seems that when the `--replaceHomotopy(simplified)` flag is switched on, the resulting initial equation do not have that strong component. So, the problem may be in the way the backend replaces the homotopy operator - if I am not mistaken --replaceHomotopy acts on the front-end, not on the backend; @perost can you please confirm?

**Comment by casella** [comment]
@matteodepascali will check the equations in the bogus strong component of initial-lambda0, to see if they haven't been simplified properly.

**Comment by casella** [comment]
Discussion continues in #12941.
