### ISSUE TITLE
Model diagram disappears due to GUI actions

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#10934]
This issue addresses two situations where the model diagram disappears, what forces the user to switch to code view and solve the problem. The first seems a bug, whereas the second could be perhaps avoided.

1. When modifying the value of fixed attribute in a vectorial variable using the dialog:

![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/b5809549-3266-4ff4-8dbe-adf961f2ed2c)

the code is modified without the keyword each:
`Component(m(fixed = true))`
causing the disappearing of diagram. The user needs modify to 
`Component(m(each fixed = true));`
and the diagram appears again. 

2. When removing temporally a connection associated with the automatic dimension (N) of an array (Dialog(connectorSizing = true)), as that pointed by the cursor in the image:
![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/5436526b-c82c-43e4-a52e-e88530b8f2f3)
if there is any array variable with a dimension that depends on N, an error is generated and the diagram disappears. 

For instance, in the following component, BloodVfracF has [N-1] dimension, with N = 2 (see figure's connection), and it is defined with the modifier: 
`Component(BloodVfracF = {0.4});`

Therefore, when the connection is removed, the following error is originated :

[4] 20:43:36 Translation Error [CybSim.Physiology.PBPK.Basic: 42:5-43:48]: [Type mismatch in binding 'BloodVfracF = {0.4}', expected array dimensions [0], got [1].](omeditmessagesbrowser:///CybSim.Physiology.PBPK.Basic?lineNumber=42)

And the diagram dissapears, forcing to remove the definition of the variable before acting on the connection. Although this is not a bug, it could be interesting to avoid the disappearing of the model diagram.

System: OM 1.22 dev (latest nightly build) on Windows 11. Enable Instance API on.

Thanks for the support!

**Comment by casella** [comment]
The diagram disappears because the frontend cannot parse the invalid code without `each`

See #5405 and #5489.

@adeas31 will look into it starting end of July.

**Comment by adeas31** [comment]
@mpradovelasco this is already fixed. The diagram does not disappear now and you can add `each` via GUI.
Please reopen if you encounter any issue.

**Comment by mpradovelasco** [comment]
Hi @adeas31 . I have tested and it works fine.

Thanks for your great work!
