### ISSUE TITLE
Parser issue in complicated expression with combined array constructors with iterators and reduction

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#10930]
### Description

Try the following model in OMC
```modelica
model TestParser
  constant Integer Ns = 5;
  constant Integer Nd = 10;
  Real A1[Ns];
  Real C1[Nd] = fill(1,Nd);
  Real M1[Ns,Nd] = fill(1,Ns,Nd);
  Real A2[Nd] = fill(1,Nd);
equation 
  A1 = {sum({{(if C1[i]>0 then M1[j,i]/(A2[i])  else 0) for i in 1:Nd} for j in 1:Ns}[k,:]) for k in 1:Ns};
end TestParser;
```
OMC gives the following error:
```
[4] 12:09:51 Syntax Error
[M: 9:86-9:86]: Missing token: ')'
```
The model is correct and simulates in Dymola.

Keeping @AndreaBartolini in the loop.

**Comment by mahge** [comment]
This is basically equivalent to this:
```mo
A = {{(if C1[i]>0 then M1[j,i]/(A2[i])  else 0) for i in 1:Nd} for j in 1:Ns}[k,:]
// Equivalent to
a = {1, 2, 3}[1];
```

I don't think subscripting non component reference expressions is allowed by the Modelica Standard. Dymola is probably just showing off.

**Comment by perost** [comment]
The issue is that you're subscripting an expression (the middle array constructor), which is not valid Modelica. There's an ongoing discussion about adding it in [#2659](https://github.com/modelica/ModelicaSpecification/issues/2659), but there are still open questions about if and how it should be done.

**Comment by casella** [comment]
In fact I already had a slight doubt about indexing an expression, but I was lazy and did not check what the spec said 😅

**Comment by perost** [comment]
> In fact I already had a slight doubt about indexing an expression, but I was lazy and did not check what the spec said 😅

We could support it if we wanted to, the NF already does. Since #10732 it's even part of the Absyn, it's really only the parser that doesn't support it yet. But the syntax isn't decided yet of course, and I'm assuming it's not really that important to you.

**Comment by casella** [comment]
Good to hear that we could support this easily. However, I would be hesitant at using constructs that are not (yet) in the MLS and on which there is no general consensus in the MAP-LANG group. 

@perost maybe you can help going forward with the discussion in modelica/ModelicaSpecification#2659. I understand it got stuck because of some corner case and there is lack of manpower to resolve it.
