### ISSUE TITLE
OpenMP not found when compiling in MacOS 13.4.1

### ISSUE THREAD

**Issue by IronAspen** [OpenModelica/OpenModelica#10959]
OpenMP not found when compiling in MacOS 13.4.1 (M1 chip)
Can I turn this option off when compiling OpenModelica in this system:

-----------------------------------------------------
ycg@YcgdeAir OpenModelica % cmake -S . -B build_cmake -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -DOM_OMC_ENABLE_FORTRAN=OFF -DOM_OMC_ENABLE_IPOPT=OFF -D OM_ENABLE_GUI_CLIENTS=OFF -D CMAKE_INSTALL_PREFIX=$PWD/install
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OMC_TARGET_ARCH="unknown"
-- Found Git: /usr/bin/git (found version "2.39.2 (Apple Git-143)") 
-- SOURCE_REVISION="v1.22.0-dev-239-gca93d5a252-cmake"
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- CMAKE_VERSION="3.26.4"
-- CMAKE_C_COMPILER_ID="AppleClang"
-- CMAKE_CXX_COMPILER_ID="AppleClang"
-- CMAKE_Fortran_COMPILER_ID=""
-- CMAKE_LIBRARY_ARCHITECTURE=""
-- OM_ENABLE_GUI_CLIENTS="OFF"
-- OM_ENABLE_ENCRYPTION="OFF"
-- OM_USE_CCACHE="ON"
-- CMAKE_BUILD_TYPE="Debug"
-- Found ccache. It will be used for compilation C/C++ sources
-- CCACHE_PROGRAM="/opt/homebrew/bin/ccache"
-- CMAKE_INSTALL_PREFIX="/Users/ycg/Downloads/OpenModelica/install"
-- [OMCompiler] OM_OMC_ENABLE_FORTRAN="OFF"
-- [OMCompiler] OM_OMC_ENABLE_IPOPT="OFF"
-- [OMCompiler] OM_OMC_ENABLE_CPP_RUNTIME="ON"
-- [OMCompiler] OM_OMC_USE_CORBA="OFF"
-- [OMCompiler] OM_OMC_USE_LAPACK="ON"
CMake Error at cmake/omc_utils.cmake:16 (add_subdirectory):
  The source directory

    /Users/ycg/Downloads/OpenModelica/OMCompiler/3rdParty

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  OMCompiler/CMakeLists.txt:49 (omc_add_subdirectory)

CMake Deprecation Warning at OMCompiler/SimulationRuntime/c/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for sgemm_
-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for sgemm_ - not found
-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for dgemm_
-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for dgemm_ - found
-- [OMCompiler.3rdParty.SimulationRuntime.c] Found BLAS: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/Accelerate.framework  
-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for cheev_
-- [OMCompiler.3rdParty.SimulationRuntime.c] Looking for cheev_ - found
-- [OMCompiler.3rdParty.SimulationRuntime.c] Found LAPACK: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/System/Library/Frameworks/Accelerate.framework;-lm;-ldl  
-- [OMCompiler.3rdParty.SimulationRuntime.cpp] Found Boost: /opt/homebrew/lib/cmake/Boost-1.82.0/BoostConfig.cmake (found version "1.82.0") found components: program_options filesystem 
-- [OMCompiler.3rdParty.SimulationRuntime.ParModelica] Found Boost: /opt/homebrew/lib/cmake/Boost-1.82.0/BoostConfig.cmake (found version "1.82.0") found components: graph chrono 
-- [OMCompiler.3rdParty.Parser] Found Java: /Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home/bin/java (found version "20.0.1") found components: Runtime 
-- [OMCompiler.3rdParty.Parser] Found Intl: /opt/homebrew/lib/libintl.dylib (found version "0.21.1") 
-- [OMCompiler.3rdParty.Parser] added antrl (BaseModelica_Lexer dependent) target /Users/ycg/Downloads/OpenModelica/build_cmake/OMCompiler/Parser/generated/Modelica_3_Lexer
-- [OMCompiler.3rdParty.Parser] added antrl (BaseModelica_Lexer dependent) target /Users/ycg/Downloads/OpenModelica/build_cmake/OMCompiler/Parser/generated/ParModelica_Lexer
-- [OMCompiler.3rdParty.Parser] added antrl (BaseModelica_Lexer dependent) target /Users/ycg/Downloads/OpenModelica/build_cmake/OMCompiler/Parser/generated/MetaModelica_Lexer
-- [OMCompiler.3rdParty.Parser] added antrl target /Users/ycg/Downloads/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser
-- [OMCompiler.3rdParty.Compiler.runtime] Found CURL: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libcurl.tbd (found version "7.87.0")  
-- [OMCompiler.3rdParty.Compiler.runtime] Performing Test Iconv_IS_BUILT_IN
-- [OMCompiler.3rdParty.Compiler.runtime] Performing Test Iconv_IS_BUILT_IN - Failed
-- [OMCompiler.3rdParty.Compiler.runtime] Found Iconv: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/lib/libiconv.tbd (found version "1.11") 
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for LAPACK. This can be slow sometimes. Hang tight!
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for dgeqpf_
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for dgeqpf_ - found
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for time.h
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for time.h - found
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for ctime_s
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for ctime_s - not found
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for ctime_r
-- [OMCompiler.3rdParty.Compiler.runtime] Looking for ctime_r - found
-- [OMCompiler.3rdParty.Compiler.runtime] OMC_TARGET_SYSTEM_NAME="darwin"
-- [OMCompiler.3rdParty.Compiler.runtime] Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- [OMCompiler.3rdParty.Compiler.runtime] Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- [OMCompiler.3rdParty.Compiler.runtime] Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- [OMCompiler.3rdParty.Compiler.runtime] Performing Test BSTATIC_INT
-- [OMCompiler.3rdParty.Compiler.runtime] Performing Test BSTATIC_INT - Success
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 26% complete]
-- [download 27% complete]
-- [download 28% complete]
-- [download 29% complete]
-- [download 30% complete]
-- [download 31% complete]
-- [download 32% complete]
-- [download 33% complete]
-- [download 34% complete]
-- [download 35% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 38% complete]
-- [download 39% complete]
-- [download 40% complete]
-- [download 41% complete]
-- [download 42% complete]
-- [download 43% complete]
-- [download 44% complete]
-- [download 45% complete]
-- [download 46% complete]
-- [download 47% complete]
-- [download 48% complete]
-- [download 49% complete]
-- [download 50% complete]
-- [download 51% complete]
-- [download 52% complete]
-- [download 53% complete]
-- [download 54% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 73% complete]
-- [download 74% complete]
-- [download 75% complete]
-- [download 76% complete]
-- [download 77% complete]
-- [download 78% complete]
-- [download 79% complete]
-- [download 80% complete]
-- [download 81% complete]
-- [download 82% complete]
-- [download 83% complete]
-- [download 84% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- [testsuite.difftool] Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- --------------------------------------------------------------------------
-- --------------------------------------------------------------------------
-- The following features have been enabled:

 * OMC_TARGET_ARCH, unknown
 * SOURCE_REVISION, v1.22.0-dev-239-gca93d5a252-cmake
 * CMAKE_VERSION, 3.26.4
 * CMAKE_C_COMPILER_ID, AppleClang
 * CMAKE_CXX_COMPILER_ID, AppleClang
 * OM_USE_CCACHE, ON
 * CMAKE_BUILD_TYPE, Debug
 * CCACHE_PROGRAM, /opt/homebrew/bin/ccache
 * CMAKE_INSTALL_PREFIX, /Users/ycg/Downloads/OpenModelica/install
 * OM_OMC_ENABLE_CPP_RUNTIME, ON
 * OM_OMC_USE_LAPACK, ON
 * OMC_TARGET_SYSTEM_NAME, darwin

-- The following OPTIONAL packages have been found:

 * Git
 * FLEX

-- The following REQUIRED packages have been found:

 * boost_program_options (required version == 1.82.0)
 * boost_atomic (required version == 1.82.0)
 * boost_filesystem (required version == 1.82.0)
 * boost_headers (required version == 1.82.0)
 * boost_graph (required version == 1.82.0)
 * boost_chrono (required version == 1.82.0)
 * Boost
 * Java
 * CURL
 * Intl
 * Iconv
 * BLAS
 * Threads
 * LAPACK

-- The following features have been disabled:

 * CMAKE_Fortran_COMPILER_ID
 * CMAKE_LIBRARY_ARCHITECTURE
 * OM_ENABLE_GUI_CLIENTS
 * OM_ENABLE_ENCRYPTION
 * OM_OMC_ENABLE_FORTRAN
 * OM_OMC_ENABLE_IPOPT
 * OM_OMC_USE_CORBA

-- The following OPTIONAL packages have not been found:

 * OpenMP

-- Configuring incomplete, errors occurred!

**Comment by mahge** [comment]
I think the immediate issue is not the unavailability of OpenMP. It is that you have not initialized the submodule repositories of OpenModelica properly yet. 

OpenModelica contains a few submodules (some of them nested inside other submodules). For this reason, you have to either 
- Tell git to clone the submodules when you clone OpenModelica
```
git clone --recurse-submodules https://github.com/OpenModelica/OpenModelica.git
```

- OR initialize the submodules manually after cloning OpenModelica  
```
git clone https://github.com/OpenModelica/OpenModelica.git
git submodule update --init --recursive
```

The second option is probably what you want here since you have already cloned OpenModelica without the submodules. 

-------------------------

To get OpenMP for macOS and AppleClang you can use hombrew to install the libomp library.
```
brew install libomp
```

**Comment by IronAspen** [comment]
> I think the immediate issue is not the unavailability of OpenMP. It is that you have not initialized the submodule repositories of OpenModelica properly yet.
> 
> OpenModelica contains a few submodules (some of them nested inside other submodules). For this reason, you have to either
> 
> * Tell git to clone the submodules when you clone OpenModelica
> 
> ```
> git clone --recurse-submodules https://github.com/OpenModelica/OpenModelica.git
> ```
> 
> * OR initialize the submodules manually after cloning OpenModelica
> 
> ```
> git clone https://github.com/OpenModelica/OpenModelica.git
> git submodule update --init --recursive
> ```
> 
> The second option is probably what you want here since you have already cloned OpenModelica without the submodules.
> 
> To get OpenMP for macOS and AppleClang you can use hombrew to install the libomp library.
> 
> ```
> brew install libomp
> ```

Really thanks for your help, I fixed this issue by following your instruction. Now I can run om in my mac Wow.
