### ISSUE TITLE
 Modelica-Buildings Library (master): Simulation Aborted due to chattering detected

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#11006]
### Description

The solver fails to solve the system due to Chattering detected around time 4210.04189188..5065.76400301 (100 state events in a row with a total time delta less than the step size 3605.71). This can be a performance bottleneck. 
The following below listed models have same issues:

```
Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer 
```
On simulating the model in OpenModelica leads to following errors/warnings:

```
1. The following assertion has been violated during initialization at time 0.000000 ((false)) --> "*** Warning in ChillerDXHeatingEconomizer.hvac.pumChiWat: Mover has per.etaHydMet=.Power_VolumeFlowRate or per.etaHydMet=.EulerNumber. This requires per.pressure to be provided. Because it is not, the model overrides this setting by using per.etaHydMet=.NotProvided."
2. The following assertion has been violated during initialization at time 0.000000 ((false)) --> "*** Warning in ChillerDXHeatingEconomizer.hvac.pumChiWat: Mover has per.etaMotMet=.Efficiency_MotorPartLoadRatio or per.etaMotMet=.GenericCurve. This requires per.WMot_nominal or per.pressure to be provided. Because neither is provided, the model overrides this setting and by using per.etaMotMet=.NotProvided."
3. Chattering detected around time 4210.04189188..5065.76400301 (100 state events in a row with a total time delta less than the step size 3605.71). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: not pre(con.hysHea.y) and hvac.uHea > 0.05 or pre(con.hysHea.y) and hvac.uHea >= 0.01
4. Homotopy solver Newton iteration: Maximum number of iterations reached at time 382608.479582, but no root found. (Note: 15 times same warning)
```
The log report for these models are as given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer.sim)

```
LOG_STDOUT        | info    | Using sparse solver for linear system 10,
|                 | |       | because density of 0.160 remains under threshold of 0.200.
LOG_STDOUT        | info    | Using sparse solver for linear system 22,
|                 | |       | because density of 0.160 remains under threshold of 0.200.
LOG_STDOUT        | info    | The maximum density for using sparse solvers can be specified
|                 | |       | using the runtime flag '<-lssMaxDensity=value>'.
LOG_STDOUT        | warning | The default linear solver fails, the fallback solver with total pivoting is started at time 0.000000. That might raise performance issues, for more information use -lv LOG_LS.
LOG_ASSERT        | warning | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 10.0.0-master/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:417:3-426:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((false)) --> "*** Warning in ChillerDXHeatingEconomizer.hvac.pumChiWat: Mover has per.etaHydMet=.Power_VolumeFlowRate or per.etaHydMet=.EulerNumber.
|                 | |       | This requires per.pressure to be provided.
|                 | |       | Because it is not, the model overrides this setting by using per.etaHydMet=.NotProvided."
LOG_ASSERT        | warning | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 10.0.0-master/Fluid/Movers/BaseClasses/PartialFlowMachine.mo:428:3-437:39:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((false)) --> "*** Warning in ChillerDXHeatingEconomizer.hvac.pumChiWat: Mover has per.etaMotMet=.Efficiency_MotorPartLoadRatio or per.etaMotMet=.GenericCurve.
|                 | |       | This requires per.WMot_nominal or per.pressure to be provided. Because neither is provided,
|                 | |       | the model overrides this setting and by using per.etaMotMet=.NotProvided."
LOG_SUCCESS       | info    | The initialization finished successfully with 3 homotopy steps.
LOG_STDOUT        | info    | Chattering detected around time 4024.56325862..4905.24585862 (100 state events in a row with a total time delta less than the step size 1802.85714286). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: not pre(con.hysHea.y) and hvac.uHea > 0.05 or pre(con.hysHea.y) and hvac.uHea >= 0.01
LOG_ASSERT        | debug   | Aborting simulation due to chattering being detected and the simulation flags requesting we do not continue further.
```
The list of warnings reported in the simulation test are given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer.err)

```
1. The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the 
   conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates 
   please use -d=aliasConflicts.
2. It was not possible to determine if the initialization problem is consistent, because of not evaluable parameters/start values during compile time: hvac.heaCoi.vol.dynBal.medium.p = hvac.heaCoi.vol.dynBal.p_start (weaDat.pAtmSel.p = hvac.heaCoi.vol.dynBal.p_start)
3. The initial conditions are over specified. The following 3 initial equations are redundant, so they are removed from the initialization system:         
     hvac.heaCoi.vol.dynBal.medium.p = hvac.heaCoi.vol.dynBal.p_start
     hvac.chi.vol1.dynBal.medium.p = hvac.chi.vol1.dynBal.p_start
     zon.roo.air.vol.dynBal.medium.p = zon.roo.air.vol.dynBal.p_start.
```
### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the examples model present in Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer 

### Expected Behavior

The simulation should succeed.

### Version and OS

-    OpenModelica Version: OpenModelica 1.22.0~dev-243-g1088818
-    OS: Ubuntu 20.04 focal

       Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings master (10.0.0)

**Comment by AndreaBartolini** [comment]
It (`Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer`) simulates with just few warnings with
OpenModelica v1.23.0-dev-378-g063c0d3760
Win 11 pro

**Comment by casella** [comment]
@AndreaBartolini this is weird. 063c0d (which you used) was committed on Mar 15, while the latest CI test was run using 513c66, which was committed on Mar 16. Basically the same.

Could it be a difference beween Linux and Windows? Can you test it on Linux?

**Comment by AndreaBartolini** [comment]
actually the chattering is detected also under WIN

`Chattering detected around time 4024.56325862..4905.24585862 (100 state events in a row with a total time delta less than the step size 3605.71). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: not pre(con.hysHea.y) and hvac.uHea > 0.05 or pre(con.hysHea.y) and hvac.uHea >= 0.01`

but after few seconds the simulation exits from the chattering and goes straight to the end without any problem.
I think the CI stops when chattering is detected (I remember that there is a flag that does it).

I'll investigate the origin of the chattering.

**Comment by AndreaBartolini** [comment]
The chattering is induced by the thresold with hysteresis `hysHea` that implements the ON/OFF logic of the Supply fan

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/98d84949-c7f1-4eb9-9fc6-95fe07d8c131)

more in detail, the chattering is induced by the control action `yHea` of the Air heating coil, that is used to trigger the thresold `hysHea` and shows a lot of oscillations during the control transient, most probably due to the large band choosen for the PID controller.

![ChillerDXHeatingEconomizerChattering](https://github.com/OpenModelica/OpenModelica/assets/25974985/93fe4bef-119a-4a2b-8bcb-e6d175f4dd6e)

herebelow the same transient obtained by reducing the gain of the controller by one order of magnitude:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/5e5a24f4-d429-4b88-a190-e035d2e3ead8)

the control performances are less than before and the chattering phenomenon disappears.

Now the point is to found the right compromise between chattering (that means stress of the actuators) and control performances, but this should be decided by the modeler that has built this example. Maybe the performances are the priority, in this case the CI should avoid to stop when the chattering is detected, taking also into account the fact that the chattering is temporary.

**Comment by casella** [comment]
I opened  lbl-srg/modelica-buildings#3735, let's see what the modellers say.

**Comment by Pavanrajhr** [comment]
@casella The model `Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer ` is currently passing. I think we can close this ticket.

**Comment by casella** [comment]
Agreed, this was solved upstream in the Building library.
