### ISSUE TITLE
 Modelica-Buildings Library (master): Simulation fails due to Repetitive warning.

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#11000]
### Description

The solver fails to solve system due to Repetitive warning  that is Need to output more then one event from spatialDistribution. Step size to big! time: 32250.915284, spatialDistribution index: 3, number of events: 2
The following below listed models have same issues:

```
Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT
Buildings.Fluid.Geothermal.BuriedPipes.Validation.GroundCouplingAIT
```

On simulating the model in OpenModelica leads to following errors/warnings:

```
1. Need to output more then one event from spatialDistribution. Step size to big! time: 32250.915284, spatialDistribution index: 
   3, number of events: 2 (Note: same warning is repetitive) 
```
The log report for these models are as given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT.sim)

```
LOG_STDOUT        | info    | ... loading "dat" from "/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 10.0.0-master/Resources/Data/Fluid/FixedResistances/Validation/PlugFlowPipes/PipeDataAIT151218.mos"
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_STDOUT        | warning | Removed more then one event from spatialDistribution. Step size to big!
LOG_STDOUT        | warning | time: 32250.531751, spatialDistribution index: 3, number of events: 3
LOG_STDOUT        | warning | Removed more then one event from spatialDistribution. Step size to big!
LOG_STDOUT        | warning | time: 105007.111974, spatialDistribution index: 3, number of events: 15
LOG_STDOUT        | warning | Removed more then one event from spatialDistribution. Step size to big!
LOG_STDOUT        | warning | time: 105300.000000, spatialDistribution index: 3, number of events: 52
LOG_ASSERT        | debug   | New front position is not smaller then previous first node.
LOG_STDOUT        | error   | x got reinitialized during an event at time 171000.000000. OpenModelica can't handle that.
```

The list of warnings reported in the simulation test are given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT.err)

```
1. The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the 
   conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates 
   please use -d=aliasConflicts.
```

### Steps to Reproduce

Load the Modelica-Buildings master library (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html)
 Simulate the examples model present in Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT

### Expected Behavior

The simulation should succeed.

### Version and OS

-    OpenModelica Version: OpenModelica 1.22.0~dev-243-g1088818
-    OS: Ubuntu 20.04 focal

       Versions of used Modelica libraries:
        Modelica 4.0.0
        Buildings master (10.0.0)

**Comment by AndreaBartolini** [comment]
The model `Buildings.Fluid.Geothermal.BuriedPipes.Validation.GroundCouplingAIT` is no longer present in the master branch.

The model `Buildings.Fluid.FixedResistances.Validation.PlugFlowPipes.PlugFlowAIT` simulates but al lot of following warnings are thrown:
```
Removed more then one event from spatialDistribution. Step size to big!
time: 32400.000000, spatialDistribution index: 3, number of events: 2
```
and the simulation ends without any message. Herebelow the transient of a simulated delta-pressure:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/c347d943-7e95-4ba0-ada4-d5b394c2c311)

The simulation reaches the end time of 603900 seconds as request.

OpenModelica v1.23.0-dev-409-ga5a3ab3b6f (64-bit)
Win11 64 bit

**Comment by casella** [comment]
@AndreaBartolini please check if the problem is solved by shortening the time interval from 900 to, say, 120 or 60 s.

**Comment by AndreaBartolini** [comment]
With both time interval = 120  and 60 only one warning is risen and simulation speed up:

```
Removed more then one event from spatialDistribution. Step size to big!
time: 32250.512827, spatialDistribution index: 3, number of events: 9
```
The same by reducing the time interval again (tried up to 10).

**Comment by casella** [comment]
@AndreaBartolini please open a PR on https://github.com/lbl-srg/modelica-buildings/ where you reduce the Interval annotation to 120 s, pointing to this ticket as a background.

**Comment by AndreaBartolini** [comment]
done in PR https://github.com/lbl-srg/modelica-buildings/pull/3771

**Comment by casella** [comment]
There were some issues with our CI, but I hope they have been all resolved. The current [Buildings_latest](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) report refers to version c5fd934 of the Buildings master branch, which is one commit behind lbl-srg/modelica-buildings#3773. We should see the results tomorrow.

**Comment by casella** [comment]
Problem solved upstream by https://github.com/lbl-srg/modelica-buildings/pull/3773
