### ISSUE TITLE
Error in the Linux Debian / Ubuntu Packages installation instructions

### ISSUE THREAD

**Issue by jskortel** [OpenModelica/OpenModelica#11014]
### Description

There is a typo/error in the Linux Debian / Ubuntu Packages installation instructions on the OpenModelica website, page: https://openmodelica.org/download/download-linux/

### Steps to Reproduce

Go the the web page and to the first command line code box. The text is now:

```sh
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg sudo
curl -fsSL http://build.openmodelica.org/apt/openmodelica.asc | \
  sudo gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg
```

The error is at the end of the second and the beginning of the third line. The "sudo" command is on a wrong line. The text should be:

```sh
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo curl -fsSL http://build.openmodelica.org/apt/openmodelica.asc | \
  sudo gpg --dearmor -o /usr/share/keyrings/openmodelica-keyring.gpg
```

### Expected Behavior

The current set of commands fails, the new set of commands works.

### Screenshots

No screenshot.

### Version and OS

Debian and Ubuntu Linux distributions.

**Comment by HumanG33k** [comment]
Need a fix too

**Comment by casella** [comment]
Fixed. Thanks for reporting!
