### ISSUE TITLE
Suport sum(scalar) 

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#11015]
### Description

See this model error:
https://libraries.openmodelica.org/branches/master/TransiEnt/files/TransiEnt_TransiEnt.Components.Electrical.FuelCellSystems.Check.TestFuelCellSystem_SOFC.err

**Comment by adrpo** [comment]
https://libraries.openmodelica.org/branches/master/TransiEnt/files/TransiEnt_TransiEnt.Components.Electrical.FuelCellSystems.SteamReformer.Check.TestSteamReformer.err

**Comment by adrpo** [comment]
Other software seems to support sum(scalar):

```mo
model TestSum
  Real a[10] = fill(1, 10);
  Real b[10] = fill(1, 10);
  Real d = a * b;
  Real x = sum(1);
  Real c = sum(a * b);
end TestSum;
```

**Comment by phannebohm** [comment]
[MLS section 10.3.4](https://specification.modelica.org/master/arrays.html#reduction-functions-and-operators) clearly states that these reductions are defined for arrays or reduction expressions, not for scalars. So shouldn't these models be fixed instead?

**Comment by adrpo** [comment]
Ok. I will try to fix these in the library. I have seen this behavior from Dymola on other operators as well such as min and max.

**Comment by adrpo** [comment]
Maybe we should add some of these tests in the Compilance testsuite.

**Comment by adrpo** [comment]
Somehow I understand why one would want to support this behavior where min, max and sum can be applied to scalars. If you make the scalar an array it will just work and you won't need to change the code again, but maybe it could introduce errors.

**Comment by adrpo** [comment]
Like fore example here, which `sum` should I remove? :)
Looking at the code is not that easy to spot.

```mo
  H_flow_in_NCV=gasPortIn.m_flow*sum(NCV*cat(1,gasIn.xi,{1-sum(gasIn.xi)}));
  H_flow_out_NCV=gasPortOut.m_flow*sum(NCV*cat(1,xi[N_cv,:],{1-sum(xi[N_cv,:])}));
  H_flow_in_GCV=gasPortIn.m_flow*sum(GCV*cat(1,gasIn.xi,{1-sum(gasIn.xi)}));
  H_flow_out_GCV=gasPortOut.m_flow*sum(GCV*cat(1,xi[N_cv,:],{1-sum(xi[N_cv,:])}));
  H_flow_out_GCV_woWater=gasPortOut.m_flow*sum({GCV[1],GCV[2],0,GCV[4]}*cat(1,xi[N_cv,:],{1-sum(xi[N_cv,:])}));
```

**Comment by perost** [comment]
> Somehow I understand why one would want to support this behavior where min, max and sum can be applied to scalars. If you make the scalar an array it will just work and you won't need to change the code again, but maybe it could introduce errors.

In that case you probably need to change a lot more too, so I'm not sure how useful that would really be in practice. In my experience it's much more likely that the operators have simply been used by mistake, so I think it's better to be strict about it since it could otherwise hide bigger issues.
