### ISSUE TITLE
Inherited class without replaceable clause in a redeclarable component should not allow redeclarate that component

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#11020]
Hi, 

The model S is given by the following code:
```modelica
package TestConstrainedBy
  package Interfaces
    partial function F0
      input Real x;
      output Real y;
    end F0;
  end Interfaces;

  encapsulated package F
    import CybSim.test.TestConstrainedBy.Interfaces;
    function F1 "F1"
      extends Interfaces.F0;
    algorithm
      y := 2*x;
    end F1;

    function F2 "F2"
      extends Interfaces.F0;
    algorithm
      y := x;
    end F2;
    
    block B
      replaceable function procF = F1 constrainedby F0
      annotation(choicesAllMatching = true);
    equation
      annotation(
        Diagram(graphics = {Rectangle(fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}})}));
    end B;

    model S
      type C = B(redeclare function procF = F2);
      C comp1 annotation(
        Placement(visible = true, transformation(origin = {-4, 16}, extent = {{-14, -14}, {14, 14}}, rotation = 0)));
      B comp2 annotation(
        Placement(visible = true, transformation(origin = {-4, -16}, extent = {{-14, -14}, {14, 14}}, rotation = 0)));
    end S;
  end F;
```
S has two components comp1 and comp2. 

comp2 is an instance of class B, which has the replaceable function procF, whereas comp1 is an instance of class C, which in turn derives from class B and uses the modifier (redeclare function procF = F2). However, OM allows redeclaring procF also in class C, despite procF must not be a redeclarable function since "replaceable" clause has not been added in the modifier (Section 7.3.3 of ModelicaSpecification 3.4).  The same occurs for other type of classes (not only with functions). 

The following figure shows the diagram of model S and the dialog of comp1:
![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/c67ba4b1-4032-4e70-b11c-e35a48f995da)

and the following, the same for comp2:
![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/cfafc3ec-1628-4e62-92d7-8e324dbf562d)

I am not sure that this is really a bug. In that case, is there any other possibility to avoid the redeclaration of procF in the derived class C?
 
Latest OM 1.22 dev on Windows 11, EnableInstanceAPI flag is on.

Thanks in advance!

**Comment by adeas31** [comment]
I think this is same as #11311.
