### ISSUE TITLE
Modelica.Blocks.Math.RealToBoolean cannot handle input=treshold

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11049]
### Description

The MSL class `Modelica.Blocks.Math.RealToBoolean` is supposed to output true if its input is **equal** or larger than a parameter threshold. However, if the input resembles a step from a lower value to the threshold the output of the converter class stays false. Other Modelica tools (tested with Dymola) on the other hand change the output from 'false" to 'true'. Even tight tolerances and small stepzises like in the example below do not change this behaviour. I am aware that testing Real values for equality is numerically not really possible. The observed behaviour in OMEdit however contradicts the greater or equal statement from the class' documentation.

### Steps to Reproduce

1. Run the following example
```modelica
model RealToBoolTest
  Modelica.Blocks.Sources.Step step(height = 2, offset = 0, startTime = 0.5)  annotation(
    Placement(visible = true, transformation(origin = {-30, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.RealToBoolean realToBoolean(threshold = 2)  annotation(
    Placement(visible = true, transformation(origin = {10, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(realToBoolean.u, step.y) annotation(Line(points = {{-2, 10}, {-18, 10}}, color = {0, 0, 127}));

annotation(uses(Modelica(version = "4.0.0")),
    experiment(StopTime=1,Interval=0.001,Tolerance=1e-10));
end RealToBoolTest;
```
2. Inspect the result variables especially `realToBoolean.y` which is `false` during the whole simulation.

### Expected Behavior

`realToBoolean.y` is `false` from 0s to 0.5s and `true` from 0.5s to 1s. 

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth
@niklwors

**Comment by Arinomo** [comment]
maybe its related https://github.com/OpenModelica/OpenModelica/discussions/8600

**Comment by Arinomo** [comment]
> Is there any way to tell based on machine accuracy and/or number of significant when this change in behaviour happens.

Changing the integration's tolerance to `1e-10` when using `dassl` works for you example above. So I guess you can expect the integration tolerance has something to do with triggering the threshold. Even changing `greaterThreshold1(threshold = 1 - 1e-12)` works.

**Comment by casella** [comment]
@abuntrock, it really depends on the context. For example, `>` and `>=` work well with parameters, e.g.
```modelica
package Test
model M
  parameter Real p;
  Real x,y;
equation
  if p > 0 then 
    x = 1;
  else
    x = 0;
  end if;
  if p >= 0 then 
    y = 1;
  else
    y = 0;
  end if;
end M;

model S
  M m1(p = 0);
  M m2(p = 1.0);
end S;
end Test;
```
will behave as expected. Distinguishing between > and >= when _time varying_ variables are handled is really problematic, and should IMHO be avoided in sound modelling practice.

**Comment by abuntrock** [comment]
@casella Thanks for the additional clarification. So would you suggest opening an issue for the MSL then?

**Comment by casella** [comment]
You can do it and see what the reaction is. I would expect a potentially long discussion 😄

**Comment by abuntrock** [comment]
I think so. I'll probably let this go. There are more important things for us as well :)
