### ISSUE TITLE
Protection status of existing instances influences diagram visualization

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11055]
### Description

Consider a class, where all instances are below the `protected` keyword. When a new class instance is dragged onto the diagram layer the existing instances change their places and the diagram layer is wrong (it does not fit to the still correct text layer anymore). 
This does not happen when the existing instances are public or if the new instance is created via the text layer.

### Steps to Reproduce

1. Consider the following modelica model:
```modelica
model NewInstanceToOnlyProtected
protected
  Modelica.Blocks.Math.RealToBoolean realToBoolean annotation(
    Placement(visible = true, transformation(origin = {10, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step annotation(
    Placement(visible = true, transformation(origin = {-30, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(step.y, realToBoolean.u) annotation(Line(points = {{-18, 30}, {-2, 30}}, color = {0, 0, 127}));
  annotation(uses(Modelica(version = "4.0.0")));
end NewInstanceToOnlyProtected;
```
The diagram layer looks as shown in the first screenshot. 
2. Add any new class to the diagram layer. In our case we drag `Modelica.Electrical.Analog.Basic.Ground` to the bottom left corner far away from the already existing instances. The diagram layer looks as shown in the second screenshot. All three instances are depicted in a wrong position and do not fit to text layer anymore. The text layer is still correct and presented below.
```modelica
model NewInstanceToOnlyProtected
  Modelica.Electrical.Analog.Basic.Ground ground annotation(
    Placement(visible = true, transformation(origin = {-90, -92}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
protected
  Modelica.Blocks.Math.RealToBoolean realToBoolean annotation(
    Placement(visible = true, transformation(origin = {10, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step annotation(
    Placement(visible = true, transformation(origin = {-30, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(step.y, realToBoolean.u) annotation(Line(points = {{-18, 30}, {-2, 30}}, color = {0, 0, 127}));
  annotation(uses(Modelica(version = "4.0.0")));
end NewInstanceToOnlyProtected;
```
3. Take the modelica model from step one again. Create the text layer with three instances by copying the new instance into the text layer above the protected keyword. The resulting text layer is exactly the same as in step 2. The text to copy is. 
```modelica
  Modelica.Electrical.Analog.Basic.Ground ground annotation(
    Placement(visible = true, transformation(origin = {-90, -92}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
```
However, now the diagram layer is correct, fits to the text layer and looks as shown in the third screenshot. 
4. If the protected keyword is removed from the modelica text from step 1 and then step 2 is performed, the diagram layer is also correct and looks like shown in the third screenshot.

### Expected Behavior

The protection status of instantiated components does not influence the visualization of the diagram layer when a new class is instantiated.
The way of isntantiation (dragging vs text layer) does not influence the diagram layer visualization. 

### Screenshots

My colleague @niklwors will add the mentioned screenshots below in a comment.

### Version and OS

 - OpenModelica Version: 1.21.0 and v1.22.0-dev-263-gfae4e4871e both withe instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
picture 1:
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/6490a3bf-07aa-4d06-ac38-e963ed5276ab)

picture 2:

![image002](https://github.com/OpenModelica/OpenModelica/assets/12269776/e8593cbd-b5bc-487f-b612-2393f7b57669)

picture 3:
![image003](https://github.com/OpenModelica/OpenModelica/assets/12269776/f231f779-7967-4178-bb17-38862b35448a)

**Comment by abuntrock** [comment]
With the current nightly (v1.23.0-dev-257-gcfdfeb87e5) this problem is fixed. I do not know during which other fix. But it looks good now. Thanks a lot.
