### ISSUE TITLE
Checking of index out of bounds should generate a warning in if equations

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#11065]
### Description

This model:
https://libraries.openmodelica.org/branches/master/TransiEnt/files/TransiEnt_TransiEnt.Storage.Heat.ElectricWaterHeater_constProp_L4.Check.CheckStratifiedElectricWaterHeater_CoolDown.err

Gets this error:
`TransiEnt 2.0.2-master/Storage/Heat/ElectricWaterHeater_constProp_L4/ElectricWaterHeater_constProp_L4.mo:189:5-203:11:writable] Error: Subscript '0' for dimension 1 (size = 50) of T is out of bounds.`

But the code looks like:
```mo
for i in 1:n-1 loop
    if i==i_minturb_2 and u[2] and u[1] then
      dTdt_turb[i] = 2 * m_flow_cf/m_i * (- T[i] + T[i+1]);
    elseif i>=i_minturb_2 and u[2] and u[1] then  // upper heating element, both on
      dTdt_turb[i] = 2 * m_flow_cf/m_i * (T[i-1] - 2*T[i] + T[i+1]);
    elseif i==i_minturb_2 and u[2] then  // upper heating element on
      dTdt_turb[i] = m_flow_cf/m_i * (- T[i] + T[i+1]);
    elseif i>=i_minturb_2 and u[2] then  // upper heating element on
      dTdt_turb[i] = m_flow_cf/m_i * (T[i-1] - 2*T[i] + T[i+1]);
    elseif i==i_minturb_1 and u[1] then // lower heating element on
      dTdt_turb[i] = m_flow_cf/m_i * ( - T[i] + T[i+1]);
    elseif i>=i_minturb_1 and u[1] then // lower heating element on
      dTdt_turb[i] = m_flow_cf/m_i * (T[i-1] - 2*T[i] + T[i+1]);
    else  // below lower heating element, or elements off
      dTdt_turb[i]=0;
    end if;
  end for;
```

While there is an access to` T[i-1]` when` i `goes from `1` to `n-1` is in an if equation that ensures that `i` is larger or equal than `2`.
I think that the index out of bounds check should become a warning in an if equation, especially if the index is part of the condition.

**Comment by perost** [comment]
I don't think we should even be giving a warning in that case, the check is supposed to be conservative and not give false positives. So I changed it so that we don't go into the bodies of e.g. if- or when-equations when doing the check, since we don't know if those equations will actually be part of the simulation.
