### ISSUE TITLE
__OpenModelica_simulationFlags(s = "cvode") annotation is not respected

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11094]
### Description

An OpenModelica solver can be defined in a model annotation with `__OpenModelica_simulationFlags(s = "cvode"))`. This however does not seem to be used when simulating or is at least not correctly shown in the simulation output. I searched old issues but I could not find a similar one. Excuse me if I overlooked something existing.

### Steps to Reproduce

1. Consider the following modelica file. The experiment annotation and the simulation flag have been saved using the OMEdit "Simulation Setup" parameter dialogue. The desired solvermethod is `cvode`.
```modelica
model Solvermethod
  Modelica.Blocks.Sources.Ramp ramp(height = 5, duration = 1, offset = 1, startTime = 0)  annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

annotation(uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-6, Interval = 0.002),
  __OpenModelica_simulationFlags(s = "cvode"));
end Solvermethod;
```
2. Simulate the model in the OMEdit GUI using the green arrow. In the blue output (execution command?) the solver is correctly listed as `cvode`. However in the statistics section the solver is shown as `euler`. (See first screenshot)
3. Simulate the model using the OpenModelica Compiler CLI. There the used method is specified as `dassl` but the desired solver `cvode` is mentioned in the simflags section. (See second screenshot) 

### Expected Behavior

The used solver should be "cvode" and this should be listed in the both logging outputs correctly.
Maybe this example is too simple and OMEdit thus uses a simpler solver on its own. However, this also happened for complex models using our BRSL library.

### Screenshots

Will be added by my colleague @niklwors in a comment.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-278-ge7b7ec3ee1 (64-bit) with instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/195f5c38-c39a-40ff-8128-c87bfe1c7cf5)

**Comment by adeas31** [comment]
@AnHeuermann can you please take a look at this?

OMEdit correctly calls `translateModel` with `cvode` and passes it to the simulation executable. Still `euler` is listed in the simulation stats.

**Comment by AnHeuermann** [comment]
The `simulationOptions` record is already wrong. Or at least `method=dassl` is outputted before `initRuntimeAndSimulation` is called in the C runtime. I think `record SimulationResult` is set in the frontedn.

But then I can't really see where
```
LOG_SOLVER        | info    | overwrite solver method: cvode [from command line]
LOG_SOLVER        | info    | Allocated simulation result data storage for method 'mat' and file='Solvermethod_res.mat'
LOG_SOLVER        | info    | No states present, continuing without ODE solver.
LOG_SOLVER        | info    | recognized solver: euler
```
is coming from. I'll see if gdb can help me here.

**Comment by casella** [comment]
If there are no state variables and the model is fully causalized (i.e. you are not using daeMode to solve it), there is no need to use an ODE solver to solve the ODEs, because there aren't any.

In this case, the euler solver is used by default. It basically just computes the output equations at each time step, since there are no state equations.

@abuntrock maybe we should state this somewhere in the User's Guide? If so, where?

**Comment by abuntrock** [comment]
@casella Thanks for the explanation. I will think about your suggestion regarding the UserGuide. But isn't the output of the CLI command wrong then? Because there `dassl` is listed instead of `euler`. (For more complicated models when the log after the simulate button shows `cvode`, the output of the command cli also shows `dassl` as the method

**Comment by casella** [comment]
I guess the solver override happens at low level, so the CLI is not aware of it. But, anyway, who cares about what the ODE solver is, if there are no ODEs? 😄

**Comment by abuntrock** [comment]
Yeah the example here is too easy but this also happens for our BRSL testcases and there we have code that uses the CLI and reads the used method, which is wrong then. I will post another example where no euler is used.

**Comment by abuntrock** [comment]
The following model (still easy but with ODEs) is probably a better example then: 
```modelica
model Solvermethod2
  Modelica.Blocks.Continuous.PI PI(k = 1, T = 0.1, initType = Modelica.Blocks.Types.Init.InitialState) annotation(
    Placement(visible = true, transformation(origin = {-10, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Pulse pulse(amplitude = 1, period = 0.25) annotation(
    Placement(visible = true, transformation(origin = {-70, 30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(pulse.y, PI.u) annotation(Line(points = {{-58, 30}, {-22, 30}}, color = {0, 0, 127}));
  annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-06, Interval = 0.002),
    __OpenModelica_simulationFlags(s = "cvode"));
end Solvermethod2;
``` 
When simulating this model with the green simulation button the output shows `cvode` as the solver. When simulating the model with the command CLI the displayed method is `dassl` (`cvode` is only listed in the simflags section).

**Comment by abuntrock** [comment]
Understood. The displayed method is only correct, when I use `simulate(Solvermethod2, method="cvode")` and the annotation does not influence the displayed method because the overriding of the default method by `simflags = '-s=\\'cvode\\''` only happens internally. This makes the parsing of the actually used method harder for us because we do not need any other information from `lv=LOG_STATS`. But if #11096 is not existing, parsing the additional output is the only way to go for us. Thanks for the answer.

**Comment by casella** [comment]
See comment in #11096.
