### ISSUE TITLE
Missing API call "getSolverMethod"

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11096]
### Description

This ticket is related to #11094. Currently there seems to be no OpenModelica scripting call to retrieve the solver method given a class path. 

### Steps to Reproduce

1. Consider the following modelica model
```modelica
model Solvermethod
  Modelica.Blocks.Sources.Ramp ramp(height = 5, duration = 1, offset = 1, startTime = 0)  annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

annotation(uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-6, Interval = 0.002),
  __OpenModelica_simulationFlags(s = "cvode"));
end Solvermethod;
```
2. There seems to be no OpenModelica scripting method to retrieve the desired solver method (in this example `cvode`) using the class path. The call `getSimulationOptions(Solvermethod)` only retrieves the parts of the experiment annoation specified in the modelica specification (Start time, stop time, tolerance, number of intervals and step size). 

### Expected Behavior

There is an OpenModelica scripting method to retrieve the solver method given a class path.
Either a standalone one or the method `getSimulationOptions` is extended by another output.

### Version and OS

 - OpenModelica Version: v1.22.0-dev-278-ge7b7ec3ee1 (64-bit) with instance API
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by abuntrock** [comment]
If the method after simulating with the command CLI is correct (I added a comment in #11094 regarding this), this ticket here is not important anymore.

**Comment by casella** [comment]
I guess the problem is, the runtime solver ultimately decides which solver to use, based on flags and on the presence of state variables. I'm not sure OMC is really aware of that.

I would suggest to fetch this information from LOG_STATS. That's the safest option.

**Comment by casella** [comment]
@AnHeuermann maybe you can comment on this issue as well.

**Comment by AnHeuermann** [comment]
I guess we could create a scripting function to retrieve the information from `__OpenModelica_simulationFlags`, including the solver method. It should be very similar to `getSimulationOptions`.

But having a scripting API function that knows what the runtimes (C or C++) will do with said flag is bit tricky. The Backend can't communicate with the simulation runtimes or more precisely the runtime can only say what it will do when the model is already build. I think the runtimes are looking at some xml files to get these `__OpenModelica_simulationFlags` and then decide on those and the other specified flags what solver to use. But apparently there is a bug somewhere in this as mentioned in https://github.com/OpenModelica/OpenModelica/issues/11094.

**Comment by casella** [comment]
I still think using LOG_STATS is the simplest option.

**Comment by abuntrock** [comment]
It seems complicated otherwise. So I will have to parse this information from LOG_Stats.
