### ISSUE TITLE
Missing variable description in plotting window when using encrypted components

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11107]
### Description

When a class from an encrypted library is used inside a model all description strings disappear from the plotting window. 
Since you do not have an encrypted BRSL version available right now, you are hopefully able to recreate this behavior with another encrypted class since the behavior does not seem to be BRSL specific. If not, please let us know.

### Steps to Reproduce

1. Simulate the following very simple model. The parameter and the variable are both displayed in the plotting window together with their description as shown in the first screenshot.
```modelica 
model ResultDescriptions

parameter Real realParameter = 5 "This is a real parameter";
Real resultVariable "This is a result description";

equation
  resultVariable = realParameter*time;
end ResultDescriptions;
```
2. Add any class from the BRSL (in my example a hydraulic tank) to the model from step 1 and simulate again. The plotting window from step 1 is extended by the tank. All description strings are displayed as shown in the second screenshot.
```modelica 
model ResultDescriptions

parameter Real realParameter = 5 "This is a real parameter";
Real resultVariable "This is a result description";
Rexroth_BRSL.Generic.Hydraulics.Sources.Tank tank_1 annotation(
  Placement(visible = true, transformation(origin = {0, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

equation
  resultVariable = realParameter*time;
  annotation(uses(Modelica(version = "4.0.0"), Rexroth_BRSL(version = "3.0.0")));
end ResultDescriptions;
```
3. Simulate the exact same model from step 2 but with an encrypted BRSL library loaded. No description strings are displayed at all as shown in the third screenshot. Even the description strings of `realParameter` and `resultVariable` have vanished despite them having no "connection" to the encrypted tank.

### Expected Behavior

The description strings are present in the plotting window even if a used class is encrypted. 

### Screenshots

My colleague @niklwors will add the screenshots in a comment.  

### Version and OS

 - OpenModelica Version for: v1.22.0-dev-255-gdedd489acd (64-bit)
 - OS: Windows 10, 64 bit

Thanks for considering this
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
picture 1:
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/336ce7fc-98c3-4de4-9f23-a460b70e68d2)

picture 2:
![image002](https://github.com/OpenModelica/OpenModelica/assets/12269776/e9c2b33b-3da2-47ff-8521-871dd35267fc)

**Comment by casella** [comment]
@adeas31, @perost I'm not sure whether the information is lost by the frontend or by OMEdit, can you please check and fix this?

**Comment by adeas31** [comment]
I think this is because we don't dump the descriptions in the `model_init.xml` file for encrypted classes.

We should dump the descriptions based on the protection annotation. If the protection is `Access.icon` or higher then just dump the descriptions.

**Comment by adeas31** [comment]
@phannebohm can you please take a look at it?

**Comment by casella** [comment]
@perost please check if the comments are removed by the front-end already, in which case it will be an NF issue

**Comment by perost** [comment]
#11487 should hopefully fix the issue. Previously we removed all comments when there were encrypted libraries present, now we instead use the Protection annotation to determine whether to remove comments from variables or not.

I haven't tested it with an encrypted library, maybe @adeas31 could do that, but the only difference between an encrypted and not encrypted library in this regard is the default access level.

**Comment by adeas31** [comment]
> I haven't tested it with an encrypted library, maybe @adeas31 could do that, but the only difference between an encrypted and not encrypted library in this regard is the default access level.

It works now. @perost can you please port this to 1.22

**Comment by perost** [comment]
> > I haven't tested it with an encrypted library, maybe @adeas31 could do that, but the only difference between an encrypted and not encrypted library in this regard is the default access level.
> 
> It works now. @perost can you please port this to 1.22

#11496

**Comment by abuntrock** [comment]
This apparently even made it into the 1.22.0 release. Thank you very much
