### ISSUE TITLE
External Object alias replacement

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#11114]
### Description

I'm investigating, why the model `ClaRa.Components.VolumesValvesFittings.Pipes.Check.TwoPhaseFlow.Test_Pipe_L4_Advanced` is initialized wrong.
I noticed, that a TILMedia function is called and the result seems odd:

```C
/*
equation index: 2906
type: SIMPLE_ASSIGN
tube.mechanicalEquilibrium.rho_mix[40] = TILMedia.Internals.VLEFluidConfigurations.FullyMixtureCompatible.VLEFluidObjectFunctions.density_phxi(tube.p[40], tube.h[40], {}, tube.iCom.fluidPointer[40])
*/
void ClaRa_Components_VolumesValvesFittings_Pipes_Check_TwoPhaseFlow_Test_Pipe_L4_Advanced_eqFunction_2906(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,2906};
  (data->localData[0]->realVars[2601] /* tube.mechanicalEquilibrium.rho_mix[40] variable */) = omc_TILMedia_Internals_VLEFluidConfigurations_FullyMixtureCompatible_VLEFluidObjectFunctions_density__phxi(threadData, (data->localData[0]->realVars[2642] /* tube.p[40] DUMMY_STATE */), (data->localData[0]->realVars[79] /* tube.h[40] STATE(1) */), _OMC_LIT6, (data->simulationInfo->extObjs[87]));
  TRACE_POP
}
```

The result `tube.mechanicalEquilibrium.rho_mix[40]` is -1 instead of something around `708.3` which Dymola is reporting at initialization.
This is also triggering asserts:

```LOG_ASSERT        | warning | [/path/to/ClaRa-official/ClaRa/Basics/ControlVolumes/Fundamentals/SpacialDistribution/Homogeneous_L4.mo:7:3-7:64:writable]
|                 | |       | The following assertion has been violated at time 0.000000
|                 | |       | ((tube.mechanicalEquilibrium.rho_mix[40] >= 0.0)) --> "Variable violating min constraint: 0.0 <= tube.mechanicalEquilibrium.rho_mix[40], has value: -1"
```

Now I have several questions:

- Is this an error code from TILMedia?
- Is the external object not initialized correctly?
- Is this the expected result?
- Is the C code function prototype missing, like in https://github.com/OpenModelica/OpenModelica/issues/9249?

### Steps to Reproduce

```
loadModel(ClaRa, {"1.8.1"}); getErrorString();
simulate(ClaRa.Components.VolumesValvesFittings.Pipes.Check.TwoPhaseFlow.Test_Pipe_L4_Advanced, stopTime=0.0); getErrorString();
```

### Version and OS

 - OpenModelica Version: 
 - OS: Ubuntu Focal
 - ClaRa: 1.8.1(from https://github.com/xrg-simulation/ClaRa-official)
 - TILMedia 1.8.1 ClaRa (from https://github.com/xrg-simulation/ClaRa-official)

### Additional Context

Related to https://github.com/OpenModelica/OpenModelica/issues/10980.

**Comment by AnHeuermann** [comment]
Looks like the constructor of external object `tube.iCom.fluidPointer[40]` is missing, but we have

```C
/*
equation index: 4670
type: SIMPLE_ASSIGN
massFlowSink.fluidOut.vleFluidPointer = TILMedia.Internals.TILMediaExternalObject.constructor("VLEFluid", "Interpolation.LoadSpline(filename=\"/home/aheuermann/workspace/libraries/ClaRa-official/TILMedia 1.8.1 ClaRa/Resources/TILMediaDataPath/WATER_SPLINE.DAT\")", massFlowSink.fluidOut.computeFlags, {}, 1, 0, "Test_Pipe_L4_Advanced.massFlowSink.fluidOut")
*/
OMC_DISABLE_OPT
static void ClaRa_Components_VolumesValvesFittings_Pipes_Check_TwoPhaseFlow_Test_Pipe_L4_Advanced_eqFunction_4670(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,4670};
  (data->simulationInfo->extObjs[0]) = omc_TILMedia_Internals_TILMediaExternalObject_constructor(threadData, _OMC_LIT39, _OMC_LIT40, (data->simulationInfo->integerParameter[2] /* massFlowSink.fluidOut.computeFlags PARAM */), _OMC_LIT6, ((modelica_integer) 1), ((modelica_integer) 0), _OMC_LIT46);
  TRACE_POP
}
```

It's coming from `ClaRa.Basics.Records.IComVLE_L3`

```
TILMedia.Internals.TILMediaExternalObject fluidPointer[N_cv] "|System||Fluid pointer of outlet ports" annotation(Dialog(tab="System"));
```

**Comment by AnHeuermann** [comment]
Frontend:
```
protected TILMedia.Internals.TILMediaExternalObject tube.iCom.fluidPointer[1];
[...]
protected TILMedia.Internals.TILMediaExternalObject tube.iCom.fluidPointer[40];
[...]
tube.iCom.fluidPointer = {tube.fluid[1].vleFluidPointer, tube.fluid[2].vleFluidPointer, tube.fluid[3].vleFluidPointer, tube.fluid[4].vleFluidPointer, tube.fluid[5].vleFluidPointer, tube.fluid[6].vleFluidPointer, tube.fluid[7].vleFluidPointer, tube.fluid[8].vleFluidPointer, tube.fluid[9].vleFluidPointer, tube.fluid[10].vleFluidPointer, tube.fluid[11].vleFluidPointer, tube.fluid[12].vleFluidPointer, tube.fluid[13].vleFluidPointer, tube.fluid[14].vleFluidPointer, tube.fluid[15].vleFluidPointer, tube.fluid[16].vleFluidPointer, tube.fluid[17].vleFluidPointer, tube.fluid[18].vleFluidPointer, tube.fluid[19].vleFluidPointer, tube.fluid[20].vleFluidPointer, tube.fluid[21].vleFluidPointer, tube.fluid[22].vleFluidPointer, tube.fluid[23].vleFluidPointer, tube.fluid[24].vleFluidPointer, tube.fluid[25].vleFluidPointer, tube.fluid[26].vleFluidPointer, tube.fluid[27].vleFluidPointer, tube.fluid[28].vleFluidPointer, tube.fluid[29].vleFluidPointer, tube.fluid[30].vleFluidPointer, tube.fluid[31].vleFluidPointer, tube.fluid[32].vleFluidPointer, tube.fluid[33].vleFluidPointer, tube.fluid[34].vleFluidPointer, tube.fluid[35].vleFluidPointer, tube.fluid[36].vleFluidPointer, tube.fluid[37].vleFluidPointer, tube.fluid[38].vleFluidPointer, tube.fluid[39].vleFluidPointer, tube.fluid[40].vleFluidPointer};
```
and
```
parameter TILMedia.Internals.TILMediaExternalObject tube.fluid[1].vleFluidPointer = TILMedia.Internals.TILMediaExternalObject.constructor("VLEFluid", tube.fluid[1].vleFluidType.concatVLEFluidName, tube.fluid[1].computeFlags, {}, 1, 0, "Test_Pipe_L4_Advanced.tube.fluid");
```

We have constructor calls for these `vleFluidPointers` in the generated C code:

```C
tube.fluid[1].vleFluidPointer = TILMedia.Internals.TILMediaExternalObject.constructor("VLEFluid", "Interpolation.LoadSpline(filename=\"/home/aheuermann/workspace/libraries/ClaRa-official/TILMedia 1.8.1 ClaRa/Resources/TILMediaDataPath/WATER_SPLINE.DAT\")", tube.fluid[1].computeFlags, {}, 1, 0, "Test_Pipe_L4_Advanced.tube.fluid")
```

So I guess the alias replacement in the Backend is missing to remove/replace the external objects.

**Comment by AnHeuermann** [comment]
In `12.9.7 External Objects` of the [Modelica Standard 3.6](https://specification.modelica.org/maint/3.6/MLS.pdf) there is a section about alias equations of external objects:

> -  Only the constructor may return external objects and an external object can only be bound in
component declarations and neither modified later nor assigned to.
[It follows that a function cannot return a component containing an external object, since only the
constructor may return an external object and the constructor exactly returns the external object.]

My understanding is, that it is not allowed to do something like

```modelica
  parameter TILMedia.Internals.TILMediaExternalObject vleFluidPointer;
  TILMedia.Internals.TILMediaExternalObject fluidPointer[1];
equation
  vleFluidPointer = TILMedia.Internals.TILMediaExternalObject([...]);
  fluidPointer[0] = vleFluidPointer;
```

In a model inside the testsuite we are also issuing a warning like 
```
Warning: Alias equations of external objects are not Modelica compliant as in:
    addBoolean.pkgOut[1].pkg = resetPointer.pkgIn.pkg
    getBoolean.pkgIn.pkg = getInteger.pkgOut[1].pkg
    addBoolean.pkgIn.pkg = addInteger.pkgOut[1].pkg
    getInteger.pkgIn.pkg = unpackInt1.pkgOut[1].pkg
    unpackInt.pkgOut[1].pkg = unpackInt1.pkgIn.pkg
    resetPointer.pkgOut[1].pkg = unpackInt.pkgIn.pkg
    addInteger.pkgIn.pkg = packInt1.pkgOut[1].pkg
    packInt.pkgOut[1].pkg = packInt1.pkgIn.pkg
    packInt.pkgIn.pkg = packager.pkgOut.pkg
    addBoolean.pkgOut[1].pkg = addBoolean.pkgIn.pkg
    unpackInt1.pkgOut[1].pkg = unpackInt1.pkgIn.pkg
    getInteger.pkgOut[1].pkg = getInteger.pkgIn.pkg
    unpackInt.pkgOut[1].pkg = unpackInt.pkgIn.pkg
    resetPointer.pkgOut[1].pkg = resetPointer.pkgIn.pkg
    packInt1.pkgOut[1].pkg = packInt1.pkgIn.pkg
    addInteger.pkgOut[1].pkg = addInteger.pkgIn.pkg
    packInt.pkgOut[1].pkg = packInt.pkgIn.pkg
```

I guess the `getExternalObjectAlias` is missing this alias equation because of the `extends` and array of records structure.

**Comment by casella** [comment]
Do you mean it is a problem with the library?

**Comment by AnHeuermann** [comment]
I'm not sure if the way the external object is defined is allowed or not, but if not it would be an issue in ClaRa.

I'm going to investigate with @kabdelhak if we can handle the alias equations in the Backend.

**Comment by CSchulzeTLK** [comment]
I remember, that we had a discussion about these external object aliases. Most tools seemed to allow them, and nobody questioned them. TIL library avoids these assignments. However, ClaRa library passes the external objects to submodels in records to reuse the cached values, also for rarely used properties.

In the example above the variability changes from parameter to continuous. IMHO this means, it is not an alias.

**Comment by casella** [comment]
> I remember, that we had a discussion about these external object aliases. Most tools seemed to allow them, and nobody questioned them.

What does the Modelica Language specification say about it?

**Comment by CSchulzeTLK** [comment]
AnHeuermann already identified the relevant text. https://github.com/modelica/ModelicaSpecification/issues/540. It seems only records and constructor wrappers had been in discussion.

I think the spec. could be interpreted as follows:
- Only the constructor can "return" external objects (i.e. no other function is allowed to do that, such as a record constructor)
- Can only be assigned in a binding equation (i.e. neither equation nor algorithm)

This IMHO means, that a binding equation is allowed, which "copies" the values. It is a binding equation, and it is not something "returning" the external object, and it is not modifying the external object. A pure assignment in a binding equation seems to be allowed.

**Comment by casella** [comment]
Seems reasonable to me. To summarize, what it the status with OMC supporting alias external objects?

**Comment by casella** [comment]
In the meantime PR #11429 got [20+ more models working in ClaRa](https://libraries.openmodelica.org/branches/history/master/2023-10-23%2023:17:30..2023-10-24%2023:40:02.html). Very good!

Can this issue be considered fixed? I guess so. Maybe you could open another one as a reminder for non-trivial alias equations?

**Comment by ceraolo** [comment]
> In the meantime PR #11429 got [20+ more models working in ClaRa](https://libraries.openmodelica.org/branches/history/master/2023-10-23%2023:17:30..2023-10-24%2023:40:02.html). 

EHPTlib examples have worsened, I don' know why, since it does not use external objects.
I'll try to check one of the next days

**Comment by ceraolo** [comment]
This pr seems to have caused some regressions, see #11462
