### ISSUE TITLE
Enhancement: Diagram nodes when connections meet

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11115]
### Description

A graphical distinction between "merging" and "crossing" lines on the diagram layer would be helpful. 

### Steps to Reproduce

Look at the diagram layer of the following class 
```modelica
model ConnectionNodes
  Modelica.Blocks.Sources.Ramp ramp annotation (Placement(transformation(extent={{-60,20},{-40,40}})));
  Modelica.Blocks.Continuous.Integrator integrator annotation (Placement(transformation(extent={{60,20},{80,40}})));
  Modelica.Blocks.Continuous.FirstOrder firstOrder annotation (Placement(transformation(extent={{60,-20},{80,0}})));
  Modelica.Blocks.Sources.Constant const annotation (Placement(transformation(extent={{-58,60},{-38,80}})));
  Modelica.Blocks.Continuous.PI PI annotation (Placement(transformation(extent={{0,-60},{20,-40}})));
equation
  connect(ramp.y, integrator.u) annotation (Line(points={{-39,30},{58,30}}, color={0,0,127}));
  connect(firstOrder.u, ramp.y) annotation (Line(points={{58,-10},{-30,-10},{-30,30},{-39,30}}, color={0,0,127}));
  connect(PI.u, const.y) annotation (Line(points={{-2,-50},{-8,-50},{-8,70},{-37,70}}, color={0,0,127}));
  annotation (uses(Modelica(version="4.0.0")));
end ConnectionNodes;
```
In OMEdit this diagram layer looks as presented in the first screenshot. The desired behavior, which exists in Dymola, is shown in the second screenshot (highlighted in yellow). The output of the `ramp` block is connected to the inputs of the `integrator` and `firstOrder` blocks. At the point where the line starting from the `ramp` splits, a "graphical" node could be placed. This would make a distinction between Meeting (converging) and crossing lines easier.

### Expected Behavior

A node is added to the diagram layer when two lines converge, which share one endpoint.

### Screenshots

My colleague @niklwors will add the screenshots as a comment 

### Version and OS

 - OpenModelica Version: v1.22.0-dev-278-ge7b7ec3ee1 (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for considering this
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
picture 1:
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/9e4243ef-6098-4c8d-8aa7-6bafe49b3066)

picture 2:
![image002](https://github.com/OpenModelica/OpenModelica/assets/12269776/741684dc-9258-4ac1-8760-b56883732897)

**Comment by casella** [comment]
I agree. I'm not sure how difficult this would be. @adeas31, does Qt provide the primitives to handle this, without the need of programming it from scratch?

**Comment by adeas31** [comment]
The connection from `const` to `PI` is also converging with other 2 connections but no nodes are shown there.

**Comment by abuntrock** [comment]
I was probably not clear with my wording but to connection from `const` to `PI` only crosses the other connections but does not "converge/meet/fusions" with them. Thus, there should be no node at those points. Dymola indicates this by adding a little whitespace between those crossing lines.

**Comment by adeas31** [comment]
PR #11186 tries to fix this issue.

I am not sure what Dymola is doing as I found cases where it doesn't work so well.

I based my implementation on connections that have a common start or end connectors. And if such connections converge/intersect then we draw a node otherwise just a whitespace between the crossing lines.

**Comment by abuntrock** [comment]
@adeas31 That sounds really nice. Thanks a lot.

**Comment by casella** [comment]
> PR #11186 tries to fix this issue.
> 
> I am not sure what Dymola is doing as I found cases where it doesn't work so well.
> 
> I based my implementation on connections that have a common start or end connectors. And if such connections converge/intersect then we draw a node otherwise just a whitespace between the crossing lines.

That's one option, but it leads to some artefacts, see [#4645](https://github.com/OpenModelica/OpenModelica/issues/4645#issuecomment-1721573148). Ideally we should consider all connections that belong to the same connection set. The front end know who they are, so it shouldn't be hard to pass this information to OMEdit.

@perost what do you think?

**Comment by perost** [comment]
> > PR #11186 tries to fix this issue.
> > I am not sure what Dymola is doing as I found cases where it doesn't work so well.
> > I based my implementation on connections that have a common start or end connectors. And if such connections converge/intersect then we draw a node otherwise just a whitespace between the crossing lines.
> 
> That's one option, but it leads to some artefacts, see [#4645](https://github.com/OpenModelica/OpenModelica/issues/4645#issuecomment-1721573148). Ideally we should consider all connections that belong to the same connection set. The front end know who they are, so it shouldn't be hard to pass this information to OMEdit.
> 
> @perost what do you think?

That might be a lot of work, the connection handling works on the flat model but the instance API doesn't flatten the model. It also works on connector primitives rather than the connectors themselves, so tracing the sets back to the connections isn't entirely trivial.

**Comment by casella** [comment]
> That might be a lot of work, the connection handling works on the flat model but the instance API doesn't flatten the model.

I see. On the other hand, the connection handling does a lot more things than just identifying the connection sets, which we don't need.

Maybe what @adeas31 could do is, instead of looking for connections starting from the same connector, is to look for top-level connection sets. But I guess this is not urgent, I'll open a separate ticket for that.

**Comment by adeas31** [comment]
What do you mean by same connection set and top level connections?

**Comment by casella** [comment]
Let's continue the discussion in #11194 😃

**Comment by abuntrock** [comment]
Thanks a lot for the quick fix of this issue. I never expected this in this short time frame.

**Comment by casella** [comment]
The "proper" solution would have been quite complicated, because it would have required to change fundamental data structures in the code. We settled down on some simple heuristics (paint the white border of the connections stopping a bit short of the connectors9 that seems to do the job.
