### ISSUE TITLE
Incorrect component name in dialogue of nested replaceables

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11119]
### Description

When opening a sub-dialogue of a replaceable definition with the new edit button the displayed component name is `classInstanceName.replName`, which is correct. However, when you have nested replaceable definitions, the displayed component name is not extended correctly. 

### Steps to Reproduce

1. Consider the following modelica package:
```modelica
package PackageForTesting
    model ClassWithInstance
     TopLevelClass topLevelClass annotation(
      Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end ClassWithInstance;

  model TopLevelClass
   replaceable PackageForTesting.SubLevel1 replModel;
  end TopLevelClass;

  model SubLevel1
   parameter Real modelParameter = 5;
   replaceable parameter PackageForTesting.SubLevel2 replParam;
  end SubLevel1;

  record SubLevel2
   parameter Real recordParameter = 5;
  end SubLevel2;
end PackageForTesting;
```
2. Open the parameter dialogue of the class instance `topLevelClass` in the class `ClassWithInstance`.
3. Open the sub-dialogue of `topLevelClass.replModel` via the Edit button. The component name is correctly displayed, which can be seen in the first screenshot. 
4. Open the nested sub-dialogue of `topLevelClass.replModel.replParam` via the Esdit button next to `replParam`. The component name is displayed as `replParam` instead of `topLevelClass.replModel.replParam`, which is shown in the second screenshot. 

### Expected Behavior

The component name in the second sublevel parameter dialogue should be `topLevelClass.replModel.replParam` instead of `replParam`.

### Screenshots

My colleague @niklwors will add the screenshots as a comment. 

### Version and OS

 - OpenModelica Version: v1.22.0-dev-278-ge7b7ec3ee1 (64-bit)
 - OS: Windows 10, 64 bit

Thanks for considering this
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@perost, @adeas31, one more issue to consider before shipping 1.22.0.

**Comment by abuntrock** [comment]
If its only a visualization issue and hard to fix its not of utmost importance to us that this is fixed for 1.22

**Comment by casella** [comment]
OK, removed from the list of urgent stuff for 1.22.0

**Comment by adeas31** [comment]
Fixed with #11911

**Comment by adeas31** [comment]
Keep it open until ported to 1.22.2

**Comment by adeas31** [comment]
Ported to 1.22.2 with PR #11982
