### ISSUE TITLE
installer fails with wrong path: windows 1.21 openmodelica-latest.exe and openmoedlica-v1.21.0-64bit.exe

### ISSUE THREAD

**Issue by CThuleHansen** [OpenModelica/OpenModelica#11122]
# Description
During the installation process of https://build.openmodelica.org/omc/builds/windows/releases/1.21/0/64bit/OpenModelica-latest.exe OR https://build.openmodelica.org/omc/builds/windows/releases/1.21/0/64bit/OpenModelica-v1.21.0-64bit.exe
I choose the destination folder: `C:\Program Files\OpenModelica1.21.0-64bit`.
![image](https://github.com/OpenModelica/OpenModelica/assets/3479481/aa813f3f-c438-4b53-81a0-10a4a630ef9f)

Click Next
Choose Start Menu Folder
Click Install
And then I get the following issue:
![image](https://github.com/OpenModelica/OpenModelica/assets/3479481/c73f84ec-c4cd-419d-9452-598fe8116798)

# Version and OS

 - OS: [e.g. Windows 10, 64 bit]

**Comment by adeas31** [comment]
That is weird. Have you tried running the installer again or downloading a new installer file?

**Comment by CThuleHansen** [comment]
Yes. It is an issue for both 
https://build.openmodelica.org/omc/builds/windows/releases/1.21/0/64bit/OpenModelica-latest.exe and https://build.openmodelica.org/omc/builds/windows/releases/1.21/0/64bit/OpenModelica-v1.21.0-64bit.exe
I also tried https://build.openmodelica.org/omc/builds/windows/releases/1.20/0/64bit/OpenModelica-v1.20.0-64bit.exe
with the same result

**Comment by CThuleHansen** [comment]
Does it work for you? Because then it might be some corporate stuff...

**Comment by adeas31** [comment]
Yes it does work for me.

**Comment by casella** [comment]
@CThuleHansen did you have some undeleted file on that path, perhaps?

**Comment by CThuleHansen** [comment]
It was some corporate stuff. It worked on my own laptop, and today it worked at my company as well. 

Thanks, sorry for all the fuss

**Comment by casella** [comment]
Corporate stuff 😄
