### ISSUE TITLE
Using Recursive class will crash.

### ISSUE THREAD

**Issue by benben233** [OpenModelica/OpenModelica#11126]
using Recursive class will crash.
```
model test
test t;
end test;
```

_Originally posted by @benben233 in https://github.com/OpenModelica/OpenModelica/issues/4121#issuecomment-1707518561_

**Comment by perost** [comment]
Fixed in #11127, at least using the new API (Options->General->Enable instance API). It still crashes when using the old API, but that's a lot harder to fix and we'll be switching to the new API as default soon enough anyway.

**Comment by casella** [comment]
@perost I guess the general problem in #4121 remains open, right? Probably not high priority compared to more urgent stuff, but worth considering.

**Comment by perost** [comment]
> @perost I guess the general problem in #4121 remains open, right? Probably not high priority compared to more urgent stuff, but worth considering.

Yes, the issue in #4121 is actually a MetaModelica issue that will likely never be fixed and is unrelated to this issue.

**Comment by casella** [comment]
Maybe we could mark #4121 as "wontfix" since it's too hard?
