### ISSUE TITLE
The simulation progress bar should reflect the actual outcome in case of failure

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11128]
### Description

Consider the two test cases in the following MWE:
```modelica
package Failures
  model M1
    Real x(start = 1);
  initial equation
    x^2 + 1 = 0;
  equation
    der(x) = -x;
  end M1;
  model M2
    Real x(start = 1, fixed = true);
  equation
    der(x) = -1/(x - 0.5);
  annotation(experiment(StopTime=1));
  end M2;
end Failures;
```
The first model already fails at initialization. The second model fails after 0.12 s of simulation. However, in both cases the simulation progress bar shows a very reassuring 100% green bar
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/db26caa6-bc2a-4e77-a7c6-b8ad25d1210a)
One has to look into the textual log to figure out that, in fact, the simulation failed at some point. This is really misleading and inconvenient.

### Expected Behavior

In both cases, I would expect to get immediate visual feedback about the possible bad outcome of the simulation from the progress bar. Specifically, for both models I'd expect to see something in red in the simulation bar, not green. 

For M1, I'd expect to an empty bar with 0% indication, since it failed before even started. For M2, I'd expect to see a red bar at 12%, which is the point where the simulation managed to proceed before failing.

@adeas31 this would be nice to have in 1.22.0 if it's a quick development, otherwise let's keep it for the next release.

**Comment by adeas31** [comment]
Unfortunately, it is not possible to change the color of the progressbar. The progressbar control is done using the style of the OS and playing with it will give weird results on different systems.

However, I changed the code so that we don't show 100% in case of failure.

The `M2` doesn't work as expected because the underlying simulation runtime sends progress status as 100%. Maybe @AnHeuermann  can help with this.

**Comment by casella** [comment]
> Unfortunately, it is not possible to change the color of the progressbar. The progressbar control is done using the style of the OS and playing with it will give weird results on different systems.

OK, never mind, that's not a big deal. The important thing is not to see a green 100% in case of failure.

> However, I changed the code so that we don't show 100% in case of failure.

Good.
 
> The `M2` doesn't work as expected because the underlying simulation runtime sends progress status as 100%. Maybe @AnHeuermann can help with this.

That's weird. @AnHeuermann any comment on your side?
