### ISSUE TITLE
Compilation and runtime problems when using `ExternalObject`

### ISSUE THREAD

**Issue by msmommer** [OpenModelica/OpenModelica#11151]
### Description

I've found what seems to be a cluster of bugs around `ExternalObject.`. I've reproduced it in the nightly build downloaded on the 7th of september (running on Windows 10 64 bit). It's a bit hard to describe, but in certain circumstances the compiler stops checking for correctness, and the generated code simply does not call the constructors.

I've attached a package showing the behavior, including the corresponding C code, in a Zip file.

The cases where I've found it involve two external objects where the second one depends on the first.

This code here for example compiles without issues, despite being obviously faulty (lines 6 and 7):

```
model BugTrigger2
  Real x(start = 0);
  Real y;

  // No checking of initializer arguments. This should probably not compile.
  SubExtern  esx(invisble=to_the_compiler, mx=emx, x=21);
  MainExtern emx(whatever=foo_bar);
equation
  der(x)=1;
  y = ExternFrob(esx, x);
end BugTrigger2;
```
Putting in a correct initialization does not work either, it results in a segfault (`Simulation process failed. Exited with code 0xffffffffc0000005.`) and does not call the constructors. This is in the model BugTrigger1 in the attached package.

### Version and OS

Versions where I've reproduced the bugs:

OpenModelica v1.21.0 64 bit (release version) + corresponding OMSimulator.

OpenModelica v1.22.0-dev-301-gdb2ff9a7aa (64-bit) with OMSimulator v2.1.1.post200-geaf993a-mingw-notlm

OS: Windows 10, 64 bit

[Somepack.zip](https://github.com/OpenModelica/OpenModelica/files/12563006/Somepack.zip)

**Comment by perost** [comment]
#11166 adds better error checking for external objects, and both of your examples now fail due to the modifiers. The correct way to initialize an external object is with e.g.:
```
MainExtern emx = MainExtern(x=21);
```
At least that's the only style mentioned in the specification. Changing your `BugTrigger1` model to use that style instead of using modifiers makes it simulate successfully, so I'll consider this issue fixed. Feel free to reopen the issue if you disagree.
