### ISSUE TITLE
Visible=someInstance.someParameter is not supported by OMEDit

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11182]
### Description

OMEdit seems to be unable to use variables from within an instance (via dot notation) in its graphic annotation's visible modifier. 

### Steps to Reproduce

1. Consider the following modelica package:
```modelica
package RecordParamInVisible
  model ClassWithInstance
    ClassWithReplaceable classWithReplaceable(replRecord(variant=1)) annotation (Placement(transformation(extent={{-12,40},{8,60}})));
    ClassWithReplaceable classWithReplaceable1(replRecord(variant=2)) annotation (Placement(transformation(extent={{-10,-60},{10,-40}})));
  end ClassWithInstance;

  model ClassWithReplaceable
    replaceable parameter RecordParamInVisible.SomeRecord replRecord;

    annotation (Icon(graphics={
          Text(
            extent={{-80,80},{80,20}},
            textColor={28,108,200},
            visible=replRecord.variant==1,
            textString="Variant 1"),
          Text(
            extent={{-80,-20},{80,-80}},
            textColor={28,108,200},
            visible=replRecord.variant==2,
            textString="Variant 2"),
          Rectangle(
            extent={{-100,100},{100,-100}},
            lineColor={28,108,200},
            lineThickness=0.5)}));
  end ClassWithReplaceable;

  model SomeRecord
    parameter Integer variant = 1;
  end SomeRecord;
end RecordParamInVisible;
```
2. Open the diagram view of `RecordParamInVisible.ClassWithInstance`.
3. Both instances (`classWithReplaceable` and `classWithReplaceable1`)  look the same in the diagram view.

### Expected Behavior

The instances look different in the diagram view of `RecordParamInVisible.ClassWithInstance`.
The icon of `classWithReplaceable` only includes the text "Variant 1".
The icon of `classWithReplaceable1` only includes the text "Variant 2".

### Version and OS

 - OpenModelica Version: v1.22.0-dev-317-g5a1f654c74 (64-bit) with Instance API
 - OS: Windows 10, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
@abuntrock this works as expected with the master. Please test again and report.

**Comment by abuntrock** [comment]
@adeas31 Looks good for me as well. Thanks for fixing this somewhere in the process.
