### ISSUE TITLE
Make a 1.22-dev.01 stable release

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11193]
We have completed the first batch of improvements required by @ceraolo, who is happy with 1.22.0-dev-341, i.e. bf24d825. He needs to have it installed in a classroom and keep it stable throughout the autumn semester.

@adrpo, could you please build a 1.22.0-dev.01 release with bf24d825 ASAP?

Thanks!

**Comment by ceraolo** [comment]
thank you

**Comment by casella** [comment]
In fact, 1.22.0-dev.01 is now superseded by 1.22.0

**Comment by casella** [comment]
You can still use 1.22.0-dev.01 under Windows, though 1.22.0 has some additional features in OMEdit.

**Comment by ceraolo** [comment]
In fact I had to intlstall OM before the beginning of the semester, so I did install dev341 successfully.  
Nevertheless I thank developpers for all their efforts.

**Comment by casella** [comment]
Please let us know if there is any quirk that pops up during the classroom use. We are always ready to provide round-the-clock fixes 😄
