### ISSUE TITLE
Make new instance API GUI the default in 1.22.0

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11208]
The new instance-based API interface for OMEdit is now quite good, and better than the old one in most cases, so it should become the default choice in 1.22.0. There should still be an option to disable it, just in case, but it should be off by default.

This could be a problem because we retain the settings from the previous installations, if there are any, so we can't change the default when one installs 1.22.0 after installing a previous version.

As suggested by @rfranke a simple solution to that is to change the name of the option. Currently we have Tools | Options | General | Optional Features "Enable instance API" which is off by default. We can remove that option (so that settings from previous versions are ignored) and replace it with "Disable new instance-based graphical editing of models", which should be off by default. I'll explain in the release notes what it means, but I guess it's important that "graphical editing" is mentioned, otherwise it's quite obscure.

@adeas31 please take care of that before we branch off 1.22.0-dev.beta1. Thanks!

**Comment by adeas31** [comment]
> I'll explain in the release notes what it means

We should also write some notes about it in the users guide here https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#general-options

**Comment by casella** [comment]
Great!
