### ISSUE TITLE
Crashed FMUs: infinite while loop

### ISSUE THREAD

**Issue by sturmk** [OpenModelica/OpenModelica#11229]
### Description
Given an FMU exported by OpenModelica. If it runs into trouble during exection (doStep/internalEventIteration) it tends to run into an infinite while loop, and does not exit, thereby hogging a lot of compute resources.

### Expected Behavior
If an FMU crashes, it should not run into an infinite loop, but rather return an "fmi2error" status code.

**Comment by casella** [comment]
@arun3688, @mahge could you give this a look?

**Comment by mahge** [comment]
Fixed in #11230.

**Comment by casella** [comment]
Will be available in the next nightly build.
