### ISSUE TITLE
Base (Flat) Modelica representation of constant array elements

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11242]
Consider the following MWE:
```modelica
model TestConstantArray
  constant Real[3] f = {1.0, 2.0, 3.5};
  Real[3] x;
  Real[3] y;
equation
  x = {time, 2*time, 10*time};
  for i in 1:3 loop
    y[i] = f[i]*x[i]^i;
  end for;
end TestConstantArray;
```
The current output of the NF with the `-f` flag is:
```modelica
model 'TestConstantArray'
  constant Real[3] 'f' = {1.0, 2.0, 3.5};
  Real[3] 'x';
  Real[3] 'y';
equation
  'x' = {time, 2.0 * time, 10.0 * time};

  for 'i' in 1:3 loop
    'y'['i'] = {1.0, 2.0, 3.5}['i'] * 'x'['i'] ^ 'i';
  end for;
end 'TestConstantArray';
```
which is not valid according to MLS 3.6, even from a purely syntactical standpoint.

The current draft of the Base Modelica ([formerly known as Flat Modelica](https://github.com/modelica/ModelicaSpecification/commit/1b34193434f6b3756cc6b042cee16179097c077c)) allows subscripting of general expressions, see [differences.md](https://github.com/modelica/ModelicaSpecification/blob/MCP/0031/RationaleMCP/0031/differences.md#subscripting-of-general-expressions), and amends the syntax to allow that as well.

As I understand, this would mean that the MWE posted above should be flattened as:
```modelica
model 'TestConstantArray'
  constant Real[3] 'f' = {1.0, 2.0, 3.5};
  Real[3] 'x';
  Real[3] 'y';
equation
  'x' = {time, 2.0 * time, 10.0 * time};

  for 'i' in 1:3 loop
    'y'['i'] = ({1.0, 2.0, 3.5})['i'] * 'x'['i'] ^ 'i';
  end for;
end 'TestConstantArray';
```
@perost, do I get it right? If so, could you please fix the output of the flat Modelica model in Base Modelica accordingly?

Keeping @mscuttari, @danielecattaneo in the loop.

**Comment by perost** [comment]
I just noticed that I placed the parentheses wrong and output e.g. `({1, 2, 3}['i'])` instead of the correct `({1, 2, 3})['i']`. #11448 fixes that mistake as part of implementing support for subscripted expressions.
