### ISSUE TITLE
OMEdit renders Modelica.Fluid.Interfaces.FluidPorts_b incorrectly

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#11247]
### Description

OMEdit incorrectly renders the fluid port as shown below.
![image](https://github.com/OpenModelica/OpenModelica/assets/1329080/f5d23749-9f38-4675-9ad2-562298301526)

This model is `Buildings.Fluid.Sources.Examples.MassFlowSource_WeatherData`.

### Steps to Reproduce

This has been tested with Buildings v9.0.0, v10.0.0 and the latest master of IBPSA 4f6e0dfb904d1d29fe2621b59033d18b9faf760c
The same rendering bug is also in `Modelica.Fluid.Examples.PumpingSystem`.

So this seem to be a bug that was introduced in a recent version of OMEdit.

### Expected Behavior

Properly render the port, see the static image in the `info` section of `Modelica.Fluid.Examples.PumpingSystem`.

### Screenshots

See above.

### Version and OS

OpenModelica 1.22.0~ dev-350-gc13196c
OMSimulator 2.1.1~236-g634b019-linux-notlm-debug

**Comment by bilderbuchi** [comment]
I've seen that, too. For a minimal repro, open `Modelica.Fluid.Examples.PumpingSystem`.

**Comment by casella** [comment]
@adeas31 please cherry-pick into maintenance/v1.22

**Comment by adeas31** [comment]
Done. See #11260
