### ISSUE TITLE
OMEdit - Diagram view response is very slow

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#11271]
### Description

The diagram view is not very responsive.

### Steps to Reproduce

Open any MSL model that contains several components and connections. Try to zoom in/out. The GUI response time is very slow.

### Expected Behavior

The GUI should be very quick for such operations.

### Additional Context

This is because of the collision detection code that was added for drawing the connection nodes.

**Comment by casella** [comment]
Good that you found it!

I guess the results of collision detection should be cached and reused when zooming.

**Comment by casella** [comment]
Please also port to maintenance/v1.22

**Comment by adeas31** [comment]
Done.
