### ISSUE TITLE
The gbode solver is broken

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11280]
The gbode solver is currently broken. Basically, most if not all simulations of dynamical systems (i.e. those that are not rerouted to euler because they have no states) currently fail, see e.g. [MSL](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html) or [Buildings](https://libraries.openmodelica.org/branches/gbode/Buildings_latest/Buildings_latest.html). Not even simple simulations such as [Modelica.Blocks.Examples.Filter](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Blocks.Examples.Filter.sim) work anymore.

I checked the [latest commits to gbode_main.c](https://github.com/OpenModelica/OpenModelica/commits/master/OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c) and I saw PR #10792, which took place on Jun 6. I installed OpenModelica-v1.22.0-dev-155-g28817ae75c-64bit.exe (Jun 3) and it works fine, while OpenModelica-v1.22.0-dev-160-gb8f9594377-64bit.exe (Jun 9) is broken already.

@AnHeuermann it looks like something in your PR broke gbode badly. This is a bad regression for 1.22.0, we need to fix it ASAP. If you can fix PR #10792 in a few days that would be excellent, otherwise I would suggest you to revert it both on master and on maintenance/v1.22, and then work it out on a new branch, while checking that simulations with gbode still work fine 😅 

I think we should also put some tests with gbode in the core testsuite, to avoid breaking it again.

Thanks!

**Comment by phannebohm** [comment]
> I checked the [latest commits to gbode_main.c](https://github.com/OpenModelica/OpenModelica/commits/master/OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c) and I saw PR #10792, which took place on Jun 6. I installed OpenModelica-v1.22.0-dev-155-g28817ae75c-64bit.exe (Jun 3) and it works fine, while OpenModelica-v1.22.0-dev-160-gb8f9594377-64bit.exe (Jun 9) is broken already.

Thanks for the search! Indeed #10792 seems to have been the source of the bug. I'd wait for the regression report and then port #11283 to maintenance/v1.22.

> I think we should also put some tests with gbode in the core testsuite, to avoid breaking it again.

Can you propose some small test models? We can definitely take some random samples from the MSL. I'd like to talk to @AnHeuermann next week for some representative models.

**Comment by casella** [comment]
Please cherry-pick this fix into maintenance/v1.22, otherwise the new release remains broken.

**Comment by casella** [comment]
> Can you propose some small test models? We can definitely take some random samples from the MSL. I'd like to talk to @AnHeuermann next week for some representative models.

I would add a few (working!) examples from Modelica.Blocks, MultiBody (including some free-flying examples with dynamic state selection), Fluid, and Clocked. That should be enough to stress the main parts of the algorithm.

**Comment by casella** [comment]
The fix seems to work well, gbode now simulates [500/514 models of MSL 4.0.0](https://libraries.openmodelica.org/branches/gbode/Modelica_4.0.0/Modelica_4.0.0.html) and [1502/1628 models of Buildings](https://libraries.openmodelica.org/branches/gbode/Buildings_latest/Buildings_latest.html).

Please port to maintenance/v1.22 now.

**Comment by casella** [comment]
As for testing, if we have some tests for IDA, we should do the same for GBODE, if not we should add both 😅

**Comment by phannebohm** [comment]
Turns out we do have some tests in [testsuite/simulation/modelica/solver/gbode](https://github.com/OpenModelica/OpenModelica/tree/da018ab11cbf7fc8e4e402f30221bbef49572f60/testsuite/simulation/modelica/solver/gbode) (btw we also do for IDA, in the parent folder). I guess we can look through those to see what's missing.

**Comment by casella** [comment]
Interesting. Why did they they pass the test in PR #10792?

**Comment by casella** [comment]
I opened #11303 on testting, so we can close this
