### ISSUE TITLE
Modelica-Buildings Library (master): Initialization problem is structural singular

### ISSUE THREAD

**Issue by Pavanrajhr** [OpenModelica/OpenModelica#11281]
### Description
The solver fails to solve system at initialization due to singular error. Iteration variable xloc[1] is nan.
The model which fails is given below:
```
Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus
```
The simulation is failing after the below update in the openmodelica library:
https://libraries.openmodelica.org/branches/history/master/2023-09-13%2013:38:18..2023-09-16%2020:01:22.html

On simulating the model in OpenModelica leads to following errors/warnings:
```
1) Homotopy solver total pivot: Matrix (nearly) singular at initialization.
2) residualFunc1198: Iteration variable xloc[1] is nan.
3) residualFunc1198 failed at time=0. For more information please use -lv LOG_NLS.
4) Homotopy solver total pivot: Matrix (nearly) singular at initialization.
5) The following assertion has been violated during initialization at time 0.000000 ((varSpeDX.eva.watVapEva.nomVal.gamma <= varSpeDX.eva.watVapEva.gammaMax)) --> "*** Warning: In DX coil model, gamma is too large for these coil conditions.     Instead of gamma = 1.5, a value of 0.346977, which     corresponds to a mass transfer effectiveness of 0.8, will be used.     Coil nominal performance data are:     nomVal.m_flow_nominal = 0.462462     dX_nominal = XEvaOut_nominal-XEvaWetBulOut_nominal = 0.00571197 - 0.00634552 = -0.000633544     QLat_flow_nominal  = -1689.5 "
6) Homotopy solver total pivot: Matrix (nearly) singular at initialization.
7) Homotopy solver total pivot: Matrix (nearly) singular at time 0.000000.
```

The log report for these models are as given below: (source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.sim)
```
LOG_NLS           | error   | residualFunc1198: Iteration variable xloc[1] is nan.
LOG_ASSERT        | debug   | residualFunc1198 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.
LOG_STDOUT        | warning | While solving non-linear system an assertion failed during initialization.
|                 | |       | | The non-linear solver tries to solve the problem that could take some time.
|                 | |       | | It could help to provide better start-values for the iteration variables.
|                 | |       | | For more information simulate with -lv LOG_NLS_V
LOG_NLS           | error   | residualFunc1198: Iteration variable xloc[6] is nan.
LOG_ASSERT        | debug   | residualFunc1198 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.
LOG_NLS           | error   | residualFunc1198: Iteration variable xloc[1] is nan.
LOG_ASSERT        | debug   | residualFunc1198 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.
LOG_ASSERT        | warning | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 11.0.0-master/Fluid/DXSystems/Cooling/BaseClasses/Evaporation.mo:185:3-194:27:writable]
|                 | |       | The following assertion has been violated during initialization at time 0.000000
|                 | |       | ((varSpeDX.eva.watVapEva.nomVal.gamma <= varSpeDX.eva.watVapEva.gammaMax)) --> "*** Warning: In DX coil model, gamma is too large for these coil conditions.
|                 | |       |     Instead of gamma = 1.5, a value of 0.346977, which
|                 | |       |     corresponds to a mass transfer effectiveness of 0.8, will be used.
|                 | |       |     Coil nominal performance data are:
|                 | |       |     nomVal.m_flow_nominal = 0.462462
|                 | |       |     dX_nominal = XEvaOut_nominal-XEvaWetBulOut_nominal = 0.00571197 - 0.00634552 = -0.000633544
|                 | |       |     QLat_flow_nominal  = -1689.5
|                 | |       | "
LOG_SUCCESS       | info    | The initialization finished successfully with 3 homotopy steps.
LOG_ASSERT        | info    | [/home/hudson/saved_omc/libraries/.openmodelica/libraries/Buildings 11.0.0-master/Fluid/DXSystems/Cooling/BaseClasses/Evaporation.mo:59:3-62:61:writable]
|                 | |       | The following assertion has been violated at time 17.280000
|                 | |       | ((varSpeDX.eva.watVapEva.m >= 0.0)) --> "Variable violating min constraint: 0.0 <= varSpeDX.eva.watVapEva.m, has value: -1.01942e-27"
LOG_NLS           | error   | residualFunc1801: Iteration variable xloc[1] is nan.
LOG_ASSERT        | debug   | residualFunc1801 failed at time=3600.00000036556.
|                 | |       | For more information please use -lv LOG_NLS.
LOG_STDOUT        | warning | While solving non-linear system an assertion failed at time 3600.
|                 | |       | | The non-linear solver tries to solve the problem that could take some time.
|                 | |       | | It could help to provide better start-values for the iteration variables.
|                 | |       | | For more information simulate with -lv LOG_NLS_V
.
.
.
repetitive errors
```

The list of warnings reported in the simulation test are given below: (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.err)
```
Warnings:
1) The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
2) Assuming fixed start value for the following 1 variables:
         varSpeDX.eva.watVapEva.off:DISCRETE(fixed = true protected = true final = true )  "Signal, true when component is off" type: Boolean
3)The initial conditions are over specified. The following 1 initial equations are redundant, so they are removed from the initialization system:
         varSpeDX.eva.vol.dynBal.medium.p = varSpeDX.eva.vol.dynBal.p_start.

Errors:
1) Initialization problem is structural singular. Please, check the initial conditions.
```

### Steps to Reproduce
Load the Modelica-Buildings master library (Source: https://github.com/lbl-srg/modelica-buildings/)
Simulate the model Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus

### Expected Behavior
The simulation should succeed.

### Version and OS
 - OpenModelica Version: OpenModelica 1.23.0~dev-2-ga714efa
 -  - OS: Ubuntu 20.04 focal
Versions of used Modelica libraries:
	Modelica 4.0.0
	Buildings 11.0.0

**Comment by casella** [comment]
We made a bit of research and the situation is pretty odd.
- Apparently, the test got broken _on the Linux CI_ [between Sep 13 and Sep 16](https://libraries.openmodelica.org/branches/history/master/2023-09-13%2013:38:18..2023-09-16%2020:01:22.html) (went from Verify to Simulate), either due to changes to OMC or to changes to Buildings during those three days
- We checked the model with the previous version of Buildings and a previous version of OMC _on Windows_, and it still fails with the same error, which is weird, because the old library and the old OMC were successful on Linux

My interpretation is that there was something not correct with uninitialized variables or pointers that worked on Linux by chance but caused OMC to fail on Windows. Then, some commits to OMC during those three days also caused it to fail on Windows, in the same way. The most likely candidate is @mahge's commit 2c8441d604.

@mahge could you perhaps try to compile OMC with and without that commit and check how Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus works in both cases?

Then, we can decide what is the best course of action.

**Comment by mahge** [comment]
#11177 changed how variables are used in the Linux Makefiles. It did not change anything in the simulation related code or in any actual code for that matter. The title of the PR could have been a bit clearer. 

The change in the PR meant that the compiler and flags used to compile some 3rdParty libraries got changed from always being `g++` to the specified compiler during configuration. Normally this should not cause any issues to simulation. However, we have seen before that these changes can cause some tests to behave differently. As you mentioned these t

If the test was failing on Windows already then it is likely that it already had issues.

> @mahge could you perhaps try to compile OMC with and without that commit and check how Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus works in both cases?

I will check.

**Comment by mahge** [comment]
In the meantime this is the regression history of the model:

http://libraries.openmodelica.org/branches/history/master/2023-09-13%2013:38:18..2023-09-16%2020:01:22.html
http://libraries.openmodelica.org/branches/history/master/2023-07-12%2022:38:33..2023-07-13%2012:38:39.html
http://libraries.openmodelica.org/branches/history/master/2023-07-01%2016:04:26..2023-07-01%2022:38:22.html
http://libraries.openmodelica.org/branches/history/master/2023-07-01%2009:25:16..2023-07-01%2014:10:34.html

There is not anything that looks useful though.

**Comment by mahge** [comment]
I have tried a commit before my changes with the Makefiles build plus a few other combinations (CMake based debug build, release build, using clang) and in all of them the model reports similar issues as reported here. I **have not** tried different version of the Buildings library though. I used the latest version `11.0.0-master` available through the package manager (The model does not exist in older versions I think).  

One thing I have noticed, however, is that after all of these error log messages the model finishes simulation successfully, as in you will see

```
LOG_SUCCESS       | info    | The simulation finished successfully.
```

and the exit code is 0. Maybe that explains why it seemed to pass before. It might be being killed by a timer now (I don't see any finalizing messages in [the log](https://[libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.sim](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.sim)) telling us whether it passed or failed).

The run on the regression tests also has a bit different simulation parameters compared to the default ones used by the model. On the [regression testing](https://[libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.sim](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus.sim)) I see:

```
startTime=0
stopTime=86400
numberOfIntervals=2500
stepSize=34.56
```

while the model by default (at least on my machine uses)

```
startTime =0
stopTime =86400
stepSize =172.8
```

I tried using the same parameters as specified on the CI But this did not make any difference in the outcome apart from making it finish a bit faster.


I think the model is faulty in any case. It would be nice if we found a working version to compare with but no luck so far.

**Comment by casella** [comment]
> One thing I have noticed, however, is that after all of these error log messages the model finishes simulation successfully, as in you will see
> 
> ```
> LOG_SUCCESS       | info    | The simulation finished successfully.
> ```

You are right, I was fooled by the fact that the first error messages were the same, so I did not bother checking the log file. The progress bar was indeed 100%, but it is only since a few days that it means the simulation was complete, I'm still used to the old behaviour, i.e., we got 100% also in case of initialization failure.

So the question is, why does that example actually work with the latest OMC and the latest Buildings on my Windows PC, while it doesn't on the Linux CI?

> It might be being killed by a timer now 

That could be the case, but the Windows version runs in less than a second, so I guess that's unlikely.

> I don't see any finalizing messages in the log telling us whether it passed or failed. 

Right. Which may mean, the simulation executable crashes so badly it can't leave his final will on stderr 😄. That could be because we changed the compiler that builds some of the 3rd party libraries, e.g. linear algebra.

> I think the model is faulty in any case.

Indeed. It gets singular all the time, and NaN values pop up, which shouldn't be the case, see #9539.

> It would be nice if we found a working version to compare with but no luck so far.

Do you mean working on the CI Linux machine?

**Comment by casella** [comment]
I ran the model with Dymola. Most flow rates are zero from time = 0 to time = 25000 and from time = 61800 to the end. This probably makes the model close to singularity. Maybe the way OMC solves it is less robust than Dymola, these warnings look very suspicious to me:
```
solver will try to handle division by zero at time 18000.00000456315: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
division leads to inf or nan at time 18000, (a=1) / (b=0), where divisor b is: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
solver will try to handle division by zero at time 18000.00000456315: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
division leads to inf or nan at time 18000, (a=1) / (b=0), where divisor b is: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
solver will try to handle division by zero at time 18000.00000456315: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
division leads to inf or nan at time 18000, (a=1) / (b=0), where divisor b is: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
solver will try to handle division by zero at time 18000.00000456315: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
division leads to inf or nan at time 18000, (a=1) / (b=0), where divisor b is: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
solver will try to handle division by zero at time 18000.00000456315: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
division leads to inf or nan at time 18000, (a=1) / (b=0), where divisor b is: 1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut
residualFunc1801: Iteration variable xloc[5] is nan.
residualFunc1801 failed at time=18000.0000045632. For more information please use -lv LOG_NLS.
```

**Comment by casella** [comment]
I checked further for the use of `varSpeDX.eva.watVapEva.XEvaWetBulOut` using the debugger. There is an implicit system of equations with residuals such as
```
(residual) if not varSpeDX.eva.watVapEva.off then 
  varSpeDX.eva.watVapEva.dX else 
  varSpeDX.eva.watVapEva.XiSatRefOut - 
    (1.0 - varSpeDX.eva.vol.dynBal.medium.Xi[1]) * 
    varSpeDX.eva.watVapEva.XEvaWetBulOut / 
    (1.0 - varSpeDX.eva.watVapEva.XEvaWetBulOut) 
 = 0
```
According to the debugger, this comes from these equations:
```modelica
    if on then
      dX = 0;
      mEva_flow = 0;
      mTotWat_flow = mWat_flow;
      der(m) = -mWat_flow;
      TEvaWetBulOut = 293.15;
      XEvaWetBulOut = 0;
      XiSatRefOut = 0;
    else
      XiSatRefOut=(1-XEvaOut)*XEvaWetBulOut/(1-XEvaWetBulOut);
      XEvaWetBulOut  = Buildings.Utilities.Psychrometrics.Functions.X_pSatpphi(
        pSat = Buildings.Utilities.Psychrometrics.Functions.saturationPressureLiquid(TEvaWetBulOut),
        p =    nomVal.p_nominal,
        phi =  1);
      (TEvaWetBulOut-T_ref) * (
                (1-XEvaOut) * cpAir_nominal +
                XiSatRefOut * cpSte_nominal +
                (XEvaOut-XiSatRefOut) * cpWatLiq_nominal) =
        (TEvaOut-T_ref) * (
                (1-XEvaOut) * cpAir_nominal +
                XEvaOut * cpSte_nominal)  +
        (XEvaOut-XiSatRefOut) * Buildings.Utilities.Psychrometrics.Constants.h_fg;
      dX = smooth(1, noEvent(
         Buildings.Utilities.Math.Functions.spliceFunction(
         pos=XEvaOut,
         neg=XEvaWetBulOut,
         x=abs(mAir_flow)-nomVal.m_flow_nominal/2,
         deltax=nomVal.m_flow_nominal/3)))
        - XEvaWetBulOut;
      mEva_flow = -dX * smooth(1, noEvent(
        Buildings.Utilities.Math.Functions.spliceFunction(
         pos=if abs(mAir_flow) > mAir_flow_small/3 then
            abs(mAir_flow) * (1-Modelica.Math.exp(-K2*m*abs(mAir_flow)^(-0.2))) else 0,
         neg=K2*mAir_flow_small^(-0.2)*m*mAir_flow^2,
         x=abs(mAir_flow)- 2*mAir_flow_small/3,
         deltax=2*mAir_flow_small/6)));
      der(m) = -mEva_flow;
      mTotWat_flow = mWat_flow + mEva_flow;
    end if;
```
I'm not sure if the way the equations from the two if branches are paired is 100% sound.

@mwetter, the term (1-XEvaWetBulOut) at the denominator of the first equation in the else branch looks very suspicious to me. Are you sure it never gets to zero?

**Comment by mwetter** [comment]
@casella : The quantity `XEvaWetBulOut` is the water vapor mass fraction at the wet bulb temperature that corresponds to the temperature of the heat exchanger outlet. From physics, we know this is two orders of magnitudes smaller than `1`.

The expression below its use is where it is computed:
```modelica
XEvaWetBulOut  = Buildings.Utilities.Psychrometrics.Functions.X_pSatpphi(
        pSat = Buildings.Utilities.Psychrometrics.Functions.saturationPressureLiquid(TEvaWetBulOut),
        p =    nomVal.p_nominal,
        phi =  1);
```
This is from here:
https://github.com/lbl-srg/modelica-buildings/blob/59fa38c9b3f4c492dd3837377a593e0346d5f070/Buildings/Utilities/Psychrometrics/Functions/X_pSatpphi.mo#L15
with `phi=1`.

Note however that this requires evaluation of the saturation pressure which is only valid for above-freezing temperatures:
https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Utilities/Psychrometrics/Functions/saturationPressureLiquid.mo
I would however be surprised if evaluating this function outside the range of validity cause the expression to be `1`.

Do we know what initial values are selected by the solver?

**Comment by casella** [comment]
@mwetter sorry, I overlooked the fact that you can't have x = 1 in humid air 😅. The issue arises during simulation, so the initial value should be picked based on the previous step, possibly with some extrapolation.

@mahge this looks like a low-level generated code issue. If `XEvaWetBulOut` is always << 1, how is it possible that `(1 - XEvaWetBulOut) = 0`, so we get a division by zero? Is there any practical way to debug this issue at the lowest possible level to see what is going wrong?

**Comment by casella** [comment]
> this looks like a low-level generated code issue. If `XEvaWetBulOut` is always << 1, how is it possible that `(1 - XEvaWetBulOut) = 0`, so we get a division by zero? Is there any practical way to debug this issue at the lowest possible level to see what is going wrong?

The reason is explained in [#11010](https://github.com/OpenModelica/OpenModelica/issues/11010#issuecomment-2035855308)

**Comment by Pavanrajhr** [comment]
@casella The model `Buildings.Fluid.DXSystems.Cooling.WaterSource.Validation.VariableSpeedEnergyPlus` is passing in the current "Buildings Latest Library". We can close this ticket.

**Comment by casella** [comment]
Agreed.
