### ISSUE TITLE
OMEdit crashes on exit when a result plot is open in the background

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#11298]
### Description

OMEdit crashes when exiting if a result plot subwindow is open in the Plotting tab but it's not the currently active tab.

### Steps to Reproduce

1. Open and simulate any model.
2. Switch back to the Modeling tab without closing the new plot subwindow.
3. Quit OMEdit.

### Expected Behavior

OMEdit should exit normally without crashing.

**Comment by adeas31** [comment]
Ported this to maintenance 1.22 branch.
