### ISSUE TITLE
Consistently use 'fill' for non-scalarized array modifiers having the same scalar values

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11304]
### Description

As already discussed in #10795, it would be nice to avoid large literal constant arrays in non-scalarized flat models, if their elements have all the same value, and use fill() instead. This allows to write maximally efficient and compact simulation code.

Consider the following MWE:
```modelica
package TestFill
 
  model Test
    parameter Integer N = 3;
    parameter Integer M = 2;
    parameter Integer P = 2;
    parameter Types.Temperature T0 = 493.15;
    Types.Temperature T1[N];
    Types.Temperature T2[N](each start = T0, each fixed = true);
    Types.Temperature T3[N, M, P + 1];
    Types.Temperature T4[N, M, P](each start = T0, each fixed = true);
    Types.Temperature T5[N, M, P](each start = T0, each fixed = true);
  end Test;

  package Types
    type Temperature = Real(unit = "K", displayUnit = "degC", nominal = 500);
  end Types;
end TestFill;
```
Flattening the `Test` model with `-f --newBackend -d=nonfScalarize` gives:
```modelica
model 'TestFill.Test'
  parameter Integer 'N' = 3;
  parameter Integer 'M' = 2;
  parameter Integer 'P' = 2;
  parameter Real 'T0'(nominal = 500.0, displayUnit = "degC", unit = "K") = 493.15;
  Real[3] 'T1'(nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}});
  Real[3] 'T2'(nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}}, fixed = fill(true, 3), start = {'T0', 'T0', 'T0'}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}});
  Real[3, 2, 3] 'T3'(nominal = fill(500.0, 3, 2, 3), displayUnit = fill("degC", 3, 2, 3), unit = fill("K", 3, 2, 3));
  Real[3, 2, 2] 'T4'(nominal = fill(500.0, 3, 2, 2), fixed = fill(true, 3, 2, 2), start = {'T0' for '$T43' in 1:2, '$T42' in 1:2, '$T41' in 1:3}, displayUnit = fill("degC", 3, 2, 2), unit = fill("K", 3, 2, 2));
end 'TestFill.Test';
```
All attributes of array `T1` are given by constant literal arrays, instead of using the `fill()` operator. Furthermore, the literal arrays are N-dimensional instead of being 1-dimensional.

For array `T2`, the `each fixed = true` modifier is rendered as expected with a `fill()` operator, but the modifier `each start = T0` is given by a literal constant array (although with the right dimensions). The other modifiers are N-dimensional as in the previous case.

Array `T3` is flattened as expected.

For array `T4`, all modifiers are flattened using `fill()` except the `start` modifier, which uses iterators instead. Although technically correct and with O(1) size, `'T0' for '$T23' in 1:2, '$T22' in 1:2, '$T21' in 1:3` is a rather baroque way to express `fill(T0, 3, 2 2)`, which would be preferrable.

### Expected Behaviour

```modelica
model 'TestFill.Test'
  parameter Integer 'N' = 3;
  parameter Integer 'M' = 2;
  parameter Integer 'P' = 2;
  parameter Real 'T0'(nominal = 500.0, displayUnit = "degC", unit = "K") = 493.15;
  Real[3] 'T1'(nominal = fill(500.0, 3), displayUnit = fill("degC", 3), unit = fill("K", 3));
  Real[3] 'T2'(nominal = fill(500.0, 3), displayUnit = fill("degC", 3), unit = fill("K", 3), fixed = fill(true, 3), start = fill(T0, 3));
  Real[3, 2, 3] 'T3'(nominal = fill(500.0, 3, 2, 3), displayUnit = fill("degC", 3, 2, 3), unit = fill("K", 3, 2, 3));
  Real[3, 2, 2] 'T4'(nominal = fill(500.0, 3, 2, 2), displayUnit = fill("degC", 3, 2, 2), unit = fill("K", 3, 2, 2), fixed = fill(true, 3, 2, 2), start = fill(T0, 3, 2, 2));
end 'TestFill.Test';
```

**Comment by casella** [comment]
Keeping @mscuttari in the loop.

**Comment by perost** [comment]
The new backend actually prefers array constructors, there's even a phase in the frontend that replaces fill calls with array constructors. I don't remember the reason for that, maybe @kabdelhak can elaborate.

It seems the `-f` flag interfers with this somehow though, only using `--newBackend` (`-d=nonfScalarize` is redundant) instead gives:
```Modelica
class Test
  final parameter Integer N = 3;
  final parameter Integer M = 2;
  final parameter Integer P = 2;
  parameter Real T0 = 493.15;
  Real[3] T1(unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}});
  Real[3] T2(unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, start = {T0, T0, T0}, fixed = array(true for $i1 in 1:3), nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}});
  Real[3, 2, 3] T3(unit = array(array(array(array(array(array("K" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3), displayUnit = array(array(array(array(array(array("degC" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3), nominal = array(array(array(array(array(array(500.0 for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3));
  Real[3, 2, 2] T4(unit = array(array(array(array(array(array("K" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), displayUnit = array(array(array(array(array(array("degC" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), start = array(array(array(T0 for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), fixed = array(array(array(true for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2), nominal = array(array(array(array(array(array(500.0 for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3));
end Test;
```
As you mentioned the dimensions are wrong in some cases when scalarization is disabled, but here it seems to be even worse since e.g. the expressions for the `T3` and `T4` type attributes are six-dimensional for some reason (look like it been expanded to array constructors twice somehow since there are two different sets of iterators).

**Comment by casella** [comment]
> The new backend actually prefers array constructors, there's even a phase in the frontend that replaces fill calls with array constructors. I don't remember the reason for that, maybe @kabdelhak can elaborate.

That looks strange to me. One of the goals of the new backend is to scalarize as little as possible - what would be the point of replacing fill(0, 1000, 1000) with one million of zero constants?
 
> It seems the `-f` flag interfers with this somehow though, only using `--newBackend` (`-d=nonfScalarize` is redundant) instead gives:
> 
> ```modelica
> class Test
>   final parameter Integer N = 3;
>   final parameter Integer M = 2;
>   final parameter Integer P = 2;
>   parameter Real T0 = 493.15;
>   Real[3] T1(unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}});
>   Real[3] T2(unit = {{"K", "K", "K"}, {"K", "K", "K"}, {"K", "K", "K"}}, displayUnit = {{"degC", "degC", "degC"}, {"degC", "degC", "degC"}, {"degC", "degC", "degC"}}, start = {T0, T0, T0}, fixed = array(true for $i1 in 1:3), nominal = {{500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}, {500.0, 500.0, 500.0}});
>   Real[3, 2, 3] T3(unit = array(array(array(array(array(array("K" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3), displayUnit = array(array(array(array(array(array("degC" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3), nominal = array(array(array(array(array(array(500.0 for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:3) for $T33 in 1:3) for $T32 in 1:2) for $T31 in 1:3));
>   Real[3, 2, 2] T4(unit = array(array(array(array(array(array("K" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), displayUnit = array(array(array(array(array(array("degC" for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), start = array(array(array(T0 for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3), fixed = array(array(array(true for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2), nominal = array(array(array(array(array(array(500.0 for $i1 in 1:3) for $i2 in 1:2) for $i3 in 1:2) for $T43 in 1:2) for $T42 in 1:2) for $T41 in 1:3));
> end Test;
> ```
> 
> As you mentioned the dimensions are wrong in some cases when scalarization is disabled, but here it seems to be even worse since e.g. the expressions for the `T3` and `T4` type attributes are six-dimensional for some reason (look like it been expanded to array constructors twice somehow since there are two different sets of iterators).

Whoa 😓 

The reason why we are using `--newBackend` is to avoid flattening records in variable declarations. We could introduce a specific flag to just do that.

However, I guess what the `--newBackend` flag is doing is plain wrong in many case, so we should first fix that. Then, discuss with @kabdelhak about if and when to replace fill() with expanded expressions.

@perost is there something you can do right now, or should we discuss this with @kabdelhak outright?

**Comment by perost** [comment]
> > The new backend actually prefers array constructors, there's even a phase in the frontend that replaces fill calls with array constructors. I don't remember the reason for that, maybe @kabdelhak can elaborate.
> 
> That looks strange to me. One of the goals of the new backend is to scalarize as little as possible - what would be the point of replacing `fill(0, 1000, 1000)` with one million of zero constants?

There's no scalarization, just replacing `fill` calls with the equivalent array constructor. Array constructors can handle a lot more cases than `fill` can, and I guess it's easier for the new backend to just deal with array constructors and not both `fill` and array constructors.

> @perost is there something you can do right now, or should we discuss this with @kabdelhak outright?

It would be good to agree on what we actually want before we start changing things.

**Comment by casella** [comment]
> There's no scalarization, just replacing `fill` calls with the equivalent array constructor. Array constructors can handle a lot more cases than `fill` can, and I guess it's easier for the new backend to just deal with array constructors and not both `fill` and array constructors.

OK, so that would mean replacing `fill(a, 3)` with `(a for i in 1:3)`. This is reasonable (ad would also be fine for the MARCO compiler which handles them as well). However, maybe it is best to decouple the flat output from the new backend processing.

As I wrote, we currently set --newBackend to avoid flattening records in variable declarations, as suggested one year ago in #8197. Unfortunately, there was no MWE source code there, just the flat output. I tried to reconstruct the source code:
```modelica
model M
record R
  Real x;
  Real y;
end R;

function f
  input Real x;
  output R r;
algorithm
  r.x := x;
  r.y := 2.0 * x;
end f;

  R r1;
  R r2;
  R r3;

equation
  r1 = f(time);
  r2 = r1;
  r3.x = r2.y;
  r3.y = r2.x;
end M;
```
I flattened it with just `-f` and I got
```modelica
model 'M'
function 'M.f'
  input Real 'x';
  output 'R' 'r';
algorithm
  'r'.'x' := 'x';
  'r'.'y' := 2.0 * 'x';
end 'M.f';

record 'R'
  Real 'x';
  Real 'y';
end 'R';

  'R' 'r1';
  'R' 'r2';
  'R' 'r3';
equation
  'r1' = 'M.f'(time);
  'r2' = 'r1';
  'r3'.'x' = 'r2'.'y';
  'r3'.'y' = 'r2'.'x';
end 'M';
```
Apparently, the record declarations are no longer expanded into their scalar components, so we can probably just skip --newBackend. Did you change something about this in the NF since the, or am I missing something?

**Comment by perost** [comment]
> Apparently, the record declarations are no longer expanded into their scalar components, so we can probably just skip `--newBackend`. Did you change something about this in the NF since the, or am I missing something?

The difference is that you're using `-f` now.

**Comment by casella** [comment]
@mscuttari ping!

Are you fine with the current Base Modelica output of OMC using both each and fill()?

**Comment by mscuttari** [comment]
Should be fine, but we will have to test more for this.

**Comment by casella** [comment]
OK. Please reopen if necessary.
