### ISSUE TITLE
OM crashes when open a function

### ISSUE THREAD

**Issue by mpradovelasco** [OpenModelica/OpenModelica#11319]
Hi,

Although, the following code is incorrect due to self dependency in binding equation on c[:], I think OM should notice it and not to crash. But it is currently crashing when trying to open F.

``` Modelica
package crash
  partial function F "user function with state and cross dependence"
    input Real c[:]=fill(0,size(c,1)) "Real vectorial vector of coefficientes";
  end F;
end crash;
```

System: OMEdit 1.23 dev (23/9), Windows 11 64

Thanks!

**Comment by adeas31** [comment]
Opening `crash.F` works fine for me. Can you please elaborate more?

**Comment by perost** [comment]
This was actually fixed last week by #11279. Previously we treated functions like model when opening them in OMEdit which caused some issues, and this happens to be one of the things that were affected.

**Comment by perost** [comment]
On second thought this only applies to functions, a similar model would still cause the compiler to crash. But #11326 should fix that too.

**Comment by mpradovelasco** [comment]
I have updated to the latest nightly OM1.23-dev build and I can open F without crash. 

Thank you!
