### ISSUE TITLE
Redeclared but not replaceable classes should not show up in the parameter window

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11311]
### Steps to Reproduce

- Download this branch of PowerGrids: https://github.com/PowerGrids/PowerGrids/tree/Issue%2354_PFTest2
- Open PowerGrids.Examples.ENTSOE.SteadyState
- Double-click on TGEN

The parameter windows shows terminalAC_a, terminalAC_b and componentPF. Those three components are all redeclared in the [TransformerFixedRatio](https://github.com/PowerGrids/PowerGrids/blob/Issue%2354_PFTest2/PowerGrids/Electrical/Branches/TransformerFixedRatio.mo) model, but they are not redeclared replaceable, so they shouldn't end up in the parameter window at all.

### Expected Behavior

terminalAC_a, terminalAC_b and componentPF should be absent from the parameter window.

**Comment by mpradovelasco** [comment]
I wonder is this issue is related to #11020 that it is still open.

**Comment by adeas31** [comment]
They are `replaceable` in base class `PowerGrids.Electrical.BaseClasses.TwoPortACVI` but are redeclared via modified in `PowerGrids.Electrical.Branches.TransformerFixedRatio`.

@perost we don't have this information in the instance JSON.

**Comment by adeas31** [comment]
Sorry, we do have this information. But it is dumped as it is,

`"componentPF":{"$value":"redeclare PowerGrids.Electrical.PowerFlow.PVBus componentPF(UNom = UNom, SNom = SNom, P = -PPF, U = UPF)"}`

Maybe we can add `redeclare` boolean as we do `final`. What do you think?

**Comment by perost** [comment]
> Sorry, we do have this information. But it is dumped as it is,
> 
> `"componentPF":{"$value":"redeclare PowerGrids.Electrical.PowerFlow.PVBus componentPF(UNom = UNom, SNom = SNom, P = -PPF, U = UPF)"}`
> 
> Maybe we can add `redeclare` as boolean attribute as we do for `final`. What do you think?

Sure, added in #11318. I was going to suggest just checking if the string starts with `redeclare`, since that will always be the case for a redeclare modifier. But having an attribute for it in the JSON is perhaps a bit more robust in case that ever changes in the future.

**Comment by adeas31** [comment]
Ported to maintenance 1.22

**Comment by casella** [comment]
> I wonder is this issue is related to #11020 that it is still open.

@mpradovelasco probably. Please check with the next nightly build and close it if it works for you.

**Comment by adeas31** [comment]
We also need to check that its not `replaceable`. See #11337
