### ISSUE TITLE
Recent additions to NF scale badly

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11329]
When I ran the tests for the new backend paper to the Modelica Conference (I guess last June, but I may be mistaken), we were able to compile `LargeTestSuite.Mechanical.HarmonicOscillator.HarmonicOscillator_N_819200`, which has 1.6 M states and equations, in about 4 minutes. 

I ran the [LargeTestSuite_NB](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html) job a few days ago, and it turns out that the performance has degraded dramatically, to the point that we cannot handle models larger than LargeTestSuite.Mechanical.HarmonicOscillator.HarmonicOscillator_N_12800. 

Some quick analysis reveals that the time spent by NFFlatten.collectFunctions, combineBinaries, and NFVerifyModel.verify scale as O(N^2). I guess this is due to some recent additions to the frontend, unfortunately we are not running LargeTestSuite_NB job regularly, as it is quite time-consuming, so I don't know when this happened. Also, we are not keeping track of previous results, so I lost the actual information about when we ran the previous test. We should probably improve this, e.g. by scheduling LargeTestSuite_NB to run every other weekend, or something.

To figure out when things went wrong, you can probably do some bisection and check how long it takes to flatten HarmonicOscillator_N_12800, it shouldn't take more than 5-10 seconds.

I wonder if we should add some of these large tests to the core testsuite, to catch any commit that is not really scalable, e.g. LargeTestSuite.Mechanical.HarmonicOscillator.HarmonicOscillator_N_51200 shouldn't take more than 15 seconds to compile and run when everything works fine, so if some new addition scales badly, it will make the test fail due to timeout and prevent merging the PR.

@perost can you please check? I'm not sure if these additions are due to NB requirements or if they are just NF improvements.

**Comment by perost** [comment]
The issue turned out to be that we created incorrect bindings for some of the type attributes (quantity, unit, etc), which somehow caused the frontend to expand them and create huge array expressions. #11334 fixes that issue, and now the HarmonicOscillator models flatten in milliseconds regardless of the value of N.

And while it's no longer needed for this case I also improved the performance of combineBinaries (which is only used by the NB) in #11335 by not traversing the elements of arrays of literal values, since they by definition can't contain binary expressions.

**Comment by casella** [comment]
Great, I'll run the scalable test again at once, so we can double-check that everything's in order.

**Comment by casella** [comment]
@perost would you mind porting this to 1.22.0 as well, so we avoid the regression in there?

Thanks!

**Comment by casella** [comment]
[LargeTestSuite_NB test report](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html) back to normal. Thanks @perost for the quick fix!
