### ISSUE TITLE
versions 1.23.0-dev and 1.22.0-dev.beta.1:  OMEdit crashes with applying minor changes in the code

### ISSUE THREAD

**Issue by SogolKharrazi** [OpenModelica/OpenModelica#11333]
### Description
I tried nightly build version (1.23.0-dev), as well as the stable development version (1.22.0-dev.beta.1) and both of them intends to crash on my computer (I have windows 11, 64bit), as soon as I apply a minor change in one file in the model and wants to switch to the another file in the model, or if I try to save it. Finally I installed the official release verion (1.21.0) and it seems to work.

**Comment by adeas31** [comment]
Unfortunately, I can't reproduce this. Can you please provide a MWE?

**Comment by arun3688** [comment]
@adeas31 I also cannot reproduce this issue, but i looked into her computer and it was crashing if we tried to save the model

**Comment by adeas31** [comment]
Yeah but she mentioned that 1.21.0 works. So I wonder what combination of actions does work in 1.21.0 and does not work in 1.22.

**Comment by arun3688** [comment]
@adeas31 what is happening is we open OMEdit and we open 3 models in the editor and when we try to edit the models and when we switch between the editors it is crashing

**Comment by arun3688** [comment]
@adeas31 I can reproduce the issue, for me also it is crashing
