### ISSUE TITLE
I'm compiling OpenModelica for windows, and I'm having problems

### ISSUE THREAD

**Issue by suyufeng1** [OpenModelica/OpenModelica#11354]
```sh
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c: In function 'class_definition':
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:3913:48: error: macro "Absyn__CLASS" passed 9 arguments, but takes just 7
 3913 |                       PARSER_INFO(retval.start));
      |                                                ^
In file included from F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:886:
F:/code/OpenModelica/OMCompiler/Compiler/OpenModelicaBootstrappingHeader.h:1820: note: macro "Absyn__CLASS" defined here
 1820 | #define Absyn__CLASS(name,partialPrefix,finalPrefix,encapsulatedPrefix,restriction,body,info) (mmc_mk_box8(3,&Absyn_Class_CLASS__desc,name,partialPrefix,finalPrefix,encapsulatedPrefix,restriction,body,info))
      |
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:3908:35: error: 'Absyn__CLASS' undeclared (first use in this function); did you mean 'Absyn__LESS'?
 3908 |                       retval.ast= Absyn__CLASS(cs.name, mmc_mk_bcon(p), mmc_mk_bcon(final), mmc_mk_bcon(e), ct, cs.ast,
      |                                   ^~~~~~~~~~~~
      |                                   Absyn__LESS
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:3908:35: note: each undeclared identifier is reported only once for each function it appears in
In file included from F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:45:
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c: In function 'argument_list':
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:11537:60: error: implicit declaration of function 'Absyn__ELEMENTARGCOMMENT'; did you mean 'Absyn__LEXER_5fCOMMENT'? [-Werror=implicit-function-declaration]
11537 |           commentAst = mmc_mk_cons_typed(Absyn_ElementArg, Absyn__ELEMENTARGCOMMENT(mmc_mk_scon((char*)tok->getText(tok)->chars)),commentAst);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.h:300:54: note: in definition of macro 'mmc_mk_cons_typed'
  300 |   #define mmc_mk_cons_typed(T,head,tail) mmc_mk_cons(head,tail)
      |                                                      ^~~~
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:11537:60: warning: passing argument 1 of 'mmc_mk_cons' makes pointer from integer without a cast [-Wint-conversion]
11537 |           commentAst = mmc_mk_cons_typed(Absyn_ElementArg, Absyn__ELEMENTARGCOMMENT(mmc_mk_scon((char*)tok->getText(tok)->chars)),commentAst);
      |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                            |
      |                                                            int
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.h:300:54: note: in definition of macro 'mmc_mk_cons_typed'
  300 |   #define mmc_mk_cons_typed(T,head,tail) mmc_mk_cons(head,tail)
      |                                                      ^~~~
In file included from F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:881:
F:/code/OpenModelica/OMCompiler/SimulationRuntime/c/meta/meta_modelica.h:117:39: note: expected 'void *' but argument is of type 'int'
  117 | static inline void *mmc_mk_cons(void *car, void *cdr)
      |                                 ~~~~~~^~~
In file included from F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:45:
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:11616:67: warning: passing argument 1 of 'mmc_mk_cons' makes pointer from integer without a cast [-Wint-conversion]
11616 |                         ast = mmc_mk_cons_typed(Absyn_ElementArg, Absyn__ELEMENTARGCOMMENT(mmc_mk_scon((char*)tok->getText(tok)->chars)),ast);
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                   |
      |                                                                   int
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.h:300:54: note: in definition of macro 'mmc_mk_cons_typed'
  300 |   #define mmc_mk_cons_typed(T,head,tail) mmc_mk_cons(head,tail)
      |                                                      ^~~~
In file included from F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:881:
F:/code/OpenModelica/OMCompiler/SimulationRuntime/c/meta/meta_modelica.h:117:39: note: expected 'void *' but argument is of type 'int'
  117 | static inline void *mmc_mk_cons(void *car, void *cdr)
      |                                 ~~~~~~^~~
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c: In function 'expression':
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:19789:35: error: implicit declaration of function 'Absyn__EXPRESSIONCOMMENT'; did you mean 'Absyn__LEXER_5fCOMMENT'? [-Werror=implicit-function-declaration]
19789 |                       retval.ast= Absyn__EXPRESSIONCOMMENT(listReverseInPlace(commentBefore), retval.ast, listReverseInPlace(commentAfter));
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                   Absyn__LEXER_5fCOMMENT
F:/code/OpenModelica/build_cmake/OMCompiler/Parser/generated/ModelicaParser.c:19789:33: warning: assignment to 'void *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
19789 |                       retval.ast= Absyn__EXPRESSIONCOMMENT(listReverseInPlace(commentBefore), retval.ast, listReverseInPlace(commentAfter));
      |                                 ^
cc1.exe: some warnings being treated as errors
make[2]: *** [OMCompiler/Parser/CMakeFiles/omparse.dir/build.make:231: OMCompiler/Parser/CMakeFiles/omparse.dir/generated/ModelicaParser.c.obj] Error 1
```

I need some help

**Comment by mahge** [comment]
I am afraid you need to add some more information. How did you get the OpenModelica source code? What series of instructions did you use to compile OpenModelica.

Please list out all steps you took as clearly as possible and add as much detail as you can to the issue report. It will make it easier for us to spot the problem.

**Comment by suyufeng1** [comment]
> I am afraid you need to add some more information. How did you get the OpenModelica source code? What series of instructions did you use to compile OpenModelica? What is your Operating System and compiler?
> 
> Please list out all steps you took as clearly as possible and add as much detail as you can to the issue report. It will make it easier for us to spot the problem.

I get the code through git.
git clone --recurse-submodules https://github.com/OpenModelica/OpenModelica.git

I downloaded OMDev and set up the environment variables, then used these commands in README.Windows.md. 

cd /path/to/OpenModelica
cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles"
cd build_cmake
make -j16 install -Oline

$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\OMDev\tools\msys\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran
,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --dis
able-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-
boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entro
py-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev5, Built by MSYS2 project)

$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\OMDev\tools\msys\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/OMDev/tools/msys/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran
,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --dis
able-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev5, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-
boot-ldflags='-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' 'LDFLAGS_FOR_TARGET=-pipe -Wl,--dynamicbase,--high-entropy-va,--nxcompat,--default-image-base-high' --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--dynamicbase,--high-entro
py-va,--nxcompat,--default-image-base-high\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev5, Built by MSYS2 project)

**Comment by suyufeng1** [comment]
Thank you very much

**Comment by mahge** [comment]
Based on the steps you took, everything should work as expected. I can not see any issues and OpenModelica is being built successfully on our CI servers as well as local computers.

I have a suspicion as to where your issue might be but we need to verify it. By the time you are trying to configure and build OpenModelica, does your machine still have internet connection? 


We can try this. 

 - Delete your build (`build_cmake/`) directory completely.
 - Run the following command in the OpenModelica directory:
 ```
cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles" |& tee config.trace
```

This will create a file named config.trace in the root OpenModelica directory. Please attach that file here. Maybe it can tell us something.

**Comment by suyufeng1** [comment]
> Based on the steps you took, everything should work as expected. I can not see any issues and OpenModelica is being built successfully on our CI servers as well as local computers.
> 
> I have a suspicion as to where your issue might be but we need to verify it. By the time you are trying to configure and build OpenModelica, does your machine still have internet connection?
> 
> We can try this.
> 
> * Delete your build (`build_cmake/`) directory completely.
> * Run the following command in the OpenModelica directory:
> 
> ```
> cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles" |& tee config.trace
> ```
> 
> This will create a file named `config.trace` in the root OpenModelica directory. Please attach that file here. Maybe it can tell us something.

I can't upload the.trace file, I will change it to.txt, thank you very much

[config.txt](https://github.com/OpenModelica/OpenModelica/files/12851791/config.txt)

**Comment by suyufeng1** [comment]
> 您已经修改了您的工作副本。中有修改`OMCompiler/Compiler/boot`。创建问题报告时，请确保您没有修改源代码。如果您对它们进行了修改，那么您应该提及所做的修改。
> 
> 什么是
> 
> ```
> git status
> ```
> 
> 报告？

Thank you for your reply, but I didn't modify it.

yunlu@DESKTOP-NKVJ2SD MINGW64 /f/code/OpenModelica/OMParser (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../OMCompiler/Compiler/boot/CMakeLists.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../OMCompiler/build/
        ../config.txt

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by suyufeng1** [comment]
I see what you're talking about. I manually copied the tarball-include directory to boot/bomc

**Comment by suyufeng1** [comment]
This is because cmake reports an error

**Comment by suyufeng1** [comment]
![QQ图片20231010172209](https://github.com/OpenModelica/OpenModelic
![QQ图片20231010172248](https://github.com/OpenModelica/OpenModelica/assets/48075972/20527662-90b9-46f1-8edc-a0140be16947)
a/assets/48075972/d13319d6-6338-4bd9-b744-a72ebb7f3734)

**Comment by suyufeng1** [comment]
![QQ图片20231010172209](https://github.com/OpenModelica/OpenModelica/assets/48075972/af83336f-d382-48c6-97fb-bee92cbb3f15)

**Comment by mahge** [comment]
> I see what you're talking about. I manually copied the tarball-include directory to boot/bomc

That will not work. The files might look similar but their contents are different. The change you made is a very important detail that should be mentioned in the description of the ticket.  

> This is because cmake reports an error

This is what I was suspecting when asking if you had internet connection when you are calling CMake to configure OpenModelica. CMake checks if you have the appropriate files, if you do not have them yet, it will try to download them. This means if you do not have internet connection then CMake will report an error.

**Comment by suyufeng1** [comment]
I had the Internet when I was doing cmake

> > I see what you're talking about. I manually copied the tarball-include directory to boot/bomc
> 
> That will not work. The files might look similar but their contents are different. The change you made is a very important detail that should be mentioned in the description of the ticket.
> 
> > This is because cmake reports an error
> 
> This is what I was suspecting when asking if you had internet connection when you are calling CMake to configure OpenModelica. CMake checks if you have the appropriate files, if you do not have them yet, it will try to download them. This means if you do not have internet connection then CMake will report an error.

I had the Internet when I was doing cmake

**Comment by mahge** [comment]
1. If you have internet connection when you configure OpenModelica then you should just clone OpenModelica again and follow the steps without modifying anything. If you encounter errors that way, let me know and we can fix them.

2. If you DO NOT have internet connection when you configure OpenModelica then follow the steps here https://github.com/OpenModelica/OpenModelica/issues/11327#issuecomment-1748528944. Let me know fi you encounter any issues and we can fix them.

**Comment by suyufeng1** [comment]
> 1. If you have internet connection when you configure OpenModelica then you should just clone OpenModelica again and follow the steps without modifying anything. If you encounter errors that way, let me know and we can fix them.
> 2. If you DO NOT have internet connection when you configure OpenModelica then follow the steps here [v1.22.0-dev.beta.1 fails to build: File OpenModelicaBootstrappingHeader.h does not exist #11327 (comment)](https://github.com/OpenModelica/OpenModelica/issues/11327#issuecomment-1748528944). Let me know fi you encounter any issues and we can fix them.

![QQ图片20231010175656](https://github.com/OpenModelica/OpenModelica/assets/48075972/10916c4e-0a6b-4467-9326-215a5040183b)

Thank you very much, I have solved this problem, but I have encountered a new problem, I try to restart the administrator to rebuild
