### ISSUE TITLE
Wrong extent for models with extend and without annotation

### ISSUE THREAD

**Issue by MaksKBV** [OpenModelica/OpenModelica#11363]
### Description

Wrong extent for models with extend and without annotation

### Steps to Reproduce

Example model:
[mpkg.mo.txt](https://github.com/OpenModelica/OpenModelica/files/12861623/mpkg.mo.txt)

### Expected Behavior

Model m1 icon in example looks like:
![1](https://github.com/OpenModelica/OpenModelica/assets/145646967/3406f623-f23c-4dd7-818a-02686fb3fcc7)

Model m2 extends from m1 and hasn`t its own annotation. Its icon looks like:
![2](https://github.com/OpenModelica/OpenModelica/assets/145646967/6903ab53-7e31-48d6-8b08-839646c753cf)

but m2 must have same icon as m1

when use these models it looks like (m2 - left, m1 - right):
![3](https://github.com/OpenModelica/OpenModelica/assets/145646967/bf4eb8bc-e034-49df-a508-d488fd198ad1)

### Version and OS

 - OpenModelica Version: 1.23.0-dev
 - OS: Windows 10, 64 bit

**Comment by adeas31** [comment]
Fixed in PR #11383
