### ISSUE TITLE
A minor glitch when exporting to clipboard

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11367]
### Steps to Reproduce
Load the following code:
```
model TestConn1
  Modelica.Electrical.Analog.Interfaces.PositivePin pin_p annotation(
    Placement(transformation(origin = {74, 0}, extent = {{-10, -10}, {10, 10}}), iconTransformation(origin = {92, -2}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Electrical.Analog.Basic.Resistor resistor annotation(
    Placement(transformation(origin = {20, 0}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(resistor.n, pin_p) annotation(
    Line(points = {{30, 0}, {74, 0}}, color = {0, 0, 255}));
  annotation(
    uses(Modelica(version = "4.0.0")),
  Diagram(coordinateSystem(extent = {{0, 20}, {80, -20}})),
  version = "");
end TestConn1;

```

The diagram is as follows: 
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/276d1153-08fb-4fd9-acaf-eb05af59f259)

Copy the diagram to clipboard, and the keyboard content is as follows:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/1347d09c-de05-4f63-a0f3-d226a75c62b5)

I.e. a white rectangle has appeared around the blue wire, over the pin.

### Expected Behavior
the image copied on the clipboard shoud be as the one visibile before copying, i.e without the white rectangle.

### Version and OS

OM 1.22.0-dev-341 Win64 
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
This works fine with the latest version. I think it got fixed with this commit 69a6c3ff77e9590d676c667c76dc58ef24a73c7e.
