### ISSUE TITLE
Scripting Error Failed to load package Modelica (default) using MODELICAPATH C:/Users/yunlu/AppData/Roaming/.openmodelica/libraries.

### ISSUE THREAD

**Issue by suyufeng1** [OpenModelica/OpenModelica#11372]
After the source code compiles OpenModelica, after the compilation is successful, I open OMEdit, which has an error.
I don't know why.
I also added these two environment variables.

I'm using cmake, I don't have a build folder in my OpenModelica directory, and I don't understand what this environment variable is doing.

![QQ图片20231013140230](https://github.com/OpenModelica/OpenModelica/assets/48075972/157d8fe5-5cb4-41aa-b615-9e6d938fd72c)

**Comment by suyufeng1** [comment]
![QQ图片20231013141922](https://github.com/OpenModelica/OpenModelica/assets/48075972/fdacf4c5-a2c6-49ef-a2e0-7a1d1688c6c6)

**Comment by suyufeng1** [comment]
![QQ图片20231013142125](https://github.com/OpenModelica/OpenModelica/assets/48075972/6ae22b8f-dec5-4371-897c-00275742c805)

**Comment by suyufeng1** [comment]
![QQ图片20231013143148](https://github.com/OpenModelica/OpenModelica/assets/48075972/22688b4c-ecfa-4894-ab2a-37ad493c6bac)
I tried to set MODELICAPATH to this path, but it didn't work and still reported an error

**Comment by suyufeng1** [comment]
![QQ图片20231013171411](https://github.com/OpenModelica/OpenModelica/assets/48075972/737f171e-e9da-4712-945c-8267c22036b9)

**Comment by suyufeng1** [comment]
It doesn't do any good

**Comment by suyufeng1** [comment]
![QQ图片20231013171544](https://github.com/OpenModelica/OpenModelica/assets/48075972/2f0cb694-4806-4dbf-b05c-6a471d56f569)

**Comment by arun3688** [comment]
@suyufeng1 just go to tools->OpenModelica Compiler CLI and paste the following command suggested by OMEdit 
`  installPackage(ModelicaReference)`, something like below and it should work
![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/15079d46-ccef-461b-a3b6-13d9c83986a0)

**Comment by suyufeng1** [comment]
> @suyufeng1 just go to tools->OpenModelica Compiler CLI and paste the following command suggested by OMEdit ` installPackage(ModelicaReference)`, something like below and it should work ![image](https://user-images.githubusercontent.com/6870949/274861322-15079d46-ccef-461b-a3b6-13d9c83986a0.png)

![image](https://github.com/OpenModelica/OpenModelica/assets/48075972/010e21f4-5c4c-4464-a2b8-7c7bf18355e3)
Let me try

**Comment by suyufeng1** [comment]
> @suyufeng1 just go to tools->OpenModelica Compiler CLI and paste the following command suggested by OMEdit ` installPackage(ModelicaReference)`, something like below and it should work ![image](https://user-images.githubusercontent.com/6870949/274861322-15079d46-ccef-461b-a3b6-13d9c83986a0.png)

I wonder why there is no response every time I click "send"

**Comment by arun3688** [comment]
@suyufeng1 there will be no response unfortunately, you can give it some time and restart the omedit, this is one of the ways to install the libraries, or  you can write a mos script example 

### a.mos
```
installPackage(ModelicaReference);
getErrorString();
```

**Comment by suyufeng1** [comment]
> @suyufeng1 there will be no response unfortunately, you can give it some time and restart the omedit, this is one of the ways to install the libraries, or you can write a mos script example
> 
> ### a.mos
> ```
> installPackage(ModelicaReference);
> getErrorString();
> ```

I'm trying to update how this script works. Thank you very much

**Comment by arun3688** [comment]
@suyufeng1 just create a file named "a.mos" and run it with omc , something like below

`>>> omc.exe a.mos `

**Comment by mahge** [comment]
@suyufeng1 any luck?

**Comment by adeas31** [comment]
First of all the CMake should have installed the default offline libraries that includes Modelica Standard Library, so something for @mahge to test.

Secondly, do not try to set `MODELICAPATH` unless you know exactly what you are doing.

Lastly, if the default libraries are not installed by CMake you can always install them yourself by going to `File->Manage Libraries->Install Library`. Select `Modelica` from the list and press `OK`. Restart OMEdit or load the installed `Modelica` library from `File->System Libraries->Modelica`. See also https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#install-library

**Comment by suyufeng1** [comment]
> 首先，CMake 应该安装默认的离线库，其中包括 Modelica 标准库，所以需要一些东西@mahge去测试。
> 
> `MODELICAPATH`其次，除非您确切知道自己在做什么，否则不要尝试设置。
> 
> 最后，如果 CMake 未安装默认库，您始终可以通过转到 自行安装它们`File->Manage Libraries->Install Library`。从列表中选择`Modelica`并按`OK`。`Modelica`重新启动 OMEdit 或从加载已安装的库`File->System Libraries->Modelica`。另请参阅https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#install-library

That solved my problem. Thank you very much

**Comment by suyufeng1** [comment]
> Lastly, if the default libraries are not installed by CMake you can always install them yourself by going to `File->Manage Libraries->Install Library`. Select `Modelica` from the list and press `OK`. Restart OMEdit or load the installed `Modelica` library from `File->System Libraries->Modelica`

Another friend's method solved my problem.
Lastly, if the default libraries are not installed by CMake you can always install them yourself by going to File->Manage Libraries->Install Library. Select Modelica from the list and press OK. Restart OMEdit or load the installed Modelica library from File->System Libraries->Modelica

**Comment by suyufeng1** [comment]
> @suyufeng1 any luck?

Thank you very much for your help before, I solved the problem
