### ISSUE TITLE
[NF] unscalarized frontend still expands start values

### ISSUE THREAD

**Issue by kabdelhak** [OpenModelica/OpenModelica#11385]
### Description

 I am currently working on creating initial equations again. It seems like the frontend parses attributes differently.
```
  Real[5] Tu(nominal = fill(300.0, 5), fixed = fill(true, 5), start = {Tu0, Tu0, Tu0, Tu0, Tu0}, min = fill(0.0, 5), displayUnit = fill("degC", 5), unit = fill("K", 5), quantity = fill("ThermodynamicTemperature", 5));
```
this is the result of an unscalarized variable in `ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5` . Is there a reason the start attribute is flattened while the others are not?
```
  SI.Temperature Tu[N](each start = Tu0, each fixed = true)
    "Temperature of individual heated units";
```
This is the original declaration, doesn't seem to be declared differently. For me it would be best if it also was a fill() operation or something similar array preserving

### Steps to Reproduce
run `ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5`  from the ScalableTestsuite using `--newBackend` and the dumping flag `--dumpFlatModel`.

### Expected Behavior

I would expect it to be not expanded as the other attributes. 

### Additional Context
First step to solving #9986. Currently the new backend creates incorrect start equations using the start attribute assuming it's constant (which it isn't since its a parameter). Trying to create the correct assignment for the start attribute instead leads me to the problem at hand. Since i create for-loops for these start equations it would be beneficial to have a `fill()` operator or something similiar array preserving as a start value.

**Comment by casella** [comment]
Related to #11304. If we use the -f flag, apparently we only get either fill() or each, no more expanded parameters.

@perost could you get the same for Karim's backend?

**Comment by kabdelhak** [comment]
Can confirm, just checked `-f -d=-nfScalarize` produces exactly the output i need. Does `-f` do anything specific i might also want in general? Should we implicitely activate that flag on `--newBackend` ?

**Comment by perost** [comment]
> Can confirm, just checked `-f -d=-nfScalarize` produces exactly the output i need. Does `-f` do anything specific i might also want in general? Should we implicitely activate that flag on `--newBackend`? Unfortunately adding `--newBackend` prevents the magic from happening so i cannot really test it.

It's only `-d=-nfScalarize` that's needed, `-f` only changes the output format. The issue is probably related to `--newBackend` changing the fill calls to array constructors which in some cases are then simplified to arrays for some reason.

**Comment by kabdelhak** [comment]
Thanks for the quick fix, i got my backend changes ready to commit as well. Worked with this minimal model:
```
model M
  parameter Real[5] T0 = {i for i in 1:5};
  Real[5] T(start = T0, each fixed = true);
  parameter Real X0 = 10;
  Real[5] X(start = fill(X0, 5), each fixed = true);
equation
  for i in 1:5 loop
    der(T[i]) = sin(time);
  end for;
  for i in 1:5 loop
    der(X[i]) = cos(time);
  end for;
end M;
```
Hopefully it will generally work with your changes applied.
