### ISSUE TITLE
OMEdit reports "Failed to evaluate expression"

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#11388]
### Steps to Reproduce

Open OMEdit with `OMEdit --NAPI=true` and open for example `Modelica.Fluid.Vessels.OpenTank`. This shows multiple entries such as
```
[4] 08:39:45 Scripting Notification
Failed to evaluate expression.
showDesignFlowDirection could not be found
Failed to evaluate expression.
allowFlowReversal could not be found
Failed to evaluate expression.
showDesignFlowDirection could not be found
Failed to evaluate expression.
port_a_exposesState could not be found
Failed to evaluate expression.
...
```

The same also happens with many models of `Buildings.Fluid`.

### Expected Behavior

Is there a way to suppress these so that the user is not confronted with a lot of "failures" when browsing models?

### Version and OS

 
OpenModelica 1.23.0~dev-59-g7a41456

OMSimulator 2.1.1~241-g54ebbdc-linux-notlm-debug

**Comment by casella** [comment]
--NAPI=true is no longer needed for version 1.23.0-dev. The new inst-based interface is activated by default. Please try it that way.

**Comment by mwetter** [comment]
Removing --NAPI=true avoids the problem.

**Comment by adeas31** [comment]
The `--NAPI=true` is still valid but is not needed since the new inst-based interface is default now.

However, the warnings will be shown whenever the instance based API is used. One idea is to just show them when `--Debug=true`.

**Comment by mwetter** [comment]
I agree it would be clearer to show these debug information only if ``--Debug=true``.

I now run OMEdit without ``--NAPI=true``. To remove these messages, I also had to select
![image](https://github.com/OpenModelica/OpenModelica/assets/1329080/855d3bab-17a1-4294-9dd4-1edadbea4ee3)
and restart. As the new inst-based interface is default now, do we indeed need to disable it, or is this just a left over from the old configuration?

This is with
```
OpenModelica 1.23.0~dev-59-g7a41456
OMSimulator 2.1.1~241-g54ebbdc-linux-notlm-debug
```

**Comment by adeas31** [comment]
> I agree it would be clearer to show these debug information only if `--Debug=true`.

See #11403

> I now run OMEdit without `--NAPI=true`. To remove these messages, I also had to select ![image](https://user-images.githubusercontent.com/1329080/276414803-855d3bab-17a1-4294-9dd4-1edadbea4ee3.png) and restart. As the new inst-based interface is default now, do we indeed need to disable it, or is this just a left over from the old configuration?

If you run without `--NAPI=true` and check `Disable new instance-based graphical editing of models` then OMEdit will not use the new instance-based API. Only use this option if you really don't want to use the new instance-based API.

**Comment by casella** [comment]
@mwetter we had to change the set up from "activate new api" to "deactivate new api" because OMEdit remembers the settings you had with the previous version, so to make the new api the default for all installations (also those that replace previous one) it was necessary to define a new option.
