### ISSUE TITLE
OMEdit does not render icon

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#11400]
### Description

I have a new model for which OMEdit does not render its icon.
Also if started with `OMEdit --Debug=true package.mo`, I see no information that points me to the problem. Is there a way to debug the issue?

### Steps to Reproduce

Download Modelica IBPSA Library, commit d32ad169efcd757ed4c0629ac273eb9ff9d5c25b

Open model `IBPSA.Fluid.Geothermal.Aquifer.MultiWell`

### Expected Behavior

Display the icon. Instead, I see

![image](https://github.com/OpenModelica/OpenModelica/assets/1329080/9a29350e-80b1-444e-b95c-276a06d2e6b8)

### Version and OS

OpenModelica 1.23.0~dev-59-g7a41456
OMSimulator 2.1.1~241-g54ebbdc-linux-notlm-debug

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - IBPSA, commit d32ad169efcd757ed4c0629ac273eb9ff9d5c25b

### Additional Context

The icon renders normal in Dymola.
If used in a system model, the icon is replaced with a place holder:
![image](https://github.com/OpenModelica/OpenModelica/assets/1329080/20ce6fc3-f6d8-4dab-9a81-a9f082f4e3de)

**Comment by adeas31** [comment]
This works fine for me. I noticed that this is not working when instance-based API is disabled. So makesure you have enabled instance-based API. We will remove the old code that is not using the instance-based API in the future versions.

OMEdit,
![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/983e88c7-aa9d-4475-b9df-3a51ae7d4612)

Dymola,
![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/f7815670-4ed6-48eb-b421-8a03bd09b567)
