### ISSUE TITLE
Support expression subscripting

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11424]
Expression subscripting is used in the current BaseModelica draft specification, and it was also recently added to the Modelica 3.7 specification, see Section 10.5, so we should now implement it in OpenModelica.

As a first step, it has to be accepted by the front end, which currently fails when fed a model such as
```modelica
model M1
  Real x[2] = {1, 2};
  Real y = (x.*x)[2];
end M1;
```
In this case, I guess the front-end could constant-evaluate y to be 4. In general, however, the expression could be time-varying, e.g.
```
model M2
  Real x[2](start = {1, 2}, each fixed = true);
  Real y = (x.*x)[2];
equation
  der(x) = -x;
end M2;
```
and thus need to be handled by the backend.

@perost, @kabdelhak, @phannebohm what do you think? Should we only do it in the new backend?

Until the (new) backend is ready, we could handle it by having the frontend generate auxiliary variables that can be indexed. For example, model M2 could be transformed into
```
model M2
  Real x[2](start = {1, 2}, each fixed = true);
  Real y = $idx[2];
protected
  Real $idx[2] =  x.*x;
equation
  der(x) = -x;
end M2;
```
This is probably not super-efficient in all cases, since the whole array will always be computed even though maybe only a few elements are really needed, but at least avoids compilation errors. We already had such cases, where we had to fix the library to avoid this problem, if the arrays are small even such a simple solution would be perfectly OK.

**Comment by perost** [comment]
It's already supported by the frontend and backend since we generate subscripted expressions internally, we just need to add it to the parser.

**Comment by casella** [comment]
OK, very good. Please do that at your earliest convenience.

**Comment by perost** [comment]
#11448 adds support for subscripted expressions in the parser, and as mentioned it's already supported in the rest of the compiler. There's probably going to be some issues since we already have some old backend issues with subscripted expressions, but it should generally work now.
