### ISSUE TITLE
File | Load encrypted library should be grayed out in the regular open-source release

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11437]
As notices by @ceraolo, one can only load encrypted libraries using a special version of OpenModelica with encryption support. Regular versions can't do that, so I guess the File | Load encrypted library menu item should be greyed out there.

**Comment by perost** [comment]
Or just removed? Or possibly keep it and show a popup message when the user tries to use it that explains why it can't be used. Just deactivating it without explanation doesn't seem very user friendly.

**Comment by casella** [comment]
Maybe a popup with explanation would be the best option. This could be the text:
> The open-source versions of OpenModelica cannot handle encrypted libraries, because the private key for decryption cannot be made public published.'
>
> OpenModelica supports loading encrypted libraries through SEMLA technology, provided by Modelon AB. For that, you need a special version of OpenModelica that is only released in binary form; please contact your library supplier for information on how to get it.

**Comment by casella** [comment]
On the other hand, the Export | Encrypted Library is just greyed out. Maybe it's best to explain the whole story in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/encryption.html).

**Comment by casella** [comment]
> On the other hand, the Export | Encrypted Library is just greyed out. Maybe it's best to grey out Load Encrypted Library as well and explain the whole story in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/encryption.html).

**Comment by adeas31** [comment]
I think we should popup a message so this can reach more people.

![image](https://github.com/OpenModelica/OpenModelica/assets/4007231/dfc06c51-5ba2-4494-b9ca-4b621ef43864)

> On the other hand, the Export | Encrypted Library is just greyed out. Maybe it's best to grey out Load Encrypted Library as well and explain the whole story in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/encryption.html).

The option will only be enabled for top level package stored in a folder structure. SEMLA doesn't yet support encryption of single file models.

**Comment by casella** [comment]
@adeas31, LGTM, except that you should remove "published" from "cannot be made public published" 😃

**Comment by adeas31** [comment]
I just copied the text that you proposed without noticing it :)

**Comment by casella** [comment]
Sorry about that :)
