### ISSUE TITLE
Simulation progress bar doesn't work with GBODE when equidistant time grid is deactivated.

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11433]
If you run this model
```modelica
model TestEquidistant
  Real x(start = 0, fixed = true);
  Real v(start = 1, fixed = true);
  Real f=30*sin(10000*time);
equation
  der(x) = v;
  der(v) = -5000*x -20*v + f;
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_STDOUT,LOG_ASSERT,LOG_STATS", s = "gbode", variableFilter = ".*"));
end TestEquidistant;
```
in OMEdit, you happily see the progress bar going from 0 to 100% over time. However, if you add the no equidistant time grid option, the progress bar remains stuck at 0% until the end of the simulation.
```modelica
model TestEquidistant2
  Real x(start = 0, fixed = true);
  Real v(start = 1, fixed = true);
  Real f=30*sin(10000*time);
equation
  der(x) = v;
  der(v) = -5000*x -20*v + f;
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_STDOUT,LOG_ASSERT,LOG_STATS", s = "gbode", variableFilter = ".*", noEquidistantTimeGrid = "()"));
end TestEquidistant2;
```
This is not happening if you use the default dassl solver; with this solver, the progress bar works fine both with and without equidistant time grid.

@adeas31 what kind of output is required from the runtime to properly update the progress bar status? Do you understand what is going wrong with gbode, with respect to dassl?

Thanks!

**Comment by adeas31** [comment]
@AnHeuermann can you please check this? OMEdit doesn't receive the progress status when no equidistant time grid option is used.

**Comment by AnHeuermann** [comment]
I'll have a look.

**Comment by AnHeuermann** [comment]
This is because when calling GBODE to do a step
```
LOG_SOLVER        | info    | call solver from 0 to 0.002 (stepSize: 0.002)
```

it's doing one step until the end time is reached.
So no progress is communicated until that "first" and only GBODE step is done.

I see two solutions:
  1. Don't have a main integration loop inside GBODE itself, but return back to the solver_main_step after each step.
  2. Add an extra communication for OMEdit in each step: Add `communicateStatus` at the end of the main integration loop of GBODE.

**Comment by AnHeuermann** [comment]
For 2: https://github.com/OpenModelica/OpenModelica/pull/11461 (but I don't like to have to main integration loops)

**Comment by casella** [comment]
I have no strong opinions on this.

**Comment by casella** [comment]
In fact, I would do it the same way as we do it with other variable step-size solvers such as IDA or DASSL.
