### ISSUE TITLE
Memory leak in GBODE

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11431]
### Steps to Reproduce

Load the attached [HeatingSystemExogenous.mo](https://github.com/OpenModelica/OpenModelica/files/13077728/HeatingSystemExogenous.mo.txt) library, then run one of the two last models in the package. The simulation runs for several minutes, during which the memory footprint of the simulation executable grows by about 100 kB/min.

This happens both for single- and multi-rate operation.

### Expected Behavior

The memory footprint of the executable file should remain constant during simulation, as it happens if you simulate the models using DASSL.

**Comment by AnHeuermann** [comment]
Running Valgrind:

```bash
valgrind --suppressions=../omc-boehm-gc.suppr --leak-check=full -v ./HeatingSystemExogenous.HeatingSystem_N_1000_SR_ESDIRK -override=stopTime=1,stepSize=0.1 -s=gbode -noEquidistantTimeGrid -gbratio=0.05 &> ../valgrind_gbode.log
```

reveals:

```
==18487== 3,846,720 (480 direct, 3,846,240 indirect) bytes in 30 blocks are definitely lost in loss record 114 of 118
==18487==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==18487==    by 0x4B6F1DF: SUNMatNewEmpty (sundials_matrix.c:36)
==18487==    by 0x4B77E0B: SUNSparseMatrix (sunmatrix_sparse.c:68)
==18487==    by 0x4A93837: nlsKinsolFScaling (kinsolSolver.c:856)
==18487==    by 0x4A9460D: nlsKinsolSolve (kinsolSolver.c:1163)
==18487==    by 0x4AC0516: solveNLS (nonlinearSystem.c:1034)
==18487==    by 0x4A73CC1: solveNLS_gb (gbode_nls.c:490)
==18487==    by 0x4A77A82: expl_diag_impl_RK (gbode_step.c:298)
==18487==    by 0x4A6E93C: gbode_birate (gbode_main.c:1238)
==18487==    by 0x4A72B57: gbode_main (gbode_main.c:2041)
==18487==    by 0x4AC82BF: solver_main_step (solver_main.c:191)
==18487==    by 0x23A68E: HeatingSystemExogenous_HeatingSystem_N_1000_SR_ESDIRK_performSimulation (in /home/aheuermann/workspace/Testitesttest/issue-11431/temp/HeatingSystemExogenous.HeatingSystem_N_1000_SR_ESDIRK)
```

We lose memory in https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/kinsolSolver.c#L871

```C
      spJac = _omc_SUNSparseMatrixVecScaling(kinsolData->J, kinsolData->xScale);
```

**Comment by casella** [comment]
Great, thanks @AnHeuermann!

I'll check this tomorrow with the new nightly build.

**Comment by casella** [comment]
I tried GBODE both single- and multi-rate and the memory consumption is now fixed throughout the simulation.

Thanks @AnHeuermann!
