### ISSUE TITLE
Error when duplicating single-file packages into multi-file

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11442]
### Steps to Reproduce
_To reproduce the issue I need to share privately package TestEncr.mo, which cannot be put on a public environment as this discussion._
(this list of steps requires System Library EHTPlib to be previously installed)
1. Open TestEncr.mo. 
2. Double click on DCT: the file opens without errors
3. Duplicate TestEncr into a new package, TestEncrMF, with "Directories For All" structure
4. double-click on TestEncrMF.DCT
The following error appears:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/5e71aa61-b39c-4388-b859-37f7f3ddc2d9)

### Expected Behavior
The multi-file version should behave ad the single-file version. DCT should open without errors.

### Version and OS
OM 1.22-beta6 (with encryption)

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@ceraolo can you please check this with the new Duplicate feature?

**Comment by ceraolo** [comment]
I've checked today with 1.25.0-dev24 and **the issue is still there.** 
I can send the package privately to reproduce the issue.

**Comment by adeas31** [comment]
Please send the package.

**Comment by casella** [comment]
You can also re-open this one: Reduce, Reuse, Recycle 😃
