### ISSUE TITLE
Provide buildDescription.xml to exported FMUs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11441]
@t-sommer reports that trying to compile an exported FMU of the model Modelica.Mechanics.Rotational.Examples.CoupledClutches from source code directly with MS Visual Studio 2022 gives the error:
```
C:\Users\tsr2\AppData\Local\Temp\tmp1le065or\sources\gc/omc_gc.h(48): fatal error C1083:
Cannot open include file: 'pthread.h': No such file or directory
```
Since support for pthreads may not be available, @mahge suggested to manually set OMC_NO_THREADS, so that the compilation won't use pthreads at all. 

FMI 2.0.4 (p. 71) defines buildDescription.xml (originally defined in FMI 3.0) to support this automatically. We should also have OMC FMI 2.0 export generate this file to avoid this kind of problems. This would also be one step in the direction of supporting FMI 3.0

**Comment by AnHeuermann** [comment]
Duplicate of https://github.com/OpenModelica/OpenModelica/issues/10548.

**Comment by casella** [comment]
Oops 😅
