### ISSUE TITLE
EHPTExamples.PSD.PSecu1 started failing at simulation stage after pr #11429

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11462]
### Description
Recently, model EHPTExamples.PSD.PSecu1 started failing during simulation. 
OM output is as follows:

```
Environment - simulationEnvironment:
startTime=0
stopTime=1400
tolerance=0.0001
numberOfIntervals=500
stepSize=2.8
Regular simulation: ./EHPTexamples_main_EHPTexamples.PSD.PSecu1  -abortSlowSimulation -alarm=480 -lv LOG_STATS
LOG_STDOUT        | info    | ... loading "iceSpecificCons" from "PSDmaps.txt"
LOG_ASSERT        | debug   | Not possible to open file "PSDmaps.txt": No such file or directory
LOG_ASSERT        | info    | simulation terminated by an assertion at initialization
```
So the issue is that it was impossible to open PSDmaps.txt. In PSecu1 loading of PSDmaps was requested here:

```
 EHPTlib.MapBased.TwoFlangeConn mot(effTableName = "motEffTable", mapsFileName = Modelica.Utilities.Files.loadResource("modelica://EHPTexamples/Resources/PSDmaps.txt"), mapsOnFile = true) ;
```

I noted that, instead, EHPTExamples.PSD.PSecu3 simulates. Its ouput is: 

```
Environment - simulationEnvironment:
startTime=0
stopTime=1400
tolerance=0.0001
numberOfIntervals=500
stepSize=2.8
Regular simulation: ./EHPTexamples_main_EHPTexamples.PSD.PSecu3  -abortSlowSimulation -alarm=480 -lv LOG_STATS
LOG_STDOUT        | info    | ... loading "iceSpecificCons" from "/home/hudson/saved_omc/libraries/.openmodelica/libraries/EHPTexamples main/Resources/PSDmaps.txt"
LOG_STDOUT        | info    | ... loading "Cycle" from "/home/hudson/saved_omc/libraries/.openmodelica/libraries/EHPTexamples main/Resources/NEDC.txt"
LOG_SUCCESS       | info    | The initialization finished successfully with 3 homotopy steps.

``` 

In this case, file PSDmaps.txt is found. In Ecu3 loading PSDmaps is requested here:

```     EHPTlib.MapBased.IceConnPOO ice(
mapsFileName=Modelica.Utilities.Files.loadResource("modelica://EHPTexamples/Resources/PSDmaps.txt"),    wIceStart = wIceStart,    flange_a(phi(start=0, fixed=true))) ; 

```

I cannot see any reasonable difference between PSecu1 and PSecu3 ways of asking for PSDmaps.txt possibly causing failure. These models started failing here:

https://libraries.openmodelica.org/branches/history/master/2023-10-23%2023:17:30..2023-10-24%2023:40:02.html

**Comment by casella** [comment]
@ceraolo the [regression report](https://libraries.openmodelica.org/branches/history/master/2023-10-23%2023:17:30..2023-10-24%2023:40:02.html) spans three commits to omc and three commits to your libraries.

The commits to omc seem pretty unrelated to me:
- the first is an update to the text of the user's guide
- the second concerns the new backend, that is not used for testing
- the third concerns #11429, which is about external object, that I guess you are not using in EHPTlib (are you)

To me, it's most likely that something got wrong with your latest thee commits to the libraries. You can easily checkout earlier commits and test them with the latest nightly build, to see if those are the problem, or rather the new nightly build.

**Comment by ceraolo** [comment]
> * the third concerns [Alias replacement for external object array equations #11429](https://github.com/OpenModelica/OpenModelica/pull/11429), which is about external object, that I guess you are not using in EHPTlib (are you)

Well, as you can see in the ticket's description, the offending command contains loadResource() to access a txt file. Can this be impacted by PR 11429? 
> 
> To me, it's most likely that something got wrong with your latest thee commits to the libraries. 

Before posting this I verified that my latest version of the libraries works well wih my OM (beta6)

**Comment by ceraolo** [comment]
> You can easily checkout earlier commits and test them with the latest nightly build, to see if those are the problem, or rather the new nightly build.

I still believe that https://github.com/OpenModelica/OpenModelica/issues/11462#issuecomment-1783830077 is the most relevant thing to say.

However I did more:
- checked out the most recent EHPTexamples
- updated on my Linux VM OM (got nightly1.23-dev-90)
- ran PSecu1
=> it simulates on my PC.

So, I really cannot envisage what is wrong when it is being tested on the OM site.
It is totally out of my control; I even cannot obtain the logs mentioned in this ticket's description anymore (don't even remember how I did when opened the ticket).

**Comment by ceraolo** [comment]
Thank you.
I'll also try myself to investigate more.

**Comment by casella** [comment]
See #2 for another issue reported on the same regression report.

**Comment by casella** [comment]
The flat `EHPTExamples.PSD.PSecu1` model contains the following declaration:
```
parameter String ice.toGramsPerkWh.fileName = "PSDmaps.txt" "File where matrix is stored";
```
"PSDmaps.txt" is searched in the default directory, rather than in the `Resources` directory, as it should.

**Comment by casella** [comment]
@ceraolo I would suggest that you make an official release on GitHub, so we can separately test the development version of your library on the main branch and the stable released version. That makes it easy to tell apart issues caused by the library development (which will only affect the former in the regression reports) from issues caused by OMC bugs (which will likely affect both).

**Comment by ceraolo** [comment]
Thank you for all the ttieme on this ticket.

I could make the official release..
Or at least I will be more careful about checking changes before committing, and before drawing consequences when regressions are reported on my libraries.

**Comment by casella** [comment]
> Or at least I will be more careful about checking changes before committing, and before drawing consequences when regressions are reported on my libraries. I did make all my checks that all models were not broken with Dymola, which is more tolerant tham OM with that dangling "mapsOnFile". The next time I will repeat them with OM.

The whole point of having both the stable and development version under CI testing is precisely that you can worry a bit less about introducing regressions, because they will be reported on the following day on a systematic basis. If that happens, you can roll back and figure out what's wrong, otherwise there's no need to worry.

**Comment by casella** [comment]
In case you make the release, please let me know, so I can add the development version report; by default, we test the latest official release, or the version on master if there are none.

**Comment by casella** [comment]
All fine now:
- https://libraries.openmodelica.org/branches/master/EHPTlib_main/EHPTlib_main.html
- https://libraries.openmodelica.org/branches/master/EHPTexamples_main/EHPTexamples_main.html

**Comment by ceraolo** [comment]
> @ceraolo I would suggest that you make an official release of your libraries on GitHub, so we can separately test the development version of your library on the main branch and the stable released version. 

I've just marked today's state of the two libraries EHPTlib and EHPTexamples as release v2.1.4 (first release).
Thank you for the suggestion.

**Comment by casella** [comment]
Good! I just updated the CI configuration. If everything works fine, you should get two reports for each library, the one with the `_latest` suffix points to the main branch HEAD version, while the other one uses the last released version. Of course they will be identical until you make some commit to the main branch.
