### ISSUE TITLE
Near zero real comparison gives unexpected results

### ISSUE THREAD

**Issue by JayHuLBL** [OpenModelica/OpenModelica#11468]
### Steps to Reproduce

- Load Modelica Buildings Library
- Create a model using following script
```
model Greater_test "Validation model for the Greater block"
  Buildings.Controls.OBC.CDL.Reals.Greater gre
     "Greater block, without hysteresis"
      annotation (Placement(transformation(extent={{40,-10},{60,10}})));
  Buildings.Controls.OBC.CDL.Reals.Sources.Pulse pul(period=1, shift=0.1)
      annotation (Placement(transformation(extent={{-40,10},{-20,30}})));
  Buildings.Controls.OBC.CDL.Reals.Sources.Constant con(k=0)
      annotation (Placement(transformation(extent={{-40,-40},{-20,-20}})));
equation 
  connect(con.y, gre.u2)
      annotation (Line(points={{-18,-30},{20,-30},{20,-8},{38, -8}}, color={0,0,127}));
  connect(pul.y, gre.u1) annotation (Line(points={{-18,20},{20,20},{20,0},{38,0}}, color={0,0,127}));
      annotation ( experiment(StopTime=1.5, Tolerance=1e-06));
end Greater_test;
```
- run the simulation
- check the results: we will see that the `gre.y` stays `true` even when both `gre.u1` and `gre.u2` become zero.
![Omc-1](https://github.com/OpenModelica/OpenModelica/assets/23491921/9d6ac81f-1137-442c-a6d5-780fcccd4595)
![Omc-2](https://github.com/OpenModelica/OpenModelica/assets/23491921/4902bf06-8d71-4103-a0bd-b2b6dd749d88)

### Expected Behavior
The `gre.y` should become `false` when both `gre.u1` and `gre.u2` are zero.

### Screenshots
![Greater_test](https://github.com/OpenModelica/OpenModelica/assets/23491921/cec2e23a-65ea-4af3-87d1-534142462c0b)

### Version and OS

 - OpenModelica Version: OpenModelica 1.23.0~dev-59-g7a41456
 - OS: Ubuntu 20.04.4
 - Versions of used Modelica libraries if applicable: Modelica Buildings Libarary 10.0.0

**Comment by Arinomo** [comment]
Maybe related [8600](https://github.com/OpenModelica/OpenModelica/discussions/8600) and [11049](https://github.com/OpenModelica/OpenModelica/issues/11049)

**Comment by casella** [comment]
> Maybe related [8600](https://github.com/OpenModelica/OpenModelica/discussions/8600) and [11049](https://github.com/OpenModelica/OpenModelica/issues/11049)

Absolutely. @JayHuLBL please check the discussion in those two tickets. I don't think it is possible _in general_ to obtain a reliable behaviour with conditions such as `x >= threshold` when `x == threshold`.

The only case when this really works is when you compare to zero some parameter that is explicitly assigned to zero, e.g.
```modelica
  parameter Real p = 0;
equation
  if p > 0 then 
     ...
  end if;
```
If you leave the parameter to the default value of zero, the conditional equation will be deactivated, if you assign it explicitly to a nonzero value, it will be activated.

However, if `p` is the result of a computation, then it won't be reliable.

**Comment by JayHuLBL** [comment]
@casella Thanks for the clarification. I did read the two tickets and see the difficulty. We will find a work around to avoid the comparison.
