### ISSUE TITLE
Loss of zooming on plot window when selecting an additional variable

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11474]
### Description

On plot window, select a variable and make zoom over a part of it. Then select an additional variable -> the zoom is loosed and all timeline is shown again,

### Steps to Reproduce

See description.

### Expected Behavior

The zoom shall not be loosed after adding/removing variables.

### Screenshots

N/A

### Version and OS

OpenModelica v1.22.0-dev.beta.6 (64-bit)
 - OS: Windows 10, 64 bit

### Additional Context

N/A

**Comment by casella** [comment]
Seems reasonable to me. @adeas31 can you do that?

**Comment by adeas31** [comment]
This is because the `Auto Scale` option is on my default. Disable it if you want to retain the zoom.
