### ISSUE TITLE
lack of libicuucd67.dll when run the OMEdit.exe after build correctly

### ISSUE THREAD

**Issue by chygithub2020** [OpenModelica/OpenModelica#11478]
### Description
os：windows 10 home
build：cmake
introduction: REDEME.Windows.md
code branch: master
details:build the project correctly but OMEdit.exe can not work and show the information that lack of libicuucd67.dll.(Some modules can work correctly such as OMNotebook )

**Comment by chygithub2020** [comment]
Thank you so much!I have solved the problem.I find the lacked files in "OMDev\tools\msys\mingw64\bin" and copy them to "install_cmake/bin" so that it works.I guess it was caused by the neglect in install.

**Comment by mahge** [comment]
@anotheruserofgithub @chygithub2020 can you tell me exactly how you configured the project? i.e., 
- Are you using OMDev or an fresh MSYS/MinGW installation?
- The CMake command you used to configure the project. 

The error reported here should not happen and the DLLs are supposed to be copied for you automatically.  I can see that we copy `libicuuc67.dll` but not `libicuucd67.dll`. Seems like this has something to do with a debug build although I am not sure why it happened now since OMDev has not been changed recently as far as I know.

**Comment by chygithub2020** [comment]
I copy libicuucd67.dll and libicudtd67.dll.And I use the OMDEV for the build.And the cmake commands are as follows:

- cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles"
- cd build_cmake/
- make -j8 install -Oline

**Comment by mahge** [comment]
> I'm using OMDev and I was using [these instructions](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Windows.md#21-msys-and-cmake). I had not compiled on Windows since February, so yesterday I just updated the OpenModelica repository to master, cleaned up everything, and ran the cmake+make commands. If I remember correctly, there are several (all?) debug versions of libicu*.dll that are missing in bin at the end, and maybe other libraries as well but I didn't check.

I see. Then something must have changed recently and I did not notice. I will check properly and add the missing DLLs. 

> Also, I noticed that the OMEdit executable that I compiled with CMake was about 170MB while with Make it is about 280MB, is that expected? (It was working fine, but maybe something to do with debug/release modes, or -g compiler option?)

It might be related to static vs dynamic linking of the needed libraries. If so, I don't think it should not affect how OMEdit works at all as long as it starts up.

**Comment by mahge** [comment]
> I copy libicuucd67.dll and libicudtd67.dll.And I use the OMDEV for the build.And the cmake commands are as follows:
> 
> * cmake -S . -B build_cmake -Wno-dev -G "MSYS Makefiles"
> * cd build_cmake/
> * make -j8 install -Oline

Looks perfectly fine. I am not sure why the required DLLs changed suddenly but I will check and see if we can add them to the installation anyway.

**Comment by mahge** [comment]
This should be fixed with #11490. If you encounter other issues with the CMake build, please feel free to open new tickets.
