### ISSUE TITLE
fatal error: filesystem: No such file or directory  #include <filesystem> 

### ISSUE THREAD

**Issue by chygithub2020** [OpenModelica/OpenModelica#11472]
### Description
when Building C object OMCompiler/Compiler/boot/CMakeFiles/bomc.dir/bomc/bootstrap-sources/build/BackendInterface.c.o,the error
"fatal error: filesystem: No such file or directory
 #include <filesystem>
"occurs.
### Environment
os:Ubuntu 18.04
guide:REDEME.Linux.md

**Comment by casella** [comment]
Maybe Ubuntu 18.04 is a bit old? End of life was April 2023.

**Comment by perost** [comment]
Yes, default GCC in Ubuntu 18.04 seems to be 7.4.0 which is still using the pre-C++17 `<experimental/filesystem>` instead of the standard `<filesystem>`. The oldest GCC we build with ourselves seems to be 8.5.0, but I think any GCC 8 version should work.
