### ISSUE TITLE
Lacks of dll when run the .exe file after build without errors

### ISSUE THREAD

**Issue by chygithub2020** [OpenModelica/OpenModelica#11477]
### Description
I build by cmake tools without errors but when I click the OMEdit.exe it shows the lacks of some dlls including libOpenModelicaRuntimeC.dll,libOpenModelicaCompiler.dll,libomcgc.dll,libOMPlotLib.dll.
My exe path:C:\path\to\OpenModelica\build_cmake\OMEdit\OMEditGUI

**Comment by chygithub2020** [comment]
os:windows 10 home

**Comment by casella** [comment]
@chygithub2020 is this issue resolved for you?
