### ISSUE TITLE
Windows MSYS build failure: collect2.exe: error: ld returned 1 exit status make[2]:

### ISSUE THREAD

**Issue by sunmin89** [OpenModelica/OpenModelica#11488]
### Description

collect2.exe: error: ld returned 1 exit status
make[2]: *** [OMEdit/OMEditGUI/CMakeFiles/OMEdit.dir/build.make:167: OMEdit/OMEditGUI/OMEdit.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:8135: OMEdit/OMEditGUI/CMakeFiles/OMEdit.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

#### Install the latest msys2 environment
https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-x86_64-20231026.exe

#### install all the dependencies
```
 pacman -S zip unzip make libtool flex mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-binutils mingw-w64-x86_64-curl mingw-w64-x86_64-libiconv mingw-w64-x86_64-readline mingw-w64-x86_64-expat mingw-w64-x86_64-libsystre mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-opencl-headers mingw-w64-x86_64-openblas mingw-w64-x86_64-qt5 mingw-w64-x86_64-qtwebkit mingw-w64-x86_64-OpenSceneGraph mingw-w64-x86_64-boost mingw-w64-x86_64-python-numpy mingw-w64-x86_64-mesa
```

#### Generate the makefile
```
 cmake -S . -B build_cmake-msys -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=omc-win64-rel -DOM_OMEDIT_INSTALL_RUNTIME_DLLS=OFF -Wno-dev
```

#### Make install

```
cmake --build build_cmake-msys --target install --parallel 3
```

### Screenshots

![image](https://github.com/OpenModelica/OpenModelica/assets/17847861/657b21ed-9371-425c-9f79-953f85ce656f)

![image](https://github.com/OpenModelica/OpenModelica/assets/17847861/819876fe-36b1-401b-b609-59f20a6b6bff)

### Version and OS

 - OpenModelica Version: The latest source code
 - OS: [Windows 10, 64 bit]
 

### Here I pasted all the logs
[config-log.txt](https://github.com/OpenModelica/OpenModelica/files/13235994/config-log.txt)
[Makefile.txt](https://github.com/OpenModelica/OpenModelica/files/13235995/Makefile.txt)
[make-install.txt](https://github.com/OpenModelica/OpenModelica/files/13235996/make-install.txt)

**Comment by mahge** [comment]
There has been a recent change in MSYS regarding the libraries `libbfd`, `libiberity` and `libsframe`.  We already have https://github.com/OpenModelica/OpenModelica/pull/10939 addressing these changes but it is not merged yet.  For now you can replace the contents of the file `OpenModelica\cmake\modules\Findbinutils.cmake` with this


```cmake
# This small module (which is not as 'proper' as it should be) finds and sets up
# libbfd from binutils. libbfd is need for providing crash reporting backtrace
# support for OMEdit on Windows (OMDev/MinGW). Unfortunately neither CMake nor
# the binutils people provide a CMake module or config files to set up the libraries.

# This small module tries to find libbfd as well as its dependencies. Currently these
# are libiberty, libsframe, libzstd and libintl. The first two are part of the binutils packages
# so we manually manage the finding here.

# zstd is a separate package and comes with its own CMake config files
# (at least on recent versions) so we use that. That is perfect.

# libintl is also a separate package and a find module is provided by CMake
# itself for now (albeit old style, i.e, no imported targets)

# Finally this module exports an imported targets 'binutils::bfd', 'binutils::iberty' and
# binutils::sframe to be used as needed.

if(binutils_FOUND)
  return()
endif()

find_library(LIBBFD_LIBRARY
             NAMES libbfd.a)

find_library(LIBIBERTY_LIBRARY
             NAMES libiberty.a)

find_library(LIBSFRAME_LIBRARY
             NAMES libsframe.a)


if(MINGW)
  find_path(BINUTILS_INCLUDE_DIR
            bfd.h
            PATHS include)
endif()

include (FindPackageHandleStandardArgs)


# handle the QUIETLY and REQUIRED arguments and set binutils_FOUND to TRUE if all listed variables are TRUE
find_package_handle_standard_args(binutils
                                  REQUIRED_VARS LIBBFD_LIBRARY LIBIBERTY_LIBRARY LIBSFRAME_LIBRARY BINUTILS_INCLUDE_DIR
                                  HANDLE_COMPONENTS)

mark_as_advanced(LIBBFD_LIBRARY LIBIBERTY_LIBRARY LIBSFRAME_LIBRARY BINUTILS_INCLUDE_DIR)

if(binutils_FOUND)

  find_package(Intl REQUIRED)
  find_package(zstd CONFIG REQUIRED)

  add_library(binutils::iberty STATIC IMPORTED)
  set_target_properties(binutils::iberty PROPERTIES IMPORTED_LOCATION ${LIBIBERTY_LIBRARY})

  add_library(binutils::sframe STATIC IMPORTED)
  set_target_properties(binutils::sframe PROPERTIES IMPORTED_LOCATION ${LIBSFRAME_LIBRARY})

  add_library(binutils::bfd STATIC IMPORTED)
  set_target_properties(binutils::bfd PROPERTIES IMPORTED_LOCATION ${LIBBFD_LIBRARY})
  set_target_properties(binutils::bfd PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${BINUTILS_INCLUDE_DIR})

  target_link_libraries(binutils::bfd INTERFACE binutils::iberty)
  target_link_libraries(binutils::bfd INTERFACE binutils::sframe)
  target_link_libraries(binutils::bfd INTERFACE zstd::libzstd_static)
  target_link_libraries(binutils::bfd INTERFACE ${Intl_LIBRARIES})
endif()
```

Just remove everything from that file and replace it with the code above. 

Let me know how it goes.

**Comment by sunmin89** [comment]
> Let me know how it goes.

Wow，thanks, it works!

I can launch the OMEdit now, it's fantastic.

**Comment by mahge** [comment]
> I can launch the OMEdit now, it's fantastic.

Perfect. 

Just one more thing, I can see in your configure command, you have `-DOM_OMEDIT_INSTALL_RUNTIME_DLLS=OFF`. With this option off, you can launch OMEdit from the MSYS/MinGW64 terminal but NOT from the Windows explorer directly.

I recommend you reconfigure the project once more and set this to ON. That is, don't just skip it but actually specify `-DOM_OMEDIT_INSTALL_RUNTIME_DLLS=ON` the next time you configure. After that, if you need to configure again, you can skip it completely since CMake will remember the value set in the last run.

**Comment by sunmin89** [comment]
> I recommend you reconfigure the project once more and set this to ON. That is, don't just skip it but actually specify `-DOM_OMEDIT_INSTALL_RUNTIME_DLLS=ON`

Hi,mahge:

I tried configure again with this flag, but failed.

```
CMake Error at OMEdit/OMEditGUI/CMakeLists.txt:30 (message):
  Environment variable "OMDEV" is not set.
```

But I can't clone the OMDev repo.



> I can launch the OMEdit now, it's fantastic.

Besides, I can't compile any `.mo` file.

```
$ omc Hello.mo
We could not find some needed MINGW paths in $OPENMODELICAHOME or $OMDEV. Sear
ched for paths:
        D:/work/omc/OpenModelica/omc-win64-rel\tools\msys\mingw64\bin [not fou
nd]
        D:/work/omc/OpenModelica/omc-win64-rel\tools\msys\mingw64\lib\gcc\x86_
64-w64-mingw32\13.2.0 [not found]
Error processing file: Hello.mo
[D:/work/omc/OpenModelica/duduwa/Hello.mo:2:19-2:29:writable] Error: Modified
element fixes not found in class Real.

# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed!
```
could you give a hand.
