### ISSUE TITLE
OMEdit does not show connection lines inside for loops when using instance API

### ISSUE THREAD

**Issue by BernhHammmer** [OpenModelica/OpenModelica#11489]
### Description
Connections are not showing when created in for-loop.

### Steps to Reproduce
Create this model

```Modelica
model Test
  parameter Integer nHeatFlows = 2;
  Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemperature annotation(Placement(transformation(origin = {26, 0}, extent = {{10, -10}, {-10, 10}})));
  Modelica.Thermal.HeatTransfer.Sources.FixedHeatFlow[nHeatFlows] fixedHeatFlow annotation(Placement(transformation(origin = {-32, 0}, extent = {{-10, -10}, {10, 10}})));
equation
 for i in 1:nHeatFlows loop
   connect(fixedTemperature.port, fixedHeatFlow[i].port) annotation(Line(points = {{16, 0}, {-22, 0}}, color = {191, 0, 0}));
 end for;

annotation(
    uses(Modelica(version = "4.0.0")));
end Test;
```

### Expected Behavior
The connection is shown:
![image](https://github.com/OpenModelica/OpenModelica/assets/143067908/30670cd3-9599-4abf-a594-3ac59fb79d51)

### Screenshots
![image](https://github.com/OpenModelica/OpenModelica/assets/143067908/a974c07e-bbef-4823-83ce-9380fe5456d7)

### Version and OS
Connected to OpenModelica v1.22.0-dev.beta.6 (64-bit)
OS: Windows 10, 64 bit

**Comment by perost** [comment]
Fixed in #11491. Connections in for-loops weren't dumped when using the instance API previously because we didn't know what information we needed for them, but for now just dumping them as they are seems to be good enough.

**Comment by perost** [comment]
Also ported to 1.22 in #11494.

**Comment by casella** [comment]
Sorry, I was mistaken. 1.22.0 is tag 2997235, which includes Per's commit to the maintenance branch. So, this is actually in 1.22.0.
