### ISSUE TITLE
The NB cannot handle binding equations with time-varying Complex RHS

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11504]
I am trying to understand how far we are from being able to support power grid models in the NB. I prepared the following MWE collection:

```modelica
package ComplexTestNB
  model T01
    parameter Complex z1 = Complex(1);
    parameter Complex z2 = Complex(0, 1);
    parameter Complex z3 = z1 + z2;
    Complex z4, z5;
  equation
    z4 = z1*z2;
    z5 = z1/z2;
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T01;

  model T02
    Complex z1 = Complex(1);
    Complex z2 = Complex(0, 1);
    Complex z3, z4, z5;
  equation
    z3 = z1 + z2;
    z4 = z1*z2;
    z5 = z1/z2;
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T02;
  
  model T03
    Complex z1;
    Complex z2;
    Complex z3, z4, z5;
  equation
    z1 = Complex(1);
    z2 = Complex(0, 1);
    z3 = z1 + z2;
    z4 = z1*z2;
    z5 = z1/z2;
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T03;
  
  model T04
    Complex z1, z2, z3, z4, z5;
  equation
    z1 = Complex(time,0);
    z2 = Complex(0,1);
    z3 = z1 + z2;
    z4 = z1*z2;
    z5 = z1/z2;
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T04; 
  
  model T05
    Complex z1;
  equation
    z1  = Complex(time,0);
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T05;

  model T06
    Complex z1 = Complex(time,0);
  equation
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T06;

  model T07
    Complex z1 = Complex(time,0);
    Complex z2 = Complex(0, 1);
    Complex z3, z4, z5;
  equation
    z3 = z1 + z2;
    z4 = z1*z2;
    z5 = z1/z2;
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T07;
  
  model T08
    parameter Real v_re_start = 1;
    parameter Real v_im_start = 0;
    parameter Real i_re_start = 1;
    parameter Real i_im_start = -0.3;
    parameter Complex Z = Complex(0.03,0.1);
    Complex v0 = Complex(1);
    Complex v(re(start = v_re_start), im(start = v_im_start));
    Complex i(re(start = i_re_start), im(start = i_im_start));
  equation
    v = v0 - Z*i;
    v*Modelica.ComplexMath.conj(i) = Complex(1,0.2);
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T08;
  
  model T09
    parameter Real v_re_start = 1;
    parameter Real v_im_start = 0;
    parameter Real i_re_start = 1;
    parameter Real i_im_start = -0.3;
    parameter Complex Z = Complex(0.03,0.1);
    Complex v0 = Complex(1);
    Complex v(re(start = v_re_start), im(start = v_im_start));
    Complex i(re(start = i_re_start), im(start = i_im_start));
    Real P,Q;
  equation
    v = v0 - Z*i;
    P = 1 + 0.1*time;
    Q = 0.2 + 0.1*time;
    v*Modelica.ComplexMath.conj(i) = Complex(P, Q);
    annotation(
      __OpenModelica_commandLineOptions = "--newBackend");
  end T09;
end ComplexTestNB;
```
This package contains the main patterns used in PowerGrids. As far as I see, they all work fine with the NB, except `T06` and `T07`, which both contain a binding equation with a time-varying RHS, and for both of which the NB complains it cannot match one variable.

It looks like this is the only remaining issue to get Complex numbers working in the NB. @kabdelhak can you please have a look an see how to fix that?

**Comment by kabdelhak** [comment]
Fixed with #11517.

The issues were mainly regarding binding equations that are not created from the records but from the attributes instead. So only bindings that could be _scalarized_ worked. Now we correctly create bindings from the records themselves and supress binding creation from record elements (since the binding should always be at the record instance). Is there a way record elements are bound individually?

Furthermore we now correctly differ between parameter records and regular records in the sense that binding equations are either created for simulation or initialization system.

Will close this for now, i added all your tests to the testsuite so it will be tested in the future. Feel free to reopen if you see issues with this approach.

**Comment by casella** [comment]
Thanks @kabdelhak! I'started another run of the newInst-newBackend job and see if we get improvements elsewhere.

> Is there a way record elements are bound individually?

I guess so, you can just write
```modelica
model T10
  Real a = 1;
  Real b = 1;
  Complex z(re = a, im = b);
end T10;
```
Is that what you meant?

**Comment by kabdelhak** [comment]
> Thanks @kabdelhak! I'started another run of the newInst-newBackend job and see if we get improvements elsewhere.
> 
> > Is there a way record elements are bound individually?
> 
> I guess so, you can just write
> 
> ```modelica
> model T10
>   Real a = 1;
>   Real b = 1;
>   Complex z(re = a, im = b);
> end T10;
> ```
> 
> Is that what you meant? This already worked before you last commit.

Yea this is what i meant, i hope this still works since i kind of prevent it now. Will test it!

**Comment by kabdelhak** [comment]
It was indeed broken due to my recent changes. I reworked the record parent<-> children interaction in #11542 it should be fixed now.

**Comment by casella** [comment]
Great! Can you please add `T10` in the testsuite? That pattern is used a lot in PowerGrids, so we definitely need to support it.
