### ISSUE TITLE
Provide feedback about the FMI generation process in OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11513]
If I select Export | FMU in OMEdit, a very lengthy process starts, during which there is no feedback to the end user. Even very small models take over 30s to compile, so this is quite confusing, because it is not clear if OMEdit is stuck, or it is rather doing its job.

We should output a log of the compilation process, as we do with regular simulations, so that OMEdit can intercept it and show it to the end user.

**Comment by bilderbuchi** [comment]
Dupe of #12828 (well, the other way round, actually), can be closed.

**Comment by casella** [comment]
Absolutely
