### ISSUE TITLE
SSP broken on Windows?

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11514]
### Description

I am having trouble running a simple FMU using SSP under OMEdit.

### Steps to Reproduce
- Open OMEdit
- Load the [M.mo.txt](https://github.com/OpenModelica/OpenModelica/files/13272981/M.mo.txt) as a ME-FMU
- File | New SSP model
- Right-click on Root and add new submodel M.fmu
- Simulation | Simulate

The following error is issued:
```
python C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/Francesco Casella/AppData/Local/Temp/OpenModelica/OMEdit//MySystem.ssp --endpoint-pub=tcp://127.0.0.1:49837 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 11, in <module>
    import OMSimulator as oms
ModuleNotFoundError: No module named 'OMSimulator'
Simulation process failed. Exited with code 0x00000001.
```
### Expected Behavior

The simulation should run.

Also, the simulation setup and simulate button should also be available in the toolbar, not only in the Simulation menu

 - OpenModelica Version: v1.23.0-dev-113-g1e7fc0a46f
 - OS: Windows 10, 64 bit

**Comment by arun3688** [comment]
@casella @adeas31  I can reproduce the issue, But it is not only for this model, but in general it is not possible to simulate any ssp models, I tried to load a simple `Modelica.Blocks.Math.Gain.fmu` in OMEdit and the simulation does not work and also the simulation button is not available in the tool bar. I get the same error as above, see the attached video , i recorded the video using ppt so just play the ppt  
[sspcrash.zip](https://github.com/OpenModelica/OpenModelica/files/13279804/sspcrash.zip)

The crash is related to OMEdit and not from OMSimulator side

**Comment by casella** [comment]
@adeas31 any thoughts about this?

**Comment by arun3688** [comment]
@casella the simulation of ssp is fixed now with this commit https://github.com/OpenModelica/OpenModelica/commit/5ba5f915e852b79cbbbb38b8bc6d8d6c15a6d3d6 , Please test the nightly builds from tomorrow. The remaining thing to be fixed is showing the simulation button in the tool bar for SSP which is missing and adeel can fix that

**Comment by adeas31** [comment]
PR #11529 will fix the toolbar issue. It was the regression from https://github.com/OpenModelica/OpenModelica/commit/15ab34cfbe9. @casella since the toolbars visibility is saved in the settings file that means you need to enable the simulation toolbar. Right click the toolbar and select simulation toolbar.

**Comment by casella** [comment]
@adeas31 can you please cherry-pick all these fixes to maintenance/v1.22?

Thanks!

**Comment by casella** [comment]
As discussed together in the OSMC devmeeting, I understand we use the latest version of OMSimulator on master when building OpenModelica and OMEdit, so we get these latest updates in OpenModelica regardless of the release process of OMSimulator. I think this is fine, and I believe these changes should definitely end up in 1.22.1.

I also think we should make a new patch release of OMSimulator 2.1.2 with the latest fixes that we applied. There was one in a branch mentioned by @adrpo for v1.22.0, and several now for 1.22.0 and 1.22.1. I see no reason to not have them all in OMSimulator 2.1.2.

**Comment by adeas31** [comment]
This was fixed and ported to 1.22.1. See #11529 and #11655. The only thing remaining is perhaps making a new OMSimulator release. I remember we asked @arun3688 to make a new release of OMSimulator since the one available now v2.1.1 is from Jan 29, 2021.

**Comment by arun3688** [comment]
@adeas31 @casella  It is not possible to merge OMSimulator in OpenModelica master due to this issue https://github.com/OpenModelica/OpenModelica/issues/11549 and that is because after @casella suggested to use the default experiment settings from the modeldescription.xml https://github.com/OpenModelica/OMSimulator/pull/1273, there are some problem with the cvode solver when the step size is too large, the results are looking wrong , and it is possible to fix the test by adjusting the stepSize from runtime argument, but Andreas said that is not a proper fix and we need to fix that before merging into master

**Comment by casella** [comment]
I'm sorry, but I am a bit confused about this statement:
> It is not possible to merge OMSimulator in OpenModelica master due to this issue https://github.com/OpenModelica/OpenModelica/issues/11549

I understood we were always using the master/HEAD revision of OMSimulator for the OpenModelica release, but apparently we aren't. How do we manage that, is it a submodule? What is the current policy to manage it?

**Comment by adeas31** [comment]
The developers of OMSimulator adds commits to OMSimulator. When its stable enough, they update the submodule that is part of the OpenModelica repo.

**Comment by casella** [comment]
OK, so the submodule just lacks the latest commits which fetch the interval from the model description xml file?

**Comment by arun3688** [comment]
@casella yes that is true, but we can make this test to work by tweaking the stepSize from commandLine and make jenkins and merge it with master, but andreas said we might forget about this issue

**Comment by casella** [comment]
To recap, the original problem is solved on master. Now OMEdit refuses to add the FMU (which was only exported with ME mode) because it doesn't support CS-mode. Not sure if this is the expected behaviour, but I'll open another ticket about it.

@adeas31 has already committed the toolbar fix to the maintenance/v1.22 branch. @arun3688, con you please cherry-pick 5ba5f91 to the maintenance branch as well, so we can close this? Thanks!

**Comment by casella** [comment]
I tried this again with yesterday's nightly build v1.23.0-dev-265-gf870bb666a, I still have a lot of issues:
- if I try to import an FMU that was only exported with ME mode, OMEdit doesn't allow me to do that because, it says, it lacks CS mode. Why should that be the case, if I just wanted to simulate it in ME mode?
- if I generate the FMU with both ME and CS I can import it, though I get many red scripting errors:
```
[1] 23:52:49 Scripting Error
[NewComponent] FMU "M" doesn't support co-simulation mode.

[2] 23:54:37 Scripting Error
[NewComponent] FMU "M" doesn't support co-simulation mode.

[3] 23:54:48 Scripting Error
[NewComponent] FMU "M" doesn't support co-simulation mode.

[4] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenEas.instanceName" with type "String"

[5] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenEas.substanceName" with type "String"

[6] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenTop.instanceName" with type "String"

[7] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenTop.substanceName" with type "String"

[8] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenWes.instanceName" with type "String"

[9] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "CO2SenWes.substanceName" with type "String"

[10] 00:03:33 Scripting Error
[NewConnector] Failed to import connector "sou.substanceName" with type "String"
```
- I still can't see the simulate button and the simulation setup button in the toolbar

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/58e83573-f7f1-4408-a9d6-889224e4e43b)

- if I use the Simulation | Simulate menu item, I get these runtime errors:
```
python C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/Francesco Casella/AppData/Local/Temp/OpenModelica/OMEdit//Test.ssp --endpoint-pub=tcp://127.0.0.1:53308 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "C:/Program Files/OpenModelica1.23.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 11, in <module>
    import OMSimulator as oms
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\__init__.py", line 17, in <module>
    Scope._init()
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\Scope.py", line 5, in _init
    _capi = capi()
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\lib\omc\OMSimulator\capi.py", line 14, in __init__
    dllDir = os.add_dll_directory(os.path.dirname(omslib))
  File "C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\mingw64\lib\python3.8\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'C:\\Program Files\\OpenModelica1.23.0-dev-64bit\\lib\\omc\\OMSimulator\\../../bin'
Simulation process failed. Exited with code 0x00000001.
```
My impression is that the OMSimulator OMEdit interface is seriously broken, at least on Windows. I'm not sure we can actually fix all this stuff for 1.22.2, but we should for sure do that in 1.23.0

@arun3688 can you please check again, using Windows? Maybe we should have a short meeting after the workshop and do this together. 

Thanks!

**Comment by arun3688** [comment]
@casella I will look into it and see if i can reproduce the issue, and we can have short meeting after the workshop

**Comment by adeas31** [comment]
Let me know if I can be of any help.

**Comment by arun3688** [comment]
@casella I tested your model and i am able to import the fmu with only `ModelExchange` support see the below image

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/067f14c0-5d25-471c-aa78-ff85b57ec354)

and if i try to import the `ModelExchange` FMU as a weakly coupled system, OMEdit reports the correct error messages see below

![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/39997041-a951-4269-a29f-2758f714f759)

And the following error messages you see below are the expected error messages

```
[1] 11:31:50 Scripting Error
[NewConnector] Failed to import connector "CO2SenEas.substanceName" with type "String"

[2] 11:31:50 Scripting Error
[NewConnector] Failed to import connector "CO2SenTop.substanceName" with type "String"

[3] 11:31:50 Scripting Error
[NewConnector] Failed to import connector "CO2SenWes.substanceName" with type "String"

[4] 11:31:50 Scripting Error
[NewConnector] Failed to import connector "sou.substanceName" with type "String"
```
Currently `OMSimulator` supports connectors of the following type , otherwise we report error 

1. Real
2. Integer
3. Enumeration 
4. Boolean

And Finally i can successfully simulate the ssp in OMEdit
![image](https://github.com/OpenModelica/OpenModelica/assets/6870949/28fa06ce-c778-47a2-9f3d-f15189bc6525)



> * I still can't see the simulate button and the simulation setup button in the toolbar

And this is still true, we cannot see the simulate button or the setup in the tool bar @adeas31  can you look into this

**Comment by arun3688** [comment]
@casella after discussing with Adeel, it seems that simulation tool bar is not visible because of the config settings in the previous version we can enable it by right click on the tool bar and check the simulation toolbar.

**Comment by casella** [comment]
OK, so
- [X] the toolbar can be activated from the menu
- the failing script needs an additional "../", we need to update the submodule with master
- @adrpo will install zmq python module in UCRT64 OMDev thing, so it gets into the Windows installer

**Comment by casella** [comment]
@adrpo fixed it, I'll try it ASAP

**Comment by ClemensLinnhoff** [comment]
I am having a similar issue.

@arun3688 you say:

 > Currently OMSimulator supports connectors of the following type , otherwise we report error
Real
Integer
Enumeration
Boolean

So type string is not supported at all? I get an error trying to import an FMU in OMEdit that has a string parameter:

```
[12] 10:53:18 Scripting Error
[NewConnector] Failed to import connector "xosc_path" with type "String"
```

But if string is not supported, why can I got to SSP -> Add Connector and then select String? If I do so, however, I get the same error message.

**Comment by arun3688** [comment]
@ClemensLinnhoff We do not support `String` type, In OMEdit this is a bug, we should remove the `String` type thanks for reporting it

**Comment by ClemensLinnhoff** [comment]
Is it planned to add support for String parameters in the future? I use it quite a lot.

**Comment by arun3688** [comment]
@ClemensLinnhoff Yes we will support it in future, can you provide a simple use case with string connectors

**Comment by ClemensLinnhoff** [comment]
That's good to hear.

One example is to specify the path to an input file. E.g. it is used in the OpenSCENARIO simulator esmini, when packaged as an FMU: https://github.com/esmini/esmini/tree/master/OSMP_FMU
The parameter `xosc_path` is used to set the path to an OpenSCENARIO file.

**Comment by ClemensLinnhoff** [comment]
I set the parameter of the FMU with SSP:

```
<ssd:ParameterBindings>
  <ssd:ParameterBinding>
      <ssd:ParameterValues>
          <ssv:ParameterSet version="1.0" name="Internal Parameter-Set">
              <ssv:Parameters>
                  <ssv:Parameter name="xosc_path">
                      <ssv:String value="/path/to/my/scenario.xosc"/>
                  </ssv:Parameter>
                  <ssv:Parameter name="use_viewer">
                      <ssv:Boolean value="true"/>
                  </ssv:Parameter>
              </ssv:Parameters>
          </ssv:ParameterSet>
      </ssd:ParameterValues>
  </ssd:ParameterBinding>
</ssd:ParameterBindings>
```

**Comment by arun3688** [comment]
@ClemensLinnhoff thanks I will try to fix this, i am little busy but i try to fix this probably this week or early next week.

**Comment by casella** [comment]
@ClemensLinnhoff the issue reported in this ticket was fixed. Please follow up #12183.
