### ISSUE TITLE
Enhancement proposal: keep clipboard content after downloading files

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11540]
### Description
This is a follow-up of #11533 
The description is in https://github.com/OpenModelica/OpenModelica/issues/11516#issuecomment-1802099418 and https://github.com/OpenModelica/OpenModelica/issues/11516#issuecomment-1802497710

### Steps to Reproduce
After closing #11516 when I download a package the clipboard containing stuff copyied from it is lost. This ticket proposes to keep that content for reuse, as Dymola does.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
This is now fixed with #11574, #11598, #11613 and #11644.

The clipboard data is not retained even after unloading a model and is also available across different OMEdit sessions.

**Comment by perost** [comment]
> This is now fixed with #11574, #11598, #11613 and #11644.
> 
> The clipboard data is not retained even after unloading a model and is also available across different OMEdit sessions.

"now" instead of "not" I assume?

**Comment by adeas31** [comment]
Yes 😃

**Comment by adeas31** [comment]
Ported this to 1.22.1 #11655
