### ISSUE TITLE
Icon layer: line thickness disappears with extend clause

### ISSUE THREAD

**Issue by angmarion** [OpenModelica/OpenModelica#11541]
### Steps to Reproduce

Declare a parent with a single line, and give the line a thickness attribute.
Declare a child extending from this model.
Actual behavior: line thickness in not kept.

### Expected Behavior

All graphical annotations from the parent should be kept in the inherited classes.

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Ubuntu 20.04

### File to reproduce the issue : 

[TestIcons.zip](https://github.com/OpenModelica/OpenModelica/files/13306290/TestIcons.zip)

**Comment by casella** [comment]
@perost can you handle this?

**Comment by perost** [comment]
> @perost can you handle this?

It's an OMEdit issue as far as I can tell.

**Comment by casella** [comment]
Isn't OMEdit getting the graphical annotations of the child class from the inst-based interface?

**Comment by perost** [comment]
> Isn't OMEdit getting the graphical annotations of the child class from the inst-based interface?

Yes, and that works just fine in this case.

**Comment by casella** [comment]
Weird. @adeas31 can you take care of that?

**Comment by angmarion** [comment]
In case it helps:

The annotation of the parent is
```
annotation(
      Icon(graphics = {Line(origin = {-36, 0}, points = {{-64, 0}, {136, 0}}, thickness = 2)}));
```
The icons are here:
![Parent_icon](https://github.com/OpenModelica/OpenModelica/assets/108278467/5bda4e68-5188-454f-b8cf-72e96f6048cd)
![Child_icon](https://github.com/OpenModelica/OpenModelica/assets/108278467/ecf96bc7-7c2a-43bf-8d27-9494665fef13)

It looks as if the thickness attribute is lost.

**Comment by casella** [comment]
@adeas31 there is something fishy in the way the thickness attribute is handled. If I change it in Parent using the GUI, e.g. setting it to 12, I see a thicker line in Parent's icon but not in Child. However, if I change the thickness attribute manually by editing the annotation, the GUI is not responsive to that.

This is also demonstrated by the following MWE:
```modelica
model TestThickness
equation

annotation(
    Icon(graphics = {Line(origin = {0, 10}, points = {{-100, 0}, {100, 0}, {100, 0}}, thickness = 5)}));
end TestThickness;
```
If you load it from file, the icon shows a line with the default thickness of 0.25, and so does the Line Properties dialog if I try to edit it.

**Comment by casella** [comment]
@adeas31 sorry to bother you, I think it would be nice to cherry pick this into 1.22.1. Thanks!

**Comment by adeas31** [comment]
See #11583. Is already ported together with some other fixes. I just forgot to merge the PR :).
