### ISSUE TITLE
QtXmlPatterns is deprecated

### ISSUE THREAD

**Issue by jschueller** [OpenModelica/OpenModelica#11558]
QtXmlPatterns module is deprecated and no longer available in qt 6.x
Luckily its usage is confined to OMEdit/OMEditLIB/Util/Utilities.cpp:

```
void Utilities::parseCompositeModelText(MessageHandler *pMessageHandler, QString contents)
{
  QFile schemaFile(QString(":/Resources/XMLSchema/tlmModelDescription.xsd"));
  schemaFile.open(QIODevice::ReadOnly);
  const QString schemaText(QString::fromUtf8(schemaFile.readAll()));
  schemaFile.close();
  const QByteArray schemaData = schemaText.toUtf8();
 
  QXmlSchema schema;
  schema.setMessageHandler(pMessageHandler);
  schema.load(schemaData);
  if (!schema.isValid()) {
    pMessageHandler->setFailed(true);
  } else {
    QXmlSchemaValidator validator(schema);
    if (!validator.validate(contents.toUtf8())) {
      pMessageHandler->setFailed(true);
    }
  }
}
```

it would need to be replaced with another xml library that supports DTD validation
could we use expat (already a dependency of FMILib) ? it would have to be compiled with DTD support enabled though

**Comment by adeas31** [comment]
> Could we use expat (already a dependency of FMILib) ? it would have to be compiled with DTD support enabled though

I am not sure. Maybe there is some Qt alternative for it.

**Comment by perost** [comment]
We are in the process of getting rid of FMILib, so it's probably best to ignore its dependencies in this case.

OMSimulator seems to be using both libxml2, PugiXml, and xerces. Not sure why it needs that many XML libraries, but maybe one of those works? Though I'm not sure if OMEdit can actually use OMSimulators third-party libraries, so maybe it doesn't really matter which ones we already use if we need to add one anyway.
