### ISSUE TITLE
OMEdit 1.23.0~dev-141-g9bf037a fails to simulate on Linux

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#11575]
### Description

When trying to simulate even the simplest model, the latest (successfully compiled) nightly fails to simulate.

### Steps to Reproduce

As an example open `Modelica.Blocks.Examples.PID_Controller` and press simulate.

I get the message: 
```
Compilation process finished successfully.
-fmuRuntimeDepends=none
execvp: No such file or directory
```
instead. And no simulation result is generated.

### Expected Behavior

Simulation should succeed.

### Version and OS

 - OpenModelica Version: 1.23.0~dev-141-g9bf037a
 - OS: Linux 64 bit., Ubuntu 22.04.3
 - Versions of used Modelica libraries if applicable: MSL 4.0.0

### Additional Context

Testing the same model directly from omc works.

**Comment by adeas31** [comment]
Have you tried removing your local settings? `Tools->Options->Reset` and then restart OMEdit. Makesure to backup the `omedit.ini`.

**Comment by dietmarw** [comment]
That was the reason. Reset help, thanks @adeas31
