### ISSUE TITLE
New instance-based API Issue - realExpression Icon sizing

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11576]
### Description

In the old API, we can enlarge a realExpression on both dimensions independently:

<img width="320" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/198b33d8-d279-4721-be26-b0df702e816d">

But in new API this is not possible, both dimensions are locked.

### Steps to Reproduce

See above

### Expected Behavior

The two dimensions of the icon shall be independent in a size change.

### Screenshots

see above

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS:  Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL

**Comment by adeas31** [comment]
Can you provide an example model? For me it works fine when I add a `realExpression` to a new model.

**Comment by BasilioPV** [comment]
For me, adding a realExpression to a new model don't work:

<img width="1090" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/5bca962c-b57d-4fff-919e-cfdb6af33f64">

With this configuration:

<img width="341" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/6f70ea64-0ae6-4f2d-952a-5ed38cac6e25">

**Comment by adeas31** [comment]
So you can't resize `realExpression`? Will it work for other components?
Meanwhile I will install 1.22 release and see if I can reproduce the issue.

**Comment by BasilioPV** [comment]
Not work for other components (that has "preserveAspectRatio=false" in annotation, of course).

**Comment by adeas31** [comment]
I downloaded the release 1.22 and tested it. This works as expected.

https://github.com/OpenModelica/OpenModelica/assets/4007231/e5f3d4ad-dce3-479c-bcd3-9b733681f51c

**Comment by BasilioPV** [comment]
Is not working at all! The icon remain preserving their aspect ratio!

with "preserveAspectRatio=false" annotation, the icon can be enlarged in only one dimension, as you see:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/e2e95832-aace-4015-9df8-10a199741739)

Please, check this feature and test again:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/d068083f-9792-4a3f-9209-a1a84e9e01fe)

**Comment by adeas31** [comment]
Did you change the `preserveAspectRatio` in `Modelica.Blocks.Sources.RealExpression` because that is the one that should have impact on resizing.

I can see that your `realExpression` component has some changes as it shows `cylinderTransient......`. This means you have some custom placement annotation on it. The extent values in this annotation can be the issue. Please share the MWE.

Also create a new model and drag and drop `Modelica.Blocks.Sources.RealExpression` and try to resize it.

**Comment by BasilioPV** [comment]
Your video is a clear example where show that is not possible to change the aspect ratio by resizing the component. 
This is the expected behaviour:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/946217c6-c288-4362-8928-1ed0553e313f)

**Comment by adeas31** [comment]
> This works well in previous versions of OMedit and also works if this is unchecked:

You mean when this is checked.

I see now what is the problem. I will fix asap.

**Comment by BasilioPV** [comment]
For a sake of clarity:
- Using the new-instance based graphical editing (UNCHECKED): Not work
- Using the old graphical editing (CHECKED): work Ok
