### ISSUE TITLE
Errors for unassigned booleans on model check 

### ISSUE THREAD

**Issue by FWuellhorst** [OpenModelica/OpenModelica#11582]
### Description

Checking models with unassigned Boolean parameters which are used to enable / disable equations lead to errors on model check.
As library developers, we want to check the model but at the same time not provide a default to make model users think about the assumption they make.

### Steps to Reproduce

```modelica
package UnassignedBoolean

model Component
  parameter Boolean use;
  Real y if use;
end Component;


model Connect

  parameter Boolean use;
  Modelica.Blocks.Sources.BooleanConstant conTru(k=true);
  Modelica.Blocks.Sources.BooleanConstant conFal(k=false);
  Modelica.Blocks.Interfaces.BooleanOutput y;
  
equation 

  if use then
    connect(conTru.y, y);
  else
    connect(conFal.y, y);
  end if;

end Connect;

end UnassignedBoolean;
```
This leads to the errors:
```
[1] 10:20:43 Übersetzung Fehler
[UnassignedBoolean: 5:3-5:16]: [The conditional expression use could not be evaluated.](omeditmessagesbrowser:///UnassignedBoolean?lineNumber=5)

[1] 10:20:46 Übersetzung Fehler
[UnassignedBoolean: 19:5-19:25]: [connect may not be used inside if-equations with non-parametric conditions (found connect(conTru.y, y)).](omeditmessagesbrowser:///UnassignedBoolean?lineNumber=19) 
```

### Expected Behavior

Assume either `true` or `false`. For non-boolean values, assume the nominal value. 

### Version and OS

 - OpenModelica Version: OpenModelica v1.22.0-dev-350-gc13196cc3e (64-bit)
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
@FWuellhorst the trick is to give a `start value` to those boolean parameter. This will be used to check the model and also to generate simulation code but will generate a warning, so that the user knows he probably forgot to set it. See [Section 8.6 of the MSL](https://specification.modelica.org/maint/3.6/equations.html#initialization-initial-equation-and-initial-algorithm):

> If a parameter has a value for the start-attribute, does not have fixed = false, and neither has a binding equation nor is part of a record having a binding equation, the value for the start-attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.
>
> [This is used in libraries to give rudimentary defaults so that users can quickly combine models and simulate without setting parameters; but still easily find the parameters that should be set properly.]

So

```modelica
model Component
  parameter Boolean use(fixed = false);
  Real y if use;
end Component;
```
passes checking, but if you simulate it you get
```
[3] 20:12:53 Translation Warning
[UnassignedBoolean: 4:3-4:39]: Parameter use has no value, and is fixed during initialization (fixed=true), 
using available start value (start=false) as default value.
```
Unfortunately
```modelica
model Connect
  parameter Boolean use(start = true);
  Modelica.Blocks.Sources.BooleanConstant conTru(k=true);
  Modelica.Blocks.Sources.BooleanConstant conFal(k=false);
  Modelica.Blocks.Interfaces.BooleanOutput y;
equation 
  if use then
    connect(conTru.y, y);
  else
    connect(conFal.y, y);
  end if;
end Connect;
```
generates an error:
```
[3] 20:15:27 Translation Error
[UnassignedBoolean: 19:5-19:25]: [connect may not be used inside if-equations with non-parametric conditions (found connect(conTru.y, y)).](omeditmessagesbrowser:///UnassignedBoolean?lineNumber=19)
```

This is an OMC bug that needs to be fixed. I'll open a separate ticket for that.

**Comment by casella** [comment]
See #11606.

**Comment by FWuellhorst** [comment]
Thanks for the quick response and hint to the MSL!

**Comment by casella** [comment]
> @FWuellhorst the trick is to give a `start value` to those boolean parameter. This will be used to check the model and also to generate simulation code but will generate a warning, so that the user knows he probably forgot to set it. See [Section 8.6 of the MLS](https://specification.modelica.org/maint/3.6/equations.html#initialization-initial-equation-and-initial-algorithm):
> 
> > If a parameter has a value for the start-attribute, does not have fixed = false, and neither has a binding equation nor is part of a record having a binding equation, the value for the start-attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.
> > [This is used in libraries to give rudimentary defaults so that users can quickly combine models and simulate without setting parameters; but still easily find the parameters that should be set properly.]
> 
> So
> 
> ```modelica
> model Component
>   parameter Boolean use(fixed = false);
>   Real y if use;
> end Component;
> ```
> 
> passes checking, but if you simulate it you get
> 
> ```
> [3] 20:12:53 Translation Warning
> [UnassignedBoolean: 4:3-4:39]: Parameter use has no value, and is fixed during initialization (fixed=true), 
> using available start value (start=false) as default value.
> ```
> 
> Unfortunately
> 
> ```modelica
> model Connect
>   parameter Boolean use(start = true);
>   Modelica.Blocks.Sources.BooleanConstant conTru(k=true);
>   Modelica.Blocks.Sources.BooleanConstant conFal(k=false);
>   Modelica.Blocks.Interfaces.BooleanOutput y;
> equation 
>   if use then
>     connect(conTru.y, y);
>   else
>     connect(conFal.y, y);
>   end if;
> end Connect;
> ```
> 
> generates an error:
> 
> ```
> [3] 20:15:27 Translation Error
> [UnassignedBoolean: 19:5-19:25]: [connect may not be used inside if-equations with non-parametric conditions (found connect(conTru.y, y)).](omeditmessagesbrowser:///UnassignedBoolean?lineNumber=19)
> ```
> 
> This is an OMC bug that needs to be fixed. I'll open a separate ticket for that.
