### ISSUE TITLE
OMEdit does not retain parameter name as component parameter (if the name is the same)

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11595]
### Description

Attached file provides two models:

[Issue.zip](https://github.com/OpenModelica/OpenModelica/files/13390356/Issue.zip)

"Example": That has two parameters "A" and "B"
"TestIssue": That uses the component "Example" and also has two parameters "A" and "B"

If I open "TestIssue" and edit the parameters as follows:
<img width="440" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/92a29af3-e14b-4b66-9c85-9f2663d9e296">
And click Ok, These parameters are missed!:
<img width="369" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/3170ef70-2f7e-4697-bac1-5b5c935b3527">
<img width="391" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/622ef6d1-b649-4053-845d-2c723f9c47c9">

If I repeat with other parameter names:
<img width="373" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/9eb8de8f-f3da-4bb3-a2a3-e2f9d25c6b21">
<img width="420" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/20f11247-a3da-4e9c-953b-fd870acda3d4">

Then is Ok:
<img width="510" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/0ca135b1-50fe-4caf-a679-2a5f15fa396f">

Summary: Set a parameter with the same name as component parameter is not possible, OMEdit GUI will not record these parameters.

### Steps to Reproduce

See above

### Expected Behavior

Parameters shall be recorded in any case.

### Screenshots

See above

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: N/A

### Additional Context
N/A

**Comment by adeas31** [comment]
@perost can it be because of `setElementModifierValue`?

@BasilioPV can you please post the `omeditcommunication.log` after setting `A=A` and `B=B`. Also let us know if you are using the instance-based API or not.

**Comment by BasilioPV** [comment]
I'm are using the instace-based API, but the behaviour is the same when disabled.

[omeditcommunication.log](https://github.com/OpenModelica/OpenModelica/files/13393244/omeditcommunication.log)

**Comment by BasilioPV** [comment]
On Nightly Build 1.23.0 (23/11/2023) this window is different:

<img width="251" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/c69babc9-feb0-4de2-9caa-1052d62d0cc5">

Why is repeating the parameter name? Why they not show the parameter unit "m"?
Thanks for the support!

**Comment by adeas31** [comment]
Because you are using MSL 3.2.3 in your model without a uses annotation. When OMC detects use of MSL without a uses annotation then by default it loads MSL 4.0.0. So either add a uses annotation to your model or update your model to use `Modelica.Units.SI.Length` instead of `Modelica.SIunits.Length`.

Btw you should have got messages about it in the Messages Browser.

**Comment by BasilioPV** [comment]
Thanks @adeas31 !
I have changed to Modelica.Units.SI.Length but the window now shows two selectors on both sides of the units. 

<img width="329" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/6f5518d6-6502-4883-a0d5-3fd15e54d730">

The two combo box seems to be the same, but the right one does not work. This is a bug?

**Comment by adeas31** [comment]
This is correct. The first one allows you to set `final` and `each`(only available if parameter is an array) modifiers on parameter and the second one is for parameter unit.

**Comment by BasilioPV** [comment]
Ok! Thanks @adeas31 !

**Comment by adeas31** [comment]
This issue was fixed in #11599 and I ported this to 1.22.1 #11655
