### ISSUE TITLE
Windows uninstall not removing start menu entry users guide

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#11597]
### Description

When uninstalling OpenModelica using `uninstall.exe` the start menu entry for the User's Guide isn't removed.

### Steps to Reproduce

Install OpenModelica on a Windows PC and uninstall OpenModelica.
Directory `C:\Users\USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\OpenModelica-1.23.0\Documentation` isn't removed.

### Expected Behavior

Remove start menu entry.

### Version and OS

 - OpenModelica Version: 1.23-dev
 - OS: Windows 11

**Comment by adeas31** [comment]
I will take a look at it asap.

If you want to play with it then the repo for installer is https://github.com/OpenModelica/OpenModelicaSetup

**Comment by AnHeuermann** [comment]
I guess it should be added somewhere in https://github.com/OpenModelica/OpenModelicaSetup/blob/master/OpenModelicaSetup.nsi#L332-L347.
But I don't know how to build the installer itself to test it.

**Comment by adeas31** [comment]
Add `Delete "$SMPROGRAMS\$R1\Documentation\OpenModelica - Users Guide.lnk"` after Line 342.

Just push it in and we can test with tomorrow nightly build :)

**Comment by AnHeuermann** [comment]
Why unit tests if we can test on everybody 😎

**Comment by AnHeuermann** [comment]
One quick uninstall, download, install and uninstall later I can confirm that this solves the issue.
But now I don't have the nightly installed any more, so let me run the installer again 🤣

**Comment by adeas31** [comment]
@adrpo I talked about this with @AnHeuermann in today's dev meeting. 
Maybe can we setup a Jenkins job here to just compile the installer to test if everything is fine. We already have the scripts that does everything. What do you think?
