### ISSUE TITLE
New instance-based graphical editing -> Introduce "input" parameters with predefined start values

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11608]
### Description

In the new instance-based graphical editing, the parametrization of Modelica.Mechanical.Multibody.Visualizers.FixedShape is not possible for "length", "width" and "height" parameters because they are defined as "input" with a start value:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/d7eda738-9545-4dbc-b051-84218baec932)

On component parameters window shows only the "start" values, not the value itself:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/a01fa931-392b-4064-8760-112067c37df3)

Producing the following code when changed:  (note that there are not set any value!, only start value)

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/0876b2d1-53ce-433f-82ce-2c44c04e6fa7)

### Expected Behavior

The expected behavior is the same as when new instance-based is disabled:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/34d828a9-8f3d-49db-9bef-c7e07d81ea23)

Which produces the correct output:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/fbf47bfc-5b7b-4dfb-8b37-fae4df94fb80)

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3

**Comment by casella** [comment]
@adeas31, as I understand from Section 4.7 of the MLS, top-level input variables of models are expected to be given a binding when the model is instantiated, unless they already have one, which is then used as default binding, but can be changed when instantiating.

Also, as I understand, top-level inputs of simulation models are expected to be provided from external files; lacking that, a constant input value equal to the start attribute is assumed. I'm not sure if this is actually written in the specification, maybe you or @perost can help me find where this is specified.

If that is correct, then there is no point in using the GUI to change the start attribute of input variables, which is possibly set in the model definition but is only meant as a fallback default, not meant to be changed. Hence, for input variables, we should always use the GUI to set a binding equation for the binding itself, regardless of start attributes, as suggested by @BasilioPV.

Do you agree?

**Comment by BasilioPV** [comment]
Any news on this issue?
