### ISSUE TITLE
Build breaks: error: use of undeclared identifier 'Absyn__BREAK'

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#11603]
### Description

```
/usr/ports/science/openmodelica/work/.build/OMCompiler/Parser/generated/ModelicaParser.c:11676:29: error: use of undeclared identifier 'Absyn__BREAK'
                             ast = Absyn__BREAK;
                                   ^
/usr/ports/science/openmodelica/work/.build/OMCompiler/Parser/generated/ModelicaParser.c:23495:48: error: call to undeclared function 'Absyn__SUBSCRIPTED_5fEXP'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
                                      retval.ast= Absyn__SUBSCRIPTED_5fEXP(el, subs);
                                                  ^
/usr/ports/science/openmodelica/work/.build/OMCompiler/Parser/generated/ModelicaParser.c:23495:46: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
                                      retval.ast= Absyn__SUBSCRIPTED_5fEXP(el, subs);
                                                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to Reproduce

Regular build with cmake + ninja.

### Version and OS

Current HEAD: 1.23.0-dev-150-g6185468a41

 - OpenModelica Version: Current HEAD: 1.23.0-dev-150-g6185468a41
 - OS: FreeBSD 13.2
 - clang-16

**Comment by archiespb** [comment]
Same issue was with 1.22 release version.
You have to refresh OMBootstrapping sources. See beginning of
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/boot/CMakeLists.txt

**Comment by bilderbuchi** [comment]
> Same issue was with 1.22 release version. You have to refresh OMBootstrapping sources. See beginning of https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/boot/CMakeLists.txt

phew, thanks for the tip, this "fix" is very much nonobvious... Could this be placed in the CMake setup somehow, so that either the `OMCompiler/Compiler/boot/bomc` directory is cleaned up/removed when cleaning the project, or it notices the need to refresh (based on some version number, maybe)?
