### ISSUE TITLE
Parameter units cannot be selected after formula input

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11612]
### Description

On new instance-based graphical editing, when introduce data into a parameter, the units cannot be changed after formula input:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/33c404b5-2b20-4d55-bc57-3397748b6efd)

When introduce "273.15 + 20", the units are blocked permanently:

![image](https://github.com/OpenModelica/OpenModelica/assets/93596576/170ef68b-2b8b-4b50-9224-72637dc25b1c)

### Steps to Reproduce

See above example

### Expected Behavior

Units shall be selectable always.

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 4.0.0

**Comment by BasilioPV** [comment]
Sorry, the behaviour is correct. Issue closed

**Comment by casella** [comment]
Only literal constants can be subject to unit conversions, not expressions.
