### ISSUE TITLE
Docker images fail to build

### ISSUE THREAD

**Issue by j-emils** [OpenModelica/OpenModelica#11611]
### Description
Docker images fail to build with error
"The repository 'https://build.openmodelica.org/omc/builds/linux/releases/1.20.0 jammy Release' does not have a Release file"

### Steps to reproduce
Using openmodelica/openmodelica:v1.20.0-ompython

It seems the files the docker is searching for doesn't exist on the server.

Singularity script

```
Bootstrap: docker
From: openmodelica/openmodelica:v1.20.0-ompython

%files
    requirements.txt

%post
    # Python installation
    apt -y update
```
### Output
sudo singularity build -F py38.sif ./containers/py38.def 
INFO:    Starting build...
Getting image source signatures
Copying blob 2ab09b027e7f skipped: already exists  
Copying blob 7f6c852308db skipped: already exists  
Copying blob b4d72ed5fd94 [--------------------------------------] 0.0b / 0.0b
Copying config c9edf9c4bb done  
Writing manifest to image destination
Storing signatures
2023/11/20 15:51:44  info unpack layer: sha256:2ab09b027e7f3a0c2e8bb1944ac46de38cebab7145f0bd6effebfe5492c818b6
2023/11/20 15:51:45  info unpack layer: sha256:7f6c852308db0bb3a42b1c3af900b12a3919ecb5cd556fdc31e7fb62849963cb
2023/11/20 15:51:49  info unpack layer: sha256:b4d72ed5fd94aa29bfa8367fbbc5c5f75d86e2687806062be47b4930a0557e5a
INFO:    Copying requirements.txt to /tmp/build-temp-2554884907/rootfs/requirements.txt
INFO:    Running post scriptlet
+ apt -y update
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                          
Ign:4 https://build.openmodelica.org/omc/builds/linux/releases/1.20.0 jammy InRelease
Err:5 https://build.openmodelica.org/omc/builds/linux/releases/1.20.0 jammy Release
  404  Not Found [IP: 127.0.0.1 3128]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1204 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB] 
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1010 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]          
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1404 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]              
Get:14 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1278 kB]      
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1473 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1430 kB]
Ign:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [78.3 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [32.6 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1430 kB]
Reading package lists... Done         
E: The repository 'https://build.openmodelica.org/omc/builds/linux/releases/1.20.0 jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
FATAL:   While performing build: while running engine: exit status 100

**Comment by j-emils** [comment]
Seems to be working again.

**Comment by casella** [comment]
@j-emils is there a specific reason you want to compile 1.20.0? Later versions are very much improved and supposed to be 100% compatibile - if you have some backwards compatibility issue, please open tickets about it.

**Comment by j-emils** [comment]
@casella, thanks for asking. No, I'm using it to test some python code and had therefore not updated. I have updated now. However, I think this error was due to some server migration.

**Comment by casella** [comment]
OK. I would always recommend to update to the last official release, just in case.
