### ISSUE TITLE
Some issues with text transformation

### ISSUE THREAD

**Issue by AustraleanPerson** [OpenModelica/OpenModelica#11625]
### Description

Rotationg or flipping left/right alignment text may produce wrong result.

### Steps to Reproduce

Open model 'TextTransform' from the attached 'TXT' package ([Txt.txt](https://github.com/OpenModelica/OpenModelica/files/13435401/Txt.txt)). The actual behaviour is:
![TextTransformActual](https://github.com/OpenModelica/OpenModelica/assets/147278612/028eb5c6-4049-4cc5-ad4f-0c6c4469b3aa)

### Expected Behavior

The expected behaviour is exposed within 'TextTransformExpected.png' image:
![TextTransformExpected](https://github.com/OpenModelica/OpenModelica/assets/147278612/db788fcc-c155-4317-bb25-df663670720f)

### Version and OS

 - OpenModelica Version: 1.23 latest
 - OS: Windows 10, 64 bit

### Additional Context

@MaksKBV has already corrected this behavior, I hope he will be able to provide a pull request soon.

**Comment by casella** [comment]
Great test case, and also great if @MaksKBV can provide a PR. Thanks!

**Comment by adeas31** [comment]
See also #8236 and #10650. I guess they all have the same issue.

**Comment by adeas31** [comment]
Fixed with #11691 and ported to maintenance/v1.22
