### ISSUE TITLE
Regression in KINSOL due to PR #11455

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11636]
Myself and @AndreaBartolini just realized that the `PowerGrids.Examples.Tutorial.IslandOperation.TwoGeneratorsOneReferenceGenerator` model in the development version of the library stopped working between 6 and 9 novembers, see the [regression report](https://libraries.openmodelica.org/branches/history/master/2023-11-06%2011:38:10..2023-11-09%2013:49:11.html).

The specific version of the library causing this issue can be found here: https://github.com/PowerGrids/PowerGrids/tree/issue11636

The [CI report](https://libraries.openmodelica.org/branches/master/PowerGrids_dev/files/PowerGrids_dev_PowerGrids.Examples.Tutorial.IslandOperation.TwoGeneratorsOneReferenceGenerator.err) on that model is currently broken, but if I run it with OMEdit I get:
```
KINSol finished with errorCode -2.
KINSOL: Memory issue ERROR -2 
nonlinear system 4623 fails: at t=0.56
```
Interestingly, nothing is happening at t = 0.56, the system is initialized in steady state and there are no changes to the system input until time = 1. 

There were many commits during those three days, but I guess the likely culprit is #11455, since it deals with KINSOL memory allocation. I guess there is still something going wrong there. @AnHeuermann can you please have a look?

**Comment by AnHeuermann** [comment]
I tested your model with commit f075b4ea323ed80a90ff2b52d519d047820e94fd (passing) and the following commit 1acc680662a71c5725db4d8d82858e69e7530bc8 (broken), so it is indeed #11455.

**Comment by AnHeuermann** [comment]
Found the issue: The original Jacobian is not allowed to be scaled in fScaling.
Also there was an error for nueric Jacobians which I fixed as well.

But it looks like the dense solvers are still broken.
I need to fix `./PowerGrids.Examples.Tutorial.IslandOperation.TwoGeneratorsOneReferenceGenerator -nls=kinsol -nlsLS=lapack`. Maybe it's broken for some time now.

**Comment by casella** [comment]
Thanks @AnHeuermann! Yes, also the dense solver should be fixed but it's less urgent, we typically only use kinsol for large systems where we need sparse solvers. The hybrid solver is more robust for small dense systems
