### ISSUE TITLE
Diagonal connection lines not matching textual representation

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11683]
### Description

In some circumstances connection lines on the diagram layer are not visualized as they  are written in the text layer. Instead they have some diagonal parts.

### Steps to Reproduce

1. Open the following modelica model:
```modelica
model test
  Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(transformation(origin = {-30, 10}, extent = {{10, -10}, {-10, 10}}, rotation = -0)));
  Modelica.Blocks.Sources.Constant const annotation(
    Placement(transformation(origin = {-30, -30}, extent = {{-10, -10}, {10, 10}})));
equation
  annotation(
    uses(Modelica(version = "4.0.0")));
end test;
```
2. Connect the output of the constant block to the input of the integrator block. The following connect equation is added to the above model:
```modelica
  connect(const.y, integrator.u) annotation(Line(points = {{-18, -30}, {-18, 10}}, color = {0, 0, 127}));
```
This line should be straight in vertical direction, since both x Values are the same. But the line is diagonal as shown in the first picture.
3.  Move the `integrator` instance to another position. In our case 20 points upwards and 20 points to the left. The textual representation of the complete model looks as follows. 
```modelica
model test
  Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(transformation(origin = {-50, 30}, extent = {{10, -10}, {-10, 10}})));
  Modelica.Blocks.Sources.Constant const annotation(
    Placement(transformation(origin = {-30, -30}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(const.y, integrator.u) annotation(Line(points = {{-18, -30}, {-18, 0}, {-38, 0}, {-38, 30}}, color = {0, 0, 127}));
  annotation(uses(Modelica(version = "4.0.0")));
end test;
```
There should again be no diagonal line but the first one in the diagram layer still is not straight (see second screenshot).  Its really hard to get rid of this diagonal line just by moving line points on the diagram layer.
4. If you instantiate the two classes directly in the position from step 3 and connect them, you get the following text layer:
```modelica
model test2
  Modelica.Blocks.Sources.Constant const annotation(
    Placement(transformation(origin = {-30, -30}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(transformation(origin = {-50, 30}, extent = {{10, -10}, {-10, 10}})));
equation
  connect(const.y, integrator.u) annotation(Line(points = {{-18, -30}, {-38, -30}, {-38, 30}}, color = {0, 0, 127}));
annotation(uses(Modelica(version = "4.0.0")));
end test2;
```
Here, no connection line is diagonal (see third screenshot). However, the connection line runs across the `const` block, which could probably also be improved but which is not part of this ticket.

### Expected Behavior

The connection visualization in the diagram layer matches the text layer. 

### Screenshots

My colleague @niklwors will add the screenshots as a comment. 

### Version and OS

 - OpenModelica Version: 1.22.0
 - OS: Windows 10, 64 bit
 - MSL 4.0

Thanks for looking into this
Aaron Buntrock

**Comment by niklwors** [comment]
picture 1:

![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/0a71aaf5-0d30-4010-a199-3cf9bd98d13a)

picture 2:
![image002](https://github.com/OpenModelica/OpenModelica/assets/12269776/534fb130-8092-4244-bf98-6578b9a60474)


picture 3:
![image003](https://github.com/OpenModelica/OpenModelica/assets/12269776/61e79c08-71ee-44ee-b490-9b041701cd2d)
