### ISSUE TITLE
Protected connectors should not be shown

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11682]
### Steps to Reproduce

Open the following package

```modelica
package P
  model M
    parameter Boolean useConnectors = false;
    Modelica.Blocks.Interfaces.RealInput u1 annotation(
      Placement(transformation(origin = {-100, 66}, extent = {{-20, -20}, {20, 20}}), iconTransformation(origin = {-100, 66}, extent = {{-20, -20}, {20, 20}})));
  equation

    protected
  Modelica.Blocks.Interfaces.RealInput u2 annotation(
      Placement(transformation(origin = {-98, -50}, extent = {{-20, -20}, {20, 20}}), iconTransformation(origin = {-98, -50}, extent = {{-20, -20}, {20, 20}})));
  annotation(
      Icon(graphics = {Rectangle(extent = {{-100, 100}, {100, -100}})}));
  end M;

  model S
  M m annotation(
      Placement(transformation(origin = {-6, 8}, extent = {{-10, -10}, {10, 10}})));
  equation

  end S;
  annotation(
    uses(Modelica(version = "4.0.0")));
end P;
```
When I am editing `M`, the protected connector `u2` is not shown in the icon, which is correct. However, it is still shown in the icon of the instance `m` in the diagram of `S`, which should not be the case.

### Expected Behavior

Protected connectors should never be shown, both when showing the icon layer of a component and when displaying its icon in diagrams.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
Ported to 1.22.1 #11689
