### ISSUE TITLE
Simulation setup option "Protected Variables" should not have an influence on encrypted libraries

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11718]
### Description

In #10206 it was fixed that protected variables (and variables from protected class instances) were always written into the result file. 
However, now there is the checkbox `Protected Variables` under `Simulation Setup->Output`. 
Selecting this checkbox should have no effect when working with an encrypted library (similar to the `Hidden Class` option from #11121) The protected variables of encrypted classes should never be written to the result file and should never be shown in the variables browser. 
This is extremely important for us at Bosch Rexroth for the external (non Rexroth colleagues) release of our BRSL library. Even though the protected variables' names are obfuscated, the class instance names are not, which causes unnecessary know-how issues.

### Expected Behavior

Protected variables of encrypted libraries are under no circumstances written to the result file.

### Version and OS

 - OpenModelica Version: 1.22.0 encrypted
 - OS: Windows 10, 64 bit

Thanks for looking into this.
Aaron Buntrock

**Comment by abuntrock** [comment]
Is there any update on this issue? I assumed that a fix similar to #11121 is possible for this issue here as well. Is this thought too simple?

**Comment by casella** [comment]
It also depends where the start values are taken from. If they are taken from the .xml file _only_, that would be a problem. If instead they are set by the C code and then possibly overridden by the xml file, then we could just remove them from the .xml file.

Maybe we could encrypt the xml file as well :)

**Comment by niklwors** [comment]
I think you just have to remove the option in the simulation setup dialog that protected variables are also written to the result file if you use the OMEdit for encrypted libraries. Otherwise you could bypass the encryption because you can see the names of protected components in the plot browser.

**Comment by casella** [comment]
@niklwors it's not only a matter of the GUI, one could use OMC from the command line for that.

@adeas31 can you please clarify the role of the _init.xml model? Based on that, we can decide what is the best strategy to handle this encryption issue.

**Comment by casella** [comment]
As I understand, the only remaining problem is with record fields, obfuscating them would be problematic. If I am not mistaken we agreed that this is OK anyway.

**Comment by adeas31** [comment]
Fixed in #12043 and ported #12058

**Comment by abuntrock** [comment]
@adeas31  I was finally able to test the fix with the encrypted version v1.24.0-dev-31-gedfa9cd10e (64-bit).
From my point of view nothing has changed compared to the behavior in the encrypted versionof v1.22.3 and this issue is still open. When I activate the output of protected variables 
 Can you reopen this ticket please.

**Comment by abuntrock** [comment]
I tested it with the encrypted BRSL3.0.0, which should be available to you via @niklwors. We will also try to build up an MWE if needed. I tested with the encrypted v1.24.0-dev-31-gedfa9cd10e (64-bit) version.
It seems to me that the issue is only fixed when I simulate a class that is part of an encrypted package and not when using classes from an encrypted package in a user defined class outside this library. Sorry for not specifying this precisely in my previous comment.

If I simulate `Rexroth_BRSL.Examples.Hydraulics.FlowDirections`  with the flag activated everything looks fine and no protected things are in the variable browser (with the BRSL3.0.0 there were some obfuscated things in the variable browser but those were our fault). 
When I duplicate this class, save it as a top level model and simulate it again with the flag activated I get many additional variables in the variable browser like `tank.n1205` (protected instance in tank class) or `orifice.n290` (protected variable in orifice class).

**Comment by adeas31** [comment]
> It seems to me that the issue is only fixed when I simulate a class that is part of an encrypted package and not when using classes from an encrypted package in a user defined class outside this library. Sorry for not specifying this precisely in my previous comment.

Yeah that is true. However, the variables listed are obfuscated.

**Comment by adeas31** [comment]
Of course. I have a fix for it in my working copy. Will push it in soon.

**Comment by adeas31** [comment]
I have started the new encryption build. Please test this once the build is available.

**Comment by abuntrock** [comment]
I tested it with the following encryption build: v1.24.0-dev-57-g6c4e231c89 (64-bit)
I do not know if I am doing something wrong or using the wrong build. But for me it seems that the behavior is now worse than before your last fix where I tested with version v1.24.0-dev-31-gedfa9cd10e (64-bit).
Now, the protected variables are present in the variable browser in both scenarios when I simulate with the flag `Protected Variables` activated. With the scenarios I mean
- Simulating a model from within an encrypted package (where there were no protected variables in the browser previously)
- Simulating a model using classes from an encrypted package (no difference to before, protected variables still in the variable browser)

**Comment by adeas31** [comment]
Can you please try with the example from https://github.com/OpenModelica/OpenModelica/issues/11718#issuecomment-2079050961?

**Comment by casella** [comment]
@perost, @adeas31 can you comment on that?

**Comment by adeas31** [comment]
There are 3 scenarios,

1. Protected primitives variables inside the encrypted model.
2. Protected variables of encrypted model used in non-encrypted model.
3. Non encrypted model used as protected inside the encrypted model.

We handle 1 and 2. I know how to fix 3.
@perost can check why the protected variables of case 3 are not obfuscated.

**Comment by perost** [comment]
Previously we only checked if a component is declared in an encrypted file, so e.g. `const.y` would not be considered to be encrypted since `y` is declared in the unencrypted MSL. #12369 changes this to also take a component's parents into account, so `const.y` should now be seen as encrypted since `const` is encrypted.

**Comment by abuntrock** [comment]
I tested this with the new encryption  build:

It seems that the last fix regarding "Instance of non encrypted class inside encrypted class" #12372  was not combined with the fix for "Hide protected variables that belongs to an encrypted class" #12351.

Take the following package as an example.
```modelica
package ResultOutputWithMSL

  model TopLevel
    Real a = 1;
  protected 
    Real b = 2;
    ResultOutputWithMSL.SubLevel subLevel annotation (
      Placement(transformation(origin = {-30, 10}, extent = {{-10, -10}, {10, 10}})));
    Modelica.Blocks.Sources.Constant const(k = 1)  annotation (
      Placement(transformation(origin = {30, 10}, extent = {{-10, -10}, {10, 10}})));
  end TopLevel;

  model SubLevel
  Real c = 2;
  end SubLevel;

annotation (uses(Modelica(version = "4.0.0")), Protection(access = Access.nonPackageDuplicate));
end ResultOutputWithMSL;
```
Encrypt this package and simulate `ResultOutputWithMSL.TopLevel` with the flag `ProtectedVariables` activated. There is only the parameter `a` in the variable browser thanks to #12372, which we expected.

However, if you simulate the following top level class with an instance of `ResultOutputWithMSL.TopLevel` and with the flag activated `toplevel.n4` appears in the variable browser. The MSl instance name is now obfuscated thanks to #12372, but now there is the difference between the two scenarios (simulating from within the encrypted package and simulating a model with an instance from an encrypted) again, which was originally fixed in #12351.
```modelica
model Test
  ResultOutputWithMSL.TopLevel topLevel annotation(
    Placement(transformation(origin = {-10, 10}, extent = {{-10, -10}, {10, 10}})));
end Test;
```

**Comment by casella** [comment]
@perost I guess this is up to you :smiley

**Comment by abuntrock** [comment]
The obfuscation also looks correct from my point of view.

**Comment by adeas31** [comment]
#12372 and #12351 are indeed combined.

The problem here is that the variable in question i.e., `topLevel.const.y` doesn't belong to the encrypted class and the class that is being simulated is also not encrypted. My fixes doesn't cover that specific scenario. I talked with @adrpo a bit and we need to change some stuff in order to fix this properly.

**Comment by abuntrock** [comment]
Thanks for the explanation.
So you would need to check if at least one of the instance is protected inside an encrypted class?

**Comment by abuntrock** [comment]
I was on vacation and only now able to check this. 
With the encryption build: v1.24.0-dev-82-gd9f2966f3e it looks perfect with the above minimum example as well as with our BRSL. Thanks a lot. Was it possible to port this to 1.23.0 or will it be included in an upcoming release?

**Comment by abuntrock** [comment]
Thanks a lot
