### ISSUE TITLE
DisplayUnit modifiers should automatically get an 'each' prefix when applied to arrays

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11715]
### Steps to Reproduce

- Load this package in OMEdit:
```modelica
package TestEachDisplayUnit
  model M
    parameter Modelica.Units.SI.Density d[3];
    annotation(
      Icon(graphics = {Rectangle(origin = {-1, 0}, extent = {{-99, 100}, {101, -100}}), Text(origin = {4, 11}, extent = {{-66, 53}, {66, -53}}, textString = "M")}));
  end M;

  model S
  M m(d = {1000, 900, 950})  annotation(
      Placement(visible = true, transformation(origin = {0, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S;
  annotation(uses(Modelica(version="4.0.0")));
end TestEachDisplayUnit;
```
- Go to the diagram view of `S` and double-click on `m`. 
- Change the unit to "kg/m3"
- Click OK

The following error is reported:
```
[11] 12:14:16 Translation Error
[TestEachDisplayUnit: 3:5-3:45]: [Non-array modification '"kg/m3"' for array component 'displayUnit', possibly due to missing 'each'.](omeditmessagesbrowser:///TestEachDisplayUnit?lineNumber=3)
```
Of course this can be fixed by also setting 'each' to the `displayUnit` modifier. However, this is not really intuitive. Moreover, the only way to change the unit with the GUI is with the drop-down menu, so you can only set one unit for the whole array. Hence, when editing `displayUnits` for an array with the GUI, there is no point in not adding 'each' automatically.

### Expected Behavior

When changing `displayUnit` for arrays through the GUI, add the 'each' prefix to the 'displayUnit' modifier automatically.

### Related issues

See also #5395.

**Comment by casella** [comment]
@adeas31 I would put this in 1.22.2 if we can manage: it is quite annoying, and probably a quick fix. Thanks!

**Comment by adeas31** [comment]
PR #11999 fixes this. Now the `each` menu item is not shown for displayUnit. It doesn't make sense to show it when we are automatically adding it.

**Comment by casella** [comment]
Very good! Should we test it on master before cherry-picking it to maintenance?
