### ISSUE TITLE
Don't include pthread.h for Visual Studio

### ISSUE THREAD

**Issue by t-sommer** [OpenModelica/OpenModelica#11731]
### Description

In order to compile source code FMUs exported with OpenModelica v1.22.1 using Visual Studio the user has to manually define `OMC_NO_THREADS` which is very inconvenient.

### Steps to Reproduce

- export an FMU with OpenModelica v1.22.1
- run `fmpy compile Feedthrough.fmu`

```
Compiling platform binary...
[...]
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.3.5
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'
Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

Feedthrough.c
C:\Users\tsr2\AppData\Local\Temp\tmpanktbsvl\sources\gc/omc_gc.h(48): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
Feedthrough_functions.c
C:\Users\tsr2\AppData\Local\Temp\tmpanktbsvl\sources\meta\../gc/omc_gc.h(48): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
Feedthrough_records.c
[...]
Exception: Failed to compile shared library
```

### Expected Behavior

The availabilty of `pthread.h` is detected automatically e.g. by checking for `_POSIX_VERSION` (like in
https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaInternal.c#L214).

**Comment by mahge** [comment]
This is fixed with https://github.com/OpenModelica/OpenModelica/pull/11471. The logic handling PThreads availability has been flipped so there is no need to provid the define if you don't have PThreads. 

Unfortunately, it seems the change did not make it to the 1.22.0 main release. You can wait for the next release or you can also build OpenModelica from the master branch if that is an option for you. 

@casella for reference.

**Comment by casella** [comment]
Thanks @mahge! If you can port this to the maintenance/v1.22 branch, we can release it in 1.22.2 patch release early January 2024. Otherwise, it's already available in the nightly builds and will be included in 1.23.0 around March 2024.

**Comment by casella** [comment]
@adrpo maybe you can take care of that.

**Comment by casella** [comment]
Added to maintenance/v1.22 by #11761
