### ISSUE TITLE
Use the correct type of progress bar when the simulation fails

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11749]
### Description

In #11128, we improved the semantics of the progress bar, by showing the amount of time that was effectively processed in case of simulation failure, instead of 100%.

However, in case of failure the progress bar with a left-to-right moving clear wave is still shown once the simulation has stopped. This is both annoying (you have stuff moving onscreen forever, which is a no-no in terms of inappropriately drawing your attention) and misleading, because it gives the false impression that the simulation is still running, whereas it isn't.

### Expected Behavior

When a simulation fails, the final aspect of the status bar should be the same as in the case of success, i.e. still solid colour, only less than 100%.

**Comment by adeas31** [comment]
This is how the OS windows style renders it. I am afraid there is nothing I can do to improve it. The only other option is to draw progressbar with stylesheets but then they will not look like a native OS control.

**Comment by casella** [comment]
Do you mean a bar which is less than 100% is inherently showing waves?

**Comment by adeas31** [comment]
Yes, because the progressbar expects to increase. There is no flag in [QProgressBar](https://doc.qt.io/qt-6/qprogressbar.html) to mark it half done.

**Comment by casella** [comment]
I see. The problem here is that it is ambiguous, as you don't understand if the simulation is only getting very slow at some point, or has aborted. But you can also get this information from the status of the Cancel Simulation button, as well as from the message to the left of the bar "Simulation of XXX failed" vs. "Running simulation of XXX".

Never mind.
