### ISSUE TITLE
Copy-Paste graphical components of an icon

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#11745]
### Description

Icon graphical components are drawn in order, the last component is drawn over the other.
But when you perform a copy-paste from one component icon to another icon of a **different component**, theay are not sorted in the same way as the original, making an appearance totallly different.

### Steps to Reproduce

Copy several figures (that are to be draw one on top of another) from one component icon, and paste in a different component icon.

 
<img width="592" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/21728580-1ef7-4b26-a7f9-3fa2e24797d4">

<img width="825" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/a8b9fa9e-40d6-42e0-b59a-f63de6d9cd4a">

### Expected Behavior

The figure must be created using the components on the same sorting.

### Version and OS

 - OpenModelica Version: 1.21
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
Uh-oh. @adeas31 will look into that when he gets back from his holidays.

**Comment by BasilioPV** [comment]
Any news on this?

**Comment by adeas31** [comment]
I haven't got enough time to look into this.

**Comment by adeas31** [comment]
I didn't check it in detail but just saw that you are using version 1.21. A similar issue #9515 was fixed and ported to 1.22.1. Can you please try that and see if you can still reproduce it?

**Comment by BasilioPV** [comment]
Hi @adeas31, On the last nightly build that I have intalled it works ok. Issue Closed. thanks!
