### ISSUE TITLE
Redundant control for final parameter

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11773]
### Steps to Reproduce
- load and open [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/13785547/Test.mo.txt)
- double click on smee.
The following dialog appears:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/57e9c140-6035-4a67-99c2-af8162c0db9c)

the icons to set final parameter appear twice in many rows

### Expected Behavior
the icon should appear just once per row

### Version and OS
OM 1.23.0-dev-192

**Comment by BasilioPV** [comment]
As far as I know, the second is to set "final unit", in addition to "final parameter".

**Comment by ceraolo** [comment]
ok
