### ISSUE TITLE
[OMEdit] DisplayUnit and value do not match in parameters window

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OpenModelica#11782]
### Description

Value of parameters are not shown correctly when using DisplayUnit with factor.

### Steps to Reproduce

Create a simple model and put a block with some value with unit, e.g. Modelica.Electrical.Analog.Basic.Resistor, on it.
Open the parameters window of that block.
Change resistance value to 1000 (Ohm).
Select DisplayUnit "kOhm" -> value changes correctly to "1".
Close window with "OK" and open it again.

The value will show up with "1000" and DisplayUnit with "kOhm".
The internal value seems to be correct, because you can change the unit to "MOhm" and the value will change correctly to "0.001".
If you enter a new value instead, the displayed "kOhm" will also be respected.

### Expected Behavior

Correct value should be displayed.

### Version and OS
 - OpenModelica Version: v1.22.1
 - OS: any OS

**Comment by casella** [comment]
Thanks @hkiel, I could reproduce this. @adeas31 will look into it ASAP and we'll try to put the fix in 1.22.2 as well.

**Comment by hkiel** [comment]
When is the 1.22.2 release planned?

**Comment by casella** [comment]
End of January, see the [milestones](https://github.com/OpenModelica/OpenModelica/milestones) page. The idea is to fix some high-priority bugs in OMEdit. 1.23.0 will probably be released in March.

**Comment by adeas31** [comment]
Ported to 1.22 with #11826
