### ISSUE TITLE
Error in Electrical/Digital Libraries

### ISSUE THREAD

**Issue by choks2014** [OpenModelica/OpenModelica#11781]
### Description
In version 1.22, Input/Output ports of the Electrical Digital libraries disappear while the analog ports are OK.
In version 1.21, there was no problems like that.

### Screenshots
The following is one of the error messages:

**_[7] 16:41:14 Scripting Error
Unable to find component CLK.y while parsing connect(CLK.y, MUX.a0) in Modelica.Electrical.Digital.Examples.Multiplexer._**

### Version and OS

 - OpenModelica Version: OpenModelica-v1.22.1-64bit
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries : Version : 4.0.0

**Comment by casella** [comment]
@perost, @adeas31, this should be preferably fixed in 1.22.2

**Comment by adeas31** [comment]
Seems like @perost forgot to port some commit(s). The maintenance branch dumps `y` in `Modelica.Electrical.Digital.Sources.DigitalClock` as `enumeration` instead of `connector`.

**Comment by perost** [comment]
Should be fixed with #11814.

**Comment by adeas31** [comment]
Tested the maintenance branch. Works fine now.
