### ISSUE TITLE
Enhancenement: Possibility to undock Plot windows

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11785]
### Description

It is possible to undock GUI parts such as the "Libraries Browser", the "Variables Browser" and the "Messages Browser" and subsequently move them around different screens. This however is not possible for plots. 
When building up large hydraulic system models our BRSL users often look at a large number of different variables. This would be easier of more plots could be investigated parallel by each other by placing those plots on more than one screen.

### Expected Behavior

Plots can be undocked and moved across all available screens.

### Version and OS

 - OpenModelica Version: 1.22.1
 - OS: Windows 10, 64 bit

Thanks for looking into this.
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
It is not possible to undock plot windows. This require substantial amount of design changes.

**Comment by adeas31** [comment]
> Thanks for the information. So this issue will be closed as "not planned" then right?

Yes.

**Comment by abuntrock** [comment]
I will close this as "Not planned" then

**Comment by abuntrock** [comment]
I will close this as "Not planned" then
