### ISSUE TITLE
OMEdit: parameter, negative values, conversion / unit handling error 

### ISSUE THREAD

**Issue by marthoch** [OpenModelica/OpenModelica#11795]
### Description
Negative values of parameters of type SI.Angle are not correctly converted and the unit is not correctly handled.

### Steps to reproduce
1.  Inset the following model in a model
2.  Open the parameter window, set the parameter angle to `-5 deg`, and close the parameter window with OK.
3. Open the parameter window and observe, the parameter angle is `-286.4788975654116 rad` with is not -5 deg. 
4.  In the model it is saved as `testtest testtest1(angle(displayUnit = "rad") = -5)`. Correct would be `testtest testtest2(angle(displayUnit = "deg") = -0.08726646259971647) `.

| input | result|
|-------:|-------:|
| -1| -57.29577951308232|
| -3 |  -171.887338539247 |
| -5 | -286.4788975654116|

The factor is 57.29  wich is 360/(2*pi). 

So the value is not converted from deg to rad and the displayUnit is set wrong.

Example: 
```
model testtest
    import Modelica.Units.SI;
    parameter SI.Angle angle=0 "angle";
equation
end testtest;
```

### workaround
1. Enter a positive value and save the model.
2. Then change the value to a negative value.

### Version and OS
Windows 11  
OMEdit - OpenModelica Connection Editor  
Connected to OpenModelica v1.22.1 (64-bit)  
Connected to OMSimulator v2.1.1.post247-g614c663-mingw-notlm-debug

**Comment by casella** [comment]
Most likely the same issue as #11782. @adeas31, this should be fixed with high priority.

**Comment by adeas31** [comment]
There were 2 problems. One was mentioned by @casella and was fixed in #11782. The other was that we do not allow entering negative values. So once you try to enter the negative value the unit changes from deg to rad. So OMEdit thinks that you entered -5 rad instead of deg. I fixed now in #11837 to allow negative values.

**Comment by adeas31** [comment]
Ported to 1.22 with #11838

**Comment by casella** [comment]
Thanks @adeas31!

**Comment by casella** [comment]
And, thanks to @marthoch for reporting 😃
