### ISSUE TITLE
No synchronization from text layer to simulation setup dialog

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#11794]
### Description

When changing the experiment annotation (or simulation/translation flags) inside the text layer, the changes are not mapped to the simulation setup dialog and are not respected during simulation.

### Steps to Reproduce

1. Create the following modelica model
```modelica
model SetupSynchronization

parameter Real testParam = 5.5;
Real result = testParam*time;

end SetupSynchronization;
```
2. Open the simulation setup dialog and select "Save experiment annotation inside model". The model text layer now looks as follows: 
```modelica
model SetupSynchronization

parameter Real testParam = 5.5;

Real result = testParam*time;
annotation(experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-6, Interval = 0.002));

end SetupSynchronization;
```
3. In the text layer change the `StopTime` to 2 and save the model. Open the simulation setup dialog again. There the `StopTime` is still 1 as shown in the attached screenshot. 
4. Simulate the model. The results are only available until a `StopTime` of 1, In the textual layer `StopTime` is also changed back to 1.

### Expected Behavior

The experiment annotation and flags shown in the text layer are mapped to the simulation setup dialog.

### Screenshots

My collegue @niklwors will add a screenshot as a comment.

### Version and OS

 - OpenModelica Version: 1.22.1
 - OS: Windows 10, 64 bit

Thanks for considering this.
Aaron Buntrock - Bosch Rexroth

**Comment by niklwors** [comment]
picture:
![image001](https://github.com/OpenModelica/OpenModelica/assets/12269776/4dab4f9f-d022-471b-b500-1edec13473ab)

**Comment by casella** [comment]
Yes, I also find this behaviour a bit annoying. As I understand, OMEdit reads the annotations when simulating the model for the first time, using them to modify the internal parameter cache, which is then visualized with the Simulation Setup dialog. You can then change them further with the dialog, and possibly save them back, but not re-load them from the file - in fact, I understand you need to exit OMEdit and re-run it to actually read the annotations again.

I guess the best option is to add a button to Simulation Setup | General to reset the parameters to default and then re-read them from the annotations.

@adeas31 what do you think?

**Comment by bilderbuchi** [comment]
> I guess the best option is to add a button to Simulation Setup | General to reset the parameters to default and then re-read them from the annotations.

Or do that reload from file automatically every time you open the Simulation Setup dialog?

**Comment by casella** [comment]
> > I guess the best option is to add a button to Simulation Setup | General to reset the parameters to default and then re-read them from the annotations.
> 
> Or do that reload from file automatically every time you open the Simulation Setup dialog, or switch tabs therein?

No! If you need set additional options or flags, you don't want to add them every time you open the dialog. That was the behaviour in the past and it was really annoying. They should be retained during the session. You should just be able to reset them to the default ones, i.e. the general defaults set in Tools | Options | Simulation + the annotations.

**Comment by casella** [comment]
> Or do that reload from file automatically every time you open the Simulation Setup dialog, or switch tabs therein?

No, we had that previously and it was painful. Suppose you are trying to experiment with different settings, which are found in three different tabs. Setting them times and again every time you simulate is annoying, and also error-prone, because you may forgot some.

**Comment by casella** [comment]
> The master should be the model. If this is changed it must be considered in the next simulation run and the settings dialog, no matter what. No extra clicking to enforce it. This should be the same behavior as for any other Modelica code.

@olivleno, what we could implement is that if the experiment annotation is changed in the source code, OMEdit will detect it an reload it automatically, discarding all previously flags set with the Simulation Setup dialog. Would that suit you?

**Comment by olivleno** [comment]
> @olivleno, what we could implement is that if the experiment annotation is changed in the source code, OMEdit will detect it an reload it automatically, discarding all previously flags set with the Simulation Setup dialog. Would that suit you?

Yes, for me this would be more intuitive than ignoring the textual changes.
Of course this could have undesired side effects on other simulation flags, but if you don't save the simulations flags to the annotations then that's what you get.

**Comment by casella** [comment]
@adeas31 please implement this at your earliest convenience.

**Comment by abuntrock** [comment]
This works perfectly with today's nightly. Thanks a lot.
