### ISSUE TITLE
Dynamic select values are not updated automatically after a simulation

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11811]
### Description
Dynamic select values on diagram are not updated

### Steps to Reproduce
1. download https://github.com/PowerGrids/PowerGrids/tree/develop
2. run Examples.ENTSOE.PowerFlow
3.  the voltage at the bus NTLV is correctly displayed as being 1.000
4. in NTLV change UNom from 21 to 15 kV and simulate => the NTLV voltage is still 1.000
5. Close and reopen the diagram in Plotting perspective => the voltage value is updated (now it is correctly 1.400)

### Expected Behavior
the values should be updated without the need of closing and reopening the diagram

### Version and OS

1.22.0-beta6 I could not replicate in 1.22.0 because this version is not able to simulate the model indicated in step 2.

**Comment by casella** [comment]
@ceraolo I tried with the latest available nighty build v1.23.0-dev-214-gb890045362 (64-bit). This is what I got after changing UNom to 15 kV and hitting the Simulate button:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/cf3377a2-1835-4663-9b91-4556317d79d8)
This seems to me the correct result, we improved DynamicSelect in 1.21.0 and 1.22.0, you should try that.

**Comment by ceraolo** [comment]
Are you sure you followed all the steps above? You should first run with the default 21 kV, see the resul on the diagram.

The latest I build can check now is the latest available on Linux, i.e. 1.23.0-dev-206.
With this build I have the same problem as in the ticket's description.

**Comment by ceraolo** [comment]
I downloaded it today!

**Comment by casella** [comment]
Strange. Unfortunately I don't have access to the Linux nightly right now so I cannot test that. Unfortunately the Windows nightly job is broken because Windows Defender thinks stuff compiled by the old versions of gcc and clang we use are trojan or something, so I cannot test the latest version on master with Windows. I'll check ASAP.

On the other hand, @adeas31 has been off for some time, so nothing should have changed in the last couple of weeks on OMEdit. Maybe the caching is handled differently on Linux?

**Comment by casella** [comment]
OK, now I understand the issue: when I want to see the diagram with the dynamic select information, I always click on the Diagram Window button to display the diagram
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/f91f1b0a-ddc9-44dd-a7f7-349e3d241d26)
which triggers a refresh. No need to close and reopen the window 😃 

If you just click on the diagram tab after re-simulating, you still see the old values, which is indeed bad.

@adeas31 please trigger the update of the diagram window in the plotting perspective automatically every time a simulation ends.

**Comment by ceraolo** [comment]
There is something fishy about updating through click on the Diagram Window button.
After a few times you do this, OM crashes.
It has crashed rather regularily every few minuts to me, when I used this technique repeatedly.

**Comment by casella** [comment]
@adeas31 if you can reproduce the crash and fix it, that would be great.

**Comment by casella** [comment]
@ceraolo changed UNom back and forth from 21 to 15 kV, simulated and updated the diagram, but I couldn't get OMEdit to crash. Anyway, the solution to this issue is to update the diagram automatically when the simulation is finished.

**Comment by ceraolo** [comment]
I've been working on PF last  WE for several hours. I used 1.22.0 because 1.23.0-214 had issue #11846.
OM 1.22.0 crashed at intervals I would say between 2 min and 30 min.
Unfortunately, I could not find a repetitive procedure to produce crash voluntarily.

Since usually OM is much more stable, were in programmer's feet I would check the code used to update dynamic select values, to try to envisage whether something is potentially dangerous there.

**Comment by casella** [comment]
When it crashed, did you get a chance of sending a crash report at least once? If so, please do it, it contains useful information, in particular the stack trace immediately before the crash.

**Comment by ceraolo** [comment]
Unfortunately not

**Comment by adeas31** [comment]
The reported issue is fixed. I will port it to 1.22.2.
@ceraolo report if you find any useful information about the crash.

**Comment by casella** [comment]
@adeas31 I'm reopening this until the port is done, so we track exactly what the current status is.

**Comment by ceraolo** [comment]
Good!
You are enhancing the MMI very fast.
I'm also glad that you've just accepted #11887
