### ISSUE TITLE
Do not automatically open plot windows when resimulating

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11829]
### Description
When running any simulation OMEdit opens a plot window in plotting perspective.
This should not create any issue, in general.

But there are cases in which this opening is somewhat annoying i.e.,  when the results are shown directly on diagram by means of dynamic text.
This happens today with PowerGrids PowerFlow. PoweFlow studies often require resimulating several times. No plot is needed. 

_Other libraries may usefully show results on diagrams as well, for instance the final values. This could have interest if at the final time steady state is reached to have an overview of that steady-state._

If the user closes the plot window, it is automatically repoened at any resimulation.
If they don't, plot windows become selected and go on the foreground.

What I propose is simple:
**When resimulating no new plotting window should be automatically opened.**

I do not see any drawback of this for users that want to see line plots: if they want to see them, they will never close plots before resimulating.

Tested with OM 1.22.0-dev-341

**Comment by adeas31** [comment]
I also noticed this while working on #11811 and find this very annoying so I fixed it already with #11862.
Please test it with the latest nightly build.

**Comment by casella** [comment]
I'll keep it open until it's ported to maintenance/v1.22 as well.

**Comment by ceraolo** [comment]
> I also noticed this while working on #11811 and find this very annoying so I fixed it already with #11862. Please test it with the latest nightly build.

Thank you! I'll test it soon.

I appreciate a lot that you're considering (and fixing) my recent tickets so fast!

Please consider that, in addition to these very good fixes, something that will make much better my life with OM (especially when I use PowerFlow of PowerGrids) would be the solution of:
https://github.com/OpenModelica/OpenModelica/issues/9889#issuecomment-1899169544)
and:
https://github.com/OpenModelica/OpenModelica/issues/9889#issuecomment-1908049886

Thank you!

**Comment by adeas31** [comment]
Ported to maintenance/v1.22
