### ISSUE TITLE
The NB creates duplicate bindings when handling records

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11852]
Recent tests on `PowerGrids.Electrical.Test.OneBusOneLoad` after merging PR #11827, as reported [here](https://github.com/OpenModelica/OpenModelica/issues/11556#issuecomment-1903951935), show that sometimes binding equations for records are created twice, once for its scalar components and another time for the record as a whole.

Although they are equivalent, and later get removed, they should not be created twice in the first place.

**Comment by kabdelhak** [comment]
Fixed by #11871

**Comment by casella** [comment]
The last newInst-newBackend is still waiting in the queue, so it should get this one as well.
