### ISSUE TITLE
FMU's binary cannot be loaded because libwinpthread-1.dll is not contained

### ISSUE THREAD

**Issue by t-sommer** [OpenModelica/OpenModelica#11856]
### Description

FMUs generated with OpenModelica Compiler OpenModelica v1.23.0-dev-273-gc1eb94bbfc (64-bit) depend on `libwinpthread-1.dll` that is not contained in `binaries/win64`.

### Steps to Reproduce

Export an FMU and load it on a system where `libwinpthread-1.dll` is not on the path.

### Expected Behavior

All dependencies are contained in the FMU.

### Version and OS

OpenModelica Compiler OpenModelica v1.23.0-dev-273-gc1eb94bbfc (64-bit) on Windows

see also https://github.com/CATIA-Systems/FMPy/issues/638#issuecomment-1904569512

**Comment by casella** [comment]
Ouch, phtreads pops up again. @arun3688, @mahge, hadn't we gotten rid of it?

@t-sommer thanks for reporting!

**Comment by BasilioPV** [comment]
Same issue of #12065, already solved. Ready to close?
