### ISSUE TITLE
FMUs generated by OMC do not take into account StartTime and Interval experiment annotations

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11855]
In #11802, a problem was reported that was ultimately traceable to the FMU solving the initial equations at time = 0 instead of doing it at time = StartTime.

I thought this was a FMPy issue and opened a [ticket](https://github.com/CATIA-Systems/FMPy/issues/638) on the CATIA issue tracker, but it seems that the problem does not occur if the FMU is generated by Dymola. So, it is probably an OMC FMU export issue.

@arun3688 can you please check if the generated FMU code sets time = StartTime before solving the initial equations? If not, it should do so.

Thanks!

**Comment by casella** [comment]
Similar problem in #11757, where in that case the Interval experiment annotation is not set in the model_description.xml file, causing a too long time step to be taken, which fails.

@arun3688 please make sure that the `DefaultExperiment` of fmiModelDescription has it four attributes set as follows:
- startTime should be equal to experiment(StartTime) if defined, otherwise set to zero.
- stopTime should be equal to experiment(StopTime) if defined, otherwise set to one.
- tolerance should be equal to experiment(Tolerance) if defined, otherwise set to 1e-6
- stepSize should be equal to experiment(Interval) if defined, otherwise set to (stopTime-startTime)/500

This is what should be done when generating FMUs from scripts. If FMUs are generated from OMEdit, these settings may have been changed without being saved in the annotations, but they should be taken into account anyway - moreover, the interval length may be implicitly set by giving the number of intervals - we need to make sure that eventually the right number gets into the stepSize filed of the model_description.xml file.

@adeas31 how can we do this properly?


 all four options of the [experiment annotation](https://specification.modelica.org/maint/3.6/annotations.html#annotations-for-simulations), namely StartTime, StopTime, Inteval, and Tolerance are copied into the model_description.xml file, if they are set in the original Modelica model.

**Comment by arun3688** [comment]
> @arun3688 please make sure that the `DefaultExperiment` of fmiModelDescription has it four attributes set as follows:
> 
> * startTime should be equal to experiment(StartTime) if defined, otherwise set to zero.
> * stopTime should be equal to experiment(StopTime) if defined, otherwise set to one.
> * tolerance should be equal to experiment(Tolerance) if defined, otherwise set to 1e-6
> * stepSize should be equal to experiment(Interval) if defined, otherwise set to (stopTime-startTime)/500

I looked into the code and it is exactly implemented the same way as you proposed, except the tolerance default value is set to `1e-4` , below is the list of default settings `OMSimulator` uses if `DefaultExperiment` is not provided in `modeldescription.xml`

```
void oms::Flags::setDefaults()
{
  addParametersToCSV = false;
  algLoopSolver = oms_alg_solver_kinsol;
  defaultModeIsCS = false;
  deleteTempFiles = true;
  directionalDerivatives = true;
  dumpAlgLoops = false;
  emitEvents = true;
  ignoreInitialUnknowns = false;
  initialStepSize = 1e-6;
  inputExtrapolation = false;
  intervals = 100;
  masterAlgorithm = oms_solver_wc_ma;
  maxEventIteration = 100;
  maximumStepSize = 1e-3;
  maxLoopIteration = 10;
  minimumStepSize = 1e-12;
  numProcs = 1;
  progressBar = false;
  realTime = false;
  resultFile = "<default>";
  skipCSVHeader = true;
  solver = oms_solver_sc_cvode;
  solverStats = false;
  startTime = 0.0;
  stopTime = 1.0;
  stripRoot = false;
  suppressPath = true;
  timeout = 0.0;
  tolerance = 1e-4;
  wallTime = false;
  zeroNominal = false;
}
```

**Comment by casella** [comment]
@arun3688, OMSimulator is not relevant in this context, we are not using it. @deepak19015 showed me a FMU generated from a Buildings example model that had settings in the experiment annotation that were not put into the modelDescription.xml file.

Maybe that was because the FMI was generated some time ago with an older version of OMC - @deepak19015 can you try to re-generate them with the latest nightly build?

Thanks!

**Comment by casella** [comment]
So, there are actually three issues here:
- [ ] the code to solve the initial equations in the FMU should do so _after_ setting time = startTime, see also [my latest comment](https://github.com/OpenModelica/OpenModelica/issues/11802#issuecomment-1954856795) in #11802.
- [ ] when generating the FMU from a script, the Interval experiment annotation should be used to set the stepSize value in the DefaultExperiment tag of modelDescription.xml
- [ ] the buildModelFMU API should also allow to set the DefaultExperiment tag independently of the experiment annotation, to support generating the FMU from OMEdit when those values have been changed with the GUI but not saved to the experiment annotation

**Comment by arun3688** [comment]
> when generating the FMU from a script, the `Interval` experiment annotation should be used to set the `stepSize` value in the `DefaultExperiment` tag of `modelDescription.xml`

This can be fixed, I will implement the code

**Comment by arun3688** [comment]
> Regarding the first of the three issues, simulating an FMU obtained by exporting the follwowing model should return `x0 = 0.2`, not `x0 = 0`, as it currently happens.
> 
> ```modelica
> model M
>   Real x = time;
>   parameter Real x0(fixed = false);
> initial equation
>   x0 = x;
> equation
>   annotation(experiment(StartTime = 0.2, StopTime = 1.0, Interval = 1e-2));
> end M;
> ```

yes the fmu results are wrong, I will look into the code and see how the initial equations are solved

**Comment by arun3688** [comment]
> [x] when generating the FMU from a script, the `Interval` experiment annotation should be used to set the `stepSize` value in the `DefaultExperiment` tag of `modelDescription.xml`

This is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/4f26c776afb720761aabdf2fc5f9734cb7b9bba7

**Comment by arun3688** [comment]
> * the code to solve the initial equations in the FMU should do so _after_ setting time = startTime, see also [my latest comment](https://github.com/OpenModelica/OpenModelica/issues/11802#issuecomment-1954856795) in [ Modelica-Buildings Library (master-fmi-fmpy): Division by zero 0.5 #11802](https://github.com/OpenModelica/OpenModelica/issues/11802).

the issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/c7776a87b312e295d9ddefa36dcc5b531e802559

**Comment by casella** [comment]
Thanks @arun3688! I would wait for the next round of the master-fmi-fmpy test to see if this solves #11802 and possibly how many other similar issues in the library testsuite.

**Comment by casella** [comment]
#11802 is now also fixed.
