### ISSUE TITLE
The translateModel() API function is not documented.

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11885]
For some reason, the translateModel() API function is not documented in the API user guide.

As it is widely used, it probably should be.

@adrpo can you take care of that? Thanks!

**Comment by perost** [comment]
The issue seems to be that it hasn't been added to the ModelicaBuiltin, I can fix that.

**Comment by perost** [comment]
#11886 adds `translateModel` to `ModelicaBuiltin`, which should make it appear in the API user guide as far as I know.

**Comment by casella** [comment]
Indeed: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#translatemodel

Thanks!
