### ISSUE TITLE
Own Library in Version OpenModelica v1.22.1 is not working 

### ISSUE THREAD

**Issue by ISEFix** [OpenModelica/OpenModelica#11897]
Hello OpenModelica developers, 

I was creating in the previous Version an own Library.mo which I can not open in the new version anymore. 
Here is the problem text which I get, when I try to open the library: 

[10] 09:54:22 Syntax Fehler
[H:/01_privat/04_Modelling/BatSys/BatSysLib/BatSysLib.mo: 519:5-519:5]: Lexer failed to recognize '\ 
 
    mo'

[11] 09:54:22 Syntax Warnung
[H:/01_privat/04_Modelling/BatSys/BatSysLib/BatSysLib.mo: 46:57-46:77]: OpenModelica (64-bit) only supports 63-bit signed integers! Transforming: 10000000000000000000 into a real  

Would be wonderful if you could give me a hint to solve the problem. 
Kind Regards 
Felix

**Comment by perost** [comment]
Can you share the referenced line, i.e. line 519 in BatSysLib.mo?

**Comment by ISEFix** [comment]
Problem solved! :D 
Next time I look first into the code before I ask you. There was a backslash which shouldn´t be there. 
Thanks for the fast help.

**Comment by perost** [comment]
> Problem solved! :D Next time I look first into the code before I ask you. There was a backslash which shouldn´t be there. Thanks for the fast help.

Great! I assumed that would be the issue, but it's hard to say without knowing how the code actually looks like.
