### ISSUE TITLE
Error message when duplicating

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#11891]
### Steps to Reproduce
1. open PowerGrids (either 1.0.2 (MSL 3.2.0) or 2.0.0-develop (MSL 4.0.0)
2. open Examples.IEEE14bus-IEEE14busStaticNetwork
3. select Load12 and issue CTRL-D.

The following error messages appear:
1) PowerGrids 1.0.2:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/7b51e886-d1b7-413e-b01c-c1e831b71c09)

2) PowerGrids 2.0.0-develop:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/f58a3596-e2ca-48d2-b669-f41e4203dd20)

### Version and OS

Tested with OM 1.23.0-dev-250

**Comment by adeas31** [comment]
Fixed with #12046 and ported to maintenance 1.22 with #12050
