### ISSUE TITLE
Moving diagrams too slow due to inefficient API

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#11902]
Follow-up of #11887, regarding the slow API issue. Refer to #11887 for details.

**Comment by casella** [comment]
#11906 fixes the issue on master.

@perost, can you please port it to maintenance/v1.22 and colse this ticket? Thanks!

**Comment by perost** [comment]
Fixed in #11906 and ported to maintenance/v1.22 in #11922.
