### ISSUE TITLE
SSD File Format for Exported .ssp models from OpenModelica appears to have incorrect namespaces

### ISSUE THREAD

**Issue by GorbadPS3** [OpenModelica/OpenModelica#11907]
### Description

For example: </ssd:Annotations> should according to specifications be </ssc:Annotations>
Likewise: <ssd:Units> should be <ssc:Units>

They are defined in the .xsd as:

```
            <xs:sequence>
                <xs:element name="Units" minOccurs="0" type="ssc:TUnits"/>
                <xs:element name="Annotations" minOccurs="0" type="ssc:TAnnotations"/>
            </xs:sequence>
```

This, defining in the SSP's .ssd file "ssd:Units" seems to be incorrect, shouldn't it be ssc:Units?

### Steps to Reproduce

Simply export any .ssp file from openmodelica with units and/or annotations

### Expected Behavior

See description above. Please correct me if my assumption of the namespaces is incorrect.

### Version and OS

 - OpenModelica Version: OpenModelica v1.23.0-dev-226-g3237397174 (64-bit)
 - OS: Windows 11, 64 bit

**Comment by casella** [comment]
@arun3688 can you please check?

**Comment by arun3688** [comment]
@GorbadPS3 No they are correct according to the ssp specification 1.0. `OMSimulator` has xerces validator which validates the ssp files generated from any tool and check whether it is following the schema, otherwise it reports warning message The schema looks like this 

 ```
           <xs:sequence>
                <xs:element name="System" type="ssd:TSystem"/>
                <xs:element name="Enumerations" minOccurs="0" type="ssc:TEnumerations"/>
                <xs:element name="Units" minOccurs="0" type="ssc:TUnits"/>
                <xs:element name="DefaultExperiment" minOccurs="0" type="ssd:TDefaultExperiment"/>
                <xs:element name="Annotations" minOccurs="0" type="ssc:TAnnotations"/>
            </xs:sequence>
```
You can see that the root Element for units belong to ssd and all the unit definitions are defined as ssc:Units and this is what OMSimulator generates

```
--       <ssd:Units>
--         <ssc:Unit
--           name="Hz">
--           <ssc:BaseUnit
--             s="-1" />
--         </ssc:Unit>
--         <ssc:Unit
--           name="rad">
--           <ssc:BaseUnit />
--         </ssc:Unit>
--         <ssc:Unit
--           name="s">
--           <ssc:BaseUnit
--             s="1" />
--         </ssc:Unit>
--       </ssd:Units>
```

**Comment by GorbadPS3** [comment]
Hi! Thanks for the clarification!
