### ISSUE TITLE
Obfuscation of records causes issues when only obfuscating protected variables

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#11994]
Obfuscating a model such as this with `--obfuscate=protected` (used to obfuscate e.g. encrypted libraries):
```
record R
  Real x;
  Real y;
end R;

model M
  R r1;
protected
  R r2;
equation
  r1 = R(1, 2);
  r2 = R(3, 4);
end M;
```
results in:
```
function R "Automatically generated record constructor for R"
  input Real x;
  input Real y;
  output R res;
end R;

class M
  Real r1.x;
  Real r1.y;
  protected Real n1.n2;
  protected Real n1.n3;
equation
  r1 = R(1.0, 2.0);
  n1 = R(3.0, 4.0);
end M;
```
The backend then splits the equations into e.g. `n1.x = 3.0` based on the names in the record itself, which causes an error since there's no `n1.x` variable in the model.

So we need to either obfuscate all records or none of them to make sure the names are always consistent. Obfuscating all of them might be problematic though since the obfuscation is done based on instance nodes and not names, so e.g. `x` in `R` does not refer to the same node as `x` in `r1.x`. Not obfuscating them would be a lot easier I think, but I'm not sure if leaving record field names unobfuscated is desirable.

**Comment by perost** [comment]
@casella: Any opinion on this?

**Comment by perost** [comment]
@casella: After some thinking I decided that obfuscating record fields would be quite hard to do for the protected obfuscation (the full still does it since it operates on the SCode and just matches strings), so I decided to just go ahead and disable obfuscation of record fields to avoid this issue. I'm still interested in your opinion on if you think this is good enough for encrypted libraries though.

**Comment by casella** [comment]
I have no strong opinion on this. It's only very small pieces of information, I guess it should be ok.

**Comment by adeas31** [comment]
@perost please port this to maintenance branch.

**Comment by perost** [comment]
> @perost please port this to maintenance branch.

Done in #11997, thanks for the reminder.
