### ISSUE TITLE
'final' modifier causes 'if' condition to use start value rather than calculated value of parameter

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#12011]
### Description
I have a model where there is an 'if' test that depends on a parameter T0 and variable T.  
"elseif T/T0 < 1 then"
T0 has fixed =false. In other words T0 is calculated during initialisation. 

When I add final to the definition of T0:
"final Real T0(fixed=false, start = 0.0952)" (note that the calculated value of T0 is not 0.952!)
... simulation hangs with the message:
Chattering detected around time 38.613662395..38.6136625838 (100 state events in a row with a total time delta less than the step size 0.01). This can be a performance bottleneck. Use -lv LOG_EVENTS for more information. The zero-crossing was: HeatCap.T / 0.09520000000000001 < 1.0

According to the message ("The zero-crossing was: HeatCap.T / 0.09520000000000001 < 1.0"), the condition for the 'if' appears to be T/0.0952, but the model defines "elseif T/T0 < 1 then"
 and T0 is _not_ equal to 0.0952 (T0 is 0.0946789 when the simulation is run for only 30 sec)
Somehow the 'final' keyword leads to the wrong value for T0 used in the 'if' condition.

The code should generate an ellipse which exactly matches with a constant at its top. (continuous for the function itself as well as its 1st derivative)
Because the wrong value for T0 is used in the test, the transition from ellipse to the constant is no longer at T0 (0.0946789), but at T=0.0952, which causes a discontinuity in the function, and thus the chattering.

### Steps to reproduce
The test model in the enclosed zip file generates the error. 
When the 'final' on line 81 of the 'elliptic' submodel is removed, the simulation runs without flaws.
[test_final.zip](https://github.com/OpenModelica/OpenModelica/files/14344854/test_final.zip)

### Expected behavior
I expect 'final' to prevent modifications when the part is inherited or inserted in a larger model. Not that its start value is used as final value.

### Version and OS
 - OpenModelica Version: 1.22.1
 - OS: Windows 11, 64 bit]

**Comment by casella** [comment]
@paultjevdh thanks for reporting!

The problem is reproduced by this much simpler MWE:

```modelica
model TestFinalFixedFalse
  final parameter Real p(start = 1, fixed = false);
  Real x(start = 0, fixed = true);
equation
  der(x) = if x < p then 10 else 1;
initial equation
  p = 2;
end TestFinalFixedFalse;
```
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/29243d09-37c4-4b64-a665-70846e27e3e1)

The slope of x should change when x reaches 2 (the value of p set by the initial equation), not 1 (the start value of p).

@phannebohm would you mind having a look?

**Comment by paultjevdh** [comment]
That's brilliant.  Some tunnel vision on my side obviously. Thanks.

**Comment by phannebohm** [comment]
For some reason we write the constant `1.0` instead of `p` inside the relation check `x < p`. However `p` is set to `2.0` at initialization as it should be. I'll look at codegen.

**Comment by phannebohm** [comment]
BTW, the `--newBackend` does it correctly!

**Comment by casella** [comment]
@phannebohm thanks for the quick fix! @paultjevdh, please try with tomorrow's nightly build.

The try go get the same turnaround bug-fixing time from commercial Modelica tools 😄

**Comment by paultjevdh** [comment]
No chance there 😢
Will try tomorrow.
