### ISSUE TITLE
FMU export missing dll dependencies

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#12013]
### Steps to Reproduce

Pendulum.mo

```
model Pendulum
  extends Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum;
  annotation(
    uses(Modelica(version="4.0.0")),
    experiment(startTime=0.0, stopTime=5));
end Pendulum;
```

test.mos

```
loadFile("Pendulum.mo"); getErrorString();
buildModelFMU(Pendulum); getErrorString();
```

Run

```bash
$ omc test.mos
```

Load and simulate FMU with FMPy using the gui

Start a command prompt with python that doesn't have all the OpenModelica tools in PATH, e.g. by using a Conda environment and CMD:
```cmd
> python -m fmpy.gui
```

Error message:

```
Failed to load shared library C:\Users\USERNAME\AppData\Local\Temp\tmp0u94en5z\binaries\win64\Pendulum.dll. Could not find module 'C:\Users\USERNAME\AppData\Local\Temp\tmp0u94en5z\binaries\win64\Pendulum.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

### Expected Behavior

Correctly link dependent libraries and simulate with FMPy.

### Version and OS

 - OpenModelica Version: v1.23.0-dev-177-gb8bfff9887-cmake
 - OS: Windows 11
 - MSL: 4.0.0
 - FMPy: v0.3.18
 - Python: 3.9.18

### Additional Context

From https://stackoverflow.com/questions/78019725/fmu-export-from-openmodelica-to-python-fmpy

**Comment by AnHeuermann** [comment]
pthread is missing again:

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/bc27e7c1-5e17-46c6-a49a-18abb829ca18)

Looks like [SimCodeMain.mo#L935-L960](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L935-L960) is not working correctly for case `--fmuRuntimeDepends=default` and set's `RUNTIME_DEPENDENCIES_LEVEL="none"` instead of `"modelica"`.

```
        // Set CMake runtime dependencies level
        _ := match (Flags.getConfigString(Flags.FMU_RUNTIME_DEPENDS))
          local
            SemanticVersion.Version cmakeVersion;
            SemanticVersion.Version minimumVersion;
          case("default") algorithm
            cmakeVersion := SimCodeUtil.getCMakeVersion();
            minimumVersion := SemanticVersion.SEMVER(3, 21, 0, {}, {}); // v3.21.0
            if SemanticVersion.compare(minimumVersion, cmakeVersion) <= 0 /* minimumVersion <= cmakeVersion */ then
              cmakelistsStr := System.stringReplace(cmakelistsStr, "@RUNTIME_DEPENDENCIES_LEVEL@", "\"modelica\"");
            else
              cmakelistsStr := System.stringReplace(cmakelistsStr, "@RUNTIME_DEPENDENCIES_LEVEL@", "\"none\"");
            end if;
            then();
          case("none") algorithm
            cmakelistsStr := System.stringReplace(cmakelistsStr, "@RUNTIME_DEPENDENCIES_LEVEL@", "\"none\"");
            then();
          case("modelica") algorithm
            cmakelistsStr := System.stringReplace(cmakelistsStr, "@RUNTIME_DEPENDENCIES_LEVEL@", "\"modelica\"");
            then();
          case("all") algorithm
            cmakelistsStr := System.stringReplace(cmakelistsStr, "@RUNTIME_DEPENDENCIES_LEVEL@", "\"all\"");
            then();
          else algorithm
            Error.addCompilerError("Unsupported value " + Flags.getConfigString(Flags.FMU_RUNTIME_DEPENDS) + "for compiler flag 'fmuRuntimeDepends'.");
            then();
        end match;
```

**Comment by AnHeuermann** [comment]
Looks like piping in the system command is breaking function `getCMakeVersion`

Run the following mos script to reproduce a similar error:

```modelica
system("echo 'This is a text with version in it' 2>&1 | grep version", "stdout.log");
```

This will result in an empty log file. On the msys bash this is working:

```bash
> echo 'This is a text with version in it' 2>&1 | grep version
This is a text with version in it
```

I'll skip the piping and will do the regex maginc inside MetaModelica.
@adrpo Any idea why piping isn't working?

**Comment by casella** [comment]
Thanks  @AnHeuermann, missing pthread in FMU issues pop up every now and then, I hope this is the last time 😄
