### ISSUE TITLE
Package duplication fails to copy function or record in certain conditions

### ISSUE THREAD

**Issue by Natopsi** [OpenModelica/OpenModelica#12024]
### Description
When duplicating a class from a package stored in a single .mo file into a package where classes are stored as individual files, OMEdit fails to copy functions.
Record are also affected.

### Steps to Reproduce
From the following archive : [packages.zip](https://github.com/OpenModelica/OpenModelica/files/14379010/packages.zip)
Load APackage
Load BPackage
Duplicate APackage.ASubpackage into BPackage, selecting **Directories For All** when requested
APackage.ASubpackage.AClass.AFunction not duplicated as BPackage.ASubpackage.AClass.AFunction
APackage.ASubpackage.AClass.ARecord not duplicated as BPackage.ASubpackage.AClass.ARecord

### Expected Behavior
Function and record duplicated.

### Screenshots
![screen](https://github.com/OpenModelica/OpenModelica/assets/1297703/91512786-832f-4b4f-a2f8-55fc1c3e3a58)

### Version and OS
OpenModelica v1.23.0-dev-294-gef124e4eb6 (64-bit)
OMSimulator v2.1.1.post247-g614c663-mingw-notlm-debug
Windows 10, 64 Bit
Issue also present in version 1.18.1

**Comment by casella** [comment]
The Duplicate function needs to be improved, this is a known issue, see #5346. We'll be working on it in the next few months, please follow that issue.
