### ISSUE TITLE
Missing download for v1.22.2 Windows.

### ISSUE THREAD

**Issue by JFormhals** [OpenModelica/OpenModelica#12020]
The file for v1.22.2 Windows-Version is missing in the downloads. The folder https://build.openmodelica.org/omc/builds/windows/releases/1.22/2/ is just empty.

**Comment by AnHeuermann** [comment]
Is it working now? https://build.openmodelica.org/omc/builds/windows/releases/1.22/2/64bit/ has [OpenModelica-v1.22.2-64bit.exe](https://build.openmodelica.org/omc/builds/windows/releases/1.22/2/64bit/OpenModelica-v1.22.2-64bit.exe)

**Comment by casella** [comment]
Looks good now

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/5f11ff07-baa5-4c18-acb6-c49040ea9298)
