### ISSUE TITLE
OMEdit does not update the parameters pop-up when a replaceable model is redeclared

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12037]
### Description
consider the following MVE (also attached) that contains the model `Instance` that defines a replaceable model `M` and its instance `mInstance`. 
The `Test` model has an instance named `instance` of the model `Instance` placed on the diagram, so that the user can redeclare the model `M` by using the parameters pop-up window of the `instance`. 

```modelica
package TestParametersOnRedeclare
  model Mbase
    parameter Real Mbp1;        
  end Mbase;
  
  model M1
    extends Mbase;
    parameter Real M1p1;
  end M1; 

  model M2
    extends Mbase;
    parameter Boolean M2p1;
  end M2; 

  model Instance
    replaceable model M = M1
    constrainedby Mbase
    annotation(choices(choice(redeclare replaceable model M = M2)));
    
    M mInstance;           
  end Instance;
  
  model Test
  Instance instance annotation(
      Placement(transformation(extent = {{-10, -10}, {10, 10}})));
  end Test; 

end TestParametersOnRedeclare;
```
When model `M` is redeclared the correspondent parameters pop-up sub-window should be updated according to the replaced model, what happens is that the parameters of the original model are still shown in the pop-up sub-window, instead of that of the new one.

### Steps to Reproduce

1. load the MVE Package (attached) and open the `Test `model,
2. double click on the `instance` in the Diagram, the following pop-up window is shown

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/7462b58e-7612-4ff0-b0cf-502c8af80850)

3. click on the parameter sub-window icon (red box), the following sub-window that allows to set the parameters `Mbp1` and `M1p1` of the default model `M1` is shown:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/80acee4b-a52d-43f5-9f4a-9fdd807b5627)

4.close the sub-window and redeclare the model `M` to `M2` by using the  drop-down menu, as shown below:

![immagine](https://github.com/OpenModelica/OpenModelica/assets/25974985/69110231-9f35-4985-bce2-ad13f64d858d)

5.click again on the parameter sub-window icon, the pop-up is not updated and still shows the path of the model `M1` and the parameters `Mbp1` and `M1p1` (as before), instead of the path of the model `M2` and the parameters `Mbp1` and `M2p1`. 
Moreover, the following errors are thrown:
```
[3] 11:19:02 Syntax Error
[: 1:0-1:14]: No viable alternative near token: dummyredeclare

[4] 11:19:02 Syntax Error
[: 1:0-1:14]: No viable alternative near token: dummyredeclare
```

### Expected Behavior
The parameter sub-window will be updated with the 
path of the model `M2` and the parameters `Mbp1` and `M2p1`.

### Version and OS
OpenModelica v1.23.0-dev-327-g12a7ef5a86 (64-bit)
Windows 11 pro

### Attached
[TestParametersOnRedeclare.zip](https://github.com/OpenModelica/OpenModelica/files/14418661/TestParametersOnRedeclare.zip)

**Comment by casella** [comment]
Would be nice to have in 1.22.3 if possible.

**Comment by adeas31** [comment]
Fixed with #12047 and ported to maintenance 1.22 with #12050

**Comment by AndreaBartolini** [comment]
Thanks Adeel, I'll check with the new nightly tomorrow...

**Comment by adeas31** [comment]
Thanks for reporting this. I forgot to handle this use case of redeclare.
