### ISSUE TITLE
Duplicate data points in result mat-file at events

### ISSUE THREAD

**Issue by SKittan** [OpenModelica/OpenModelica#12034]
### Description
Simulating a model with the following output options:
 - output format: mat file
 - equidistant time grid
 - store variables at events

will lead to duplicate data points at event times in the result data.

![image](https://github.com/OpenModelica/OpenModelica/assets/36617169/722058ce-f627-490a-bc58-b943fb12fd05)

### Steps to reproduce
- Create the following model:
```modelica
model DuplicateExport
  Modelica.Blocks.Continuous.FirstOrder firstOrder(T = 1)  annotation(
    Placement(transformation(extent = {{-10, -10}, {10, 10}})));
initial equation
  firstOrder.u = 1.0;
equation

  when firstOrder.y > 0.5 then
    firstOrder.u = 2.0;
  end when;

annotation(
    uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 0, StopTime = 10, Tolerance = 1e-6, Interval = 0.01));
end DuplicateExport;
```
- simulate with the upper mentioned output options
- look in the result data, e.g. with python and DyMat package

### Expected behavior
The data point at the event time is only once in the result data.

### Version and OS
 - OpenModelica Version 1.22.2
 -Modelica 4.0.0
 - OS: Windows 11, 64 bit

**Comment by bilderbuchi** [comment]
> The data point at the event time is only once in the result data.

I'm not sure if this is a reasonable expectation -- an event can introduce a jump in a variable at the event time, and to record this you _need_ two data points.

**Comment by casella** [comment]
In fact, if there are event iterations, one could actually think of saving the values at the end of each iteration, always at the same time. This concept is sometimes known as "super-dense" time. This could be useful for debugging, but so far nobody has asked for it.
