### ISSUE TITLE
Model diagram view is empty with modifiers of final/protected variables

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#12032]
### Description
When 'final' or 'protected' parameters/variables are modified in an instantiation of a class containing those, the resulting model diagram is no longer displayed when switching to the diagram view.

### Steps to reproduce
Consider the model below 
```modelica
model test_display
  Modelica.Electrical.Analog.Sources.SineVoltage sineVoltage(V = 2)  annotation(
    Placement(transformation(origin = {-44, 34}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Ground ground annotation(
    Placement(transformation(origin = {-44, 6}, extent = {{-10, -10}, {10, 10}})));

  model RC
    extends Modelica.Electrical.Analog.Interfaces.OnePort( i(displayUnit = "uA"), v(displayUnit = "nV"));
    final parameter Modelica.Units.SI.Temperature T_crit0(displayUnit = "mK", fixed=false, start = 95e-3) "Critical temperature of the TES @ zero current (R>0 for T>T_crit0)." annotation(Dialog(enable=false,group="Ginzburg-Landau equation"));
    
  protected
    Real a(start=a_def) "Local half diameter in 'T' direction";
  end RC;

  test_display.RC RC1(m=0) annotation(
    Placement(transformation(origin = {2, 32}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
equation
  connect(sineVoltage.n, ground.p) annotation(
    Line(points = {{-44, 24}, {-44, 16}}, color = {0, 0, 255}));
  connect(sineVoltage.p, RC1.p) annotation(
    Line(points = {{-44, 44}, {2, 44}, {2, 42}}, color = {0, 0, 255}));
  connect(RC1.n, ground.p) annotation(
    Line(points = {{2, 22}, {-44, 22}, {-44, 16}}, color = {0, 0, 255}));
end test_display;
```
This defines the model below:
![image](https://github.com/OpenModelica/OpenModelica/assets/59084059/2762c468-1148-42ad-b303-f94ee0fd1bd8)

The RC instance RC1 has a modifier for the non-existent member parameter 'm': ```test_display.RC RC1(m=0) annotation(...```, which has no effect on the diagram (that is: the diagram is drawn, just like when there was no modifier).
However, if m is replaced by 'a' or 'T_crit0', the diagram view is empty. 
The effect seems to be triggered by the protected and final keywords. When 'a' is not protected, the effect is not there for 'a'. Likewise the effect for 'T_crit0' is absent when 'T_crit0' is not defined final.

### Expected behavior
Code changes or -errors like this should not affect the drawing of the diagram. I believe this has been the case up to 1.22.1, but in 1.22.2 it does.

### Version and OS
 - OpenModelica Version 1.22.2
 - OS: Windows 11

**Comment by paultjevdh** [comment]
The use-case is as follows: when you are developing models and components, the interface and internals tend to change over time. It is impossible to update all the calling models if you change the interface of a called model. When you load one of these calling models some time later, you get an empty screen, while the offense is completely unrelated to the graphical representation of the model. Also the fact that there is no model at all, when the error may be in a sub-sub-sub-sub model is over-reacting in my view.
In dymola you get a 'remove modifier' button, which is much more friendly than a blank screen. It allows the model to be fixed from the graphical interface but it requires the diagram to be visible....

**Comment by bilderbuchi** [comment]
> When you load one of these calling models some time later, you get an empty screen, while the offense is completely unrelated to the graphical representation of the model. Also the fact that there is no model at all, when the error may be in a sub-sub-sub-sub model is over-reacting in my view.

AFAIK, the fact that the diagram disappears when a model is invalid is a relatively recent change (in 2023?), and I seem to remember this not being the case previously. I agree that this feels frustrating/annoying. I wonder if there is a way to not have the diagram disappear, but some other error indication?

**Comment by paultjevdh** [comment]
If you add a non-existent variable as modifier (e.g. ```  test_display.RC RC1(m=0)```, the diagram is drawn, although this might also count as an error.

**Comment by casella** [comment]
@bilderbuchi, @paultjevdh, the reason why this happens is that now we are using the front end to flatten the model in order to get the relevant information for the GUI. If the code is invalid, you get nothing. If necessary, we can add exceptions, so that the front-end accepts not-so-legal code without breaking up.

@perost, can you please check the case that @paultjevdh posted?

**Comment by casella** [comment]
> I wonder if there is a way to not have the diagram disappear, but some other error indication?

I have discussed this with @perost and @adeas31 some time ago. Maybe we should really get something like a red warning such as "Error: the model is invalid, so it cannot be displayed", followed by some diagnostic message about why it is actually invalid.

@perost, @adeas31 what do you think?

**Comment by adeas31** [comment]
The error message is always shown in such cases. Maybe we should also display something in the diagram view which tells the user about the error. It is also possible to recover from the error by undoing the last action.

Btw, shouldn't we port this fix to 1.22.3?

**Comment by casella** [comment]
> The error message is always shown in such cases. 

It is shown in the error message browser, but it's not trivial, particularly for new users, to figure out this is related to the diagram not showing up. Normal users have no idea about the instance-based mechanism, nor they should.

I think we should show some kind of message _in the diagram window_

>It is also possible to recover from the error by undoing the last action.

This could be suggested in the aforementioned error message, e.g. "you can type Ctrl-Z to undo the last changes and get back to the previous state of this model".

> Btw, shouldn't we port this fix to 1.22.3?

That would be nice. @perost can you please do that?

**Comment by adeas31** [comment]
> > The error message is always shown in such cases.
> 
> It is shown in the error message browser, but it's not trivial, particularly for new users, to figure out this is related to the diagram not showing up. Normal users have no idea about the instance-based mechanism, nor they should.
> 
> I think we should show some kind of message _in the diagram window_
> 
> > It is also possible to recover from the error by undoing the last action.
> 
> This could be suggested in the aforementioned error message, e.g. "you can type Ctrl-Z to undo the last changes and get back to the previous state of this model".

Please make a new ticket about it.

**Comment by perost** [comment]
> > Btw, shouldn't we port this fix to 1.22.3?
> 
> That would be nice. @perost can you please do that?

Done in #12048.

**Comment by casella** [comment]
See #12049

**Comment by paultjevdh** [comment]
While I appreciate the efforts to make the situation more clear to the user through a message in the diagram window, I fail to understand why omedit chooses to be so strict. 
In reality it is not uncommon for a model to be invalid while developing, right?

>@bilderbuchi, @paultjevdh, the reason why this happens is that now we are using the front end to flatten the model in order to get the relevant information for the GUI. If the code is invalid, you get nothing. If necessary, we can add exceptions, so that the front-end accepts not-so-legal code without breaking up.

At the top level, the only relevant code for model display that I can think of are element name (refdes), annotations and possibly displayUnit from the modifiers.  
For value modification through the GUI, which _does_ access the modifiers, it is more user friendly to apply the dymola solution:
![image](https://github.com/OpenModelica/OpenModelica/assets/59084059/149d1afd-c1b9-4069-b648-6de4b16f4fcd)
You could also display the model and indicate 'broken' elements in the diagram, similar to loading a model which contains elements from a library that is not loaded. 
![image](https://github.com/OpenModelica/OpenModelica/assets/59084059/15782a46-94d8-4d7b-8544-0f0dfad28a33)
omedit has no trouble displaying this model while it has no idea about its correctness.

On the other hand I understand that you have to prioritize.

**Comment by casella** [comment]
@paultjevdh, the old OMEdit GUI tried to figure out features of the model by itself. For example, it crawled the inheritance trees itself to figure out what features should be displayed of a model that extends other ones. This was really not the right approach: Modelica is terribly complicated, and OMEdit was basically trying to redo (badly) what the frontend does already.

So, we switched to a new framework, where the frontend flattens the model, so it takes into account inheritance, parameter values that influence conditionally instantiated components, etc., and passes the results to OMEdit as a JSON file. Then, OMEdit just needs to display them. This is much more powerful, flexible and efficient than the previous approach.

The problem with the frontend is that it was born to be strict, i.e., to only allow compiling valid Modelica models. Of course there is no need to be strict when doing graphical editing and, in fact, @perost has been adding many exceptions so that the frontend is less strict when doing the flattening for editing, not for compiling models. Unfortunately, we keep on discovering new cases where we need to relax the front end. Currently, they are caught because the diagram goes blank, it would be much better if it gave you an error message. You can still open tickets if you think that those errors are unnecessarily strict, and we will relax the frontend accordingly.

**Comment by paultjevdh** [comment]
That is really valuable feedback. It is good to understand what your approach to this is in order to provide constructive feedback back to you. Thanks!
