### ISSUE TITLE
Display error messages in the diagram window if the inst-based API fails and no diagram is displayed

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12049]
Currently, when the code of some Modelica model is invalid, its diagram is not shown and you get some error messages in the Messages window.

We should also display an error message in the diagram window, such as "The Modelica code of this model is invalid, so the diagram cannot be displayed. Please check the Messages browser for error messages and possibly undo the latest changes with Ctrl-Z"

**Comment by adeas31** [comment]
Lets target this for 1.23.0

Its easy to add this functionality but its not a real bug fix so I will not prefer adding it to the maintenance branch.
