### ISSUE TITLE
PowerGrids IEEE14bus models generate a compiler error under Win11 pro

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12055]
### Description
Starting from the OpenModelica version v1.23.0-dev-340-g2ab9ff89dc (64-bit) all the models of the network IEEE14bus in PowerGrids library fail the compile phase under WIN11 pro 64 bit

### Steps to Reproduce
1) Install OpenModelica v1.23.0-dev-340-g2ab9ff89dc (64-bit) Under Win11 pro
2) Install PowerGrids library - develop branch - https://github.com/PowerGrids/PowerGrids/tree/develop
2) open the model `PowerGrids.Examples.IEEE14bus.IEEE14busPowerFlow` in OMEdit
3) simulate the model

The compile phase fails and a lot of the following errors are thrown

```
IEEE14busPowerFlow_16dae.c:26:5: error: call to undeclared function 'IEEE14busPowerFlow_eqFunction_9583'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   26 |     IEEE14busPowerFlow_eqFunction_9583(data, threadData);
      |     ^
IEEE14busPowerFlow_16dae.c:31:5: error: call to undeclared function 'IEEE14busPowerFlow_eqFunction_9584'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   31 |     IEEE14busPowerFlow_eqFunction_9584(data, threadData);
      |     ^
 .....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
mingw32-make: *** [<builtin>: IEEE14busPowerFlow_16dae.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....
mingw32-make: Leaving directory 'C:/Users/andre/DOCUME~1/OPENMO~1/POWERG~1.IEE'
Compilation process failed. Exited with code 0x00000002.
```

The same happens with all the IEEE14bus models.

### Version and OS
OpenModelica v1.23.0-dev-340-g2ab9ff89dc (64-bit)
Win11 pro - 64 bit

**Comment by AndreaBartolini** [comment]
keep @casella and @ceraolo in copy

**Comment by adrpo** [comment]
Ouch, this should not be the case, the functions should be forward declared.
I will check. 

Is this with daeMode?

**Comment by AndreaBartolini** [comment]
Yes, the simulation is made by using daeMode and also the minimal thearing, herebelow the simulaiton settings:
`__OpenModelica_commandLineOptions = "--daeMode --tearingMethod=minimalTearing"`

**Comment by adrpo** [comment]
My bad, I tested with `translateModel `instead of `buildModel `as it was faster but that was wrong as the model did not actualy build. Should be fixed with #12057.

**Comment by casella** [comment]
Is that the reason why the failure does not happen in the CI?

**Comment by casella** [comment]
#12057 causes an [error](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-12057/1/tests) in  testDAEModeFileSplit_Issue4851.mos – simulation_modelica_daemode

**Comment by adrpo** [comment]
Should be fixed now. I also changed `translateModel `to `buildModel` in the test to make sure it compiles and links.

**Comment by AndreaBartolini** [comment]
> Is that the reason why the failure does not happen in the CI?

I suppose because Linux and Win use a different C compiler

**Comment by casella** [comment]
> I suppose because Linux and Win use a different C compiler, and AFAIK the CI is made by using Linux only

As I understand, the generated C code was invalid. The difference was that OMEdit used buildModel while the CI used translateModel

**Comment by AndreaBartolini** [comment]
If I remember right, the CI under Linux simulated, so the compiler had accepted the code.
Anyway, the main thing is that the problem has been solved..

**Comment by casella** [comment]
I checked with the latest nighty on Windows, problem solved
