### ISSUE TITLE
For an encrypted library mlle_license_new is called very often

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#12062]
### Description

When you load an encrypted library into OMEdit, the SEMLA license manager function ```mlle_license_new``` is called for each library feature. However, it should only be called once when the library is loaded.
The constant calling of the mlle_license_new function causes an error in our license validation method.

### Version and OS

 - OpenModelica Version: OpenModelica v1.22.0 (64-bit)
 - OS:  Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@adeas31 maybe this also can fit in 1.22.3, not sure.

**Comment by adeas31** [comment]
@niklwors why did you close this?

**Comment by niklwors** [comment]
The problem only occurs if an error occurs in the mlle_license_new function. Then it is called again and again for each license feature. Otherwise the problem does not occur. Therefore, it is not problematic.
