### ISSUE TITLE
Icon not drawn at all in Icon view and in Diagram view

### ISSUE THREAD

**Issue by gwr69** [OpenModelica/OpenModelica#12077]
### Description

I am not seeing any icon display (wrong Icon view) at all in the Libraries window for some classes with explicit `Icon` annotation. Classes that extend from this class will not properly show in Diagram view.

### Steps to Reproduce

1. Download https://github.com/bslMS/BusinessSimulation/tree/release
2. Open one of the classes [`Icons.Source`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Icons/Source.mo), [`Icons.SourceOrSink`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Icons/SourceOrSink.mo), or [`Sink`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Icons/Sink.mo) (they will have empty white squares in Library window)
3. Inspect the Icon View for those classes: They are all empty white squares.
4. Open the class [`Examples.LotkaVolterraEquationsRevisited`](https://github.com/bslMS/BusinessSimulation/blob/efcf8940ef004c8fbd8595beed11d06889ede34d/BusinessSimulation/Examples/LotkaVolterraEquationsRevisited.mo)
5. Select Diagram view.

### Expected Behavior/Screenshots

In Wolfram System Modeler 14 the classes will show like this:

**`Icons.Source`**

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/2ed6481f-4f86-43d6-978f-4ad0eac349b3)

**`Icons.SourceOrSink`**

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/a18fe806-fe76-42da-a060-6663e44b3b1e)

**`Icons.SourceOrSink`**

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/cc19f7de-4acf-4ecf-b6ab-cd5250fde0e3)

This is how `Examples.LotkaVolterraEquationsRevisited` looks in System Modeler 14:

![image](https://github.com/OpenModelica/OpenModelica/assets/17766670/20ab3d96-9837-4a41-9e08-08e0206fe284)

... and this is Diagram view in OMEdit:

![LotkaVolterraEquationsRevisited](https://github.com/OpenModelica/OpenModelica/assets/17766670/5f61d2ec-3748-4517-b19c-c4e6fc5f3015)

Next to the false display of `reproduction`, `wolvesStarving`, and `foxesStarving`, which are all extending from above named partial classes in the `Icons` package of the BusinessSimulation library, one should note that the diagram also show the _outer connector_ `modelOutput` using its `Icon` annotation instead of the `Diagram` annotation as has been mentioned in #12074

### Version and OS

 - OpenModelica Version: `v1.22.2 (64 bit)`
 - OS: `Windows 10, 64 bit`
 - MSL 4.0

### Additional Context

These issues relate to making the free [BusinessSimulation](https://bsl-support.de/BusinessSimulation/BusinessSimulation) library in its upcoming release `v2.2.0` more usable for Open Modelica users.

**Comment by gwr69** [comment]
Note that OMEdit reports **Scripting Errors** for the mentioned classes, such as the following:

> Error: Variable Smooth.Bezier not found in scope Sink.

But `Smooth.Bezier` is a clearly defined annotation according to [Section 18.6.1.2](https://specification.modelica.org/maint/3.6/annotations.html#graphical-properties) of the Specs?

**Comment by gwr69** [comment]
For completeness, there are **no icons visible** in Libraries Browser or Icon view for `Icons.Info`, `Icons.DataBus`, `Icons.MultiPort`, and `Icons.OmniBus`.

There are **no visible icons in the Libraries Browser** but one in Icon view for the classes `Icons.FunctionLetter`, `Icons.DiscreteSmoothLabel`, `Icons.MaterialStockIndicator`, `Icons.DiscreteStockLabel`, `Icons.CapacityLabel`. The correct icon is displayed in Icon view.

To some extent I find that it is mainly **text display missing** in the icon display of the Libraries Browser: `Icons.Enumeration`, `Icons.Theta`, `Icons.Function` and other classes (a design decision?). The correct icon is displayed in Icon View.

Inspection of `Icons.Info` reveals that `smooth = Smooth.Bezier` is the culprit:

```
within BusinessSimulation.Icons;

partial class Info "Icon for information pages (UsersGuide)"
  annotation(
      Icon(
        coordinateSystem(extent = {{-100, -100}, {100, 100}}, preserveAspectRatio = true, initialScale = 0.1, grid = {10, 10}),         
        graphics = {
            Ellipse(visible = true, lineColor = {255, 170, 0}, fillColor = {255, 170, 0}, fillPattern = FillPattern.Solid, lineThickness = 5, extent = {{-95, -95}, {95, 95}}), 
            Polygon(visible = true, origin = {-4.167, -15}, fillColor = {255, 255, 255}, 
                pattern = LinePattern.None, fillPattern = FillPattern.Solid, 
                points = {{-15.833, 20}, {-15.833, 30}, {14.167, 40}, {24.167, 20}, {4.167, -30}, {14.167, -30}, {24.167, -30}, {24.167, -40}, {-5.833, -50}, {-15.833, -30}, {4.167, 20}, {-5.833, 20}}, 
                smooth = Smooth.Bezier
            ), 
            Ellipse(visible = true, origin = {7.5, 56.5}, fillColor = {255, 255, 255}, pattern = LinePattern.None, fillPattern = FillPattern.Solid, extent = {{-12.5, -12.5}, {12.5, 12.5}})
        }), 
      .... 
    );
end Info;
```

The code above from the branch `release` will not render as a visible icon and changing the `smooth` attribute for the `Polygon` to `smooth = None` will not help.

Removing the `smooth = Smooth.Bezier` part of the annotation will provide an icon:

![Info](https://github.com/OpenModelica/OpenModelica/assets/17766670/56e60180-08a4-44fe-9547-9adfdec18665)

**Comment by gwr69** [comment]
@perost Great! What about the icon annotation being used in diagram view for outer connectors. That’s different?

**Comment by perost** [comment]
> @perost Great! What about the icon annotation being used in diagram view for outer connectors. That’s different?

That's a different issue, and covered by #12074 unless I misunderstood what you wrote.

**Comment by adeas31** [comment]
@perost shall we port #12078 to maintenance 1.22?

**Comment by perost** [comment]
> @perost shall we port #12078 to maintenance 1.22?

Sure, done in #12085. I wanted to make sure it doesn't break anything since it changes the name lookup, but the library testing looks good.
