### ISSUE TITLE
Documentation Browser opens in a window that cannot be closed

### ISSUE THREAD

**Issue by gwr69** [OpenModelica/OpenModelica#12081]
### Description

Upon selecting Documentation View a window opens that cannot be closed by context menu (right click with mouse), that does not have a closing icon, and that cannot be moved or hidden.

### Steps to Reproduce

1. Start OMEdit
2. Select `Modelica` in Libraries Browser and double click (left mouse button).

or

2. Open Class `Modelica.Blocks.Examples.PID_Controller` from Libraries Browser
3. Select Documentation View tab (circled i) in Diagram View

### Expected Behavior

Window should be movable, resizable, and closable.

### Screenshots

![Screenshot 2024-03-06 151925](https://github.com/OpenModelica/OpenModelica/assets/17766670/5e8248bc-44a9-4958-9814-01bcb0c67f0b)

### Version and OS

 - OpenModelica Version: `v1.23.0-dev-358-g07765ef93c (64bit)`
 - OS: `Windows 10, 64 bit`
 - `MSL 4.0`

**Comment by adeas31** [comment]
The window is movable, resizable, and closable. The title bar is not shown in your screendump. I don't know how you managed to pop out the dock window in a way that its title bar is hidden outside the screen. You can still close this from the menu `View|Windows|Documentation`.

**Comment by gwr69** [comment]
My bad, I tried vertical movement and right clicking. But the close icon will appear eventually when I shrink the window. Very weird. Note that the window popped up extending outside of my screen after I had used the laptop with an external 43" screen. I must have stored that information and never recognised the actual screens' dimensions.

**Comment by gwr69** [comment]
Confusing behavior, which may be improved? But at least with an easy solution after all ...
