### ISSUE TITLE
CoSimulation FMUs with Sundials and DLL dependencies

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#12086]
### Description

Followup on https://github.com/OpenModelica/OpenModelica/issues/11604.
While the static linking is working, it would be nice to use shared DLLs instead of the static .lib or .a libraries for Sundials and CVODE, so users can recompile the generated Windows FMU.

### Steps to Reproduce

Build OpenModelica with dynamic Sundials libraries and gcc 🍵 :

```bash
cmake -S . -B build_cmake -G "MSYS Makefiles" -DSUNDIALS_BUILD_SHARED_LIBS=ON -DSUNDIALS_BUILD_STATIC_LIBS=ON
cmake --build build_cmake --parallel 14 --target install
```

and disable static linking in CMake FMUs in [OMCompiler\SimulationRuntime\fmi\export\buildproject\CMakeLists.txt.in](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/buildproject/CMakeLists.txt.in#L147-L152):

```cmake
if(${NEED_CVODE})
  # Force static compilation on Windows because DLLs suck
  #if(WIN32)
  #  set(CMAKE_FIND_LIBRARY_SUFFIXES .a .lib)
  #  target_compile_definitions(${FMU_NAME} PRIVATE LINK_SUNDIALS_STATIC)
  #endif()
```

Then export a FMU for

*Pendulum.mo*
```modelica
model Pendulum
  extends Modelica.Mechanics.MultiBody.Examples.Elementary.Pendulum;
  annotation(
    uses(Modelica(version="4.0.0")),
    experiment(StartTime=0.0, StopTime=5));
end Pendulum;
```

*test.mos*
```modelica
loadFile("Pendulum.mo"); getErrorString();
setCommandLineOptions("--fmiFilter=internal --fmuRuntimeDepends=modelica --fmiFlags=s:cvode"); getErrorString();
cd("temp"); getErrorString();
buildModelFMU(Pendulum, fmuType="cs"); getErrorString();
```

by running:

```bash
mkdir temp
omc test.mos
```

When simulating this FMU with e.g. OMSimulator the `Pendulum.dll` can't be loaded.

```bash
OMSimulator --mode=cs --deleteTempFiles=false Pendulum.fmu
Loading DLL failed: D:\workspace\Testitesttest\issue-11604\temp\model-omydsgf4\temp\0001_Pendulum\binaries\win64\Pendulum.dll
Failed to load functions for FMI 2.info:    fmi2Instantiate() failed
error:   [terminate] Model "model" is in wrong model state
Function "fmi2FreeInstance" is not provided by this FMU.
```

But I don't see any load errors when running Dependencies on it:
![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/6b2b4d14-689c-4df6-92a2-dc5b632d6ba9)

### Expected Behavior

Loading of `Pendulum.dll` should be possible and `FMU/binaries/win64/` should contain:

```
.
├── libPendulum.dll.a
├── libsundials_cvode.dll
├── libsundials_nvecserial.dll
├── libwinpthread-1.dll
└── Pendulum.dll
````

Maybe the 

### Version and OS

 - OpenModelica Version: v1.23.0-dev-365-gd62eaaf56d-cmake
 - OS: Windows 11 Pro (version 23H2, build 22631.3155)

### Additional Context

Here is the generated FMU (remove the `.zip` part from the name):
[Pendulum.fmu.zip](https://github.com/OpenModelica/OpenModelica/files/14522830/Pendulum.fmu.zip)

**Comment by casella** [comment]
DLL hell if I ever saw it...

**Comment by AnHeuermann** [comment]
Maybe we should keep the static linking for now.
It's way simpler and the benefit of having DLLs in FMUs isn't worth the hassle.

But for OMsimulator I opened a PR to fmi4c that would fix the issue. Someone needs to figure out how to update our copy of fmi4c, though.

**Comment by AnHeuermann** [comment]
https://github.com/OpenModelica/OMSimulator-3rdParty/pull/82 will fix this eventually.

**Comment by AnHeuermann** [comment]
While OMSimulator will be capable of simulating these FMUs, most other tools won't. So let's stick to the static version of CVODE or we can add all source files to source-code FMU.
