### ISSUE TITLE
Regression: Empty variable browser if a model from within an encrypted library is simulated

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12109]
### Description

Thanks to #11718 the simulation output option "Protected Variables" no longer applies to encrypted libraries. However, with the OMEdit 1.22.3 Pro no variables (not even public ones) are shown in the variable browser at all if a model from within an encrypted library is simulated. This is a problem for the examples included in our BRSL library. This problem did not occur for the OMEdit Pro in version 1.22.0.

### Steps to Reproduce

1. Simulate the model `Rexroth_BRSL.Examples.Hydraulics.FlowDirections` from the encrypted BRSL 3.0.0, which should be available to you. The variable browser is empty.
2. Duplicate the model and save the duplicate outside of the BRSL. 
3. Simulate the duplicated model. The variable browser now is not empty anymore and includes all public variables like `tank.pA`.

### Expected Behavior

All public parameters and public parameters of public instances are displayed in the variable browser even if the simulated model is part of an encrypted library.

### Version and OS

 - OpenModelica Version: 1.22.3 Pro
 - OS: Windows 10, 64 bit
 - BRSL 3.0.0 and MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
Sorry, I added the wrong check in #11718. Should be fixed with #12121.

I started the encryption build. Please test it when its available for download.

**Comment by abuntrock** [comment]
We'll check this with the nightly encryption build. Thanks for the quick fix

**Comment by abuntrock** [comment]
I was finally able to test this with the encryption build of version Connected to OpenModelica v1.24.0-dev-31-gedfa9cd10e (64-bit) and the results are back. Thanks a lot.
