### ISSUE TITLE
Beginner documentation referring to `class` when it should be `model`

### ISSUE THREAD

**Issue by cweickhmann** [OpenModelica/OpenModelica#12105]
### Description

The documentation contains examples like the HelloWorld example that uses `class` which is considered deprecated by Modelica. This correctly results in a compile warning/error on OpenModelica 1.23 and earlier versions. Instead it should use `model`.

### Steps to Reproduce

* Follow [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.23/plotting.html) which seems to reproduce `OMCompiler/Examples/HelloWorld.mo`.
* Create `HelloWorld.mo` in e.g. OMEdit
* Run simulation
* Observe warnings:

```
[1] 10:33:33 Compile Warning
[class_test: 2:3-2:34]: Components are deprecated in class.

[2] 10:33:33 Compile Warning
[class_test: 3:3-3:23]: Components are deprecated in class.

[3] 10:33:33 Compile Warning
[class_test: 5:3-5:19]: Equation sections are deprecated in class.
```

This behaviour is even reflected in the [automatically generated code in the docs](https://openmodelica.org/doc/OpenModelicaUsersGuide/1.23/plotting.html). Underneath the example, there is a big red box with three warnings.

### Expected Behavior

The Hello World example for beginners should not produce any warnings. If warnings occur, they should be discussed and explained in the documentation.

### Screenshots

![openmodelica_helloworld_warnings](https://github.com/OpenModelica/OpenModelica/assets/15192310/a9c71c2d-a9f5-4d7e-ad32-5f7233bcfaf2)

### Version and OS

 - OpenModelica 1.22.3
 - OS: Ubuntu 22.04.4 LTS
 - Versions of used Modelica libraries if applicable: Does not apply

### Additional Context

None.

**Comment by casella** [comment]
@cweickhmann thanks for reporting. I grep'd all .rst files in https://github.com/OpenModelica/OpenModelica/tree/master/doc/UsersGuide/source and I only found that instance.

Should be fixed by PR #12107.
