### ISSUE TITLE
Derivatives of variables of protected classes are sometimes shown in the variable browser

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12110]
### Description

For some reason, which is currently beyond my understanding, some derivatives of variables, which are part of protected instances are shown in the variable browser.

### Steps to Reproduce

1. Simulate the model `Rexroth_BRSL.Examples.Systems.SingleAxis` from the BRSL 3.0.0, which should be available to you and inspect the variable browser. 
2. The variable browser includes for example the result `singleRodCylinder.baseCylinder.Friction.der(s)`. However, the instance `baseCylinder` is protected in the `SingleRodCylinder` class. So none of `baseCylinder's`  elements should be written to the result file. Furthermore, the variable `s` inside the Friction class is also protected and does not include a `HideResult=false` annotation. 
3. This also happens with the encrypted BRSL. But thanks to your work now also the instance names and not only the parameter names are encrypted compared to the OMEdit 1.22.0, which makes the problem smaller from a know-how perspective. However, no there are some obfuscated variables in the variable browser the user might be confused of.

If you cannot pin down the problem with the BRSL example, I can try to build up a minimum example. Just let me know.

### Expected Behavior

No elements (e.g. variables) of protected instances are shown in the variable browser. Especially not if the used component is part of an encrypted library

### Version and OS

 - OpenModelica Version: 1.22.3 normal and Pro
 - OS: Windows 10, 64 bit
 - BRSL3.0.0 and MSL4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
> If you cannot pin down the problem with the BRSL example, I can try to build up a minimum example. Just let me know.

Minimum example will be very helpful.

**Comment by abuntrock** [comment]
I was able to create to much smaller example, which however still needs the BRSL: 
```modelica
model MainClass
  
protected
  Modelica.Mechanics.Translational.Components.Mass mass annotation(
    Placement(transformation(origin = {2, 0}, extent = {{-10, -10}, {10, 10}})));
  Rexroth_BRSL.Generic.Hydraulics.Cylinders.Internal.Chamber chamberA(internalUsage = false) annotation(
    Placement(transformation(extent = {{-70, -10}, {-50, 10}})));
  Modelica.Mechanics.Translational.Components.Fixed Hardstop_A(s0 = 0) annotation(
    Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 270, origin = {-90, 0})));
  Rexroth_BRSL.Generic.Hydraulics.Sources.Tank tank_1 annotation(
    Placement(transformation(origin = {0, -70}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(Hardstop_A.flange, chamberA.flange_a) annotation(
    Line(points = {{-90, 0}, {-90, 0}, {-70, 0}}, color = {103, 163, 68}));
  connect(tank_1.port_A, chamberA.port_A) annotation(
    Line(points = {{0, -60}, {-60, -60}, {-60, -10}}, color = {0, 130, 174}));
connect(mass.flange_a, chamberA.flange_b) annotation(
    Line(points = {{-8, 0}, {-50, 0}}, color = {0, 127, 0}));
end MainClass;
```
Simulating this class should yield an empty variable browser because the class has no top level variables and all instances are protected. However, the following variables are shown in the variable browser. 

- chamberA.der(s_rel)
- chamberA.volumeVariable.volumeConversionToSi.der(y)
- mass.flange_a.der(s) (This is an MSL class)

The behavior maybe has something to do with state handling and it depends on the connection (usage) of the class. If I connect the BRSL chamber class to two hardstops instead of one hardstop and a mass no results are shown as expected. This other class is shown below.

```modelica
model MainClass3

protected
  Rexroth_BRSL.Generic.Hydraulics.Cylinders.Internal.Chamber chamberA(internalUsage = false) annotation(
    Placement(transformation(extent = {{-70, -10}, {-50, 10}})));
  Modelica.Mechanics.Translational.Components.Fixed Hardstop_A(s0 = 0) annotation(
    Placement(transformation(extent = {{-10, -10}, {10, 10}}, rotation = 270, origin = {-90, 0})));
  Modelica.Mechanics.Translational.Components.Fixed fixed(s0 = 0.1)  annotation(
    Placement(transformation(origin = {32, 4}, extent = {{-10, -10}, {10, 10}})));
  Rexroth_BRSL.Generic.Hydraulics.Sources.Tank tank_1 annotation(
    Placement(transformation(origin = {0, -70}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(Hardstop_A.flange, chamberA.flange_a) annotation(
    Line(points = {{-90, 0}, {-90, 0}, {-70, 0}}, color = {103, 163, 68}));
  connect(tank_1.port_A, chamberA.port_A) annotation(
    Line(points = {{0, -60}, {-60, -60}, {-60, -10}}, color = {0, 130, 174}));
connect(fixed.flange, chamberA.flange_b) annotation(
    Line(points = {{32, 4}, {-50, 4}, {-50, 0}}, color = {0, 127, 0}));
end MainClass3;
```

I hope this helps. I will try to find a minimum example without the BRSL but I am not sure if I'm able to in a reasonable time.

**Comment by abuntrock** [comment]
I am not able to reproduce this issue without the BRSL easily. I hope the simple example above is enough for you to solve this issue. It only contains one important BRSL class which also does  not include many instances of other BRSL classes.

**Comment by casella** [comment]
Dummy derivatives may be involved, I guess. @kabdelhak, @phannebohm what do you think?

**Comment by kabdelhak** [comment]
> Dummy derivatives may be involved, I guess. @kabdelhak, @phannebohm what do you think?

It might be index reduction related. Somehow the information about protected/hide result from the states does not reach the derivatives. Do we have access to BRSL to test it ourselves?

Two questions that might get us close to the solution:
1. Are the affected states created by index reduction (through differentiation of equations) or are they states in the original model (is the derivative of it explicitly used somewhere?)
2. Are the states/state derivatives part of alias removal? It might be that they get removed and are still shown as alias of something else and we do not properly check if it should be protected.

**Comment by niwokr** [comment]
@kabdelhak Adrian can give you the library.

**Comment by kabdelhak** [comment]
I think i found a fix with #12128.

The problem was the following:
  1. the state derivatives in question did not exist originally but where created by index reduction through differentiation of equations
  2. the were not chosen to be states and marked as dummy states/dummy state derivatives (in this case they even had StateSelect.NEVER)

The combination of these two meant that the derivative had to be created by index reduction on the fly and it had its derivative property stripped and right away to become an algebraic variable. In this specific case the attributes were not inherited properly. If the derivative is created for simcode, the attributes would be inherited properly.

I could not properly test this fix since the BRSL library i was provided with only has windows binaries for the external functions and i am working on linux. From the generated files it should work fine as far as i can see, but needs to be tested once its merged.

**Comment by abuntrock** [comment]
@kabdelhak Thanks a lot for your detective work especially without being properly able to use the BRSL. I will test this with the next nightly build.

**Comment by casella** [comment]
@abuntrock please report if this now works for you. Thanks!

**Comment by abuntrock** [comment]
@casella @kabdelhak Looks good now. Thanks a lot and sorry for the late reply.

**Comment by casella** [comment]
@abuntrock no problem 😃
