### ISSUE TITLE
NB OMEdit crashes on ScalableTestSuite with Transformational Debugger

### ISSUE THREAD

**Issue by phannebohm** [OpenModelica/OpenModelica#12127]
### Description

When I try to simulate `ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5` with the new backend and Transformational Debugger OMEdit crashes.

If I start it from a terminal, it gives the following message:
```bash
$ OMEdit
Aborted (core dumped)
```

It works with the old backend. Other models work with the new backend.

### Steps to Reproduce

- Start OMEdit
- In `Tools->Options->Simulation->Additional Translation Flags:` add `--newBackend`
- Load ScalableTestSuite 2.2.0
- Open `ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5`
- Simulate with Transformational Debugger
- Observe that the simulation is performed but when it finishes OMEdit crashes immediately.

### Expected Behavior

Perhaps the transformational debugger may crash but not all of OMEdit.
At least the simulation results should be visible as if a plain simulation was done.

### Version and OS

 - OpenModelica Version: v1.23.0-dev-384-ged89b5f2f4-cmake
 - OS: Ubuntu 20.04.6 64-bit
 - ScalableTestSuite 2.2.0

**Comment by adeas31** [comment]
PR #12130 should avoid the crash.

I tried to do the diff between the OB json and NB json. Seems that there is a lot of information missing. However, it should not crash in case of missing information. Maybe you will discover more cases when simulating other models with NB.

**Comment by phannebohm** [comment]
Thanks @adeas31 also now I know where to look.
