### ISSUE TITLE
Export FMU Fails - OpenModelica-V1.23-Dev-391

### ISSUE THREAD

**Issue by Primkins** [OpenModelica/OpenModelica#12141]
### Description

Unable to export FMU. It reports the error.

### Screenshots
![image](https://github.com/OpenModelica/OpenModelica/assets/162120981/6adf78e9-8fee-4183-8e93-23467b20b6d0)

### Version and OS
 - OpenModelica Version: OpenModelica-v1.23.0-dev-391-g7423fcddfa-64bit.exe

**Comment by casella** [comment]
@Primkins can you provide the code of your example so we can reproduce it?

Thanks

**Comment by Primkins** [comment]
I am able to export the FMU using OpenModelica-V1.22.3 (64 bit). However unable to export the FMU using OpenModelica-v1.23.0-dev-391-g7423fcddfa-64bit.exe. The issue can be repeated using the PID Controller from OpenModelica examples (Modelica.Blocks.Examples.PID_Controller).

**Comment by casella** [comment]
I tried with a slightly earlier nightly  v1.23.0-dev-381-g47c3c7528c and it works for me. I'll check with the latest nightly if it is a recently introduced regression, but it looks more like a local issue. Maybe you just need to reinstall a clean version.

**Comment by casella** [comment]
It also works with the latest nightly build v1.23.0-dev-409-ga5a3ab3b6f. Looks like a problem with your OS.

**Comment by Primkins** [comment]
I have reinstalled the OpenModelica latest nightly build. It works fine. Thank you.
