### ISSUE TITLE
Autocompletion broken on loaded classes

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12152]
### Steps to Reproduce

- Start OMEdit
- New Modelica class
- Start typing a new line starting with `M`. Autocompletion should show Modelica, and if I add a dot, it should show all the packages of the MSL. Unfortunately, this doesn't happen. Autocompletion only works on keywords

I guess this is a regression, but I'm not sure when this started.

**Comment by adeas31** [comment]
This is definitely a regression from #12104
