### ISSUE TITLE
Right click "Create connector" does not create a connector

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12163]
### Description

While drawing a connection line one can do a right click and press "Create connector". But in the OMEdit no connector is created.

### Steps to Reproduce

1. Consider the following Modelica class
```modelica
model test
  Modelica.Mechanics.Rotational.Interfaces.Flange_a flange_a annotation(
    Placement(transformation(origin = {-100, 0}, extent = {{-10, -10}, {10, 10}}), iconTransformation(origin = {-100, 0}, extent = {{-10, -10}, {10, 10}})));
equation

annotation(uses(Modelica(version = "4.0.0")));
end test;
```
2. Draw a connection from the rotational MSL flange. While doing this do a right click and select "Create connector".
3. No connector is created and one is back in the "connection line drawing mode".

### Expected Behavior

A connector is created when I click on "Create connector" while drawing a connection line.

### Version and OS

 - OpenModelica Version: 1.22.3 and v1.23.0-dev-391-g7423fcddfa (64-bit)
 - OS: Windows 10, 64 bit
 - MSL4.0.0
 
Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@adeas31 is this a regression?

**Comment by abuntrock** [comment]
At least with 1.22.0 it is also already not working.

**Comment by adeas31** [comment]
> @adeas31 is this a regression?

Maybe one of things that are not working with instance API.
@abuntrock have you tried it without instance API.

**Comment by abuntrock** [comment]
@adeas31 I checked it with OMEdit 1.22.3 and it does indeed work without the instance API.

**Comment by casella** [comment]
Gotcha 😄

**Comment by abuntrock** [comment]
Works perfect with today's nightly. Thanks a lot.
