### ISSUE TITLE
Wrong entry in OMEdit parameter dialog

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#12162]
### Description

The entry in the parameter dialog is wrong. For example, with the Buildings library, commit 6475f370351f6e0339046a3223f7bb88aa6273a5

double-clicking on the pumps in `Buildings.Fluid.Movers.Validation.FlowControlled_m_flow` gives for the top pump:

<img width="854" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/1329080/d2fcdc69-f0d1-4c84-a3ce-3985881ef5f9">

and for the bottom pump:

For the model `Buildings.Experimental.DHC.EnergyTransferStations.Cooling.Examples.Indirect`, the entry is
<img width="854" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/1329080/18510318-8dea-43a0-847a-9163a6af6da9">

The entries `dp_nominal(.....)` and `dp_nominal = ` should not be there.
### Steps to Reproduce

See above.

### Version and OS

OMEdit,
Connected to OpenModelica 1.23.0~dev-407-g1fb3195
Connected to OMSimulator 2.1.2-linux-notlm-debug

On Ubuntu 20.04

Buildings library, commit 6475f370351f6e0339046a3223f7bb88aa6273a5

**Comment by casella** [comment]
@adeas31 this seems like an easy fix, if it is, let's have it in 1.23.0
