### ISSUE TITLE
Export FMU Fails for Some Examples of Fluid Library

### ISSUE THREAD

**Issue by Primkins** [OpenModelica/OpenModelica#12171]
Unable to create the FMU for HeatExchanger model from the OpenModelica library. (Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation). It shows the error. 

```
[3] 12:04:54 Symbolic Warning
The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.

[4] 12:04:54 Translation Error
Error building simulator. Build log: cmd: cd "HeatExchangerSimulation.fmutmp/sources/" && mkdir build_cmake_dynamic && cd build_cmake_dynamic && cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" .. && cmake --build . --parallel  --target install && cd .. && rm -rf build_cmake_dynamic
-- The C compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
CMake Warning in C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-htamku/CMakeLists.txt:
  The object file directory     C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-htamku/CMakeFiles/cmTC_8f038.dir/   has 243 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file     CMakeCCompilerABI.c.obj   cannot be safely placed under this directory.  The build may not work
  correctly. 
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/gcc.exe
CMake Warning in C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5/CMakeLists.txt:
  The object file directory     C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5/CMakeFiles/cmTC_b76fd.dir/   has 243 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file     testCCompiler.c.obj   cannot be safely placed under this directory.  The build may not work
  correctly. 
-- Check for working C compiler: C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/gcc.exe - broken
CMake Error at C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler     "C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/gcc.exe"   is not able to compile a simple test program.   It fails with the following output:     Change Dir: 'C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5'
    
    Run Build Command(s): "C:/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~1/OPENMO~1.0-D/tools/msys/usr/bin/make.exe -f Makefile cmTC_b76fd/fast
    /c/PROGRA~1/OPENMO~1.0-D/tools/msys/usr/bin/make  -f CMakeFiles/cmTC_b76fd.dir/build.make CMakeFiles/cmTC_b76fd.dir/build
    make[1]: Entering directory '/c/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5'
    Building C object CMakeFiles/cmTC_b76fd.dir/testCCompiler.c.obj 
    "/C/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/gcc.exe"    -o CMakeFiles/cmTC_b76fd.dir/testCCompiler.c.obj -c /C/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5/testCCompiler.c
    Linking C executable cmTC_b76fd.exe 
    "/C/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/cmake.exe" -E rm -f CMakeFiles/cmTC_b76fd.dir/objects.a
    "/C/Program Files/OpenModelica1.23.0-dev-64bit/tools/msys/ucrt64/bin/ar.exe" qc CMakeFiles/cmTC_b76fd.dir/objects.a "CMakeFiles/cmTC_b76fd.dir/testCCompiler.c.obj" 
    C:\Program Files\OpenModelica1.23.0-dev-64bit\tools\msys\ucrt64\bin\ar.exe: CMakeFiles/cmTC_b76fd.dir/objects.a: error reading CMakeFiles/cmTC_b76fd.dir/testCCompiler.c.obj: No such file or directory 
    make[1]: *** [CMakeFiles/cmTC_b76fd.dir/build.make:99: cmTC_b76fd.exe] Error 1
    make[1]: Leaving directory '/c/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation/HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5'
    make: *** [Makefile:127: cmTC_b76fd/fast] Error 2
    
          CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project) 
-- Configuring incomplete, errors occurred!_

```

Similar issue can be seen in the ‘IncompressibleFluidNetwork’ and ‘BatchPlant_StandardWater’. 

OpenModelica-v1.23.0-dev-409-ga5a3ab3b6f-64bit.exe
OS: Windows 11 64 bit

**Comment by casella** [comment]
See also #11554. Unfortunately what we did there was not enough.

@adrpo, it seems that only using the model name and not its full path for the FMU was not enough to solve the problem.

I am wondering if we really need to add the 100-characters directory name `HeatExchangerSimulation.fmutmp/sources/build_cmake_dynamic/CMakeFiles/CMakeScratch/TryCompile-o1l5u5` to the already long directory with the full pathname in the working directory.

For sure I don't see any need to have `HeatExchangerSimulation.fmutmp` - we could just use `tmp` or `fmutmp`, as there is no ambiguity which FMU is being compiled inside `Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation`

I know the proper way to fix this is to somehow get rid of the damn 200-something character limit, but for the time being could we just try to shorten that path a bit more?

@Primkins as a workaround, you can define
```
model M
  extends Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation;
end M;
```
and make an FMU out of that.

**Comment by casella** [comment]
@arun3688 maybe you can also take care of this?

**Comment by casella** [comment]
Discussion during today's devmeeting. Some ideas:
1. create a symbolic link with a short name
2. use a short hash of a few characters instead of HeatExchangerSimulation.fmutmp

**Comment by casella** [comment]
We can proceed with the first beta release and add this fix later to the final release.

**Comment by arun3688** [comment]
@casella I did a quick test and found that OMEdit is creating directory with fully qualified path for example 

`C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Fluid.Examples.HeatExchanger.HeatExchangerSimulation`

Instead of fully qualified path we can simply use the model ident to create directory and it will reduce around 40 chars and it can help a bit. for example `C:/Users/DEMO/AppData/Local/Temp/OpenModelica/OMEdit/HeatExchangerSimulation` and this worked  fine.

**Comment by casella** [comment]
@arun3688 this is how OMEdit works, so that results referring to different models can be stored without any name clashes (e.g. you could have Package1.Example and Package2.Example, and they ned different directories).

However, we could _build_ the FMU in a temporary directory with a short path name, and then just copy the FMU to the fully qualified pathname when the building process is over. This would for sure help.

**Comment by arun3688** [comment]
> However, we could _build_ the FMU in a temporary directory with a short path name, and then just copy the FMU to the fully qualified pathname when the building process is over. This would for sure help.

@casella This PR https://github.com/OpenModelica/OpenModelica/pull/12428 basically does that `Package1.Example and Package2.Example` are built under the same directory named `Example`, but the final fmu's will be generated with fully Qualified name example `Package1.Example.fmu` and `Package2.Example.fmu`, which should not be a problem , the only problem I see is if we do parallel execution,  but other than that shortening the temp directory path should solve the maximum path issue unless someone has a very big model name

**Comment by casella** [comment]
I would suggest a few small changes:
- Instead of building under Example, make a (short, e.g. 4 characters) hash code from the fully qualified name and use that as directory name (i.e. `34bf` instead of `Example`) That avoids name clashes when going parallel, and also keeps it very short
- When the compilation is done, name the FMU with just the model name, i.e. `Example` (otherwise you get impossibly long file names), but copy it in the sub-directory of the OMEdit working directory named as the fully qualified name (e.g. `Package1.Example`)
- Unless the "delete intermediate compilation files" option is disabled, delete the hash-code-named directory `34bf`.

What do you think?

**Comment by arun3688** [comment]
@casella After some discussion with Adeel we now have some short path and we hope it should fix most of the cases, and now we should surely get rid of around 30 to 40 chars depending on `hierarchy`  and this commit should fix this 26c8457070bee5ca78116392cb3cc8e8aa5ed18d. And it is not exactly like what you said just using 4 charcters from hash, Adeel suggested to use modelName suffix with hash eg. `Examplea134` so that it supports parallelization and based on some testing big models it worked for me, If needed we can still reduce the Temp Directory path and it is possible. 

@Primkins You can test it from the nightly builds tomorrow

**Comment by casella** [comment]
The idea of tmp4de3 was that some models may have a long name, but it's OK anyway, let's see how it goes. Maybe if the model name is longer than, say, 15 characters, you could shorten it somehow. At the end of the day it's just a temp directory, only useful if you want to debug the generated code.

**Comment by arun3688** [comment]
@casella that is true having `tmp4de3` is much better because there is nothing to debug in the temp directory and users are only interested in generated fmu, We will see how it goes and if some users again report long path issue we can eliminate the modename prefix and only have the hash code

**Comment by casella** [comment]
@arun3688 would you mind porting this to the maintenance/v1.23 branch?

**Comment by casella** [comment]
Ported to maintenance/v1.23 by #12510.
