### ISSUE TITLE
Component within a model should not be instantiated with composite name

### ISSUE THREAD

**Issue by gwr69** [OpenModelica/OpenModelica#12187]
### Description

Comparing with the behaviour in Wolfram System Modeler v14 and considering my understanding of name lookup rules, e.g., Modelica Specification [Section 5.3.2](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup) a non-encapsulated component within a class that is not a package or an operator should be instantiated with its name and not its composite name.

### Steps to Reproduce

Consider the following model:

```modelica
model InstantiationExample
    block MyBlock
        extends Modelica.Blocks.Icons.Block;
    end MyBlock;
end InstantiationExample;
```

Then instantiate the class `MyBlock` by dragging and dropping the Icon shown in Libraries window onto the Diagram for `model InstantiationExample`.
It will be instantiated as:

```
InstantiationExample.MyBlock <componentName>;
```

### Expected Behavior

Following the lookup rules I would expect the instantiation within `model InstantiationExample` to have the form:

```
MyBlock <componentName>;
```

### Version and OS

 - OpenModelica Version: `v1.23.0-dev-416-g0f1ee9aef5 (64bit)`
 - OS: `Windows 10, 64 bit`
 - `MSL 4.0.0`

### Additional Context

Issue popped up when examining #12184

**Comment by casella** [comment]
The full path declaration is not wrong per se, but it is true that there is no need to specify the full path, since MyBlock is defined within the scope of class InstantiationExample.

@adeas31 can you change the drag-n-drop mechanism so we get a relative path instead of a fully qualified one?
