### ISSUE TITLE
Incompatible connection false error on first file load

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#12188]
### Description

False error on connector compatibility. 

### Steps to Reproduce
Files:
[Connection_error.zip](https://github.com/OpenModelica/OpenModelica/files/14855646/Connection_error.zip)

Procedure:
1-Start OMedit
2-Load Cable.mo
3-Load Test_2.mo
4-Try to connect wrold.frame_b with cable.frame_a. The following message appears:
<img width="553" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/1c24f816-d8d7-47fa-b860-c00f5120e49d">
5-Delete cable icon from Test_2 model
6-Drag 'n drop cable component to the model
7-Try to connect wrold.frame_b with cable.frame_a. Now works!

### Expected Behavior

It should work on the first try.

### Version and OS

 - OpenModelica Version: OM v1.23.0-dev-353-g2e82712898
 - OS: e.g. Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3

**Comment by adeas31** [comment]
If you swap cable and world in `Test_2` then it works fine. But this shouldn't be the case. Somehow the instance API dumps differently.

I talked with @perost and he will take a look at it.

**Comment by casella** [comment]
Thank you @perost! Today while working with @arun3688 I stumbled upon the same problem. Good that it's been solved.

@arun3688 please try with tomorrow nightly build if you can make the connections of our propeller test model graphically.
