### ISSUE TITLE
Copy and paste of Diagram annotation elements removes previously stored elements

### ISSUE THREAD

**Issue by gwr69** [OpenModelica/OpenModelica#12192]
### Description

If one copies a graphical element from one model's diagram D1 into another model's diagram D2, the diagram D2 will correctly show the newly added graphical element and the previously present elements but inspection of the Modelica code in Text View will reveal that by copying the `Diagram` annotation has been replace by one containing only the added elements. Reloading the class will then reveal that previously present content has been "erased."

### Steps to Reproduce

Consider the following `package`:

```
package DiagramAnnotationError
  model Diagram1
  equation

  annotation(
      Diagram(graphics = {Rectangle(origin = {-3, 39}, extent = {{-47, 29}, {47, -29}}), Text(origin = {-20, -26}, extent = {{-30, 12}, {30, -12}}, textString = "Some text")}));
end Diagram1;
  
  model Diagram2
  equation
  
  annotation(
      Diagram(graphics = {Rectangle(origin = {-3, 39}, extent = {{-47, 29}, {47, -29}})}));
  end Diagram2;
end DiagramAnnotationError;
```

Here `model Diagram1` contains a rectangle and text, while `model Diagram2` only contains a rectangle in the diagram layer.
Now:

1. Go to the Diagram View of `Diagram1`, right-click upon the text and select `copy`.
2. Go to the Diagram View of `Diagram2`, right-click to `paste` the text into the diagram layer.
3. Save `model Diagram2`.
4. Go to Text View for `model Diagram2` and right-click to unfold all.

The code will then show the following annotation:

```
annotation(
    Diagram(graphics = {Text(origin = {-20, -26}, extent = {{-30, 12}, {30, -12}}, textString = "Some text")}));
``` 

### Expected Behavior

1. The `graphics` collection within the `Diagram` annotation of `model Diagram2` should consist of a _union_ of the previously present content (e.g., the `Rectangle`) and the newly added `Text` element.
2. Diagram View for `model Diagram2` should never show content that is not in fact present in the Modelica code for that model, i.e., Text View and Diagram View should be strictly synchronized at all times.

### Version and OS

 - OpenModelica Version: ` v1.23.0-dev-416-g0f1ee9aef5 (64-bit)`
 - OS: `Windows 10, 64 bit`

**Comment by adeas31** [comment]
@perost `loadClassContentString` API replaces the annotation element instead of merging it.

**Comment by perost** [comment]
> @perost `loadClassContentString` API replaces the annotation element instead of merging it.

Ok, I can take a look next week. Do you have an example of how the API is called in this case?

**Comment by adeas31** [comment]
`loadClassContentString("annotation (Diagram(graphics={Text(origin={-20,-26},extent={{-30,12},{30,-12}},textString="Some text")}));",DiagramAnnotationError.Diagram2)`

**Comment by perost** [comment]
> `loadClassContentString("annotation (Diagram(graphics={Text(origin={-20,-26},extent={{-30,12},{30,-12}},textString="Some text")}));",DiagramAnnotationError.Diagram2)`

What's the expected behaviour here? Should be old and the new `graphics` arrays just be concatenated?

**Comment by adeas31** [comment]
> > `loadClassContentString("annotation (Diagram(graphics={Text(origin={-20,-26},extent={{-30,12},{30,-12}},textString="Some text")}));",DiagramAnnotationError.Diagram2)`
> 
> What's the expected behaviour here? Should be old and the new `graphics` arrays just be concatenated?

Yes.

**Comment by perost** [comment]
> > > `loadClassContentString("annotation (Diagram(graphics={Text(origin={-20,-26},extent={{-30,12},{30,-12}},textString="Some text")}));",DiagramAnnotationError.Diagram2)`
> > 
> > 
> > What's the expected behaviour here? Should be old and the new `graphics` arrays just be concatenated?
> 
> Yes.

Ok,  #12249 adds a special case for array binding expressions in annotations. Please try it out and see if that works for you.

**Comment by perost** [comment]
I'm reverting #12249 since it caused duplicate annotations when OMEdit adds annotations, because OMEdit merges annotations before adding them. We can do the same thing when pasting annotations to avoid having to complicate the API.

**Comment by adeas31** [comment]
Ported to maintenance/v1.23 with PR #12256
