### ISSUE TITLE
Handle uses annotations correctly when duplicating to/from the global scope

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12230]
#8174 and #12218 took care of adding a uses annotation to a package when duplicating a class with dependencies into it. 

As pointed out by @abuntrock, if the class is duplicated in the global scope, the uses annotation should be added to the duplicated model instead.

I would also add that when need to make sure that if such a top-level model is duplicated into a package, its uses annotations are propagated to that package.

**Comment by abuntrock** [comment]
I tested duplicating a model to global scope and the uses annotation is correctly added. Thanks a lot.

**Comment by casella** [comment]
@adeas31 can you please add to maintenance/v1.23?

**Comment by adeas31** [comment]
Ported to maintenance/v1.23 with PR #12256
