### ISSUE TITLE
Bad generation of synchronous code

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#12245]
### Description

A function called:
`CRML_test_Spec_doc_ClockConstructors_ClockConstructors_verif_functionEquationsSynchronous_system_1_0` is called but a function `CRML_test_Spec_doc_ClockConstructors_ClockConstructors_verif_functionEquationsSynchronous_system_0_0` is generated in the code:

```
/usr/bin/ld: CRML_test.Spec_doc.ClockConstructors.ClockConstructors_verif_15syn.o: in function `CRML_test_Spec_doc_ClockConstructors_ClockConstructors_verif_function_equationsSynchronous':
CRML_test.Spec_doc.ClockConstructors.ClockConstructors_verif_15syn.c:(.text+0x1a9): undefined reference to `CRML_test_Spec_doc_ClockConstructors_ClockConstructors_verif_functionEquationsSynchronous_system_1_0'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [CRML_test.Spec_doc.ClockConstructors.ClockConstructors_verif.makefile:37: omc_main_target] Error 1
```

## Reproduce

Get the code: 

`git clone https://github.com/lenaRB/crml-compiler`

and run script: s.mos via:

`omc --std=3.5 s.mos`

```mo
// s.mos
loadModel(Modelica, {"3.2.3"}); getErrorString();
prev := cd();
cd("crml-compiler/resources/modelica_libraries"); getErrorString();
loadFile("CRML.mo"); getErrorString();
loadFile("CRMLtoModelica.mo"); getErrorString();
loadFile("CRML_test/package.mo"); getErrorString();
cd(prev); getErrorString();
simulate(CRML_test.Spec_doc.ClockConstructors.ClockConstructors_verif); getErrorString();
```

I have looked a bit into how the code is generated in the templates and I cannot find any fault there (well except that clocked partitions are traversed multiple times to generate the function code and then again to generate the function call).

**Comment by perost** [comment]
I have no clue how it should work, but if just skipping them is valid then maybe they shouldn't be generated in the first place?

**Comment by adrpo** [comment]
@perost I changed the code to do that (basically getting rid of the else part here):
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/SimCode/SimCodeUtil.mo#L995
and will make the commit in the PR to see if it breaks anything.

**Comment by adrpo** [comment]
TODO: add a test with the model given here.
