### ISSUE TITLE
No .ddl file in exported FMU model from OpenModelica

### ISSUE THREAD

**Issue by Shenris** [OpenModelica/OpenModelica#12258]
Hello everyone (forgive me if it is a trivial issue, i am new to FMU),

I am currently working on Co-simulation using FMU models. I would like to export an OpenModelica file in FMU file and co-simulate it with a Simulink Model that is also a FMU file.

However, when i try to run my co-simulation, i get the following message : Error:Error in supplied FMU: Unable to load dynamic library 'C:\Users\Léo nicolle\OneDrive\Bureau\IMT Mines Ales\Mission R&D\Modele_Commande_Moteur_CC_fmu55\slprj_fmu\95fff6f236f38c45451bf5be6e80e1a6\MoteurCC\binaries\win64\MoteurCC.dll': specified module could not be found. For more information, see the FMU troubleshooting documentation.

I understood that Simulink could not find the file 'MoteurCC.dll' and after looking in the FMU, i found that there is no .dll file !

I made some research on the OpenModelica website and through the example 'BouncingBall.fmu' exportation, a .dll file appears in their exported file.

Can you please help me ? Best regards, Leo

I tried to export my OpenModelica file to FMU file but there is no .dll file in it so i think it can not be runned on Simulink.

Edit : After advices from users on StackOverFlows, i tried to move my file to different folder where there is no special character like 'é' or OneDrive but i still get the same issue on Simulink and my fmu file still does not have .dll file 

Edit : After reading on the internet to put Solver for Co-simulation on Euler explicit, i have .dll file generated in my fmu folder but i still get the same issue on Simulink...

**Comment by casella** [comment]
It could be due to long pathnames and/or accented letters in your path. Where is the FMU located?

**Comment by Shenris** [comment]
My FMU is located : C:\Users\Public\MoteurCC. First, i had my FMU located in a file where i have special caracters but i changed it to this file and the problem is still here...

**Comment by casella** [comment]
The other questions are: what is the version of OMC you are using? Have you tried the latest nightly build?

**Comment by Shenris** [comment]
Yes, i installed the latest version of OMC on my computer

**Comment by AnHeuermann** [comment]
@Shenris please provide a way for us to reproduce the issue and show us the full log from creating the FMU and the error message from simulating the FMU.

**Comment by Shenris** [comment]
In fact, i installed the lastest nightly build on my laptop and the problem is now fixed...Maybe i made some mistakes when i downloaded OM i don't know. But when i try to run my FMU file from OpenModelica on Simulink, i don't get exactly the same output than i get on OpenModelica : any thoughts on what this could be due ?( i have modeled a motor CC with resistor, inductance and inertia and i want to vizualize inertia speed as an ouput)

**Comment by casella** [comment]
> But when i try to run my FMU file from OpenModelica on Simulink, i don't get exactly the same output than i get on OpenModelica : any thoughts on what this could be due ?( i have modeled a DC motor with resistor, inductance and inertia and i want to vizualize inertia speed as an ouput)

Please open another ticket on this topic. It would be great if you could post the model and the results.

One possible explanation is that OMC uses Tolerance = 1e-6 by default, while Simulink uses 1e-3. Could that be the cause.
