### ISSUE TITLE
Recompilation when parameter is part of an if condition

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12262]
### Description

This issue is more like a question and wish.
Parameters, which are used in the definition equation of an if condition, cannot be changed and resimulated without recompilation. This is the case, even if the change does not affect the used if branch. Dymola is also not able to handle this but for example SimulationX is able to, so there at least seems a way to allow this. I do not know if this is totally out of scope with the current OMEdit backend setup or not.

### Steps to Reproduce

1. Consider the following modelica model:

```modelica
model RecompilationIfCondition

  parameter Real simpleParam = 5;
  parameter Real paramInEqualCondition = 10;
  parameter Real paramInLowerCondition = 10;

  Real result1;
  Real result2;
  Real result3;

equation
  result1 = time*simpleParam;

    if Modelica.Math.isEqual(paramInEqualCondition,0.0,Modelica.Constants.eps) then
      result2 = time;
    else
      result2 = time*2;
    end if;

    if paramInLowerCondition < 10 then
      result3 = time;
    else
      result3 = time*2;
    end if;

end RecompilationIfCondition;
```
2. Instantiate the model in a new class and simulate this new class.
3. In the variable browser there is no edit possibility for `paramInEqualCondition` and `paramInLowerCondition` just for `simpleParam`.

### Desired Behavior

`paramInEqualCondition` and `paramInLowerCondition` can be changed without a recompilation.

### Version and OS

 - OpenModelica Version: 1..2.3 and v1.24.0-dev-9-g3bdce2a898 (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking at that
Aaron Buntrock - Bosch Rexroth

**Comment by perost** [comment]
You can put `annotation(Evaluate=false)` on those parameters to tell the compiler that you would like to keep them unevaluated if possible.

**Comment by abuntrock** [comment]
I assumed that `Evaluate=false` was the default. Thanks for the clarification, I should have tried this out myself beforehand

**Comment by casella** [comment]
`Evaluate = false` is the default for non-structural parameters 😃

**Comment by perost** [comment]
> `Evaluate = false` is the default for non-structural parameters 😃

The default is really no `Evaluate` at all, setting `Evaluate=false` on a parameter will make the compiler try extra hard to not evaluate it (but it might still evaluate it if absolutely necessary).
