### ISSUE TITLE
Regression issues with final modifiers in constrainedby clause

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12313]
### Description

This is basically a sibling ticket of another regression #11964. Final modifiers within `constrainedby` clauses were last respected for the GUI experience in OMEdit 1.22.0 after they were fixed for ticket #10814.

### Steps to Reproduce
Follow the steps in #10814.

### Expected Behavior

Modifiers applied to the constraining clause should be respected in the parameter dialog for each choice. A final modifier in the constrainedby clause lets the modified parameter disappear when opening any choice via the edit button.

### Screenshots

 - OpenModelica Version: Since 1.22.1
 - OS: Windows 10, 64 bit

Thanks for looking into this
Aaron Buntrock

**Comment by adeas31** [comment]
Fixed and ported to 1.23 #12326

**Comment by abuntrock** [comment]
Thanks a lot

**Comment by abuntrock** [comment]
Looks perfect with today's nightly. Thanks a lot.
