### ISSUE TITLE
Change the default of -gbint option of GBODE to dense_output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12321]
As we checked while preparing a paper on the multirate algorithm, the `-gbint=dense_output_ctrl` default option for the multirate integration when dense output is available is way too conservative and leads to unnecessarily short global steps, sapping the multirate performance.

The default option should be changed to `-gbint=dense_output` in that case.

We should probably also improve the way -gbint=dense_output_ctrl works, but that's the topic for another ticket.

**Comment by bernhardbachmann** [comment]
This is fixed (see #12323)
