### ISSUE TITLE
FMU Export Issue

### ISSUE THREAD

**Issue by Primkins** [OpenModelica/OpenModelica#12324]
### Description

Unable to export the FMU.

```
model BangBang2021 "Model to verify that optimization gives bang-bang optimal control"
   parameter Real m = 1;
   parameter Real p = 1 "needed for final constraints";
   Real a;
   Real v(start = 0);
   Real pos(start = 0);
   Real pow(min = -30, max = 30) = f * v annotation(isConstraint = true);
   input Real f(min = -10, max = 10);
   Real costPos(nominal = 1) = -pos "minimize -pos(tf)" annotation(isMayer=true);
   Real conSpeed(min = 0, max = 0) = p * v " 0<= p*v(tf) <=0" annotation(isFinalConstraint = true);
equation
   der(pos) = v;
   der(v) = a;
   f = m * a;
annotation(experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-07, Interval = 0.01),
__OpenModelica_simulationFlags(s="optimization", optimizerNP="1"),
__OpenModelica_commandLineOptions="+g=Optimica");
end BangBang2021;

```

It shows the below error.

```
[2] 18:05:23 Translation Error
Template error: A template call failed (C:\Program Files\OpenModelica1.24.0-dev-64bit\bin\OMEdit.exe: [unknown function name]). One possible reason could be that a template imported function call failed (which should not happen for functions called from within template code; templates assert pure 'match'/non-failing semantics).

```

OpenModelica Version: OpenModelica v1.24.0-dev-43-gc0911cda2e (64-bit)
OS: Windows 11, 64 bit

**Comment by casella** [comment]
@Primkins I guess you can't export an _optimization_ problem as FMU. FMUs are only defined for simulation, they have no provision to accommodate constraints and objective function.

Do I miss something?

**Comment by Primkins** [comment]
Able to generate the FMU with the below code:

```
model BatchReactor1Arr
  Real x[2](start = {1,0}, each fixed = true, each min = 0, each max = 1);
  //Real x2(start = 0, fixed = true, min = 0, max = 1)annotation(isMayer=true);
  input Real u(min = 0, max = 5);
equation
  der(x[1]) = -(u + u^2/2)*x[1];
  der(x[2]) = u*x[1];
annotation(experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-07, Interval = 0.01),
__OpenModelica_simulationFlags(s="optimization", optimizerNP="1"),
__OpenModelica_commandLineOptions="+g=Optimica", objective=-x[2]);

end BatchReactor1Arr;
```

Not sure why it is not working for BangBang2021 example.

**Comment by casella** [comment]
The fact that the export is successful doesn't necessarily mean much. What are you trying to accomplish with an optimization FMU (assuming that actually means something)?

**Comment by Primkins** [comment]
Thought that the OMSimulator handles the Optimization problems. I want to check the FMU in OMSimulator with Python interface.

**Comment by casella** [comment]
OMSimulator only handles _simulations_, the main reason for that being that the FMI standard does not have provisions for embedded optimization. Yes, you can use FMUs to do optimization, but they only provide the system equations, they cannot handle constraints and objective function, there are no API functions for that.

If you want to check the model before starting its optimization, you can write Modelica code for the model (which can be exported as FMU and simulated with OMSimulator), and the extend it by adding the optimization-specific features.
