### ISSUE TITLE
Make $ variables protected (was: Additional TopLevel variables when ignoring HideResult and Protected )

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#12341]
### Description

OMEdit sometimes adds top level variables to the variable browser when ignoring `HideResult` and `Protected` during simulation.

### Steps to Reproduce

1. Simulate the `Modelica.Blocks.Examples.SinCosEncoder` with the two following flags activated.
- `Protected Variables if not encrypted`
- `Ignore HideResult`
2. Inspect the variable browser. Five additional top-level variables are added to the variable browser compared with the two flags deactivated. They are named `$cse1` to `$cse5`. I could not find anything corresponding to this in the text view. Since those variables also have no description string, they do not add any value for me as a user in my opinion.
4. It seems to depend on the equation system. When simulating `Modelica.Blocks.Examples.PID_Controller` with the flags activated, no new top-level variables are added.
5. With our BRSL I was also able to create additional top-level variables called `$whenCondition1` with ascending numbers at the end. Their description string is always some if condition from the text view. I was not able to reproduce this issue with MSL components, which also contain similar if conditions. 

### Expected Behavior

Only things present in the simulated model (text view) are written to the variable browser.

### Version and OS

 - OpenModelica Version: v1.24.0-dev-52-g60c2b6efbd (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

### Additional Context

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@abuntrock all variables starting with $ are auxiliary variables added by the backend, e.g. for common subexpression elimination or when-equation conditions. They are referred to in the debugger, so they can be useful for debugging, but most certainly not for regular successful simulations. I guess we should make them automatically protected, so that they are only shown if protected variable output is optionally activated.

I don't see any IP problem with them, as their names are obfuscated by construction 😄

**Comment by abuntrock** [comment]
Thanks for the explanation.
Aren't they already protected since I can only see them in the variable browser when simulating with the flag `Protected Variables if not encrypted`?

**Comment by casella** [comment]
@abuntrock , sorry, I hadn't read your ticket description carefully enough. This is actually the intended behaviour: those variables are protected but they may be interesting for debugging, as they are referenced by the debugger, so they are shown on purpose when you output the protected variables. Is that a problem for you?

**Comment by abuntrock** [comment]
Apparently, I am just not using the debugger enough. Since those variables have a use case and are not in the variable browser by accident, I will close this issue as not planned.

**Comment by casella** [comment]
OK. BTW, if you ever wonder what those `$cse` variables correspond to, you can use the debugger and find out, since they all have a defining assignment in the regular equations.
