### ISSUE TITLE
Add Ubuntu 24.04 build instructions and build-deps.

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#12347]
### Description

A new Ubuntu LTS version was released. Since this is one of the most used Linux distribution we should support it soon.
To do so we can add build-deps and update one of the test machines to Ubuntu Nobel.

Currently I fail to install the build deps.

### Steps to Reproduce

Following the build instructions for the latest Ubuntu LTS https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md#11-debianubuntu will result in an error.

```
> sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu noble-security InRelease
Ign:5 https://build.openmodelica.org/apt noble InRelease
Ign:6 https://build.openmodelica.org/apt nightly InRelease
Err:7 https://build.openmodelica.org/apt noble Release
  404  Not Found [IP: 192.36.54.112 443]
Hit:8 https://build.openmodelica.org/apt nightly Release
Reading package lists... Done
E: The repository 'https://build.openmodelica.org/apt noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Expected Behavior

Have the build dependencies and at least one release available.
Be able to build on Ubuntu Nobel.

### Version and OS

 - OpenModelica Version: Latest master
 - OS: Ubuntu 24.04 LTS (on WSL)

**Comment by AnHeuermann** [comment]
By the way our build instruction in  https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md#11-debianubuntu are no longer up to date. See https://github.com/OpenModelica/OpenModelica/pull/12398.

**Comment by AnHeuermann** [comment]
With

*/etc/apt/sources.list.d/openmodelica.list*
```                                                                                               
deb [arch=amd64 signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] https://build.openmodelica.org/apt noble nightly
deb-src [arch=amd64 signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] https://build.openmodelica.org/apt noble nightly
```

I was able to build OpenModelica on Ubuntu Noble.

**Comment by casella** [comment]
Thanks!
