### ISSUE TITLE
Handling of time units in OMEdit is broken

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12352]
Please try to simulate the following MWE
```modelica
model LongSimulation
  Real x;
equation
  2e5*der(x) = 1 -x;
annotation(
    experiment(StartTime = 0, StopTime = 1e6, Tolerance = 1e-06, Interval = 1000));
end LongSimulation;
```
The plots have a wrong unit on the time scale (which should be Ms), as well as the results under the mouse pointer

![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/30569975-1010-4495-a9d7-9446dab1275f)

This is what I get with the latest nightly build, I am not sure if the regression was introduced before branching 1.23.0, please also check that.

**Comment by casella** [comment]
OK, so that was also ported to maintenance/v1.23. Imperative to fix it before the beta release 😅

**Comment by casella** [comment]
LGTM. Please cherry-pick to maintenance/v1.23 and close the ticket.

**Comment by adeas31** [comment]
Ported to maintenance/v1.23 with #12393.
