### ISSUE TITLE
Parametric plot crashing OMEdit or giving unpredictable results

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12375]
### Steps to Reproduce
0. to reproduce EHPTLib (experimental OM system library) must be installed
1. Load [Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/15201808/Test.mo.txt)

2. open and run AllSpeeds 
3. open a parametric plot
4. choose as x variable smpm1.wMechanical and as y variable uDC.y.

When I do this I get either a crash or crazy plots, such as: 
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/548a8726-0b8e-4edf-a467-7ab7ec32cebf)

![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/af7d6ceb-ce56-441f-a5a8-eaba3d035ed6)

They are both unreasonable, since uDC is constantly equal to 300, whatever the value of smpm1.wMechanical.

Tested with 1.23 dev-373 (win 64) and  1.24-dev-60 (Ubuntu)

**Detailed procedure giving always a crash under 1.23 dev-373 (win 64)** 

1. Load Test
2. open and run AllSpeeds 
3. close plot window
4. open diagram window (while still in Plotting perspective)
5. open a parametric plot
6. choose as x variable smpm1.wMechanical and as y variable uDC.y.
=> CRASH

**Comment by adeas31** [comment]
Probably related to #12352 but I will investigate more on Monday.

**Comment by adeas31** [comment]
We did not handle the parameters properly for parametric plots. Should work fine now with #12378.

**Comment by adeas31** [comment]
Ported to maintenance/v1.23 with #12393.

**Comment by ceraolo** [comment]
> We did not handle the parameters properly for parametric plots. Should work fine now with #12378.

Thank you.
I will check this as soon as the update is available in Ubuntu (this morning it was not).

**Comment by casella** [comment]
@ceraolo we had some issues with the Linux nightly builds but they should be resolved now

**Comment by ceraolo** [comment]
Good result.
Thank you
