### ISSUE TITLE
Opening and ending tag mismatch

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12386]
See discussion #11253, sometimes one gets multiple error messages in the OMEdit Message Browswer with the text: Opening and ending tag mismatch. This is likely due to malformed XML code being parsed by OMEdit.

@MohammadHadiAlizadeh sent a test case to @adeas31, who will look into that.

**Comment by bilderbuchi** [comment]
We are also seeing this in some cases, also at some time in the middle of simulation, but I don't have a good/small reproducer.

**Comment by casella** [comment]
I also saw that many times, and I originally thought (for some reason) that it was a solver issue - that's why I initially asked @AnHeuermann. Let's see if @adeas31 can figure out where is the root cause.

**Comment by adeas31** [comment]
Should work fine now with #12391. @MohammadHadiAlizadeh thanks for the test model.

There might be more issues like this in the logging. I talked with @AnHeuermann and he has some ideas to check and match that the message tags are properly opened and closed. @casella maybe you can open another enhancement ticket for it.

**Comment by adeas31** [comment]
Ported to maintenance/v1.23 with #12393.
