### ISSUE TITLE
Cherry-pick latest FMU extensions to 1.23.0

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12383]
@rfranke, we branched off 1.24.0 on Apr 10 morning, sorry for not updating the download page accordingly. I checked [your commits to master](https://github.com/OpenModelica/OpenModelica/pulls?q=closed%3A2023-11-15..2024-05-06+is%3Aclosed+author%3Arfranke+) after that:

- #12303 including aa4ec47 and ccf35b3
- #12348 including e432e78

We should cherry-pick those three commits to maintenance/v1.23

@adeas31 could you please take care of that?

**Comment by rfranke** [comment]
Done with #12385.

**Comment by casella** [comment]
Thanks @rfranke!
