### ISSUE TITLE
OMEdit Create Connector does not work anymore

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#12380]
### Description

OMEdit has the feature of creating new connectors when drawing a connection line. This appears to be broken.

### Steps to Reproduce

Open `Modelica.Blocks.Examples.Filter` (or a duplicate of it to be editable). 

- Click on the output of e.g. `CriticalDamping` and hold the mouse button down
- Draw a connection line
- Release the left mouse button and press the right mouse button
- Select "Create Connector" -- nothing happens

### Expected Behavior

An output connector should be created in the model diagram.

### Version and OS

 - OpenModelica Version:  v1.22.3 (64-bit)
 - OS: Windows 11
 - MSL 4.0.0

**Comment by adeas31** [comment]
See #12163. This is already fixed for 1.23.

**Comment by rfranke** [comment]
Yes, can confirm it with the current dev version.
