### ISSUE TITLE
Connection dots hide negative pins

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12399]
### Description
Connection dots in electric circuits should not be drawn when a wire directly connects to a pin.
Consider the model [Dot.mo.txt](https://github.com/OpenModelica/OpenModelica/files/15254706/Dot.mo.txt). It has the following diagram.
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/afbe458c-0e19-4ba3-a696-9a8743eecaf6)
The power meter P seems to be lacking the negative pin, that hinders the ability to evaluate the correct direction of power flow. Indeed the connection between therminal P.pv and P.nc nearly completely hides P.nc, which does not appear to have white interior (except if one looks inside very closely).

I think that connection dots should not be drawn when a wire connects directly into a pin.

### Version and OS

1.24.0-dev-70

**Comment by casella** [comment]
@ceraolo please check on the next nightly build

@adeas31 please cherry-pick to 1.23.0 ASAP, so we can proceed with the beta release.

**Comment by adeas31** [comment]
Cherry picked to 1.23 with #12431
