### ISSUE TITLE
Error in NSimVar.SimVars.splitByType when compiling models with when algorithm and enumeration types with the NB

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12409]
Following #12239, [PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad](https://libraries.openmodelica.org/branches/newInst-newBackend/PowerGrids/files/PowerGrids_PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad.err) fails with:
```
Error: Internal error NSimVar.SimVars.splitByType failed because of unhandled Variable transmissionLine.breakerStatus.
```
The problem can be replicated with this much simpler MWE:
```modelica
model TestEnumerationWhen
  type T = enumeration(off, on);
  T t(start = T.off, fixed = true);
algorithm
  when t == T.off and time > 0.4 and time < 0.6 then
    t := T.on;
  elsewhen t == T.on and time > 0.8 then 
    t := T.off;
  end when;
end TestEnumerationWhen;
```
which fails with
```
[2] 16:42:06 Translation Error
Internal error NSimVar.SimVars.splitByType failed because of unhandled Variable t.
```

**Comment by phannebohm** [comment]
The model `TestEnumerationWhen` is not translated correctly. The when-condition in the generated code looks something like this:
```C
if (0) {
  ...
} else if (0) {
  ...
}
```
Not sure why.

Anyway, the issue mentioned is fixed.

**Comment by casella** [comment]
I just opened follow-up #12423.
