### ISSUE TITLE
how to generate the mo-file from a tpl-file with omc.exe

### ISSUE THREAD

**Issue by pily1** [OpenModelica/OpenModelica#12402]
how to generate the mo-file from a tpl-file with omc.exe?
when I use the following command,
"omc.exe -s  E:\work\openModelica\paper.tpl  paper.mo",
it reports a error,
Error processing file: E:\work\openModelica\paper.tpl
# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed

**Comment by perost** [comment]
It's just `omc.exe E:\work\openModelica\paper.tpl`, which will generate the MetaModelica code in `paper.mo`. `-s` is for generating simulation code for a model and doesn't apply to Susan template files.

**Comment by pily1** [comment]
I tried use the command "omc.exe E:\work\openModelica\paper.tpl"
it reports a error
Processing file 'E:\work\openModelica\paper.tpl'

Susan parse error(s):
E:\work\openModelica\paper.tpl:7.18-7.18 Error:(parser)No such file 'paperI.mo'.(col 18)
paperI.mo:1.1-1.1 Error:(parser)Expected keyword 'interface' at the position.(col 1)

### translation of file 'E:\work\openModelica\paper.tpl' failed!  ###
### Error Buffer ###

### End of Error Buffer ###
Error processing file: E:\work\openModelica\paper.tpl
# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed!

**Comment by pily1** [comment]
I tried use the command "omc.exe E:\work\openModelica\paper.tpl"
it reports a error
Processing file 'E:\work\openModelica\paper.tpl'

Susan parse error(s):
E:\work\openModelica\paper.tpl:7.18-7.18 Error:(parser)No such file 'paperI.mo'.(col 18)
paperI.mo:1.1-1.1 Error:(parser)Expected keyword 'interface' at the position.(col 1)

### translation of file 'E:\work\openModelica\paper.tpl' failed!  ###
### Error Buffer ###

### End of Error Buffer ###
Error processing file: E:\work\openModelica\paper.tpl
# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed!

**Comment by pily1** [comment]
I change to the same folder,I use the command "omc.exe paper.tpl",it reports a error
Processing file 'paper.tpl'

Susan parse error(s):
paper.tpl:7.18-7.18 Error:(parser)No such file 'paperI.mo'.(col 18)
paperI.mo:1.1-1.1 Error:(parser)Expected keyword 'interface' at the position.(col 1)

### translation of file 'paper.tpl' failed!  ###
### Error Buffer ###

### End of Error Buffer ###
Error processing file: paper.tpl
# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed!

when I use a other tpl file,I use the command "omc.exe SusanDump.tpl",it reports a error
Processing file 'SusanDump.tpl'

Susan parse error(s):
SusanDump.tpl:2.1-2.1 Error:(parser)Expected keyword 'package' at the position.(col 1)

### translation of file 'SusanDump.tpl' failed!  ###
### Error Buffer ###

### End of Error Buffer ###
Error processing file: SusanDump.tpl
# Error encountered! Exiting...
# Please check the error message and the flags.

Execution failed!

**Comment by perost** [comment]
> paperI.mo:1.1-1.1 Error:(parser)Expected keyword 'interface' at the position.(col 1)

Does the file start with `interface package paperI` as it should?

> Susan parse error(s): SusanDump.tpl:2.1-2.1 Error:(parser)Expected keyword 'package' at the position.(col 1)

Same here, does the file start with `package SusanDump`?

**Comment by pily1** [comment]
I tried a another tpl file,I use the command "omc.exe test.tpl",it reports no error,
it print Processing file 'test.tpl',I searched my computer,but I cann't find the test.mo file

**Comment by pily1** [comment]
maybe the SusanDump.tpl and paper.tpl grammer is wrong

**Comment by perost** [comment]
> I tried a another tpl file,I use the command "omc.exe test.tpl",it reports no error, it print Processing file 'test.tpl',I searched my computer,but I cann't find the test.mo file

You can try with one of the existing template files in [OMCompiler/Compiler/Template](https://github.com/OpenModelica/OpenModelica/tree/master/OMCompiler/Compiler/Template), e.g. `omc CodegenC.tpl`. This should give the output:
```
Processing file 'CodegenC.tpl'

Susan parsing successful.

Writing result to file 'CodegenC.mo'
```

**Comment by pily1** [comment]
think you very much,I follow your instruction，now I can generate mo-file with tpl-file
