### ISSUE TITLE
FTBFS with gcc 14

### ISSUE THREAD

**Issue by jschueller** [OpenModelica/OpenModelica#12432]
### Description

latest openmodelica fails to build from source with gcc 14.1:
```
OMCompiler/3rdParty/FMIL/ThirdParty/Minizip/minizip/zip.c:1249:28: error: assignment to ‘const long unsigned int *’ from incompatible pointer type ‘const z_crc_t *’ {aka ‘const unsigned int *’} [-Wincompatible-pointer-types]
 1249 |         zi->ci.pcrc_32_tab = get_crc_table();
```

### Steps to Reproduce

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DOM_USE_CCACHE=OFF -DOM_OMEDIT_ENABLE_QTWEBENGINE=ON -B build .
        make -C build
```

### Expected Behavior

build succeeds

### Version and OS

 - OpenModelica Version: 1.22.4
 - OS: archlinux

**Comment by perost** [comment]
This was fixed a while ago with OpenModelica/OMCompiler-3rdParty#158, you may need to update the submodules if you're using an old checkout of OM:
```
git pull --recurse-submodules && git submodule update --recursive
git submodule foreach --recursive "git checkout master"
git submodule foreach --recursive "git pull"
```

**Comment by perost** [comment]
Ok, that would maybe be nice to fix, but I'm not sure how we could cherry-pick only that fix to the 1.22 maintenance branch since it's in a submodule. I guess we'd have to create a 1.22 maintenance branch also for OMCompiler-3rdParty?

@adrpo: Any thoughts?

**Comment by jschueller** [comment]
then it also fails in OMSimulator but I noticed it was fixed in https://github.com/OpenModelica/OMSimulator/pull/1295

**Comment by jschueller** [comment]
lets close it after https://github.com/OpenModelica/OMSimulator/pull/1300 is done

**Comment by bilderbuchi** [comment]
Why would you switch off that warning? Uninitialized use can be rather disastrous! 
Shouldn't you rather fix/update the involved 3rd-party dependency, or at least make sure compiler warnings for 3rd-party code are not erroring (IIRC using the [SYSTEM](https://cmake.org/cmake/help/latest/prop_tgt/SYSTEM.html#prop_tgt:SYSTEM) property)?
