### ISSUE TITLE
Add version header to Base Modelica output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12458]
Following the proposed [Base Modelica grammar](https://github.com/modelica/ModelicaSpecification/blob/MCP/0031/RationaleMCP/0031/grammar.md), the first line of the Base Modelica output should contain a version header line. For the time being I would add
```
//! base 0.1.0
```
to the first line of the Base Modelica output, as shown in the Modelica Conference paper.

**Comment by perost** [comment]
Fixed by #12460.
