### ISSUE TITLE
Library information minor glitch

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12466]
### Steps to Reproduce
1) load system library EHPTlib (version number recognised as being 2.1.4) 
2) right click on "EHTPlib" icon and select "information". What we get is as follows:
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/22e165a5-84b3-481a-a893-8f9cfad93c45)
The libray name, even though it is not long, is shortened. Moreover, it cannot be read in full enlarging the window

### Expected Behavior
The name should be immediately fully visible.
Only in case of very long names, they can be compacted, but when enlarging the window the compaction must be reduced or eliminated

### Version and OS
OM 1.22.0-341 Win64

**Comment by casella** [comment]
I guess that depends on screen resolution, this is what I get on my laptop:
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/bc877045-6b9d-4748-9931-cea76d97de43)
Anyway, I think we can make the default size of this window a bit larger, @adeas31 can you please take care of that?

**Comment by ceraolo** [comment]
As i said, even enlarging the window won't enlarge the text. So, it is also a problem of text label size

**Comment by casella** [comment]
@adeas31 I would recommend you to try this with screens of different resolution, and make sure the implementation is as much as possible independent from that. Thanks!

**Comment by adeas31** [comment]
Ported this to maintenance/v1.23 https://github.com/OpenModelica/OpenModelica/pull/12507

**Comment by ceraolo** [comment]
Thanks!
