### ISSUE TITLE
Error connecting bus to RealInput

### ISSUE THREAD

**Issue by hcasperfu** [OpenModelica/OpenModelica#12471]
### Description
An error pops up when trying to connect a weather bus to a `RealInput`.

### Steps to reproduce
1. Open `Buildings.Examples.Tutorial.SimpleHouse.SimpleHouse2` in OMEdit.
1.1. Note that right now this model can simulate with OpenModelica with no problem.
2. Select `connect(weaBus.HDirNor, gaiWin.u)` in the graphics view and delete it.
3. Reconnect `weaBus` and `gaiWin.u` in the graphics view and select `HDirNor` in the pop up.
4. Get the error prompt "Connectors gain.u and weaBus.HDirNor are not compatible."

### Expected behavior
The connection should be successful without an error prompt.

### Version and OS
- Buildings https://github.com/lbl-srg/modelica-buildings/commit/9411156ec23a91f41e621713ef36b4febbe8e4ec.
- OpenModelica 1.24.0~dev-16-gaa27cc1.
- Ubuntu 20.04.3.

### Additional context
Following exactly the same steps in Dymola 2024x would not result in an error message.
First reported in https://github.com/lbl-srg/modelica-buildings/issues/3843, with different versions.

**Comment by perost** [comment]
Should be fixed by #12474.

The issue was that the potentially present variable (`weaBus.HDirNor`) didn't have a model associated with the connector element, but I'm not sure why. Maybe @adeas31 has some clue? But in that case we probably should just assume that the connectors are compatible anyway to avoid false negatives.

**Comment by adeas31** [comment]
Of course there is no model in that case. What you did is fine. We could also avoid checking of compatibility in case of expandable connectors.

**Comment by perost** [comment]
> We could also avoid checking for compatibility in case of expandable connectors.

We already do.

**Comment by casella** [comment]
Well, if a variable already exists in the expandable connector, and it is not of the right type, I guess we should give an error right away. Of course it there is nothing there, then we need to assume it will be added somewhere else and accept it.
