### ISSUE TITLE
 Modelica-Buildings Library (master): Simulation fails while Compiling.

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#12482]
**Description**

The solver fails to check, compile & simulate the system and throws many Translation Errors.
The following below listed models have same issues:

```
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.InletTemperaturePulse
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRatePulse100
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRatePulse50
Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.MassFlowRateStep100
Buildings.Templates.Components.Validation.PumpMultipleRecord
Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone
Buildings.Templates.Components.Validation.Pumps
Buildings.Templates.Plants.HeatPumps.Validation.AirToWater
```
On checking the model in OpenModelica leads to following errors/warnings:
```
1) Translation Error [Function Buildings.Fluid.Geothermal.Borefields.BaseClasses.Boreholes.BaseClasses.Functions.convectionResistanceCircularPipe not found in scope InternalHEXTwoUTube.
2) Internal error Instantiation of Buildings.Templates.Components.Validation.PumpMultipleRecord failed with no error message.
3) The Modelica code of this model is invalid, so the graphics cannot be displayed.
4) Translation Error: Internal error NFTyping.typeComponentSections got uninstantiated component m_flow_small
5) Could not evaluate structural parameter (or constant): datAll.VAV_1.coiHeaPre.wAirEnt_nominal which gives dimensions of array:sta.Array dimensions must be known at compile time.


```

**Steps to Reproduce**

Load the Modelica-Buildings master library (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html)
Simulate the examples model present in Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone

**Expected Behavior**

The simulation should compile successfully.

 **Version and OS**

- OpenModelica Version: OpenModelica 1.25.0~dev-112-gb8e50a4
- OS: Ubuntu 20.04 focal
    Versions of used Modelica libraries:
    Modelica 4.0.0
    Buildings 11.0.0

**Comment by casella** [comment]
@perost I checked the CI test report for [Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone.err), the NF complains it cannot evaluate some structural parameters, would you mind having a look?

**Comment by AndreaBartolini** [comment]
It seems to be related to https://github.com/OpenModelica/OpenModelica/issues/12305

**Comment by casella** [comment]
@deepak19015 please assign [Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone.err) to #12305 in your Excel records

**Comment by casella** [comment]
For Buildings.Templates.Components.Validation.PumpMultipleRecord, see #13114

**Comment by casella** [comment]
For `Buildings.Templates.AirHandlersFans.Validation.VAVMultiZone`, see #13115.

**Comment by casella** [comment]
For `Buildings.Templates.Components.Validation.Pumps`, see #13116.

**Comment by casella** [comment]
For Buildings.Templates.Plants.HeatPumps.Validation.AirToWater, see #13128.

**Comment by casella** [comment]
For Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW, see #13129.

**Comment by casella** [comment]
All remaining pending issues are scheduled in separate tickets.
