### ISSUE TITLE
Buildings models fail to translate after modifying redeclarations

### ISSUE THREAD

**Issue by hcasperfu** [OpenModelica/OpenModelica#12484]
### Description
The models `Buildings.Fluid.Movers.Validation.{ComparePowerHydraulic,ComparePowerInput,ComparePowerTotal}` fail to translate with the following error message:
```
[1] 11:02:20 Translation Error
[Buildings.Fluid.Interfaces.LumpedVolumeDeclarations: 29:3-31:47]: Component 'p_start' may not have a binding equation due to class specialization 'package'.
```
All three models extend from `Buildings.Fluid.Movers.Validation.BaseClasses.ComparePower` where the components `mov1`, `mov2`, and `mov3` are redeclared.

### Steps to reproduce
1. Check out Buildings https://github.com/lbl-srg/modelica-buildings/pull/3834/commits/216e9cc781b2baf7a4bd150af354ef6862231d53 (under development  branch `ibpsa1880_moverEfficiencyFixAndValidationRework`).
2. In OMEdit, open `Buildings.Fluid.Movers.Validation.ComparePowerHydraulic` (or any of the other two).
3. Click "Simulate".
4. Get the error message.

### Expected behavior
The model should be able to simulate.

### Version and OS
 - OpenModelica 1.24.0~dev-16-gaa27cc1
 - Versions of used Modelica libraries
   - Modelica Standard Library 4.0.0
   - Modelica Buildings Library https://github.com/lbl-srg/modelica-buildings/pull/3834/commits/216e9cc781b2baf7a4bd150af354ef6862231d53 (under development  branch `ibpsa1880_moverEfficiencyFixAndValidationRework`)
 - OS: Ubuntu 64-bit 20.04.3

### Additional context
The models simulate without problem with Dymola 2024x and Optimica 1.43.0.

The models could also simulate with OpenModelica just one commit before at https://github.com/lbl-srg/modelica-buildings/pull/3834/commits/782595312ceddbf32c2a511b5c44e3cd5e60ab80.
The changes made between these two commits are to address an Optimica warning that I accessed a component in the redeclared model that is not present in the constraining class, which I think is a valid point.

`Buildings.Fluid.Interfaces.LumpedVolumeDeclarations` is a very widely used class and does not trigger this error anywhere else in the library at this commit.

**Comment by casella** [comment]
@perost the error message looks very much like a NF glitch, can you please check?

**Comment by casella** [comment]
@perost is working on that, it has a solution for this specific case but he's looking for something more general.
