### ISSUE TITLE
Issues with -d=nonfScalarize,mergeComponents in Base Modelica output of models with operator records

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12490]
### Problem description

Consider the following MWE:
```modelica
model TestArrayRecords
  model M
    Complex v;
  end M;
  Complex v[2];
  M m1;
  M m2;
  M m3;
  M m4;
equation
  v[1] = m1.v;
  v[2] = m4.v;
end TestArrayRecords;
```
When instantiating the model with `--baseModelica -d=nonfScalarize,mergeComponents,combineSubscripts,evaluateAllParameters,vectorizeBindings` one obtains
```modelica
//! base 0.1.0
package 'TestArrayRecords'
  function 'Complex.\'constructor\'.fromReal' "Construct Complex from Real"
    input Real 're';
    input Real 'im' = 0.0;
    output 'Complex' 'result';
  algorithm
    annotation(Inline = true);
  end 'Complex.\'constructor\'.fromReal';

  record 'Complex'
    Real 're';
    Real 'im';
  end 'Complex';

  model 'TestArrayRecords'
    Real[2] 'v.im' "Imaginary part of complex number";
    Real[2] 'v.re' "Real part of complex number";
    'Complex' '$M1.v';
  equation
    'v'[1] = '$M1.v'[1];
    'v'[2] = '$M1.v'[4];
  end 'TestArrayRecords';
end 'TestArrayRecords';
```
There are two issues with this flat model:
- the merged array '$M1.v' lacks the dimension
- the array `v` is split into its Real componens, but the array` $M1.v` isn't

### Desired behaviour

With `--baseModelica -d=nonfScalarize,mergeComponents,combineSubscripts,evaluateAllParameters,vectorizeBindings` one should get the following output
```modelica
//! base 0.1.0
package 'TestArrayRecords'
  function 'Complex.\'constructor\'.fromReal' "Construct Complex from Real"
    input Real 're';
    input Real 'im' = 0.0;
    output 'Complex' 'result';
  algorithm
    annotation(Inline = true);
  end 'Complex.\'constructor\'.fromReal';

  record 'Complex'
    Real 're';
    Real 'im';
  end 'Complex';

  model 'TestArrayRecords'
    'Complex'[2] 'v';
    'Complex'[4] '$M1.v';
  equation
    'v'[1] = '$M1.v'[1];
    'v'[2] = '$M1.v'[4];
  end 'TestArrayRecords';
end 'TestArrayRecords';
```
This is a high-priority requirement for me at the moment.

Once #12489 is implemented, by adding `--flatRecords` to the flags one should obtain:
```modelica
//! base 0.1.0
package 'TestArrayRecords'
  model 'TestArrayRecords'
    Real [2] 'v.re';
    Real [2] 'v.im';
    Real[4] '$M1.v.re';
    Real[4] '$M1.v.im';
  equation
    'v.re'[1] = '$M1.v.re'[1];
    'v.im'[1] = '$M1.v.im'[1];
    'v.re'[2] = '$M1.v.re'[4];
    'v.im'[2] = '$M1.v.im'[4];
  end 'TestArrayRecords';
end 'TestArrayRecords';
```
However, this second feature is not critical to me at the moment

**Comment by perost** [comment]
The issue seems to be that when dumping Base Modelica we get a flat model with e.g. `v[1].re`, `v[1].im` and so on that we then have to reconstruct the record instance from, but it doesn't work correctly for arrays yet. We should probably try to get rid of this and save the record instances somewhere instead of having to reconstruct them, since it's rather complicated and error-prone.

However, the new backend does not split records, so a possible workaround would be to use `--newBackend` which gives the desired result. `--newBackend` also implies `-d=nonfScalarize,vectorizeBindings`, so you don't need to use those two flags in that case.

**Comment by casella** [comment]
OK, so the magic incantation for getting array-preserving Base Modelica would be 
```modelica
--baseModelica --newBackend -d=arrayConnect,combineSubscripts,evaluateAllParameters
```
?

Does adding --newBackend when only using the front-end have any other possible negative side-effects (probably not, just want to make sure)?

**Comment by perost** [comment]
>OK, so the magic incantation for getting array-preserving Base Modelica would be
>
>--baseModelica --newBackend -d=arrayConnect,combineSubscripts,evaluateAllParameters
>
>?

Yes, `--newBackend` automatically force-enables `nonfScalarize` and `vectorizeBindings`, so you don't need to use them explicitly (if you do they'll just be overridden by `--newBackend` anyway).

> Does adding --newBackend when only using the front-end have any other possible negative side-effects (probably not, just want to make sure)?

I think it should only affect how records are flattened, most of the heavy lifting is done by `nonfScalarize`.

**Comment by casella** [comment]
Almost there, I still have an issue with connection equations involving record array variables 😅 

Consider this MWE
```modelica
package TestComplexConnection
  connector Port
    Complex v;
    flow Complex i;
  end Port;
  
  model VoltageSource
    Port p;
  equation
    p.v = Complex(1);
  end VoltageSource;
  
  model CurrentSource
    Port p;
  equation
    p.i = Complex(2);
  end CurrentSource;
  
  model Circuit
    CurrentSource CS[2];
    VoltageSource VS;
  equation
    connect(CS[1].p, VS.p);
    connect(CS[2].p, VS.p);
  end Circuit;
end TestComplexConnection;
```
if you flatten it with `--baseModelica --newBackend -d=mergeComponents,combineSubscripts`, you obtain
```modelica
//! base 0.1.0
package 'Circuit'
  function 'Complex.\'constructor\'.fromReal' "Construct Complex from Real"
    input Real 're';
    input Real 'im' = 0.0;
    output 'Complex' 'result';
  algorithm
    annotation(Inline = true);
  end 'Complex.\'constructor\'.fromReal';

  record 'Complex'
    Real 're';
    Real 'im';
  end 'Complex';

  model 'Circuit'
    'Complex'[2] 'CS.p.i';
    'Complex'[2] 'CS.p.v';
    'Complex' 'VS.p.v';
    'Complex' 'VS.p.i';
  equation
    'CS.p.v'.'re'[2] = 'VS.p.v'.'re';
    'CS.p.v'.'re'[2] = 'CS.p.v'.'re'[1];
    'CS.p.v'.'im'[2] = 'VS.p.v'.'im';
    'CS.p.v'.'im'[2] = 'CS.p.v'.'im'[1];
    'VS.p.i'.'re' + 'CS.p.i'.'re'[2] + 'CS.p.i'.'re'[1] = 0.0;
    'VS.p.i'.'im' + 'CS.p.i'.'im'[2] + 'CS.p.i'.'im'[1] = 0.0;

    for '$i1' in 1:2 loop
      'CS.p.i'['$i1'] = 'Complex'(2.0, 0.0);
    end for;

    'VS.p.v' = 'Complex'(1.0, 0.0);
  end 'Circuit';
end 'Circuit';
```
Unfortunately, `'CS.p.v'.'re'[2]` does not exist, it should rather be `'CS.p.v'[2].'re'`

I hope that's the last fix to get my test case to run 😄

**Comment by perost** [comment]
> Unfortunately, `'CS.p.v'.'re'[2]` does not exist, it should rather be `'CS.p.v'[2].'re'`

You're using `-d=combineSubscripts` which moves all the subscripts to the end of the component reference, so that looks correct to me. 

However, if you don't use that flag you instead get `'CS[2].p.v'.'re'`, which is wrong. In that case you should indeed get `'CS.p.v'[2].'re'`, since the normal case should be that the subscripts are semantically correct.

**Comment by casella** [comment]
We added `-d=combineSubscripts` to move all the subscripts at the end, otherwise you got stuff like `a[2].b.c[3]` instead of `a.b.c[2, 3]`.

OMC does not accept `'CS.p.v'.'re'[2]` and gives this error:

```
['Circuit': 22:5-22:37]: [Wrong number of subscripts in 'CS.p.v'.'re'[2] (1 subscripts for 0 dimensions).]
```
which looks correct to me. If I move the subscript where it belongs
```modelica
model 'Circuit'
  'Complex'[2] 'CS.p.i';
  'Complex'[2] 'CS.p.v';
  'Complex' 'VS.p.v';
  'Complex' 'VS.p.i';
equation
  'CS.p.v'[2].'re' = 'VS.p.v'.'re';
  'CS.p.v'[2].'re' = 'CS.p.v'[1].'re';
  'CS.p.v'[2].'im' = 'VS.p.v'.'im';
  'CS.p.v'[2].'im' = 'CS.p.v'[1].'im';
  'VS.p.i'.'re' + 'CS.p.i'[2].'re' + 'CS.p.i'[1].'re' = 0.0;
  'VS.p.i'.'im' + 'CS.p.i'[2].'im' + 'CS.p.i'[1].'im' = 0.0;

  for '$i1' in 1:2 loop
    'CS.p.i'['$i1'] = 'Complex'(2.0, 0.0);
  end for;

  'VS.p.v' = 'Complex'(1.0, 0.0);
end 'Circuit';
```
OMC compiles the model and runs it successfully.

BTW, there is actually no need to expand the connection equations to their scalar constituents: you could just keep the records and use the operator record functions `'+'` and `'-'` to generate the equations for flow variables; the only thing which is slightly inconventient is that the `'+'` function takes only two inputs, so if you have, say, three connector variables to sum, you'd have to output something like:
```modelica 
'+'('+'('c.v'[1], 'c.v'[2]), 'c.v'[3]) = Complex(0.0, 0.0);
```
instead of 
```modelica 
'c.v'[1].'re' + c'.v'[2].'re' + 'c.v'[3].'re' = 0.0;
'c.v'[1].'im' + c'.v'[2].'im' + 'c.v'[3].'im' = 0.0;
```
To me it's more or less the same, MARCO should be able to cope with both. 

@perost what do you think?

**Comment by perost** [comment]
> We added `-d=combineSubscripts` to move all the subscripts at the end, otherwise you got stuff like `a[2].b.c[3]` instead of `a.b.c[2, 3]`.
> 
> OMC does not accept `'CS.p.v'.'re'[2]` and gives this error:
> 
> ```
> ['Circuit': 22:5-22:37]: [Wrong number of subscripts in 'CS.p.v'.'re'[2] (1 subscripts for 0 dimensions).]
> ```

Yes, moving the subscripts to the end will just create invalid component references since it disregards the actual types, so using `combineSubscripts` will result in invalid Base Modelica models.

I'm not sure why you'd always want the subscripts at the end. To me it looks like an attempt at fixing the incorrect component references that I mentioned earlier, but if so it's the wrong solution and the actual solution is to move the subscripts to the correct place when constructing the quoted names. I.e. `a[2].b.c[3]` should become `'a.b.c'[2, 3]` (assuming `a.b.c` isn't scalarized), which is not the same as `a.b.c[2, 3]`.

> BTW, there is actually no need to expand the connection equations to their scalar constituents: you could just keep the records and use the operator record functions `'+'` and `'-'` to generate the equations for flow variables; the only thing which is slightly inconventient is that the `'+'` function takes only two inputs, so if you have, say, three connector variables to sum, you'd have to output something like:
> 
> ```modelica
> '+'('+'('c.v'[1], 'c.v'[2]), 'c.v'[3]) = Complex(0.0, 0.0);
> ```
> 
> instead of
> 
> ```modelica
> 'c.v'[1].'re' + c'.v'[2].'re' + 'c.v'[3].'re' = 0.0;
> 'c.v'[1].'im' + c'.v'[2].'im' + 'c.v'[3].'im' = 0.0;
> ```
> 
> To me it's more or less the same, MARCO should be able to cope with both.
> 
> @perost what do you think?

It's either fairly easy or almost impossible, I'm not entirely sure which. We currently split records at the first stage of the connection handling, it might be that we can just disable that and hope for the best.

**Comment by casella** [comment]
> I'm not sure why you'd always want the subscripts at the end. To me it looks like an attempt at fixing the incorrect component references that I mentioned earlier, but if so it's the wrong solution and the actual solution is to move the subscripts to the correct place when constructing the quoted names. I.e. `a[2].b.c[3]` should become `'a.b.c'[2, 3]` (assuming `a.b.c` isn't scalarized), which is not the same as `a.b.c[2, 3]`.

Consider this MWE:
```modelica
model Test
  model M
    Real v[2];
  equation
    v[1] = 3;
    v[2] = 6;
  end M;
  
  M m[3];
end Test;
```
Flattening with just `-d=nonfScalarize` gives:
```modelica
class Test
  Real[3, 2] m.v;
equation
  for $i1 in 1:3 loop
    m[$i1].v[1] = 3.0;
  end for;
  for $i1 in 1:3 loop
    m[$i1].v[2] = 6.0;
  end for;
end Test;
```
which clearly doesn't work, because `m.v` is declared as a 2D [3,2] array, so having the subscripts scattered around in component references used in equations is inconsistent with that. We then introduced `-d=combineSubscripts` so we could get
```modelica
class Test
  Real[3, 2] m.v;
equation
  for $i1 in 1:3 loop
    m.v[$i1,1] = 3.0;
  end for;
  for $i1 in 1:3 loop
    m.v[$i1,2] = 6.0;
  end for;
end Test;
```
which is more consistent: now you have a 2D array declaration `Real[3,2] m.v;` and then when scalar elements of `m.v` are used, they are indexed by a double subscript, as expected.

Now, when using `--baseModelica -d=nonfScalarize`, one gets
```modelica
//! base 0.1.0
package 'Test'
  model 'Test'
    Real[3, 2] 'm.v';
  equation
    for '$i1' in 1:3 loop
      'm['$i1'].v'[1] = 3.0;
    end for;

    for '$i1' in 1:3 loop
      'm['$i1'].v'[2] = 6.0;
    end for;
  end 'Test';
end 'Test';
```
which is seriously messed up, but if you use `--baseModelica -d=nonfScalarize,combineSubscripts`
```modelica
//! base 0.1.0
package 'Test'
  model 'Test'
    Real[3, 2] 'm.v';
  equation
    for '$i1' in 1:3 loop
      'm.v'['$i1',1] = 3.0;
    end for;

    for '$i1' in 1:3 loop
      'm.v'['$i1',2] = 6.0;
    end for;
  end 'Test';
end 'Test';
```
then it's quite good. I'm not sure whether this was intentional or serendipitous, but from user's point of view, it works just fine.

The only additional issue we have now is that record identifiers should be handled differently from model identifiers when building flat identifiers involving arrays. Now, models can contain models, records can contain records and models can contain records, but luckily records cannot contain models, so there are not that many combinations that are feasible.

Assuming you don't expand records in the declarations (which is what we want now for the MARCO compiler), if you have an identifier `a.b.c`. you only have three possibilities:
- `a` and `b` are model instance names, and `c` is a variable. A 1D array declared as `Real 'a.b.c'[N];` will have elements denoted as `'a.b.c'[2]`. No big deal.
- `a` is a model instance name, `b` is a record name and `c` is a _scalar_ variable of the record. A 1D array declared as `MyRecord 'a.b'[N];` will have elements denoted as `'a.b'[2]` for the full record and `'a.b'[2].'c'` for a single record variable.
- `a` is a model instance name, `b` is a record name and `c` is an _array_ variable of the record. A 1D array declared as `MyRecord 'a.b'[N];` will have elements denoted as `'a.b'[2]` for the full record, `'a.b'[2].'c'` for the single array record variable, and `'a.b'[2].'c'[3]` for one element of the single array record variable.

I haven't tried to generalize to more complex cases, e.g. records containing records, or arrays of records containing records, but I think they are not that frequent. It seems to me that a simple rule could work, at least for basic cases (_including all kind of models using Complex records_):
- if the flattened type is a simple type, e.g., `Real 'a.b.c'[N];`, then combine all the indeces and put them as single subscript of the array
- if the flattened type is a record type, e.g. `MyRecord 'a.b'[N];` then put all the subscripts not related to record elements at the end of the declared identifier, e.g. `'a.b'`. If you want to access individual record elements (scalar or arrays), use the dot notation for them.

@perost what do you think?

**Comment by casella** [comment]
If the above solution works, then you can forget about outputting record equations for connections involving records, and just keep it as it is now, but with correctly placed identifiers.

**Comment by casella** [comment]
Long story short, considering the following MWE:
```modelica
package TestComplexConnection
  connector Port
    Complex v;
    flow Complex i;
  end Port;
  
  model VoltageSource
    Port p;
  equation
    p.v = Complex(1);
  end VoltageSource;
  
  model CurrentSource
    Port p;
  equation
    p.i = Complex(2);
  end CurrentSource;
  
  model Circuit
    CurrentSource CS[2];
    VoltageSource VS;
  equation
    connect(CS[1].p, VS.p);
    connect(CS[2].p, VS.p);
  end Circuit;
end TestComplexConnection;
```
I need the flattened model with `--baseModelica --newBackend -d=mergeComponents,combineSubscripts` to contain the flow variable equations as
```modelica
'c.v'[1].'re' + c'.v'[2].'re' + 'c.v'[3].'re' = 0.0;
'c.v'[1].'im' + c'.v'[2].'im' + 'c.v'[3].'im' = 0.0;
```
or
```
'+'('+'('c.v'[1], 'c.v'[2]), 'c.v'[3]) = Complex(0.0, 0.0);
```

**Comment by perost** [comment]
#12582 improves the Base Modelica output, and the Base Modelica function for component references can now handle fully scalarized, partially scalarized (only last component can be an array), and non-scalarized, with and without records. 

Note that this is only for the output of component references, and of these six combinations it's only partially scalarized + records (the default) and non-scalarized + records that we output somewhat correct models for. I.e. the names are now output in the format that they should be, but the variables themselves might not be correctly declared in the models.

I also added a flag to set the output format, but for now it's more of a debug flag to allow me to test it properly than something you should actually be using. So the current flag combinations that should be somewhat working are `--baseModelica` and `--baseModelica --newBackend`, and flags such as `mergeComponents` and `evaluateAllParameters` can of course also be used since they don't change the output format.

Previously I said that the `combineSubscripts` flag will give the wrong Base Modelica output, but that wasn't entirely correct. We output the Base Modelica before the subscripts are combined, so that particular flag won't actually affect the Base Modelica output, only the normal flat model output.

**Comment by casella** [comment]
> #12582 improves the Base Modelica output, and the Base Modelica function for component references can now handle fully scalarized, partially scalarized (only last component can be an array), and non-scalarized, with and without records.

Excellent 🥇 

> Note that this is only for the output of component references, and of these six combinations it's only partially scalarized + records (the default) and non-scalarized + records that we output somewhat correct models for. I.e. the names are now output in the format that they should be, but the variables themselves might not be correctly declared in the models.

Understood. So, at the end of the day, we should only allow those two combination, since Base Modelica is expected to be machine-readable.

> I also added a flag to set the output format, but for now it's more of a debug flag to allow me to test it properly than something you should actually be using.

OK, no need to hurry with that. BTW, Base Modelica is still not standardized, so we may want to play around a bit more.

> So the current flag combinations that should be somewhat working are `--baseModelica` and `--baseModelica --newBackend`, and flags such as `mergeComponents` and `evaluateAllParameters` can of course also be used since they don't change the output format.

OK. So `--baseModelica` will (mostly) scalarize, while` --baseModelica --newBackend` will preserve arrays, right? Other flags are orthogonal.

**Comment by perost** [comment]
> OK. So `--baseModelica` will (mostly) scalarize, while` --baseModelica --newBackend` will preserve arrays, right? Other flags are orthogonal.

Yes. Ideally we shouldn't have the array-preserving tied to the new backend, but due to the earlier mentioned issues with records that's what we have at the moment. I've been thinking about maybe trying to separate the splitting of records from the flattening to make it easier to support the different ways we want things to be flattened, but we'll see.

And then there's also the planned format with full scalarization and no records, which should be a bit easier now with this change.

**Comment by casella** [comment]
> Yes. Ideally we shouldn't have the array-preserving tied to the new backend, but due to the earlier mentioned issues with records that's what we have at the moment. I've been thinking about maybe trying to separate the splitting of records from the flattening to make it easier to support the different ways we want things to be flattened, but we'll see.

Not urgent, sounds good.

> And then there's also the planned format with full scalarization and no records, which should be a bit easier now with this change.

OK, very good, this may come in handy later this year.

**Comment by casella** [comment]
@perost I see only a couple of tests failing in [#12582](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-12582/4/tests), I guess that's expected, right?

**Comment by perost** [comment]
> @perost I see only a couple of tests failing in [#12582](https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OpenModelica/detail/PR-12582/4/tests), I guess that's expected, right?

Sorry, I somehow missed that it failed to merge. I fixed the failing test and restarted the PR, it should be fine now.

**Comment by casella** [comment]
I started a new nightly build, I'll check as soon as it is available.

**Comment by casella** [comment]
OK, I tried again the original MWE with --baseModelica --newBackend and I get

```modelica
//! base 0.1.0
package 'TestArrayRecords'
  function 'Complex.\'constructor\'.fromReal' "Construct Complex from Real"
    input Real 're';
    input Real 'im' = 0.0;
    output 'Complex' 'result';
  algorithm
    annotation(Inline = true);
  end 'Complex.\'constructor\'.fromReal';

  record 'Complex'
    Real 're';
    Real 'im';
  end 'Complex';

  model 'TestArrayRecords'
    'Complex'[2] 'v';
    'Complex'[4] '$M1.v';
  equation
    'v'[1] = '$M1.v'[1];
    'v'[2] = '$M1.v'[4];
  end 'TestArrayRecords';
end 'TestArrayRecords';
```
which looks fine. Thanks @perost!
