### ISSUE TITLE
Segmentation fault when integrating functions using the MSL 

### ISSUE THREAD

**Issue by biananino** [OpenModelica/OpenModelica#12491]
### Description
When using the function quadratureLobatto from the MSL models may fail with segmentation fault for apparently no reason.

### Steps to Reproduce
Consider the following model
```
model Integrate
  parameter Real X = 1;
  Real V;
equation
  V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(), 0, X);
end Integrate;
```
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Integer DO = 1;
  input Real CO = 1;
algorithm
  y := 1;
end Integrand; 
```
This fails with segmentation fault. Delete DO:
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Real CO = 1;
algorithm
  y := 1;
end Integrand; 
### Expected Behavior
```
This integrates correctly. Add back DO and delete CO:
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Integer DO = 1;
algorithm
  y := 1;
end Integrand; 
```
This too integrates correctly.
Let's add CO and DO back but now without default value:
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Integer DO;
  input Real CO;
algorithm
  y := 1;
end Integrand; 
```
```
model Integrate
  parameter Real X = 1;
  Real V;
equation
  V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(CO = 1, DO = 1), 0, X);
end Integrate;
```
This fails with segmentation fault. Change DO to a real instead of an integer:
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Real DO;
  input Real CO;
algorithm
  y := 1;
end Integrand; 
```
This now integrates correctly. Change DO back to an integer but now change the order of the arguments in the integration:
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Integer DO;
  input Real CO;
algorithm
  y := 1;
end Integrand; 
```
```
model Integrate
  parameter Real X = 1;
  Real V;
equation
  V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(DO = 1, CO = 1), 0, X);
end Integrate;
```
This too integrates correctly.

### Expected behavior
All models run correctly.

### Version and OS

 - OpenModelica Version: 1.24.0~dev-103-g1ef9b1b
 - OS: Linux Mint 21.2.
 - MSL: 4.0.0

### Additional Context
All the legal models in the old frontend, that is the ones where the values to integrand are passed from the integrate function like this 
`V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(DO = 1, CO = 1), 0, X);`
run correctly when using the old frontend.

**Comment by biananino** [comment]
Now let's add another layer, and change the "integrate" model for an integrateFunction and add another model: "integrateModel". Notice that the inputs to integrateFunction do nothing except for X, and that a similar model seg faulted.
```
function Integrand
  extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
  input Integer DO;
  input Real CO;
algorithm
  y := 1;
end Integrand;
```
```
function integrateFunction
  extends Modelica.Icons.Function;
  input Real C;
  input Real X;
  output Real V;
algorithm
  V := Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(CO = 1, DO = 1), 0, X);
end integrateFunction;
```
```
model integrateModel
parameter Real C = 1;
parameter Real X = 1;
Real V;
equation
V = integrateFunction(X = 1, C = 15); 
end integrateModel;
```
This integrates correctly. Get the C or X value from the variable instead:
```
model integrateModel
parameter Real C = 1;
parameter Real X = 1;
Real V;
equation
V = integrateFunction(X = X, C = 15); 
end integrateModel;
```
This fails with segmentation fault now.

**Comment by perost** [comment]
Please describe the exact steps you take to get a segfault. I tried to replicate the issue but the models simulate without any issues for me, but maybe you're doing something different.

**Comment by casella** [comment]
@biananino I also tried to simulate Integrate from this package
```modelica
package TestIntegrate
  model Integrate
    parameter Real X = 1;
    Real V;
  equation
    V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(), 0, X);
  end Integrate;

  function Integrand
    extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
    input Integer DO = 1;
    input Real CO = 1;
  algorithm
    y := 1;
  end Integrand; 
end TestIntegrate;
```
using v1.24.0-dev-98-g8cc47a0cf3 under Windows 10, and it worked fine for me. Does it also work for you?

**Comment by biananino** [comment]
@casella 
> using v1.24.0-dev-98-g8cc47a0cf3 under Windows 10, and it worked fine for me. Does it also work for you?
It always works for me on windows, it doesn't work for me on linux using gcc. That particular example does work with clang, but my function of interest stills segfaults. I will find a MWE for clang later.

@perost 
I managed to reproduce the issue on the virtual machine version.
1.  Download openmodelica-1.24.0~dev-103-g1ef9b1b.vdi (I downloaded the 11G version).
2.  Paste this model

```
package TestIntegrate
  model Integrate
    parameter Real X = 1;
    Real V;
  equation
    V = Modelica.Math.Nonlinear.quadratureLobatto(function Integrand(), 0, X);
  end Integrate;

  function Integrand
    extends Modelica.Math.Nonlinear.Interfaces.partialScalarFunction;
    input Integer DO = 1;
    input Real CO = 1;
  algorithm
    y := 1;
  end Integrand; 
end TestIntegrate;
```
3. Change the C compiler and C++ compiler to gcc and g++.
4. Simulate.
5. Segfault.

**Comment by perost** [comment]
> The following MWE fails for both clang and gcc on both linux and windows (but it works on the old frontend):

I can reproduce the issue with this model. The issue seems to be that with the new frontend we get:
```
V = Modelica.Math.Nonlinear.quadratureLobatto(function TestIntegrate2.Integrand(#(1.0), #({15.0}), #(1.0)), 0.0, 1.0, 1e-13);
```
The arguments of `Integrand` are ordered wrong here, it should be `#(1.0), #(1.0), #({15.0})` like we get with the old frontend. It looks like the new frontend might not take named arguments into account and just keeps the arguments in the given order.

**Comment by casella** [comment]
@biananino thanks for reporting!
