### ISSUE TITLE
Model Buildings.Controls.Continuous.Examples.NumberOfRequests fails verification

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12508]
The model `Buildings.Controls.Continuous.Examples.NumberOfRequests` fails the verification vs the reference file produced by Dymola.
Goal of this model is to test the model `Buildings.Controls.Continuous.NumberOfRequests` that outputs the number of the input signals that are above/below a certain threshold.
In this specific case, the test outputs the number of the input signals that are **"strictly"** higher than **"zero"**.

Herebelow the output from Dymola and OpenModelica:
**Dymola**
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/04c0327c-a46b-45db-90dc-fd794c138ea5)

**OpenModelica**
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/4bc6f392-9b4f-4c9b-bf49-ee6feb2dbecc)

Apparently OpenModelica is not able to detect the **"zero""** of the squared whave.

If the comparison threshold is changed from **"zero"** to a value higher than **"1e-10"** the OpenModelica output is according to the Dymola reference:
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/490941e5-f30a-43d6-a686-95b5a3a7488a)

so the point seems to be the tolerance used by OpenModelica to check the trigger function **"input > 0"**.

The value of the threshold to be used in OpenModelica to detect the **"zero"** value of the squared wave can be reduced by reducing the tolerance of the solver, but in any case the threshold must be higher than **"zero"** to obtain the reference transient.

**Comment by casella** [comment]
@AndreaBartolini is numReq.u[1] a Real or an Integer?

If it is a Real actually representing an integer, the safest possible condition would be `input > 0.5` 😃

**Comment by AndreaBartolini** [comment]
numReq.u[.] are **RealInput** so **Real** numbers, this is the reason because the threshold value becomes critical ;)

**Comment by casella** [comment]
Then `input > 0` is really not a good idea. Would you mind opening a ticket on the Buildings repo?

**Comment by casella** [comment]
Upstream problem was fixed, this should be OK in a few days.

**Comment by AndreaBartolini** [comment]
Today (2024.07.04) it passes the verification in the CI
