### ISSUE TITLE
Global destructors of shared libraries loaded to call external functions not called

### ISSUE THREAD

**Issue by fedetftpolimi** [OpenModelica/OpenModelica#12516]
### Description

The simulation programs generated by omc don't seem to correctly unload shared libraries that are loaded to call external functions. As an observable behavior, C++ destructors of global objects are not called. We noticed this issue when using a global destructor to write a log file that was never produced.

This only happens when shared libraries are loaded by the simulator programs produced by omc. When shared libraries are loaded at translation time to resolve package constants that depend on external functions, destructors are called (at least on Linux).

### Steps to Reproduce

The following minimal non-working example contains Modelica model Test that calls external function foo() in the shared library libmnwe.so, the library also contains a global constructor and destructor, each of which prints to stdout and creates an empty file.

[mnwe.zip](https://github.com/user-attachments/files/15592914/mnwe.zip)

### Expected Behavior

When running the example, both "constructor called" and "destructor called" should be printed, and in the working directory there should be two empty files called constructorcalled.txt and destructorcalled.txt.

What happens instead, is that only the constructor-part works, the destructor does not.

### Version and OS

 - OpenModelica Version: 1.24.0~dev-103-g1ef9b1b
 - OS: Only checked on Linux, may affect also Windows

**Comment by casella** [comment]
@mahge would you like to comment on that?

**Comment by fedetftpolimi** [comment]
This could be as simple as a missing dlclose()

**Comment by AnHeuermann** [comment]
I'll see if I can find the location where we should call the deinitialization function after the simulation finishes.

**Comment by mahge** [comment]
Sorry I missed this. I can also take a look. If @fedetftpolimi says is all we need, it should be easy to fix. I will check.

**Comment by casella** [comment]
@fedetftpolimi is usually pretty accurate with these things 😄

**Comment by AnHeuermann** [comment]
We are not using dlopen / dlclose to load the symbolic or static library `libmnwe.so` / `libmnwe.a` at runtime. OMC links `mnwe` during compilation of `mnwe.Test`:

```
clang [..] "-L/path/to/issue-12516/mnwe/Resources/Source/build" -Wl,-rpath="/path/to/issue-12516/mnwe/Resources/Source/build" -lmnwe [...] "-I/path/to/issue-12516/mnwe/Resources/Source/" [...]
```

I guess the problematic part is that we use `EXIT` to exit the `int OMC_MAIN(int argc, OMC_CHAR** argv)` function:

```C
#if !defined(OMC_DLL_MAIN_DEFINE) /* do not exit, return in DLL mode */
  EXIT(res);
#endif
  return res;
```

When using `return` the destructor is called.

**Comment by AnHeuermann** [comment]
I don't know why `EXIT` was added. @adrpo do you know it?

If we use `return` it in DLL mode, why not in the executable mode?
We can also use `exit(res)` instead of `EXIT(res)`. I don't know where `EXIT` is defined, but I guess it is calling `_exit(res)` which slightly different to `exit` and won't call the destructor.

**Comment by fedetftpolimi** [comment]
_exit() is the underlying syscall to the kernel to terminate the process
exit() is the standard C function to perform cleanup and terminate the process. On Linux, exit() should call _exit(), but after it has done the following (recalling from memory, may forget some steps):
- call C "destructors" registered through atexit
- call C++ destructors, if any
- flush the stdio buffered streams, e.g. stdout

I fin it weird too that you're using _exit.

**Comment by perost** [comment]
> I don't know where `EXIT` is defined, but I guess it is calling `_exit(res)` which slightly different to `exit` and won't call the destructor.

It's defined here:
https://github.com/OpenModelica/OpenModelica/blob/aeb305eb0295f7736055100584a5c352cbf9fb77/OMCompiler/SimulationRuntime/c/openmodelica.h#L82-L89

So on Windows it's calling `exit` while on Linux it's calling `_exit`, seemingly to fix some issue with simulations not returning the correct exit code. The code is at least 13 years old and seems like a hack to fix an issue that wasn't really understood, so it might not be necessary anymore.

**Comment by perost** [comment]
It looks like `EXIT` is used in a few places in the simulation runtime too, which we should probably replace with `exit` if we merge #12580.

**Comment by AnHeuermann** [comment]
> It looks like `EXIT` is used in a few places in the simulation runtime too, which we should probably replace with `exit` if we merge #12580.

I'll add it to the PR

**Comment by perost** [comment]
> > It looks like `EXIT` is used in a few places in the simulation runtime too, which we should probably replace with `exit` if we merge #12580.
> 
> I'll add it to the PR

You may want to just remove the `EXIT` macro completely, or at least change it to just call `exit`. You could argue that having a macro allows for easier customization, but I'm not sure if making it easy to mess around with how we exit is really something we want.

**Comment by casella** [comment]
@fedetftpolimi please try with the next nightly build.

**Comment by fedetftpolimi** [comment]
I checked and the problem is fixed. Thanks!

**Comment by casella** [comment]
Thanks @fedetftpolimi for suggesting a solution and @AnHeuermann for implementing it 😃
