### ISSUE TITLE
Documentation window does not render correctly with all-in-one "annotation" sentence

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#12546]
### Description

Why OMedit shows correctly the Documentation window here:

<img width="766" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/c33379f9-edfb-41e1-91de-2d6a636765e1">

And here, all in the same "annotation" sentence not:

<img width="702" alt="image" src="https://github.com/OpenModelica/OpenModelica/assets/93596576/9d01f5c5-53d6-424e-9e8b-eb29bc8cea7b">

### Version and OS

 - OpenModelica Version: v1.23.0-dev-420-g1cb1c69e62 (64-bit)
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by perost** [comment]
You're missing an `;` at the end of the last equation, so the first (and only in the second example) annotation belongs to that equation rather than the model.

Unfortunately I don't think there's much we can do to make such issues more visible since it's still a completely valid model.

**Comment by BasilioPV** [comment]
Thanks and sorry for this newbie error...
