### ISSUE TITLE
OMEdit "losing" files when renaming classes

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#12567]
### Description

When renaming classes in a Modelica library OMEdit is littering my directory with `bak-mo` files. It's a good thing that OMEdit doesn't always loose my files, but at the same time I end up with many backup files in my library.

But when renaming class `a` to class `A` OMEdit will loose `a.mo` / `A.mo` entirely.

### Steps to Reproduce

Create new package `P` and deactivate `Save contents in one file`. Save package, that creates some location `/path/to/P/`.
Add new Modelica class `model a` to package `P` and save again.

```
P
├── a.mo
├── package.mo
└── package.order
```

Now change the model name of `a` to `A` and save again and we lost the Modelica source containing `model A` completely!
Open `/path/to/P/A.mo` in text view and change
 ```diff
within P;
- model a
- end a;
+ model A
+ end A;
```

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/a14ad86e-dd33-4d94-a3ac-bfc5343bfeb7)

The file `/path/to/P/A.mo` doesn't exist. When unloading `P` and loading it again `A` or `a` is gone.
Luckily we still have the backup file:
```
P
├── a.bak-mo
├── package.mo
└── package.order
```

------------------------

This gets even worse when renaming packages like `p2` to `P2`. OMEdit immediately looses all models in `p2` / `P2` and fails to rename the directory `p2` to `P2` (on Windows there is no difference between the two, but you can rename it nonetheless).

Before rename:
```
P
├── p2
│   ├── A.mo
│   ├── B.mo
│   ├── C.mo
│   ├── package.mo
│   └── package.order
├── package.mo
└── package.order
```

After rename:
```
P
├── p2
│   ├── A.bak-mo
│   ├── B.bak-mo
│   ├── C.bak-mo
│   ├── package.mo
│   └── package.order
├── package.mo
└── package.order
```

The package.order and the `within P.p2` are now wrong as well. I need to rename all `.bak-mo` files to `.mo` and open them with a different text editor to fix this as well as the `package.order` files before I can re-open the library in OMEdit.

### Expected Behavior

Rename models / blocks / functions /... without creating `.bak-mo` files.
Renaming packages to change the directory and to not remove everything contained in that directory.

### Version and OS

 - OpenModelica Version: v1.24.0-dev-122-g6492c57e25-cmake
 - OS: Windows 11, 64 bit

**Comment by adeas31** [comment]
Of course this is because the Windows can't handle case sensitive file names. So instead of renaming from `a` to `A` if you try to rename to `b` this should work fine.

Anyways I fixed this now with PR #12594. Now on Windows `a` is renamed successfully to `A` even the filename is changed from `a.mo` to `A.mo` and no backup file is created. But on non-Windows systems, you will get `a.bak-mo` and `A.mo`.
