### ISSUE TITLE
Model Buildings.DHC.Loads.Steam.BaseClasses.Examples.ValveSelfActing fails validation

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12569]
The following variables of the model `Buildings.DHC.Loads.Steam.BaseClasses.Examples.ValveSelfActing` fail the validation vs the Dymola reference file:
- `speEntOut.h_out`
- `speEntIn.h_out`
- `prv.dp`
- `prv.port_a.p`

the main diagram of the model is shown below:
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/04707fe5-fce5-42de-bd72-0f4b2d8d4f1a)

The root cause of the verification failure is the noise generator `pInSig` used to produce the reference pressure in the source `sou` node, that generates different noise profiles in Dymola and OpenModelica, as shown below:

![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/ed93f17f-0766-4aad-bd61-52ffb857b9da)

Both the noises shown above (Dymola and OpenModelica) have been generated by using the same physical machine and the same operating system, so it means that in some way Dymola and OpenModelica generate different noises starting from the same Modelica model. This makes impossible to use the noise generator to compare OpenModelica trends vs Dymola.

**Comment by casella** [comment]
@AndreaBartolini could you post an MWE with just the signal generator, please?

**Comment by bilderbuchi** [comment]
Feels like the actually used seeds are different between OM and Dymola, although they should not be. 
Could be related: #10475?

**Comment by AndreaBartolini** [comment]
> @AndreaBartolini could you post an MWE with just the signal generator, please?

Herebelow the MVE
```modelica
model TestNoiseGenerator
  inner Modelica.Blocks.Noise.GlobalSeed globalSeed "Setting for sublibrary noise";
  Modelica.Blocks.Noise.UniformNoise noiseGen(
    samplePeriod(displayUnit="s") = 1,
    y_min=1 + 10,
    y_max=1 - 10) "Noisy signal";

  annotation(experiment(StartTime = 0, StopTime = 100, Tolerance = 1e-06, Interval = 0.2));
end TestNoiseGenerator;
```

And herebelow the MVE output generated by Dymola vs the same generated by OpenModelica
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/6727eac4-457b-4a68-a47f-cf127f66c38e)

Dymola Version 2024x, 2023-10-06
OpenModelica v1.24.0-dev-121-gd21af17721 (64-bit)
Win 11 Pro (64 bit)

**Comment by casella** [comment]
Dymola 2024 x: noiseGen.localSeed = 1095886464
OMC 1.24.0-dev-123: noiseGen.localSeed = -1640999979

Source code:
```modelica
localSeed = if useAutomaticLocalSeed then automaticLocalSeed(getInstanceName()) else fixedLocalSeed;
```

Flat model (OMC):
```modelica
  noiseGen.localSeed = if noiseGen.useAutomaticLocalSeed then -1640999979 else noiseGen.fixedLocalSeed;
```

Flat model (Dymola)
```modelica
      noiseGen.localSeed = (if noiseGen.useAutomaticLocalSeed then 
        Modelica.Math.Random.Utilities.automaticLocalSeed("TestNoiseGenerator.noiseGen")
         else noiseGen.fixedLocalSeed);
```

Causalized model (Dymola dsmodel.mof)
```modelica
  noiseGen.localSeed := (if noiseGen.useAutomaticLocalSeed then Modelica.Utilities.Strings.hashString
    ("TestNoiseGenerator.noiseGen") else noiseGen.fixedLocalSeed);
```
`Given that noiseGen.useAutomaticLocalSeed = true`, both models should pick `Modelica.Utilities.Strings.hashString("TestNoiseGenerator.noiseGen")`. OMC does it at compile time, Dymola at run time.

So, the problem boils down to how Dymola and OMC handle this MWE:
```modelica
model TestHashString
  Integer seed = Modelica.Utilities.Strings.hashString("TestNoiseGenerator.noiseGen");
end TestHashString;
```

**Comment by casella** [comment]
OMC: seed = -1640999979
Dymola: seed = 1095886464

**Comment by casella** [comment]
MWE taken from the [Modelica.Utilities.Strings.hashString documentation](https://doc.modelica.org/om/Modelica.Utilities.Strings.hashString.html). Expected result: 1827717433

```modelica
model TestHashString
  Integer res = Modelica.Utilities.Strings.hashString("this is a test");
end TestHashString;
```
OMC: res = 1827717433
Dymola: res = 1734720768

Conclusion: the Dymola implementation has some issues and the reference results generated with it are wrong.

**Comment by casella** [comment]
@mwetter, please file an issue with this MWE at DS. Not sure how to handle the reference generation on your side in the meantime...

**Comment by mwetter** [comment]
@casella : Dymola 2024x Refresh 1 on Linux gets 1734720762 which is wrong.
I will file an issue with DS.

**Comment by casella** [comment]
That's quite weird, I though they ran ModelicaTest before each release, this should have been caught easily. Maybe some installation/C compiler issue? The culprit is an external C function. Pls. keep me posted about this.

**Comment by perost** [comment]
> That's quite weird, I though they ran ModelicaTest before each release, this should have been caught easily. Maybe some installation/C compiler issue? The culprit is an external C function. Pls. keep me posted about this.

See discussion in [MSL#3415](https://github.com/modelica/ModelicaStandardLibrary/issues/3415). OM uses the hash function defined in the MSL, while Dymola uses the default hash function from uthash because they happen to include `uthash.h` before the hash function is redefined in `ModelicaStrings.c`.

The solution to this was apparently to [remove the tests in ModelicaTest](https://github.com/modelica/ModelicaStandardLibrary/pull/3442/files) that checked that the hash function gave a specific result, which basically means that the behaviour of `Modelica.Utilities.Strings.hashString` is considered to be tool-dependent.

**Comment by casella** [comment]
@perost the test was later reintroduced in the same PR, see modelica/ModelicaStandardLibrary#4419.

**Comment by mwetter** [comment]
> keep me posted about this.

@casella : This will be fixed in future Dymola versions (Dassault SR01217667-01)

**Comment by casella** [comment]
In the meantime, you can address the issue by giving the seed explicitly as a parameter.
