### ISSUE TITLE
For loop algorithm can fail with no error message.

### ISSUE THREAD

**Issue by biananino** [OpenModelica/OpenModelica#12585]
### Description
Inside an algorithm section, attempting to modify the looping variable in a for loop results in failure with no error message. 

### Steps to Reproduce
Consider the following model:
```modelica
model forloop
Integer j[3];
algorithm
for i in 1:3 loop
 i := 1;
 j[i] := i;
 end for;
end forloop;
``` 
Attempting to simulate it outputs `Internal error Instantiation of forloop failed with no error message.
` 
### Expected Behavior
Since the model seems to be legal, it should check and simulate correctly.

### Version and OS

 - OpenModelica Version: 1.24.0~dev-137-gd94c8c9
 - OS: Linux Mint 21.2

**Comment by perost** [comment]
The model is not legal, [8.3.2.1 in the specification](https://specification.modelica.org/master/equations.html#explicit-iteration-ranges-of-for-equations) states that the loop variable shall not be assigned to. But we should of course print a proper error message for it rather than just failing.
