### ISSUE TITLE
The NF wrongly reports about partial Medium package?

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12612]
@perost, please check [ModelicaTest.Media.TestOnly.WaterIF97_dewEnthalpy](https://libraries.openmodelica.org/branches/master/ModelicaTest_trunk/files/ModelicaTest_trunk_ModelicaTest.Media.TestOnly.WaterIF97_dewEnthalpy.err). The following error is issued:
```
[ModelicaTest trunk/Media.mo:960:7-960:66:writable] Error:
Medium is partial, name lookup is not allowed in partial classes.
```
I checked the [model](https://github.com/modelica/ModelicaStandardLibrary/blob/83189ce507a0230b0c79ca4c30c052df8dfda3e2/ModelicaTest/Media.mo#L953) but it seems to me that Medium is redeclared. Do I miss something?

**Comment by perost** [comment]
There's actually no redeclaration going on in this case, the model in question defines a medium that it then uses directly in the model. But that medium is Modelica.Media.Water.WaterIF97_fixedregion which is partial. I reported it to the MSL in [#4428](https://github.com/modelica/ModelicaStandardLibrary/issues/4428).

**Comment by casella** [comment]
Ouch, I should have know better. Good that you spotted it 😄 

In fact, there is probably no for that package to be partial in the first place. But in any case we can just use StandardWater.

The problem is, Dymola is not too strict with these issues. It produces warning, but then it goes ahead, reference values are produced, and the model gets a "legal" stamp that is sometimes undeserved. We'll try to improve the situation with a multi-tool CI after we release 4.1.0.
