### ISSUE TITLE
Can't pass `format` from a parameter in String function for annotation Text

### ISSUE THREAD

**Issue by bmazurie** [OpenModelica/OpenModelica#12622]
### Description
When having a text in Diagram window with `textString = DynamicSelect("0.0", String(time, format))` , OpenModelica will crash unexpectedly if you try to change the time in the plotting tab with a diagram window open. 

### Steps to reproduce
Please see next model : 
```modelica
model show_time
  parameter String format=".6g";
equation

annotation (
    Diagram(graphics={Text(origin = {0, 10}, extent = {{-40, 30}, {40, -30}}, textString = DynamicSelect("0.0", String(time, format)))}));
end show_time;
```

- Simulate the model `show_time`
- Go to Plotting Tab
- Open a Diagram Window
- Try to change the time on the right
![image](https://github.com/OpenModelica/OpenModelica/assets/138198674/028b18f8-2dc0-4286-87ff-04e36f9ee5bc)
- OpenModelica crashes unexpectedly.
![image](https://github.com/OpenModelica/OpenModelica/assets/138198674/2235ece4-c0a5-4329-a2ed-f06406788776)

Try again but this time without the `format` in String (or at least not given by a parameter, you can directly write `".6g"`), it should work fine.

It is the most minimal working example I could find, giving a parameter String to format seems to be the problem.

### Expected behavior
To have the possibility to give format to this text by a parameter (the idea behind could be to have a block like `Modelica.Blocks.Interaction.Show.RealValue`  but where `format` is given instead of `significantDigits`).

### Version and OS
I tried with :
 - Linux Scibian11 (Debian GNU/Linux 11 (bullseye) on x86_64.) : OpenModelica 1.19.2 and 1.22.3 
 - Windows10 : OpenModelica 1.21

**Comment by adeas31** [comment]
Fixed by #12841
