### ISSUE TITLE
model Buildings.Examples.SimpleHouse fails verification

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#12653]
The variable `heaWat.u` of the model `Buildings.Examples.SimpleHouse` fails the verification vs the Dymola reference file:
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/95a744df-3ce7-4d5a-8a63-017cdb1aeb45)

Herebelow the same interval simulated in local on the following system:
Win11 pro - 64 bit
Dymola Version 2024x, 2023-10-06
OpenModelica v1.24.0-dev-168-g907b8bd1e8 (64-bit)
Building master 0d8ed44f190fae7af6fa5e84001adc4b8ee2625d
![image](https://github.com/OpenModelica/OpenModelica/assets/25974985/5af505f6-47b0-492d-b48d-f90a9c8f3c69)

OpenModelica and Dymola results overlap.

The cause of the verification failure seems to be the output interval used by the CI.

**Comment by casella** [comment]
@adrpo, @sjoelund could you please look into that?

**Comment by AndreaBartolini** [comment]
Today (2024.07.04) it passes the verification in the CI
