### ISSUE TITLE
Wrong translation error message about array modification in OMEdit

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#12662]
### Description

I believe OMEdit issues a wrong  translation error message when opening a model, please see below.

In `Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable` and in the instance which is of class `Modelica.Blocks.Sources.CombiTimeTable` the parameter `offset` is an array, so there should not be any `each` required, and the variability is `parameter` in both class definitions.

### Steps to Reproduce

Open OMEdit, and open `Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable`.

### Expected Behavior

There should be no warning.

### Screenshots

The translation error message is
```
[4] 17:47:08 Translation Notification
[Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable: 60:11-60:24]: [From here:](omeditmessagesbrowser:///Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable?lineNumber=60)

[5] 17:47:08 Translation Error
[Modelica.Blocks.Sources: 1592:5-1593:61]: [Non-array modification 'offset' for array component 'offset', possibly due to missing 'each'.](omeditmessagesbrowser:///Modelica.Blocks.Sources?lineNumber=1592)

[6] 17:47:08 Translation Error
[Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable: 60:11-60:24]: [Component offset of variability parameter has binding '(offset)[<tab, tab>]' of higher variability continuous.](omeditmessagesbrowser:///Buildings.Controls.OBC.CDL.Reals.Sources.TimeTable?lineNumber=60)
```

### Version and OS
OMEdit on Ubuntu
```
Connected to OpenModelica 1.24.0~dev-170-gf500cdb
Connected to OMSimulator 2.1.2~4-g6f4ecda-linux-notlm-debug
```

**Comment by casella** [comment]
@perost this error shows up in the message browser while using the GUI. Is this a front-end problem?

**Comment by casella** [comment]
Thanks @perost!
