### ISSUE TITLE
OMEdit 1.23.0 crashes during evaluation of external functions in ExternalMedia 4.0.0

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#12679]
### Description

The new version of OMEdit does a lot of model evaluations to improve the UI, e.g. adapt graphics to model variables. Along with ExternalMedia this may cause OMEdit to crash under Windows 64bit.

### Steps to Reproduce

Install and load ExternalMedia 4.0.0. Double click on the model `ExternalMedia.Examples.CO2CoolPropTabular`. 
OMEdit 1.23.0 crashes.

### Expected Behavior

OMEdit opens the model.

### Version and OS

 - OpenModelica Version: 1.23.0
 - OS: Windows 11, 64 bit
 - ExternalMedia 4.0.0 coming with current OpenModelica

### Additional Context

The problem disappears with the current nightly build 1.24 dev. @perost has already backported the relevant commit 332e81aa6442c4cc4761251407332f86f80e834b to 1.23 maintenance.

Can we get a new 1.23.1 from the current maintenance branch?

**Comment by rfranke** [comment]
See #12440

**Comment by casella** [comment]
@adrpo there are currently four open issue in 1.23.1, including this one. For some, we need @adeas31 and that will take some time. Should we go ahead with the 1.23.1 anyway, and have a 1.23.2 later in the fall?

**Comment by casella** [comment]
OK. @rfranke have you actually tried to build it from the maintenance branch and can you confirm it works for you?

**Comment by rfranke** [comment]
Just built maintenance/v1.23 under Linux. It works for me.

**Comment by casella** [comment]
@rfranke please note that (if I remember correctly) the ExternalMedia crashes only happen on Windows, not on Linux.

Anyway, @adrpo can make the release and if something goes wrong with it, we can make another.

**Comment by rfranke** [comment]
Thank you. I never built a Windows version myself. The setup of a proper build environment appears ways more sophisticated. But I can confirm that 1.23.0 crashes and that the current nightly works. Trusting in @perost that he has carry picked the right commit.

**Comment by casella** [comment]
OK, I'm closing the ticket since the required commit should already be on the maintenance branch, so they'll be shipped with 1.23.1
