### ISSUE TITLE
The NF fails on recently added Buildings models, due to intricate record access issue

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12675]
@perost, please check the [Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.InletTemperaturePulse](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.InletTemperaturePulse.err) model that was recently added to the master branch of Buildings, along with other similar models failing in the same way.

The NF reports:
```
[C:/dev/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFExpression.mo: 1628:7-1629:100]: Internal error NFExpression.makeSubscriptedExp: too few dimensions in Buildings.Fluid.Geothermal.Borefields.Data.Configuration.Template(Buildings.Fluid.Geothermal.Borefields.Types.BoreholeConfiguration.DoubleUTubeParallel, false, 0.0, ({0.23045972222222225, 0.23045972222222225})[<zonDat, 1>], ({5.531033333333334, 0.921838888888889})[<zonDat, 1>], ({34000.0, 34000.0})[<zonDat, 1>], 85.0, 0.075, 0.5, ({24, 4})[<zonDat, 1>], {{3.0, 1.5}, {6.0, 1.5}, {9.0, 1.5}, {12.0, 1.5}, {1.5, 4.5}, {4.5, 4.5}, {7.5, 4.5}, {10.5, 4.5}, {3.0, 7.5}, {6.0, 7.5}, {9.0, 7.5}, {12.0, 7.5}, {1.5, 10.5}, {4.5, 10.5}, {7.5, 10.5}, {10.5, 10.5}, {3.0, 13.5}, {6.0, 13.5}, {9.0, 13.5}, {12.0, 13.5}, {1.5, 16.5}, {4.5, 16.5}, {7.5, 16.5}, {10.5, 16.5}, {5.4, 22.5}, {10.8, 22.5}, {2.7, 28.5}, {8.1, 28.5}}, 0.016, 0.42, 0.0029, 0.0282842712474619, ({2.3045972222222227e-5, 2.3045972222222227e-5})[<zonDat, 1>]) to apply subscripts [<zonDat, 1>]
```
This is quite intricate, as I understand the model contains a record borFieDat, which contains a record conDat that has some array fields, something goes wrong when that is used.

I can't check the model with Dymola right now, but I guess they used Dymola to build it and Dymola accepts it, so it's probably a NF issue. Can you please check?

Keeping @deepak19015 in the loop.

**Comment by casella** [comment]
@deepak19015 this same issue also affects the other models in Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW, please update your Excel records

**Comment by casella** [comment]
@perost if you could have a look before the Christmas break, that would be great. Thanks!

**Comment by perost** [comment]
Fixed with #13377. The models in the `Buildings.Fluid.Geothermal.ZonedBorefields.Validation.FEFLOW.InletTemperaturePulse` package now pass the frontend but fail in the backend due to #12677.

**Comment by casella** [comment]
@Pavanrajhr, please update the bug summary spreadsheet accordingly. Thanks!

**Comment by Pavanrajhr** [comment]
> @Pavanrajhr, please update the bug summary spreadsheet accordingly. Thanks!

Sure
