### ISSUE TITLE
ThermalSeparation

### ISSUE THREAD

**Issue by laisagrassi** [OpenModelica/OpenModelica#12708]
Hi, I need to add tha ThermalSeparation package, but it gives an error: Translation Error - Cannot instantiate ThermalSeparation due to class specialization package. Has this error ever happened to someone?

The code is:
within ;
package ThermalSeparation "Thermal Separation Library"
constant Integer inter[:] = {1,3,6,10,15, 21, 28, 36, 45}
  "number of binary interaction values depending on the number of substances";
import      Modelica.Units.SI;

annotation (preferedView="info",
  version="0.2",
uses(Modelica(version="4.0.0")),
     Icon(graphics={Ellipse(
        extent={{-70,70},{70,-70}},
        lineColor={0,0,0},
        fillPattern=FillPattern.Solid,
        fillColor={255,0,0}), Line(
        points={{-100,-70},{-70,-70},{70,70},{100,70}},
        color={0,0,0},
        smooth=Smooth.None)}),
    Documentation(info="<html>
<p>This library is intended to describe the following separation units:</p>
<ul>
<li>Rectification column</li>
<li>Absorption column </li>
</ul>
<p><br>For getting started please take a look at the<a href=\"Modelica://ThermalSeparation.UsersGuide\"> User&apos;s Guide</a>.</p>
<p><img src=\"../images/tt_tuhh_logo.gif\"/></p>
<p><br>Technische Universit&auml;t Hamburg</p>
<p>Institut f&uuml;r Technische Thermodynamik </p>
<p>Denickestra&szlig;e 17 </p>
<p>D-21073 Hamburg </p>
<p>Germany </p>
<p><a href=\"http://www.tu-harburg.de/tt\">www.tu-harburg.de/tt</a></p>
<p>Copyright &copy; 2017, Institute of Engineering ThermoDynamics (Hamburg University of Technology (TUHH)).</p>
<p><i>This Modelica package is <b>free</b> software; it can be redistributed and/or modified under the terms of the <b>Modelica license</b>, see the license conditions and the accompanying <b>disclaimer</b> <a href=\"../ModelicaLicense2.html\">here</a>.</i> </p>
</html>", revisions="<html>
<table cellspacing=\"2\" cellpadding=\"0\" border=\"1\"><tr>
<td><p align=\"center\"><h4>created by </h4></p></td>
<td><p>Karin Dietl &AMP; Andreas Joos &AMP; Kai Wellner &AMP; Thomas Marx-Schubach </p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>creation date </h4></p></td>
<td><p>01.01.2017</p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>revised by </h4></p></td>
<td><p>nobody so far</p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>last revision </h4></p></td>
<td><p>this is an alpha version </p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>based on </h4></p></td>
<td></td>
</tr>
<tr>
<td><p align=\"center\"><br><h4>requires </h4></p></td>
<td><p>MSL 3.2.2</p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>tested on </h4></p></td>
<td><p>Dymola 2017 FD01</p></td>
</tr>
<tr>
<td><p align=\"center\"><h4>contains sensitive data </h4></p></td>
<td><p>yes</p></td>
</tr>
</table>
</html>"),
  conversion(noneFromVersion="0.1"));
end ThermalSeparation;

**Comment by Maxwellfire** [comment]
Are you just trying to translate the code you listed? or is there more that you're trying to do. (You can put code in \`\`\` code \`\`\` blocks so that it's easier to read.)

**Comment by casella** [comment]
@laisagrassi it's not clear what you problem is. What do you mean by "add the Thermal Separation package?", do you mean load it in OMEdit? For that, you need to open the package.mo file in the top directory. And of course you cannot simulate a package, you need to select a model in order to simulate it.

Also please note that there are some issues in the code of ThermalSeparation which prevent the compilation of most models, see this [report](https://libraries.openmodelica.org/branches/master/ThermalSeparation/ThermalSeparation.html).

If you want to get ThermalSeparation to work in OpenModelica we are happy to help, just let us know.

**Comment by casella** [comment]
By default, libraries with full or partial support are shown. At the moment, most models of ThermalSeparation don't work in OpenModelica, mostly because of lookup issues. Hence, the library can only be visualized if you check on the "None" checkbox.

**Comment by laisagrassi** [comment]
Thank you for your help. I was able to locate the ThermalSeparation library, but as you mentioned in your first comment, there are some issues with the code. The example I need is one of the cases that has a problem. Is there a way to fix this?

**Comment by casella** [comment]
There are some parts of some component models that use functions of partial medium models. They should use the redeclare concrete medium model instead. That's not too difficult, but not trivial either. Unfortunately the development of that library was done with Dymola which sometimes is a bit relaxed in terms of enforcing the Modelica language specification, and now that the project that funded it is over the development kind of stalled. You can open a ticket on the library github repo and see what happens. We don't have enough manpower to take care of library development, sorry.
