### ISSUE TITLE
uninitialized variable

### ISSUE THREAD

**Issue by maddin200** [OpenModelica/OpenModelica#12700]
File:
OMCompiler\SimulationRuntime\OMSICpp\runtime\src\Solver\RK12\RK12.cpp line 358

Code:
for (int i; i < _dimSys; i++) // <-- i not initialized

**Comment by AnHeuermann** [comment]
Thanks for catching this error.
Do you want to provide a pull request with a fix? Maybe together with #12698 and #12699.

**Comment by maddin200** [comment]
Would be great if you guys can do it.
