### ISSUE TITLE
ClaRa - PowerPlant model - compilation fails

### ISSUE THREAD

**Issue by AlesVojacek** [OpenModelica/OpenModelica#12701]
### Description

ClaRa.Examples.SteamPowerPlant_CombinedComponents_01 fails during compilation:

Error message:

```
clang: error: no such file or directory: 'SteamPowerPlant_CombinedCompon'
mingw32-make: *** [SteamPowerPlant_CombinedComponents_01.makefile:191: omc_main_target] Error 1
mingw32-make: Leaving directory 'C:/Work/Test/OPENMO~1/CLARAE~3.STE'
Compilation process failed. Exited with code 0x00000002.
```

### Steps to Reproduce

Load ClaRa, TILMedia and SMArtIInt (latest commit)
from [ClaRa-offcial](https://github.com/xrg-simulation/ClaRa-official)
and simulate:
ClaRa.Examples.SteamPowerPlant_CombinedComponents_01

### Expected Behavior

Tester shall run through.

### Version and OS
Omedit:
Connected to OpenModelica v1.23.1 (64-bit)
Connected to OMSimulator v2.1.2-mingw-notlm-debug

### Additional Context

Very similar tester ClaRa.Examples.SteamPowerPlant_01 already runs through.

**Comment by casella** [comment]
Maybe a problem with long filenames?

Can you try to simulate
```
model M
  extends ClaRa.Examples.SteamPowerPlant_CombinedComponents_01;
end M;
```
and report what you get? This will generate much shorter filenames.

**Comment by AlesVojacek** [comment]
It looks good. It ran through. Do you know what is the limit length for the names of the models? The compilation fails for me by model name longer than circa 18 characters.

**Comment by casella** [comment]
@AlesVojacek this depends a lot on your environment, e.g. what is the length of the path where omc is installed and where you put your models.

@adrpo, we should try to fix this as well.

**Comment by casella** [comment]
@AlesVojacek reports by e-mail that the issue is gone with the latest nightly.

@AlesVojacek, please re-open in case you still face similar problems.
