### ISSUE TITLE
Internal Errors when checking the Modelica Standard Libary.

### ISSUE THREAD

**Issue by worc4021** [OpenModelica/OpenModelica#12721]
### Description

I spent ages trying to diagnose why my model was returning these internal errors until I realised that there are several components in the standard library that produce internal errors when checking the model. On first glance they all seem to have some form of visualisation.

### Steps to Reproduce

Simply press the "Check all models" button on the package `Modelica.Mechanics.MultiBody.Parts`. This produces the following four failures for me:

```
Checking: model Modelica.Mechanics.MultiBody.Parts.BodyShape... 0.09600000000000364 seconds -> FAILED! 
         
Error String: 
 
Error Buffer: 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyShape.mo:183:3-183:49:writable] Warning: The model can't be instantiated due to top-level outer element 'world', it may only be used as part of a simulation model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyShape.mo:183:3-183:49:writable] Warning: An inner declaration for outer component world could not be found and was automatically generated. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyShape.mo:183:3-183:49:writable] Notification: The diagnostics message for the missing inner is: No "world" component is defined. A default world 
component with the default gravity field will be used 
(g=9.81 in negative y-axis). If this is not desired, 
drag Modelica.Mechanics.MultiBody.World into the top level of your model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyShape.mo:125:3-130:25:writable] Notification: Top-level input 'color' has a binding equation and will not be accessible as an input of the model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyShape.mo:136:3-141:43:writable] Notification: Top-level input 'sphereColor' has a binding equation and will not be accessible as an input of the model. 
[C:/OM123/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFExpression.mo:1599:7-1600:100:writable] Error: Internal error NFExpression.makeSubscriptedExp: too few dimensions in ({0.0, 0.0, 0.0})[<r, 1>] to apply subscripts [2] 
 
#[-], 0.09600000000000364, Modelica.Mechanics.MultiBody.Parts.BodyShape 
------------------------------------------------------------------------- 
Checking: model Modelica.Mechanics.MultiBody.Parts.BodyBox... 0.0519999999999996 seconds -> FAILED! 
         
Error String: 
 
Error Buffer: 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyBox.mo:153:3-153:49:writable] Warning: The model can't be instantiated due to top-level outer element 'world', it may only be used as part of a simulation model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyBox.mo:153:3-153:49:writable] Warning: An inner declaration for outer component world could not be found and was automatically generated. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyBox.mo:153:3-153:49:writable] Notification: The diagnostics message for the missing inner is: No "world" component is defined. A default world 
component with the default gravity field will be used 
(g=9.81 in negative y-axis). If this is not desired, 
drag Modelica.Mechanics.MultiBody.World into the top level of your model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyBox.mo:39:3-40:77:writable] Notification: Top-level input 'color' has a binding equation and will not be accessible as an input of the model. 
[C:/OM123/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1313:9-1313:67:writable] Error: Internal error NFCeval.evalBinaryScalarProduct failed to evaluate ‘0.1 * 0.1‘ 
 
#[-], 0.0519999999999996, Modelica.Mechanics.MultiBody.Parts.BodyBox 
------------------------------------------------------------------------- 
Checking: model Modelica.Mechanics.MultiBody.Parts.BodyCylinder... 0.05299999999999727 seconds -> FAILED! 
         
Error String: 
 
Error Buffer: 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyCylinder.mo:155:3-155:49:writable] Warning: The model can't be instantiated due to top-level outer element 'world', it may only be used as part of a simulation model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyCylinder.mo:155:3-155:49:writable] Warning: An inner declaration for outer component world could not be found and was automatically generated. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyCylinder.mo:155:3-155:49:writable] Notification: The diagnostics message for the missing inner is: No "world" component is defined. A default world 
component with the default gravity field will be used 
(g=9.81 in negative y-axis). If this is not desired, 
drag Modelica.Mechanics.MultiBody.World into the top level of your model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/BodyCylinder.mo:35:3-37:62:writable] Notification: Top-level input 'color' has a binding equation and will not be accessible as an input of the model. 
[C:/OM123/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1313:9-1313:67:writable] Error: Internal error NFCeval.evalBinaryScalarProduct failed to evaluate ‘0.1 * 0.1‘ 
 
#[-], 0.05299999999999727, Modelica.Mechanics.MultiBody.Parts.BodyCylinder 
------------------------------------------------------------------------- 
Checking: model Modelica.Mechanics.MultiBody.Parts.FixedTranslation... 0.0870000000000033 seconds -> FAILED! 
         
Error String: 
 
Error Buffer: 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/FixedTranslation.mo:73:3-73:49:writable] Warning: The model can't be instantiated due to top-level outer element 'world', it may only be used as part of a simulation model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/FixedTranslation.mo:73:3-73:49:writable] Warning: An inner declaration for outer component world could not be found and was automatically generated. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/FixedTranslation.mo:73:3-73:49:writable] Notification: The diagnostics message for the missing inner is: No "world" component is defined. A default world 
component with the default gravity field will be used 
(g=9.81 in negative y-axis). If this is not desired, 
drag Modelica.Mechanics.MultiBody.World into the top level of your model. 
[C:/Users/Manuel/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/Mechanics/MultiBody/Parts/FixedTranslation.mo:59:3-64:25:writable] Notification: Top-level input 'color' has a binding equation and will not be accessible as an input of the model. 
[C:/OM123/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo:1084:9-1084:67:writable] Error: Internal error NFCeval.evalBinarySub failed to evaluate ‘0.0 - {0.0, 0.0, 0.0}‘ 
 
#[-], 0.0870000000000033, Modelica.Mechanics.MultiBody.Parts.FixedTranslation 
```
These were only the issues I found in the multi body package. Once I realised that there were internal problems with the basic components I ran the check all models on the top level Modelica libarary itself and it returned 98 failed models. 

`Number of classes checked / failed: 6309/98`

### Version and OS

 - OpenModelica Version: 1.23.1
 - OS: Windows 11 (verified same behaviour on ubuntu 24
 - Modelica: 4.0.0+maint

**Comment by casella** [comment]
@worc4021 thanks for reporting! This is strange, I don't have this problem with the latest 1.24.0 development version. Also, all MultiBody models of MSL 4.0.0 run successfully in 1.23.1, see [report](https://libraries.openmodelica.org/branches/v1.23/Modelica_4.0.0/Modelica_4.0.0.html). 

I guess it is just a problem with the check model feature, or are you also getting problems running your models?

I'll check the status with 1.23.1, in the meantime you can try with the latest nightly build.

**Comment by worc4021** [comment]
Hi @casella, Thank you for your suggestion. I tried this again on the 1.24-dev version of OME and this time all components in the mechanics library did check out correctly! :)

The report you linked is running the examples. Curiously enough, the examples didn't fail in 1.23. That was what led me to believe that it had something to do with the visualisation rather than the components, since in the examples the visualisation of e.g. the fixed translation is turned off and the default is on. I rechecked on 1.24-dev and in the whole MSL I now get 8 less failures:

`Number of classes checked / failed: 6309/90`

I suppose that concludes this issue then. On the [road map](https://github.com/OpenModelica/OpenModelica/milestones) the 1.24 release is only due by winter this year. Is the recommended approach to use nightly builds of OME over released/stable ones?

**Comment by casella** [comment]
> Hi @casella, Thank you for your suggestion. I tried this again on the 1.24-dev version of OME and this time all components in the mechanics library did check out correctly! :)

Good.

> The report you linked is running the examples. Curiously enough, the examples didn't fail in 1.23.

The checkModel() API doesn't do exactly the same things that are done when running simulations. Also, the checking is done on components, which may lack some parameter values, without being invalid, so you need special care for that.

> `Number of classes checked / failed: 6309/90`

I guess we should look into that 😅 
 
> I suppose that concludes this issue then. On the [road map](https://github.com/OpenModelica/OpenModelica/milestones) the 1.24 release is only due by winter this year. Is the recommended approach to use nightly builds of OME over released/stable ones?

That is up to you. The nightly build has all the latest fixes, but it may get broken at any time; the official releases undergo a beta release process to avoid last-minute issues. If you favour stability, stick to the official release. If you want to experiment, stay on the nightly build. I always use that.

One issue with the nightly on Linux is that once you've installed the latest one, there's no way back. This can be quite bad if the latest nightly is broken. On Windows, you can choose which nightly build you want to install.

If you need a stable release on Linux, without the guarantees of the beta release process, we could make one. That will basically be a copy of one specific nightly build, but it won't change on a daily basis.

**Comment by worc4021** [comment]
Hi @casella,

thank you very much for your offer! I'm ok using the nightly build on windows. Trying on linux was more out of desperation when my models didn't check out. But normally I'm able to use windows for all my model development.

Manuel

**Comment by casella** [comment]
@worc4021 I'll keep this open so we can cherry-pick this in the 1.23.2 patch release. Other users can't use the nightly for various reasons, I think we shouldn't leve this unresolved until December.
