### ISSUE TITLE
Experiment annotation ignored by OMC in Buildings.Fluid.HeatPumps.ModularReversible.Examples.AirToWater2D_OneRoomRadiator

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12728]
Please open `Buildings.Fluid.HeatPumps.ModularReversible.Examples.AirToWater2D_OneRoomRadiator` from the master branch of the Buildings library and simulate it.

Despite the model having
```modelica
  experiment(
      StartTime=0,
      StopTime=86400,
      Tolerance=1e-08),
```
both OMEdit and the CI simulate it with the default settings StopTime = 1, Interval = 0.002, Tolerance = 1e-6.

The flattened model with `--showAnnotation` indeed shows the experiment annotation, so that is lost somewhere downstream.

**Comment by casella** [comment]
Adding @deepak19015 and @AndreaBartolini to the loop

**Comment by adeas31** [comment]
Calling `getSimulationOptions` on `Buildings.Fluid.HeatPumps.ModularReversible.Examples.AirToWater2D_OneRoomRadiator` returns the default experiment annotation instead the experiment annotation stored in the model.

```
getSimulationOptions(Buildings.Fluid.HeatPumps.ModularReversible.Examples.AirToWater2D_OneRoomRadiator)
(0.0,1.0,1e-6,500,0.002)
```

@perost can you please take a look at it.
