### ISSUE TITLE
OMEdit 1.23.1: graphical connect broken (wrong port selected)

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OpenModelica#12734]
Hello,

I came across a strange connection bug with OMEdit. Only one subsystem is having problem (among a subpackage of half a dozen other models which can be edited fine). Did I miss something (duplicate name? Indeed, I'm using short names for components and parameters)?

### Description

In OMEdit 1.23.1, when editing the following electric circuit subsystem (LC filter), it is impossible to connect `Lr.n` to the `lf` external port. Indeed, clicking on  `Lr.n` instead starts a connection from `lf` (wrong port selected).

### Steps to Reproduce

Open the following `LCFilter_bug2.mo` model in OMEdit and try to initiate a connection starting from  `Lr.n` port:

```Modelica
model LCFilter_bug2 "LC filter"

  import Modelica.Units.SI;

  parameter SI.Inductance L "inductance";
  parameter SI.Resistance rL "series resistance of inductor";
  parameter SI.Capacitance C "capacitance";
  parameter SI.Resistance rC "series resistance of capacitor";
  parameter Boolean electrolytic=true "activation of electrolytic capacitor";


 Modelica.Electrical.Analog.Interfaces.NegativePin gnd "ground (DC bus -)" annotation(
    Placement(transformation(origin = {0, -100}, extent = {{-10, -10}, {10, 10}}), iconTransformation(origin = {0, -100}, extent = {{-10, -10}, {10, 10}})));
 Modelica.Electrical.Analog.Interfaces.PositivePin hf "high frequency voltage side" annotation(
    Placement(transformation(origin = {-100, 0}, extent = {{-10, -10}, {10, 10}}), iconTransformation(origin = {-100, 0}, extent = {{-10, -10}, {10, 10}})));
 Modelica.Electrical.Analog.Interfaces.PositivePin lf "filtered voltage side" annotation(
    Placement(transformation(origin = {100, 0}, extent = {{-10, -10}, {10, 10}}), iconTransformation(origin = {100, 0}, extent = {{-10, -10}, {10, 10}})));

 
  Modelica.Electrical.Analog.Basic.Inductor LL(L = L)  annotation(
    Placement(transformation(origin = {-50, 0}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Electrical.Analog.Basic.Capacitor CC(C = C)  annotation(
    Placement(transformation(origin = {40, -30}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Resistor Cr(R = rC)  annotation(
    Placement(transformation(origin = {40, -70}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
 Modelica.Electrical.Analog.Basic.Resistor Lr(R = rL)  annotation(
    Placement(transformation(origin = {-10, 0}, extent = {{-10, -10}, {10, 10}})));
equation
  connect(CC.n, Cr.p) annotation(
    Line(points = {{40, -40}, {40, -60}}, color = {0, 0, 255}));
  connect(Cr.n, gnd) annotation(
    Line(points = {{40, -80}, {0, -80}, {0, -100}}, color = {0, 0, 255}));
  connect(hf, LL.p) annotation(
    Line(points = {{-100, 0}, {-60, 0}}, color = {0, 0, 255}));
  connect(CC.p, lf) annotation(
    Line(points = {{40, -20}, {40, 0}, {100, 0}}, color = {0, 0, 255}));
  connect(LL.n, Lr.p) annotation(
    Line(points = {{-40, 0}, {-20, 0}}, color = {0, 0, 255}));

  annotation(
    Icon(graphics = {Line(origin = {40.0598, -90.0395}, rotation = -90,points = {{-90, 0}, {-56, 0}}, color = {0, 0, 255}), Line(points = {{-60, 0}, {-59, 6}, {-52, 14}, {-38, 14}, {-31, 6}, {-30, 0}}, color = {0, 0, 255}, smooth = Smooth.Bezier), Line(points = {{-30, 0}, {-29, 6}, {-22, 14}, {-8, 14}, {-1, 6}, {0, 0}}, color = {0, 0, 255}, smooth = Smooth.Bezier), Line(points = {{0, 0}, {1, 6}, {8, 14}, {22, 14}, {29, 6}, {30, 0}}, color = {0, 0, 255}, smooth = Smooth.Bezier), Line(origin = {38.976, -40.32}, rotation = -90,points = {{-6, 28}, {-6, -28}}, color = {0, 0, 255}), Line(origin = {38.976, -40.32}, rotation = -90,points = {{6, 28}, {6, -28}}, color = {0, 0, 255}), Line(origin = {120.046, 0.0549898},points = {{-90, 0}, {-18, -1}}, color = {0, 0, 255}), Line(origin = {39.9996, -136.438}, rotation = -90, points = {{-90, 0}, {-57, 0}, {-56.5, -40}, {-36, -40}}, color = {0, 0, 255}), Line(points = {{-90, 0}, {-60, 0}}, color = {0, 0, 255}), Rectangle(extent = {{-100, 100}, {100, -100}})}));
end LCFilter_bug2;
```

### Screenshots

Video record of OMEdit:

[LCFilter_bug_OM1.23.1.webm](https://github.com/user-attachments/assets/764924b3-1b14-4160-9989-98f78a96ccc0)

### Version and OS

 - OpenModelica Version: 1.23.1
 - OS: Debian 12 (bookworm)
 - Versions of used Modelica libraries if applicable: MSL 4.0.0

**Comment by pierre-haessig** [comment]
> I tried with the latest nigthly, in fact what happens to me if I start a connection from the `If` port and try to connect to the Lr.n port, I get connectd to the `hf` port instead.

How strange. Is it because I came with "funny" port names that connection got messed up?

**Comment by casella** [comment]
Is there anything funny in `hf` and `lf`? To me, they are component identifiers as any other. I changed them to `highFreq` and `lowFreq`, but I have the same issue.

**Comment by pierre-haessig** [comment]
> Is there anything funny in `hf` and `lf`? To me, they are component identifiers as any other. I changed them to `highFreq` and `lowFreq`, but I have the same issue.

Good to know. Indeed, `hf` and `lf` are legit identifiers, but because they are short names, I was wondering whether it could interact with some hidden reserved name. Now you have cleared this hypothesis.

It must be something else which is "funny" ;-)

**Comment by casella** [comment]
> Good to know. Indeed, `hf` and `lf` are legit identifiers, but because they are short names, I was wondering whether it could interact with some hidden reserved name. Now you have cleared this hypothesis.

Were that the case, the compiler would probably complain high and loud

> It must be something else which is "funny" ;-)

Indeed. @adeas31 will fix it when he comes back from his vacation.
