### ISSUE TITLE
Text unnecessarily cut (with ellipses) on a diagram in plotting perspective

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12754]
### Description
Text is unduly cut (with ellipses) in plotting perspective. In my example I have a two-row text: only the second row is cut (see video below).

https://github.com/user-attachments/assets/1fdb24d8-b5e4-47eb-a95e-aea0df4fa5ee

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]

OM 1.23.1  Win 11

**Comment by adeas31** [comment]
Post the test model.

**Comment by ceraolo** [comment]
OOPS...
I'll post it if I still have it on my desktop PC when I return from holiday after 17t,h  of August.

**Comment by adeas31** [comment]
PR #12983 fixes this issue. We fixed in #8383 that there will be no elided text for multiline text but the check was not good enough for all cases.
