### ISSUE TITLE
Resizing a diagram crashes OMEdit

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12753]
### Steps to Reproduce
1. load 
[CarMBlib.mo.txt](https://github.com/user-attachments/files/16390725/CarMBlib.mo.txt)
(there are two red boxes beccause of a needed library, but this is irrelevant: the issue is thjere even when the library is already loaded and we do not have the two red boxes)
2. in plotting perspective resize it
3. in diagram perspectiv delete all stuff except the red text
4. go in the plotting perspective => CRASH.
(see the enclosed video)

### Screenshots
Video:

https://github.com/user-attachments/assets/ea3e7c3a-5419-4c5a-9240-af693b4b0d3b

### Version and OS
OM 1.23.1
Win11

**Comment by adeas31** [comment]
Thanks @ceraolo. This one was very tough to debug. Took me some time to find the root cause.

**Comment by ceraolo** [comment]
I'm glad you found it. 
Solving crash issues greatly improves the program's usability.

**Comment by casella** [comment]
@adeas31 I'll keep this open until you've cherry-picked it on maintenance/v1.23
