### ISSUE TITLE
Add .bmo files to Choose Files dialog in OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12764]
Currently there is no way to load Base Modelica .bmo files in OMEdit, since the Choose File dialog only shows files with the .mo, .mol, and .ssp extension.

A new entry Base Modelica Files (*.bmo) should be added.

**Comment by adeas31** [comment]
Adding a new entry `Base Modelica Files (*.bmo)` is very easy. But how do you want to handle the BaseModelica files? Like normal Modelica files? Or do we need some special handling for them?

**Comment by casella** [comment]
Upon reading at the moment there's nothing special to be done: the front end should recognize them from the first header line.

**Comment by adeas31** [comment]
PR #12780 allows loading Base Modelica files.

**Comment by adeas31** [comment]
This is already done in #12780. Should be available with 1.24.0 (whenever it is ready).
If we need something more for Base Modelica we can handle that later.
