### ISSUE TITLE
OMEdit showing extreme latency in 1.23.1 on Windows

### ISSUE THREAD

**Issue by doug-harriman** [OpenModelica/OpenModelica#12771]
### Description

OMEdit operations have a significant latency.  
* Starting OMEdit takes 22 seconds from click to ready.
* Dragging a block from the standard library into diagram takes 5-6 seconds
* Deleting a block from a diagram takes 5-6 seconds.

I've attached two log file, see below.  Both show similar behavior.  The issue seems to be around library configuration/misconfiguration, looking for libraries and downloading things.  Note that I've upgraded several times (at least from 1.18 to 1.22 to 1.23) using the Windows installer without explicitly uninstalling beforehand.  There may be old configuration information in the system that is causing incorrect loads.  If so, that's indicative of an installer defect.

Pretty much any GUI operation seems to invoke a library check which causes the delay.

Any advice on how to clean up the library configuration to eliminate the issue is greatly appreciated.

### Steps to Reproduce

Per description, reproduction is simple _on my system_.   Unclear how it impacts others.

### Expected Behavior

* Starting OMEdit should be "fast".  I'd expect < 5 sec.
* Adding or deleting a block to a diagram should be < 200 ms.  It should feel instantaneous.

### Logs
[omedit-log-add-block.txt](https://github.com/user-attachments/files/16564941/omedit-log-add-block.txt)
[omedit-log-startup.txt](https://github.com/user-attachments/files/16564942/omedit-log-startup.txt)

### Version and OS

* Runing on Windows 10, 64-bit.
* Using version 1.23.1.  
* Observed with 1.22
* Believe that 1.18 operated as expected.

**Comment by adeas31** [comment]
See #11920

**Comment by doug-harriman** [comment]
> See #11920 

I downloaded the nightly build for 10-August, which should have commit 9f1b242 with fixes for `getModelInstance()`.  I did not observe any change in behavior.   There was still significant latency on the operations described above. 

Did you have a look at the log files I posted?  I'm still seeing the `Scripting Error` log messages.  Wondering if there are additional issues related to constantly looking for packages.

**Comment by adeas31** [comment]
> I downloaded the nightly build for 10-August, which should have commit https://github.com/OpenModelica/OpenModelica/commit/9f1b2421d472497074e7b085746e1f8695ba8fc9 with fixes for getModelInstance(). I did not observe any change in behavior. There was still significant latency on the operations described above.

The only latency issue that is fixed is when you add a new component (drag n drop).

> Did you have a look at the log files I posted? I'm still seeing the Scripting Error log messages. Wondering if there are additional issues related to constantly looking for packages.

I looked at the log files. It seems you don't have libraries installed and cached libraries are used to install them. But I don't know why its installing them again and again. Maybe it has something to do with the MODELICAPATH, you have set it to `C:/ModelicaStandardLibrary_v4.0.0`. You can try to reset this path in `Tools->Options->Libraries->MODELICAPATH`.

**Comment by doug-harriman** [comment]
@adeas31 - Thank you for the advice!  I had assumed since that the standard library was installed there and had worked previously (1.18?) that this issue was elsewhere.  I removed all libraries, cleaned up the path, then reinstalled the libraries.  Now all is working as expected.
