### ISSUE TITLE
Potential Memory Leak in File Reload 

### ISSUE THREAD

**Issue by JamesZhanchunyuan** [OpenModelica/OpenModelica#12818]
### Description

We are currently developing a web-based Modelica IDE and have encountered a potential memory leak issue while editing the icons of components.

### Steps to Reproduce

The problem can be reproduced using a simple Modelica model defined as follows:
```modelica
model ReloadMemoryLeak
equation
  annotation(Icon(graphics = {Polygon(points = {{0, 38}, {38, -38}, {-38, -38}})}));
end ReloadMemoryLeak;
``` 
The issue arises when performing the following file reload logic. Executing these commands results in the omc process potentially increasing by more than 100MB of memory:
```modelica
loadModel(Modelica);
// repeat the following commands
deleteClass(ReloadMemoryLeak);
loadFile(ReloadMemoryLeak.mo);
getInheritedClasses(ReloadMemoryLeak);
getComponents(ReloadMemoryLeak);
``` 
Additionally, modifying the Model source code consistently and using reloadClass instead of the combination of deleteClass and loadFile produces the same effect.

### Expected Behavior

When reloading, the memory usage should remain almost unchanged as it did in version 1.20. This issue was first noticed after upgrading to version 1.23, where a significant increase in memory usage was observed during the reload operations. 

### Version and OS

 - OpenModelica Version: v1.23.1
 - OS: Debian 12

**Comment by JamesZhanchunyuan** [comment]
Further checks show the memory leak is not from reloads but triggered by specific APIs. Only `getInheritedClasses` and `getComponents` increase memory usage; other APIs don't.

**Comment by JamesZhanchunyuan** [comment]
I wrote a Python script that can be used to better reproduce this issue.
```python
import re
import time
import psutil
from OMPython import OMCSessionZMQ

# Define and write initial content to the model file
content = """
model ReloadMemoryLeak
equation
annotation(Icon(graphics = {Polygon(origin = {0, 0}, points = {{0, 38}, {38, -38}, {-38, -38}})}));
end ReloadMemoryLeak;
"""
file_path = "ReloadMemoryLeak.mo"

with open(file_path, 'w') as file:
    file.write(content)

def modify_mo_file(file_path):
    global content
    # Increment the first number found by 1 and write back to file
    with open(file_path, 'r+') as file:
        content = re.sub(r'\d+', lambda x: str(int(x.group()) + 1), content, 1)
        file.seek(0)
        file.write(content)
        file.truncate()

def get_omc_memory_usage():
    # Sum memory usage for all 'omc' processes
    total_memory = sum(proc.info['memory_info'].rss / 1024**2 for proc in psutil.process_iter(['name', 'memory_info']) if proc.info['name'] == 'omc')
    print(f"Total memory used by 'omc' processes: {total_memory:.2f} MB")

omc = OMCSessionZMQ()
omc.sendExpression("loadModel(Modelica)")
omc.sendExpression(f"loadFile(\"{file_path}\")")
for i in range(10):
    modify_mo_file(file_path)
    omc.sendExpression("reloadClass(ReloadMemoryLeak)")
    omc.sendExpression("getInheritedClasses(ReloadMemoryLeak)")
    omc.sendExpression("getComponents(ReloadMemoryLeak)")
    get_omc_memory_usage()
    time.sleep(1)
``` 
Below are the results of running the script with different versions of omc.
```
OpenModelica 1.20.0:
Total memory used by 'omc' processes: 408.92 MB
Total memory used by 'omc' processes: 439.44 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB
Total memory used by 'omc' processes: 491.47 MB

OpenModelica 1.23.1:
Total memory used by 'omc' processes: 425.93 MB
Total memory used by 'omc' processes: 447.94 MB
Total memory used by 'omc' processes: 489.22 MB
Total memory used by 'omc' processes: 597.53 MB
Total memory used by 'omc' processes: 634.55 MB
Total memory used by 'omc' processes: 643.06 MB
Total memory used by 'omc' processes: 721.17 MB
Total memory used by 'omc' processes: 733.99 MB
Total memory used by 'omc' processes: 842.70 MB
Total memory used by 'omc' processes: 929.32 MB
``` 
It is now clear that this is closely related to the nfAPI, as the issue also occurs in versions as early as 1.19.2 when the command line parameter -d=nfAPI is set.

**Comment by perost** [comment]
What happens if you increase the number of iterations? The memory consumption will heavily depend on the whims of the compiler's garbage collector and how much memory it decides to reserve, so 10 iterations is not necessarily enough to decide if it's a memory leak or just the GC thinking it needs more memory.

For me the memory consumption increases from around 450MB to 570MB fom the first ~40 iterations, then holds steady for another 40 iterations, then increases to 650MB for the next 30, and then stays exactly the same for the next few thousands (until I stopped it).

**Comment by JamesZhanchunyuan** [comment]
After increasing the number of iterations, the memory actually keeps increasing. I've also found that the issue persists unless time.sleep(1) is removed; at least a minimal amount of sleep is needed to observe the memory growth, which is puzzling and unexplainable.

**Comment by JamesZhanchunyuan** [comment]
> What happens if you increase the number of iterations? The memory consumption will heavily depend on the whims of the compiler's garbage collector and how much memory it decides to reserve, so 10 iterations is not necessarily enough to decide if it's a memory leak or just the GC thinking it needs more memory.
> 
> For me the memory consumption increases from around 450MB to 570MB fom the first ~40 iterations, then holds steady for another 40 iterations, then increases to 650MB for the next 30, and then stays exactly the same for the next few thousands (until I stopped it).

After increasing the number of iterations, the memory actually keeps increasing. I've also found that the issue persists unless time.sleep(1) is removed; at least a minimal amount of sleep is needed to observe the memory growth, which is puzzling and unexplainable.

**Comment by perost** [comment]
> > What happens if you increase the number of iterations? The memory consumption will heavily depend on the whims of the compiler's garbage collector and how much memory it decides to reserve, so 10 iterations is not necessarily enough to decide if it's a memory leak or just the GC thinking it needs more memory.
> > For me the memory consumption increases from around 450MB to 570MB fom the first ~40 iterations, then holds steady for another 40 iterations, then increases to 650MB for the next 30, and then stays exactly the same for the next few thousands (until I stopped it).
> 
> After increasing the number of iterations, the memory actually keeps increasing. I've also found that the issue persists unless time.sleep(1) is removed; at least a minimal amount of sleep is needed to observe the memory growth, which is puzzling and unexplainable.

Yeah, that's really weird. I just used a normal .mos script instead of your python script so I didn't have any sleep between the iterations, but I can't imagine why that would affect anything.

The API calls also have very little in common, `getInheritedClasses` uses the new frontend (if `-d=nfAPI` is set) while `getComponents` uses the old one and `reloadClass` uses neither. Can you reproduce the issue using only one of those calls?

I also doubt it would help, but could you maybe try the nightly build instead of 1.23.1? Or maybe even build it from source instead, in case there's some issue with the Debian builds (I use Arch Linux but of course build it myself).

**Comment by bilderbuchi** [comment]
> Or maybe even build it from source instead, in case there's some issue with the Debian builds (I use Arch Linux but of course build it myself).

Coincidentally, I just tried to get that going using the devcontainer setup, to see if it's easy to add ASAN to the build to maybe catch a memory leak (or try to let `clang-tidy` help catch issues). However, I run into build errors ("ld: DWARF error: invalid or unhandled FORM value: 0x23" and some `Absyn`-related errors) using clang 14.0.0, but I didn't investigate further so far.

**Comment by perost** [comment]
> > Or maybe even build it from source instead, in case there's some issue with the Debian builds (I use Arch Linux but of course build it myself).
> 
> Coincidentally, I just tried to get that going using the devcontainer setup, to see if it's easy to add ASAN to the build to maybe catch a memory leak (or try to let `clang-tidy` help catch issues). However, I run into build errors ("ld: DWARF error: invalid or unhandled FORM value: 0x23" and some `Absyn`-related errors) using the clang 14.0.0 kit, but I didn't investigate further so far.

That's odd, I haven't seen any such issues with clang before, and 14.0.0 has been out for a while. But it's unlikely that ASAN will be of much help since the GC tend to confuse such tools.

**Comment by bilderbuchi** [comment]
> > > Or maybe even build it from source instead, in case there's some issue with the Debian builds (I use Arch Linux but of course build it myself).
> > 
> > 
> > Coincidentally, I just tried to get that going using the devcontainer setup, to see if it's easy to add ASAN to the build to maybe catch a memory leak (or try to let `clang-tidy` help catch issues). However, I run into build errors ("ld: DWARF error: invalid or unhandled FORM value: 0x23" and some `Absyn`-related errors) using the clang 14.0.0 kit, but I didn't investigate further so far.
> 
> That's odd, I haven't seen any such issues with clang before, and 14.0.0 has been out for a while. But it's unlikely that ASAN will be of much help since the GC tend to confuse such tools.

It seems that I ran into #12476 at least in part, let's see, now the build continues... ^.^ 

Bummer to hear about the GC complicating things. 😞

**Comment by JamesZhanchunyuan** [comment]
Despite testing across different operating systems and compiling the latest code from the master branch, the problem remains unresolved. After analyzing the caching implementation, I introduced a modification in #12826 , which temporarily addresses the issue, although it may not represent the optimal solution.

**Comment by perost** [comment]
> Despite testing across different operating systems and compiling the latest code from the master branch, the problem remains unresolved. After analyzing the caching implementation, I introduced a modification in #12826 , which temporarily addresses the issue, although it may not represent the optimal solution.

Yeah, the whole cache implementation seems rather scetchy to me, it shouldn't be up to the functions using it to maintain it. Maybe we'll reimplement the whole thing later, but for now I merged your PR since it seems reasonable enough.
