### ISSUE TITLE
MSL battery StackData record fails at checking:  Internal error 

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#12837]
### Description

while checking model Modelica.Electrical.Batteries.ParameterRecords.StackData using MSL 4.0 and OME v1.23.1 (64-bit)
I got the following output 

`[C:/OM123/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFRangeIterator.mo:245:11-246:61:writable] Error: Internal error NFRangeIterator.hasNext got invalid range Ns `

This concerns also several components of the Battery package of MSL4.0

**Comment by bilderbuchi** [comment]
Could this be an instance of #12717, due to the `BaseStackData.cellData[Ns, Np]` array?

**Comment by arouhan** [comment]
Indeed, looks like the same error as  https://github.com/OpenModelica/OpenModelica/issues/12717.

**Comment by bilderbuchi** [comment]
Then you can close this issue as a duplicate.
