### ISSUE TITLE
Unqualified import statement fails

### ISSUE THREAD

**Issue by MarcusHoffmannGH** [OpenModelica/OpenModelica#12844]
### Description

The unqualified import statement fails within the top level package. The qualified version works and unqualified version works with Dymola.

### Steps to Reproduce

See the following package definition:
```Modelica
package UnqualifiedImportFails

  import UnqualifiedImportFails.Units.*;
  // import UnqualifiedImportFails.Units.Pressure;

  package ImportTest

    model test
      parameter Pressure p=1;
    end test;

  end ImportTest;

  package Units
    type Pressure = Real;
  end Units;

end UnqualifiedImportFails;
```
### Expected Behavior

The model "test" should be able to be simulated. But there is the following error:
```
Translation Error
[UnqualifiedImportFails: 4:3-4:40]: [Import UnqualifiedImportFails.Units not found in scope <top>.]
```
If you use the qualified import
import UnqualifiedImportFails.Units.Pressure;
"test" can be translated and simulated.

### Version and OS

 - OpenModelica Version: v1.23.1
 - OS: Windows 10, 64 bit

**Comment by perost** [comment]
It seems to specifically be when having an unqualified import referencing a package directly in the package itself. If the import is instead placed inside e.g. `ImportTest` or `test` then it works fine.
