### ISSUE TITLE
Automatic parallelization doesn't work on Windows

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#12848]
### Description

When compiling with parallelization:

![image](https://github.com/user-attachments/assets/bec1d024-9cce-47cb-b776-6bbfe0765d7d)

linker wants to link with non existing `-lboost_system`

```
C:/OMDev/tools/msys/ucrt64/bin/ld: cannot find -lboost_system: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
mingw32-make: *** [RLCCircuit.makefile:37: omc_main_target] Error 1
```

Seems like the Windows installer doesn't copy the needed files.

**Comment by bilderbuchi** [comment]
Close as duplicate of #8776?

**Comment by adrpo** [comment]
Ouch, yes, is a duplicate of that.
