### ISSUE TITLE
Invalid generated code because the NB generates a Complex residual for an algebraic loop.

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12880]
Please check [PowerGrids.Examples.IEEE14bus.IEEE14busPowerFlow]( https://libraries.openmodelica.org/branches/newInst-newBackend/PowerGrids/files/PowerGrids_PowerGrids.Examples.IEEE14bus.IEEE14busPowerFlow.err) with the NB. The C code compilation fails because of invalid C code. According to @phannebohm (see [comment](https://github.com/OpenModelica/OpenModelica/issues/12628#issuecomment-2348938027)) this happens because the NB generates a Comples residual for an algebraic loop. The same happens with [PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad](https://libraries.openmodelica.org/branches/newInst-newBackend/PowerGrids/files/PowerGrids_PowerGrids.Electrical.Test.TestOneBusTransmissionLineWithBreakersOneLoad.err).

**Comment by casella** [comment]
The general idea is that there is no benefit at all at keeping Complex records as such when generating code. In fact, doing so may prevent from doing further symbolic manipulation and simplifications that are possible if all Complex equations are transformed into scalar ones, see, e.g., the discussion in [#4354](https://trac.openmodelica.org/OpenModelica/ticket/4354).

To achieve this goal, the NB needs to:
1. Inline the function calls coming from the application of operators to operator records, which have `annotation(Inline = true)` 
2. Split record equations `r1 = r2` into their constituents, i.e.., `r1.re = r2.re`, `r1.im = r2.im`

As I understand this was implemented in the OB a long time ago. Do we have these provisions in the OB as well? If not, can you please implement them? They are essential to get efficient code for models using the Complex package.

Thanks!

**Comment by phannebohm** [comment]
The NB already removes `record`-equations as much as possible.

However there may be functions that cannot be inlined, in which case the `FunctionAlias` module creates alias equations `$FUN_1 = functionCall()`. These alias equations should be moved to inner equations if they are part of an algebraic loop, but currently Tearing does not do that. I guess we can try to do that as a first stage in minimal Tearing.

**Comment by casella** [comment]
> The NB already removes `record`-equations as much as possible.

Good.
 
> However there may be functions that cannot be inlined, in which case the `FunctionAlias` module creates alias equations `$FUN_1 = functionCall()`.

Hmm, I though there would be none, but I checked the flattened model and I found the function Modelica.Math.atan3() function, which has a non-trivial algorithm. This is called by Modelica.Complex.Math.arg(), which however is only used to compute start attributes, so it should not get involved in algebraic loops.

I don't yet have a nightly build so I can't check this with the debugger. Could you please check who is $FUN_1 for the `PowerGrids.Examples.IEEE14bus.IEEE14busPowerFlow` model?

**Comment by phannebohm** [comment]
The problematic equations are `$RES_SIM_364` and `$RES_SIM_369`. From `--newBackend -d=dumpSimCode` I get
```
  (3698) Nonlinear System (size = 4, homotopy = false, mixed = false, torn = true)
  --Iteration Vars:{L1to5.YB_actual.re, L1to5.YA_actual.im, L1to5.YB_actual.im, L1to5.YA_actual.re}
  --(3696) 0 = if $SEV_6 then (Complex(0.0, 5.167e-4) - L1to5.YB_actual) - $RES_SIM_369 else if $SEV_7 then (Complex(6.943660319567153e-7, 5.195497351085109e-4) - L1to5.YA_actual) - $RES_SIM_369 else if $SEV_8 then (Complex(6.943660319567153e-7, 5.195497351085109e-4) - L1to5.YB_actual) - $RES_SIM_369 else (Complex(0.0, 0.0) - L1to5.YA_actual) - $RES_SIM_369
  --(3697) 0 = if $SEV_6 then (Complex(0.0, 5.167e-4) - L1to5.YA_actual) - $RES_SIM_364 else if $SEV_7 then (Complex(0.0, 0.0) - L1to5.YB_actual) - $RES_SIM_364 else if $SEV_8 then (Complex(0.0, 0.0) - L1to5.YA_actual) - $RES_SIM_364 else (Complex(0.0, 0.0) - L1to5.YB_actual) - $RES_SIM_364
```
which looks like it can be split into elementwise equations. Perhaps we don't yet do it for `if`-expressions. I'll have a closer look.

BTW, I also see these two systems
```
(3521) Nonlinear System (size = 934, homotopy = false, mixed = false, torn = true)
(2558) Nonlinear System (size = 32, homotopy = false, mixed = false, torn = true)
```
which have a bunch of alias equations inside. TODO: check Alias module!

**Comment by casella** [comment]
> The problematic equations are `$RES_SIM_364` and `$RES_SIM_369`. From `--newBackend -d=dumpSimCode` I get
> 
> ```
>   (3698) Nonlinear System (size = 4, homotopy = false, mixed = false, torn = true)
>   --Iteration Vars:{L1to5.YB_actual.re, L1to5.YA_actual.im, L1to5.YB_actual.im, L1to5.YA_actual.re}
>   --(3696) 0 = if $SEV_6 then (Complex(0.0, 5.167e-4) - L1to5.YB_actual) - $RES_SIM_369 else if $SEV_7 then (Complex(6.943660319567153e-7, 5.195497351085109e-4) - L1to5.YA_actual) - $RES_SIM_369 else if $SEV_8 then (Complex(6.943660319567153e-7, 5.195497351085109e-4) - L1to5.YB_actual) - $RES_SIM_369 else (Complex(0.0, 0.0) - L1to5.YA_actual) - $RES_SIM_369
>   --(3697) 0 = if $SEV_6 then (Complex(0.0, 5.167e-4) - L1to5.YA_actual) - $RES_SIM_364 else if $SEV_7 then (Complex(0.0, 0.0) - L1to5.YB_actual) - $RES_SIM_364 else if $SEV_8 then (Complex(0.0, 0.0) - L1to5.YA_actual) - $RES_SIM_364 else (Complex(0.0, 0.0) - L1to5.YB_actual) - $RES_SIM_364
> ```
> 
> which looks like it can be split into elementwise equations. Perhaps we don't yet do it for `if`-expressions. I'll have a closer look.

Please do. The if-equations have record equations on both branches, so this shouldn't be a problem.

> BTW, I also see these two systems
> 
> ```
> (3521) Nonlinear System (size = 934, homotopy = false, mixed = false, torn = true)
> (2558) Nonlinear System (size = 32, homotopy = false, mixed = false, torn = true)
> ```
> 
> which have a bunch of alias equations inside. TODO: check Alias module!

Interesting. At the end of the day, if a sparse solver is used this is not such a big deal, but yes, aliases should preferably be handled at compile time. Would you like to open a separate ticket to track this specific issue?

**Comment by phannebohm** [comment]
FYI, we actually have a flag for dumping the inline steps: `-d=dumpBackendInline` :tada:

**Comment by phannebohm** [comment]
Well that's sort of what I'm going to do, not *before* we split the record but *while* we do, insignificant detail I guess.

**Comment by casella** [comment]
@phannebohm is working on that with an incremental approach

**Comment by casella** [comment]
Very good! 

newInst-newBackend job [#8757](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/8757) now running, can't wait to see the results.

**Comment by phannebohm** [comment]
Here it is: https://libraries.openmodelica.org/branches/history/newInst-newBackend/2024-12-03%2003:59:39..2024-12-04%2015:46:06.html

We didn't get far in terms of compiled models, only 6 more compile. But there are none left with this issue's problem.

**Comment by casella** [comment]
Quite some improvements on PowerGrids_dev as well. 77/87 now compile with the NB.
