### ISSUE TITLE
inner prefix lost when copying and pasting

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12899]
Use case: I wanted to copy a World model with some non-default parameter settings into another model. I did it by copy and paste, and I got weird behaviour, until I realized that the pasted world model did not have the inner modifier.

I guess such modifier should be kept when copying and pasting.

**Comment by abuntrock** [comment]
We from Bosch Rexroth are also interested in a fix to this issue.

**Comment by abuntrock** [comment]
Works perfect with today's nightly. Thanks a lot.

**Comment by adeas31** [comment]
It might be that `constrainedby` clause is not copied correctly but I haven't tested it. You can try copy paste of component that has `constrainedby` clause.
