### ISSUE TITLE
Modelica version of 1D thermal conduction scalable models takes almost 100 time more time to compile the C code than equation-based version

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12922]
@perost, I noticed another interesting thing by looking a the[ LargeTestSuite_NB report](https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html).

The OneDHeatTransferFD models are very similar to the OneDHeatTransferModelica models, except that the former are written directly in terms of array equations, while the latter are written using arrays of basic connected components.

If array-preserving methods are properly used, I would expect the compilation performance of the two not to differ too much. Instead, the ones using Modelica sub-components take almost two orders of magnitude more time to compile the generated C code.

Could you briefly investigate why that is the case?

Thanks!

**Comment by perost** [comment]
It's because the Modelica ones uses connections while the FD ones don't, and the connections are scalarized by default. If you use `-d=arrayConnect` then the Modelica ones take no time at all to compile.

The result might not be correct since the array preserving connection handling has a lot of issues, but it might work well in this case since the connections are very simple.

**Comment by casella** [comment]
Thanks @perost, I forgot about that. When you say "issues" do you mean it could fail, or it could produce wrong connection equations?

**Comment by perost** [comment]
> When you say "issues" do you mean it could fail, or it could produce wrong connection equations?

Both, but incorrect connect equations are the more common issue I think, and the reason why we don't use it by default.

**Comment by casella** [comment]
Fixed by OpenModelica/OpenModelicaLibraryTesting#127

**Comment by casella** [comment]
BTW, do you have plans to improve this?

**Comment by perost** [comment]
> BTW, do you have plans to improve this?

Not at the moment, the array connection handling is based on arcane set magic while handling arrays with the normal one is hard. At some point we might need to do something about it, but there's nothing planned.

**Comment by casella** [comment]
OK. It's not top priority at the moment. Could be later on with OpenSCALING, perhaps.
