### ISSUE TITLE
The NB fails during causalization of DistributionSystemLinear models

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12926]
All the `DistributionSystemLinear_N_XX_M_XX` models of ScalableTestSuite silently fail in the NB after running Partitiong, see [report](https://libraries.openmodelica.org/branches/heavy_tests/ScalableTestSuite_NB/files/ScalableTestSuite_NB_ScalableTestSuite.Electrical.DistributionSystemAC.ScaledExperiments.DistributionSystemLinear_N_10_M_10.err). This should be investigated.

**Comment by phannebohm** [comment]
I think it's the Causalize module on the simulation partition.

**Comment by casella** [comment]
Now it fails with some error message:
```
Error: Internal error NBSlice.resolveSkips failed because skip of 2 for type Real is invalid.
Error: Internal error NBSlice.resolveDependency failed for: load[$i1, $i2].sensor.s.i.im.
Error: Internal error NBAdjacency.Matrix.upgradeRow failed for:
[FOR-] (100) ($RES_SIM_173)
[----] for {$i1 in 1:10, $i2 in 1:10} loop
[----]   [SCAL] (1) (load[$i1, $i2].sensor.s.i + load[$i1, $i2].p.i).re = 0.0 ($RES_SIM_174)
[----] end for;
```

**Comment by casella** [comment]
@kabdelhak any clue?

**Comment by phannebohm** [comment]
Weird that we don't distribute the real part:
```
(load[$i1, $i2].sensor.s.i + load[$i1, $i2].p.i).re
```
should become
```
load[$i1, $i2].sensor.s.i.re + load[$i1, $i2].p.i.re
```
right?

**Comment by casella** [comment]
Now the model fails during C compile time.
