### ISSUE TITLE
Generated code does not compile with latest nightly-build

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#12945]
### Description

windows nightly build, see: https://github.com/OpenModelica/OpenModelicaLibraryTesting/actions/runs/11067454279/job/30751855594

`HelloWorld.c:163:5: error: incompatible function pointer types initializing 'const void (*)(DATA *, threadData_t *)' (aka 'const void (*)(struct DATA *, struct threadData_s *)') with an expression of type 'void (DATA *, threadData_t *)' (aka 'void (struct DATA *, struct threadData_s *)') [-Wincompatible-function-pointer-types]`

**Comment by arun3688** [comment]
@adrpo may be this issue https://github.com/OpenModelica/OpenModelica/issues/12749 is related with this
