### ISSUE TITLE
Show parameters in conditional component masks

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#12959]
### Steps to Reproduce
Consider [TestCond.mo.txt](https://github.com/user-attachments/files/17193170/TestCond.mo.txt)

Block gain1 is shown inactive, because the selecting boolean variable has as default value true.
If I double click on gain1, I cannot change the gain value. This is not good. 
In fact, when I write a model containing conditional components I would like to have access to submodel parameters through the GUI, even if by default they are not active. 
This would ease library development, since obviously the submodel can become active when instantiation founds that it has to. Other tools already do what proposed in this ticket.

### Expected Behavior
When double-clicking on gain1 I should have access to k, to see or change its value.

### Screenshots
![image](https://github.com/user-attachments/assets/6a52ffa4-8bcb-46fa-a695-8e878207c421)
![image](https://github.com/user-attachments/assets/76b8c36e-5a43-40d0-9813-9ccf9b5eba4d)

### Version and OS

OM 1.23.1

**Comment by adeas31** [comment]
The information about the conditional components is not included in the instance tree. This is intentional to reduce the size of the instance tree. We can of course include this information. @perost what do you think?

**Comment by perost** [comment]
> The information about the conditional components is not included in the instance tree. This is intentional to reduce the size of the instance tree. We can of course include this information. @perost what do you think?

Disabled components are part of the JSON from `getModelInstance`, but the information you get about them is limited since they're not instantiated. Just instantiating them and adding the to the JSON is not really an option, since there exists large library models that use conditional components to the extent that instantiating all of the components can make them several times slower.

So we need some other solution that would let us instantiate things only on demand, but that's hard to do with the design we've chosen.

**Comment by ceraolo** [comment]
ok. This is not critical for me. 

Much more important is #11920. 
I thought to that one because maybe there is a relation between the two (in both cases we need to access parameters).

**Comment by casella** [comment]
> ok. This is not critical for me.

In fact, you can now right-click on the diagram, choose "Parameters" and activate the disabled components easily to access their parameter values.

**Comment by ceraolo** [comment]
> > ok. This is not critical for me.
> 
> In fact, you can now right-click on the diagram, choose "Parameters" and activate the disabled components easily to access their parameter values.

What OM release? Doing this with 1.23.1 with the example in this ticket has issues

**Comment by casella** [comment]
This feature was introduced in 1.23.0, see #4408, but indeed it doesn't work properly. I'll open another ticket about that.
