### ISSUE TITLE
Incorrect behaviour of OMEdit with parameter-based conditional components

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12967]
Follow-up of #12959. 

Please consider the attached [TestCond.mo](https://github.com/user-attachments/files/17230958/TestCond.mo.txt). When first opening the diagram, `select = true`, so the upper gain block is active and its parameter `k` can be modified.

If I right-click on the diagram and set `select = false`, the upper gain block is disabled, but the lower gain block is not fully enabled: its connectors are visible, its parameter `k` can be modified, but the rest of the icon is still grayed off.

If I now set `select = true` again, the same happens to the upper block: input and output connectors are visible, `k` can be modified, but the rest of the icon is greyed out.

@adeas31 I guess the process of updating the icons when changing parameters that influence their activation/visibility is not fully complete. Can you please check?

Thanks!

**Comment by adeas31** [comment]
Fixed with #12975 and ported to maintenance/v1.24 with #12976.

**Comment by casella** [comment]
Thanks @adeas31!

@ceraolo please check with the next nightly build.
