### ISSUE TITLE
Question: OMC API call to get value of short class definition (record)

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#13013]
### Description

I do not know if there is an API call to get the value of a replaceable short class definition. I found nothing regarding this on the scripting API help pages and GitHub but maybe I searched with the wrong keywords.

### Steps to Reproduce

1. Load the following modelica model:
```modelica
package GetExtendsNames
  model TopLevelClass
    extends GetExtendsNames.ExtendedClass(realParam=20, redeclare record AnotherRecord=SomeRecord);
  
  replaceable record SomeRecord = GetExtendsNames.BaseRecord;
  end TopLevelClass;

  model ExtendedClass
    parameter Real realParam = 10;
    replaceable record AnotherRecord = GetExtendsNames.BaseRecord;
  end ExtendedClass;

  model BaseRecord
  end BaseRecord;

end GetExtendsNames;
```
2. I do not know of an API call that has the input `GetExtendsNames.TopLevelClass.SomeRecord` and the output `GetExtendsNames.BaseRecord`.

### Expected Behavior

There is an OMC API call which outputs the value of a replaceable short class definition.

### Version and OS

 - OpenModelica Version: 1.24.0
 - OS: Windows 11, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
```
getElements(GetExtendsNames.TopLevelClass)
{{"cl", "record", GetExtendsNames.BaseRecord, SomeRecord, "", "public", false, false, false, true, "unspecified", "none", "unspecified", $Any, {}}}
```

The first output argument is either `co` or `cl`. `cl` tells that its a short class definition. The 3rd argument is the type of the class.

**Comment by abuntrock** [comment]
Thanks a lot.
