### ISSUE TITLE
getExtendsModifierNames does not include names of redeclare modifiers

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#13012]
### Description

Maybe this is on purpose, but the OMC API call `getExtendsModifierNames` does not return the name of redeclare modifiers in extent statements.

### Steps to Reproduce

1. Load the following modelica package:
```modelica
package GetExtendsNames
  model TopLevelClass
    extends GetExtendsNames.ExtendedClass(realParam=20, redeclare record AnotherRecord=SomeRecord);
  
  replaceable record SomeRecord = GetExtendsNames.BaseRecord;
  end TopLevelClass;

  model ExtendedClass
    parameter Real realParam = 10;
    replaceable record AnotherRecord = GetExtendsNames.BaseRecord;
  end ExtendedClass;

  model BaseRecord
  end BaseRecord;

end GetExtendsNames;
```
2. Execute the following OMC API call: `getExtendsModifierNames(GetExtendsNames.TopLevelClass, GetExtendsNames.ExtendedClass)`.
The output is `{realParam}`.

### Expected Behavior

I would expect the output of the OMC API call to be `{realParam, AnotherRecord}`.

### Version and OS

 - OpenModelica Version: 1.24.0
 - OS: Windows 11 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
> That should be easy to fix, but it's used by OMEdit. @adeas31, any comment on whether changing this would cause issues for OMEdit, or maybe even be helpful?

OMEdit is using `getModelInstance` now. These are only used by OMEdit if `Disable new instance-based graphical editing of models` is checked. The idea is to completely move to the new instance API.

I think @abuntrock can also start using `getModelInstance` since most of the APIs in `Interactive.mo` have limitations.

Related to #13013

**Comment by abuntrock** [comment]
I have to admit that I was reluctant to switch to `getModelInstance` since that means some rework in our backend (we use the OMC API for continuous integration style checks of our models). But since you understandably will only develop this function instead of all the other ones it might be time for us to switch.

**Comment by abuntrock** [comment]
@adeas31 Maybe I can ask one question here then. I cannot change `getModelInstance` so that it only provides information about the input class and not also about all extended and instantiated classes right?

**Comment by adeas31** [comment]
I guess `getModelInstanceAnnotation` does that but I am not sure. @perost knows more.

**Comment by perost** [comment]
> I guess `getModelInstanceAnnotation` does that but I am not sure. @perost knows more.

Not really, that just provides information about the annotation and not much more.

**Comment by abuntrock** [comment]
And `getModelInstanceAnnotation` also provides output regarding the annotations not only for the input classes but also for inherited ones
