### ISSUE TITLE
Units on parameter window: unit over final unit?

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13030]
### Description

Change units when using a Type with embedded final unit in OMedit. 

### Steps to Reproduce

OMedit shows the definition of the parameter instead of empty cell:
<img width="757" alt="image" src="https://github.com/user-attachments/assets/5f679996-450e-4f10-a919-8b46f569b46a">

<img width="411" alt="image" src="https://github.com/user-attachments/assets/ad884ea8-25cb-4f3d-ae44-e2cf510bed44">

But if I put a predefined value, this value is shown:
<img width="794" alt="image" src="https://github.com/user-attachments/assets/aabd24e3-ab31-4dd3-bc12-2660658936c2">

<img width="350" alt="image" src="https://github.com/user-attachments/assets/9be23fe0-9478-4454-8d9b-03c65bbea01a">

### Expected Behavior

I don't know what is right here. If I use a data Type (Modelica.Units.SI.Length) that has a "final unit" definition, why is possible to change this unit after? should raise an error?

### Version and OS

 - OpenModelica Version: v1.24.0-dev-238
 - OS: e.g. Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
Looks similar to #12898

**Comment by adeas31** [comment]
OMEdit only changes the `displayUnit`. The `unit` is not changed. However, if the `displayUnit` is marked `final` then we don't check that.

In your example above you are changing the binding value of `Dw` and the not the `unit` modifier. If possible, please provide a MWE.

**Comment by adeas31** [comment]
The code `parameter Modelica.Units.SI.Diameter Dw(unit="mm") "Nominal ball diameter, in millimeters";` should give an error message,

`[Modelica.Units: 247:56-247:64]: [Trying to override final element unit with modifier '= "mm"'.]`

**Comment by BasilioPV** [comment]
Yes, for me this shall be the behavior:

[Modelica.Units: 247:56-247:64]: [Trying to override final element unit with modifier '= "mm"'.]

**Comment by adeas31** [comment]
As I said, the `unit` is never changed. OMEdit only updates the `displayUnit`.

Can you please post a simple model that causes this.

**Comment by BasilioPV** [comment]
@adeas31 You are rigth, the error raises when try to change units.

The way to set a default display units is therefore:

```
model unitsTest

parameter Modelica.Units.SI.Length diam(displayUnit="mm");
parameter Modelica.Units.SI.Length diam2(displayUnit="mm")=0.010;
parameter Modelica.Units.SI.Length diam3;

Modelica.Units.SI.Length Sum;

equation

Sum=diam+diam2+diam3;

end unitsTest;
```
Which produces the expected behaviour:

![image](https://github.com/user-attachments/assets/fdd67a92-f8cd-4274-8e90-9de6f12577a2)

Sorry for my confusion, issue closed.
