### ISSUE TITLE
Unable to simulate my model.

### ISSUE THREAD

**Issue by lucas-mior** [OpenModelica/OpenModelica#13048]
This is related to #13045 and #13046.

Circa 1 month ago, I was able to run my model just fine with openmodelica v1.23.
Yesterday, I tried to run it but it failed with an error I unfortunately did not register.
However, I noticed that v1.24 was released, so I updated through the [AUR](https://aur.archlinux.org/packages/openmodelica).
When trying to run the simulation, the bugs reported in #13045 and #13046 happened.

Then, I tried to build openmodelica as described in the README from this repo. The previous bug was not there, but I still wasn't able to simulate the model, and got the following error message:
```
Limited backtrace at point of segmentation fault /usr/local/bin/../lib//omc/libOpenModelicaRuntimeC.so(+0x5baaf) 
[0x70488ede6aaf] /usr/lib/libc.so.6(+0x3d1d0) [0x70488cc4c1d0] /usr/lib/libc.so.6(__libc_free+0x71) [0x70488ccb45c1] 
/usr/local/bin/../lib//omc/libOpenModelicaRuntimeC.so(omc_free_csv_reader+0x53) [0x70488edcaf81] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(+0x1f0215) [0x70488e5f0215] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(externalInputallocate+0xb5) [0x70488e5efccd] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(solver_main+0x2a9) [0x70488e6538ed] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(+0x1e3532) [0x70488e5e3532] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(startNonInteractiveSimulation+0xf1f) [0x70488e5e220c] 
/usr/local/bin/../lib//omc/libSimulationRuntimeC.so(_main_SimulationRuntime+0xc9) [0x70488e5e5955] 
drum(main+0x1e8) [0x5fab448b7868] /usr/lib/libc.so.6(+0x25e08) [0x70488cc34e08] 
/usr/lib/libc.so.6(__libc_start_main+0x8c) [0x70488cc34ecc] drum(_start+0x25) [0x5fab448b7955] 
```

So I tried to run the windows version from openmodelica, using wine. The model ran fine, except when I made a small change in it, which previously did not cause any bug. The change is basically the boolean `pressure_input`:
```
  if pressure_input then
    derpdt.u = pinput;
  else
    Q = Qinput;
  end if;
```
Changing `pressure_input` to true made the model be stuck without any error message, forever. But both values for `pressure_input` used to work before updating OpenModelica.

The next thing I tried was to compile an older version of OpenModelica. I tried compiling v1.23, v1.22, v1.21, but all of them failed during the build process, with the error:
```
OpenModelica/OMCompiler/SimulationRuntime/ParModelica/auto/om_pm_model.cpp:45:1: note: ‘std::ifstream’ is defined in header ‘<fstream>’; this is probably fixable by adding ‘#include <fstream>’
   44 | #include "json.hpp"
  +++ |+#include <fstream>
   45 | 
make[2]: *** [OMCompiler/SimulationRuntime/ParModelica/auto/CMakeFiles/ParModelicaAuto.dir/build.make:104: OMCompiler/SimulationRuntime/ParModelica/auto/CMakeFiles/ParModelicaAuto.dir/om_pm_model.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6714: OMCompiler/SimulationRuntime/ParModelica/auto/CMakeFiles/ParModelicaAuto.dir/all] Error 2
make[1]: ** Esperando que outros processos terminem.
```

Considering everything I tried, would someone help me to be able to simulate the model successfully again?
It can be pointing me to a possible bug in the model, or how to fix the bug in the building process from the previous versions, for example.
Thanks.

**Comment by lucas-mior** [comment]
The problem with the build process was fixed by #12792. This patch was also included in the AUR build but only a commit before updating to v1.24. Now I'm checking if with this version does not contain the bugs.

**Comment by lucas-mior** [comment]
The segfault bug persisted, so I tweaked the model until it worked. It had something to do with missing inputs from the csv file, and initial conditions. It seems to be working now on version v1.23.1-cmake.

**Comment by phannebohm** [comment]
@lucas-mior thanks for reporting this.

> The segfault bug persisted, so I tweaked the model until it worked. It had something to do with missing inputs from the csv file, and initial conditions.

Even though the csv and initial system were faulty, the segfault shouldn't happen. Can you open another issue and add your model or an MWE? Thanks.

**Comment by lucas-mior** [comment]
What is an MWE?
