### ISSUE TITLE
Array plot window and Array parametric plot window do not allow time selection

### ISSUE THREAD

**Issue by joferrei** [OpenModelica/OpenModelica#13042]
### Description
When I select a vector to plot, it plots at t=0 and no other time can be selected as the time slider is not active. This happens for both type of array plots (standard and parametric). I use OMEdit 1.24.0

### Steps to reproduce
With this example I can create a vector that changes all its values during the simulation time.
```modelica
model test_array
Real vector[10];
equation
for i in 1:10 loop
vector[i]=time;
end for;
end test_array;
```
If the vector is selected the plot array is shown at time=0 and no other time can be selected as the slider is inactive (please see next picture).

![image](https://github.com/user-attachments/assets/afd59491-e3e6-443d-bf14-1113d53b9c3b)

### Expected behavior
The slider should be active to plot the values at different times (i.e. to plot a spatial profile at different times). This is the expected behaviour according to the documentation: https://openmodelica.org/doc/OpenModelicaUsersGuide/1.24/omedit.html#d-plotting

### Version and OS
 - OpenModelica Version 1.24.0
 - OS: Windows 11, 64 bit

**Comment by casella** [comment]
Indeed, it looks like a recent regression. @adeas31 will check on Monday. We can fix this in the 1.24.1 patch release anytime soon.

**Comment by adeas31** [comment]
Should work fine with #13072. I also added a context menu item called `Enable Time Controls` to Variable Browser result file node.

**Comment by joferrei** [comment]
Thanks! I will do so.

> @joferrei please check tomorrow's nightly build. If this works fine, we can back-port it to 1.24.1

**Comment by joferrei** [comment]
Hello I have tested it, and it works as expected.
Thanks!

**Comment by casella** [comment]
@joferrei thanks again for reporting this.

@adeas31 can you please back-port this to maintenance/v1.24 so we can release 1.24.1 with this important regression fix? Thanks!

**Comment by adeas31** [comment]
Ported to 1.24.1 with #13081
