### ISSUE TITLE
import files but cannot run the codes

### ISSUE THREAD

**Issue by alikazemian1998** [OpenModelica/OpenModelica#13059]
Hello
When I loaded the models, for all of the components write: "not found in scope" or sth like that, as below error
Class RLC_Circuit.Inductor not found in scope dummyOMEditClass.

I would apperite to solve my problem.

![image](https://github.com/user-attachments/assets/e23896ff-6ca1-4f2d-8b55-2af5d589b9f5)

**Comment by perost** [comment]
Your model uses an older versions of the Modelica Standard Library than what OMEdit loads by default, probably 3.2.3 while OMEdit uses 4.0.0.

You can add a `uses` annotation to your model to indicate to OMEdit which version of the MSL it uses, i.e.:
```Modelica
model RLC_Circuit
  ...
  annotation(uses(Modelica(version = "3.2.3")));
end RLC_Circuit;
```
You can also change which version OMEdit loads by default in `Tools -> Options -> Libraries`, but having a `uses` annotation in your models is a good idea regardless.

**Comment by alikazemian1998** [comment]
Hello

Thank you for your reply and guidance.

I will do that. Could you please introduce a good course for learning
Modelica?

**Comment by perost** [comment]
> Could you please introduce a good course for learning Modelica?

[Modelica by Example](https://mbe.modelica.university/) perhaps? I'm not really up to date on what the best learning material is at the moment, maybe @casella can give some better recommendations.

**Comment by alikazemian1998** [comment]
Thanks you so much

**Comment by casella** [comment]
> [Modelica by Example](https://mbe.modelica.university/) perhaps? I'm not really up to date on what the best learning material is at the moment, maybe @casella can give some better recommendations.

That's a good starting points. You can check [here](https://modelica.org/language/) for further pointers.
