### ISSUE TITLE
Update OMedit CMake to >=3.29.0

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#13054]
There are several issues compiling models, or exporting FMUs from OMEdit, where it's missing to copy some needed dlls in the `install` step, but they are sometimes hard to reproduce.
Main related issues: #12065 #12640
Possibly/probably connected: #7005 #11464 #10619 #13053
 
We observe similar symptoms:
* Compilation on Windows (10)
* Needed dlls **do not get copied** to their destination during CMake `install` step
* Problem only happens when compiling with clang (17.0.6), disappears when using gcc (13.2.0)

They could maybe have a similar root cause in dll handling/identification differences between gcc and clang . It could have the same root cause as the issue at (https://github.com/OpenModelica/OpenModelica/discussions/12965#discussioncomment-10958596), which @adrpo helped me hunt down.

One attempt to reduce the number of potential problem causes would be to update the CMake in OMEdit to at least CMake 3.29.0. This is where @adrpo's[ upstream PR](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325/diffs) got released in AFAICT.
Is that quickly accomplishable?

AFAICT, the [patched cmake](https://gitlab.liu.se/OpenModelica/OMDev/-/commit/e1bb0576bfb1ebb4c63fbbcc6e37fb825da16ac9) is present and used. I'm not sure why the patch does not seem effective. Note that the patch is slightly different from [what got merged ](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325/diffs) to CMake upstream.

cc @adrpo

**Comment by adrpo** [comment]
I updated my msys in OMDev to the latest packages and will build OM now to see if everything works correctly. If it does I will push my OMDev changes to gitlab. CMake is up to version 3.30.5.

**Comment by bilderbuchi** [comment]
I see cmake version 3.30.5 in my OMEdit command prompt on OpenModelica v1.25.0-dev-163-g35bca59dc7, thank you!
