### ISSUE TITLE
Update OMDev CMake to >=3.29.0

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#13053]
There is an issue compiling OM from source where it's missing to copy some dlls in the `install` step, see #12965. It could have the same root cause as the issue at (https://github.com/OpenModelica/OpenModelica/discussions/12965#discussioncomment-10958596), which @adrpo helped me hunt down.

One attempt to reduce the number of potential problem causes would be to update the CMake in OMDev to at least CMake 3.29.0. This is where @adrpo's[ upstream PR](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325/diffs) got released in AFAICT.
Is that quickly accomplishable?

Additional details: we observe similar symptoms:
* Compilation on Windows (10)
* dlls do not get copied to their destination. In this case, `omc.exe` is missing `libopenblas.dll` and `libstdc++-6.dll` filesthat do not get copied to `build_cmake\install_cmake\bin` when building the CMake `install` target. I'm assuming that the FMU collection/packaging also happens during CMake `install`
* Problem only happens when compiling with clang 17.0.6, disappears when using gcc 13.2.0
* OMDev is (necessarily) installed

AFAICT, the [patched cmake](https://gitlab.liu.se/OpenModelica/OMDev/-/commit/e1bb0576bfb1ebb4c63fbbcc6e37fb825da16ac9) is present and used. I'm not sure why the patch does not seem effective. Note that the patch is slightly different from [what got merged ](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9325/diffs) to CMake upstream.

I'm wondering if the (hard to reproduce) #12640 (required external function dlls not ending up in an FMU) could also have the same root cause?

Related: #13054
cc @adrpo

**Comment by adrpo** [comment]
Seems fixed with the update of OMDev. I now actually used VSCode for the build and ran the install target.

![image](https://github.com/user-attachments/assets/b4faec56-e0c9-42e9-98ab-438fac7a49f9)

I will try to push the new OMDev today but I need to also build via make to test that part works too.

**Comment by adrpo** [comment]
Of course, this is never easy, now it seems the OMDev update breaks the building of libffi via the makefile/autoconf way which is very weird. I will debug this until I find the issue, but I guess it will take some time.

**Comment by bilderbuchi** [comment]
> Seems fixed with the update of OMDev. I now actually used VSCode for the build and ran the install target.

That's great to hear! Just do check: did you reproduce the problem before the update (with VS Code+clang+previous omdev)?
I'll update omdev on my end and do a new compile, too, to see if the problem disappeared.

**Comment by adrpo** [comment]
> That's great to hear! Just do check: did you reproduce the problem before the update (with VS Code+clang+previous omdev)?

Yes, I managed previously in OMDev to fix some of the code in the cmake modules that handle the clang objdump but not the compiled code. This one will fix that as well via the cmake update.

**Comment by adrpo** [comment]
> Edit: oh, this update is not yet pushed; then I'll wait for that.

Will ping you as soon as I push a new OMDev so you can test with it.

**Comment by adrpo** [comment]
Now we have an OMDev update on master: https://gitlab.liu.se/OpenModelica/OMDevUCRT

Please check with it.

**Comment by bilderbuchi** [comment]
> Now we have an OMDev update on master: https://gitlab.liu.se/OpenModelica/OMDevUCRT
> 
> Please check with it.

Confirmed fixed -- compiling with Clang I get copies of the required dlls and `omc.exe -h` does not crash but displays the help text.
Thank you!

**Comment by bilderbuchi** [comment]
Note that I had to add an include, otherwise compilation would fail:
```diff
diff --git a/OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_system.hpp b/OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_system.hpp
index bfa268bf44..18c254124e 100644
--- a/OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_system.hpp
+++ b/OMCompiler/SimulationRuntime/ParModelica/auto/pm_cluster_system.hpp
@@ -38,6 +38,7 @@
 */
 
 #include <iostream>
+#include <fstream>
 #include <map>
 
 #include <boost/graph/adjacency_list.hpp>
```

**Comment by adrpo** [comment]
> Note that I had to add an include, otherwise compilation would fail because it would not find `std::basic_ofstream`.

Had already fixed that if you do pull on the OpenModelica: #13066.
