### ISSUE TITLE
A tiny useful OMEdit enhancement

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#13052]
OMEdit in plotting perspective shows the active output in bold, with  the name prefixed by "(Active)".
During years of experience with this, the presence of word "(Active)" required me many, many times to enlarge the "variables" field to see the ouput file name. It is a very simple action, but when repeated hundreds of times becomes annoying.

I think that bold is sufficient to indicate the active ouput file in the Output window, exactly as it is the active model in the Libraries window, and therefore  propose to delete the string "(active)".

### Expected Behavior
the active output file is highlighte in bold, without prepending "(active)".

### Version and OS
OM 1.23.1.

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
That is not the case in the current release/version.

**Comment by ceraolo** [comment]
Wow, I was granted what I asked for, even _before_ asking....
Thank you.
