### ISSUE TITLE
Trouble in the behavior of the initialisation from a results file ( tags -ii_ )

### ISSUE THREAD

**Issue by felix-sil3x** [OpenModelica/OpenModelica#13064]
### Description
It seems like if the imports of parameters failed during the overriding process.

### Steps to reproduce
1 : Run the ThreeTanks example from the MSL: Modelica.Fluid.Examples.Tanks.ThreeTanks

2 : Duplicate with Rename the file "_res.mat" and "_init.xml" within the same dump directory 

3 : Within OMEdit (or in the CLI), Simulate the ThreeTanks models with the following options
Initialization Method : None
Initialization file : renamed results file
Initialization time : 50 (or whatever)

### Expected behavior
With the symbolic initialization method, the simulation runs despite error messages on data (parameters) imports. However, with the none method, the simulation does not run due to division by zero.

With the none method, I would expect the values at the initialization being the one observed at the given time in the initialization result file 

### Screenshots
Using the symbolic method:
![image](https://github.com/user-attachments/assets/924b0102-fd67-428a-86b2-f9b4d0d6edc0)

Using the none method:
![image](https://github.com/user-attachments/assets/42a93cd7-fd33-469a-a54c-d1c47d72ef41)

### Version and OS
 - OpenModelica Version : OpenModelica 1.23.1
 - Modelica (MSL) version : 4.0.0
 - hardware / OS : HP HP ZBook 15u G6 / Debian GNU/Linux 12 (bookworm)

### Additional context
We would like this issue to be solved in a reasonable short time so we propose to use DFD as financial compensation in extra resources are used.

**Comment by casella** [comment]
@felix-sil3x the problem in this case is that protected/hidden variables are not written to the .mat file by default.

If you use the symbolic initialization method, the initial equations are solved anyway, so even if some start values are missing from the .mat file, with a bit of luck they can be solved correctly anyway and the simulation can start successfully.

With `-iim=none`, instead, if some variables are missing in the .mat file, they are initialized to zero. Hence the division-by-zero error when you start the simulation.

If you set this two checkboxes in the Simulation Setup | Output tab
![immagine](https://github.com/user-attachments/assets/ba50cf5e-0abf-4e44-8e3c-6154cf97953a)
when you create the .mat file, or equivalently set the `-emit_protected` and `-ignoreHideResult` simulation flags, then the initialization with `-iim=none` works fine.

**Comment by casella** [comment]
To me, this has always been very clear since when I played around with the corresponding feature in Dymola some 20 years ago, but I just realized that I didn't mention that when I wrote the documentation of the OpenModelica feature some time ago, contrary to what I thought.

I'll update the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/solving.html#importing-initial-values-from-previous-simulations) to point this out clearly.

**Comment by casella** [comment]
See PR #13131

**Comment by felix-sil3x** [comment]
@casella Thanks a lot. It seems actually obvious with your explanations. Good idea to update the documentation to become crystal clear

**Comment by casella** [comment]
It's [online](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/solving.html#importing-initial-values-from-previous-simulations) already 😎

**Comment by felix-sil3x** [comment]
I have seen, that was a congrats :)

**Comment by casella** [comment]
I hadn't checked yet, oftentimes something goes wrong with the Sphynx source code and the user's guide is really not updated. This time I was lucky 😄
