### ISSUE TITLE
Creating a sub package in a single-file library should not give option to deactivate "Save contents in one file"

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#13061]
### Description

When one works on a library that was chosen to be created with the option "Save contents in one file" then that option should be locked for the creation  any other sub-packages in that library.

### Steps to Reproduce

1. create a new packages as with "Save contents in one file" activated
2. create a new sub-package in that library

### Expected Behavior

The option "Save contents in one file" should be locked active and it should not be possible to uncheck.

### Version and OS

1.25.0-dev-71 on Ubuntu 24.04

**Comment by casella** [comment]
Indeed, the "Save contents in one file" is actually ignored.

**Comment by dietmarw** [comment]
So this should be reflected in the UI

**Comment by casella** [comment]
Seems like a quick fix, maybe we can put it in 1.24.1, even though it is not critical.

**Comment by adeas31** [comment]
Fixed with #13079 and ported to 1.24.1 with #13081.

**Comment by dietmarw** [comment]
Tested with 1.25.0~dev-112 and works now as expected. Thanks!
