### ISSUE TITLE
FMU export does ignore source code export option

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#13070]
### Description

When deselecting that an exported FMU should contain the c-source code then the generated FMU contains the sources anyway.

### Steps to Reproduce
Export an FMU and make sure to deselect  "Include Source Code"

### Expected Behavior

FMU should not contain `sources` folder.

### Version and OS

 - OpenModelica Version: 1.25.0-dev-99
 - OS: Ubuntu 24.04

**Comment by casella** [comment]
@arun3688, @adeas31 could you please check?

**Comment by adeas31** [comment]
I just tested this and the option `Include Source Code` is working as expected. The `sources` folder is not added to the FMU, if `Include Source Code` is unchecked. You can even see it in the build log that which files are added to the zip.

@arun3688 I noticed that you are duplicating the zip process arguments https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/FMI/FMUExportOutputWidget.cpp#L511.
Also, it will be nice to output the actual process and its arguments to the logs. I would like to see that its calling `zip -r -z sources/* .....` or `cmake --build --parallel .....` so I know what the output is for.

**Comment by arun3688** [comment]
@adeas31 this command `cmake --build . --parallel --target install` builds only the binaries for the platform and it does not zip the fmu 

```
Install the project...
-- Install configuration: ""
-- Installing: C:/OPENMODELICAGIT/OMEditDir/Examplec4ba/Example.fmutmp/sources/../binaries/win64/libExample.dll.a
-- Installing: C:/OPENMODELICAGIT/OMEditDir/Examplec4ba/Example.fmutmp/sources/../binaries/win64/Example.dll
-- Installing: C:/OPENMODELICAGIT/OMEditDir/Examplec4ba/Example.fmutmp/sources/../binaries/win64/ExternalFunc1.dll
-- Installing: C:/OPENMODELICAGIT/OMEditDir/Examplec4ba/Example.fmutmp/sources/../binaries/win64/libwinpthread-1.dll
```
and the zip command is actually run in a separate process. As you said we can export the zip command on how it is called, i can do that. But the issue seems to be in linux, my guess is the following command to exclude the sources directory does not work in linux i guess
`zip -r "Test.fmu" -x "'sources/*'"`

I guess we can do some quick command line testing in WSL to test the above command

**Comment by arun3688** [comment]
@adeas31 I did a quick testing in linux and it seems the following zip command works `zip -r test.fmu . -x "sources/*"` , the linux does not like `zip -r test.fmu . -x "'sources/*'"` the single quotes in the sources and in windows we need the single quotes to exclude the directory

```
arun@win00085:/mnt/c/OPENMODELICAGIT/OMEditDir/Examplec4ba/Example.fmutmp$ zip -r test.fmu . -x "sources/*"
  adding: binaries/ (stored 0%)
  adding: binaries/win64/ (stored 0%)
  adding: binaries/win64/Example.dll (deflated 67%)
  adding: binaries/win64/ExternalFunc1.dll (deflated 67%)
  adding: binaries/win64/libExample.dll.a (deflated 93%)
  adding: binaries/win64/libwinpthread-1.dll (deflated 57%)
  adding: modelDescription.xml (deflated 83%)
  adding: resources/ (stored 0%)
  adding: resources/Example_flags.json (stored 0%)
  adding: resources/Example_JacA.bin (deflated 44%)
```

**Comment by adeas31** [comment]
@arun3688 see #13073

**Comment by dietmarw** [comment]
Just tested this with 1.25.0~dev-106 and it now works as expected. Thanks for the quick fix :-)
