### ISSUE TITLE
Show array component declarations as such in tooltip windows

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13083]
While looking into #2891 I noticed an issue that has nothing to do with hierarchical editing but should definitely be fixed.

Steps to reproduce: 
- load the following MWE
```modelica
package TestArrayComponent
  model System
    Module modules[2] annotation(
      Placement(transformation(origin = {-18, 0}, extent = {{-10, -10}, {10, 10}})));
  end System;

  model Module
  Component component annotation(
      Placement(transformation(origin = {-10, 4}, extent = {{-10, -10}, {10, 10}})));
  end Module;
end TestArrayComponent;
```
open the Diagram of System and hover with the cursor over the `modules` instance; the following tootip window shows up
![immagine](https://github.com/user-attachments/assets/11c1187a-5449-4e4a-9493-0e54fefbbd0f)

With the current setup it is impossible to figure out that modules is actually an array, unless one looks into the source code. 

I would suggest that the tooltip windows displays

**TestArrayComponent.Module**
modules[2]

to make that clear.

**Comment by adeas31** [comment]
Shall we also add this to the display name of the component? So instead of `modules` we show `modules[2]`.

**Comment by casella** [comment]
Do you mean, the content of the %name string in icons?

**Comment by adeas31** [comment]
> Do you mean, the content of the %name string in icons?

Yes.

**Comment by casella** [comment]
> > Do you mean, the content of the %name string in icons?
> 
> Yes.

Seems a good idea, please go ahead with that.

**Comment by adeas31** [comment]
Done.

![image](https://github.com/user-attachments/assets/1ec06e8f-519b-4a21-8143-ae8457b564f0)
