### ISSUE TITLE
Launch of v1.25.0~dev-133 causes Scripting warning

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#13138]
### Description

When launching  v1.25.0~dev-133 I now get the following scripting warning: 

```
[3] 10:10:08 Scripting Warning
Failed to load Qt translation file qt_C from location /usr/share/qt5/translations

[4] 10:10:08 Scripting Warning
Failed to load translation file OMEdit_C from location /usr/bin/../share/omedit/nls
```
This was not present in the previous dev-125 version.

### Version and OS

 - OpenModelica Version: v1.25.0~dev-133
 - OS: Ubuntu Linux 24.04.1 (native and via WSL)

**Comment by adeas31** [comment]
We are working on it. See #13107 and #13106.

How did you build? You should have Qt translations files in `/usr/share/qt5/translations`.
I will see if OMEdit translation files are copied correctly or not.

**Comment by dietmarw** [comment]
I use the nightly builds. So I don't compile myself.

**Comment by dietmarw** [comment]
> How did you build? You should have Qt translations files in `/usr/share/qt5/translations`. I will see if OMEdit translation files are copied correctly or not.

There is no `qt_C` file. Hence when one has LANG=C (like it is the case for WSL) you get the first warning. However if you have a locale loaded only the second warning is triggered.

**Comment by dietmarw** [comment]
Just for clarification my Linux box runs en_GB which then causes the OMEdit to look for: 
```
[3] 10:51:24 Scripting Warning
Failed to load translation file OMEdit_en_GB from location /usr/bin/../share/omedit/nls
```

**Comment by casella** [comment]
Unfortunately I'm also getting the same issue on Windows, nightly build v1.25.0-dev-152-g78d9a41044. This includes @adeas31's PR 13139.

**Comment by adeas31** [comment]
That's weird. What is the warning?

**Comment by casella** [comment]
Same as @dietmarw's:
```
[3] 11:01:51 Scripting Warning
Failed to load Qt translation file qt_en_US from location C:/Program Files/OpenModelica1.25.0-dev-64bit/bin/share/qt5/translations
```

**Comment by adeas31** [comment]
I forgot to update the Windows installer. Should work fine with https://github.com/OpenModelica/OpenModelicaSetup/pull/69

**Comment by adeas31** [comment]
Just tested this with latest nightly build. Works as expected.
