### ISSUE TITLE
Connectors do not show

### ISSUE THREAD

**Issue by AnnaLiU23** [OpenModelica/OpenModelica#13174]
I have created submodel with connectors pin_n and pin_p but when I import in a main models, connectors do not show up and therefore it is not possible to make connections.
I show a simple example with RLC system, just to show the problem.

![image](https://github.com/user-attachments/assets/16c4ea6b-6e3a-44f6-a498-1739205eab0e)
![image](https://github.com/user-attachments/assets/db980d83-17f4-4d24-a806-09bc74fc781b)

 - OpenModelica Version: 1.24.0 (64-bit)
 - OS: Windows 11 Education
 - Versions of used Modelica libraries: 3.2.3

Here is the code generated for the two models

```Modelica
model RLC_submodel
  Modelica.Electrical.Analog.Basic.Ground ground1 annotation(
    Placement(visible = true, transformation(origin = {0, -32}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Resistor resistor1(R = 15)  annotation(
    Placement(visible = true, transformation(origin = {-36, 56}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Capacitor capacitor1(C = 0.0001)  annotation(
    Placement(visible = true, transformation(origin = {18, 56}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Inductor inductor1(L = 0.15)  annotation(
    Placement(visible = true, transformation(origin = {52, 12}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Interfaces.PositivePin pin_p annotation(
    Placement(visible = true, transformation(origin = {-86, 54}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {-86, 54}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Interfaces.NegativePin pin_n annotation(
    Placement(visible = true, transformation(origin = {-84, -20}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {-84, -20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(ground1.p, pin_n) annotation(
    Line(points = {{0, -22}, {-84, -22}, {-84, -20}, {-84, -20}}, color = {0, 0, 255}));
  connect(resistor1.p, pin_p) annotation(
    Line(points = {{-46, 56}, {-86, 56}, {-86, 54}, {-86, 54}}, color = {0, 0, 255}));
  connect(inductor1.n, ground1.p) annotation(
    Line(points = {{52, 2}, {54, 2}, {54, -22}, {0, -22}, {0, -22}}, color = {0, 0, 255}));
  connect(capacitor1.n, inductor1.p) annotation(
    Line(points = {{28, 56}, {52, 56}, {52, 22}, {52, 22}}, color = {0, 0, 255}));
  connect(resistor1.n, capacitor1.p) annotation(
    Line(points = {{-26, 56}, {8, 56}, {8, 56}, {8, 56}}, color = {0, 0, 255}));
  annotation(
    uses(Modelica(version = "3.2.3")));
end RLC_submodel;
```

```Modelica
model test
  RLC_submodel RLC_submodel1 annotation(
    Placement(transformation(origin = {23, 5}, extent = {{-33, -33}, {33, 33}})));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage1 annotation(
    Placement(transformation(origin = {-69, 5}, extent = {{-23, -23}, {23, 23}}, rotation = -90)));
equation

annotation(
    uses(Modelica(version = "3.2.3")));
end test;
```

**Comment by adeas31** [comment]
You posted the same code twice. Add the code for model `test`.

**Comment by ceraolo** [comment]
Just a comment. Not sure if related to this issue or not.

I think it is never a good idea to add grounds inside submodels: it makes usage of these submodels tricky and error prone.
A few years ago I noted a mistake of this kind in a MSL model; and after my objections this was fixed in MSL 4.0.0.

**Comment by AnnaLiU23** [comment]
> Just a comment. Not sure if related to this issue or not.
> 
> I think it is never a good idea to add grounds inside submodels: it makes usage of these submodels tricky and error prone. A few years ago I noted a mistake of this kind in a MSL model; and after my objections this was fixed in MSL 4.0.0.

Thanks for your comment. I have tried to move the ground component in the main model but, unfortunately, it does not fix the problem

**Comment by adeas31** [comment]
> > Just a comment. Not sure if related to this issue or not.
> > I think it is never a good idea to add grounds inside submodels: it makes usage of these submodels tricky and error prone. A few years ago I noted a mistake of this kind in a MSL model; and after my objections this was fixed in MSL 4.0.0.
> 
> Thanks for your comment. I have tried to move the ground component in the main model but, unfortunately, it does not fix the problem

That is just an advice on good modeling practice. The actual issue should be fixed with PR #13177.

**Comment by casella** [comment]
@adeas31 maybe we could back-port this to maintenance/v1.24?

**Comment by adeas31** [comment]
> @adeas31 maybe we could back-port this to maintenance/v1.24?

Done. #13200
