### ISSUE TITLE
Why is the code downloaded from git hub, different from the displayed source code?

### ISSUE THREAD

**Issue by dollPrincess** [OpenModelica/OpenModelica#13171]
Why is the code downloaded from git hub, different from the displayed source code?
Source code: https://github.com/OpenModelica/OpenModelica?tab=readme-ov-file
git command: git clone --recurse-submodules https://openmodelica.org/git-readonly/OpenModelica.git

I used git to clone the code and also tried downloading the zip package directly, but it's all the same. I downloaded the latest version of the code, it can't be that the original developer didn't finish updating it.
However, some of the code that is available on the original git hub only has an empty folder with no content inside the folder. The code you get in both ways of downloading is the same.

The problematic folders are all named in blue with ‘@---’ at the end, as follows:

![Snipaste_2024-11-11_16-59-27](https://github.com/user-attachments/assets/e2969594-3e08-4267-a6b9-f5e60177bf0c)

I checked the code structure when I didn't unzip it, and it wasn't there. git Cloning the code was also successful, there was no network problem not downloading the whole thing.
My computer uses window defender and tencent butler, when I finished downloading the zip, tencent butler prompted me for a virus, so I ignored it and didn't let him check and delete the code, etc. After that, I turned off the virus alert. After that, I turned off the Tencent butler and re-downloaded the zip, but the same folder is still missing.

Checked a lot of pages online, and it's not a problem with the primary or secondary branch or anything.
What's going on here? Why is the code downloaded from git hub different from the source code displayed?
Why does the folder name in the directory on the git hub code display page turn blue?

**Comment by bilderbuchi** [comment]
Those are Git "submodules", you can read the documentation about this Git feature at https://git-scm.com/book/en/v2/Git-Tools-Submodules and https://git-scm.com/docs/git-submodule

**Comment by perost** [comment]
Closing since it's not an issue, and there's a duplicate discussion in #13172.

**Comment by dollPrincess** [comment]
> Those are Git "submodules", you can read the documentation about this Git feature at https://git-scm.com/book/en/v2/Git-Tools-Submodules and https://git-scm.com/docs/git-submodule

Thank you very much! Your advice is so useful. ~~~ I have succeed in compiling it.
