### ISSUE TITLE
The NB unnecessarily creates mixed systems of equations when smooth is used

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13170]
with the following MWE:
```modelica
model SmoothTearing
  Real x;
  Real y;
initial equation
  der(x) = 0;
equation
  der(x) = y;
  y = smooth(0, if x > 0 then -2*x else -x) - 1;
end SmoothTearing;
```
With the old backend, the implicit equation to compute x is not mixed:
```modelica
(residual) -1.0 + smooth(0, if x > 0.0 then (-2.0) * x else -x) - y = 0
```

With the new backend, the smooth() expression causes the generation of auxiliary boolean unknowns:
```modelica
(torn) $SEV_0 := x > 0.0
(residual) -1.0 + smooth(0, if $SEV_0 then -2.0 * x else -x) - y = 0
```
Per se, this is not a bad idea, except when you have a system of 100,000 equations and you need to perform tearing on it, which will be quite time-consuming. Currently, when dealing with large-scale phasor-based power system models, we skip tearing as we know it's not worth the backend time, as long as the system is solved by an efficient sparse nonlinear solver.

@phannebohm, @kabdelhak, could we avoid generating these auxiliary Boolean variables when considering `smooth()` and `noEvent() `expressions also in the NB?

**Comment by casella** [comment]
As discussed during today's devmeeting, basically do with `smooth(0, ...)` what we arleady do with `noEvent()`

**Comment by casella** [comment]
Update: it is reasonable to treat `smooth(0, ...)` as `noEvent()` for initial equations, but not during simulations, where events should be generated. Unfortunately, the NB handles such issues before splitting initial and regular equations, so minimal tearing needs to be handled.

@phannebohm is working on a more efficient implementation - regarding minimal tearing, the analysis will be restricted to the subset of equations with discrete variables and discrete variables themselves, so it should be efficient even for large systems of equations

**Comment by phannebohm** [comment]
I'm closing this, as we agree that these mixed systems are necessary for proper event search.

**Comment by casella** [comment]
Yeah, I wanted to do this myself but I got carried away by other stuff and forgot. Thanks for pointing that out!
