### ISSUE TITLE
GBODE test models fail verification

### ISSUE THREAD

**Issue by phannebohm** [OpenModelica/OpenModelica#13180]
### Description

Since #13163 the gbode solvers are tested. There are two models failing verification.

testsuite/simulation/modelica/solver/gbode/IRKGaussian_01.mos:
```
Running RK gauss5 with NLS kinsol and errCtrl default:
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.

Failed vars:
der(y[1])
Failed to compare simulation results


--------------------------------------------------------
Running RK gauss6 with NLS kinsol and errCtrl default:
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.

Failed vars:
der(y[1])
Failed to compare simulation results
```
 and testsuite/simulation/modelica/solver/gbode/multiRate_02.mos:
```
Running RK gauss6 with NLS newton:
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.

Failed vars:
der(y[1])
Failed to compare simulation results


--------------------------------------------------------
Running RK gauss6 with NLS kinsol:
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.

Failed vars:
der(y[1])
Failed to compare simulation results
```

We should investigate what is the problem and fix the solver or update the tests.

After that is done we should add those tests back to the testsuite.

**Comment by casella** [comment]
Thanks @phannebohm!

We also have a [gbode](https://libraries.openmodelica.org/branches/gbode/) library test job running on demand. Last time it ran 6 months ago. I just scheduled a new gbode test job [#8657](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/8657/)

**Comment by casella** [comment]
The job was cancelled for some reason. I scheduled [#8682](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/8682/console).

**Comment by casella** [comment]
> That one finished. But AFAICT unfortunately it didn't generate any regression report.

OpenModelica/OpenModelicaLibraryTesting/issues/180
 
> I looked at a few libraries manually and nothing seems to be horribly broken, so I guess GBODE is still doing fine.

Good!
