### ISSUE TITLE
FMU resources are being not used

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13209]
### Description

Considers the following MWE:

[lookup tables.zip](https://github.com/user-attachments/files/17728086/lookup.tables.zip)

When export to FMU the component "lookTable", the resources are correctly set in the FMU:

![image](https://github.com/user-attachments/assets/e230f71e-d92e-4924-8b34-5598d71e7e1f)

Then, I try to do the following:

 - Import this FMU as CS in other software: -> The result is Ok
 - Import this FMU as ME in other software: -> The result is Ok

 - Change inside the FMU the file "tabla.txt" with new data and load this new FMU in other software as CS: -> The result ignore the data and show the original result.
 - Change inside the FMU the file "tabla.txt" with new data and load this new FMU in other software as ME: -> The result ignore the data and show the original result.

 - Delete inside the FMU the file "tabla.txt" and load this new FMU in other software as CS/ME: -> The result ignore that the file is missing and show the original result !

It seems that the table is hard coded into the FMU when export.

Please find attached the fmu file (change to .fmu): 

[lookTable.zip](https://github.com/user-attachments/files/17728145/lookTable.zip)

### Expected Behavior

The expected behavior is that in both ME/CS the FMU used the resource file on the simulation.

The following forum message start this discussion on 2019, but I cannot find the ticket and the result:

https://openmodelica.org/forum/default-topic/2667-how-fmu-handle-a-lookup-table.html

NOTE: This works as expected in both ME/CS on other Modelica software, so I think that is the correct behavior.

### Version and OS

 - OpenModelica Version: 1.25 (nigthly)
 - OS: e.g. Windows 10, 64 bit

**Comment by BasilioPV** [comment]
This is not problem of OM.... I will investigate

**Comment by bilderbuchi** [comment]
Please report back on your results. I might have a similar workflow planned, it would be good to know if this works as you expect.

**Comment by BasilioPV** [comment]
@bilderbuchi After some tests, I found that FMU exported with OMedit including resources (a csv table, in this case) are working fine on OM and other Modelica software. If I change manually this table inside the FMU, the new data is correctly loaded when executed. This is the expected behavior.
