### ISSUE TITLE
Relative path "modelica://" does not work

### ISSUE THREAD

**Issue by BasilioPV** [OpenModelica/OpenModelica#13201]
### Description

The use of relative paths (Modelica language) does not work to retrieve data from files:

![image](https://github.com/user-attachments/assets/02220047-097a-4f11-8fbf-704fed7a2b23)

![image](https://github.com/user-attachments/assets/84aefe24-fc5b-4244-bfde-1e7a54efc329)

### Steps to Reproduce

Unzip the following MWE :

[lookup tables.zip](https://github.com/user-attachments/files/17719021/lookup.tables.zip)

The library has the following:

```
package externalTables
  model lookTable
    Modelica.Blocks.Tables.CombiTable1Ds combiTable1Ds(tableOnFile = true, tableName = "datos", fileName = "modelica://externalTables/Resources/tabla.txt", extrapolation = Modelica.Blocks.Types.Extrapolation.HoldLastPoint)  annotation(
      Placement(transformation(origin = {-10, 12}, extent = {{-10, -10}, {10, 10}})));
  Modelica.Blocks.Sources.RealExpression realExpression(y = time)  annotation(
      Placement(transformation(origin = {-58, 12}, extent = {{-10, -10}, {10, 10}})));
  equation
  connect(realExpression.y, combiTable1Ds.u) annotation(
      Line(points = {{-46, 12}, {-22, 12}}, color = {0, 0, 127}));
    annotation(
      uses(Modelica(version = "4.0.0")),
  experiment(StartTime = 0, StopTime = 11, Tolerance = 1e-06, Interval = 0.1));
  end lookTable;
  annotation(
    uses(Modelica(version = "4.0.0")));
end externalTables;
```
where the "modelica://externalTables/Resources/tabla.txt" is the relative path to the folder where the package "externalTables" is placed.

### Expected Behavior

The table .txt shall be found and loaded.

### Version and OS

 - OpenModelica Version:  v1.25.0-dev-121-g3b470d1ae3 (64-bit)
 - OS: Windows 10, 64 bit

** ++ EDIT: ++**

On other package case, using visualization shapes, this works ok:
![image](https://github.com/user-attachments/assets/5280abda-a35c-4f74-b597-dc1af643a5f2)

Its strange that here the conversion URI works fine and on the other example not?¿

**Comment by casella** [comment]
@BasilioPV as I understand from [Section 13.4](https://specification.modelica.org/maint/3.6/packages.html#file-system-mapping-of-package-class) of the the MLS, a package is either stored as a single file, or in a directory. If you want to have a Resources directory in the package, to be accessed by the modelica URI, you are obliged to use the second option. Hence, you should have an externalTables directory containing a package.mo file with the top-level package declaration, and also containing the Resources directory.

This should work.

**Comment by perost** [comment]
> @BasilioPV as I understand from [Section 13.4](https://specification.modelica.org/maint/3.6/packages.html#file-system-mapping-of-package-class) of the the MLS, a package is either stored as a single file, or in a directory. If you want to have a Resources directory in the package, to be accessed by the modelica URI, you are obliged to use the second option. Hence, you should have an externalTables directory containing a package.mo file with the top-level package declaration, and also containing the Resources directory.
> 
> This should work.

13.5 says that it's allowed but not recommended:
>For a Modelica-package stored as a single file, A.mo, the resource modelica://A/C.jpg refers to a file C.jpg stored in the same directory as A.mo, but using resources in this variant is not recommended since multiple packages will share resources.

The issue here is simply that CombiTable1Ds does not convert URIs to filenames automatically. Like the documentation of e.g. CombiTable1Ds mentions you need to use `loadResource` for that, i.e. `fileName = Modelica.Utilities.Files.loadResource("modelica://externalTables/Resources/tabla.txt")`. This should work fine in OpenModelica even for single file packages.

**Comment by BasilioPV** [comment]
Thanks @perost @casella !

**Comment by casella** [comment]
Sorry, I got fooled by this thing, that filename can't be a URI. Thanks @perost!
