### ISSUE TITLE
Drop support of the old graphical editing mode

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13257]
The new instance-based infrastructure for graphical editing in OMEdit was first introduced experimentally in release 1.22.0 in Apr 2023 and later on made the preferred operating mode in release 1.23.0 in Nov 2023. Since then, it has been further enhanced and several bugs have been fixed. We kept the old mode as a backup just in case, but after more than a year from the release, there is no reason to keep it and maintain it.

If there are any remaining issue that force some users to use the old interface, they should be fixed in the new infrastructure.

With the 1.25.0 release, the Options | Optional Features | Disable new instance-based editing of models option will be removed

**Comment by adeas31** [comment]
Fixed with PR #13284
