### ISSUE TITLE
readSimulationResult Api has problem

### ISSUE THREAD

**Issue by onesandineye** [OpenModelica/OpenModelica#13287]
### Description
If the variable that needs to get the result is nested in multiple der functions, it would return error.

### Steps to reproduce
Use OMShell.exe on windows
loadModel(Modelica)
simulate(Modelica.Blocks.Examples.FilterWithDifferentiation)
readSimulationResultVars("C:/Users/account/AppData/Local/Temp/OpenModelica/Modelica.Blocks.Examples.FilterWithDifferentiation_res.mat")
Above command will return all variables as following:
 {"Bessel.A_ripple","Bessel.analogFilter","Bessel.f_cut","Bessel.f_min","Bessel.filterType","Bessel.gain","Bessel.init","Bessel.normalized","Bessel.nx","Bessel.order","Bessel.u","Bessel.u_nominal","Bessel.x[1]","Bessel.x[2]","Bessel.x[3]","Bessel.x_start[1]","Bessel.x_start[2]","Bessel.x_start[3]","Bessel.y","Bessel.y_start","der(Bessel.x[1])","der(Bessel.x[2])","der(Bessel.x[3])","**der(der(Bessel.x[2]))**","der(der(Bessel.x[3]))","**der(der(der(Bessel.x[3])))**","der(der1.u)","der(der2.u)","der(der3.u)","der1.u","der1.y","der2.u","der2.y","der3.u","der3.y","f_cut","step.height","step.offset","step.startTime","step.y","time"}

readSimulationResult("C:/Users/panxz/AppData/Local/Temp/OpenModelica/Modelica.Blocks.Examples.FilterWithDifferentiation_res.mat",{der(der(der(Bessel.x[3])))})

Above command will return error:
"[<interactive>:1:1-1:0:writable] Error: Class readSimulationResult not found in scope <global scope> (looking for a function or record).

### Version and OS
 - OpenModelica 1.24
 - Modelica 4.0.0
 - OS: Window 10|11

**Comment by perost** [comment]
> Yes, it should tell you that the second argument is an arrays of strings and its elements need quotes:
> 
> ```
> { "der(der(der(Bessel.x[3])))" }
> ```

No, the second arguments is an array of variable names, strings are not accepted. The issue is that the elaboration of variable names doesn't handle nested `der`-calls. I'll see if I can fix it.

**Comment by perost** [comment]
Fixed with #13288 and ported to 1.24 maintenance with #13289.

**Comment by adrpo** [comment]
I think we should overload the `readSimulationResult` function to support an array of strings as well. 
The result that you get from `readSimulationResultVars` is a list of strings, not a list of variable names.
