### ISSUE TITLE
Copy command does not work on FMUs

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#13286]
### Description

Calling the `copy(from, to)` command from a .mos script usually works but not with FMUs.
The destination ends up being 1kB. It seems that copies only one of the internal files.
Tried also with admin rights, but nothing changes.

### Version and OS

 - OpenModelica Version: 1.24.2 (64bit)
 - OS: Win 11

**Comment by casella** [comment]
@dariomangoni it's not really clear to me what your problem is. Please provide a detailed description to reproduce it. Thanks!

**Comment by adeas31** [comment]
Seems some issue with the [copy](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.copy.html) API. @perost can you please take a look at it.

**Comment by perost** [comment]
> Seems some issue with the [copy](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.copy.html) API. @perost can you please take a look at it.

I can't replicate the issue, I tried it on [Zones1.fmu](https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/Resources/src/ThermalZones/EnergyPlus/FMUs/Zones1.fmu) from the Buildings library and it worked just fine.

Maybe it's Windows-specific, or maybe it only happens with some FMUs? But `copyFile` just copies the binary data from one file to another, so what the file contains shouldn't matter.

The implementation for `copyFile` is [here](https://github.com/OpenModelica/OpenModelica/blob/920fac75864ae26e10492c43977c05ed202161fc/OMCompiler/Compiler/runtime/systemimpl.c#L975) and uses some functions from [here](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/util/omc_file.c), in case anyone is interested in how it works.

**Comment by casella** [comment]
@perost did you actually try with 1.24.2? Maybe we introduced some glitch there.

**Comment by perost** [comment]
> @perost did you actually try with 1.24.2? Maybe we introduced some glitch there.

No, I used the latest master, but `copyFile` hasn't been touched in years.

**Comment by adrpo** [comment]
I will have a look but my feeling is that antivirus or something like that gets in the way.

**Comment by adrpo** [comment]
Ok, I can reproduce this:

```
C:\temp>type copyfmu.mos
copy("PumpingSystem.fmu", "newfmu.fmu"); getErrorString();

C:\temp>"%OPENMODELICAHOME%"\bin\omc copyfmu.mos
true
""

C:\temp>dir /a *.fmu
 Volume in drive C is Windows
 Volume Serial Number is 0C4D-7352

 Directory of C:\temp

11/29/2024  20:38             1,022 newfmu.fmu
11/22/2024  14:20         1,739,231 PumpingSystem.fmu
               2 File(s)      1,740,253 bytes
               0 Dir(s)  16,945,160,192 bytes free
```

**Comment by adrpo** [comment]
Geez! Found the problem. We open the file with `mode="r"` which is text mode:
https://github.com/OpenModelica/OpenModelica/blob/920fac75864ae26e10492c43977c05ed202161fc/OMCompiler/Compiler/runtime/systemimpl.c#L982

**Comment by adrpo** [comment]
How this worked in previous versions beats me!

**Comment by perost** [comment]
> How this worked in previous versions beats me!

Did it work in previous versions? Maybe it's always been broken on Windows but no one noticed. The man page for `fopen` says:
>The mode string can also include the letter 'b' either as a last character or as a character between the characters in any of the two-character strings described above.  This is strictly for compatibility with ISO C and has no  effect;  the  'b'  is ignored on all POSIX conforming systems, including Linux. (Other systems may treat text files and binary files differently, and  adding the  'b'  may  be  a good idea if you do I/O to a binary file and expect that your program may be ported to non-UNIX environments.)

So I guess that's why it works on Linux, it doesn't care and treats text files and binary files the same.

**Comment by adrpo** [comment]
Fixed this and added a test. I think the `mingw64` implementation of `fread` might have assumed binary mode but now with `ucrt64` that has changed.
