### ISSUE TITLE
Some of models Buildings.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase* fail the verification due to synchronization issue

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#13291]
The variable `assEqu.diff` of some models in the group `Buildings.ThermalZones.ReducedOrder.Validation.VDI6007.TestCase*` fails the verification vs the Dymola reference file because OM triggers some `state-events` instead of `time-events`.

This general issue has been already reported and discussed in https://github.com/OpenModelica/OpenModelica/issues/2152, herebelow some details about these particular cases will be reported.

The `assEqu` model computes the `assEqu.diff` variable as output of a first-order system that receives as input the difference `diffExa` calculated in some monitoring intervals only (otherwise forced to zero):
```modelica
  if (time >= t0) and (time < t1) or
     (time >= t2) and (time < t3) or
     (time >= t4) and (time < t5) then
     diffExa = abs(u1 - u2);
  else
    diffExa = 0; // Test is not needed in this time domain
  end if;
  der(diff) = (diffExa-diff)/tau;
```
the `tx` thresholds are `Modelica.Units.SI.Time` parameters `(fixed=false)`,  calculated during the initialization.
The `u2` input is updated at fixed intervals by a `sample()` structure, that is triggered by both OM and Dymola as a `time-event`. 
OM triggers the time-condition above as a `state-event`, Dymola as a `time-event` synchronous with the `u2` updating. The `state-event` is usually detected in a time slightly different from the `time-event` and this generates the differences in the `diffExa` variable that are the cause of the verification failure.

```
**OM**
time event at time=46800 (sample)
state event at time=46800.0000005 (if condition)
```

```
**Dymola**
Time event at time: 46800 (sample)
Time event at time: 46800 (if condition)
```

**Comment by casella** [comment]
Unless there is urgency to get this model to work in OMC, I would refrain from changing the source code. OMC really should handle time events properly.
