### ISSUE TITLE
Duplicate Model broken with "// Modelica" comment

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#13302]
I have a complex model which I have reduced to the following small test case: 
```
within P.SP;
model myModel
  Modelica.Blocks.Continuous.Integrator myInt() annotation(
  // Modelica
    Placement(visible = true, transformation(origin = {70, 90}, extent = {{10, -10}, {-10, 10}}, rotation = 0)));
end myModel;
```
(Full package attached as a zip file: [P.zip](https://github.com/user-attachments/files/17945990/P.zip)
)

Opening this, pressing right on myModel -> Duplicate, choosing some name, and pressing OK gives:
![image](https://github.com/user-attachments/assets/1ea949f7-3c0f-4e2f-9950-1981d6a94a21)
(side note: this text cannot be selected/copied to clipboard, which is annoying)

Removing the `  // Modelica` line makes Duplicate work.

 OpenModelica v1.25.0-dev-174-g92fc808a19 (also seen on latest release), Windows 10

**Comment by bilderbuchi** [comment]
To avoid distraction (even though it is fully above-board), instead of `myModel` naming the model `bla` or somesuch does not avoid the problem.

**Comment by perost** [comment]
> @perost `copyClass` API fails in this case without any error message.

Fixed with #13308.

**Comment by casella** [comment]
@bilderbuchi please check with the next nightly and close if it works for you

**Comment by casella** [comment]
BTW, which other modeling and simulation tool gives you a fix in 5 hrs time? 😄

**Comment by bilderbuchi** [comment]
> BTW, which other modeling and simulation tool gives you a fix in 5 hrs time? 😄

None that I am familiar with. I also know that this was not the first time of such a speedy turnaround, and it's pretty awesome when it happens! 😄
I trust y'all are aware of my/our appreciation, in here I can't do much more than say thank you and dole out ❤️. :-P

**Comment by bilderbuchi** [comment]
> @bilderbuchi please check with the next nightly and close if it works for you

Fix confirmed, thank you!
