### ISSUE TITLE
Replaceable dropdown appearance depends on choicesAllMatching annotation

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#13304]
### Description

The syntax of the choices in a replaceable dropdown depends on the `choicesAllMatching `keyword.

### Steps to Reproduce

1. Load the following modelica package
```modelica
package DropdownAppearance
    model ClassWithComponents
  ClassWithReplaceables classWithReplaceables annotation(
      Placement(transformation(extent = {{-10, -10}, {10, 10}})));
  end ClassWithComponents;

  model ClassWithReplaceables
  
  replaceable DropdownAppearance.BaseRecord recordWithAllMatching constrainedby DropdownAppearance.BaseRecord "Replaceable record with choicesAllMatching" annotation (
      choicesAllMatching=true);

  replaceable DropdownAppearance.BaseRecord recordWithChoices "Replaceable record with explicit choices"
  annotation(choices(choice( redeclare DropdownAppearance.BaseRecord recordWithChoices "Record choice description")));
  
  end ClassWithReplaceables;

  model BaseRecord "Record class description"
  parameter Real a = 1;
  end BaseRecord;
  
end DropdownAppearance;
```
2. Open the class `ClassWithComponents` and there the parameter dialog of the `classWithReplaceables` component.
3. Inspect the dropdown menu appearance of both replaceables.

With choicesAllMatching (`classWithReplaceablesrecordWithAllMatching`) only path and comment are displayed:
![{2ADF7961-94F0-46D4-BC16-B55971357B00}](https://github.com/user-attachments/assets/2ca08924-3801-486a-ab71-39b612d4494f)

With explicit choices(`classWithReplaceables.recordWithChoices`) the complete redeclare statement is displayed:
![{0B3D77A8-FC06-4AC6-AE08-19E946C60E1E}](https://github.com/user-attachments/assets/2dc73450-7d79-451d-a3b7-db48786b8d84)

### Expected Behavior

We expect that all replaceable dropdown choices are displayed in the same way (complete redeclare statement or path + comment) no matter if the choices are explicitly defined or extracted by OMEdit.

We at Bosch Rexroth prefer the "path + comment" option because the "redeclare" keyword does not add value in our opinion but as I understood from the discussion in #10212 the "complete redeclare statement" option is already agreed upon.

### Version and OS

 - OpenModelica Version: v1.25.0-dev-191-g9288a73aaf
 - OS: Windows 11, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
With `choices` you are suppose to show the entire choice string as option but with `choicesAllMatching` we show the matching subtypes of the class which is of course not standardized. So it is not clear how they should appear. Anyway with PR #13314 I tried to unify the way options are shown.

**Comment by abuntrock** [comment]
Thanks @adeas31.
With todays nightly the dropdown appearance is the same independent from `choicesAllMatching` for the use cases in our library.
