### ISSUE TITLE
Dynamicselect behaviour

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#13317]
According to MS 18.6.6, a DinamicSelect object should update its appearence during the simulation. 

In OM, according to my tests, instead, DynamicSelect objects have the apparence corresponding to the values variables have at the initial instant of the simulation.

Consider the following example:

```
package Test1
model DynSelect
Real y=time;

  annotation (
    Icon(graphics={  Rectangle(fillColor = {255, 255, 255},
fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}),
Text(origin={97,-11}, extent={{-195,23},{0, 0}},
textString = DynamicSelect("time", String(y, 3, 0, true)))}));
end DynSelect;

  model M
    DynSelect dynSelect annotation (
      Placement(transformation(origin = {2, 0}, extent = {{-10, -10}, {10, 10}})));
  equation
  annotation(
      experiment(StartTime = 1, StopTime = 2, Tolerance = 1e-06, Interval = 0.002));
end M;
end Test1;
```

OM should show during the simulation time, and in particular at the end of the simulation the final time, i.e. 2, while it shows, instead, the initial value, which is 1.

### Expected Behavior
I expect to see the value variables have during the simulation and when the simulation has finished, the final time.

### Version and OS
Tested with OM 1.23.1

**Comment by casella** [comment]
@ceraolo, all arguments of String except the first one must be passed as named arguments, see [MLS 3.7.1 Operator 3.3](https://specification.modelica.org/maint/3.6/operators-and-expressions.html#modelica:to-String).

If you write `String(y, significantDigits = 3, minimumLength = 0, leftJustified = true)`, the DynamiSelect operator works fine.

**Comment by casella** [comment]
I would also recommend  use 1.24.2 instead of 1.23.1. Lots of [issues](https://github.com/OpenModelica/OpenModelica/issues?q=is%3Aissue+is%3Aclosed+milestone%3A1.24.0+-is%3Ainvalid) were solved in it.

**Comment by ceraolo** [comment]
> @ceraolo, all arguments of String except the first one must be passed as named arguments, see [MLS 3.7.1 Operator 3.3](https://specification.modelica.org/maint/3.6/operators-and-expressions.html#modelica:to-String).
> 
> If you write `String(y, significantDigits = 3, minimumLength = 0, leftJustified = true)`, the DynamiSelect operator works fine.

Thank you, Francesco  this is very useful for me!

**Comment by ceraolo** [comment]
> I would also recommend use 1.24.2 instead of 1.23.1. Lots of [issues](https://github.com/OpenModelica/OpenModelica/issues?q=is%3Aissue+is%3Aclosed+milestone%3A1.24.0+-is%3Ainvalid) were solved in it.

I usually check the latest nightly before posting tickets, but in this case I did not, because I did not expect changes.
BTW, I have on my pc newer versions, but for teaching I must use the one available at the beginning of each academic year, i.e. end of  August, at the latest. This year, 1.23.1.

**Comment by casella** [comment]
> Unfortunately, I could not replicate your result...

Because you are not using the latests nightly build, I guess.

> @casella, are you sure you want to shut down this ticket?

I'm afraid we cannot fix past released versions, unless you have access to a time machine 😄

**Comment by ceraolo** [comment]
I mean that OM does not update the field "time", also in its recent versions (just tried with 1.25.0-dev191)

**Comment by casella** [comment]
This one works for me, OMC v1.25.0-dev-157-g7a05431bba (64-bit)
```modelica
package Test1
  model DynSelect
    Real y=time;
  annotation (
    Icon(graphics={  Rectangle(fillColor = {255, 255, 255},
    fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}),
    Text(origin={97,-11}, extent={{-195,23},{0, 0}},
    textString = DynamicSelect("time", String(y, significantDigits = 3, minimumLength = 0, leftJustified = true)))}));
end DynSelect;

  model M
    DynSelect dynSelect annotation (Placement(transformation(origin = {2, 0}, extent = {{-10, -10}, {10, 10}})));
  equation
  annotation(experiment(StartTime = 1, StopTime = 2, Tolerance = 1e-06, Interval = 0.002));
  end M;
end Test1;
```
![immagine](https://github.com/user-attachments/assets/7ddc8bed-878b-4bec-b8e9-0371d6ec73d2)

**Comment by casella** [comment]
Of course you need to press the "play" button to see the results evolving. Maybe we could pre-load the outputs at the initial time, so that you can see the initial values outright. 

@ceraolo is that what you mean?

**Comment by ceraolo** [comment]
This discussion is becoming kakafkian ...
Obviousy I press play! Do you? 
I'll upload  a shirt video in a few minutes

**Comment by ceraolo** [comment]
> This one works for me, OMC v1.25.0-dev-157-g7a05431bba (64-bit)

I see, in your screenshot 1.24, which is not good. The final value (here 2) shoud be displaied shoundn't it?

My result is worse, as you can see in this video (1.25.0-dev191):
[Screencast from 2024-12-02 09-22-52.webm](https://github.com/user-attachments/assets/cac45b73-685e-473a-949b-82ab3e4e6f7d)

**Comment by ceraolo** [comment]
I can envisage what happens.
1. the sample time on which the label is updated is not under the users's control. In my case, even if I reduce the timestep to tiny values, to make the simulation longer, the label is not got updated, with some reason
2. the final value (erroneoously is not shown.

Maybe in your case the label is updated during the triansient.

For completeness I add a video from Dymola 2024x here:
 _(coming soon: I must switch to another PC)_

**Comment by adeas31** [comment]
> > This one works for me, OMC v1.25.0-dev-157-g7a05431bba (64-bit)
> 
> I see, in your screenshot 1.24, which is not good. The final value (here 2) shoud be displaied shoundn't it?
> 
> My result is worse, as you can see in this video (1.25.0-dev191): [Screencast from 2024-12-02 09-22-52.webm](https://github.com/user-attachments/assets/cac45b73-685e-473a-949b-82ab3e4e6f7d)

@ceraolo you only simulated the model. You did not run the animation. The animation controls are located in the `Variable Browser`.

After the simulation you should open the `Diagram Window` in plotting perspective and then click on the play button.

![{0712F8EB-B33B-4816-85D6-A544A34C6C88}](https://github.com/user-attachments/assets/b8b42fc2-6260-428b-926b-ab641327b621)

**Comment by casella** [comment]
Sorry, I thought that was obvious, probably it wasn't...

**Comment by casella** [comment]
@ceraolo at the moment when the simulation is finished the diagram is displayed with the editing string ("time" in this case). Should we automatically load the initial value, consistently with the status of the animation controls?

**Comment by ceraolo** [comment]
I've just checked (using OM 1.25-dev210) with PowerGrids - Develop version, model Examples.ENTSOE.PowerFlow, and the numerival values are displayed, corresponding to t=0. This is good for me.
Using the same OM with the Test1.mo of this ticket, I see 1, which again is the initial value, and ok for me. If change the initial time to 1.5, I see 1.5 on the diagram.

**Comment by casella** [comment]
> I've just checked (using OM 1.25-dev210) with PowerGrids - Develop version, model Examples.ENTSOE.PowerFlow, and the numerical values are displayed, corresponding to t=0. 

Indeed, this was fixed from the old nightly I was using, I confirm this behaviour on the latest nightly.

> This is good for me. Using the same OM with the Test1.mo of this ticket, I see 1, which again is the initial value, and ok for me. If change the initial time to 1.5, I see 1.5 on the diagram.

OK, all's well that ends well.
