### ISSUE TITLE
Branch name in library testing changed 

### ISSUE THREAD

**Issue by FWuellhorst** [OpenModelica/OpenModelica#13311]
### Description

We renamed master to main in `AixLib`. Apparently, your testing webpage renamed main to master for the url, because the new models of the latest release show up in the report: https://libraries.openmodelica.org/branches/master/AixLib/AixLib.html
Are you planning on keeping this rename? If so, we will add a case for our CI pipeline to replace main with master to link to this page.

### Expected Behavior

Have the report available at https://libraries.openmodelica.org/branches/main/AixLib/AixLib.html

**Comment by adrpo** [comment]
We are testing two branches, one is the default ("main" or "master") and the other one is "development":
https://github.com/OpenModelica/OpenModelicaLibraryTesting/blob/master/configs/conf.json#L152

The "master" that appears in the URL is for OpenModelica "master" branch, the "nightly-build" OpenModelica.
For example, we also have: https://libraries.openmodelica.org/branches/v1.24/AixLib/ and https://libraries.openmodelica.org/branches/v1.24/AixLib_latest/ for the OpenModelica latest release.

**Comment by FWuellhorst** [comment]
Ok, thanks for the clarification, makes sense! We removed the development, as our CI is now extensive and we only require main. Thus, you can just test the default branch.

**Comment by adrpo** [comment]
Ok, I will remove AixLib "development" testing.

**Comment by adrpo** [comment]
We could add "libraryVersion":"main" and "libraryVersionNameForTests":"main" then you would get an url like:
https://libraries.openmodelica.org/branches/master/AixLib_main/AixLib_main.html

Let me know if we should keep it like it is or change it to include the branch in the name.

**Comment by adrpo** [comment]
I also changed branch "master" to "main" for AixLib in our PackageManager:
https://github.com/OpenModelica/OMPackageManager/commit/ce9b1cce30e210a6530461c18012f714862d3eab

**Comment by FWuellhorst** [comment]
> Let me know if we should keep it like it is or change it to include the branch in the name.

No need to do that, thanks!

**Comment by adrpo** [comment]
Closing this as fixed.
