### ISSUE TITLE
Regression: Parameter dialog of nested replaceable cannot be opened multiple times

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#13334]
### Description

After parameterizing and closing a class with nested replaceables, one cannot open all replaceable levels again after reopening the dialog. This has to be some kind of regression problem because otherwise the tickets #10659 and #10669 could not have been solved. However, the problem described here even exists for OMEdit 1.22.0, which is the oldest OMEdit version I still have installed.

### Steps to Reproduce

1.Open the following modelica package:
```modelica
package NestedReplaceableDialog

    model ClassWithInstance
  ClassWithReplaceable classWithReplaceable annotation(
      Placement(transformation(origin = {2, 0}, extent = {{-10, -10}, {10, 10}})));
  end ClassWithInstance;

  model ClassWithReplaceable
  replaceable NestedReplaceableDialog.SubLevel1 firstLevel
  annotation(choices(choice( redeclare NestedReplaceableDialog.SubLevel1 firstLevel)));
  end ClassWithReplaceable;

  model SubLevel1
  parameter Real a = 5;
  replaceable parameter NestedReplaceableDialog.SubLevel2 secondLevel
  annotation(choices(choice( redeclare NestedReplaceableDialog.SubLevel2 secondLevel)));
  end SubLevel1;

  record SubLevel2
  parameter Real b = 2;
  end SubLevel2;
end NestedReplaceableDialog;
```
2. Open the instance `classWithReplaceable` in class `ClassWithInstance`. Then select something in both nested replaceable dropdowns and add a value for parameter `b`. Close all three dialog windows and reopen them. The replaceable parameter `secondLevel` is no longer visible in the parameter dialog of `classWithReplaceable.firstLevel` as shown in the attached video.

https://github.com/user-attachments/assets/f4b5ffba-2cc9-4046-b085-dec85234c2e5

### Expected Behavior

One can always open all layers of a nested replaceable construct via the GUI edit button. This problem is our biggest OMEdit issue now at Bosch Rexroth.

### Version and OS

 - OpenModelica Version: 1.24.2 und v1.25.0-dev-210-ge91d746f9e
 - OS: Windows 11, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by adeas31** [comment]
I tracked it down to #11311. We hide the parameter/element if it is redeclared and not replaceable.

Maybe we should check for it when showing the top level and not for nested level. I have no idea.

**Comment by abuntrock** [comment]
Thanks for tracking it down. The issue mentioned by you is important as well (also for us).

Maybe it needs to be checked if the redeclaration of the nested replaceable happens in the class itself (in my example in `ClasWithInstance`) and not in the subclass' class definition. 

If `secondLevel` would be redeclared as part of the instantiation of `firstLevel` in class `ClassWithReplaceable` we also do not want it to be shown in the parameter dialog.

**Comment by adeas31** [comment]
> If secondLevel would be redeclared as part of the instantiation of firstLevel in class ClassWithReplaceable we also do not want it to be shown in the parameter dialog.

I did not get this part. Can you please come up with examples when it should or should not be shown.

**Comment by abuntrock** [comment]
For toplevel replaceables it also already works since I can change the value of `firstLevel` after reopening of the parameter dialog even though it is redeclared and not replaceable. So from my naive understanding there has to be some logic that "knows" that the redeclaration takes place in the class one is currently in.

Sorry for my non-technical wording. I do not know how to describe this better.

I will provide an example for my previous post.

**Comment by abuntrock** [comment]
Here is an example where I cannot change `secondLevel` when opening the parameter dialog of `classWithReplaceable.firstLevel` in 'ClassWithInstance' when opening the parameter dialog for the first time, which is correct as a result of #11311 and we also expect it like this.
For this I just slightly changed my original example (see constraindedby clause at `firstLevel` in `ClassWithReplaceable`.
```modelica
package NestedReplaceableDialog2
    model ClassWithInstance
  NestedReplaceableDialog2.ClassWithReplaceable classWithReplaceable annotation(
      Placement(transformation(origin = {2, 0}, extent = {{-10, -10}, {10, 10}})));
  end ClassWithInstance;

  model ClassWithReplaceable
  replaceable NestedReplaceableDialog2.SubLevel1 firstLevel
  constrainedby NestedReplaceableDialog2.SubLevel1(redeclare NestedReplaceableDialog2.SubLevel2 secondLevel)
  annotation(choices(choice(redeclare NestedReplaceableDialog2.SubLevel1 firstLevel)));
  end ClassWithReplaceable;

  model SubLevel1
  parameter Real a = 5;
  replaceable parameter NestedReplaceableDialog2.SubLevel2 secondLevel
  annotation(choices(choice( redeclare NestedReplaceableDialog2.SubLevel2 secondLevel)));
  end SubLevel1;

  record SubLevel2
  parameter Real b = 2;
  end SubLevel2;
end NestedReplaceableDialog2;
```
To be able to open `secondLevel` when opening the parameter dialog of `classWithReplaceable.firstLevel` in the above example I need to change the constrainedby clause to 
 `constrainedby NestedReplaceableDialog2.SubLevel1(redeclare replaceable NestedReplaceableDialog2.SubLevel2 secondLevel)`, which works perfectly and is the expected behavior.


To reiterate, in the example from the original post I should be able to change `secondLevel` when opening the parameter dialog of `classWithReplaceable.firstLevel`. However, it is only possible once. In the example from this post I should not be able to change it, which is the case and expected.
I hope this helps.

**Comment by adeas31** [comment]
Please test PR #13398 with your actual models. I have tested the above examples and #11311 and it works as expected.

**Comment by abuntrock** [comment]
I will check with the next nightly build. Thanks a lot.

**Comment by abuntrock** [comment]
It works also with our actual models. Thanks a lot. This was very important to us.

If there is any 1.24.3 version needed we would love the see this fix in there if possible. Otherwise we`ll  wait for the 1.25.0 version.

**Comment by adeas31** [comment]
I have ported the fix to maintenance branch. See #13403.

1.24.3 is planned. @adrpo will make it soon.
