### ISSUE TITLE
Issue for script Api getAnnotationModifierValue

### ISSUE THREAD

**Issue by onesandineye** [OpenModelica/OpenModelica#13332]
### Description

Call getAnnotationNamedModifiers(Modelica.Blocks.Examples.SlewRateLimiter,"experiment") in OMShell, it's return {"StopTime", "Interval"},
and then call getAnnotationModifierValue(Modelica.Blocks.Examples.SlewRateLimiter,"experiment","StopTime"), it's return empty, I think it should be return 1.0

Is that right?

 - OpenModelica Version: 1.24.2
 - OS: Win11 64bit
 - Modelica: 4.0.0

**Comment by perost** [comment]
Fixed with #13335. `getAnnotationModifierValue` was for some reason implemented to only work for string modifiers, I changed it to handle other types of expressions too.
