### ISSUE TITLE
Missing initialization of the first state variable in OMEdit 1.23.2 Parameters dialog

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OpenModelica#13333]
### Description

I just noticed with students a strange bug in the OMEdit Parameters dialog, in the Initialization section: it seems that the first state variable is forgotten in the list of variables to be initialized!

### Steps to Reproduce

In OMEdit 1.24.2,

1. create blank Model
2. drag and drop a `Modelica.Electrical.Analog.Basic.Capacitor` and `Modelica.Mechanics.Translational.Components.Mass`
3. For each of these two components, opens the Parameters dialog:
  - for the capacitor, there is no variable `v` to be initialized (cf screenshot 1)
  - for the mass, the position initialization is missing (only `v` and `a` are left, cf screenshot 2)

### Expected Behavior

All state variables should be listed in the Initialization section.

### Screenshots

![Parameters dialog of the Capacitor: missing v init](https://github.com/user-attachments/assets/fec7ef1d-a24e-4719-acbc-346516eb4f60)
![Parameters dialog of the Mass: missing s init](https://github.com/user-attachments/assets/fbc9f169-d49c-47bd-b598-a7120f901766)

### Version and OS

 - OpenModelica Version: OpenModelica 1.24.2
 - OS: Windows 10, 64 bit and Ubuntu
 - MSL 4.0.0

### Additional Context

In 1.23.?, this bug is not present.

**Comment by casella** [comment]
@pierre-haessig thanks for reporting! I had noticed this behaviour recently, I told myself I had to investigate it, but didn't do that

@adeas31 this is clearly a regression and should be fixed in 1.24.3 ASAP

**Comment by adeas31** [comment]
This was a regression from the fix for #12898.

Fixed with #13359 and ported to maintenance/v1.24 with #13362

**Comment by casella** [comment]
@pierre-haessig can you confirm the correct behaviour with the latest nightly build?

**Comment by casella** [comment]
We will release 1.24.3 with this fix soon. 

@pierre-haessig thanks for reporting!

**Comment by casella** [comment]
Thanks again for reporting 😃
