### ISSUE TITLE
Some MSL classes throw an error when checked

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#13364]
### Description
When checking "Check Model" one of the following four MSL classes 

- Modelica.Icons.TypeReal
- Modelica.Icons.TypeInteger
- Modelica.Icons.TypeBoolean
- Modelica.Icons.TypeString

with OMEdit 1.24.2 the following error occurs:
![{9FA52744-6B6B-4C41-A385-DB312902250C}](https://github.com/user-attachments/assets/5b6a87c0-3a81-4d9f-a9bb-64fab8de8c18)

### Expected Behavior

All MSL models can be checked without an error.
I was not sure if had to post this issue here or in the MA github. I first tried here since the models successfully check with Dymola.

### Version and OS

 - OpenModelica Version: 1.24.2
 - OS: Windows 11, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth

**Comment by perost** [comment]
>I was not sure if had to post this issue here or in the MA github. I first tried here since the models successfully check with Dymola.

If you get an internal error you can assume that it's a compiler issue and report it here, those should never occur even if the model happens to be invalid in some way.

**Comment by abuntrock** [comment]
Is it possible to get this into an 1.24.3 release?

**Comment by casella** [comment]
Too late for that, but we could make a 1.24.4.

**Comment by abuntrock** [comment]
You do not have to make a 1.24.4 just for that. Its not that important for us.

**Comment by casella** [comment]
OK. We'll make 1.25.0 soon anyway.
