### ISSUE TITLE
Issue For getNthInheritedClassIconMapAnnotation and getNthInheritedClassDiagramMapAnnotation

### ISSUE THREAD

**Issue by onesandineye** [OpenModelica/OpenModelica#13374]
### Description

I tested getNthInheritedClassIconMapAnnotation script api in OMShell

getNthInheritedClassIconMapAnnotation(Modelica.Blocks.Examples.Filter,1)

The result is following:
{Modelica.Icons.Example, {}}

but the Modelica.Icons.Example model has Icon annotation.

![image](https://github.com/user-attachments/assets/1c51b5c1-a7e4-4e3a-8e27-6c8f88a406b1)

whether the Api didn't return the correct result or i didn't use it correctly?

and the getNthInheritedClassDiagramMapAnnotation api seems also has same issue.

 - OpenModelica Version: 1.24.2
 - OS: win11
 - Modelica: 4.0.0

**Comment by perost** [comment]
The API:s you mention return the `IconMap` and `DiagramMap` annotations, not `Icon` and `Diagram`. We don't seem to have the corresponding functions for getting the `Icon` and `Diagram` annotations, but they're oddly specific so I assume someone just needed that particular functionality at some point and added those API:s.

You can instead use e.g. `getIconAnnotation(getNthInheritedClass(Modelica.Blocks.Examples.Filter, 1))`.
