### ISSUE TITLE
Wrong prefix for units that include a power

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#13379]
Please consider this MWE
```modelica
model Test
  Modelica.Units.SI.Length H;
  Modelica.Units.SI.VolumeFlowRate q;
equation
  H = 5 - 0.75e3*q - 0.125e6*q^2;
  q = time*0.004;
end Test;
```
the parametric plot H vs. q looks like this:
![immagine](https://github.com/user-attachments/assets/1608c6d0-8cf7-48f8-81d7-2768677a8c2a)

with the unit for q declared as "mm3/s". This is obviously wrong: milli(cubic meters per second) is not the same as cubic millimeters per second, which is how you should read mm3/s.

So, we should be careful when applying prefixes to units that include powers. As a starting point, we should probably not apply them at all.

BTW, for volume flow rate it would be good to have extra display units l/s, which is 0.001 m3/s, and maybe also m3/h, which is 1/3600 m3/s.

**Comment by ceraolo** [comment]
The rule is simple, but many disregard it.
_Prefixes are part of the unit_. That's all.

 cm^2 means (cm)^2.

I've found very authoritative sources discussing 1 Gm^3 meaning one billion of cubic metrers, but these authoritative sources are plainly wrong.
One Gm^3 is 10^27 m^3 !!     One billion m^3 is one km^3,

**Comment by casella** [comment]
Absolutely. No question that 1 km^3 is one cubic kilometer (the volume of a medium-sized lake), not 1000 cubic meters (which is more like a cargo train with tanks can carry).

**Comment by ceraolo** [comment]
From BIPM-SI-Brochure:
![image](https://github.com/user-attachments/assets/73c07cca-33db-48b6-be97-2ae513ef0a21)

**Comment by adeas31** [comment]
> So, we should be careful when applying prefixes to units that include powers. As a starting point, we should probably not apply them at all.

Yeah there shouldn't be any prefix for `m3/s`. This was just a stupid mistake in the code. Should be fine with #13383. Btw, this only happens with parametric plots. I will port the fix to maintenance branch.

**Comment by ceraolo** [comment]
> > So, we should be careful when applying prefixes to units that include powers. As a starting point, we should probably not apply them at all.
> 
> Yeah there shouldn't be any prefix for `m3/s`. 

If we want to keep it siomple this is right.

In more general terms, units with powers _can_ have prefixes, as cm^2 or kg^2, etc.. See 
https://github.com/OpenModelica/OpenModelica/issues/13379#issuecomment-2536058129

**Comment by adeas31** [comment]
> > > So, we should be careful when applying prefixes to units that include powers. As a starting point, we should probably not apply them at all.
> > 
> > 
> > Yeah there shouldn't be any prefix for `m3/s`.
> 
> If we want to keep it simple this is right. In more general terms, units with powers _can_ have prefixes, as in cm^2 or kg^2, etc.. See [#13379 (comment)](https://github.com/OpenModelica/OpenModelica/issues/13379#issuecomment-2536058129)

For now we want to keep it simple. We can of course improve it later with next OM release.

Btw, how do we write cubic millimeters per second?

**Comment by adeas31** [comment]
> BTW, for volume flow rate it would be good to have extra display units l/s, which is 0.001 m3/s, and maybe also m3/h, which is 1/3600 m3/s.

Done with PR #13385. I made a new PR since we don't want to port this change. This is an enhancement.

**Comment by adeas31** [comment]
Ported to maintenance/v1.24 with PR #13386.

**Comment by ceraolo** [comment]
> Btw, how do we write cubic millimeters per second?

mm^3/s

**Comment by adeas31** [comment]
I don't get it. This is what @casella reported in the first [comment](https://github.com/OpenModelica/OpenModelica/issues/13379#issue-2732610600). Was it the wrong prefix or the wrong value?

**Comment by ceraolo** [comment]
cubic millimiters per second are written mm^3/s.

In the Casella's example Casella says that we did not have cubic millimeters per second, we had 10^(-3)*m^3/s, which is equivalent to dm^3/s

**Comment by casella** [comment]
Yep. 

You had 0.004 m3/s. There are (10^3)^3 = 10^9 cubic millimiters in a cubic meter, so the value in mm^3/s should have been 4e6, not 4.

@ceraolo currently we are only using the 10^k*3 multiples: milli, micro, nano, pico, etc. and kilo, mega, giga, tera, etc.. We may also introduce deci, centi and deca, hecto. I don't think they will be very useful for base units (you can plot in millimiters or centimeters, it's basically the same), but they could be used for units with power, e.g. dm^3 or cm^3.

In this case, the best unit would have been dm^3/s, and the result would have been 0.004 m3/s = 4 dm3/s.

But I think for the time being we should stick with what we have, fix bugs and avoid breaking it.

@adeas31, as I wrote, it may be useful to add "l/s" and "m3/h" to the display units for volume flow rate, because they are widely used in practical applications - m3/s is in most cases a too large unit, unless you model power plants or aeroengines.

**Comment by casella** [comment]
> @adeas31, as I wrote, it may be useful to add "l/s" and "m3/h" to the display units for volume flow rate, because they are widely used in practical applications - m3/s is in most cases a too large unit, unless you model power plants or aeroengines.

sorry, I see now they were added in #13385. I guess we can close this.

**Comment by ceraolo** [comment]
> @ceraolo currently we are only using the 10^k*3 multiples: milli, micro, nano, pico, etc. and kilo, mega, giga, tera, etc.. We may also introduce deci, centi and deca, hecto. I don't think they will be very useful for base units 

Prefixes such as deci and centi are rather rarely used. A significant exception is dm3 and cm3 (they are commonly used also outside technical contexts)
I would never had proposed using deci and centi in all situations (ley alone deca!); an excepion for dm3 and cm3 would have been nice, but it not essential.
