### ISSUE TITLE
Issues with missing dll dependencies when exporting an FMU

### ISSUE THREAD

**Issue by thomash303** [OpenModelica/OpenModelica#13435]
### Description

I have created a simple pendulum model in OpenModelica and have exported it as as FMU to run using FMPython. It appears I am running into the issue outlined in (#12013). I tried to manually set the compiler flag to
 --fmuRuntimeDepends=modelica as recommended in the linked StackOverflow discussion but am still getting the same error. 

### Version and OS

 - OpenModelica Version: v1.24.0 (64-bit)
 - OS: Windows 11, 64 bit]

### Additional Context

I see that @AnHeuermann has worked on this issue previously so have added here.

**Comment by adrpo** [comment]
Please take v1.24.3:
https://build.openmodelica.org/omc/builds/windows/releases/1.24/3/64bit/

Or the nightly build.

**Comment by adrpo** [comment]
I have updated cmake in v1.24.3 and also ported some more fixes from master with runtime dependency handling.

**Comment by thomash303** [comment]
@adrpo The simulations now run successfully, thank you for your help!

**Comment by adrpo** [comment]
Welcome!
