### ISSUE TITLE
annotation(Dialog(enable = ...)) is not working correctly

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#2661]

**Comment by casella** [comment]
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/2661

**Comment by casella** [comment]
Wow! A 9-year-old ticket was finally fixed for good 😎

**Comment by dietmarw** [comment]
Although the issue is fixed the dialogue functionality of enabling and disabling a parameter field still does not work. Should it as part of the fix in #9846?

**Comment by adeas31** [comment]
The dialog functionality should work with `--NAPI=true` flag.

**Comment by casella** [comment]
@dietmarw, the idea is to eventually make that flag true by default in 1.21.0.

**Comment by dietmarw** [comment]
> The dialog functionality should work with `--NAPI=true` flag.

Ah yes, forgot about that. It does indeed work with the new API

**Comment by casella** [comment]
It's still not on by default because it breaks badly if some models fail to flatten, e.g. because you didn't load all the dependencies. @perost is currently working on that.
