### ISSUE TITLE
Synchronous Language Elements support in OpenModelica

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#2728]
A ticket to keep track of implementation of support for Clocked synchronous features
 - what is needed for front-end (new types? clock inference?)
 - what is needed for back-end (partitioning?)

------------
From https://trac.openmodelica.org/OpenModelica/ticket/2728

**Comment by AnHeuermann** [comment]
I guess this ticket was solved a long time ago.

OpenModelica supports synchronous language elements and the frontend and backend handle most of the features. The only problem is, that some details are not quiet working yet.
Everything else will be handled in #7854
