### ISSUE TITLE
Allow assumptions for unassigned parameters argument when checking partial models.

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#3304]

**Comment by bilderbuchi** [comment]
[Original issue](https://trac.openmodelica.org/OpenModelica/ticket/3304) description:
When building and debugging models it's quite handy to also be able to check partial models that have parameters without any binding equation. Dymola normally assigns either 0 or the min value if present. This is quite handy it would be nice to have.

**Comment by casella** [comment]
@bilderbuchi this ticket is quite old, maybe it is a bit outdated.

I checked these two models in OMEdit and they checked successfully
```modelica
model Test
  parameter Real p;
end Test;

partial model Test
  parameter Real p;
end Test;
```
Do you have any specific model that doesn't check because of this issue?

**Comment by bilderbuchi** [comment]
Yes, in #3944 ([link](https://github.com/OpenModelica/OpenModelica/issues/3944#issuecomment-1092766217)), which now exhibits a new error "Constant free_volume.Medium.singleState is used *without having been given a value*." (emphasis mine), hence the cross-reference to here.

I tried to break this further down into a smaller MWE with simpler models, but could not find a better repro.

**Comment by casella** [comment]
free_volume.Medium.singleState is a _package constant_, not a _parameter_. I guess we should close this issue and continue the discussion about the binding-less constant in #3944.
