### ISSUE TITLE
If +std=3.3 is set there are issues when using Modelica.Blocks.Sources.Clock

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#3860]
Consider the following model: 

```modelica
model Test
  Modelica.Blocks.Sources.Clock clock1;
  Modelica.Blocks.Logical.Greater greater1;
  Modelica.Blocks.Sources.RealExpression realExpression1(y=time - 1);
equation
  connect(realExpression1.y, greater1.u2);
  connect(greater1.u1, clock1.y);
end Test;
```

When checked it generates the following error message:
```
[Test: 7:3-7:33]: Failed to instantiate equation connect(greater1.u1, clock1.y);
```

This seems to be a bug.

OMEdit v1.10.0-dev-95-gdcd1258
Connected to OpenModelica v1.10.0-dev-324-g50cddbb

-----------
Taken from https://trac.openmodelica.org/OpenModelica/ticket/3860

**Comment by AnHeuermann** [comment]
See https://trac.openmodelica.org/OpenModelica/ticket/3860#comment:11
