### ISSUE TITLE
Simulation crashes in libstdc++-6.dll using ExternalMedia

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#3981]

**Comment by bilderbuchi** [comment]
Upstream: https://trac.openmodelica.org/OpenModelica/ticket/3981

This issue is 7 years old, most probably it can be closed (with the recent ExternalMedia release working in OM), and any further issues placed in a fresh issue.

**Comment by casella** [comment]
Absolutely

**Comment by mahge** [comment]
Probably the same as https://github.com/OpenModelica/OpenModelica/issues/8738. Fixed in https://github.com/OpenModelica/OpenModelica/pull/8961.
