### ISSUE TITLE
OMEdit Plot: Log scale dose not take settings from zoom box

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4015]

**Comment by mpradovelasco** [comment]
Hi, I would want to report a bug with this issue, but it is open. I would like to point that this is a very important functionality during the simulation of drugs transport. 
Starting from this plot:

![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/00dabe7a-83a5-4a73-a137-9be9a668d1d6)
The zoom box works fine with the lineal scale (some times it fails, but it is infrequent), 

![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/2ae0a7de-7ac4-4a41-b19a-70de5c838662)

But if I convert to log Y: 

![image](https://github.com/OpenModelica/OpenModelica/assets/114144098/e2100e92-ad84-429b-bff9-d8ad046f142b)
If I try to apply a zoom box, it does not work and thus it is not possible to analyze the function with the logarithmic scale. 

Thank you!

**Comment by casella** [comment]
Could be related to #7468, which we should fix ASAP.
