### ISSUE TITLE
Use sparse solvers for event handling in daemode

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4034]

**Comment by casella** [comment]
Original trac ticket: https://trac.openmodelica.org/OpenModelica/ticket/4034

**Comment by casella** [comment]
As of Jan 2022, there is no longer any noticeable difference between the simulation time in [odeMode](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) and [daeMode](https://libraries.openmodelica.org/branches/newInst-daeMode/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) of the BreakerNetwork and BreakerNetworkDelayed. In both cases, simulation time scales as O(N^2) for larger models.

**Comment by casella** [comment]
I checked the odeMode model `BreakerNetwork_N_640_M_10` with the debugger, there is only one implicit linear system with 1922 equations, which is caught by the automatic sparse solver selection logic and solved with KLU. The performance in daeMode seems pretty similar, so it seems that the issue has been solved
