### ISSUE TITLE
Icon not rendered if visible annotation is used

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4236]

**Comment by casella** [comment]
See original trac [ticket #4236](https://trac.openmodelica.org/OpenModelica/ticket/4236)

**Comment by adrpo** [comment]
@adeas31 maybe we can test this ticket also with the new API, it should work I guess.

**Comment by casella** [comment]
@niklwors have you tried this recently with --NAPI=true?

**Comment by niklwors** [comment]
@casella  yes, I think the newly created tickets with the label [COMP/GUI/InstBased Interface](https://github.com/OpenModelica/OpenModelica/labels/COMP%2FGUI%2FInstBased%20Interface)  cover this case as well. E.g. the ticket: https://github.com/OpenModelica/OpenModelica/issues/9535

**Comment by adeas31** [comment]
@casella this is not handled yet.

**Comment by adeas31** [comment]
This is fixed now. Please test with `--NAPI=true` and reopen if you still have issues.
