### ISSUE TITLE
MacOS build lacks support for 3d animation + visualisation

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4358]

**Comment by casella** [comment]
@mrtompet, @Javier, @hkiel, @dersh, @mahge, can you comment on that?

**Comment by hkiel** [comment]
I just tried MSL4.Mechanics.MultiBody.Examples.Rotational3DEffects.GyroscopicEffects with "Simulate with Animation" and I can successfully play the 3D animation on my M1 macOS.

**Comment by casella** [comment]
Great, then we can close the old ticket for good
