### ISSUE TITLE
Properly fix handling of Clocks the front-end, back-end and codegen

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4363]
See PR:
​https://github.com/OpenModelica/OMCompiler/pull/1574

Currently we force in the front-end:
- evaluation of solverMethod in Clock (Static.mo)
- vectorization of clock operators (Static.mo)
because:
- back-end does not evaluate the solverMethod
- the C++ runtime does not support non-vectorized clock operators

This ticket is for fixing these issues:
1. revert PR ​https://github.com/OpenModelica/OMCompiler/pull/1574
2. implement evaluation of clocks in SynchronousFeatures.resolveClocks
3. add proper support for non-vectorized clocked operators in the C++ runtime

----------
Taken from https://trac.openmodelica.org/OpenModelica/ticket/4363

**Comment by AnHeuermann** [comment]
This ticket is very broad and I don't see what actually is missing now.
@casella Is this still relevant or should we create new issues for each left over problem?

**Comment by casella** [comment]
From what I understand this ticket is totally obsolete and superseded by recent improvements from @AnHeuermann and @rfranke, which are going into 1.19.0. I'd mark it as a duplicate of #7854.

We can open new tickets on the further improvements to synchronous systems.
