### ISSUE TITLE
Top level parameter settings

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4408]

**Comment by bilderbuchi** [comment]
Original description: https://trac.openmodelica.org/OpenModelica/ticket/4408

>  In order to manipulate the top-level parameters of a model from the graphical view, one could make a double-click on the canvas that opens a dialog which features all parameters (and maybe simulation settings annotations as well).

**Comment by casella** [comment]
Of course in this case the effect of the Parameters menu is not to change modifiers in some component instances, but rather to change the bindings of the model itself. Do we already have and API for that?

**Comment by adeas31** [comment]
> @adeas31 rather than double-clicking on the diagram, I would rather use right-click for consistency. Consider this MWE:
> 
> ```modelica
> model TestTopParameter
>   parameter Real p = 1;
>   parameter Real q = 2 annotation(Dialog(tab="Some Tab"));
> equation
> end TestTopParameter;
> ```
> 
> When you right-click on the diagram layer, you get:
> 
> ![immagine](https://private-user-images.githubusercontent.com/4233148/319362048-3d96b737-1bb4-421f-aeb9-620fd763fa73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODE3MjMsIm5iZiI6MTcxMjE4MTQyMywicGF0aCI6Ii80MjMzMTQ4LzMxOTM2MjA0OC0zZDk2YjczNy0xYmI0LTQyMWYtYWViOS02MjBmZDc2M2ZhNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMjE1NzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM1ZjkzNDQwZGQwYTJiMDBiODc1ODNkODYzZmVkMWFiZjI4Yjc3MGQzMWU0NDgwZDQzZTAxYTIzNmQzY2IwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2MaXP4iPRCAShCHovXePqudRak_PGmAj-Q_isLvP5hk)
> 
> I would add a _Parameters_ item to the menu; if you select it you should get the same parameter window you get when double-clicking on an instance of TestTopParameter:
> 
> ![immagine](https://private-user-images.githubusercontent.com/4233148/319362616-e0adbcdb-1ede-4f31-8d20-01fa7c400210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODE3MjMsIm5iZiI6MTcxMjE4MTQyMywicGF0aCI6Ii80MjMzMTQ4LzMxOTM2MjYxNi1lMGFkYmNkYi0xZWRlLTRmMzEtOGQyMC0wMWZhN2M0MDAyMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMjE1NzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRiNzcxODI5ZjYwNGRkN2I4YzUwYzdkNDc4ZDVmYTRiODdmNmViYzE3ZWQ3MDc4NGQ4NzdiZWUzZmUwM2EyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MYXufjh-dsRpqo9zQBIyEEqg_eA49qP4VIWVOrdLar8)
> 
> Adding @gwr69 to the loop.

Yes, I have the same in my mind. Already working on it.

**Comment by casella** [comment]
OK, we tentatively try to get it in 1.23.0, that would be nice.

**Comment by gwr69** [comment]
Great. From what I can see regarding where to offer the action "open parameter input window":

-  Right-clicking upon a selected class in the Libraries window
-  Right-clicking on the canvas (not a component or connection) in Diagram view
-  Right-clicking on the icon in Icon View
-  If a class is selected in Libraries view, then the View menu should offer an "enabled" entry "Parameters"

For completeness, variables that have `constant` variability, but have a `Dialog` annotation should be editable in such a Parameters window as well.

**Comment by adeas31** [comment]
> Great. From what I can see regarding where to offer the action "open parameter input window":
> 
> * Right-clicking upon a selected class in the Libraries window
> * Right-clicking on the canvas (not a component or connection) in Diagram view
> * Right-clicking on the icon in Icon View
> * If a class is selected in Libraries view, then the View menu should offer an "enabled" entry "Parameters"
> 

That will be unnecessarily too many places. It leads to extra code and maintenance. The most obvious place is of course **Right-clicking on the canvas (not a component or connection) in Diagram view**. I will start with this one and then we will see if there is need to have more starting points for this functionality.


> For completeness, variables that have `constant` variability, but have a `Dialog` annotation should be editable in such a Parameters window as well.

Sure. Can you provide a MWE.

**Comment by casella** [comment]
@adeas31, I guess this should do:
```
model M
  constant Real c = 1 annotation(Dialog(tab = "Constants"));
end M;
```

**Comment by adeas31** [comment]
I am not sure how to handle the top level replaceable elements. I guess when editing the top level then only parameters and variables should be shown.

**Comment by adrpo** [comment]
We should check what other tools do. We should also be able to edit the replaceable top level element by basically changing their binding or type.

```mo
replaceable restriction X = Y; // <---- change Y
replaceable T component;  // <--- only possible to change type T (I guess we already have support for that on double click if it is a visible component)
```

**Comment by adeas31** [comment]
Yeah I expected the binding to be updated with the current API but that is not the case. And we probably have no API to update the type. I will talk with @perost about it.

**Comment by casella** [comment]
I'm not sure about this. If you have something like
```modelica
replaceable model M = M1 constrainedby M0;
```
it seems reasonable to me that you can change `M1` to any other subclass of `M0`, because this won't break the model, as in the case of changing parameter values.

If you have
```modelica
replaceable model M1;
```
it would only make sense to change `M1` to a subclass of `M1`, say, `M2`, but then you would get
```
replaceable model M2;
```
and there won't be any way to get back to `M1`. If we don't have the restriction that you can only replace with a subclass, then it would be very easy to break the model. I'm not sure what would be the added value of this feature.

Ditto for replaceable components.

**Comment by gwr69** [comment]
My use case is typically something in this vein:

```
model M
    import BusinessSimulation.Units.*
    replaceable type ParameterType = Unspecified constainedby Unspecified; // where Unspecified = Real;
    parameter ParameterType globalParameter1 = ... ;
    ...
end M;
```

**Comment by adeas31** [comment]
Update: I had a discussion with @perost. He will add a new API that allows changing the type in case of replaceable components and will update that existing API to allow setting the binding value in case of short class definition.

**Comment by adeas31** [comment]
PR #12198 partially fixes the issue. The support for replaceable is still in progress.

**Comment by casella** [comment]
@adeas31, if top parameter settings is now in place I would close this, and open another one for top-level redeclares. This is a nice feature for 1.23.0 that should be mentioned in the release notes.

**Comment by adeas31** [comment]
> @adeas31, if top parameter settings is now in place I would close this, and open another one for top-level redeclares. This is a nice feature for 1.23.0 that should be mentioned in the release notes.

Yes, please do that.

**Comment by casella** [comment]
Mentioned in the 1.23.0 draft release notes.
