### ISSUE TITLE
Artifacts in plotting discrete simulation using synchronous Clock feature

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4481]
Hi,

I am testing the new Modelica_Synchronous features by building a simple discrete PI controller. The Clock() command seems to work fine but while plotting the outputs, there seems to be some unusual artefacts. There appears extra plot lines shown in the attached pictures.

Attaching simulation .mo files for testing.

Thanks,
Rahul

------
Taken from https://trac.openmodelica.org/OpenModelica/ticket/4481

**Comment by AnHeuermann** [comment]
The artifacts in the plot are still there and should be addressed while solving #7854.

**Comment by AnHeuermann** [comment]
I tested the original example as well and now it's looking correct.

![image](https://user-images.githubusercontent.com/38031952/145424950-d9d7098c-69e1-4c3d-a8d8-71d48d190b40.png)

**Comment by AnHeuermann** [comment]
Fixed in #8287

**Comment by casella** [comment]
Good that we have this in 1.19.0, though the implementation of Clocks there is still far from perfect.
