### ISSUE TITLE
Processing arrays of records fails

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4611]
Original ticket https://trac.openmodelica.org/OpenModelica/ticket/4611

This is similar but different from [#4606](https://trac.openmodelica.org/OpenModelica/ticket/4606)
I hope the solution is as straightforward as it was in that case!
Consider the following code:

```mo
package NumEqBug
  model TestLineZb
    parameter Real y[:] = {8, 10} ;
    Complex Z[2, 2];
  equation
      Z =LineZb(
        y=y );
  end TestLineZb;
  function LineZb
    import Modelica.ComplexMath;
    input Real y[2];
    output Complex Z[2, 2];
  algorithm
    Z:=fill(Complex(1,1),2,2);
  end LineZb;
end NumEqBug;
```

Checking TestLineZb I get 4 equations and 8 variables. I would expect 8 equations and 8 variables.
Note that y[] was included in the code even if it is not used because otherwise in the flattened code the function call is not included.
Tested with
v1.13.0-dev-188-g2c5818d (64-bit) for Win

**Comment by mahge** [comment]
The test now passes checkModel successfully. Unfortunately, it still fails in the backend with the error message:
```
Notification: Automatically loaded package Complex 4.0.0 due to usage.
Error: Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!
```

**Comment by max-privato** [comment]
Today I verified the behaviour witn OM 1.20.0, and got 8 variables and 8 equations as expected.

**I think this ticket can now be closed**
