### ISSUE TITLE
Badly wrong visualization in OMEdit in a simple case

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4839]

**Comment by jung40l** [comment]
This issue is also confirmed in version 1.20.0.

https://trac.openmodelica.org/OpenModelica/ticket/4839

[BugConnection.zip](https://github.com/OpenModelica/OpenModelica/files/10326814/BugConnection.zip)

**Comment by ceraolo** [comment]
I'm glad that other people than me is considering this.
After years of teaching I woild say it is the one single major barrier students meet when starting to use OMEdit. It  causes them not to like (sometimes to hate) this actually very useful SW.

**Comment by casella** [comment]
@ceraolo you are right. We have already considered a solution in #4645. 

@adeas31 could you please take care of this ASAP?
