### ISSUE TITLE
Split the 16dae.c source file into multiple files

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4851]

**Comment by casella** [comment]
Original ticket https://trac.openmodelica.org/OpenModelica/ticket/4851

**Comment by casella** [comment]
The file `modelName_16dae.c` should be split into `modelName_16dae_part0.c`,`modelName_16dae_part1.c`, etc. if the size goes above a certain threshold, same way as `modelName_06inz.c`, so that large models can benefit of multi-CPU machines to shorten the code generation time.

**Comment by casella** [comment]
@ceraolo, this should speed up the compilation phase significantly when running the larger PowerGrids tests, e.g. the IEEE14Bus models. Even more if you try larger models still.

**Comment by ceraolo** [comment]
I suppose it depends on how many cores you have on you CPU isn'it? Is the number of logical processes also meaningful?

Have you made a comparison with the IEEE14bus included in powerGrids? 
In principle I can try the same in one of the next days, but I first I must understand what I should expect, depending on the number of cores and logical processors  (I don' have a multi-CPU machine, if such a thing exists)

**Comment by adeas31** [comment]
OMEdit bydefault compiles the model code in parallel with option [Number of Processors](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#general) which is fetch using [numProcessors](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.numProcessors.html) API. This is using logical processors.

So instead of compiling one big file, we split it in multiple files so that it can be compiled in parallel.

**Comment by casella** [comment]
@ceraolo you sure have a multi-core CPU, unless your PC is more than 15 years old 😃. If it's a laptop, I guess it could have 4 or 8.

**Comment by ceraolo** [comment]
> Now I'm able to make tests on my machines.

well... when  IEEE14Bus models are working again!
I've checked today with Powergrids 2.0.0-develop downloaded the 19-th of February, but unfortunately none of the transient examples seems to be working with OM 1.23.0-dev-344.

**Comment by casella** [comment]
> well... when IEEE14Bus models are working again! I've checked today with Powergrids 2.0.0-develop downloaded the 19-th of February, but unfortunately none of the transient examples seems to be working with OM 1.23.0-dev-344.

This is weird, the latest [test report](https://libraries.openmodelica.org/branches/master/PowerGrids_dev/PowerGrids_dev.html) gives
![immagine](https://github.com/OpenModelica/OpenModelica/assets/4233148/c1bf0824-5bae-45d4-9b43-65758b7f2422)
Never mind verification results, those are still in the works. The IEEE14 bus tests simulate successfully.

**Comment by casella** [comment]
IEEE14busStaticNetwork works fine also on my laptop.

**Comment by casella** [comment]
PowerGrids.Examples.IEEE14bus.IEEE14busGen2Disconnection  also works fine.

I haven't checked the performance change, I'd need to uninstall and reinstall, too busy now...

**Comment by casella** [comment]
oops, I am using a nightly build which is older than Adrian's commit 2ab9ff8. I need to update it and re-check

**Comment by casella** [comment]
See #12055
