### ISSUE TITLE
[NF] Issues with inner/outer with redeclare

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#4908]
Attached model has an:

```modelica
inner SimCenter simCenter(
   contributeToCycleSummary = true, 
   redeclare TILMedia.VLEFluidTypes.TILMedia_InterpolatedWater fluid1,
   showExpertSummary = true);
```

where `fluid1` is modifying: (`nc_propertyCalculation = 1`) which
is then send to an outer: `outer SimCenter simCenter` from which is used in an array inside `Turbine_HP1`: `Turbine_HP1.medium.nc_propertyCalculation`.

What i get is:
```
[C:/home/adrpo33/dev/OMTesting/ClaRa/SteamCycle_01_total.mo:1382:7-1382:145:writable] 
Error: Could not evaluate structural parameter (or constant):
 Turbine_HP1.medium.nc_propertyCalculation which gives 
 dimensions of array: vleFluidNames. Array dimensions must be 
 known at compile time.
```

--------------
From https://trac.openmodelica.org/OpenModelica/ticket/4908

**Comment by adrpo** [comment]
https://trac.openmodelica.org/OpenModelica/ticket/4908

**Comment by adrpo** [comment]
This also happens with ClaRa1.7.0, model ClaRa.Examples.SteamCycle_01:
`
[ClaRa1.7.0/TILMedia 1.7.0 ClaRa/VLEFluidTypes/BaseVLEFluid.mo:16:3-18:42:writable] Error: Could not evaluate structural parameter (or constant): condenser.tubes.heattransfer.iCom.mediumModel.nc_propertyCalculation which gives dimensions of array: mixingRatio_propertyCalculation. Array dimensions must be known at compile time.
`

Of course, you get this error after fixing all bad case files/directories and the Real x(value = binding) that are in the library.

**Comment by adrpo** [comment]
A total model to be able to debug the bug: [SteamCycle_01.zip](https://github.com/OpenModelica/OpenModelica/files/7605456/SteamCycle_01.zip)

**Comment by perost** [comment]
With the fix in #8398 the model now incorrectly passes the frontend, which #8400 fixes and gives a proper error message:
```Modelica
ClaRa/Basics/ControlVolumes/FluidVolumes/VolumeVLE_2.mo:197:3-197:130:writable] Error: Type mismatch for positional argument 1 in sum(a=der(condenser.tubes.xi) * (condenser.tubes.bulk.drhodxi_ph)). The argument has type:
  Real
expected type:
  Array
```
The reason is that the model contains the expression `sum(der(xi)*bulk.drhodxi_ph)` where both `xi` and `bulk.drhodxi_ph` are vectors, so it's calling `sum()` on a scalar which as far as I know isn't allowed.

It would be trivial to allow it (Dymola does) since `sum` of a scalar would just be the scalar itself. I can't see any reason why someone would do that on purpose though, so it seems better to forbid it instead of silently ignoring what's probably a mistake by the user.

**Comment by casella** [comment]
der(array)*array is a scalar product according to [Section 10.6.4](https://specification.modelica.org/maint/3.5/arrays.html#matrix-and-vector-multiplication-of-numeric-arrays), Table 10.11 of the Modelica Specification, so there is no need to use sum() there.

**Comment by perost** [comment]
> der(one_dim_array)*another_one_dim_array is a scalar product according to [Section 10.6.4](https://specification.modelica.org/maint/3.5/arrays.html#matrix-and-vector-multiplication-of-numeric-arrays), Table 10.11 of the Modelica Specification, so there is no need to use `sum()` there.

Yes, that's exactly my point. We shouldn't allow it since it doesn't make sense to use `sum` like that, and we don't know if it's just an unnecessary `sum` call or if the argument is a scalar only by mistake.
