### ISSUE TITLE
OMEdit generates invalid displayUnit modifiers for arrays of parameters

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5395]

**Comment by casella** [comment]
Load the attached model in OMEdit, double-click on `m` and change the display unit to kg/m3. A displayUnit modifier without each is added to the modifications, making the model invalid.

[TestEachDisplayUnit.mo.txt](https://github.com/OpenModelica/OpenModelica/files/11490521/TestEachDisplayUnit.mo.txt)

**Comment by casella** [comment]
@adeas31 would you mind porting this to the maintenance/v1.22 branch, so we can have it in 1.22.1 as planned?

**Comment by casella** [comment]
I'm not reopening #5405, #5489, #5737, #7750 and #10226, since I understand the commits required are the same. I would just keep this ticket as a reminder that we still need to port 0281e54 to the maintenance/v1.22 branch.

**Comment by adeas31** [comment]
There is still an issue when trying to set `final` and `each` for replaceable. I will fix it first and then port the changes.

**Comment by adeas31** [comment]
Ported via PR #11571 and #11573.
