### ISSUE TITLE
OMEdit cannot generate 'each' modifiers for parameters of arrays of components

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5405]
https://trac.openmodelica.org/OpenModelica/ticket/5405

**Comment by casella** [comment]
@adeas31 it is now really time to fix this in the new instantiation-based interface, unless it has been fixed already.

Thanks!

**Comment by casella** [comment]
This also holds for setting the fixed attribute of state variable arrays.

**Comment by adeas31** [comment]
Yes, its already on my list.
