### ISSUE TITLE
Proper handling of library versions in OMEdit

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5427]

**Comment by casella** [comment]
Original ticket: https://trac.openmodelica.org/OpenModelica/ticket/5427

We'll have most of the required features implemented in version 1.19.0

**Comment by casella** [comment]
Version 1.19.0 handles libraries in a much better way than previous versions:

- the package manager is fully integrated in the GUI and helps installing and updating system libraries
- if a library is opened that is not compatible with already loaded ones, there are options to either cancel the operation or to reload that library from scratch with its dependencies
- upgrading existing libraries to newer versions of their dependencies that are not backwards compatible (using conversion scripts) is now supported through the GUI

@GallLeo, you are very welcome to try these features out in the 1.19.0-beta.1 release, should be out later this week.

-
