### ISSUE TITLE
Try to avoid using numbers in exponential form on vertical axes

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5447]

**Comment by casella** [comment]
Original ticket https://trac.openmodelica.org/OpenModelica/ticket/5447.

We forgot points 5. and 6., which were due for the DFD a long time ago.
- For angular speeds always add in the menu in the unit column, in addition to the standard “rad/s” also “rpm”
- For energies always add in the menu in the Display Unit column, in addition to standard “J”, also “Wh” (prefixes such as kWh, MWh, GWh will be obtained automatically)

@adeas31 can you manage in time for 1.19.0?
