### ISSUE TITLE
Usage of the Synchronous Library not possible

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5450]
In order to use the Synchronous-Library it is necessary to add the Command Line Option "+std=3.3".
Unfortunately there is no way (or not a documented way) to do this via the `mod=ModelicaSystem(...` command.
As a workaround the line:
```
self.requestApi("setCommandLineOptions", '"+std=3.3"')
```

in the file "_init_.py", function: "loadingModel" solves the problem.
It would be nice if there where an additional parameter in the loadingModel-function or a hint in the documentation how to do this.

**Comment by AnHeuermann** [comment]
Simulating examples from `Modelica_Synchronous` (with MSL 3.2.3) works fine in OMEdit. No need to add an additional `+std=3.3`.

Also Synchronous became part of the MSL 4.
