### ISSUE TITLE
Complex number issue when compiling PhotoVoltaics example

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5523]

**Comment by pierre-haessig** [comment]
Dear OM devs,
While searching for another issue, I came across this issue (see original on [Trac #5523](https://trac.openmodelica.org/OpenModelica/ticket/5523)) by @christiankral. Regarding the initial report "When trying to simulate the model `PhotoVoltaics.Examples.SimpleModuleMP3` an error occurs during compilation.", I've run this model in OM 1.18 beta2 and I didn't get a compilation error. I've no idea if output is correct, but the variable `module.power` stabilizes at −185W after 200 s.

**Comment by perost** [comment]
Thanks, our library testing confirms that the model is indeed working.

**Comment by pierre-haessig** [comment]
Also for the reference, the issue on Trac has a comment saying #4611 (Processing arrays of records fails) may be related or even duplicate. I have not looked in that one.

**Comment by mahge** [comment]
It was _fixed_ when we Switched to the new Front End.
https://libraries.openmodelica.org/branches/history/master/2020-12-14%2003:04:35..2020-12-14%2022:49:53.html

**Comment by christiankral** [comment]
> While searching for another issue, I came across this issue (see original on [Trac #5523](https://trac.openmodelica.org/OpenModelica/ticket/5523)) by @christiankral. Regarding the initial report "When trying to simulate the model `PhotoVoltaics.Examples.SimpleModuleMP3` an error occurs during compilation.", I've run this model in OM 1.18 beta2 and I didn't get a compilation error. I've no idea if output is correct, but the variable `module.power` stabilizes at −185W after 200 s.

I just tested `PhotoVoltaics.Examples.SimpleModuleMP3` with OM 1.18.0. The simulation result is correct, the steady state result of the electric power approx. 185W after 200s.

![image](https://user-images.githubusercontent.com/4184218/134464393-857842ea-bed0-47d0-ac54-928ce91f79b6.png)

**Comment by pierre-haessig** [comment]
Yes, exactly the curve shape I got.

**Comment by casella** [comment]
> Also for the reference, the issue on Trac has a comment saying #4611 (Processing arrays of records fails) may be related or even duplicate. I have not looked in that one.

That issue is still there, I just checked the test case a the beginning.
