### ISSUE TITLE
DXF shapes in animations are not displayed correctly

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5593]

**Comment by casella** [comment]
How it is currently shown:
![immagine](https://user-images.githubusercontent.com/4233148/217260222-e59e28f5-ac24-4c4e-8609-38b280602f27.png)
How it should be:
![immagine](https://user-images.githubusercontent.com/4233148/217260383-f6460992-c115-4f1c-b51f-649abc808094.png)

**Comment by casella** [comment]
@anotheruserofgithub do you think you can help fixing this?
