### ISSUE TITLE
Categorize open-source libraries in OpenModelica for different uses

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5726]

**Comment by casella** [comment]
Original track ticket: https://trac.openmodelica.org/OpenModelica/ticket/5726

**Comment by casella** [comment]
The categorization is now available in the OMPackageManager, see https://github.com/OpenModelica/OMPackageManager/blob/master/repos.json, with the following categories: fullSupport, partialSupport, experimental, noSupport, obsolete.

The categorization should be reviewed before releasing 1.19.0, based on the latest coverage test results and on the latest status of libraries.

**Comment by dietmarw** [comment]
Is there any documentation resource that specifies the meaning of the categorisation? 
For example if I look at a categorisation like:

```
"support": [
      ["prerelease", "noSupport"],
      [">=1.2.0", "experimental"],
      ["*", "obsolete"]
```
I'm a bit lost as to what matches obsolete here. Everything?

**Comment by casella** [comment]
> Is there any documentation resource that specifies the meaning of the categorisation?

We should definitely have one in a readme.md file, currently the documentation is in the scripts source code and in @sjoelund's head 😄 

I understand the items are applied sequentially, so obsolete matches whatever was not matched in the previous two items.

**Comment by casella** [comment]
> Is there any documentation resource that specifies the meaning of the categorisation? For example if I look at a categorisation like:

@dietmarw, I just updated the [readme.md](https://github.com/casella/OMPackageManager/blob/master/README.md) file with some information about that. Please have a look and comment if needed.

**Comment by dietmarw** [comment]
@casella This looks very good. However it would also be good to have the documentation of what "release identifiers" are allowed. The code example uses `prerelease`, `>=...`,`*`. Now what else is legal here? Would `>` be allowed and how about `<` and are there other terms than `prerelease` that can be used.  To make it really clear you should list the allowed release identifiers.

**Comment by sjoelund** [comment]
> @casella This looks very good. However it would also be good to have the documentation of what "release identifiers" are allowed. The code example uses `prerelease`, `>=...`,`*`. Now what else is legal here? Would `>` be allowed and how about `<` and are there other terms than `prerelease` that can be used? To make it really clear you should list the allowed release identifiers.

https://github.com/OpenModelica/OMPackageManager/blob/master/common.py#L16

`>` and `<` are not allowed.

Entries beginning with a `+` are allowed (to mark certain branches unsupported):
```
["+default.modelica.association", "noSupport"]
```

Other entries match verbatim.

**Comment by casella** [comment]
-[X] Updated [OMPackageManager README](https://github.com/OpenModelica/OMPackageManager/blob/master/README.md) with the latest comment by @sjoelund.
-[X] Update support tags to reflect the current status more accurately.
