### ISSUE TITLE
Need to manually insert "each" before fixed = false or true statement when initializing a vector

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5737]
https://trac.openmodelica.org/OpenModelica/ticket/5737

**Comment by casella** [comment]
@adeas31 now that we have released 1.22.0, can you please port this to maintenance/v1.22, so it gets into 1.22.1?

Thanks!

**Comment by casella** [comment]
Sorry, I forgot we already have #5395 for the cherry-picking.
