### ISSUE TITLE
Connections.isRoot statement outside equation results in instantiation failure with no error message

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#5763]

**Comment by annikakuhlmann** [comment]
Hello,

can anyone tell me if there has already been a solution to this? I currently have the same problem. Although the Modelica specification (acc. to 3.8.3) explicitly allows to use Connections.isRoot(A.R) as parameter expression, an error occurs in OM: "error: call to undeclared function 'isRoot'; ISO C99 and later do not support implicit function declarations".

Are there any plans to allow this in the future?
