### ISSUE TITLE
Docker cross-compile FMUs dialog in OMEdit

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6009]
Users can cross compile FMUs very easily if they have Docker installed. That is a cool feature but hidden very well.
Adding it to OMEdit and promoting it in the next realese notes would be great.
Basically you need to have Docker in your PATH and you are able to generate FMUs for every main system (except of course macOS for legal reasons), no matter what OS you are on.

Just set `platforms` to something like

```
  "arm-linux-gnueabihf docker run docker.openmodelica.org/armcross-omsimulator:v2.0",
  "x86_64-linux-gnu docker run docker.openmodelica.org/build-deps:v1.13",
  "i686-linux-gnu docker run docker.openmodelica.org/build-deps:v1.13-i386",
  "x86_64-w64-mingw32 docker run docker.openmodelica.org/msyscross-omsimulator:v2.0",
  "i686-w64-mingw32 docker run docker.openmodelica.org/msyscross-omsimulator:v2.0"
```

and call `buildModelFMU` with it.

We could add checkboxes, plus a static list of "docker run" labels for FMU export dialog in OMEdit.

--------------
Taken from https://trac.openmodelica.org/OpenModelica/ticket/6009

**Comment by AnHeuermann** [comment]
Should be done with #8168 in one go.

**Comment by AnHeuermann** [comment]
Also somewhat related ticket: #7458 
Would be bad to give users a "new" option in OMEdit only to see that is's not working on Windows.
