### ISSUE TITLE
Support for "visible" attribute missing in graphical annotation rendering of OMEdit

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6111]
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6111

**Comment by niklwors** [comment]
Is there a new status on this ticket yet?

**Comment by casella** [comment]
No. We need to reassign these issue to someone else than @adrpo, he simple does not have time for that. Maybe @perost once the Buldings issue with the NF have been all ironed out.

**Comment by casella** [comment]
@adrpo has a PR that solves this with the NF, so he should just dig it out
