### ISSUE TITLE
Extend overconstrained connector semantics to handle dynamic branches (prototype)

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6240]
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6240

**Comment by casella** [comment]
See full proposal [here](https://trac.openmodelica.org/OpenModelica/ticket/6240#comment:2). 

I re-attach the code of the example here:

[DynamicOverconstrainedConnectors2.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7927715/DynamicOverconstrainedConnectors2.mo.txt)

**Comment by casella** [comment]
A package with exemplary test cases and a general discussion is now available here: https://github.com/looms-polimi/DynamicOverconstrainedConnectors.

A prototype implementation has been successfully made in the @JKRT's OpenModelica.jl experimental compiler framework. A paper on the topic has been submitted to the 2022 Asian Modelica Conference.

**Comment by casella** [comment]
We can close this ticket since the prototyping activity was concluded successfully. Ticket #10274 was opened regarding the actual implementation in the new backend of OMC.
