### ISSUE TITLE
Modelica External C dependencies are not found on Windows

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#6242]
This is a placeholder created during migration to preserve original issue numbers.

----

Migrated-From: https://trac.openmodelica.org/OpenModelica/ticket/6242

**Comment by niklwors** [comment]
This problem is not yet solved

**Comment by casella** [comment]
@niklwors I re-read the original [ticket #6242](https://trac.openmodelica.org/OpenModelica/ticket/6242). I see two separate issues there.

**Comment by casella** [comment]
Issue 1: OMEdit fails to load a certain dll and other stuff which is required to run external C functions. I understand if everything is copied into the working directory of the model, everything works fine. The question is: where is all this stuff going to be found? Is it somewhere in the Resources folder? 

The external function interface provide annotations to specify that, see [Section 12.9.4](https://specification.modelica.org/maint/3.5/functions.html#annotations-for-external-libraries-and-include-files) of the language specification. Are you using that already? Please provide more information here, so we can try to close the issue.

**Comment by casella** [comment]
Issue 2: when dlls are not found, the simulation executable terminates with error message` Exited with code -1073741515`, which is not really understandable. We should at least print that number as unsigned int in hex code ( 0xC0000135 in this case) possibly adding a link to the [list of all error codes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55).

@niklwors would that be good for you?

**Comment by perost** [comment]
> Issue 2: when dlls are not found, the simulation executable terminates with error message` Exited with code -1073741515`, which is not really understandable. We should at least print that number as unsigned int in hex code ( 0xC0000135 in this case) possibly adding a link to the [list of all error codes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55).

This was fixed in #7316, so the error code should be printed using hexadecimal format on Windows now.

**Comment by casella** [comment]
> This was fixed in #7316, so the error code should be printed using hexadecimal format on Windows now.

Nice, thanks @perost for reporting!

**Comment by niklwors** [comment]
> 
> 
> Issue 2: when dlls are not found, the simulation executable terminates with error message` Exited with code -1073741515`, which is not really understandable. We should at least print that number as unsigned int in hex code ( 0xC0000135 in this case) possibly adding a link to the [list of all error codes](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55).
> 
> @niklwors would that be good for you?
yes, this would be fine.

**Comment by niklwors** [comment]
<3ed 
-k,mjnhgbvfc mknjhbgftdrsewaq^w345

> 
> 
> Issue 1: OMEdit fails to load a certain dll and other stuff which is required to run external C functions. I understand if everything is copied into the working directory of the model, everything works fine. The question is: where is all this stuff going to be found? Is it somewhere in the Resources folder?
> 
> The external function interface provide annotations to specify that, see [Section 12.9.4](https://specification.modelica.org/maint/3.5/functions.html#annotations-for-external-libraries-and-include-files) of the language specification. @niklwors, are you using that already? A comment by @adrpo in the original ticket says: "We need to add the LIBS directories to the PATH variable when we run the executables so that DLLs in the library resources can be found.". @adrpo, is the information already available in the annotation, are are we just not using that right?

Yes we are using the annotation from Section 12.9.4 already

**Comment by casella** [comment]
OK.

@adeas31 could you please implement @adrpo's suggestion ""We need to add the LIBS directories to the PATH variable when we run the executables so that DLLs in the library resources can be found."?

**Comment by casella** [comment]
@adrpo has a PR in the works, then he will hand it over to @adeas31.

**Comment by casella** [comment]
@adrpo, any chance to get this thing through? Thanks!

**Comment by casella** [comment]
@mahge, what about you?

**Comment by mahge** [comment]
I can not verify it but this might be fixed by #8506. However omc should now look in the correct places when looking for libraries for loading on Windows after 4717759fc5a28a0b60f9d7b1519f262c7b70f3ad. 

This seems to me a mix of linking and loading so I am not sure if there are more issues. @niklwors please check again and update the ticket accordingly.

**Comment by mahge** [comment]
#8552 (fixes for the APIs) has been followed up by #8572 which should fix the problem for OMEdit as well. If the issue was not resolved yet it should probably be now.
