### ISSUE TITLE
Incompatibility with gcc > 9.x

### ISSUE THREAD

**Issue by sanguinariojoe** [OpenModelica/OpenModelica#6747]
The issue was initially reported here:

https://openmodelica.org/forum/default-topic/3001-installing-openmodelica-on-linux

The suggested solution was upgrading MUMPS. However, for the time being using appropriate flags can do the job. To this end you can merge [this](https://github.com/OpenModelica/OpenModelica/pull/6746), so the following command compiles just fine:

`./configure FCFLAGS="-fallow-argument-mismatch"`

**Comment by perost** [comment]
This was fixed by the mentioned #6747 (thanks!) to respect FCFLAGS and #6807 that added `FCFLAGS="-fallow-argument-mismatch"` to `configure.ac`.
