### ISSUE TITLE
Invoking listed functions only works in tuples

### ISSUE THREAD

**Issue by kabdelhak** [OpenModelica/OpenModelica#6873]
I am currently working on a smart way to order my modules in the new backend and stumbled upon this bug:

if i have a partial function such as
```
partial function wrapper
  input output BackendDAE bdae;
end wrapper;
```
And create multiple modules with this wrapper which i want to loop over the `BackendDAE` i can only do so in tuples. 

Example that does **not** work:
  ```
function applyModules1
    input output BackendDAE bdae;
    input list<Module.wrapper> moduleFuncs;
  algorithm
    for moduleFunc in moduleFuncs loop
      bdae := moduleFunc(bdae);
    end for;
  end applyModules1;
```

Example that does work:
  ```
function applyModules2
    input output BackendDAE bdae;
    input list<tuple<Module.wrapper, String>> moduleFuncs;
  protected
    Module.wrapper funcMod;
    String funcName;
  algorithm
    for moduleFunc in moduleFuncs loop
      (funcMod, funcName) := moduleFunc;
      bdae := funcMod(bdae);
    end for;
  end applyModules2;
```

The Error for the failing one:
```
/home/kab/workspace/OpenModelica/OMCompiler/Compiler/NBackEnd/NBackendDAE.mo:241:56: error: passing 'modelica_metatype' (aka 'void *') to parameter of incompatible type 'base_array_t'
      (aka 'struct base_array_s')
    for(tmp1 = 1; tmp1 <= size_of_dimension_base_array(_moduleFuncs, 1); ++tmp1)
                                                       ^~~~~~~~~~~~
/home/kab/workspace/OpenModelica/build/include/omc/c/util/base_array.h:73:71: note: passing argument to parameter 'a' here
static OMC_INLINE int size_of_dimension_base_array(const base_array_t a, int i)
                                                                      ^
/home/kab/workspace/OpenModelica/OMCompiler/Compiler/NBackEnd/NBackendDAE.mo:241:23: error: implicit declaration of function 'fnptr_array_element_addr1' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
      _moduleFunc = *(fnptr_array_element_addr1(&_moduleFuncs, 1, tmp1));
                      ^
/home/kab/workspace/OpenModelica/OMCompiler/Compiler/NBackEnd/NBackendDAE.mo:241:21: error: indirection requires pointer operand ('int' invalid)
      _moduleFunc = *(fnptr_array_element_addr1(&_moduleFuncs, 1, tmp1));
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
```

I suppose this never was a problem due to the fact that you always also want to pass the function name as a string for debugging. If this is easy to fix we should do it because i probably would like to use that in the future for some other smaller modules (also it could be confusing for new developers if this does not work and the tuple one works). 

Does not have high priority to me because i will implement it for the main modules with the `String` extra argument.

**Comment by kabdelhak** [comment]
@adrpo @sjoelund Do you have any intel on this for me? :)

**Comment by sjoelund** [comment]
I guess the automatically generated variable for the iterator has some problem in it. You could perhaps assign it to a declared variable and make it work?

**Comment by perost** [comment]
Not just the iterator, the code generated for the for loop seems to be for a Modelica array and not a list. I guess we've never used lists with function pointers before.

**Comment by mahge** [comment]
#6887 seems to have fixed it. Check it and if all good I will merge it.

**Comment by kabdelhak** [comment]
Works as intended, thanks @mahge for the fix! :+1:
