### ISSUE TITLE
Internal error FUnitCheck.checkUnits: unit check module failed

### ISSUE THREAD

**Issue by CSchoel** [OpenModelica/OpenModelica#6882]
With OpenModelica 1.16.0 I get an internal error during the unit check of a large electrophysiological model (which can be found here: https://github.com/CSchoel/inamo).

```verbatim
[/var/lib/jenkins3/ws/LINUX_BUILDS/tmp.build/openmodelica-1.16.0/OMCompiler/Compiler/FrontEnd/FUnitCheck.mo:88:5-88:91:writable] Error: Internal error FUnitCheck.checkUnits: unit check module failed
```

This occurs for many but not all of the different examples/unit tests in the repository (i.e. the models in `InaMo/Examples`):

```verbatim
Test Summary:                       | Pass  Error  Total
Simulate examples                   |  143     32    175
  SodiumChannelSteady               |    5      2      7
  SodiumChannelIV                   |    7             7
  InwardRectifierLin                |    5      2      7
  GHKFlux                           |    5      2      7
  LTypeCalciumSteady                |    5      2      7
  LTypeCalciumIV                    |    7             7
  LTypeCalciumIVN                   |    7             7
  LTypeCalciumStep                  |    7             7
  TransientOutwardSteady            |    5      2      7
  TransientOutwardIV                |    5      2      7
  RapidDelayedRectifierSteady       |    5      2      7
  RapidDelayedRectifierIV           |    5      2      7
  HyperpolarizationActivatedSteady  |    5      2      7
  HyperpolarizationActivatedIV      |    7             7
  SustainedInwardSteady             |    5      2      7
  SustainedInwardIV                 |    7             7
  SustainedInwardIVKurata           |    7             7
  SodiumPotassiumPumpLin            |    7             7
  SodiumCalciumExchangerRampInada   |    5      2      7
  SodiumCalciumExchangerLinMatsuoka |    5      2      7
  SodiumCalciumExchangerLinKurata   |    5      2      7
  AllCells                          |    5      2      7
  AllCellsC                         |    5      2      7
  FullCellSpon                      |    5      2      7
  CaHandlingApprox                  |    7             7
```

With OpenModelica 1.14.2 the unit checking worked fine for these models.

This issue may be related to #6881, since this model does use higher order functions. However, the smallest example that shows the error is `GHKFlux`, which only tests that the correct value was used to fix the avoidable discontinuity in the `ghkFlux` function, which is a simple Modelica function without any `redeclare` involved. I attached the result of saving this model with the "Save Total" feature: [GHKFluxTotal.zip](https://github.com/OpenModelica/OpenModelica/files/5476287/GHKFluxTotal.zip).

Steps to reproduce: Load `GHKFluxTotal.mo` with `--unitChecking` enabled.

OpenModelica version: 1.16.0 (also tested with `OMCompiler v1.17.0-dev.94+g4da66238ab`)

**Comment by phannebohm** [comment]
Thanks for the example model. I will need to examine it tmrw.

The module for unit checking has been refactored recently, so some bug may have slipped in. In fact there were several modules doing similar things. The flag `--unitChecking` now activates a front-end module, which it didn't do before. What flag did you use on version 1.14.2?
You may want to try the new front-end (`-d=newInst`).

In any case, the error message isn't very helpful, so this needs to be dealt with.
Thanks for pointing this out!

**Comment by CSchoel** [comment]
Thanks for the quick reply!

On 1.14.2 I used `--preOptModules+=unitChecking`. I was not aware that `--unitChecking` also existed back then.

Interestingly, `-d=newInst` fixes the issue for `GHKFlux` and `InwardRectifierLin` (both tests run without errors), but gives me a lot of other errors and warnings, many of them related to name resolution and at least some of them are definitely my fault. I already wondered why OMEdit kept complaining about some issues that were not reported when I used the ZMQ interface. I guess now I have my answer and I have some bugfixing to do. :sweat_smile: Thanks for the hint!

**Comment by phannebohm** [comment]
> On 1.14.2 I used `--preOptModules+=unitChecking`. I was not aware that `--unitChecking` also existed back then.

Yea, both of these were pretty old, the front end modules are newer with the version in the new frontend being newest.
I'm not sure if unit checking in the old front end will be fixed at this point.

> I guess now I have my answer and I have some bugfixing to do.

Please report any remaining bugs :slightly_smiling_face:

**Comment by CSchoel** [comment]
I went through all the errors from the new front-end and most if not all of them were indeed errors in my code, including some unit consistency errors that were not picked up by the old version. I also found the error messages quite helpful. Nice work on the improvements!

I have only one issue remaining, but this may very well be just due to a lack of understanding on my end: I need to access some functions, which are defined in a redeclare statement. Example:

```modelica
model ReplaceableFunction
  function f
    input Real x;
    input Real k = 1;
    output Real y;
  algorithm 
    y := x + k;
  end f;
  model OuterModel
    model InternalModel
      Real a(start=0, fixed=true);
      replaceable function func = f;
    equation
      der(a) = func(a);
    end InternalModel;
    InternalModel im(redeclare function func = f(k=0));
  end OuterModel;
  OuterModel om;
  Real c(start=0, fixed=true);
  Real b = om.im.func(c);
equation
  der(c) = 1;
end ReplaceableFunction;
```

Here, I get the following error:

```
Illegal access of class 'func' via a component when looking for 'om.im.func'.
```

How can I access these internal functions in a legal way and why does this work, if there is only one hierarchical level between the redeclared function and the component (i.e. when `OuterModel` is not there, and I instead access `im.func`)?

However, this is not related to this issue anymore and if you do not have a quick answer, I can also ask the question on the forums or open a separate issue (whichever you think is more appropriate).

**Comment by perost** [comment]
That seems like a bug in the compiler, functions are supposed to be possible to lookup inside components. I'll check why that's happening.

**Comment by CSchoel** [comment]
Wow, you people are lightning quick. :zap: :laughing:  Thanks for looking into this. :smile:

**Comment by perost** [comment]
I was wrong, it's actually not allowed. See [5.3.2 in the Modelica specification](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup), point 3. In a name used as a function call where the first identifier refers to a component the rest of the identifiers must refer to classes. So `om.im.func` is not allowed but `im.func` is, though I'm not sure what the rationale behind that is.

I'm also not sure how to deal with that issue. At first I thought you could add a `function func = im.func` inside `OuterModel`, but that's also not allowed since you're only allowed to look up functions inside component when they're used as a function call. I guess you could say:
```Modelica
    InternalModel im(redeclare function func = func);
    function func = f(k = 0);
```
in `OuterModel` and then just use `om.func`.

**Comment by CSchoel** [comment]
Ah, damn. Then I will have to find a workaround. Nevertheless, thank you very much for looking up the specification (I probably should have done this myself :sweat_smile: ).

I think your proposed solution may be the way to go. I will have to think a little bit about it to make sure that the solution does not add too much boilerplate code, but at least I know what the issue is and what can be done about it. :+1: 

In any way, there is no error in the OMC left here, so I will close the issue.
