### ISSUE TITLE
omc not launching in Ubuntu - missing dependency libModelicaExternalC.so.0

### ISSUE THREAD

**Issue by rodrigodcastro** [OpenModelica/OpenModelica#6980]
I can't start OMShell or omc or OMEdit, always get:

error while loading shared libraries: libModelicaExternalC.so.0: cannot open shared object file: No such file or directory

Just installed the latest 1.16.1 version following the steps in
https://www.openmodelica.org/download/download-linux

System:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

**Comment by sjoelund** [comment]
We changed omc to use a statically compiled version of ModelicaExternalC some time ago... Are you sure everything was updated? Perhaps `apt dist-upgrade` or `apt install omc` or `apt install libomc` shows some package that was not upgraded. If all else fails, `apt remove libomc` and reinstall to make sure all packages are updated.

**Comment by rodrigodcastro** [comment]
This **alone** solved the problem: apt dist-upgrade
Thanks for your quick assistance!
