### ISSUE TITLE
FMU export from OMEdit fails with external "C" static library dependencies if additional linker flags are needed

### ISSUE THREAD

**Issue by pstelzig** [OpenModelica/OpenModelica#7006]
### Description
OMEdit fails on exporting a FMU for a Modelica model with a static library dependency `<staticLibDep>.a` if `<staticLibDep>.a` requires other libraries to be linked. This is becaues there is no option to set linker flags for the FMU export like there is for building a model in "Simulation Setup->C/C++ Copmiler Flags (Optional)"

### Steps to reproduce
**Reproducing the problem** Assume to work in Ubuntu 20.04. Create a folder `FmuWithStaticLibDep` and place two files in there: `package.mo` and `externalfunc.c`

Content of `package.mo`
```modelica
package FmuWithStaticLibDep
  extends Modelica.Icons.Package;

  model ModelWithExternalLib
    extends Modelica.Blocks.Interfaces.SISO;

    function Multiplier
      input Real x;
      input Real m;
      output Real y;
    
      external "C" y = multiply(x, m) annotation(
        Library = "externalfunc");
    end Multiplier;

    parameter Real m = 2.0;
  equation
    y = Multiplier(u, m);
  end ModelWithExternalLib;
end FmuWithStaticLibDep;
```

Content of `externalfunc.c`
```cpp
#include <iostream>

extern "C" double multiply(double x, double m)
{
    std::cout << "multiply called with arguments x=" << x << " and m=" << m << std::endl;
    
    return m*x;
}
```
This is an `extern "C"` function that internally uses elements of the C++ Standard Library, thus will require linking `libstdc++` into the resulting simulation executable.  

Then run from this folder `FmuWithStaticLibDep`
```
$ mkdir -p ./Resources/Library
$ g++ -c -fPIC -o ./Resources/Library/externalfunc.o externalfunc.c
$ ar rcs ./Resources/Library/libexternalfunc.a ./Resources/Library/externalfunc.o
```

Open OMEdit and do "File->Load Library" and select `FmuWithStaticLibDep/package.mo`. Open `FmuWithStaticLibDep.ModelWithExternalLib` from the library tree, then click "Simulation Setup", check both "Build Only" and "Simulate" and then click "Ok". OMEdit will fail to compile. 

Reopen "Simulation Setup" and type `-lstdc++` in the textbox "C/C++ Compiler Options (Optional)". Click Ok. OMEdit will compile successfully and run successfully on simulation printing "multiply called with arguments x=0 and m=2" during simulation. 

Then with `FmuWithStaticLibDep.ModelWithExternalLib` open click "File->Export->FMU". OMEdit will fail with the message (and other errors)
```
/usr/bin/ld: externalfunc.c:(.text+0xc2): undefined reference to `std::ios_base::Init::~Init()'
```

**Manual solution** Go to the partially created FMU in the `<OMEdit working directory>` and open `FmuWithStaticLibDep.ModelWithExternalLib/FmuWithStaticLibDep_ModelWithExternalLib.fmutmp/sources/Makefile` in a text editor and change

```
LDFLAGS=-L'/usr/bin/../lib/x86_64-linux-gnu/omc' -Wl,-rpath,'/usr/bin/../lib/x86_64-linux-gnu/omc'   -lSimulationRuntimeFMI  -Wl,--no-as-needed -Wl,--disable-new-dtags -llapack -lblas -lm -lm -lpthread -rdynamic -Wl,--no-undefined 
```

to 

```
LDFLAGS=-L'/usr/bin/../lib/x86_64-linux-gnu/omc' -Wl,-rpath,'/usr/bin/../lib/x86_64-linux-gnu/omc'   -lSimulationRuntimeFMI  -Wl,--no-as-needed -Wl,--disable-new-dtags -llapack -lblas -lm -lm -lpthread -rdynamic -Wl,--no-undefined -lstdc++
```

i.e. add `-lstdc++` to the end. 

Save and run
```
$ make
```
from this folder. This will compile the FMU's shared library and build the `FmuWithStaticLibDep.ModelWithExternalLib/FmuWithStaticLibDep.ModelWithExternalLib.fmu`. 

Close OMEdit and repoen OMEdit. Import the just created `FmuWithStaticLibDep.ModelWithExternalLib/FmuWithStaticLibDep.ModelWithExternalLib.fmu`. 

Open `FmuWithStaticLibDep_ModelWithExternalLib_me_FMU` and click "Simulation Setup", check "Build Only" and "Simulate" and then click "Ok". OMEdit will compile without problems and run successfully on simulation printing "multiply called with arguments x=0 and m=2" during simulation. 

### Expected behavior
OMEdit should give the user the option to provide additional linker flags for the export of an individual FMU, e.g. a textbox on export just like the textbox "C/C++ Compiler Options (Optional)" in the "Simulation Setup" window . 

### Version and OS
 - OpenModelica Version `1.16.1`
 - OS: Ubuntu 20.04 64bit

**Comment by sjoelund** [comment]
You are required to put all of the libraries in the annotation, like the standard library does:
https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Blocks/Tables.mo#L973

**Comment by pstelzig** [comment]
I see! Thanks for the hint! Indeed it *nearly* works. May I ask another hint: If I do this
```modelica
model ModelWithExternalLib
  extends Modelica.Blocks.Interfaces.SISO;

  function Multiplier
    input Real x;
    input Real m;
    output Real y;
  
    external "C" y = multiply(x, m) annotation(
      Library = {"externalfunc", "stdc++"});
  end Multiplier;

  parameter Real m = 2.0;
equation
  y = Multiplier(u, m);
end ModelWithExternalLib;
```
then OMEdit (or omc) will look indeed for `libstdc++.so` and `libstdc++.a` in various standard paths. 

Problem: `libstc++.so` carries a version suffix, namely `libstdc++.so.6` and thus cannot be found in these standard paths
```
  /usr/bin/../lib/x86_64-linux-gnu/omc/libstdc++.a
  /usr/bin/../lib/x86_64-linux-gnu/omc/libstdc++.so
  /usr/lib/x86_64-linux-gnu/libstdc++.a
  /usr/lib/x86_64-linux-gnu/libstdc++.so
  /lib/x86_64-linux-gnu/libstdc++.a
  /lib/x86_64-linux-gnu/libstdc++.so
  /usr/lib//libstdc++.a
  /usr/lib//libstdc++.so
  /lib//libstdc++.a
  /lib//libstdc++.so
  /usr/bin/../lib/x86_64-linux-gnu/omc/libstdc++.a
  /usr/bin/../lib/x86_64-linux-gnu/omc/libstdc++.so
  /usr/bin/../lib//libstdc++.a
  /usr/bin/../lib//libstdc++.so
```

How do I do that? If I give it as a linker flag, gcc knows where to find libstdc++.so (namely in `/usr/lib/gcc/x86_64-linux-gnu/9` where there is a symbolic link to `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`)

**Comment by pstelzig** [comment]
Ah, wait. It does work! You're right. 

These outputs on omc not being able to find `libstdc++` in the standard paths are warnings, but nevertheless: Apparently OMEdit compiles the above model `ModelWithExternalLib` and also exports to FMU from within OMEdit works without error. I can reimport the FMU and simulate. 

Thanks @sjoelund

So the apparently working construction is
```modelica
model ModelWithExternalLib
  extends Modelica.Blocks.Interfaces.SISO;

  function Multiplier
    input Real x;
    input Real m;
    output Real y;
  
    external "C" y = multiply(x, m) annotation(
      Library = {"externalfunc", "stdc++"});
  end Multiplier;

  parameter Real m = 2.0;
equation
  y = Multiplier(u, m);
end ModelWithExternalLib;
```
as you suggested. 

I'll try it out later with more care, but it looks promising now.

**Comment by pstelzig** [comment]
@sjoelund I can confirm that what I reported as a bug no longer persists if I change the Modelica model as you suggested (see the working Modelica model above in my last comment). 

Thanks again for the quick and great answer. It helped me a lot. 

I will close the ticket now.
