### ISSUE TITLE
Icon extraction : color issue

### ISSUE THREAD

**Issue by ThermoSysPro** [OpenModelica/OpenModelica#7026]
### Description
I use *generate_icons.py* to generate the icons of ThermoSysPro library. Some extracted icons do not have the same colors as original icons.

### Steps to reproduce
Run *generate_icons.py* (OpenModelica/OMCompiler/Examples/generate_icons.py) on ThermoSysPro library.

### Screenshots
In attachment, two components for which automated extraction of icons is not perfect (left : extracted icons ; right : original icons).
![color_issue](https://user-images.githubusercontent.com/74178172/101320900-c94bb880-3864-11eb-827d-f2032f2179f1.png)

**Comment by adeas31** [comment]
I will take a look at it as soon as possible.

**Comment by adeas31** [comment]
Here is how the new icons look like,

![image](https://user-images.githubusercontent.com/4007231/106466001-0dd98600-649b-11eb-94c9-fc3628cd0807.png)
![image](https://user-images.githubusercontent.com/4007231/106466134-3c576100-649b-11eb-871b-50a2ac5356da.png)

**Comment by ThermoSysPro** [comment]
Thanks a lot for this work !






Bien cordialement,



Claire-Eleuthèriane Gerrer
Ingénieur d'études et de recherche






18-20, boulevard de Reuilly – 75012 Paris

Tél : 07 70 49 75 74

www.phimeca.com  | LinkedIn







De : Adeel Asghar <notifications@github.com>
Envoyé : lundi 1 février 2021 14:39:48
À : OpenModelica/OpenModelica
Cc : GRP-PHIMECA-THERMOSYSPRO; Author
Objet : Re: [OpenModelica/OpenModelica] Icon extraction : color issue (#7026)
 



Here is how the new icons look like,


—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenModelica/OpenModelica/issues/7026#issuecomment-770863698",
"url": "https://github.com/OpenModelica/OpenModelica/issues/7026#issuecomment-770863698",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
