### ISSUE TITLE
Open the view of the root system instead of the model for new SSP models 

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OpenModelica#7103]
### Description
This is not a bug but an enhancement. It would be nice to open the root system automatically whenever a new SSP model is created. This is what one has to do anyways in order to start modelling.

![image](https://user-images.githubusercontent.com/8457302/105489165-1f5caa00-5cb3-11eb-937c-806b4166dcd8.png)

### Version and OS
- OMCompiler v1.17.0-dev.354+g9220249be4
- OMSimulator v2.0.0.post281-g1ce5796-linux
- OS: WSL - Ubuntu 20.04

**Comment by adeas31** [comment]
Sounds like a simple and good enhancement. Would it make sense to open both model and root system? Of course making root system the active tab.

**Comment by adeas31** [comment]
@AnHeuermann what do you think?
