### ISSUE TITLE
Renaming of components, i.e., submodels

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OpenModelica#7110]
### Description
OMEdit doesn't allow renaming submodels.

### Screenshots
![image](https://user-images.githubusercontent.com/8457302/105728559-9781d480-5f2c-11eb-83a1-206a1e68e2f3.png)

### Version and OS
- Connected to OMCompiler v1.17.0-dev.359+ge7fca47128
- Connected to OMSimulator v2.0.0.post285-g7de662d-linux
 - WSL2, 64 bit

**Comment by adeas31** [comment]
While trying to fix this. I got the message `[oms_rename] Only implemented for model identifiers`.

**Comment by lochel** [comment]
I didn't notice that even renaming the model itself was not possible. Good that it will be fixed by the same PR 👍
