### ISSUE TITLE
Final Complex parameters not updating after compilation

### ISSUE THREAD

**Issue by tinrabuzin** [OpenModelica/OpenModelica#7156]
### Description
When changing the real and imaginary variables after compilation, the complex number does not change.

### Steps to reproduce
If one compiles the example model below, and after compilation tries to change `a` or  `b`, this change is not reflected in `cplx1`. If I am not mistaken, `cplx1` should be updated accordingly. At least that is what happens with `Real` parameters.

```modelica
model example_complex
parameter Real a=1;
parameter Real b=1;

final parameter Complex cplx1 = Complex(a,b);
equation

end example_complex;
```

I am running  OpenModelica v1.16.2.

**Comment by perost** [comment]
My fix is causing some minor changes in some of our test cases. It's probably fine, but I will do some more testing to make sure before merging the PR.

**Comment by tinrabuzin** [comment]
I found another related problem for the following model

```
model test
parameter Real phi = Modelica.Constants.pi/4;
final parameter Complex x = Complex(cos(phi),sin(phi))*1;
end test;
```

If `*1` is removed from the binding expression, the change in `phi` is reflected. With `*1` included, `x` is not updated.
