### ISSUE TITLE
Parsing error of simulation output

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OpenModelica#7245]
### Description
Simulating the example `PNlib.Examples.ConTest.Conflict` with `LOG_NLS` in OMEdit results in a parsing error of the simulation output:

> Fatal error on line 610, column 103: unexpected character

I am not sure if it is a problem in the parser or the simulation executable itself.

![image](https://user-images.githubusercontent.com/8457302/109480235-9556ec80-7a7b-11eb-9ea0-0ba97876607d.png)

**Comment by adeas31** [comment]
@lochel this should be fixed. If it doesn't work feel free to reopen it.

**Comment by lochel** [comment]
@adeas31 Is it in the OpenModelica master? I could only find it in your fork.

**Comment by lochel** [comment]
Ahh, I guess it is part of #7257

**Comment by adeas31** [comment]
Yes.

**Comment by lochel** [comment]
Works fine, thanks!
