### ISSUE TITLE
Hide simulation progress bar after simulation

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OpenModelica#7252]
### Description
The new simulation output tabs are pretty nice. To use the available screen space a little better, I propose to hide the simulation progress bar as soon as the simulation succeeded. It basically doesn't provide any information in that situation and the cancel button is deactivated anyways.

### Screenshots
![image](https://user-images.githubusercontent.com/8457302/109682810-0cc17480-7b7f-11eb-8eb2-6411b542a514.png)

**Comment by adeas31** [comment]
I am not sure if this is a good idea. I mean the gain is not too much if we remove the progress bar. On the other hand it will be confusing for the users.

**Comment by lochel** [comment]
I knew you would say this 😆 I do not think that people would be confused. 
And look at the screenshot, the gain is actually pretty significant: The simulation output would expand by almost 50%.
