### ISSUE TITLE
Error when trying to build OpenModelica from source on Raspberry PI

### ISSUE THREAD

**Issue by sayantan-m** [OpenModelica/OpenModelica#7259]
Hello,

I tried to build OpenModelica with cpp runtime from source on a Raspberry PI with OS being Debian Buster. I followed the steps as mentioned here
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md, under Debian/Ubuntu Compile Cheat Sheet. I got the following errors.
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int SetCommandLineOptions(data*, const char*)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:123:14: error: ‘omc_OpenModelicaScriptingAPI_setCommandLineOptions’ was not declared in this scope
     result = omc_OpenModelicaScriptingAPI_setCommandLineOptions(threadData, mmc_mk_scon(expression));
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int GetOMCVersion(OMCData*, char**)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:139:17: error: ‘omc_OpenModelicaScriptingAPI_getVersion’ was not declared in this scope
     result_mm = omc_OpenModelicaScriptingAPI_getVersion(threadData, mmc_mk_scon(name.c_str()));
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int LoadModel(OMCData*, const char*)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:164:16: error: ‘omc_OpenModelicaScriptingAPI_loadModel’ was not declared in this scope
       result = omc_OpenModelicaScriptingAPI_loadModel(threadData, mmc_mk_scon(className), priorityVersion_lst, notify, mmc_mk_scon(languageStandard.c_str()), requireExactVersion);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int LoadFile(data*, const char*)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:183:16: error: ‘omc_OpenModelicaScriptingAPI_loadFile’ was not declared in this scope
       result = omc_OpenModelicaScriptingAPI_loadFile(threadData, mmc_mk_scon(fileName), mmc_mk_scon(encoding.c_str()), uses, notify, requireExactVersion);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int GetError(data*, char**)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:199:17: error: ‘omc_OpenModelicaScriptingAPI_getErrorString’ was not declared in this scope
     result_mm = omc_OpenModelicaScriptingAPI_getErrorString(threadData, warningsAsErrors);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp: In function ‘int SetWorkingDirectory(data*, const char*, char**)’:
/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/omcWrapper/omcCAPI/src/OMC.cpp:211:17: error: ‘omc_OpenModelicaScriptingAPI_cd’ was not declared in this scope
     reply_str = omc_OpenModelicaScriptingAPI_cd(threadData, mmc_mk_scon(directory));
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[6]: *** [omcCAPI/CMakeFiles/OMCDLL.dir/build.make:66: omcCAPI/CMakeFiles/OMCDLL.dir/src/OMC.cpp.o] Error 1
make[6]: Leaving directory '/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/Build_CAPI'
make[5]: *** [CMakeFiles/Makefile2:94: omcCAPI/CMakeFiles/OMCDLL.dir/all] Error 2
make[5]: Leaving directory '/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/Build_CAPI'
make[4]: *** [Makefile:133: all] Error 2
make[4]: Leaving directory '/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp/Build_CAPI'
make[3]: *** [Makefile:49: omcCAPIinstall] Error 2
make[3]: Leaving directory '/home/pi/OpenModelica/OMCompiler/SimulationRuntime/OMSICpp'
make[2]: *** [Makefile.omsi.common:86: OMSICPPinstall] Error 2
make[2]: Leaving directory '/home/pi/OpenModelica/OMCompiler'
make[1]: *** [Makefile.common:231: omc-and-runtimeCPPinstall] Error 2
make[1]: Leaving directory '/home/pi/OpenModelica/OMCompiler'
make: *** [Makefile:12: omc.skip] Error 2

On further investigation, I noticed that the header file, OpenModelicaScriptAPI.h present in OpenModelica/build/include/omc/scripting-API, where the functions whose definitions are missing, such as omc_OpenModelicaScriptingAPI_setCommandLineOptions, is empty on my system.

It will be of great help to me if someone may please suggest where the build may have gone wrong to end up with the aforementioned errors.

Thank you.

**Comment by sjoelund** [comment]
I think these things only happen if you abort a build halfway through and end up with a broken/older omc version. Can the omc you ended up with be used to simulate models? If it cannot, remove the build/ directory and run make again.

**Comment by sayantan-m** [comment]
Thank you very much for your prompt response. I cleaned the build directory and ran make again. This time, OpenModelica with CPP runtime was built without any problems.
