### ISSUE TITLE
Missing config.guess and config.sub

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OpenModelica#7320]
### Description
`config.guess` and `config.sub` are missing/not created for the install procedure documented on [README.Linux.md](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/README.Linux.md).

### Steps to Reproduce

Doing a fresh `git clone` then `autoconf` and `./configure` leads to an error:
```
$ MY_FORK=hkiel ; git clone https://openmodelica.org/git-readonly/OpenModelica.git --recursive && (cd OpenModelica && git remote set-url --push origin git@github.com:$MY_FORK/OpenModelica.git && git submodule foreach --recursive 'git remote set-url --push origin `git config --get remote.origin.url | sed s,^.*/,git@github.com:'$MY_FORK'/,`')$ cd OpenModelica
$ autoconf
configure.ac:95: warning: AC_OUTPUT should be used without arguments.
configure.ac:95: You should run autoupdate.
$ ./configure 
configure: error: cannot find required auxiliary files: config.guess config.sub
```

You can create them by hand by running `autoreconf --install`

### Expected Behavior

All files should be automatically created, or the installation procedure must be updated.

**Comment by sjoelund** [comment]
For me (autoconf 2.69), autoconf generates a configure script that creates config.guess and config.sub when it is run

**Comment by hkiel** [comment]
I'm using `autoconf (GNU Autoconf) 2.71` from macports. I never encountered this problem before. Looks like 2.71 just came in recently.
I reactivated the old 2.69 version of autoconf and now the files are generated again.
I guess I can close this ticket.

**Comment by sjoelund** [comment]
2.71 might be the default soon, so I think it's good if we can support both.

https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html suggests that each distribution should contain these files (but it's the gettext manual; not autoconf). Perhaps we could include the files in git to make things easier or we could simply fetch the config.guess/sub when generating the tarballs to get the latest ones in there.
