### ISSUE TITLE
Optimica

### ISSUE THREAD

**Issue by valfaro** [OpenModelica/OpenModelica#7356]
OpenModelica v1.17.0

Optimica does not recognise  the "constraint" section of an optimizacion problem

the problem has 1 constraint but optimize command output indicates "number of nonlinear constraints: 0"

[optimization_problem.zip](https://github.com/OpenModelica/OpenModelica/files/6260759/optimization_problem.zip)

This optimization problem works fine with OM v1.16.5

####
Optimica compiler does not work with OM v1.17.0

See optimization example results in OM v1.16.5 User Manual section 12.3 (BatchReactor) and the corresponding in same section but in OM v1.17.0 Manual. Optimization results are different.  

######
Van der Pol Optimal Control works in OM v1.16.5 but not in OM v1.17.0(see annexed files)
[VanDerPollOptimalControl.zip](https://github.com/OpenModelica/OpenModelica/files/6387401/VanDerPollOptimalControl.zip)

**Comment by valfaro** [comment]
Optimization still not working (OpenModelica v18..0)

**Comment by sjoelund** [comment]
I am guessing it might work if you disable the new front-end (which doesn't support most of the old research prototypes).
