### ISSUE TITLE
OMEdit re-simulation

### ISSUE THREAD

**Issue by valfaro** [OpenModelica/OpenModelica#7360]
### Description

Model re-simulation (change a parameter value) does not work properly

### Steps to Reproduce

Change a parameter value in variables browser and re-simulate (using a different output file name, in re-simulate set-up)

### Expected Behavior

New (different) variable plot.  The display variable plot is always the same (regarding the parameter value)

### Version and OS

Windows 10, 64 bit / OpenModelica v1.17.0

Re-simulation works fine with OM v1.16.5

**Comment by adeas31** [comment]
This works as expected.

The same variable plot will not be updated to the new value since you set a new output file. Plot the variable from the new result file and you will see the updated value.

**Comment by adeas31** [comment]
See #7402
