### ISSUE TITLE
Simple SSP does not work anymore

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7379]
### Description

The attached very simple ssp works with OM 1.17 beta3, does not with 1.18-dev 218.

[Test.zip](https://github.com/OpenModelica/OpenModelica/files/6318460/Test.zip)

### Steps to Reproduce

Load Test.ssp and try to run it. The following message is displayed:

python F:/AllOMs/OM1.18.0-dev-218-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/Massimo/AppData/Local/Temp/OpenModelica/OMEdit//Test.ssp --endpoint-pub=tcp://127.0.0.1:62462 --logLevel=0 --option "--suppressPath=true"
Traceback (most recent call last):
  File "F:/AllOMs/OM1.18.0-dev-218-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 12, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
Simulation process failed. Exited with code 0x00000001.

### Expected Behavior

Should run and give results (as does with rel. 1.17)
### Version and OS

 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

### Additional Context

[Test.zip](https://github.com/OpenModelica/OpenModelica/files/6318466/Test.zip)

**Comment by adrpo** [comment]
What python are you using? As far as I know you need to install zmq in it:
`python -m pip install zmq`

**Comment by adrpo** [comment]
Nevermind, I talked with the OMSimulator guys and it sems we're using the OMDev python which did not had this module intalled.
I now installed it in OMDev and in the next nightly this should work fine.

**Comment by adrpo** [comment]
Please test tomorrow and close the ticket if is OK.

**Comment by max-privato** [comment]
Sure. Thank you

Il Gio 15 Apr 2021, 16:06 Adrian Pop ***@***.***> ha scritto:

**Comment by max-privato** [comment]
I've downloaded today dev 221 and repeated the test. Now I don't have the issue anymore.
Thank you!
