### ISSUE TITLE
Parameters are not located correctly in parameter dialog under

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#7388]
### Description

Parameters grouped by the `Dialog` annotations `tab` and `group` are not located correctly under some conditions.

#### Case 1

Consider the following test package:

```modelica
package DialogGroup
  model DialogGroup
    parameter Real A annotation(
      Dialog(tab = "Tab 1"));
    parameter Real B annotation(
      Dialog(tab = "Tab 1", group = "Group 1"));
    parameter Real C annotation(
      Dialog(tab = "General", group = "Group 1"));
    parameter Real D annotation(
      Dialog(tab = "General"));
    parameter Real E annotation(
      Dialog(tab = "Tab 3", group = "Group 1"), enable = dummy);
  annotation(
      Icon(graphics = {Rectangle(lineThickness = 0.5, extent = {{-100, 100}, {100, -100}})}));
  end DialogGroup;

  model TestDialogGroup
  DialogGroup.DialogGroup dialogGroup  annotation(
      Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation

  end TestDialogGroup;
end DialogGroup;
```

The parameter dialog of the test model `TestDialogGroup` then shows:

![image](https://user-images.githubusercontent.com/4184218/115198973-f81b4a80-a0f2-11eb-8148-a2247385ab5d.png)

Once the undefined parameter `dummy` is replaced by `true` the parameter dialog is shown properly:

![image](https://user-images.githubusercontent.com/4184218/115199177-37e23200-a0f3-11eb-8edb-4394a989a312.png)

#### Case 2

Open the parameter dialog of the model `Modelica.Magnetic.FundamentalWave.Examples.BasicMachines.SMEE_DOL.smee`:

The parameters indicated by the red box are not located on the correct `tab="Nominal resistances and inductances"` and `group="DamperCage"`:

![image](https://user-images.githubusercontent.com/4184218/115200178-36fdd000-a0f4-11eb-8598-8f148a5cc9c1.png)

In case, however, the `enable` parameter `useDamperCage` is well defined, e.g.,

```modelica
parameter Modelica.SIunits.Resistance Rrd(start=0.04)
    "Rotor resistance, d-axis, w.r.t. stator side" annotation (Dialog(
      tab="Nominal resistances and inductances",
      group="DamperCage",
      enable=useDamperCage));
```

### Expected Behavior

- Case 1: Even though the parameter `dummy` in the model `DialogGroup.DialogGroup` is not defined the dialog shall be shown properly
- Case 2: The location of the damper cage parameters of the machine models shall be shown properly

### Version and OS

- Manjaro Linux Kernel 5.10.26-1
- Connected to OMCompiler v1.18.0-dev.143+g812c562916
- Connected to OMSimulator v2.1.1.post35-g69d29f1-linux

**Comment by christiankral** [comment]
Refs #2661

**Comment by christiankral** [comment]
In the current OMEdit 1.18.0 the following dialog is show without having the parameter `dummy` explicitly defined:

![image](https://user-images.githubusercontent.com/4184218/134571164-4cb6f03a-9f18-48bc-8399-d3780d6b06c5.png)

Observing this behavior this issue seems to be fixed. Is this the case? Can the ticket be closed?

**Comment by casella** [comment]
@christiankral I'm not sure if this fix is definitive or just due to random causes.

@perost is going to write a simple expression evaluator to solve the problems releated to parameters that influence the visualization (e.g. conditional connectors) and the dialog annotations, see #5631. Once that is done, we should have all the OMEdit features depending on parameters updated automatically. This evaluator is needed because the activation conditions may be written as expressions.

**Comment by adeas31** [comment]
I tested this today. This works with the old api since we take the default value as true and with instance api this works as expected.

**Comment by christiankral** [comment]
I also double checked the implementation. The behavior is now as expected.
