### ISSUE TITLE
Wrong URI expansion with loadResources

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#7409]
### Description

While using the `modelica://<LibraryName>` syntax the expanded URI 
is missing the library name.
e.g. the file `"modelica://polyFit_Pack/Resources/testPoly2D.mat"` gets expanded to
`"C:/workspace/_modelica_temp/Resources/testPoly2D.mat"` instead of
`"C:/workspace/_modelica_temp/polyFit_Pack/Resources/testPoly2D.mat"`

### Steps to Reproduce
Minimal example
[polyFit_Pack.zip](https://github.com/OpenModelica/OpenModelica/files/6377560/polyFit_Pack.zip)

### Version and OS

 - OpenModelica Version: v1.18.0-dev-239-g0e423e178d
 - OS: e.g. Windows 10, 64 bit
 - MSL 3.2.3

**Comment by sjoelund** [comment]
I get `... loading "Y" from "/home/martin/tmp/polyFit_Pack/Resources/testPoly2D.mat"`. Are you sure that the `package.mo` is loaded and not `C:/workspace/_modelica_temp/polyFit_Pack.mo`? You can check in OMEdit or using `getSourceFile(polyFit_Pack)`

**Comment by dariomangoni** [comment]
Hi Martin,
I probably did something strange because it's working also for me now. Sorry, don't know what happened.
