### ISSUE TITLE
Cannot resolve matrix product when array dimensions are given by different variables

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#7415]
### Description

I have this matrix production operation: `monEval*coeffs`
that works fine if the columns of `monEval` and rows of `coeffs` are defined by the same variable, but fails as soon as an alias variable is used.
e.g.
```
// THIS IS OK
Integer monCount = size(powerMatrix,1);
Real monEval[ptsCount, monCount];
Real coeffs[monCount];
```
```
// THIS IS OK
Real monEval[ptsCount, size(powerMatrix,1)];
Real coeffs[size(powerMatrix,1)];
```
```
// THIS FAILS
Integer monCount = size(powerMatrix,1);
Real monEval[ptsCount, monCount];
Real coeffs[size(powerMatrix,1)];
```

It's not a big deal, but it does make confusion.

### Steps to Reproduce

Minimal example: [productMatrixTest.zip](https://github.com/OpenModelica/OpenModelica/files/6385114/productMatrixTest.zip)

### Version and OS

 - OpenModelica Version: v1.18.0-dev-239-g0e423e178d
 - OS: e.g. Windows 10, 64 bit

**Comment by perost** [comment]
This was fixed by the same fix as for ##7432.
