### ISSUE TITLE
Preserve inverse functions in the flat model

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7416]
### Description

Inverse functions should be included in the flattened model

### Steps to Reproduce

If I flatten the attached `InverseFlattening.M` model after setting `--showStructuralAnnotations` I get
```
function InverseFlattening.f
  input Real x;
  input Real y;
  output Real z;
algorithm
  z := x * y + 1e-10 * sin(x * y);
  annotation(Inline = false, inverse(y = f_inv(x, z)));
end InverseFlattening.f;

class InverseFlattening.M
  Real x;
  Real y;
  Real z;
equation
  x = 10.0 + sin(time);
  z = 2.0 * x;
  InverseFlattening.f(x, y) = z;
end InverseFlattening.M;
```
### Expected Behavior

The definition of the inverse function `f_inv` should also be included, otherwise it is impossible to use it to solve the model more efficiently

**Comment by casella** [comment]
```
package InverseFlattening
  function f
    input Real x;
    input Real y;
    output Real z;
  algorithm
    z := x*y+1e-10*sin(x*y);
    // The small sin term prevents symbolic inversion
    // by smart tools
  annotation(Inline = false,
             inverse(y = f_inv(x,z)));
  end f;
             
  function f_inv
    input Real x;
    input Real z;
    output Real y;
  algorithm
    y := z/x;
    // approximated inverse
  annotation(Inline = false);
  end f_inv;
  
  model M
    Real x, y, z;
  equation
    x = 10 + sin(time);
    z = 2*x;
    f(x,y) = z;
  end M;
end InverseFlattening;
```

**Comment by perost** [comment]
This is probably a bigger issue than just adding inverse functions to the flat model, because as far as I can determine there's nothing in the compiler that actually uses the inverses. We store information about function derivatives in the DAE, but we have no equivalent for inverse functions.

**Comment by casella** [comment]
Absolutely. But I'd say that passing this information to the backend is the first required step to do that.

The reason I'm asking for this now is that we want to use this information in our new efficient LLVM compiler, which gets the flat, nonscalarized model as an input. So it would be nice to have it right away.

**Comment by phannebohm** [comment]
This is also something we want to make use of in the new backend. So please proceed :slightly_smiling_face:

**Comment by perost** [comment]
I've implemented support for function inverses in the frontend in #7567. @phannebohm please have a look if the DAE representation looks good or if you want it in some other form.

I don't do a whole lot of error checking, mostly just checking that it's on the correct form, that the variable is actually a function input parameter, and that the function has exactly one output. Are there anything else that's important that we check?

Also, I'm not sure how strict to be about errors, right now the compilation fails if there's an invalid inverse annotation. On one hand we might want to issue warnings instead since it's just an annotation that might no be entirely necessary, on the other hand users might miss that an inverse annotation is ignored if we only issue warnings.

**Comment by casella** [comment]
Thanks @perost! 

Inverse annotations are provided to improve efficiency, as far as I understand they are not that critical in general. Of course they could cause a model to fail because its lack may require to solve an inverse system numerically, and the lack of proper start values may cause it to fail. In that case, you would notice the warning. I'd suggest something like: "Invalid inverse annotation. Please note this may affect the efficiency of simulation and potentially cause numerical failures"

**Comment by perost** [comment]
I've now merged my PR. I'm not sure if we want to keep this issue open or not, the reported issue is technically fixed but without backend support it's kind of useless.

**Comment by casella** [comment]
> That was my understanding too, but thinking about it a bit more I realised it might be more trouble than it's worth to just give warnings. We would then have to either silence any error messages that might occur during instantiation and typing of the expressions in the annotation, leaving users with no clue what's wrong, or show the error messages and confuse users since they're not really errors.
> 
> So I'm leaning towards just keeping the current behaviour and fail on invalid inverse annotations. I don't think that invalid inverse annotations will be an issue in libraries, and if users write their own inverse annotations they probably want to know if they make a mistake. We've also dealt with invalid derivative annotations in the same way for a long time.

Makes sense, I agree.

**Comment by casella** [comment]
> 
> 
> I've now merged my PR. I'm not sure if we want to keep this issue open or not, the reported issue is technically fixed but without backend support it's kind of useless.

I'm going to close it. The reason I opened it was that we wanted to have access to derivative annotations for the experimental LLVM-based compiler at Politecnico.

Supporting the derivative annotations in OMC is a different topic. There is already a ticket about partial derivatives, maybe we should open one about this issue as well.
