### ISSUE TITLE
OMEdit - bad behaviour of the graph legend when a trace is hidden

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#7421]
### Description
suppose to plot more than one trace in the same graph, by clicking on a trace name in the legend the trace can be hidden/visualized.
Normally the name of the hidden trace is grayed out in the legend, and this is still true for the first trace that is hidden, but when you hide another trace the previous hidden trace  name in the legend comes back to black, so it is very difficult to understand what traces are hidden.

### Version and OS
OMEdit - OpenModelica Connection Editor
Connected to OpenModelica 1.18.0~dev-239-g0e423e1
Sysop: linux Ubuntu 18.04

**Comment by adeas31** [comment]
I quickly tested this and I can't reproduce this with the latest version on Windows. I will try to test it on Linux.

Can you make a small screencast that shows the problem.

**Comment by AndreaBartolini** [comment]
here a little screencast that shows the problem...

https://user-images.githubusercontent.com/25974985/116387629-462efd00-a81b-11eb-987b-8e9af03d6691.mp4

**Comment by AndreaBartolini** [comment]
here a screencast that shown the problem...

https://user-images.githubusercontent.com/25974985/116388367-0caac180-a81c-11eb-8da2-d221f802da31.mp4

**Comment by AndreaBartolini** [comment]
Hi Adeel, I've made a screencast but if I upload it here only the audio is reproduced (I don't understand the reason...).
So I send it directly @your email...

**Comment by adeas31** [comment]
Yes, that was a regression introduced in https://github.com/OpenModelica/OpenModelica/commit/0e423e178dc5c96573a0579a2a90c0080424293c. I already fixed it in https://github.com/OpenModelica/OpenModelica/commit/0e423e178dc5c96573a0579a2a90c0080424293c. I guess the Linux build is older than https://github.com/OpenModelica/OpenModelica/commit/0e423e178dc5c96573a0579a2a90c0080424293c

**Comment by AndreaBartolini** [comment]
Thanks Adeel,
in fact the linux build is broken since 5 days.... I'll wait that it becomes available yet...
