### ISSUE TITLE
OM compatibility on a very simple case

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7429]
### Description

I have a very simple case for which the FMUs created by OM can be successfully imported into Dymola, but cannot if pedantic mode is selected.
I'm not able to understand whether it is an OM or Dymola issue, and therefore report here. Indeed it could be an issue of the Dymola importing routine, which creates pedantic-incompatible OM code.

The error message I get from Dymola (pedantic mode) is as follows: 

`For algorithm 
CrossFMU_MOs_FirstOrder_fmu.fmi_Functions.fmiSetTime(
first.fmi, 
first.myTimeStart);
first.firstOrder.initType := CrossFMU_MOs_FirstOrder_fmu.fmi_Functions.fmiGetIntegerScalar (
first.fmi, 
0);

The types of the operands in (first.firstOrder.initType) = (CrossFMU_MOs_FirstOrder_fmu.fmi_Functions.fmiGetIntegerScalar (
first.fmi, 
0))
are Enumeration and Integer, but they must be compatible.

Variable first.firstOrder.initType was declared in class Modelica.Blocks.Types, declaration window at line 16, and used in component first.firstOrder.

The types of the operands in (first.firstOrder.initType) = (CrossFMU_MOs_FirstOrder_fmu.fmi_Functions.fmiGetIntegerScalar (
first.fmi, 
0))
are Integer and Integer, but they must be compatible.

Variable first.firstOrder.initType was declared in class Modelica.Blocks.Types, declaration window at line 16, and used in component first.firstOrder.

Basic type inconsistencies detected.

Translation aborted.`

Since the issue shows up only with pedantic mode, it should be a minor glitch. 
But just to let you know...

### Version and OS

OM 1.18.0-dev247 Win10 64 bit

[FirstOrder.zip](https://github.com/OpenModelica/OpenModelica/files/6413820/FirstOrder.zip)

**Comment by sjoelund** [comment]
Have you tried if Dymola allows you to import Dymola-generated FMUs in Dymola with pedantic mode? I suspect you cannot given the error message.

**Comment by max-privato** [comment]
Dymola imports the FMUs it creates in pedantic mode without any complaint. In the zip enclosed here you find the same firstOrder.mo as in the previous example, along with the FMU Dymola created (and can import in pedantic mode).

[FirstOrderDym.zip](https://github.com/OpenModelica/OpenModelica/files/6429982/FirstOrderDym.zip)

**Comment by sjoelund** [comment]
Dymola:
```xml
    <SimpleType
      name="Modelica.Blocks.Types.Init">
      <Enumeration>
        <Item name="NoInit"
          value="1"
          description="No initialization (start values are used as guess values with fixed=false)"/>
        <Item name="SteadyState"
          value="2"
          description="Steady state initialization (derivatives of states are zero)"/>
        <Item name="InitialState"
          value="3"
          description="Initialization with initial states"/>
        <Item name="InitialOutput"
          value="4"
          description="Initialization with initial outputs (and steady state of the states if possible)"/>
      </Enumeration>
    </SimpleType>
    <ScalarVariable
      name="firstOrder.initType"
      valueReference="100663298"
      description="Type of initialization (1: no init, 2: steady state, 3/4: initial output)"
      variability="constant">
      <Enumeration
        declaredType="Modelica.Blocks.Types.Init"
        start="2"/>
    </ScalarVariable>
```
OpenModelica:
```xml
    <SimpleType name="Modelica.Blocks.Types.Init">
      <Enumeration>
        <Item name="NoInit" value="1"/>
        <Item name="SteadyState" value="2"/>
        <Item name="InitialState" value="3"/>
        <Item name="InitialOutput" value="4"/>
      </Enumeration>
    </SimpleType>
  <ScalarVariable
    name="firstOrder.initType"
    valueReference="0"
    description="Type of initialization (1: no init, 2: steady state, 3/4: initial output)"
    variability="fixed"
    causality="calculatedParameter"
    >
    <Enumeration declaredType="Modelica.Blocks.Types.Init"/>
  </ScalarVariable>
```
So I don't see any difference except in Dymola it is a constant.

**Comment by max-privato** [comment]
yeah, it is rather strange.
Dymola has already shown to be not that good with FMUs recently, since it incorrectly gives zero as nominal value for state variables (ticket #1007). 

Maybe this is another example, but I don't have enough FMU knowledge to say anything serious about this.

Just to be sure, I checked again the behaviour of the enclosed two zip files, and I confirm that the OM fmu causes the given error message with pedantic=true, while it does not with the Dymola'se FMU.
Without pedantic, the OM FMU issues the same message, which however is now considered just a warning.

**Comment by sjoelund** [comment]
So I checked in Dymola, and their generated code contains:
```mo
constant Modelica.Blocks.Types.Init initType = Modelica.Blocks.Types.Init.SteadyState "Type of initialization (1: no init, 2: steady state, 3/4: initial output)";
```

So I guess it would work if OpenModelica would turn that final parameter into a constant, like Dymola does. But otherwise, it simply seems like Dymola cannot handle enumerations in imported FMUs without warnings/errors (pedantic mode).

I'm not sure if OpenModelica should be changed to consider these parameters as constants. It would change into constant when importing (like Dymola does). But an evaluated `final parameter` is sort of like a constant anyway... @lochel any comments?

**Comment by max-privato** [comment]
I made several tests today, but could not replicate the issue.
So, I'm closing the ticket.
