### ISSUE TITLE
Weird regression of OMC on Apr 29

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7439]
### Description

one of the [three commits on Apr 29](https://github.com/OpenModelica/OpenModelica/commits/master?before=877362bf7aaa7be3cb0f28d6b688f20a87586365+35&branch=master) broke some models of the [AES library](https://github.com/looms-polimi/Automation_of_Energy_Systems/tree/main/Modelica/AES), that used to work with the previous nightly build, based on the previous day's commit [355f2a42](https://github.com/OpenModelica/OpenModelica/commit/355f2a42a3908c35ce663ee4d5da0e7fb7bbd9d1). I checked that by running the same library with these two nightly builds:

OpenModelica-v1.18.0-dev-250-g877362bf7a-64bit.exe (fails)
OpenModelica-v1.18.0-dev-247-g355f2a42a3-64bit.exe (work fine)

For example, the model AES.Devel_test_models.Test_twin_pipes_002 now fails with

[1] 19:41:22 Translation Error
Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular
and cannot be handled because the number of unassigned equations is larger than the number of states.
Use -d=bltdump to get more information.

[2] 19:41:22 Translation Error
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!

This is particularly weird, because the three commits on Apr 29 have nothing to do with the backend. One is a library update, which has nothing to do with this issue (the regression is obtained with exactly the same version of the library). One concerns record in the frontend, whereas this test case has no records and I checked that the flat model output is exactly the same I got with the previous nightly build. The last one concerns the GUI.

I really have no clue what could have caused this regression. Anyone can help?

### Steps to Reproduce

Get AES from the github repo and try to simulate AES.Devel_test_models.Test_twin_pipes_002 in OMEdit with those two versions of OMC

### Version and OS

The problem can be reproduced both on Linux and Windows

**Comment by perost** [comment]
>One concerns record in the frontend, whereas this test case has no records and I checked that the flat model output is exactly the same I got with the previous nightly build. The last one concerns the GUI.

This is actually not true, my record fixes touched a lot of the backend. That commit also broke 2 models in the Buildings library, and I couldn't figure out why. I had given up on fixing that issue myself, but the fact that this model doesn't actually contain any records was the clue I needed since very few of my changes did not concern records.

**Comment by casella** [comment]
I'll check with the latest nightly build that includes https://github.com/perost/OpenModelica/commit/5d4d8445ae23927b70819ba4ff6bb9c63387cf83, but I'm a bit skeptical. I compared the output of `-d=dumpdaelow` before and after your original changes and they were exactly the same. Unless I messed up somehow with the installations...

**Comment by perost** [comment]
> I'll check with the latest nightly build that includes [perost@5d4d844](https://github.com/perost/OpenModelica/commit/5d4d8445ae23927b70819ba4ff6bb9c63387cf83), but I'm a bit skeptical. I compared the output of `-d=dumpdaelow` before and after your original changes and they were exactly the same. Unless I messed up somehow with the installations...

The issue was that it just failed during index reduction because it used a function in the old frontend that I had changed, up to that point the behaviour would've been identical and not shown up in dumpdaelow.

**Comment by casella** [comment]
Aha, that explains it. I was starting to believe ghouls and poltergeists were involved... 😄
