### ISSUE TITLE
Memory leak in modelInfoInit

### ISSUE THREAD

**Issue by jschueller** [OpenModelica/OpenModelica#7444]
the memory allocated in modelInfoInit: https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/simulation_info_json.c#L396

leaks from fmi2Instantiate:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu2_model_interface.c.inc#L549

and also possibly in fmi2Reset where it should be freed before the new is allocated:
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/openmodelica/fmu2_model_interface.c.inc#L841

could you have a look @AnHeuermann ?

**Comment by AnHeuermann** [comment]
Thanks for finding the potential leaks! That is usually the annoying part.
I'll have a look into it when I have some time.

**Comment by jschueller** [comment]
yes, it takes some valgrind-fu, thanks

**Comment by casella** [comment]
If possible, pls. commit to master and then backport to 1.17.1

**Comment by AnHeuermann** [comment]
I have created a PR with the fix and when all tests are passing it will be in the next nightly build.
I will backport it to 1.17.1 as soon as we are sure it doesn't introduced any strange new bugs.

@jschueller Can you re-run your example and check if that solved the memory leak for you?

**Comment by jschueller** [comment]
I can only test this in a few weeks when I get back

**Comment by casella** [comment]
@jschueller no problem, in case there are still issues please open a new issue here on Github
