### ISSUE TITLE
Docker build FMUs from Windows not working

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7458]
### Description

On native Linux (and from WSL) it is possible to generate a FMU for a different system using Docker images. On Windows it fails because `configure` is missing.

### Steps to Reproduce

Run the following script with omc:
```
loadModel(Modelica); getErrorString();
buildModelFMU(Modelica.Electrical.Analog.Examples.Rectifier, platforms={"x86_64-linux-gnu docker run docker.openmodelica.org/build-deps:v1.13"}); getErrorString();
```

This works fine on Linux and WSL but not on Windows:
```bash
true
""
""
"Error: Error building simulator. Build log: docker run  --rm -w /fmu -v d5a61f086415c080e081f71aa66f6e91f668de1e08ce749a7bd6783d835cbfbd:/fmu docker.openmodelica.org/build-deps:v1.13 sh -c \"cd \"/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources\" && ./configure --host='x86_64-linux-gnu' CFLAGS='-Os' CPPFLAGS=-I/fmu/fmiInclude LDFLAGS= && make -j16 nozip\":
d5a61f086415c080e081f71aa66f6e91f668de1e08ce749a7bd6783d835cbfbd
sh: 1: ./configure: not found
"
```

When running `ls` inside the directory I can see that indeed `configure` is missing. Simply calling `autoconf` doesn't solve the issue, because it can't find `lapack.m4`:
```bash
/usr/bin/m4:configure.ac:179: cannot open `../../../../m4/lapack.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
"
```

How do we create `configure` for this on a Linux system?

### Version and OS

 - OpenModelica Version: OpenModelica v1.18.0-dev-272-g684374e13a (64-bit)
 - OS: Windows 10

**Comment by lochel** [comment]
@AnHeuermann can you take of the issue? I have not much experience with docker.

**Comment by AnHeuermann** [comment]
The Docker part itself is not complicated here. 
But I don't know how to get the configure stuff running. It would be good to understand how it works on Linux when generating a Windows FMU with a Docker image. 

Normally we either run autoconf or generate the Makefile with some guessed configuration I think.

**Comment by sjoelund** [comment]
We don't run autoconf in omc. It is done once during `make omc` and the generated configure script is simply copied into the FMU:
```
  <%\t%>cp -a "<%makefileParams.omhome%>/share/omc/runtime/c/fmi/buildproject/"* <%fileNamePrefix%>.fmutmp/sources
```

**Comment by AnHeuermann** [comment]
I managed to get a configure from a Linux container and to generate Code that targets Linux, but it seems that `docker cp` is not working they way I think it should. Maybe it is a bug on Windows or I just use it wrong.

We are doing
```
$ docker volume create
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df

$ docker run --cidfile Modelica_Electrical_Analog_Examples_Rectifier.fmutmp.cidfile -v d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df:/data busybox true
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df

$ docker cp Modelica_Electrical_Analog_Examples_Rectifier.fmutmp b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48:/data
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df

$ docker cp "D:/workspace/OpenModelica/build/include/omc/c/fmi" b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48:/data/fmiInclude
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df

$ docker run  --rm -w /fmu -v d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df:/fmu openmodelica/openmodelica:v1.17.0-minimal sh -c "cd "/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/sources" && cp -a /usr/share/omc/runtime/c/fmi/buildproject/* . && ./configure --host='x86_64-linux-gnu' CFLAGS='-Os' CPPFLAGS=-I/fmu/fmiInclude LDFLAGS= && make -j16 nozip"
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df

$ docker cp 'b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48:/data/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp' .:
d6027fa65497e3adf2d316af1808745fa77d208244eff990c40a7aca8a52c5df
Error: No such container:path: 'b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48:/data/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp'
```

First we copy some files into the newly created volume.
Then inside the container that uses the volume we compiled all sources to some Linux binaries which are in `/fmu/Modelica_Electrical_Analog_Examples_Rectifier.fmutmp/`.
Now we want to copy everything pack to the host wich I can't get to work. I always get an error telling me that the path doesn't exist.

We are copying everything to `/data/` on the third call, so why does copying back not work? Is `/data/` never created in the container in the first place? Is it a bug in Docker on Windows (Docker with WSL2)....

**Comment by sjoelund** [comment]
https://stackoverflow.com/questions/40313633/how-to-copy-files-from-local-machine-to-docker-container-on-windows

**Comment by sjoelund** [comment]
Does `docker ps` list b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48 ?

**Comment by AnHeuermann** [comment]
>Does docker ps list b84cb44ff37f701c8bc630bd33b53d087129ffff9e94719478d3eaac8d2d9c48 ?

No. So that's why the `docker cp` is failing.

I removed the `--rm` but that didn't help. Any idea why the container is stopped/removed?

**Comment by sjoelund** [comment]
It should remove it unless you remove that part of omc, I guess. But otherwise I have no clue :)
Try to make sure omc does not remove the containers/volumes and check their contents after the failure.

**Comment by AnHeuermann** [comment]
So I got something to run.

We need to copy files from `OpenModelica/common` (containing some `.m4` files and `install-sh`, as well as `OpenModelica/OMCompiler/m4` into the FMU.

The FMI headers should already be available in `fmu/fmiInclude`.

Then we can configure with
```
$ autoconf
$ ./configure --host='x86_64-linux-gnu' CFLAGS='-Os' CPPFLAGS=-I/fmu/fmiInclude
```

Next I need to figure out how to compile the sources. We have some problems with the Makefile as it wants to use `-Wl,--kill-at` for g++. Removing that should be fine.
But we also link to `liblis` which we don't have for Linux (from Windows host) and the source-code FMU should compile it itself.

I don't think we have a general `Makefile.in` that could be used for corss-compiled FMUs.

Maybe the basic problem is that we don't have source-code FMUs that can be compile on different OS.
