### ISSUE TITLE
OMEdit shall support simple creation of connectors

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7460]
When building component models graphically, some of the connectors need to be exposed to the outside. As of today, these top level connectors need to be created like component models from the respective model library.

OMEdit should support the creating of top level connectors directly when drawing a connection line. E.g. a right click could open a popup menu with a button to create a connector of the respective type.

See this example -- a top level output shall be created:

![CreateConnector](https://user-images.githubusercontent.com/4224368/117947393-7218ab00-b310-11eb-94fa-b8b39ab65ece.png)

**Comment by casella** [comment]
This feature requires OMEdit to fetch the type of the connector to which the connection is made. I guess this feature is already available from the API, in which case this would be quite easy to implement. @adeas31, is this the case?

**Comment by adeas31** [comment]
See #5069.

We already had a ticket about it in our old trac system [#5069](https://trac.openmodelica.org/OpenModelica/ticket/5069).
I will close the old one.
