### ISSUE TITLE
Bad log scale in OMEdit

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7468]
### Description

OMEdit chooses as y log scale 1e100 whatever the range is.

### Steps to Reproduce
1) load and run Test in OMEdit
2) plot Cf.abs_v
3) choose Log Y scale: the range is between 1e-100 and 1 instead of 1e-4 and 1 (as can be seen manually scaling the vertical axis).

The same bad scale is chosen also if one clicks on "Fit in view" after manual scaling

### Expected Behavior
The y range should be between 1e-4 and 1 

### Screenshots
![image](https://user-images.githubusercontent.com/37046832/118439092-9fd16b80-b6e5-11eb-878d-7173a40cecc3.png)
![image](https://user-images.githubusercontent.com/37046832/118439138-acee5a80-b6e5-11eb-9e14-502742ca322e.png)

### Version and OS
OM 1.18.0-dev247 64 bit Win 10.

### Additional Context

[Test.zip](https://github.com/OpenModelica/OpenModelica/files/6491467/Test.zip)

**Comment by max-privato** [comment]
Just to prompt about this ticket.
I see that OM re. 1.18.0 is issued. In case this requires a little work, maybe can it go into 1.18.1?
Thank you.

**Comment by casella** [comment]
I guess so, it shouldn't be hard to fix.

**Comment by adeas31** [comment]
I guess the absolute value in this case becomes zero so we are in dealing with point 2 here. Note that the tool doesn't consider the actual value for finding the range but it actually takes a slightly higher and lower value which is the bounding rectangle of the plot.

I am fine with 1e-20 and 1e20. This is how the plot will look like in this case,

![plot](https://user-images.githubusercontent.com/4007231/137487803-2137ce01-169a-44ee-bee6-728957b92029.png)

@max-privato what do you think?

**Comment by max-privato** [comment]
I'm always surprised at know how these so-called professional tools like Qwt (and, as you say, even Dymola) manage things!

Along recent years I continuously come across limitations that my amateur PlotXY (http://ceraolo-plotxy.ing.unipi.it/default.htm) does not have. 
Also in this case: PlotXY manages the log scale of sample of this ticket very smoothly (see png below).

To put it simple, what I basically do in potXY, and seems to me very easy to implement is:
1. determine the maximum and minimum values of the numbers on a given axis
2. write them  internally in exponential form on a string, 
3. read the exponents from those strings and use this info to choose the log scale.

Easy peasy!

![XY](https://user-images.githubusercontent.com/37046832/137807879-86a1b8aa-3423-4889-abcc-f3014480b64e.png)

**Comment by casella** [comment]
See also [#6222](https://trac.openmodelica.org/OpenModelica/ticket/6222#comment:5).

**Comment by max-privato** [comment]
@adeas31 , have you seen my comment above dated Oct, 18?

**Comment by adeas31** [comment]
Yes I saw your comment. I didn't get much time to look into this issue.
I will see what we can do to get this working.

**Comment by casella** [comment]
@max-privato we need to finalize the library handling ASAP, we can look into this once we've branched off 1.19.0-beta.1

**Comment by adrpo** [comment]
The Linux nightly builds are broken so I guess you have an older version. I reported the issues to Adeel hopefully he can fix them quickly and we will have new nightly-builds soon.

**Comment by adeas31** [comment]
See #11105

**Comment by casella** [comment]
@ceraolo can you please confirm it now works for you?

Thanks!

**Comment by ceraolo** [comment]
yes, it's ok.
