### ISSUE TITLE
Is the FMU correct?

### ISSUE THREAD

**Issue by GianniFerretti** [OpenModelica/OpenModelica#7469]
Good afternoon,

we tried to generate an FMU of the model

https://www.dropbox.com/s/caay6ap1o1gyhsb/ADM1_BMP_noinput_monolitico_day.mo?dl=0

to use it for parameter identification with OMSysIdent.
We then tried to simulate the generated FMU:

https://www.dropbox.com/s/5hq6lo69yde1jzg/ADM1_BMP.fmu?dl=0

with SSP but it crashed.
Of course OMSysIdent also crashed.
Are we missing something?

Thank you in advance

G. Ferretti
@casella

**Comment by casella** [comment]
@lochel, it is not 100% clear if the problem is with the FMU generation or with the FMU simulation, but I guess there is something wrong with the FMU generation, since also OMSysIdent fails.

Could you have a look at it?

Thanks!

**Comment by lochel** [comment]
Good question. I tried to simulate the model on Windows and Linux and can confirm that it doesn't quite work. However, I cannot judge at this point if the fmi export or import is to blame. I'll have to investigate more...

**Comment by bilderbuchi** [comment]
Issue seems very outdated, and FMU for reproduction is not available anymore, so I think this should be closed.

**Comment by casella** [comment]
@GianniFerretti if necessary please reopen.
