### ISSUE TITLE
Missing attribute in modelDescription.xml

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#7472]
### Description

Variable type input is missing the "variability" attribute in modelDescription.xml when exported using v1.18

```
<!-- Index of variable = "5" -->
-<ScalarVariable name="R_in" valueReference="4" causality="input">
<Real start="1.2"/>
</ScalarVariable>
```

### Steps to Reproduce

Export following model as fmi v2.0 co-simulation with static library and no filter for xml

```
model RLC_circuit_v2
  input Real R_in(start=1.2, fixed=true);
  Modelica.Electrical.Analog.Basic.Inductor inductor1(L = 0.001)  annotation(
    Placement(visible = true, transformation(origin = {30, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.VariableResistor resistor annotation(
    Placement(visible = true, transformation(origin = {-4, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage1(V = 12)  annotation(
    Placement(visible = true, transformation(origin = {-32, -4}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Ground ground1 annotation(
    Placement(visible = true, transformation(origin = {-32, -32}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.Capacitor capacitor1(C = 0.1, v(fixed = true, start = 10))  annotation(
    Placement(visible = true, transformation(origin = {52, -8}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
equation
  connect(resistor.n, inductor1.p) annotation(
    Line(points = {{6, 10}, {20, 10}, {20, 10}, {20, 10}}, color = {0, 0, 255}));
  connect(resistor.p, constantVoltage1.p) annotation(
    Line(points = {{-14, 10}, {-32, 10}, {-32, 6}, {-32, 6}}, color = {0, 0, 255}));
  connect(ground1.p, constantVoltage1.n) annotation(
    Line(points = {{-32, -22}, {-32, -22}, {-32, -14}, {-32, -14}}, color = {0, 0, 255}));
  resistor.R = R_in;
  connect(inductor1.n, capacitor1.p) annotation(
    Line(points = {{40, 10}, {52, 10}, {52, 2}, {52, 2}}, color = {0, 0, 255}));
  connect(ground1.p, capacitor1.n) annotation(
    Line(points = {{-32, -22}, {52, -22}, {52, -18}, {52, -18}}, color = {0, 0, 255}));
  annotation(
    uses(Modelica(version = "3.2.3")));
end RLC_circuit_v2;
```

### Expected Behavior

input R_in has attribute "variability" like in v1.14

```
<!-- Index of variable = "5" -->
-<ScalarVariable name="R_in" causality="input" variability="continuous" valueReference="4">
<Real start="1.2"/>
</ScalarVariable>
```

### Version and OS

Version: OpenModelica-v1.18.0-dev-250-g877362bf7a-64bit
OS: Windows 10 64bit

**Comment by lochel** [comment]
The default variability is continuous and therefore skipped according to the FMI specification. You can force all attributes, including default values, with the flag `-d=force-fmi-attributes`.

```xml
  <!-- Index of variable = "5" -->
  <ScalarVariable
    name="R_in"
    valueReference="4"
    variability="continuous"
    causality="input"
    >
    <Real start="1.2"/>
  </ScalarVariable>
```

**Comment by Arinomo** [comment]
@lochel quick question, this flag is set on Translation Flags right?

**Comment by adeas31** [comment]
Yes, put it in `Additional Translation Flags:`.

**Comment by lochel** [comment]
Yes, that's right:
![image](https://user-images.githubusercontent.com/8457302/118795238-aead4f00-b89a-11eb-8e75-886a2c3ce926.png)

**Comment by Arinomo** [comment]
Thank you.. Thats why it didn't work, i put the flag in model annotation :p

**Comment by Arinomo** [comment]
> 
> 
> You can find it [here in the documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-debug-force-fmi-attributes). Debug flags are part of the translation flags, not runtime simulation flags.

Yes, i didn't realize i should add the flag from Tools -> Option -> Simulation -> Additional Tranlsation Flags. I thought adding `-d=force-fmi-attributes` in annotation is sufficient.

```
annotaion(
   __OpenModelica_commandLineOptions= "--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian, -d=force-fmi-attributes"
);
```

**Comment by lochel** [comment]
I haven't tested it, but it should also work from the annotation I think. @adeas31 is there anything to fix? Is it a problem to have -d twice in the command line string?

**Comment by sjoelund** [comment]
It might be a problem that FMUs don't use the flags perhaps? It's an OMEdit-specific annotation as far as I know

**Comment by casella** [comment]
> > You can find it [here in the documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-debug-force-fmi-attributes). Debug flags are part of the translation flags, not runtime simulation flags.
> 
> Yes, i didn't realize i should add the flag from Tools -> Option -> Simulation -> Additional Tranlsation Flags. I thought adding `-d=force-fmi-attributes` in annotation is sufficient.
> ``` annotation(
>    __OpenModelica_commandLineOptions= "--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian -d=force-fmi-attributes"
> );
> ```


It should be the same. In fact, if you put that flag in the Additional Translation Flag and then check the checkbox to save it in the annotation, it will automatically be written there, so next time you load the model this setting is included.

I'm not 100% sure if having two separate `-d=xxx` annotations would work, though, it may be that the second overrides the first, so you should put all the debug flags together in a single `d=xxx,yyy,zzz` flag. @adrpo, @adeas31, is that the case?

**Comment by sjoelund** [comment]
Having them separate works just fine. However, like I thought:
```mo
model M
equation

annotation(
    __OpenModelica_commandLineOptions = "--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian -d=xxx");
end M;
```
Try that in OMEdit, and press simulate and after Export->FMU. The error-message that `-d=xxx` is an invalid flag is only printed for simulate. So OMEdit doesn't use its own flag. And omc itself doesn't know about the flag.

**Comment by casella** [comment]
> 
> 
> Having them separate works just fine. However, like I thought:
> 
> ```modelica
> model M
> equation
> 
> annotation(
>     __OpenModelica_commandLineOptions = "--matchingAlgorithm=PFPlusExt --indexReductionMethod=dynamicStateSelection -d=initialization,NLSanalyticJacobian -d=xxx");
> end M;
> ```
> 
> Try that in OMEdit, and press simulate and after Export->FMU. The error-message that `-d=xxx` is an invalid flag is only printed for simulate. So OMEdit doesn't use its own flag. And omc itself doesn't know about the flag.

@lochel, what do you think?

**Comment by lochel** [comment]
It should be fixed. I opened #7478 which should fix the issue. However, we might want to test it a bit before merging it.

**Comment by adeas31** [comment]
`__OpenModelica_commandLineOptions` is not an OMEdit specific annotation. It is used inside the compiler as well during the translateModel.

#7478 is perfectly fine.
