### ISSUE TITLE
FMU Export Error

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#7474]
### Description

Exporting model with OpenModelica-v1.18.0-dev-250-g877362bf7a-64bit failed with following error

> [1] 11:23:34 Translation Warning
> Assuming fixed start value for the following 1 variables:
>          inductor1.i:VARIABLE(start = 0.0 unit = "A" fixed = true )  "Current flowing from pin p to pin n" type: Real
> 
> [2] 11:23:34 Translation Error
> Error building simulator. Build log: clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit.o RLC_circuit.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_functions.o RLC_circuit_functions.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_records.o RLC_circuit_records.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_01exo.o RLC_circuit_01exo.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_02nls.o RLC_circuit_02nls.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_03lsy.o RLC_circuit_03lsy.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_04set.o RLC_circuit_04set.c
> In file included from RLC_circuit.c:7: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_05evt.o RLC_circuit_05evt.c
> In file included from RLC_circuit_functions.c:2: 
> In file included from ./RLC_circuit_functions.h:3: 
> In file included from ./meta/meta_modelica.h:49: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_records.c:4: 
> In file included from ./meta/meta_modelica.h:49: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_06inz.o RLC_circuit_06inz.c
> 2 warnings generated. 
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_07dly.o RLC_circuit_07dly.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_08bnd.o RLC_circuit_08bnd.c
> In file included from RLC_circuit_04set.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_01exo.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_06inz.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.hIn file included from RLC_circuit_03lsy.c:2:219:28: warning: expression result unused [-Wunused-value] 
> : 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_05evt.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_02nls.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> In file included from RLC_circuit_07dly.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_09alg.o RLC_circuit_09alg.c
> In file included from RLC_circuit_08bnd.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> 2 warnings generated. 
> 22 warnings generated. 
>  warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_10asr.o RLC_circuit_10asr.c
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_11mix.o RLC_circuit_11mix.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_12jac.o RLC_circuit_12jac.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_13opt.o RLC_circuit_13opt.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_14lnz.o RLC_circuit_14lnz.c
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_15syn.o RLC_circuit_15syn.c
> In file included from RLC_circuit_09alg.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_10asr.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> In file included from RLC_circuit_11mix.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_12jac.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_16dae.o RLC_circuit_16dae.c
> In file included from RLC_circuit_13opt.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_14lnz.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_15syn.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_17inl.o RLC_circuit_17inl.c
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_18spd.o RLC_circuit_18spd.c
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_init_fmu.o RLC_circuit_init_fmu.c
> 2 warnings generated. 
> In file included from RLC_circuit_16dae.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> 2 warnings generated. 
> clang -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1  -c -o RLC_circuit_FMU.o RLC_circuit_FMU.c
> 2 warnings generated. 
> In file included from RLC_circuit_17inl.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_18spd.c:2: 
> In file included from ./RLC_circuit_model.h:5: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> In file included from RLC_circuit_init_fmu.c:1: 
> In file included from ./simulation_data.h:39: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> In file included from RLC_circuit_FMU.c:9: 
> In file included from ./openmodelica.h:71: 
> In file included from ./gc/../openmodelica_types.h:149: 
> ./gc/omc_gc.h:219:28: warning: expression result unused [-Wunused-value] 
>   GC_register_displacement(0); 
>                            ^ 
> ./gc/omc_gc.h:223:34: warning: expression result unused [-Wunused-value] 
>   GC_set_force_unmap_on_gcollect(1); 
>                                  ^ 
> 2 warnings generated. 
> 2 warnings generated. 
> In file included from RLC_circuit_FMU.c:55: 
> ./fmi-export/fmu2_model_interface.c.inc:169:16: warning: passing 'char **' to parameter of type 'const char **' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers] 
>   GC_vasprintf(&str, msg, args); 
>                ^~~~ 
> ./gc/../meta/../util/modelica_string.h:71:31: note: passing argument to parameter 'strp' here 
> int GC_vasprintf(const char **strp, const char *fmt, va_list ap); 
>                               ^ 
> 2 warnings generated. 
> In file included from RLC_circuit_FMU.c:56: 
> ./fmi-export/fmu_read_flags.c.inc:181:7: warning: implicit declaration of function 'access' is invalid in C99 [-Wimplicit-function-declaration] 
>   if( access( flags_filename, 0 ) != -1 ) 
>       ^ 
> 4 warnings generated. 
> g++ -shared -I. -o RLC_circuit.dll   RLC_circuit.o RLC_circuit_functions.o RLC_circuit_records.o RLC_circuit_01exo.o RLC_circuit_02nls.o RLC_circuit_03lsy.o RLC_circuit_04set.o RLC_circuit_05evt.o RLC_circuit_06inz.o RLC_circuit_07dly.o RLC_circuit_08bnd.o RLC_circuit_09alg.o RLC_circuit_10asr.o RLC_circuit_11mix.o RLC_circuit_12jac.o RLC_circuit_13opt.o RLC_circuit_14lnz.o RLC_circuit_15syn.o RLC_circuit_16dae.o RLC_circuit_17inl.o RLC_circuit_18spd.o RLC_circuit_init_fmu.o RLC_circuit_FMU.o -I"C:/OpenModelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -DCMINPACK_NO_DLL=1 -L"R:/9010_Misc"   -Os -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -L"C:/OpenModelica/lib//omc" -Wl,-rpath,"C:/OpenModelica/lib//omc" -fopenmp -Wl,-Bstatic -lregex -ltre -lintl -liconv -lexpat -lomcgc -lpthread -loleaut32 -limagehlp -lhdf5 -lz -lszip -Wl,-Bdynamic  -lSimulationRuntimeFMI  -Wl,-Bstatic -lregex -ltre -lintl -liconv -static-libgcc -lpthread -lm  -lgfortran -lquadmath -lmingw32 -lgcc_eh -lmoldname -lmingwex  -luser32 -lkernel32 -ladvapi32 -lshell32 -limagehlp -lopenblas -lhdf5 -lz -lszip -Wl,-Bdynamic  -llis -Wl,--kill-at
> mkdir.exe -p ../binaries/win64
> dlltool -d RLC_circuit.def --dllname RLC_circuit.dll --output-lib RLC_circuit.lib --kill-at
> cp RLC_circuit.dll RLC_circuit.lib RLC_circuit_FMU.libs ../binaries/win64/
> rm -f *.o RLC_circuit.dll RLC_circuit.o RLC_circuit_functions.o RLC_circuit_records.o RLC_circuit_01exo.o RLC_circuit_02nls.o RLC_circuit_03lsy.o RLC_circuit_04set.o RLC_circuit_05evt.o RLC_circuit_06inz.o RLC_circuit_07dly.o RLC_circuit_08bnd.o RLC_circuit_09alg.o RLC_circuit_10asr.o RLC_circuit_11mix.o RLC_circuit_12jac.o RLC_circuit_13opt.o RLC_circuit_14lnz.o RLC_circuit_15syn.o RLC_circuit_16dae.o RLC_circuit_17inl.o RLC_circuit_18spd.o RLC_circuit_init_fmu.o RLC_circuit_FMU.o  
> cd .. && rm -f ../RLC_circuit.fmu && zip -r ../RLC_circuit.fmu *
> rm: cannot remove '../RLC_circuit.fmu': Device or resource busy
> make: *** [Makefile:65: nozip] Error 1

### Steps to Reproduce

exporting this model works in v1.14
```
model RLC_circuit
  Modelica.Blocks.Interfaces.RealInput R_in;
  parameter Integer P1 = 8;
  Modelica.Electrical.Analog.Basic.Capacitor capacitor1(C = 0.1, v(fixed = true, start = 10))  annotation(
    Placement(visible = true, transformation(origin = {78, -4}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Inductor inductor1(L = 0.001)  annotation(
    Placement(visible = true, transformation(origin = {30, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Basic.VariableResistor resistor annotation(
    Placement(visible = true, transformation(origin = {-4, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage1(V = 12)  annotation(
    Placement(visible = true, transformation(origin = {-32, -4}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Ground ground1 annotation(
    Placement(visible = true, transformation(origin = {-32, -32}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interfaces.RealOutput y annotation(
    Placement(visible = true, transformation(origin = {84, 40}, extent = {{-10, -10}, {10, 10}}, rotation = 0), iconTransformation(origin = {76, -40}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Sensors.CurrentSensor currentSensor annotation(
    Placement(visible = true, transformation(origin = {58, 10}, extent = {{-10, 10}, {10, -10}}, rotation = 0)));
equation
  connect(resistor.n, inductor1.p) annotation(
    Line(points = {{6, 10}, {20, 10}, {20, 10}, {20, 10}}, color = {0, 0, 255}));
  connect(resistor.p, constantVoltage1.p) annotation(
    Line(points = {{-14, 10}, {-32, 10}, {-32, 6}, {-32, 6}}, color = {0, 0, 255}));
  connect(ground1.p, constantVoltage1.n) annotation(
    Line(points = {{-32, -22}, {-32, -22}, {-32, -14}, {-32, -14}}, color = {0, 0, 255}));
  connect(ground1.p, capacitor1.n) annotation(
    Line(points = {{-32, -22}, {78, -22}, {78, -14}}, color = {0, 0, 255}));
  resistor.R = R_in;
  connect(inductor1.n, currentSensor.p) annotation(
    Line(points = {{40, 10}, {48, 10}}, color = {0, 0, 255}));
  connect(currentSensor.n, capacitor1.p) annotation(
    Line(points = {{68, 10}, {78, 10}, {78, 6}}, color = {0, 0, 255}));
  connect(y, currentSensor.i) annotation(
    Line(points = {{84, 40}, {58, 40}, {58, 22}, {58, 22}}, color = {0, 0, 127}));

annotation(
    uses(Modelica(version = "3.2.3")));
end RLC_circuit;
```

### Expected Behavior

FMU export sucessfully

### Version and OS

Version: OpenModelica-v1.18.0-dev-250-g877362bf7a-64bit
OS: Windows 10 64bit

**Comment by adrpo** [comment]
Is telling you Is not possible to delete the previously build fmu: ​`rm: cannot remove '../RLC_circuit.fmu': Device or resource busy`.
Which probably means you have the fmu file opened in some zip tool or some modeling tool. Close that and try to build again.
