### ISSUE TITLE
No drop down menue in parameter dialog for string choices

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7489]
### Description
A definition like 
 `parameter String Option = "Option 1" annotation(choices(choice = "Option 1", choice = "Option 2", choice = "Option 3"));`

should end in a parameter dialog with a drop down menue with the entries 
"Option 1"
"Option 2"
"Option 3"

but only shows 
![grafik](https://user-images.githubusercontent.com/84787397/119623468-7cef3780-be08-11eb-980f-3b53e52c065d.png)

Here a translational error occurs (Duplicate modification of element choice on component choices) which might be the problem. But this one should not be there in my opintion. Minimal example for string choices is given in the Modelica Specification

### Steps to Reproduce

Open the parameter dialog of Model1 in below given minimal example

```
package NoDropDownChoicesString
  model Model1
    parameter String Option = "Option 1" annotation(choices(choice = "Option 1", choice = "Option 2", choice = "Option 3"));
  
    parameter Boolean test1;
  equation

  end Model1;

  model testModel1
    Model1 model11(test1 = false)  annotation(
      Placement(visible = true, transformation(origin = {2, 4}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation

  end testModel1;
end NoDropDownChoicesString;
```

### Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

Best wishes

Sven Bätzing

**Comment by casella** [comment]
I guess the reason is the same as in #7487, i.e. `choices()` not (fully?) implemented

**Comment by casella** [comment]
PR #7652 should fix this

**Comment by casella** [comment]
Unfortunately this is different from #7487, so PR #7652 was not beneficial.

**Comment by niklwors** [comment]
This is fixed now.
