### ISSUE TITLE
Ports which are disabled via conditions still appears in Icon of the class

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7492]
### Description

E.g in 
Modelica.Mechanics.Translational.Sources.Force
there is a support flange derived in class
Modelica.Mechanics.Translational.Interfaces.PartialOneFlangeAndSupport
which is disabled by default parametrization. Even so its always displayed when using the force class. Even setting up connections is possible.

![grafik](https://user-images.githubusercontent.com/84787397/119626798-db69e500-be0b-11eb-8e09-e1054cf936ec.png)

### Expected Behavior

Ports which are disabled due to their condition e.g. 
```
Support support if useSupport "Support/housing of component"
    annotation (Placement(transformation(extent={{-10,-110},{10,-90}})));

```
should disappear from the icon if their are disabled.

## Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

Best wishes

Sven Bätzing

**Comment by adeas31** [comment]
Same as #2081.

**Comment by casella** [comment]
One of the oldest tickets known. I'm trying to prioritize it but it's hard.
