### ISSUE TITLE
Parameter in icons can only be displayed out of toplevel

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7493]
### Description
It's a nice feature to show the current value of parameters in the icon layer (%parameterName) but unfortunately it is not possible to show any values of subclasses or instantiated records (%instanceName.parameterName). Also tried to use brackets or other markers to identify the ending of the to be interpreted string.

### Version and OS

OpenModelica v1.18.0-dev-280-g0b76908279 (64-bit)
OMSimulator v2.1.1.post70-gdf73447-mingw
OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable: MSL 3.2.3, Bosch Rexroth Simulation Libraries (1.4)

Best wishes

Sven Bätzing

**Comment by adeas31** [comment]
Do not see any such thing in [Modelica specification](https://specification.modelica.org/master/annotations.html#text).

**Comment by adeas31** [comment]
Can you also share the example Modelica code?

**Comment by sbaetzing** [comment]
find the example attached (as txt file)

[TestParameteSubLevelrinIcon.txt](https://github.com/OpenModelica/OpenModelica/files/6553734/TestParameteSubLevelrinIcon.txt)

**Comment by adrpo** [comment]
Is very annoying that github doesn't allow .mo files to be attached. I think it also works to zip a .mo file and attach the zip.

**Comment by adeas31** [comment]
There was a minor typo in the example code. Here is the updated code,

```
package TestParameteSubLevelrinIcon
  model testmodel1
    extends testmodel2;
    parameter Real a = 1;
  
    testrecord testrecord1
      annotation (Placement(transformation(extent={{-76,26},{-56,46}})));
    annotation (Icon(coordinateSystem(preserveAspectRatio=false), graphics={Text(lineColor = {28, 108, 200}, extent = {{-48, 76}, {40, 26}}, textString = "a = %a"),
          Text(lineColor = {28, 108, 200}, extent = {{-50, 8}, {40, -46}}, textString = "b = %{b}"),
          Text(lineColor = {28, 108, 200}, extent = {{-60, -60}, {72, -90}}, textString = "c = %{testrecord1.c}")}),                    Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end testmodel1;
  
  model testmodel2
    parameter Real b = 2;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end testmodel2;
  
  record testrecord
    parameter Real c = 3;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end testrecord;
  
  
  model ClassWhereTestModelisUsed
    TestParameteSubLevelrinIcon.testmodel1 testmodel1 annotation(
      Placement(visible = true, transformation(origin = {-26, 12}, extent = {{-46, -32}, {46, 32}}, rotation = 0)));
  equation
  
  end ClassWhereTestModelisUsed;
  
end TestParameteSubLevelrinIcon;
```

**Comment by casella** [comment]
> Is very annoying that github doesn't allow .mo files to be attached. I think it also works to zip a .mo file and attach the zip.

Yeah. I see that also .c or .cpp are not considered. I guess we should just recommend using .zip files and explain this in the template ticket text.

**Comment by adeas31** [comment]
#7509 should fix the issue. Now it handle the case `%instanceName.parameterName` as well. There might be more variants of this form but since is not in the specification so the one mentioned in this issue is taken care of.
