### ISSUE TITLE
Reinstalling problem

### ISSUE THREAD

**Issue by skgoswami1** [OpenModelica/OpenModelica#7495]
I am working in Ubuntu Linux distribution. I tried to upgrade latest stable version of openmodelica. But it is always reporting received fragmented package and failing installation. Request help

**Comment by AnHeuermann** [comment]
I guess you are having the same problem as the user in this StackOverflow question:
https://stackoverflow.com/questions/66627657/openmodelica-release-in-ubuntu-20-04-focal-e-unable-to-correct-problems
See also https://trac.openmodelica.org/OpenModelica/ticket/6393.

If not please add the error message here.

**Comment by skgoswami1** [comment]
Dear Andreas,
Sorry a bit late in thanking you for the response. Before your suggestion came I reinstalled the OS and next installation of &#39;openmodelica&#39; went smooth. Yes the error was similar to the referred link but I hit that in different sequence. I am very new to openmodelica and felt that simply reinstalling will take to openmodelica 1.17 version. However after that all went awry. I removed openmodelica with &#39;apt purge&#39; command but appeared it did not clean properly. Subsequent installation command did not get success over fragmented package. If a bit of instruction is given in the user manual over changing version will help user like me. Pl. see if it can fit in your policy as appearing version change will be a regular need.
With regards
S.K.Goswami&nbsp;

**Comment by AnHeuermann** [comment]
If more people encounter this issue we can add it to the install instructions on https://www.openmodelica.org/download/download-linux.

But, if I understand you correct your issue is solved, so I'll close this for now. If you encounter the same problem again please open a new ticket about it.
