### ISSUE TITLE
OMEncrypted loads and simulate a licensed libray it even though you do not have a valid license

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7500]
### Description
It is possible to load and use in OMEncypted a licensed and encrypted library for which you do not have a license.

### Steps to Reproduce

The attached example uses a Protection Annotation with a feature "license-1" for the package "LicenseOption"
[LicenseOption.zip](https://github.com/OpenModelica/OpenModelica/files/6559794/LicenseOption.zip)

If you load the encrypted library:
(Unfortunately it is not possible to upload an encrypted library, I can send it by email)

OMEncrypted loads the libray

But the library uses a simple  license check for the SEMLA implementation in _SEMLA\src\license_managers\testingdummy\src\mlle_license_manager.c_ 
for the function:
```
int mlle_license_checkout_feature(struct mlle_license *mlic,
                              size_t feature_length,
                              const char *feature,
                              struct mlle_error **error)
{
    if (!strcmp(feature, "license-2")) {
        return 1;
    } else {
        *error = mlle_error_new(1, 3, "Feature not licensed");
        return 0;
    }
}
```
It only returns for feature "license-2" a valid license but not for the used feature "license-1"

### Expected Behavior
OMEncrypted should not load the library, and also not show the Modelica text and simulate the library.

### Screenshots

(Unfortunately it is not possible to add a picture here)

### Version and OS

 - OpenModelica Version:  v1.16.0-dev-331-g8c4285669 (64-bit) (OMEncrypted)
 - OS:  Windows 10, 64 bit
 -

### Additional Context
@sbaetzing, @RuedKamp

**Comment by casella** [comment]
@adeas31, @adrpo, I guess this should be fixed ASAP and released in 1.17.1. Can you have a look?
