### ISSUE TITLE
OMEncrypted does not release a license 

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7501]
### Description

OMEncrypted does not return a license for a library feature when the library is unloaded or when OMEdit is closed

### Steps to Reproduce

The attached example uses a Protection Annotation with a feature "license-1" for the package "LicenseOption"

[LicenseOption.zip](https://github.com/OpenModelica/OpenModelica/files/6560795/LicenseOption.zip)

If you load the encrypted library:
(Unfortunately it is not possible to upload an encrypted library, I can send it by email)
and then unload the libaray, OMEDit does not call the SEMLA function  ```mlle_license_checkin_feature``` to return the license
for feature "license-1".

### Expected Behavior

The license for feature "license-1" should be released

### Version and OS

 - OpenModelica Version: v1.16.0-dev-331-g8c4285669 (64-bit) (OMEncrypted)
 - OS:Windows 10, 64 bit

### Additional Context
@sbaetzing, @RuedKamp

**Comment by adeas31** [comment]
Is it really necessary to return the feature when the library is unloaded or OMEdit is closed? One alternative is to read the features, if everything is fine load the packages, and return the feature.

**Comment by casella** [comment]
This could be problematic if OMEdit crashes, because the library is not unloaded, and you can no longer use it. We need some mechanism to handle that.

**Comment by adeas31** [comment]
I am expecting SEMLA to handle it gracefully since if OMEdit crashes the underlying LVE(library vendor executable) will also crash.

**Comment by casella** [comment]
I guess we should check this, it is critical

**Comment by adrpo** [comment]
When OMEdit dies LVE which is another process doesn't have to die. The question is what happens if you re-run OMEdit which will run another LVE.

**Comment by adeas31** [comment]
I tested this and I confirm that when OMEdit dies the LVE also dies.

**Comment by adeas31** [comment]
@niklwors I remember you mentioned that this is not a valid problem anymore. In that case can this issue be closed?

**Comment by niklwors** [comment]
@adeas31  yes the issue can be closed.
