### ISSUE TITLE
reshuffleLoops scales very badly in one test case

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7507]
### Description

We recently reactivated reshuffleLoops in PR #7454, to solve some high-index problems that are not yet handled well by the ASSC algorithm. 

The outcome was good in general, see [regression report](https://libraries.openmodelica.org/branches/history/master/2021-05-25%2022:55:09..2021-05-26%2022:55:09.html), 

On the other hand, there is one model from [ScalableTestSuite](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) (and apparently only one), which shows a dramatic slow-down of the backend performance, which is due to the resolveLoops method scaling very badly as O(N^a) with a > 3 (!). For example, in TransmissionLineModelica_N_320 resolveLoops takes 19 s, while in TransmissionLineModelica_N_640.err it takes 271 s. What is strange is that this only happens with that specific model, I checked all other ones, and for none of the was resolveLoops scaling so badly. Including TransmissionLineEquations, which is the same system, only written directly through equations, without the use of connectors and components. Karim, it would be interesting to figure out why, so we could have some fail-safe mechanism that prevents OMC getting stuck forever on this method, which is probably not necessary at all to successfully simulate that model.

### Steps to Reproduce

Run the TransmissionLineModelica_N_640 from ScalableTestSuite.

### Expected Behavior

The resolveLoops function should time out much earlier that it does now. After all, this test case needs no reshuffling to work properly.

**Comment by casella** [comment]
@kabdelhak, while doing testing on benchmarks for our high-performance LLVM compiler, we stumbled upon another case where resolveLoops scales badly, in this case as O(N^2). With system sizes below 10k equations it doesn't even register, but as you go above 40k equations (which is not too big, yet), it just blows up and becomes the major bottleneck for compilation, particularly because of humongous memory usage.

Of course if you know how to use `-d=execstat` you can figure that out and turn it off, since it is not needed. But that's pretty advanced stuff, and it's not really explained anywhere.

Do you think you could easily set up something like a counter that aborts the method when it goes above a certain threshold of iterations, or time spent, or something?  We can use the ScalableTestSuite example to tune the default value for that, and then I can double-check on our benchmark.

**Comment by kabdelhak** [comment]
I will try to have a look at this in the next weeks. I am not really sure what could actually iterate for that long.

**Comment by hkiel** [comment]
I fixed the issue in #8680. Benchmark is fine again.

I think that someone (@kabdelhak ?) should have a look at the code again. `ResolveLoops.removeEqualPaths()` seems to be there to remove candidates, but instead it spawned duplicates of them. I suppressed the generation of duplicates with my fix, but it should be checked that the function indeed can "remove equal paths".

**Comment by casella** [comment]
> I fixed the issue in #8680. Benchmark is fine again.

Let's see when we get the results on the [test suite report](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html), the one I see now was run before #8680 was merged in.

If the test suite report shows good scaling tomorrow, we can close this ticket.

> I think that someone (@kabdelhak ?) should have a look at the code again. `ResolveLoops.removeEqualPaths()` seems to be there to remove candidates, but instead it spawned duplicates of them. I suppressed the generation of duplicates with my fix, but it should be checked that the function indeed can "remove equal paths".

@hkiel would you mind opening a separate issue describing this last problem? I understand there's some description of it in #8680, but that's closed now, so it's not the proper place for that. Thanks!

**Comment by hkiel** [comment]
@casella The last run of the test suite was on 2022-03-15. Does it need to be started by hand?

**Comment by casella** [comment]
No, it runs daily, see the [job report](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/).

@sjoelund, @adrpo, it looks like there is something wrong with the reporting, the test on master has run several times since Mar 15. Can you please check?
