### ISSUE TITLE
User's guide issuing warning with MSL 4.0.0

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7522]
### Description

The user's guide has some problems with MSL 4.0.0 and the examples are broken, see https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/introduction.html

```
Warning
Warning: dcmotor requested package Modelica of version 3.2.2. Modelica 4.0.0 is used instead which states that it is only compatible with a conversion script. OpenModelica currently does not support conversion scripts and will proceed with potential issues as a result.
```

**Comment by casella** [comment]
@adrpo, who can take care of this?

**Comment by AnHeuermann** [comment]
I'll change it to load MSL 3.2.3 explicitly. I'll fix it for https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/omnotebook.html as well.

**Comment by casella** [comment]
Thanks!
