### ISSUE TITLE
Allow selection of static or dynamic linking of simulation executable in OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7534]
### Description

In 1.17.0, we introduced dynamic linking of simulation executables under Windows, to reduce the overall time spent from clicking the Simulate button to getting the simulation results. This time was substantially reduced, but some users are reporting DLL hell issue, see e.g. #7525

Although keeping dynamic linking as default makes sense for most users, we should ad an option in OMEdit to allow getting back to static linking, if one wants to have a standalone .exe file for some reason.

**Comment by adrpo** [comment]
@casella we can do this via:
1) a new parameter in `buildModel|translateModel(..., linkType="static|dynamic")`
2) a command line config flag `--linkType="static|dynamic"`
which one would be preferable?

The second one doesn't need to be set for each model. 
The first one can have a default to "dynamic" and if you want "static" is an explicit user choice which does not remain for the next model. Myself I prefer this one.

**Comment by sjoelund** [comment]
I think a command-line flag would be preferable. However, there is no static linking on Linux/MacOS, so it might be a bit weird that it does nothing...

**Comment by adeas31** [comment]
The second one has advantage in the case of #7525. Think of a user who always want to use static linking. For such user first option will be annoying to set for each model every time.

**Comment by adeas31** [comment]
> I think a command-line flag would be preferable. However, there is no static linking on Linux/MacOS, so it might be a bit weird that it does nothing...

We only do it for Windows. I can also make it in OMEdit to only show controls when is running on Windows.

**Comment by sjoelund** [comment]
> We only do it for Windows. I can also make it in OMEdit to only show controls when is running on Windows.

But if you want to hide the flag from `omc --help`, it would need to be an internal flag. But why would we hide such a flag from the documentation, etc?

**Comment by casella** [comment]
I don't think it is a problem if some flags don't have any effect on some OSs. Maybe we should issue a warning if an option which is not available on the local OS is selected.

The command line flag has the advantage that it can be set in a vendor-specific annotation, similarly to other ones affecting compilation like "-O0".

**Comment by casella** [comment]
As the comments in #7594 point out, there are some users (e.g. at EDF) that use the generated .exe outside OMEdit, possibly on a different computer. For portability, statically linked simulation executables are of course a lot better.

@felixmarsollier2 is still using 1.16.5 because of that, as with the case of ABB we should avoid at all cost having users stuck to old OMC versions because of this kind of issues. It would be really bad if he could not use 1.18.0, nor the forthcoming 1.19.0-dev nightly builds.

I would recommend to implement the command-line feature in 1.18.0. This is a special feature that is only useful in a small number of cases, so having to set it in each and every model is not a big deal - one would just set it as default in Tools|Options, and get that automatically in all models.

@adeas31, @adrpo, can we fit this in 1.18.0? This issue is actually a regression for people like @felixmarsollier2

**Comment by adrpo** [comment]
Should be fixed with PR #7618, @adeas31 you can push to this PR if you want to make a new Qt dialog for this setting, or you can make a new one. Your choice.

**Comment by casella** [comment]
@felix-marsollier2, please try the new nightly build, you should now be able to get a statically linked .exe simulation file and use it anywhere.

**Comment by felix-marsollier2** [comment]
Hi  Everyone,

I tried with the version v1.18.0-dev-386-g13ce53237a, it seems that the flag do not generate error but the exe is still no longer portable. There are messages regarding missing DLL. Maybe I did something wrong during my process.

**Comment by adeas31** [comment]
Is it for some specific Modelica model? Which dll is missing?

**Comment by casella** [comment]
Can you please post the missing DLL error in its entirety? Maybe something was forgotten in the static linking process.

**Comment by adrpo** [comment]
I will check it again, maybe I missed something.

**Comment by felix-marsollier2** [comment]
> 
>
> Is it for some specific Modelica model? 
I have tried with the model "TwoMasses" from Modelica.Thermal.HeatTransfer.Examples package (MSL3.2.3 but I think has no importance).

Before that, to select static linking, I went to Tools -> Options -> Simulation then I added in the Additional Translation Flags: --linkType=static
I restarted OMEdit to be sure that the flag is catched and stored. I ran the model that has generated the output files in the temporary folder. Then I copy pasted from the temporary folder either the folder or the exe itself to an other directory. I ran again the exe and the following errors were raised.

>Which dll is missing?
Missing libsundials_kindsol.dll on my computer
Missing libsundials_idas.dll on my computer
Missing libsundials_cvode.dll on my computer
Missing libsundials_nvecserial.dll on my computer

What is strange is that I used the dassl solver where here, the error messages seem like refering to unused solvers

**Comment by felix-marsollier2** [comment]
Moreover when I run again the exe from the temporary folder, the same messages of missings dll appear.

**Comment by sjoelund** [comment]
> What is strange is that I used the dassl solver where here, the error messages seem like refering to unused solvers

All solvers are linked to the simulation executable. You can select solver as a command-line argument.

**Comment by adeas31** [comment]
That is not how you use it from OMEdit.
Go to `Tools->Options->Simulation` and check `Use static linking` checkbox. Remove `--linkType=static` from `Additional Translation Flags`.

**Comment by felix-marsollier2** [comment]
> 
> 
> That is not how you use it from OMEdit.
> Go to `Tools->Options->Simulation` and check `Use static linking` checkbox. Remove `--linkType=static` from `Additional Translation Flags`.

That has worked well. Thanks again

**Comment by casella** [comment]
@adeas31, for the record, why isn't --linkType=static enough to get rid of all DLL dependencies?

**Comment by casella** [comment]
I just opened #7659 to improve the documentation of the flag. I also noticed a problem with the documentation formatting, so I opened #7661 about it.

**Comment by adeas31** [comment]
> @adeas31, for the record, why isn't --linkType=static enough to get rid of all DLL dependencies?

It should be enough if `OMEdit` uses the compile process as `omc` does. `OMEdit` compiles the model by directly calling the compilation script and then passes the link type value based on the checkbox i.e., static or dynamic. So even if we set `--linkType=static`, it will be overwritten.

**Comment by casella** [comment]
OK, so the `--linkType` flag would work fine if I set it with the API function `setCommandLineOptions()` in a` .mos` script?

**Comment by adrpo** [comment]
Yes, if you then call simulate or buildModel.
