### ISSUE TITLE
Cpp runtime handles array constructor incorrectly

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#7535]
The Cpp runtime generates invalid code for a model such as this:
```Modelica
function f
  input Real x1;
  input Real x2;
  output Real y[2];
algorithm
  y := cos({x1, x2});
end f;

model M
  Real x[:] = f(time, time);
end M;
```
where the model flattens to:
```Modelica
function f
  input Real x1;
  input Real x2;
  output Real[2] y;
algorithm
  y := array(cos({x1, x2}[$i1]) for $i1 in 1:2);
end f;
```
For the `cos({x1, x2}[$i1]` expression it generates a switch that uses an undeclared variable called `_omcQ_24i1_`, but the rest of the code for the array constructor calls the iterator `$i1_loopVar` instead.

The `cos` call should really be flattened by the frontend to `{cos(x1), cos(x2)}` rather than an array constructor in this case, but it's not always possible to avoid generating an array constructor (for example if the dimension of the argument wasn't known) so this should be handled by the code generation regardless.

**Comment by perost** [comment]
I forgot to mention that this affects the PowerSystems library, for example `PowerSystems.Examples.AC3ph.Elementary.Source`.

**Comment by rfranke** [comment]
`System.unquoteIdentifier(name)` translates `$i1` to `_omcQ_24i1_`. This needs to be fixed in two files: CodegenCppCommonOld.tpl and CodegenCppCommon.tpl, see below.

This was the simple part of the fix. But how to create a pull request and get it merged after having followed the instructions in README.Linux.md to build OpenModelica?

```diff
-------------- OMCompiler/Compiler/Template/CodegenCppCommon.tpl --------------
index 5fbe0b8d92..608c180969 100644
@@ -176,7 +176,7 @@ end contextFunName;
 template contextIteratorName(Ident name, Context context)
   "Generates code for an iterator variable."
 ::=
-  name + "_"
+  System.unquoteIdentifier(name) + "_"
 end contextIteratorName;
 
 template crefWithIndex(ComponentRef cr, Context context, Text &varDecls, SimCode simCode, Text& extraFuncs, Text& extraFuncsDecl,

------------- OMCompiler/Compiler/Template/CodegenCppCommonOld.tpl -------------
index fe4d489dfb..53c461e343 100644
@@ -176,7 +176,7 @@ end contextFunName;
 template contextIteratorName(Ident name, Context context)
   "Generates code for an iterator variable."
 ::=
-  name + "_"
+  System.unquoteIdentifier(name) + "_"
 end contextIteratorName;
 
 template crefWithIndex(ComponentRef cr, Context context, Text &varDecls, SimCode simCode, Text& extraFuncs, Text& extraFuncsDecl,
```

**Comment by perost** [comment]
> This was the simple part of the fix. But how to create a pull request and get it merged after having followed the instructions in README.Linux.md to build OpenModelica?

See [how to contribute](https://github.com/OpenModelica/OpenModelica/blob/master/CONTRIBUTING.md). Basically fork the project, push a commit to your fork, then make a pull request.

**Comment by rfranke** [comment]
OK, I made an additional fork to create a pull request.

**Comment by casella** [comment]
@rfranke, this fix is currently on master, so it will get into 1.18.0. If you want it to be in the 1.17.1 release, it needs to be ported to the [maintenance/v1.17](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.17) branch.

Can you please take care of that? Once it's merged in, you can change the milestone again for the record.

Thanks!
