### ISSUE TITLE
Presence of "closure" annotation causes icons to not be rendered

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#7544]
### Description

When one uses graphics where the `closure` annotation is used then OMEdit will simply not display **all** of the icon. I.e., it does not render anything and not just not the object that uses `closure`

### Steps to Reproduce

See the attached test package
[TestAnnoations.mo.zip](https://github.com/OpenModelica/OpenModelica/files/6636275/TestAnnoations.mo.zip) where there are three variants of the same two objects with just using different closure types.

### Expected Behavior

All Icons should be displayed and if there is no support for `closure` yet then at least the fall-back to no closure present should be implemented displaying the icon as if `closure` was not present as a work around.

### Version and OS

- OMEdit OpenModelica Connection Editor Connected to OpenModelica 1.18.0~dev-311-ge3219aa
 - OS: Ubuntu 20.04

**Comment by adeas31** [comment]
See #6739 and #6110

**Comment by adeas31** [comment]
See also #6357
