### ISSUE TITLE
Resizing an object in OMedit will cause broken-number coordinates

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#7545]
### Description

In OMEdit when drawing an object (tested with rectangular) it is generated with correct integer coordinates only. **But** when one then tries to resize the object broken number coordinates are generated which then make it impossible to properly align a resized object to the grid or other objects. 

### Steps to Reproduce

![2021-06-11_OMEditAnnotationCoordinates](https://user-images.githubusercontent.com/9332/121642618-0d787980-ca91-11eb-80c5-18598c2baf22.gif)

### Expected Behavior

When resizing only integer coordinates (at least for the corner points) should be generated.

### Version and OS

 - OMEdit Connected to OpenModelica 1.18.0~dev-311-ge3219aa

**Comment by casella** [comment]
@adeas31, I think this is quite important. I'm not sure there is enough time to fix this in 1.18.0, what do you think?

**Comment by dietmarw** [comment]
Thanks for the quick turn around, I can confirm it is fixed now :-) 
One side-remark. Does it really make sense to display the coordinates with 2 significant digits. I would even say they should simply be displayed as integers. Just avoids problems by not encouraging to set non-integer coordinates.
