### ISSUE TITLE
Export of clocked FMUs broken

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7548]
The commit "do not export clocks in typeDefinitions in modelDescription.xml" cf81f24a449fcc811a02710180a65bcf146e819d
breaks the export of clocked FMUs. This breaks all of our applications of OpenModelica.

Please re-introduce!

**Comment by arun3688** [comment]
@rfranke the reason for removing clocks in typeDefinitions in modelDescription.xml is due to this ticket https://trac.openmodelica.org/OpenModelica/ticket/6371. According to FMI-2.0 specification clocks should not be part of  either `Scalar Variable ` or `typeDefinitions`

**Comment by rfranke** [comment]
Yes, clocks didn't make it into FMI 2.0 anymore. The discussions about their introduction took about 10 years -- way too long for an industrial application. The implementation in OpenModelica goes back to the standardization effort in 2016/2017 with implementations in Dymola and OpenModelica.
If this causes problems with a checker, then they could be disabled with a `strict` option -- or enabled with a `clocks` option, but not removed.

**Comment by arun3688** [comment]
@yes it broke couple of tests in cppruntime, https://github.com/OpenModelica/OpenModelica/pull/7139/files?file-filters%5B%5D=

**Comment by rfranke** [comment]
Works nicely. Thank you!
