### ISSUE TITLE
Cpp compilation of models with tables fails with MSL 4.0

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7549]
See e.g. `Modelica.Clocked.Examples.Elementary.BooleanSignals.BackSample` (and many more in Modelica and ModelicaTest).

This is caused by missing `const` qualifiers for pointers passed as input to `ModelicaStandardTables`, e.g. `table` and `columns` in:
```
MODELICA_EXPORT void* ModelicaStandardTables_CombiTimeTable_init(_In_z_ const char* tableName,
                                                 _In_z_ const char* fileName,
                                                 _In_ double* table, size_t nRow,
                                                 size_t nColumn,
                                                 double startTime,
                                                 _In_ int* columns,
                                                 size_t nCols, int smoothness,
                                                 int extrapolation) MODELICA_NONNULLATTR;
```

Why does it work for MSL 3.2.3 -- the tables code doesn't seem to have changed ?!

**Comment by rfranke** [comment]
I opened an issue for MSL: https://github.com/modelica/ModelicaStandardLibrary/issues/3839

**Comment by adrpo** [comment]
@sjoelund has patched our lib (via removal of Include annotation) and now it works:
https://libraries.openmodelica.org/branches/history/master/2021-06-18%2023:24:56..2021-06-21%2010:10:23.html

**Comment by rfranke** [comment]
"That’s one small step for a man, ... "

**Comment by rfranke** [comment]
A couple of more examples from MSL 4 fail:
Many Noise examples, e.g. `Modelica.Blocks.Examples.Noise.ActuatorWithNoise`
    (ModelicaRandom.h included from Modelica/Math/Random.mo)
FFT examples, e.g. `Modelica.Math.FastFourierTransform.Examples.RealFFT1`
    (ModelicaFFT.h included from Modelica/Math/FastFourierTransform.mo)

Can you remove those Includes as well?

**Comment by rfranke** [comment]
Today's nightly library coverage looks good in this regard. Thank you for the patches!
