### ISSUE TITLE
OpenModelica -cpu flag does not work for 1.18.0~dev-320-g1a21771-1

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#7551]
Checking the -cpu box with OMEdit 1.18.0~dev-320-g1a21771-1 in the `Simulation Setup -> Simulation Flags` window does not generate $cpu output.  The -cpu option works fine in version 1.17.

**Comment by casella** [comment]
@adeas31, can you have a quick look? We should try to avoid regressions in the new release. Thanks!

**Comment by adeas31** [comment]
I am guessing this is because we recently changed to read the result variables from `model_init.xml` file instead of the `model_res.mat` file. @kabdelhak or @AnHeuermann does anyone of you can have a look at it? Just add the `$cpu` variable in the `model_init.xml` file when `-cpu` flag is set.

**Comment by sjoelund** [comment]
We don't know if the `-cpu` flag will be set or not when generating the `_init.xml`. You know in OMEdit if you passed that flag or not.

**Comment by adeas31** [comment]
So then is probably just to generate a new node when `-cpu` is set. I will take care of it then.
