### ISSUE TITLE
spatialDistribution fails with "I don't think this case can happen"

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OpenModelica#7575]
https://libraries.openmodelica.org/branches/master/ThermofluidStream_OM_adaptions/files/ThermofluidStream_OM_adaptions_ThermofluidStream.Undirected.Processes.Tests.TransportDelay.sim

```
Regular simulation: ./ThermofluidStream_OM_adaptions_ThermofluidStream.Undirected.Processes.Tests.TransportDelay -abortSlowSimulation -alarm=480 -lv LOG_STATS
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
stdout            | error   | I don't think this case can happen, but we will see...!
```

**Comment by AnHeuermann** [comment]
And I was so hopeful that this would indeed never happen...

How do I get the library `ThermofluidStream_OM_adaptions`? I can't find it with the package manager and it is not installed with `make omlibrary-all`. Or do I have the wrong name?
