### ISSUE TITLE
C++ backend fails for matrix multiplication

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OpenModelica#7582]
[valgrind.txt](https://github.com/OpenModelica/OpenModelica/files/6685224/valgrind.txt) - Modelica.Mechanics.MultiBody.Examples.Rotational3DEffects.MovingActuatedDrive (there are several models that seem to fail due to the same issue)

It seems multiply_array allocates based on the left array's size. But the input is a 3x1 multiplied by a 1x3 matrix and the output should be a vector with dimensions 1. I suppose the old frontend simplified this in some way that the C++ code generation could handle and this case never appeared. I cannot figure out how to resolve this as the function performs too many different kinds of operations at once.

**Comment by rfranke** [comment]
Thank you for pointing this out. I have a backlog of a couple of fixes / adaptations to the new frontend, waiting for Merge most of the time (#7580 at the moment), in order to become able to make further changes.

**Comment by rfranke** [comment]
#7588 should fix this. It's not easy to formulate something in Modelica that is not pre-evaluated and results in such simulation code :)
```
rotor1D.rotorWith3DEffects.cylinder.R.w[3] = ((promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 1] + rotor1D.rotorWith3DEffects.e[2] * sin(rotor1D.phi) - (promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 1] * cos(rotor1D.phi)) * rotor1D.rotorWith3DEffects.w_a[1] + ((promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 2] + (-(promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 2]) * cos(rotor1D.phi) - rotor1D.rotorWith3DEffects.e[1] * sin(rotor1D.phi)) * rotor1D.rotorWith3DEffects.w_a[2] + ((promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 3] + (1.0 - (promote(rotor1D.rotorWith3DEffects.e, 2) * transpose(promote(rotor1D.rotorWith3DEffects.e, 2)))[3, 3]) * cos(rotor1D.phi)) * rotor1D.rotorWith3DEffects.w_a[3]
```

**Comment by rfranke** [comment]
Moving discussion from PR to the issue. Below is the summary of the new valgrind file. Can you please rerun with `-s` as proposed?
```
==261447== HEAP SUMMARY:
==261447==     in use at exit: 20,607 bytes in 62 blocks
==261447==   total heap usage: 2,388,840 allocs, 2,388,778 frees, 83,952,621 bytes allocated
==261447== 
==261447== LEAK SUMMARY:
==261447==    definitely lost: 0 bytes in 0 blocks
==261447==    indirectly lost: 0 bytes in 0 blocks
==261447==      possibly lost: 0 bytes in 0 blocks
==261447==    still reachable: 20,607 bytes in 62 blocks
==261447==         suppressed: 0 bytes in 0 blocks
==261447== Rerun with --leak-check=full to see details of leaked memory
==261447== 
==261447== For lists of detected and suppressed errors, rerun with: -s
==261447== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 4 from 2)
```

**Comment by sjoelund** [comment]
[valgrind.txt](https://github.com/OpenModelica/OpenModelica/files/6686965/valgrind.txt)
