### ISSUE TITLE
Static link with clang and CPP runtime should not have any dll dependencies

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#7583]
### Description

See #7579 

### Steps to Reproduce

Build an FMU with the Cpp runtime on Windows using the clang compiler.

### Expected Behavior

Should link the dll without any dependencies.

### Version and OS

 - OS: Windows 10, 64 bit

**Comment by rfranke** [comment]
Today's nightly build still fails for any model (32bit, Target/Compiler options: Cpp, MinGW, gcc, g++). clang cannot be selected. This is new since 1-2 weeks:
```
g++ -fopenmp=libomp  -Winvalid-pch -O0 -DNDEBUG  -std=c++11 -DBOOST_ALL_DYN_LINK   -DUSE_DGESV -DUSE_LOGGER -DOMC_BUILD -DUSE_THREAD -DSUNDIALS_MAJOR_VERSION=5 -DSUNDIALS_MINOR_VERSION=4 -DPMC_USE_SUNDIALS -I"." -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/" -I.  -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/3rdParty/boost/gcc/" -I"." -I"C:\PROGRA~2\OPENMO~1.0-D/include/omc/cpp/sundials"     -DMEASURETIME_PROFILEBLOCKS -DUSE_LOGGER  -c -o OMCppPID_ControllerCalcHelperMain.o OMCppPID_ControllerCalcHelperMain.cpp
g++.exe: error: unrecognized command-line option '-fopenmp=libomp'; did you mean '-fopenmp-simd'?
mingw32-make: *** [<builtin>: OMCppPID_ControllerCalcHelperMain.o] Error 1
```
Any idea?

**Comment by rfranke** [comment]
Now I get it: clang can still be selected -- it just doesn't appear in the drop down menu; selecting the empty entry results in clang. Then the simulation works as before (1-2 weeks ago I had configured gcc für FMU export due to the link dependencies with clang).

**Comment by rfranke** [comment]
I just added these two lines for the current nightly build under Windows, i.e. copied two gcc lines for clang:
```
  else ifeq ($(findstring clang,$(CC)),clang)
    $(eval LIBS=$(LIBS) $(if $(findstring linux,$(PLATFORM)),-static-libstdc++ -static-libgcc,-static))
```
Then it works (and it should not break anything for gcc). Don't know if `-static-libstdc++ -static-libgcc` are the right options for clang under Linux though.

**Comment by adrpo** [comment]
I have tried those on my WSL and they work. 
The #7589 is not yet merged as some tests fail, so the new nightly doesn't have this fix yet.
