### ISSUE TITLE
Infinity norm of a vector

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7586]
The example [Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot](https://libraries.openmodelica.org/branches/master/Modelica_3.2.3_cpp/files/Modelica_3.2.3_cpp_Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot.err) fails with the Cpp runtime as abs(array) is not yet implemented, see `OMCppModelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobotInitialize.cpp` attempting to call `std::abs` for an array:
```
/*
equation index: 462
type: SIMPLE_ASSIGN
pathPlanning.path.sd_max_inv = max(abs(pathPlanning.path.aux1))
*/
void fullRobotInitialize::initEquation_462()
{
  double tmp162;
  tmp162 = min_max<double>(std::abs(_pathPlanning_P_path_P_aux1_)).second;
  SystemDefaultImplementation::setRealStartValue(_pathPlanning_P_path_P_sd_max_inv_, tmp162, false);
}
```
Interestingly the C runtime does neither support abs(array). Just the simulation code looks different for the C runtime, see `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot_06inz.c`:
```
/*
equation index: 462
type: SIMPLE_ASSIGN
pathPlanning.path.sd_max_inv = max({abs(pathPlanning.path.aux1[1]), abs(pathPlanning.path.aux1[2]), abs(pathPlanning.path.aux1[3]), abs(pathPlanning.path.aux1[4]), abs(pathPlanning.path.aux1[5]), abs(pathPlanning.path.aux1[6])})
*/
```
Why does OpenModelica generate different simulation code for the C runtime?

Don't get me wrong. I like the more extensive use of arrays and complex types with the new frontend. Just a question.

**Comment by perost** [comment]
The new frontend generates the flat equation:
```Modelica
pathPlanning.path.sd_max_inv = max(array(abs(pathPlanning.path.aux1[$i1]) for $i1 in 1:6));
```
In the SimCode this has been turned into (regardless of which simCodeTarget is used):
```Modelica
2929: pathPlanning.path.sd_max_inv=max({abs(pathPlanning.path.aux1[1]), abs(pathPlanning.path.aux1[2]), abs(pathPlanning.path.aux1[3]), abs(pathPlanning.path.aux1[4]), abs(pathPlanning.path.aux1[5]), abs(pathPlanning.path.aux1[6])}) [Real]
```
So it looks like something after SimCode changes it back to just `abs(pathPlanning.path.aux1)` again when using the Cpp code generation.

**Comment by rfranke** [comment]
This might go back to a change once introduced by @sjoelund as I was complaining about array flattening ... ok, will implement abs_array then ...

**Comment by sjoelund** [comment]
I don't think you should have an abs(array) - there is no such function in Modelica. It would be best to figure out which code changes it back to abs(arrayVariable). It should probably be some Cpp-specific transformation since it's not done for C...

**Comment by sjoelund** [comment]
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo#L905 - if I make it fail for Cpp there, the generated code is fine. I guess that code assumes there is an array implementation for each and every operator in the Cpp runtime... Might have been safer with a list of working implementations. But then you know where to fix it if you don't want to support that everywhere.

**Comment by casella** [comment]
> I don't think you should have an abs(array) - there is no such function in Modelica.

Of course there is, see [Section 3.7.1](https://specification.modelica.org/maint/3.5/operators-and-expressions.html#numeric-functions-and-conversion-functions). 

`abs(v)` should be vectorized in the [usual way](https://specification.modelica.org/maint/3.5/functions.html#scalar-functions-applied-to-array-arguments). Of course, this means that `abs(v)` is not the infinity norm, but just an array with the absolute values of `v`.

Do I miss something?

**Comment by sjoelund** [comment]
> > I don't think you should have an abs(array) - there is no such function in Modelica.
> 
> Of course there is, see [Section 3.7.1](https://specification.modelica.org/maint/3.5/operators-and-expressions.html#numeric-functions-and-conversion-functions).
> 
> `abs(v)` should be vectorized in the [usual way](https://specification.modelica.org/maint/3.5/functions.html#scalar-functions-applied-to-array-arguments). Of course, this means that `abs(v)` is not the infinity norm, but just an array with the absolute values of `v`.
> 
> Do I miss something?

The runtime is C/C++ and not vectorized. Flat Modelica does not have vectorization because the rules for that are pretty complicated as well. But as you could see in https://github.com/OpenModelica/OpenModelica/issues/7586#issuecomment-865199451 it seems the C++ runtime does this at runtime anyway. This is quite unexpected and means the functions need to be a lot more complicated than necessary for probably low gains (there is no magic you can perform to apply abs to an array faster).

**Comment by rfranke** [comment]
Ideally the backend should keep the `for` expression generated by the new frontend. The expansion of arrays is bad for code size and compilation speed. Large arrays easily break limits of available computing resources.

**Comment by sjoelund** [comment]
> Ideally the backend should keep the `for` expression generated by the new frontend. The expansion of arrays is bad for code size and compilation speed / memory needs. Large arrays easily break limits of available computing resources.

I could disable that expansion for Cpp if you want. It's around https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/BackEnd/BackendDAETransform.mo#L905 and I think I know what to remove...

**Comment by sjoelund** [comment]
> Ideally the backend should keep the `for` expression generated by the new frontend. The expansion of arrays is bad for code size and compilation speed / memory needs. Large arrays easily break limits of available computing resources.

Ideally then the expression would not be:
```mo
max(array(abs(pathPlanning.path.aux1[$i1]) for $i1 in 1:6));
```
But simplified into:
```mo
max(abs(pathPlanning.path.aux1[$i1]) for $i1 in 1:6);
```
