### ISSUE TITLE
Do not consider case of partial text when offering hints

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7593]
### Description

A useful characteristic of OMEdit is the hints we get when we write code.
For instance, consider writing a Unit of Measure. There are so many of them in MSL that having help in finding the correct one is a boon. 
However, to have a hint one should write the first part of what they are looking for case sensitive, 
This is not optimal for two reasons:
1. when we look for something maybe we don't know exactly if the part of the name we remember is uppercase or lowercase or whatever. 
2. Writing all lowercase is faster, and programmers prefer to use it even though they know the correct case.

For instance if I look for "angular" quantities, when I write
`Modelica.SIunits.ang
`
I don't get any hint, while if I write 
`Modelica.SIunits.Ang
`I get hints. 

Other tools, such as Qt Creator, give code hints in the way I propose for OpenModelica (i.e. nont considering the case of what one writes).
Obviously, if my proposal is agreed upon, making the correction would involve a minimal effort (possibly changing a single row of code).

### Expected Behavior
Code should be hinted based on what the user writes, no matter the case of the letters

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@adeas31, could this be a one-liner modification, as @ceraolo suggests?

**Comment by casella** [comment]
Thanks Adeel, highly appreciated!

**Comment by max-privato** [comment]
Thank you!
By the way, I made a mistake: the fix involved two lines instead of one  :-)
Thanks again also for the speed.
