### ISSUE TITLE
Coverage of PowerSystems library broke down for any runtime and any lib version

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7596]
The number of compiled models went down from 95 yesterday to 57 today for any runtime and any library version!
Which commit can that be?

**Comment by rfranke** [comment]
Most likely the commits by @mahge yesterday afternoon.

**Comment by casella** [comment]
@rfranke, I understand this is the relevant [regression report](https://libraries.openmodelica.org/branches/history/master/2021-06-21%2013:25:14..2021-06-21%2023:30:45.html). There are commits by you, @mahge, and @adeas31. No commit from @sjoelund.

I guess @adeas31's commits are irrelevant, as they concern OMEdit. So it's you and Mahder.

@mahge, would you mind trying out on your local branch some of the PowerSystems models that got broken, before and after your commits?

**Comment by rfranke** [comment]
Fortunately the previous library test had been started yesterday at noon. So, it must have happened in the afternoon. My commits only affect the Cpp runtime, but the C runtime faces the same regression problems. This is why I assume that the changes authored by @mahge and committed by @sjoelund are causing this.

**Comment by casella** [comment]
> Fortunately the previous library test had been started yesterday at noon. So, it must have happened in the afternoon. My commits only affect the Cpp runtime, but the C runtime faces the same regression problems. 

You are right, I overlooked that. Then, it's most likely some issue with @mahge's commit.

**Comment by mahge** [comment]
My previous changes caused this regression indeed. It has now been fixed in #7606. Here is today's [regression report](https://libraries.openmodelica.org/branches/history/master/2021-06-23%2011:57:35..2021-06-23%2023:19:13.html)

Check and if everything looks good we can close this now.

**Comment by rfranke** [comment]
Thank you! Looks good again.

**Comment by casella** [comment]
@rfranke, any other pending issues for you before we branch off 1.18.0?
