### ISSUE TITLE
Run-time license text inconsistent with the OSMC bylaws

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#7612]
### Description

I noticed that the license header of (some/many) files in the run-time system is not consistent with the license text from the [OSMC bylaws](https://www.openmodelica.org/images/docs/OpenSourceModelicaConsortium-bylaws-191203-v24.pdf) from https://www.openmodelica.org/home/consortium.

One randomly chosen example is [here](https://github.com/OpenModelica/OpenModelica/blob/81066b9ee3f51c11336db4569e6f5e16fe9a4126/OMCompiler/SimulationRuntime/c/omc_inline.h):

```
 * Copyright (c) 1998-CurrentYear, Open Source Modelica Consortium (OSMC),
 * c/o Linköpings universitet, Department of Computer and Information Science,
 * SE-58183 Linköping, Sweden.
 *
 * All rights reserved.
 *
 * THIS PROGRAM IS PROVIDED UNDER THE TERMS OF THE BSD NEW LICENSE OR THE
 * GPL VERSION 3 LICENSE OR THE OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.2.
 * ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES
 * RECIPIENT'S ACCEPTANCE OF THE OSMC PUBLIC LICENSE OR THE GPL VERSION 3,
 * ACCORDING TO RECIPIENTS CHOICE.
 *
 * The OpenModelica software and the OSMC (Open Source Modelica Consortium)
 * Public License (OSMC-PL) are obtained from OSMC, either from the above
 * address, from the URLs: http://www.openmodelica.org or
 * http://www.ida.liu.se/projects/OpenModelica, and in the OpenModelica
 * distribution. GNU version 3 is obtained from:
 * http://www.gnu.org/copyleft/gpl.html. The New BSD License is obtained from:
 * http://www.opensource.org/licenses/BSD-3-Clause.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, EXCEPT AS
 * EXPRESSLY SET FORTH IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE
 * CONDITIONS OF OSMC-PL.
 ```

In the all-caps paragraph, notice how it provides the program under BSD New/GPLv3/OSMC-PL 1.2, but to use etc, you have to accept OSMC-PL or GPL, no mention of BSD New! 
This is weirdly inconsistent, especially as the BSD is mentioned again further down. 
Btw, this same error is present in the OSMC runtime license text [linked from the OM homepage](https://openmodelica.org/osmc-pl/osmc-pl-1.2-runtime.txt).

### Expected Behavior

Now, I thought I'd check the ground truth in the latest [OSMC bylaws](https://www.openmodelica.org/images/docs/OpenSourceModelicaConsortium-bylaws-191203-v24.pdf) I could find (from the consortium page linked above), and sure enough, Appendix D on p 29 makes more sense to me:

```
Copyright (c) 1998-CurrentYear, Open Source Modelica Consortium (OSMC),
c/o Linköpings universitet, Department of Computer and Information Science,
SE-58183 Linköping, Sweden. 

All rights reserved.

THIS PROGRAM IS PROVIDED UNDER THE TERMS OF THE BSD NEW LICENSE OR THE 
GPL VERSION 3 LICENSE OR THE OSMC PUBLIC LICENSE (OSMC-PL) VERSION 1.2. 
ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS PROGRAM CONSTITUTES 
RECIPIENT'S ACCEPTANCE OF THE BSD NEW LICENSE OR THE OSMC PUBLIC LICENSE OR THE GPL VERSION 3, 
ACCORDING TO RECIPIENTS CHOICE.

The OpenModelica software and the OSMC (Open Source Modelica Consortium) 
Public License (OSMC-PL) are obtained from OSMC, either from the above 
address, from the URLs: http://www.openmodelica.org or 
http://www.ida.liu.se/projects/OpenModelica, and in the OpenModelica 
distribution. GNU version 3 is obtained from: 
http://www.gnu.org/copyleft/gpl.html, The BSD NEW License is obtained from: 
http://www.opensource.org/licenses/BSD-3-Clause.

This program is distributed WITHOUT ANY WARRANTY; without even the implied 
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, EXCEPT AS 
EXPRESSLY SET FORTH IN THE BY RECIPIENT SELECTED SUBSIDIARY LICENSE 
CONDITIONS OF OSMC-PL.
```
Here, the same three licenses are listed in the "provided under" and "recipient's acceptance" parts.

I think this is probably a copy-paste problem of an outdated license (cf. 863ecbb33d42adaa6e99a13c6b7930c0ec0566d4), and I think it is important to update the affected files quickly so that the license situation is clear and consistent.

P.S.: The bylaws also mention that 
> The line: **“This file belongs to the OpenModelica Run-Time System”** together with the above OpenModelica Run-time System Public License text should be placed at the top of all OpenModelica source files belonging to the OpenModelica Run-Time System.

which (emphasis mine) I found also to not be the case at least for some spot-checks.

**Comment by bilderbuchi** [comment]
According to #5154 ([link with description](https://trac.openmodelica.org/OpenModelica/ticket/5154)), this license also ends up in FMI files.

**Comment by bilderbuchi** [comment]
Is there any other information you need to triage this issue?

**Comment by casella** [comment]
Sorry, been away for holidays for a while

**Comment by bilderbuchi** [comment]
No need to say sorry! It's summer time after all! 😃

**Comment by sjoelund** [comment]
I cannot remember who was assigned to updating the license headers of all files, but I know it was not me. And it shouldn't be Adrian either.

**Comment by bilderbuchi** [comment]
Maybe because you were the last one to touch that part of the source (see above commit link)?
The previous trac ticket linked above is owned by lochel, but I'm not sure if that is not just the default for new trac tickets.

**Comment by sjoelund** [comment]
Yes, every time we create new files we have copied from https://openmodelica.org/osmc-pl/osmc-pl-1.2-runtime.txt

But it seems the text does not match the bylaws. I am fairly sure someone was assigned the task of updating that file and the headers several years ago though...

**Comment by sjoelund** [comment]
I have now updated the URL. Please check that the text is correct

**Comment by bilderbuchi** [comment]
Yes that looks correct now, thanks! Two minor things: 
* My current Firefox (on Windows, in Austria so used to "ö"s 😛) curiously mangles Linköping to `LinkÃ¶ping` when displaying that text file, maybe there's something weird in the encoding?
* You used the formulation "New BSD" in the additions but the first mention uses "BSD NEW", maybe it's worth it to get the word order consistent. FWIW, OSI [uses](https://opensource.org/licenses/BSD-3-Clause) the "New BSD" order (but prefers "3-clause")

**Comment by sjoelund** [comment]
Changed it to BSD NEW in both places (otherwise the bylaws need to change). As for encoding, it seems Apache doesn't send text encoding for .txt-files by default (I updated that).

**Comment by bilderbuchi** [comment]
wah, I don't want to be OCD about this, but you missed a spot 😝  " The New BSD License is obtained from:" (I think that one was already present)
encoding works correctly now, thx!

**Comment by sjoelund** [comment]
> wah, I don't want to be OCD about this, but you missed a spot  " The New BSD License is obtained from:" (I think that one was already present)

It was. I fixed it now.

**Comment by casella** [comment]
I understand this issue was fixed. @bilderbuchi if that is not the case, please comment here.

**Comment by bilderbuchi** [comment]
@casella that is unfortunately incorrect, please reopen. 

* [x] What has been fixed is the RT license text on [the homepage](https://openmodelica.org/osmc-pl/osmc-pl-1.2-runtime.txt). 
* [ ] The license headers of relevant files in the codebase have not been corrected afaict, see e.g. [the file mentioned ](https://github.com/OpenModelica/OpenModelica/blob/81066b9ee3f51c11336db4569e6f5e16fe9a4126/OMCompiler/SimulationRuntime/c/omc_inline.h) in the OP. (I don't know enough to determine the precise set of files that are part of the RT and should have the RT license)
* [x] If you also deal with all FMI-related RT files, too, #5154 can also be closed.
* [ ] Also, the files lack the "This file belongs to the OpenModelica Run-Time System" introductory text.

**Comment by casella** [comment]
We should probably add a pointer with an URL, so it's easier to keep this up to date
