### ISSUE TITLE
OMEdit replaceable package dialog should be restricted to packages

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#7630]
The current nightly build of 1.18-dev shows a too large list of candidates for replaceable packages if choicesAllMatching=true. See e.g. the model `PowerSystem.Examples.Generic.Test.ImpedanceTest`, component `load`. The list contains e.g. `PowerSystems.Interfaces.Terminal.PhaseSystem` defined in a connector, or `PowerSystems.Generic.Inverter.PhaseSystem_dc` defined in a model. Shouldn't the list be restricted to packages defined in packages?

![image](https://user-images.githubusercontent.com/4224368/123851044-0bc90580-d91b-11eb-8869-45389fecabee.png)

**Comment by adrpo** [comment]
True. Also we should filter out protected elements but allow local classes. I'll see what I can do.

**Comment by perost** [comment]
This should be fixed in #10277.
