### ISSUE TITLE
Variables Browser show non-existing variable

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#7632]
### Description
After simulation with output filter, variable browser shows variable that could not be found in result file (in case of csv, the parameters are also shown, although they are not saved in csv-result file).

Clicking said variable resulting in error.

Opening the result file using file --> Open Result File(s) show only existing variable in the result file

### Steps to reproduce
<details>
<summary> Test code </summary>

```
model simple
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage1;
  Modelica.Electrical.Analog.Basic.Ground ground1;
  Modelica.Electrical.Analog.Basic.Resistor resistor1 ;
equation
  connect(ground1.p, constantVoltage1.n);
  connect(resistor1.p, constantVoltage1.p);
  connect(ground1.p, resistor1.n) ;
end simple;
```
filter ``` resistor1\.p\.i```

</details>

### Expected behavior
Variable Browser only show existing variable and parameter in result file.

### Version and OS
 - OpenModelica Version v1.18.0-dev-285-gc5eac8a7bd
 - OS: [e.g. Windows 7, 64 bit]

**Comment by casella** [comment]
Probably related to #7624

**Comment by Arinomo** [comment]
@casella probably. From a quick test i've done. it seems that Variables Browser looks in the currently simulated model and just listed all available variables and parameters. When the user select an item, it then looks inside the result file and could not find the data, hence the error "Following variable(s) are not found: varName"

**Comment by adrpo** [comment]
I think it looks into Model_init.xml file for the parameters and their values. @adeas31 should be able to enlighten us.

**Comment by adeas31** [comment]
Yes we read the variables from model_init.xml file now to support editing of String variables for re-simulation, see #5177. The list of variables in `model_init.xml` file and `model_res.mat` file are different. I will filter out the `model_init.xml` file variables according to the result file variables.

**Comment by adeas31** [comment]
#7663 should fix this issue. However, note that the variables that do not exist in the result file are still shown but without a checkbox so it is not possible to plot them. We need these variables so we can update the values and use them for re-simulation. We cannot hide them because of the issue #5177.
