### ISSUE TITLE
Recent versions of OMEdit very often corrupt files

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7645]
### Description

I recently decided to have a try to a 1.18.0-dev version of OMEDIT. I chose -dev-384.
Unfortunately, it very often corrupts files.
Insofar, I could not find a repetitive sequence able to reproduce the issue but have a screenshot that may help.
Note that this occurs after a few re-simulations took place.

Good that all the plots appear again after resimulation: the user does not have to restart OMEdit, and does not lose the plot setup.

### Expected Behavior
more stability

### Screenshots
This is a screenshot of part of my screen, showing several windows, since this way I can capture both the OMEdit window and the error message.
![Screen](https://user-images.githubusercontent.com/37046832/124282263-ee7a7e00-db4a-11eb-8306-03c776fff5cd.png)

### Version and OS
Win 10 - 64 bit

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
As far as I know this is fixed with https://github.com/OpenModelica/OpenModelica/commit/2c55a33cb5d801a3b041468b95f5820ede8c4300. Please reopen if you still have issues.

**Comment by casella** [comment]
@max-privato the 1.18.0 beta contains the fix

**Comment by max-privato** [comment]
> @max-privato the 1.18.0 beta contains the fix

great
