### ISSUE TITLE
Undefined reference to `data_of_boolean_f77_array`

### ISSUE THREAD

**Issue by mahge** [OpenModelica/OpenModelica#7667]
### Description

Compilation fails due to use of undefined function `data_of_boolean_f77_array`
### Steps to Reproduce

Try simulating this example model
```modelica
model T
  Real A[2,2] = {{0,1},{2,3}};
  Real B[2,2];
equation
  B = Modelica.Math.Matrices.LAPACK.dgees(A);
  annotation(uses(Modelica(version="4.0.0")));
end T;
```

### Expected Behavior

Should compile fine.

Right now the C compilation fails at link time due to the undefined function.  

_Note: We should actually forbid implicit function declaration as well._ 

### Version and OS

 - OpenModelica Version: v1.19.0-dev-24-gd2fdb43160
 - OS: Any
 - Versions of used Modelica libraries: Any

### Additional Context

This issue was shadowed by another issue #7660,  which is now fixed in #7666

**Comment by casella** [comment]
@mahge, would you take care of this yourself?

**Comment by mahge** [comment]
Ya. I am going to fix it. Just forgot to assign it to myself.
