### ISSUE TITLE
Derivatives should never be picked as torn variables in strong components

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7704]
### Description

In some cases (e.g. thermo-fluid models when index reduction is applied), state derivatives become unknowns of strong components. When tearing is used to solve them, it may happen that the derivatives themselves are picked as torn variables. When solving the residual equations, appropriate error estimators are employed to guarantee a high precision of their unknowns, i.e. the tearing variables, see the simulation parameter [-newtonXTol=1e-12](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-newtonxtol). However, if some derivatives are picked as torn variables, _there is no guarantee on the numerical precision of their solution_. Hence, in case of high sensitivity of those derivatives w.r.t. the tearing variables, their numerical values may end up being corrupted by numerical noise with an amplitude much greater than `newtonXTol`.

This may cause problems to the ODE solver that is performing the (odeMode) integration over time, because a large amount of numerical noise may fool the error estimation algorithms of variable step-size solvers to the point that they either become very slow or even abort the simulation. This happens because the estimated error is caused by the numerical noise, and reducing the step size obviously does not, in general, reduce the estimated error, causing further reductions of the step size, until eventual failure.

BTW, this kind of behaviour is very sensitive in completely unpredictable ways on the selection of tolerance, ODE solver, stopTime, number of intervals etc.

### Steps to Reproduce

Consider this system firsts
```
model M1
  Real x, y, u;
  Real p = 1e14;
equation
  der(x) = p*(y-x/2);
  y = (u - x);
  u = sin(time);
  annotation(experiment(StopTime = 20));
end M1;
```
Although it is very stiff due to the large value of `p`, the OMC toolchain eventually solves it with about 200 steps, which is what is required to reproduce the sinusoidal trajectory of x (which is very close to u) with sufficient precision, give the tolerance. 

Consider now this slight variation of the same model, that introduces infinitesimally small structural coupling to the previous model, causing der(x) to become a torn variable.

```
model M2
  Real x, y, u;
  Real p = 1e14;
equation
  der(x) + 1e-12*sin(y) = p*(y-x/2);
  y = (u - x) + 1e-12*sin(y)*der(x);
  u = sin(time);
  annotation(experiment(StopTime = 20));
end M2;
```
This model fails because of an ODE solver error:

```
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =   2.9854923928640E-02   R2 =   9.5717537590803E-10
DASKR--  NONLINEAR SYSTEM SOLVER COULD NOT CONVERGE                             
DASKR--  BECAUSE IRES WAS EQUAL TO MINUS ONE                                    
DASKR--  AT T (=R1) AND STEPSIZE H (=R2) THE                                    
      In above,  R1 =   0.0000000000000E+00   R2 =   1.9073486328125E-11
DASKR--  NONLINEAR SYSTEM SOLVER COULD NOT CONVERGE                             
DASKR--  BECAUSE IRES WAS EQUAL TO MINUS ONE                                    
```

Despite shortening the step size to 1.9e-11, the solver is not able to reduce the error estimation below the default 1e-6 tolerance, and thus fails.

### Expected Behavior
In all cases whereby state derivatives end up as unknowns of nonlinear strong components and tearing is used, then all derivatives should always be selected as tearing variables, i.e. unknowns of the Newton algorithm. In this way there is a theoretical guarantee on the numerical quality of their solution, thanks to the very low value of `newtonXTol`.

**Comment by casella** [comment]
cc: @andreabartolini

**Comment by phannebohm** [comment]
After some playing around, your reasoning seems very plausible to me. So basically you want every state to have `tearingSelect = always` if not specified otherwise? Unfortunately, in this example that is not sufficient.

For the simulation the component gets an extra cse variable so it looks like this:
```
Variables (3)
========================================
1: x:STATE(1)(fixed = true )  type: Real
2: $cse3:VARIABLE(protected = true )  type: Real unreplaceable
3: y:VARIABLE()  type: Real

Equations (3, 3)
========================================
1/1 (1): y = u + 1e-12 * $cse3 * der(x) - x   [dynamic |0|0|0|0|]
2/2 (1): $cse3 = sin(y)   [unknown |0|0|0|0|]
3/3 (1): der(x) + 1e-12 * $cse3 = 100000000000000.0 * (y + (-0.5) * x)   [dynamic |0|0|0|0|]
```
Choosing `der(x)` is not enough to tear the system. By default `$cse3` is added to the tearing variables instead of `y`. It seems that choice is less stable so the nls has trouble solving the system. It fails at about `time = 6.36`. Not so incidentally, that is when the Jacobian's determinant gets close to zero. If however `y` is selected in the tearing set, the nls can somehow manage it (with some amount of struggle).

Maybe cse variables need to have `tearingSelect = avoid` by default. However I have no idea if that holds in general. What do you think?

In any case, I don't think that invalidates your proposal.

**Comment by phannebohm** [comment]
Also the choice of residual equations is crucial (similar to https://github.com/OpenModelica/OpenModelica/issues/7628#issuecomment-872076466). Luckily it works out in this example. I think I tried every possible combination and the only one that works is having `der(x)` and `y` as tearing variables and (with the numbering above) residual equations 1 and 3. It even breaks if tearing is turned off!

**Comment by phannebohm** [comment]
> In this way there is a theoretical guarantee on the numerical quality of their solution, thanks to the very low value of `newtonXTol`.

BTW this seems to break down whenever the Jacobian is close to singular right?
Below is the value of `der(x)` along with the value of the determinant scaled by `1e7`.
I'm assuming you are aware of that, and it's not necessarily relevant to the discussion, the plot just looks so nice...

![stability](https://user-images.githubusercontent.com/16221675/127526066-f89edda0-18f9-4ab1-8f49-6bfade59aab5.png)

**Comment by phannebohm** [comment]
> I'm assuming you are aware of that, and it's not necessarily relevant to the discussion, ...

Actually, let me take that back. I now believe the problem is that the coupling introduces singularities in the Jacobian of the strong component that weren't there before.

The newly introduced coupling term in equation 3 is in fact negligible but the one in equation 1 isn't. The Jacobian for this component has determinant `1 - 1e-12 * (cos(y)*der(x) + sin(y)*p)` (neglecting the small term in eq 3) which can become zero as the figure shows.

Changing the term in eq 1 from `sin(y)` to , e.g., `cos(y)` "solves" the problem (determinant `1 - 1e-12 * (-sin(y)*der(x) + cos(y)*p)`, happily jiggling around -96 or something) without ever tampering with tearing selection.

So I'm forced to conclude that tearing is not at fault here.

In any case I opened #7733. @casella, please tell me if that addresses the issue with thermo-fluid models.

**Comment by casella** [comment]
> After some playing around, your reasoning seems very plausible to me. So basically you want every state to have `tearingSelect = always` if not specified otherwise? 

I guess you man every state _derivative_. States are never going to be unknowns in odeMode simulations.
 
> For the simulation the component gets an extra cse variable so it looks like this:
> 
> ```
> Variables (3)
> ========================================
> 1: x:STATE(1)(fixed = true )  type: Real
> 2: $cse3:VARIABLE(protected = true )  type: Real unreplaceable
> 3: y:VARIABLE()  type: Real
> 
> Equations (3, 3)
> ========================================
> 1/1 (1): y = u + 1e-12 * $cse3 * der(x) - x   [dynamic |0|0|0|0|]
> 2/2 (1): $cse3 = sin(y)   [unknown |0|0|0|0|]
> 3/3 (1): der(x) + 1e-12 * $cse3 = 100000000000000.0 * (y + (-0.5) * x)   [dynamic |0|0|0|0|]
> ```
> 
> Choosing `der(x)` is not enough to tear the system. By default `$cse3` is added to the tearing variables instead of `y`.

Of course this is a bad choice, since `$cse3` is multiplied by 1e-12 everywhere,  so the sensitivity of the residual to it is very low and caused problems due to finite precision and rounding errors.

However, this specific issue is completely unrelated to the topic of this ticket. It is more related to [#4845](https://trac.openmodelica.org/OpenModelica/ticket/4845), though in that case the problem is the opposite, i.e. that the sensitivity is too large.

> It seems that choice is less stable so the nls has trouble solving the system. It fails at about `time = 6.36`. Not so incidentally, that is when the Jacobian's determinant gets close to zero. If however `y` is selected in the tearing set, the nls can somehow manage it (with some amount of struggle).

The system is stiff anyway, so some struggle is expected.

> Maybe cse variables need to have `tearingSelect = avoid` by default. However I have no idea if that holds in general. What do you think?

I'm not sure this is a good idea in general, from a numerical point of view it depends how those cse variables are used.

From a structural point of view, in general cse are defined to be equal to a certain expression, so they look like the ideal candidates for being torn variables, because their definition equation is already in the form `cse := <expr>` and then this `cse` will be used everywhere else once computed. But I'm not sure this is a good idea in general, I haven't thought about that.

**Comment by casella** [comment]
> I think I tried every possible combination and the only one that works is having `der(x)` and `y` as tearing variables and (with the numbering above) residual equations 1 and 3. It even breaks if tearing is turned off!

Maybe the provided MWE is unnecessary tough on the solver, unfortunately real-life cases with this problem are very complicated and mostly confidential, so I'd rather not share them here. 

However, I think the principle is sound: we need to have good precision control on the derivatives for the sake of the sanity of ode solver error estimators. If we select them as tearing variables, we lose this control, so your mileage may vary.

**Comment by casella** [comment]
> > In this way there is a theoretical guarantee on the numerical quality of their solution, thanks to the very low value of `newtonXTol`.
> 
> BTW this seems to break down whenever the Jacobian is close to singular right?
> Below is the value of `der(x)` along with the value of the determinant scaled by `1e7`.
> I'm assuming you are aware of that, and it's not necessarily relevant to the discussion

OMG, no, I was not aware of that, and in fact it may be quite relevant. I managed to pick up an example which becomes nearly singular every now and then.

**Comment by casella** [comment]
> The newly introduced coupling term in equation 3 is in fact negligible but the one in equation 1 isn't. The Jacobian for this component has determinant `1 - 1e-12 * (cos(y)*der(x) + sin(y)*p)` (neglecting the small term in eq 3) which can become zero as the figure shows.

Right. If `p*1e-12 >> 1`, we're done for. I overlooked that.

> So I'm forced to conclude that tearing is not at fault here.

Yeah. Finding a MWE for this problem is not trivial at all.
 
> In any case I opened #7733. @casella, please tell me if that addresses the issue with thermo-fluid models.

@AndreaBartolini will get back to you when he comes back from his vacation.

**Comment by phannebohm** [comment]
> I guess you man every state _derivative_. States are never going to be unknowns in odeMode simulations.

Sure, if you annotate the state, its derivative "inherits" that attribute. There is this weird thing in the backend where states and their derivatives are kind of the same thing for simulation.

BTW, at initialization it's different and there are dedicated `$DER` crefs. The way #7733 operates is that only for simulation states (i.e. their derivatives) are added to the `always` list of tearing variables. Since the above example model initialized without trouble and you are talking about the ODE solver, I think this is only needed for simulation, right?

**Comment by phannebohm** [comment]
> However, this specific issue is completely unrelated to the topic of this ticket. It is more related to [#4845](https://trac.openmodelica.org/OpenModelica/ticket/4845), though in that case the problem is the opposite, i.e. that the sensitivity is too large.

> > Maybe cse variables need to have `tearingSelect = avoid` by default. However I have no idea if that holds in general. What do you think?
> 
> I'm not sure this is a good idea in general, from a numerical point of view it depends how those cse variables are used.
> 
> From a structural point of view, in general cse are defined to be equal to a certain expression, so they look like the ideal candidates for being torn variables, because their definition equation is already in the form `cse := <expr>` and then this `cse` will be used everywhere else once computed. But I'm not sure this is a good idea in general, I haven't thought about that.

A good topic for another day!

**Comment by phannebohm** [comment]
> Maybe the provided MWE is unnecessary tough on the solver, unfortunately real-life cases with this problem are very complicated and mostly confidential, so I'd rather not share them here.

I see... :sweat_smile: 


> However, I think the principle is sound: we need to have good precision control on the derivatives for the sake of the sanity of ode solver error estimators.

True. 

> If we select them as tearing variables, we lose this control, so your mileage may vary.

You mean the other way around. The tearing variables are the ones we iterate over, or is my vocabulary wrong?

**Comment by casella** [comment]
> > I guess you man every state _derivative_. States are never going to be unknowns in odeMode simulations.
> 
> Sure, if you annotate the state, its derivative "inherits" that attribute. There is this weird thing in the backend where states and their derivatives are kind of the same thing for simulation.

I guess that's because you never have to solve for a state, you always solve for a derivative. Of course `x` and `der(x)` are not the same, otherwise we would only simulate systems with exponentially diverging trajectories...

> BTW, at initialization it's different and there are dedicated `$DER` crefs.
Yeah, at initialization you need to worry about both of them at the same time.

> The way #7733 operates is that only for simulation states (i.e. their derivatives) are added to the `always` list of tearing variables. Since the above example model initialized without trouble and you are talking about the ODE solver, I think this is only needed for simulation, right?

Absolutely. But maybe it's not really needed after all, see #7734.

**Comment by casella** [comment]
> > However, I think the principle is sound: we need to have good precision control on the derivatives for the sake of the sanity of ode solver error estimators.
> 
> True.
> 
> > If we select them as tearing variables, we lose this control, so your mileage may vary.
> 
> You mean the other way around. The tearing variables are the ones we iterate over, or is my vocabulary wrong?

Of course. I meant "torn variables". Time to pull the plug for good.

**Comment by phannebohm** [comment]
We had a discussion in the backend group and @bernhardbachmann alluded to the fact that there is no way to set nominal values for state derivatives, which would be necessary for proper convergence checks and thus precision in the iteration variables.

Also, we could potentially try to introduce a convergence check for state derivatives in strong components without necessarily adding them to the iteration variables. However that would similarly suffer from the absence of nominal values.

I added the config flag `--tearingAlwaysDer` in the master branch for @AndreaBartolini to test this.

**Comment by casella** [comment]
@phannebohm unfortunately we left this issue unfinished during the summer.

Regarding the problem of establishing a nominal value for derivatives, see [#3111](https://trac.openmodelica.org/OpenModelica/ticket/3111) and #7794.

@phannebohm, at the very least we should propagate the nominal value of variables to their derivatives. Then, I guess we could close this ticket for good.

**Comment by phannebohm** [comment]
> @phannebohm, at the very least we should propagate the nominal value of variables to their derivatives. Then, I guess we could close this ticket for good.

I think this was done in #7819, we can discuss there if needed.

**Comment by casella** [comment]
> I think this was done in #7819, we can discuss there if needed.

There it is, I couldn't find it. I currently don't really have ideas beyond that, maybe we need some more testing and evidence-based decisions...
