### ISSUE TITLE
getNthComponent and GetComponents

### ISSUE THREAD

**Issue by mahesRBR** [OpenModelica/OpenModelica#7706]
There was an issue reported in Trac
https://trac.openmodelica.org/OpenModelica/ticket/2940

is that fixed  ? as I observed the  same issue  with another class

using OMShell

>> getComponents(Modelica.Thermal.FluidHeatFlow.Components.OpenTank)
{{Modelica.Units.SI.Area,ATank,"Cross section of tank", "public", false, false, false, false, "parameter", "none", "unspecified",{}},{Modelica.Units.SI.Length,hTank,"Height of tank", "public", false, false, false, false, "parameter", "none", "unspecified",{}},{Modelica.Units.SI.Pressure,pAmbient,"Ambient pressure", "public", false, false, false, false, "parameter", "none", "unspecified",{}},{Modelica.Units.SI.Acceleration,g,"Gravitation", "public", false, false, false, false, "parameter", "none", "unspecified",{}},{Boolean,useHeatPort,"= true, if HeatPort is enabled", "public", false, false, false, false, "parameter", "none", "unspecified",{}},{Modelica.Units.SI.Mass,m,"Mass of medium in tank", "public", false, false, false, false, "unspecified", "none", "unspecified",{}},{Modelica.Thermal.HeatTransfer.Interfaces.HeatPort_a,heatPort,"Optional port for cooling or heating the medium in the tank", "public", false, false, false, false, "unspecified", "none", "unspecified",{}},{Modelica.Blocks.Interfaces.RealOutput,level,"Level of medium in tank", "public", false, false, false, false, "unspecified", "none", "unspecified",{}},{Modelica.Blocks.Interfaces.RealOutput,TTank,"Temperature of medium in tank", "public", false, false, false, false, "unspecified", "none", "unspecified",{}},{Modelica.Units.SI.Enthalpy,H,"Enthalpy of medium", "protected", false, false, false, false, "unspecified", "none", "unspecified",{}},{Modelica.Units.SI.HeatFlowRate,Q_flow,"Heat flow at the optional heatPort", "protected", false, false, false, false, "unspecified", "none", "unspecified",{}}}

>> getComponentCount(Modelica.Thermal.FluidHeatFlow.Components.OpenTank)
11

>> getNthComponent(Modelica.Thermal.FluidHeatFlow.Components.OpenTank, 11)
{Modelica.Blocks.Interfaces.RealOutput,TTank,"Temperature of medium in tank"}

But the 11th item in getComponents is Modelica.Units.SI.HeatflowRate

I am using OpenModelica 1.17

Thanks

**Comment by adrpo** [comment]
Should be fixed via: PR #7709.
