### ISSUE TITLE
OMEdit plot grids

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7711]
### Description

This is not a bug report, just a suggestion for improvements,
1) detailed grid. According to my experience, all or nearly all computer programs do not have detailed grid as default. Indeed, while a detailed grid is useful on printed plots, it is much less important on screens when one has the cursor to see actual values.
**My proposal**: either default the grid to "Grid" (not to "detailed grid"), or add an option in the options|plotting to allow the preferred grid level (default should be grid)
2)  I've been thinking for many years that in the current OMEdit plots the grid is too pervasive, at least for plots with one-pixel curves. In the default plot, in fact, both curves and gridlines are one pixel, which is not optimal.

**My proposal**: Several options can do well:
- Use gray gridlines (not black) instead of black, when curves are one pixel
- Use always gray gridlines (not black) instead of black
- use dotted gridlines to make them less pervasive
The right choice between the various options is to be made looking at the result. in all plots the curves must dominate over gridlines.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@ceraolo, this seems very reasonable to me. Maybe just using grey would improve the situation already. Plot lines that are slightly thicker, e.g. 1.5 points with aliasing, could also look great. Maybe we can experiment with that a bit.

**Comment by adeas31** [comment]
The fix is on its way. You can try it out in tomorrow's nightly build. Let me know what you think? If everything goes fine we can port it to 1.18

**Comment by max-privato** [comment]
> The fix is on its way. You can try it out in tomorrow's nightly build. Let me know what you think? If everything goes fine we can port it to 1.18

thank you.
I'll be able to test it next 16th. Before I've not enough Internet data.

**Comment by max-privato** [comment]
unfortunately, it seems that the main gridlines are now hardly visible on a  1920x1080 screen (very common nowadays), see screenshots.pdf.

As far as I'm concerned, I would feel comfortable if, when drawing plots with thickness one, you use for all gridlines the pattern you currently use for detailed ones: i.e. black-dotted. 

In case all curves have thickness equal to at least two pixels, more visible gridlines would be better, e.g. one-pixel solid or two pixel dotted.

So, my proposal is not to distinguish the aspect between main and minor gridlines, but take somehow into consideration also the thickness of curves.
Naturally, if you find better solutions I would be glad.

[screenshots.pdf](https://github.com/OpenModelica/OpenModelica/files/6988663/screenshots.pdf)

**Comment by adeas31** [comment]
> As far as I'm concerned, I would feel comfortable if, when drawing plots with thickness one, you use for all gridlines the pattern you currently use for detailed ones: i.e. black-dotted.

I don't think this is a good solution.

> In case all curves have thickness equal to at least two pixels, more visible gridlines would be better, e.g. one-pixel solid or two pixel dotted.

I would prefer to have a static solution rather than dynamic.

I did some experiments with different color values. This is what we have currently,

![F2F2F2-current-version](https://user-images.githubusercontent.com/4007231/129908268-a219d973-e1e1-4467-90f0-f24442872407.png)

As you mentioned the grid lines are hardly visible. This uses a gray value of F2F2F2.

The following one uses a gray value of C0C0C0,

![LightGray](https://user-images.githubusercontent.com/4007231/129908476-c1e28a98-e891-4b38-9840-b9abcebb4706.png)

Now the one with D2D2D2. This is the one I recommend,

![D2D2D2](https://user-images.githubusercontent.com/4007231/129908576-46a20004-8c34-457b-89d8-32fc964a023f.png)

Apart from color I also did some experiment with anit-aliasing. The following one is D2D2D2 with curves with anit-aliasing,

![D2D2D2-anti-aliasing](https://user-images.githubusercontent.com/4007231/129908757-20fb13c3-5262-448b-b6ec-73414934abaa.png)

The last one with D2D2D2 and without anit-aliasing,

![D2D2D2-without-anti-aliasing](https://user-images.githubusercontent.com/4007231/129908812-b6091f8a-89a3-4794-8c77-19e420e01d8c.png)

**Comment by max-privato** [comment]
> I don't think this is a good solution.
Ok.  
> 
> I would prefer to have a static solution rather than dynamic.
I understand that the static solution is simpler for the implementation, but for the user experience I think is worse.
The reason why I proposed this is that with released OMEdit, the ratio of curves to gridlines visibility is good with 2-3 pixels for curves and one for gridlines, while is suboptimal for one pixel curves.
Have you tried this?

> 
> I did some experiments with different color values. 
I agree that C0C0C0 and D2D2D2 are much better than 000000 (present default) and F2F2F2.

Can you share with us also plot having both major **and** minor gridlines **and** a plot curve with  C0C0C0 and D2D2D2  or whatever intermediate value you deem adequate? From your present examples, I would prefer somewhere between C0C0C0 and D2D2D2

Regarding anti-aliasing, the plots you shared seem identical. Are you sure they are created in different ways?

**Comment by adeas31** [comment]
> I agree that C0C0C0 and D2D2D2 are much better than 000000 (present default) and F2F2F2.

The F2F2F2 is the current value used in nightly builds. Previously we had A0A0A4 (gray). We never had 000000 (black).

I used C9C9C9 as intermediate color value for major gridlines. For minor gridlines we have C0C0C0.

The following is without anti-aliasing,

![C9C9C9-without-anti-aliasing](https://user-images.githubusercontent.com/4007231/130412937-fefa7bbe-06cb-4251-aaaf-635d804816cc.png)

The following is with anti-aliasing,

![C9C9C9-with-anti-aliasing](https://user-images.githubusercontent.com/4007231/130415670-b129227c-b014-4172-a843-f62dcac6251a.png)

> Regarding anti-aliasing, the plots you shared seem identical. Are you sure they are created in different ways?

The anti-aliasing makes the curve slightly thicker. However, it is not very obvious from the screenshots.

**Comment by max-privato** [comment]
On my screen I see no difference between aliasing and anti-aliasing. I general I would conclude that this difference, if exists, is  very small, negligible  I would say. 
I wonder whether anti-aliased plotting is slower than the other. I would check this with a huge plot (say one-million points) to see differences. In case of significant slowing due to anti-aliasing, I think best to avoid it.

Regarding gridlines, can you, please, share the plots I mentioned in my previous comment?

**Comment by adeas31** [comment]
> Regarding gridlines, can you, please, share the plots I mentioned in my previous comment?

I shared the screenshots in my last comment. I used C9C9C9 as intermediate color value for major gridlines and C0C0C0 for minor gridlines.

**Comment by max-privato** [comment]
aha.
Ok. For me gridlines now are ok.

Will you please consider also ticket #7712?

**Comment by adeas31** [comment]
> Ok. For me gridlines now are ok.

PR #7810 fixes this one.

> Will you please consider also ticket #7712?

Yes, I will take care of it.
