### ISSUE TITLE
Enhance OMEdit plot windows

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7712]
### Description
This is not a bug report, just a recommendation for an enhancement.

I use subwindow plotting.
I think that all people that want, like me, have a full simultaneous view of several curves, they will open several subwindow plot windows. To arrange all of them in the limited screen space, very often they can be very small.
Unfortunately, when plot windows are small, access to "setup" button is tricky, because it is outside the window area.

I have a simple proposal to make small plots easier.
1) "Auto Scale" button. Frankly, I don't see the need to be there; auto scale is already an option inside Setup. 
2) "Fit in view" can be changed into "Fit"
3) Instead of having "Grid", "Detailed Grid", and "No Grid", just a "Grid" button could be there that rotates between Grid->Detailed Grid-> No Grid-> Grid.
4) (not for horizontal size reduction, just as a possible further enhancement) maybe Save and Print can be moved to the end of the menu, since, differently from the other buttons, they don't relate to the plot appearance. 

Another (possibly even better) way to reduce the menu's horizontal size is to use ToolButtons with icons and tooltips. If this is chosen, all the buttons could be always visible, even for the narrowest plot window, maybe using, also in this case, some of the numbered items above.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
The fix is one its way. Here is the comparison,

Old:
![image](https://user-images.githubusercontent.com/4007231/134509000-a3a4cd22-2f1f-4b82-83b3-46f7e3309c7a.png)

New:
![image](https://user-images.githubusercontent.com/4007231/134509027-5c4942c4-7a40-497e-8b1f-5bd567561e83.png)

**Comment by max-privato** [comment]
I think it is a good result.
This may be not apparent with plots this size, but the modification was proposed to enhance the usability of very small plot windows, and I’m sure it will.

**Comment by max-privato** [comment]
I've started using OM 1.19.0.
I would like to suggest a minimal, yet useful fine tuning of this ticket.
In the Grid combo box, the two items are :
detailed Grid 
no Grid.

I would suggest to change into:
_detailed
none_
or, if you prefer:
_detailed
no grid._

This will allow the combo to become smaller.
Thank you.
