### ISSUE TITLE
Simulations that are not run because of flag issues exit with the success code

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7719]
### Description

Please check [the TGM_Comax_Analytical_2016 simulation results](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Comax_Analytical_2016.sim) in [PhotoVoltaics_TGM](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/PhotoVoltaics_TGM.html).

The simulation is not even attempted because of badly formed flags. However, the simulation is reported as successful in the test report. I guess the reason is that in this case, an error code is not returned, but rather a successful one.

### Expected Behavior

An error code should be returned, and the simulation should be reported as failed in the test report.

**Comment by AnHeuermann** [comment]
@lochel Did your commits fix this issue?

**Comment by lochel** [comment]
I think so, yes. But I didn't check that specific model or the test report...

**Comment by casella** [comment]
This issue seems to be resolved, the [test report page](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/PhotoVoltaics_TGM.html) is consistent with the specific simulation results, in particular as regards [TGM_Comax_Analytical_2016](https://libraries.openmodelica.org/branches/master/PhotoVoltaics_TGM/files/PhotoVoltaics_TGM_PhotoVoltaics_TGM.TGM_Comax_Analytical_2016.sim)
