### ISSUE TITLE
Checking for functions fails systematically 

### ISSUE THREAD

**Issue by arouhan** [OpenModelica/OpenModelica#7737]
using OpenModelica v1.18.0-dev.beta1, checking of any function fails.
the error message being: (example: splitPathName  from the MSL 4.0.0):

`Error: Cannot instantiate Modelica.Utilities.Files.splitPathName due to class specialization FUNCTION.`

**Comment by casella** [comment]
Duplicate of [#5045](https://trac.openmodelica.org/OpenModelica/ticket/5045).

@arouhan, we'll try to address it in one of the next releases.
