### ISSUE TITLE
DisplayUnit is not shown in Icon layer

### ISSUE THREAD

**Issue by sbaetzing** [OpenModelica/OpenModelica#7765]
### Description

If a parameters value is displayed in icon layer via %parameterName in a text string its SI unit is always displayed.
Better would be the value in its corresponding displayUnit.  

### Expected Behavior

Currently defined displayUnit should be shown.

### Version and OS

 - OpenModelica Version: OpenModelica v1.19.0-dev-14-g63df406c47 (64-bit)
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
That's an easy one, I guess

**Comment by adeas31** [comment]
> That's an easy one, I guess

I though the same but that was not the case. The first thing that took some time to find is that I used `displaytUnit` in the code instead of `displayUnit`, stupid mistake. And then I realized there is one case that was not handled. Anyways the fix is on its way.

**Comment by casella** [comment]
Great, thanks!
