### ISSUE TITLE
Bad placement of big pictures in parameter dialog 

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#7768]
### Description
A parameter dialogue's group image is always displayed to the right of the parameters. If the image gets bigger, this leads to unnecessarily wide parameter dialogues, which are harder to grasp. 

### Steps to reproduce
Insert any large image as a group image and open the parameter dialogue of the component. 

### Expected behaviour
Place large group images above or below the group's parameters in order to reduce the overall window size. 

### Screenshots
Look into Rexroth_Generic.Hydraulics.Valves.DirectionalValves.DirectionalValve43 from the BRSL, which to my knowledge is accessible to you. 
I cannot upload screenshots right now due to VPN but I can send them via email.

### Version and OS
 - OpenModelica Version v1.19.0-dev-14-g63df406c47 (64-bit)
 - OS: Windows 10, 64 bit

**Comment by adeas31** [comment]
You can email me the screenshots.

One idea is to put the picture in a scroll area with some maximum size. When the maximum size is reached the user can use the scrollbars to view the picture.

**Comment by abuntrock** [comment]
Attached you can find a screenshot of the problem. The horizontal scrollbar on the bottom shows that the picture reaches out even further to the right.
Thanks for indicating a possible workaround. I will discuss and test it with my colleagues.

Mit freundlichen Grüßen / Best regards

Aaron Buntrock
DC/ESS12

Tel. +49 731 49373-443
​
Von: Adeel Asghar ***@***.***>
Gesendet: Montag, 23. August 2021 10:00
An: OpenModelica/OpenModelica ***@***.***>
Cc: Buntrock Aaron (DC/ESS12) ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenModelica/OpenModelica] Bad placement of big pictures in parameter dialog (#7768)


You can email me the screenshots.

One idea is to put the picture in a scroll area with some maximum size. When the maximum size is reached the user can use the scrollbars to view the picture.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenModelica%2FOpenModelica%2Fissues%2F7768%23issuecomment-903532242&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C354d3f2343f844fef09208d9660c0b8a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637653024193115629%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hepn%2B4FMg%2BbgCrnfa2XlVrYl8%2BaVjcEFAGzTtuIEjAA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHDMRRYY5M6W4F6L2TCJP3T6H5Y7ANCNFSM5CHVC2JA&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C354d3f2343f844fef09208d9660c0b8a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637653024193125589%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hETQA4in2Mth6Uum5WAHHKyWyLoaDG8IyNtWZhiXccI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C354d3f2343f844fef09208d9660c0b8a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637653024193135540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wKCt7iCOgbBwEPtHi33Fl2ni%2B2jKgIgPQbnTiMFk%2BLs%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C354d3f2343f844fef09208d9660c0b8a%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637653024193135540%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DViEfZWFa86OgVaokb36coccLOZK8dShI3XHo1fQzkU%3D&reserved=0>.

**Comment by adeas31** [comment]
There is no attachment. Maybe GitHub filter it out.
You can send me a separate email adeel.asghar[at]liu.se

**Comment by adeas31** [comment]
We recently changed to use high dpi pixmaps in OMEdit that causes the layout size issue in this case. PR #7850 fixes the issue and shows the image in a proper size.

However, the issue of handling the big pictures is still there. I think OMEdit is doing a pretty good job right now. OMEdit ensures that the parameters dialog gets all the available space on the screen but still be inside the screen and then adds scrollbars if needed. I created a dummy example to demonstrate the handling of big pictures. You can compare the parameters dialog of `BooleanConstant` component in `P.View`.
[P.zip](https://github.com/OpenModelica/OpenModelica/files/7097997/P.zip)

**Comment by abuntrock** [comment]
Thank you very much for the information.

Mit freundlichen Grüßen / Best regards

Aaron Buntrock
DC/ESS12

Tel. +49 731 49373-443
​
Von: Adeel Asghar ***@***.***>
Gesendet: Donnerstag, 2. September 2021 12:00
An: OpenModelica/OpenModelica ***@***.***>
Cc: Buntrock Aaron (DC/ESS12) ***@***.***>; Author ***@***.***>
Betreff: Re: [OpenModelica/OpenModelica] Bad placement of big pictures in parameter dialog (#7768)


We recently changed to use high dpi pixmaps in OMEdit that causes the layout size issue in this case. PR #7850<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenModelica%2FOpenModelica%2Fpull%2F7850&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338185039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LLZ6FPtFYveRgrlJofLCHwV5rjqzoDPTYa2JZ%2BsRqFA%3D&reserved=0> fixes the issue and shows the image in a proper size.

However, the issue of handling the big pictures is still there. I think OMEdit is doing a pretty good job right now. OMEdit ensures that the parameters dialog gets all the available space on the screen but still be inside the screen and then adds scrollbars if needed. I created a dummy example to demonstrate the handling of big pictures. You can compare the parameters dialog of BooleanConstant component in P.View.
P.zip<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenModelica%2FOpenModelica%2Ffiles%2F7097997%2FP.zip&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338194987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qG90xe2XRvoh7Ax6BSuGU0%2BwQG1BsRP1NeX%2FGNSD41k%3D&reserved=0>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOpenModelica%2FOpenModelica%2Fissues%2F7768%23issuecomment-911481244&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338194987%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FS8KMfkA%2B28Oj17w4nmYPikzly4qygD9wEUZqweT5JQ%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVHDMRRUV6QW2XS53EUNEDDT75DJXANCNFSM5CHVC2JA&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338204945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xx73FHh6uwgJN5vGk1PnzdkZku7HPCRJSPIPpj%2Bv8kM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338204945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rx15eu%2F4vt7ekEqVmEzcv5FRqe8ebaDV6khojONdPhY%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CAaron.Buntrock%40boschrexroth.de%7C886843e46eb9426f594108d96df86b58%7C0ae51e1907c84e4bbb6d648ee58410f4%7C0%7C0%7C637661737338204945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=75GPmvXYUV5Tgusv43nDMNw53PMG4TFjoC7QYF65RY8%3D&reserved=0>.
