### ISSUE TITLE
Opening model when in Plotting perspective opens in plot tab

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#7772]
When you are in the plotting perspective (e.g. because you are examining some simulation results), and open a class, a new tab that displays a diagram view of the model is shown in the plot perspective instead of the modeling perspective.

### Steps to reproduce
* Go to the plotting perspective
* Double click a class/model in the libraries browser
* A diagram view of the model is shown in a new tab in the plotting area. You cannot switch to text view or do most other modelling tasks (because the buttons are for the plotting perspective). 
* When you manually go back to Modeling Perspective, you realise that the model has been opened here, too.
### Expected behavior
* the UI switches back to the modeling view and displays the model there.

### Screenshots
![image](https://user-images.githubusercontent.com/327442/129671275-bd32f7ed-5b29-4953-8a99-6d9e90722f5a.png)

### Version and OS
OpenModelica v1.18.0-dev.beta1 (64-bit)
OMSimulator v2.1.1.post80-g1bf17f4-mingw
Windows 10, 64 bit

I'm reasonably confident that this behaviour was different in earlier OMEdit versions, but I can't point to a specific version that introduced this behaviour.

**Comment by casella** [comment]
I guess this is meant for those cases where some results are shown in the diagram. @adeas31 is that the case?

**Comment by bilderbuchi** [comment]
You mean the "diagram view" that is opened with the gear icon in the plotting toolbar? That one opens the just simulated model in a diagram view. I guess this is to get a model overview or something like that, and presumably to later show changing diagram elementsover simulation time? 

I am not sure if that should be generalised to double-click of *any* (not simulated) model in the libraries browser. I can't see the purpose behind that (but surely I could miss something).

**Comment by adeas31** [comment]
This is intended for the diagram animation via dynamic select annotations. The double click feature on the model name checks in the user's current perspective and based on that opens either a diagram view for modeling or a diagram view for animation.

**Comment by bilderbuchi** [comment]
Ah I see. Even for models that have not been simulated?

**Comment by adeas31** [comment]
Yes!

**Comment by bilderbuchi** [comment]
OK. If you think that this should be improved we can leave this open, or I can file a more specific one. If you feel that the present situation is as it should be, I think this can be closed.

**Comment by adeas31** [comment]
We are of course open for suggestions :)

> and I'll retrain myself to hit Ctrl-F2 before clicking in the library browser...

You can also do a right click on the model in the `Libraries Browser` and select `Open Class`. This will always open the model in Modeling perspective.

**Comment by bilderbuchi** [comment]
> We are of course open for suggestions :)

In that case:
As a Modeler, in the plotting perspective, it would be useful if only classes that are meaningful for animation open in a diagram view in the plotting perspective, and all others switch to the modelling perspective and display there.
As a simple heuristic, it could be checked if the clicked class occurs in the simulated models/available simulation results (those in the variables browser). I guess that any animation features will also have to do that check at some point?  
Maybe a bit more involved, a check could search for dynamic select annotations in the clicked class (as those are needed for animation features)

I don't know how feasible those things are to implement, though :-P

> You can also do a right click on the model in the Libraries Browser and select Open Class. This will always open the model in Modeling perspective.

Ah, that is good to know, thanks!

**Comment by casella** [comment]
> 
> 
> OK. If you think that this should be improved we can leave this open, or I can file a more specific one. If you feel that the present situation is as it should be, I think this can be closed (and I'll retrain myself to hit Ctrl-F2 before clicking in the library browser...).

@adeas31 what do you think? I'd try to avoid having dangling tickets that are not going to be followed up. Of course we can keep it with low priority, but it has to be > 0 :)

**Comment by adeas31** [comment]
> In that case:
As a Modeler, in the plotting perspective, it would be useful if only classes that are meaningful for animation open in a diagram view in the plotting perspective, and all others switch to the modelling perspective and display there.
As a simple heuristic, it could be checked if the clicked class occurs in the simulated models/available simulation results (those in the variables browser). I guess that any animation features will also have to do that check at some point?
Maybe a bit more involved, a check could search for dynamic select annotations in the clicked class (as those are needed for animation features)

> I don't know how feasible those things are to implement, though :-P

This will result in a non-uniform behavior i.e., double click for some models opens in modeling perspective and for some models in plotting perspective. I believe this will create more confusion for users rather then helping them.

I am more in favor of a uniform solution e.g., double click will always open a model in the current perspective (i.e., what we have right now) and ctrl + double click will always open the model in modeling perspective.

**Comment by bilderbuchi** [comment]
> Of course we can keep it with low priority, but it has to be > 0 :)

you can always schedule it for the "Future" milestone 😆 

> I am more in favor of a uniform solution e.g., double click will always open a model in the current perspective (i.e., what we have right now) and ctrl + double click will always open the model in modeling perspective.

I agree, uniform behaviour is probably good to preserve. Sounds reasonable!

**Comment by casella** [comment]
> I am more in favor of a uniform solution e.g., double click will always open a model in the current perspective (i.e., what we have right now) and ctrl + double click will always open the model in modeling perspective.

Mee too :)

Can we consider this issue closed?

**Comment by bilderbuchi** [comment]
I have not checked yet - does ctrl-click already open a model in the modelling perspective? (can't check right now) Then yes 😀

**Comment by adeas31** [comment]
@bilderbuchi it is done now. You can test the feature in tomorrow's nightly build. I will port it to 1.18

**Comment by bilderbuchi** [comment]
Thanks!
