### ISSUE TITLE
OMEncrypted does not find the license file

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7773]
### Description
When an encrypted library is loaded, the license is checked at the beginning and a license file must be loaded for this. please see here: https://github.com/modelon-community/SEMLA/blob/master/doc/SEMLA.md#semla---communication-protocol-between-a-tool-and-lve
The directory in which OMEncrypted searches, is always the working directory and it cannot be changed in which folder the license should be located. The working directory is also regularly deleted by OMEdit so that the license file is also deleted.
### Steps to Reproduce
You can use the encrypted and licensed test library I have send you and place the license.txt file in a different folder then the working directory

### Expected Behavior
The SEMLA API function mlle_license_new needs to get passed the path in which the license is located. Currently it is the working directory.

### Version and OS

 - OpenModelica Version: v19
 - OS:Windows 10, 64 bit

**Comment by casella** [comment]
I guess this should be fixed in 1.18.0 already, right?

**Comment by niklwors** [comment]
@casella  We want to discuss this ticket on Friday as it is an important ticket for us. But it is not necessary to fix it for 1.18.0
