### ISSUE TITLE
It takes a long time to load a recently loaded encrypted library.

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#7774]
### Description

Loading an encrypted library that has been loaded before takes a very long time, in our case a minute. This is because the mol package is unpacked into the working directory. OMEdit could check if the unpacked directory already exists and not unpack it again.

### Steps to Reproduce

In OMEdit click in "recently used files" on a mol package

### Expected Behavior
OMEdit could check if the unpacked directory already exists and not unpack it again.

### Screenshots
<img width="1245" alt="reload" src="https://user-images.githubusercontent.com/12269776/129693574-5e39ccfb-8764-4075-a1a2-3d7f537b31d2.png">

### Version and OS

 - OpenModelica Version: v19
 - OS: Windows 10, 64 bit

**Comment by adeas31** [comment]
AFAIR the last time I checked it was not possible to load in parallel using SEMLA. This might be primarily the reason for slow loading. Unzipping the mol doesn't take a lot of time.

> OMEdit could check if the unpacked directory already exists and not unpack it again.
I believe this is not a good solution. In case of a new version of the library or if the contents of the library are changed then the user manually had to kill the unpacked library version from the working directory.

**Comment by casella** [comment]
@niklwors, it seems that there is disagreement on what is the root cause of the one-minute-long wait. If the problem is with SEMLA, there's not much we can do at the moment. Also, I agree with @adeas31 that relying on the existence of the unpacked directory is not robust against changes in the directory itself.

@niklwors can you please double-check how much of that minute is actually spent unpacking the zip file? One minute seems to me a very long time, even for a large library. Not even the MSL would take that long, and it has a lot of resource files.

**Comment by casella** [comment]
@niklwors could you check the time spent unzipping? Thanks!

**Comment by abuntrock** [comment]
With v1.24.0-dev-31-gedfa9cd10e (64-bit) we we are able to test the loading time with the parallel decryption feature of SEMLA. The loading time decreased significantly and we thus think that this ticket can be closed.

**Comment by adeas31** [comment]
I guess you mean parallel unzipping. We still haven't done anything for the parallel decryption. The SEMLA functions are not thread safe and the solution suggested by Modelon is not very optimal.

**Comment by abuntrock** [comment]
You are obviously right. But the zipping was the root thing of this issue and this is definitely done from our prespective.

**Comment by casella** [comment]
This is currently only on master (-> 1.24.0). @abuntrock is that OK for you, or would you like to get it ported to 1.23.0?

**Comment by adeas31** [comment]
The fix for it is very old and is definitely part of 1.23 branch https://github.com/OpenModelica/OpenModelica/commit/64091384f7fc0641f45d0a099663716a9a6a1954

AFAIK, @abuntrock is testing it with the latest encryption build.

**Comment by abuntrock** [comment]
That makes sense from a timeline perspective and yes I was just testing the fix with an encryption build from this week.
