### ISSUE TITLE
Probably erroneous Translation Warning 'each' used when modifying non-array element

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#7777]
### Description
I have a Modelica model where I am initialising an array of submodels, and I'm getting "Translation Warning 'each' used when modifying non-array element p" when setting `fixed=true` for `Sub.p` for all `Sub` elements in an array. See the below MWE.

### Steps to Reproduce
```
model test_each_fixed
  model Sub
    Real p;
  end Sub;
  // gives Translation Error Non-array modification ‘true‘ for array component 
  // ‘fixed‘, possibly due to missing ‘each‘.
  //Sub sub1[6](p(start=linspace(0.0, 1.0, 6), fixed=true));
  
  // fair enough, let's add an "each":
  
  // gives Translation Warning 'each' used when modifying non-array element p.
  Sub sub2[6](p(start=linspace(0.0, 1.0, 6), each fixed=true));
  
  // works, but having to use an explicit fill instead of each seems wrong
  //Sub sub3[6](p(start=linspace(0.0, 1.0, 6), fixed=fill(true,6)));
  
  // also generates the warning (probably could be expected)
  //Sub sub4[6](p.start=linspace(0.0, 1.0, 6), each p.fixed=true);
equation
end test_each_fixed;
```

### Expected Behavior
I have already [asked this on StackOverflow](https://stackoverflow.com/q/68812822/599884), and Hans has indicated that this should work without a warning. Do you agree?

Relevant standard section 7.5.2 https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#modifiers-for-array-elements

### Version and OS
This is using OpenModelica v1.18.0-dev.beta1 (64-bit) on Windows 10 64 bit

**Comment by perost** [comment]
The specification is ambiguous on whether `each` applies to the immediately enclosing array or if it can be used in a nested modifier as long as one of the modified elements is an array.

In OM we interpret it such that it only applies to the immediately enclosing array, i.e. in `a(b(each ...))` we say that `b` should be an array, but it seems like Hans interprets it to mean that it's also fine if `a` is an array when `b` is a scalar. I guess we could change OM to use the looser definition, we only give a warning right now anyway, but it would be good get some clarification.

**Comment by bilderbuchi** [comment]
Yeah, I think the salient point is how in this sentence
> The each keyword on a modifier requires that it is applied in an array declaration/modification

the "in" is interpreted. Arguably in `sub2` each is applied *in* (i.e., within) an array declaration/modification, just not directly as  `p()` is not an array declaration/modification.
Related https://github.com/modelica/ModelicaSpecification/issues/2630? I've read it, but now my head spins 😝

**Comment by casella** [comment]
@bilderbuchi, would you mind taking care of opening a request for clarification on the [ModelicaSpecification issue tracker](https://github.com/modelica/ModelicaSpecification/issues) and add a reference here? Otherwise this ticket is going to eventually get stale and die. Thanks!

**Comment by bilderbuchi** [comment]
Sure thing, see https://github.com/modelica/ModelicaSpecification/issues/3052

**Comment by perost** [comment]
The ticket for the specification has not been resolved yet, but it still seems clear that OM's interpretation is to strict. With the way we handle modifiers we can't really check this properly right now, so I've chosen to just remove the warning for now since applying `each` on a scalar doesn't actually cause any issues anyway. So it's better to just ignore it for now instead of giving false warnings.
