### ISSUE TITLE
Delay operator not working as expected when dealing with discontinuous equations

### ISSUE THREAD

**Issue by SVVS-KOUNDINYA** [OpenModelica/OpenModelica#7792]
### Description
**Delay** operator **not working as expected** when dealing with **discontinuous equations**

### Steps to reproduce
take any sort of discontinuous equation and assign the delayed version of that equation to a new variable. 
Observation: While the original equation is discontinuous, the delay function isn't. 

We really 💖 minimal working examples. With these reproducing a bug is straightforward and we can respond faster.

Example minimalExample.mos:

```Modelica
model Delay_Bug
  Real x;
  Real y;
equation
  x  = if time<0.5 then 1 else time;
  y = delay(x,0.1);
end Delay_Bug;
```

### Expected behavior
The discontinuity of x at time=0.5 is expected to be caught by the delay function at time=0.6 which isn't happening. Y is continuous, despite x being discontinuous
### Screenshots
![image](https://user-images.githubusercontent.com/89289705/130312633-d76e45f7-a333-424f-8c3f-4142f625e775.png)

### Version and OS
Connected to OpenModelica v1.17.0 (64-bit)
Connected to OMSimulator v2.0.0.post284-gc8ec782-mingw
Windows10

**Comment by casella** [comment]
@SVVS-KOUNDINYA did you try this with the 1.18.0-beta.1 release?

**Comment by AnHeuermann** [comment]
I worked a bit on re-implementing the delay operator. It's not finished yet, but should (mostly) solve this as well. This partikular issue is already solved on my branch but I still need to fix one or two others.

**Comment by AnHeuermann** [comment]
Related ticket #7536.

**Comment by SVVS-KOUNDINYA** [comment]
> @SVVS-KOUNDINYA did you try this with the 1.18.0-beta.1 release?

No, I haven't. Been using the stable release since the start. Will try this. Thanks

**Comment by casella** [comment]
@SVVS-KOUNDINYA I understand from @AnHeuermann that 1.18.0 doesn't yet address this. Please monitor #7536 and try the nightly build once it's merged in

**Comment by casella** [comment]
@AnHeuermann, @rfranke, what about increasing the default value right away? I'm not sure why 500 was used, but we may as well put 5000, or 10000 there.

**Comment by rfranke** [comment]
The reported error is exactly the interval length of 1/500=0.002s -- reduced to 1/5000=0.0002s in my reply. The delay operator would need to replay events to get exact discrete changes out of it.
However, many examples do already increase the number of intervals in their experiment settings -- certainly also for other reasons. Also the daily library tests introduce more intervals in many cases, I guess to improve verification results. This is why a larger default value might be sensible.

**Comment by AnHeuermann** [comment]
I don't think changing the number of simulation intervals is a good idea. It will slow down the simulation problems while not improving the plotted solution in OMEdit (outside of this ticket) and the simulation error is not affected by this, but the given tolerance.

Increasing the intervals on a model is a good workaround for this issue, but not the general solution. I have a branch for it and only need to fix some remaining problems.

**Comment by sjoelund** [comment]
The delay operator doesn't trigger events, so I think we have a correct solution at the moment (according to the language). Dymola has the slope to the left of t=0.6 and we have it to the right.

**Comment by SVVS-KOUNDINYA** [comment]
> The reported error is exactly the interval length of 1/500=0.002s -- reduced to 1/5000=0.0002s in my reply. The delay operator would need to replay events to get exact discrete changes out of it.
> However, many examples do already increase the number of intervals in their experiment settings -- certainly also for other reasons. Also the daily library tests introduce more intervals in many cases, I guess to improve verification results. This is why a larger default value might be sensible.

**Comment by SVVS-KOUNDINYA** [comment]
The reported code is just a sample to explain the issue I'm facing with the operator.
I have to use this operator to catch the delay of the variable while keeping the interval length at 5 (requirement of the code).
The variable is discontinuous and I need this discontinuity to be caught to make the results viable.
I have attached my actual code for reference.

model Pop_GDPp_ODE_M9

  Real Pop;
protected
  Real GDPp (start = 1);
  Real BR;
  Real DR;    
  Real GDP;
  
  Modelica.Blocks.Tables.CombiTable1Ds US(columns = {2, 3, 4, 5}, extrapolation = Modelica.Blocks.Types.Extrapolation.LastTwoPoints, smoothness = Modelica.Blocks.Types.Smoothness.ContinuousDerivative, table = [1970, 212, 0.0173, 0.0093, 4.7; 1975, 222, 0.0154, 0.0092, 5.5; 1980, 233, 0.0145, 0.0086, 6.4; 1985, 244, 0.0151, 0.0086, 7.2; 1990, 256, 0.0153, 0.0087, 8.7; 1995, 270, 0.0151, 0.0086, 9.9; 2000, 286, 0.0139, 0.0084, 12.1; 2005, 299, 0.0137, 0.0083, 14.1; 2010, 313, 0.0135, 0.0080, 15.3; 2015, 324, 0.0123, 0.0081, 16], tableOnFile = false)  annotation(
    Placement(visible = true, transformation(origin = {-38, 68}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  
  Real D_Pop;
protected  
  Real GAT;
  Real GG;
  Real BRG;
  Real DRG;
  Real Af;
  Real D_GDPp;
  Real D_GAT;

  Real D_BR;
  Real D_DR;

  
algorithm



  D_GDPp := delay(GDPp,5);
  D_GAT := delay(GAT,5);
  D_Pop := delay(Pop,5);
  D_BR := delay(BR,5);
  D_DR := delay(DR,5);


if time<2015 then

  US.u := time;
  Pop := US.y[1]; 
  BR :=US.y[2]; 
  DR := US.y[3];   
  GDP := US.y[4];
  GDPp :=(10 ^ 6*GDP / Pop );
  GAT :=(GDPp - D_GDPp)/D_GDPp/5;
  Af := 1;
  DRG := 0; 
  BRG :=0;  
  GG :=0; 
 
else

  GG :=(9 * exp(-0.07 * (D_GDPp / 1000)) - 6 * exp(-0.3 * D_GDPp / 1000)) / 100;
  GAT := (D_GAT - (D_GAT - GG)*5/20);
  GDPp := D_GDPp + D_GDPp * GAT * 5;
  BRG := ((0.8 + 3*exp(-1*GDPp/(1000*5)))/100); 
  BR :=(D_BR - (D_BR - BRG)*5/20);  
  Af := (exp(0.008 * (time - 2015)));  
  DRG := (((0.8 + 1.5*exp(-1*GDPp/(1000*2)))/100)*Af);
  DR :=(D_DR - (D_DR - DRG)*5/30);   
  Pop :=(D_Pop + D_Pop*BR*5 - D_Pop*DR*5);  
  GDP := GDPp*Pop/1000000;

 end if;
 
  annotation(
    experiment(StartTime = 1970, StopTime = 2050, Tolerance = 1e-06, Interval = 5),
    uses(Modelica(version = "4.0.0")));

end Pop_GDPp_ODE_M9;

**Comment by SVVS-KOUNDINYA** [comment]
> The reported error is exactly the interval length of 1/500=0.002s -- reduced to 1/5000=0.0002s in my reply. The delay operator would need to replay events to get exact discrete changes out of it.
> However, many examples do already increase the number of intervals in their experiment settings -- certainly also for other reasons. Also the daily library tests introduce more intervals in many cases, I guess to improve verification results. This is why a larger default value might be sensible.


The attached example is just a sample to explain my issue with the delay operator.
My code actually requires the interval length to be exactly 5 and the variables that I use in my code are discontinuous and I need this discontinuity to be caught by the delay operator to get viable results.

**Comment by casella** [comment]
@AnHeuermann, do you think you'll have time to deal with this for the 1.19.0 release? If so, can you please add it to https://github.com/OpenModelica/OpenModelica/projects/3?

**Comment by AnHeuermann** [comment]
> @AnHeuermann, if you eventually find time to upgrade the delay() implementation, please also consider its vectorization, see #7996.

It's not really related to what is happening in #8150

**Comment by casella** [comment]
No, it isn't, but it would be nice to eventually have delay() properly implemented according to the standard 😅
