### ISSUE TITLE
Fresh install, but i get error with some Modelica Example

### ISSUE THREAD

**Issue by Nico-Hard** [OpenModelica/OpenModelica#7793]
### Description
Using a fresh install of OpenModelica.
I have issue **with several examples** provided in the modelica library.

### Steps to reproduce
- Open file example in Modelica>Electrical>Batteries>Examples>CCCV_StackRC
Then Simulate.

I get the errors :
```
[1] 19:59:16 Translation Warning
[Modelica.Electrical.Batteries.BatteryStacks.CellRCStack: 14:26-14:33]: 'each' used when modifying non-array element v.

[2] 19:59:16 Symbolic Error
Too few equations, under-determined system. The model has 983 equation(s) and 1013 variable(s).

[3] 19:59:16 Symbolic Error
[Modelica.Electrical.Batteries.Examples.CCCV_StackRC: 54:3-57:22]: stack.stackBus.cellBus.T = busTranscription.stackBus.cellBus.T has size 1 but 0 variables ()
```

### Expected behavior
A simulation of the example...

### Version and OS
 - OpenModelica Version 1.18
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
@Nico-Hard, we are aiming at providing 100% success rate for the Modelica Standard Library, but we're still not there.  What you experience is expected, see the [coverage report](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) of the MSL 4.0.0 with the current development version, as you can see there are still about 20 models out of 514 that have some issues. Most of them are related to complex model structures involving arrays.

The situation will be further improved with the 1.19.0 release at the beginning of 2021
