### ISSUE TITLE
$cse variables lack scaling information

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7800]
Scaling information of unknowns is essential for the robust solution of nonlinear systems, as discussed [here](scaling). The nominal attribute can be used to provide such information. When function calls are involved, the `wrapFunctionCalls` module adds extra `$cse` variables that contain the result of such function calls, to avoid calling them multiple time with the same arguments. Unfortunately, such `$cse` variables do not have a nominal value, which is problematic in case they are selected as iteration variables for the nonlinear solver. For example, in the following MWE
```
model TestCSE
  Real x(nominal = 1e3), y(nominal = 1e2), z(nominal = 1e1);
equation
  (y+1) * sin(z) = time;
  sin(x) - y + z + x = time;
  sin(x)*sin(z) + y = time;
end TestCSE;
```
OMC selects `$cse6 = sin(x)` as tearing variable, and has no scaling information for it. In this specific case, `sin(x)` has order of magnitude one, so that is no big deal, but in other cases the result of the function might as well have order of magnitude 1e-10 or 1e12, and that would be a problem.

A simple way to solve this issue is to _force all $cse variables to be torn_, which in general makes sense, since their defining equation is explicit by construction.

In case one wanted to deal with these systems properly when tearing is switched off, then a scaling value for the $cse variable could be obtained by means of sensitivity analysis, by computing the Jacobian of the function and then taking the norm of the vector obtained by multiplying each element of the Jacobian by the nominal attribute of the corresponding variable. However, this is a bit involved, so I guess the tearing-based solution would be the best, since tearing is already implemented.

I would then suggest to include the `$cse` variables among the tearing variables even in the case `--tearingMethod=minimalTearing`. This would mean that the Newton solver still sees all the original unknowns of the problem, but not the auxiliary ones, which are only introduced to compute the residuals more efficiently, avoiding unnecessary repeated computations.

This issue is somwhat related to #7704, though it is in some sense the opposite.

**Comment by casella** [comment]
@AndreaBartolini provided the original motivation for this issue

**Comment by casella** [comment]
@phannebohm, thanks for #8049! Apparently, it had a [quite positive impact](https://libraries.openmodelica.org/branches/history/master/2021-10-30%2004:09:07..2021-10-31%2010:14:17.html) on the library testsuite. There are some regressions, but I understand you already know the cause of at least some of them.

@AndreaBartolini, #8049 partially addresses the issue you raised originally. Can you please check with your test cases and report here?

**Comment by AndreaBartolini** [comment]
I've tested the models for that the previous nightly build generated $cse as iteration variables and (in the same models) the current nightly build calculate all the $cse variables as assignments or torn variables.

Thanks :)

**Comment by phannebohm** [comment]
> Apparently, it had a [quite positive impact](https://libraries.openmodelica.org/branches/history/master/2021-10-30%2004:09:07..2021-10-31%2010:14:17.html) on the library testsuite.

Seems so. But I have become hesitant since we found those inconsistencies in the reports. :sweat_smile:

> There are some regressions, but I understand you already know the cause of at least some of them.

I have no clue what causes the regressions, except the obvious: randomly bad or missing nominal values for the newly chosen tearing variables. We often have `$cse1 = sin(x)` so the default nominal value of `1.0` is reasonable, that may have helped in some cases.

**Comment by phannebohm** [comment]
Some things are not done yet:
1. minimalTearing still operates as before, ignoring $cse variables. I will work on that now so that they will be treated like discrete variables.
2. Array- or record-cse are not touched by this. The reason is the following situation
(see ThermoSysPro.Examples.SimpleExamples.TestStaticCondenser.mos)
```
Variables (12)
========================================
1: $cse17.d:VARIABLE(min = max(1e-09, 0.0) max = 100000.0 start = 900.0 nominal = 998.0 protected = true )  type: Real unreplaceable
2: $cse17.duph:VARIABLE(protected = true )  type: Real unreplaceable
3: $cse17.x:VARIABLE(protected = true )  type: Real unreplaceable
4: $cse17.ddph:VARIABLE(protected = true )  type: Real unreplaceable
5: $cse17.s:VARIABLE(min = -1000000.0 max = 1000000.0 nominal = 1000.0 protected = true )  type: Real unreplaceable
6: $cse17.duhp:VARIABLE(protected = true )  type: Real unreplaceable
7: $cse17.ddhp:VARIABLE(protected = true )  type: Real unreplaceable
8: $cse17.u:VARIABLE(min = -100000000.0 max = 100000000.0 nominal = 1000000.0 protected = true )  type: Real unreplaceable
9: condenseur.Pex:VARIABLE(min = max(0.0, max(0.0, 0.0)) start = 100000.0 unit = "Pa" nominal = 100000.0 )  "Drain pressure at the outlet" type: Real
10: $cse17.cp:VARIABLE(min = 1e-09 max = 9.999999999999999e+59 nominal = 1000.0 protected = true )  type: Real unreplaceable
11: $cse17.T:VARIABLE(min = 200.0 max = 6000.0 start = 288.15 nominal = 320.0 protected = true )  type: Real unreplaceable
12: condenseur.Hex:VARIABLE(start = 500000.0 unit = "J/kg" )  "Drain specific enthalpy at the outlet" type: Real

Equations (3, 12)
========================================
1/1 (1): condenseur.Hex = if noEvent($cse17.d > 0.0) then condenseur.Hsate + (condenseur.Pex - condenseur.Pcond) / $cse17.d else condenseur.Hsate   [dynamic |0|0|0|0|]
2/2 (10): $cse17 = ThermoSysPro.Properties.WaterSteam.IF97.Water_Ph(condenseur.Pex, condenseur.Hex, condenseur.mode_ex)   [unknown |0|0|0|0|]
3/12 (1): condenseur.Pex = condenseur.Pcond + 9.806649999999999 * $cse17.d * condenseur.z   [dynamic |0|0|0|0|]
```
I suppose choosing `condenseur.Hex` and `condenseur.Pex` would tear the system nicely so that the record `$cse17` becomes the inner variable(s). For some reason though the tearing heuristics get into trouble here. I am currently trying to go thorough the exact reasoning.
Another observation, `condenseur.Hex` has no nominal value but some of the components of `$cse17` have.
So I'm wondering, should I leave those $cse variables alone or try to treat them like the scalar ones?

**Comment by casella** [comment]
> I have no clue what causes the regressions, except the obvious: randomly bad or missing nominal values for the newly chosen tearing variables.

OK, but this shouldn't be a cause to reject the commit - we should rather improve the nominal attribute propagation, see [#4515](https://trac.openmodelica.org/OpenModelica/ticket/4515).

> We often have `$cse1 = sin(x)` so the default nominal value of `1.0` is reasonable, that may have helped in some cases.

However, using as intermediate value a periodic function of some other unknowns is probably not such a good idea :)

**Comment by casella** [comment]
> Some things are not done yet:
> 
>     1. minimalTearing still operates as before, ignoring $cse variables. I will work on that now so that they will be treated like discrete variables.

Looking forward to it.

>     2. Array- or record-cse are not touched by this. The reason is the following situation
>        (see ThermoSysPro.Examples.SimpleExamples.TestStaticCondenser.mos)
> 
> 
> ```
> Variables (12)
> ========================================
> 1: $cse17.d:VARIABLE(min = max(1e-09, 0.0) max = 100000.0 start = 900.0 nominal = 998.0 protected = true )  type: Real unreplaceable
> 2: $cse17.duph:VARIABLE(protected = true )  type: Real unreplaceable
> 3: $cse17.x:VARIABLE(protected = true )  type: Real unreplaceable
> 4: $cse17.ddph:VARIABLE(protected = true )  type: Real unreplaceable
> 5: $cse17.s:VARIABLE(min = -1000000.0 max = 1000000.0 nominal = 1000.0 protected = true )  type: Real unreplaceable
> 6: $cse17.duhp:VARIABLE(protected = true )  type: Real unreplaceable
> 7: $cse17.ddhp:VARIABLE(protected = true )  type: Real unreplaceable
> 8: $cse17.u:VARIABLE(min = -100000000.0 max = 100000000.0 nominal = 1000000.0 protected = true )  type: Real unreplaceable
> 9: condenseur.Pex:VARIABLE(min = max(0.0, max(0.0, 0.0)) start = 100000.0 unit = "Pa" nominal = 100000.0 )  "Drain pressure at the outlet" type: Real
> 10: $cse17.cp:VARIABLE(min = 1e-09 max = 9.999999999999999e+59 nominal = 1000.0 protected = true )  type: Real unreplaceable
> 11: $cse17.T:VARIABLE(min = 200.0 max = 6000.0 start = 288.15 nominal = 320.0 protected = true )  type: Real unreplaceable
> 12: condenseur.Hex:VARIABLE(start = 500000.0 unit = "J/kg" )  "Drain specific enthalpy at the outlet" type: Real
> 
> Equations (3, 12)
> ========================================
> 1/1 (1): condenseur.Hex = if noEvent($cse17.d > 0.0) then condenseur.Hsate + (condenseur.Pex - condenseur.Pcond) / $cse17.d else condenseur.Hsate   [dynamic |0|0|0|0|]
> 2/2 (10): $cse17 = ThermoSysPro.Properties.WaterSteam.IF97.Water_Ph(condenseur.Pex, condenseur.Hex, condenseur.mode_ex)   [unknown |0|0|0|0|]
> 3/12 (1): condenseur.Pex = condenseur.Pcond + 9.806649999999999 * $cse17.d * condenseur.z   [dynamic |0|0|0|0|]
> ```
> 
> I suppose choosing `condenseur.Hex` and `condenseur.Pex` would tear the system nicely so that the record `$cse17` becomes the inner variable(s). 

Absolutely! Using the whole record as iteration variable is really terrible from the point of view of efficiency.

> For some reason though the tearing heuristics gets into trouble here. I am currently trying to go thorough the exact reasoning (there might be a bug hiding in there).

I guess so. I understand the underlying problem is that you have some kind of Schroedinger's indetermination between a record as an atomic input or output of functions and the same record as a container of related quantities. I'm not sure how you deal with it in the tearing algorithm. To me, an equation with the structure
```
<somerecord> = <somefunction>(<var1>, <var2>, ..., <varN)
```
strongly suggests to use `<somerecord>` as an inner variable for tearing, for the obvious reason that its content is in general related to (and oftentimes of higher dimensionality than) a few scalar variables, so you should better avoid splitting it up into its many components, each playing a role in some residual equation.

Could you add that rule to the tearing algorithm?

**Comment by casella** [comment]
> Another observation, `condenseur.Hex` has no nominal value but some of the components of `$cse17` have. So I'm wondering, should I leave those $cse variables alone or try to treat them like the scalar ones?

No, I think in this case we should infer the nominal value. In this case Hex has a defined start attribute, which is not the default of zero. This means the library developer clearly has some definite idea about the order of magnitude of that variable. If it is not possible to infer the nominal attributes from other sources (e.g. from some alias variable), than we should definitely infer it from the start attribute.

**Comment by casella** [comment]
> To me, an equation with the structure
> 
> ```
> <somerecord> = <somefunction>(<var1>, <var2>, ..., <varN)
> ```
> 
> strongly suggests to use `<somerecord>` as an inner variable for tearing, for the obvious reason that its content is in general related to (and oftentimes of higher dimensionality than) a few scalar variables, so you should better avoid splitting it up into its many components, each playing a role in some residual equation.
> 
> Could you add that rule to the tearing algorithm?

I'm even more convinced that this heuristic could be useful in many cases, and I'd definitely try it out.

**Comment by casella** [comment]
@phannebohm, this issue is almost done except for the record = functioncall() part. Do you think that is doable in a short time?

**Comment by phannebohm** [comment]
I can't really tell. But if I don't fix it by the end of next week it will have to wait until Christmas.

**Comment by casella** [comment]
OK. My goal is to avoid having countless, almost-finished open tickets, because it becomes messy. We can close this one, because the original issue is fixed in most cases, an then open a new one on the specific case of records.
