### ISSUE TITLE
Issue with variability in Buildings 7.0.1

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7834]
Please check [Buildings.Controls.Predictors.Examples.BESTEST](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.Controls.Predictors.Examples.BESTEST.err). The NF reports
```
[Buildings 7.0.1/ThermalZones/Detailed/Validation/BESTEST/Cases6xx/Case600FF.mo:96:7-96:25:writable]
Error: Component glaSys of variability parameter has binding '{window600}[<datConExtWin, 1>]' of higher variability continuous.
```
@perost, is this a NF bug or an issue with the source code?

**Comment by perost** [comment]
This was fixed in the library in lbl-srg/modelica-buildings#2555, but we need a new release of Buildings to pick up the fix in our testing. With the fix the model passes the frontend, but fails in the backend with the `Internal error function createSimCode failed` error.

**Comment by casella** [comment]
See https://github.com/lbl-srg/modelica-buildings/issues/2555#issuecomment-921332654

**Comment by perost** [comment]
Fixed, [see report](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.Controls.Predictors.Examples.BESTEST.err). The model now fails due to #7999 instead.
