### ISSUE TITLE
Variability issues in Buildings 7.0.1

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7839]
Please check [Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.err). The NF reports
```
[Buildings 7.0.1/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo:327:5-374:55:writable] 
Error: Function argument name=nameConExt[i] in call to Buildings.ThermalZones.Detailed.BaseClasses.CFDSurfaceIdentifier
has variability discrete which is not a parameter expression.
```
@perost is this a NF bug or an issue with the source code?

Same issue with [Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Examples.FFD.NaturalConvectionWithControl.err) and other similar models

Similar issue with [Buildings.ThermalZones.Detailed.FLEXLAB.Rooms.Examples.X3AWithRadiantFloor](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.FLEXLAB.Rooms.Examples.X3AWithRadiantFloor.err) and [Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Validation.BESTEST.Cases6xx.Case600FF.err), but the supposed variability is continuous instead of discrete

**Comment by casella** [comment]
@JayHuLBL, @mwetter, I had a closer look at this issue, which is breaking several Buildings model with OMC.

Function [assignSurfaceIdentifier](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo#L264) has an [input String nameConExt[nConExt]](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo#L292), which in general has variablity discrete, as all String variables.

This discrete input is then assigned as an input argument for the constructor of a [CFDSurfaceIdentifier](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo#L329) record. This record [is declared](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDSurfaceIdentifier.mo#L4) to have a `parameter String name "Name of the surface";` element. 

Of course this can't work _in general_, because a discrete variable cannot be passed to a constructor of an array of fixed parameters. In some special cases, if you pass parameters to the `assignSurfaceIdentifier()` function, this may be possible, and this may be the reason why Dymola accepts it, but from a language theory point of view this is not legal, and I understand OMC has all the rights to complain.

I would suggest that you remove the `parameter` prefixes from the definition of the CFDSurfaceIdentifier. I tried this with Dymola and the first two mentioned models still simulated with the same results. OMC fails for other reasons, but that's another story.

**Comment by perost** [comment]
> This discrete input is then assigned as an input argument for the constructor of a [CFDSurfaceIdentifier](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDAirHeatMassBalance.mo#L329) record. This record [is declared](https://github.com/lbl-srg/modelica-buildings/blob/983943166acf64b31fa0a5c4693c630272b9bfe3/Buildings/ThermalZones/Detailed/BaseClasses/CFDSurfaceIdentifier.mo#L4) to have a `parameter String name "Name of the surface";` element.

This is actually fine, because the variability prefixes should be removed when constructing the record constructor. OMC does not currently do that because it causes some issues, which I'm currently working on solving.

**Comment by casella** [comment]
In any case, I opened three PR's on LBL's repo to remove it from the library, a quick check with Dymola showed no difference, though @JayHuLBL may want to double-check. If that fixes the problem, we should focus on other NF issues first.

**Comment by perost** [comment]
> In any case, I opened three PR's on LBL's repo [#2618](https://github.com/lbl-srg/modelica-buildings/pull/2618), [#2619](https://github.com/lbl-srg/modelica-buildings/pull/2619), and [#2620](https://github.com/lbl-srg/modelica-buildings/pull/2620) to remove them from the library, a quick check with Dymola showed no difference. Let's see what LBL's CI thinks about it.

It shouldn't break the examples in Buildings itself, since the record is only used as a parameter anyway. It could break user models though if they use the record differently, but I don't know if that's a valid concern or not.

**Comment by casella** [comment]
> It shouldn't break the examples in Buildings itself, since the record is only used as a parameter anyway. 

But it does, see the [report](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.err). Do I miss something?

**Comment by perost** [comment]
> > It shouldn't break the examples in Buildings itself, since the record is only used as a parameter anyway.
> 
> But it does, see the [report](https://libraries.openmodelica.org/branches/master/Buildings_7.0.0/files/Buildings_7.0.0_Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.err). Do I miss something?

No, I mean that your proposed change wouldn't break the examples. Since the record is always used like
```Modelica
parameter CFDSurfaceIdentifier cfd;
```
all the fields become parameters anyway.

**Comment by casella** [comment]
Aha, OK, sure. That's actually what I thought, but I couldn't find those declarations myself.

According to LBL's Travis reports, [it didn't break 8.0.x](https://github.com/lbl-srg/modelica-buildings/pull/2619). The 7.0.x version is not tested. The version on master [gave some errors](https://github.com/lbl-srg/modelica-buildings/pull/2618), but I guess my PR is not the culprit.

**Comment by mwetter** [comment]
@casella : I understand that String are discrete variables, but once a string is declared as parameter, shouldn't the parameter variability be a stronger constraint? Also, here parameters are assigned to parameters via a function call, so I am not sure I understand where the possible language violation arises.

For this class, I am fine to merge the PR's as a user is not expected to use `CFDSurfaceIdentifier` directly.

Please let me know if I should go ahead and merge the PRs in view of this discussion.

**Comment by casella** [comment]
> @casella : I understand that String are discrete variables, but once a string is declared as parameter, shouldn't the parameter variability be a stronger constraint?

Yes, but this declaration is outside the body of the function `assignSurfaceIdentifier`, and I think the compiler checks variability locally based on the function input declaration, not only based on what you actually pass it when you call it.

On the other hand, @perost wrote that in fact the parameter prefixes should be ignored in the constructor, that he was fixing it, but had some difficulties. I don't know which part of the specification says that, though I trust his judgement.

In any case, if you merge the PRs into the library we'll get better coverage right away, which is our main goal, so I would suggest to go ahead with that.

@perost can take care of the prefix stripping afterwards, and focus on more urgent things, or just go on with it if he's almost done.

**Comment by casella** [comment]
[Problem solved](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.ThermalZones.Detailed.Examples.FFD.ForcedConvection.err) after the 7.0.x branch was updated. 

Now the model fails in the backend, but that is another story.
