### ISSUE TITLE
Ensure proper implementation of Clocked variable semantics

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7842]
### Description

The current implementation of Clocked variables semantics is incorrect. As a result, many test cases produce wrong results, see e.g. the verification results of the following libraries

- [MSL 4.0.0](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html), Modelica.Clocked.Examples.*
- [Modelica_Synchronous](https://libraries.openmodelica.org/branches/master/Modelica_Synchronous/Modelica_Synchronous.html)

### Expected Behavior

All clocked models in MSL 4.0.0 and Modelica_Synchronous should run and produce correct results.

**Comment by rfranke** [comment]
@casella: the Cpp runtime uses the same frontend and produces correct results in all except one questionable case (https://github.com/modelica/ModelicaStandardLibrary/issues/3858).
This is why this appears not to be an issue of the frontend, but of the C runtime.

**Comment by casella** [comment]
@rfranke, I guess I made some mistakes reading the reports, sorry.

Regarding `Modelica.Clocked` we can compare the [Modelica_trunk](https://libraries.openmodelica.org/branches/master/Modelica_trunk/Modelica_trunk.html) and [Modelica_trunk_cpp](https://libraries.openmodelica.org/branches/master/Modelica_trunk_cpp/Modelica_trunk_cpp.html) reports. There are 17 models failing verification with the C runtime and 2 models failing with the cpp runtime. One of them is `Modelica.Clocked.Examples.Elementary.ClockSignals.LogicalSample`, which is mentioned inthe MSL ticket, the other one is `Modelica.Clocked.Examples.CascadeControlledDrive.SubClocked`, where PI.y is delayed by 2 ms by both runtimes. Not sure what is the root cause of that. 

Regarding Modelica_Synchronous we can compare the [Modelica_Synchronous]() and [Modelica_Synchronous_cpp](https://libraries.openmodelica.org/branches/master/Modelica_Synchronous_cpp/Modelica_Synchronous_cpp.html) reports. There are 14 models failing the verification with the C runtime and only 3 failing the verification with the cpp runtime, producing the same wrong results with both runtimes.

This fundamentally confirms your analysis, with two exceptions. I'll open separate follow-up tickets.

**Comment by casella** [comment]
Regarding the issue with Modelica.Clocks, it seems a problem with the testing environment, see #7852. 

Regarding the issues with Modelica_Synchronous, the reference results appear to be completely wrong, also compared to a simulation I just ran in Dymola. I'll check with @GallLeo
