### ISSUE TITLE
Impossibile to run OMEdit 1.8.0-beta1

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7862]
### Description
On a PC I've uninstalled, trhough uninstall.exe, a previous OM installation, and installed a neq one in the following location:
E:\OM\OM1.18.0-beta1-64bit
So no spaces, no special characters in thepath..
When I try to run any model I get:
```sh
E:/OM/OM1.18.0-beta1-64bit/share/omc/scripts/Compile.bat EVbasic msvc15 mingw64 parallel dynamic 8 0
PATH = "E:\OM\OM1.18.0-beta1-64bit\tools\msys\mingw64\bin;E:\OM\OM1.18.0-beta1-64bit\tools\msys\mingw64\bin\..\..\usr\bin;"
mingw32-make: Entering directory 'E:/OM_Work/EVPkg2021eng.EVbasic'
cl /FeEVbasic.exe EVbasic.c EVbasic_functions.c EVbasic_records.c EVbasic_01exo.c EVbasic_02nls.c EVbasic_03lsy.c EVbasic_04set.c EVbasic_05evt.c EVbasic_06inz.c EVbasic_07dly.c EVbasic_08bnd.c EVbasic_09alg.c EVbasic_10asr.c EVbasic_11mix.c EVbasic_12jac.c EVbasic_13opt.c EVbasic_14lnz.c EVbasic_15syn.c EVbasic_16dae.c EVbasic_17inl.c EVbasic_18spd.c  /MP /Od /ZI /EHa /fp:except /I"E:/OM/OM1.18.0-beta1-64bit/include/omc/c" /I"E:/OM/OM1.18.0-beta1-64bit/include/omc/msvc/" /I. /DNOMINMAX /TP /DNO_INTERACTIVE_DEPENDENCY /DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME  /MD /link /NODEFAULTLIB:libcmt /STACK:0x2000000 /pdb:"EVbasic.pdb" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib//omc/msvc/" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib//omc/msvc/release/" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib//omc/cpp/msvc/" /LIBPATH:"E:/OneDrive - University of Pisa/2_MODELICA/VEI/PE/1 BasicBatEV"  /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib//omc" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib/" /LIBPATH:"C:/Users/pc1/AppData/Roaming/.openmodelica/binaries/Modelica" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib/omlibrary/Modelica 3.2.3/Resources/Library/mingw64" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib/omlibrary/Modelica 3.2.3/Resources/Library/win64" /LIBPATH:"E:/OM/OM1.18.0-beta1-64bit/lib/omlibrary/Modelica 3.2.3/Resources/Library" ModelicaExternalC.lib ModelicaStandardTables.lib ModelicaIO.lib ModelicaMatIO.lib zlib.lib f2c.lib initialization.lib libexpat.lib math-support.lib meta.lib results.lib simulation.lib solver.lib sundials_kinsol.lib sundials_nvecserial.lib util.lib lapack_win32_MT.lib lis.lib  omcgc.lib user32.lib pthreadVC2.lib wsock32.lib cminpack.lib umfpack.lib amd.lib
/usr/bin/sh: cl: command not found
mingw32-make: *** [EVbasic.makefile:46: EVbasic.exe] Error 127
mingw32-make: Leaving directory 'E:/OM_Work/EVPkg2021eng.EVbasic'
Compilation process failed. Exited with code 0x00000002.
```

So I cannot run any model.

### Steps to Reproduce
I don't know. On my work PC the steps are just as explained above; in another one I did not have any issue.

### Expected Behavior
Files should run

### Screenshots
![image](https://user-images.githubusercontent.com/37046832/131985380-1b41e88d-f669-4acd-9655-52b69489c42a.png)

### Version and OS
1.18.0-beta2, Windows 10, 54 bit

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by mahge** [comment]
It seems OMEdit is trying to use the _Microsoft C++ compiler_ by default. `cl.exe` is the MSVC compiler. For now, as a workaround, you can change it to use the `MinGW g++` version that comes with OMEdit. 

I think the option is at _Options->Simulation_, then change Target Build to `MinGW` from the dropdown menu. Hopefully it fixes it until @adeas31 gets here.

**Comment by max-privato** [comment]
> It seems OMEdit is trying to use the _Microsoft C++ compiler_ by default. `cl.exe` is the MSVC compiler. For now, as a workaround, you can change it to use the `MinGW gcc/g++` versions that comes with OMEdit itself.
> 
> I think the option is at _Options->Simulation_, then change _Target Build_ to `MinGW` from the dropdown menu. Hopefully, it fixes it until @adeas31 gets here.

It worked, thank you!
I don't know when and how I did change the compiler (and settings are retained between different installations): this is a PC I've not used for months.
In fact, the PC with the issue does have visual studio, but not exactly in the default place: it is on disk E: instead of C:.

Your suggestion did solve the issue for me.
I' don't close the ticket right now, so you can evaluate whether in cases like this the error message could say something similar to what you said in your message here. If possible, this could help any other that, like me, falls in a similar case.

**Comment by casella** [comment]
@max-privato, when in doubt, you can reset all the options to factory settings: Tools | Options menu, then hit the "Reset" button and confirm in the dialog window.

**Comment by max-privato** [comment]
Thanks.
Maybe I could have tried this, but I, instead thought the issue was coming from an incorrect previous uninstallation.
