### ISSUE TITLE
Download link from openmodelica.org for windows is broken

### ISSUE THREAD

**Issue by sergniko** [OpenModelica/OpenModelica#7865]
### Description

Download link for new release on https://openmodelica.org/download/download-windows points to https://build.openmodelica.org/omc/builds/windows/releases/1.18/0/ and results in 404 error - not found.

https://build.openmodelica.org/omc/builds/windows/releases/1.18/ has no "final" directory.

### Steps to Reproduce

Go to https://openmodelica.org/download/download-windows and click on 
<html>
<body>

Official Release | 1.18.0(32bit/64bit)
-- | --

</body>
</html>
 link.

**Comment by adrpo** [comment]
The builds were ongoing, now they are there already.
