### ISSUE TITLE
Can't plot a variable along pipe component

### ISSUE THREAD

**Issue by yildirimilh** [OpenModelica/OpenModelica#7878]
### Description
It is not possible to plot a variable(ex: Reynolds Number) along a pipe element for each calculation node. There was an empty tick box nest to the variable name in Plotting window in previous versions of OMEdit. When you check that box, it was possible to plot the variable with indices as x-variable in the plot. I have installed OM v1.18.0 today and run some test cases. I realized that there is no check box to plot all the variables (see attachment).

### Steps to reproduce
Run a simple Modelica.Fluid simulation involving pipe element and check result variables like Reynolds Number.

### Version and OS
 - OpenModelica Version v1.18.0 (64-bit)
 - MSL 4.0.0 
 - OS: Windows 10, 64 bit
![Capture4](https://user-images.githubusercontent.com/90286126/132412321-2329e807-6aaa-495a-8426-07fd1e81c7aa.PNG)

**Comment by casella** [comment]
@adeas31, is there any reason why this feature was removed?

**Comment by adeas31** [comment]
This feature is not removed. I didn't handle it well when I changed to read variables from `model_init.xml` and then comparing variables against the result file. This should work fine again after #7879.

**Comment by casella** [comment]
@adeas31, could you also port this to maintenance/v.18, so we have it in 1.18.1?

Thanks!

**Comment by adeas31** [comment]
Ported to maintenance/v.1.18

**Comment by casella** [comment]
@yildirimilh you can get this fix either on the nightly build, or in the forthcoming 1.18.1 stable release, due later this year.
