### ISSUE TITLE
Empty result arrays in pipe simulation with heat transfer

### ISSUE THREAD

**Issue by yildirimilh** [OpenModelica/OpenModelica#7880]
### Description
There are some empty result variables in Plotting perspective Variables Browser. These variable names, such as **Nu_1, Nu_2, Nus_lam, Nus_turb, Xis**, were not available in previous versions of the OMEdit. They became available with v1.18.0 but without any value. 

### Steps to Reproduce
Any simple simulation of Modelica.Fluid pipe element with heat transfer and LocalPipeFlowHeatTransfer HTC correlation will produce the outcome.

### Version and OS
OpenModelica Version v1.18.0 (64-bit)
MSL 4.0.0
OS: Windows 10, 64 bit

### Additional Context
It is good to have those results variables though for plotting :)

![Capture5](https://user-images.githubusercontent.com/90286126/132475041-bd3d1c95-c4a7-41ee-bbd6-a24425dbd038.PNG)

**Comment by adeas31** [comment]
Can you provide a model with example? I am guessing these are string type variables/arrays that are not possible to plot but is useful for re-simulation with modified value.

**Comment by yildirimilh** [comment]
model singlePipeHT
  replaceable package Medium = Modelica.Media.Water.StandardWater;

  inner Modelica.Fluid.System system(energyDynamics = Modelica.Fluid.Types.Dynamics.SteadyState, p_ambient(displayUnit = "Pa")) annotation(
    Placement(visible = true, transformation(origin = {-180, 180}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

  Modelica.Fluid.Pipes.DynamicPipe pipe1a(redeclare model FlowModel = Modelica.Fluid.Pipes.BaseClasses.FlowModels.DetailedPipeFlow(show_Res = true, from_dp = false), redeclare model HeatTransfer = Modelica.Fluid.Pipes.BaseClasses.HeatTransfer.LocalPipeFlowHeatTransfer, redeclare package Medium = Medium, T_start = 293.15, diameter = 0.05, length = 10, nNodes = 25, roughness = 2.500000000000001e-05, use_HeatTransfer = true) annotation(
    Placement(visible = true, transformation(origin = {0, 120}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));

  Modelica.Fluid.Sources.Boundary_pT pressure_sink(redeclare package Medium = Medium, T = 20 + 273.15, nPorts = 1, p = 101325) annotation(
    Placement(visible = true, transformation(origin = {80, 120}, extent = {{10, -10}, {-10, 10}}, rotation = 0)));
  Modelica.Fluid.Sources.MassFlowSource_T massFlow_source(redeclare package Medium = Medium, T = 20 + 273.15, m_flow = 2.5, nPorts = 1) annotation(
    Placement(visible = true, transformation(origin = {-80, 120}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Thermal.HeatTransfer.Sources.FixedHeatFlow fixedHeatFlow[pipe1a.nNodes](Q_flow = 200000 * pipe1a.dxs, T_ref = 293.15 * ones(pipe1a.n), alpha = 0 * ones(pipe1a.n)) annotation(
    Placement(visible = true, transformation(origin = {0, 170}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));

equation
  connect(massFlow_source.ports[1], pipe1a.port_a) annotation(
    Line(points = {{-70, 120}, {-10, 120}}, color = {0, 127, 255}));
  connect(pipe1a.port_b, pressure_sink.ports[1]) annotation(
    Line(points = {{10, 120}, {70, 120}}, color = {0, 127, 255}));
  connect(fixedHeatFlow.port, pipe1a.heatPorts) annotation(
    Line(points = {{0, 157}, {0, 124}}, color = {191, 0, 0}, thickness = 0.5));
  annotation(
    uses(Modelica(version = "4.0.0")),
    Diagram(coordinateSystem(extent = {{-200, -200}, {200, 200}}, grid = {1, 1}, initialScale = 0.1)),
    Icon(coordinateSystem(extent = {{-200, -200}, {200, 200}}, grid = {1, 1}, initialScale = 0.1)),
    version = "");
end singlePipeHT;

**Comment by yildirimilh** [comment]
Hi, I just copied the simple model that I used to check. I don't why I coudln't upload the *.mo file. Below is the screen shot of the location where the mentioned variables are described.
Regards,

![image](https://user-images.githubusercontent.com/90286126/132821490-f811c06e-85c3-4ff9-ad3b-252dcdfba8f2.png)

**Comment by casella** [comment]
@yildirimilh GitHub does not accept attachments that [it doesn't recognize](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files). You can change the extension from `.mo` to `.txt`

**Comment by adeas31** [comment]
Thanks for the test model. I looked in the code and these variables are marked protected so is not possible to plot them. That is why you don't see a checkbox next to them. In the previous versions so simply hide such variables but in the latest version these variables are shown but without the possibility to plot them.
