### ISSUE TITLE
InitImpureRandom: passing ID isn't working properly in discrete step

### ISSUE THREAD

**Issue by Kjaldyo** [OpenModelica/OpenModelica#7888]
### Description
We currently have a problem with initializing ImpureRandom when passing the ID into another model/function etc.

Assumption: Init isn't recocknized within discrete step.

We try to initializeImpureRandom and give the resulting ID into a function in which we are calling impureRandom/impureRandomInteger. When doing so following error will raise as soon as impureRandom is executed:
![image](https://user-images.githubusercontent.com/90654043/133159667-3731ccb2-cdd7-4e5e-becf-ca584c742993.png)

Modelica.Math.Random.Utilities.initializeImpureRandom
Modelica.Math.Random.Utilities.impureRandom

Modelica Version: 4.0.0

### Steps to reproduce
To reproduce please use following script:

In here we have two cases: 

_1. Function:_ GiveRandomWithOutsideInit (Id) --> isn't working
_2. Function:_ GiveRandomWithInsideInit --> is working

```
model Random
  import impureRandom = Modelica.Math.Random.Utilities.impureRandom;
  import initializeImpureRandom = Modelica.Math.Random.Utilities.initializeImpureRandom;
  Integer id;
  Real randomIsntWorking;
  Real random;

  function GiveRandomWithOutsideInit
    input Integer id;
    output Real randomNumber;
    algorithm
      randomNumber := impureRandom(id);
  end GiveRandomWithOutsideInit;
  
  function GiveRandomWithInsideInit
    output Real randomNumber;
    Integer id;
    algorithm
      id := initializeImpureRandom(1);
      randomNumber := impureRandom(id);
  end GiveRandomWithInsideInit;
  
equation

  id = initializeImpureRandom(1);
  when sample(0, 0.001) then
    randomIsntWorking = GiveRandomWithOutsideInit(id);
    random = GiveRandomWithInsideInit();
  end when;
  
end Random;
```

### Expected behavior
Simulation isn't aborted and impureRandom is returning random Reals

### Version and OS
 - OpenModelica Version: **OpenModelica v1.17.0 (64-bit)**
 - Library: **Modelica Version: 4.0.0**
 - OS: **Win 10 (64bit)**

**Comment by sjoelund** [comment]
`initializeImpureRandom` is an impure function. When you call it, it sets the random seed for all `impureRandom` calls. For each sample, you are setting the random seed to be `1`, which means you will always get the same number returned.
What you want is
```mo
model Random
  import impureRandom = Modelica.Math.Random.Utilities.impureRandom;
  import initializeImpureRandom = Modelica.Math.Random.Utilities.initializeImpureRandom;
  Integer id;
  Real random;

  
equation

  when initial() then
    id = initializeImpureRandom(1);
  end when;
  when sample(0, 0.001) then
    random = impureRandom(id);
  end when;
  
end Random;
```

Or using the pure random functions instead (Modelica.Math.Random.Generators).
