### ISSUE TITLE
OMEdit crashes when loading Air library (Modelica.Media) 

### ISSUE THREAD

**Issue by cmosercm** [OpenModelica/OpenModelica#7900]
When loading the Air library (Modelica.Media)  OMEdit gets stuck at Modelica.Media.Air.ReferenceMoistAir and crashes afterwards 

![omedit_load_air_error](https://user-images.githubusercontent.com/90772718/133436370-6ea673c4-85a0-47e8-881e-d009736ee4a4.PNG)

Windows Event log viewer (sorry it is in german):

Name der fehlerhaften Anwendung: OMEdit.exe, Version: 0.0.0.0, Zeitstempel: 0x61337b76
Name des fehlerhaften Moduls: ntdll.dll, Version: 10.0.19041.1110, Zeitstempel: 0xe7a22463
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000000a2097
ID des fehlerhaften Prozesses: 0x4074
Startzeit der fehlerhaften Anwendung: 0x01d7aa2e851b49e4
Pfad der fehlerhaften Anwendung: C:\Program Files\OpenModelica1.18.0-64bit\bin\OMEdit.exe
Pfad des fehlerhaften Moduls: C:\Windows\SYSTEM32\ntdll.dll
Berichtskennung: 07858213-1f39-4a3e-a99a-0043b7f97899
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

Operating System: Windows 10
notebook:  intel i7 6 core  32 Gb ram

**Comment by cmosercm** [comment]
Sorry, i forgot:   Openmodelica 1.18.0 (64-bit)

**Comment by casella** [comment]
Unfortunately this a known issue, see [#5669](https://trac.openmodelica.org/OpenModelica/ticket/5669) we haven't been able to fix it so far. I'll try to increase its priority.

**Comment by perost** [comment]
I can't replicate the crash, but opening Air is really slow. I've fixed it locally by implementing `getInheritedClasses` in the new API, which should fix the crash that some people are encountering too.

I need to push in another fix first though, and it seems our CI is having some issues at the moment. But this issue should hopefully be resolved soon.

**Comment by casella** [comment]
Great! 😄

**Comment by perost** [comment]
Fixed in #7905, so the fix should be in the next nightly build.

**Comment by casella** [comment]
@cmosercm, when you install the nightly please check that the build date is 17 Sep or later.
