### ISSUE TITLE
 Setting to export CVODE CS FMU in OMEdit

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#7920]
### Description

I would like to have an option to export CS FMUs with CVODE to make it more straight forward to use this feature from OMEdit.
Something like a checkbox added to FMI options in OMEdit would be enough. So when that checkbox is active all CS FMUs exported will use compiler flag `--fmiFlags=s:cvode`.

### Screenshots

![image](https://user-images.githubusercontent.com/38031952/134160881-4afd7f39-948b-43a7-b8a5-092fbabb8a8c.png)

Adding something like `Export CVODE to Co-Simuataion` in the screenshot above would be great.

### Additional Context

Users are stumbling about the option to export CVODE but don't know how to use it, see e.g. https://openmodelica.org/forum/default-topic/3352-how-to-export-fmu-co-sim-using-cvode#p11118.

**Comment by casella** [comment]
Good point. @adeas31, can we do this for 1.19.0?

**Comment by Arinomo** [comment]
@AnHeuermann Thank you for the ticket.

Maybe i might add one point, analog to #7472, could the translation flag for cvode solver in model annotation automatically implemented when the user export the model as an fmu regardless of the golbal settings?

**Comment by AnHeuermann** [comment]
I think it would be best to use flags as sparse as possible in the GUI. If possible we should hide all needed flags in some menu or option. The debug, compiler and runtime flags are hard to find for a lot of users and the differences between them are not always obvious.
But I don't have a strong opinion on this.

Also we might need to make omc use the flags used in the Simulation Setup dialog from OMEdit and not only the global used flags (from  Tools->Options->Simulation->Additional Translation Flags).
![image](https://user-images.githubusercontent.com/38031952/134299583-727787e7-7329-4414-8358-b72b0d2945c5.png)

**Comment by adeas31** [comment]
@AnHeuermann I looked at [--fmiflags](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmiflags) are there are several possible options for it. Do you just want to support `s:cvode` for now or do you want to support all possible options? If yes, then what are the possible options? Is there a list of them somewhere?

**Comment by AnHeuermann** [comment]
The initial idea was to pass several options to FMUs, but currently only the solver can be changed. So I guess it would be enough to just support this one for now.

**Comment by AnHeuermann** [comment]
Now that I think about it again a drop-down menu would be best to set the CS FMU solver. There are already two options (explicit Euler = no flag, CVODE=--fmiFlags=s:cvode) and we might want to add more solvers, like an implicit Euler.

**Comment by adeas31** [comment]
OK. I will make a PR and let you review it.
