### ISSUE TITLE
Global name lookup fails to display class in diagram

### ISSUE THREAD

**Issue by wischhusen** [OpenModelica/OpenModelica#7921]
Class references with a dot notation according to Modelica Spec. chap. 5.3.3 are not displayed. 

model GlobalLookup

  .Modelica.Blocks.Examples.PID_Controller pID_Controller annotation(
    Placement(visible = true, transformation(origin = {-2, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

annotation(
    uses(Modelica(version = "3.2.3")));
end GlobalLookup;

### Expected behavior
Should be visible in diagram.

### Version and OS
 - OpenModelica Version 1.7.0 
 - Win 10

**Comment by casella** [comment]
@sjoelund.se, this is simply unforgivable 😄 

Any idea what's going wrong? I guess the interactive API was not updated to allow this?

**Comment by sjoelund** [comment]
Yeah, @adeas31 can find out where it goes wrong. But it might be problematic in several places of the API

**Comment by casella** [comment]
@wischhusen is this important for the support of your libraries?

**Comment by wischhusen** [comment]
The funny thing was, that the models can be compiled. It just looks odd in some of the libraries examples, were red crosses appear. 
Nevertheless, I believe that users of HumanComfort might not proceed to use these examples. From a commercial point of view it looks like a quality flaw although it is not relevant for simulation. Thus, I would say: yes it is important.

**Comment by casella** [comment]
OK. @adeas31 can you provide a quick assessment of the required effort?

**Comment by adrpo** [comment]
I will also have a quick look a this, maybe I can find the issue quickly.

**Comment by adeas31** [comment]
We should update `getComponents` API or OMEdit accordingly. I am not sure what happens in the case of relative paths. I will investigate it.

**Comment by adeas31** [comment]
This is working as expected. I tested with the latest version and then noticed that @wischhusen reported version 1.7.0 which was released in 2017. Maybe he meant 1.17.0

This is the same issue that is reported in #7378 and is already fixed.
