### ISSUE TITLE
OMedit message browser z-position

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#7925]
### Description
The message browser, when docked, for me, spoils too of precious desktop space. Therefore, after any simulation, I close it. This behaviour is a bit annoying.
I tried using that window undocked. In this case, however, the message browser window is in front of any other (and this is correct), but stays in that position even after I click on the main OMEdit window, i.e. in the plotting perspective area (this is what I would like to avoid).
To close the message browser we must go with the mouse pointer on its "x" button on top-left, and click. This is significantly slower than just clicking the mouse without moving it.

So what I propose is a tiny modification that will produce a small but useful result:

_To avoid keeping the the message browser window fixed on top of all the other ones_. I mean when it is displayed it should be on top, but when I click elsewhere on the main OMedit window it should go below the others

### Steps to Reproduce
1) run any model 
2) if not already undocked, undock the message browser
3) ran again any model (or re-simulate) 
4) click anywhere on the OMEdit main window 
=> the message browser is still visible on top of all the other windows.

### Expected Behavior
See description

### Version and OS

 - OpenModelica Version: 1.18.0
 - OS:  Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
> To avoid keeping the the message browser window fixed on top of all the other ones. I mean when it is displayed it should be on top, but when I click elsewhere on the main OMedit window it should go below the others

This is not possible. The Messages Browser is a QDockWidget that is part of QMainWindow. Since the Messages Browser is a child of MainWindow so its not possible to put it under.

**Comment by max-privato** [comment]
> > To avoid keeping the the message browser window fixed on top of all the other ones. I mean when it is displayed it should be on top, but when I click elsewhere on the main OMedit window it should go below the others
> 
> This is not possible. The Messages Browser is a QDockWidget that is part of QMainWindow. Since the Messages Browser is a child of MainWindow so it's not possible to put it under.

...unless it is changed into an independent window (inherited from QWidget). But in this case it would lose the capability of being docked. Maybe it used to be an independent window and you switched to docked recently? I don't remember to have hated the Message Browser during the past!

The thing is that when programmers design enhancements or new features, they look at things trying to envisage how working with a feature will be. Then, during real live one works with it, maybe he finds that something that seemed brilliant is indeed clumsy.

I don't know if other users share my opinion that having to continuously close the message window or let it always stole precious desktop space is bad. In case they don't, this ticket should obviously be rejected.

BTW: after a lot of usage I find the recent change of the gridlines colour into gray, as a solution to another ticket, a very good improvement!

**Comment by adeas31** [comment]
> ...unless it is changed into an independent window (inherited from QWidget). But in this case it would lose the capability of being docked. Maybe it used to be an independent window and you switched to docked recently? I don't remember to have hated the Message Browser during the past!

Yes it is changed recently from independent window to dock window. I don't remember if there was any specific issue reported about it perhaps @lochel does.
