### ISSUE TITLE
PowerGrids regression due to initialization issue

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#7928]
All models in PowerGrids simulated correctly with v 1.18.0, one model now fails on master, see [overview report](https://libraries.openmodelica.org/branches/overview-combined.html).

The culprit is [PowerGrids.Examples.Tutorial.GridOperation.Controlled.ControlledGridWithReferenceCalculationSat](https://libraries.openmodelica.org/branches/master/PowerGrids/files/PowerGrids_PowerGrids.Examples.Tutorial.GridOperation.Controlled.ControlledGridWithReferenceCalculationSat.sim)

which fails at runtime with
```
assert            | debug   | Solving non-linear system 322 failed at time=0.
|                 | |       | For more information please use -lv LOG_NLS.

```
we should identify and fix the regression. Maybe we can now use @mahge's script or @sjoelund's grep to figure out why this happened.

**Comment by mahge** [comment]
Some of the PowerGrids models stopped simulating here
https://libraries.openmodelica.org/branches/history/master/2021-07-18%2022:50:57..2021-08-12%2019:12:22.html

and all of them except the one in this ticket started working again here
https://libraries.openmodelica.org/branches/history/master/2021-08-19%2012:17:07..2021-08-19%2022:55:54.html

The fact that they started working here implies that they probably started failing due to 773d98e4a9 which, indirectly, made it an error to have repeated simulation flags. 

PowerGrids contains ___OpenModelica_simulationFlags_ annotations with [lv=LOG_STATS](https://github.com/PowerGrids/PowerGrids/search?l=Modelica&q=log_stats). These combined with our testing scripts give (for the models that have the annotation) command lines like this 

`PowerGrids_PowerGrids.Controls.Test.TestDerivativeLag -abortSlowSimulation -alarm=480   -lv=LOG_STATS -s=dassl -lv LOG_STATS`

`lv` specified twice which became an error with 773d98e4a9  and was allowed again with ec5d97160f.


Here is the kicker:
It is **most probable** these models did not actually simulate at all before that point and just returned exit code 0 without actually simulating.

**Comment by casella** [comment]
> It is **most probable** these models did not actually simulate at all before that point and just returned exit code 0 without actually simulating.

Uh-oh.

I just tried this manually on `v1.19.0-dev-187-g12eb8cf` with some more logging, and indeed it fails during initialization. The lambda = 0 step is successful, then the next step at lambda = 0.3333 fails.

I haven't tried this with OMC 1.18.0, because uninstalling and reinstalling it takes quite some time, but I'm afraid @mahge's diagnostic is probably right, i.e., this model has probably been broken for a long time.

I am pretty sure it worked back in 2018, because of course during the library development we ran simulation manually and checked the simulation results, but I can't be 100% sure about that. That means finding the offending commit (if any) is probably going to be hopeless. 

We should probably also provide reference results for verification, to avoid this issue. Unfortunately, providing small enough but yet significant verification sets of variables is a non-trivial task, so that's not somthing I can take care of now. If the plot annotations make it into the standard, then we could add them for demonstrational purposes, and then we could simply use those variables to automatically produce the reference trajectories.

**Comment by mahge** [comment]
For what it is worth, this are the only changes for this model in the reports

http://libraries.openmodelica.org/branches/history/master/2020-07-03%2023:04:09..2020-07-07%2005:22:51.html
http://libraries.openmodelica.org/branches/history/master/2020-12-14%2003:04:35..2020-12-14%2022:49:53.html
http://libraries.openmodelica.org/branches/history/master/2021-07-18%2022:50:57..2021-08-12%2019:12:22.html  

As you said it is not possible to pinpoint an exact commit of failure for this model. We can try to see if it was actually working during the times it was considered passing. 

A good starting point would be to try and see if it works exactly at 97adc965d8. If it does now work there then it probably never did.

**Comment by casella** [comment]
> For what it is worth, this are the only changes for this model in the reports
> 
> http://libraries.openmodelica.org/branches/history/master/2020-07-03%2023:04:09..2020-07-07%2005:22:51.html
> http://libraries.openmodelica.org/branches/history/master/2020-12-14%2003:04:35..2020-12-14%2022:49:53.html
> http://libraries.openmodelica.org/branches/history/master/2021-07-18%2022:50:57..2021-08-12%2019:12:22.html

Not much relevant information there IMO.

> As you said it is not possible to pinpoint an exact commit of failure for this model. We can try to see if it was actually working during the times it was considered passing.
> 
> A good starting point would be to try and see if it works exactly at [97adc96](https://github.com/OpenModelica/OpenModelica/commit/97adc965d88d03e88e1dd156cdda34fb01ec9675). If it does now work there then it probably never did.

That's one point for checking. I would also try it out with a much earlier version, much closer to the point the library was first rolled out. I would try 1.13.1 for example, it should have been working back then. If it did, then I would do bisection over [homotopy-related PRs](https://github.com/OpenModelica/OpenModelica/pulls?page=1&q=is%3Apr+is%3Aclosed+homotopy).

@mahge, you wrote me that you can compile OMC from scratch in 3 minutes with the Legion laptop, would you mind trying this out when you have some spare time?

**Comment by casella** [comment]
Some more intel on this issue. I ran `ControlledGridWithReferenceCalculationSat` with the latest nigtly, turning on LOG_NLS_V, LOG_INIT, and LOG_INIT_HOMOTOPY. Here is what I get:
```
homotopy process
---------------------------
homotopy parameter lambda = 0
...
homotopy parameter lambda = 0 done
---------------------------
homotopy parameter lambda = 0.333333
############ Solve nonlinear system 178 at time 0 ############
############ Solve nonlinear system 212 at time 0 ############
...
############ Solve nonlinear system 240 at time 0 ############
############ Solve nonlinear system 322 at time 0 ############
Start Kinsol solver at time 0
...
kinsol failed for system 322
[module] KINSOL | [function] KINSol | [error_code] -11
The linear solver's setup function failed in an unrecoverable manner.
KINSol finished with errorCode -11.
The kinls setup routine (lsetup) encountered an error. Retry with numerical Jacobian.
...
Solution status: FAILED
 number of iterations           : 5
 number of function evaluations : 82
 number of jacobian evaluations : 11
```
So, the initialization works at lambda = 0, when there are no control saturations. As soon as they are introduced in the first nonzero-lambda homotopy step, there is something wrong with the system, probably some kind of singularity. This also happens if I substantially reduce the continuation trajectory step size, e.g., by setting `-ils=1000`.

I also tried to simulate the model with Dymola, and it also fails there.

The involved nonlinear system is a non-trivial one with conditional expressions. It may turn out there is actually something wrong in how those conditions were written down, though I find it strange that we didn't notice it back then. I'll investigate more

**Comment by casella** [comment]
OK, I had a look at the issue, also using Dymola, and it looks like the root cause is in a bad formulation of the initialization problem, rather than in the solver, see [PowerGrids #40](https://github.com/PowerGrids/PowerGrids/issues/40).

We can now close this issue for good, 1.18.0 should be good enough to simulate this model, once it's been fixed.
