### ISSUE TITLE
Problems installing in Ubuntu Focal

### ISSUE THREAD

**Issue by r-a-c** [OpenModelica/OpenModelica#7930]
### Description

When I install openmodelica, dependency problems occur

### Steps to Reproduce
Create the repo file with the line according docs

```
/etc/apt/sources.list.d/openmodelica.list 
deb https://build.openmodelica.org/apt focal release
```

Then, just launch the installation
```

apt-get install openmodelica
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 openmodelica : Depende: omc (< 20000) pero no va a instalarse
                Depende: omshell (< 20000) pero no va a instalarse
                Depende: omshell-terminal (< 20000) pero no va a instalarse
                Depende: omnotebook (< 20000) pero no va a instalarse
                Depende: drmodelica (< 20000) pero no va a instalarse
                Depende: drcontrol (< 20000) pero no va a instalarse
                Depende: omedit (< 20000) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

```

### Expected Behavior

A clean install?

### Version and OS

Ubuntu Focal, up to date.

**Comment by sjoelund** [comment]
You will need to try installing one of the other packages (like omc) to see which dependencies will not be satisfied.

**Comment by r-a-c** [comment]
Hello,

I have been following the dependency chain, and looks like this one causes the problem:





```

Los siguientes paquetes tienen dependencias incumplidas:
 libc6-i386 : Depende: libc6 (= 2.31-0ubuntu9.2) pero 2.31-0ubuntu9.3 va a ser instalado
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

```

The chain:

omc -> clang -> clang-10 -> libclang-common-10-dev -> This one has 3 dependencies

 ```
libclang-common-10-dev : 

                          Depende: lib32gcc-s1 (>= 4.2) pero no va a instalarse
                          Depende: lib32stdc++6 (>= 4.1.1) pero no va a instalarse
                          Depende: libc6-i386 (>= 2.17) pero no va a instalarse

```


The last one is dependency for the first two too. Full log:

 ```
apt-get install libc6-i386
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 libc6-i386 : Depende: libc6 (= 2.31-0ubuntu9.2) pero 2.31-0ubuntu9.3 va a ser instalado
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.
```

So it looks like in the repos 0ubuntu9.3 is present when that package needs 0ubuntu9.2 
Mmmm.  Bad problem. This box has no personalization regarding packages, as far as I know. (In this box I only use official repo's software)

Right now the web for ubuntu's packages does not work, so I can not check it.

Apt says:

```
apt show libc6
Package: libc6
Version: 2.31-0ubuntu9.3
Status: install ok installed
```


Today i tried with this 
https://stackoverflow.com/questions/66507866/how-to-install-openmodelica-1-9-5-on-ubuntu-20-04

Same result.

**Comment by sjoelund** [comment]
Are you running a 32-bit Ubuntu Focal? It's not even supported by Canonical, right? I suspect you need to `apt dist-upgrade` though, because we compile against the most recent Ubuntu versions (like 20.04.3 instead of 20.04.0)

**Comment by r-a-c** [comment]
Hello,

No, it's x86_64, updated.

uname -a
Linux xxxxxx 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

(Last kernel)

As far as I know there are no 32 bit releases anymore for Ubuntu. But you can find i386 libraries for development purposes.

**Comment by r-a-c** [comment]
Hello,

If anyone reaches this issue, probably  it's a problem with the repos

https://askubuntu.com/questions/1315906/unmet-dependencies-libc6-the-package-system-is-broken
https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1926918

If you properly update your system, you'll find yourself with this issue, since the 0ubuntu9.3 was removed from the repos.

Than

**Comment by sjoelund** [comment]
Yes it's an upstream bug, so I'll close this
