### ISSUE TITLE
Do not use internal headers of Kinsol 

### ISSUE THREAD

**Issue by mahge** [OpenModelica/OpenModelica#7959]
### Description

The CPP runtime uses the header `kinsol_impl.h` in [KinsolLapack.h](https://github.com/OpenModelica/OpenModelica/blob/7b42f0ac3e92fc25caf75079b180c165d7720e36/OMCompiler/SimulationRuntime/cpp/Solver/Kinsol/KinsolLapack.h#L8)

_kinsol_impl.h_ is an internal header and is not installed by sundials. We are installing it manually. While this should work fine for now it is better to fix it since 
  - This means we will not be able to use system Sundials anymore.
  - It should also be relatively easier to fix since Kinsol actually has the interface to specify the linear solver [Here](https://github.com/OpenModelica/OMCompiler-3rdParty/blob/296fd3d988a2d04111850cf4759abc14c67d5cc3/sundials-5.4.0/include/kinsol/kinsol_ls.h#L72)

If this is an easy fix then it should be done so as not to modify Sundials internals.

**Comment by AnHeuermann** [comment]
When I updated Kinsol I did not find a good replacement for this function that uses `kinsol_impl.h`. But I didn't search for long.

I can check again, maybe next week.

**Comment by AnHeuermann** [comment]
It seems that `KINLapackCompletePivoting` is not used by anything.
I could only find a section in [Kinsol.cpp#L492-L527](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Solver/Kinsol/Kinsol.cpp#L492-L527) where it is commented out.

So my suggestion would be to just remove the unused parts and then revert [5e5e4c2f1f24d99822defaf7b1da995b7e6eec72](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/5e5e4c2f1f24d99822defaf7b1da995b7e6eec72).

@niklwors and @rfranke: Or do you plan to use Kinsol with complete pivoting from the C++ runtime in the future?
While it probably would be possible to update that section to work in the by SUNDIALS recomended way to add your own linear solver to KINSOL I don't think it is worth the effort.

**Comment by AnHeuermann** [comment]
OpenModelica should not longer be using internal Sundials headers. So now it should be possible to use the systems Sundials.

**Comment by mahge** [comment]
Thanks. This is good. While we will not remove sundials anytime soon at least we can (maybe?) start thinking about source code FMUs with sundials with a lot less of a complication.

**Comment by niklwors** [comment]
> 
> 
> It seems that `KINLapackCompletePivoting` is not used by anything. I could only find a section in [Kinsol.cpp#L492-L527](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/OMSICpp/runtime/src/Solver/Kinsol/Kinsol.cpp#L492-L527) where it is commented out.
> 
> So my suggestion would be to just remove the unused parts and then revert [5e5e4c2f1f24d99822defaf7b1da995b7e6eec72](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/5e5e4c2f1f24d99822defaf7b1da995b7e6eec72).
> 
> @niklwors and @rfranke: Or do you plan to use Kinsol with complete pivoting from the C++ runtime in the future? It would probably be possible to update that section to work in the by SUNDIALS recomended way. But I don't think it is worth the effort.

I think we do not need it.
