### ISSUE TITLE
OMEdit crashes if a simulation fails or is canceled

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#8008]
### Description

It can be frustrating if a model fails numerically; it's really bad if additionally the whole simulation tool crashes in such a case.
Recent versions of OMEdit tend to crash more often, not even asking if a crash report should be sent anymore. Unfortunately it's not deterministic. 

I took some time to drill this down to the function `omc_new_matlab4_reader` and then saw commit 81537a472c9f54ea14ecf335343005f18f4e83af -- Add omc_fread() to wrap fread() by @mahge.

The former version of `read_matlab4.c` was checking for errors of `fread` and generating specific error messages, such as "Corrupt header" or "Could not read, names matrix". The current version calls `omc_fread` instead, bypassing any own error checks with long jumps and the generic new error message "omc_fread() failed to read file".

OMEdit only catches the long jumps when opening a results file manually -- but doesn't report any specific error message anymore. OMEdit does not catch the long jumps after simulations or when running animations. It just crashes.

https://github.com/OpenModelica/OpenModelica/blob/3a728b8cffa2898eb11448c56e67dc92f861c5ef/OMCompiler/SimulationRuntime/c/util/omc_file.c#L62-L77

### Steps to Reproduce

Use OMEdit, in particular with models that fail. Best crash rate obtained with Cpp runtime for MSL trunk and `Modelica.Electrical.Analog.Examples.Lines.LightningLosslessTransmissionLine`.

### Expected Behavior

OMEdit should show error messages and keep running. In the case of "Cancel Simulation", OMEdit should keep running and present the results obtained so far.

### Possible Solutions

1. Revert the changes for those cases that did it right before, such as `read_matlab4.c`. Alternatively the last call argument `allow_early_eof` of `omc_fread` could be changed from 0 to 1, but this still would leave a crash of OMEdit if `ferror(stream)`. 
2. Or, check existing uses of the affected functions and make sure the new errors are caught and treated appropriately.

**Comment by mahge** [comment]
I agreed to remove the throw here. 
> I will change the throw to be an assert instead and hopefully that helps for now.
https://github.com/OpenModelica/OpenModelica/issues/8008#issuecomment-945654638

Then again we also discussed it in the meeting and I said I will remove the throw and instead return the actual error code.

I am sorry that this affected you. But I am not sure what more I can do.

I will answer most of your questions in another comment.

**Comment by mahge** [comment]
> There are more examples, where commit 81537a472c9f54ea14ecf335343005f18f4e83af replaces existing specific error tests, e.g.
https://github.com/OpenModelica/OpenModelica/blob/81537a472c9f54ea14ecf335343005f18f4e83af/OMCompiler/Compiler/runtime/systemimpl.c#L428-L438

Error message changed from "Failed to read the entire file" to a more descriptive error telling you why it failed, i.e., not enough data in the file or some other error. I do not see what the problem is here. It continues to throw.

**Comment by rfranke** [comment]
OMEdit used to generate a message like -- File -> Open Results File(s):
```
[1] 11:34:23 Scripting Error
Failed to open simulation result LightningLosslessTransmissionLine_res.mat: Corrupt header (1)
```
A user might ask a developer who then knows that the first read operation for a matrix in the results file `LightningLosslessTransmissionLine_res.mat` failed.

With your commit the message for the same error changed to
```
[1] 11:45:15 Scripting Notification
Error reading stream: unexpected end of file
Expected to read 1. Read only 0
assert            | debug   | Error: omc_fread() failed to read file
```
Not even a developer can infer the circumstances of the error anymore!!!

Here is the code for your picked error message that is disabled at the moment:
```c
    name = (char*) malloc(hdr.namelen);
    nr = omc_fread(name,hdr.namelen,1,reader->file, 0);
    if(nr != 1) {
      free(name);
      return "Corrupt header (2)";
    }
```
Another new memory leak for `name` as `omc_fread` does not return but throws a long jump.

**Comment by rfranke** [comment]
I took a lot of time to find the code causing the new crashes and the reason is exactly that it throws because "**you wanted to read strictly n bytes**". The proposed replacement of a thrown error with assert would change from long jump to abort -- not solving the issue at hand "OMEdit crashes if a simulation fails or is canceled".
Yes, I'm determined if it comes to crashes and memory leaks -- and if I find ever more new bugs the longer I look at the introduced change. Arrogance is something else.
