### ISSUE TITLE
Bad presentation of results in Variables Browser

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#8009]
### Description

OMEdit does not allow to plot protected variables even upon selection of the simulation option "Output->Protected Variables". This is considered a bug. Moreover, the presentation of derivatives of arrays is bad. See the following example:
```modelica
model BadOMEditVariables
  input Real u(start = 1);
  Real x(start = 0);
  Real[2] v(start = {1, 2}) "this comment should appear with v";
protected
  Real y "should be shown and checkable with Output->Protected Variables";
equation
 der(x) = u;
 der(v) = {u, u} "der(v) should be shown as vector of its own";
 y = x;
 annotation(experiment(StopTime=1));
end BadOMEditVariables;
```
This gives in the Variables Browser:
<img src="https://user-images.githubusercontent.com/4224368/137677047-ebdc1dd6-66dc-44b1-ab24-f61bbd2c317c.png" width="70%"/>

Alternatively, with the simulation option "Output->Protected Variables":
<img src="https://user-images.githubusercontent.com/4224368/137677872-d68e27c7-4074-4eed-b79c-9015faca972f.png" width="70%"/>

### Steps to Reproduce

Run the above example `BadOMEditVariables`.

### Expected Behavior

**Protected variables**
They should not appear at all per default. They should appear with checkbox for plotting if "Output->Protected Variables" is enabled.

**Derivatives of arrays**
They might appear as entry on their own. Descriptions might better appear once with the array variables instead of multiple times with each element. 
```
+der(v)         der(this comment should appear with v)
   [1]     1
   [2]     1
+v              this comment should appear with v
   [1]     1
   [2]     2
```

### Version and OS

Current trunk version.

**Comment by adeas31** [comment]
#8031 fixes the display of protected variables. By default the protected variables are hidden. Protected variables are only shown when `Output->Protected Variables` is true OR if the protected variable has annotation `HideResult=false`. Note that the first case i.e., protected variables are only shown when `Output->Protected Variables` is true, is not working yet because we set `HideResult=true` by default for protected variables which is wrong, see #4346.

**Comment by casella** [comment]
@rfranke it seems all your concerned were addressed, so, I'm closing this ticket. If they weren't, feel free to reopen it and comment on what is still wrong.

**Comment by adeas31** [comment]
This is not done yet. The presentation of derivatives of arrays is still pending.
