### ISSUE TITLE
Diagram and Icon annotations are ignored in 1.19.0-dev

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8022]
### Description

Diagrams and icons annotations are ignored with the current dev-master version of omc

### Steps to Reproduce

- Load the attached model
- Open with OMEdit
- Show the diagram and icon layers: they should be rectangles, but they are not

### Expected Behavior

The annotations should be considered

### Additional Context

I guess something went wrong with the API recently, probably not more than one-two weeks ago. This issue probably causes other problems, such as icons in non-square or non-symmetric extents now being wrongly displayed. It is difficult to make MWEs of these other cases, so I'd fix this first
[TestExtent.zip](https://github.com/OpenModelica/OpenModelica/files/7379890/TestExtent.zip)
.

**Comment by adeas31** [comment]
Yes that is right. I think with your changes to `getStrings` the last empty part is not considered.
