### ISSUE TITLE
Update the class loader to use the package manager correctly

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8060]
We have now introduced GUI support for the package manager, which thus stop being a geek thing and will become mainstream from 1.19.0. We need to make sure that the class loader works consistently with it, otherwise we'll be in a mess.

As discussed with @sjoelund, the rationale of the package manager is described by the following points:
- We (the OSMC) select the OS libraries we want to support, discuss this with the developers, and classify different versions and builds in [this file](https://libraries.openmodelica.org/index/v1/index.json)
- We need to be able to manage, test, and install different builds of the same version of the same library, e.g. the MSL 4.0.0 and the patched version to be used in OMC, _which both have the same version annotation_, namely "4.0.0". This is currently not supported by the Modelica Specification, [Section 13.4](https://specification.modelica.org/maint/3.5/packages.html#mapping-package-class-structures-to-a-hierarchical-file-system) and [18.8](https://specification.modelica.org/maint/3.5/annotations.html#annotations-for-version-handling). 
- @sjoelund implemented a solution where the version number as defined in [18.8](https://specification.modelica.org/maint/3.5/annotations.html#annotations-for-version-handling) is optionally augmented according to [semver](https://semver.org/) with either a pre-release (starting with -)  or post-release (starting with +) metadata.
- The idea is that post-releases have precedence over the default one (hence "4.0.0+maint.omc" has precedence over "4.0.0"), while pre-releases such as "4.0.0-beta.01" have low priority and are superseded by regular and post-releases, even of previous versions.
- Additionally, we are collecting information from the `noneFromVersion` conversion annotations to figure out what is the most recent version of a certain library that is backwards compatible with another one, and should then be preferably installed and loaded instead.

I understand that all this information is already available via the API.  Referring to the Buildings library as an example, one can get a complete ordering of all the versions to figure out what are the most recent ones (ignoring backward compatibility), e.g.:
```
getAvailablePackageVersions(Buildings, "")
{"8.0.0","7.0.1","7.0.0","6.0.0","5.1.0","5.0.1","5.0.0","4.0.0","3.0.0","2.1.0","2.0.0",
 "1.6.0+build.1","1.5.0+build.3","1.5.0+build.2","1.5.0+build.1",
  "9.0.0-master","7.0.2-maint.7.0.x","2.0.0-rc.1","1.4.0-build1"}
```
If a certain package `XYZ` has a uses annotation referring to a specific version, the API function returns the versions which are compatible to it, ordered by priority, e.g.
```
getAvailablePackageVersions(Buildings, "7.0.0")
{"7.0.1","7.0.0","7.0.2-maint.7.0.x"}
```
In this case we see that the version which should be loaded is the first one, namely `7.0.1`, which is declared to be backwards compatible with `7.0.0` via the noneFromVersion conversion annotation. Version `7.0.2-maint.7.0.x` is tagged as pre-release (it has a minus in the build metadata), so it has lower priority. In fact, this refers to the HEAD/master revision on the maintenance branch, which will eventually be released as `7.0.2`, but is currently under development. We keep it on our package manager server for testing purposes, but it's not meant to be loaded by end-users, so it has low priority.

In case post-release builds are available, they get the precedence, e.g.

```
getAvailablePackageVersions(Buildings, "1.5.0")
{"1.5.0+build.3","1.5.0+build.2","1.5.0+build.1"}
```
in this case, the most recent build should be loaded, i.e., `1.5.0+build.3`

@perost, if I understood correctly, this is what the class loader should do:
- if a package has a uses annotation without specifying a version, it should load the version corresponding to the first element of the result of `getAvailablePackageVersions(<LibraryName>, "")` and give a notification about the loaded version
- if a package uses another package but has no uses annotation, it should probably do as in the previous case, except that we give it as a warning, because it may be completely wrong
- if a package has a uses annotation with a specified version, it should load the version corresponding to the first element of the result of `getAvailablePackageVersions(<LibraryName>, <version-number>)`. If the output of the API function call is an empty array, **we should not load another version** , because that is by definition not backwards compatible and will certainly lead to trouble. We should instead give an error, such as "Error: There is no installed version of library `<LibraryName>` compatible with version `<version_number>`. Please update the installed libraries with File | Upgrade Installed Libraries in OMEdit or directly with the package manager, and retry.

The third bullet point in particular ensures that we always get the most up-to-date installed version of any given package that can be used without running conversion scripts, based on the version annotation of the library that uses it.

@sjoelund, @adrpo, did I get this right?

**Comment by casella** [comment]
If that is the case, then maybe @mahge can have a look?

**Comment by mahge** [comment]
> even what the issue were trying to solve actually is

I am also not 100% sure but I did not want to pollute the discussion too much . 

I am guessing the issue is that 'uses' libraries are loaded immediately as they are seen. Instead what we probably want is to collect all 'uses' libraries recursively and load the versions we want after resolving the 'conflicts'. 

@casella Is this what we want?

**Comment by casella** [comment]
> I am guessing the issue is that 'uses' libraries are loaded immediately as they are seen. Instead what we probably want is to collect all 'uses' libraries recursively and load the versions we want after resolving the 'conflicts'.
> 
> @casella @sjoelund Is this what we want?

Yes. I guess we could do that using the information collected by the package manager.

**Comment by sjoelund** [comment]
The package manager installs a metadata file for each package, so we can get the uses of all installed packages (there may be versions not in the current package index). This+the index could be cached as a dependency graph if it needs to be done faster (not sure how long creating the graph takes if it needs to load and parse potentially hundreds of json-files). Using this graph, for all uses annotations on packages we are loading and the currently loaded packages: find the "best" set of libraries to load that satisfy all uses annotations of all loaded models/libraries. When installing packages, consider all packages available in the index. When loading packages, consider installed packages first and if there is no possible set, give a notification saying which package commands to run to install the required packages (and in OMEdit, I suppose make it link to or directly pop up a dialog asking if you want to install them).

**Comment by casella** [comment]
> As far as I am concerned, regular users should not depend on pre-releases, that's for developers and advanced users, that will most likely handle those pre-releases with their own local repos mirroring their fork for pull requests. Not as installed system libraries. It's fine if we use them for testing, but I don't think we should stress this use case.
> 
> In all other cases I understand that using the current implementation of getAvailablePackageVersions() for the class loader on a one-by-one basis would be good enough. For sure it would be better than what we have currently.

@perost, can you handle that in time for the 1.19.0 release?

**Comment by perost** [comment]
> @perost, can you handle that in time for the 1.19.0 release?

I made an attempt in #8821. Since the actual logic for loading libraries is done in external C code that I don't want to touch I changed the class loader to replace the requested versions with versions from the package manager.

So if you do e.g. `loadModel(Buildings, {"7.0.0"})` it will basically replace it with e.g. `loadModel(Buildings, {"7.0.2", "7.0.1", "7.0.0", "7.0.3-maint.7.0.x"}`. This seems to work as we want it to, but I'm really not sure how all of this is supposed to work.

**Comment by casella** [comment]
> This seems to work as we want it to, but I'm really not sure how all of this is supposed to work.

My requirement is very simply stated:
- the _package manager_ uses some sophisticated logic to determine what are the most up-to-date backwards-compatible versions of a library dependencies and installs them
- once those libraries are installed, the _package loader_ should use _exactly the same logic_ to load the most up-to-date backwards-compatible installed library.

Is that what happens now? If so, we can close this ticket 😃

**Comment by perost** [comment]
> Is that what happens now? If so, we can close this ticket smiley

I broke a lot of test cases, probably because they use libraries not managed by the package manager. I changed the logic to not replace requested versions for which the package manager returns an empty list, let's see if that works.

**Comment by perost** [comment]
My PR works fine with the changes I made, so I merged it. Please try it out and see if it fixes the issue.

**Comment by casella** [comment]
OK. I need to figure out a meaningful test case...

**Comment by casella** [comment]
Based on @perost [previous comment](https://github.com/OpenModelica/OpenModelica/issues/8060#issuecomment-1096446592), I understand the class loader should work fine, as long as it is requested to load libraries that are indeed managed by the package manager, because it uses the package manager API to figure out the most recently installed library which is backwards-compatible with the requested one.

Hence, we can close this ticket 😅 

There is one issue remaining, i.e. how to deal with libraries which are found in the MODELICAPATH but are not managed by the package manager, see #8883.
