### ISSUE TITLE
Implement basic support for conversion scripts in OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8061]
The implementation of conversion scripts is nearly complete and performing very well in tests. This means we should actually provide access to it via the OMEdit GUI, at least in some basic form, with the next 1.19.0 release. This would actually allow OMC users to switch to MSL 4.0.0, after more than a year from its release.

For the time being, I think we should address the two basic end-user cases:
- My own package ABC uses MSL 3.2.3, I need to convert it to MSL 4.0.0
- My own package ABC uses package XYZ version p.q.r, a new non-backwards compatible XYZ version s.t.w comes out, I need to convert my library ABC to use it (same story, but more general).

We assume that the responsibility to update the "read-only" libraries that are installed with the package manager is not with the end user, but with the library developer. In other words, if my package uses XYZ p.q.r that uses MSL 3.2.3, and I want to move to MSL 4.0.0 with my package, I will have to wait until a MSL 4.0.0-compatible version of XYZ is released, and simply download it with the package manager via File | Upgrade Installed Libraries.

Hence, I understand the required functionality is rather simple, and applies to both cases cited above:

- my library ABC version d.e.f. uses XYZ version p.q.r.
- a new version XYZ s.t.w is released, which is not backwards compatbile with XYZ p.q.r.
- I download XYZ s.t.w via File | Upgrade Installed library
- I open ABC version d.e.f., which automatically loads XYZ version p.q.r.
- I right-click on ABC in the package browser and get a menu item "Upgrade to use newer installed dependencies"
- OMEdit scans for all the uses annotations in ABC and identifies all the libraries it uses, XYZ version p.q.r, in this case.
- For each identified library, OMEdit checks what are their installed versions that have a conversion script from the currently used version; in this case, the installed versions of XYZ that have a conversion script from p.q.r., i.e., s.t.w in this case; OMEdit then shows them to me and allows me to choose to which specific one I want to convert my ABC.
- After a confirmation dialog, that also asks for the new version number of ABC (e.g g.h.j) and for possible semver metadata, the conversion script for XYZ from p.q.r. to s.t.w. is applied, and the new version of ABC g.h.j is then overwritten onto the old one on disk, with exactly the same file system structure, and with updated version annotation. If GIT is used, one should first switch to a new branch before doing that. 

That's it. 

@adeas31, what do you think?

**Comment by adeas31** [comment]
See #8111

**Comment by casella** [comment]
Thank @adeas31, I'll test this myself and report
