### ISSUE TITLE
combiTable2Ds1 extrapolation

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#8075]
### Description
'Hold last point' extrapolation of the 2D table is not implemented as described in the 2Dtable documentation. More specifically: no matter the extrapolation setting, the behaviour is always extrapolation by last slope (LastTwoPoints)

### Steps to reproduce
Below is code for an MWE. Plot combiTable2Ds1.u1, combiTable2Ds1.u2 and combiTable2Ds1y.
The table is only 10x10, where first row and column define grid points according to the documentation. Therefore the output should be limited between 2 and 18 when hold last point is the extrapolation method.

```mo
model tabletest
  Real y;
  parameter Real M[10,10]=[0.0,1,2,3,4,5,6,7,8,9; 1,2,3,4,5,6,7,8,9,10; 2,3,4,5,6,7,8,9,10,11; 3,
        4,5,6,7,8,9,10,11,12; 4,5,6,7,8,9,10,11,12,13; 5,6,7,8,9,10,11,12,13,14;
        6,7,8,9,10,11,12,13,14,15; 7,8,9,10,11,12,13,14,15,16; 8,9,10,11,12,13,14,
        15,16,17; 9,10,11,12,13,14,15,16,17,18];
  Modelica.Blocks.Sources.Ramp ramp(
    height=20,
    duration=1,
    offset=-1)
    annotation (Placement(transformation(extent={{-78,12},{-58,32}})));
  Modelica.Blocks.Sources.Ramp ramp1(
    height=20,
    duration=2,
    offset=-1)
    annotation (Placement(transformation(extent={{-80,-36},{-60,-16}})));
  Modelica.Blocks.Tables.CombiTable2Ds combiTable2Ds1(
    extrapolation=Modelica.Blocks.Types.Extrapolation.HoldLastPoint,
    smoothness=Modelica.Blocks.Types.Smoothness.ConstantSegments,
    table=M,tableOnFile=false)
    annotation (Placement(visible = true, transformation(extent = {{-10, -12}, {10, 8}}, rotation = 0)));
equation
  der(combiTable2Ds1.y) = y;
  connect(combiTable2Ds1.u1, ramp.y) annotation(
    Line(points = {{-12, 4}, {-30, 4}, {-30, 22}, {-57, 22}}, color = {0, 0, 127}));
  connect(combiTable2Ds1.u2, ramp1.y) annotation(
    Line(points = {{-12, -8}, {-48, -8}, {-48, -26}, {-59, -26}}, color = {0, 0, 127}));
  annotation (
    Icon(coordinateSystem(preserveAspectRatio=false)),
    Diagram(coordinateSystem(preserveAspectRatio=false)),
    uses(Modelica(version="4.0.0")),
    experiment(StopTime=1.2, __Dymola_Algorithm="Dassl"));
end tabletest;
```

### Expected behavior
I expect the output to be clipped between 2 and 18. (For verification: dymola _does_ clip between 2 and 18)

### Screenshots
![image](https://user-images.githubusercontent.com/59084059/139845980-82a1bd0c-7331-48f0-854b-d07da64e12cc.png)

Note the smooth behaviour when u1 >9, while u2 is still in range. Apparently also interpolation is affected.

### Version and OS
 - OpenModelica Version 1.18.0
 - OS: Windows 10, 64 bit

Best regards,
Paul van der Hulst

**Comment by casella** [comment]
@mahge maybe you could have a look?

**Comment by sjoelund** [comment]
This seems to be because upstream MSL has:
```
void* ModelicaStandardTables_CombiTable2D_init2(_In_z_ const char* fileName,
                                                _In_z_ const char* tableName,
                                                _In_ double* table, size_t nRow,
                                                size_t nColumn, int smoothness,
                                                int extrapolation,
                                                int verbose) {
    return ModelicaStandardTables_CombiTable2D_init3(fileName, tableName,
        table, nRow, nColumn, smoothness, LAST_TWO_POINTS, 1 /* verbose */, ",", 0);
}
```

https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaStandardTables.c#L2891

Probably some copy-paste error when init3 was introduced?

**Comment by beutlich** [comment]
> Probably some copy-paste error when init3 was introduced?

No, this is just for backward-compatibility. ModelicaStandardTables_CombiTable2D_init2 is nowhere called in MSL.

**Comment by sjoelund** [comment]
MSL 4.0.0 uses it, and we use the latest external C library with it for some bug fixes. The backwards compatibility is broken is the point. Anyway, I opened a PR to MSL master.
