### ISSUE TITLE
OM creates FMU converting parameters into constants

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8087]
### Description

When we create an FMU from a model containing conditional models inside, and the actual model depends on a parameter value, OM (Dymola does the same) creates the FMU in the actual configuration related to the default parameter value, which is converted into a constant **And does this silently.**
I understand that FMUs do not support conditional components, and therefore OM is obliged, if it wants to create an FMU, to create it from the default value of parameter which defines what conditional component is actually alive. But it should inform the user of this.

 
### Steps to Reproduce
You can use the Test.mo file below (convert txt to mo before use)
[Test.txt](https://github.com/OpenModelica/OpenModelica/files/7473228/Test.txt)

Load Test (it uses a model from PoerGrids library)
create an FMU from test
Load that FMU into an SSP
Look at the parameters

It occurs that the parameter list contains only k and not T (T is kept constantly equal to the default value, so that the conditional components are internally converted into fixed components).

### Expected Behavior
OM should issue a warning stating that a parameter is converted into a constant, and the active conditional components are converted into regular components, and the actual inactive conditional components are dropped.
I think that it should also say _what_ parameters and components are involved (useful if there are more than one pair of conditional components)

### Version and OS

OM 1.18.0, WIn10 64 bit
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@max-privato, this is true not only for parameters that influence the activation of conditional components, but for all kinds of so-called _structural parameters_, i.e. parameters that influence the structure of the mathematical model, such as its size or its incidence matrices. For example:
- parameters that influence the activation of conditional components
- parameters that determine the size of arrays of any kind
- parameters that determine the choice of branches in conditional equations

@perost may add further items to the list.

The front-end identifies these structural parameters and constant-evaluates them very early at compile time during the flattening process. What we could do would be to add a flag to issue _notifications_ about all parameters that get constant-evaluated in the frontend. Bear in mind that you could get much output in this case, so I would make this optional. 

@max-privato is this what you are looking for?

**Comment by max-privato** [comment]
> @max-privato, this is true not only for parameters that influence the activation of conditional components, but for all kinds of so-called _structural parameters_

AHA, I did not realize this!
So every model containing structural parameters unavoidably gets limited when converted into FMUs: the FMU flexibility is that of a "re-simulation" in OMEdit.

In the case of conditional components, the modeller may take steps to use different techniques to obtain the same behaviour. In the example of FirstOrder, one could add a switch to change its behaviour depending on T, which becomes an input. T is converted from a parameter into a variable, with some (small) resource waste, since it will not change during the simulation, but that's it. I don't see other ways.

Now I realise that ticket (for me) is invalid and can be closed.

**Comment by perost** [comment]
As casella already mentioned it's just a normal part of Modelica that some parameters are evaluated during the compilation.

We already had a debug flag (`-d=printStructuralParameters`) for the purpose of printing out which parameters where determined to be structural, but it was only implemented for the old frontend. I'm not sure how useful it really is, but I implemented it also for the new frontend in #8096 since it was trivial to do so.

**Comment by max-privato** [comment]
> I'm not sure how useful it really is, 
I think this could be useful for people (like me) that create FMUs from Modelica, just to understand the usage limits of the created FMUs.

BTW, it seems to me that the very concept of "structural parameter" is not absolute: what is structural for a tool can not be such for another. 
Up to some time ago, for instance, the filename of inputs of CombiTables could not be changed for re-simulations. I guess this allows us to say it was structural. Later, following a ticket of mine, the situation has changed; the name can be changed without recompilation, i.e. I would say, it has become non-structural.

**Comment by perost** [comment]
> BTW, it seems to me that the very concept of "structural parameter" is not absolute: what is structural for a tool can not be such for another. Up to some time ago, for instance, the filename of inputs of CombiTables could not be changed for re-simulations. I guess this allows us to say it was structural. Later, following a ticket of mine, the situation has changed; the name can be changed without recompilation, i.e. I would say, it has become non-structural.

Yes, structural parameter is not something that's currently standardized. There's been some effort on trying to standardize it, but that effort has been more towards specifying what can be evaluated rather than what should be evaluated. So there will likely always be some tool differences in that regard.

**Comment by casella** [comment]
In fact, the reason why we have structural parameters is that our code generation methods are not flexible enough to handle structural changes at runtime, possibly even during the simulation (i.e., variable-structure systems). We're doing research on that topic, though, see e.g. @JKRT's PhD work.
