### ISSUE TITLE
Homotopy is broken

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8097]
### Description

When initializing models using `homotopy()`, all lambda-steps except the first, which is carried out with the separate, `initial-lambda0` set of equations, actually use `lambda = 1`. This means that the first step already corresponds to the last step, and then all subsequent steps are trivial, since nothing changes w.r.t. the previous step and the solver converges immediately.

Most models actually work fine with just one step, i.e. `lambda = 0` and then` lambda = 1` straight away, and we are never checking the intermediate results, so this issue (which is a regression, as I understand) was not caught by any of the Jenkins jobs. 

Unfortunately, there are indeed models that do need to take some intermediate steps, and those currently fail miserably.

### Steps to Reproduce

Run the following MWE with the latest nightly build
```
model TestTornHomotopy
  Real x,y,z;
equation
  x = homotopy(y + 0.1*y^2 - 0.001*y^3, y);
  y = 3*z;
  z + 1e-6*x = 1;
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_INIT_HOMOTOPY,LOG_NLS_V,LOG_STATS", s = "dassl"));
end TestTornHomotopy;
```

The `TestTornHomotopy_equidistant_global_homotopy.csv` file contains 
```
"lambda",          "x",             "y",          "z"
0,                 2.99999099993147, 2.999991000027,  0.999997000009
0.3333333333333333,3.872981723411532,2.99998838105483,0.9999961270182766
0.6666666666666666,3.872981723411532,2.99998838105483,0.9999961270182766
1,                 3.872981723411532,2.99998838105483,0.9999961270182766
```
It is clear that the first step already computes the solution for `lambda = 1`, while the subsequent ones just solve the same problem.

### Expected Behavior

Each step should be solved with the right lambda value.

### Additional Context

Although I have no documentary evidence, I am fairly certain that homotopy-based initialization worked as expected until some time ago, so I guess this is a regression, but I have no idea when it could have been introduced.

I remember @kabdelhak, @AnHeuermann and @sjoelund were involved at some points in February and March fixing some homotopy-related stuff. Could you please check? I would also include some test models in the core testsuite to make sure that lambda steps are taken correctly.

This is very high priority for me, as it is a blocker for some important work that will have strategic importance for OSMC in the near future. I cc: @matteodepascali for his information.

Thanks!

**Comment by sjoelund** [comment]
Are we sure that it's solving it wrong or could it just be a printing error? 77658af1e232fee1421134e5c78fb2cbeb87c329 was my commit and hopefully should not affect this in a negative way. It should actually have fixed some potential problems for non-linear systems which would be forced into lambda=1. Would be easy to verify with a little time (just revert it and test).

**Comment by casella** [comment]
I am 100% sure. Just check the `LOG_NLS_V` output at each lambda step.

**Comment by casella** [comment]
>  [77658af](https://github.com/OpenModelica/OpenModelica/commit/77658af1e232fee1421134e5c78fb2cbeb87c329) was my commit and hopefully should not affect this in a negative way. It should actually have fixed some potential problems for non-linear systems which would be forced into lambda=1. Would be easy to verify with a little time (just revert it and test).

Would you mind trying that out? Thanks!

**Comment by casella** [comment]
> 
> 
> > [77658af](https://github.com/OpenModelica/OpenModelica/commit/77658af1e232fee1421134e5c78fb2cbeb87c329) was my commit and hopefully should not affect this in a negative way. It should actually have fixed some potential problems for non-linear systems which would be forced into lambda=1. Would be easy to verify with a little time (just revert it and test).
> 
> Would you mind trying that out? Thanks!

@sjoelund, @adrpo, never mind that. I just tried with 1.16.3, released on Feb 2021, and the situation was exactly the same. I will continue the bisection search further backwards.

**Comment by casella** [comment]
This is a slightly improved MWE, where the effects of changing lambda should be clearly visible also on y (hence in the LOG_NLS_V output), not only on x.
```
model TestTornHomotopy2
  Real x,y,z;
equation
  x = homotopy(y + 0.1*y^2 - 0.001*y^3, y);
  y = 3*z;
  z + 0.1*x = 1;
annotation(
    __OpenModelica_simulationFlags(lv = "LOG_INIT_HOMOTOPY,LOG_NLS_V,LOG_STATS", s = "dassl"));
end TestTornHomotopy2;
```

**Comment by casella** [comment]
Also 1.13.2 has the same behaviour: four homotopy steps, many iterations on the first, none on the subsequent ones.

**Comment by casella** [comment]
OK, we got a bracket. Version 1.9.4 (@lochel's original implementation) works as expected. Back then we didn't have the initial-lambda0 equations, so the lambda iteration is performed on the full homotopy equations with these results for TestTornHomotopy2:
- lambda = 0.000, y  =  2.3076923,
- lambda = 0.333, y  =  2.2689885,
- lambda = 0.667, y = 2.2327123,
- lambda = 1.000, y = 2.1985951.

Something went wrong between that and 1.13.2.

**Comment by sjoelund** [comment]
I'm wondering if during initialization, nonlinear systems with local homotopy should perhaps just use the global homotopy instead and that would solve it?

**Comment by casella** [comment]
I guess we need to establish some notation first, so we get ourselves understood, otherwise "nonlinear systems with local homotopy should use the global homotopy instead" is a bit too fuzzy to me 😃 

The initialization problem _with global homotopy_ can be formulated as
```
f(z, lambda) = 0   (1)
```
where `z` collects all the unknowns of the initialization problem, i.e. the initial values of states, derivatives, algebraic variables, discrete variables, pre() values of discrete variables, and unknown parameters with fixed = false, while `lambda` is the global homotopy parameter, which stems from the `homotopy()` operator. The equations in (1) are formulated by replacing each call of `homotopy(actual, simplified)` with ` lambda*actual + (1-lambda)*simplified`.

The usual BLT and tearing machinery is applied to (1), which is not solved simultaneously, but rather as a sequence of solutions of smaller systems of equations. Some explicit, some implicit and linear, some implicit and nonlinear. In the latter case, we get a sequience one or more smaller nonlinear systems
```
f_i(z_i, lambda) = 0   (2)
```
with `i` going from `1` to `N`, where `z_i` is a subset of `z`, and where `lambda` is the global homotopy parameter.

As I understand it, the default hybrid solver first tries to solve each instance of (2) using a damped Newton method. If that fails, then the so-called "homotopy solver" kicks in. This has _nothing to do_ with the homotopy() operator; it uses some standard homotopy to try to achieve convergence. In mathematical notation, this would be something like:
```
f_i(z_i, lambda)*lambda_s + (1 - lambda_s)*(z_i-z_0) = 0   (3a - fixed point homotopy)
f_i(z_i, lambda)*lambda_s - (1 - lambda_s)*f_i(z_i, lambda) = 0   (3b - Netwon homotopy)
f_i(z_i, lambda)*lambda_s + (1 - lambda_s)*df_i/d_zi(z_0)*(z_i - z_0) = 0 (3c - affine homotopy)
```
Note that there are _two_ lambdas here: one global (`lambda`), defined by the modeller with the homotopy() operator, and one local `lambda_s,` used by the numerical solver, without any input by the modeller. The solver needs access to both in order to compute the correct residuals. In general, the two lambda-cycles will be nested, i.e., the outer global lambda, which is used by the homotopy operators, should gradually go from zero to one, while the local lambdas cycle from zero to one multiple times, each time with a fixed value of the global lambda, if the damped Newton solver fails and the local homotopy solver kicks in.

Are we aligned so far?

To make things even more confusing, besides the default `--homotopyApproach=globalEquidistant` and `--homotopyApproach=globalAdaptive`, that correspond to equations (2) and (3) as explained above, the runtime also implements `--homotopyApproach= localEquidistant` and `localAdaptive`, where I understand the homotopy() `lambda` is separately cycled from 0 to 1 in the solution of each `f_i(...) = 0` solution. I don't even know why this was implemented, since the specification is very clear that homotopy() is meant to be global, and if you do it local you will be missing the influence that earlier f_i(...) = 0 have on later ones in the BLT, but yet it is there.

The whole thing is a bit messy, so it is important we get it straight and understand each other.

I'm not much into the code, and I guess it's time for me to take a guided tour there, but what I understood from @sjoelund so far is that there is only one `lambda` in the code, so global values are saved and retrieved at times. I am really worried that there is some fundamental flaw there - and in any case it is clear that the whole thing is currently broken beyond repair, because at the end of the day we get lambda = 1 all the time, at least with the `--homotopyApproach=equidistantGlobal` default setting.

I would suggest a meeting with myself, @sjoelund, @AnHeuermann and possibly @lochel were we try to clarify all these issues and resolve the bug.

**Comment by casella** [comment]
Here is what I understood so far by looking at the LOG_NLS_V output of `TestTornHomotopy2` in version 1.11.0 (released Feb 2017), and 1.12.0 (released Oct 2017). The former works fine, the latter was broken already. Note that in both cases, the `initial-lambda0` equations were not yet generated, so the same general formulation is used for all homotopy steps, including the first at `lambda = 0`.

When running `TestTornHomotopy2` in version 1.11.0, the behaviour is as expected:
- the nonlinear solver runs on the torn system four times during initialization, with four different values of `lambda`. Sadly, I can't see them directly, because `LOG_INIT_HOMOTOPY` was not yet implemented back then, but I know them to be `lambda = 0`, `lambda = 0.333`, `lambda = 0.667`, and `lambda = 1.0`.
- during the first run (`lambda = 0`), the tearing variable `y` immediately converges to 0.23076923. This is expected, since the system is actually linear at `lambda = 0`, so the Newton solver converges in one iteration.
- during the second run, there are a few iterations until `y` converges to 2.2689885,
- during the third run, there are a few iterations until `y` converges to 2.2327123
- during the last run, there a a few more iterations until `y` converges to 2.1985951, which is the actual value that is also later displayed during simulation.

So far so good.

With 1.12.0, this is the observed behaviour
- During the first run of the Newton solver, `y` is computed to 2.3076923 after the first iteration, consistently with the fact that the nonlinear system at `lambda = 0` is actually linear and has that solution
- However, the first run does not stop there: at the second iteration, `y` is computed to 2.1988272, which is close to the value for `lambda = 1`. Then, there are a few more iterations until `y` converges to 2.1985951, which is the exact value for `lambda = 1`.
- During subsequent Newton solver runs, that correspond to `lambda = 0.333`, `0.667`, and `1.0`, the solver starts from the previously computed value `y = 2.1985951`, does one iteration that doesn't change it significantly, and then terminates successfully with that very same value.

So, it seems that after 1.12.0, something is overwriting the "right" value of `lambda` with 1.0 after the very first iteration of the Newton solver on a system that has a call to the `homotopy()` macro in it. This macro is defined in `OMCompiler/SimulationRuntime/c/openmodelica.h` as
```C
#define homotopy(actual, simplified) 
             ((simplified) * (1.0-data->simulationInfo->lambda) + (actual) * data->simulationInfo->lambda)
```
so it seems that after the first Newton iteration, something is fiddling with `simulationInfo->lambda` in an improper way. As far as I understand, this is still the current behaviour with the development version on master, except that the iteration with `lambda = 0` is handled separately by the `initial-lambda0` equations.

I hope this is enough information to fix this issue easily 😃

**Comment by AnHeuermann** [comment]
Okay, commenting out [nonlinearSystem.c#L1077](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/simulation/solver/nonlinearSystem.c#L1077)

```C
      if (!homotopyDeactivated && !omc_flag[FLAG_HOMOTOPY_ON_FIRST_TRY])
        infoStreamPrint(LOG_INIT_HOMOTOPY, 0, "Try to solve nonlinear initial system %d without homotopy first.", sysNumber);

      data->simulationInfo->lambda = 1.0;
      /* SOLVE! */
      nonlinsys->solved = solveNLS(data, threadData, sysNumber);
```
seems to give the correct solutions for y:

```csv
"lambda",          "x",               "y",               "z"
0,                  2.307692307692307, 2.307692307692308, 0.7692307692307693
0.3333333333333333, 2.436704982096462, 2.268988505371062, 0.7563295017903539
0.6666666666666666, 2.557625806717175, 2.232712257984848, 0.7442374193282825
1,                  2.671349569180263, 2.198595129245921, 0.7328650430819735
```

I'll create a PR, together with this test case and let's see how much of the test suite we will break.

**Comment by casella** [comment]
Looks good, we get two more models of ThermoPower working, see last comment in #8109.

@matteodepascali confirms that he can now get the initialization of his problem to converge until lambda = 1. The solution is not the expected one, but I guess this is due to a bad simplified model that leads homotopy to converge on the "wrong" solution.

Thanks for you efforts!
