### ISSUE TITLE
Arrays with 0-dimensions still sometimes referenced in flat model

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#8120]
We currently remove arrays with 0-dimensions during scalarization, but this causes issues since they can still be referenced in the model. For example:
```Modelica
model M
  Real x[0];
  Real y;
  Real z;
algorithm
  y := time;
  for m in 1:1 loop
    z := if m == 1 then y else x[m - 1];
  end for;
end M;
```
is flattened to (notice the missing declaration for `x`):
```Modelica
class M
  Real y;
  Real z;
algorithm
  y := time;
  for m in 1:1 loop
    z := if m == 1 then y else x[m - 1];
  end for;
end M;
```
This affects e.g. [ClientLBNL90](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.Controls.DemandResponse.Examples.ClientLBNL90.err) in Buildings, which fails because the generated code references missing variables.

The most obvious solution to me is to just add a declaration for such variables, since we can't really remove the references in the flat model. I tried to implement this in #8119, in which I made the NF just skip scalarization for variables with 0-dimensions and also fixed CheckModel.

It doesn't pass the backend yet though, because it counts the variables wrong (and if I disable the check it still fails for other reasons). So ideas are welcome, either on other options or on how to fix the backend with my current approach.

**Comment by perost** [comment]
@kabdelhak

**Comment by casella** [comment]
Hmm. [Section 10.7](https://specification.modelica.org/maint/3.5/arrays.html#empty-arrays) states:

> It is not possible to access an element of an empty matrix, e.g. `v[j, k]` cannot be evaluated if `v = []` because the assertion fails that the index must be bigger than one.

To me your MWE looks invalid because of this. And I guess also the Buildings models may be. What do you think?

**Comment by perost** [comment]
> Hmm. [Section 10.7](https://specification.modelica.org/maint/3.5/arrays.html#empty-arrays) states:
> 
> > It is not possible to access an element of an empty matrix, e.g. `v[j, k]` cannot be evaluated if `v = []` because the assertion fails that the index must be bigger than one.
> 
> To me your MWE looks invalid because of this. And I guess also the Buildings models may be. What do you think?

`x[m - 1]` will never be evaluated in my example, so that should be fine. But we generally can't know that until we actually simulate the model, so we have to handle it somehow.

**Comment by casella** [comment]
This is a bit borderline. Looks to me like accessing a conditional connector which may not be there, which is actually illegal.
```Modelica
model M
  parameter Boolean use_in_u = false;
  Modelica.Blocks.Interfaces.RealInput u if use_in_u;
  parameter Real y_const = 0;
  Real y;
algorithm 
  y := if use_in_u then u else y_const;
end M;
```
Why should we use different criteria for arrays with zero elements and disabled conditional connectors? In both cases, they actually don't exist.

**Comment by perost** [comment]
> Why should we use different criteria for arrays with zero elements and disabled conditional connectors? In both cases, they actually don't exist.

Note that it's not the fact that an empty array is subscripted that is the issue, but that it's used at all (and remain in the flat model). We can't forbid empty arrays completely, that would break a lot of things.

**Comment by sjoelund** [comment]
> Why should we use different criteria for arrays with zero elements and disabled conditional connectors? In both cases, they actually don't exist.

An empty array does exist :) If you do in a function `arr := fill(N,M);`, should the code stop working if N or M is equals to 0? You could even create an array with multiple dimensions and do calculations based on its sizes by playing with `size(arr)`

**Comment by perost** [comment]
There seems to be a lot of issues with getting this to work with the current backend, some modules seems to remove empty array variables while others have various issues with variable counting. I think I'll just merge #8117 instead for now since that works around the issue for the Buildings models, and then we can revisit this when we have the new backend which might handle this better.

**Comment by mahge** [comment]
I have added 
```mo
y := time;
```
to the example since it was missing one equation even without the zero dim issue.

**Comment by perost** [comment]
> I have added
> 
> ```modelica
> y := time;
> ```
> 
> to the example since it was missing one equation even without the zero dim issue.

Sure, it was just to demonstrate the issue. I was using `ClientLBNL90` when I actually tried to make it work.

**Comment by perost** [comment]
Another option might be to replace 0-size arrays with {}, since they haven't got any elements anyway.

**Comment by sjoelund** [comment]
> Another option might be to replace 0-size arrays with {}, since they haven't got any elements anyway.

I think I did something like that for the old frontend, but it's a very bad solution. If you call `size()` on that, you just get `0` even though it is possible you should get `0,1,3` or something...

**Comment by adrpo** [comment]
It should preserve the dimensions so maybe `fill` would be better or some explicit expression for zero size arrays of any dimension.

**Comment by perost** [comment]
I went with replacing references to 0-size array variables with the appropriate array and got rid of the `size` issue by replacing e.g. `size(/*Real[0, 2]*/exp, index)` with `{0, 2}[index]` (except in functions where it doesn't work but also isn't needed).

Using `fill` might've also worked but then we'd have to make sure it's never evaluated or we'd get an array anyway, so just going with arrays from the start is probably simpler.
