### ISSUE TITLE
Issues with -d=nonfScalarize combined with -f, -arrayConnect, and combineSubscripts

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8130]
Please consider the attached test package [TestArray.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7534907/TestArray.mo.txt).

If I set `-d=nonfScalarize,arrayConnect,combineSubscripts` and instantiate `TestArray.ConnectEquations.SC`, I get:
```
class TestArray.ConnectEquations.SC "A model using arrays of models with arrays of basic types (same dimensions)"
  final parameter Integer N = 3;
  final parameter Real[3] p = {1.0, 1.5, 2.0};
  Real[3] c.c.f;
  Real[3] c.c.e;
  Real[3, 3] c.x;
  final parameter Real[3] c.p = {1.0, 1.5, 2.0};
  final parameter Integer[3] c.N = 3;
  final parameter Real s.p = 3.0;
  Real s.c.e;
  Real s.c.f;
equation
  c.x[1] = c.c.e;
  c.x[c.N] = c.c.f;
  for $i1 in 1:3 loop
    for i in 2:3 loop
      c.x[$i1,i] = c[$i1].x[i - 1] + {1.0, 1.5, 2.0}[$i1];
    end for;
  end for;
  s.c.f = 3.0;
  c.c.e[2] = c.c.e[1];
  s.c.e = c.c.e[1];
  c.c.e[3] = c.c.e[1];
  c[3].c.f + s.c.f + c[2].c.f + c[1].c.f = 0.0;
end TestArray.ConnectEquations.SC;
```
This is almost fine, except for two issues:
- `c[$i1].x[i - 1]` should be `c.x[$i1, i - 1]`
- `c[1].c.f` should be `c.c.f[1]`. Ditto for the other two elements of the array

If I now add `-f` to the flags, I get
```
class 'TestArray.ConnectEquations.SC'
function 'subscriptReal[3]_Integer'
  input Real[3] exp;
  input Integer s1;
  output Real result = exp[s1];
end 'subscriptReal[3]_Integer';

  public parameter Integer 'N' = 3;
  public parameter Real[3] 'p' = {1.0, 1.5, 2.0};
  public Real[3] 'c.c.f';
  public Real[3] 'c.c.e';
  public Real[3, 3] 'c.x';
  public parameter Real[3] 'c.p' = {1.0, 1.5, 2.0};
  public parameter Integer[3] 'c.N' = 3;
  public parameter Real 's.p' = 3.0;
  public Real 's.c.e';
  public Real 's.c.f';
public
equation
  'c.x'[1] = 'c.c.e';
  'c.x'['c.N'] = 'c.c.f';

  for $i1 in 1:3 loop
    for i in 2:3 loop
      'c['$i1'].x'['i'] = 'c['$i1'].x'['i' - 1] + 'subscriptReal[3]_Integer'({1.0, 1.5, 2.0},'$i1');
    end for;
  end for;

  's.c.f' = 3.0;
  'c[2].c.e' = 'c[1].c.e';
  's.c.e' = 'c[1].c.e';
  'c[3].c.e' = 'c[1].c.e';
  'c[3].c.f' + 's.c.f' + 'c[2].c.f' + 'c[1].c.f' = 0.0;
end 'TestArray.ConnectEquations.SC';
```
This time there are a few more issues, e.g.:
- `'c['$i1'].x'['i']` should be `'c.x'['$i1', 'i']`
- `'c['$i1'].x'['i' - 1]` should be `'c.x'['$i1','i' - 1]`
- `'c[1].c.e'` should be `'c.c.e'[1]`
-  `'c[1].c.f'` should be `'c.c.f'[1]`

**Comment by perost** [comment]
The issue was that when using `-f` we dump the flat model before `combineSubscripts` is run, so I changed the dumping to call `combineSubscripts` on a copy of the flat model before dumping it (need a copy since we don't want to change the actual flat model at that stage).

Additionally I noticed that `combineSubscripts` wasn't actually traversing the expressions, so for e.g. an equality equation it would check the lhs and rhs but not traverse into them. So e.g. `c[$i1].x[i - 1]` would not be changed since it wasn't alone on the rhs but part of a bigger expression. Now it should check all subexpressions too.
