### ISSUE TITLE
Incorrectly flattened sliced array with -nonfScalarize

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8132]
Consider the test case reported in [#6173 comment:8](https://trac.openmodelica.org/OpenModelica/ticket/6173#comment:8) by @mahge:
```Modelica
record A
  Real[4] a;
end A;

model B
  A[3] b;
equation
  // normal
  for i in 1:4 loop
    b[3].a[i] = 1;
    // b.a[3][i] = {1, 2, 3};
  end for;

  // sliced. 
  for i in 1:4 loop
    b.a[i] = {1, 2, 3};
    // { b[1].a[i], b[2].a[i], b[3].a[i] } = {1, 2, 3}
    // b.a[:][i] = {1, 2, 3};
  end for;

  for i in 1:3 loop
    b[i].a = {1, 2, 3, 4};
    // { b[i].a[1], b[i].a[2], b[i].a[3], b[i].a[3] } = {1, 2, 3, 4}
    // b.a[i][:] = {1, 2, 3};
  end for;
end B;
```
The current flat output of P.B with `-d=nonfScalarize` is _almost_ correct from this point of view:
```Modelica
class P.B
  Real[3, 4] b.a;
equation
  for i in 1:4 loop
    b.a[3,i] = 1.0;
  end for;
  for i in 1:4 loop
    b.a[i] = {1.0, 2.0, 3.0};
  end for;
  for i in 1:3 loop
    b.a[i,:] = {1.0, 2.0, 3.0, 4.0};
  end for;
end P.B;
```
except for the second for-equation, which should instead be:
```Modelica
  for i in 1:4 loop
    b.a[:,i] = {1.0, 2.0, 3.0};
  end for;
```

**Comment by perost** [comment]
Seems I got it mixed up, we removed `:` subscripts from the head of the list instead of from the end. I just removed that line of code so we don't remove subscripts at all now, which means that all unsubscripted dimensions will be filled with `:`.

**Comment by perost** [comment]
Also, this is of course with `-d=combineSubscripts`, without that flag you'll still get `b.a[i]` since that's correct when you don't move the subscripts to the end.

**Comment by casella** [comment]
> 
> 
> Also, this is of course with `-d=combineSubscripts`, without that flag you'll still get `b.a[i]` since that's correct when you don't move the subscripts to the end.

Of course, I forgot to mention that in the original text.
