### ISSUE TITLE
vector(zeros(0,1)) failing

### ISSUE THREAD

**Issue by dariomangoni** [OpenModelica/OpenModelica#8141]
I see that:
```
// parameter Real a[0] = vector(zeros(0, 1)); // BROKEN
parameter Real b[0] = zeros(0); // WORKS
```
where the first line throws
```
Type mismatch in binding ‘a = CAST(Real[1], vector({}))‘, expected array dimensions [0], got [1].
```
Is this an expected behaviour? I see that other Modelica environments accept it while others don't.

**Comment by sjoelund** [comment]
`zeros(0, 1)` returns a 0x1 2-dimensional array:
```mo
size(zeros(0)) = {0}
size(zeros(0,1)) = {0,1}
size(zeros(0,1,2)) = {0,1,2}
```

**Comment by sjoelund** [comment]
Now other tools might just say if there is a 0-dimension anywhere, it's an empty array so it fits anything empty... But it shouldn't do that.

**Comment by perost** [comment]
> Now other tools might just say if there is a 0-dimension anywhere, it's an empty array so it fits anything empty... But it shouldn't do that.

I think it should, `vector` is specified to return a vector containing all the elements of the array given that not more than one dimension is larger than 1.

**Comment by dariomangoni** [comment]
Yes, I would have expected `vector` to be able to squeeze the 0x1 array created by `zeros(0,1)` into a 0 array, thus squeezing the 2D array into a 1D array of size {0}.

**Comment by sjoelund** [comment]
Oh yeah, I missed that vector call. Then I suppose it should indeed work...
