### ISSUE TITLE
Weird notifications when installing MSL 3.2.3 with the package manager

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8143]
### Description

The package manager gives unexplicable warnings when first trying to install MSL 3.2.3.

### Steps to Reproduce

- Create a new user, so that the default modelicapath has no installed libraries
- Start the package manager
- type `updatePackageIndex()`
- type `installPackage(Modelica,"3.2.3");getErrorString()`

The following notification is issued:
```
"Warning: Conflicting versions for loading package Modelica: 3.2.3+maint.om is to be installed, but
another package requires version 4.0.0 which is not provided by this version.
```
This is completely odd, extremely confusing, and also a bit infuriating: if there is "another package" creating problems, why won't the package manager kindly inform me about his whereabouts?

### Expected Behavior

No warning message issued.

**Comment by casella** [comment]
Additionally, we need to make sure that when we type `installPackage(Modelica, "3.2.3")` we actually also get Complex and ModelicaServices with the right versions.

According to @sjoelund, currently this only happens if one additional sets `exactMatch = true`

**Comment by casella** [comment]
@sjoelund explanation by email to me:

It's again because we don't have full dependency resolution, but a greedy algorithm. Because there are noneFromVersion annotations on ModelicaServices 4.0.0 saying it's the same as 3.2.3, when we try to install MSL 3, Services 4 is installed and because Services 4 depends on MSL 4, that gives a warning.

What a full dependency algorithm would do is it would build all possible combinations of packages (let's say given that we ask to install MSL 3.2.3):

MSL 3.2.3, Services 4.0.0 (fail)
MSL 3.2.3, Services 4.0.1 (fail)
MSL 3.2.3, Services 4.0.2 (fail)
MSL 3.2.3, Services 3.2.3 (OK)
...

and see which ones:
* Work
* Work, but require conversion script

and then order them according to some priority (if MSL 3, Services 4 would produce a working installation, it would have higher priority than Services 3, etc).

**Comment by casella** [comment]
This example shows me that maybe we are making a conceptual mistake about the concept of "backwards compatiblity". 

We always interpreted having a `noneFromVersion` annotation as equivalent to being backwards-compatible. However, for me backwards compatible means that you can use the new library instead of the old one without any problem. The `noneFromVersion` annotation in version 4.0.0 only says that any model or library using ModelicaServices doesn't need any class or parameter named to be changed if you upgrade ModelicaServices from 3.2.3. But that _doesn't necessarily mean this is hot-plug-compatible, precisely because ModelicaServices has a dependency on a library which is not backwards-compatible with the dependency of the previous version_. 

Conclusion: ModelicaServices 4.0.0 is not really backwards compatible with 3.2.3, and thus it was correctly called 4.0.0, not 3.4.0.

**Comment by casella** [comment]
I would make an alternative proposal to fix this issue.

Currently, we consider version Y backward-compatible with version X if it has a `noneFromVersion(X)` annotation. I would propose an alternative definition:

> Version Y of a package is backwards-compatible with version X of the same package if it has a  `noneFromVersion(X)` and if all the dependencies of version Y are backwards-compatible with the corresponding dependencies of version X

Implementing this definition is not completely trivial because you need to check the backwards-compatibility of the dependencies, which may require to check the backwards-compatibility of the dependencies of the dependencies, with possible formation of infinite loops etc. 

For the time being, we could use a simpler version of the previous definition:

> Version Y of a package is backwards-compatible with version X of the same package if it has a  `noneFromVersion(X)` and if all the dependencies of version Y have a `noneFromVersion` annotation including the dependencies of version X

This is not perfect, but it would at least fix this issue, issue #8060, and a host of other MSL 3.2.3-vs-4.0.0 problems that are popping up all  the time. So, it would be much better than the current situation. We could later improve it by implementing the original full definition.

Let me make a concrete example with our case. Currently we consider ModelicaServices 4.0.0 a better alternative to ModelicaServices 3.2.3 because it has a `noneFromVersion(3.2.3)` annotation, and we load it instead of 3.2.3 because the higher semver version number tells us it is more recent, thus a better alternative.  

However, ModelicaServices 4.0.0 uses MSL 4.0.0, while ModelicaServices 3.2.3 uses MSL 3.2.3, and unfortunately _MSL 4.0.0 does not have a `noneFromVersion(3.2.3)` annotation_. Hence, _ModelicaServices 4.0.0 is actually not backwards-compatible with ModelicaServices 3.2.3_, and should be listed as such in the json file on our server. This would ensure that ModelicaServices 3.2.3 is loaded instead.

@sjoelund I guess you could implement this new definition of "backwards-compatible version" in the script that compiles the json file very easily. Could you do that in the next couple of weeks, so we can test it properly before the 1.19.0 release? Thanks!

**Comment by sjoelund** [comment]
The format of the index-file cannot really be changed (would need to create a new version and support the old one independently). What could be done is perhaps putting it as conversion required. But then you cannot use the index to know which packages need to be converted anymore. Or duplicating some information and adding a new field for isCompatibleWith. But really it is duplicate information since it could just as well be calculated client-side with something we anyway need to implement.

**Comment by casella** [comment]
> The format of the index-file cannot really be changed (would need to create a new version and support the old one independently).

Of course I don't want to do that, though I understand we could add more information to the json file without creating backwards-compatibility issues.

> What could be done is perhaps putting it as conversion required. But then you cannot use the index to know which packages need to be converted anymore. Or duplicating some information and adding a new field for isCompatibleWith. But really it is duplicate information since it could just as well be calculated client-side with something we anyway need to implement.

OK, I guess I get your point, sorry but it's a bit complicated. You wrote:

> Because there are noneFromVersion annotations on ModelicaServices 4.0.0 saying it's the same as 3.2.3, when we try to install MSL 3, Services 4 is installed and because Services 4 depends on MSL 4, that gives a warning.

There is some mechanism in place already we are using that provides this information, I understand it is `getAvailablePackageVersions()`. This is what we I currently get after running `updatePackageIndex()`:
```
getAvailablePackageVersions(ModelicaServices, "3.2.3")
{"4.0.0+maint.om","4.0.0+default.modelica.association","3.2.3+maint.om","3.2.3+default.modelica.association","trunk","4.0.0-master"}
```
I don't know exactly how this API function is implemented, but I understand that:
- it uses information from https://libraries.openmodelica.org/index/v1/index.json, which is updated automatically based on the setup in https://github.com/OpenModelica/OMPackageManager/blob/master/repos.json
- this information includes backwards-compatibility information obtained from the noneFromVersion annotations of the library
- specifically, this information is contained in a "provides" field, which lists the backwards-compatible versions for each version of a library

My suggestion was that you shortened the "provides" list to only include versions which don't need a conversion and whose dependencies don't either. But then, we would lose the information about when we actually need to run conversions scripts.

So, what we'd need to do is to improve getAvailablePackageVersions(SomePackage, "x.y.z") so that it not only looks at the "provides" lists of the library in question to find all backwards-compatible versions and then ordering them according to semver priority, but also checks the provides lists of the dependencies. I came up with the following pseudo-code:
```
input SomePackage x.y.z
get the full list LP of versions of SomePackage
// remove from LP versions that are not compatible based on noneFromVersion
for each SomePackage p.q.r in LP loop
  if SomePackage p.q.r doesn't have x.y.z in the provides list then remove it from LP
end for
// further remove from LP versions whose dependencies are not compatible based on noneFromVersion
get the list LD of dependencies of SomePackage x.y.z from its "uses" list, each with its version 
for each SomePackage p.q.r in LP
  bw_compatible = true
  for each DependencyPackage a.b.c in the uses list of  SomePackage p.q.r loop
    if DependencyPackage a.b.c. does not "provide" the version of DependencyPackage in list LD then bw_compatible = false
  end for
  if not bw_compatible then remove SomePackage p.q.r from LP
end for
return LP
```

Could you consider implementing that? It should be fairly straightforward for you.

Thanks!

**Comment by sjoelund** [comment]
> My suggestion was that you shortened the "provides" list to only include versions which don't need a conversion and whose dependencies don't either. But then, we would lose the information about when we actually need to run conversions scripts.

Yes. But looking at the JSON-file, I suppose we could extend it to have:
* provides
* noneFromVersion - provides
* convertFromVersion

Note that changing the index in this way does not change the metadata of already installed packages though. So they might still have the bad provides in them.

I'll see if this can be done. I suppose by doing the dependency resolution while creating the index we get some sort of sanity check as well, but not for the `version="X.X.X"` which will always be provided (it's a separate non-optional field)

**Comment by casella** [comment]
> > My suggestion was that you shortened the "provides" list to only include versions which don't need a conversion and whose dependencies don't either. But then, we would lose the information about when we actually need to run conversions scripts.
> 
> Yes. But looking at the JSON-file, I suppose we could extend it to have:
> 
>     * provides
> 
>     * noneFromVersion (= noneFromVersion - provides)
> 
>     * convertFromVersion
> 
> 

LGTM.

> Note that changing the index in this way does not change the metadata of already installed packages though. So they might still have the bad provides in them.

We could suggest users to flush the installed package when upgrading to 1.19.0. Is there any "clean" way to do that, beyond manually deleting the contents of the installation file? 
 
> I'll see if this can be done. I suppose by doing the dependency resolution while creating the index we get some sort of sanity check as well, but not for the `version="X.X.X"` which will always be provided (it's a separate non-optional field)

Good.

Thanks!

**Comment by sjoelund** [comment]
So this is something that only happens for Modelica and ModelicaServices. And the thing is that these require each other of the exact same version. If you have uses Modelica="3.2.2" ModelicaServices="3.2.3", you need Modelica="3.2.3" and vice versa.
If I try to fix it the way I wanted to like above, I end up with no provides for ModelicaServices. But I actually do want to allow loading of MSL 3.2.3 when 3.2.2 is requested by one library and 3.2.3 by another. So it is much harder than I initially though to handle this. I'll see if it's possible to handle this in a generic way...

**Comment by casella** [comment]
Interesting that nobody found out so far...

**Comment by casella** [comment]
I opened #8268 on the specific issue of resolving the cyclic dependencies

**Comment by casella** [comment]
@sjoelund, I just tried to run File | Upgrade packages in the latest nightly build of OMEdit. I got some proper messages such as
```
[3] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Complex 3.2.3+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA e68d7a0317c565ee00c1b8d44c527979ea0304bf).

[4] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Complex 4.0.0+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA c11123102e94d4b5acb139331a6d85f45d8adcc0).

[5] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries//Complex 4.0.0+maint.om: 0:0-0:0]: Complex  will not be installed since version 4.0.0+maint.om is installed.

[6] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/ModelicaServices 3.2.3+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA e68d7a0317c565ee00c1b8d44c527979ea0304bf).

[7] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA e68d7a0317c565ee00c1b8d44c527979ea0304bf).

[8] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/ModelicaServices 4.0.0+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA c11123102e94d4b5acb139331a6d85f45d8adcc0).

[9] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Modelica 4.0.0+maint.om/package.mo: 0:0-0:0]: Package installed successfully (SHA c11123102e94d4b5acb139331a6d85f45d8adcc0).

[10] 10:35:12 Scripting Notification
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries//Modelica 4.0.0+maint.om: 0:0-0:0]: Modelica  will not be installed since version 4.0.0+maint.om is installed.
```
but then I got this in red:
```
[11] 10:35:13 Scripting Error
[C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/index.json: 0:0-0:0]: The package index did not contain an entry for package ModelicaReference of version . There are other versions that claim to be compatible: 4.0.0+maint.om, 3.2.3+maint.om, 3.2.2+maint.om, 3.2.1+maint.om, 3.2.0+maint.om, 3.1.0+maint.om, 3.0.1+maint.om, 3.0.0+maint.om, 4.0.0-trunk, 4.0.0-master.
```
I guess there's still something wrong with the way Modelica Reference is handled.

**Comment by bilderbuchi** [comment]
I just installed MSL3.2.+maint.om via the package manager, but after unloading `Modelica` and opening MSL3.2.+maint.om via the System libraries menu, I get
```
[1] 11:50:05 Syntax Error
[C:/Users/bla/AppData/Roaming/.openmodelica/libraries/Modelica 3.2.3+maint.om/Mechanics/MultiBody/Examples/Constraints.mo: 20:24-20:33]: No viable alternative near token: Prismatic

[2] 11:50:05 Scripting Error
Failed to load package Modelica (3.2.3+maint.om) using MODELICAPATH C:/OpenModelica1.19.0-dev-64bit/lib/omlibrary;C:/Users/bla/AppData/Roaming/.openmodelica/libraries/.
```
and it does not open successfully. Is that only happening for me? Should I report this as a separate issue or could it be connected to this?
(I tried this upgrading step, and get similar/identical output to Francesco's.)

**Comment by casella** [comment]
This issue should now be resolved both in Windows and in Linux. Version 4.0.0 of Complex and ModelicaServices are loaded, which are backwards compatible.

**Comment by casella** [comment]
@bilderbuchi would you mind trying out the package manager once more? We fixed several issues in the last few weeks. 

You can use the nighly build until we release 1.19.0-beta.1 later this week, then you can use the beta for testing.

**Comment by bilderbuchi** [comment]
Yes, this works correctly now, thank you!
