### ISSUE TITLE
Finalize package management documentation

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8147]
The section of the User's Guide dealing with the package manager and conversion scripts needs to be finalized for 1.19.0.

PR #8146 significantly expands the original text. Information about the OMEdit GUI is still missing and should be added before the release.

**Comment by casella** [comment]
There are two remaining open points here, as I understand
- reinstate the package manager mos script in the documentation, as suggested by @sjoelund [here](https://github.com/OpenModelica/OpenModelica/pull/8146#discussion_r749950343). I don't think it is really necessary in that section of the documentation, I'm not sure if it is needed elsewhere
- fix #8183, so that it is also consistent with the documentation
- add cross-references to the API documentation, I need help to do that because I have no clue how this can be done

**Comment by casella** [comment]
See #8263

**Comment by adeas31** [comment]
> reinstate the package manager mos script in the documentation, as suggested by @sjoelund [here](https://github.com/OpenModelica/OpenModelica/pull/8146#discussion_r749950343). I don't think it is really necessary in that section of the documentation, I'm not sure if it is needed elsewhere

I don't think there is any need to add the mos-script back. The latest documentation by @casella doesn't use any API call so setting the environment is not needed.

> add cross-references to the API documentation, I need help to do that because I have no clue how this can be done

Done.
