### ISSUE TITLE
Error: post-optimization module wrapFunctionCalls (simulation) failed

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#8166]
### Description

When building the attached model [logical_op_Total.zip](https://github.com/OpenModelica/OpenModelica/files/7562260/logical_op_Total.zip) you get this error:
`Error: post-optimization module wrapFunctionCalls (simulation) failed`

### Steps to Reproduce

```
adrpo33@ida-0030 MINGW64 /e/dev/embrace
# omc logical_op_Total.mo +s
```

### Expected Behavior

Code should be generated.

**Comment by mahge** [comment]
@adrpo #8196 might have fixed this but I have not verified if the result is actually correct. I think it should be fine. You can check it and merge the PR if everything is good.

**Comment by AnHeuermann** [comment]
Should we always return the error message in https://github.com/OpenModelica/OpenModelica/pull/8196/files#diff-9cc4431be7f701499677dfee1e848acbe3beb830f1fe4fa16b25514b55ebbe12R1483-R1488?

Thant we can find the error faster next time.

**Comment by adrpo** [comment]
Fixed via #8196. @mahge can you add the test model in the testsuite or should I?

**Comment by mahge** [comment]
Tomorrow 🙂.

**Comment by mahge** [comment]
Added in #8223.
