### ISSUE TITLE
Bad display of copied parameter

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8170]
### Description
Resistor value is erroneously shown to be zero

### Steps to Reproduce
Just load test.mo (below) and look at its diagram
[Test.mo.txt](https://github.com/OpenModelica/OpenModelica/files/7565888/Test.mo.txt)

The diagram shows resistor1.resistance being 0. Instead, it is r1.R.

This is not a tricky example: copying parameters from a component to another is very helpful and commonly used whenever a parameter should be forcedly be kept equal to another.

### Version and OS
1.19.0-dev-336 64 bit, Win11.
(works with 1.18.0)

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@adeas31, is this an API problem or an OMEdit problem?

**Comment by max-privato** [comment]
This issue is not present anymore in 1.20.0
