### ISSUE TITLE
Add library dependency in annotation after duplicating a model

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#8174]
This is a feature request.

If I graphically drag and drop a model from a (system) library (e.g. `ElectroMechanicalDrives.Components.Vehicles.Vehicle`) into a user model, then the library dependency is inserted correctly. In case of ElectroMechanicalDrives 2.4.0 this is 

```modelica
  annotation(
    uses(ElectroMechanicalDrives(version = "2.4.0")));
```

If I create a duplicate of e.g. `ElectroMechanicalDrives.Components.Vehicles.Vehicle` in a user package, then the annotation is not inserted even though it is clear that duplicating a model from ElectroMechanicalDrives causes a dependency of this library. It were beneficial, if such library dependency were inserted automatically after duplicating a model from another library.

**Comment by casella** [comment]
@adeas31 can you please take care of that?

**Comment by abuntrock** [comment]
@casella You mentioned in your release notes for the 1.22 beta6 (https://github.com/OpenModelica/OpenModelica/releases/tag/v1.22.0-dev.beta.6) that a fully functional duplicate feature is planned for the 1.23.0. Can I assume that this ticket will be part of this upcoming workpackage? 

We also encountered the same problem with examples that we provide with our BRSL library. One of their main purposes is duplication to serve as a blueprint for the users system.

**Comment by casella** [comment]
> @casella You mentioned in your release notes for the 1.22 beta6 (https://github.com/OpenModelica/OpenModelica/releases/tag/v1.22.0-dev.beta.6) that a fully functional duplicate feature is planned for the 1.23.0. Can I assume that this ticket will be part of this upcoming workpackage?

Sure.
 
> We also encountered the same problem with examples that we provide with our BRSL library. One of their main purposes is duplication to serve as a blueprint for the users system.

That's a requirement for a lot of people 😅

**Comment by abuntrock** [comment]
Maybe the current nightly (which is named 1.24-dev) has some other problems but when I try to duplicate a class (e.g. `Modelica.Blocks.Examples.PID_Controller`), the current OMEdit nightly crashes completely.

**Comment by perost** [comment]
> Maybe the current nightly (which is named 1.24-dev) has some other problems but when I try to duplicate a class (e.g. `Modelica.Blocks.Examples.PID_Controller`), the current OMEdit nightly crashes completely.

It crashes if you try to put the duplicated class at the top-level, i.e. without specifying a path. I don't know if that was what you tried to do but it looked like it from the crash logs. I opened #12218 for that issue.

**Comment by abuntrock** [comment]
Yes. That's exactly what I tried to do. Thanks for opening the new issue.
