### ISSUE TITLE
Wrong SimulationResults record when running simulations from a script

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8175]
Run the attached test.mos on the attached M.mo. The following log is obtained:
```
true
""
record SimulationResult
    resultFile = "D:/Temp/OMEdit/M_res.mat",
    simulationOptions = "startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'M', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = '-lv=\\'LOG_STATS\\' -s=\\'ida\\''",
    messages = "LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_STATS         | info    | ### STATISTICS ###
|                 | |       | | timer
|                 | |       | | |    0.0010473s          reading init.xml
|                 | |       | | |    0.0001001s          reading info.xml
|                 | |       | | |    0.0003453s [ 25.6%] pre-initialization
|                 | |       | | |    0.0001315s [  9.7%] initialization
|                 | |       | | |        4e-07s [  0.0%] steps
|                 | |       | | |    0.0002444s [ 18.1%] solver (excl. callbacks)
|                 | |       | | |    0.0001967s [ 14.6%] creating output-file
|                 | |       | | |     1.34e-05s [  1.0%] event-handling
|                 | |       | | |     9.08e-05s [  6.7%] overhead
|                 | |       | | |    0.0003266s [ 24.2%] simulation
|                 | |       | | |    0.0013491s [100.0%] total
|                 | |       | | events
|                 | |       | | |     0 state events
|                 | |       | | |     0 time events
|                 | |       | | solver: ida
|                 | |       | | |    37 steps taken
|                 | |       | | |    44 calls of functionODE
|                 | |       | | |    16 evaluations of jacobian
|                 | |       | | |     0 error test failures
|                 | |       | | |     0 convergence test failures
|                 | |       | | | 2.17e-05s time of jacobian evaluation
LOG_SUCCESS       | info    | The simulation finished successfully.
",
    timeFrontend = 0.0005965,
    timeBackend = 0.007882999999999999,
    timeSimCode = 0.0006306,
    timeTemplates = 0.0106144,
    timeCompile = 9.5818584,
    timeSimulation = 0.1328171,
    timeTotal = 9.7346389
end SimulationResult;
""
```

The `method = 'dassl'` indication is wrong and misleading, since ida is actually running, as reported by the runtime.

The correct `method = 'ida'` should be reported instead.

**Comment by sjoelund** [comment]
Why not use method="ida" instead of passing it as simflags? I'm not sure how OMC would detect the actual solver used in this case

**Comment by casella** [comment]
[Test.zip](https://github.com/OpenModelica/OpenModelica/files/7569918/Test.zip)

**Comment by casella** [comment]
> Why not use method="ida" instead of passing it as simflags? 

Because it's there 😄 

I mean, why shouldn't one be allowed to do that?

I'm not sure how OMC would detect the actual solver used in this case

**Comment by casella** [comment]
`startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06` are all standardized annotations, so it is clear what they mean. What is `method`? And what relation does it have with the -s option? This is unclear to me...

**Comment by sjoelund** [comment]
`simflags` was not an option to the simulate command in the past. You had to use the `method` option. It sets the default solver method in the XML-file (which `-s` may override).

**Comment by casella** [comment]
Yeah, I understand the software grows organically and it is somehow inevitable to end up with some sub-optimal situations. There is a technical reason for that, but from a user's point of view, it's just contradictory and, hence, confusing.

Luckily in this case we have very clear feedback about the actual solver being used (ida, that is), so one comes to the conclusion that notifications are a bit sloppy and lives with it...
