### ISSUE TITLE
Debian package repositorydoes not have Release file so apt update fails with error

### ISSUE THREAD

**Issue by reos-rcrozier** [OpenModelica/OpenModelica#8176]
### Description
I followed the instruction to install OpenModelica from the debian/ubuntu package repository as detailed [here](https://www.openmodelica.org/download/download-linux). After doing so, `apt update` fails with the following error:

```
Ign:12 https://build.openmodelica.org/apt uma InRelease
Err:13 https://build.openmodelica.org/apt uma Release
  404  Not Found [IP: 192.36.54.111 443]
Reading package lists... Done
E: The repository 'https://build.openmodelica.org/apt uma Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
And therefore OpenModelica cannot be installed

### Steps to reproduce
This could either be a list of actions or a Modelica script file (mos) that uses the [OpenModelica scripting API](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html).

### Version and OS
 - Ubuntu 20.04

**Comment by sjoelund** [comment]
`uma` is not Ubuntu 20.04 - use the name `focal` if the distribution is based on Ubuntu 20.04. I have added a symbolic link for it now though: https://build.openmodelica.org/apt/dists/uma/
