### ISSUE TITLE
Changed name is not displayed in Diagram View

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#8180]
### Description

When renaming a graphical component by changing its attribute, the newly given name is not displayed.

### Steps to Reproduce

Create a new test Model `Test` and graphically add the component `Modelica.Electrical.Analog.Basic.Ground` to the model. Confirm the standard name.

![image](https://user-images.githubusercontent.com/4184218/142723772-19dfdb83-7f5b-479a-83a1-68b56256cdc5.png)

Then make a right click on the ground a choose **Attributes** from the context menu

![image](https://user-images.githubusercontent.com/4184218/142723853-9ae76910-bf8a-4742-b72a-bfa24859e851.png)

Change the name to `ground2` and confirm with **OK**

![image](https://user-images.githubusercontent.com/4184218/142723875-ce817e2d-9e0f-4fc2-8c53-a03843a1301d.png)

The changed name is *not displayed*:

![image](https://user-images.githubusercontent.com/4184218/142723918-3ec178bf-08fc-4a7d-8c56-bffc8636d471.png)

### Expected Behavior

The changed name shall be displayed in the Diagram View.

### Version and OS

- OpenModelica 1.19.0~dev-388-gb35aa9c
- Linux Mint 20.2 x86_64

**Comment by casella** [comment]
@adeas31 I guess we should refresh all the cached stuff after renames.

**Comment by adeas31** [comment]
This is a regression probably because of new Expression class. I will try to fix it.
