### ISSUE TITLE
Resolving conflicts with loaded libraries when opening new ones

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8183]
Suppose you open a library XXX that uses a version of some library YYY (e.g. MSL 3.2.3), but another, non-backwards compatible version of YYY (e.g. MSL 4.0.0) is already loaded. In this case, OMEdit should warned that the library being loaded uses versions of already loaded libraries which are not compatible with the required ones. It should then propose three possible actions:

1. cancel the operation: library XXX is unloaded
2. unload everything and reload library XXX from the start (in most cases this will work out of the box thanks to the uses annotations)
3. upgrade library YYY to use the already opened version of XXX, using conversion scripts (only if a conversion script is available, which would not be the case here, since there is no conversion script from MSL 4.0.0 to 3.2.3

The first option is required in case one opens the wrong version by mistake, and only figures that out when OMEdit warns him about that.

The second can be handy if one has the "wrong" default loaded version of MSL, or has messed up loading the wrong dependencies of a library first.

I'm not sure if the third option is good to have. This is what Dymola does: it starts preloading MSL 4.0.0, and then if you load a library that uses 3.2.3, it immediately offers you to upgrade it. However, upgrading a library is a big deal, because it is an irreversible operation. 

I would personally prefer that the upgrade operation is performed explicitly by first loading the library and the using right-click "convert to newer versions of used libraries". BTW, in that case, once the conversion is done, the old dependencies should be unloaded, and the new ones should be loaded instead.

**Comment by casella** [comment]
As of v1.19.0-dev-697-gfa7189b918, if first load MSL 4.0.0 and then I open the following package
```
package TestConversion
  model M
    Modelica.SIunits.Length L = 1;
  end M;
  annotation(uses(Modelica(version="3.2.3")));
end TestConversion;
```
I get the following notification:
```
[1] 23:52:47 Scripting Warning
TestConversion requested package Modelica of version 3.2.3. Modelica 4.0.0 is used instead which states that it is only compatible with a conversion script. OpenModelica currently does not support conversion scripts and will proceed with potential issues as a result.
```
This is not correct and misleading for multiple reasons:
- OpenModelica actually does support conversion scripts (or at least claims to...)
- In any case there is no conversion script to downgrade from MSL 4.0.0 to MSL 3.2.3
- "Potential issues" are actually "certain issues", since 99% of models use SI units, and those are guaranteed not to work if you load the wrong version of MSL, because they changed place.

**Comment by adeas31** [comment]
> cancel the operation: library XXX is unloaded

A lot of time the library XXX uses more than one libraries. So if a library XXX that uses a version of some library YYY and another library ZZZ. A non-backwards compatible version of YYY (e.g. MSL 4.0.0) is already loaded but ZZZ is not loaded. In that case when XXX is loaded then ZZZ is also loaded automatically. So if we are to cancel the operation then shall we also unload ZZZ?

> I would personally prefer that the upgrade operation is performed explicitly by first loading the library and the using right-click "convert to newer versions of used libraries". BTW, in that case, once the conversion is done, the old dependencies should be unloaded, and the new ones should be loaded instead.

That is what we do right now. The old dependency is unloaded and the new one is loaded.

**Comment by casella** [comment]
> > cancel the operation: library XXX is unloaded
> 
> A lot of time the library XXX uses more than one libraries. So if a library XXX that uses a version of some library YYY and another library ZZZ. A non-backwards compatible version of YYY (e.g. MSL 4.0.0) is already loaded but ZZZ is not loaded. In that case when XXX is loaded then ZZZ is also loaded automatically. So if we are to cancel the operation then shall we also unload ZZZ?

I guess so. We attempted to load a certain version of XXX that was not valid (because it is not compatible with YYY). So one should assume that also its automatically loaded dependencies (ZZZ) would in general not be valid. If you cancel, you should gt rid of all the them.

> > I would personally prefer that the upgrade operation is performed explicitly by first loading the library and the using right-click "convert to newer versions of used libraries". BTW, in that case, once the conversion is done, the old dependencies should be unloaded, and the new ones should be loaded instead.
> 
> That is what we do right now. The old dependency is unloaded and the new one is loaded.

OK, good. Then, let's just keep options 1. and 2., if possible. 

Option 1 brings me back to the status where I was before attempting to load the incompatible XXX (and its automatically loaded dependencies). This means: oops, I opened the wrong version of XXX, so I want to go back to the previous status and then I'll open the right one.

Option 2 instead means: I do really want this version of XXX, so clean up everything and load the right dependencies from scratch.

If I want to upgrade XXX to newer versions of used libraries, I start loading it and then use the upgrade menu. This is not what Dymola does, Dymola expects you to first load the newerr YYY (i.e. MSL 4.0.0), and then when you tried to load XXX asks if you want to upgrade it. Personally I don't like this very much and I prefer to do that the other way round.

@adeas31, does this make sense to you?
