### ISSUE TITLE
OMEdit Install Libraries feedback on `OK` button

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8187]
### Description

OMEdit "freezes" while installing libraries via File->Install Library.
The feature itself is great and works finde. But I guess when your internet connection is (very) slow users will wonder if anything happens at all.

### Steps to Reproduce

Download some Modelica library that takes some time to download, e.g. Buildings.
Open the Packate manager GUI in OMEDit via File->Install Library. Select Buildings and click `OK`.
Nothing will happen, until the Download finished and a scripting notification will appear:
```
[4] 10:42:12 Scripting Notification
[C:/Users/UserName/AppData/Roaming/.openmodelica/libraries/index.json: 0:0-0:0]: Downloaded package index from URL https://libraries.openmodelica.org/index/v1/index.json.

[5] 10:43:02 Scripting Notification
[C:/Users/UserName/AppData/Roaming/.openmodelica/libraries/Buildings 8.0.0/package.mo: 0:0-0:0]: Package installed successfully (SHA 5fa0bed0caa0f27b8ebfa20c1a39e22cdd0f5008).
```

Clicking the `OK` button multiple times seems to be safe, though.

### Expected Behavior

Give some feedback that the click on `OK` did start the download/installation.
Some sort of progress bar would be perfect. A text status in the message browser every few seconds would be fine as well.

Or jsut a simple message that the download startet
```
[2] 10:42:12 Scripting Notification
Buildings 8.0.0 is not installed.
Start downloading Buildings 8.0.0

[4] 10:42:12 Scripting Notification
Finished downloading Buildings 8.0.0

[5] 10:43:02 Scripting Notification
[C:/Users/UserName/AppData/Roaming/.openmodelica/libraries/Buildings 8.0.0/package.mo: 0:0-0:0]: Package installed successfully (SHA 5fa0bed0caa0f27b8ebfa20c1a39e22cdd0f5008).
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/38031952/142838996-2b3fe8e1-a7d9-4f32-9f87-07b4d458830c.png)

### Version and OS

 - OpenModelica Version: OpenModelica v1.19.0-dev-317-gc49166fd59
 - OS: Windows 10, 64 bit

**Comment by sjoelund** [comment]
This could be resolved by passing flags to libcurl from OMEdit: https://curl.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html

**Comment by adeas31** [comment]
@AnHeuermann #8226 includes a message "Installing library" in the dialog when users clicks on ok button. If you prefer more detailed messages like download started and finished as you proposed in the issue then we take it later on.
