### ISSUE TITLE
Error regarding libexpat in OMEdit compilation window

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8195]
Whatever model I compile with the latest nightly build version of OMEdit, I always see this red line in the compilation windows output:
```
C:\PROGRA~1\OPENMO~2.0-D\tools\msys\mingw64\bin\ld: skipping incompatible C:/Program Files/OpenModelica1.19.0-dev-64bit/bin/libexpat.dll when searching for -lexpat
```
@adrpo, @mahge, any idea what is going wrong here?

**Comment by mahge** [comment]
I can see that we copy libexpat.dll to OpenModelica bin directory from OMDev,  here

https://github.com/OpenModelica/OpenModelica/blob/0aeaad6d97beda4529ef1f2b1027cb2d9b8074e2/OMCompiler/Makefile.omdev.mingw#L297-L299

However, I am not sure why it just started to show any messages in OMEdit. This has been there for a long time (added 7 years ago). Maybe it is an improvement from OMEdit side or maybe it became "incompatible" when OMDev got updated and we never noticed.

Anyway, it is probably not needed now. We build, install and use, a static version of `libexpat` that comes with `FMIL`.  That is probably why it is working despite the warning (it should not be a red message if possible). 

Let's wait for @adrpo and if there is no reason for it I will remove the copy and see what happens. I do not expect anything to fail.

**Comment by adrpo** [comment]
I think it is needed for the msvc runtime as far as I remember.

**Comment by mahge** [comment]
We build FMIL with msvc. Maybe we can try to use the static `libexpat` from there if whatever is needing this DLL does not actually require it to be a DLL. 

I will see if I can fix it.

**Comment by casella** [comment]
Thanks @mahge! I'll check with the next nightly that all's fine in OMEdit.

**Comment by casella** [comment]
Indeed all red messages are now gone, which is good for 1.19.0 😃
