### ISSUE TITLE
Optionally avoid flattening record members in flat Modelica output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8197]
@perost, hopefully one last favour to support our high-performance code generation starting from the flat vector-preserving Modelica output.

Currently, records are flattened to their basic type components, even though they may appear as whole record instances in some cases, e.g.
```Modelica
record M.R
  input Real x;
  input Real y;
end M.R;

function M.f
  input Real x;
  output M.R r;
algorithm
  r.x := x;
  r.y := 2.0 * x;
end M.f;

class M
  Real r1.x;
  Real r1.y;
  Real r2.x;
  Real r2.y;
  Real r3.x;
  Real r3.y;
equation
  r1 = M.f(time);
  r2 = r1;
  r3.x = r2.y;
  r3.y = r2.x;
```
In some equations, having r2.x and r2.y declared explicitly as Reals is of course good, but in other equations we just have `r1` or `r2`. In this case, our compiler needs to figure out what is the type of those variables, which is not completely trivial.

For our purposes, it would be much better if the flat output actually did not flatten records to their members in the declarations, but rather kept them as records, i.e.
```Modelica
record M.R
  input Real x;
  input Real y;
end M.R;

function M.f
  input Real x;
  output M.R r;
algorithm
  r.x := x;
  r.y := 2.0 * x;
end M.f;

class M
  R r1;
  R r2;
  R r3;
equation
  r1 = M.f(time);
  r2 = r1;
  r3.x = r2.y;
  r3.y = r2.x;
```
we can then expand the records where needed in our backend. Of course this should also work if we have records inside instantiated models, but I guess that comes naturally.

Could you add this feature under some flag, e.g. `-d=dontFlattenRecords`?

I cc: @ennioquaglia so he's up-to-date with the development.

**Comment by perost** [comment]
The flag `--newBackend` actually does this currently, in case you don't care about which backend is used.

**Comment by casella** [comment]
> The flag `--newBackend` actually does this currently, in case you don't care about which backend is used.

No, we don't 😄 

@ennioquaglia, one more flag for you to consider, please keep the list up-to-date somewhere.
