### ISSUE TITLE
While exporting to CSV from plot, the values attached to pressure source or sink (constant pressure boundary) the first two values are in pascal and rest are in bars

### ISSUE THREAD

**Issue by Vivek106singh** [OpenModelica/OpenModelica#8206]
### Description
When exporting to CSV from plot, the values attached to pressure source or sink, first two values are in pascal and rest are in bars. This I got when I exported hex.infl.p and hex.outfl.p in the model "ThermoPower.Test.DistributedParameterComponents.TestWaterFlow1DFV2ph_Cmodel" this happened when the pressure was constant at one of the boundary. 
I checked with other models also were pressure was not constant, there was no issue. also i checked with enthalpy and other variables they were also correct.
Then I exported the the value that was wrongly exported earlier. It showed only two values one at the 0s and other at 250s. 

### Steps to Reproduce

Run the model "ThermoPower.Test.DistributedParameterComponents.TestWaterFlow1DFV2ph_C" and export "hex.outfl.p" to csv from plotting view. Screenshots will make issue clear. The issue happened in version 1.18 and 1.19

### Version and OS

 - OpenModelica Version:1.18 and 1.19 Nightlybuild
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

### Additional Context

<!--- Add any other context about the problem here. --
![Capture1](https://user-images.githubusercontent.com/12408991/143061588-a2f0ede1-c65f-4fa5-8f58-fd46faa09009.PNG)
![Capture2](https://user-images.githubusercontent.com/12408991/143061600-e3c399fb-c059-4297-bf53-47539ed5ae16.PNG)
![Capture3](https://user-images.githubusercontent.com/12408991/143061604-302716f9-1851-4b0b-89e4-edd705068893.PNG)
>

**Comment by Vivek106singh** [comment]
![Capture1](https://user-images.githubusercontent.com/12408991/143062444-3a55699a-46b6-43cc-a349-45dcf765c0e4.PNG)
![Capture2](https://user-images.githubusercontent.com/12408991/143062454-1f5fab69-7534-479a-9f01-a93ab2b2fbcd.PNG)
![Capture3](https://user-images.githubusercontent.com/12408991/143062460-eb0c1948-f925-4794-ac1a-21240129385e.PNG)

**Comment by adeas31** [comment]
> When exporting to CSV from plot, the values attached to pressure source or sink, first two values are in pascal and rest are in bars.

All the values should be exported in pascal. #8212 fixes this issue.

> Then I exported the the value that was wrongly exported earlier. It showed only two values one at the 0s and other at 250s.

The parameters just have start and stop data points so if you just export a single parameter you will only get start and stop. If you export a parameter along with a variable, as you did earlier, you will get constant value for parameter for all data points.
