### ISSUE TITLE
Buildings simulations segfaulting

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8219]
There are 8 models in Buildings 7.0.x that fail with segmentation fault on Jenkins, see report starting from [Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.ShaGFunction](https://libraries.openmodelica.org/branches/master/Buildings_maint.7.0.x/files/Buildings_maint.7.0.x_Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.ShaGFunction.err). 

Causes seem somehow related. @mahge, could you please investigate a bit?

Thanks!

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by sjoelund** [comment]
```
/home/marsj/.openmodelica/libraries/Buildings 9.0.0-master/Resources/C-Sources/cryptographicsHash.c:301:21: warning: implicit declaration of function 'ModelicaAllocateString' is invalid in C99 [-Wimplicit-function-declaration]
  char* hexresult = ModelicaAllocateString(40);
                    ^
/home/marsj/.openmodelica/libraries/Buildings 9.0.0-master/Resources/C-Sources/cryptographicsHash.c:301:9: warning: incompatible integer to pointer conversion initializing 'char *' with an expression of type 'int' [-Wint-conversion]
  char* hexresult = ModelicaAllocateString(40);
        ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This causes half of the pointer to be lost since the default is to assume a 32-bit integer is returned. It's an error in the library (not including `ModelicaUtilitites.h`) and seems to affect at least Buildings 7..master
