### ISSUE TITLE
Flat Modelica output strips comments

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8228]
If I flatten the following test model with -f
```Modelica
model TestFlatComments "Model to test comments in Flat Modelica output"
  Real x "Some variable";
  Real y "Some other variable";
equation
  x + y = 0 "Some equation";
  x - y = 1 "Some other equation";
end TestFlatComments;
```
I get
```Modelica
class 'TestFlatComments'
  public Real 'x';
  public Real 'y';
public
equation
  'x' + 'y' = 0.0;
  'x' - 'y' = 1.0;
end 'TestFlatComments';
```
I'm not sure if the comments were stripped on purpose, but it seems to me that they could be of good use to any downstream tool, since they carry valuable information regarding the meaning of equations and variables in the model. I would rather keep them, as it happens in the regular flat Modelica output.

**Comment by perost** [comment]
I also realised we don't output annotations either, except for functions. I don't know how annotations are supposed to be handled in Flat Modelica, but I added them anyway for now.

**Comment by casella** [comment]
I hope that `--showStructuralAnnotations` only keeps the structural ones there as well

**Comment by perost** [comment]
> I hope that `--showStructuralAnnotations` only keeps the structural ones there as well

Printing all annotations was not a good idea in hindsight, I changed it to always just print structural annotations. We could make it depend on the flag, but I think we want the default to be only structural annotations and the flag is `false` by default.

**Comment by casella** [comment]
LGTM
