### ISSUE TITLE
Implementation of horizontalAlignment=TextAlignment not correct

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#8236]
annotation(Icon(graphics={
      Rectangle(extent={{-100,100},{100,-100}}, lineColor={0,0,255},
        fillColor={255,255,255}, fillPattern=FillPattern.Solid, radius=10),
      Rectangle(extent={{-94,94},{94,6}}, lineColor={0,0,255},
        fillColor={215,215,215}, fillPattern=FillPattern.Solid),
      Ellipse(extent={{-80,-10},{-20,-70}}, lineColor={0,0,255},
        fillColor={215,215,215}, fillPattern=FillPattern.Sphere),
      Ellipse(extent={{20,-10},{80,-70}}, lineColor={0,0,255},
        fillColor={215,215,215}, fillPattern=FillPattern.Sphere),
      Text(extent={{-140,140},{140,100}}, lineColor={0,0,255},
        textString="%name"),
      Text(extent={{-80,60},{80,40}}, textColor={0,0,0},
        textString="%V0", horizontalAlignment=TextAlignment.Left),
      Text(extent={{-80,30},{80,10}}, textColor={0,0,0},
        textString="%I0", horizontalAlignment=TextAlignment.Right),
      Text(extent={{-60,-30},{-40,-50}}, textColor={0,0,0},
        textString="V"),
      Text(extent={{40,-30},{60,-50}}, textColor={0,0,0},
        textString="A"),
      Text(extent={{-90,90},{90,70}}, textColor={0,0,0},
        textString="%P0")}));
![grafik](https://user-images.githubusercontent.com/6900273/143719745-47d900db-9cf4-4cd5-a593-ef33aebde44f.png)
Looks fine, but after flipping the component horizontal:
![grafik](https://user-images.githubusercontent.com/6900273/143719781-fe7b1c58-f8ae-4189-a5fb-bab087397d65.png)

v1.18.0 on Windows 10 64 bit

**Comment by casella** [comment]
@adeas31 if you can fix it quickly, otherwise please reschedule to 1.20.0

**Comment by casella** [comment]
@adeas31 any chance we can get this in 1.19.0? If so, we can cheery-pick it after we branch off beta.1

**Comment by casella** [comment]
@adeas31, can we get this in 1.19.0?

**Comment by adeas31** [comment]
Fixed with #11691 and ported to maintenance/v1.22
