### ISSUE TITLE
cpp testing is broken on Jenkins

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8242]
On 6 Nov 2021 testing was resumed on a Jenkins server running an updated Ubuntu 20.04 LTS.

Among other things, all cpp tests reported 0 successful runs, giving this error:

> Running: ./testmodel.py --libraries=/home/hudson/saved_omc/libraries/.openmodelica/libraries/ --ompython_omhome=/usr PowerSystems_cpp_PowerSystems.Examples.AC1ph_DC.Drives.BLDC.conf.json
C++ runtime not supported in this installation (HelloWorld failed)

This is weird, since the tests do run in other Ubuntu 20.04 installations

@sjoelund reported:

> /usr/bin/ld: /home/hudson/saved_omc/master/bin/../lib/x86_64-linux-gnu/omc/cpp/libOMCppOMCFactory.a(OMCFactory.cpp.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
>
>https://stackoverflow.com/questions/34143265/undefined-reference-to-symbol-pthread-createglibc-2-2-5
>
>@Rüdiger: Seems -pthread is needed for CXXFLAGS or C++ runtime fails on Ubuntu 20.04. If it's used when compiling cppruntime libraries but not in the generated makefile, these kinds of errors may occur. Although I'm not sure why. I have other 20.04 systems and they don't require this... I'm also not sure what the best way to pass the flag only on C++ runtime systems is, or where to detect if it exists.

@adrpo will investigate what's wrong with pthread and try to get HelloWorld (and, consequently, the entire testsuite) working again.

Keeping @rfranke in the loop also.

**Comment by casella** [comment]
From today's webmeeting: @adrpo has made some investigations but not yet found out the cause. He will continue in the next days.

**Comment by casella** [comment]
@mahge will have a look ASAP

**Comment by casella** [comment]
You must use the `-pthread` flag when compiling, in the past it worked without, but now we need to have it

**Comment by adrpo** [comment]
Hopefully this is fixed now, I also ported it to maintenance/v1.18. We will see after the library coverage is ran.

**Comment by adrpo** [comment]
Adding @rfranke to the ticket so we can follow this properly.

**Comment by casella** [comment]
The cpp tests are back, see [report](https://libraries.openmodelica.org/branches/history/master/2021-12-13%2022:49:44..2021-12-14%2014:43:33.html). Thanks @adrpo!
