### ISSUE TITLE
Advanced alias elimination

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8272]
The current OpenModelica backend eliminates alias equations such as `x = y`, `x + y = 0`, where variable are equal up to their sign. This concept will be extended to constant-coefficient equations, e.g. `x = 2*y`, ending up in much smaller size code to be handled by the solver, with benefits on runtime performance.

Problem: how do you save them? Possible solution: define interesting outputs, and only apply extended alias elimination to variables which are not outputs. This is somewhat related to #8271.

Alternative solution: extend the file format by not only having aliases which are +/- the chosen representative variable, but that can have any coefficient besides +1/-1

@kabdelhak  can test it using the new backend with the following restrictions, which are fine for power grid models:
- daeMode (could take some time)
- no events
- no functions except built-in
- no algorithms
- no index reduction

The ScalableTestGrids library can be used for testing.

**Comment by sjoelund** [comment]
If the format is changed I would make aliases `y=a*x + b`. You'd need 2 more rows in the dataInfo matrix I believe. It's currently negative index for the a=-1, but if you want any coefficient it should simply be a new entry. That's easier. But you'd break backwards compatibility with other tools if this is added so it could be nice to enable the old format on a flag.

**Comment by casella** [comment]
This feature is now implemented in the new backend and tested in [RSE.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/simulation/modelica/NBackend/basics/RSE.mos) and [RSE2.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/simulation/modelica/NBackend/basics/RSE2.mos).

Unfortunately I can't yet test it on a power system model because the new backend is not yet good enough to do that.
