### ISSUE TITLE
Newlines in strings not handled correctly in Jenkins reports.

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8279]
Error messages reported by the Jenkins testing infrastructure often contain strings, which are terminated by `\n` instead of a proper carriage return, which makes reading those error messages much harder than it already is.

For example, you can check https://libraries.openmodelica.org/branches/master/TILMedia/files/TILMedia_TILMedia.Testers.TestVLEFluidObjectFunctions.err or https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Electrical.Transmission.Functions.Validation.SelectCable_med.err

**Comment by perost** [comment]
Both the examples are now fixed and give no error messages during C code compilation, so here are some other ones that still do:
https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Clocked.Examples.Elementary.RealSignals.SampleWithADeffects.err
https://libraries.openmodelica.org/branches/master/ThermoPower/files/ThermoPower_ThermoPower.PowerPlants.SteamTurbineGroup.Tests.TestTurbineHPefficiency.err

**Comment by casella** [comment]
> Both the examples are now fixed and give no error messages during C code compilation

Inverse Murphy's law: if something should really go wrong, it won't 😄

**Comment by sjoelund** [comment]
Fixed by https://github.com/OpenModelica/OpenModelicaLibraryTesting/commit/ff65645d63aeea3d6fe151ff745e3fd0611cd3aa
