### ISSUE TITLE
Ask for a name when duplicating or copying/pasting models

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8282]
### Description

When dropping models from MSL OMEdit asks for a name for the model.
When we duplicate or copy/paste a model it doesn't.
I think it would be better if it asked for a name also in these cases.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
BTW, this was a duplicate of https://trac.openmodelica.org/OpenModelica/ticket/5967. @max-privato, you should take over my role of ticket-opener, apparently you are more effective at getting things fixed 😄

**Comment by max-privato** [comment]
@casella  I gladly leave the mastery of this to you!

I'm happy that @adeas31 is back. There are a few other tickets of mine dropped on GitHub during the last weeks...
