### ISSUE TITLE
Use the package manager only for installing system libraries

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8291]
If I run `getModelicaPath()` on my PC I get
```
C:/Program Files/OpenModelica1.19.0-dev-64bit/lib/omlibrary;
C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/
```
while if I do it on my Linux server I get
```
/usr/bin/../lib/omlibrary:
/home/casella/.openmodelica/libraries/
```
As I understand, the first directory was originally used before the package manager was introduced, the latter is instead used by the package manager. Unfortunately the former has precedence over the latter, which would cause messy behaviour when interacting with the package manager.

I also understand that the idea was to use the package manager only from 1.19.0, because it makes life much easier on our side (everything is decided and categorized in one place), and also gives greater flexibility and ease of use to end-users. We actually need to do this in 1.19.0.

The cleanest solution is probably to remove the first path entirely. However, this means that newbies will have to figure out advanced concepts such as package management before they can run the simplest HelloWorld models that use the MSL, or before they can actually use the MSL. I don't think this would be good.

My suggestion is that we swap the order of the two directories, and pre-install the MSL 3.2.3. and 4.0.0 (and dependencies) there when installing omc. This means that whatever is installed with the package manager has precedence, but if you don't install anything, MSL just works out of the box as a fallback option.

Last, but not least, the choice of libraries to install should disappear from the Windows installer entirely.

@adrpo, @sjoelund, @adeas31, @max-privato, what do you think?

**Comment by sjoelund** [comment]
Are you sure that's the order of preference? From what I remember the last directory has higher priority for some reason... Given identical version names.

**Comment by sjoelund** [comment]
Stupid implementation. It looks up and finds the first one first, then looks for better ones and replaces it with the last found. At least that's what I remember :)

**Comment by casella** [comment]
Well, the specification says:

> The version information for a library (as defined in section 18.8) may also be used during this search to search for a specific version of the library (e.g. if Modelica library version 2.2 is needed and the first directory in MODELICAPATH contain Modelica library version 2.1, whereas the second directory contains Modelica version 2.2, then Modelica library version 2.2 is loaded from the second directory.).

so this could actually make sense. The specification doesn't mention the case of a third directory containing Modelica 2.3 with noneFromVersion(2.2.), but I guess it could be in the spirit of the above quote to load that in this case.

In any case, if we keep the installation libraries to provide a fallback provision for the MSL, we should swap the order of those two directories in the MODELICAPATH.

**Comment by casella** [comment]
After discussion at today's devmeeting, we have this plan:
- [ ] remove the `lib/omlibrary` directory, which may point to obsolete installed stuff, from the MODELICAPATH
- [ ] when first running a newly installed version of OpenModelica, call the package manager to update the list of packages and to install the latest versions of MSL which are backwards-compatible with 3.2.3 and 4.0.0

**Comment by casella** [comment]
After some discussion, we figured out that most new users are on Windows, and they should get MSL out of the box without the need of additional installation processes, also in case of off-line or behind-a-firewall/proxy industrial installations

We may consider doing this in a future release if we manage to make the process straightforward, but it's too late to get it in 1.19.0

**Comment by casella** [comment]
I thought a bit how we can solve this issue. My requirements for the solution:
- it should work both on Linux and Windows, to avoid double implementation work
- it should be straightforward to implement, so we can get it in 1.20.0 without sweating
- system libraries under package management, no duplicate versions anywhere
- OMEdit works out of the box when started after installation, without the need of internet connection, automatically loading in the package browser the latest version of the MSL available when the release was built
- packages using older versions of the MSL should work without trouble
- handle the fact that each user can have different libraries in his package manager (.openmodelica directory) smoothly
- easily customized in to support off-line installations with customized sets of system libraries, e.g. for classroom use in corporate environments behind firewalls

Here is my proposal, that addresses all those points
- remove the `lib/omlibrary` directory from the installation directories
- remove the `lib/omlibrary` directory from the default MODELICAPATH
- build a basic system library setup containing versions 3.2.3 of the MSL and dependencies (the same we have in lib/omlibrary today), zip it and put it in the installer, so that it gets put into `lib/pkgman_cache.zip` or something
- when starting OMEdit, check if the .openmodelica/libraries directory is empty or nonexistent. In that case, fetch the `pkgman_cache.zip` from the installation directory and unzip it in the user's .openmodelica directory
- set the OMEdit factory defaults to load the latest version of MSL (4.0.0 as of today) when starting OMEdit
- add the File | Manage Libraries | Create library snapshot item, which takes the contents of the current .openmodelica directory and puts it in a pkgman_cache.zip file, that the user can save where he wants
- add the File | Manage Libraries | Load library snapshot item, which cleans up the user's .openmodelica directory, loads a pkgman_cache.zip file from the file system (e.g. a memory stick), and unzips it there

I think this solution addresses all the requirments. If one loads a package using MSL 3.2.3, OMEdit is already capable of recognizing that the pre-loaded MSL is not good, and offers to offload it and reload the library with the right dependencies. That's just one click, so it's ok. Advanced users that often switch between incompatible versions of MSL can of course disable loading MSL automatically, if they want.

@dietmarw, @adrpo, @adeas31, @sjoelund, what do you think?

**Comment by sjoelund** [comment]
> build a basic system library setup containing versions 3.2.3 of the MSL and dependencies (the same we have in lib/omlibrary today), zip it and put it in the installer, so that it gets put into lib/pkgman_cache.zip

I think I had a similar proposal somewhere, except:
Have some `.../index.json` `.../cache/963474fe5aac6685d12ef1450d4057728688c2bf.zip` where the cache corresponds to `~/.openmodelica/cache` with the libraries included in the index.json and the index being generated by something like:
https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/libraries-for-testing/update.py

It would be really easy to extend that script to also download the zip-files.

**Comment by casella** [comment]
Some notes after discussion at today's OSMC devmeeting.

As proposed by @sjoelund, instead of zipping the whole library directory, just reuse the cached .zip libraries mechanism.

Although most users will install OpenModelica and start using OMEdit, some of them may not, e.g. because they just use OMNotebook (e.g. my students of the Control System course) or because they actually start from the [Introduction of the User' Guide](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/introduction.html), that uses the interactive mode.

The goal is that MSL will be available out of the box after a new installation for all the tools in the OpenModelica suite, including when internet is not available, without any need to explain all the arcana of package management and MSL versioning before even getting started. However, it should also be possible for advanced users to delete the automatically installed libraries if they want to play around with them, without them being reinstalled automatically upon the next run.

**Comment by casella** [comment]
One simple way to achieve that is to modify the package manager and the class loader as follows:
- modify the package manager so that it first looks for cached .zip libraries in` C:\Program Files\OpenModelica1.20.0-dev-64bit\lib\omlibrary\cache` (or its Linux equivalent)
- whenever the class loader is called (either by the `loadModel()` API or indirectly via uses annotation), check if there is no `.openmodelica/index.json` file. If there is none (which means, fresh install):
  - fetch the pre-packaged `index.json` file from the installation directory (`e.g. C:\Program Files\OpenModelica1.20.0-dev-64bit\lib\omlibrary`) and copy it in `.openmodelica/`
  - install all the libraries listed there - the actual libraries will be fetched from the installation directory cache and installed into the current user's .openmodelica directory

That's it.

If we set up the defaults in OMEdit to load the latest MSL upon starting, as requested e.g. in #9369, OMEdit will call `loadModel()` on it and this will automatically trigger the default MSL installation. On the other hand, also the interactive environment and OMNotebook will actually find the MSL out of the box when they try to load it, for the same reason.

If you are an advanced user and you don't like these preinstalled packages, just delete them, _without deleting the `index.json` file_ (or using the Uninstall feature, when we make it available, see #9066), then use the package manager to get them as you wish. As long as the `index.json` file is not deleted, the autoinstall won't happen anymore.

@sjoelund, @adeas31, @adrpo, what do you think?

**Comment by sjoelund** [comment]
So I really think it's a lot simpler to let OMEdit ask what you want to do.

**Comment by casella** [comment]
> So I really think it's a lot simpler to let OMEdit ask what you want to do.

 But this doesn't work with interactive environment and OMNotebook (which affects me personally, BTW, I'm not using OMEdit at all in that course)

**Comment by sjoelund** [comment]
> > So I really think it's a lot simpler to let OMEdit ask what you want to do.
> 
> But this doesn't work with interactive environment and OMNotebook (which affects me personally, BTW, I'm not using OMEdit at all in that course)

But is the error-message you get so bad for OMNotebook?

```
false
"[/home/marsj/tmp/.openmodelica/libraries/index.json:0:0-0:0:readonly] Notification: Downloaded package index from URL https://libraries.openmodelica.org/index/v1/index.json.
Notification: You can install the requested package using one of the commands:
  installPackage(Modelica, \"4.0.0+maint.om\", exactMatch=true)
  installPackage(Modelica).
```

**Comment by casella** [comment]
> > fetch the pre-packaged index.json file from the installation directory (e.g. C:\Program Files\OpenModelica1.20.0-dev-64bit\lib\omlibrary) and copy it in .openmodelica/
> 
> The problem with this is you then have to updatePackageIndex() manually to get the list of all libraries.

This is true. But there may be ways to solve this issue.

> Before it would be enough to just installPackage() and it fetches the index.

Sorry, I don't get this. I'm not sure what you mean by "before", and how it can fetch the index if it is offline

**Comment by casella** [comment]
> Maybe by only modifying `loadModel(Modelica)` (of a version in the cached index)?

That's one option. However, it would be nice if we had a more general solution, that you could e.g. use for workshops in offline labs, where participants get all the required libraries to run the workshop out of the box.

> Or perhaps if we would make it so that it doesn't actually leave you with the index.json copied into ~/.openmodelica/libraries (and only installs the libraries into it)

LGTM 😃 

In fact, it may also try to download the index.json from the internet - if there is a connection, you get an up-to-date version of the available libraries when you first run your fresh installed OpenModelica, which doesn't hurt. But it would just be a lightweight download (like 250 kB), not the 40 MB of the MSL 3.2.3+4.0.0 zip files, which could be problematic in a classroom with internet access but not enough bandwidth to download that 50 times or something. 

The only issue then is how to detect it's a first install, if you can't use the presence of `index.json` for that. I guess it will have to be the empty` .openmodelica/libraries` directory. Which means, if you want to get rid of the auto-installed MSL, you need to install something else first and then delete/uninstall it.

Would that work for you?

**Comment by casella** [comment]
I assume tacit consent from @sjoelund 😄.

Here is my **revised proposal** according to all the received input:
- [ ] remove the `lib/omlibrary` directory from the default MODELICAPATH
- [ ] put an `index.json` file with only the MSL's and their dependencies in the `lib/omlibrary/libraries` installation directory
- [ ] put the corresponding cached zip files in the `lib/omlibrary/cache` installation directory
- [ ] modify the package manager so that it first looks for cached `.zip` libraries in the `lib/omlibrary/cache` installation directory
- [ ] modify the class loader so that when it is called, either by the `loadModel()` API or indirectly via uses annotation, it checks that the `.openmodelica/library` is empty, which means, fresh install, or first use by logged in user in case of multi-user installation. In this case, it should install all the libraries that show up in `lib/omlibrary/libraries/index.json`. The installation cached files will be used because of the priority set above
- [ ] set the OMEdit factory defaults to load the latest version of MSL (4.0.0 as of today) when starting OMEdit
- [ ] update the documentation to reflect this new setup

This proposal addresses all use cases of fresh install by a new user out of the box, without the need of any splash screen with lengthy and obscure instructions, which I think is good for usability:
1. The new user goes through the interactive session presented in the [User's Guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/introduction.html#interactive-session-with-examples). As soon as it gets to `loadModel(Modelica)`, the offline MSL installation is triggered, so it works out of the box. We should probably update the text, that still refers to Modelica 3.2.3, but that's another story.
2. The new user opens an OMNotebook file, where models contain the uses(Modelica) annotation. As soon as that is processed, the offline MSL installation is triggered, so it works out of the box
3. The new user opens OMEdit, which loads MSL 4.0.0 that is set to be loaded by default. As soon as loadModel() is called, the auto-install procedure is triggered, so it works out of the box

Additionally, the pre-installed versions of MSL are handled by the package manager as if they had been downloaded from the network, so there are no duplicate versions of the MSL or other weird side-effects.

Advanced users may want to uninstall those pre-installed versions of MSL and use others. They can do so _after_ they have installed them. As long as the `.openmodelica/library` directory is not empty, the default MSL won't be re-installed automatically.

Finally, implementing extended auto-install that includes more libraries beyond MSL is straightforward, e.g. for workshops with no internet access or limited available bandwidth. In principle, one can set up the required libraries on a fresh, internet-connected installation, and set aside the `.openmodelica/library/index.json` file and the whole `.openmodelica/cache` directory. These files should be placed in `lib/omlibrary/` after installation. Maybe we could provide some extended installers that just do that.

**Comment by casella** [comment]
@adeas31 could you take care of this yourself?

**Comment by adeas31** [comment]
I can fix the parts related to installer and OMEdit. Someone else has to take care of the class loader.

**Comment by casella** [comment]
@adrpo, @perost, @sjoelund could you help with that? Thanks!

**Comment by adeas31** [comment]
> - [ ] modify the package manager so that it first looks for cached `.zip` libraries in the `lib/omlibrary/cache` installation directory
> - [ ] modify the class loader so that when it is called, either by the `loadModel()` API or indirectly via uses annotation, it checks that the `.openmodelica/library` is empty, which means, fresh install, or first use by logged in user in case of multi-user installation. In this case, it should install all the libraries that show up in `lib/omlibrary/libraries/index.json`. The installation cached files will be used because of the priority set above

Maybe we don't need to change the class loader. Just fix package manager. Whenever we try to access `index.json` and it doesn't exist then use the one from `lib/omlibrary/libraries`, download/install the cached libraries and that's it. The only annoying thing with that is if user explicitly deletes the `index.json` then we end up treating this as if its a fresh install and copy the cache stuff again.

**Comment by casella** [comment]
@adeas31 I'm not sure. OMEdit maybe looks into index.json, but I understand script files started from the command line, the interactive environment, and OMNotebook have no idea about it. Do I miss something?

**Comment by casella** [comment]
At today's devmeeting, @perost volunteered to take care of that, with help from @sjoelund if needed.

**Comment by adeas31** [comment]
> @adeas31 I'm not sure. OMEdit maybe looks into index.json, but I understand script files started from the command line, the interactive environment, and OMNotebook have no idea about it. Do I miss something?

That doesn't matter. What I meant is that api calls like `loadModel` or `getAvailableLibraries` internally use package manager. So its best to just fix inside package manager instead of doing some special handling in other places like class loader etc.

**Comment by perost** [comment]
> > @adeas31 I'm not sure. OMEdit maybe looks into index.json, but I understand script files started from the command line, the interactive environment, and OMNotebook have no idea about it. Do I miss something?
> 
> That doesn't matter. What I meant is that api calls like `loadModel` or `getAvailableLibraries` internally use package manager. So its best to just fix inside package manager instead of doing some special handling in other places like class loader etc.

Some minor changes to the class loader might be necessary, because right now it skips the package manager if `requireExactVersion` is used for `loadModel` (since the package manager is otherwise only used to figure out which version to load).

But except for that case everything mostly points to `PackageManagement.getPackageIndex`, i.e. the common function that fetches the package index, so we can probably just have `loadModel` always call that even if it doesn't actually use it.

**Comment by casella** [comment]
@perost does this also include class loaded because of `uses()` annotations?

**Comment by perost** [comment]
I've now implemented this in a way that I hope will work, in #9464.

The logic now is that if `CevalScript.loadModel` (such as by calling the `loadModel` API) is called and the user's library directory is empty or doesn't exist, then we look for a `lib/omlibrary/libraries/index.json` in the installation folder. If it's found then we install all versions of all libraries in that index, using the normal installation procedure but skipping the download step and looking for a zip-file in `lib/omlibrary/cache` instead.

During this process the compiler will normally download a `index.json` and put it in the user's library directory. If this isn't done for some reason (such as no internet) then we instead fall back to copying the installed index to the user's library directory just so we at least have information about the installed libraries.

Some differences to what was mentioned earlier is that we do this when calling `CevalScript.loadModel` rather than `PackageManagement.getPackageIndex`, because it's otherwise easy to go into a loop of `access package index => install cached libraries => access package index => ...`. If needed we can add the check to other API calls too, but I think handling `loadModel` will probably cover most user needs (maybe OMEdit needs something more).

I also added some notification messages and improved some of the existing for installing libraries, to hopefully make it clear to the user what is happening. So please try it out and see if it works for you, I've only tested it on Linux and not with a proper installation.

**Comment by casella** [comment]
Thanks @perost! I understand you haven't touched the Windows installer, so if one wants to test this on Windows, one has to first create the index.json and cache files and then move them manually to the installation directory, to try out the mechanism. Do I get it right?

**Comment by perost** [comment]
> Thanks @perost! I understand you haven't touched the Windows installer, so if one wants to test this on Windows, one has to first create the index.json and cache files and then move them manually to the installation directory, to try out the mechanism. Do I get it right?

Yes

**Comment by casella** [comment]
OK, I'll try it with the nightly ASAP.

**Comment by adeas31** [comment]
> Some differences to what was mentioned earlier is that we do this when calling CevalScript.loadModel rather than PackageManagement.getPackageIndex, because it's otherwise easy to go into a loop of access package index => install cached libraries => access package index => .... If needed we can add the check to other API calls too, but I think handling loadModel will probably cover most user needs (maybe OMEdit needs something more).

Yes, for OMEdit we need to check this for `getAvailableLibraries()`.

**Comment by casella** [comment]
I can do that while testing

**Comment by casella** [comment]
Maybe we should automate that for the future 😅

**Comment by perost** [comment]
Unfortunately I deleted my build folder to get OMEdit to build and forgot it also contained the files I used to test with. But you just take the `index.json` and cut out the libraries you want, and the URL:s to download the zip files are in that file.

**Comment by perost** [comment]
> > Thanks @perost! I understand you haven't touched the Windows installer, so if one wants to test this on Windows, one has to first create the index.json and cache files and then move them manually to the installation directory, to try out the mechanism. Do I get it right?
> 
> If someone can create the cache libraries and index.json in `lib/omlibrary/libraries` then I will copy that to Windows installer.

Done in #9467 (I also added it to `getAvailableLibraryVersions` for good measure).

**Comment by perost** [comment]
> @perost, I'm not sure why this happens, it would be nice to avoid it, but it's no big deal, as it only happens when you run OMEdit for the first time after a fresh install. All subsequent starts work normally, with MSL 4.0.0 being loaded automatically up front.

It's because when installing a package we use the `package.json` in the user library folder to look up which versions are available and then try to match them to the requested version, and if no `package.json` exists we try to download one.

I tried to improve this in #9477 by changing the behaviour such that we first copy the `index.json` from the installation folder to the user library folder and use that one during the installation of the cached libraries, and then when that's done we try to download a new index so the user gets an up to date one.

**Comment by casella** [comment]
One thing I could not test is what happens if there is a network connection, but our server is unreachable, either because it is behind a firewall, or because it is down. I guess in that case one would have to wait for some timeout. Not sure how I can test that easily, any suggestions?

**Comment by perost** [comment]
> One thing I could not test is what happens if there is a network connection, but our server is unreachable, either because it is behind a firewall, or because it is down. I guess in that case one would have to wait for some timeout. Not sure how I can test that easily, any suggestions?

Shut down the server? :smile: 

Looking at the download code we use a timeout of 8 seconds. I have some memory that we used the default earlier which was too long and decreased it to 8 seconds.

**Comment by sjoelund** [comment]
You could play with your /etc/hosts to point libraries.openmodelica.org to some server that doesn't run a webserver or one that will return an error for this URL :)

**Comment by sjoelund** [comment]
> Yes, I guess we had 30 s, which is forever if you are expecting OMEdit to react to your input. Maybe 8 s is too short in some cases, but we can live with that.

I think the default (that we did not change) was 5 minutes

**Comment by casella** [comment]
OK, so as I understand, the remaining tasks to close this epic ticket are:
- [ ] remove the installation library directory from MODELICAPATH
- [ ] add the [omlibrary.zip](https://casella.faculty.polimi.it/transfer/omlibrary.zip) files in the Windows installer, so that they are copied to the lib/ directory
- [ ] remove the dialog with MSL installation from the Windows installer #9471 
- [ ] add the [omlibrary.zip](https://casella.faculty.polimi.it/transfer/omlibrary.zip) files to the Linux installation package
- [ ] update the User's Guide [Package Management](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html) section

Then we can branch off 1.20.0. 

@adeas31 can you please take care of the first three tasks?

@sjoelund can you please take care of the Linux installation, or explain how this can be done?

I'll take care of the last item.

**Comment by casella** [comment]
@adeas31/@perost can you please take care of the Linux installation as explained by @sjoelund? Thanks!

**Comment by perost** [comment]
> @adeas31 / @perost can you please take care of the Linux installation as explained by @sjoelund? Thanks!

I don't really have any clue how it works since I don't use the Linux packages, but if we have no one else that can do it...

**Comment by casella** [comment]
> I think the default (that we did not change) was 5 minutes

OMG, 5 minutes is totally insane in the 21st century. Do you mean it's still like that?

**Comment by casella** [comment]
> > @adeas31 / @perost can you please take care of the Linux installation as explained by @sjoelund? Thanks!
> 
> I don't really have any clue how it works since I don't use the Linux packages, but if we have no one else that can do it...

I understand @sjoelund is super-busy with teaching. You may give it a try. If you break everything @sjoelund will have to fix it 😝

**Comment by casella** [comment]
> Where shall we keep/store this omlibrary.zip? In the OM repo?

Good question. The best solution would be to keep the cut-out index.json file in the OM repo, and then build the file on the fly when building the release. In this way, updating it is very easy. Not sure how easy it is to implement that.

We could also put it in the OM repo, but it's 32 MB of binary stuff, probably not a good idea. We could have a dedicated repo for that, where we force-push any new version to avoid inflating the database, and that we could eventually get rid of, if we ever implement the proper solution.

**Comment by sjoelund** [comment]
Only the index.json, or have a script that generates the index.json. I want to change how the source tarballs are built for later anyway. When creating the source tarball, we should generate the bootstrapping sources, documentation and these files. Small on git, but larger tar.xz files for the nightly builds.

**Comment by adrpo** [comment]
When we are building OpenModelica release and we have omc we can just call a script to install what we want and then copy that in the installer. In the windows installer we can copy it to: `build\lib\omlibrarycache` and then on startup of omc or OMEdit we can fetch it from there.

**Comment by adeas31** [comment]
Or maybe just fetch the index.json and install MSL and then copy the stuff. So we just need a script for it.

**Comment by sjoelund** [comment]
You could modify this script to generate the index.json: https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/libraries-for-testing/update.py

**Comment by adeas31** [comment]
See #9491 and https://github.com/OpenModelica/OpenModelicaSetup/pull/22

**Comment by casella** [comment]
@adeas31 will the next nightly build incorporate everything already?

**Comment by adeas31** [comment]
No. The PRs are not yet merged. Still waiting for @sjoelund review but that might take forever. I will merge it anyway and then build the nightly for testing.

**Comment by adeas31** [comment]
The windows tasks are done. I just tested the latest nightly build.

**Comment by perost** [comment]
I've been trying to fix the Linux package but not having much luck so far. I set up Debian in a VM to try and build the packages and see how it works, but I think I'm going to need some guide on how the OM builds actually work if I'm going to get anywhere with that.

**Comment by adeas31** [comment]
Shall we close this one now? The Windows build are fixed and @sjoelund fixed the Linux ones as well.

**Comment by casella** [comment]
I guess we should try at least once to install from scratch and see that everything works fine. Has that been done already?

**Comment by adeas31** [comment]
I will test the Windows nightly tomorrow.

**Comment by sjoelund** [comment]
I have tested the LInux builds

**Comment by adeas31** [comment]
Just tested the latest nightly and the Windows version works as expected.

**Comment by casella** [comment]
Very good! @adrpo, all systems GO for the 1.20.dev-beta.1 release!
