### ISSUE TITLE
Internal error Instantiation failed with no error message.

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OpenModelica#8305]
Please have a look at the enclosed test package:
Either checking HallTimeSpan or compiling DemoEncoder (shich instantiates HallTimeSpan) produced the error message:
**Internal error Instantiation of Test.HallTimeSpan failed with no error message.**
I have neither an idea why nor how to avoid that.
OM1.18.0 on Windows 10 64bit
[Test.zip](https://github.com/OpenModelica/OpenModelica/files/7702153/Test.zip)

**Comment by sjoelund** [comment]
The old frontend says:
> Internal error: no tokens left to replace %s with.
> Given message was: Wrong type on edge({uC[1], uC[2], uC[3]}), expected %s.

The following also fails with no message:
```mo
model M
  Boolean b[3];
  Boolean x = edge(b);
end M;
```

**Comment by AHaumer** [comment]
I have to admit: I don't understand. Anything I did wrong? Waht should I change? Or something to bugfix OM?

**Comment by sjoelund** [comment]
> The operators noEvent, pre, edge, and change, are vectorizable according to section 12.4.6.

So it should work. But the OM code probably lacks that case.

**Comment by perost** [comment]
> > The operators noEvent, pre, edge, and change, are vectorizable according to section 12.4.6.
> 
> So it should work. But the OM code probably lacks that case.

The issue was actually that `edge` was vectorized, but then we tried to unbox the arguments which didn't expect a vectorized call. It's fixed in #8308 which also fixes the test package.

**Comment by casella** [comment]
@AHaumer please use the latest nightly build, it should work out of the box.

**Comment by casella** [comment]
Sorry, I meant **tomorrow's** nightly build.
