### ISSUE TITLE
The debugger always crashes under Windows

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8316]
Steps to reproduce:
- Start OMEdit
- Open Modelica.Blocks.Examples.PID_Controller
- Run "Simulate with transformational debugger"

OMEdit freezes and then crashes when trying to open the debugger windows. The relevant files are attached: 
[OMEdit.zip](https://github.com/OpenModelica/OpenModelica/files/7706036/OMEdit.zip)

 - OpenModelica Version: v1.19.0-dev-460-gaeb8a6d1a3 (64-bit)
 - OS: Windows 10, 64 bit

**Comment by perost** [comment]
Do you have profiling enabled? Because it looks like an exception occurs while it's trying to read the profiling data. I'm not sure if there's some global flag for it, the only thing I can find is Simulation Setup->Simulation Flags->Profiling.

You can check if you can find the `PID_Controller_prof.json` file, I'm not sure where it gets generated on Windows but it should be in the same folder as the simulation executable and other files. If you can find it please upload it too, it might contain some clues.

**Comment by casella** [comment]
> Do you have profiling enabled? Because it looks like an exception occurs while it's trying to read the profiling data.

Thanks @perost, you nailed it!

 AFAIK there is no global flag for it, Simulation Setup->Simulation Flags->Profiling was set to none, _but I had an _old prof.json file in the simulation result directory_. OMEdit apparently crashed trying to load it into the profiler. Please find it attached.

[PID_Controller_prof.zip](https://github.com/OpenModelica/OpenModelica/files/7707754/PID_Controller_prof.zip)

If I delete that file from the simulation output directory, I can then safely open the debugger, and if I enable profiling=all, a new _prof.json file is generated and loaded correctly

[PID_Controller_prof_new.zip](https://github.com/OpenModelica/OpenModelica/files/7707776/PID_Controller_prof_new.zip)

I compared the two files, for some reason the old one has two more blocks than the old one, I guess that explains the failure.



I'm not aware of global flags for profilin
> 
> You can check if you can find the `PID_Controller_prof.json` file, I'm not sure where it gets generated on Windows but it should be in the same folder as the simulation executable and other files. If you can find it please upload it too, it might contain some clues.

**Comment by casella** [comment]
BTW, in [#6443](https://trac.openmodelica.org/OpenModelica/ticket/6443) I already noticed that old `_prof.json` files could linger around and provide bogus output, and recommended to remove them. In fact, they can actually cause OMEdit to crash, if the old file is old enough to cause some changes to the generated code structure.

I would definitely recommend that the runtime (all runtimes, C and C++) deletes any existing `_prof.json` file before starting the simulation. There is simply no reason not to do it, since the old file becomes obsolete the very moment a new simulation starts, and several good reasons to actually do it, including avoiding the issue reported here.

@mahge, could you take care of that? 

Thanks!

**Comment by adrpo** [comment]
Whatever input we gave it, it should not crash, it should just say that it cannot be parsed and that's that.

**Comment by perost** [comment]
> Whatever input we gave it, it should not crash, it should just say that it cannot be parsed and that's that.

I've tried to make OMEdit crash, but I can't find a way to do it either with casella's old file or trying to maliciously change it. Either it won't be valid JSON, in which case it just gives an error message, or the values in it are wrong in which case it will just default-initialize them.

There's nothing in the code that should throw an exception as far as I can see, so I'm really not sure what's going wrong for casella. Some Windows issue perhaps? I don't see why it would be any different, but I guess @adeas31 can check later. At least the immediate issue is fixed.

**Comment by casella** [comment]
> Whatever input we gave it, it should not crash, it should just say that it cannot be parsed and that's that.

I agree with that. But there are other reasons to automatically remove old _prof files, mainly to avoid displaying old bogus results if profiling is turned off. So I would do that automatically, and then it is much unlikely that this issue will pop up. We have to prioritize :)

**Comment by casella** [comment]
> There's nothing in the code that should throw an exception as far as I can see, so I'm really not sure what's going wrong for casella. Some Windows issue perhaps?

Probably. On my side it could be reproduced with 100% certainty.

> At least the immediate issue is fixed.

I'm not sure how it is, unless old _prof files are automatically deleted when running new simulations. I mean, removing the file manually is not a viable option to avoid a crash.

**Comment by casella** [comment]
The only 100% safe way to handle this is to delete the file at the beginning of the runtime simulation. This guarantees that even if a) the simulation fails, or b) the profiling info generation is switched off, there is no way old profiling data could be misunderstood as being irrelevant.

If we want omc to do that, we should add this instruction at the beginning of the runtime(s). IMO doing that when you compile the model would work in most cases, but not all of them. OMEdit does the compilation and the runtime execution separately, so it could do it at the beginning of the runtime execution. 

@adrpo, @adeas31, see what is the quickest way to get this done, thanks!
