### ISSUE TITLE
No option to select FMI Co-simulation solver?

### ISSUE THREAD

**Issue by AJamesPhillips** [OpenModelica/OpenModelica#8327]
### Description
Under `Preferences` -> `FMI`, I can not see an option for selecting the Co-simulation solver (as "Explicit Euler") as shown shown in this screenshot from [this page, section 2.3. Setup FMU Export options](https://bodylight.physiome.cz/Bodylight-docs/tutorial/#../tutorial/basic2exportom.md)

![image](https://user-images.githubusercontent.com/526509/146089686-9bb8c4dd-48b0-4bf4-b39c-da07758268c3.png)

### Steps to reproduce
1.18.0~dev-109-ged8ef0a

### Expected behavior
Have a dropdown option to select the Co-simulation solver.

### Screenshots
![OMEdit_-_Options](https://user-images.githubusercontent.com/526509/146090241-6832fe90-2e5a-4497-b945-3cc0993e3e5d.png)

### Version and OS
 - 1.18.0~dev-109-ged8ef0a
 - OS: Mac 11.6.1, 64 bit

**Comment by Arinomo** [comment]
@AJamesPhillips you could try the nightly-build. If I'm not mistaken it was added in 1.19

**Comment by AJamesPhillips** [comment]
@Arinomo my apologies, I took the [latest nightly from here](https://build.openmodelica.org/omc/builds/mac/binaries/) but I see we're on 1.19 now.  Could you point me to the community of Mac users / installers please?

I'm happy to try to help to get the latest actual nightly build available for others to use though I assume there's a reason Mac doesn't look like it's supported at the moment?

**Comment by Arinomo** [comment]
@AJamesPhillips  sorry i can't help you with that. I my self ist just a user. @sjoelund might be able to help you with further information :D

**Comment by sjoelund** [comment]
> If you know where the community of Mac users / installers are then I'd be grateful if you pointed me to them, thank you, no worries if you don't know. I'm happy to try to help to get the latest actual nightly build available for others to use though I assume there's a reason Mac is not supported at the moment.

MacOS is supported through VirtualBox or docker.

**Comment by AJamesPhillips** [comment]
Thank you.  I got stuck on that approach so went back to it and [posted to the forum](https://openmodelica.org/forum/default-topic/3387-running-on-mac-in-docker).  The latest docker build is 1.18 so I can't check this in 1.19 yet.  I'm happy to close as it sounds like it's a feature that's present in 1.19 and not 1.18.
