### ISSUE TITLE
Test the whole library testsuite with the cpp runtime

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8330]
Currently we only test a few selected libraries with the cpp runtime: MSL, ModelicaTest, Modelica_Synchronous, PowerSystems.

It would be nice to run the entire library testsuite with that runtime, to better assess its performance.

**Comment by casella** [comment]
@sjoelund wrote:
> Nope, we only have a few libraries tested with C++. You need different flags for everything, so you cannot easily just test all the libraries with C++. 

Can you be more specific? I checked, e.g., the [Buildings report](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html), I see many compiler flags but no simulation flags.

> If the interface was the same as the C runtime it would be a lot easier, but student flags,

what are student flags?

> result files

I understand the file format is the same, i.e. Dymola's, isn't it?

> compiler flags, etc.

You mean C compiler flags? We should stick to the defaults.

**Comment by sjoelund** [comment]
> Can you be more specific? I checked, e.g., the [Buildings report](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html), I see many compiler flags but no simulation flags.

Look at the libraries tested with the C++ runtime and you'll see more flags.

> what are student flags?

Simulation flags. I guess phone autocorrected it.

> I understand the file format is the same, i.e. Dymola's, isn't it?

It didn't use to be at least.

> You mean C compiler flags? We should stick to the defaults.

No, it's had some different compiler flags needed for some libraries in the past. And some of the tested libraries use special flags to work.

When the library testing scripts were implemented, I asked if we should test it the way described in this ticket. And I was told no, because it was only intended for those selected libraries. So it's a bit more work to change things around.

**Comment by casella** [comment]
> Look at the libraries tested with the C++ runtime and you'll see more flags.

[PowerSystems_latest](https://libraries.openmodelica.org/branches/master/PowerSystems_latest/PowerSystems_latest.html)
```
Tested Library: 1.0.1

{
 "path": "PowerSystems",
 "sha": "07b5d32cc291e2397becd2f97351c0bc1a375d54",
 "support": "noSupport",
 "uses": {
  "Modelica": "3.2.3"
 },
 "version": "1.0.1-master",
 "zipfile": "https://github.com/modelica-3rdparty/PowerSystems/archive/07b5d32cc291e2397becd2f97351c0bc1a375d54.zip"
}

BuildModel time limit: 660s

Simulation time limit: 480s

Default tolerance: 1e-06

Optimization level: -Os -march=native
Flags:

setCommandLineOptions("-d=nogen");
setCommandLineOptions("-d=initialization");
setCommandLineOptions("-d=backenddaeinfo");
setCommandLineOptions("-d=discreteinfo");
setCommandLineOptions("-d=stateselection");
setCommandLineOptions("-d=execstat");
setMatchingAlgorithm("PFPlusExt");
setIndexReductionMethod("dynamicStateSelection");

Config:

{
 "library": "PowerSystems",
 "libraryVersion": "master",
 "libraryVersionNameForTests": "latest",
 "optlevel": "-Os -march=native"
}
```

[PowerSystems_cpp](https://libraries.openmodelica.org/branches/master/PowerSystems_cpp/PowerSystems_cpp.html):
```
Tested Library: 1.0.1

{
 "path": "PowerSystems",
 "sha": "07b5d32cc291e2397becd2f97351c0bc1a375d54",
 "support": "noSupport",
 "uses": {
  "Modelica": "3.2.3"
 },
 "version": "1.0.1-master",
 "zipfile": "https://github.com/modelica-3rdparty/PowerSystems/archive/07b5d32cc291e2397becd2f97351c0bc1a375d54.zip"
}

BuildModel time limit: 660s

Simulation time limit: 480s

Default tolerance: 1e-06

Optimization level: Tool default
Flags:

setCommandLineOptions("-d=nogen");
setCommandLineOptions("-d=initialization");
setCommandLineOptions("-d=backenddaeinfo");
setCommandLineOptions("-d=discreteinfo");
setCommandLineOptions("-d=stateselection");
setCommandLineOptions("-d=execstat");
setMatchingAlgorithm("PFPlusExt");
setIndexReductionMethod("dynamicStateSelection");
setCommandLineOptions("--simCodeTarget=Cpp")

Config:

{
 "abortSlowSimulation": "",
 "alarmFlag": "--alarm",
 "configExtraName": "cpp",
 "library": "PowerSystems",
 "simCodeTarget": "Cpp"
}
```
Obviously the latter adds `setCommandLineOptions("--simCodeTarget=Cpp")`, but that will be in common with all the models run in the cpp job.

There are some differences in the Config part (e.g. using `--alarm`),  but they seem completely marginal to me.

I don't really see a problem at running the entire library testsuite with the additional command `setCommandLineOptions("--simCodeTarget=Cpp")`, pretty much as we run the daeMode job with `setCommandLineOptions("--daeMode")`. 

In fact, the whole point of the job is to make sure that stuff runs with the cpp runtime without the need of extra magic.

Do I miss something?

**Comment by casella** [comment]
> > I understand the file format is the same, i.e. Dymola's, isn't it?
> 
> It didn't use to be at least.

I simulated a MSL model with both runtimes and compared the results. The cpp one is double the size, I guess because it uses double precision by default, but other than that they look pretty much the same, ad I can load and display both of them in OMEdit. If it walks like a duck, swims like a duck...

**Comment by casella** [comment]
> When the library testing scripts were implemented, I asked if we should test it the way described in this ticket. And I was told no, because it was only intended for those selected libraries.

That was a long time ago, I guess the situation has changed quite a bit in the meantime 😃 

In any case, we need extensive testing results to assess the current status with runtime development and take informed strategic decisions about future developments. We are testing the hell out of OMC: all past releases of the compiler, daeMode, oldInst, fmi, I see no reason why we shouldn't also test cpp, since it is used by at least two key OSMC members.

_My_ requirement here is to run the whole library testsuite with no other special flags than `setCommandLineOptions("--simCodeTarget=Cpp")`, to see what happens. @rfranke, are other flags needed to ensure we are not getting sub-optimal performance?

**Comment by sjoelund** [comment]
It seems there are some changes to the C++ runtime to ignore unknown flags now. I started a run using it and disabled the C++ config so we test C++ in only report. Maybe we would need to also test the previous release to be able to compare it to some baseline. But let's first see how it behaves. There are some fixes to the timeouts, so hopefully it won't get stuck anywhere...

**Comment by sjoelund** [comment]
https://libraries.openmodelica.org/branches/overview-c++.html 9422 simulating tests.C-runtime 10922 simulating tests.

**Comment by casella** [comment]
@sjoelund, before closing this issue, I checked the overview-c++ report today (Jan 9 2022) and I got this:
```
v1.18-cpp | OMCompiler v1.18.0-v1.18.0.38+ga767f054d8 | 2022-01-08 05:07:02 | 2 days,  8:09:59 | 9065 | 12123
cpp       | OMCompiler v1.19.0-dev.504+g8291efd717    | 2022-01-05 19:54:32 | 2 days, 18:28:07 | 9414 | 12123

```
I understand this report compares the testing of the latest official release with master. I'm not sure how often each of them is run, but it seems that the official release is ran more often, since the latest report is one day old, while the one on master is four days old.

I think we should try to run the test on master as often as possible, to catch possible regressions on omc. @sjoelund, can you report what is the current setting and if we can improve it in this direction? Thanks!

**Comment by sjoelund** [comment]
cpp (master) runs daily if there are library or omc changes (it seems it skipped Sundays before - I re-added that now). During the Christmas break, there has been few changesets.

**Comment by casella** [comment]
OK, then we can consider this closed. Thanks!
