### ISSUE TITLE
[NF] ClaRa modified element not found in class

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8340]
### Description

When building `ClaRa.Basics.ControlVolumes.FluidVolumes.Check.Validation_VolumeVLE_L2_HeatTransfer_1ph_shell` from ClaRa_dev the frontend issues the following error:

```bash
true
"Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.
Notification: Automatically loaded package TILMedia 1.7.0 ClaRa due to uses annotation.
"
{"",""}
"[/path/to/ClaRa/Basics/ControlVolumes/FluidVolumes/Check/Validation_VolumeVLE_L2_HeatTransfer_1ph_shell.mo:38:9-38:28:writable] Error: Modified element parallelTubes not found in class HollowBlockWithTubes.
"
```

See https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Basics.ControlVolumes.FluidVolumes.Check.Validation_VolumeVLE_L2_HeatTransfer_1ph_shell.err for a full report.

### Steps to Reproduce

Get ClaRa_dev and run
```
loadFile("/hpath/to/ClaRa/package.mo"); getErrorString();

buildModel(ClaRa.Basics.ControlVolumes.FluidVolumes.Check.Validation_VolumeVLE_L2_HeatTransfer_1ph_shell); getErrorString();
```

### Version and OS

 - OpenModelica Version: omc @ 6f1e7d1c3280e561b0e18ee1c899d425692fbf89
 - OS: Ubuntu Focal 20.04
 - Versions of used Modelica libraries:
   - MSL 4.0.0
   - Complex 4.0.0
   - ModelicaServices 4.0.0
   - development version of  TILMedia 1.7.0 ClaRa @ 134d94af5460e95304dddb12bc866f3691d1cb60
   - development version of ClaRa @ 134d94af5460e95304dddb12bc866f3691d1cb60

**Comment by perost** [comment]
This was an issue in the library which was fixed last week. The model still fails due to what seems to be the same issue as in #4908.
