### ISSUE TITLE
OpenPBS Library not working with NewFrontEnd

### ISSUE THREAD

**Issue by arun3688** [OpenModelica/OpenModelica#8344]
### Description

The OpenPbs Library package does not simulate with the NewFrontEnd. due to `Non-array modification for array component possibly due to missing each`

### Steps to Reproduce

Load the attached OpenPBS package in the mos file and simulate the following Manoeuvres

```
// load Modelica library
loadModel(Modelica,{"3.2.3"});
getErrorString();

// load the package.mo
loadFile("./OpenPBS/package.mo");
getErrorString();

simulate(OpenPBS.Manoeuvres.LowSpeedCurve);
getErrorString();

simulate(OpenPBS.Manoeuvres.SingleLaneChangeRollDynamicsNonLinTyre);
getErrorString();

```
### Error 

```
"[C:/performancebasedstandard/OpenPBSScripts/flaskapp/static/OpenPBSLibrary/OpenPBS/Manoeuvres/LowSpeedCurve.mo:14:53-14:59:writable] Notification: From here:
[C:/performancebasedstandard/OpenPBSScripts/flaskapp/static/OpenPBSLibrary/OpenPBS/Components/PathPosition.mo:6:3-7:38:writable] Error: Non-array modification ÔÇÿ0ÔÇÿ for array component ÔÇÿn0ÔÇÿ, possibly due to missing ÔÇÿeachÔÇÿ."

```

[OpenPBSLibrary.zip](https://github.com/OpenModelica/OpenModelica/files/7735176/OpenPBSLibrary.zip)

**Comment by sjoelund** [comment]
Note that you attached a zip-file with the entire git history of the project.

**Comment by perost** [comment]
The error message is correct, this is something that should be fixed in the library instead.
