### ISSUE TITLE
Windows installer not trusted because of unknown publisher

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8348]
### Description

The Windows installer of OpenModelica is not signed.
Whenever users want to install OpenModelica they need to make an acception. That's not looking very professional.

### Steps to Reproduce

Start the Windows installer, e.g. from https://build.openmodelica.org/omc/builds/windows/releases/1.18/0/64bit/.
The Microsoft Defender SmartScreen will stop the execution of the installer. Users need to click on `More Information` to continue anyway.
The issue is an unknown publisher.

### Expected Behavior

Don't get a warning about untrusted software.

### Screenshots

![image](https://user-images.githubusercontent.com/38031952/146737154-3d78f853-ab53-4590-9b72-27a7b641ca1f.png)

![image](https://user-images.githubusercontent.com/38031952/146737184-ba841d91-40e4-4680-a41a-6301d739a7ba.png)

### Version and OS

 - OpenModelica Version: all
 - OS: Windows 10, Windows 11

**Comment by AnHeuermann** [comment]
The Windows SignTool could be used to sign the binary: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool.

Buying a certificate issued by a CA can be quiet expensive, sometimes less expensive for open-source projects.

**Comment by casella** [comment]
Sorry, I was interrupted and left this unfinished.

**Comment by casella** [comment]
Original ticket: https://trac.openmodelica.org/OpenModelica/ticket/4829

**Comment by casella** [comment]
> The Windows SignTool could be used to sign the binary: https://docs.microsoft.com/en-us/windows/win32/appxpkg/how-to-sign-a-package-using-signtool.
> 
> Buying a certificate issued by a CA can be quiet expensive, sometimes less expensive for open-source projects.

@sjoelund, @adrpo, perhaps we could use one issued by LiU?

**Comment by sjoelund** [comment]
> @sjoelund, @adrpo, perhaps we could use one issued by LiU?

No. It has to be the same issuer as the certificate. But it's possible to create a self-signed certificate. It shouldn't be any problem to sign the executables.

**Comment by casella** [comment]
> No. It has to be the same issuer as the certificate. But it's possible to create a self-signed certificate. It shouldn't be any problem to sign the executables.

I'm not sure if Windows Defender recognizes self-signed certificates. I mean, anybody could claim to be the OSMC and self-sign a certificate stating so. Of course we can try and see if it works, but I'm doubtful. From what I read on the net, it's a lose-lose situation for OS developers, but of course Microsoft couldn't care less.

**Comment by sjoelund** [comment]
Well. Without a self-signed certificate, we can't even press the button to ignore the warning and install anyway (on the machines we develop OM on)... But yes, a proper certificate is good.
