### ISSUE TITLE
Make sure cpp runtime support is added by default when installing OMC in Linux

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8352]
This should be done both on `master` and `maintenance/v.18` branches

**Comment by adrpo** [comment]
Already done:
https://github.com/OpenModelica/OpenModelicaBuildScripts/commit/e94dae9303c9f79703c295e1a7600561ab79ef42

https://github.com/OpenModelica/OpenModelicaBuildScripts/commit/e94dae9303c9f79703c295e1a7600561ab79ef42
