### ISSUE TITLE
Why val() can not detect the results directly from workspace after executing system() in omshell?

### ISSUE THREAD

**Issue by Amuri44** [OpenModelica/OpenModelica#8361]
I have implemented the example below, however, when I added the command val(variable, time) after the system() command it didt detect any of the output variables. How can I read the output variables by val() directly after systems() i.e. without saving the results into a file (such as .mat) and then read it?
https://openmodelica.org/doc/OpenModelicaUsersGuide/1.18/scripting_api.html#simulation-parameter-sweep

**Comment by adrpo** [comment]
`system` is used to run any command or external program, `omshell` or `omc` has no way of knowing you are running a model and produce a result. You can however, after you run the model and get a result, use `val(varName, time, "resultFile.mat|csv")` to read it from the produced result file.

`simulate` will load the result and can be used with `val` with no filename, however, is slow because it builds the model. We should just add a flag to `simulate` to not build the model if it exists.

**Comment by adrpo** [comment]
You can also use `readSimulationResult` https://build.openmodelica.org/Documentation/OpenModelica.Scripting.readSimulationResult.html
to read the result.

**Comment by sjoelund** [comment]
> We should just add a flag to `simulate` to not build the model if it exists.

Or probably better: a `resimulate` API or something that takes the executable as an argument.

**Comment by Amuri44** [comment]
> `simulate` will load the result and can be used with `val` with no filename, however, is slow because it builds the model. We should just add a flag to `simulate` to not build the model if it exists.

What is the flag, can you write the simulate with the flag? and if I use it, will it be fast as using system?

**Comment by Amuri44** [comment]
> Or probably better: a `resimulate` API or something that takes the executable as an argument

Can you give me a link for it or an example?

**Comment by sjoelund** [comment]
There is none (yet)

**Comment by Amuri44** [comment]
> There is none (yet)

Ok, 
Can I use val to read two variables at the same time, such as val(var1,time1,var2,time2"twovariableaddition_res.csv")? if readSimulationResult can do that, can you give me an example please?

**Comment by sjoelund** [comment]
https://www.openmodelica.org/doc/OpenModelicaUsersGuide/1.18/scripting_api.html#readsimulationresult says it takes filename + variable names. So:

```modelica
readSimulationResult("M_res.mat", {time,var1,var2});
```

`val` doesn't vectorize so you need to make one call per variable.

**Comment by Amuri44** [comment]
> https://www.openmodelica.org/doc/OpenModelicaUsersGuide/1.18/scripting_api.html#readsimulationresult says it takes filename + variable names. So:
> 
> ```modelica
> readSimulationResult("M_res.mat", {time,var1,var2});
> ```
> 
> `val` doesn't vectorize so you need to make one call per variable.

Thank you very much!
I am just carious to understand how do you know that the variables need to be put between curly brackets as it was been mentioned in its documentation?

**Comment by sjoelund** [comment]
It's because TypeNames is a special type for OpenModelica scripting. Either way, it's always 1 arguement to the function for each input in the scripting API.
