### ISSUE TITLE
Index reduction failures in multibody models with kinematic loops

### ISSUE THREAD

**Issue by anotheruserofgithub** [OpenModelica/OpenModelica#8365]
Hello,

I am facing problems with multibody models containing kinematic loops.
Below I provide a rich enough example for you to replicate and better understand my concerns.

I successfully managed to simulate a double Cardan joint, which is a kind of constant velocity (CV) joint.
Note that the prismatic joint in the middle is there to model the elasticity required in the parts for this overconstrained mechanism to move.
However, as soon as I try to add another branch between the input and output shafts, therefore creating a loop, the model cannot be simulated even if the two branches are equivalent as in the following example.

Here is the toy model:

```modelica
model CVjointDoubleCardanDuplicated
  import Modelica.Constants.pi;
  final parameter Real o = 2 * pi;
  final parameter Real speed = 20;
  final parameter Real force [3] = {0, 0, 0};
  final parameter Real torque[3] = {9, 0, 0};
  inner Modelica.Mechanics.MultiBody.World world(n = {-1, -1, -1}, g = 0 * Modelica.Constants.g_n);
  Modelica.Mechanics.Rotational.Sources.ConstantSpeed cs(w_fixed = speed) if true;
  Modelica.Blocks.Sources.Constant cf[3](k = force ) if false;
  Modelica.Blocks.Sources.Constant ct[3](k = torque) if false;
  Modelica.Mechanics.MultiBody.Forces.WorldForceAndTorque ft(resolveInFrame = Modelica.Mechanics.MultiBody.Types.ResolveInFrameB.world) if false;
  Modelica.Mechanics.MultiBody.Parts.Fixed f1(r = {0, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.FixedRotation f2(r = {1 + 1 / sqrt(2), 1 + 1 / sqrt(2), 0}, n = {0, 0, 1}, angle = 90);
  Modelica.Mechanics.MultiBody.Joints.Revolute r1(n = {1, 0, 0}, phi(start = o + 0, fixed = true ), useAxisFlange = true, stateSelect = StateSelect.always);
  Modelica.Mechanics.MultiBody.Joints.Revolute r2(n = {1, 0, 0}, phi(start = o + 0, fixed = false), useAxisFlange = true, stateSelect = StateSelect.prefer);
  Modelica.Mechanics.MultiBody.Parts.BodyBox b1(r = {1, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.BodyBox b2(r = {1, 0, 0});
  Modelica.Mechanics.MultiBody.Joints.Universal u1(n_a = {0, 0, 1}, n_b = {0, 1, 0}, phi_a(start = o + pi / 4), phi_b(start = o + 0));
  Modelica.Mechanics.MultiBody.Joints.Universal u2(n_b = {0, 0, 1}, n_a = {0, 1, 0}, phi_b(start = o + pi / 4), phi_a(start = o + 0));
  Modelica.Mechanics.MultiBody.Parts.BodyBox i1(r = {1 / 2, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.BodyBox i2(r = {1 / 2, 0, 0});
  Modelica.Mechanics.MultiBody.Joints.Prismatic p0(n = {1, 0, 0}, s(start = 0)) if true;
  Modelica.Mechanics.MultiBody.Parts.BodyBox db11(r = {0, 0, +1 / 4});
  Modelica.Mechanics.MultiBody.Parts.BodyBox db22(r = {0, 0, -1 / 4});
  Modelica.Mechanics.MultiBody.Parts.BodyBox db12(r = {0, +1 / 4, -1 / 4});
  Modelica.Mechanics.MultiBody.Parts.BodyBox db21(r = {0, -1 / 4, +1 / 4});
  Modelica.Mechanics.MultiBody.Joints.Revolute dr11(n = {0, 0, 1}, phi(start = o + pi / 4));
  Modelica.Mechanics.MultiBody.Joints.Revolute dr22(n = {0, 0, 1}, phi(start = o + pi / 4));
  Modelica.Mechanics.MultiBody.Joints.Revolute dr12(n = {0, 1, 0}, phi(start = o +      0));
  Modelica.Mechanics.MultiBody.Joints.Revolute dr21(n = {0, 1, 0}, phi(start = o +      0));
  Modelica.Mechanics.MultiBody.Parts.BodyBox di1(r = {1 / 2, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.BodyBox di2(r = {1 / 2, 0, 0});
  Modelica.Mechanics.MultiBody.Joints.Prismatic dp0(n = {1, 0, 0}, s(start = 0)) if true;
  Modelica.Mechanics.MultiBody.Parts.BodyBox dh0(r = {0, -1 / 4, 0});
equation
  connect(cf.y, ft.force );
  connect(ct.y, ft.torque);
  connect(ft.frame_b, r1.frame_b);
  connect(cs.flange, r1.axis);
  connect(f1.frame_b, f2.frame_a);
  connect(f1.frame_b, r1.frame_a);
  connect(f2.frame_b, r2.frame_a);
  connect(r1.frame_b, b1.frame_a);
  connect(r2.frame_b, b2.frame_b);
  connect(b1.frame_b, u1.frame_a);
  connect(b2.frame_a, u2.frame_b);
  connect(u1.frame_b, i1.frame_a);
  connect(u2.frame_a, i2.frame_b);
  connect(i1.frame_b, p0.frame_a);
  connect(i2.frame_a, p0.frame_b);
  connect(b1.frame_b, db11.frame_a);
  connect(db11.frame_b, dr11.frame_a);
  connect(dr11.frame_b, db12.frame_a);
  connect(db12.frame_b, dr12.frame_a);
  connect(dr12.frame_b, di1.frame_a);
  connect(di1.frame_b, dp0.frame_a);
  connect(dp0.frame_b, di2.frame_a);
  connect(di2.frame_b, dr21.frame_a);
  connect(dr21.frame_b, db21.frame_a);
  connect(db21.frame_b, dr22.frame_a);
  connect(dr22.frame_b, db22.frame_a);
  connect(db22.frame_b, b2.frame_a);
  connect(dh0.frame_a, di1.frame_b);
  //connect(dh0.frame_b,  i1.frame_b);
end CVjointDoubleCardanDuplicated;
```

Basically this model fails during translation with the well-known error “Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states.”
From there, three tests you might want to experiment:
- If you open the loop in the 2nd branch by toggling to `false` the condition at line **33**, it works perfectly well as a double universal joint.
- If you open the loop in the 1st branch by toggling to `false` the condition at line **22**, it works perfectly well as a double universal joint.
- If you close the loop by toggling to `true` both conditions, but remove `f2` and `r2` by adding a `false` condition at lines **13** and **15**, and replace one of the `Joints.Revolute` in the second branch by a `Joints.Constraints.Revolute`, the model is translated (correctly or not, I cannot tell) but does not pass the initialization during simulation.

Also note that I had to force the state selection and start value of `r1` at line **14**.

This toy model should convince you that having a loop like this one should work, since the first and second branches are kinematically equivalent.
In the second branch (elements of which are prefixed with a `d` for “duplicate”) the position of each revolute joint is simply shifted along its axis.
Both branches would thus produce the same motion, therefore the last `connect` equation could be uncommented.

I do not have a license to test this model in Dymola, so if anyone can try it in Dymola and share the results, I would be grateful.
I would greatly appreciate your help on solving this issue, or your explanations on the reason why this mechanism is not supposed to work.

I use OMEdit with MSL 4.0.0. I tried both old and new frontends.
Version of OpenModelica: 1.19.0~dev-493-gff44d50 (nightly build).
OS: Ubuntu 20.04 64-bit.

**Comment by anotheruserofgithub** [comment]
By the way this issue seems related to #8116.

**Comment by AnHeuermann** [comment]
It seems to be a problem with your model and not OpenModelica.
At least Dymola is reporting that the model is structurally singular as well.

#8116 is about state selection. Here it is index reduction that reports that the system is structurally singular.

I'm not much of a modeler, so I can't hep with this. To get help with your model you could try [StackOverflow](https://stackoverflow.com/questions/tagged/openmodelica) or the [OpenModelica forum](https://www.openmodelica.org/forum).

**Comment by casella** [comment]
I agree with @AnHeuermann, this issue tracker is only for issues that need fixes or improvements to the compiler.

Dymola reports:

> The model includes the following hints:
> All Forces cannot be uniquely calculated.
> The reason could be that the mechanism contains
> a planar loop or that joints constrain the
> same motion. For planar loops, use for one
> revolute joint per loop the joint
> Joints.RevolutePlanarLoopConstraint instead of
> Joints.Revolute.

I hope you can find it useful.

**Comment by anotheruserofgithub** [comment]
Thank you for your answers and the Dymola report! It helped me solve (part of) the problem.
Please accept my apologies, as I really thought this was a more general issue with OpenModelica.

**Comment by casella** [comment]
No problem at all 😃
