### ISSUE TITLE
OMEdit crashes on re-simulate

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#8369]
### Description

OMEdit crash on re-simulate from Plotting view

### Steps to Reproduce

Try to re-simulate any model from the Plotting view. OMEdit will crash.

### Expected Behavior

Don't crash! :)

**Comment by casella** [comment]
Thanks @adrpo! @matteodepascali found this out one week ago, so I had it on the radar screen before Christmas, but he only managed to open #8371 two days ago. All's well that ends well.
