### ISSUE TITLE
Conditional array component declaration with negative index not removed from DAE

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8374]
### Description

According to the [Modelica language specification 4.4.5 Conditional Component Declaration](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#conditional-component-declaration) it should be possible to have an array of components with an condition-attribute (if-expression). The component should only be added to the DAE if the condition is true.

But I get a negative array index error when compiling such a model in a case where the component declaration should be removed from the DAE.

### Steps to Reproduce

Simulate `negativeArrayIndex`:

```Modelica
model Comp
  Real u=time;
end Comp;

model negativeArrayIndex
  parameter Integer param1=2;
  parameter Integer param2=3;
  Comp conditionalArray[param1-param2] if param2<param1;
end negativeArrayIndex;
```

```
[1] 13:23:58 Translation Error
[negativeArrayIndex: 4:3-4:49]: Negative dimension index (-1) for component someArray.
```

### Expected Behavior

Remove `conditionalArray` from the DAE and continue.

### Version and OS

 - OpenModelica Version: OMCompiler v1.19.0-dev.497+g4c87b752b8
 - OS: Ubuntu Focal

**Comment by casella** [comment]
@perost will look into this and fix it after Jan 10. In the meantime as a workaround I guess you can write 
```
Comp conditionalArray[max(param1-param2,0)] if param2<param1;
```
