### ISSUE TITLE
CombiTimeTable fails to read table if file has .csv extension

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#8385]
### Description

Simulating `IBPSA.Utilities.IO.Files.Examples.CSVReader` in OpenModelica fails with the error:
```
Error in line 1 when reading numeric data of matrix "csv(41,1)" from file "/home/mwetter/proj/ldrd/bie/modeling/github/ibpsa/modelica-ibpsa/IBPSA/Resources/Data/Utilities/IO/Files/Examples/CSVReader/Data.csv"
```
This model reads the file https://github.com/ibpsa/modelica-ibpsa/blob/master/IBPSA/Resources/Data/Utilities/IO/Files/Examples/CSVReader/Data.csv (which has extension .csv, but is not a csv file), using `CombiTimeTable` from the MSL. It appears that OpenModelica interprets this file as a csv file, and this causes the error. If `Data.csv` is renamed to `Data.txt` and that file is read, the model works.

Is this a bug in OpenModelica, or shall we fix this in the `IBPSA` library? I don't see any mention in `CombiTimeTable` that indicates that files with csv extensions are handled differently.

### Steps to Reproduce

Simulate `IBPSA.Utilities.IO.Files.Examples.CSVReader` in omc or OMEdit.

### Expected Behavior

The simulation should succeed.

### Version and OS

OpenModelica 1.19.0~dev-497-g4c87b75

IBPSA, commit 675dc37a364304e2212478e6ba35ca54d189a71c (current master).

**Comment by sjoelund** [comment]
Newer MSL versions support CSV-files: https://github.com/modelica/ModelicaStandardLibrary/commit/9d6d6d8f9bf3ff15d8dc52ad64400a9b5d317e35

We have some bugfixes from MSL and they are enabled for all MSL versions. Sometimes you get newer features, like in this case.

**Comment by mwetter** [comment]
Thanks, I will fix it in the `IBPSA` and `Buildings` libraries.
