### ISSUE TITLE
Strange condition in common.groovy

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#8386]
### Description

The comment says "// compile OMSens_Qt for Qt5" here:
https://github.com/OpenModelica/OpenModelica/blob/master/.CI/common.groovy#L379
but the if (isQt5) true part *does not build* omsens_qt, the false part does!

Somebody that knows what's going on (@adeas31, @sjoelund, @AnHeuermann) please check if this is correct.

**Comment by adrpo** [comment]
I guess we can close this ticket, touching omsense_qt.skip will actually prevent its build! I'll leave this open so that somebody can check also.

**Comment by adeas31** [comment]
This is correct. The first part is suppose to build OMSens since it only compiles with Qt5. The second skips it because of `omsense_qt.skip`.
