### ISSUE TITLE
boost is a required dependency, not optional

### ISSUE THREAD

**Issue by jdpipe** [OpenModelica/OpenModelica#8419]
### Description

Attempting to build omc from the master branch on Ubuntu 20.04 (via Github Actions).

### Steps to Reproduce

https://github.com/jdpipe/OpenModelica/runs/4812472162?check_suite_focus=true

### Expected Behavior

Boost is listed as an optional requirement. However, when it is not installed, the cmake step fails. Hence it is not optional. Some selected output:

```

-- The following OPTIONAL packages have not been found:

 * AsciiDoc
 * Boost

-- Configuring done
CMake Error at OMCompiler/SimulationRuntime/cpp/SimCoreFactory/CMakeLists.txt:11 (add_library):
  Target "OMCppOMCFactory" links to target "Boost::program_options" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at OMCompiler/SimulationRuntime/cpp/SimCoreFactory/CMakeLists.txt:11 (add_library):
  Target "OMCppOMCFactory" links to target "Boost::filesystem" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

### Screenshots

See link above.

### Version and OS

Master, at commit  aed8f074586888f2d60bd1e48cf126b2575d2e7b.
OS is Ubuntu 20.04 via GHA.

**Comment by mahge** [comment]
OpenModelica comes with C and CXX runtimes. The C runtime is the default and always enabled. The CXX runtime is built optionally since it takes some time to build and not everyone uses it daily. Boost is used by the CXX runtime.

The autoconf build handles this properly. The CMake build needs to make CXX runtime optional as well.

**Comment by mahge** [comment]
If you want to continue working without installing boost for now, a hack/workaround is to comment out this line: 
https://github.com/OpenModelica/OpenModelica/blob/4196d445144b4b0c86c9de3d8363e2b7ccd50cfc/OMCompiler/SimulationRuntime/CMakeLists.txt#L4

**Comment by mahge** [comment]
This has been fixed for quite some time. The CPP runtime can be disabled by specifying `-DOM_OMC_ENABLE_CPP_RUNTIME=OFF` when configuring OpenModelica.
