### ISSUE TITLE
"Setup of Modelica Standard Library version" dialog needs updated text

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OpenModelica#8445]
In a fresh install of OpenModelica 1.18.1, the first launch of OMEdit shows a dialog to setup the version of Modelica Standard Library to be loaded at startup (MSL v3.2.3, or v4.0.0, or none).

I believe the text inside the dialog was composed fro OM 1.17, so it needs an update for OM 1.18 and onwards. In particular:

> Please note that conversion scripts are not yet available in OpenModelica 1.17.x, so you need to use other Modelica tools to upgrade existing libraries to use MSL v4.0.0. Conversion script support is planned in OpenModelica 1.18.0.

I just saw that a MSL conversion script is heavily discussed in #7683. Is that the same script mentioned in the dialog?

**Comment by casella** [comment]
> In a fresh install of OpenModelica 1.18.1, the first launch of OMEdit shows a dialog to setup the version of Modelica Standard Library to be loaded at startup (MSL v3.2.3, or v4.0.0, or none).
> 
> I believe the text inside the dialog was composed fro OM 1.17, so it needs an update for OM 1.18 and onwards. In particular:
> 
> > Please note that conversion scripts are not yet available in OpenModelica 1.17.x, so you need to use other Modelica tools to upgrade existing libraries to use MSL v4.0.0. Conversion script support is planned in OpenModelica 1.18.0.

You are right, but it turned out conversion scripts were not available in 1.18.x either. They will be available in 1.19.0. I guess now it's too late to fix that, since most people have installed 1.18.x already, and 1.19.0 should be released in about one month.
 
> I just saw that a MSL conversion script is heavily discussed in #7683. Is that the same script mentioned in the dialog?

Yes.

**Comment by pierre-haessig** [comment]
> You are right, but it turned out conversion scripts were not available in 1.18.x either. They will be available in 1.19.0. I guess now it's too late to fix that, since most people have installed 1.18.x already, and 1.19.0 should be released in about one month.

OK, that's what I suspected. 

I agree, no need to make an "emergency" 1.18.2 release just for that ;-)

So once the dialog text is updated in the development branch, I guess this issue can be closed (no need to wait for the 1.19 release).

**Comment by casella** [comment]
Yes, I think the whole dialog will be updated and simplified, we'll take care of that in the next one-two weeks.

**Comment by adeas31** [comment]
See PR #8720
