### ISSUE TITLE
Add reference results to Buildings library testing

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8453]
Reference results for the latest version of Buildings are available here: https://simulationresearch.lbl.gov/jmodelica/modelica-buildings/Dymola/

@sjoelund, @adrpo, is the file format ok? Can you add them to the CI tests?

**Comment by casella** [comment]
@sjoelund, @adrpo, @adeas31, please note we must be able to read this file format by Sep 15 at the latest, to comply with our obligations with LBL.

**Comment by casella** [comment]
Some more info:
- the results are posted at https://simulationresearch.lbl.gov/jmodelica/modelica-buildings/Dymola/
- filenames have `_` replacing `.` for composite pathnames
- the file format is not the standard csv, though I guess a few lines of python could turn it into that
- there are .mos scripts [here](https://github.com/lbl-srg/modelica-buildings/tree/master/Buildings/Resources/Scripts/OpenModelica/compareVars) that build an array with the name of the saved variables for each model. Apparently they were set up for use in OMC, not sure if the can come in handy
- https://simulationresearch.lbl.gov/jmodelica/modelica-buildings/Dymola/lastCommit.txt shows which version of the library has been used to generate the results

I'm not sure if our CI already supports something like this, or if we need to write some extra Python code to do so. Please let me know if we can get this to work in a short time or if it requires some substantial work. Thanks!

**Comment by adrpo** [comment]
I remember that @sjoelund has made a script to translate from the Buildings format to something that OMC can understand.

**Comment by casella** [comment]
Can you please give me some feedback this Monday? I cannot participate to the devmeeting, but if we could put this online now that would be great.

**Comment by casella** [comment]
Update from @mwetter: the reference result repository has been refactored and is available at https://simulationresearch.lbl.gov/ReferenceResults/modelica-buildings/

We should
- [ ] Add a Buildings_9 test that refers to the HEAD of the [maint_9.1.x branch](https://github.com/lbl-srg/modelica-buildings/commits/maint_9.1.x), similarly to what we do for Buildings_8
- [ ] Set the test result sources for the Buildings_9 report to https://simulationresearch.lbl.gov/ReferenceResults/modelica-buildings/maint_9.1.x/Dymola/
- [ ] Set the test result sources for the Buildings_latest report to https://simulationresearch.lbl.gov/ReferenceResults/modelica-buildings/master/Dymola/

**Comment by casella** [comment]
The proper reference files should now be used, we'll see after the next test run in 1-2 days.

**Comment by casella** [comment]
The [Buildings_9 report](https://libraries.openmodelica.org/branches/master/Buildings_9/Buildings_9.html) is now online with verification results.

**Comment by casella** [comment]
The [Buildings_latest](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) report now uses the version specific data from the new source.
