### ISSUE TITLE
The NF cannot evaluate a parameter due to a (supposed?) cyclic dependency

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8454]
@mwetter reports that model [Buildings.Experimental.DHC.Examples.Combined.ParallelConstantFlow](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Experimental.DHC.Examples.Combined.ParallelConstantFlow.err) fails during flattening with this error:
```
[Buildings 9.0.0-master/Experimental/DHC/Plants/Reservoir/BoreField.mo:44:3-46:55:writable] Error: 
Dimension 1 of cooBor, 'borFie.nBor', could not be evaluated due to a cyclic dependency.
```
@perost, is this cyclic dependency real?

**Comment by perost** [comment]
Minimal example:
```Modelica
record BorefieldTemplate
  parameter ConfigurationTemplate conDat;
end BorefieldTemplate;

record ConfigurationTemplate
  parameter Integer nBor;
  parameter Real[:] cooBor;
end ConfigurationTemplate;

model BoreField
  parameter BorefieldTemplate borFieDat(conDat = ConfigurationTemplate(nBor = 350, cooBor = cooBor));
  parameter Integer nBor = borFieDat.conDat.nBor;
  final parameter Real[nBor] cooBor = {i for i in 1:nBor};
end BoreField;
```
There's a cycle between `size(cooBor, 1)`, nBor, and `size(borFieDat.conDat.cooBor, 1)` that arises due to needing to type `borFieDat.conDat` in order to look up the value of `borFieDat.conDat.nBor` needed for the dimension of `cooBor`.

To handle this we'd have to look up the value of `borFieDat.conDat.nBor` without typing `borFieDat.conDat` or only typing it partially, which I think it possible but quite complicated.

**Comment by casella** [comment]
@mwetter I'm wondering if it is really necessary to support such a convolute construct. If there is no easy way to change the library design to avoid this loop, then I guess @perost should implement what he suggested in the previous comment.

**Comment by mwetter** [comment]
Let me have a look into it next week. I tried some other formulations, but didn't succeed yet.

**Comment by perost** [comment]
I played around a bit and found a solution that seems to work. We could actually handle this already since the dimension triggering the error isn't actually used, the issue was just how to allow it without breaking the detection of actual cycles.

**Comment by mwetter** [comment]
Great, thanks for fixing it.
