### ISSUE TITLE
Documentation for source-code FMUs

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8458]
### Description

With OpenModelica it is possible to generate and use source-code FMUs, at least in theory. But it is terrible complicated and I can't find any documentation on it in the user's guide.

Of course this is a difficult topic, but we could at least show how it works for a linux64 FMU that is "re-compiled" on the same system that has no omc.
And clarify what you can do with these FMUs and what are the limitations.

Also adding a test case for re-compiling source-code FMUs to the testsuite would be nice and to make sure the documentation stays valid.

### Steps to Reproduce

See e.g. https://github.com/OpenModelica/OpenModelica/issues/8452 where I failed to re-compile a FMU.

**Comment by sjoelund** [comment]
The problem with source-code FMUs is that OMSimulator doesn't do it and OM itself doesn't read the XML-structure to compile the correct files. There are third-party tools that have used this method...

**Comment by AnHeuermann** [comment]
But we could still provide a documentation on how to do it by hand. Or make sure that tools that can do this work with our source-code FMUs (I think FMPy has this feature, but doesn't work out of the box.).

If you do it yourself I hope it isn't that much more then running `configure` in the source folder with the correct variables, maybe linking to 3rdParty solvers (CMINPACK, KINSOL, CVODE) installed on the host system and running `make`.

And if someone wants to implement it in OM or OMSimulator that could be a good point to start.
