### ISSUE TITLE
ClaRa Variable not found in scope

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8465]
### Description

For the developer version of ClaRa a variable is not found in scope for model `ClaRa.Components.TurboMachines.Compressors.Check.Test_CompressorVLE_L1_stageStacked`, see the [log file](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.TurboMachines.Compressors.Check.Test_CompressorVLE_L1_stageStacked.err).

### Steps to Reproduce

Simulate `ClaRa.Components.TurboMachines.Compressors.Check.Test_CompressorVLE_L1_stageStacked` with omc.

```
[/mnt/ReferenceFiles/ExtraLibs/packaged/ClaRa/Components/TurboMachines/Compressors/CompressorVLE_L1_stageStacked.mo:311:7-311:44:writable] Error: Variable inlet.m_flow not found in scope CompressorVLE_L1_stageStacked.
```

### Version and OS

- OpenModelica Version: OMCompiler v1.19.0-dev.545+g5c10d4c725
- OS: Ubuntu 20.04.3 LTS
- Versions of used Modelica libraries: ClaRa_dev @ c57bace0acbe86a8ae2ccf3e427c60093c5ac95c

**Comment by perost** [comment]
That's because `inlet` doesn't actually exist in that model. `inlet.m_flow` is used in a modifier of `summary` which itself contains a `inlet` component, so I assume it's supposed to be `summary.inlet.m_flow` instead of just `inlet.m_flow`.

**Comment by AnHeuermann** [comment]
Okay, I'll create an issue on the GitLab.

**Comment by AlesVojacek** [comment]
That should be solved now (inlet.m_flow->fluid_inlet.m_flow).
