### ISSUE TITLE
ClaRa fails to pass properly array pointers (ExternalObject) via inner/outer record

### ISSUE THREAD

**Issue by AlesVojacek** [OpenModelica/OpenModelica#8469]
### Description

For the developer version of ClaRa some models are failing to pass properly array pointers (ExternalObject), e.g. {tube.fluidInlet.vleFluidPointer} via inner/outer record (e.g. tube.iCom). 
Error:  tube.iCom.fluidPointer_in = {tube.fluidInlet.vleFluidPointer} has size 1 but 0 variables ()

Check [reports](https://libraries.openmodelica.org/branches/master/ClaRa_dev/ClaRa_dev.html) for:
- ClaRa.Components.VolumesValvesFittings.Pipes.Check.FlowReversal.Test_Pipe_L4_Simple
[direct link](https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.VolumesValvesFittings.Pipes.Check.FlowReversal.Test_Pipe_L4_Simple.err)
- ClaRa.Components.VolumesValvesFittings.Pipes.Check.FlowReversal.Test_Pipe_L4_Advanced
- ClaRa.Components.HeatExchangers.Check.Test_HEXvle2vle_L3_2ph_BU_ntu
- ClaRa.Components.HeatExchangers.Check.Test_HEXvle2vle_L3_2ph_BU_simple
- and in many other models

### Steps to Reproduce

Simulate above mentioned models.

### Expected Behavior

It should pass the array pointers properly to iCom.

### Version and OS

 - OpenModelica Version: OpenModelica v1.19.0-dev-541-gebaac9b11c (64-bit)
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by perost** [comment]
Minimal example:
```Modelica
class EO
  extends ExternalObject;

  function constructor
  end constructor;

  function destructor
  end destructor;
end EO;

model M
  EO e1;
  EO e2[1] = {e1};
end M;
```
Not sure who might want to have a look at this, @AnHeuermann @kabdelhak ?

**Comment by kabdelhak** [comment]
I looked a bit into it and it seems that `e1` as well as `e2` are filtered out during the lowering to backend and are not considered unknowns. What is supposed to happen here actually? I don't really understand. If both are unknown, we have 1 equation and 2 unknowns.

**Comment by kabdelhak** [comment]
I also think that the message from the minimal system is not the same as the one from the original system.

**Comment by perost** [comment]
> I also think that the message from the minimal system is not the same as the one from the original system.

I get:
```
Error: e2 = {e1} has size 1 but 0 variables ()
```
which is the same as the reported error. Do you get something else?

Anyway, I don't know what's supposed to happen either. The specification says that an `ExternalObject` can be bound in a component declaration but doesn't say what the implications of that are.

**Comment by kabdelhak** [comment]
> > I also think that the message from the minimal system is not the same as the one from the original system.
> 
> I get:
> 
> ```
> Error: e2 = {e1} has size 1 but 0 variables ()
> ```
> 
> which is the same as the reported error. Do you get something else?
> 

Oh yes i was a little confused about the 
```
Error: Too many equations, over-determined system. The model has 1 equation(s) and 0 variable(s).
```

**Comment by kabdelhak** [comment]
> Anyway, I don't know what's supposed to happen either. The specification says that an `ExternalObject` can be bound in a component declaration but doesn't say what the implications of that are.

Hmm okay. @AlesVojacek is the minimal model properly representing your problem and could you explain what is expected to happen? From what i can see there are 2 unknowns and 1 equation. Does `e1` get assigned implicitly somehow?

**Comment by perost** [comment]
> Oh yes i was a little confused about the
> 
> ```
> Error: Too many equations, over-determined system. The model has 1 equation(s) and 0 variable(s).
> ```

My small example may very well be unbalanced, I was mostly just aiming to demonstrate the `has size 1 but 0 variables` error and I don't really know how you'd make such a model balanced. Dymola says there are 1 equation and 2 variables, so maybe `ExternalObject` variables are supposed to be counted as unknowns.

**Comment by sjoelund** [comment]
`e1` in that example needs to be bound to a constructor call indeed.

**Comment by kabdelhak** [comment]
I think this properly represents the problem:

```
class EO
  extends ExternalObject;

  function constructor
    output EO e;
    external "C" e = init();
  end constructor;

  function destructor
    input EO e;
    external "C" deinit(e);
  end destructor;
end EO;

model M
  EO e1 = EO();
  EO e2[1] = {e1};
end M;
```

**Comment by AlesVojacek** [comment]
> ```modelica
> (
> ```

**Comment by AlesVojacek** [comment]
> I think this properly represents the problem:
> 
> ```modelica
> class EO
>   extends ExternalObject;
> 
>   function constructor
>     output EO e;
>     external "C" e = init();
>   end constructor;
> 
>   function destructor
>     input EO e;
>     external "C" deinit(e);
>   end destructor;
> end EO;
> 
> model M
>   EO e1 = EO();
>   EO e2[1] = {e1};
> end M;
> ```

I think this represents it.

**Comment by kabdelhak** [comment]
I created a PR #8472 where the minimal model passes backend and now (as expected) fails during runtime because i just made up the external functions and they do not really exist. I do get the warning: 
```
Warning: Alias equations of external objects are not Modelica compliant as in:                                                                                                                                     
    e2 = {e1} 
```
I think this is expected but i cannot tell if it is parsed correctly anyway. It might be that this passing of a pointer is not happening.

**Comment by perost** [comment]
> I created a PR #8472 where the minimal model passes backend and now (as expected) fails during runtime because i just made up the external functions and they do not really exist. I do get the warning:
> 
> ```
> Warning: Alias equations of external objects are not Modelica compliant as in:                                                                                                                                     
>     e2 = {e1} 
> ```
> 
> I think this is expected but i cannot tell if it is parsed correctly anyway. It might be that this passing of a pointer is not happening.

As I mentioned the specification says that external objects can be bound in a component declaration, so it should be allowed. It might be that this was added to the specification later and our warning predates it, or it might be because we move the binding to an equation in the frontend and the backend thinks it's just a normal equation.

**Comment by kabdelhak** [comment]
> the backend thinks it's just a normal equation.

Yes thats exactly it. It is handled as any other equation, is there maybe something in the EquationAttributes that indicates it stems from component declaration?

**Comment by perost** [comment]
> > the backend thinks it's just a normal equation.
> 
> Yes thats exactly it. It is handled as any other equation, is there maybe something in the EquationAttributes that indicates it stems from component declaration?

Equations have a `DAE.ElementSource` which contains a lot of information (most of which the NF doesn't bother filling in since the backend doesn't seem to use it), but nothing to indicate the actual source of an equation. But we could add a field to it to indicate that if you need it.

**Comment by kabdelhak** [comment]
My PR passes and i further tested it to see if it works as expected. I expanded the MWE to the following:
```Modelica
class EO
  extends ExternalObject;
  function constructor
    output EO e;
    external \"C\" e = init();
  end constructor;

  function destructor
    input EO e;
    external \"C\" deinit(e);
  end destructor;
end EO;

function getStuff
  input EO e;
  output Real y;
  external \"C\" stuffReturn(e);
end getStuff;

model M
  Real y;
  EO e1 = EO();
  EO e2[1] = {e1};
equation
  y = getStuff(e2[1]);
end M;
```

Just to see if the alias equation gets handled properly. And it does, the backend shows that the equation 
```Modelica
  y = getStuff(e2[1]);
```
gets replaced by
```Modelica
  y = getStuff(e1);
```
and `e2[1]` is removed entirely. There are only two things i see left to do here:
 1. Suppress the warning since it is not actually true
 2. Check if `e2[1]` ends up in the result file (which i don't think it does since it also is not in the init_xml.

I think it is expected to be in the result file right?

**Comment by perost** [comment]
I updated `checkModel` in both the OF and the NF (which isn't used yet, but might as well fix it for when it will be) in #8473, by defining the size of `ExternalObject` to be 0. This was already the case in the NF and should've been the case in the OF too, but the OF miscounted empty classes as having size 1 due to a bug. The NF also didn't consider tuple types and miscounted due to that.

With these changes both `checkModel` implementations now report 6512 variables and 6512 equations for the `Test_Pipe_L4_Simple` model.

**Comment by kabdelhak** [comment]
> I updated `checkModel` in both the OF and the NF (which isn't used yet, but might as well fix it for when it will be) in #8473, by defining the size of `ExternalObject` to be 0. This was already the case in the NF and should've been the case in the OF too, but the OF miscounted empty classes as having size 1 due to a bug. The NF also didn't consider tuple types and miscounted due to that.
> 
> With these changes both `checkModel` implementations now report 6512 variables and 6512 equations for the `Test_Pipe_L4_Simple` model.

I think that is the better solution for now. My approach tries to remove it using something like alias elimination and i don't know if everything is done properly.

**Comment by perost** [comment]
> > I updated `checkModel` in both the OF and the NF (which isn't used yet, but might as well fix it for when it will be) in #8473, by defining the size of `ExternalObject` to be 0. This was already the case in the NF and should've been the case in the OF too, but the OF miscounted empty classes as having size 1 due to a bug. The NF also didn't consider tuple types and miscounted due to that.
> > With these changes both `checkModel` implementations now report 6512 variables and 6512 equations for the `Test_Pipe_L4_Simple` model.
> 
> I think that is the better solution for now. My approach tries to remove it using something like alias elimination and i don't know if everything is done properly.

I was going to say that my changes only affected `checkModel` and not simulation, but then realised that the `Test_Pipe_L4_Simple` model actually passes the backend now. I guess the backend uses the same type size function from the old frontend that I changed. That wasn't my intention, but maybe it's for the best anyway since it seems to actually work?

**Comment by kabdelhak** [comment]
> I was going to say that my changes only affected `checkModel` and not simulation, but then realised that the `Test_Pipe_L4_Simple` model actually passes the backend now. I guess the backend uses the same type size function from the old frontend that I changed. That wasn't my intention, but maybe it's for the best anyway since it seems to actually work?

Yes, it was only the size check that failed. Ship it! :)

**Comment by perost** [comment]
#8473 fixed the issue, and all the mentioned models at least pass the frontend now.
