### ISSUE TITLE
OpenModelica build not available for Ubuntu 21.10 (Impish Indri)

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OpenModelica#8470]
This issue is a follow-up of the forum post [OpenModelica install on Ubuntu 21.10](https://openmodelica.org/forum/default-topic/3402-openmodelica-install-on-ubuntu-21-10)

There is not yet (as of OM 1.18.1 release) an OpenModelica build available for Ubuntu 21.10 (Impish Indri). The most recent Ubuntu build target is 21.04 (hirsute). As said on the forum, the 21.04 build works quite well on 21.10, except for C++ code generation, after fiddling a bit with missing dependencies.

The main platform change between 21.04 and 21.10 seems to be the LLVM 12 → 13 transition, but I'm not at all a compilation expert, so do not trust my words.

Remark: the apt-key deprecation issue #8443 I also discovered while installing OM on Ubuntu 21.10 *does not need* to be addressed to target 21.10 (it can, but it's not mandatory before at least 22.10).

By the way, the paragraph on the Linux download page https://openmodelica.org/download/download-linux should be updated:
> We provide .deb packages compiled on Ubuntu and Debian: jessie, stretch, xenial, bionic (x86, amd64, and armv7), and usually the most recent non-LTS Ubuntu versions. 

If I understand correctly [jessie's Packages](https://build.openmodelica.org/apt/dists/jessie/stable/binary-amd64/Packages) file, only OM 1.16 is available for jessie. Xenial seems to have been dropped after 1.18.0 in september 2021.

**Comment by casella** [comment]
> By the way, the paragraph on the Linux download page https://openmodelica.org/download/download-linux should be updated:
> 
> > We provide .deb packages compiled on Ubuntu and Debian: jessie, stretch, xenial, bionic (x86, amd64, and armv7), and usually the most recent non-LTS Ubuntu versions.
> 
> If I understand correctly [jessie's Packages](https://build.openmodelica.org/apt/dists/jessie/stable/binary-amd64/Packages) file, only OM 1.16 is available for jessie. Xenial seems to have been dropped after 1.18.0 in september 2021.

@sjoelund can you please check and update the download-linux page? Thanks!

**Comment by durapensa** [comment]
Could this issue perhaps be expanded to encompass a general review of deb dependency strictness?

E.g., attempting to `sudo apt-get install omedit` on a `bullseye`-derived system (MX Linux 21 + AHS adavanced hardware support, with `deb http://build.openmodelica.org/apt bullseye release` in `/etc/apt/sources.list.d/openmodelica.list`) fails with the dependency error `libopengl0 : Depends: libglvnd0 (= 1.3.2-1) but 1.3.4-1~mx21ahs+1 is to be installed`.

Could some installation problems be resolved by allowing point version variations (e.g. `> 1.3.2` rather than `= 1.3.2-1` in the case of `libglvnd0`) with the caveat/disclaimer that only installations from stock repositories have been tested?

**Comment by sjoelund** [comment]
> Could some installation problems be resolved by allowing point version variations (e.g. `> 1.3.2` rather than `= 1.3.2-1` in the case of `libglvnd0`) with the caveat/disclaimer that only installations from stock repositories have been tested?

The dependencies on binaries are automatically generated and not chosen by us.

**Comment by pierre-haessig** [comment]
I believe this issue can be closed. The remaining question of apt-key deprecation is tracked separately (https://github.com/OpenModelica/OpenModelica/issues/8443). I haven't looked at the question of the upcoming 22.10 (kinetic).
