### ISSUE TITLE
Incorrect behaviour of drop-down unit menus for parameter inputs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8487]
### Description

Please load the following MWE package
```modelica
package TestDisplayUnit
  model M
    parameter Modelica.Units.SI.VolumeFlowRate q0(displayUnit="l/s");
    parameter Modelica.Units.SI.VolumeFlowRate q1(displayUnit="m3/h");        
    parameter Modelica.Units.SI.VolumeFlowRate q2(displayUnit="kg/s");
    parameter Modelica.Units.SI.VolumeFlowRate q3;
  end M;

  model S
  M m(q0 = 1, q1 = 1, q2 = 1, q3 = 1)  annotation(
      Placement(visible = true, transformation(origin = {8, 2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S;
end TestDisplayUnit;
```
When I double-click on `m,` I get a parameter window, where the unit menus do not behave as I'd expect.

1. The menu for `q0` allows me to change the unit from l/s to m3/s (which is the SI unit) but not to other units, such as m3/h.
2. The menu for  `q1` allows me to change the unit from m3/h to m3/s (which is the SI unit) but not to other units, such as l/s.
3. The menu for  `q2` displays the value in SI units (1 m3/s) but has a wrong indication of unit kg/s; if I change it to m3/s, the numerical value remains the same
4. The menu for  `q3` (which has no displayUnit attribute) does not allow me to use other units than SI.

### Expected Behavior
1. All available volume flow rate units should be displayed and selectable
2. All available volume flow rate units should be displayed and selectable
3. If an incompatible displayUnit is set, a warning should be issued and the menu should show the value with the SI unit selected by default, with the possibility of changing it to another compatible unit
4. The value with the default unit should be shown, but a menu should be provided that allows to change it to all other known compatible units.

**Comment by casella** [comment]
@adeas31 can we manage this for 1.19.0?

**Comment by bilderbuchi** [comment]
> 3. If an incompatible displayUnit is set, a warning should be issued and the menu should show the value with the SI unit selected by default, with the possibility of changing it to another compatible unit

would that be dependent on ` --unitChecking` being active, and show during unit checking? Ot do you mean in the plot perspective, even if unit checking is disabled?

**Comment by casella** [comment]
> would that be dependent on ` --unitChecking` being active, and show during unit checking? Ot do you mean in the plot perspective, even if unit checking is disabled?

`--unitChecking` runs dimensional checks on _units_ of variables _in equations_. AFAIK it has nothing to do with displayUnit.

**Comment by bilderbuchi** [comment]
Ah ok, I thought you might need that to determine *If an incompatible displayUnit is set*

**Comment by casella** [comment]
Yes, that is the idea. But we need to check if the displayUnit is dimensionally compatible with the unit. That's not what --unitchecking does, that feature checks for dimensional consistency of units in equations.

**Comment by casella** [comment]
See #8758.
