### ISSUE TITLE
Update keyring and add ccache to OMDev MSYS2 

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8501]
### Description

There is a new msys2-keyring package. The old one is no longer usable and gives errors like
```
error: msys: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
```

Also the CMake build needs ccache.

### How to update

I tried following https://www.msys2.org/news/#2020-06-29-new-packagers
and https://unix.stackexchange.com/questions/314698/pacman-error-duplicated-database-entry and did something like below.
But currently I'm still failing to update the keyring.

```
# rm -r /etc/pacman.d/gnupg/
# pacman-key --init
# pacman-key --populate msys2
```

```bash
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
$ pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
==> Checking msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig... (detached)
gpg: Signature made Mon Jun 29 07:36:14 2020 CEST
gpg:                using DSA key AD351C50AE085775EB59333B5F92EFC1A47D45A1
gpg: Good signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" [full]
```

```
# pacman -U --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
```

Remove duplicates in `/var/lib/pacman/local/`:
```
# rm /var/lib/pacman/local/pacman-mirrors-20220126-1/
# rm /var/lib/pacman/local/pacman-6.0.1-7/
# rm /var/lib/pacman/local/msys2-keyring-1~20210904-1/

# pacman -U --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
```

Update package mirrors
```
# pacman -S pacman-mirrors
[...]
warning: /etc/pacman.d/mirrorlist.mingw installed as /etc/pacman.d/mirrorlist.mingw.pacnew
warning: /etc/pacman.d/mirrorlist.mingw32 installed as /etc/pacman.d/mirrorlist.mingw32.pacnew
warning: /etc/pacman.d/mirrorlist.mingw64 installed as /etc/pacman.d/mirrorlist.mingw64.pacnew
warning: /etc/pacman.d/mirrorlist.msys installed as /etc/pacman.d/mirrorlist.msys.pacnew
# mv /etc/pacman.d/mirrorlist.mingw.pacnew /etc/pacman.d/mirrorlist.mingw
# mv /etc/pacman.d/mirrorlist.mingw32.pacnew /etc/pacman.d/mirrorlist.mingw32
# mv /etc/pacman.d/mirrorlist.mingw64.pacnew /etc/pacman.d/mirrorlist.mingw64
# mv /etc/pacman.d/mirrorlist.msys.pacnew /etc/pacman.d/mirrorlist.msys
```

Get a coffee and update everything:
```
# pacman -Syu
```

Also `base` group was replaced by `base` metapackage. So you might need to run
```
pacman -S base
```
as well.

### Version and OS

 - OMDev @ f5761810321b22a7d5280ee38c6d83f97052ec3f
 - OS: Windows with OMDev

**Comment by AnHeuermann** [comment]
@adrpo I have a branch with these changes, so I can upload it to somewhere.

**Comment by AnHeuermann** [comment]
Oh and to test that OMDev is actually usable:

Run MINGW64 shell
```bash
$ cd /path/to/OpenModelica
$ mkdir build_cmake
$ cd build_cmake
$ cmake -G "MSYS Makefiles" ..
$ make
```

**Comment by AnHeuermann** [comment]
I think it is also needed to update the keyring, see https://stackoverflow.com/questions/68669920/invalid-pgp-signature-when-updating-packages-in-msys2-despite-fixes

```
# pacman-key --keyserver keyserver.ubuntu.com --refresh-keys
```

**Comment by AnHeuermann** [comment]
@mahge I got it running without updating everything.
So no changes to OpenModelica are needed (`libszip*.dll` replaced by `libsz*.dll`).

I think one needs to do the following. But I tried a lot of different stuff, so maybe there is still something missing...

Reset pacman key store:
```bash
$ rm -r /etc/pacman.d/gnupg/
$ pacman-key --init
$ pacman-key --populate msys2
```

pacman-key was changed to to keyserver.ubuntu.com:
```bash
$ pacman-key --keyserver keyserver.ubuntu.com --refresh-keys
```

Update keyring:
```bash
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
$ curl -O https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
$ pacman-key --verify msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig
==> Checking msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig... (detached)
gpg: Signature made Mon Jun 29 07:36:14 2020 CEST
gpg:                using DSA key AD351C50AE085775EB59333B5F92EFC1A47D45A1
gpg: Good signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" [full]

$ pacman -U --config <(echo) msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
```

Install ccache:
```
$ pacman -S mingw64/mingw-w64-x86_64-ccache
$ pacman -S mingw32/mingw-w64-i686-ccache
```

**Comment by mahge** [comment]
> `$ pacman-key --keyserver keyserver.ubuntu.com --refresh-keys`

I guess this was missing. I have not seen this before. 

I am going get a new OMDev and try it out.

**Comment by AnHeuermann** [comment]
@adrpo Can we do this after the release is done?

Updating OMDev on a different machine takes forever and new Windows users can't compile OpenModelica with cmake.

**Comment by adrpo** [comment]
Yeah, we should try to update OMDev, maybe make a new report as the old one is already huge

**Comment by AnHeuermann** [comment]
ccache is now part of OMDev origin/master.

**Comment by AnHeuermann** [comment]
@adrpo 
Turns out the ccache from OMDev is broken.

```bash
user@PC MINGW64 ~
# ccache.exe --help

user@PC MINGW64 ~
#
```

Adding @mahge as well.

**Comment by adrpo** [comment]
Ouch. This is maybe because I installed a newer package on an older msys. I will see what i can do.

**Comment by AnHeuermann** [comment]
Maybe we should use a clean and newer MSYS to start over? I think that is what @mahge is doing at the moment.
I'll talk with him about this later today.

In the meantime we should probably revert f5f57b55f90f581e1997d82ef3e8ab81be475fae on origin/master and origin/maintenancev1.20.

**Comment by adrpo** [comment]
Yeah, i will do that. I found out the issue, it does: `_ZSt28__throw_bad_array_new_lengthv symbol not found`.
I will not revert it, I will compile ccache myself on the current OMDev and make a new commit.
When we are done with the release I will update OMDev to the latest.
