### ISSUE TITLE
Searching in wrong directory for external library

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8511]
### Description

I'n loading two libraries: `ClaRa` and `TILMediaClaRa`.
In TILMedia an external library `TILMedia170ClaRa` is used.

For example in 
```Modelica
annotation(
      __iti_dllNoExport=true,
      Include="double TILMedia_GasObjectFunctions_density_phxi(double,double,double*,void*);",
      Library="TILMedia170ClaRa");
```

`omc` is searching in `ClaRa/Resources/Library/` but not in `TILMedia/Resources/Library/`.

See also the test output: https://libraries.openmodelica.org/branches/master/ClaRa_dev/files/ClaRa_dev_ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_OffDesign.err

### Steps to Reproduce

Download clara_om from private GitLab, download TILMedia from the official TLK repo: https://github.com/TLK-Thermo/TILMediaClaRa

Then run
```modelica
loadFile("TILMediaClaRa/TILMedia/package.mo"); getErrorString();
loadFile("clara_om/ClaRa/package.mo"); getErrorString();

simulate(ClaRa.Components.TurboMachines.Pumps.Check.TestPump_L1_OffDesign); getErrorString();
```

Output
```
[/path/to/TILMediaClaRa/TILMedia/Internals/VLEFluidConfigurations/FullyMixtureCompatible/VLEFluid.mo:121:25-122:60:writable] Warning: Could not find library TILMedia170ClaRa in either of:
  [... omc install directory, /usr and lib/ stuff and ~/.openmodelica ...]
  /path/to/clara_om/ClaRa/Resources/Library/x86_64-linux/libTILMedia170ClaRa.a
  /path/to/clara_om/ClaRa/Resources/Library/x86_64-linux/libTILMedia170ClaRa.so
  /path/to/clara_om/ClaRa/Resources/Library/linux64/libTILMedia170ClaRa.a
  /path/to/clara_om/ClaRa/Resources/Library/linux64/libTILMedia170ClaRa.so
  /path/to/clara_om/ClaRa/Resources/Library/libTILMedia170ClaRa.a
  /path/to/clara_om/ClaRa/Resources/Library/libTILMedia170ClaRa.so
```

### Expected Behavior

According to [12.9.4 Annotations for External Functions](https://specification.modelica.org/master/functions.html) from the Modelica specification omc should search in `LibraryDirectory="modelica://ModelicaLibraryName/Resources/Library"` if nothing is provided.

Search in `/path/to/TILMedia`.

### Version and OS

 - OpenModelica Version: v1.19.0-dev-564-g9489298ff1
 - OS: Ubuntu 20.04
 - Versions of used Modelica libraries if applicable

**Comment by sjoelund** [comment]
This is an error in the library. If there is ClaRa code that links to a library in TILMedia, then there must be a `LibraryDirectory` annotation: `LibraryDirectory="modelica://TILMedia/Resources/Library"` on each such function.
Note that in this case, the library is found later anyway (because `-L` flags were added for TILMedia as well), but to suppress the notifications, the library should be fixed.

**Comment by casella** [comment]
In any case, referring to binaries of another libraries seems a questionable style for me. It would be much better if ClaRa only used Modelica stuff from TILMedia, and then the calls to external code would be confined to TILMedia itself.
