### ISSUE TITLE
Translation Error class not found in scope for package within

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8521]
### Description

When loading ClaRa (dev version) in OMEdit I get the following error:
```
[5] 15:40:31 Translation Error
[ClaRa.Basics: 19:3-19:52]: Base class ClaRa.Basics.Icons.PackageIcons.Basics100 not found in scope Basics.

[6] 15:40:31 Translation Error
[ClaRa: 3:3-3:52]: Base class ClaRa.Basics.Icons.PackageIcons.ClaRab100 not found in scope ClaRa.
```

### Steps to Reproduce

The problem looks something like this:

```modelica
within; 
package myLib
  extends myLib.A.Icon1;
end myLib;
```

```modelica
within myLib;
package A
  extends myLib.A.Icon1;
  
  partial class Icon1
    annotation(
      Icon(graphics = {Ellipse(fillColor = {200, 16, 191}, fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}), Text(origin = {0, -72}, textColor = {255, 0, 0},extent = {{-100, 100}, {100, -100}}, textString = "Icon2")}));
  end Icon1;

end A;
```

Here is a minimal working example: 
[myLib.zip](https://github.com/OpenModelica/OpenModelica/files/8033999/myLib.zip)

### Expected Behavior

Find `myLib.A.Icon1` in scope.

### Screenshots

![image](https://user-images.githubusercontent.com/38031952/153236739-fbdca2b8-a2cf-46d6-bfd2-80732cfb31a4.png)

### Version and OS

 - OpenModelica Version: v1.19.0-dev-564-g9489298ff1

**Comment by adeas31** [comment]
The problem comes from `getInheritedClasses` API call.

```
setCommandLineOptions("-d=nfAPI");
getErrorString();
loadFile("package.mo");
getErrorString();
getInheritedClasses(myLib);
getErrorString();
```
