### ISSUE TITLE
Libraries not available on Debian

### ISSUE THREAD

**Issue by valentindrou** [OpenModelica/OpenModelica#8523]
### Description
I am trying to install OpenModelica (nightly release) on Debian 11. I followed the instructions of https://www.openmodelica.org/download/download-linux. I managed to install OpenModelica but cannot install any library, including Modelica Standard Library. 

The command `apt-cache search "omlib-.*"` yields nothing, even after running `sudo apt update` and checking my internet connection. 

### Steps to reproduce
In Debian terminal : 
```
echo "deb https://build.openmodelica.org/apt `lsb_release -cs` nightly" | sudo tee /etc/apt/sources.list.d/openmodelica.list
wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
sudo apt update
apt-cache search "omlib-.*"
```

### Version and OS
- OpenModelica 1.19.0~dev-567-g4a43dbc
- Debian 11 working in WSL on Windows 10

**Comment by sjoelund** [comment]
Those instructions are for the release. You installed the nightly build, which has instructions:
> In the latest nightly build, there is now a package manager for Modelica libraries. See the [documentation](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html) for how to install the libraries.
