### ISSUE TITLE
Source files missing from modelDescription.xml <SourceFiles> section

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8524]
### Description

When generating a source-code FMU not all source files in FMU/sources/ are listed in the appropriate section in the modelDescription.xml.

This can be a problem for FMU Importing tools that can automatically rebuild the FMU. The depend on the correctness of this information.

### Steps to Reproduce

Build a source-code FMU for
```
model simpleLoop
  Real r(min = 0);
  Real s(min = -sqrt(2), max = sqrt(2));
  Real x(start=1.0), y(start=0.5);
  Real x_ref, y_ref;
equation
  r = 1+time;
  s = sqrt((2-time)*0.9);

  r^2 = x^2 + y^2;
  r*s = x + y;

  x_ref = r * (s/2 + sqrt(1/2-s^2/4));
  y_ref = r*s - x_ref;
  annotation(experiment(StartTime=0, StopTime=2));
end simpleLoop;
```

This model has a non-linear loop, so sources like CMinpack sources are missing from the modelDescription.xml.

### How to fix

One needs to uncomment these lines
https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/SimCode/SimCodeMain.mo#L822-L828
```
        // I need to see some tests failing or something not working to make sense of what to add here
        shared_source_files := List.flatten({RuntimeSources.simrt_c_sources,
                                             // dgesv_sources, // listed separately
                                             // simrt_c_sundials_sources, // listed separately
                                             simrt_linear_solver_sources,
                                             simrt_non_linear_solver_sources,
                                             simrt_mixed_solver_sources
                                            });
```
and fix the resulting issues.

### Version and OS

 - OpenModelica Version: v1.19.0-dev-564-g9489298ff1
 - OS: All

**Comment by AnHeuermann** [comment]
@mahge We could have a meeting to decide how to do this. I stumbled across this as well as you did previously.

Uncommenting the lines creates some issues, so we need to fix the copy files stuff above first.

**Comment by AnHeuermann** [comment]
Maybe waiting for the CMake build to be used for FMUs would be good. No point in fixing it now when we have to re-do it for the CMakeLists.txt anyway.

**Comment by mahge** [comment]
> @mahge We could have a meeting to decide how to do this. I stumbled across this as well as you did previously.
Uncommenting the lines creates some issues, so we need to fix the copy files stuff above first.

You are right I was not able to figure out what they were for. We can probably fix it easily. Meeting sounds better.

**Comment by mahge** [comment]
> Maybe waiting for the CMake build to be used for FMUs would be good. No point in fixing it now when we have to re-do it for the CMakeLists.txt anyway.

I think apart from "possible" bugs or overlooked stuff, the CMake build should support FMUs just as good as the normal one. In some rare cases you might get different text output printed but you should not care about that unless you are doing the diff (e.g. rtest or jenkins). for those we need to updated the expected outputs. Other than that it should be good to go.

However, if we find out how to fix it for the Makefiles build it should be quite easy to port it to the CMake build and vice versa.
