### ISSUE TITLE
OMEdit does not save experiment annotation

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8538]
### Description
I already posted this issue some time ago, without a procedure to reproduce it, and at that time it seemed invalid. Now I have that procedure.
The issue is that  OMEdit does not save experiment annotation if "simulate" check box is not checked

### Steps to Reproduce
[RL.mo.txt](https://github.com/OpenModelica/OpenModelica/files/8053071/RL.mo.txt)
1. Run the enclosed RL.mo and plot inductor.i. The timespan of the curve is 0.01 s
2. Go in the diagram perspective, and change the simulation Stop Time to 0.02s; "Save experiment annotation inside model" must be checked, while "Simulate" must not.
3. Click on the Simulate Button: OMEdit runs, then switches into the Plotting perspective, but the time span is still 0.01s
4. Get back to the Modelling perspective: there one sees, in both the "Simulation setup" and in the experiment annotation, that the Stop Time is still 0.01.

### Expected Behavior
At step 3 we should see results with a time span of 0.02s
At step 4 we should see in both the Simulation Setup and experiment annotation StopTime=0.02.

### Version and OS

OM 1.18.0 64 bit Win 10.
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adeas31** [comment]
This should work fine now. Thanks @max-privato for excellent description of the issue. That helped a lot.
