### ISSUE TITLE
Backend issue in HanserModelica

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8539]
@perost, there are three models failing in HanserModelica as [HanserModelica.Machines.TestDoubleLayer7over9](https://libraries.openmodelica.org/branches/master/HanserModelica/files/HanserModelica_HanserModelica.Machines.TestDoubleLayer7over9.err). There is one NF error reported
```
Error: Internal error NFAlgorithm.getInputsOutputs failed.
```
and then the NF finishes with
```
Notification: Model statistics after passing the front-end and creating the data structures used by the back-end:
 * Number of equations: 0
 * Number of variables: 0
```
which is kind of weird, because the whole model went AWOL. Looking at the overview report, this seems a regression since 1.17.0, i.e., a NF-specific problem.

Can you please have a look?

@christiankral, this fix should get you 100% support back with the next release.

**Comment by perost** [comment]
`NFAlgorithm.getInputsOutputs` was added by #8520, so that's something for @kabdelhak to look at.

The 0 equations and 0 variables seems to be correct though, the model only contains parameters and an initial equation as far as I can see. But that in itself shouldn't cause any issues, so there much be something else going wrong in the backend.

**Comment by casella** [comment]
> `NFAlgorithm.getInputsOutputs` was added by #8520, so that's something for @kabdelhak to look at.

In any case, the problem was there also in 1.18.0 and 1.17.0.

> The 0 equations and 0 variables seems to be correct though, the model only contains parameters and an initial equation as far as I can see.

You're right, I hadn't looked into it. 

> But that in itself shouldn't cause any issues, so there much be something else going wrong in the backend.

Yes. @kabdelhak, this model involves scalar functions handling arrays of operator records, so there are quite many things that can go wrong there 😄 

Can you please have a look?

**Comment by phannebohm** [comment]
> `NFAlgorithm.getInputsOutputs` was added by #8520, so that's something for @kabdelhak to look at.

I think that was me actually, way back in 2019. Let's see :smile:

**Comment by kabdelhak** [comment]
> > `NFAlgorithm.getInputsOutputs` was added by #8520, so that's something for @kabdelhak to look at.
> 
> I think that was me actually, way back in 2019. Let's see smile

Yea we can have a look together at it. Unfortunately it is still not really tested since i did not implement algorithms in the new backend yet.

**Comment by casella** [comment]
I have no strong opinions on that :)

**Comment by phannebohm** [comment]
Thanks @perost, I also found the issue with `HashSet.add` but had no clue what it was about. I suppose we didn't have `UnorderedSet` back then, I changed it to use them now. 

In fact I don't exactly remember what this was about, but we wanted to have the iterators for something, maybe for shadowing, I don't know.

Anyhow, my changes seem to fix the frontend issue, but the backend issue remains for now
```
Error: No system for the symbolic initialization was generated
```

**Comment by casella** [comment]
@phannebohm any cluse why we still have a backend issue here?

**Comment by casella** [comment]
@phannebohm one more call if you can figure out what went wrong here, before we branch off 1.19.0-beta.1

Thanks!

**Comment by phannebohm** [comment]
The failing stage is analyzeInitialSystem, which is also responsible for balancing the initial system.
@kabdelhak did some improvements to the algorithm, I guess there is something missing, might be small but I can't tell. It looks like it is somewhere in step 6. of function balanceInitialSystem, `scal_to_arr` is problematic I guess:
https://github.com/OpenModelica/OpenModelica/blob/67d7e86f7287fa69b203b0ca2d54699c5aee4903/OMCompiler/Compiler/BackEnd/Initialization.mo#L1291

I'm loaded with other things so I give up to @kabdelhak :innocent:

**Comment by casella** [comment]
Thanks @phannebohm!

@kabdelhak this would be good to get this fixed in 1.19.0. It is an old regression, and it's a shame that @christiankral cannot use OMC for teaching with his library without compromises, using a recent version of OMC. He may still be using 1.16.5 for that reason.

`HanserModelica.Machines.TestDoubleLayer7over9` did work in [v. 1.16.5](https://libraries.openmodelica.org/branches/v1.16/HanserModelica/files/HanserModelica_HanserModelica.Machines.TestDoubleLayer7over9.err), got broken in [v. 1.17.0](https://libraries.openmodelica.org/branches/v1.17/HanserModelica/files/HanserModelica_HanserModelica.Machines.TestDoubleLayer7over9.err) and then remained broken since then.

I'm not sure when exactly it got broken, if that is useful maybe @mahge can run his magic scripts and figure that out.

**Comment by perost** [comment]
> `HanserModelica.Machines.TestDoubleLayer7over9` did work in [v. 1.16.5](https://libraries.openmodelica.org/branches/v1.16/HanserModelica/files/HanserModelica_HanserModelica.Machines.TestDoubleLayer7over9.err), got broken in [v. 1.17.0](https://libraries.openmodelica.org/branches/v1.17/HanserModelica/files/HanserModelica_HanserModelica.Machines.TestDoubleLayer7over9.err) and then remained broken since then.
> 
> I'm not sure when exactly it got broken, if that is useful maybe @mahge can run his magic scripts and figure that out.

It got broken when switching to the new frontend, that model works with the old. The difference is a declaration in `TestSingleLayer12over12`:
```Modelica
      parameter Complex[winding.m] N = HanserModelica.Machines.Functions.complexTurns(winding);
```
The old frontend evaluates the function call in this case while the new one doesn't (because `N` is neither structural nor `final`), so the new frontend creates an initial equation for the binding equation that the backend can't handle (might be because `N` is an array of records). So a workaround is to just stick an `annotation(Evaluate=true)` on the declaration of `N`.

**Comment by casella** [comment]
Aha! Thanks @perost!

In this case, there's no point wasting time to fix the old backend for that. I assume the new one will be able to handle this kind of things. @kabdelhak can you confirm?

**Comment by casella** [comment]
@christiankral, please see https://github.com/christiankral/HanserModelica/pull/13

**Comment by christiankral** [comment]
@casella Thanks for your support.

Created new bug fix version [v1.1.2](https://github.com/christiankral/HanserModelica/tree/v1.1.2) of HanserModelica.

**Comment by casella** [comment]
As the change makes its way through the pipeline, we should eventually see [this report](https://libraries.openmodelica.org/branches/master/HanserModelica/HanserModelica.html) mentioning 1.1.2 and going all green. Then, we can close the ticket.

**Comment by phannebohm** [comment]
> As the change makes its way through the pipeline, we should eventually see [this report](https://libraries.openmodelica.org/branches/master/HanserModelica/HanserModelica.html) mentioning 1.1.2 and going all green. Then, we can close the ticket.

All green.

**Comment by casella** [comment]
One more library with 100% OMC support :)

Thanks to @christiankral for the quick reaction on the library side.

**Comment by christiankral** [comment]
Thanks to the great OpenModelica team @casella @phannebohm @perost @kabdelhak for making this possible!

**Comment by casella** [comment]
@christiankral, this is only the beginning :)
