### ISSUE TITLE
Is a record of parameters a parameter itself?

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8540]
Model [Buildings.Fluid.Geothermal.BuriedPipes.Validation.GroundCouplingAIT](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Fluid.Geothermal.BuriedPipes.Validation.GroundCouplingAIT.err) fails with
```
[Buildings 9.0.0-master/Fluid/Geothermal/BuriedPipes/Validation/GroundCouplingAIT.mo:248:5-248:18:writable]
Error: Component cliCon of variability parameter has binding 'cliCon[<groMai, groMai>]' of higher variability continuous.
```
where `cliCon` is defined as
```modelica
  BoundaryConditions.GroundTemperature.ClimaticConstants.Generic cliCon(
    TSurMea=281.53,
    TSurAmp=9.88,
    sinPha=9002880)
    "Climatic constants in Pongau, Austria"
    annotation (Placement(transformation(extent={{120,-80},{140,-60}})));
```
and `BoundaryConditions.GroundTemperature.ClimaticConstants.Generic` is defined as
```modelica
record Generic "Generic climatic constants"
  extends Modelica.Icons.Record;
  parameter Modelica.Units.SI.Temperature TSurMea
    "Mean annual surface temperature";
  parameter Modelica.Units.SI.TemperatureDifference TSurAmp
    "Surface temperature amplitude";
  parameter Modelica.Units.SI.Duration sinPha(displayUnit="d")
    "Phase lag of soil surface temperature";
end Generic;
```
@perost, is a record of parameters only a parameter itself? If so, the NF should behave accordingly, otherwise we should ask @mwetter to add a parameter prefix to the declaration of `cliCon`. I scanned the specification but I couldn't find any indication about that. Also, I have a feeling of deja-vu, but I can't remember if and where we already discussed this.

**Comment by perost** [comment]
> @perost, is a record of parameters only a parameter itself? If so, the NF should behave accordingly, otherwise we should ask @mwetter to add a parameter prefix to the declaration of `cliCon`. I scanned the specification but I couldn't find any indication about that. Also, I have a feeling of deja-vu, but I can't remember if and where we already discussed this.

A component is only a parameter if it's defined as a parameter. There's a specification ticket about it somewhere, but that was the conclusion and there was no need to add anything to the specification since that is what's already specified. The Buildings library has had several such issues in the past that were fixed, but it seems another one has snuck in that needs to be fixed.

**Comment by mwetter** [comment]
This will be corrected in the Buildings library through https://github.com/lbl-srg/modelica-buildings/pull/2888

**Comment by casella** [comment]
Thanks @mwetter!

For the record, the issue was discussed in [MLS #1832](https://github.com/modelica/ModelicaSpecification/issues/1832).
