### ISSUE TITLE
Display all available libraries per default in OMEdit package manager dialog

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8545]
### Description

I can't download TILMedia with the package manager from OMEdit. The `OK` button is greyed out.
I can't choose a version, but the repository on GitHub has a release tagged.

### Steps to Reproduce

Start OMEdit.
File->Install Library
Name: TILMedia

### Expected Behavior

Install the library or tell me why I can't press okay.

### Screenshots

![image](https://user-images.githubusercontent.com/38031952/154039721-6a43b702-3dd8-4ab0-9201-462a0e03af36.png)

### Version and OS

 - OpenModelica Version: omc v1.19.0-dev-569-g4dbf5668cf (64-bit)
 - OS: Windows 10
 - Library: TILMedia https://github.com/TLK-Thermo/TILMediaClaRa

**Comment by sjoelund** [comment]
You need to enable installing pre-releases with no support (since there is no tagged release).

**Comment by AnHeuermann** [comment]
Ah I see. How can we make this obvious to the user?

Maybe use a table with all available libraries and some filter options to only show the ones with a specific version or support level?
In that I would see something like this


| Version     | Release type      | Support Level |
|-------------|-------------------|---------------|
| 1.7.0-ClaRa | Pre release build | None          |
| 1.7.0-main  | Pre release build | None          |

and could pick the one that is closes to what I need.

**Comment by casella** [comment]
@AnHeuermann that's precisely what we're trying to avoid: having people try all kind of experimental, obsolete and unsupported libraries, and then complain they don't work, as if it were our fault.

I would rather not do that. The idea was to only show those libraries that reasonably can work out of the box by default. If you are daring to go further, that's your choice :)

However, I recognize now that the way the drop-down menu is handled is not very intuitive. I just opened #8550 on that topic.
