### ISSUE TITLE
Filter libraries in drop-down menus based on support level selection

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8550]
When installing a new library from the package manager OMEdit GUI, the drop-down list of libraries always shows the complete list of libraries taken from the OSMC server. However, the OK button is greyed out if there is no match for the currently version filter and support level.

This is really not intuitive at all, and leaves the end user wondering why he can't install the library (see #8545).

I would recommend that the drop-down menu list is updated to the actual status of the check-boxes, so that you always get a list of libraries that can actually be installed, based on that selection.

@adeas31, is this a quick fix?

**Comment by adeas31** [comment]
PR #8563 does what you want. The only thing is that we need to go through all the libraries and their available versions. That basically means calling `getAvailablePackageVersions` api on each of the library. With the latest libraries json it resulted in 160 calls. That went pretty fast on my machine and one can hardly notice it. But of course it depends on how many libraries we support in the future. The bigger the list the slower the response time.

I also modified the layout of the dialog. First you get the filters and then the libraries and their versions.

![image](https://user-images.githubusercontent.com/4007231/154291730-ee60c262-046f-4cb3-8fd9-ea9cbd3d1201.png)

**Comment by casella** [comment]
> PR #8563 does what you want. 

Good.

> The only thing is that we need to go through all the libraries and their available versions.

But I guess you did that anyway, right? The OK button was greyed or not depending on which checkboxes were clicked and on which library was selected, so the information was there already before #8563.

> That basically means calling `getAvailablePackageVersions` api on each of the library. With the latest libraries json it resulted in 160 calls. That went pretty fast on my machine and one can hardly notice it. But of course it depends on how many libraries we support in the future. The bigger the list the slower the response time.

Well, if you want to install libraries, you may have to wait for a while. If the waiting becomes noticeable, we'll add some "loading library info, please wait" message somewhere.
> 
> I also modified the layout of the dialog. First you get the filters and then the libraries and their versions.
> 
> ![image](https://user-images.githubusercontent.com/4007231/154291730-ee60c262-046f-4cb3-8fd9-ea9cbd3d1201.png)

LGTM.

Thanks!

**Comment by adeas31** [comment]
> But I guess you did that anyway, right? The OK button was greyed or not depending on which checkboxes were clicked and on which library was selected, so the information was there already before https://github.com/OpenModelica/OpenModelica/pull/8563.

No, before #8563 the versions are fetched when user selects a library. Now its driven by filters instead of the library. Now we fetch versions of all libraries and then apply the filter.

**Comment by sjoelund** [comment]
I've been thinking about the UI and I believe it's a bit redundant. In the JSON we change the support level based on if it's pre-release or not. So I think it would be simpler to only select support level.

**Comment by casella** [comment]
@sjoelund, I'm not sure I get it. Do you mean that the support level is not defined for a library as such, but it is defined for each version, and pre-release get only get experimental?

**Comment by sjoelund** [comment]
Look at https://github.com/OpenModelica/OMPackageManager/blob/3927acb33d9965998dbb3aa5d3ab7f59cbb362e9/repos.json#L7

Why filter on pre-release when you can just filter on supported/partially supported, etc? It will mostly be the same after all.

**Comment by casella** [comment]
OK, understood. I totally agree with that.

@adeas31, if you don't mind I would remove the Versions Filters checkboxes. This definitely makes the interface much neater and easy to understand without reading the manuals :)

> No, before https://github.com/OpenModelica/OpenModelica/pull/8563 the versions are fetched when user selects a library. 

OK, I see. 

> Now its driven by filters instead of the library. Now we fetch versions of all libraries and then apply the filter.

Looks much better to me anyway. If the waiting time is more than a few seconds, we can add a "please wait, loading libraries" message somewhere.

**Comment by adeas31** [comment]
> @adeas31, if you don't mind I would remove the Versions Filters checkboxes. This definitely makes the interface much neater and easy to understand without reading the manuals :)

I can make that change but still the user will see filtered libraries based on the support level selection. @AnHeuermann is not satisfied with that approach.

**Comment by adeas31** [comment]
PR #8550 is updated now.

![image](https://user-images.githubusercontent.com/4007231/154477297-ca819a5b-e311-4ab5-aa00-d6fe820046e2.png)

**Comment by AnHeuermann** [comment]
The current version is much better then the previous version of that PR.
But I'm still not sure if that is improved enough compared to the master.

A first time user has to know (or try at random) that the library in question has a specific support level.
So we assume that the user knows what we mean by support level i.e. how well OpenModelica supports the library, not how well the library is supported by the library developers.

But now there are less boxes to tick at random until the user is successful (worst case).
I guess for the next version we could go with a table with filter options, but this should be good enough for now.

**Comment by casella** [comment]
> A first time user has to know (or try at random) that the library in question has a specific support level.

If you desperately need library XYZ, and you don't find it in the drop-down menu with full or partial level, then you can check Experimental, Obsolete or None, but then you know you are walking a tight rope, and you can't complain if nothing ever works.

> So we assume that the user knows what we mean by support level i.e. how well OpenModelica supports the library, 

We have to write this in the documentation. That's on my todo list.

> not how well the library is supported by the library developers.

OK, now I see what you mean. If this is not 100% clear, then we should write "Level of support by OpenModelica" instead of "Support Levels" in the title of the checkbox group.

@adeas31, would you mind updating that?

Thanks!

> But now there are less boxes to tick at random until the user is successful (worst case). I guess for the next version we could go with a table with filter options, but this should be good enough for now.

Sure. Please open another ticket with your specification and set it for 1.20.0.
