### ISSUE TITLE
Unit prefixes in OMEdit plots should be used carefully

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8584]
@adeas31, as we go along I am discovering many use cases of automatic unit prefixing which are highly questionable, if not plain wrong. 

1. We get wrong multiples in case of powers at the numerator (1000 m2 is not 1 km2), see #8488

2. We get weird multiples k°C, which are not really used in practice, see
```modelica
model M
  Real T(unit="K", displayUnit="degC") = 1e4+1e3*sin(10*time);
end M;
```
![immagine](https://user-images.githubusercontent.com/4233148/154697124-a9ff0bbd-0d04-4ceb-b618-7a186064f939.png)

3. We get multiples that make no sense at all, e.g. k1 or m1
```modelica
model PerUnit
  Real x(unit="1");
  Real y(unit="1");
equation
  x = 1e-3*sin(10*time);
  y = 1e4*sin(10*time);
annotation(
    experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-6, Interval = 0.002));
end PerUnit;
```
![immagine](https://user-images.githubusercontent.com/4233148/154697356-6d8067d0-6130-48b7-a446-7cd8bc882062.png)
![immagine](https://user-images.githubusercontent.com/4233148/154697408-ecac1803-b773-4e69-9d71-8987261e3ffb.png)

All these cases look weird and/or confusing and covey an impression of sloppy quality. On the other side, getting MW or mV automatically is really nice. 

I just wonder, for the time being, could it be best if we had an explicit list of units for which we want to use prefixes, and only stick to that? Can you provide a list of the currently supported units in OMEdit?

@max-privato, what do you think?

**Comment by sjoelund** [comment]
kK would make more sense than k°C. I've never heard anyone say the latter, butI have heard the former.

**Comment by casella** [comment]
I'm fine with T(kK) and I can leave with T(k°C), but I would be very confused by y(k) or y(m) or y(M). I mean, prefixes are prefixes, they cannot be used alone. We seriously risk that people misunderstand results by orders of magnitude, and/or get angry at us.

**Comment by lochel** [comment]
I can sort of agree with both @max-privato and @casella. There is no problem and the graphs get actually improved as long as the user is aware of the prefixes. So in case we go down the route with prefixes like y(k) we have to make it cristal clear to all users. Or we could have this as an option feature in the settings. In this case we can assume that people are aware of it if they actively enable it for themselves.

**Comment by casella** [comment]
> The tool is ignorant and doesn't have any knowledge of the units. The implementation is simple, it just uses the plot range and decides the prefix based on thousand multiple. It doesn't care if the unit specified is valid or not.

OK. Although someone said "ignorance is strenght" (that was Orwell's 1984), I guess we should improve this :)

> Yes we could have a list of units that we want to use the prefix with.

LGTM, I'll make a proposal on this ticket.

> > Or we could have this as an option feature in the settings.
> 
> `Tools->Plotting->Prefix Units`

Would be nice to have, but doesn't solve the problem. If you activate this, you expect to get "good" units with prefixes, not bogus stuff.

**Comment by casella** [comment]
I scanned Modelica.Units.SI, thought of typical applications of Modelica I've seen through the years, and came up with this list of units for which prefixes definitely make sense, are immediately clear and can be quite useful in real life:

s, m, m/s, m/s2, rad, rad/s, rad/s2, Hz, N, N.m, Pa, Pa.s, J, J/kg, J/(kg.K), K, V, V/m, A, C, F, T, Wb, Wb/m, H, Ohm, S, W, W/m W/m2, var

If there are others that you'd like to see here, please add a further comment.

@adeas31, I would suggest to
- Add the Tools | Plotting | Prefix Units option, but keep it on by default, because it's nice in most cases, so I would rather have users disable it if they don't like it, rather than enable it - most users won't even know of its existence
- Only apply prefixes if the unit (or displayUnit) matches one of the units listed above.

Thanks!

**Comment by adeas31** [comment]
> Add the Tools | Plotting | Prefix Units option, but keep it on by default, because it's nice in most cases, so I would rather have users disable it if they don't like it, rather than enable it - most users won't even know of its existence

What I meant is that we already have that option but is not on by default. As I remember we decided to have it off by default.
https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#plot-window-menu

Right now we have this,

- Prefix units is applied only if there is a unit (doesn't matter what the unit is).
- Prefix units feature can be enabled/disabled.

What we want to have,

- List of units.
- Prefix units is applied only if unit matches one of the units listed above.
- Prefix units feature can be enabled/disabled.

What should we do in cases when there is no unit. Shall we apply prefix on them or not? @max-privato is in favor of x(m) or y(k).

**Comment by max-privato** [comment]
> What I meant is that we already have that option but is not on by default. As I remember we decided to have it off by default. https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#plot-window-menu

Obviously I would like to have it on by default. It is so useful!

> 
> What should we do in cases when there is no unit. Shall we apply prefix on them or not? @max-privato is in favor of x(m) or y(k).

I'm _strongly_ in favor of it. I have experience of this solution usage for several years. One is just a bit confused the first hour; later, it apprieciates the compactneess and expressivity of numarical labels writing.

BTW, there is an open ticket which requests to have for rotational speeds automatically both rpm and rad/s, and for energies both J and Wh: I know that this is not strictly related to this ticket, but just I mentioned this as a reminder... It is, for me, a much-needed feature

**Comment by adeas31** [comment]
> Obviously I would like to have it on by default. It is so useful!

OK.

> I'm strongly in favor of it. I have experience of this solution usage for several years. One is just a bit confused the first hour; later, it apprieciates the compactneess and expressivity of numarical labels writing.

Then this is what we need,

- List of units.
- Prefix units is applied if unit matches one of the units listed above and if there is no unit at all. Do not add prefix in case of non-listed units.
- Prefix units feature can be enabled/disabled.

@casella do you agree?

> BTW, there is an open ticket which requests to have for rotational speeds automatically both rpm and rad/s, and for energies both J and Wh: I know that this is not strictly related to this ticket, but just I mentioned this as a reminder... It is, for me, a much-needed feature

Can you please mention the ticket number?

**Comment by max-privato** [comment]
#5447, points 5 and 6

**Comment by casella** [comment]
I am also in favour to have this feature on by default, _as long as the functionality is not experimental anymore_, but is guaranteed to always produce correct, meaningful, and well understood results (i.e. only apply prefixes to the list of units where that is correct and makes sense). In that case, it can only do good, and if we turn it off by default, almost nobody will use it.

On the other hand, mi duole di contraddire il mio illustre amico e collega (this is a quote from Pinocchio, the original text, not the Disney version) @max-privato on the use of prefixes when there is no unit, for two reasons. 

The first reason is that, by definition, a prefix must be applied to a unit; a stand-alone prefix is an oxymoron. This is the standard use in the SI units and is well-understood by everybody who has a basic training (units and their prefixes are actually taught in primary school, as i remember). Conversely, the use of k to mean thousands, M to mean millions, and mu to mean millionths is not standard at all, and although it may be useful if you get used to it, it is not a well-recognized standard and may confuse users.

The second reason, which for me is the killer argument, is that the use of stand-alone prefixes leads to ambiguities and confusion. Does y(m) with a value of 3 mean 3.000 or 3 meters? Does x(T) with a value of 12 mean 12 Tesla or 12 trillions? There's no way to tell. If you use _m_ only as a prefix, as it was intended by the SI committee, then the is no longer any ambiguity: _m_ means meter, _mm_ means millimeter, and so forth.

IMO, when you have to balance between potential usefulness and potential misunderstandings in a software product for the general public, you always need to play safe. It's better to have a slightly less comfortable user than an angry one (or many). Hence, I would just use prefixes as, well, prefixes, for those units where this is correct and well understood.

I love these academic discussions 😄
