### ISSUE TITLE
Make a new test job for the new backend

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8590]
@kabdelhak requests a testing job for the new backend. For the time being it should only test MSL and ScalableTestSuite.

It's not necessary that it runs every day, once or twice per week is enough.

It would also be very nice to test ScalableTestGrids, to see if and to which extent it can benefit from the array-preserving frontend and backend. This requires to activate the `-d=mergeComponents,nonfScalarize` frontend flags: the first merges individual instances of the same class with the same kind of modifiers into an array, while the latter preserves the array. I guess the latter is maybe implicitly activated by --newBackend, but the first one would need to be added in vendor annotations. @kabdelhak please let me know about that.

If we can demostrate O(1) code generation time on ScalableTestGrids, this would be a big deal for RTE.

**Comment by casella** [comment]
@kabdelhak maybe you can also comment about which flags you actually need, is it just `--newBackend`?

**Comment by kabdelhak** [comment]
I would like to only test with `--newBackend` actually. It already also activates `-d=-nfScalarize,arrayConnect` by default because it should never be run without. What exactly does `-d=mergeComponents` do?

**Comment by kabdelhak** [comment]
We now do have a test job for the NB so i will close this.

**Comment by casella** [comment]
I would have just called it newBackend, since the old FE is now obsolete (except for bootstrapping).

**Comment by perost** [comment]
> I just checked https://libraries.openmodelica.org/branches/newInst-newBackend/Modelica_4.0.0/Modelica_4.0.0.html, but it is still showing one month old results. How often is this new test ran?

Don't know, but all library testing has been broken for two weeks now.

>     * I do not understand why one third of models fail during flattening. With the regular test job, [100% of MSL 4.0.0](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) pass the frontend.

Because it uses `-d=-nfScalarize,arrayConnect`. Turning of scalarization doesn't work in many cases, and the array connection handling scales very badly and causes some models to timeout. I'm actually surprised that so many models work with those flags.

**Comment by casella** [comment]
> > I do not understand why one third of models fail during flattening. With the regular test job, [100% of MSL 4.0.0](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) pass the frontend.
> 
> Because it uses `-d=-nfScalarize,arrayConnect`.

Sure, that is implicitly turned on by --newBackend, I only realized it now.
