### ISSUE TITLE
DynamicSelect does not survive inheritance

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#8607]
I see that DynamicSelect does not survive inheritance apparently - maybe the variable lookup fails in an inherited class?
Simulate the following model:
```
model Dyamicselect_OM_3675
  model DSBase
  Modelica.Units.SI.MassFlowRate Val;
  equation
    Val = 42 + 10* time;
  
  annotation(
      Icon(graphics = {Text(origin = {-8, 35}, extent = {{-66, 39}, {66, -39}}, textString = DynamicSelect("static", String(Val))), Text(origin = {0, 120}, extent = {{-100, 20}, {100, -20}}, textString = "%name")}));
  end DSBase;

  model DSDerived
    extends Dyamicselect_OM_3675.DSBase;
  equation

  end DSDerived;

  Dyamicselect_OM_3675.DSBase dSBase annotation(
    Placement(visible = true, transformation(origin = {-22, 60}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Dyamicselect_OM_3675.DSDerived dSDerived annotation(
    Placement(visible = true, transformation(origin = {-22, 26}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

end Dyamicselect_OM_3675;
```
Observe in the plotting perspective, diagram view, that the text of `dSBase` changes with time as expected, but `dSDerived` erroneously shows `static`.
* OpenModelica Version: OpenModelica v1.19.0-dev-624-g164b90d287 (64-bit)
* OS: Windows 10, 64 bit

cf. also #8593

_Originally posted by @bilderbuchi in https://github.com/OpenModelica/OpenModelica/issues/3675#issuecomment-1047739506_

**Comment by casella** [comment]
I guess this case will be handled correctly once #8425 is implemented.

**Comment by adeas31** [comment]
Not really. I am working on a fix. Hope to get it done today.

**Comment by casella** [comment]
> Not really. I am working on a fix. Hope to get it done today.

Very good, thanks!

**Comment by bilderbuchi** [comment]
Thanks for the fix, confirmed working!
