### ISSUE TITLE
Pretty-Printing algorithm being called after deleting components in OMEdit v1.18.1

### ISSUE THREAD

**Issue by mjschuh** [OpenModelica/OpenModelica#8635]
### Description
Pretty Printing is triggered by deleting two components which causes unwanted loss of code formatting.

### Steps to reproduce
Delete FlowResDepChamIn and FlowResPreChamOut in the attached [PrettyPrintingTest.mo.txt](https://github.com/OpenModelica/OpenModelica/files/8181089/PrettyPrintingTest.mo.txt) model to trigger OMEdit calling the Pretty Printing algorithm which reformats the source code.

![2022-03-03_pretty_printing](https://user-images.githubusercontent.com/24213026/156651431-e8ea5c62-7caa-40ef-a022-322a1695cf93.png)

### Desired behavior
What can I do to prevent the pretty printing algorithm from being used when I don't want it used?

### Version and OS
 - OpenModelica v1.18.1 (64-bit)
 - OS: Windows 10, 64 bit

Thanks,  Michael

**Comment by bilderbuchi** [comment]
This is especially annoying when one tries to get good indentation of parameters to avoid exorbitant line lengths, and adds comments to those parameters, as the pretty-printing algorithm puts all those comments after the component definition.

**Comment by casella** [comment]
@mjschuh unfortunately there is no way to disable the pretty-printing algorithm. The models with which you interact in the GUI are contained in OMC's memory as abstract syntax trees, without any formatting. Whenever you add or remove some stuff, a diff algorithm is run to figure out what changed, and then the original source code is only changed where it really matters, while leaving all the existing formatting intact.

This diff algorithm has been improved over time, but it still has some issues, and it sometimes fail. When it does, the only way to reconstruct the textual Modelica code from the AST in memory is to use the built-in pretty-printing algorithm.

**Comment by mjschuh** [comment]
Thank you @casella for explaining why pretty-printing is called.

From trial and error testing, I have found that pretty-printing is triggered by what look like innocuous comments in my code.  Is there any logging that shows what triggered the pretty-printing?  If so, perhaps I could use the logging output to figure out how to write comments that work better with pretty-printing.

Thanks, Michael

**Comment by casella** [comment]
@mjschuh, go to Tools | Open Temporary Directory, then open the `omeditcommunication.log` file, where all communication between OMEdit and OMC is logged. 

On Windows unfortunately there is a significant time delay before the communication buffer is flushed to the file, so you may need to do something extra to eventually see what you are interested into in the file. Anyway, every API call is timestamped, so you should be able to figure out what happens when.

**Comment by mjschuh** [comment]
Thank you @casella for your help with the log files.  I will give what you said a try.

**Comment by mjschuh** [comment]
I took another look at my test case and I found that the <code>// 72000 seconds</code> comment following the <code>connect(DepositionHeatExchanger.port_tubes_a, flowResDepChamOut.port_b)</code> statement and before the <code>annotation</code> statement is causing the Pretty Printing algorithm to be called after the FlowResDepChamIn and FlowResPreChamOut models in [PrettyPrintingTest.mo.txt](https://github.com/OpenModelica/OpenModelica/files/8181089/PrettyPrintingTest.mo.txt) are deleted.  Pretty Printing is not called if the <code>// 72000 seconds</code> comment on line 676 is deleted before deleting the FlowResDepChamIn and FlowResPreChamOut models.

<pre>
    674     connect(flowResDepChamOut.port_a, depositionChamber.port_b) annotation(
    675       Line(points = {{66, -60}, {80, -60}, {80, -44}, {72, -44}}, color = {0, 127, 255}));
    676 // 72000 seconds
    677     annotation(
    678       Documentation(info = "<html>
</pre>

Maybe I missed it, but I did not find anything helpful in the <code>omeditcommunication.log</code> file that would help me figure out what is causing Pretty Printing to be called.  I did find what looks like a copy my Modelica source code with the formatting that existed right before Pretty Printing was called.  This could be really helpful for recovering from future unwanted Pretty Printing.

**Comment by bilderbuchi** [comment]
> This could be really helpful for recovering from future unwanted Pretty Printing calls.

For this, I recommend having your project under version control, and having a good handle on its status. It's probably going to be easier to git-revert a change than digging through log files. 😃

**Comment by casella** [comment]
@sjoelund any idea why that comment should cause the diff algorithm to fail?

**Comment by casella** [comment]
After fixes by @sjoelund to the diff algorithm, deleting those two components no longer causes pretty-printing to be called.

Tested with OpenModelica `v1.20.0-dev-305-geb5e7e0a95`.

**Comment by mjschuh** [comment]
I tried OpenModelica v1.20.0-dev-345 and verified that the comment no longer causes the diff algorithm to fail.  Thank you @sjoelund and @casella fixing this Pretty Printing problem!
