### ISSUE TITLE
Large regression on cpp version of library testsuite

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8648]
### Description

Please check this regression report https://libraries.openmodelica.org/branches/history/cpp/2022-02-15%2020:59:29..2022-02-16%2020:59:19.html. There are almost 500 models breaking.

Unfortunately there are many commits in there
<html><body>

 git hash | author | description
-- | -- | --
~~9bca51e40d~~ | ~~phannebohm~~ | ~~[janitor] Remove unnecessary wrapper (#8566)~~
**_2590823b62_** | **Lennart Ochel** | **_Only literal constants qualify as initial=exact (#8557)_**
~~75c31ea6cd~~ | ~~Lennart Ochel~~ | ~~Return default start value according to type (#8558)~~
~~3e9e9f81ce~~ | ~~perost~~ | ~~Fix simplification of `array or array` (#8559)~~
~~83634b05b2~~ | ~~perost~~ | ~~Improve checking of protected modifications (#8556)~~
~~b1522d89fc~~ | ~~Lennart Ochel~~ | ~~Make cse variables parameters that are added to globalKnownVars (#8551)~~
~~0897872ac1~~ | ~~Mahder Gebremedhin~~ | ~~Update PATH with library dirs before system calls. (#8552)~~

<h2></h2>
</body>

Not sure which one(s) is the culprit. We should definitely investigate this and fix it before 1.19.0. At least identify which is the offending commit and roll it back temporarily for the 1.19.0 branch-off.

**Comment by casella** [comment]
Notsure if #8649 is relevant, in fact 11b99d95] generated an additional [73 regressions](https://libraries.openmodelica.org/branches/history/cpp/2022-02-16%2020:59:19..2022-02-17%2020:55:08.html).

**Comment by casella** [comment]
@adrpo, can you check them one by one? I guess the ones by @lochel are the most probable candidates.

**Comment by adrpo** [comment]
Commit 0897872ac1 works fine.

**Comment by adrpo** [comment]
Commit b1522d89fc works fine.

**Comment by adrpo** [comment]
Commit 75c31ea6cd works fine.

**Comment by adrpo** [comment]
Commit 2590823b62 is the bad one!

**Comment by lochel** [comment]
Thanks @adrpo. I'll look into it.

**Comment by lochel** [comment]
I hope that #8649 fixes the issue for the cpp runtime. It is, however, a bit odd to handle these things differently for the c and cpp runtimes. I would expect that the modelDescription.xml should be identical for both targets.

**Comment by casella** [comment]
@lochel I checked #8649 but it is not clear to me what the difference in the two .xml file would be. Could you briefly comment on that and/or add a simple example here? Thanks!

**Comment by casella** [comment]
It seems that most (if not all) regressions were fixed, see [the regression report](https://libraries.openmodelica.org/branches/history/cpp/2022-03-24%2020:55:16..2022-03-25%2020:54:50.html).

@rfranke, the comparison of cpp runtime performance on the library testsuite between [master and v. 1.18.1](https://libraries.openmodelica.org/branches/overview-c++.html) is now largely positive, there are a few regressions but they are apparently not related to the cpp runtime.
