### ISSUE TITLE
Instanciation issue when using inner/outer connectors

### ISSUE THREAD

**Issue by TMitard** [OpenModelica/OpenModelica#8667]
Hey, I just encountered a problem when using the inner/outer keywords with connectors.

I have written two simple models involving a connector on one side and a Real parameter on the other.
![Models](https://user-images.githubusercontent.com/101272756/157471212-bdb445b4-4f73-4187-ace5-bf4c7e288051.png)

The one with the Real parameter is instanciated correctly (compiles and simulates as well) whereas the other seems to have a problem: the outer connector in the child class is kept rather than being replaced. Hence, I get an unbalanced variables-to-equations ratio and the model wont compile.
![InstanciatedModels](https://user-images.githubusercontent.com/101272756/157471242-e855a4c8-1e6c-4a05-92ad-99df74376f56.png)

Is it a mistake of mine or is it a bug? Files and pictures are attached if someone needs them.

 - OpenModelica Version: v1.18.0 (64-bit)
 - Windows 10 (64 bit)

Thanks!
[Modelica_BugReporting_InnerOuterConnector.zip](https://github.com/OpenModelica/OpenModelica/files/8215860/Modelica_BugReporting_InnerOuterConnector.zip)

**Comment by perost** [comment]
Fixed in #8668, the `outer` attribute was mistakenly overwritten on components in some specific cases.

**Comment by TMitard** [comment]
Nice! When will an OpenModelica version resolving this issue be available? Should I download the next nightly build?

**Comment by perost** [comment]
> Nice! When will an OpenModelica version resolving this issue be available? Should I download the next nightly build?

Yes, my PR should be merged in 20-30 min unless something goes wrong, in which case it will be in the next nightly build. This issue will be closed automatically when my PR is merged.

**Comment by casella** [comment]
@TMitard, please note that according to the rules of [Section 4.7](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#balanced-models) of the Modelica specification, the RealConn connector is not balanced. OMC currently does not check that, but in general unbalanced connectors can easily lead to unbalanced system models.

**Comment by TMitard** [comment]
@casella, after having read the provided section of the Modelica specification, I am not sure to understand your point, could you clarify please? Does it mean that I am missing an equation or something? Is it because I didn't include neither the 'input' or 'output' keywords? Thanks.

**Comment by casella** [comment]
> Is it because I didn't include neither the 'input' or 'output' keywords? Thanks.

Exactly. The complete rules for balanced connectors are quite involved, but basically every variable which is not input, output, or flow must have a corresponding flow variable, which is not the case in your example.

**Comment by TMitard** [comment]
@casella, I see. How would be the proper way to define a bi-directional real connector then?

**Comment by casella** [comment]
I'm not sure what you mean by bi-directional Real connector. I guess you may define something like:
```modelica
connector conn_in
  input Real y;
end conn_in;

connector conn_out
  output Real y;
end conn_out;
```
and use them wherevere appropriate. When checking for balancedness, the input variable counts as an extra equation. The rule is that there must be exactly one output variable in each connection set.

**Comment by TMitard** [comment]
Yes, sure. On my side I would like to have a behavior similar to physical connectors (those used in the common electrical, mechanical, etx. libraries) where there is a couple across + through variables. What I mean by bi-directional connector would then correspond to a physical connector with an across variable only, neither involving the 'input' nor 'ouput' keywords.

Nonetheless, I totally get that equations must be balanced for the solver to find a solution. Maybe this kind of behavior cannot be acheived. Let me know your thoughts @casella !

**Comment by TMitard** [comment]
You may view it as a thought experiment. Actually a use case could be a model linking its connectors through equations but the resolving of each connector being whether an input or an output will be defined by its context, that is, by the models connected to it in this very implementation. Also meaning that in a different context, a connector which was resolved to an input, may now be resolved to an output. Hence the need for a connector that can handle either connection. Another use case could be some numerical component were information can be sent or received through a single connector but, contrarily to physical connectors, nothing is actually flowing. Then we would need only an across variable without a through one.

These two use case may very well have two different solutions but that's the general idea !

**Comment by casella** [comment]
The problem with such models is that in general you won't be able to guarantee that the overall system will be balanced. Hence, they were forbidden since Modelica 3.0, which introduced the concept of balanced components. The idea of balanced components is that no matter how you connect them, you always get a balanced system, which is of course a very nice property to avoid headaches, such as finding out where it the missing equation in a model with 13429 variables and 13428 equations.

In fact, you can still use unbalanced components; if the system model is balanced the compiler won't bother, but if it isn't, you're on your own.

**Comment by TMitard** [comment]
I see, this links your previous answers with one another. And all of this is perfectly clear now. It is true that this is a great feature and I'll try to leverage it from now on. Anyway, thanks for your time and your detailed answers !
