### ISSUE TITLE
Remove "Keep using new front-end" dialog when the flattening fails

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8670]
### Description

Currently, when the flattening of a model fails, we open a dialog asking the user if he wants to try with the old front-end. This was introduced in 1.16.0 when the new front-end was good enough (and much faster) in most cases, but still failed in a significant number of cases. This is now completely obsolete, as the new front-end performs much better than the old one in all cases. 

### Steps to Reproduce

Simulate this model in OMEdit
```
model M
  Real x = "2";
end M;
```
### Expected Behavior

The compilation should just fail with the appropriate error message

**Comment by adeas31** [comment]
See #8663
