### ISSUE TITLE
OMEdit not responding if info documentation editor has unsaved document

### ISSUE THREAD

**Issue by sergniko** [OpenModelica/OpenModelica#8723]
### Description

If you edit info documentation in Document browser and didn't save you data OMedit  stops responding and eventually consumes all available RAM.

### Steps to Reproduce

1. Create new model.
2. Place some block (I used **Modelica.Mechanics.Translational.Components.Mass** **mass**)
3. In Document browser press Edit info documentation button. 
4. Add some text to info. Do not press Save.
5. In model window switch to text view
6. Insert some valid code (I used **connect(mass.flange_a,mass.flange_b);** )
7. While adding code notice what code completion is not working (no suggestions for **mass**)
8. Press **Save a file** button in main window - progress bar is shown and OMEdit stops responding. All free memory is gone.

### Expected Behavior

I expect what file saves normally. 
Or some error message if this is not allowed.

### Version and OS

 - OpenModelica Version: Connected to OpenModelica v1.18.1 (64-bit)
 - OS: Windows 10, 64 bit
 - Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

### Additional Context

Same behavior can be obtaine if you :
1. open some of you models
2. Press **edit info documentation** in Document browser. 
3. In Text view change code to other valid code (delete some line for example ) and press save. It will also stop responding.
If you change code to something invalid - with pressing **Save** a warning message will pops up to revert changes.

**Comment by casella** [comment]
@adeas31 I guess we should save it as soon as we switch the context, what do you think?
