### ISSUE TITLE
Start values of enumeration with new front end

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OpenModelica#8743]
The model [simulation/modelica/initialization/parameters.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/simulation/modelica/initialization/parameters.mos) from the testsuite produces wrong start values for enumerations with the new frontend. @perost, I am rather certain that it isn't directly a problem with the frontend itself. It probably just generates slightly different input to the backend.

@hkiel recently fixed start values for enumeration in #8589.

https://github.com/OpenModelica/OpenModelica/blob/8b2625358d66c18e3acfd8d43661b27e26b1a7ec/testsuite/simulation/modelica/initialization/parameters.mos#L10-L31

**Comment by perost** [comment]
The difference was that the OF always creates `DAE.VariableAttributes` for variables even if they have no attributes, while the NF just sets it to `NONE()` in that case to save memory. `DAEUtil.getStartAttr` didn't take that into account and just returned `0.0` for any variable lacking attributes.

**Comment by lochel** [comment]
@perost thanks for the quick fix 👍
