### ISSUE TITLE
Fix upgrade/update library menu

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8757]
@adeas31, regarding #8724 I am really sorry, I misunderstood the upgrade/update issue completely.

I previously understood there were just two actions (update index and install newest version), but now I understand there are _three_ possible actions:
- updatePackageIndex() just updates the index, syncing with the OSMC server, but does not download (install) anything
- upgradeInstalledPackages(installNewestVersions = true) downloads and install only the latest (newest) versions for each library. This is the default, so you get the same by calling upgradeInstalledPackages()
- upgradeInstalledPackages(installNewestVersions = false) downloads and install all newer versions for each library. This is the default, so you get the same by calling upgradeInstalledPackages()

@sjoelund, is that correct? Maybe it would be good to add a line of explanation of the meaning of installNewstVersions in the [API documentation](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.upgradeInstalledPackages.html). 

> OMEdit calls updatePackageIndex() when a new package is installed or whenever needed without letting the user know. 

I see. This could be a bit dangerous if there are network problems, because either OMEdit hangs without the user knowing why, or the index is actually not updated, but the user is not aware of that (maybe a cable was accidentally disconnected, or something)

Besides, only performing updatePackageIndex() doesn't really make much sense.

I would propose the following solution
- change back File | Update installed libraries to File | Upgrade installed libraries (sorry about that...)
- when this option is invoked, pop up a window, display a message "Updating library index", and call updatePackageIndex()
- if updatePackageIndex() does not return because of bad internet connection, display "Cannot connect to server" and a Close button
- if it returns but there are no new packages, display "No new versions available" and a Close button
- if it returns and there are new packages, display "New versions available" (it would be nice to actually list them explicitly), then provide two buttons "Install all new versions" and "Install newest versions only", that call the corresponding upgrade functions

@sjoelund does this make sense to you?

**Comment by adeas31** [comment]
> if it returns but there are no new packages, display "No new versions available" and a Close button
> if it returns and there are new packages, display "New versions available" (it would be nice to actually list them explicitly), then provide two buttons "Install all new versions" and "Install newest versions only", that call the corresponding upgrade functions

I believe we need a new API for this.  Alternatively I can check the index.json file to look for new versions but then this is only possible from OMEdit and not from command line interface.

**Comment by casella** [comment]
> Alternatively I can check the index.json file to look for new versions but then this is only possible from OMEdit and not from command line interface.

That would be fine. From the CLI one should directly use the package manager API functions.

**Comment by casella** [comment]
LGTM, I'll try this out tomorrow with the next nightly build.

One question only: I assume that the updatePackageIndex automatic action is carried out by a non-blocking thread, much as, e.g., the update of the New Item. Otherwise it could be very annoying if one had to wait for that to take place if you don't have the intention of updating/installing any library (which is the case 99.9% of the times you start and OMEdit session). Is that the case?

**Comment by sjoelund** [comment]
That's not the case if you use the API :)

**Comment by adeas31** [comment]
> Otherwise it could be very annoying if one had to wait for that to take place if you don't have the intention of updating/installing any library (which is the case 99.9% of the times you start and OMEdit session).

It will only be called if you want to update/install the library.

**Comment by casella** [comment]
OK, looks good. Will test it ASAP.
