### ISSUE TITLE
Add more units to parameter input drop-down menus

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8758]
The current behaviour of unit drop-down menus in parameter editing windows is the following
- if only the unit attribute is specified, that unit only is made available
- if also a displayUnit attribute is specified, then the drop-down menu allows to chose between that and the unit attribute

This is unnecessarily restrictive. In particular, it prevents using multiples of SI units if a displayUnit attribute is not set in the library. 

On the other hand, putting all compatible units in the drop-down menu is not a good idea, because you get dimensionally equivalent units that make no sense, e.g. Bq together with Hz (both are s^-1), see [#4031](https://trac.openmodelica.org/OpenModelica/ticket/4031).

I would propose that for all the units for which we automatically set multiple prefix (see e.g. [here](https://github.com/OpenModelica/OpenModelica/issues/8584#issuecomment-1057828875)), we build the drop-down menu as follows: first the displayUnit (if defined), then the unit, then all multiples of the unit from the smallest to the largest one. Maybe we can skip the ones smaller than pico and larger than Tera, I never saw them in applications except for measuring memory size and would really look odd in most cases.

Additionally, if possible I would add an extra rule that whenever unit = "K", we also add "degC" even if it is not defined as displayUnits.

You can use S.m in the attached package for testing. 
[TestUnits.mo.txt](https://github.com/OpenModelica/OpenModelica/files/8346545/TestUnits.mo.txt)

This would fix [#4796](https://trac.openmodelica.org/OpenModelica/ticket/4796), which has been there for a while.

**Comment by bilderbuchi** [comment]
What do you think about also showing compatible imperial units? This would be useful if your model parameters are in SI (e.g. meters), but you are in the unfortunate situation that your data is imperial (e.g. dimensions in inch).

**Comment by casella** [comment]
That would be possible, but it may have some pitfalls. I'd keep it for 1.20.0

**Comment by casella** [comment]
@adeas31 could you have a look at this by the end of this week? Thanks!

**Comment by casella** [comment]
@adeas31 could you take care of this before the final release? This should be fairly straightforward to implement. Thanks!

**Comment by casella** [comment]
Agreed with @adeas31 to put this in the final 1.19.0-beta.5

**Comment by casella** [comment]
I'll check this in 1.19.0-dev.beta5 when available

**Comment by casella** [comment]
Looks good also in 1.19.0-dev.beta5
