### ISSUE TITLE
Simulation process failed if an initialization file specified

### ISSUE THREAD

**Issue by sergniko** [OpenModelica/OpenModelica#8765]
### Description

If you set an **Equation System Initialization File** with Browse... button in **Simulation Flags** tab an "unable to read input-file" error is produced and simulation process failed.

### Steps to Reproduce
1. Open Simulation Flags tab and press Browse... button
2. Select a file - notice a full path is shown
3. Start simulation
4. After compilation a model *.exe starts with -iif=C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/gue108_3/gue108_3_init.mat command line option.
5.In **Output tab** an error produced:
 `An unable to read input-file <C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/gue108_3/C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/gue108_3/gue108_3_init.mat> [Invalid argument]`
6. Note that full path of selected file is appended to inputPath
7. If only a filename specified - simulation runs normally.
### Expected Behavior

I expect I can select a file in any directory not only in inputPath

### Version and OS

 - OpenModelica Version: Connected to OpenModelica v1.18.1 (64-bit)
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
@sergniko, are you sure the *** path does not contain non-ASCII characters?

**Comment by adeas31** [comment]
git blame says,

```
adeas31@win01283 MINGW64 /C/OpenModelica
# git blame OMCompiler/SimulationRuntime/c/simulation/simulation_runtime.cpp -L 545,547
fdbbc4c1fcc (Andreas 2020-06-30 12:19:37 +0200 545)     if (omc_flag[FLAG_INPUT_PATH]) {
fdbbc4c1fcc (Andreas 2020-06-30 12:19:37 +0200 546)       const char *tmp_filename;
fdbbc4c1fcc (Andreas 2020-06-30 12:19:37 +0200 547)       if (0 > GC_asprintf(&tmp_filename, "%s/%s", omc_flagValue[FLAG_INPUT_PATH], omc_flagValue[FLAG_IIF])) {
```

@AnHeuermann I think you assume the `FLAG_IIF` path is relative. It could be relative and in that case your code is correct. But at the same time it could be absolute path as well. So you need to check for both.

**Comment by AnHeuermann** [comment]
Yeah, we should use a function to convert the flag value into an absolute path and then check if that file does exist. So we ware independent of relative or absolute paths.
