### ISSUE TITLE
OMEdit cannot load large result file

### ISSUE THREAD

**Issue by sergniko** [OpenModelica/OpenModelica#8766]
### Description

It seems that OMEdit cannot load a result file with size over ~2Gb. It produces `Corrupt header: data_2 matrix` error.

### Steps to Reproduce

1. Create some model with many variables. Easiest way is to use Modelica.Fluid.Pipes.DynamicPipe and increase a number of nNodes.
2. Simulate with small interval (1e-5 for example). 
3. The simulation finished successfully.
4. Ensure that resulting file is more than 2Gb. (for example: 2741 variable, 100000 intrevals - results in 2 490 008 083 bytes of *.mat file)
5. Plot any variable - an `Corrupt header: data_2 matrix` error.
### Expected Behavior

I expect results of successfull simulation to load or a warning that results file cannot be read but before simulation starts.

### Version and OS

 - OpenModelica Version: Connected to OpenModelica v1.18.1 (64-bit)
 - OS: Windows 10, 64 bit

### Additional Context

If results file less than 2G - all works fine. For example 1,7G - loads normally.
Maybe some issues with 2^32 for **int** datatype?

**Comment by casella** [comment]
Maybe a problem with the .mat format itself? See https://www.google.com/search?client=firefox-b-d&q=.mat+file+matlab+max+size

**Comment by sergniko** [comment]
Other option doesn't work well for me:
plt - Process crashed
csv - almost 3 times bigger file (863M vs 352M *.mat) and OMEdit very slow on csv - several seconds (with "not responding" in window header) to plot one variable.

**Comment by sergniko** [comment]
> Perhaps use a variable filter to reduce the size of the result file. `Simulation Setup->Output->Variable Filter`.

I don't know how this feature works. Can't find it in User Manual. Is it working same as filter in variable browser?

**Comment by sergniko** [comment]
> No, this is not same as filter in variable browser.
> 
> You go to `Simulation Setup->Output`, set the `Variable Filter` and then simulate your model. In this way only the variables that passes the variable filter will be added to the result file. `Variable Filter` is a regular expression.

I've tried, but it didn't work for me.

For example I've opened `Modelica.Mechanics.Translational.Examples.Damper `  and in  `Simulation Setup->Output`, set the `Variable Filter` to `mass.*`.  I expect in results to get only mass1 mass2 mass3.  But I got all variables as for not setting filter at all.

**Comment by casella** [comment]
It seems that the variable filter option of the interactive environment is broken. I tried this test script:
```
loadModel(Modelica);getErrorString();
simulate(Modelica.Blocks.Examples.Filter, variableFilter="Bessel");getErrorString();
```
I would expect only the results of the Bessel filter to be included in the .mat file, but when I load it with OMEdit, I get the full set of variables.

**Comment by adeas31** [comment]
See what is the value of `variableFilter` in the `model_init.xml` file.

**Comment by adeas31** [comment]
I just tested this. `variableFilter` is working fine. The reason you see all the variables listed in Variables Browser is because they are read from `model_init.xml` file. Note that you will only see the checkbox next to the parameters or filtered variables. The rest of them are there so they can be possibly used for re-simulation. This is the intended behavior.

**Comment by adeas31** [comment]
@sergniko if you test this on your model you will note that the size of the result file is a lot smaller.

**Comment by casella** [comment]
> I just tested this. `variableFilter` is working fine. The reason you see all the variables listed in Variables Browser is because they are read from `model_init.xml` file. Note that you will only see the checkbox next to the parameters or filtered variables. The rest of them are there so they can be possibly used for re-simulation. This is the intended behavior.

Aha, I missed that. Now that you mention it, I have a sense of dejà-vù, see [#4898](https://trac.openmodelica.org/OpenModelica/ticket/4898)

> @sergniko if you test this on your model you will note that the size of the result file is a lot smaller.

I should have also noticed, that, but the file explore window was clipped, so I couldn't see the file size.

The original issue (file size limited to 2 GB) is still valid, but not that urgent. However, the documentation of this feature is really poor, see #8839

**Comment by sergniko** [comment]
> @sergniko if you test this on your model you will note that the size of the result file is a lot smaller.

Yes, it really helps.  Thank you for your help.
I think adding simple warning message in case of results file bigger that 2Gb will be fine.

**Comment by casella** [comment]
> Yes, it really helps. Thank you for your help. I think adding simple warning message in case of results file bigger that 2Gb will be fine.

@AnHeuermann, @sjoelund, @adrpo are we keeping track of the size of the .mat file as we write data into it? In that case, this would be doable.

**Comment by marcusfuchs** [comment]
Just to throw in my perspective: For our use cases it would really help if loading result files larger than 2 GB would be possible. We have several models which simulate a whole year with 5 - 15 minute steps and even if we only save the variables we need the result will be larger than 2 GB.

**Comment by casella** [comment]
I understand this is a problem of the Matlab-based file format that we use. You can try CSV output, and possibly limit the number of output variables using the output variable filter

**Comment by perost** [comment]
> Maybe a problem with the .mat format itself? See https://www.google.com/search?client=firefox-b-d&q=.mat+file+matlab+max+size

https://www.mathworks.com/help/matlab/import_export/mat-file-versions.html only lists size limits _per variable_, so the 2 GB limit should be per variable and not per file (it explicitly says "The maximum size of a MAT-file is imposed only by your native file system"). So this is likely an issue with our code rather than with the .mat format itself.

**Comment by sjoelund** [comment]
All time-varying variables are stored in the same table=variable though

**Comment by BasilioPV** [comment]
I have produced 6GB of .mat file output and opened with with MC's PLOTXY software, the data is ok inside:
http://ceraolo-plotxy.ing.unipi.it/default.htm

On the other hand, protected variable output are always writeen on .mat file with strange behaviour using this checkbox option, see #10707.

Filters don't work to reduce .mat file, see #10708

**Comment by casella** [comment]
> I have produced 6GB of .mat file output and opened with with MC's PLOTXY software, the data is ok inside: http://ceraolo-plotxy.ing.unipi.it/default.htm

@adeas31 then I guess we need to have another look at how we load those .mat files. Maybe there is some issue with 32-bit pointers or 32-bit integers that must be converted to 64-bit ones.

What code are we currently using to load those .mat files into OMEdit?

**Comment by bilderbuchi** [comment]
Considering a current Matlab file is basically HDF5 already, would it be realistic/an "easily" achievable option to get HDF5 result file export/import, and would that enable larger result files? I think this is already #5180 but the trac server seems offline so can't read more.

**Comment by sjoelund** [comment]
> Considering a current Matlab file is basically HDF5 already, would it be realistic/an "easily" achievable option to get HDF5 result file export/import, and would that enable larger result files?

That would be an alternative, but someone would need to define the hdf5 schema and then program all the tools to export/import that. And ideally, the format would be the same in all Modelica tools.

> I think this is already #5180 but the trac server seems offline so can't read more.

The server is not offline. The ISP removed IPv4 from DHCP, so you'll need IPv6 to the server until they fix that...

**Comment by bilderbuchi** [comment]
> That would be an alternative, but someone would need to define the hdf5 schema and then program all the tools to export/import that. And ideally, the format would be the same in all Modelica tools.

Ha, perhaps unsurprisingly there's some previous work from 2012 (http://www.ep.liu.se/ecp/076/050/ecp12076050.pdf) and a tangentially related specification discussion: https://github.com/modelica/ModelicaSpecification/issues/2207 :-)

**Comment by sjoelund** [comment]
> Ha, perhaps unsurprisingly there's some previous work from 2012 (http://www.ep.liu.se/ecp/076/050/ecp12076050.pdf) including schema work, and a tangentially related specification discussion: [modelica/ModelicaSpecification#2207](https://github.com/modelica/ModelicaSpecification/issues/2207) But yeah, I see we are not going to resolve that in here. :-)

And I seem to remember a working group to try to standardize it, that didn't lead anywhere :(

**Comment by ceraolo** [comment]
A very simple file that creates a mat file 2.3 GB in sizse, that cannot be read by OMEdit:
```
model test
  Modelica.Blocks.Sources.Sine sine[1000](each f = 50) annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.FirstOrder firstOrder[1000] annotation(
    Placement(visible = true, transformation(origin = {42, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(sine.y, firstOrder.u) annotation(
    Line(points = {{11, 0}, {29, 0}}, color = {0, 0, 127}));
  annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime = 0, StopTime = 100, Tolerance = 1e-06, Interval = 0.001),
    Diagram(coordinateSystem(extent = {{-20, 20}, {60, -20}})),
    version = "");
end test;

```
OMEdit complains that the data file is corrupt, while it should not, as it is correctly ready by PlotXY:
http://ceraolo-plotxy.ing.unipi.it/default.htm

The code PlotXY uses to read modelica mat files is here:
https://github.com/max-privato/PlotXY_OpenSource/blob/master/CSimOut.cpp

at rows 116-391 (unfortunately comments are in Italian language)

**Comment by ceraolo** [comment]
What is really strange is that even Matlab itself cannnot read this file.
![image](https://github.com/OpenModelica/OpenModelica/assets/7373030/e1545db8-3072-428a-9236-c2b063be6756)

**Comment by casella** [comment]
> Considering a current Matlab file is basically HDF5 already, would it be realistic/an "easily" achievable option to get HDF5 result file export/import, and would that enable larger result files? I think this is already #5180 but the trac server seems offline so can't read more.

Trac is back from the dead now. And yes, we may consider HDF5, though there are some details about how to efficiently store aliases and constant results that should be defined. The current .mat format is basically using the de-facto standard, i.e. the Dymola output format.

**Comment by casella** [comment]
It seem that there is a 7.3 MAT file format, that allows to overcome the 2 GB limit, see https://www.mathworks.com/help/matlab/large-mat-files.html

Maybe we should just go for that, until the Modelica Association comes up with something better, based on open standards such as HDF5.

**Comment by sjoelund** [comment]
Matlab 7.3 is also called... HDF5 :)

Still doesn't change the fact that you need to implement the file writer, import, and plotting

**Comment by ceraolo** [comment]
However, in the wait for a "more general, more effective" standard, one can actually read very easily mat files currently created by OM and Dymola, beyond the 2GB barrier, using a few rows such as those I mentioned earlier.

**Comment by casella** [comment]
> Matlab 7.3 is... HDF5 :)

Ah, ok :)

**Comment by bilderbuchi** [comment]
> Still doesn't change the fact that you need to implement the file writer, import, and plotting

With this I assume you mean the data model/schema/structure of the file, and the mapping to OMEdit's internal representation, right? OM already ships libhdf5, so file writing/reading should not be a problem (however, see #10583).

**Comment by BasilioPV** [comment]
> However, in the wait for a "more general, more effective" standard, one can actually read very easily mat files currently created by OM and Dymola, beyond the 2GB barrier, using a few rows such as those I mentioned earlier.
> 
> That code was created doing reverse-engineering on Dymola and Openmodelica outputs

I vote this, remove the 2GB barrier while a "general solution" is not agreed.

**Comment by casella** [comment]
If anybody here knows how to remove the 2GB barrier in the OMEdit code, please go ahead with a PR, there's no reason we should not accept it even if it's not "standard".

If you want to restart the discussion on HDF5 or netcdf 4 standards at the Modelica Association level, we can also do that. It's hard work and requires perserverance, but eventually you'll get results and the whole community will benefit.

**Comment by casella** [comment]
> In OMEdit, it probably uses a signed integer instead of size_t somewhere

That should be easy to spot and fix.

**Comment by sjoelund** [comment]
The actual file format seems to use long. But that's 2 billion elements, so the file should be possible to be much larger (8-byte for long, time and a variable should be around 32GB that it has a problem). But the size variable might be coded differently and the multiplication broken

**Comment by adeas31** [comment]
> In OMEdit, it probably uses a signed integer instead of size_t somewhere

It might be that there are some issues in OMEdit. But I think we first need to fix the `ModelicaMatReader`.

```
loadString("model test
  Modelica.Blocks.Sources.Sine sine[1000](each f = 50) annotation(
    Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.FirstOrder firstOrder[1000] annotation(
    Placement(visible = true, transformation(origin = {42, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(sine.y, firstOrder.u) annotation(
    Line(points = {{11, 0}, {29, 0}}, color = {0, 0, 127}));
  annotation(
    uses(Modelica(version = \"4.0.0\")),
    experiment(StartTime = 0, StopTime = 100, Tolerance = 1e-06, Interval = 0.001),
    Diagram(coordinateSystem(extent = {{-20, 20}, {60, -20}})));
end test;");
getErrorString();
simulate(test);
getErrorString();
readSimulationResultVars("test_res.mat");
getErrorString();

```

With the above script I get the error,

`Error: Failed to open simulation result test_res.mat: Corrupt header: data_2 matrix`

**Comment by sjoelund** [comment]
It works just fine for me on Linux, but perhaps you need to cast the sizes to size_t to int64_t on Windows in order to make the multiplication work? Or maybe it is the fseek command that fails and Windows needs to use a different file API to support >31-bit length files?

**Comment by adeas31** [comment]
With #10739 I successfully tested result file of size 7GB.

**Comment by casella** [comment]
I would then suggest to merge this on master. I see no counter-indications to that. If and when the MA agrees on a HDF5 format, we will of course support that.
