### ISSUE TITLE
Add dictionary of variable names to output of linearize() function when using Python

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8770]
The current implementation of linearize() when using Python output only provides the ABCD matrices. 

@naibafomsare proposed [here](https://github.com/OpenModelica/OpenModelica/issues/8687#issuecomment-1080252796) to add a dictionary with names for inputs, outputs, and states. This should be done to get the same functionality as in the Matlab output

**Comment by arun3688** [comment]
@casella the feature is implemented with this commit https://github.com/OpenModelica/OpenModelica/commit/62abb405183a9464a3ad5443db36c243e40a6731

**Comment by casella** [comment]
@naibafomsare, would you mind testing it with the next nigthly build and report? Thanks!

**Comment by naibafomsare** [comment]
@casella and @arun3688, I have tested the new code, and it seems to be working very well, thank  you very much! I can simplify my code now.

The only observation I have is about the description of the new feature. @arun3688 did not add a dictionary, but just a list with the names of the variables in the appropriate order. Such a solution is better than the one I had proposed.
