### ISSUE TITLE
Constant values not plotted

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8796]
### Description
In this tiny example T[1],Tp[2], Tp[3] are not plotted: the plot area is blank

### Steps to Reproduce
Consider this piece of code in OMEdit:
```
model BugConstant
  parameter Real Tp[:] = linspace(1, 10, 3);
equation
end BugConstant;
```
It compiles and runs, but when we try to plot Tp[1], or Tp[2], or Tp[3], they do not appear in the plot: the plot area remains blank.

### Expected Behavior
Horizontal lines should shown with values 1.0, 5.5, 10.0.

### Screenshots
![image](https://user-images.githubusercontent.com/37046832/161311777-c48e7604-d2b4-4890-b2a6-6522f77f33d3.png)

### Version and OS
OM 1.18.0, 64 bit, WIndows 11.

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
Tried this with the latest 1.19.0 nightly build. This is the result:
![immagine](https://user-images.githubusercontent.com/4233148/161345518-1eee0865-506e-4d7d-b468-eacfa2b1e3a6.png)

Whatever caused this issue was fixed in the meantime.
