### ISSUE TITLE
Template error for to long file names on Windows

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#8838]
### Description

When exportin a FMU for Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot in OMEdit I'm getting scripting and translation errors. 
Doing "the same" with a mos script only fails when I change into the OMEdit working directory.

The path to the created files in the OMEdit working directory is quiet long, my test directory I started from has a way shorter name.
The file with the longest name is 274 characters long, probably to long:
```
C:\Users\USERNAME\AppData\Local\Temp\OpenModelica\OMEdit\Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot\Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp\sources\Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_functions.c
```
My USERNAME has no special characters or spaces.

### Steps to Reproduce

Running

```Modelica
loadModel(Modelica,{"4.0.0+maint.om"},true,"",false); getErrorString();

// Replace with your OMEdit working directory
cd("C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot"); getErrorString();

setCommandLineOptions("--fmiFilter=none"); getErrorString();
setCommandLineOptions("--fmiSources=true"); getErrorString();
buildModelFMU(Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot,
              "2.0",
              "me_cs",
              "<default>",
              {"static"},
              false);
getErrorString();
```

produces

```cmd
D:\workspace\Testitesttest\exportfmubug>"C:\Program Files\OpenModelica1.18.1-64bit\bin\omc.exe" run.mos
true
"Notification: Automatically loaded package Complex 4.0.0 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.
"
"C:/Users/USERNAME/AppData/Local/Temp/OpenModelica/OMEdit/Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot"
""
true
""
true
""
""
"Warning: The model contains alias variables with redundant start and/or conflicting nominal values. It is recommended to resolve the conflicts, because otherwise the system could be hard to solve. To print the conflicting alias sets and the chosen candidates please use -d=aliasConflicts.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_literals.h.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_functions.h.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_functions.c.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_includes.h.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_records.c.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_model.h.
Error: Error writing to file Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot.fmutmp/sources/Modelica_Mechanics_MultiBody_Examples_Systems_RobotR3_FullRobot_01exo.c.
Error: Template error: A template call failed (C:\\Program Files\\OpenModelica1.18.1-64bit\\bin\\omc.exe: [unknown function name]). One possible reason could be that a template imported function call failed (which should not happen for functions 
called from within template code; templates assert pure 'match'/non-failing semantics).
"
```

### Expected Behavior

Just work.

### Version and OS

 - OpenModelica Version: v1.18.1 (64-bit)
 - OS: Windows 10
 - Versions of used Modelica libraries if applicable

**Comment by AnHeuermann** [comment]
We could return a error message that the maximum path length (`MAX_PATH=256`) will be reached when trying to write to a file. A possible solution for the user would be to change the maximum path length limitation.

Basically run powershell with
```powershell
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```
on a Windows 10, version 1607 or newer.
Of course many users would not want to do this or aren't allowed to do so.

We would need to count the path length each time we generate a file in the templates or at runtime (I encountered the same problem for the profiling JSON).

A better approach would be to always use path prefixed with `\\?\`, so we can use 32,767 characters. Should be enough for the time being.

See https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd

**Comment by bilderbuchi** [comment]
> Of course many users would not want to do this or aren't allowed to do so.

Indeed! The prefix approach is probably much more useful.

While you're in there, it might make sense to also take care of the presence of UNC paths. I hit this previously when working on a DFS network share.
See [here](https://github.com/gabrielcnr/pytest-datadir/issues/33#issue-661856259) for additional context (in a Python package, but the mechanism is the same) and [here](https://github.com/gabrielcnr/pytest-datadir/pull/34/files#diff-6b34d7568f2d4d6bec98fa3bf619f90fda8539eff864c6da221cfed7179e7a02) for the logic I proposed at the time.

**Comment by casella** [comment]
@AnHeuermann, in your example of file name, the full path of the Modelica model is repeated three times. The first time is necessary, to keep uniqueness of simulation results in the working directory. However, for the other two times, this is not really necessary, only the name of the model would suffice. In your example case, we'd get this path:
```
C:\Users\USERNAME\AppData\Local\Temp\OpenModelica\OMEdit\Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot\FullRobot.fmutmp\sources\FullRobot_functions.c
```
which is way below 254 characters and is easily handled without any black magic. 

Could you take care of that?

**Comment by AnHeuermann** [comment]
I don't think this is the best solution. Next time someone creates a library with longer names we have the same issue.

Using  he `\\?\` prefix is the saver one. I only have to check how to do it.
For the template generation we could change `System.writeFile` to check the path length and either issue a warning or add the string `"\\\\\?\\"` or go one level deeper and change the C functions that actually handle file writing. Probably `SystemImpl__writeFile` is the right place to add this check.

**Comment by AnHeuermann** [comment]
> You can give a filename prefix in the FMI settings in OMEdit, I have myFMU. Then all generated FMUs will have this name.

I could add that to the error message.

But I don't like, that users have to change the names of the models/fmus or the working directory to be able to use one of the core features for a MSL model.
And this won't solve my issue with profiling the FullRobot example.

**Comment by AnHeuermann** [comment]
> While you're in there, it might make sense to also allow for the presence of [UNC paths](https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention) (e.g. `\\ComputerName\SharedFolder\Resource`). I hit this previously when working on a DFS network share. See [here](https://github.com/gabrielcnr/pytest-datadir/issues/33#issue-661856259) for additional context (in a Python package, but the mechanism is the same) and [here](https://github.com/gabrielcnr/pytest-datadir/pull/34/files#diff-6b34d7568f2d4d6bec98fa3bf619f90fda8539eff864c6da221cfed7179e7a02) for the logic I proposed at the time.

@bilderbuchi Please open a feature request in a new issue for this. I can't test UNC paths on my machine. The change itself wouldn't be difficult. Just adding `"\\\\\?\\UNC\\"` to the front of the filenames. But I wouldn't be surprised if the compiler chain can't handle these paths.

**Comment by adrpo** [comment]
Make for sure cannot handle these paths. Gcc and Clang might work directly

**Comment by casella** [comment]
> I don't think this is the best solution. Next time someone creates a library with longer names we have the same issue.

@AnHeuermann, it may not be the ultimate solution, but in any case I don't really see a point at having these ultra-long file names, when there is absolutely no need to have them that long. The ambiguity with model names can only happen at the level of working directory. In fact, everywhere else we could even get rid of the model name entirely. Incidentally, that's what Dymola does, if I am not mistaken, and for a good reason :)

Ockham's razor: whatever is not necessary should be shaved out.

**Comment by AnHeuermann** [comment]
Now users should get a warning when using to long paths in all locations that use `omc_fopen`. That's good enough for the moment, so I'm closing this.

When we get reports about errors with too long path names we can try to change the default locations for OMEdit in Windows. But that should be a new ticket.
