### ISSUE TITLE
Add documentation and examples to variable filter options

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8839]
The "Variable filter" option is not really documented in the [user's guide](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#output); we don't even say that a regexp is expected there. Ditto for the variableFilter inputs in several API functions that accept it, e.g. [simulate](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#simulate).

This information is only available as folklore, e.g. in [this post](https://www.openmodelica.org/forum/default-topic/1535-variable-filtering-for-array-type-of-variables) and [this post](https://www.openmodelica.org/forum/default-topic/1227-filtering-variables-in-simulation).

Another potentially confusing point is that `.` and `[]` have a special meaning in a regexp, so if you want to seek names with dots or array indeces, you have to escape them.

Action items:
- [X] add some explanation to the documentation of the OMEdit feature, _including some examples_ (@casella)
- [x] add the "regex" information to the API function documentation (@casella)
- [x] add a link to the user's guide in the Simulation Setup | Output window (@adeas31)

**Comment by casella** [comment]
Adding @sergniko to the loop

**Comment by casella** [comment]
@sergniko, please check https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#output

**Comment by sergniko** [comment]
> @sergniko, please check https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#output

I think this is good.
Maybe worth adding a note that all of variables are still be in Variables browser. So filter effect you can observe with absence of checkbox next to variable.

**Comment by casella** [comment]
@adeas31 can you take care of task item number 3?

**Comment by casella** [comment]
> Maybe worth adding a note that all of variables are still be in Variables browser. So filter effect you can observe with absence of checkbox next to variable.

Done in #8887 and #8888.

**Comment by casella** [comment]
@adeas31, could you please add a link to the user's guide in the Simulation Setup | Output window, both on master and on maintenance/1.19?

**Comment by casella** [comment]
@adeas31 please cherry-pick into maintenance/v1.19

**Comment by casella** [comment]
Looks good on master. One last check due in 1.19.0-dev.beta5

**Comment by casella** [comment]
Works fine also in 1.19.0-dev.beta5
