### ISSUE TITLE
Record seem to be not fully copied when passed to external C function

### ISSUE THREAD

**Issue by mwetter** [OpenModelica/OpenModelica#8849]
### Description

The model below uses a C function to print the value of a record. The first element of the record is printed correctly, but the second element is incorrectly 0. It looks like the value is not set when passing the record to the C function.

### Steps to Reproduce

Run the model:
```modelica
model TestRecord

  record MyRec
    parameter Integer i = 5;
    parameter Integer j = 6;
  end MyRec;

  parameter MyRec rec;

  function printRecord
    input MyRec rec;

    external "C" myPrint(rec, rec.i, rec.j);
    annotation (Include="#include \"myPrint.c\"");
  end printRecord;

initial equation
  printRecord(rec);
end TestRecord;

```
using the C function
```C
#include "ModelicaUtilities.h"

typedef struct{
    int i;
    int j;
} myStruc;

void myPrint(
  const myStruc* myRecord,
  int i,
  int j){
    ModelicaFormatMessage("i: Record value = %i, primitive value = %i", myRecord->i, i);
    ModelicaFormatMessage("j: Record value = %i, primitive value = %i", myRecord->j, j);
  }
```
### Expected Behavior

`i` and `j` should each have the same value, but `myRecord->j` is `0`. The console output is
```
i: Record value = 5, primitive value = 5
j: Record value = 0, primitive value = 6
```

### Version and OS

 - OpenModelica Version: OpenModelica 1.20.0~dev
 - OS: Linux Ubuntu 20.04

### Additional Context
The model gives the following compile time warning which would be good to correct as well, assuming my code is correct:
```
TestRecord_functions.c:33:11: warning: incompatible pointer types passing 'TestRecord_MyRec *' to parameter of type 'const myStruc *' [-Wincompatible-pointer-types]
  myPrint(_rec_ext, _rec_extPi, _rec_extPj);
          ^~~~~~~~
/home/mwetter/test/structure/Resources/Include/myPrint.c:9:18: note: passing argument to parameter 'myRecord' here
  const myStruc* myRecord,
                 ^
1 warning generated.
```

**Comment by perost** [comment]
Probably a duplicate of #8591.

**Comment by mwetter** [comment]
This is fixed. Tested with OpenModelica 1.23.0~dev-120-g5ba5f91 on Linux.
