### ISSUE TITLE
Model check fails is stream variables are used in Hierarchical connectors

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#8852]
### Description

Consider the following package `TestHierarchicalConnector` (also attached):

```
package TestHierarchicalConnector
  connector C1
    Real e1;
    flow Real f1;
    stream Real s1;
  end C1;

  connector C2
    Real e2;
    flow Real f2;
  end C2;

  connector HC
    C1 c1;
    C2 c2;
  end HC;
  
  model Test
    HC hc; 
  end Test;
  
end TestHierarchicalConnector;
```

- the connector `C1` is balanced and contains a flow variable plus a stream variable
- the connector `C2` is balanced and contains a flow variable
- the connector `HC` is hierarchical and contains `C1` and `C2`

The model `Test` instantiates a connector `HC`

If you check the model `Test` the omc rises the following error:
```
[1] 19:08:35 Translation Error
[TestHierarchicalConnector: 19:5-19:10]: Invalid stream connector hc: A stream connector must have exactly one flow variable, this connector has 2 flow variables.
```

### Version and OS
 - OpenModelica Version: 1.20.0~dev-2-gdcf3514
 - OS: Ubuntu 18.04
[TestHierarchicalConnector.zip](https://github.com/OpenModelica/OpenModelica/files/8542829/TestHierarchicalConnector.zip)

**Comment by perost** [comment]
Should be fixed in #8853, but our servers are a bit wonky at the moment so it might be a while before I can get the PR merged.

**Comment by casella** [comment]
@AndreaBartolini thanks for reporting! Please try out with the latest nightly and report if this works for you now as well.

**Comment by AndreaBartolini** [comment]
Already tried, and it works fine.
Thanks for the quick fix.
