### ISSUE TITLE
Pretty-printing algorithm mangles comments/linebreaks

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#8859]
### Description
The pretty-printer destroys attempts to structure component definitions with the aim to avoid needlessly long lines. It removes (intentionally inserted) linebreaks, and puts source comments into a different order, which is quite undesirable.
The impact of this is increased because currently (#8635) the pretty printer runs after deleting components.

I have resorted to watching my Git status like a hawk, which is a sort of bad workaround -- it's annoying to unload the package, git-revert the undesired line changes, re-load the package, navigate to the previous location, and continue working. Just using the undo buffer is not an easier option if you have done any other unrelated changes in the meantime.

### Steps to Reproduce
* Observe that Options - Modelica Editor - Preserve text indentation is checked
* Open this model
```
model OM_8365
  Modelica.Mechanics.Translational.Components.ElastoGap elastoGap(
    c=1, // take care not to foo the bar
    d=1 // another comment
  ) annotation(
    Placement(visible = true, transformation(origin = {-20, 22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Mechanics.Translational.Components.Rod rod annotation(
    Placement(visible = true, transformation(origin = {-18, -30}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation

annotation(
    uses(Modelica(version = "4.0.0")));
end OM_8365;
```
* Observe the definition of `elastoGap`
* switch to diagram view
* delete `rod`
* The message browser now says "Scripting Warning Could not preserve the formatting of the model instead internal pretty-printing algorithm is used." (this is #8635)
* The model looks like this now, with linebreaks removed and the line comments on the arguments moved _outside_ the component definition:
```
model OM_8365
  Modelica.Mechanics.Translational.Components.ElastoGap elastoGap(c = 1, d = 1) annotation(
    Placement(visible = true, transformation(origin = {-20, 22}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  // take care not to foo the bar
  // another comment
equation

  annotation(
    uses(Modelica(version = "4.0.0")));
end OM_8365;
```
### Expected Behavior

* Enable a user to structure code to avoid endlessly long lines.
* Don't move source comments elsewhere/in another order

### Version and OS
 - OpenModelica Version:  v1.19.0-dev.beta1 (64-bit)
 - OS: e.g. Windows 10, 64 bit

**Comment by casella** [comment]
@bilderbuchi see [my comment in #8635](https://github.com/OpenModelica/OpenModelica/issues/8635#issuecomment-1108596109).

@sjoelund, another test case for the diff algorithm, can you please have a look?

**Comment by bilderbuchi** [comment]
@casella Is it possible that the MSL conversion script machinery uses this pretty printer in the background? 
I have just attempted to convert a package, and the git diff shows me that some comments (both at the end of lines, and comments on a line by themselves!) are moved downward, sometimes by tens of lines! They get bunched together near the end of the model. This totally destroys the context the comments are made in.

I think this kind of mutation is somewhere between annoying (meaning of comments is lost) and dangerous (wrong code portions are annotated). I can try to come up with an MWE, if useful & needed.

**Comment by casella** [comment]
> @casella Is it possible that the MSL conversion script machinery uses this pretty printer in the background?

It uses it in the same way OMEdit does: every time a change is made to the code in the API, it has to be merged into the old formatted source code. If this fails, the pretty-printer kicks in as a fall-back, and since it doesn't know about comments, they are pretty much destroyed.

@sjoelund is working on that.

> I have just attempted to convert a package, and the git diff shows me that some comments (both at the end of lines, and comments on a line by themselves!) are moved downward, sometimes by tens of lines! They get bunched together near the end of the model. This totally destroys the context the comments are made in.
> 
> I think this kind of mutation is somewhere between annoying (meaning of comments is lost)

Agreed.

> and dangerous (wrong code portions are annotated). 

This is something that shouldn't happen anyway.

> I can try to come up with an MWE, if useful & needed.

That would be very useful indeed, please go ahead.

**Comment by bilderbuchi** [comment]
> > and dangerous (wrong code portions are annotated).

> This is something that shouldn't happen anyway.

I was imprecise, I meant "annotated" in the sense of "further explained by comments", not in the Modelica `annotation` sense.

**Comment by bilderbuchi** [comment]
Creating a model and paste this code:
```
block B1
  parameter Real a = 2; // comment on param a
  parameter Real b = 4; // comment on param b
  Modelica.Blocks.Interfaces.RealOutput yCharge;

algorithm
  when time > 1 then
    for ii in 2:5 loop
//      if true then // disabled code at start of for loop
        if a > 0 and a < b then  // explanation on if condition
          yCharge := ii;
        end if;
//      end if; // 
    end for;
    // standalone comment before end when
  end when;
end B1;
```
Pressing Save results in this code:

```
block B1
  parameter Real a = 2;
  // comment on param a
  parameter Real b = 4;
  // comment on param b
  Modelica.Blocks.Interfaces.RealOutput yCharge;
algorithm
  when time > 1 then
    for ii in 2:5 loop
      if a > 0 and a < b then
        yCharge := ii;
      end if;
    end for;
  end when;
//      if true then // disabled code at start of for loop
// explanation on if condition
//      end if; //
// standalone comment before end when
end B1;
```
Note how all comment slipped to a separate line, and especially that all comments _within_ the `with` statement were ejected from the `with`, destroying the context/connection to the code they were commenting on.

Now, I found a trigger for this. Note how in the last-but-one comment line `//      end if; // `, this ends with a `// ` (double slash + space). If I *remove* the space at the end of the line, the pretty printer is _not triggered_ on save anymore! This could be significant when searching why the pretty printer gets triggered by some comments.

**Comment by bilderbuchi** [comment]
Now, if I remove that trailing space to avoid _that_ trigger, and put this block into a package
```
package OM_8859
  block B2
    parameter Real a = 2; // comment on param a
    parameter Real b = 4; // comment on param b
    Modelica.Blocks.Interfaces.RealOutput yCharge;
  
  algorithm
    when time > 1 then
      for ii in 2:5 loop
  //      if true then // disabled code at start of for loop
          if a > 0 and a < b then  // explanation on if condition
            yCharge := ii;
          end if;
  //      end if; // no space at end now
      end for;
      // standalone comment before end when
    end when;
  end B2;
  annotation(
    uses(Modelica(version = "3.2.3")));
end OM_8859;
```
and run the conversion to MSL4, I end up with clustered and appended comments as before, so the pretty printer gets triggered in another way:
```
package OM_8859
  block B2
    parameter Real a = 2;
    // comment on param a
    parameter Real b = 4;
    // comment on param b
    Modelica.Blocks.Interfaces.RealOutput yCharge;
  algorithm
    when time > 1 then
      for ii in 2:5 loop
        if a > 0 and a < b then
          yCharge := ii;
        end if;
      end for;
    end when;
//      if true then // disabled code at start of for loop
// explanation on if condition
//      end if; // no space at end now
// standalone comment before end when
  end B2;
  annotation(
    uses(Modelica(version = "4.0.0")));
end OM_8859;
```

**Comment by bilderbuchi** [comment]
Fun fact about the conversion process I just noticed, apparently it removes newlines at the end of files for no reason I can discern (even if nothing else in that file is changed), which my Git complains about with "\ No newline at end of file" in the diff.
I don't know if that stems from the pretty printer or something else.

**Comment by casella** [comment]
@sjoelund, any explanation for that, and any hope for it to be fixed, eventually?

**Comment by casella** [comment]
Tried `OM_8365` with `v1.20.0-dev-305-geb5e7e0a95`, no comment mangling if i delete the `rod` component from the GUI

**Comment by casella** [comment]
Saving the B1 model no longer mangles the formatting.

**Comment by bilderbuchi** [comment]
Thank you, awesome! :-)
