### ISSUE TITLE
the results of the api (getElements) is not correct

### ISSUE THREAD

**Issue by broisZhang** [OpenModelica/OpenModelica#8867]
When i use the api(getElements) for getting info of model,the result is not correct.

omc.sendExpression("getElements(Modelica.Media.Interfaces.PartialMedium, useQuotes = true)")

the results:
(('co', '-', 'Modelica.Media.Interfaces.Choices.IndependentVariables', 'ThermoStates', 'Enumeration type for independent variables', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'String', 'mediumName', 'Name of the medium', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'String', 'substanceNames', 'Names of the mixture substances. Set substanceNames={mediumName} if only one substance.', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{:}'), ('co', '-', 'String', 'extraPropertiesNames', 'Names of the additional (extra) transported properties. Set extraPropertiesNames=fill("",0) if unused', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{:}'), ('co', '-', 'Boolean', 'singleState', '= true, if u and d are not a function of pressure', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Boolean', 'reducedX', '= true if medium contains the equation sum(X) = 1.0; set reducedX=true if only one substance (see docu for details)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Boolean', 'fixedX', '= true if medium contains the equation X = reference_X', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.AbsolutePressure', 'reference_p', 'Reference pressure of Medium: default 1 atmosphere', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.Temperature', 'reference_T', 'Reference temperature of Medium: default 25 deg Celsius', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.MassFraction', 'reference_X', 'Default mass fractions of medium', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{nX}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.AbsolutePressure', 'p_default', 'Default value for pressure of medium (for initialization)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.Temperature', 'T_default', 'Default value for temperature of medium (for initialization)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.SpecificEnthalpy', 'h_default', 'Default value for specific enthalpy of medium (for initialization)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.MassFraction', 'X_default', 'Default value for mass fractions of medium (for initialization)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{nX}'), ('co', '-', 'Modelica.Media.Interfaces.PartialMedium.ExtraProperty', 'C_default', 'Default value for trace substances of medium (for initialization)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{nC}'), ('co', '-', 'Integer', 'nS', 'Number of substances', 'public', 'true', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Integer', 'nX', 'Number of mass fractions', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Integer', 'nXi', 'Number of structurally independent mass fractions (see docu for details)', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Integer', 'nC', 'Number of extra (outside of standard mass-balance) transported properties', 'public', 'true', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{}'), ('co', '-', 'Real', 'C_nominal', 'Default for the nominal values for the extra properties', 'public', 'false', 'false', 'false', 'false', 'constant', 'none', 'unspecified', '$Any', '{nC}'), ('cl', 'record', 'Modelica.Media.Interfaces.Types.Basic.FluidConstants', 'FluidConstants', 'Critical, triple, molecular and other standard data of fluid', 'public', 'false', 'false', 'false', 'true', 'unspecified', 'none', 'unspecified', '$Any', '{}'), ('cl', 'function', 'Modelica.Media.Interfaces.PartialMedium.specificHeatCapacityCp', 'heatCapacity_cp', 'Alias for deprecated name', 'public', 'false', 'false', 'false', 'false', 'unspecified', 'none', 'unspecified', '$Any', '{}'), ('cl', 'function', 'Modelica.Media.Interfaces.PartialMedium.specificHeatCapacityCv', 'heatCapacity_cv', 'Alias for deprecated name', 'public', 'false', 'false', 'false', 'false', 'unspecified', 'none', 'unspecified', '$Any', '{}'), ('cl', 'function', 'Modelica.Media.Interfaces.PartialMedium.isobaricExpansionCoefficient', 'beta', 'Alias for isobaricExpansionCoefficient for user convenience', 'public', 'false', 'false', 'false', 'false', 'unspecified', 'none', 'unspecified', '$Any', '{}'), ('cl', 'function', 'Modelica.Media.Interfaces.PartialMedium.isothermalCompressibility', 'kappa', 'Alias of isothermalCompressibility for user convenience', 'public', 'false', 'false', 'false', 'false', 'unspecified', 'none', 'unspecified', '$Any', '{}'), ('cl', 'type', 'Modelica.Units.SI.MassFlowRate', 'MassFlowRate', 'Type for mass flow rate with medium specific attributes', 'public', 'false', 'false', 'false', 'false', 'unspecified', 'none', 'unspecified', '$Any', '{}'))

the classname(Modelica.Media.Interfaces.PartialMedium.AbsolutePressure ) is not existed in the modelica standard lib.
 the excepted result is Modelica.Media.Interfaces.Types.AbsolutePressure

 OpenModelica Version: 'OpenModelica v1.19.0-dev-330-ga25f5f34c8 (64-bit)'
 OS: [Windows 10, 64 bit]
 Versions of used Modelica libraries  3.2.3

**Comment by casella** [comment]
> the classname(Modelica.Media.Interfaces.PartialMedium.AbsolutePressure ) does not exist in the modelica standard lib. the expected result is Modelica.Media.Interfaces.Types.AbsolutePressure

If you check the [definition of PartialMedium](https://github.com/modelica/ModelicaStandardLibrary/blob/94f2be9f84e4056acbb6210cd48cca2054ae23c4/Modelica/Media/package.mo#L4956), you'll see:
```modelica
  partial package PartialMedium
    "Partial medium properties (base package of all media packages)"
    extends Modelica.Media.Interfaces.Types;
  ...
  end PartialMedium;
```
hence, all types defined in `Modelica.Media.Interfaces.Types` are also defined within each medium model. This allows to use those type definitions directly when declaring all medium properties, without the need of long dot-qualified paths for the corresponding types and, most importantly, allows to use Medium-specific type definitions when the partial medium is redeclared to be a concrete one.

**Comment by broisZhang** [comment]
Thank you for your reply。
You mean the result (Modelica.Media.Interfaces.PartialMedium.AbsolutePressure) of the api is right?
Is it not this (Modelica.Media.Interfaces.Types.AbsolutePressure)?
![image](https://user-images.githubusercontent.com/87741169/165418869-08925f5d-0889-4e80-95b1-d7dbb0341a26.png)

**Comment by casella** [comment]
`PartialMedium` extends `Modelica.Media.Interfaces.Types`, hence it incorporates everything that is defined there, including the definition of the `AbsolutePressure` type, which becomes part of `PartialMedium`. So, when used within the scope of `PartialMedium`, that type definition is correctly referred to as `Modelica.Media.Interfaces.PartialMedium.AbsolutePressure`, even though it was _originally_ defined somewhere else. That's how inheritance works in object-oriented computer languages.

Of course it is up to the compiler front end to figure out where the original definition is, and what are the possible modifications or redeclarations applied to it. If you ask through the API what are the features of `Modelica.Media.Interfaces.PartialMedium.AbsolutePressure` (e.g. the `unit` attribute or the `nominal` attribute), it's the job of the front-end to flatten the class and figure that out automatically, which it does.

One thing that could be very useful is to have a tool that explicitly shows where the definitions of various components in a class obtained by inheritance come from, and where they were possibly modified or redeclared, see #4586.

**Comment by broisZhang** [comment]
Thanks a lot. 👍
