### ISSUE TITLE
OMEdit should open the HTML User's Guide corresponding to the installed version

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8874]
When selecting Help | Open Modelica User's Guide, this link is opened in the browser: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/ 

This is not a good idea, because we will be showing new features as we are developing and documenting them on master, that are actually not available on official release installations. 

The pdf version of the documentation instead refers correctly to the same version of OMEdit being run. The HTML documentation should follow the same logic. In principle, it should be identical to the PDF file. I guess this is not possible, because we are not keeping the documentation of every commit on the web server, but at least we should refer to the correct version, e.g. https://openmodelica.org/doc/OpenModelicaUsersGuide/1.19/ for the latest stable release, https://openmodelica.org/doc/OpenModelicaUsersGuide/1.18/ for the latest official release.

**Comment by casella** [comment]
@adeas31 can you take care of this in time for the 1.19.0 release? Thanks!

**Comment by casella** [comment]
KISS, never mind specific 1.19.x versions :)

**Comment by adeas31** [comment]
Getting `x.y` from `getVersion()` output is not an issue. The only problem is that for nightly builds we should use `latest` instead of `x.y` and there is no such information that the specific version is a release or a nightly.

**Comment by casella** [comment]
The current nightly build has version number 1.20.0. I guess we simply need to stop calling the master version `latest` on the webserver, and just call it with its version number, i.e. 1.20 in the current case. I'm not sure exactly how this can be done, but it seems to me not such a big deal. Do I miss something?

**Comment by adeas31** [comment]
For now I made a symlink (1.20 -> latest) on the server. We should automate this somehow.

**Comment by casella** [comment]
@adeas31, @adrpo, do we have a check-list of stuff to do when doing a release? I'd add a line there, before we forget

**Comment by casella** [comment]
I'll check this with the final beta, just in case.

**Comment by casella** [comment]
Both 1.19.0-dev.beta5 and 1.20.0-dev load the correct HTML version now.
