### ISSUE TITLE
Toggling sign should not un-zoom

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8877]
### Description

Toggling sign should not un-zoom

### Steps to Reproduce
1. show a plot
2. 2. zoom on part of it
3. toggle sign: the curve is toggled but it is also unzoomed

### Expected Behavior
Toggling sign should just toggle sign. 
When we are looking at a part of a plot, we expect the same part of the plot to be shown, with sign toggled.
For instance, in a ten-second simulation, we are just looking at the last 100 ms, and when we ask a curve to be toggled, we just want it to change its sign in the shown time window (i.e the same last 100 ms).

### Version and OS
OM 1.19.0-beta1, Win10 64 bit.

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
Most definitely!

**Comment by max-privato** [comment]
Now part of ncluded in #10118
