### ISSUE TITLE
Bad behaviour of text completion

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#8879]
### Steps to Reproduce
paste the following code into OMEdit:

```
model Test
  Modelica.Electrical.Analog.Ideal.IdealGTOThyWithBadText;
end test;
```
Imagine we note that the word `IdealGTOThyWithBadText` is badly written.
We go with the cursor immediately after 'y' meaning that the text should continue as "thyristor"; we just write 'r' and OMEdit brilliantly proposes "IdealGTOThyristor" At this point, to accept the suggested completion, one clicks tab, expecting to read `IdealGTOThyristor `before ';'.
Instead we read `IdealGTOThyristorWithBadText`, which is wrong.

### Expected Behavior
When clicking on tab, the correction should fix the error, _substituting_ the bad word with the correct one. Currently, instead, it _inserts_ the good word into the bad one, creating a bad result.

### Version and OS

OM 1.19.0-beta1, Win10 64 bit.
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by max-privato** [comment]
Any news on this? I expected it to be easy to fix.

**Comment by adeas31** [comment]
I tested this and I believe the current behavior is the correct way. I also tested how other editors are doing e.g., Qt Creator and Visual Studio Code also do the same thing.

@atrosinenko what are you thoughts on it since you are the one who implemented this.

**Comment by ceraolo** [comment]
Ah. 
I remembered badly that Qt behaved as I propose here.

Nevertheless, I still think this ticket proposes something useful. Pressing Tab means we accept the modification and therefore the bad part of the word should IMO be deleted. 
Let see what @atrosinenko thinks.

**Comment by atrosinenko** [comment]
@adeas31 Sorry for the delay. I am not an active user of Modelica for quite a long time, so I fear I cannot give any valuable comments :(

**Comment by bilderbuchi** [comment]
I just checked, and IPython behaves the same, as does Visual Studio Code in a Fortran codebase.
I'd vote for keeping the behaviour consistent with other editors.

**Comment by bilderbuchi** [comment]
Sorry. You reported other editors' behaviour:

> I tested this and I believe the current behavior is the correct way. I also tested how other editors are doing it. For example, Qt Creator and Visual Studio Code also do the same thing.

I tested some others, and found (AFAICT) the same thing, i.e. "inserting" the completion instead of substituting the whole word.

So, currently as reported above OMEdit does the same thing as all other tested editors, i.e. its behaviour is consistent with theirs. Let's keep it this way.

**Comment by adeas31** [comment]
The current behavior of text completion is same as all other tested text editors.
