### ISSUE TITLE
1.19.0-beta.1 loads the wrong pre-installed MSL version on Windows

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8881]
I just installed 1.19.0-beta.1 on Windows, after deleting all installation files, so it should work as a first installation.

If I start OMEdit and load a library using MSL 3.2.3 (e.g. PowerGrids), I get these scripting notifications
```
[1] 13:24:26 Scripting Notification
Automatically loaded package Modelica 4.0.0 due to uses annotation.

[2] 13:24:26 Scripting Notification
Automatically loaded package Complex 4.0.0 due to uses annotation.

[3] 13:24:26 Scripting Notification
Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.
```
and then of course nothing works because the wrong MSL is loaded.

I tried to figure out why this happens by looking at omcommunication.log but I got a bit lost there.

**Comment by sjoelund** [comment]
Is 3.2.3 installed?

**Comment by casella** [comment]
Of course it is :)

**Comment by casella** [comment]
```
loadFile("D:/Lavoro/Dynamica/RTE/RTE 003/GIT/PowerGrids/PowerGrids/package.mo","UTF-8",true,true,false) 13:24:24:453
true 13:24:26:160
#s#; 1.706000; 1.991000; 'loadFile("D:/Lavoro/Dynamica/RTE/RTE 003/GIT/PowerGrids/PowerGrids/package.mo","UTF-8",true,true,false)'

countMessages() 13:24:26:160
(3,0,0) 13:24:26:160
#s#; 0.000000; 1.991000; 'countMessages()'

errors:=getMessagesStringInternal() 13:24:26:160
{record OpenModelica.Scripting.ErrorMessage
    info = record OpenModelica.Scripting.SourceInfo
    filename = "",
    readonly = false,
    lineStart = 0,
    columnStart = 0,
    lineEnd = 0,
    columnEnd = 0
end OpenModelica.Scripting.SourceInfo;,
    message = "Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.",
    kind = .OpenModelica.Scripting.ErrorKind.scripting,
    level = .OpenModelica.Scripting.ErrorLevel.notification,
    id = 223
end OpenModelica.Scripting.ErrorMessage;,record OpenModelica.Scripting.ErrorMessage
    info = record OpenModelica.Scripting.SourceInfo
    filename = "",
    readonly = false,
    lineStart = 0,
    columnStart = 0,
    lineEnd = 0,
    columnEnd = 0
end OpenModelica.Scripting.SourceInfo;,
    message = "Automatically loaded package Complex 4.0.0 due to uses annotation.",
    kind = .OpenModelica.Scripting.ErrorKind.scripting,
    level = .OpenModelica.Scripting.ErrorLevel.notification,
    id = 223
end OpenModelica.Scripting.ErrorMessage;,record OpenModelica.Scripting.ErrorMessage
    info = record OpenModelica.Scripting.SourceInfo
    filename = "",
    readonly = false,
    lineStart = 0,
    columnStart = 0,
    lineEnd = 0,
    columnEnd = 0
end OpenModelica.Scripting.SourceInfo;,
    message = "Automatically loaded package Modelica 4.0.0 due to uses annotation.",
    kind = .OpenModelica.Scripting.ErrorKind.scripting,
    level = .OpenModelica.Scripting.ErrorLevel.notification,
    id = 223
end OpenModelica.Scripting.ErrorMessage;} 13:24:26:300
#s#; 0.139000; 2.130000; 'errors:=getMessagesStringInternal()'
```

**Comment by casella** [comment]
@perost, I guess [loadFile()](url) loads the wrong MSL

**Comment by casella** [comment]
Small MWE attached, [TestMSL.zip](https://github.com/OpenModelica/OpenModelica/files/8602716/TestMSL.zip).

Just unzip it and run omc test.mos. You get
```
"Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.
```

**Comment by sjoelund** [comment]
On Linux with Modelica 3.2.3 and 4.0.0 in /usr/lib/omlibrary (but not Complex/Services):
```mo
true
"Notification: Automatically loaded package Modelica 3.2.3 due to uses annotation.
Notification: You can install the requested package using one of the commands:
  installPackage(Complex, \"4.0.0+maint.om\", exactMatch=true)
  installPackage(Complex, \"3.2.3\", exactMatch=false)
  installPackage(Complex, \"3.2.3\", exactMatch=false).
Notification: Skipped loading package Complex (3.2.3,default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/marsj/.openmodelica/libraries/ (uses-annotation may be wrong).
Notification: You can install the requested package using one of the commands:
  installPackage(ModelicaServices, \"4.0.0+maint.om\", exactMatch=true)
  installPackage(ModelicaServices, \"3.2.3\", exactMatch=false)
  installPackage(ModelicaServices, \"3.2.3\", exactMatch=false).
Notification: Skipped loading package ModelicaServices (3.2.3,default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/marsj/.openmodelica/libraries/ (uses-annotation may be wrong).
"
record SimulationResult
    resultFile = "/home/marsj/tmp/TestMSL/Test_res.mat",
    simulationOptions = "startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'Test', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
    messages = "LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
",
    timeFrontend = 0.09742730600000001,
    timeBackend = 0.003838709,
    timeSimCode = 0.001331738,
    timeTemplates = 0.002588573,
    timeCompile = 0.424348647,
    timeSimulation = 0.017613749,
    timeTotal = 0.5472539790000001
end SimulationResult;
"Notification: You can install the requested package using one of the commands:
  installPackage(Complex, \"4.0.0+maint.om\", exactMatch=true)
  installPackage(Complex, \"3.2.3\", exactMatch=false)
  installPackage(Complex, \"3.2.3\", exactMatch=false).
Notification: Skipped loading package Complex (3.2.3,default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/marsj/.openmodelica/libraries/ (uses-annotation may be wrong).
Notification: You can install the requested package using one of the commands:
  installPackage(ModelicaServices, \"4.0.0+maint.om\", exactMatch=true)
  installPackage(ModelicaServices, \"3.2.3\", exactMatch=false)
  installPackage(ModelicaServices, \"3.2.3\", exactMatch=false).
Notification: Skipped loading package ModelicaServices (3.2.3,default) using MODELICAPATH /usr/bin/../lib/omlibrary:/home/marsj/.openmodelica/libraries/ (uses-annotation may be wrong).
"
"3.2.3" // getVersion(Modelica)
"/usr/lib/omlibrary/Modelica 3.2.3/package.mo" // getSourceFile(Modelica)
```

**Comment by casella** [comment]
>  1. `loadModel` checks if the requested library is already loaded, and gives some error message if an incompatible version is already loaded.

Looks good. As I understand, this error message is then caught by OMEdit to cancel loading the library, or to unload everything and reload the offending library from start, @adeas31 can you please confirm?

> 3. The `ClassLoader` uses the package manager to convert each version to a list of compatible installed versions (or just passes the version through if none is found). An exception is if `requireExactVersion` is `true`, in which case this step is skipped.

How does this work for libraries which are not under package management, but just happen to be located somewhere in the MODELICAPATH? As I understood from today's discussion, different builds of the same versions are ordered according to the semver metadata in their directory name, and then the most recent one is loaded as if it had no semver metadata in the directory name.

If that is correct, then I understand `ClassLoader` loads
- the most recent installed backwards-compatible version and build of the library specified in the loadClass (or in the uses annotation), if the library is installed by the package manager and the metadata is available
- the most recent build of the library, without looking for more recent backwards-compatible versions, if the library is not indexed by the package manager

@perost can you please confirm?

This would be fine, at least for 1.19.0. For the future, we could possibly improve the selection of more recent backwards-compatible libraries for libraries in the MODELICAPATH, which are not indexed by the package manager.

>     5. ???
> 
>     6. Some version of the library is potentially loaded.

I'm not sure I understand these last two points 😅

**Comment by perost** [comment]
> How does this work for libraries which are not under package management, but just happen to be located somewhere in the MODELICAPATH? As I understood from today's discussion, different builds of the same versions are ordered according to the semver metadata in their directory name, and then the most recent one is loaded as if it had no semver metadata in the directory name.

It tries to load an exact version first, and otherwise some greater version (the greatest?).

> 
> If that is correct, then I understand `ClassLoader` loads
> 
>     * the most recent installed backwards-compatible version and build of the library specified in the loadClass (or in the uses annotation), if the library is installed by the package manager and the metadata is available
> 
>     * the most recent build of the library, without looking for more recent backwards-compatible versions, if the library is not indexed by the package manager
> 
> 
> @perost can you please confirm?

Yes, pretty much.

**Comment by casella** [comment]
> > How does this work for libraries which are not under package management, but just happen to be located somewhere in the MODELICAPATH? As I understood from today's discussion, different builds of the same versions are ordered according to the semver metadata in their directory name, and then the most recent one is loaded as if it had no semver metadata in the directory name.
> 
> It tries to load an exact version first, and otherwise some greater version (the greatest?).

Loading the exact version first is not necessarily a good idea, if there are newer ones that are backwards-compatible in the same path. Even more importantly, loading the greatest one next is not in general a good idea either, since it may not be backwards-compatible, and then you would run into problem when trying to run actual stuff after loading.

Assuming that libraries outside the library manager are stored in libraries according to the language specification Section 13.4.1, i.e. without any semver metadata in the directory name, hence with only one directory for each version (no multiple builds of the same version), I would suggest to use this algorithm for `ClassLoader`, to load class ClassXYZ version x.y.z
```
foreach path P in MODELICAPATH loop
  if P contains a package manager index file then
    look for the most recent version of ClassXYZ which is backwards-compatible with version x.y.z using the package manager
    if found then load it; return; endif
  else
    sort the directory or file names in the path using class names and version semantics (hence ClassXYZ 11.0.0 is higher than ClassXYZ 2.0.0)
    foreach version of ClassXYZ (in reverse order from the greatest to the smallest) loop
      load the library
      if it has annotation(conversion(noneFromVersion="x.y.z")) then load it; return; end if
      unload the library
    end for
  end if
end for
errorMessage("Could not find ClassXYZ in the MODELICAPATH")
```
This ensures that the most recent _backwards compatible_ class is loaded. In theory, this is not very efficient. In practice, in most cases the greates version will be indeed backwards-compatible, and will be loaded first; only in some cases one or two trial-and-error rounds would be needed. But at least we have a safe solution.

To improve this, in the future we may introduce a function that doesn't load the whole class, but just looks for the version and conversion annotations.

@perost, do you think you can implement this? Or maybe, this is actually what is already implemented?

**Comment by perost** [comment]
> @perost, do you think you can implement this? Or maybe, this is actually what is already implemented?

Implementing that might be quite a lot of work. As Martin hinted at during the meeting we should probably reimplement the external C part in MetaModelica so we can integrate it better with the ClassLoader and the package manager. Right now it's quite messy since we basically have two systems that don't interact well.

**Comment by sjoelund** [comment]
The package manager also does not do dependency resolution, but it could in the future and then it would improve both systems.

And yes, it can be done. But would be better to skip the external C stuff. That's just putting lipstick on a pig. At least in MetaModelica we can parse semver and make some assumptions. If we have write access to the directory, we could also parse the library and add metadata (reading the noneFromVersion stuff, etc)

**Comment by casella** [comment]
Gotcha! Yet another case of trouble caused by Bill Gate's brilliant idea to use slashes for options and backslashes for directories in MS-DOS, may God bless him 👿

- Case 1: immediately after installation, the MODELICAPATH string in Tools | Options | Libraries is `C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`. This doesn't work
- Case 2: if I remove the package manager path and I set it to `C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`, I get MSL 3.2.3 loaded automatically.
- Case 3: if I change the slashes in the package manager path to backslashes `C:\Users\Francesco Casella\AppData\Roaming\.openmodelica\libraries;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`, I also get MSL 3.2.3 loaded automatically.

Apparently, forward slashes in MODELICAPATH under Windows are fine, except for the case of the package manager directory, where forward slashes completely break the MODELICAPATH parsing. 

There are spaces also in the installation directory (because of Program Files), so I guess the culprit is the directory starting with the dot. Or something. @adeas31, @adrpo, I hope this intel is good enough to fix this issue 😄

**Comment by casella** [comment]
> Gotcha! Yet another case of trouble caused by Bill Gate's brilliant idea to use slashes for options and backslashes for directories in MS-DOS, may God bless him 👿
> 
>     * Case 1: immediately after installation, the MODELICAPATH string in Tools | Options | Libraries is `C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`. This doesn't work
> 
>     * Case 2: if I remove the package manager path and I set it to `C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`, I get MSL 3.2.3 loaded automatically.
> 
>     * Case 3: if I change the slashes in the package manager path to backslashes `C:\Users\Francesco Casella\AppData\Roaming\.openmodelica\libraries;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary`, I also get MSL 3.2.3 loaded automatically.
> 
> 
> Apparently, forward slashes in MODELICAPATH under Windows are fine, except for the case of the package manager directory, where forward slashes completely break the MODELICAPATH parsing.
> 
> There are spaces also in the installation directory (because of Program Files), so I guess the culprit is the directory starting with the dot. Or something. @adeas31, @adrpo, I hope this intel is good enough to fix this issue 😄

Please make sure that both forward and backward slashes in MODELICAPATH work on Windows, one never knows if a tool working on multiple platforms expects one or the other, so supporting both seems the best option.

**Comment by casella** [comment]
One more important remark: setting MODELICAPATH with backward slashes in the package manager path allows the other path (i.e. the one with the program files directory) to be actually used to load the default MSL. 

However, it actually prevents the package manager to run, I guess because it was written by @sjoelund to use Unix-style directory names. If I set MODELICAPATH to `C:\Users\Francesco Casella\AppData\Roaming\.openmodelica\libraries;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary` and then try Files | System Libraries | Install Library, I get
```
[4] 22:56:10 Scripting Error
The MODELICAPATH (C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries;C:/Program Files/OpenModelica1.19.0-dev.beta1-64bit/lib/omlibrary)
does not contain C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/, 
so the package index cannot be used.
```
which is really kind of weird, because it looks like the backward slashes were converted to forward slashes, but apparently not convincingly enough. What a bloody mess... 😄 

Ideally, we should make sure that paths for the package manager under Windows are read correctly both by the package manager and by the class loader, regardless of the slash orientation.

**Comment by casella** [comment]
This now works fine in 1.19.0-dev.beta3
