### ISSUE TITLE
The package manager doesn't work with Buildings 8.1.0 on Windows

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8886]
I just tried to use the package manager with OMEdit under Windows to install Buildings 8.1.0, using 1.19.0-beta.1, but I failed. I then reproduced the issue with a simple `install.mos` file containing the following line:
```
installPackage(Buildings, "8.1.0", exactMatch = true);getErrorString()
```
Running `omc install.mos` produces the following output:
```
false
"Error: Failed to open file for writing C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/Resources/ReferenceResults/Dymola/Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt
Notification: After extracting C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/cache/8a5db0ce3a7c54803e0abc2c01b28f7c18e81b09.zip, 
C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/package.mo does not exist. Removing the failed installation.
"
```
However, if I do the same on Linux with OpenModelica 1.20.0~dev-4-g9b510d8, I get
```
true
"[/home/casella/.openmodelica/libraries/ModelicaServices 3.2.3+maint.om/package.     mo:0:0-0:0:readonly] Notification: Package installed successfully (SHA e68d7a031     7c565ee00c1b8d44c527979ea0304bf).
[/home/casella/.openmodelica/libraries/Complex 3.2.3+maint.om/package.mo:0:0-0:0     :readonly] Notification: Package installed successfully (SHA e68d7a0317c565ee00c     1b8d44c527979ea0304bf).
[/home/casella/.openmodelica/libraries/Buildings 8.1.0/package.mo:0:0-0:0:readon     ly] Notification: Package installed successfully (SHA 8a5db0ce3a7c54803e0abc2c01     b28f7c18e81b09).
```
This may be due to the same issue as #8881, we should re-check once that is fixed.

**Comment by AnHeuermann** [comment]
I bet its the good old path limit on Windows, see also https://github.com/OpenModelica/OpenModelica/issues/8838.

`C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/Resources/ReferenceResults/Dymola/Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt` is 260 (>256) charcters long.

**Comment by sjoelund** [comment]
So fopen here needs to be changed for Windows? https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/runtime/om_unzip.c#L101

**Comment by AnHeuermann** [comment]
I'm creating a function `System_longpath` in PR #8848 that translates a path `some\path` to the equivalent `\\?\C:\some\path` and used it in some places during template generation with
```C
#if defined(__MINGW32__) || defined(__MINGW64__) || defined(_MSC_VER)
  int pathLen = strlen(System_realpath(filename));
  if (pathLen > MAX_PATH) {
    long_filename = System_longpath(filename);
  }
#endif
omc_fopen(long_filename, fileOpenMode);
```

**Comment by AnHeuermann** [comment]
But maybe we should just integrate that into `omc_fopen` and never use `fopen` anywhere. Samoe for the other file functions (check for existence, check mode, whatever...)

**Comment by casella** [comment]
> I bet its the good old path limit on Windows, see also #8838.
> 
> `C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/Resources/ReferenceResults/Dymola/Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt` is 260 (>256) charcters long.

Bill Gates again. God bless him.

@adrpo figured a solution using short windows path names (which also covered weird characters), could it be used here?

**Comment by adeas31** [comment]
AFAIR if you just use `omc_fopen` then you don't need to worry about MAX_PATH.

**Comment by AnHeuermann** [comment]
@casella With 6cbe43712ea68e85a8e4e3ce046b657c520a74df omc_fopen is used, which should
a) Issue a warning that your path is longer then PATH_MAX and how to change it on your Windows system
and
b) just work

Can you test again?

**Comment by casella** [comment]
Sure, as soon as I get a new nightly build, just started one now.

**Comment by casella** [comment]
@AnHeuermann, I tried with the latest nightly 0e39c77, which includes 6cbe437, but I still have the same issue
```
[9] 20:11:39 Error
Failed to open file for writing C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/Resources/ReferenceResults/Dymola/Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt

[10] 20:11:39 Scripting Notification
After extracting C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/cache/8a5db0ce3a7c54803e0abc2c01b28f7c18e81b09.zip, C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/package.mo does not exist. Removing the failed installation. 
```

**Comment by AnHeuermann** [comment]
I'm able to reproduce the issue after hacking `settingsimpl.c` to use

```C
static char* omc_userHome = "D:/Users/Francesco Casella/AppData/Roaming";
```

(An option to change the directory would be nice, see #8945)

`omc_fopen` is failing to open `D:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/Resources/ReferenceResults/Dymola/Buildings_Fluid_Geothermal_Borefields_BaseClasses_Boreholes_BaseClasses_Functions_Validation_InternalResistancesTwoUTube_NegativeResistance.txt`, because it has exactly 260 characters (and my MAX_PATH is equal to 260).

Off-by-one-error ....

A fix is on the way

**Comment by AnHeuermann** [comment]
@casella Please verify with the next nightly build, but I'm very sure the problem should be solved.

**Comment by casella** [comment]
Will do. But then you need to cherry-pick this commit into maintenance/v1.19, otherwise the fix will only be available with 1.20.

**Comment by casella** [comment]
@AnHeuermann: this is still not working:
```
[10] 13:36:58 Scripting Notification
After extracting C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/cache/8a5db0ce3a7c54803e0abc2c01b28f7c18e81b09.zip, C:/Users/Francesco Casella/AppData/Roaming/.openmodelica/libraries/Buildings 8.1.0/package.mo does not exist. Removing the failed installation.
```

**Comment by AnHeuermann** [comment]
Will do

**Comment by AnHeuermann** [comment]
I can't reproduce the issue with my self-build omc from `maintenance/v1.19`, but 3de805117068f1a85b4bb138c510120055829013 is not in the [tag for beta3](https://github.com/OpenModelica/OpenModelica/commits/v1.19.0-dev.beta3), so it is missing from that beta version.

@adrpo Can you create a new tag / add it to the next beta version?

**Comment by adrpo** [comment]
dev.beta4 is building now.

**Comment by casella** [comment]
Works in 1.19.0-dev.beta4.

I am getting this warning:
```
Warning: Maximum path length limitation reached while opening 
        C:\Users\Francesco Casella\AppData\Roaming\.openmodelica\libraries\Buildings 8.1.0\Resources\Scripts\OpenModelica\compareVars\Buildings.Fluid.Geothermal.Borefields.BaseClasses.HeatTransfer.ThermalResponseFactors.Validation.FiniteLineSource_Integrand_Length.mos 
Consider changing the working directory, using shorter names or to enable longer paths in Windows. 
```
which is not really very useful, since the end-user has no clue how to change the package manager working directory - in fact, that's not even possible, unless the username is changed.

Anyway, I can live with that.

**Comment by AnHeuermann** [comment]
Yeah the warning isn't really helpful in this case. Actually there is an additional line on how to resolve the problem:
```
See https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation for more information.
```

But we can change the message for 1.20 or think about a more holistic approach.

**Comment by casella** [comment]
Unfortunately the Microsoft webpage can't tell me how to reduce the length of this path, because obviously it has no idea how OMC generates it in the first place. That's the problem with this error message, it tells me something about the root cause, but not enough to allow me to solve it. :)

The question is, now that we have 8.3 paths implemented, is this really still an issue, or can we just stop bothering about long pathnames? In the latter case, we should probably drop the warning, because there is really no reason to be warned in the first place.

**Comment by AnHeuermann** [comment]
Basically it tells you to run
```powershell
New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
-Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
```

**Comment by AnHeuermann** [comment]
> The question is, now that we have 8.3 paths implemented, is this really still an issue, or can we just stop bothering about long pathnames? In the latter case, we should probably drop the warning, because there is really no reason to be warned in the first place.

There is no issue with loading / writing to files that have long names. But compiling (make, gcc, ld) will not work when the path limit is reached.

**Comment by casella** [comment]
> Basically it tells you to run
> 
> ```powershell
> New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
> -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
> ```

I'm a bit puzzled, do you mean running this from the DOS cmd prompt?

**Comment by casella** [comment]
> There is no issue with loading / writing to files that have long names. But compiling (make, gcc, ld) will not work when the path limit is reached.

I understood from @adrpo that he had fixed that. Do I miss something?

**Comment by AnHeuermann** [comment]
> I'm a bit puzzled, do you mean running this from the DOS cmd prompt?

Sorry. I was a bit to brief. The Microsoft help page tells you what the issue is and how to solve it by fiddling with the registry to increase the maximum path length. At the end of the page is code for CMD and PowerShell to do that. The code I posted is the PowerShell version. But I would not recommend changing stuff in the registry, since I don't know what the code exactly does.

**Comment by casella** [comment]
Me neither 😄
