### ISSUE TITLE
Simple testcase does not simulate properly in DAEMode (v1.19.0-dev)

### ISSUE THREAD

**Issue by rosiereflo** [OpenModelica/OpenModelica#8920]
### Description
With OMEdit v1.19.0-dev the simple model provided below does not generate the correct curves when daeMode is activated. in ode the simulation is correct.

### Steps to reproduce

Create the following model in OMEdit, simulate and plot the curves.
```
model test
  Real i1(start=0);
  Real i2(start=0);
equation
  i1 = time;
  i1+i2=0;
  annotation(__OpenModelica_commandLineOptions = "--daeMode");
end test;
```

When daeMode is enabled, we get i1 = i2 = 0 for any time.
When daeMode is disabled, we get the correct curves.

### Version and OS
 - OMEdit v1.19.0-dev
 - OS: Ubuntu20

**Comment by casella** [comment]
This issue was very likely fixed by pull request #8655, which was merged in on Mar 8. If your 1.19.0-dev is earlier than that, you should get it to run with either a new 1.20.0 nightly build or with the 1.19.0-beta.1. 

Please repen or comment here if that is not the case. Thanks!
