### ISSUE TITLE
Class annotation is missing in getModelInstance API

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#8940]
### Description

The whole class annotation is missing from `getModelInstance` api.

### Steps to Reproduce

Run

```
loadString("model M
  annotation (
    Icon(graphics={Rectangle(extent={{-66,78},{70,-56}}, lineColor={28,108,200})}),
    Diagram(graphics={Ellipse(extent={{-62,68},{56,-60}}, lineColor={28,108,200})}));
end M;");
getErrorString();
getModelInstance(M, prettyPrint=true);
getErrorString();
```

### Expected Behavior

The result should contain the class annotation.

**Comment by perost** [comment]
Fixed in #8947.

Right now we dump the annotations as strings though. Would it perhaps be better to dump them as JSON structures instead?

**Comment by adeas31** [comment]
JSON structures would be nice!

**Comment by perost** [comment]
> JSON structures would be nice!

Implemented in #8963. It's a bit weird though, since e.g.:
```
Icon(graphics = {Rectangle(extent = {{-66, 78}, {70, -56}}, lineColor = {28, 108, 200})}
```
is now dumped as:
```json
"Icon": {
  "modifiers": {
    "graphics": {
      "value": "{Rectangle(extent = {{-66, 78}, {70, -56}}, lineColor = {28, 108, 200})}"
    }
  }
}
```
So most of it is still dumped as a string because it's an expression rather than part of the modifier structure.

**Comment by sjoelund** [comment]
Couldn't we dump the expression as JSON?

**Comment by perost** [comment]
> Couldn't we dump the expression as JSON?

We've discussed it a bit but have so far preferred to keep it as a string, but it's still very much work in progress.
