### ISSUE TITLE
How to handle modification from top level

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#8950]
One of the things we want to achieve with the new `getModelInstance` api is to be able to handle conditional connectors. Right now its is very unclear how to manage this. Lets say we have the following package,
```
package ConditionalConnector
  connector Port
    annotation (Icon(coordinateSystem(preserveAspectRatio=false), graphics={
            Rectangle(
            extent={{-100,100},{100,-100}},
            lineColor={255,0,0},
            fillColor={255,0,0},
            fillPattern=FillPattern.Solid)}), Diagram(coordinateSystem(
            preserveAspectRatio=false)));
  end Port;

  model ConditionalPort
    parameter Boolean usePort=false annotation(Evaluate=true, choices(checkBox=true));
    Port port if usePort
      annotation (Placement(transformation(extent={{-10,-108},{10,-88}})));
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false), graphics={Rectangle(
            extent={{-100,100},{100,-100}},
            lineColor={255,0,0},
            fillColor={255,0,0},
            fillPattern=FillPattern.None)}));
  end ConditionalPort;

  model Foo
    extends ConditionalPort;
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end Foo;

  model M
    Foo resistor(usePort=true)
      annotation (Placement(transformation(extent={{-10,-8},{10,12}})));
    annotation (Icon(coordinateSystem(preserveAspectRatio=false)), Diagram(
          coordinateSystem(preserveAspectRatio=false)));
  end M;
end ConditionalConnector;
```

Now if we use `getModelInstance(ConditionalConnector.M, prettyPrint=true)`,
```
"{
  \"name\": \"ConditionalConnector.M\",
  \"components\": {
    \"resistor\": {
      \"type\": \"ConditionalConnector.Foo\",
      \"modifier\": \"(usePort = false)\",
      \"prefixes\": {
        \"public\": true,
        \"final\": false,
        \"inner\": false,
        \"outer\": false,
        \"replaceable\": false,
        \"redeclare\": false,
        \"connector\": \"\",
        \"variability\": \"\",
        \"direction\": \"\"
      },
      \"annotation\": \"(Placement(transformation(extent = {{-10, -8}, {10, 12}})))\"
    }
  },
  \"connections\": [

  ],
  \"replaceable\": [

  ]
}"
```

And `getModelInstance(ConditionalConnector.ConditionalPort, prettyPrint=true)` gives,
```
"{
  \"name\": \"ConditionalConnector.ConditionalPort\",
  \"components\": {
    \"port\": {
      \"type\": \"ConditionalConnector.Port\",
      \"modifier\": \"\",
      \"condition\": {
        \"binding\": \"false\"
      },
      \"prefixes\": {
        \"public\": true,
        \"final\": false,
        \"inner\": false,
        \"outer\": false,
        \"replaceable\": false,
        \"redeclare\": false,
        \"connector\": \"\",
        \"variability\": \"\",
        \"direction\": \"\"
      },
      \"annotation\": \"(Placement(transformation(extent = {{-10, -108}, {10, -88}})))\"
    },
    \"usePort\": {
      \"type\": \"Boolean\",
      \"modifier\": \" = false\",
      \"value\": {
        \"binding\": \"false\"
      },
      \"prefixes\": {
        \"public\": true,
        \"final\": false,
        \"inner\": false,
        \"outer\": false,
        \"replaceable\": false,
        \"redeclare\": false,
        \"connector\": \"\",
        \"variability\": \"parameter\",
        \"direction\": \"\"
      },
      \"annotation\": \"(Evaluate = true, choices(checkBox = true))\"
    }
  },
  \"connections\": [

  ],
  \"replaceable\": [

  ]
}"
```

Note that `ConditionalConnector.ConditionalPort` does have `condition binding` as `false` but this is same as old api. How should we evaluate the placement annotation of the `ConditionalConnector.ConditionalPort.Port` so that `usePort` modified in `ConditionalConnector.M` is applied.

**Comment by adeas31** [comment]
Had a meeting with @adrpo about it. We need to give everything in one call. So `getModelInstance(ConditionalConnector.M)` needs to returns everything that is needed by OMEdit for drawing and this way the modification from the top level are applied.

**Comment by adrpo** [comment]
So `getModelInstance(ConditionalConnector.M)` should give you ***all*** the needed info:
- the entire hierarchy of components (and replaceable classes) and their annotation (to populate the Dialog annotations and the Diagram)
- connect equations and their annotation (to populate the Diagram)

This way OMEdit does not do its own flattening, doesn't try to apply any modifiers by itself.  OMEdit:
- takes the JSON and populates the structures needed to draw Dialogs and diagrams
- if there are any changes via Dialogs or via Diagram manipulation those are give back as a JSON
   * value or class changes via the Dialogs
   * graphical stuff in the diagram (move, add new component, connections)
- OMC takes the JSON and applies the modification to the AST
   * value or class changes are applied as modifications to the components at the top level
   * new components and connections are added to the AST 
   * annotation changes (from component movement or Diagram edits) are applied where needed

I think this is the only way to correctly fix the bugs that we have, no other way is possible.
Of course, I don't know the details on how the JSON will look but this is what it needs to contain.

**Comment by casella** [comment]
@adrpo's suggestion looks good to me. BTW, once we have that, it seems to me that implementing 8-yrs-old [#2891](https://trac.openmodelica.org/OpenModelica/ticket/2891) would be straightforward, you just need to take sub-trees of that instantiation tree, right?

**Comment by perost** [comment]
#8984 changes the API so that the whole instance tree is now dumped recursively. A component's type will now be either a string if it's a builtin type or a class structure if it's not.

I also made the connector and replaceable information optional so that it's only dumped when there's something to dump, to keep the amount of data down a bit. But I'm not sure if we need this information for each class or just the root class, right now I dump it for every class.
