### ISSUE TITLE
MultiBody visualizers not drawn

### ISSUE THREAD

**Issue by anotheruserofgithub** [OpenModelica/OpenModelica#8979]
### Description

Some visualizers (surfaces) are not drawn in simulation, in particular the `Modelica.Mechanics.MultiBody.Visualizers.Torus` which would be very useful since it could be used to display bodies with spherical geometry.

For months now, as an alternative I draw 3D circular arcs by concatenating multiple `Modelica.Mechanics.MultiBody.Parts.BodyBox` at varying angles, but with very large models the translation time increases quite a lot, and anyway this does not exactly represent a segment with constant curvature (thus it is not easy to see potential collisions either).

What I am trying to achieve, by the way, is something like in [this picture](https://www.shutterstock.com/fr/image-illustration/blank-geometric-arc-element-white-isolated-1486478870), hence it would be even more wonderful if you were able to add a visualizer similar to the torus but with flat faces and straight angles instead.

This problem might be related to issue #8211.

### Steps to Reproduce

Try simulating the `Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces` example.

### Expected Behavior

All surfaces should be drawn.

### Version and OS

 - OpenModelica Version: 1.20.0~dev-61-gef01ade
 - OS: Linux Ubuntu 18.04

**Comment by casella** [comment]
@anotheruserofgithub the problem is, the original developer @vwaurich most likely doesn't have time to work on this anymore, and we are short of manpower to carry on this task. Would you like to contribute, or know someone who could? In that case, we would give you support.

**Comment by anotheruserofgithub** [comment]
Hi @casella, thank you for your reply.

For sure I can give it a try if you guys can give me some pointers, although I am not familiar with the OpenModelica code/workflow.

In fact my issue is a duplicate of #8076, I did not see it previously, sorry.
Apparently, drawing surfaces is not implemented at all...
@vwaurich gave some hints [here](https://github.com/OpenModelica/OpenModelica/issues/8076#issuecomment-987641561) on how to do it.

Probably one should implement Surfaces/ExtraSurfaces similarly to Shapes/ExtraShapes in [OMEdit/OMEditLIB/Animation](https://github.com/OpenModelica/OpenModelica/tree/master/OMEdit/OMEditLIB/Animation)?
And first save the specific simulation output variables in [VisualXML.mo](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/BackEnd/VisualXML.mo)?

**Comment by casella** [comment]
@anotheruserofgithub, let's continue the discussion in #8076, otherwise this becomes messy.

Also related to #8211.
