### ISSUE TITLE
-csvInput with constant segments

### ISSUE THREAD

**Issue by LukasKoenemann** [OpenModelica/OpenModelica#8991]
I'm using OMPython to simulate OpenModelica models within python. Therefore I use the flag "-csvInput" to specify the values of the input variables for my model. Is it possible to give omc the information how to interpolate the values of the csv-file (like in the CombiTimeTables)? Currently they will be connected piecewise linear, but I want constant segments.

**Comment by casella** [comment]
@LukasKoenemann good question. We may add some options to the runtime to change the interpretation of the input variable table. I guess this should be done in general, not only for python.

@AnHeuermann what do you think?

**Comment by AnHeuermann** [comment]
Does a csv table like

```csv
time, x
0.0, 1.0
0.5, 1.0
0.5, 2.0
1.0, 2.0
```

already work?

Basically this should trigger an event at `time=0.5` where constant `x` changes from `1` to `2`.

If this is not already working we could make it work in the runtime.

**Comment by LukasKoenemann** [comment]
Ah, okay this one works already. Thank you for the information!

**Comment by AnHeuermann** [comment]
For higher order interpolation I would suggest to use Modelica models/blocks (maybe exported to FMUs) instead of CSV files.
I don't think adding this to a Modelica tool is the right approach, when it can be modelled by Modelica itself.

Closing this issue. If someone wants spline interpolation for CSV we can open a new ticket about that.

**Comment by casella** [comment]
> For higher order interpolation I would suggest to use Modelica models/blocks (maybe exported to FMUs) instead of CSV files. I don't think adding this to a Modelica tool is the right approach, when it can be modelled by Modelica itself.

@AnHeuermann I agree with you in general, but if there are many such inputs, this could still be problematic: if you add many blocks each generating one variable, there may be a lot of duplicate code in the simulation executable, and additionally the runtime will have to figure out somehow that all these blocks generate events exactly at the same time.

On the other hand, adding only one big data generator (like CombiTimeTable) makes it non-trivial to dispatch each element in the output array to the right input. Maybe this could be done in a clean way using expandable connectors, so you have labelled inputs.
