### ISSUE TITLE
Problems with code generation in ExternalMedia

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#8995]
### Description

I hoped that the solution of #8738 would finally allow us to run ExternalMedia in OMC. Unfortunately, when I tried to run some examples with the latest nightly build, that includes those fixes, I got errors because of invalid generated C code. This is clearly a regression, because with earlier versions we could at least get to runtime.

@mahge, it would be good if you could have a look so that we finally manage to get ExternalMedia to run. Then, we can add it to the library testsuite and get it tested regularly. Thanks!

### Steps to Reproduce

Download [ExternalMedia 3.3.1](https://github.com/modelica-3rdparty/ExternalMedia/releases/tag/v3.3.1) from GitHub. Run `ExternalMedia.Test.CoolProp.CO2.TestStatesSupercritical` with the latest nightly build. You get:
```
TestStatesSupercritical_functions.c:49:53: warning: incompatible pointer types passing 'ExternalMedia_Test_CoolProp_CO2_TestStatesSupercritical_Medium_ThermodynamicState *' to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_pT_C_impl(_p_ext, _T_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                    ^~~~~~~~~~~
D:/Temp/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:171:110: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_pT_C_impl(double p, double T, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                    ^
TestStatesSupercritical_functions.c:114:65: warning: incompatible pointer types passing 'ExternalMedia_Test_CoolProp_CO2_TestStatesSupercritical_Medium_ThermodynamicState *' to parameter of type 'ExternalThermodynamicState *' (aka 'struct ExternalThermodynamicState *') [-Wincompatible-pointer-types]
  TwoPhaseMedium_setState_ph_C_impl(_p_ext, _h_ext, _phase_ext, &_state_ext, MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp1)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp2)), MMC_STRINGDATA(MMC_REFSTRINGLIT(tmp3)));
                                                                ^~~~~~~~~~~
D:/Temp/ExternalMedia 3.3.1/Resources/Include\externalmedialib.h:170:121: note: passing argument to parameter 'state' here
        EXTERNALMEDIA_EXPORT void TwoPhaseMedium_setState_ph_C_impl(double p, double h, int phase, ExternalThermodynamicState *state, const char *mediumName, const char *libraryName, const char *substanceName);
                                                                                                                               ^
TestStatesSupercritical_functions.c:195:9: error: use of undeclared identifier '_completeState1'
  _MM = _completeState1._Medium._externalFluidConstants._molarMass;
        ^
TestStatesSupercritical_functions.c:316:9: error: use of undeclared identifier '_completeState2'
  _MM = _completeState2._Medium._externalFluidConstants._molarMass;
        ^
```
Maybe this is related to #8957?

Keeping @fedetft in the loop.

**Comment by mahge** [comment]
Some clarification needed here. The [ExternalMedia 3.3.1](https://github.com/modelica-3rdparty/ExternalMedia/releases/tag/v3.3.1) linked in the issue does not have shared versions of ExternalMediaLib available. This means the FronEnd is not able to evaluate some function calls when needs to do so. 

Can you please check if the issue is still there with a shared version ExternalMediaLib available for the test setup? For me the error does not appear if I build the shared version of the ExternalMediaLib library and add it in the `Resources/Library/linux64` directory.

**Comment by casella** [comment]
@mahge, sorry, you are right. I tried the experimental version in the `v4-dev` branch and indeed it worked fine. I'm struggling a bit to cope with this thing, because there are so many things that can go wrong, but I hope we are near the end :)

**Comment by mahge** [comment]
No worries. To be fair we should find a way to detect those function evaluations that would, on failure, end up causing an error in code generation. I have no idea now how we would go about doing that but we can think about it at least. Plus I think @perost is already overloaded with things to fix. So this one can be left for later.
