### ISSUE TITLE
NF complains about missing 'each' while the prefix is actually there

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9011]
Please check [IDEAS.Buildings.Components.Examples.BuildingShadeExample](https://libraries.openmodelica.org/branches/master/IDEAS_dev/files/IDEAS_dev_IDEAS.Buildings.Components.Examples.BuildingShadeExample.err). The NF complains:
```
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/IDEAS 3.0.0-master/Buildings/Components/Shading/Overhang.mo:30:46-30:57:writable]
Notification: From here:
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/IDEAS 3.0.0-master/Buildings/Components/Shading/Overhang.mo:30:3-31:57:writable]
Error: Non-array modification ‘false‘ for array component ‘fixed‘, possibly due to missing ‘each‘.
```
but it turns out that [line 30 of Overhang.mo](https://github.com/open-ideas/IDEAS/blob/77e78819a87f5a029171b6db9d28befbcd12daf5/IDEAS/Buildings/Components/Shading/Overhang.mo#L30) actually does contain an 'each' prefix. Is it because of the `Real[4] x` declaration style, instead of `Real x[4]`?

Keeping @Mathadon in the loop.

**Comment by bilderbuchi** [comment]
That `each` was only added 10 hours ago, though: https://github.com/open-ideas/IDEAS/commit/0519fd289ae8c1f1058f35e0ee10001245469ff0#diff-050b10bb46fd2e1530a14911ae7627a1903484c61ecaa63f0d41823404395fa7R30

**Comment by Mathadon** [comment]
@bilderbuchi @casella I'm sorry it seems that the each was no there indeed.. I must have added it and then forgot that I added it :s

**Comment by casella** [comment]
Success https://libraries.openmodelica.org/branches/history/master/2022-05-23%2022:44:41..2022-05-24%2011:46:14.html 😃
