### ISSUE TITLE
ClaRa: Constant array variables not equal in connect equation

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9024]
### Description

For some array the dimension is wrong and omc fails when copying an array into another one at simulation time. This is related to #9017, but a different cause.

The problematic part could be related to `inStream`, but I have to debug more.

```Modelica
ClaRa.Basics.Media.FuelObject fuelObject(fuelModel=fuelModel,
    p=inlet.fuel.p,
    T=inStream(inlet.fuel.T_outflow),
    xi_c=inStream(inlet.fuel.xi_outflow))
```

### Steps to Reproduce

```
loadFile("/path/to/TILMediaClaRa/TILMedia/package.mo"); getErrorString();
loadFile("/path/to/clara_om/ClaRa/package.mo"); getErrorString();

simulate(ClaRa.Components.Furnace.Check.Test_CombustionChamber); getErrorString();
```

```
record SimulationResult
    resultFile = "",
    simulationOptions = "startTime = 0.0, stopTime = 10.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'ClaRa.Components.Furnace.Check.Test_CombustionChamber', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
    messages = "Simulation execution failed for model: ClaRa.Components.Furnace.Check.Test_CombustionChamber
src->dim_size[0] != dst->dim_size[0], 2 != 4
assert            | debug   | Failed to copy array. Dimension sizes are not equal and destination array is not flexible.
assert            | info    | simulation terminated by an assertion at initialization
```

### Expected Behavior

The dimensions of the arrays should align.

### Version and OS

OpenModelica Version: v1.20.0-dev-103-ge4e4270543
OS: Ubuntu Focal
Versions of used Modelica libraries: ClaRa dev version @ d931ea39e5a56704911d2d4fb78d4386e13ec553

### Additional Context

Follow-up of #9017.

**Comment by AnHeuermann** [comment]
Pretty sure the underlying problem is https://github.com/OpenModelica/OpenModelica/issues/9036.

**Comment by casella** [comment]
@AnHeuermann is C_LHV a Real array? Does it make sense to have equality checks on them?

**Comment by AnHeuermann** [comment]
Yes, it's a real array:

```Modelica
record Fuel_verbandsformel_v1
  [...]
  C_LHV={33907e3,142324e3 - 2512e3*9,-142324e3/8,0,10465e3,0,-2512e3},
  [...]
end Fuel_verbandsformel_v1
```

I guess in general that it's not a good idea to test two floating point numbers for equality. The assert is generated by omc from a connect equation:
```Modelica
connect(coalFlowSource.fuel_a,coalGas_join.fuel_inlet);
```

So we should not do that for `Real`s.

----------------

But in this case the error is valid:
```
data->simulationInfo->realParameter[186]/* coalGas_join.fuel_inlet.fuelModel.C_LHV[2] PARAM */ = 0
data->simulationInfo->realParameter[43]/* coalFlowSource.fuel_a.fuelModel.C_LHV[2] PARAM */ = 0.97499999999999998
```

**Comment by casella** [comment]
> Yes, it's a real array:
> 
> ```modelica
> record Fuel_verbandsformel_v1
>   [...]
>   C_LHV={33907e3,142324e3 - 2512e3*9,-142324e3/8,0,10465e3,0,-2512e3},
>   [...]
> end Fuel_verbandsformel_v1
> ```
> 
> I guess in general that it's not a good idea to test two floating point numbers for equality. The assert is generated by omc from a connect equation:
> 
> ```modelica
> connect(coalFlowSource.fuel_a,coalGas_join.fuel_inlet);
> ```
> 
> So we should not do that for `Real`s.

We can, but instead of if` a==b then...` we could write something like `if abs(a-b)/(max(abs(a), abs(b)), 1e-10) < 1e-10` then...

> But in this case the error is valid:
> 
> ```
> data->simulationInfo->realParameter[186]/* coalGas_join.fuel_inlet.fuelModel.C_LHV[2] PARAM */ = 0
> data->simulationInfo->realParameter[43]/* coalFlowSource.fuel_a.fuelModel.C_LHV[2] PARAM */ = 0.97499999999999998

Oops. Is this because of a frontend issue? That is where the costants are evaluated, right?

Adding @perost to the loop.

Or maybe the fuel model is not redeclared everywhere correctly?

**Comment by AnHeuermann** [comment]
I'm afraid that the fixes for https://github.com/OpenModelica/OpenModelica/issues/9036 are not good enough yet.

**Comment by AnHeuermann** [comment]
I managed to create a minimal working example.

```modelica
package MWE 
  model CombustionChamberMWE
    inner SimCenter simCenter(redeclare ExtendedRecord r);
    MWE.Left left;
    MWE.Right right;
  equation
    connect(left.con, right.con);
  end CombustionChamberMWE;

  model Left
    outer SimCenter simCenter;
    parameter BaseRecord r = simCenter.r;
    Connector con(r = r);
  end Left;
  
  model Right
    outer SimCenter simCenter;
    parameter BaseRecord r = simCenter.r;
    Connector con(r = r);
  end Right;

  record EmptyRecord
  end EmptyRecord;

  record BaseRecord
    extends EmptyRecord;
    constant Integer N_c=5;
    parameter Real C_LHV[N_c] = {1,1,1,1,1};
    constant Real defaultComposition[N_c - 1];
  end BaseRecord;

  record ExtendedRecord
    extends BaseRecord(
      N_c=3,
      C_LHV={30769230.769230768,0,-2500e3},
      defaultComposition={0.975,0.025});
  end ExtendedRecord;

  model SimCenter
    replaceable parameter ExtendedRecord r constrainedby EmptyRecord;
  end SimCenter;

  connector Connector
    parameter ExtendedRecord r = ExtendedRecord();
  end Connector;
end MWE;
```

**Comment by AnHeuermann** [comment]
I can see two issues in this example:

  1. We have `assert(left.con.r.C_LHV[2] == right.con.r.C_LHV[2], "Connected constants/parameters must be equal");`.
      In this example the values are equal (both `0`), but the generated C code cecks if `right.con.r.C_LHV[2]` is non-zero. 
  2. `left.con.r.C_LHV[2]` shouldn't be zero in the first place, but `-2500e3`.
      But I can't see generated code to initialize the parameter to that value.

**Comment by AnHeuermann** [comment]
With #9276 this seems to be fixed

```
assert            | warning | The following assertion has been violated at time 0.000000
|                 | |       | combustionChamber.flueGasOutlet.p_i[10] >= 0.0
assert            | warning | Variable violating min constraint: 0.0 <= combustionChamber.flueGasOutlet.p_i[10], has value: -691.49
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
```

**Comment by perost** [comment]
> I guess in general that it's not a good idea to test two floating point numbers for equality. The assert is generated by omc from a connect equation:
> 
> ```modelica
> connect(coalFlowSource.fuel_a,coalGas_join.fuel_inlet);
> ```
> 
> So we should not do that for `Real`s.

For Real we usually generate `abs(lhs - rhs) <= 0` instead, see `NFConnectEquations.makeEqualityAssert`. But it only handles scalars, so for arrays it will fall back to the default `lhs == rhs`.

**Comment by casella** [comment]
Nice regression testing result [here](https://libraries.openmodelica.org/branches/history/master/2022-08-04%2000:50:23..2022-08-04%2011:22:53.html)
