### ISSUE TITLE
Finalize the 1.19.0 release

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9039]
- [X] Finalize the release notes on trac https://trac.openmodelica.org/OpenModelica/wiki/ReleaseNotes/1.19.0
- [X] Move open issues to 1.19.1 and 1.20.0 release
- [x] Tag the 1.19.0 (and also the previous 1.18.1) releases on GitHub https://github.com/OpenModelica/OpenModelica/releases
- [x] Build the release for Windows 
- [x] Build the release for Linux
- [x] Update the download pages on https://openmodelica.org
- [x] Close milestone on GitHub
- [x] Make news announcement for automatic display in OMEdit welcome screen
- [x] Update the testing CI to also test 1.19.0 https://libraries.openmodelica.org/branches/overview.html
- [x] Send announcement on mailing list(s): osmc@ida.liu.se, openmodelicadevelopers, openmodelicainterest (@casella)
- [x] Send announcement on mailing list modprodannounce@ida.liu.se (@adrpo)
- [x] Send announcement on mailing list openmodelicannounce1 (@petfr)
- [x] Prepare shorter text for 1.19.0 release and send it out in OSMC Newsletter, alongside OSMC info (new members etc) (@casella, @petfr)

**Comment by bilderbuchi** [comment]
> Update the download pages on https://openmodelica.org/

FYI, the "stable development" link is the new one, but the "official release" one still points to 1.18.1 (despite the link text claiming otherwise)

**Comment by adrpo** [comment]
> > Update the download pages on https://openmodelica.org/
> 
> FYI, the Windows "stable development" link is the new one, but the "official release" one still points to 1.18.1 (despite the link text claiming otherwise)

Thanks for that! I actually thought I updated it but you need to push the update button. It should be fixed now.

**Comment by casella** [comment]
Absolutely 😄
