### ISSUE TITLE
JSON structure for components in instance API

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#9046]
@niklwors suggested that the JSON structure for components for e.g.:
```Modelica
model M
  parameter Real pi = 3;
  parameter Real e = 2;
end M;
```
might be changed to something like:
```json
"parameter": [
  {
    "name": "pi",
    "value": "4",
    "type": "real",
    "prefixes": [
      {
        "modifier": "public",
        "value": true
      },
      {
        "modifier": "final",
        "value": false
      },
      …        
    ]
  },
  {
    "name": "e",
    "value": "3",
    …
  }
]
```
For the current structure, see e.g. [GetModelInstanceAttributes1.mos](https://github.com/OpenModelica/OpenModelica/blob/master/testsuite/openmodelica/instance-API/GetModelInstanceAttributes1.mos)

There are two significant changes here. The first is to dump the components as arrays based on their variability (one for constants, one for parameters, etc.). I'm not sure if this makes sense for OMEdit though. It would also mean that we lose the component ordering, which I'm not sure matters (a workaround would be to dump an additional array with the component names in the order they're declared in, but that doesn't seem like the best solution).

The other change is to dump the prefixes as an array of objects, which again I'm not sure about. Maybe @niklwors can elaborate on why that's better. We might want to consider not dumping all the prefixes though, and only dump the ones that are different than the defaults. But I'm not sure what's best for deserialization.

**Comment by adeas31** [comment]
The order is important for OMEdit. I like the current structure. We can of course skip the default prefixes and just dump the ones that are different.

**Comment by perost** [comment]
I don't think this issue is revelant any more.
