### ISSUE TITLE
[OMEdit] Clear recent files no longer works

### ISSUE THREAD

**Issue by anotheruserofgithub** [OpenModelica/OpenModelica#9074]
It seems that the `Clear Recent Files` action does not work anymore, neither from the home screen button nor from the Files menu.
The list of files is indeed empty after clicking the button, but when OMEdit is restarted they are there again.

I saw that about two weeks ago when I compiled OMEdit locally, so I do not know if it might be because I am using two instances of OMEdit currently on my machine.

I use the nightly build on Linux, and with my own compiled version I have this bug since at least commit ff8602f.

**Comment by adeas31** [comment]
Works as expected on Windows.

Run OMEdit, clear recent files list either via home screen or from menu, close OMEdit. Open the file `omedit.ini` and see what is the value of key `files` in group `recentFilesList`.

**Comment by anotheruserofgithub** [comment]
OK, now it's working fine, I found out (joke coming -->) the root cause.

On Linux, file located at `~/.config/openmodelica/omedit.ini`.
In fact it was only writable by root user, and this is because I once launched OMEdit with `sudo` from the terminal.
This seemed weird to me when I saw that because usually I don't run OMEdit from the command line (and certainly not as root!) but from the launch icon.

But now I remember why: When I wanted to test the `ForceAndTorque` example before implementing Vector visualization, I ran into the bug that was fixed in #9018.
Before I understood what in the code was making OMEdit crash, I relied on the error log which was saying something about [ptrace scope](https://stackoverflow.com/a/32274645) and after googling I found some answer saying that instead of changing the config like suggested in this link, you could actually run as root, so I tried that (but obviously it didn't work either, hence #9018).

And I'm pretty sure I did that because I clearly remember that when you do that (`sudo OMEdit`), the graphic font is smaller and thiner than usually.

So two problems to be solved here, I think, if we want OMEdit to be perfect:
- Prevent it from displaying different fonts when running as root, or is that intentional?
- Is it possible, when running as root, to write to `omedit.ini` without making it root-only accessible? Otherwise the config is locked when you later run as normal user.

I don't know if other files are also impacted by running as root.
For the results files, it seems OK since I see two folders in `/tmp/`, one is `OpenModelica_<user>` with user permissions and the other one is `OpenModelica_root` with root permissions.

**Comment by adeas31** [comment]
`omedit.ini` is always created with user scope so perhaps you have two `omedit.ini` files, one for root and one for normal user.

As for displaying different fonts, I have no idea why. This is perhaps done by the windowing system you are using.

**Comment by casella** [comment]
I'm not a power Linux user myself, but my understanding is that the first commandment of Unix usage is: _Thou shalt not run anything as superuser, unless it is absolutely necessary_. Of course there could be some hacker's suggestions on the web to try running stuff (e.g. OMEdit) as superuser to do advanced debugging - I have nothing against that, but I guess we can live with OMEdit having some glitches in that case. In general, you are not supposed to run OMEdit as root, and I am afraid we have so many other higher priority issues to worry about, that this one has a good chance to never get fixed in the foreseeable future.

@anotheruserofgithub I hope we have your understanding 😄

**Comment by anotheruserofgithub** [comment]
Of course I understand. Fair enough ;)
