### ISSUE TITLE
OMEdit crashes if dialog is left open when quitting

### ISSUE THREAD

**Issue by perost** [OpenModelica/OpenModelica#9101]
### Description

OMEdit crashes if the user quits OMEdit while a dialog window is still open.

### Steps to Reproduce

* Open any model and e.g. instantiate or run check model on it.
* Quit OMEdit without closing the new dialog window that shows the result of the operation.
* Wait until OMEdit crashes, this can take a few seconds.

### Expected Behavior

OMEdit should not crash, and any open windows should be closed when OMEdit is shutting down.

### Version and OS
 - OpenModelica Version: master
 - OS: Linux 64-bit

**Comment by casella** [comment]
Works fine in 1.19.2-dev.beta2.
