### ISSUE TITLE
Simulation hangs during initialisation

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9120]
### Description

For the model Rexroth_Generic_Test.Hydraulics.Pipes_Hoses.Pipe_TC02 the simulation hangs during initialisiation.
The last log output is: 
```
LOG_INIT          | info    | ### START INITIALIZATION ###
LOG_INIT          | info    | updating min-values
LOG_INIT          | info    | updating max-values
LOG_INIT          | info    | updating nominal-values
LOG_INIT          | info    | updating primary start-values
LOG_LS_V          | info    | update static data of linear system solvers
LOG_INIT          | info    | initialization method: symbolic        [solves the initialization problem symbolically - default]
```

### Steps to Reproduce

Load the BRSL package: Rexroth_Generic_Test/package.mo
Simulate the model Rexroth_Generic_Test.Hydraulics.Pipes_Hoses.Pipe_Easy_TC02

### Version and OS

 - OpenModelica Version: v1.20.0-dev-119-g4241954151
 - OS: Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.1

**Comment by AnHeuermann** [comment]
Works for me. Any special simulation or compiler flags?
There are some MSL 4 vs 3.2.3 compability issues though.

```Modelica
loadModel(Modelica, {"3.2.3"}); getErrorString();
loadFile("/path/to/Rexroth_Generic_Test/package.mo"); getErrorString();
simulate(Rexroth_Generic_Test.Hydraulics.Pipes_Hoses.Pipe_Easy_TC02); getErrorString();
```

```
true
"Warning: Requested package Modelica of version 4.0.0, but this package was already loaded with version 3.2.3. There are no conversion annotations for this version but 4.0.0 is newer than 3.2.3. There is a possibility that 3.2.3 remains backwards compatible, but it is not loaded so OpenModelica cannot verify this.
"
true
"Notification: Automatically loaded package Rexroth_Generic 1.4.0 due to uses annotation.
"
""
record SimulationResult
    resultFile = "path/to/issue-9120/temp/Rexroth_Generic_Test.Hydraulics.Pipes_Hoses.Pipe_Easy_TC02_res.mat",
    simulationOptions = "startTime = 0.0, stopTime = 0.01, numberOfIntervals = 999, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'Rexroth_Generic_Test.Hydraulics.Pipes_Hoses.Pipe_Easy_TC02', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
    messages = "LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
",
    timeFrontend = 0.4983976999999999,
    timeBackend = 0.2140479,
    timeSimCode = 0.068777,
    timeTemplates = 0.2468313,
    timeCompile = 2.7641034,
    timeSimulation = 0.0738569,
    timeTotal = 3.8662259
end SimulationResult;
"Notification: Modelica requested package Complex of version 3.2.3. Complex 4.0.0 is used instead which states that it is fully compatible without conversion script needed.
Notification: Modelica requested package ModelicaServices of version 3.2.3. ModelicaServices 4.0.0 is used instead which states that it is fully compatible without conversion script needed.
Warning: Requested package Modelica of version 4.0.0, but this package was already loaded with version 3.2.3. There are no conversion annotations for this version but 4.0.0 is newer than 3.2.3. There is a possibility that 3.2.3 remains backwards compatible, but it is not loaded so OpenModelica cannot verify this.
```

**Comment by AnHeuermann** [comment]
When using MSL 4.0.0 there are some errors, but because `Rexroth_Generic_Test` requested package Modelica of version 3.2.3.

**Comment by AnHeuermann** [comment]
@niklwors updated the libraries to use MSL 4.0.0. @phannebohm and myself can give it another go, when we get the updated BRSL.

**Comment by AnHeuermann** [comment]
Sorry, I don't have the time at the moment to check on this. I have to focus on a different project at the moment.

**Comment by niklwors** [comment]
@AnHeuermann  do you had time to look into this problem? This is an important ticket for us.

**Comment by AnHeuermann** [comment]
I guess I can take a few hours this/next week to at least reproduce the error and find a clue what is the cause. But I'm not sure I can fix it.

**Comment by AnHeuermann** [comment]
I'm using BRSL v2.2dev-09-09-22 and slightly different example `Pipe_TC02.mo` provided by @niklwors.

KINSOL is looping forever for equation 3871. It seems that some iteration values become `NaN` or `inf`, but Kinsol doesn't stop/break.
Adding an error at that place sounds reasonable. I can't see why a non-linear solver should get back to a decent solution if all iteration variables become `NaN`.

This won't solve the underlying problem, but at least simulation stops.

**Comment by AnHeuermann** [comment]
Variable `pipe1.pipeSegment[50].dpRes` is becoming `inf` at one step.
```
pipe1.pipeSegment[50].dpRes = 0.5 * (pipe1.pipeSegment[50].lambda * pipe1.pipeSegment[50].l / pipe1.pipeSegment[50].dCurrent + pipe1.pipeSegment[50].zeta) * pipe1.pipeSegment[50].rho * pipe1.pipeSegment[50].vFluid * abs(pipe1.pipeSegment[50].vFluid)
```

And that is because `pipe1.pipeSegment[50].lambda` becomes `inf`. And that is because we are dividing by 0 in
```
pipe1.pipeSegment[50].lambda = if pipe1.pipeSegment[50].Re < 1187.384381946929 then 64.0 / pipe1.pipeSegment[50].Re else 0.3164 / pipe1.pipeSegment[50].Re ^ 0.25
```
where `pipe1.pipeSegment[50].Re = 0`.

I'm not sure why `DIVISION_SIM` is not an error when dividing by zero.

**Comment by niklwors** [comment]
Unfortunately, you can not close the ticket yet, because the model is not yet simulated.

**Comment by niklwors** [comment]
I have just seen that you have created a new ticket for this

**Comment by AnHeuermann** [comment]
> Unfortunately, you can not close the ticket yet, because the model is not yet simulated.

Yeah, just to keep it one problem per ticket. The endless loop is resolved, but not the underlying problem.

**Comment by casella** [comment]
> I'm using BRSL v2.2dev-09-09-22 and slightly different example `Pipe_TC02.mo` provided by @niklwors.
> 
> KINSOL is looping forever for equation 3871. It seems that some iteration values become `NaN` or `inf`, but Kinsol doesn't stop/break. Adding an error at that place sounds reasonable. I can't see why a non-linear solver should get back to a decent solution if all iteration variables become `NaN`.

Good question. You may subscribe to the kinsol mailing list and post a message there on this topic https://computing.llnl.gov/projects/sundials/mailing-list 

> This won't solve the underlying problem, but at least simulation stops.

This is correct in principle. However, as I understand we should never get to that point. Inf is the result of operations such as division by zero or log(0) or similar, that we should be catching properly with macros that throw errors. Are there any exceptions to that?

**Comment by AnHeuermann** [comment]
> Are there any exceptions to that?

Yes. `DIVISION_SIM` throws an error if dividing by zero. But not during initialization. I don't know what the reasoning behind that is.

**Comment by casella** [comment]
@AnHeuermann I guess this is a relic from the (very) old days when initialization was handled by minimizing `sum(f_i(x)^2)` using Nelder-Mead algorithm, see e.g. [this paper](https://www.researchgate.net/publication/228973312_Overdetermined_Steady-State_Initialization_Problems_in_Object-Oriented_Fluid_System_Models). That approach nicely solved overdetermined initialization problems, bu unfortunately didn't scale up well with size, so it was abandoned in favour of the same machinery that is used to bring the DAEs into ODE form for time integration, i.e. BLT, tearing etc. I guess `DIVISION_SIM` may have not been updated properly at that point.

If that was the case, I believe we should update it. Maybe @bernhardbachmann can also comment on that.

However, I am not really sure division-by-zero errors are never thrown during initialization, see e.g. [this log](https://libraries.openmodelica.org/branches/master/Buildings_latest/files/Buildings_latest_Buildings.Air.Systems.SingleZone.VAV.Examples.OptimalStart.Guideline36Summer.sim). There, I read
```
assert            | debug   | division by zero at time 15984000, (a=1555.667434820921) / (b=0), where divisor b expression is: max(-zonAHUG36Con.hvac.out.ports[3].m_flow, 1e-07) - zonAHUG36Con.sinZonFlo.ports[2].m_flow
assert            | error   | Failed to solve the initialization problem with global homotopy with equidistant step size.
assert            | debug   | Unable to solve initialization problem.
```
which obviously imply division-by-zero exceptions are thrown and caught also during initialization. Can you shed some light here?

**Comment by phannebohm** [comment]
If a strongly connected component, i.e. a single equation or an algebraic loop, is the same in the simulation system as in the initial system, then only one function call is generated and the initial system reuses it. That could be the reason for your log message.

**Comment by AnHeuermann** [comment]
Let's use #9522 to continue the discussion to have problem and discussion on one place.
