### ISSUE TITLE
Weird event interaction in simple boolean comparison

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#9140]
### Description

On [Stackoverflow ](https://stackoverflow.com/questions/72723947)someone reported the `<=` operator being broken in surprising ways. I extracted the following MWE:
```
model OM_ "MWE from https://stackoverflow.com/questions/72723947"
Boolean state1;
// Boolean state_noevent;
parameter Real threshold = 0.4;
Real f(nominal=0.5);

equation
  f = if time<1 then 0.5 else if time<3 then threshold else 0.5;
  state1 = f<=threshold;
  //state_noevent = noEvent(f<=threshold); //This works correctly when alone
annotation(
    experiment(StartTime = 0, StopTime = 10, Tolerance = 1e-06, Interval = 0.02));
end OM_;
```

`state1` should be True from time=1..3, when `f` has the value `threshold`.

Using OM 1.19.0/Win10, I instead see
![image](https://user-images.githubusercontent.com/327442/175493715-2f1cf916-e1e6-4f17-b950-e874fa2425d1.png)

It reportedly works correctly in Dymola.

Originally, I suspected floating-point issues. 
Prompted by an answer from Hans, I now think there is a weird event interaction between the changes in `f` and `state1`. I see two events in the log related to the time comparison.

When using  `state_noevent` **instead** of `state1`, the model works as expected! 

Interestingly, when using **both** `state_noevent`and `state1`, **both** show the unexpected behaviour, always False.

Maybe the event connected to time interacts badly with the one connected to `state1`?

**Comment by leo603222** [comment]
Change target language to CPP will be fine.
I think this something wrong to C generator.

**Comment by bilderbuchi** [comment]
Thank you for the workaround! I can confirm that the switch to CPP avoids the issue.
Any deeper idea what could be going wrong in the C generator?

**Comment by casella** [comment]
@AnHeuermann, @phannebohm, would you mind having a quick look? This may also affect other models as well.

Thanks!

**Comment by bilderbuchi** [comment]
Ah, so it _is_ a floating point issue after all?

> However, relying on equality among Reals in general is not a numerically robust modelling style.

I know, that's why I modified the initial example to use the same variable `threshold` instead of multiple float literals. `state1` should then trigger as `state1 = (threshold <= threshold)`, which should work despite floating-point arithmetic, no?

**Comment by bilderbuchi** [comment]
Thank you for the clarification/illustration! 
I have to say that the initial example did not come from me, but from some person on the internet (see link in the OP). It also puzzled me and I tried to put it into an MWE.

From my side the matter is clarified with "don't write Modelica like that". You can either keep the issue open to follow up on the machine epsilon question, or close it as you see fit.

**Comment by casella** [comment]
I guess we can close it for the time being. My take is that the fact that it works with the cpp runtime and not with the C runtime is purely by chance. If the original author on stackoverflow wants to reopen it with some argument, he or she is free to do that 😃
