### ISSUE TITLE
Fix configuration and build for MacOS 

### ISSUE THREAD

**Issue by mahge** [OpenModelica/OpenModelica#9145]
There are a couple of issues that need to be fixed to get MacOS support back on track. These are listed here 

## Issues that are caused by OpenModelica configuration:
- [x] macOS BUNDLEs should be installed in `Applications/` folder instead of `bin/` folder.

   - Install macOS BUNDLEs to an `Applications/` directory instead of `bin/`

  Fixed in #9155.
      
- [x] OpenScenGraph include directories.
   
    - OpenScenGraph does not provide imported targets. 
    - Manually add the include directory
    ```cmake
        target_include_directories(OMEditLib PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
    ```

  Fixed in #9150
  
- [x] `check_c_compiler_flag` used in OMCompiler/Compiler/runtime/CMakeLists.txt without including the CMake `CheckCCompilerFlag` module
  
  - add include(CheckCCompilerFlag) in .cmake/omc_utils.cmake so that it is available everywhere.

  Fixed in #9150

- [x] Expect `libOMSimulator.dynlib` instead of `libOMSimulator.so` on MacOS

  - Use `CMAKE_SHARED_LIBRARY_SUFFIX` or create a separate case for MacOS (probably not needed,
    changing the suffix should suffice.)
  - This is to be done in the external-project handling of `OMSimulator `in the file `omsimulator.cmake`

  Fixed in #9150

## Upstream issues that can be _easily_ fixed in OpenModelica

- [x] libffi generates faulty config header.
  
  -  The issue seems to be with the macro `FFI_EXEC_TRAMPOLINE_TABLE` being undefined when it should be defined to 0 or 1, i.e. `#define FFI_EXEC_TRAMPOLINE_TABLE 1`
  - The issue is manifests only with `macOS` on `aarch64` (such as M1 mac)
  - It is very likely that this is an upstream issue but probably something we can workaround in our codebase.
  - libffi **does not officially support** cmake as a configuration tools. Our version is taken from https://github.com/am11/libffi/tree/feature/cmake-build-configs in the hopes that it works well. The issue might be in that configuration.  

  Fixed in #9159.

- [x] 3rdParty/gc unknown linker flag --no-undefined. 
  
    - It is using check_c_compiler_flag to check linker flags. This will always succeed because nothing is linked.
    - The flag (and the check) is not necessary anyway for end-users. Remove it.

  Fixed in #9152

## Upstream issues which can be  _potentially_ fixed  in OpenModelica

- [x] GLDEBUGPROC is undefined in Qt's `qopenglextrafunctions.h` 
 
  - ~This seems to be a Qt and MacOS issue. There are proposed solutions [here](https://github.com/traversaro/homebrew-modelica/issues/4) and [here](https://forum.qt.io/topic/94567/gldebugproc-symbol-not-defined/4).~
  - ~There is an include sequence error where one header file defines a macro that should protect a `typedef `without actually adding the `typedef `causing subsequent headers to think that the `typedef` has already been added.   This a an educated guess and might be wrong. Unfortunately it is difficult to debug this without having a machine at hand.~
  
  - ~Potential solutions are adding the include to the relevant headers in OMEdit manually, adding the include directly to the Qt header.~

  - This probably needs to be fixed upstream to be more robust.

  ~Probably fixed in #9153. `x86_64` builds are fixed and confirmed. We need to check `arm64 `(M1 macs).~

  - The issue turned out to be a conflict between Qt and OpenSceneGraph headers.
  - Reported to the Qt tracker https://bugreports.qt.io/browse/QTBUG-104673. 
  
  - However, it is very unlikely that a fix will make it to most users soon (even if we assume that someone there accepts it is an issue and decides to fix it.).

  - A temporary solution for OpenModelica is to always add #include <QOpenGLContext> before any OSG headers.

  Fixed for OpenModelica in #9170.

## Upstream issues which _can not be_ fixed in OpenModelica

 None yet.

**Comment by mahge** [comment]
@Mathadon @JavierArroyoBastida for reference.

**Comment by hkiel** [comment]
I guess installation dir of the applications should be changed for macOS. They are now installed in e.g. `build_cmake/install_cmake/bin/OMPlot.app`, but should be in `build_cmake/install_cmake/Applications/OMPlot.app` like for the old GNU make build `build/Applications/OMPlot.app`.

**Comment by mahge** [comment]
That is okay with me. You know better about it than I do. I will fix it.

**Comment by mahge** [comment]
@hkiel The installation should be fixed #9155. Please check if everything is as it should be when you can.

**Comment by mahge** [comment]
The last remaining issue (`GLDEBUGPROC is undefined in Qt's qopenglextrafunctions.h`) has been fixed in #9170. There is also a small improvement #9171 for those of you without boost.

Hopefully everything should work out of the box for both `x86_64` and `arm64` `macOS` now.

Please update your sources to master and test when you are able to do so. If there are no more issues we can then close this ticket.

**Comment by JavierArroyoBastida** [comment]
I have updated the sources to the current master and could build and install just out of the box now. Thanks a lot @mahge!

**Comment by mahge** [comment]
@JavierArroyoBastida Glad it worked. Thank you for taking the time and helping with the debugging.
