### ISSUE TITLE
Error message "instantiation failed with no error" when missing parameter modification

### ISSUE THREAD

**Issue by matteodepascali** [OpenModelica/OpenModelica#9160]
### Description
Instantiating a model missing a required parameter modification outputs the error message:
"Internal error Instantiation of <*model name*> failed with no error message."

### Steps to reproduce
In the attached file, obtained through save total command,  the model *SourceJustPressure* can't be instantiated because of a missing parameter modification for the instance *flange*. The required paramerter is *nX*.

### Expected behavior
The error message should suggest that a parameter modification is missing.

### Attachment
[SourceJustPressureTotal.txt](https://github.com/OpenModelica/OpenModelica/files/9008225/SourceJustPressureTotal.txt)

@casella

**Comment by perost** [comment]
Instantiating the model gives the expected error message:
```
[SourceJustPressureTotal.mo:11:7-11:108:writable] Error: Could not evaluate structural parameter (or constant): flange.nX which gives dimensions of array: y. Array dimensions must be known at compile time.
```
However, when checking the model this error message is suppressed for some reason. Checking is a bit more permissive, but perhaps it's being too permissive in this case.

**Comment by perost** [comment]
The issue turned out to be that the connector balance check expected all dimensions to be evaluated and failed otherwise. For now I just turned off the check in that case, but it might be possible to handle it better by e.g. doing the check symbolically instead. But that's not exactly trivial, so for now we have to settle for just not failing.

**Comment by casella** [comment]
@perost, in fact in OMEdit we got the "no error message" thing also when trying to simulate, not only when checking. So we were a bit clueless, until we figured out we forgot a modifier to set the size of the array on the connector.

Does you fix address that?

**Comment by perost** [comment]
> @perost, in fact in OMEdit we got the "no error message" thing also when trying to simulate, not only when checking. So we were a bit clueless, until we figured out we forgot a modifier to set the size of the array on the connector.
> 
> Does you fix address that?

I can't reproduce that, in that case I just get the same error message as when instantiating the model. The frontend does nothing different when simulating compared to just flattening the model.

**Comment by matteodepascali** [comment]
I can confirm that I have the same error message @perost is getting when simulating: @casella, we might have confused which message was given in the various trials we made to understand the issue.
