### ISSUE TITLE
Wrong generated C- file names

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9175]
### Description
For some models there is an error that a file cannot be found by gcc. 
The error is: 
``` [model name]bnd_part0: file not recognized: file format not recognized```
It is probably because the suffix ".c" is missing,

### Version and OS

 - OpenModelica Version: v1.20.0-dev-173-g78ef84d254
 - OS: Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable

**Comment by adrpo** [comment]
I could 1000% bet this is the same as #9188

**Comment by adrpo** [comment]
Fixed via #9194.
