### ISSUE TITLE
Implement regression testing on maintenance releases

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9182]
#9168 shows how easy it is to introduce bugs in maintenance releases because of incomplete cherry-picks. Unfortunately we are not testing maintenance versions systematically during development, as we do for the master branch.

In that specific case we were lucky because the bug affected some other bugs that were expected to be fixed in 1.19.2, so I caught it by chance.

We need to be able to do regression testing between maintenance versions, to make sure there are only improvements there, not regressions (except perhaps those caused by out-of-memory issues).

Maybe the easiest way to get that is to implement a Jenkins job that can run the library testsuite on an arbitrary pair of commits (identified by their hash codes) and show the regressions. After all, there are not many commits in maintenance versions, so it's probably not necessary to automate this process, while it's good to have the flexibility to check between any two versions, rather than against the HEAD commit.

**Comment by adrpo** [comment]
Of course we do, see https://libraries.openmodelica.org/branches/history/v1.19/00_history.html.

**Comment by casella** [comment]
Aha, I never ventured down that rabbit hole in the the file system of libraries.openmodelica.org 😅 

And indeed there it was: https://libraries.openmodelica.org/branches/history/v1.19/2022-06-08%2023:15:49..2022-06-10%2022:19:56.html

Thanks @adrpo!

**Comment by casella** [comment]
@mahge https://libraries.openmodelica.org/branches/history/v1.19/2022-06-08%2023:15:49..2022-06-10%2022:19:56.html shows that you indeed spotted the right cause for #9168

**Comment by mahge** [comment]
I went looking and found that after you mentioned we did not have it. But then could not update you for a while. 

That helps but solves only half the problem though. We still have to figure out what is missing and that is not always as straightforward as just bisecting.  You can bisect and rebase and resolve and bisect .... but it can get complicated and frustrating quickly. Of course, it gets easier when you add some educated guesses about the commits. 

It does not hurt to be a bit more picky about which commits get picked though.

**Comment by casella** [comment]
I agree we need to be very picky. From this point of view, I'm in favour of releasing 1.20.0 early, with whatever we have in it, rather than waiting for features that may not be showing up for many months. Let's realign with the 6-months release schedule.
