### ISSUE TITLE
MM stringAppend concatenation fails in some cases

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#9188]
### Description

See #9185 and #9176

### Steps to Reproduce

Revert #9185 and then try to build the Modelica model in #9176 in OMEdit as it doesn't happen in omc.
I suspect the problem is happening because of #9064.

### Expected Behavior

String concatenation should just work.

### Version and OS

Windows 10 64bit.

**Comment by adrpo** [comment]
This seems to affect also the package manager and the way version numbers are shown in OMEdit. 
Instead of getting `4.0.0` we get `4` only.

Of course this is an issue only on 64bit Windows as on 64bit Linux size of `int` is 64bit as it should.

**Comment by adrpo** [comment]
I will revert #9064 on my computer and see if that fixes the issues we are having.

**Comment by adrpo** [comment]
The single digits versions are fixed after reverting:
![image](https://user-images.githubusercontent.com/4192979/177195009-34e00c00-1875-431d-80c6-86aca7da142a.png)

**Comment by adrpo** [comment]
The revert also fixes the concatenation issue #9188 and #9176.

**Comment by adrpo** [comment]
What should we do about it? Just revert it for now and fix it when @mahge comes back?

**Comment by mahge** [comment]
Of course. Just revert it. It was a hopeful attempt anyway. I will check if there is a way around it later but for now absolutely revert it.

**Comment by adrpo** [comment]
Of course for systems with sizeof(int) == sizeof(void*) we don't need any fix. I think for the other systems we should just make sure that we generate Modelica (an not MetaModelica) records with 32bit Integers even if we by default have 64bit Integers. I'm not sure if that is possible but is something we could try.

**Comment by adrpo** [comment]
OK. I will revert 9064 now.

**Comment by casella** [comment]
> Of course for systems with sizeof(int) == sizeof(void*) we don't need any fix. I think for the other systems we should just make sure that we generate Modelica (an not MetaModelica) records with 32bit Integers even if we by default have 64bit Integers. I'm not sure if that is possible but is something we could try.

Looks like the easiest way to stay compatible with external C functions. The other approach is to catch calls to/from external C functions and convert it on the fly. Maybe this is possible by simply putting appropriate cast operators in the generated C code?

**Comment by casella** [comment]
> > Of course for systems with sizeof(int) == sizeof(void*) we don't need any fix. I think for the other systems we should just make sure that we generate Modelica (an not MetaModelica) records with 32bit Integers even if we by default have 64bit Integers. I'm not sure if that is possible but is something we could try.
> 
> Looks like the easiest way to stay compatible with external C functions. The other approach is to catch calls to/from external C functions and convert them on the fly. Maybe this is possible by simply putting appropriate cast operators in the generated C code?

**Comment by adrpo** [comment]
I think Modelica spec should define a header with Modelica C types for all the Modelica basic types that users can use in their external libs. That way there would be no size conflicts and alignment issues (or at least less of it).

**Comment by casella** [comment]
We can make a proposal for that. But then, how should these C types actually be defined? What would be the definition of modelica_int?

**Comment by adrpo** [comment]
It doesn't really matter as long as they are used at the interface instead of other types.

This can be discussed in the MDM.

**Comment by perost** [comment]
> I think Modelica spec should define a header with Modelica C types for all the Modelica basic types that users can use in their external libs. That way there would be no size conflicts and alignment issues (or at least less of it).

Does that really solve anything? We'd still have the issue that we need to actually use the specified types instead of our own.

**Comment by perost** [comment]
> > Of course for systems with sizeof(int) == sizeof(void*) we don't need any fix. I think for the other systems we should just make sure that we generate Modelica (an not MetaModelica) records with 32bit Integers even if we by default have 64bit Integers. I'm not sure if that is possible but is something we could try.
> 
> Looks like the easiest way to stay compatible with external C functions. The other approach is to catch calls to/from external C functions and convert it on the fly. Maybe this is possible by simply putting appropriate cast operators in the generated C code?

I guess the issue might be that if we generate records with Modelica types then we could get issues when doing operations that mix our types with Modelica types. Converting to and from the correct types when calling external functions would be the cleanest solution and something we already do for arrays, but records are of course more complicated.
