### ISSUE TITLE
New API to store and restore the AST at certain points to help with OMEdit editing

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#9240]
### Description

Currently when OMEdit does an operation will:
1. getModelInstance to retrieve instantiated info about a model
2. display the dialogs or diagram based on the instantiated info and accepts edits
3. sends the edits to OMC to be applied on the AST usually as modifiers or changes in the annotations

Now if a user does undo to roll back the changes, OMEdit needs to rollback the edits previously
sent to OMC which means removing all modifications fron components, extends, etc and re-applying 
the old modifications which never really works as expected because of defaults, comments, etc.

We can do this better by having a new API that stores the AST before number 3. above  is performed 
and then undo will just change the AST back. The API can work like below:

```
sequence_number = storeAST(); // tell OMC to store the AST and give back a sequence_number (ever increasing)
success = restoreAST(sequence_number);  // tell OMC to put back the AST with the corresponding sequence_number.
```

This would not consume too much memory as it is just a list of top level elements with one of the class pointers changed but it would simplify the undo quite drastically.

1. getModelInstance to retrieve instantiated info about a model
2. display the dialogs or diagram based on the instantiated info and accepts edits
3. store the AST: `sequence_number = storeAST(); // tell OMC to store the AST and give back a sequence_number (ever increasing)`
4. sends the edits to OMC to be applied on the AST usually as modifiers or changes in the annotations

**Comment by casella** [comment]
I'm not into the details, but this looks a very good idea to me 👍

**Comment by perost** [comment]
Implemented in #9306, but I think we also need to think of a strategy to limit how much to store and not just keep storing until we run out of memory.

One solution would be to limit the API to only storing a certain number of ASTs and throw away old ones when it's full. Another would be to have some API for removing specific stored ASTs and let OMEdit handle it itself. I'm not sure what would be the best way to handle it for our purposes.

**Comment by casella** [comment]
@perost, given that only parameters and graphical annotations should be stored, is this really going to be an issue? If we start worrying about out-of-memory issues, there's 1e4 places we should take care of that...

**Comment by adrpo** [comment]
How many undo operations do we need? 
I guess we could just investigate how the memory  grows during usge and then choose the cap. 
I would say 5000 should be plenty but is better to experimentally get to a number.

**Comment by perost** [comment]
> @perost, given that only parameters and graphical annotations should be stored, is this really going to be an issue? If we start worrying about out-of-memory issues, there's 1e4 places we should take care of that...

It's a memory leak, which as a computer engineer I'm allergic to.

**Comment by perost** [comment]
#9310 limits the AST cache to an arbitrarily chosen limit of 1000 elements (because who would ever need more than 1000 levels of undo?). But the limit can of course be trivially changed if needed.

**Comment by adeas31** [comment]
#9309 implements the use of these APIs in OMEdit.

**Comment by perost** [comment]
I guess we may as well close this then.
