### ISSUE TITLE
OM Connection Editor crashes without license

### ISSUE THREAD

**Issue by wischhusen** [OpenModelica/OpenModelica#9250]
### Description

OM Connection Editor craches when the license is not found. I believe, it is a good idea to prompt an error message in this case and offer a safe exit. 

### Steps to Reproduce

Encrypt and license a library with SEMLA. Open the library without the license file or not in right place.  

### Expected Behavior

Dialog should open to explain the failure (License file is missing for library ... )

 - OpenModelica Version: 1.19.2 with encryption
 - OS: Windows 10, 64 bit

**Comment by casella** [comment]
@wischhusen can you please provide an empty library with SEMLA that we can use for testing without IP issues?

Thanks!

**Comment by adrpo** [comment]
We need a way to test the encryption stuff. I guess that would be easier if we would build and distribute with encryption by default and restrict usage via other ways.

**Comment by adrpo** [comment]
I wanted to add a test for this but currently is not possible.

**Comment by adrpo** [comment]
I will build v1.19.3 with encryption and will send you a link to test it.

**Comment by wischhusen** [comment]
Many thanks, Adrian!
--
XRG Simulation GmbH
Dr.-Ing. Stefan Wischhusen
Harburger Schlossstrasse 6-12, 3rd Floor, Rm. 318
21079 Hamburg, Germany
Tel: ++49-(0)40-766 29 26 31
Fax: ++49-(0)40-766 29 26 39
Mobile: ++49-(0)151-120 42 398
Internet: http://www.xrg-simulation.de
Linkedin: https://www.linkedin.com/in/stefan-wischhusen-2b20528b/

XRG Simulation GmbH
Sitz / Legal Domicile: Hamburg
Registergericht / Registration Court: Hamburg HR B 94129
Geschäftsleitung / Board of Management: Dr.-Ing. Stefan Wischhusen, Dipl.-Ing. Jörg Eiden, Dipl.-Ing. Ole Engel, Dipl.-Ing. Sven Rutkowski

25.07.2022 15:23:09 Adrian Pop ***@***.***>:
