### ISSUE TITLE
Symbolic jacobian dramatically improve dassl performance, but not gbode|esdirk4

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9257]
Consider the Buildings.Airflow.Multizone.Examples.ClosedDoors model. As reported in ticket #9256, turning on --generateSymbolicJacobian has a dramatic effect in reducing the number of simulation steps and jacobian recomputations when the default dassl ODE solver is used: the former goes down from 76,000 to 270, the latter from 112,000 to 84. 

Unfortunately, If I try the same comparison using the default gbode algorithm (esdirk4), I always get the same result:
```
  289 steps taken
78107 calls of functionODE
 4695 evaluations of jacobian
   56 error test failures
  224 convergence test failures
```
regardless of the presence or absence of the `--generateSymbolicJacobians` flag.

I guess there may be something fishy going on here with the way gbode handles symbolic jacobians, would you mind checking that?

Thanks!
0s time of jacobian evaluation

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
BTW, esdirk4 shows a high number of convergence issues in this test case, while DASSL has none. I suspect something wrong in the handling of the Jacobian is to blame, and maybe solving them would make those solvers a lot more robust in the handling of highly nonlinear systems, such as the continuous-time HeatingSystem benchmark.

**Comment by bernhardbachmann** [comment]
GBODE uses the symbolical jacobian, even when the flag -jacobian=coloredNumerical is set. This has been corrected now.
(see pull request: Correct handling of flag -jacobian #9278)
