### ISSUE TITLE
Installing OMOptim (Ubuntu 20.04): errors during configure and make

### ISSUE THREAD

**Issue by sitadrost** [OpenModelica/OpenModelica#9274]
I'm trying to install OMOptim on Ubuntu 20.04 (with OpenModelica 1.19.2 already installed), following the Linux build instructions given on GitHub, but I'm running into several errors.
What I did so far:
1. Check for dependencies: OpenModelica 1.19.2 (although I'm not sure about the CORBA support; I installed this years ago, using the Debian package and the instructions on the OpenModelica website), g++ 9.4.0, omniORB 4.2.2
2. Run `autoconf`: no errors there as far as I can tell
3. Run `./configure --prefix=/path/to/OPENMODELICAHOME CXX=g++`: seems alright (`exit 0`), but there are errors in the log file, like
```
configure:2884: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2895: $? = 1
configure:2884: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.

```
4. Run `make`: this results in a number of errors:
```
Cannot read /home/sita/Downloads/OMOptim/OMOptimBasis/vars.pri: No such file or directory
Project ERROR: Unknown module(s) in QT: webkitwidgets
make[1]: *** [Makefile.unix:19: Makefile] Error 3
make[1]: Leaving directory '/home/sita/Downloads/OMOptim/OMOptimBasis/build'
make: *** [Makefile:43: omoptimbasis] Error 2
```
So apparently `make` is looking for a file that doesn't exist, would that have to do with the `gcc` errors encountered by `configure`?
Also, I'm not sure what the other errors mean, or what to do about them.

From a recent post (#9259 ) I gathered that OMOptim is currently not maintained, but I was hoping that someone can help me resolve these errors anyway (after all, apparently @anotheruserofgithub managed to compile it on Linux not too long ago, so there might just be something silly/simple that I'm doing wrong here).

**Comment by sitadrost** [comment]
I forgot to mention: when I cloned OMOptim into my Downloads folder, this resulted in an empty `commons` directory, so I replaced that by the `OpenModelica-common` folder (cloned into OMOptim, renamed to `common`)

**Comment by sjoelund** [comment]
There are always errors in the config.log because it tests for flags that no longer exist, and so on. If it fails on webkitwidgets, you probably didn't install that Qt (development) module.
We stopped building OMOptim packages in 2019 because nobody was maintaining the code and it probably will break compilation on a newer OS (Qt changes and so on).

**Comment by sitadrost** [comment]
Thanks for this explanation! In that case, I think I'll try to find another solution; see how far I can get with manual parameter tweaking in OpenModelica, or fall back to my old (and painfully slow...) Python code.
