### ISSUE TITLE
Error loading MSL 3.2.3

### ISSUE THREAD

**Issue by AndreaBartolini** [OpenModelica/OpenModelica#9285]
I've installed the following libraries by using the Library Manager available in OMEdit:
- Modelica Standard Library 3.2.3
- Complex 3.2.3
- ModelicaServices 3.2.3

But trying to open the MSL 3.2.3 i got an error.

Step to reproduce the issue:
1) open OMEdit
2) File -> System Libraries -> Modelica -> 3.2.3 (post-release build maint.om)

The following pop-up is shown :

![Screenshot_20220810_102129](https://user-images.githubusercontent.com/25974985/183853530-2e9d74d4-a44e-4a01-91b7-b7b57c6e771b.png)

and the following error is thrown:
[1] 10:18:30 Scripting Notification
Automatically loaded package Complex 4.0.0 due to uses annotation.

[2] 10:18:30 Scripting Notification
Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

The option "Unload all & Reload Modelica" repeats the same issue

OMEdit - OpenModelica Connection Editor
Connected to OpenModelica 1.20.0~dev-241-g06757b1
sysop: Ubuntu 18.04

**Comment by casella** [comment]
@AndreaBartolini you can try to delete (or move elsewhere) the contents of your ~/.openmodelica directory and reinstall everything from scratch. Does that solve your problem?

**Comment by AndreaBartolini** [comment]
Tried to do it and it solves the problem... just two notes:
1) it is necessary to delete also the old installation of modelica libraries in /usr/lib/omlibrary (maybe better to show an alert about this)
2) the opening of the MSL 3.2.3 still load the 4.0.0 version of Complex and  ModelicaServices libraries while in the MSL 3.2.3 the uses annotation requires the 3.2.3 version of them

OMEdit - OpenModelica Connection Editor
Connected to OpenModelica 1.20.0~dev-250-gb17e1a0
sysop: Ubuntu 18.04

**Comment by sjoelund** [comment]
I suppose the Ubuntu packages could add a `Breaks:` directive on the old MSL packages

**Comment by casella** [comment]
> Tried to do it and it solves the problem... just two notes:
> 
>     1. it is necessary to delete also the old installation of modelica libraries in /usr/lib/omlibrary (maybe better to show an alert about this)

Yeah, this is a bit messy. Also related to #8353, which we should get done for 1.20.0. Where would you put the alert? In the [linux installation instruction page](https://openmodelica.org/download/download-linux)?

>     2. the opening of the MSL 3.2.3 still load the 4.0.0 version of Complex and  ModelicaServices libraries while in the MSL 3.2.3 the uses annotation requires the 3.2.3 version of them

This is fine, Complex and ModelicaServices 4.0.0 are backwards-compatible and this is reported by a notification.

**Comment by AndreaBartolini** [comment]
Linux installation page maybe a good place to put an alert.... better if highlighted (in red or similar).
It could be useful that also the package manager checks the presence of old installation of the libraries and rises an alert if it found them.

**Comment by sjoelund** [comment]
I wouldn't make it part of the instructions. If there is a `Breaks` directive in the package, MSL would be automatically uninstalled

**Comment by casella** [comment]
@sjoelund can you take care of that, and then we test it?

**Comment by sjoelund** [comment]
I have pushed a change to the nightly control files. When there is a new nightly build, hopefully it is built with these dependencies

**Comment by casella** [comment]
@AndreaBartolini I'm not sure if you can reproduce the old problem and check that it is solved now. I guess you should recover what you deleted in your .openmodelica directory. If you can, please check and report, otherwise I guess we need to trust @sjoelund's solution and close this ticket for good.

**Comment by AndreaBartolini** [comment]
Unfortunately I cannot reproduce the old problem...

**Comment by sjoelund** [comment]
I think that's fortunate :)
