### ISSUE TITLE
Dynamic select does not work in this case

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#9291]
### Description
I know that Dynamic select feature is not fully implemented in OpenModelica yet.
To help finalise the implementation of this feature, in this ticket I report a case in which it does not work.

### Steps to Reproduce
Use the following library
[PowerGrids.zip](https://github.com/OpenModelica/OpenModelica/files/9331684/PowerGrids.zip)
that is a modified version of PowerGrdids library 1.0.2.
The main modification consists in the addition of a feature that allows some significant values to be shown in the model diagram.
Using the above PowerGrids library, run Examples.Tutorial.GridOperation.Static.Powerflow. When run from Dymola, we get the following diagram: 
![image](https://user-images.githubusercontent.com/37046832/184500268-e0194bb4-25bc-4324-9afb-03709cae5a0e.png)

while running it from OM we get: 
![image](https://user-images.githubusercontent.com/37046832/184499994-4ed02e0f-2163-436c-b209-345b0e7cc0f2.png)

So, OM does not display the numbers.
The code requiring them to be displayed is in the icon of the transformer where the following rows are included:

      textString=DynamicSelect("P", String(portA.PPu, significantDigits=3))),
[...]
      textString=DynamicSelect("Q", String(portA.QPu, significantDigits=3))),
[...]
     textString=DynamicSelect("V", String(portA.VPu, significantDigits=3))),

### Expected Behavior
We should see the numbers as in the case of the Dymola screenshot.

### Version and OS

OM 1.19.0 Win10 64 bit
 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by adrpo** [comment]
From what I know from the implementation this case is supported so it looks like there is a bug somewhere.

**Comment by adeas31** [comment]
This works as expected.

https://user-images.githubusercontent.com/4007231/184639507-5f7e370a-3e9f-4abb-95fd-c197831194bf.mp4

**Comment by max-privato** [comment]
Why you say it works as expected? I don't see in your video the numbers on the diagram.

I'm sad that you closed this ticket so fast , not giving me the opportunity to comment. I don't know why you did so.
This does not encourage me to contribute to the Om development with tickets.

**Comment by adrpo** [comment]
Sorry @max-privato. Developers are eager to close tickets if they think it works as it should. I reopened the ticket now until you can test it again to see that is working for you. 

As far as I understand you need to open the diagram in the Plotting view to animate with the dynamic select. This is what @adeas31 has shown you with the video. After simulation when you are in the Plotting view you need to double click on the model in the tree browser to open the diagram, then click play above the variable browser. As far as I can see from your picture above you are displaying the diagram in the Modeling view where everything is static.

**Comment by adrpo** [comment]
@max-privato please publish all your issues to new tickets and we will check them properly. Do not get discouraged by ticket closing as we can easily reopen them for further discussion.

**Comment by adeas31** [comment]
> Why you say it works as expected? I don't see in your video the numbers on the diagram. Unless the numbers are correctly shown in the diagram, in my opinion, OpenModelica DOES NOT work as expected.

Because the numbers are shown correctly in the diagram window shown in the plotting perspective. If you look at the end of the video you can see the numbers replacing the alphabets.

> 
> I'm sad that you closed this ticket so fast, not giving me the opportunity to comment. I don't know why you did so. This does not encourage me to contribute to the Om development with tickets (I have some ready, but I'm not sure publishing them makes sense if the outcome is this...)

I didn't mean to discourage you by closing this ticket. I just closed it since its crystal clear to me that it works as it should. I like the feedback we get from you. It helped OM to improve over time. You are one of the users that create very good descriptive tickets. So as @adrpo said, please continue opening new issues and feel free to reopen issues for more discussion.

**Comment by max-privato** [comment]
> 
> As far as I understand you need to open the diagram in the Plotting view to animate with the dynamic select. This is what @adeas31 has shown you with the video. After simulation when you are in the Plotting view you need to double click on the model in the tree browser (or click the diagram icon in the toolbar) to open the diagram, then click play above the variable browser. As far as I can see from your picture above you are displaying the diagram in the Modeling view where everything is static.

AHA! And it was also shown in the Adeeel video.
Sorry for being too imprecise in looking at it.
Please forget about my previous message: it was totally my fault

**Comment by max-privato** [comment]
> 




> Double click will switch back to Modeling view. Always use diagram icon in the toolbar.
Ok! It was my fault. I'd just returned from holidays and my mind was maybe still on holiday ;-)

**Comment by max-privato** [comment]
> I didn't mean to discourage you by closing this ticket. 

Now I understand perfectly. As I said, it was my fault. 
> please continue opening new issues and feel free to reopen issues for more discussion.
I'll do
