### ISSUE TITLE
[NewAPI] Dump the connection annotation same as graphical annotation

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#9293]
### Description

The connection annotation is returned as json object instead of json array.

### Expected Behavior

Keep the annotation output consistent.

Instead of returning,

```
\"annotation\": {
  \"Line\": {
    \"points\": [
      [
        -54,
        22.2
      ],
      [
        -52,
        22.2
      ],
      [
        -52,
        2
      ],
      [
        30,
        2
      ],
      [
        30,
        -15.8
      ]
    ],
    \"color\": [
      255,
      0,
      0
    ]
  },
  \"Text\": {
    \"string\": \"connection text\"
  }
}
```

return in this format,

```
\"graphics\": [
  {
    \"$kind\": \"record\",
    \"name\": \"Rectangle\",
    \"elements\": [
      true,
      [
        0,
        0
      ],
      0,
      [
        255,
        0,
        0
      ],
      [
        255,
        0,
        0
      ],
      {
        \"$kind\": \"enum\",
        \"name\": \"LinePattern.Solid\",
        \"index\": 2
      },
      {
        \"$kind\": \"enum\",
        \"name\": \"FillPattern.Solid\",
        \"index\": 2
      },
      0.25,
      {
        \"$kind\": \"enum\",
        \"name\": \"BorderPattern.None\",
        \"index\": 1
      },
      [
        [
          -100,
          100
        ],
        [
          100,
          -100
        ]
      ],
      0
    ]
  }
]
```

**Comment by perost** [comment]
The issue here is that the first is a modifier like `Line(points = ...)`, while the second is something like `graphics = {Rectangle(extent = ...), ...}`. So the output is consistent, it's just that `Line` is modified while `Rectangle` is called.

I guess we could pretend that it actually says `??? = Line(points = ...)`, but we'll have to add a lot of special handling of certain modifiers in that case.

**Comment by adeas31** [comment]
But you can make elements as array instead of objects. That's all I want. Makes the parsing a lot easier.

**Comment by perost** [comment]
> But you can make elements as array instead of objects. That's all I want. Makes the parsing a lot easier.

I'm not sure what you mean, could you perhaps change the second example to show what you actually want? It's a bit confusing now since the examples are completely different rather than being the same data with different formats.

**Comment by adeas31** [comment]
Instead if dumping as,

```
\"annotation\": {
  \"Line\": {
    \"points\": [
      [
        -54,
        22.2
      ],
      [
        -52,
        22.2
      ],
      [
        -52,
        2
      ],
      [
        30,
        2
      ],
      [
        30,
        -15.8
      ]
    ],
    \"color\": [
      255,
      0,
      0
    ]
  },
  \"Text\": {
    \"string\": \"connection text\"
  }
}
```

Please dump as,

```
\"annotation\": [
  {
    \"$kind\": \"record\",
    \"name\": \"Line\",
    \"elements\": [
      true,
      [
        -45,
        21.294
      ],
      0,
      [
        [
          -54,
          22.2
        ],
        [
          -52,
          22.2
        ],
        [
          -52,
          2
        ],
        [
          30,
          2
        ],
        [
          30,
          -15.8
        ]
      ],
      [
        0,
        0,
        0
      ],
      {
        \"$kind\": \"enum\",
        \"name\": \"LinePattern.Solid\",
        \"index\": 2
      },
      0.25,
      [
        {
          \"$kind\": \"enum\",
          \"name\": \"Arrow.None\",
          \"index\": 1
        },
        {
          \"$kind\": \"enum\",
          \"name\": \"Arrow.Filled\",
          \"index\": 3
        }
      ],
      3,
      {
        \"$kind\": \"enum\",
        \"name\": \"Smooth.None\",
        \"index\": 1
      }
    ]
  }
]
```

Hope it makes some sense now.

**Comment by perost** [comment]
Ok, that's kind of what I wrote earlier. You want to treat top-level modifiers in annotations as records even if they aren't, essentially treating annotations as a list of expressions rather than a modifier. To make that work we'll have to convert them to records and instantiate them first I guess, to get the correct element order.

Also, it doesn't work if the annotation contains anything that doesn't look like a record, like `annotation(Evaluate = true)`.

**Comment by adeas31** [comment]
OK. I will add parsing for graphical objects then. Should be easy to handle in OMEdit.

**Comment by adrpo** [comment]
If you need to parse Modelica you can use the parser we have. I only used it for getting the comment from a modifier:
https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/Util/StringHandler.cpp#L1968

**Comment by perost** [comment]
> If you need to parse Modelica you can use the parser we have. I only used it for getting the comment from a modifier: https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/Util/StringHandler.cpp#L1968

That's not really an issue, we dump instantiated expressions as JSON structures regardless. This is more about the JSON structure we use when dumping annotation modifiers.

**Comment by adeas31** [comment]
Now we have 2 parsing methods for `Line` class [here](https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/Modeling/Model.h#L185) and the same for `Text` class [here](https://github.com/OpenModelica/OpenModelica/blob/master/OMEdit/OMEditLIB/Modeling/Model.h#L266).

I prefer to have only when method that parses the JSON but if its too much work on the compiler side then its fine to have it this way in OMEdit.

**Comment by adeas31** [comment]
We (me, @perost and @adrpo) had a meeting today and decided to close this issue. The current solution is fine.
