### ISSUE TITLE
OMEdit repeatedly filled memory until it crashed when opening models

### ISSUE THREAD

**Issue by darohde** [OpenModelica/OpenModelica#9328]
An official release version of OMEdit (1.19.0 I think) kept crashing when I tried to open models in the HumanComfortLib. The memory usage increased for a while until the OMEdit window simply disappeared at about 10GB of RAM usage (Windows 10 Business, 16GB RAM). I re-installed several times and also tried stable development and nightly build versions without any luck.

What helped was deleting the openmodelica folder in Users\....\AppData\Roaming after uninstalling. Unfortunately I don't have the folder anymore so I can't provide any more information and can't reproduce the error either. Maybe the uninstaller should delete the folder or at least ask to delete?

@AnHeuermann suggested that I should report this issue here.

**Comment by casella** [comment]
I'm sorry, what do you mean by "what helped"? Did removing that folder solve your problem?

**Comment by darohde** [comment]
Yes, deleting the folder after uninstalling and then reinstalling solved the problem.

**Comment by adrpo** [comment]
Probably you had the old frontend on by default.

**Comment by darohde** [comment]
I tried both old and new frontend together with Andreas when it first happened. Not sure if I switched back and forth with later versions.

**Comment by casella** [comment]
BTW, it is possible to reset OMEdit to factory settings without the need to delete folders and reinstall: Tools | Options | Reset button.
