### ISSUE TITLE
CMake FMU with external function

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9331]
### Description

When building a FMU with the CMake build, external functions are not compiled into the binaries.

### Steps to Reproduce

Create `run.mos`

```Modelica
loadString("
model externalCall
  Real x(start=1, fixed=true);
  Integer s = Modelica.Math.Random.Utilities.automaticGlobalSeed();
equation
  der(x) = -0.5*x;
end externalCall;"); getErrorString();

setCommandLineOptions("--fmuCMakeBuild=true"); getErrorString();
buildModelFMU(externalCall, platforms={"dynamic"}); getErrorString();
```

and run

```bash
$ omc run.mos
$ OMSimulator externalCall.fmu
error:   [fmiLogger] module FMICAPI: Could not load the FMU binary: /path/to/model-gflsim9f/temp/0001_externalCall/binaries/linux64/externalCall.so: undefined symbol: ModelicaRandom_automaticGlobalSeed
error:   [instantiate] Could not load "resources/0001_externalCall.fmu" which is associated with "model.root.externalCall"; it may be corrupted or may not support your platform
```

### Expected Behavior

Add library `ModelicaExternalC` to the CMakeLists.txt

### Version and OS

 - OpenModelica Version: v1.20.0-dev-268-g5c43522580
 - OS: Ubuntu Focal
 - MSL: v 4.0.0

**Comment by casella** [comment]
@mahge perhaps you can help here?

**Comment by jcramer-bc** [comment]
I found that this doesn't work with the docker build.  Should this issue be reopened?

To reproduce:

```
loadString("
model externalCall
  Real x(start=1, fixed=true);
  Integer s = Modelica.Math.Random.Utilities.automaticGlobalSeed();
equation
  der(x) = -0.5*x;
end externalCall;"); getErrorString();

setCommandLineOptions("--fmuRuntimeDepends=none"); getErrorString();
setCommandLineOptions("--fmuCMakeBuild=true"); getErrorString();

buildModelFMU(externalCall,"2.0","cs","<default>",{"x86_64-linux-gnu docker run --pull=never multiarch/crossbuild"},true); getErrorString();

```
Running `omc run.mos` produces:

with cmake:
```
-- Linking ModelicaExternalC-NOTFOUND
-- Configuring incomplete, errors occurred!
```

without cmake:
```
/usr/bin/ld: cannot find -lModelicaExternalC
collect2: error: ld returned 1 exit status
```

**Comment by AnHeuermann** [comment]
@jcramer-bc That's an interesting question, please open a new issue for this.
There are a number of problems I can see with Docker compiled CMake FMUs.

- Suitability of `multiarch/crossbuild`: CMake version is too old.
- Adding external libraries locations to Docker container.
- Cross-Compilation for external libraries that don't provide the correct binary for OS inside Docker.

We can discuss all of this in that new ticket.
