### ISSUE TITLE
Probably erroneous position of block connectors

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#9335]
### Description
I've created an empty block (only connectors. When it is loaded from Dymola the connector positions are badly changed.
I don't know if it is an OpernModelica or Dymola issue

### Steps to Reproduce
Consider the following code:

```
block Test
  Modelica.Blocks.Interfaces.RealInput u annotation (Placement(visible = true, transformation(origin = {-60, -134}, extent = {{-20, -20}, {20, 20}}, rotation = 90), iconTransformation(extent = {{-76, -140}, {-36, -100}}, rotation = 90)));
  Modelica.Blocks.Interfaces.RealInput alphaDeg annotation (Placement(
        visible = true, transformation(origin = {60, -134}, extent = {{-20, -20}, {20, 20}}, rotation = 90), iconTransformation(extent = {{44, -140}, {84, -100}}, rotation = 90)));
  Modelica.Blocks.Interfaces.BooleanOutput y annotation (Placement(
        visible = true, transformation(origin = {0, 130}, extent = {{-10, -10}, {10, 10}}, rotation = 90), iconTransformation(extent = {{-10, 100}, {10, 120}}, rotation = 90)));
equation

  annotation (Icon(coordinateSystem(preserveAspectRatio = false), graphics={  Rectangle(lineColor = {85, 0, 0}, fillColor = {255, 255, 255}, fillPattern = FillPattern.Solid, extent = {{-100, 100}, {100, -100}}),
        Text(origin = {-135, 0}, rotation = 90, lineColor = {0, 0, 255}, extent = {{-100, 21}, {100, -21}}, textString = "%name"),
        Text(extent = {{-100, 50}, {98, -46}}, textString = "SCR
fire")}), Diagram(coordinateSystem(preserveAspectRatio=false,
          extent={{-100,-120},{100,120}})));
end Test;
```

This was created using OpenModelica. Its icon has the expected appearance, i.e. the following one:
![image](https://user-images.githubusercontent.com/37046832/187189516-39f16aff-8143-4033-bd20-2a53a15b14c5.png)

When read from Dymola, the aspect is changed:
![image](https://user-images.githubusercontent.com/37046832/187188775-f56d402c-e9f4-4de8-9e84-10734c87715c.png)
I.e., the position of connectors is completely different,.

### Expected Behavior
The two icons should be similar to each other. I don't know whether this is a Dymola or OpenModelica issue.

### Version and OS
OM 1.19.0 WIn 10 63 bit

**Comment by casella** [comment]
@adeas31 can you please check?

**Comment by adeas31** [comment]
The origin is not defined in the annotation. Dymola is using the origin (0, 0) and we are using the origin as the center of the connectors. However, when I look at the Modelica specification https://specification.modelica.org/master/annotations.html#component-instance the default value for origin is (0, 0) so I guess Dymola is doing it right. I will fix this asap.

**Comment by max-privato** [comment]
> The origin is not defined in the annotation. Dymola is using the origin (0, 0) and we are using the origin as the center of the connectors. However, when I look at the Modelica specification https://specification.modelica.org/master/annotations.html#component-instance the default value for origin is (0, 0) so I guess Dymola is doing it right. I will fix this asap.

Note that I did not set any annotation manually. So it was OMEdit itself which did not define origin in the annotation

**Comment by adeas31** [comment]
Yes, that is intentional. No origin should be origin (0, 0) as I said earlier.

**Comment by max-privato** [comment]
Thanks
