### ISSUE TITLE
Bad display of parameters when formulas are used

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OpenModelica#9339]
### Description
In OM 1.19.2 when we use a formula for a parameter, the value is shown to be zero, which is very confusing. In OM 1.18.0 we did not have this issue.
Both in OM 1.18.10 and 1.19.2 the unit of measure is set to "1!, instead of being dropped.

Consider the following code:
`model Test
  Modelica.Blocks.Math.Gain gain(k = 1 / 150) 
   annotation(
    Placement(visible = true, transformation(origin = {-6, 20}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
end Test;`

It is better in OM 1.18.0, although the unit of measure should be  dropped, not set to "1":
![image](https://user-images.githubusercontent.com/37046832/188135513-1247d7ca-c3e3-4184-b38a-3c8346a0f1f6.png)
The same code implies a much worse diagram in OM 1.19.2:
![image](https://user-images.githubusercontent.com/37046832/188137391-4373950f-cbd6-4797-b9f3-8b0d8f6704fa.png)
Here we see "0" as a value!
 
### Expected Behavior

When we use a formula for a parameter we should read the formula, not "0".
Its unit of measure should be dropped, not shown as "1"

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by casella** [comment]
@max-privato I guess this is a duplicate of #8966. Please check and report.

**Comment by max-privato** [comment]
yes, it is similar. 
I just added a comment there, in particular mentioning the unit of measure, discussed here, but not considered on #8966 yet. 

Note that the example proposed by kral had as value for R just "R", which created the false impression that the display with older OM versions was bad: "K=K".
In reality it is not that bad. If the parameter to assign to "R" is "value", the string displayed is "R=value", which is ok.

I'm going to close this ticket.
