### ISSUE TITLE
Implement JSON to Expression mapping for DynamicSelect support in OMEdit

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OpenModelica#9359]
The DynamicSelect support is not implemented for the new model instance based api. We need to map the Model class data structures that are built using the instance api JSON to the Expression class.

**Comment by casella** [comment]
Yep. Too bad we just spent time doing it for the old interface, which will be (hopefully) retired soon.

**Comment by adeas31** [comment]
Now we support DynamicSelect with the JSON instance api.
