### ISSUE TITLE
Silent uninstallation leaves uninstall on Windowss registry entry behind

### ISSUE THREAD

**Issue by pjb1008** [OpenModelica/OpenModelica#9365]
### Description
After doing a silent uninstallation on Windows, it looks like the software is still installed.

This is because it leaves the following registry entry in place:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OpenModelica
As far as I can tell, all the other work required is done - it's only the registry entry left behind.

### Steps to reproduce
Install the software with ```OpenModelica-v1.19.2-64bit.exe /S```
Then remove it with ```C:\Program Files\OpenModelica1.19.2-64bit\Uninstall.exe /S```

### Expected behavior
It should remove the registry entry.

### Version and OS
 - OpenModelica Version 1.19.2
 - Windows 10 Enterprise 21H2

**Comment by casella** [comment]
@adeas31 it would be nice to fix this for 1.20.0, if it's an easy thing. Thanks!

**Comment by adeas31** [comment]
Maybe it requires a restart. We do delete the registry,

https://github.com/OpenModelica/OpenModelicaSetup/blob/master/OpenModelicaSetup.nsi#L405

**Comment by casella** [comment]
@pjb1008 please reopen the ticket if rebooting doesn't solve the problem. I wouldn't make that mandatory, I uninstall and reinstall OMC nightly builds many times a week, it is already slow enough, no need for me to also reboot at the end of uninstall.
