### ISSUE TITLE
error in optimization model constraints

### ISSUE THREAD

**Issue by LukasKoenemann** [OpenModelica/OpenModelica#9366]
I'm using `Built-in Dynamic Optimization using Annotations` to optimize my input variables. I'm modeling different components with specific limits. In each component model I define via 
```
model component
  parameter Real eta = 0.8;
  parameter Real P_max = 10;
  parameter Real f = 1;
  input Real u;
  output Real P;
  Real limit(min = 0*f, max=P_max*f) = u*f annotation(isConstraint=true);
  
  equation
    P = u*eta;
  end component;
```
bounds for the variable u. If I load multiple instances of the `component`-model, I get the error that I have defined 6 equations and 5 variables.
```
model minimal_optimization
  parameter Integer n = 2;
  input Real u_set[n];
  Real P_EG;
  component c[n];
  output Real Z = P_EG annotation(
    isLagrange = true);
equation
  0 = -50+P_EG+sum(c.P);
  for i in 1:n loop 
    u_set[i] = c[i].u;
  end for;
  annotation(
    experiment(StartTime = 0, StopTime = 5, Tolerance = 1e-08, Interval = 1),
    __OpenModelica_simulationFlags(s = "optimization", optimizerNP = "1"),
    __OpenModelica_commandLineOptions = "+g=Optimica");
end minimal_optimization;
```

The reason is, because in the outrolled equation system the condition variables are defined multiple times for each `c[i]`:
```
$con$c_limit = u[1] * c[1].f
$con$c_limit = u[2] * c[2].f 
```
the c[i] is mapped to c_ and thats why my equation system is overdeterminded, if I load the component model multiple times into my system model.

**Comment by LukasKoenemann** [comment]
is there a possibility to include the array number `[1]` in the constraint variables. For example like this:
```
$con$c_1_limit = ...
$con$c_2_limit = ...
```
Best regards, 
Lukas Koenemann

**Comment by vruge** [comment]
I suspect something is going wrong in line:

https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/BackEnd/DynamicOptimization.mo#L267

**Comment by vruge** [comment]
By the way use  [box constraints](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/optimization.html#built-in-dynamic-optimization-using-annotations) for  inputs. 

```modelica
Real limit(min = 0, max=P_max) = u;
```

**Comment by LukasKoenemann** [comment]
@vruge is there a mathematical difference between 
```
Real limit(min=0, max=P_max) = u;
```
and

```
Real limit(min = 0*f, max=P_max*f) = u*f annotation(isConstraint=true);
```
? 
In the [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/optimization.html#built-in-dynamic-optimization-using-annotations) they always use the `annotation(isContraint=true)` way. And I thought the min/max-values were only regarded by the optimization algorithm if they are added to `input` variables.

**Comment by vruge** [comment]
> @vruge is there a mathematical difference between

`annotation(isConstraint=true)` create new variable/equation `$con$name` which also fails here.
we  have a possible numerical difference for the solver. 


> ? In the [documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/optimization.html#built-in-dynamic-optimization-using-annotations) they always use the `annotation(isContraint=true)` way. And I thought the min/max-values were only regarded by the optimization algorithm if they are added to `input` variables.

(`input` and `state`)

if I am not mistaken here you have an alias equation inside the model
```modelica
u_set[i] = c[i].u;
c[i].u = c[I].limit;
```
=>  a merge of the attributes.

**Comment by vruge** [comment]
> > @vruge is there a mathematical difference between
> 
> `annotation(isConstraint=true)` create new variable/equation `$con$name` which also fails here. we have a possible numerical difference for the solver.

that was not quite correct. the suppression ( multiplication with `f`) of alias elimination make the difference

**Comment by LukasKoenemann** [comment]
> I suspect something is going wrong in line:
> 
> https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/BackEnd/DynamicOptimization.mo#L267

Is it possible to fix that problem? I got this error in multiple situation (because I'm using component-arrays often).

In my implementation it is not possible to use `min`and `max` parameter bounds (for the state/input variable), because also the  `min` and `max` values are time dependent variables, thats why I reformulate the constraints like this:
```
Real v1;
input Real v2;
Real constraints (max=0) = v2 -v1 annotation(isConstraint = true);
```
