### ISSUE TITLE
OMEdit displays the parameter values incorrectly on the icon

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9371]
### Description

When entering parameters in a component that displays the value of the parameter in the icon layer very strange things are happening when one uses the unit dropdown list. Fortunately the actual value stored in the code stays correct:.

![Peek 2022-09-14 15-21](https://user-images.githubusercontent.com/9332/190166539-3c968c58-94f3-40ab-b3eb-324a116d91e0.gif)

### Version and OS
 - OpenModelica Version: 1.20.0~dev-250-gb17e1a0
 - OS: Ubuntu Linux 22.04

**Comment by dietmarw** [comment]
Update: I actually found out that the value stored **will** be modified to the strange round-error value :-(

**Comment by bilderbuchi** [comment]
Is this a dupe of #7491? See also #8865.

**Comment by dietmarw** [comment]
Yes kind of, what missing there is that the rounding errors are actually written back to the model which is critical.

**Comment by bilderbuchi** [comment]
See #8860, then?

**Comment by dietmarw** [comment]
> See #8860, then?
Yes. So this can be set as a duplicate of #7491 and #8860

**Comment by casella** [comment]
@dietmarw all those tickets are related, and should be handled consistently using a smart library such as Ryu to handle decimal representations, see #8865. We have other higher-priority issues to fix in the next 2-3 months, but this is quite critical for usability, so we'll try to address it next year. If you want to help with the implementation, you're always welcome 😃
