### ISSUE TITLE
Feature request: "Unload all" menu item for OMEdit

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9377]
### Description

When working with different versions of one library it is often not enough to unload that library but also its dependencies. OMEdit already does unload all libraries and reloads the correct MSL version incl. its dependencies when it discovers this via the "uses" annotation. But if one like to switch independent of that (or it is not detected by OMEdit) one has to manually unload each library one by one. 

### Expected Behavior

It would be nice to have a menu entry under "File" called "Unload all". Might be nice to also have that available in the context menu of right-click in the library browser.

**Comment by casella** [comment]
LGTM, it should be easy to implement.

**Comment by dietmarw** [comment]
@adeas31 Any chance to get this in for 1.21.0?

**Comment by adeas31** [comment]
@casella shall we squeeze this in 1.20? Theoretically speaking this is an enhancement but is good to have it in 1.20

**Comment by casella** [comment]
> @casella shall we squeeze this in 1.20? Theoretically speaking this is an enhancement but is good to have it in 1.20

We have to draw a line somewhere, otherwise 1.20.0 will never be released 😅 

@dietmarw I hope you are fine getting this in 1.21.0

**Comment by dietmarw** [comment]
@casella If you look above, I never asked it to be part of 1.20.0 but was hoping for 1.21.0 :-)

**Comment by adeas31** [comment]
Yeah that is true. It was just me who thought we can get this in 1.20 :).
It seems it is better to have this in 1.21
