### ISSUE TITLE
Issue with array declaration

### ISSUE THREAD

**Issue by navasv** [OpenModelica/OpenModelica#9386]
Part of Code:
 parameter Integer NCEL=7;
Units.SI.Temperature Tpi[NCEL](start=fill(400, NCEL))
   "Wall temperature for node i";
Error:
[Non-array modification ‘false‘ for array component ‘fixed‘, possibly due to missing ‘each‘.

Modified Code(added 'each'):
 Units.SI.Temperature Tpi[NCEL](each start=fill(400, NCEL))
Error:
[Type mismatch in binding ‘start = fill(400, 7)‘, expected array dimensions [], got [7].]

Pls help to resolve this issue. I am using Thermosyspro lib on OpenModelica1.20.0.

**Comment by perost** [comment]
The first error is for some other line, notice that it says `fixed` while the declaration you're showing uses `start`. The declaration you're showing is correct, adding `each` to it makes it incorrect.
