### ISSUE TITLE
Standard Libraries Missing

### ISSUE THREAD

**Issue by jordeam** [OpenModelica/OpenModelica#9407]
### Description

Installing OpenModelica via apt in debian, not a single standard library package is available.

### Steps to Reproduce

Just follow instruction steps to install OpenModelica on Linux, available at: https://www.openmodelica.org/download/download-linux accessed in Sept 21, 2022. Contents of openmodelica.list 

```bash
$ cat /etc/apt/sources.list.d/openmodelica.list 
deb [arch=amd64 signed-by=/usr/share/keyrings/openmodelica-keyring.gpg] https://build.openmodelica.org/apt bullseye stable
```

### Expected Behavior

All libraries would be available to be installed via apt, and when OMEdit is running, the libraries panel (on the left) must show standard Modelica library, but it is not shown, and only OpenModelica system library is available. Standard libraries are not available either to install, either in the system.

### Screenshots

![image](https://user-images.githubusercontent.com/11684801/191526050-79b8f6eb-5ebc-4ba3-8317-31bf9d0d5b7a.png)

### Version and OS

 - OpenModelica Version: 1.19.3
 - Debian Linux AMD64 11 (bullseye)
 - Versions of used Modelica libraries if applicable: ??

### Additional Context

Just installing it in a fresh new Debian Linux installation.

**Comment by jordeam** [comment]
Just to add some more information, `bullseye` [Packages](https://build.openmodelica.org/apt/dists/bullseye/release/binary-amd64/Packages) as well as `buster` [Packages](https://build.openmodelica.org/apt/dists/buster/release/binary-amd64/Packages), they do not list any OM standard library. However, for `jessie`, library files are listed in its [Packages](https://build.openmodelica.org/apt/dists/jessie/release/binary-amd64/Packages) file, as it can be seen. So, since buster, they are missing.

**Comment by jordeam** [comment]
Sorry, I was using OpenModelica from an old installation and did not see that installation changed since Jessie.

**Comment by casella** [comment]
@jordeam we are changing how this is handled in the next 1.20.0 release, see #8291. The idea is to get MSL installed automatically in the user's own package manager profile using a cached version in the installation files. Then, it can be managed consistently with the package manager.

**Comment by jordeam** [comment]
@casella thanks for your answer.
