### ISSUE TITLE
‘class OMCInterface’ has no member named ‘storeAST’

### ISSUE THREAD

**Issue by ElMastro** [OpenModelica/OpenModelica#9412]
### Description

When trying to compile Openmodelica it brings out an error that is:
"OMC/OMCProxy.cpp: In member function ‘int OMCProxy::storeAST()’:
OMC/OMCProxy.cpp:3481:28: error: ‘class OMCInterface’ has no member named ‘storeAST’
 3481 |   int id = mpOMCInterface->storeAST();
      |                            ^~~~~~~~
OMC/OMCProxy.cpp: In member function ‘bool OMCProxy::restoreAST(int)’:
OMC/OMCProxy.cpp:3494:33: error: ‘class OMCInterface’ has no member named ‘restoreAST’
 3494 |   bool result = mpOMCInterface->restoreAST(id);
      |                                 ^~~~~~~~~~
make[3]: *** [Makefile:3761: OMCProxy.o] Errore 1"

### Steps to Reproduce
    #autoreconf -fi
    autoconf
    #export CPPFLAGS="$CPPFLAGS -DH5_USE_18_API"
    ./configure --prefix=/usr/ #CC=clang --with-UMFPACK CXX=clang++
    make

### Expected Behavior

It should run over make without error

### Version and OS

 - OpenModelica Version: Source from Github
 - OS: Linux, kernel 5.18
 - make: 4.3-3, gcc 12.2.0-1, clang 14.0.6-2

### Additional Context
I couldn't really find anything on what "storeAST" or RestoreAST is about. I tried modifing the paramters of autoconf and ./config but it still stops

**Comment by perost** [comment]
Try using the `--without-omc` flag with `configure` to make sure it's no picking up some old system installed `omc`.

**Comment by ElMastro** [comment]
Thank you perost. It solved my problem.
If someone will experience this same or a similar issue on linux, mine works with:
"    autoreconf -fi
    autoconf
    ./configure --prefix=/usr/ --without-omc --with-UMFPACK CC=clang"
Unfortunately I can;t make it works with "CXX=clang++", but this must be an error in my configuration
