### ISSUE TITLE
NB simulations fail because of division by zero involving parameters

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9414]
In the [newInst-newBackend ScalableTestSuite](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/ScalableTestSuite.html) report, there are many models failing because of division by zero involving parameters, e.g. [CounterCurrentHeatExchangerEquations_N_10](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/files/ScalableTestSuite_ScalableTestSuite.Thermal.HeatExchanger.ScaledExperiments.CounterCurrentHeatExchangerEquations_N_10.sim) or [OneDHeatTransfer_TT_FD](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/files/ScalableTestSuite_ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_FD_N_10.sim).

@kabdelhak, I guess that's because of some bug in code generation, I would suggest you to have a quick look.

**Comment by casella** [comment]
This seems to be related to the following error reported by the new backend in all those models:
```
Error: Internal error NBResolveSingularities.balanceInitialization failed because following non-fixable variables could not be solved:
        [DER-] (10) Real[10] $DER.T
```

**Comment by hkiel** [comment]
A MWE for the above NB error is the following model, which works fine for the old backend. It works again if you replace the second equation by `y = der(sin(time));`
```modelica
model test
  Real x;
  Real y;
equation
  x = sin(time);
  y = der(x);
end test;
```

**Comment by casella** [comment]
@kabdelhak, here is the [regression report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2022-12-15%2015:10:03..2022-12-16%2017:18:05.html) after your PRs #9953 and #9954. Note that most of the regressions are in Buildings_8 because Martin removed the reference files, that were not appropriate for that version of the library.

The results are encouraging, but we are still not there. The `OneDHeatTransferTI_Modelica` and `OneDHeatTransferTT_Modelica` models now simulate, but unfortunately the `OneDHeatTransfer_TI_FD` and `OneDHeatTransfer_TT_FD` still fail because of division by zero, and so still do all the heat exchanger models.

Furthermore, the simulation performance shows that there is some problem with wrong ODE Jacobians, similarly to #9843.

For example, `ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_Modelica_N_320` has these [simulation statistics](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_Modelica_N_320.sim) with the new backend
```
LOG_STATS         | info    | ### STATISTICS ###
|                 | |       | | timer
|                 | |       | | |    0.0346164s          reading init.xml
|                 | |       | | |   0.00147384s          reading info.xml
|                 | |       | | |  0.000869611s [  0.0%] pre-initialization
|                 | |       | | |   0.00015479s [  0.0%] initialization
|                 | |       | | |    0.0440796s [  0.0%] steps
|                 | |       | | |      174.009s [ 90.2%] solver (excl. callbacks)
|                 | |       | | |    0.0939878s [  0.0%] creating output-file
|                 | |       | | |   0.00179789s [  0.0%] event-handling
|                 | |       | | |   0.00280491s [  0.0%] overhead
|                 | |       | | |      18.7898s [  9.7%] simulation
|                 | |       | | |      192.942s [100.0%] total
|                 | |       | | events
|                 | |       | | |     0 state events
|                 | |       | | |     0 time events
|                 | |       | | solver: dassl
|                 | |       | | | 467125 steps taken
|                 | |       | | | 935978 calls of functionODE
|                 | |       | | | 700610 evaluations of jacobian
|                 | |       | | |     0 error test failures
|                 | |       | | | 233533 convergence test failures
```
while it has [these ones](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_Modelica_N_320.sim) 
```
LOG_STATS         | info    | ### STATISTICS ###
|                 | |       | | timer
|                 | |       | | |    0.0433434s          reading init.xml
|                 | |       | | |   0.00263026s          reading info.xml
|                 | |       | | |   0.00109046s [  0.8%] pre-initialization
|                 | |       | | |  0.000323908s [  0.2%] initialization
|                 | |       | | |   1.9767e-05s [  0.0%] steps
|                 | |       | | |    0.0219177s [ 16.2%] solver (excl. callbacks)
|                 | |       | | |    0.0127131s [  9.4%] creating output-file
|                 | |       | | |  0.000248615s [  0.2%] event-handling
|                 | |       | | |   0.00105418s [  0.8%] overhead
|                 | |       | | |    0.0976644s [ 72.3%] simulation
|                 | |       | | |     0.135032s [100.0%] total
|                 | |       | | events
|                 | |       | | |     0 state events
|                 | |       | | |     0 time events
|                 | |       | | solver: dassl
|                 | |       | | |   193 steps taken
|                 | |       | | |   223 calls of functionODE
|                 | |       | | |    25 evaluations of jacobian
|                 | |       | | |     2 error test failures
|                 | |       | | |     0 convergence test failures
```
with the old backend. As explained in #9843, the problem here is that the Jacobian is not computed correctly, so the convergence of the BDF algorithm, which depends on (I - h*df/dx), is hampered if h is not very small, forcing the solver to take many very short steps. Please check the values of the jacobian with the smallest test and compare it to the new backend case.

**Comment by kabdelhak** [comment]
I now understand why this does not work. It requires index reduction for balanced initialization which is not yet implemented in the new backend.

```
  x = sin(time);
  y = cos(time); 
  der(x) = y;
```
or 
```
  x = sin(time);
  der(x) = cos(time); 
  y = der(x);
```
is how this should be solved. The second equation is the result of differentiating the first one due to no unknown being present. I do have a work in progress solution for index reduction, but i have to clean it up to make future work regarding arrays easier.

**Comment by casella** [comment]
@kabdelhak I'm not sure I understand. 

This is the `OneDHeatTransferTI_FD` model, which is one of the models failing at runtime:
```modelica
model OneDHeatTransferTI_FD
  "One end at a fixed temperature, one end is insulated; implemented by FD method"
  import SIunits = Modelica.Units.SI;
  parameter SIunits.Length L "Length";
  parameter Integer N = 2 "number of nodes";
  parameter SIunits.Temperature T0 "Initial temperature";
  parameter SIunits.Temperature TN "Temperature at the last node";
  parameter SIunits.SpecificHeatCapacity cp "Material Heat Capacity";
  parameter SIunits.ThermalConductivity lambda
    "Material thermal conductivity";
  parameter Modelica.Units.SI.Density rho "Material Density";
  final parameter Modelica.Units.SI.Length dx=L/(N - 1) "Element length";
  SIunits.Temperature T[N] "temperature of the nodes";
initial equation
  for i in 1:N - 1 loop
    T[i] = T0;
  end for;
equation
  T[N] = TN;
  for i in 2:N - 1 loop
    der(T[i]) = lambda * ((T[i + 1] - T[i]) / dx + ((-T[i]) + T[i - 1]) / dx) / cp / rho / dx;
  end for;
  der(T[1]) = lambda * ((T[2] - T[1]) / dx) / cp / rho / dx;
end OneDHeatTransferTI_FD;
```
This is an index-0 ODE model, with state vector T[1:N-1] and explicit initial equations setting their initial values to a parameter. I don't understand why index reduction should be required, nor why your example with sin(time) and cos(time) should be relevant. The only tricky point could be that we have an array, but only a slice of it is actually a state. Is that a problem?

The runtime error is
```
division by zero in partial equation: dx
|                 | |       | at Time=0.000000
```
it seems to me that for some reason the binding equation dx=L/(N - 1) is not computed before dx is used.

Are we on the same page?

**Comment by kabdelhak** [comment]
> Are we on the same page?

My comments referred to the MWE by hkiel, i thought it represents the same problem.

Regarding the proposed model `ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_Modelica_N_10` (smaller version): It is an older problem which i mentioned to you last summer. The new backend currently cannot handle mixed state arrays. Only index 1-9 of `T` are states and index 10 is not. The following model works fine with the new backend making use of dummy variables to represent the state slice. 
```
model OneDHeatTransferTI_FD
  "One end at a fixed temperature, one end is insulated; implemented by FD method"
  import SIunits =
         Modelica.Units.SI;
  parameter SIunits.Length L "Length";
  parameter Integer N = 2 "number of nodes";
  parameter SIunits.Temperature T0 "Initial temperature";
  parameter SIunits.Temperature TN "Temperature at the last node";
  parameter SIunits.SpecificHeatCapacity cp "Material Heat Capacity";
  parameter SIunits.ThermalConductivity lambda
    "Material thermal conductivity";
  parameter Modelica.Units.SI.Density rho "Material Density";
  parameter Modelica.Units.SI.Length dx=L/(N - 1) "Element length";
  SIunits.Temperature T[N] "temperature of the nodes";
  SIunits.Temperature X[N-1] "temperature of the nodes";
initial equation
  for i in 1:N - 1 loop
    T[i] = T0;
  end for;
equation
  T[N] = TN;
  for i in 1:N - 1 loop
    X[i] = T[i];
  end for;
  for i in 2:N - 1 loop
    der(X[i]) = lambda * ((T[i + 1] - T[i]) / dx + ((-T[i]) + T[i - 1]) / dx) / cp / rho / dx;
  end for;
  der(X[1]) = lambda * ((T[2] - T[1]) / dx) / cp / rho / dx;
end OneDHeatTransferTI_FD;
```

I did not yet decide on how to handle sliced array states in the new backend and we agreed on postponing that to when we handle index reduction since that is closely related to one another.

@casella would it be fine for now to update the scalable testsuite accordingly? and might this be the issue for other real models as well?

**Comment by casella** [comment]
> Regarding the proposed model `ScalableTestSuite.Thermal.HeatConduction.ScaledExperiments.OneDHeatTransferTT_Modelica_N_10` (smaller version): It is an older problem which i mentioned to you last summer. 

I apologize, but there are really too many pending issues, and often they differ in intricate and subtle ways. We need to keep track of it in writing in these tickets 😅 

> The new backend currently cannot handle mixed state arrays. Only index 1-9 of `T` are states and index 10 is not. The following model works fine with the new backend making use of dummy variables to represent the state slice.

OK, good.

> ```
> model OneDHeatTransferTI_FD
>   "One end at a fixed temperature, one end is insulated; implemented by FD method"
>   import SIunits =
>          Modelica.Units.SI;
>   parameter SIunits.Length L "Length";
>   parameter Integer N = 2 "number of nodes";
>   parameter SIunits.Temperature T0 "Initial temperature";
>   parameter SIunits.Temperature TN "Temperature at the last node";
>   parameter SIunits.SpecificHeatCapacity cp "Material Heat Capacity";
>   parameter SIunits.ThermalConductivity lambda
>     "Material thermal conductivity";
>   parameter Modelica.Units.SI.Density rho "Material Density";
>   parameter Modelica.Units.SI.Length dx=L/(N - 1) "Element length";
>   SIunits.Temperature T[N] "temperature of the nodes";
>   SIunits.Temperature X[N-1] "temperature of the nodes";
> initial equation
>   for i in 1:N - 1 loop
>     T[i] = T0;
>   end for;
> equation
>   T[N] = TN;
>   for i in 1:N - 1 loop
>     X[i] = T[i];
>   end for;
>   for i in 2:N - 1 loop
>     der(X[i]) = lambda * ((T[i + 1] - T[i]) / dx + ((-T[i]) + T[i - 1]) / dx) / cp / rho / dx;
>   end for;
>   der(X[1]) = lambda * ((T[2] - T[1]) / dx) / cp / rho / dx;
> end OneDHeatTransferTI_FD;
> ```

Excellent.

> I did not yet decide on how to handle sliced array states in the new backend and we agreed on postponing that to when we handle index reduction since that is closely related to one another.

Sure. Quaternions in the MultiBody library are a nice example of that. Though I guess the case in question here is a really trivial one.

> @casella would it be fine for now to update the scalable testsuite accordingly?

Absolutely. The point of ScalableTestSuite is to stress compilers with increasingly large models, not necessarily to check how well array-preserving models can handle complicated sliced matching and index reduction. BTW:
-  when this library was written, array-preserving stuff was the realm of science fiction, so we didn't care about this issue too much
- in fact, in cases such as this one it may make lots of sense to define a separate array for the states; this is handy, e.g., to handle start, fixed, and stateSelect attributes without contortions.

It may be useful to also have models to test sliced variable arrays, but that's a different purpose than ScalableTestSuite's.

I understand array-preserving index reduction is probably the most challenging topic in array-preserving code generation, and there are lots of very interesting problems (e.g. power grid models, thermal chip models) where this is really not necessary and the choice of states is trivial. It definitely makes sense to start testing them first without worrying about this issue. 

I will update ScalableTestSuite myself, making sure that all the tests that do not involve index reduction do not have sliced 

> and might this be the issue for other real models as well?

I will check.

Thanks!

**Comment by casella** [comment]
After updating ScalableTestSuite to avoid arrays containing both state and non-state variables, this problem is solved both in heat transfer and heat exchanger models
