### ISSUE TITLE
Case sensitive file names in Modelica library prevents loading

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9421]
### Description

I can't load ClaRa v1.8.0. The problem is that the file `testReheater.mo` should be named `TestReheater.mo` / the names in `package.order` are case sensitive.

I'm not sure if OpenModelica should be that picky. Maybe this is a Windows only issue.

### Steps to Reproduce

Download ClaRa v1.8.0 using the package manager or clone https://github.com/ClaRaLibrary/ClaRa.
Load the library in OMedit:

```
[6] 14:09:49 Grammar Warning
[C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/Components/Control/PredictorModels_3508/Check/package.order: 0:0-0:0]: The package.order file does not list all .mo files and directories (containing package.mo) present in its directory.
Missing names are:
        testReheater

[7] 14:09:49 Scripting Warning
[C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries/ClaRa 1.8.0-master/Components/Control/PredictorModels_3508/Check/testReheater.mo: 2:1-117:17]: Expected the package to have name testReheater, but got TestReheater. Proceeding since only the case of the names are different.

[8] 14:09:50 Translation Error
[C:/dev/OM64bit/OMCompiler/Compiler/FrontEnd/ClassLoader.mo: 802:11-802:186]: Internal error HashTable missing file C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/Components/Control/PredictorModels_3508/Check/TestReheater.mo - all entries include:
C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/Basics/Choices/package.mo
C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/Basics/Choices/Position.mo
[...]
C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/package.mo
C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries//ClaRa 1.8.0-master/SimCenter.mo

[9] 14:09:50 Scripting Error
Failed to load package ClaRa (1.8.0-master) using MODELICAPATH C:/Users/USERNAME/AppData/Roaming/.openmodelica/libraries/;C:/Program Files/OpenModelica1.20.0-dev-64bit/lib/omlibrary.
```

### Expected Behavior

Issue a warning and load the library any way.

### Version and OS

 - OpenModelica Version: v1.20.0-dev-303-g30328835ce
 - OS: Windows 10
 - Versions of used Modelica libraries:
   - ClaRa v1.8.0 (SHA 950f1712b02297932e388e65d18e958b4179f643) from https://github.com/ClaRaLibrary/ClaRa.git

### Additional Context

Dymola can handle the library just fine.
Out nightly tests on Linux can load the library as well.

**Comment by AnHeuermann** [comment]
I have this issue also on Ubuntu, so it's not a Windows only issue.

**Comment by casella** [comment]
@AnHeuermann [Section 13.4.2](https://specification.modelica.org/maint/3.5/packages.html#mapping-a-package-class-hierarchy-into-a-single-file-nonstructured-entity) of the language spec is pretty clear:

> When mapping a package or class-hierarchy to a file (e.g. the file A.mo), that file shall only define a single class A **with a name matching the name of the nonstructured entity**. In a file hierarchy the files shall have the extension .mo.

Since Modelica class names are case-sensitive, it follows quite obviously that the file names also should be. There is no mention of case-insensitive file name handling in the spec. Particularly for Linux :)

I guess the best solution for this ticket is to correct the file name in the ClaRa package. Can you do that?

**Comment by AnHeuermann** [comment]
I opened a ticket for it and changed it myself on my clone. It is already fixed in ClaRa_dev, but apparently the changes are not included in the public release on https://github.com/ClaRaLibrary/ClaRa.
