### ISSUE TITLE
External C lib dependency not contained in FMU export

### ISSUE THREAD

**Issue by pstelzig** [OpenModelica/OpenModelica#9424]
### Description

When exporting a Modelica model that has an external C library dependency to FMU, the library it depends on is not included in the FMU. Instead, the resulting <Model name>.so of the FMU has in its `rpath` a hard coded path to the original library dependency. 

This makes it basically impossible to move the FMU from one computer to another. 

#### Reproducing the problem
Assume to work in Ubuntu 22.04 or xubuntu 22.04. Create a folder `FmuWithSharedLibDep` and place two files in there: `package.mo` and `externalfunc.c`

Content of `package.mo`
```modelica
package FmuWithSharedLibDep
  extends Modelica.Icons.Package;

  model ModelWithExternalLib
    extends Modelica.Blocks.Interfaces.SISO;

    function Multiplier
      input Real x;
      input Real m;
      output Real y;
    
      external "C" y = multiply(x, m) annotation(
        Library = "externalfunc");
    end Multiplier;

    parameter Real m = 2.0;
  equation
    y = Multiplier(u, m);
  end ModelWithExternalLib;
end FmuWithSharedLibDep;
```

Content of `externalfunc.c`
```c
double multiply(double x, double m)
{
    return m*x;
}
```

Then run from this folder `FmuWithSharedLibDep`
```
$ mkdir -p ./Resources/Library
$ gcc -shared -fPIC -o ./Resources/Library/libexternalfunc.so externalfunc.c 
```

Open OMEdit and do "File->Load Library" and select `FmuWithSharedLibDep/package.mo`. Then with `FmuWithSharedLibDep.ModelWithExternalLib` open click "File->Export->FMU". OMEdit will successfully export a FMU file. 

**Important: Now delete the `Resources/Library/libexternalfunc.so`** you generated before, to mimick another computer where this file is not present. A look in the FMU will reveal that it does not contain any `libexternalfunc.so`, but running `ldd FmuWithSharedLibDep_ModelWithExternalLib.so` on the .so in the FMU will reveal its `rpath` pointing to the absolute path of the `Resources/Library/libexternalfunc.so` created before. 

When importing this FMU into a new SSP file, saving as `sharedlibcosim.ssp` and running

```bash
/usr/bin/../bin/OMSimulatorPython3 /usr/bin/../share/OMSimulator/scripts/OMSimulatorServer.py --model=<your dir to>/sharedlibcosim.ssp --endpoint-pub=tcp://127.0.0.1:42201 --logLevel=0
```

the simulation will fail with something like 

```bash
error:   [fmiLogger] module FMICAPI: Could not load the FMU binary: libexternalfunc.so: cannot open shared object file: No such file or directory
```

#### Manual fix
One can add the missing `libexternalfunc.so` manually to the FMU and change the `rpath` of the FMU's .so file.  

Extract `FmuWithSharedLibDep.ModelWithExternalLib.fmu` to some folder `<manualcorrection>`, copy the `FmuWithSharedLibDep/Resources/Library/libexternalfunc.so` you compiled manually before to `<manualcorrection>/binaries/linux64` so that `libexternalfunc.so` and `FmuWithSharedLibDep_ModelWithExternalLib.so` are side by side. 

Next, run `chrpath --list FmuWithSharedLibDep_ModelWithExternalLib.so`, copy the string after `RPATH=` to a text editor and replace the absolute folder containing the original `libexternalfunc.so`, i.e. `<some local path>/FmuWithSharedLibDep/Resources/Library/linux64:<some local path>/FmuWithSharedLibDep/Resources/Library` simply with `./`. 
Then apply this new string as the `RPATH` like
```
chrpath -r <your new RPATH> FmuWithSharedLibDep_ModelWithExternalLib.so
```

To check, run `ldd FmuWithSharedLibDep_ModelWithExternalLib.so` which will print something like `libexternalfunc.so => ./libexternalfunc.so (...)` 

Then, you can zip the entire extracted and manipulated FMU again. 

Again delete the original `FmuWithSharedLibDep/Resources/Library/libexternalfunc.so` you compiled. 

Close OMEdit and repoen OMEdit. If you repeat the simulation steps up to `sharedlibcosim.ssp` as above, this time the simulation will run without error.

### Expected Behavior

Exporting a Modelica model with an external C library dependency to FMU should result in an FMU that runs on another computer. It should contain the external library dependency and have the library's search path set up correctly.

### Version and OS

 - OpenModelica Version: 1.19.2
 - OS: Ubuntu 22.04, 64bit and xubuntu 22.04, 64bit

### Additional Context
Workaround basically same to my previous #7005

**Comment by casella** [comment]
@pstelzig one comment on this, stemming from a discussion I had with Andreas Junghanns some time ago. In some cases, it is expected that FMUs use system-installed external libraries, rather than libraries that are shipped with the FMU. This is crucial in corporate environments that have strict rules regarding cybersecurity, mandating that certain libraries are updated regularly. Using old versions of libraries shipped with the FMU that may contain security threats may not be acceptable.

This is just to note that the issue of dependencies of FMUs is a bit complicated, and unfortunately not fully specified by the standard. I'm not sure if FMI 3.0 has addressed these issues more specifically.

**Comment by pstelzig** [comment]
@casella Thanks for the insight! 

Having come from a corporate background myself I can see the reasoning in this direction of thought. It does however restrict the ability to move FMUs from one machine to another. Well, I suppose there is no free lunch indeed. 

My use case is a little different: I have external C libraries which contain extensions to the mathematics of the surronding Modelica model and were just easier to implement in C and C++ rather than in plain Modelica. 

Well, for the moment we do have our workaround. Just add whathever shared object library you need to ship by hand to the FMU, then -- at least for Linux -- change the search paths and then zip everything. 

Maybe the issue of dependency management is indeed something where the FMI standard should at least give guidance on how tools should implement a choice. 

Like: 
1. On export the simulation tool lists all dependencies to shared libs the FMU has
2. Simulation tool lets user choose which ones to include in exported FMU
3. FMI standard has a dependency tree according to which an FMU tells the importing tool which lib to use from the FMU and which must be provided

I would guess that e.g. Linux dependency management systems like aptitude could serve as an example here.

**Comment by AnHeuermann** [comment]
In case you want to play around a bit and if you are more familiar with CMake instead of Makefiles you can use the [--fmuCMakeBuild](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-fmucmakebuild) compiler flag to create CMake FMUs.

For me it is simpler to change and re-compile those FMUs.

**Comment by AnHeuermann** [comment]
I'll try to add something to CMake FMUs to copy at least the external C libraries from the `LIBRARY/Resources/Library/` directory. I need it for ClaRa CMake FMUs.

My minimal example using ClaRa_dev:

```modelica
loadFile("/path/to/ClaRa/package.mo"); getErrorString();
cd("temp"); getErrorString();
setCommandLineOptions("--fmuCMakeBuild=true"); getErrorString();
buildModelFMU(ClaRa.Components.Furnace.Check.Test_CombustionChamber_vs_Burner_control, platforms={"dynamic"}); getErrorString();
```

A different solution could be to compile everything statically into the FMU, but that's not really simpler.

**Comment by AnHeuermann** [comment]
I have something working, but it's very simple and getting ugly very quickly. I'm copying the linked library into the binary directory, which needs to be added to rpath.

If you use symbolic links for your linked external library (which is very common on Unix systems, e.g. `libmylib.so --> libmylib.1.so`, `libmylib.1.so`, ...) it can happen that only the link is copied (I guess). Also if the copied library itself has dependencies I'm not sure that that one get's copied.

```cmake
find_library(TILMedia180ClaRa
             NAMES TILMedia180ClaRa
             PATHS [...]
                   "/path/to/.openmodelica/libraries/TILMedia 1.8.0-ClaRa/Resources/Library/x86_64-linux"
                   "/path/to/.openmodelica/libraries/TILMedia 1.8.0-ClaRa/Resources/Library/linux64"
                   "/path/to/.openmodelica/libraries/TILMedia 1.8.0-ClaRa/Resources/Library"
                   [...])
message(STATUS "Linking ${TILMedia180ClaRa}")
target_link_libraries(${FMU_NAME} PRIVATE ${TILMedia180ClaRa})
message(STATUS "Copying ${TILMedia180ClaRa} into binaries/")
file(COPY ${TILMedia180ClaRa}
           DESTINATION ${CMAKE_INSTALL_LIBDIR})
```

There is for sure a nice CMake solution for this, but I'm not advanced enough in CMake for that.
And for source-code FMUs we would like to copy all of the `Resources/Library/` directories into the `FMU/resources` directory.
@mahge any idea on this one?

**Comment by AnHeuermann** [comment]
@pstelzig Your provided example (btw. very nice example ❤️) works with https://github.com/OpenModelica/OpenModelica/pull/9441.

The ClaRa FMU segfaults, but that's an issue in itself.

**Comment by bilderbuchi** [comment]
> There is for sure a nice CMake solution for this, but I'm not advanced enough in CMake for that.

I'm not sure what "this" is that you're looking for, but for copying libraries around I have used [`add_custom_command`](https://cmake.org/cmake/help/v3.21/command/add_custom_command.html) previously, which gives you a bit more control over timing/relationships:
```
add_custom_command(
  COMMENT "Copy the built module..."
  COMMAND ${CMAKE_COMMAND} -E copy ${libraryname} ${CMAKE_SOURCE_DIR}/foo/${libraryname}
  DEPENDS ...
  OUTPUT ${CMAKE_SOURCE_DIR}/foo/${libraryname}
)
```

**Comment by AnHeuermann** [comment]
> add_custom_command(
  COMMENT "Copy the built module..."
  COMMAND ${CMAKE_COMMAND} -E copy ${libraryname} ${CMAKE_SOURCE_DIR}/foo/${libraryname}
  DEPENDS ...
  OUTPUT ${CMAKE_SOURCE_DIR}/foo/${libraryname}
)

I saw that on StackOverflow as well. It's a question of when we want to copy the libraries and all of its dependencies. In this case it is copied after compilation. But I think we should link against the copied library in the first place, to validate everything is working correctly. So maybe calling `find_library()`, copy found library, use `find_library()` on copied library and use that one to compile / link.

**Comment by pstelzig** [comment]
@AnHeuermann Thanks for the hint with the CMake FMUs in OpenModelica. I was not aware of that! 

I'm pretty sure you are right, too, in that the manual copying of a library into an FMU does not solve the problem of that library potentially having again other dependencies. Indeed this could become ugly pretty quickly. 

I usually run `ldd` to find out about lib dependencies of an FMU's shared library, but afaik `ldd` is not recursive. CMake `find_library` -- never used it before -- still requires to specify the sought after library name, correct? Apparently there was something similar to `ldd` in CMake called [`GetPrerequisites`](https://cmake.org/cmake/help/latest/module/GetPrerequisites.html) , but this has been deprecated in favor of [`file(GET_RUNTIME_DEPENDENCIES)`](https://cmake.org/cmake/help/latest/command/file.html#command:file). No idea yet whether this works recursively.

**Comment by casella** [comment]
@AnHeuermann this information you posted here is precious! However, it is difficult to find out.

It would be great if it ended up [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/fmitlm.html). Do you think you could write a short primer on how to handle these library dependency issues and put it there? This would be very helpful for a lot of people.

**Comment by pstelzig** [comment]
@casella 
You are right. The main problem with dependencies was that the lib referenced by external "C" was not there. What exotic dependencies that in turn might have I guess the modeler could for now sort out on his own. 

@AnHeuermann
If I understand your nice solution correctly, all libraries that are mentioned in the library annotation of an external "C" function in Modelica code would be copied over into the FMU's `binaries/<OS>` folder on export, as long as one uses CMake FMUs and the libraries mentioned in the annotations could be found by CMake's `find_library`. And `find_library` would also look into the common relative search paths for Modelica external "C" functions, like `./Resources/Library`. Is that correct?

E.g. if I wrote

```modelica
external "C" y = multiply(x, m) annotation(
        Library = "externalfunc, yetanotherlib");
```

then the CMake FMU would in the (Linux) build look for `libexternalfunc.so` and `libyetanotherlib.so` by means of `find_library`, and if they are in one of the search paths `find_library` looks into, would copy them over into the FMU. 

If that is the case, then I would be *really* happy because that would exactly solve my and probably many other use cases!

**Comment by bilderbuchi** [comment]
It seems to me like the `install` command [here](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/fmi/export/buildproject/CMakeLists.txt.in#L61-L64) needs to also have the [`RUNTIME_DEPENDENCIES` option](https://cmake.org/cmake/help/latest/command/install.html#install-targets):
> RUNTIME_DEPENDENCIES

 >   New in version 3.21.

>    This option causes all runtime dependencies of installed executable, shared library, and module targets to be installed along with the targets themselves. The RUNTIME, LIBRARY, FRAMEWORK, and generic arguments are used to determine the properties (DESTINATION, COMPONENT, etc.) of the installation of these dependencies.

**Comment by mahge** [comment]
I have tried to use CMake's [RUNTIME_DEPENDENCIES](https://cmake.org/cmake/help/latest/command/install.html#install-targets) once but I was not able to get it work. We can give it another shot if needed because it is useful for other purposes as well.

However, it is available only for CMake versions >= 3.21. OpenModelica's unofficial minimum CMake requirement is version 3.14 right now. We can upgrade this for FMU's of course or use a fallback mechanism for people with lower CMake versions.

Another option is to use system specific tools like `ldd (linux)`, otool (macOS) and `dumpbin` (Windows) to get a list of shared libraries and DLL's and copy them manually. The only I can see with this is that we have to find some mechanism for differentiating between system and user libraries so that we do not copy system libraries (maybe we can see tell this by looking at their root folders. If we need a reference, we can take a look at what vcpkg does, I think it has to deal with this exact problem).  

I don't think we need to copy things before linking because we can always use CMake to modify the rapths (linux) after linking. For Windows we just need to copy the DLLs to the same directory as the FMU binary.

Regarding symbolic links, CMake has an option to follow symbolic links on copy command. 

@AnHeuermann maybe we can take the simple example and have a meeting to try it out when you have time.

**Comment by AnHeuermann** [comment]
@mahge and myself got it to work with `RUNTIME_DEPENDECIES`. We could either include everything (including used system libraries) or try to filter them out by matching to the default system directories to exclude them from the FMU.

I'm not sure what we want to keep as default and if I should add a flag for it to choose between all dependencies or only those mentioned in the Modelica code.

**Comment by mahge** [comment]
> Including all libraries could be interesting in some cases, but I would only include them into the FMU if the modeler explicitely decides to do so, e.g. by adding a suitable flag to the CMake build.

This is a good idea. We can have different levels of dependency inclusions. Something like `all`, `non-system`, `direct`, and `none` to include: all dependencies, non-system dependencies, only direct dependencies (listed in Modelica annotations) and nothing at all respectively. This might get complicated to implement but it is certainly doable.

However, I think by default we should include all dependencies. If not, we should, at least, include all non-system dependencies. Including those not explicitly listed in the Modelica annotations.

**Comment by casella** [comment]
I have one question abou this. In many cases one exports a single, monolithic FMU to simulate a certain system, so that it can be simulated in other environment. In this case, it must carry all the dependencies with him, in some way.

However, it is not 100% clear to me what happens if I build an SSP model (e.g. with OMSimulator) where I drag in 50 instances of the same FMU. Are all the dependencies loaded just once, or are they loaded 50 times? This may be severely sub-optimal in terms of memory requirement and efficient CPU cache management.

**Comment by mahge** [comment]
Of course, there is no solution that works perfectly for every use case. Right now, what @AnHeuermann is doing in #9441 is including every direct and indirect dependency (not explicitly listed but depended on indirectly) except for system libraries. 

For the use case you presented we will need another command-line option as suggested. What we need to decide is what the default behavior should be. I vote that the FMU needs to contain everything it needs inside it. Even system libraries like `pthread` and `math` `(libm)`. If not, it should at least contain all non-system dependences (direct or indirect). This allows non-expert users to get a working FMU without having to modify or adjust more options. 

This means specialized use cases will need additional options/configurations.

**Comment by pstelzig** [comment]
Hi @AnHeuermann @mahge @casella @bilderbuchi 

I wanted to say a **big thanks for your superb response to this issue and for your quick fix**! Can't wait to get the new release with the fix. 

If I understood your comment in #9441 correctly, there is even now a compiler flag to choose from

> There is now a new compiler flag --fmuRuntimeDepends that will choose the degree of runtime dependecies included. Options are none, modelica and all. Default is modelica (when using CMake FMUs). So everyone with an old CMake get's an error message.

The choice `fmuRuntimeDepends=modelica` would copy only those libraries named explicitely in the Modelica code, correct?

Very cool indeed!

**Comment by AnHeuermann** [comment]
> It will copy all libraries used by the FMU binary except system installed libraries.

Yes, that is correct. 

The reasoning is, that we don't know the structure of the libraries include by `annotation(Library = "externalfunc");`. It could have additional dependencies right next to it or be some symbolic link or whatever. So this should be a robust option.

If really needed we could instead of filtering system libraries with `POST_EXCLUDE_REGEXES` only include libraries from the library directories we collect from the Modelica model using `POST_INCLUDE_FILES` or make this a fourth option for `--fmuRuntimeDepends`.

**Comment by casella** [comment]
> I wanted to say a **big thanks for your superb response to this issue and for your quick fix**! Can't wait to get the new release with the fix.

You're welcome!

BTW, there is no need to wait for the release, you can go straight for a nightly build, we make them available every day for [Linux](https://openmodelica.org/download/download-linux) and [Windows](https://openmodelica.org/download/download-windows) systems.

**Comment by casella** [comment]
At some point we should get this stuff into the OMEdit GUI as well.

@AnHeuermann do you think the flags are mature enough that they won't change in the future and we can ask @adease31 to add them to the OMEdit [FMI export menu](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#fmi)?
