### ISSUE TITLE
newlines stripped from string parameters

### ISSUE THREAD

**Issue by Mathadon** [OpenModelica/OpenModelica#9429]
### Description
When sending a string parameter into an external C function, newlines seem to be stripped from the string.

### Steps to reproduce
Related to this issue: https://github.com/ibpsa/modelica-ibpsa/pull/1602

When executing the model `IBPSA.Utilities.IO.Files.Examples.WeeklySchedule` in https://github.com/ibpsa/modelica-ibpsa/tree/1601_weeklySchedule , the following string is put into an external C function: 

```
  parameter String data = "double tab1(3,5) #test:
mon:0:0:10          -  3   1  -  
tue,thu:20:30:59  123  -  45  -
wed                12  1   4  -" "Contents of schedule.txt";
```
where each line is interpreted by a C code. It seems that the newlines ( and also the string '\n') are ignored/removed by openmodelica such that the C code terminates unsuccessfully. 

The Modelica spec allows newlines:

![](https://user-images.githubusercontent.com/5970879/183242473-cd00ba99-bd8f-47ad-adf6-5e3724da8e19.png)

and this model does work in Dymola, so this seems to be a bug?

### Screenshots
<img width="755" alt="image" src="https://user-images.githubusercontent.com/5970879/192209150-cfc4dafe-ca74-4354-bc05-aa0dcf928d20.png">

### Version and OS
 v1.20.0-dev-305-geb5e7e0a95
macOS

**Comment by Mathadon** [comment]
See lines 109 and 340 in https://github.com/ibpsa/modelica-ibpsa/blob/500982bb637fe55b49e53db9329520bd205e47b0/IBPSA/Resources/C-Sources/WeeklySchedule.c

**Comment by casella** [comment]
@mahge if this is a quick fix we can try to get it into 1.20.0.

**Comment by mahge** [comment]
@Mathadon are you sure the error is because of the string passed to the external function? The following works fine for me.

test.mos
```mo
loadFile("test.mo");
getErrorString();

simulate(M);
getErrorString();
```

test.mo
```mo
function f
  input String s;
  external "C" f_impl(s) annotation(Include="#include \"f.h\"");
end f;

model M
  String s = "double tab1(3,5) #test:
mon:0:0:10          -  3   1  -
tue,thu:20:30:59  123  -  45  -
wed                12  1   4  -" "Contents of schedule.txt";
initial equation
  f(s);
end M;
```

f.h
```c
#include <stdio.h>
#include <string.h>

void f_impl(const char *str)
{
  // printf("%s\n", str);

  char* str2 = strdup(str);
  int i = 1;

  char* pch = strtok(str2, "\n");
  while (pch != NULL)
  {
      printf("%d: %s\n", i, pch);
      i++;
      pch = strtok(NULL, "\r\n");
  }
}
```

run it as
```sh
omc test.mos
```

gives the output
```sh
true
""
record SimulationResult
    resultFile = "/home/mahder/dev/OpenModelica/working/ticket_9429/M_res.mat",
    simulationOptions = "startTime = 0.0, stopTime = 1.0, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'M', options = '', outputFormat = 'mat', variableFilter = '.*', cflags = '', simflags = ''",
    messages = "1: double tab1(3,5) #test:
2: mon:0:0:10          -  3   1  -
3: tue,thu:20:30:59  123  -  45  -
4: wed                12  1   4  -
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
LOG_SUCCESS       | info    | The simulation finished successfully.
",
    timeFrontend = 0.003072682,
    timeBackend = 0.00688915,
    timeSimCode = 0.001272569,
    timeTemplates = 0.002153664,
    timeCompile = 0.3238837889999999,
    timeSimulation = 0.005525255000000001,
    timeTotal = 0.3429023499999999
end SimulationResult;
""
```

with the lines detected and numbered as expected (see messages = " ... " in the output).

I can see in your linked code that you actually open [another file](https://github.com/ibpsa/modelica-ibpsa/blob/500982bb637fe55b49e53db9329520bd205e47b0/IBPSA/Resources/C-Sources/WeeklySchedule.c#L72-L77) and read contents from it. That is where the count of new lines is calculated from.

Are you sure that is not where the problem is?

**Comment by Mathadon** [comment]
@mahge I'll have to double-check but the idea of the code section that you quoted is that `tableOnFile=false` such that the data is read from the string parameter input, instead from the file. See also https://github.com/ibpsa/modelica-ibpsa/blob/500982bb637fe55b49e53db9329520bd205e47b0/IBPSA/Resources/C-Sources/WeeklySchedule.c#L89-L94 . Perhaps the value of`tableOnFile` is incorrect, I didn't double check. Let me get back to you.

**Comment by Mathadon** [comment]
@mahge I could reproduce your result. However, changing 
```Modelica
  String s = "double tab1(3,5) #test:
mon:0:0:10          -  3   1  -
tue,thu:20:30:59  123  -  45  -
wed                12  1   4  -" "Contents of schedule.txt";
```
to 
```Modelica
  parameter String s = "double tab1(3,5) #test:
mon:0:0:10          -  3   1  -
tue,thu:20:30:59  123  -  45  -
wed                12  1   4  -" "Contents of schedule.txt";
```

results in 

```
1: double tab1(3,5) #test:  mon:0:0:10          -  3   1  -  tue,thu:20:30:59  123  -  45  -  wed                12  1   4  -
```

instead of 

```
1: double tab1(3,5) #test:
2: mon:0:0:10          -  3   1  -
3: tue,thu:20:30:59  123  -  45  -
4: wed                12  1   4  -
```

so it seems that OMC treats continuous variables differently than parameters?

**Comment by mahge** [comment]
This turned out to be an issue with how we parse xml files. The values for parameters are read from the init.xml file we generate for each model. The string is written to the file as expected with the newlines. However, when we parse it to set the values for a simulation run, the parser (expat) seems to eat up the newlines. 

I have added escaping for newlines to their xml values in #9521. I am not fully convinced that this will have some unexpected consequences though.

**Comment by Mathadon** [comment]
Okay, glad this will be fixed! :)

**Comment by casella** [comment]
@Mathadon, this is already available in the Windows nightly build, and will be in the forthcoming 1.20.0 release anytime soon. Unfortunately the Linux nightly build pipeline is broken, so if you use that you need to be patient.

**Comment by Mathadon** [comment]
@casella I have built from sources on macOS and it works :)
