### ISSUE TITLE
Add documentation of CSV-input files for models with top-level inputs

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9472]
This feature is currently undocumented, except for the [-csvInput](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/simulationflags.html#simflag-csvinput) Simulation Flag, whose documentation doesn't tell much. 

It should be described in the User's Guide. I guess we could add it [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#simulating-a-model), though this actually also applies for simulations that are not started from OMEdit.

Keeping @MohammadHadiAlizadeh in the loop.

**Comment by mahge** [comment]
The issues are all sorted out. If you see any more issues let me know and we can fix them as well.

**Comment by casella** [comment]
Thank @mahge, very much appreciated 😃.

**Comment by casella** [comment]
Reopening until online version is checked

**Comment by casella** [comment]
The User's Guide now [properly describes the feature](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#csv-file-data-input), which has been re-established and tested.

**Comment by casella** [comment]
> The issues are all sorted out. If you see any more issues let me know and we can fix them as well.

@mahge are there some tests of this feature in the core testsuite? This would be good, to avoid that they get accidentally broken again in the future and we don't see that.

Thanks!
