### ISSUE TITLE
CSV-input files only work with comma separators

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9487]
I am trying to figure out how CSV-input files actually work to document them, see #9472.

I am using this MWE
```modelica
model TestTopInputs
  Modelica.Blocks.Interfaces.RealInput u1;
  Modelica.Blocks.Interfaces.RealInput u2;
  Modelica.Blocks.Interfaces.RealInput u3;
  Real y = 2*u1;
  Real z = 4*u2;
  Real w = u1*u2*u3;
  annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime = 0, StopTime = 5, Tolerance = 1e-06, Interval = 0.01));
end TestTopInputs;
```
I am simulating this MWE with `-csvInput=abc.csv`, where `abc.csv` is a file that needs to be in the same directory as TestTopInput.mo (see also #9482). I am putting the input data u1, u2, and u3 in reverse order in the csv file, to make sure that the column are actually associated to the corresponding variable, and not just ordered lexicographically or something.

```
time, u3, u2, u1,
0, 0, 0, 0,
1, 0, 0, 0,
2, 0, 0, 1,
3, 0, 2, 1,
4, 3, 1, 1,
5, 1, 1, 1,
```
The reason why there are commas at the end of each line is explained in #9486.

Commit a7b38287 by @lochel seemed to imply that one could use just any delimiter, not only a comma. However, if I try to replace the comma with a semicolon, a space, or a tab, I always get something like
```
Found non-double data in csv result-file: 0; 0; 0; 0;
Failed to read CSV-file abc.csv
```
This also happens if I use actual double literals
```
time; u3; u2; u1;
0.0; 0.0; 0.0; 0.0;
1.0; 0.0; 0.0; 0.0;
2.0; 0.0; 0.0; 1.0;
3.0; 0.0; 2.0; 1.0;
4.0; 3.0; 1.0; 1.0;
5.0; 1.0; 1.0; 1.0;
```
```
Found non-double data in csv result-file: 0.0; 0.0; 0.0; 0.0;
Failed to read CSV-file abc.csv
```
@adeas31, @sjoelund, @mahge, you have worked on [read_csv() ](https://github.com/OpenModelica/OpenModelica/blame/master/OMCompiler/SimulationRuntime/c/util/read_csv.c) recently, can you please check what is going wrong there?

**Comment by mahge** [comment]
This should be fixed with #9517. 

Note that if you are using a separator other than the default `,` (comma), you have to **specify it using a specific pattern**. Examples:

Semicolon separated
```
"sep=;" time; u3; u2; u1
0.0; 0.0; 0.0; 0.0
1.0; 0.0; 0.0; 0.0
2.0; 0.0; 0.0; 1.0
```

Space separated
```
"sep= " time u3 u2 u1
0.0 0.0 0.0 0.0
1.0 0.0 0.0 0.0
2.0 0.0 0.0 1.0
```
