### ISSUE TITLE
OMEdit should write out/use Text.textColor instead of the deprecated Text.lineColor attribute

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9498]
### Description
The annotation attribute `Text.lineColor` has been deprecated for in MLS v3.3. See also https://github.com/modelica/ModelicaStandardLibrary/issues/2152#issue-204122014 and `Text.textColor` should be used/written out instead.

The lack of support in OMEdit leads to other projects not being able to accept PRs like for example https://github.com/OpenIPSL/OpenIPSL/pull/311

**Comment by casella** [comment]
@adeas31 can we sneak this in 1.20.0? Looks like a simple fix
