### ISSUE TITLE
Problems in OpenModelica v1.19.2 when installing OpenHydraulics v1.0.1 with Modelica Standard Lib v3.2

### ISSUE THREAD

**Issue by computational-physcis-2011301020083** [OpenModelica/OpenModelica#9502]
Greeting Everyone,

I'm a brand new Modelica user. I'm trying to learn the language with OpenModelica. I'd like to use OpenHydraulics which is in [github link](https://github.com/cparedis/OpenHydraulics) in OpenModelica (specifically in the OMEdit Connection Editor).

I downloaded OpenModelica v1.19.2 and Modelica Standard Lib v3.2 to browse and run the library OpenHydraulics v1.0.1. However, when I open the Excavator example and try to Instantiate or Simulate the model I get many errors of the form:

**[OpenHydraulics.Basic.VariableRestriction: 51:3-54:64]: Function ReynoldsNumber_m_flow not found in scope VariableRestriction.**

Could you help me with this problem? Thanks in advance.

**Comment by perost** [comment]
It seems the tagged 1.0.1 version on GitHub is actually broken, which is the version that we distribute via the package manager. If you instead download the master version directly from GitHub it should work better. But beware that it's a really old library that's not maintained.

**Comment by dietmarw** [comment]
Note that you need to tick the box "None" in the package manager in order to see that. Also it is called  `1.0.0 (pre-released build master)` which might be confusing since the latest release version is `v1.0.1`.

**Comment by computational-physcis-2011301020083** [comment]
Thank you guys!
