### ISSUE TITLE
OMEdit fails to find referenced stl files for simulation with animation

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9503]
### Description

When trying `OpenHydraulics.Examples.Excavator.DigCycleSimulation`  in animation mode I noticed that I get error messages that the stl find can not be found. 

### Steps to Reproduce

1. open `OpenHydraulics.Examples.Excavator.DigCycleSimulation` 
2. run "Simulate with animation"
3. OMEdit reports: 
  ```
[15] 11:04:03 Scripting Error
Could not find the file OpenHydraulics/Resources/Shapes/Excavator/arm.stl.
``` 
  etc ... also for the other stl files.

4. checking the code shows it is referenced correctly: `shapeType="modelica://OpenHydraulics/Resources/Shapes/Excavator/arm.stl"`
5. checking the file system shows:
  ```
$ find . -name arm.stl
./OpenHydraulics/Resources/Shapes/Excavator/arm.stl
```

### Version and OS

 - OpenModelica Version:  OpenModelica 1.20.0~dev-336-g8a791ee
 - OS: Ubuntu Linux 22.04.1
 - OpenHydraulics (master)

**Comment by adeas31** [comment]
Already fixed in 6814223cf8a279f79d8f048b73edc96282e4f4ee.
