### ISSUE TITLE
FMU export  : Maximum path length limitation reached while opening 

### ISSUE THREAD

**Issue by denis-jidovtseff-jc** [OpenModelica/OpenModelica#9508]
### Description

When I want to make export an FMU from a model, Openmodelica is showing the following error:
`Warning: Maximum path length limitation reached while opening 
        C:\Users\denis.jidovtseff@johncockerill.com\simulations\Hyptimise.Hyptimise2HRStest.PhDthesis.VerificationOfComponents.Bypass_Verification\Hyptimise_Hyptimise2HRStest_PhDthesis_VerificationOfComponents_Bypass_Verification.fmutmp\sources\omc_simulation_settings.h 
Consider changing the working directory, using shorter names or to enable longer paths in Windows. 
See https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation for more information. 
`
I already have removed the maximum file path limitation. but nothing changed
If I change the position of the model inside the package ( at a upper level) the path lenght is shorten and it works

### Steps to Reproduce
setup the simulation folder into a long path name >256 caracters
Make a FMU from any model in OpenModelica

### Expected Behavior

no error should happen when creating the FMU with any path lenghts

### Version and OS

 - OpenModelica Version: OpenModelica v1.19.2 (64-bit)
 - OS: Windows 10 entreprise version 10.0.019044

**Comment by AnHeuermann** [comment]
Does it fail or is it just the warning that is displayed?

I added this warning some time ago. It should continue by using long paths (adding `\\?\` to the beginning of the path).
The problem is - and why the warning is shown even if long path are used - that further down the GNU compiler tools most likely will fail and I didn't found a way to make all compiler tools work with those pesky `\\?\` paths.

If it fails the only option I see is to reduce the length of the path by copying it to a different location or use smaller model/package names. Or switch to a Linux distribution.

**Comment by denis-jidovtseff-jc** [comment]
if I use the \\?\ at the beginning of the path I have the it says that the UNC path is not take into account
without that, I have errors during compilation

**Comment by denis-jidovtseff-jc** [comment]
No I Have this problem only when doing FMU export, It runs normally in OpenModelica
try this library, 
[TEstlibraryforgithub.zip](https://github.com/OpenModelica/OpenModelica/files/9777064/TEstlibraryforgithub.zip)
I have the following error
`[7] 15:24:39 Traduction Erreur
Error building simulator. Build log: gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx.c
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_functions.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_functions.c
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_records.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_records.c
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_01exo.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_01exo.c
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_02nls.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_02nls.c
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_03lsy.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_03lsy.c
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx.c: No such file or directory
gcc -O0 -g -Wno-parentheses-equality -falign-functions -mstackrealign -msse2 -mfpmath=sse  -I. -I"C:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/include/omc/c/fmi" -DOMC_FMI_RUNTIME=1 -O0 -g  -DWITH_SUNDIALS=1 -DLINK_SUNDIALS_STATIC -Isundials -DCMINPACK_NO_DLL=1 "-IC:/Users/denis.jidovtseff@johncockerill.com/Openmodelica/lib/omlibrary/Modelica 4.0.0/Resources/C-Sources"  -c -o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_04set.o TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_04set.c
gcc.exe: fatal error: no input files
compilation terminated. 
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_functions.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated. 
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_functions.o] Error 1
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_records.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated. 
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_01exo.c: No such file or directory
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_records.o] Error 1
gcc.exe: fatal error: no input files
compilation terminated. 
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_01exo.o] Error 1
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_02nls.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated. 
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_03lsy.c: No such file or directory
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_02nls.o] Error 1
gcc.exe: fatal error: no input files
compilation terminated. 
gcc.exe: error: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_04set.c: No such file or directory
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_03lsy.o] Error 1
gcc.exe: fatal error: no input files
compilation terminated. 
make: *** [<builtin>: TEstlibraryforgithub_Tests_trythispackagelocationforpathbug_testHeatEx_04set.o] Error 1
`

**Comment by AnHeuermann** [comment]
There is not much we can do about this.
Problem is, that `gcc` and other compiler tools are coming from Unix and don't (fully / at all) support UNC paths. At least as far as I know.

Maybe there is a way to get this working with CMake and MSVC on UNC paths. I sort of need CMake FMUs with MSVC at some point anyway, but it has super low priority for me.

So your only option at the moment is to use shorter names for your library / models.

**Comment by denis-jidovtseff-jc** [comment]
I expected this answer. I can have it solved when moving location of model inside the package. I'll do that

**Comment by casella** [comment]
@denis-jidovtseff-jc there may be another simple workarond. Define a new model

model M
  extends Hyptimise.Hyptimise2HRStest.PhDthesis.VerificationOfComponents.Bypass_Verification;
end M;

and save it in M.mo. Then generate an FMU out of it. Et voilà 😄
