### ISSUE TITLE
NFExpression.makeSubscriptedExp: too few dimensions 

### ISSUE THREAD

**Issue by DaJansenGit** [OpenModelica/OpenModelica#9510]
### Description
In the AixLib Example: `AixLib.Controls.HVACAgentBasedControl.Examples.BookTrading.BookTrading` an error occurs while checking with OM. 
```modelica
[2] 11:42:47 Übersetzung Fehler
[C:/OM119/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFExpression.mo: 1551:7-1552:100]: Internal error NFExpression.makeSubscriptedExp: too few dimensions in [3551555559.0, 30; 3551555577.0, 20; 3551555588.0, 20] to apply subscripts [<bookSellerAgent, bookSellerAgent>]
```
The error occurs due to the component `AixLib.Controls.HVACAgentBasedControl.Examples.BookTrading.BookSellerAgent` but the component itself checks. 
The example checks well in Dymola 2023 in pedantic mode.
I found the similar issues https://github.com/OpenModelica/OpenModelica/issues/8692 and [here](https://trac.openmodelica.org/OpenModelica/ticket/5991). These were solved by changes in OM. 
Unfortunately I was not able to track down the error any further and hope you can help.

### Steps to reproduce
Clone the below mentioned branch of AixLib and check the model.

### Expected behavior
The model check running fine.

### Version and OS
 - OpenModelica Version v1.19.2 (64-bit)
 - AixLib branch: https://github.com/RWTH-EBC/AixLib/tree/1348-multiple-fails-in-controls-package-in-openmodelica
 - OS: e.g. Windows 10, 64 bit

**Comment by perost** [comment]
Minimal model that reproduces the issue:
```Modelica
model A
  Real [:, 2] x;
end A;

model M
  A a(x(start = [1, 1; 1, 1; 1, 1]));
end M;
```
The issue seems to be related to deducing the size of the array based on its start attribute (since the variable itself lacks a binding equation), where the binding equation for the start attribute comes from a modifier.

Deducing array dimensions from a variable's attributes rather than its binding is something that I know needs improvements in the compiler, but its rarely used so it hasn't gotten much attention so far. I don't have much time to work on this right now, but maybe next month hopefully.

**Comment by perost** [comment]
Also, this similar model just fails without any error at all:
```Modelica
model A
  Real [:, 2] x;
end A;

model M
  A a(x(start = {{1, 1}, {1, 1}, {1, 1}}));
end M;
```

**Comment by DaJansenGit** [comment]
Thanks for your quick reply! 
The behavior sounds of logic to me. But it doesn't seem to be the exact same case because when I check your provided example in Dymola 2023 (even in non pedantic mode) it fails with the following message.
```modelica
Check of M:

The problem is structurally singular.

It has 6 scalar unknowns and 0 scalar equations.
The Real part has 6 unknowns and 0 equations.
The Integer part has 0 unknowns and 0 equations.
The Boolean part has 0 unknowns and 0 equations.
The String part has 0 unknowns and 0 equations.

The model is not well-posed.
The model has
2*size(a.x, 1)
scalar unknowns and
0
scalar equations.
Using the given settings of the parameters, the difference could be reduced to
6

Attempting to further localize singularity.

The model M component a is structurally singular.

WARNINGS have been issued.

ERRORS have been issued.
```

So there still seems to be some differences between the proposed problem from my site and your MWE

**Comment by perost** [comment]
@DaJansenGit: My MWE is not meant to be a valid simulation model, it's just reproducing the frontend issue that we have. The frontend only flattens the model, so it doesn't care if the model is balanced or not.

**Comment by DaJansenGit** [comment]
@perost: Ok, thanks for the explanation!
