### ISSUE TITLE
Order (z-position) of graphical element not preserved 

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9515]
### Description
When we copy-paste graphical elements their order should be preserved, but it is not.

### Steps to Reproduce
- Load Modelica.Electrical.Analog.Sensors.PowerSensor in icon perspective
- select everything and copy
- create a new model and go to icon perspective
-  paste.

You'll see that the graphical elements are all there, but some hide others because their order was not preserved.
Screenshot:
![image](https://user-images.githubusercontent.com/7373030/195708011-eeb219fd-4890-4812-8d4d-bd7693029642.png)

### Expected Behavior
When pasting a set of graphical objects the order should remain the same as when they were copied.
The issue is made more severe by the fact that OMEdit does not have a graphical way to change the order of graphical elements, but this is another story.

### Version and OS
Win10 64 bit OM 1.19.2

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: [e.g. Windows 10, 64 bit]
 - Versions of used Modelica libraries if applicable

**Comment by ceraolo** [comment]
tank you

**Comment by adeas31** [comment]
I ported this to 1.22 so should be available with 1.22.1
