### ISSUE TITLE
Different step handling in assert and boolean expression

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#9520]
### Description

When checking if step.y>1e-10 (step.y jumps from 100 to 0 at 0.5s) the result is correctly identified as false in an assert but wrongly identified as true in a boolean expression. (Maybe due to a different treating of events in asserts and other parts of the code)

### Steps to Reproduce

1. Execute the script pasted below.
2. At 0.5 the assert (level=warning) checking if step.y>1e-10 is correctly thrown. 
3. However, the parameter "test" and the output of the boolean expression "wrong.y", which are identically defined by >1e-10 remain true. 
4. If the boolean expression checks against 1e-9 (correct.y) its output correctly jumps to false after 0.5s. If the input is not a step but a ramp which goes from 100 at 0s to 0 at 0.5s the boolean expression (rampCheck.y) correctly jumps to false at 0.5s as well.
5. If the tolerance is changed to 1e-8 the problem does not occur as well anymore. Both the assert as well as "test" and "wrong.y" act correctly at 0.5s. 

### Expected Behavior

The result of the equation step.y>1e-10 is the same no matter where it is placed in the modelica code. This behavior is seen in other modelica tools like Dymola and SimulationX.

### Version and OS

 - OpenModelica Version: 1.19.2
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

### Minimal problem 
I cannot upload my .mo file with a minimal example so i am pasting my model code below.

```
model StepProblem

  Boolean test = step.y > 1e-10;

  Modelica.Blocks.Sources.BooleanExpression correct(y = step.y > 1e-9) annotation(
    Placement(visible = true, transformation(origin = {-8, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.BooleanExpression wrong(y = step.y > 1e-10)  annotation(
    Placement(visible = true, transformation(origin = {-6, -12}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step(height = -100, offset = 100, startTime = 0.5)  annotation(
    Placement(visible = true, transformation(origin = {-6, 46}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Ramp ramp(duration = 0.5, height = -100, offset = 100, startTime = 0.0)  annotation(
    Placement(visible = true, transformation(origin = {34, 44}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.BooleanExpression rampCheck(y = ramp.y > 1e-10) annotation(
    Placement(visible = true, 
[StepProblem.txt](https://github.com/OpenModelica/OpenModelica/files/9826747/StepProblem.txt)
[StepProblem.txt](https://github.com/OpenModelica/OpenModelica/files/9826752/StepProblem.txt)
transformation(origin = {32, 10}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
assert(step.y > 1e-10, "\nError in "+getInstanceName()+": \nStep.y must be greater than 1e-10.",level=AssertionLevel.warning);

annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime=0.0, StopTime=1.0, Interval=0.01, Tolerance=1e-6));
end StepProblem;
```

Thanks for looking into it
Aaron Buntrock - Bosch Rexroth

**Comment by casella** [comment]
@abuntrock you can attach .mo files by adding .txt to the filename or by zipping them.

**Comment by casella** [comment]
Coming to your question, I think that relying on such small epsilons to trigger events is hazardous and implicitly ill-conditioned; zero-crossing functions are always evaluated with some numerical tolerance. Remember that Modelica is a declarative language, so the way a statement like step.y > 1e-9 is handled (i.e. by generating zero-crossing functions and enabiling event detection during simulation)  is different from how it would be interpreted in a procedural language like C or Python (i.e., literally).

The robust way to determine when a step or ramp is triggered is to rely on the condition that triggers the step itself, e.g.
```modelica
model M
  Real step_y;
  Boolean on(start = false, fixed = true);
equation
  when time > 1 then
    on = true;
  end when;
  step_y = if on then 1e-9 else 0;
  assert(not on, "the step has been triggered, AssertionLevel.warning");
annotation(experiment(StopTime = 2));
end M;
```

**Comment by abuntrock** [comment]
@casella Thanks for the tip regarding the .txt file upload. I hope my company laptop allows this. 

Also, thanks for the explanation regarding the step handling. I can see the effectiveness of your solution applied to my minimal example.
However, I am still not sure how I would apply your solution to a more complicated problem. E.g. if my input function is not a step but a timetable, I have to detect the points in time where the table output crosses my threshold because I do not know those times a priori like in your example (you must know the time where the step occurs to use it in your when statement). 
Furthermore I would have to change the input of my model (in the minimum example this would be the Boolean expression block) to accept the Boolean variable defining the times where the threshold is crossed (in your example “on”) instead of the variable (step.y) itself. This would mean that a user, who uses our BRSL library, would not be able to input a timetable but would have to determine the times where a threshold is crossed himself and input this Boolean variable into our BRSL model. Do I understand this correctly?

All in all this ticket might be closed if the difference in event handling (x <1e-10) in asserts and other Boolean statements is due to numerical issues. 
Thanks for your help
Aaron

**Comment by casella** [comment]
@abuntrock, there is no way to reliably detect when a variable_starts moving away_ from a constant value, unless you refer to the root cause. You need to put a threshold which is significantly larger. 1e-10 is definitely too small a threshold. I think 1e-6 should be fine from a practical point of view, while not affecting the accuracy of the results significantly. 

Of course I am referring to variables that have order-of-magnitude of unity. If they are significantly larger (e.g. pressures in Pascal), the `nominal` attribute should be used so that threshold crossing is automatically scaled in a convenient way.

Can you try this out for your examples?

> All in all this ticket might be closed if the difference in event handling (x <1e-10) in asserts and other Boolean statements is due to numerical issues.

As far as I understand, definitely. Please reopen if you have trouble with larger thresholds.
