### ISSUE TITLE
Missing parts of a component diagram with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9533]
### Description

When inserting a component from the BRSL library onto a sheet in OMEdit, only parts of the component diagram  are drwan.
Please see therefore picture 1. In the example the ground diagram and the real inputs diagrams are missing.
### Steps to Reproduce

Load the BRSL package: Rexroth_Generic/package.mo.
Drag and Drop a component onto a new sheet.

### Expected Behavior

please see picture 2.

### Screenshots
**Picture 1**
<img width="209" alt="Diagram-Parts-1" src="https://user-images.githubusercontent.com/12269776/196223079-0e027af1-0c1d-416a-912d-b626ab13d032.png">
**Picture 2**
<img width="149" alt="Diagram-Parts-2" src="https://user-images.githubusercontent.com/12269776/196223143-b644f3d0-d884-4ed7-bbe0-6e83ba3029b4.png">

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.2 dev

### Additional Context

@sbaetzing @abuntrock

**Comment by adeas31** [comment]
The api says,

`"$error": "[C:/Users/adeas31/Desktop/BRSL_Dev_OM/Rexroth_Generic/SignalBlocks/Interfaces/RealInput.mo:4:84-14:60:writable] Error: Variable FillPattern.Solid not found in scope RealInput.\\n",`

I am not sure why its failing. The annotation in `Rexroth_Generic.SignalBlocks.Interfaces.RealInput` looks legit.

**Comment by niklwors** [comment]
I have tested it with the current version but the problem is still there, so I reopen the ticket.

**Comment by perost** [comment]
@adeas31: It seems like the icons and the diagrams don't match, i.e. if I add a `Rexroth_Generic.Mechanics.Rotational.Components.Inertia` to the diagram it's using the diagram for `Rexroth_Generic.Mechanics.Rotational.Components.VariableFrictionalRotational` instead.

**Comment by adeas31** [comment]
Maybe its because whats happening in #9531

**Comment by adeas31** [comment]
@niklwors can you please test this again.

**Comment by niklwors** [comment]
The missing parts are now visible again. But the labeling is a little wrong now because of the scaling.  The "visible attribute" is actually turned off for the label, but it is displayed anyway.

**Comment by adeas31** [comment]
I think the labeling is wrong because of the horizontal alignment (see #8236).

The visible attribute on/off is still under implementation.

**Comment by casella** [comment]
I would close this ticket since this issue is resolved. Feel free to open another issue regarding the visible attribute
