### ISSUE TITLE
Connect equations that contain conditional components generate an error with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9534]
### Description

For components of our BRSL that including connect equations with conditional components generate an error in the message window when a folder is expanded in the library browser.
e.g.
```
[27] 18:01:35 Skripting error
Unable to find component baseCylinderMovingHousing.encoder while parsing connect(baseCylinderMovingHousing.encoder, encoder) in Rexroth_Generic.Hydraulics.Cylinders.SingleRodCylinder.
```
### Steps to Reproduce
Load the BRSL package: Rexroth_Generic/package.mo.
Expand the folder Cylinders from the Rexroth Generic package, see picture 1.

### Expected Behavior
There should be no error message in the message window

### Screenshots

**Picture 1**

<img width="266" alt="Wrong-error-mesages" src="https://user-images.githubusercontent.com/12269776/196228158-c2284602-7ada-47d4-a94c-679dfa800050.png">

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: Windows 10, 64 bit
- MSL 4.0.0
- BRSL 2.2 dev

### Additional Context

@sbaetzing @abuntrock

**Comment by casella** [comment]
@perost will this be handled correctly once #8425 is done?

**Comment by perost** [comment]
> @perost will this be handled correctly once #8425 is done?

I assume so, but that's an OMEdit issue.

**Comment by adeas31** [comment]
OMEdit prints this error message when it fails to find the connectors and as a result the connection line is not shown.

This particular issue is related to #9533. The `encoder` is of type `Rexroth_Generic.SignalBlocks.Interfaces.RealInput` which is not drawn hence the error message.
