### ISSUE TITLE
Enabling a visible attribute removes complete component diagram or labels with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9535]
### Description

If you enable the visible attribute of a component of the BRSL, the complete component disappears.

### Steps to Reproduce

Load the BRSL package: ```Rexroth_Generic/package.mo```
Example 1:
1. Drag and drop the ```SingleRodCylinder``` on a new sheet.
2. Enable the parameter ```movableHousing``` in the parameter dialog.

Example 2:
1. Drag and drop the ```SingleRodCylinder``` on a new sheet.
2. The enconder symbole in the icon of the ```SingleRodCylinder```  is missing,  see picture 2 and 3.

Example 3:
1. Drag and drop the ```SingleRodCylinder``` on a new sheet.
2. The labels in the icon of the ```SingleRodCylinder``` are missing (see picture 2) . It can be enabled and disabled in the parameter dialog (see picture 4 )

Example 4:
1. Drag and drop the ```SingleRodCylinder``` on a new sheet.
3. The connecting line of port B in the icon of the ```SingleRodCylinder``` is missing, see picture 2 and 3.

### Screenshots
**Picture 1**
<img width="1749" alt="vissible-attribute" src="https://user-images.githubusercontent.com/12269776/196232736-78aa6837-00fb-4da2-a6c5-e6b7637b6043.png">
**Picture 2**
<img width="1291" alt="encoder_1" src="https://user-images.githubusercontent.com/12269776/196738307-323d26fc-8b2e-4a2c-ad53-470400650d72.png">
**Picture 3**
<img width="913" alt="encoder_2" src="https://user-images.githubusercontent.com/12269776/196738350-354f2412-f6dd-4ff8-b5fd-0defda4ab8ea.png">
**Picture 4**
<img width="732" alt="encode-4" src="https://user-images.githubusercontent.com/12269776/196738425-cecf13df-7d97-4b01-b025-f4df8b532ae6.png">

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: Windows 10, 64 bit
- MSL 4.0.0
- BRSL 2.2 dev

### Additional Context

@sbaetzing @abuntrock

**Comment by adeas31** [comment]
I tested this again. With the latest changes the first 3 cases works as expected.

The case 4 doesn't work. The compiler reports the error,

`Rexroth_Generic/Hydraulics/Cylinders/Internal/ChamberBInterface.mo:34:20-55:32:writable] Error: Variable showPortDescription not found in scope ChamberBInterface.`

I am guessing you need to add `extends Rexroth_Generic.Auxiliaries.Interfaces.BaseSimulationModel;` to the model `Rexroth_Generic.Hydraulics.Cylinders.Internal.ChamberBInterface`.

**Comment by abuntrock** [comment]
@adeas31 Regarding case 4 your assumption is completely correct. This is an error in our model.

**Comment by adeas31** [comment]
OK great! Please test with latest version tomorrow and report. I fixed few more things today.

**Comment by casella** [comment]
Great!
