### ISSUE TITLE
Loading MSL 3.2.3 loads the wrong Modelica Services and Complex library

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9546]
### Description
On a system where version 3.2.3 and 4.0.0 of the MSL are installed as system libraries, loading MSL 3.2.3 will load the wrong version 4.0.0 of Modelica Services and Complex

### Steps to Reproduce
1. Start up OMEdit with no libraries loaded by default
2. Select "systems library --> Modelica --> 3.2.3" on the welcome screen
3. MSL 3.2.3 gets loaded but also ModelicaServices 4.0.0 and Complex 4.0.0

The same happens when one switches from an already loaded MSL4.0.0 to 3.2.3 triggered by a uses annotation in a user library

### Expected Behavior
The matching ModelicaServices and Complex library versions should be loaded.

### Version and OS

 - OpenModelica Version: OpenModelica 1.20.0~dev-336-g8a791ee
 - OS: Ubunutu 22.04.1
### Additional Context
@casella I think this ought to be a release blocker for 1.20.0

**Comment by perost** [comment]
That's done on purpose, we load the latest version that's compatible (see e.g. #8800). Are you experiencing some issue due to this?

**Comment by dietmarw** [comment]
I see. I'm actually not sure since I now found that using the "Check All Models" function on a library that uses MSL3.2.3 (and was loaded with it) complains about things like: 
Warning: <LibX> requested package Modelica of version 3.2.3. Modelica 4.0.0 is used instead
And then you get errors relating to 3.2.3 parameters not found in 4.0.0. This could well be a totally orthogonal problem but since I noticed that ModelicaServices and Complex are loaded as 4.0.0 I thought that had something to do with it.

**Comment by perost** [comment]
That seems like a different issue. ModelicaServices and Complex should be backwards compatible, but the MSL surely is not. So if MSL 4.0.0 is loaded for a library that uses 3.2.3 then we have an issue, but probably not related to ModelicaServices or Complex.

I tried the Check All Models myself on an older library, and then it loaded 3.2.3 even though I have a lot of different MSLs installed including 4.0.0. It wasn't the best experience since OMEdit froze for a long time while doing it and it printed out warnings about ModelicaServices and Complex for every single model it checked, so it could certainly be improved.

So the issue seems to be more complex than that Check All Models just does something wrong. Maybe @casella can have a look.

**Comment by dietmarw** [comment]
Yes looks like a different issue then. Still Check All Models seems to do some 4.0.0 checking on 3.2.3 libraries.

**Comment by casella** [comment]
@dietmarw I confirm that loading ModelicaServices and Complex 4.0.0 is ok, as they are fully backwards compatible. 

I tried the Check All Models feature on the MEV library, that was developed with MSL 3.2.3. I got several messages like this one:
```
Notification: Modelica requested package Complex of version 3.2.3. Complex 4.0.0 is used instead which states that it is fully compatible without conversion script needed. 
Notification: Modelica requested package ModelicaServices of version 3.2.3. ModelicaServices 4.0.0 is used instead which states that it is fully compatible without conversion script needed. 
```
which are fine, as they state things exactly as they are.

@dietmarw are you getting other messages involving 4.0.0 stuff? Can you post them here?

**Comment by casella** [comment]
I'll close this issue since it is a non issue and open another one one regarding Check All Models.

**Comment by dietmarw** [comment]
@adeas31 Just one last thing, would it be possible to remove the Complex and ModelicaServices notices. They clutter the report rather up and don't really add any useful info.

**Comment by adeas31** [comment]
It is possible. Question is shall we just suppress the notices in OMEdit or in the compiler?

**Comment by perost** [comment]
> It is possible. Question is shall we just suppress the notices in OMEdit or in the compiler?

Preferably in the compiler I think, but I'm not sure how easy that is.

**Comment by casella** [comment]
@dietmarw I'm not sure we really want to hide this. Package management is a non-trivial issue, you can pretend all works by magic, but up to a certain point. A notification is just a notification, not a warning, not an error. You can safely ignore it, if you want.

Besides, people will use MSL 3.2.3 less and less in the future, so this issue will fade away by itself anyway.

**Comment by dietmarw** [comment]
That notification is useful once for the library but not every single time. And makes it really hard to find the real issues.

**Comment by casella** [comment]
I agree. I'm not sure there is an easy way to avoid this, though.
