### ISSUE TITLE
Diagram contain black stains with new instantiation-based OMEdit GUI.

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9553]
### Description

Some diagrams of components from our BRSL library contain black stains when you zoom out or in.

### Steps to Reproduce

Load the BRSL package: Rexroth_Generic/package.mo
Example 1:

1. Drag and drop the ```Rexroth_Generic.Hydraulics.Cylinders.SingleRodCylinder``` on a new sheet.
2. Select "open class" from the conect menu of the  ```SingleRodCylinder```
3. Zoom in and zoom out, see picture 1

Example 2:

1. Drag and drop the ```Rexroth_Generic.Hydraulics.Cylinders.TandemCylinder``` on a new sheet.
2. Select "open class" from the conect menu of the  ```TandemCylinder```
3. Zoom in and zoom out, see picture 2

### Screenshots
**Picture 1**
<img width="541" alt="Stain-1" src="https://user-images.githubusercontent.com/12269776/196743991-36537729-6f07-4743-adcc-12a2518e2de8.png">

**Picture 2**
<img width="699" alt="Stain-2" src="https://user-images.githubusercontent.com/12269776/196744017-518d1e93-31fa-4cfa-ac32-890e93db6851.png">

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS: Windows 10 64 bit
 - MSL 4.0.0
 - BRSL 2.2 dev

### Additional Context

@sbaetzing @abuntrock

**Comment by adeas31** [comment]
I also noticed this today with MSL models. I will debug more tomorrow.
