### ISSUE TITLE
Encapuslated models cause "Check All Models" to load wrong MSL version

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9554]
### Description
When checking a library with "Check All Models" and that library contains an encapsulated model it will cause OMEdit to load "internally" the default version (most likely the latest, 4.0.0) version of MSL and from then on all classes are checked against MSL 4.0.0 even though the library uses 3.2.3

### Steps to Reproduce
1. Load:
```mo
package TestCheckAll
model A
  parameter Modelica.SIunits.Voltage V = 10;
end A;
encapsulated model B 
 parameter Modelica.SIunits.Current A = 5;
end B;
model C
  parameter Modelica.SIunits.Voltage V = 10;
end C;
annotation(
    uses(Modelica(version = "3.2.3")));
end TestCheckAll;
```
2. Run "Check All Models"
3. (**updated**) OMEdit reports model A to pass, but B and C to fail because of invalid (3.2.3) classes. **When it should really report B to fail because of the missing reference to a non-imported class and not because of invalid 3.2.3 classes** .
4. In addition OMEdit has now internally loaded MSL 4.0.0 even though the library browser is still displaying the 3.2.3 package. Only way to continue to work with OMEdit is to close and reopen it.

### Expected Behavior
OMEdit should not load MSL 4.0.0

### Version and OS
 - OpenModelica Version: OpenModelica 1.20.0~dev-336-g8a791ee
 - OS: Ubuntu 22.04.1

**Comment by perost** [comment]
> @perost this looks like an oversight in the mechanism for loading dependencies. There is no reason why encapsulated classes should be handled differently from this point of view. Encapsulation stops the lookup in the containing classes, but has nothing to do with dependencies on other packages.

It's most likely because we automatically try to load a library if we can't find a name during lookup (as specified), but we should probably first check that the library isn't already loaded in that case.

**Comment by dietmarw** [comment]
See also my update to 3.

**Comment by casella** [comment]
@perost, referring to @dietmarw's update, is omc also complaining that it can't find class parameter Modelica.SIunits.Current when checking B, because B is encapsulated?

If a class name XXX or XXX.YYY.ZZZ cannot be found in an encapsulated class, I would suggest to issue the following error:
> Class XXX (or XXX.YYY.ZZZ) could not be found because of encapsulation. Please add the import XXX; to the encapsulated class to make it accessible

**Comment by perost** [comment]
> @perost, referring to @dietmarw's update, is omc also complaining that it can't find class parameter Modelica.SIunits.Current when checking B, because B is encapsulated?
> 
> If a class name XXX or XXX.YYY.ZZZ cannot be found in an encapsulated class, I would suggest to issue the following error:
> 
> > Class XXX (or XXX.YYY.ZZZ) could not be found because of encapsulation. Please add the import XXX; to the encapsulated class to make it accessible

It just gives the standard "could not be found" error. Finding out if the name couldn't be found because of encapsulation would complicate the lookup quite a bit.

**Comment by casella** [comment]
OK. I checked with Dymola, which also issues a warning:

> Encapsulation of [TestCheckAll.B](modelica://TestCheckAll.B)
> prevented us from finding Modelica in global scope.

I found this very helpful to understand how to fix the problem. To help newbies, we may add a similar heuristic warning in  in case a class name could not be found:

> Warning: Look-up of XXX failed. Make sure it is properly installed and loaded, and add the statement import XXX; if you want to refer to it from inside an encapsulated package.

Is that easy to implement?
