### ISSUE TITLE
When opening a parameter dialog, OMEdit crashes with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9558]
### Description

When opening a parameter dialog of a component of the BRSL library that contains replaceable choices, OMEdit crashes.

### Steps to Reproduce

1. Load the BRSL package: ```Rexroth_Pumps/package.mo```
2. Drag and drop the ```Rexroth_Pumps.AxialPistonUnits.ConstantUnits.A4FO``` on a new sheet.
3. Open the paramter dialog of the ```A4FO`` component

### Version and OS

 - OpenModelica Version: v1.20.0-dev-348-g7cc2ddob5b (64-bit)
 - OS:  Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.2 dev

### Additional Context

@sbaetzing @abuntrock

**Comment by niklwors** [comment]
@adeas31  I can also open the dialog now, but the replaceable choices are now missing. Should I open an extra ticket for that?

**Comment by adeas31** [comment]
No. There is already a ticket about it. See #9559

**Comment by adeas31** [comment]
Closing this since the actual issue reported is fixed.

**Comment by niklwors** [comment]
But in my version there are no replaceable choices in the drop down menu available. You can easily check it with your installation.
So for us this is definitely no fixed

**Comment by niklwors** [comment]
<img width="824" alt="error" src="https://user-images.githubusercontent.com/12269776/197528521-7888281a-390e-4ee4-98ef-0f02d907198a.png">

**Comment by adeas31** [comment]
> But in my version there are no replaceable choices in the drop down menu available. You can easily check it with your installation.

Yes, there are no replaceable choices because of the issue reported in #9559.

> So for us this is definitely no fixed

The actual issue reported was that OMEdit is crashing opening parameters dialog. It is not crashing anymore.
For the replaceable choices we can follow #9559.
