### ISSUE TITLE
OMDev update CMake

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9566]
### Description

For some FMU features a newer CMake (version >= 3.21) is needed. On non-Windows systems it is easy to update, but on Windows we ship OMDev with MSYS that already has CMake.

### Additional Context

Needs #8501 to do any updates.
Needed to finalize #9509.

**Comment by AnHeuermann** [comment]
I'm not sure if we should ship CMake in the Windows installation. For some task users need a newer CMake version, but if `%OPENMODELICAHOME%/tools/msys/mingw64/bin` is in PATH before a newer CMake version it's not possible to build CMake FMUs with build dependencies. Should we tell users to install CMake before installing OpenModelica? Is there a way to handle these dependencies in Windows?

**Comment by bilderbuchi** [comment]
> I'm not sure if we should ship CMake in the Windows installation. For some task users need a newer CMake version, but if `%OPENMODELICAHOME%/tools/msys/mingw64/bin` is in PATH before a newer CMake version it's not possible to build CMake FMUs with build dependencies. Should we tell users to install CMake before installing OpenModelica? Is there a way to handle these dependencies in Windows?

When you explicitly use that newer cmake for the configure step (e.g. `/path/to/my/newer/cmake -G ...`), doesn't that path get recorded in a variable in CMakeCache.txt (`CMAKE_COMMAND`?) and will be automatically used where appropriate afterwards?

**Comment by AnHeuermann** [comment]
Maybe, but you would need to do this for each build of a simulation executable or FMU. We could probably make the CMake path an option users can configure. Currently we are using Autoconf.cmake which should be `constant String cmake = "cmake";`. Changing that to something configurable should be possible, simmilar on how you can change the C compiler.

**Comment by bilderbuchi** [comment]
It seems I misunderstood what you meant with "For some task users need a newer CMake version". I thought you meant that task is unrelated to OMEdit/FMU, but the OM-shipped version takes priority (via `PATH`) if users just invoke plain `cmake` -- that was the case I tried to offer a solution for (i.e. users _can_ select the desired cmake version that way).

**Comment by AnHeuermann** [comment]
Ah I see. Maybe my original post was a bit unclear.

**Comment by BasilioPV** [comment]
@AnHeuermann Is this issue closed?

**Comment by AnHeuermann** [comment]
@adrpo updated CMake to 3.28.1
The nightly builds and the next release should work out of the box.
