### ISSUE TITLE
Expected XXX_FMU to be a class, but found component instead.

### ISSUE THREAD

**Issue by richman2024** [OpenModelica/OpenModelica#9570]
I got bleow error whatever the FMU function is. 

Expected XXX_FMU to be a class, but found component instead.](omeditmessagesbrowser:///test?lineNumber=0)

I have no idea what happened, since the same FMU can be worked 1 years ago

**Comment by casella** [comment]
Probably related to #6000, is that the case?

**Comment by AnHeuermann** [comment]
Resolved in https://github.com/OpenModelica/OpenModelica/issues/6000#issuecomment-1288684373
