### ISSUE TITLE
Jacobian generation for sparse systems should not scale as O(N^2)

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9588]
Please check the new backend performance of `AdvectionReactionXXX` systems in the [ScalableTestSuite](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite/ScalableTestSuite.html) library. The time spent by the Jacobian generation is O(N^2), although the number of non-zero elements in it is O(N).

**Comment by casella** [comment]
Possibly #9031 improved the situation, let's see the testsuite results.

**Comment by casella** [comment]
Unfortunately the issue is not completely resolved, see the [latest report](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html).

| Model | Jacobian time  |
| ------- | -------------|
|AdvectionReaction_N_3200 | 0.36 |
|AdvectionReaction_N_6400 | 0.94 |
|AdvectionReaction_N_12800 | 2.43 |
| ---- | --------- |
|CascadedFirstOrder_N_6400 | 0.92 |
|CascadedFirstOrder_N_12800 | 2.39 |
|CascadedFirstOrder_N_25600 | 8.73 |

**Comment by casella** [comment]
Based on some profiling, the bottleneck is most likely found in the section of the code where the variables of the Jacobian are scalarized _including their attributes_, for the scalarized sparsity pattern. Maybe this operation is not done in the most efficient way, CS-wise. 

This section is basically the same as in the frontend (which scalarizes as O(N)), except for attributes, so the culprit is most likely there. Function NFScalarize.scalarizeBackendVariable. Here a regular list structure while expression iterator seem to be more efficient.

Possible actions:
- disable scalarization of attributes, to see if this solves the problem
- have @perost look at the code and see if he spots some obvious inefficiency

**Comment by kabdelhak** [comment]
After my update regarding scalarization of variables the times now look like this:

| Model | Jacobian time |
| ------------- | ------------- |
| CascadedFirstOrder_N_3200 	| 0.1561 |
| CascadedFirstOrder_N_6400 	| 0.4253 |
| CascadedFirstOrder_N_12800 	|1.401|
| CascadedFirstOrder_N_25600 	| 5.152 |

Its gotten better but still scales badly and i narrowed it down to two crucial parts. The first part being dependency collection:
| Model | Jacobian time |
| ------------- | ------------- |
| CascadedFirstOrder_N_3200 	| 0.014030523|
| CascadedFirstOrder_N_6400 	| 0.022975218 |
| CascadedFirstOrder_N_12800 	| 0.126372858 |
| CascadedFirstOrder_N_25600 	| 0.31403685|

and the other one being the coloring algorithm:
| Model | Jacobian time |
| ------------- | ------------- |
| CascadedFirstOrder_N_3200 	| 0.115406262|
| CascadedFirstOrder_N_6400 	| 0.2730025859999999 |
| CascadedFirstOrder_N_12800 	| 1.189437214 |
| CascadedFirstOrder_N_25600 	| 4.57412575 |

As we can see, the coloring algorithm causes the majority of time loss, but dependency collection could  be a relevant bottle neck after coloring is solved. Our implementation is a pretty simple greedy one taken from the publication "What color is your jacobian?" and on analysis i could not find oversights in the implementation. The algorithm itself just seems to scale like this. The paper claims a computation time of `O(|E| · ∆(V))` where `E` is the set of edges and `V` is the set of variables with  `∆(V)` as their maximum degree. In the paper it also states that they assume `∆^2 << |V |`, which might not be true for our scaling models.

In my opinions our options here are:
  1. Design a new greedy algorithm that scales better (but probably has worse results)
  2. Implement current one in C (still bad scaling but way better single operation costs)
  3. move all of the sparsity and coloring detection to runtime
  4. Design an array based sparsity and coloring algorithm
  
I ordered them such that 1. has least expected effort and 4. the most. 1 and 2 would only be temporary solutions whereas i could see 3 and 4 as permanent solutions. @bernhardbachmann already proposed that 3. could be a good idea while working on the gbode solver. The perfect solution in my opinion would be a combination of 3 and 4, but this would take a lot of time.

@casella What do you think?

**Comment by casella** [comment]
Judging by the test results I'm still not 100% convinced that this is an inherent problem of the colouring algorithm.

I compared the profiling of the OB for "symbolic Jacobian (simulation)" and of the NB for "Jacobian" from the [OB](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) and [NB](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html) Jenkins reports:

| N | OB | NB |
|--|--|--|
|3200 |0.058 | 0.64 |
|6400 | 0.48 | 1.64|
|12800 | 0.27 | 3.85|
|25600 | 1.25 | 12.14|

As I understand, the same colouring algorithm is also implemented in the OB.

Now, the behaviour is slighlty irregular, which is possibly due to the fact that the algorithm uses a greedy heuristics, or possibly because of other stuff running in parallel and accessing the memory. Anyway, what is very clear to me is that if you compare the performance for N = 6400 and N = 25600, which is 4X bigger, the OB takes 3X more time, while the NB takes 8X more time. Ditto, if you compare N = 3200 with N = 12800, the OB takes 4X more time while the NB takes 6X more time.

I will check these figures on my PC, to avoid issues with many computations running in parallel which could spoil the results, but I'm still convinced that there is something in the implementation of the NB colouring algorithm that is not scaling correctly. Before starting new implementations, I'd like to be absolutely certain that the issue is not due to some inefficient MetaModelica data structure handling.

**Comment by casella** [comment]
> As we can see, the coloring algorithm causes the majority of time loss, but dependency collection could be a relevant bottle neck after coloring is solved. Our implementation is a pretty simple greedy one taken from the publication "What color is your jacobian?" and on analysis i could not find oversights in the implementation. The algorithm itself just seems to scale like this. The paper claims a computation time of `O(|E| · ∆(V))` where `E` is the set of edges and `V` is the set of variables with `∆(V)` as their maximum degree. In the paper it also states that they assume `∆^2 << |V |`, which might not be true for our scaling models.

CascadedFirstOrder has a really simple sparsity structure for the ODE Jacobian: the derivative of each state depends on the state itself and on the previous state in the cascaded chain. So, the incidence matrix is lower bi-diagonal. As I understand `∆ = 2`, so as `|V |` increases the condition  `∆^2 << |V |` should definitely hold. Do I get it right?

**Comment by casella** [comment]
Here are the results from my i9-12900 server:

| N | OB | NB |
|--|--|--|
|3200 |0.035 | 0.10 |
|6400 | 0.082 | 0.35 |
|12800 | 0.17 | 1.11|
|25600 | 0.43 | 4.4 |

It seems very clear to me that the implementation of colouring in the OB is much more efficient than the one in the NB. I'd definitely have a closer look at them to figure out why this is the case.

**Comment by kabdelhak** [comment]
> CascadedFirstOrder has a really simple sparsity structure for the ODE Jacobian: the derivative of each state depends on the state itself and on the previous state in the cascaded chain. So, the incidence matrix is lower bi-diagonal. As I understand `∆ = 2`, so as `|V |` increases the condition `∆^2 << |V |` should definitely hold. Do I get it right?

Yes it does and i also understand why it scales badly. The result of this is that everything needs a separate color and that's where this algorithm also scales badly i think.

**Comment by kabdelhak** [comment]
> As I understand, the same colouring algorithm is also implemented in the OB.

I looked into it and that is true.

> but I'm still convinced that there is something in the implementation of the NB colouring algorithm that is not scaling correctly. Before starting new implementations, I'd like to be absolutely certain that the issue is not due to some inefficient MetaModelica data structure handling.

The OB uses a C implementation of the same algorithm. It looks like i can use that framework too, it should not take too long to understand the interface. From what i can see it still scales nonlinearly but it will be an improvement.

**Comment by casella** [comment]
> Yes it does and i also understand why it scales badly. The result of this is that everything needs a separate color and that's where this algorithm also scales badly i think.

Hmm. Are you telling me that in this case you actually need N colours?

I'm not much into coloured jacobians, but this doesn't seem necessary to me. As I see it, you just need two colours: one for even elements of the array, and one for the odd ones. Do I miss something?

**Comment by casella** [comment]
What I'm still not sure about is whether or not these tests are just pushing the algorithm to the limit, but are not representative of real-life large-scale models.

**Comment by kabdelhak** [comment]
> I'm not much into coloured jacobians, but this doesn't seem necessary to me. As I see it, you just need two colours: one for even elements of the array, and one for the odd ones. Do I miss something?

You are right, don't know what i was thinking. It would have matched the part that is slow in my implementation. I don't really understand what happens there, but i was able to adapt the C implementation interface for the NB. New results:

Its gotten better but still scales badly and i narrowed it down to two crucial parts. The first part being dependency collection:

| Model | dependency collection time |
| ------------- | ------------- |
| CascadedFirstOrder_N_3200 	| 0.014029656|
| CascadedFirstOrder_N_6400 	| 0.021201807 |
| CascadedFirstOrder_N_12800 	| 0.126672392 |
| CascadedFirstOrder_N_25600 	|0.090149821|

and the other one being the coloring algorithm:
| Model | sparsity pattern time |
| ------------- | ------------- |
| CascadedFirstOrder_N_3200 	| 0.007812469000000001|
| CascadedFirstOrder_N_6400 	| 0.012739372|
| CascadedFirstOrder_N_12800 	| 0.025361548|
| CascadedFirstOrder_N_25600 	|0.055964222|

Sparsity pattern detection scales fine now from what it looks like, the dependency collection still is a little off. I don't know why it suddenly took less time for the last size increment, i suppose it is mainly overhead cost at what we are looking here. I ran it three times and it always looked like this, so maybe there is some fishy memory management going on.

Overall it seems fine for now, but dependency collection could be a problem in the future.

I will clean up my branch and create a PR.

**Comment by casella** [comment]
Excellent! 

The somewhat erratic performance of dependency collection doesn't scare me too much, as long as we are around a tenth of a second for 25.000 states. That is acceptable (it's two orders of magnitude smaller than it was previously), at least for the time being. Lets' see what happens when we can run larger models with a few hundred thousand states, but I'm not seeing a clear superlinear behaviour with size, so I'm not expecting big surprises there.

I just started [a new job](https://test.openmodelica.org/jenkins/job/LibraryTesting/job/LibraryTest/5748/) with the newInst library testsuite, let's see what the results are on the whole testsuite.

**Comment by casella** [comment]
Looks like the situation improved significantly with #10024, see [regression report](https://libraries.openmodelica.org/branches/history/newInst-newBackend/2023-01-06%2017:42:58..2023-01-09%2018:07:49.html): the backend time for CascadedFirstOrder_N_25600 went down by a factor 4-5X.

Looking at the [new ScalableTestSuite report](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html), CascadedFirstOrder_N_25600 now takes 7.5 s overall to build, while it takes 62 s with the [old backend](https://libraries.openmodelica.org/branches/master/ScalableTestSuite_noopt/ScalableTestSuite_noopt.html).

AdvectionReaction models also scale very favourably, the largest one taking 3.2 s to build, compared to 25 s with the old backend.

I think this is quite good, at least for the time being. Thanks @kabdelhak for your effort.
