### ISSUE TITLE
The NB does not differentiate the sum() operator

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9624]
When compiling [ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5.err](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5.err) with the new backend, the following error is generated:
```
Error: Internal error NBDifferentiate.differentiateBuiltinCall1Arg failed for: sum
```

**Comment by kabdelhak** [comment]
I added the differentiation of `sum()` in #9709, the model still fails since list for loop generators are not yet correctly parsed, i will keep this open for now until i fixed that.

**Comment by casella** [comment]
I'll open a new ticket when the testing results are available. @kabdelhak if you want to post the new error message here, I can do that right away.

**Comment by phannebohm** [comment]
The aforementioned model compiles now and fails during initialization with
```
assert            | debug   | Division by zero 2.0 * (x - xmin) / (xmax - xmin) in function context
assert            | info    | simulation terminated by an assertion at initialization
```
Closing this issue as it seems fixed. The zero division is something else.

**Comment by casella** [comment]
> Closing this issue as it seems fixed. The zero division is something else.

#9986 for the record.
