### ISSUE TITLE
OMEdit 1.19.0, 1.19.2, 1.20.0-dev crashing on startup under win10

### ISSUE THREAD

**Issue by bc0n** [OpenModelica/OpenModelica#9643]
### Description
Installing a new version of OMEdit, the window launches from the installer and works fine.  Closing and relaunching OMEdit, it draws the main window and welcome screen with a spinning cursor, I see the Automatically loaded package messages for Complex and ModelicaServices, then the window crashes.  Subsequent launches all crash.  Deleting omedit.ini does not fix.  It launches and works correctly under Administrator.  1.19.0 shows the same behavior.

Event viewer gives events:
```
---------------------------------------------------------
Faulting application name: OMEdit.exe, version: 0.0.0.0, time stamp: 0x635f2c53
Faulting module name: ntdll.dll, version: 10.0.19041.2130, time stamp: 0xb5ced1c6
Exception code: 0xc0000374
Fault offset: 0x00000000000ff6a9
Faulting process id: 0x9358
Faulting application start time: 0x01d8ee0f0bcb3f13
Faulting application path: C:\Program Files\OpenModelica1.20.0-dev-64bit\bin\OMEdit.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: f6a1f676-23cb-4fb4-a5bd-0e79bc501158
Faulting package full name: 
Faulting package-relative application ID: 
---------------------------------------------------------
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: OMEdit.exe
P2: 0.0.0.0
P3: 635f2c53
P4: StackHash_2131
P5: 10.0.19041.2130
P6: b5ced1c6
P7: c0000374
P8: PCH_4D_FROM_ntdll+0x000000000009DC14
---------------------------------------------------------
```

### Steps to Reproduce
Launch OMEdit from start menu.

### Version and OS
OpenModelica-v1.20.0-dev-410-gbe1f2bf045-64bit
Win10 x64
MSL 4.0

I didn't see a verbose flag if launched from cmd, let me know if I can take a better log.
Thanks

**Comment by adeas31** [comment]
Run `OMEdit.exe --Debug=true`. Send the `omeditcommunication.log` file located in temp.

**Comment by bc0n** [comment]
[omeditcommunication.log](https://github.com/OpenModelica/OpenModelica/files/9913127/omeditcommunication.log)

**Comment by adeas31** [comment]
The log gives no hint about what is going wrong. Please upload the whole ´%TEMP%/OpenModelica/OMEdit´ folder. There are other log files that might show some information.

**Comment by adeas31** [comment]
Simple google search about `Faulting module name: ntdll.dll` tells to reboot or reinstall the program.

**Comment by bc0n** [comment]
That was it @adeas31, many thanks.
