### ISSUE TITLE
enable setActive option for simulation results loaded from existing file

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#9652]
### Description
This is an enhancement suggestion:
In version v1.19.0-dev-590-g0897872ac1 one could load an existing simulation result file but can not set result tree to active (setActive option is grayed out). As a result one could not "replay" the simulation result on a model with DynamicSelect

### Expected Behavior

One could replay existing simulation result

### Version and OS

 - OpenModelica Version: v1.19.0-dev-590-g0897872ac1
 - OS:  Windows 10, 64 bit

**Comment by Arinomo** [comment]
@adeas31 a quick question, this patch was not included in 1.20.beta, right?

**Comment by adeas31** [comment]
No, it is included.

**Comment by casella** [comment]
@Arinomo you can check the [commit history of maintenance/v1.20](https://github.com/OpenModelica/OpenModelica/commits/maintenance/v1.20), you find it in the first page.
