### ISSUE TITLE
Impossible to delete OMEdit toolbar

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9674]
### Description
Impossible to delete OMEdit toolbar

### Steps to Reproduce
Open a model in OMEdit
remove the shapes toolbar right-click on toolbar area, unselect Shapes Toolbar checkbox). The toolbar is deleted
click on desktop
click on OMEdit window => the shapes toolbar is back!

### Expected Behavior
if I delete a toolbar is should stay deleted up when I require it to be shown again

### Version and OS

OM 1.21.0-dev
Ubuntu 22.4 (checked also on WIndows 11)

**Comment by adeas31** [comment]
This was not as straight forward as I thought. We show/hide toolbars based on the different perspectives i.e., modeling, plotting, etc. So the shapes toolbar always becomes visible when the modeling perspective is active.

With PR #11046, I changed it so each perspective have its own show/hide setting for toolbars.
