### ISSUE TITLE
Custom connectors icons are not rendered in diagram view

### ISSUE THREAD

**Issue by matteodepascali** [OpenModelica/OpenModelica#9689]
### Description
Custom connectors icons are not rendered in diagram view, while Modelica Standard Library Connectors are rendered correctly.

### Steps to reproduce
TestPackage.mo contains a custom connector model and a test model TestModel where the connector is instanciated. Opening TestModel's diagram view, the connector's icon is not rendered correctly.

### Expected behavior
The connector's icon should be displayed correctly

### Additional files
[TestPackage.txt](https://github.com/OpenModelica/OpenModelica/files/9989602/TestPackage.txt)

### Version and OS
 - OpenModelica Version 1.21.0-dev-5-ga68b9e2dbd (64-bit)
 - OS: windows 11 64 bit

**Comment by adeas31** [comment]
This is the expected behaviour. There is no `Diagram` annotation of `TestConnector`.

**Comment by matteodepascali** [comment]
You are right, it is missing the Diagram annotation. 
I opened the ticket because this was not the standard behavior with the OMEdit version I was working with before updating to 1.21.
The Icon annotation was enough to show the connectors in Diagram View of other models.

**Comment by adeas31** [comment]
That is true. I recently changed it to conform to the Modelica specification,

`For connectors, the icon layer is used to represent a connector when it is shown in the icon layer of the enclosing model. The diagram layer of the connector is used to represent it when shown in the diagram layer of the enclosing model.`

**Comment by matteodepascali** [comment]
Perfect, thanks for the clarification and the help!

**Comment by casella** [comment]
Too bad other tools don't do that. But that is no reason to accept non-standard code, as usual.
