### ISSUE TITLE
The solver is chattering but it doesn't show in the plots

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9711]
Please simulate the following MWE:
```modelica
model test_min
  Real x(start=1.0, fixed=true),y(start=0.0, fixed=true);
  parameter Real a=-0.01; // Fine tune to get OMC as slow as needed.
equation
  der(x) = x*(y+1);
  der(y) = if noEvent(y > 0.5) then a else 1.0;
annotation(
    experiment(StartTime = 0, StopTime = 0.52, Tolerance = 1e-6),
    __OpenModelica_simulationFlags(lv = "LOG_STATS", noEquidistantTimeGrid = "()", s = "dassl"));
end test_min;
```
After time > 0.5, the solution enters a chattering phase: because of the discontinuous RHS, the derivative oscillates extremely fast between a positive and a negative value, keeping y very close to the 0.5 threshold. The variable-step size algorithm estimates large errors (due to the discontinuous behaviour) so it reduces the step size to extremely small values, causing a ludicrous number of steps to be taken.
```
events
    0 state events
    0 time events
solver: dassl
580729 steps taken
1185650 calls of functionODE
871059 evaluations of jacobian
    7 error test failures
290348 convergence test failures
```
This is the plot of y, which remains around 0.5 after time > 0.5
![immagine](https://user-images.githubusercontent.com/4233148/202204489-d1ff3930-6eea-49f7-ba80-3df65b3ca438.png)

This is expected behaviour, given the nature of the model. What is not OK is the plot of der(y):

![immagine](https://user-images.githubusercontent.com/4233148/202204876-22e2fc25-6b13-48fb-9dc6-8f4e129ba35b.png)

I switched equidistant time grid off, so I would expect to see rapidly alternating positive and negative values of the derivative. Instead, I see a constant value of -0.01, which is of course wrong, since y is actually constant!

What I would expect to see is something like this (obtained from Dymola)

![immagine](https://user-images.githubusercontent.com/4233148/202206683-0c47deff-d341-4605-b1e2-66ecb1ecabdd.png)

I strongly suspect that this is a tell-tale sign revealing that something is not handled correctly when systems with noEvent are simulated.

@AnHeuermann, @kabdelhak I would really urge you to figure out exactly what is going on in this very simple example (only one equation), because it may hold the key to solving #9131.

**Comment by AnHeuermann** [comment]
I can rule out that this is just a display problem. No `der(y)=1` is written into the result file after `time > 0.5`.

After each DASSL step we do an additional ODE evaluation (in `simulationUpdate`) to check if some zero-crossing changed, clock timers need to be added or asserts are thrown. So whenever becomes `der(y)=-0.01` DASSL computes `y=1`. So when we now evaluate the ODE again `der(y)=if noEvent(y > 0.5) then a else 1.0` leads to `der(y)=-0.01`.

I don't see a way to resolve this. We can't remove the `simulationUpdate`.
And isn't this behavior (derivative changes while state hasn't changed) an indicator for an issue?

**Comment by casella** [comment]
> After each DASSL step we do an additional ODE evaluation (in `simulationUpdate`) to check if some zero-crossing changed, clock timers need to be added or asserts are thrown. So whenever `der(y)=-0.01` DASSL computes `y=1`.

I don't understand, y is a state, why should it be computed to be one?

**Comment by casella** [comment]
Anyway, I think I understand what is going on, it depends on the fact that the discontinuity is strongly asymmetric when a  =-0.01.

**Comment by casella** [comment]
Consider this even simpler MWE:
```modelica
model TestChattering
  Real x(start=0.0, fixed=true);
  parameter Real a=-1;
equation
  der(x) = if noEvent(x > 0.5) then a else 1.0;
end TestChattering;
```
If I simulate it with an explicit algorithm, flags: `-s=gbode -gbm=dopri45 -noEquidistantTimeGrid`, I can see the chattering behaviour:
![immagine](https://user-images.githubusercontent.com/4233148/202479999-2429f451-cf88-4d8e-84f9-3198c5519354.png)
These are the values of time and x close to the discontinuity:
```
   0.499997528618574   0.499997528618574
   0.499999022992887   0.499999022992887
   0.499999676781648   0.499999676781648
   0.499999893841391   0.499999893841391
   0.499999975572937   0.499999975572937
   0.500000089911597   0.499999987181444
   0.500000149016888   0.499999993182251
   0.500000182927213   0.499999996625078
   0.500000208867036   0.499999998720089
   0.500000232335258   0.500000000615483
   0.500000263630762   0.499999998087924
   0.500000303409410   0.500000001300617
   0.500000351989322   0.499999997377097
   0.500000409373966   0.500000002011725
   0.500000475303217   0.499999996686998
   0.500000549317159   0.500000002664679
   0.500000630820680   0.499999996082107
   0.500000719141290   0.500000003215256
   0.500000813576396   0.499999995588275
   0.500000913429055   0.500000003652801
   0.500001018033015   0.499999995204539
```
As you can see, the behaviour with an explicit algorithm and a symmetric discontinuity is obvious: at each time step, the solution is taken on the other side of the discontinuity, and this goes on forever.

If I use dassl, instead, which is implicit, this adds some damping to the solution, because of the "look-ahead" effect of the implicit BDF formula, and also apparently the error control is more cautious, so it takes shorter steps. Hence, I still get chattering, but not every other step:
```
   0.500000017578125   0.500000000000000
   0.500000018554687   0.500000000976562
   0.500000020507812   0.499999999023438
   0.500000021484375   0.500000000000000
   0.500000023437500   0.499999998046875
   0.500000024414062   0.499999999023438
   0.500000026367187   0.499999997070313
   0.500000027343750   0.499999998046875
   0.500000029296875   0.500000000000000
   0.500000030273437   0.499999999023438
   0.500000032226562   0.500000000976562
   0.500000033203125   0.500000000000000
   0.500000035156250   0.500000001953125
   0.500000036132812   0.500000000976562
   0.500000038085937   0.500000002929687
   0.500000039062500   0.500000001953125
   0.500000041015625   0.500000003906250
   0.500000041992187   0.500000002929687
   0.500000043945312   0.500000000976562
   0.500000044921875   0.500000001953125
   0.500000046875000   0.500000000000000
   0.500000047851562   0.500000000976562
   0.500000049804687   0.499999999023438
   0.500000050781250   0.500000000000000
   0.500000052734375   0.499999998046875
   0.500000053710937   0.499999999023438
   0.500000055664062   0.499999997070313
   0.500000056640625   0.499999998046875
   0.500000058593750   0.500000000000000
   0.500000059570312   0.499999999023438
```
If I now make the discontinuity asymmetric with a = -0.01, the solution pulls toward y = 0.5 less strongly when you are above it than when you are below it, so it seems that the damping effect of the implicit solver is such that the "next state" never actually crosses the threshold. So you get this derivative
![immagine](https://user-images.githubusercontent.com/4233148/202499508-e30d43ce-21fc-4ebf-a45a-663ffbe72b83.png)
and these values for time and state
```
   0.500000000000000   0.500000000000000
   0.500000003906250   0.499999999960937
   0.500000005859375   0.500000001914062
   0.500000009765625   0.500000001875000
   0.500000017578125   0.500000001796875
   0.500000033203125   0.500000001640625
   0.500000064453125   0.500000001328125
   0.500000126953125   0.500000000703125
   0.500000158203125   0.500000000390625
   0.500000173828125   0.500000000234375
   0.500000181640625   0.500000000156250
   0.500000185546875   0.500000000117187
   0.500000193359375   0.500000000039063
   0.500000197265625   0.500000003945313
   0.500000205078125   0.500000003867187
   0.500000220703125   0.500000003710938
   0.500000251953125   0.500000003398438
   0.500000314453125   0.500000002773437
   0.500000439453125   0.500000001523437
   0.500000501953125   0.500000000898437
   0.500000533203125   0.500000000585937
   0.500000548828125   0.500000000429687
   0.500000580078125   0.500000000117187
   0.500000583984375   0.500000000078125
   0.500000585937500   0.500000000058594
   0.500000589843750   0.500000000019531
   0.500000591796875   0.500000001972656
   0.500000595703125   0.500000001933594
   0.500000603515625   0.500000001855469
   0.500000619140625   0.500000001699219
   0.500000650390625   0.500000001386719
   0.500000712890625   0.500000000761718
   0.500000744140625   0.500000000449218
   0.500000759765625   0.500000000292968
   0.500000767578125   0.500000000214843
   0.500000783203125   0.500000000058593
   0.500000785156250   0.500000000039062
   0.500000789062500   0.500000003945312
   0.500000796875000   0.500000003867187
   0.500000812500000   0.500000003710937
```
BTW, the nice thing in this case is that this case can be worked out analytically. If you apply implicit Euler (BDF-1) to this system, defining `w = x_k` and `z = x_k+1`, you get
```
(x_k+1 - x_k)/h = if x_k+1 > 0.5 then -a else 1.0
(z - w)/h = if z > 0.5 then -a else 1.0
z - w = if z > 0.5 then -a*h else h
z - w - (if x_k+1 > 0.5 then -a*h else h) = 0
f(z, w, h) = 0
```
At each time step, you need to solve this implicit equation for z (the next state) given w (the current state) and the step size h. @AnHeuermann, I don't have time to play with this now, but maybe you could understand something more by doing that,

**Comment by casella** [comment]
I think we can draw two conclusions here.

The first is that the behaviour of OMC in the presence of noEvent'd discontinuities and dassl is reasonable. I can't say for certain that it is correct, but it is definitely plausible. In fact, there's no "correct" behaviour of dassl if the fundamental assumptions of variable-order BDF, namely that the RHS is smooth enough, are so blatantly violated.

Which brings us to the conclusion of this ticket, which I believe are relevant for #9131 as well. Integrating systems which contain conditional expressions with suppressed events (either because of `noEvent()` or because of `smooth()`) is potentially problematic, if the expression is actually not smooth enough, either intentionally or by mistake.

If the solver can cope, there is no reason to bother the end user.

However, if the solver gets stuck or shows dismal performance, it should be possible to debug the issue with a reasonable effort. In the case of #9131 I tried to follow the information flow through the model by inspection, but that is really a difficult task, particularly if the model is obtained by connecting several sub-models, so that is not a viable path in general.

My recommendation is to add the possibility to log the change of conditions in noEvent expressions at runtime. As the saying goes, "the tongue always turns to the aching tooth". Let the solver itself tell us where the problem is, by showing what is the condition that changes all the time, causing the step size to reduce and the jacobian to be recomputed often. Then, it would be possible to either fix the source code, or improve the solver, or both.

I'll open a ticket about that ASAP.
