### ISSUE TITLE
Crazy synchronous machine icon

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9729]
### Description

![image](https://user-images.githubusercontent.com/7373030/203165759-eccae11c-75fc-4c82-9afa-8a4a2612e80f.png)

I don't know when this huge white triangle has appeared on the correct icon. It was not there in OM 1.20.0-dev-415
### Version and OS

1.21.0-dev-38 (as reported by Ubuntu)

**Comment by ceraolo** [comment]
In today's nightly the issue is not present anymore

**Comment by adeas31** [comment]
I somehow missed this issue :). But yes this is already fixed.
