### ISSUE TITLE
Issue with Buildings.ThermalZones.EnergyPlus models

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9731]
If you check the [Buildings_latest](https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html) report, all the `Buildings.ThermalZones.EnergyPlus_9_6_0` models fail at runtime. Similarly for `Buildings.ThermalZones.EnergyPlus.Examples` in [Buildings 8](https://libraries.openmodelica.org/branches/master/Buildings_8/Buildings_8.html).

The models contain some EnergyPlus external functions which are installed by a Python script
```
 "runOnceBeforeTesting": [
  [
   "$resourceLocation/src/ThermalZones/install.py",
   "--binaries-for-os-only"
```
@adrpo reported by email on Nov 10:

> It works on my machine but not on Jenkins.
> 
> It seems the jenkins path has a @ in it which the FMU cannot properly handle in the URI resource location. I guess if one tries to put the library in a path containing @ it will fail to parse the JSON.
> 
> I will see if I can make Jenkins to not use a @ in the job workspace path.

@mwetter reported by email on Nov 10
```
Interesting. It works on my system if I start OMEdit from the directory
`~/test/test@test/modelica-buildings/Buildings`
and run for example Buildings.ThermalZones.EnergyPlus_9_6_0.Validation.ZoneSurface.OneZoneConstantFloorTemperature

```

@adrpo reported by email on Nov 10

> Ok! I can reproduce it.
> If the working directory (where the simulation
> executable is ran) contains "@" then it fails
> to parse the JSON.
> 
> mkdir test@test
> cd test@test
> cat > script.mos
> loadModel(Buildings, {"10.0.0"}); getErrorString();
> simulate(Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.ASHRAE2006Winter); getErrorString();
> CTRL+D
> omc script.mos > trace.txt
> 
> gets you:
> messages = "Simulation execution failed for model: Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice.ASHRAE2006Winter
> Cannot parse json: '/home/adrpo33/test%40test/spawn-ASHRAE2006Winter.flo/resources/model.spawn'
> Unknown Exception during EnergyPlus fmi2Instantiate
> 
> I guess the %40 in the URI needs to be translated into @ by the FMU but it doesn't happen. Probably only it removes the ["file://"](file:///) from the URI: file:///path and keeps the path as it is.
> 
> If I think about it, probably also the OM FMUs does the same but one would need to handle also the translation of the %NN from the path.
> We need to check this.

So, it seems we have some issue with '@' in URI pathnames inside FMUs. But not on all machines. I'm not really sure what is the best way to solve this, probably, as @adrpo suggests, getting rid of `@` in the jenkins pathname would help a lot.

**Comment by casella** [comment]
Jenkins now uses `_` instead of `@`. Most of the failing tests now work again.

Most `Buildings.ThermalZones.EnergyPlus_9_6_0.Examples.SmallOffice`still fail, presumably because of slow simulations triggering timeouts.

**Comment by casella** [comment]
@mwetter, you can check the [regression report](https://libraries.openmodelica.org/branches/history/master/2022-11-21%2022:25:55..2022-11-23%2000:59:38.html) showing the models being restored to good functioning. We still need to figure out what's wrong with the SmallOffice models, but that's another issue.

**Comment by mwetter** [comment]
Thanks for fixing the `EnergyPlus_9_6_0` tests, which look good apart from some of the models that seem to have simulation issues.

Also, a frequent occurrence that leads some models to fail is
`division by zero at time 0, (a=0) / (b=0), where divisor b expression is: hvac.cooCoi.m1_flow + hvac.ideVal.preMasFlo.m_flow`.
This affects
`
Buildings.Air.Systems.SingleZone.VAV.Examples.ChillerDXHeatingEconomizer
Buildings.Air.Systems.SingleZone.VAV.Examples.Guideline36
Buildings.Air.Systems.SingleZone.VAV.Examples.OptimalStart.ConventionalSpring
Buildings.Air.Systems.SingleZone.VAV.Examples.OptimalStart.ConventionalSummer
Buildings.Air.Systems.SingleZone.VAV.Examples.OptimalStart.ConventionalWinter
Buildings.Experimental.DHC.Plants.Cooling.Examples.ElectricChillerParallel
Buildings.Obsolete.Air.Systems.SingleZone.VAV.Examples.Guideline36
`
(and I think some others). This looks like it is related to mixing of mass flows when mass flow rates are zero.

**Comment by casella** [comment]
Thanks @mwetter for pointing out this other issue, see  #9778. Given all the information available, it shouldn't be too hard to fix it.
