### ISSUE TITLE
Remove delay(<expr>,0) in the NF

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9735]
The issue in #9131 is ultimately caused by something going wrong in the Jacobian computation due to `delay()` operators called with `delayTime = 0`. Although the exact mechanism is not yet fully clear, removing those delay operators fixes the problem.

We should then do this directly during flattening. Every time the NF is faced with a call to `delay()` with `delayTime` being a parameter expression, this expression should be tentatively evaluated. If the result is zero, then the call to the `delay()` operator should be replaced by its first argument.

@perost can you please implement this ASAP? This should finally fix #9131 for good.

If this fix has beneficial effects on the library testsuite, we should incorporate it in 1.20.0 (or 1.20.1 if it takes more than a few days to test it).

Keeping @AnHeuermann and @kabdelhak in the loop.

**Comment by casella** [comment]
BTW, there is some discussion to forbid delayTime = 0 in MLS 3.6, see modelica/ModelicaSpecification#3287. In that case, we may add a warning and eventually an error here. However this doesn't harm for the time being - in fact, I expect it to do some good 😄

**Comment by casella** [comment]
@perost, unfortunately I cannot yet test this because the Windows nightly builds are broken. Would you mind testing if the BR test model `Rexroth_Valves_Test.Valves_4WR.Rexroth_4WSE2ED10_5X_5.VC43_PO_TC11a` simulates with a reasonable number of steps and Jacobian computations (not one million of them)?

**Comment by perost** [comment]
> @perost, unfortunately I cannot yet test this because the Windows nightly builds are broken. Would you mind testing if the BR test model `Rexroth_Valves_Test.Valves_4WR.Rexroth_4WSE2ED10_5X_5.VC43_PO_TC11a` simulates with a reasonable number of steps and Jacobian computations (not one million of them)?

LOG_STATS gives me:
```
LOG_STATS         | info    | ### STATISTICS ###
|                 | |       | | timer
|                 | |       | | |      0.32885s          reading init.xml
|                 | |       | | |    0.0360729s          reading info.xml
|                 | |       | | |    0.0225257s [  1.4%] pre-initialization
|                 | |       | | |     0.001174s [  0.1%] initialization
|                 | |       | | |   5.9702e-05s [  0.0%] steps
|                 | |       | | |     0.229737s [ 14.3%] solver (excl. callbacks)
|                 | |       | | |     0.326071s [ 20.3%] creating output-file
|                 | |       | | |     0.273781s [ 17.0%] event-handling
|                 | |       | | |    0.0138236s [  0.9%] overhead
|                 | |       | | |     0.738971s [ 46.0%] simulation
|                 | |       | | |      1.60614s [100.0%] total
|                 | |       | | events
|                 | |       | | |  1004 state events
|                 | |       | | |   100 time events
|                 | |       | | solver: dassl
|                 | |       | | | 85777 steps taken
|                 | |       | | | 124694 calls of functionODE
|                 | |       | | | 20993 evaluations of jacobian
|                 | |       | | |  5197 error test failures
|                 | |       | | |    29 convergence test failures
|                 | |       | | | 0.169706s time of jacobian evaluation
LOG_SUCCESS       | info    | The simulation finished successfully.
```

**Comment by casella** [comment]
Sounds reasonable, this is a non-trivial simulation that takes quite some steps. Before this fix, we had this result:
```
### STATISTICS ###
timer
    0.251586s          reading init.xml
     300.387s [ 81.6%] simulation
     368.113s [100.0%] total
   0.0390606s          reading info.xml
   0.0184163s [  0.0%] pre-initialization
   0.0041692s [  0.0%] initialization
   0.0001045s [  0.0%] steps
     33.3584s [  9.1%] solver (excl. callbacks)
     1.08479s [  0.3%] creating output-file
     33.2095s [  9.0%] event-handling
   0.0504988s [  0.0%] overhead
events
solver: dassl
16840868 steps taken
52138284 calls of functionODE
25396216 evaluations of jacobian
11799778 error test failures
   25 convergence test failures
216.1s time of jacobian evaluation
```
so we reduced the number of steps by a factor 200 and the number of Jacobian evaluations by a factor 1000. Not bad :)

**Comment by casella** [comment]
I hoped this could also help with the library testuite, unfortunately the [regression report](https://libraries.openmodelica.org/branches/history/master/2022-11-23%2000:59:38..2022-11-23%2015:42:13.html) where this commit was introduced only shows one improvement in Buildings_8.

Too bad, we'll have to look for something else.
