### ISSUE TITLE
elsewhen gives error when reinit variables are different

### ISSUE THREAD

**Issue by paultjevdh** [OpenModelica/OpenModelica#9738]
### Description
When a 'when' and 'elsewhen' section reinit different variables, omedit throws an error. 
### Steps to reproduce
Please try to simulate the following model:
```mo
model test_elsewhen
  Real a,b;
equation
  der(a)=1;
  der(b)=2;

  when a>1 then
    reinit(b,0);
  elsewhen b>1.5 then 
    reinit(a,0);
  end when;
end test_elsewhen;
```
Logically this would generate two sawtooth signals, with different phase (because they are reset at different times)
This model runs fine in dymola, as well as wolfram system modeler.
![image](https://user-images.githubusercontent.com/59084059/203513416-2d564136-148d-47cc-9ab5-5ac19bbf7367.png)

Instead, openmodelica gives the error:
```
[2] 10:31:43 Symbolic Error
[test_elsewhen: 7:1-11:9]: The same variables must be solved in elsewhen clause as in the when clause.
```
A workaround is to add something like reinit(a,a) in the 'when' and reinit(b,b) in the 'elsewhen.
```mo
model test_elsewhen
  Real a,b;
equation
  der(a)=1;
  der(b)=2;

  when a>1 then
    reinit(b,0);
    reinit(a,a);
  elsewhen b>1.5 then 
    reinit(a,0);
    reinit(b,b);
  end when;
end test_elsewhen;
```
This does not seem to be something we should want.

### Version and OS
 - OpenModelica Version 1.20 beta 2 (64 bit)
 - OS: Windows 11, 64 bit

Best regards,
Paul van der Hulst

**Comment by bilderbuchi** [comment]
This could be an overeager check for [Spec 8.3.5.3](https://specification.modelica.org/master/equations.html#equations-within-when-equations) "same set of component references on the left-hand side", which explicitly excludes `reinit` from that requirement?

**Comment by perost** [comment]
> This could be an overeager check for [Spec 8.3.5.3](https://specification.modelica.org/master/equations.html#equations-within-when-equations) "same set of component references on the left-hand side", which explicitly excludes `reinit` from that requirement?

Indeed, thanks for pointing that out!

**Comment by bilderbuchi** [comment]
Checking this, I also noticed https://github.com/modelica/ModelicaSpecification/issues/3291, but that should not have a bearing on this issue.
