### ISSUE TITLE
Focus view jumps back from Plotting to Modelling when a model is double clicked

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OpenModelica#9751]
### Description

When a simulation is started, the view jumps to Plotting. After it finished, i want to open a model in plotting view to check if the `DynamicSelect` is working, but the said model always shown in Modeling view instead of Plotting.
 
<details><summary> Test Package </summary>

```.mo
package TestPackage
  model constantCurrentLoad
    extends Modelica.Electrical.Analog.Interfaces.TwoPin;
    parameter Modelica.Units.SI.Voltage Voff = 3.0;
    parameter Modelica.Units.SI.Time t_init = 0.300;
  
    Modelica.Blocks.Interfaces.RealInput Isoll annotation(
      Placement(visible = true, transformation(origin = {-30, 60}, extent = {{-20, -20}, {20, 20}}, rotation = -90), iconTransformation(origin = {-30, 40}, extent = {{-20, -20}, {20, 20}}, rotation = -90)));
    Modelica.Blocks.Interfaces.BooleanInput Reset annotation(
      Placement(visible = true, transformation(origin = {30, 60}, extent = {{-20, -20}, {20, 20}}, rotation = -90), iconTransformation(origin = {30, 40}, extent = {{-20, -20}, {20, 20}}, rotation = -90)));
  protected
    Boolean UnderVoltage(start=false, fixed=true), foo;
    parameter Modelica.Units.SI.Current Imin = 1e-10;
  
  algorithm
  foo := p.v < Voff;
  when edge(foo) and time >= t_init and not UnderVoltage then
    UnderVoltage:= true;
  end when;
  
  when edge(Reset) then
    UnderVoltage := false;
  end when;
  
  equation
  
    0 = p.i + n.i;
    
    if not UnderVoltage then
      p.i = Isoll + Imin;
    else
      p.i = Imin;
    end if;
  annotation(
      Icon(graphics = {Rectangle(extent = {{-100, 40}, {100, -40}}), Text( extent = {{-74, 11}, {74, -11}}, textString = "Const Current Load")}));end constantCurrentLoad;

  model foo
  TestPackage.constantCurrentLoad constantCurrentLoad annotation(
      Placement(visible = true, transformation(origin = {50, 30}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Sources.ConstantVoltage constantVoltage(V = 12)  annotation(
      Placement(visible = true, transformation(origin = {-70, 30}, extent = {{-10, -10}, {10, 10}}, rotation = -90)));
  Modelica.Electrical.Analog.Basic.Ground ground annotation(
      Placement(visible = true, transformation(origin = {-70, -2}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Electrical.Analog.Ideal.IdealOpeningSwitch switch(Ron = 0)  annotation(
      Placement(visible = true, transformation(origin = {-10, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Noise.UniformNoise uniformNoise(enableNoise = true, samplePeriod = 0.01, useGlobalSeed = false, y_max = 1, y_min = 0)  annotation(
      Placement(visible = true, transformation(origin = {-70, -40}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  equation
    constantCurrentLoad.Isoll = 10;
    constantCurrentLoad.Reset = false;
    switch.control = uniformNoise.y >= 0.5;
    connect(ground.p, constantVoltage.n) annotation(
      Line(points = {{-70, 8}, {-70, 20}}, color = {0, 0, 255}));
    connect(ground.p, constantCurrentLoad.n) annotation(
      Line(points = {{-70, 8}, {50, 8}, {50, 20}}, color = {0, 0, 255}));
    connect(switch.p, constantVoltage.p) annotation(
      Line(points = {{-20, 50}, {-70, 50}, {-70, 40}}, color = {0, 0, 255}));
    connect(switch.n, constantCurrentLoad.p) annotation(
      Line(points = {{0, 50}, {50, 50}, {50, 40}}, color = {0, 0, 255}));
  annotation(
      Diagram(graphics = {Text(origin = {30, 58}, extent = {{-12, 4}, {12, -4}}, textString = DynamicSelect("text", String(constantCurrentLoad.p.i, significantDigits=3)))}));
end foo;
  annotation(
    uses(Modelica(version = "4.0.0")));
end TestPackage;
```
</details>

### Steps to Reproduce

1) Load MWE Above
2) Right click on `foo` and click simulate
3) Wait for simulation to finish and double click `foo` from plotting view
4) `foo` is shown in modelling view

### Expected Behavior

Model opened in plotting view stay in plotting view :D

### Version and OS

 - OpenModelica Version:v1.20.0-dev.beta2 (64-bit)
 - OS:  Windows 10, 64 bit

**Comment by bilderbuchi** [comment]
In step 3., have you tried the blue gears icon ("Diagram window") in the plotting perspective toolbar?

**Comment by adeas31** [comment]
That is the expected behavior. Click on the `Diagram Window` icon in the plotting perspective toolbar to open the diagram for DynamicSelect.

**Comment by Arinomo** [comment]
I see, I was using OMEV1.19 and i used to it always open it directly in plotting view. 

Thanks for the tips. One follow-up question, If no model was open, it give you a blank tab (obviously!) and if you double click `foo` from library browser, it still jumps to modelling view. If you have other model opened, for example `constantCurrentLoad`, then that model will be shown when the `Diagram Window` is clicked. Is that also the intended behavior?

**Comment by adeas31** [comment]
> I see, I was using OMEV1.19 and i used to it always open it directly in plotting view.

Yes, we changed it always open model in Modeling perspective since it was creating confusion.

> Thanks for the tips. One follow-up question, If no model was open, it give you a blank tab (obviously!) and if you double click foo from library browser, it still jumps to modelling view. If you have other model opened, for example constantCurrentLoad, then that model will be shown when the Diagram Window is clicked. Is that also the intended behavior?

The `Diagram Window` will always show whatever is the active model in Modeling perspective.

**Comment by casella** [comment]
I understand this is resolved, if not please reopen.
