### ISSUE TITLE
Unclear instructions on setting the MODELICAPATH in OMEdit

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OpenModelica#9759]
### Description

When a user wants to set several paths for `MODELICAPATH` in Options -> Libraries, the tooltip gives rather unclear instructions as to achieve this: 

"List of paths searched while loading a library. Paths are separated by **native path separator**."

Now the term "native path separator" could be interpreted either as "/" and "\\" or as ";" and ":". The former is especially for non-programmers the natural choice. And even for programmers languages like Python are not very consistent here: 

```python
>>> import os
>>> print(os.sep)
/
>>> print(os.path.sep)
/
>>> print(os.pathsep)
:
```

### Expected Behavior

I would suggest changing the message to:

 "List of paths searched while loading a library. Paths are separated by `;` on Windows and `:` on Linux and macOS."

**Comment by adeas31** [comment]
This one can definitely go in 1.20

**Comment by casella** [comment]
> This one can definitely go in 1.20

Agreed, mind porting it to maintenance/v1.20?

**Comment by adeas31** [comment]
Done. See #9781

**Comment by olivleno** [comment]
I'd like to see this important hint also in the scripting API documentation of [getModelicaPath](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#getModelicaPath)

**Comment by adeas31** [comment]
Looking at the [source code](https://github.com/OpenModelica/OpenModelica/blob/master/doc/UsersGuide/interface.mos#L12) shows that the information should be part of the scripting API documentation.

I am not sure why its not showing up. Maybe the `system` command is failing or `pandoc` is not missing on the server. Perhaps @sjoelund can check when he gets some time.

**Comment by casella** [comment]
Or @adrpo
