### ISSUE TITLE
Connection equations not generated by OMEdit

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9776]
### Description

I am using v1.21.0-dev-54-g353082d6a1. If I start building a new model, when I make connections with the GUI they are displayed, but do not show up in the source code. If I save, quit, and reopen, they are gone.

Not sure when this started. I cannot check with the betas because I don't have enough bandwidth right now, but I'll check with the latest OpenModelica-v1.20.0-dev-444-g13fe6b71d6-64bit I have on my PC to make sure this didn't creep into the release.

**Comment by casella** [comment]
13fe6b7 is OK from this point of view

**Comment by adrpo** [comment]
Diagram:
![image](https://user-images.githubusercontent.com/4192979/204159421-b3ebde6e-04e4-4461-adf4-1b678ab66235.png)

Text:
![image](https://user-images.githubusercontent.com/4192979/204159402-ed4d3dd9-0b18-4179-9ed0-5309673aaf15.png)

OMEdit log:
[omeditcommunication.zip](https://github.com/OpenModelica/OpenModelica/files/10099191/omeditcommunication.zip)

**Comment by adrpo** [comment]
The problem was that there were some changes in the handling of Line annotations which introduced a bug:
```
addConnection(inductor.n,resistor.p,NNNN,annotate=Line(points={{-56,52},{-24,52}},color={0,0,255},pattern=&1)) 21:57:34:694
Error occurred building AST
Syntax Error
[<interactive>:1:108-1:108:writable] Error: Lexer got '&1' but failed to recognize the rest: '))' 21:57:34:694
#s#; 0.000000; 10.423000; 'addConnection(inductor.n,resistor.p,NNNN,annotate=Line(points={{-56,52},{-24,52}},color={0,0,255},pattern=&1))'
```
After my fix it should work fine.

**Comment by adeas31** [comment]
Thanks @adrpo
