### ISSUE TITLE
FMU & inputs

### ISSUE THREAD

**Issue by ANaumann85** [OpenModelica/OpenModelica#9785]
### Discussed in https://github.com/OpenModelica/OpenModelica/discussions/9768

<div type='discussions-op-text'>

<sup>Originally posted by **ANaumann85** November 25, 2022</sup>
Are input variables in modelica assumed to be constant in time? See for example the following simple model:

```mo
model testModel "test model"
  extends Modelica.Icons.Example;

  Real T;
  input Real Tref1 "reference Temperature";
  parameter Real alpha1 = 10;
  parameter Real T0 = 0 "start value for T";
  output Real q "output variable";
initial equation
  T = T0;
equation
   der(T) = alpha1*Tref1; 
   q = alpha1*(Tref1-T);
end testModel;
```

where Tref1 is assumed to be a time dependent input. 

When I generate an FMU in cosimulation mode with that model, I get completely wrong solutions. The root cause is, that the generator differentiates the equation for q under the assumption, that Tref is constant in time.

</div>

I created several testing examples in this [repository](https://github.com/ANaumann85/openmodelica-fmu)

**Comment by ANaumann85** [comment]
The [table](https://github.com/ANaumann85/openmodelica-fmu/actions/runs/3568787019/attempts/1#summary-9755955840) runs the comparison with the analytical solution using different index reduction methods.

**Comment by ANaumann85** [comment]
Indeed, it is a straightforward state-space model. But at the same time it is a simple differential equation of index one, because we have to differentiate the algebraic equation at least once to get a differential equation for $q$. 
If one disables the index reduction, the open-modelica compiler detects this and complains `Structurally singular system detected, but no index reduction method has been selected.` (see for example the log of [run-test](https://github.com/ANaumann85/openmodelica-fmu/actions/runs/3573380658/jobs/6007376847)).

The generated code from the omc (for example using indexReductionMethod=dummyDerivatives) contains the derivative $\dot{q}=-\alpha_1 \dot{T}$, which lacks the derivative of $T_{ref1}$. That explains only, why $q$ gets wrong. 

To my surprise, the differential equation for $T$ was replaced by $T=T_{ref1}-q/\alpha_1$. So why does the compiler first differentiate an algebraic equation and later replace a differential equation by using that same algebraic equation? 

It should keep the original equations instead, right? Or at differentiate correctly.

**Comment by ANaumann85** [comment]
Please find the generated FMU using the flag `--indexReductionMethod=dummyDerivatives` with omc version `1.19.2`.
[testModel_cs.zip](https://github.com/OpenModelica/OpenModelica/files/10116913/testModel_cs.zip) (i renamed the suffix to zip to allow uploading)

The model (including the equations) are in the file `sources/testModel_cs.c` lines 92-150. The algebraic equation for $T$ (function `testModel_cs_eqFunction_11`) is used only when evaluating the DAE.  
The function `testModel_cs_eqFunction_8` implements the wrong ODE for $q$

**Comment by casella** [comment]
See my [comment in #9782](https://github.com/OpenModelica/OpenModelica/issues/9782#issuecomment-1332865257), could be relevant here also.

**Comment by ANaumann85** [comment]
Thank you for the pointer. This issue is a duplicate of [that](https://github.com/OpenModelica/OpenModelica/issues/9782#issuecomment-1332865257).

**Comment by casella** [comment]
Feel free to close this if you think #9782 is good enough. One less ticket to worry about 😅
