### ISSUE TITLE
Textbox in Package icon annotation is not shown in library tree

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#9833]
### Description

If a package has an icon with a textbox (single letter) this letter is not shown in the library tree.
However the standard package icon in Omedit with a single P is shown in the library tree.

### Steps to Reproduce
Create a new package with the following text in OMedit and look at the library tree. There is no package icon visible in the library tree.

`
package TestPackage
annotation (
    Icon(graphics={Text(
          extent={{0,100},{0,-100}},
          textColor={0,130,174},
          textString="H")}));
end TestPackage;
`

### Expected Behavior

The package icon in the library browser should include the letter "H" just like the letter "P" is shown when a package has no icon annotation in OMEdit.

### Version and OS

 - OpenModelica Version: OMEDit 1.19.2 and 1.21-dev nightly from 1.12.2022
 - OS: Windows 10, 64 bit

If this is a problem with our package icon annotations please let us know. In Dymola and SimulationX the library tree looks as expected though.

Thanks for looking into it
Aaron Buntrock- Bosch Rexroth

**Comment by adeas31** [comment]
For me this works as expected. There are 2 things that we can check,

1. What value do you have for `Tools->Options->General->Libraries Browser->Max. Library Icon Text Length to Show: *`? This value defines how many test characters will be shown in the Libraries Browser.
2. The text color is blue and is very hard to see this in the Libraries Browser since the highlight color is also blue.

**Comment by adeas31** [comment]
> However the standard package icon in Omedit with a single P is shown in the library tree.

The package icon is a hard coded image with letter P.

**Comment by abuntrock** [comment]
Thanks @adeas31. I forgot that I for whatever reason set this value to zero some time ago.
My apologies for opening this issue.
