### ISSUE TITLE
NF/NB - Unnecessary and incorrect Array unrolling

### ISSUE THREAD

**Issue by kabdelhak** [OpenModelica/OpenModelica#9839]
### Original Model
`ScalableTestSuite.Thermal.DistrictHeating.ScaledExperiments.HeatingSystem_N_5`

### Minimal Model
Please consider the following model:
```
model binding_array
  parameter Integer N = 5;
  parameter Real Cu[N] = (ones(N)+ linspace(0,1.348,N))*1e7;
end binding_array;
```

### Issue
1. When running with `--newBackend` the new frontend creates an unrolling of `ones(N)` that is not wanted for the new backend:
```
class binding_array
  final parameter Integer N = 5;
  parameter Real[5] Cu = ({1.0, 1.0, 1.0, 1.0, 1.0} + array(1.348 * /*Real*/(i - 1) / 4.0 for i in 1:5)) * 10000000.0;
end binding_array;
```

2. Also later on during the processing in the new backend when calling the frontend module `SimplifyExp` (in NBEquation.generateBindingEquation) the iterator array constructor gets unrolled and causes the following error:
```
Error: Internal error NBSolve.solveMultiStrongComponent failed for equation:
[ARRY] (5) Cu = 10000000.0 .* ({1.0, 1.0, 1.0, 1.0, 1.0} + {1.348 * CAST(Real, i - 1) / 4.0, 1.348 * CAST(Real, i - 1) / 4.0, 1.348 * CAST(Real, i - 1) / 4.0, 1.348 * CAST(Real, i - 1) / 4.0, 1.348 * CAST(Real, i - 1) / 4.0}) ($RES_BND_0)
```
Which is not only unwanted in the new backend but seems to be generally wrong since the iterator is removed but the iterator component reference in the expression stayed. 

### Expected Behaviour
1. `ones(N)` and similar array constructors should always result in iterator array constructors like `array(1.0 for i in 1:5)`, if they are not part of a reduction like `sum()`.

2. The frontend simplification module should not try to simplify iterator array constructors and keep them as they are.

### Desired New Backend Result
A binding equation as such:
```
for i in 1:5 loop
   Cu[i] = (1.0 + 1.348*(i - 1)/4.0)* 10000000.0;
end for;
```

**Comment by perost** [comment]
#9840 should improve it. The simplification was a bit inconsistent before when scalarization was turned off, it would constant evaluate calls to builtin functions if the arguments were literals but otherwise it would skip simplification. Now I've changed it so we neither constant evaluate nor simplify it when scalarization is turned off.

The flat model now ends up as:
```Modelica
parameter Real[5] Cu = (fill(1.0, 5) + array(1.348 * /*Real*/(i - 1) / 4.0 for i in 1:5)) * 10000000.0;
```
Not the prettiest expression perhaps, but SimplifyExp doesn't really do more advanced simplifications.

**Comment by kabdelhak** [comment]
> #9840 should improve it.
Thanks for the quick fix! 
> The flat model now ends up as:
> 
> ```modelica
> parameter Real[5] Cu = (fill(1.0, 5) + array(1.348 * /*Real*/(i - 1) / 4.0 for i in 1:5)) * 10000000.0;
> ```
is it possible to have the proposed `array(1.0 for i in 1:5)` instead of `fill(1.0, 5)`? I would need to do that replacement in the backend anyway.

**Comment by kabdelhak** [comment]
Yes probably. Also the second model failing seems to be for the same reason... i guess it does not evaluate `integer()` and/or `CAST()` but i need to do that to reduce the index to a single integer value after replacing the iterator `i` with a value.

**Comment by perost** [comment]
@kabdelhak: Should we close this?
