### ISSUE TITLE
Invisible RealOutput is visible

### ISSUE THREAD

**Issue by christiankral** [OpenModelica/OpenModelica#9847]
### Description

The RealOutput used with the `annotation (Placement(visible=false))` is yet shown.

### Steps to Reproduce

Navigate to the following example:

![image](https://user-images.githubusercontent.com/4184218/205504378-223abe96-f6b9-428f-b778-d8089d395a38.png)

Once double clicking on `SMEE_DOL` the full size triangle appears which is apparently related with the following code:

```modelica
Modelica.Blocks.Interfaces.RealOutput irRMS(
    final quantity="ElectricCurrent",
    final unit="A") if smee.useDamperCage "Damper cage RMS current"
    annotation (Placement(visible=false));
```

The Diagrams View of the model `SMEE_DOL` shows:

![image](https://user-images.githubusercontent.com/4184218/205504454-8964e12d-a36b-4895-a53a-6ba05752c016.png)

**Note:** The Font (under Linux) apparently changed to Times (or something similar), which causes reduced readability.

### Expected Behavior

The connector `RealOutput irRMS` shall not be displayed as the annotation states `Placement(visible=false)`

### Version and OS

```
Connected to OpenModelica 1.21.0~dev-103-g26cb005
Connected to OMSimulator Linux Mint 20.3
```

### Additional Context

Could this be related with #7388?

**Comment by adeas31** [comment]
This was a regression in 37ce4b460503c94beb9dc6694fdefab2b07a1ee4 but is already fixed with 0146756a84c94404ebc280c4995149b2ff1d98e2

**Comment by christiankral** [comment]
OK, it now works in OpenModelica 1.21.0~dev-119-g7dc99cd.

**Comment by christiankral** [comment]
> **Note:** The Font (under Linux) apparently changed to Times (or something similar), which causes reduced readability.

@casella @adeas31 Do you a comment on this (side) issue. Does it require a separate ticket? Or is it intention?

**Comment by adeas31** [comment]
I will take a look at it.

**Comment by casella** [comment]
> @casella @adeas31 Do you a comment on this (side) issue. Does it require a separate ticket? Or is it intention?

In general it's best to have one ticket for each issue, but this one was apparently easy :)
