### ISSUE TITLE
OMEdit warning color for simulation warnings

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9855]
### Description

Warning messages inside the `Messages Browser` simulation `Output` tab in OMEdit are displayed in error color instead of the warning color.

### Steps to Reproduce

Simulate a model that produces warnings:
E.g simulate `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` in OMEdit.

### Expected Behavior

The warning messages displayed by `warningStreamPrint` should be displayed in orange.

### Screenshots

![grafik](https://user-images.githubusercontent.com/38031952/205674959-fb507a2e-7e71-4aaa-bdd4-77a26c1af10c.png)
All red messages are warnings and should be displayed in orange.

### Version and OS

 - OpenModelica Version: v1.21.0-dev-109-g4a67a9fef2-cmake
 - OS: Windows 11, 64bit
 - Versions of used Modelica libraries: Modelica 4.0.0

### Related issues

Coming from https://github.com/OpenModelica/OpenModelica/issues/9811.
With the warning color the user probably wouldn't worry about the displayed warnings in the first place.

**Comment by ceraolo** [comment]
Thank you. This is somethig that changes the student's experience significantly.
My students needed to learn that red messages were not so severe, that created a bad feelig towards the program.
Thanks again!
