### ISSUE TITLE
The Vissible attribute in a component base class is not used with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9857]
### Description

The visible attribute in a  base class  of component is not used with the BRSL library. For components where the visible attribute is used directly in the component class it will work. 

### Steps to Reproduce
Load the BRSL package: ```Rexroth_Generic/package.mo```.
Drag and drop the ```SingleRodCylinder``` on a new sheet.
Disable the ```shownName``` parameter of the singleRodCylinder component  (s.h. picture 1)
The component name is still shown in the components icon

### Screenshots
<img width="638" alt="OM_ticket-showname" src="https://user-images.githubusercontent.com/12269776/205685899-587754c0-7320-4c53-9475-90aca6f04c2e.png">

### Version and OS

 - OpenModelica Version: v1.21.0-dev-106-g14b2673de1
 - OS:  Windows 10, 64 bit
 - Versions of used Modelica libraries if applicable
 - MSL 4.0.0
 - BRSL 2.2 RC

**Comment by casella** [comment]
@niklwors what if you save, unload, and reload the library? It may be just a matter of cached values not being recomputed when needed.

**Comment by adeas31** [comment]
Fixed in ec1861391345187b17351a1c37312328e9e6e013.
