### ISSUE TITLE
The Vissble attribute cannot be set with parameters of an outer instance with new instantiation-based OMEdit GUI

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9858]
### Description

In the BRSL library components have parameters that can also be set via a global instance that are used to set visible attributes,  e.g. to switch the name of a component in the icon on and off. This does not yet work with the new new instantiation-based OMEdit GUI.

### Steps to Reproduce
Load the BRSL package: ```Rexroth_Generic/package.mo```.
Drag and drop the ```SingleRodCylinder``` on a new sheet.
Drag and drop the ```Rexroth_Generic.BRSL_World``` on the sheet
Disable the ```ShowComponentParamters```  in the ```BRSL_World``` see picture 1.
The parameter are still visible in the component icon

### Screenshots
<img width="433" alt="OM-ticket3" src="https://user-images.githubusercontent.com/12269776/205691253-c97312b2-7451-4256-8c5b-d5c436eb808d.png">

### Version and OS

 - OpenModelica Version: v1.21.0-dev-106-g14b2673de1
 - OS: e.g. Windows 10, 64 bit
 - MSL 4.0.0
 - BRSL 2.2 RC

**Comment by niklwors** [comment]
@sbaetzing @abuntrock FYI

**Comment by casella** [comment]
Same comment as in #9857, does it work if you save, unload, and reload the package?

**Comment by niklwors** [comment]
Unfortunately this did not help.

**Comment by niklwors** [comment]
For some reason it suddenly works. Unfortunately, I do not know what the problem was, maybe I did not start OMedit correctly.
