### ISSUE TITLE
Recommended constraining-clause description location not supported by OMEdit

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#9863]
### Description

In the Modelica specification section 7.3.2.1 it is specified that the description of a replaceable declaration is recommended to be behind the constrainedby keyword. The omc and thus OMedit, however, seem to only support it, when the description is before the constrainedby keyword (which is identical according to the specification).

### Steps to Reproduce
Consider the following test package below. In in the model _propertySettings_ has one replaceable declaration (_constrainedBaseProperty2_) where the description is at the recommend position according to the specification and another replaceable declaration (_constrainedBaseProperty_) where the description is before the constrainedby keyword.

```modelica
package ReplaceableComment
  partial model baseProperty
    parameter Real density;
  end baseProperty;
  model propertySettings
    replaceable baseProperty constrainedBaseProperty "Comment at defintion" constrainedby baseProperty
      annotation(choicesAllMatching=true);
    replaceable baseProperty constrainedBaseProperty2 constrainedby baseProperty "Comment at constraining clause"
      annotation(choicesAllMatching=true);
  end propertySettings;
end ReplaceableComment;
```

If you call the omc method `getComponents(ReplaceableComment.propertySettings)` it results in the following output. The description is only listed in the output of getComponents if it is placed before the constrainedby keyword (_constrainedBaseProperty_):

```modelica
{{ReplaceableComment.baseProperty, constrainedBaseProperty, "Comment at defintion", "public", false, false, false, true, "unspecified", "none", "unspecified", {}},
{ReplaceableComment.baseProperty, constrainedBaseProperty2, "", "public", false, false, false, true, "unspecified", "none", "unspecified", {}}}
```

As a result, if you instantiate the model _propertySettings_ and look at its parameter dialog no description/comment is shown for _constrainedBaseProperty2_.

### Expected Behavior

A description behind the constrainedby keyword is found with `getComponents()` and consequently shown in the OMEdit parameter dialog.

### Version and OS

 - OpenModelica Version: 1.19.2 and 1.21-dev
 - OS: Windows 10, 64 bit

Thanks for looking into this
Aaron Buntrock - Bosch rexroth

@niklwors

**Comment by perost** [comment]
With #9864 we now check for a comment on the constraining clause too. In case there are comments in both places we use the one on the constraining clause, since as you pointed out that's where the specification recommends placing it.

**Comment by perost** [comment]
Note to self: make sure to include the comment when fixing #9559.

**Comment by abuntrock** [comment]
@perost thanks. That was fast

**Comment by perost** [comment]
> @perost thanks. That was fast :)
> 
> I assume I will be able to check it with one of the upcoming nightly builds?

Yes, it should be in tomorrow's nightly build if everything goes right.

**Comment by abuntrock** [comment]
@perost I checked todays nightly and I now get the comment as expected when using `getComponents(ReplaceableComment.propertySettings)`. However the comment still does not appear in the parameter dialog when I instantiate the _propertySettings_ model. Was this supposed to be fixed as well?

**Comment by perost** [comment]
> @perost I checked todays nightly and I now get the comment as expected when using `getComponents(ReplaceableComment.propertySettings)`. However the comment still does not appear in the parameter dialog when I instantiate the _propertySettings_ model. Was this supposed to be fixed as well?

I'm not entirely sure how that works, but I did check that the comments showed up if I added `propertSettings` to a diagram and checked the properties. But maybe you mean something else? Maybe @adeas31 has a better idea of what's needed.

**Comment by adeas31** [comment]
@abuntrock this works fine for me.

![image](https://user-images.githubusercontent.com/4007231/206168208-b0aef371-9678-425b-9672-9aeea498f285.png)

Note that this is fixed for the old api. If you are using instance api with `--NAPI=true` then see https://github.com/OpenModelica/OpenModelica/issues/9863#issuecomment-1339444191.

**Comment by abuntrock** [comment]
@adeas31 Thanks for clarifying. I indeed checked it with the new API.
