### ISSUE TITLE
Running District Energy System (Buildings Library) with OpenModelica

### ISSUE THREAD

**Issue by glinn07** [OpenModelica/OpenModelica#9885]
### Description
Issue when attempting to simulate District Energy System (Buildings Library) as generated by gesjson-modelica-translator

### Steps to reproduce

I have built a fairly simple example district energy system model using the geojson modelica translator as provided by NREL (I am using GMT version 0.3.0). I attached my model to this post, its pretty simple so I am including the whole thing.

I can successfully load the project in OpenModelica (v19) and see all the different elements of the model. When I attempt to simulate the District Energy System, I receive the following error:

	"Dimension 1 of ‘V_flow‘ could not be deduced from the component's binding equation ‘perCHWPum_cooPla_f20eb611.pressure.V_flow‘."
	
However when I load the project in Dymola (v2023) I can run the simulation without any issue.

### Expected behavior
Simulation to run and provide results

### Version and OS
 - OpenModelica Version 1.19.3
 - Modelica Buildings Library v9, Modelica Standard Library v4
 - OS: Ubuntu on Wimdows Subsystem for Linux (Ubuntu 20.04.5 LTS (GNU/Linux 5.15.74.2-microsoft-standard-WSL2 x86_64)

### Attachments
[m1 original from GMT.zip](https://github.com/OpenModelica/OpenModelica/files/10180131/m1.original.from.GMT.zip)

### Additional context

Michael Wetter suggested the following change to get it working:

	--- a/Districts/DistrictEnergySystem.mo
	+++ b/Districts/DistrictEnergySystem.mo
	@@ -84,7 +84,7 @@ parameter Integer nBui_disNet_cc85640d=2;
	   // pumps
	   parameter Buildings.Fluid.Movers.Data.Generic perCHWPum_cooPla_f20eb611(
		 pressure=Buildings.Fluid.Movers.BaseClasses.Characteristics.flowParameters(
	-      V_flow=((mCHW_flow_nominal_cooPla_f20eb611/cooPla_f20eb611.numChi)/1000)*{0.1,1,1.2},
	+      V_flow=((mCHW_flow_nominal_cooPla_f20eb611/2)/1000)*{0.1,1,1.2},
	
This allows simulation to start but then I receive some linear system solver errors

**Comment by perost** [comment]
Possibly fixed in #9890. It does fix the issue, but I'm not 100% confident that it won't break anything. It passes the testsuite, but we'll see what the library coverage testing says later.

**Comment by glinn07** [comment]
If I install the next nightly build will your new commit be included? I am new to the project and still learning about the process!

**Comment by perost** [comment]
The results from the library coverage testing are in and says everything is fine, so I'll close this issue since the model at least simulates now. I'm not sure if the simulation is correct, but feel free to open a new issue if you find there are still some problems with the simulation.

**Comment by glinn07** [comment]
Thank you, I will test it out!
