### ISSUE TITLE
Compiler error for models that use ExternalC function with a record parameter.

### ISSUE THREAD

**Issue by niklwors** [OpenModelica/OpenModelica#9887]
### Description
Models that including an externalC function with record parameter generating a compiler error e.g. for the model 

updated: 
The model can now be compiled without errors. The subsequent error is that the string passed to the C function is not passed correctly. In the log file the printed output string is empty. Please check the modified example:

```CallExternalCFunctionExample```
```modelica
package CallExternalCFunctionError
  partial block Base
  parameter CallExternalCFunctionError.Data data;
  initial equation 
    CallExternalCFunctionError.WriteData(data=data);
  end Base;

  class Component
    extends CallExternalCFunctionError.Base(
       data(value=true,name= "Component"));
   end Component;

  record Data
   //usage statistics parameter
    constant Boolean value = false;
    parameter String name = "unknown";
  end Data;

 function WriteData
  input CallExternalCFunctionError.Data data;
 external"C" WriteDataC(data)
    annotation(IncludeDirectory="modelica://CallExternalCFunctionError/Resources/Include",Include="#include \"WriteData.c\"");
end WriteData;

  model CallExternalCFunctionExample
    Component component;
  end CallExternalCFunctionExample;
end CallExternalCFunctionError;
```

C Code placed in package folder: ```Resources/Include/WriteData.c```

```C

struct DataC
{

    int value;
    const char* name;

};
typedef struct DataC Data;

void  WriteDataC(void* data)
{
    Data* wrtieData = (Data*)data;
    if (wrtieData->value)
    {
      printf("received name: %s ",wrtieData->name);
    }
}
```

### Steps to Reproduce

simulate the above model ```CallExternalCFunctionExample```
In the log file the passed string is not printed:
```
received name:  

```

### Expected Behavior

```
received name:   component

```

### Version and OS

 - OpenModelica Version: v1.21.0-dev-106-g14b2673de1
 - OS: Windows 10, 64 bit

**Comment by mahge** [comment]
This should be fixed with #9971. 

The issue was that the NF was not marking the record as one that is used externally. We want to know which records are used externally in order to map their layout properly (due to size differences between `int` and `long` on some systems). In this specific case the NF was missing the marking. I have added a preliminary fix for it. Once @perost is back he can take a second look and adjust it as needed.

I will leave the ticket open until then.

**Comment by niklwors** [comment]
@mahge Thanks for the fix, the model now translates without error. There is a subsequent error that the string passed to the C function is not passed correctly.

**Comment by niklwors** [comment]
There is no warning,  just  the passed string is empty

**Comment by niklwors** [comment]
I have generated a new ticket for it: https://github.com/OpenModelica/OpenModelica/issues/9980
