### ISSUE TITLE
Scripting error in OM 1.20.0

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9891]
### Description
I've just installed OM 1.20.0 in the following folder:
C:\OM\OpenModelica1.20.0-64bit

When I launch OMEdit I receive a Scripiting error message (in red in the attached screenshot), which seems to have no effect on activities.

### Expected Behavior
This error should not occur, or (incase of false message) this message should not be displayed

### Screenshots
![image](https://user-images.githubusercontent.com/7373030/206441472-81c4b00d-3fbc-404a-93a6-768c6644d62d.png)

### Version and OS
OM 1.20.0 Win11 64 bit

**Comment by adeas31** [comment]
Seems like you have `ModelicaReference` defined in `Tools->Options->Libraries->System libraries loaded automatically on startup *`. We don't ship `ModelicaReference` now as default so you can either install it via `File->Manage Libraries->Install Library` or can delete the entry from `Tools->Options->Libraries->System libraries loaded automatically on startup *`.

**Comment by ceraolo** [comment]
> 

AHA, yes, you are right!
I think I never made this definition manually: it is probably  residue of previous installations which added ModelicaReference to the library list.

Sorry of not having thought better before posting.

For me this ticket can be closed.

**Comment by casella** [comment]
When in doubt you can always reset to factory setting with Tools | Options | Rest, and then re-apply the settings you need, one by one.
