### ISSUE TITLE
getInstantiatedParametersAndValues() fails when input class includes class instance

### ISSUE THREAD

**Issue by abuntrock** [OpenModelica/OpenModelica#9894]
### Description
getInstantiatedParametersAndValues() fails if its input class instantiates at least one other class.
The problem seems more severe if the input class includes a inner class.

### Steps to Reproduce
Load the MSL4.0.0. Execute the following API calls:
`getInstantiatedParametersAndValues(Modelica.Blocks.Sources.Constant)`, 
`getInstantiatedParametersAndValues(Modelica.Mechanics.Translational.Components.Vehicle)` and `getInstantiatedParametersAndValues(Modelica.Mechanics.MultiBody.Forces.WorldForce)` .
Only the first API call returns a value (_{"k"}_). 
It looks as if the API call fails if the input class instantiates at least one other class like in the second API call. 
The third API call fails because the class WorldForce includes a inner world (error message : _The model can't be instantiated due to top-level outer element ‘world‘, it may only be used as part of a simulation model_).  In this case a good approach from our point of view would be to use the corresponding outer element with its default parametrization.

### Expected Behavior

`getInstantiatedParametersAndValues(Modelica.Mechanics.Translational.Components.Vehicle)` and `getInstantiatedParametersAndValues(Modelica.Mechanics.MultiBody.Forces.WorldForce)` should also return a valid output.

### Version and OS

 - OpenModelica Version: [e.g. `omc --version` or `Help->About OMEdit` from OMEdit]
 - OS: Windows 10, 64 bit
 - MSL 4.0.0

Thanks for looking into this
Aaron Buntrock - Bosch Rexroth
@niklwors fyi

**Comment by abuntrock** [comment]
In our usecase we do not need 'getInstantiatedParametersAndValues' to print qualified names like `a.b` because we can collect them via 'getComponentModifierNames(className,a)'.

For us this function call is important because it takes into account modifications of parameters in extend statements. Thus, the function call should still output parameters which are defined in an extended class. This is the current behavior and I've seen it tested in one of the unit tests (https://github.com/OpenModelica/OpenModelica-testsuite/tree/master/openmodelica/interactive-API) but cannot find the correct one right now.

**Comment by perost** [comment]
Ok, #9896 fixes the issue by filtering out any parameters with qualified names so you only get the top-level ones (including inherited parameters). So same behaviour as before, just without failing on qualified names.

**Comment by abuntrock** [comment]
@perost Thanks for the fast fix.

**Comment by casella** [comment]
@abuntrock please reopen if not solved with the next nightly build.
