### ISSUE TITLE
Windows: Profiling equation time not always working

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OpenModelica#9898]
### Description

When using OMEdit with profiling I can see the `number of executions`, `max time` and `time` only for some models on Windows.
On Linux I can see them for all models (that I checked).

E.g. for `Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.FullRobot` it's working fine on both Windows and Linux, and for `OpenIPSL.Examples.IEEE14` I can't view the times on Windows but can on Linux.

I'm not so sure if this is an OMEdit issue while displaying the `*_prof.json` or if the json file itself is broken.
The [IEEE_14_Buses_prof.json.txt](https://github.com/OpenModelica/OpenModelica/files/10187035/IEEE_14_Buses_prof.json.txt) has some non-zero values and value for `ncall` and looks more or less identical to the Linux version of it.

### Steps to Reproduce

Open `OpenIPSL.Examples.IEEE14` in OMEdit. Under `Simulation Setup`->`Translation Flags` set `Profiling all` and simulate.
After the simulation finished open the declarative debugger and have a look at the equations browser.

### Expected Behavior

Display the `number of executions`, `max time` and `time` from the `*_prof.json`.

### Screenshots

Linux:
![grafik](https://user-images.githubusercontent.com/38031952/206486976-6504e86a-4d9e-46a8-881c-8ca253e52c7d.png)

Windows:
![grafik](https://user-images.githubusercontent.com/38031952/206487066-2d9895bc-eedc-4407-b6ba-079192f5308c.png)

### Version and OS

 - OpenModelica Version: v1.21.0-dev-119-g7dc99cda91
 - OS: Windows 11
 - Versions of used Modelica libraries: OpenIPSL 3.0.1

**Comment by adeas31** [comment]
Can you please compare the JSON files from Windows and Linux and see if they different?

**Comment by AnHeuermann** [comment]
Uhmmm.... now it's working. Did I used it wrong previously? Magic reboot on Windows or some other issue?
This could be difficult to find.

Maybe the root cause is: https://github.com/OpenModelica/OpenModelica/issues/9423 I'm getting some of the warnings when generating the _prof.json
```
modelInfoGetEquation failed to get info for equation 2571, out of range. 
```

**Comment by adeas31** [comment]
Yeah perhaps the file is not fully written because of the seg fault.
