### ISSUE TITLE
Project looks for sundials' static libraries when they aren't installed

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#9901]
OMCompiler/3rdParty/CMakeLists.txt looks for these:
```
## that does not seem to work. This should be fine anyway.
target_link_libraries(sundials_cvode_static PUBLIC sundials_interface_static)
target_link_libraries(sundials_idas_static PUBLIC sundials_interface_static)
target_link_libraries(sundials_kinsol_static PUBLIC sundials_interface_static)
target_link_libraries(sundials_sunlinsolklu_static PUBLIC sundials_interface_static)
target_link_libraries(sundials_sunlinsollapackdense_static PUBLIC sundials_interface_static)
```
We only have shared libraries, generally.

FreeBSD 13.1

**Comment by mahge** [comment]
> static libraries when they aren't installed 

These are not looking for installed libraries. Sundials is part of the project itself and is built from source. Can you give us more information about the issue?

**Comment by yurivict** [comment]
There were some errors with these libraries but I can't reproduce them now.
Sorry for the noise.
