### ISSUE TITLE
Build fails: fatal error: 'expat.h' file not found #include <expat.h>

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#9913]
[openmodelica-1.20.0-expat-failure.txt](https://github.com/OpenModelica/OpenModelica/files/10198650/openmodelica-1.20.0-expat-failure.txt)

FreeBSD 13.1

**Comment by mahge** [comment]
You can try adding
```diff
add_library(expat ${_SHARED} ${expat_SRCS})
+target_include_directories(expat PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/lib) 
```

to the file `OpenModelica/OMCompiler/3rdParty/FMIL/ThirdParty/Expat/expat-2.1.0/CMakeLists.txt` at line 64.

This should have been there. All this time we were probably picking up expat.h from somewhere else on the system.
