### ISSUE TITLE
ExternalMedia installation missing packaged binaries

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OpenModelica#9938]
When installing ExternalMedia v3.3.1 (experimental support) using the Package manager in OM 1.20, the installed package is lacking the necessary compiled binaries that are provided with the [release](https://github.com/modelica-3rdparty/ExternalMedia/releases/tag/v3.3.1), in a zip file.
I presume this is because the repo source is cloned/used.

I could not find documentation on the repos.json format, but I suspect the [entry for ExternalMedia](https://github.com/OpenModelica/OMPackageManager/blob/0b3ce1e9fa06758a1e3780f1573edd8f8c999ae3/repos.json#L379-L389) needs an additional entry like

```
"zipfile": "https://github.com/modelica-3rdparty/ExternalMedia/releases/download/{0}/ExternalMedia_{0}.zip",
```

Note that the structure of the zip file is different from the structure of the git repository, so probably the `search-extra-paths` entry will need some attention, too. The zip file contains a folder ExternalMedia 3.3.1 (with version tag!) with what resides in the git repo at Modelica/ExternalMedia (and additionally the compiled binaries therein).

cc @casella

_(Previously erroneously reported at https://github.com/OpenModelica/OMPackageManager/issues/10, before I realised you want the issues tracked here)_

**Comment by casella** [comment]
@bilderbuchi as soon as we have a properly working release, we just need to change the configuration script so that it download the .zip file of the release. Shouldn't be a big deal.

Thanks for reporting!

**Comment by bilderbuchi** [comment]
Sure! I just tried to do some of that leg-work already -- afaict, getting ExternalMedia to install correctly with the package manager is a necessary precondition for getting it tested in the OM library tests.

**Comment by bilderbuchi** [comment]
See https://github.com/modelica-3rdparty/ExternalMedia/issues/62#issuecomment-1348432819 for a probably working approach for how to fetch the zip file of the latest ExternalMedia commit for CI library testing.

**Comment by casella** [comment]
> Sure! I tried to do some of that leg-work (collecting probable config changes) already -- afaict, getting ExternalMedia to install correctly with the package manager is a necessary precondition for getting it tested in the OM library tests, which will then be illuminating as to how well it is "properly working".

Absolutely. I was still getting failures on some tests on my PC, so I wanted to fix them before making the release and having that handled by the package manager.

**Comment by bilderbuchi** [comment]
I think with the recent ExternalMedia release, this can now be closed. 
Awesome that the test suite already picked it up, too: https://libraries.openmodelica.org/branches/master/ExternalMedia/ExternalMedia.html (the FluidProp tests that fail due to that library not being installed kinda distort the statistics :D)

**Comment by casella** [comment]
Thanks @bilderbuchi!
