### ISSUE TITLE
CMake compiled version could not find Modelica Standard Library

### ISSUE THREAD

**Issue by Zbm1996** [OpenModelica/OpenModelica#9943]
I compiled OpenModelica on Windows 10 through MSYS with CMake files, but I could not find Modelica Standard Library under build_cmake folder. 
While compiling OpenModelica with makefiles, I could find Modelica Standard Library under folder OpenModelica\build\lib\omlibrary.
I'm not sure if I missed some configuration steps within the compiling process, but I could run omc.exe, OMEdit and other executable files successfully.

**Comment by mahge** [comment]
OpenModelica has a package manager now. Users can install and uninstall libraries using the package manager. So we no longer manage libraries with the build system.

You can find instructions for installing libraries with OMEdit [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html#omedit-install-library-label).

If you are not using OMEdit, then you can also install packages using Modelica scripts. You can find more information about that and the package manager in general [here](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/packagemanager.html#using-the-package-manager-from-the-interactive-environment)
