### ISSUE TITLE
Low-level issue with mingw-32 on Windows 11

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9948]
A student of mine using Windows 11 reports this issue, which started popping up at some point, was apparently resolved by deleting all the working directory files, but now remains even in that case:
![immagine](https://user-images.githubusercontent.com/4233148/207849741-1d0db935-b2f1-4fb5-9bf7-bf120adc3f61.png)
The error code when turned to unsigned int apparently corresponds to 0x40000142. I couldn't find that error code on the internet, while there are many references to 0xC0000142.

I wonder, maybe mingw-32 is not happy running in Windows 11, and we should eventually switch to mingw-64? Or, update mingw to a more recent version?

**Comment by AnHeuermann** [comment]
Don't get confused by the name. `mingw32-make` is the make shipped with MinGW-w64, so it is the correct one for a 64 bit Windows OS.

**Comment by casella** [comment]
OK. Something like having a new frontend, and then a new new frontend :)
