### ISSUE TITLE
Moving an object crashes OMEdit

### ISSUE THREAD

**Issue by ceraolo** [OpenModelica/OpenModelica#9965]
### Description
I have an example in which just moving an object in diagram view causes OMEdit to crash.

### Steps to Reproduce
My example is written for MSL 3.2.3 and to run requires Powergrids 1.0.2, but this does not matter for the bug, since the following simple procedure causes the crash:

1. load [Test1_puFMU.mo.txt](https://github.com/OpenModelica/OpenModelica/files/10253878/Test1_puFMU.mo.txt)
2. Go in diagram mode and try to move the leftmost read box up or down with keyboard or mouse: this causes OMEdit to crash (and send a crash report).

### Version and OS
OM 1.21.0-dev-164,   Win 11 64 bit

**Comment by ceraolo** [comment]
I hope someone will have time to have a look at this.
Occasionally I have OMEdit crashes, but it is usually very difficult to find repeatitive combinations causing systematic crashes.

This is one of these miracle cases in which we can replicate the bad behaviour, and therefore  an opportunity to fix a program weakeness, which could manifest itself in other less-repeatitive cases.

**Comment by casella** [comment]
@adeas31 will look into it when he's back from the holidays. Maybe this will be superseded when we make the new API default beginning of 2023, see #8425.

**Comment by ceraolo** [comment]
> @adeas31 will look into it when he's back from the holidays. 
Thanks!
>Maybe this will be superseded when we make the new API default beginning of 2023, see #8425.
Even better! I cannot try it by now since with --NAPI=true we don't see diagrams with red boxes, but I'll try to find a simpler system showing this bad behaviour and then test it with NAPI.

**Comment by casella** [comment]
>  I cannot try it by now since with --NAPI=true we don't see diagrams with red boxes, 

This shouldn't happen normally, i.e., you should have all libraries loaded correctly when editing diagrams.

**Comment by ceraolo** [comment]
> > I cannot try it by now since with --NAPI=true we don't see diagrams with red boxes,
> 
> This shouldn't happen normally, i.e., you should have all libraries loaded correctly when editing diagrams.

Sure. The example for this ticket was originally much more complicated, involving  importing an fmu and powergrids. And the crash still occurred.

What I actually posted was simplified in order to ease the search of the issue (and I mentioned this in the description). This, however, is not adeguate for the current stage of development of NAPI.

**Comment by ceraolo** [comment]
Important updates.

1) the issue is not present witn OM 1.20.0

2) The procedure to reproduce it with without red boxes is as follows:
a. load OM with Modelica 3.2.3
b. load PowerGrids 1.0.2
c. load Test1_puFMU (provided with this ticket's description)
d. import the following fmu: [Avr4s_pu.fmu.txt](https://github.com/OpenModelica/OpenModelica/files/10284241/Avr4s_pu.fmu.txt)
e. rename the imported fmiu (i.e. its wrapper) into Avr4s_ou_fmu (this is rather nannoying because you have to do it manually on the model text and because of #9966)
f. Try to move the fmu icon either by keyboard or mouse => CRASH

**Comment by casella** [comment]
> Important updates.
> 
>     1. the issue is not present witn OM 1.20.0

This is important information, so it's a regression between the 1.20.0 branch-off and OM 1.21.0-dev-164. We should probably do some bisection testing.

**Comment by casella** [comment]
@adeas31 please check this at your earliest convenience, we should fix this regression before releasing 1.21.0

**Comment by adeas31** [comment]
> Important updates.
> 
> 1. the issue is not present witn OM 1.20.0
> 2. The procedure to reproduce it with without red boxes is as follows:
>    a. load OM with Modelica 3.2.3
>    b. load PowerGrids 1.0.2
>    c. load Test1_puFMU (provided with this ticket's description)
>    d. import the following fmu: [Avr4s_pu.fmu.txt](https://github.com/OpenModelica/OpenModelica/files/10284241/Avr4s_pu.fmu.txt)
>    e. rename the imported fmiu (i.e. its wrapper) into Avr4s_ou_fmu (this is rather nannoying because you have to do it manually on the model text and because of [Allow choosing the name of imported FMU #9966](https://github.com/OpenModelica/OpenModelica/issues/9966))
>    f. Try to move the fmu icon either by keyboard or mouse => CRASH

This works fine for me on the master. Try using the latest nightly build.

**Comment by ceraolo** [comment]
I've checked with today's nightly build and I confirm that the issue is not there anymore.

**Comment by adeas31** [comment]
Great! I am closing this issue then. I also fixed #9966.
