### ISSUE TITLE
Compatibility Issues on readRealParameter

### ISSUE THREAD

**Issue by acolov** [OpenModelica/OpenModelica#9968]
Hi everyone,

some months ago I successfully compiled and ran a complex model which was reading start parameters from an external txt file (all done in windows). The solution was optimal since the compiling time was pretty long (more or less 3 hrs in OMEdit 1.14.1) and this allowed to have fast simulations changing the parameters in the txt and running the .exe compiled model directly. 

Due to a PC update, I had to reinstall OMEdit, and I tried to install OMEdit 1.20.0 reading it was completely backward-compatible. 

The same model which still works on 1.14.1 (on another PC) does not start in 1.20.0. When I run it on the new front-end the following errors occur:
`Not possible to open file "*file path*\StartParameters.txt" for reading:
Too many open files`
`[Modelica.Utilities.Examples: 299:4-299:57]: [Failed to evaluate function: Modelica.Utilities.Streams.readLine.](omeditmessagesbrowser:///Modelica.Utilities.Examples?lineNumber=299)`

I tried to run it also using the old front-end and this error occurs:
```
`[615] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final.bat with mode 2: Too many open files

[616] 11:13:06 Translation Errore
[C:/OM120/OM64bit/OMCompiler/Compiler/SimCode/SimCodeUtil.mo: 15546:9-15546:91]: Internal error SimCodeMain.generateRunnerBatScript failed

[617] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_info.json with mode 2: Too many open files

[618] 11:13:06 Translation Errore
[C:/OM120/OM64bit/OMCompiler/Compiler/SimCode/SerializeModelInfo.mo: 116:9-116:84]: Internal error SerializeModelInfo.serialize failed

[619] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final.c with mode 2: Too many open files

[620] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_functions.c with mode 2: Too many open files

[621] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_model.h with mode 2: Too many open files

[622] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_18spd.c with mode 2: Too many open files

[623] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_16dae.h with mode 2: Too many open files

[624] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_16dae.c with mode 2: Too many open files

[625] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_17inl.c with mode 2: Too many open files

[626] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_15syn.c with mode 2: Too many open files

[627] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_14lnz.c with mode 2: Too many open files

[628] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_13opt.c with mode 2: Too many open files

[629] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_12jac.h with mode 2: Too many open files

[630] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_10asr.c with mode 2: Too many open files

[631] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_13opt.h with mode 2: Too many open files

[632] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_12jac.c with mode 2: Too many open files

[633] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_09alg.c with mode 2: Too many open files

[634] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_05evt.c with mode 2: Too many open files

[635] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_08bnd.c with mode 2: Too many open files

[636] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_04set.c with mode 2: Too many open files

[637] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_06inz.c with mode 2: Too many open files

[638] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_02nls.c with mode 2: Too many open files

[639] 11:13:06 Scripting Errore
Error writing to file Camera_ABCD_final_11mix.c.

[640] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_03lsy.c with mode 2: Too many open files

[641] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_01exo.c with mode 2: Too many open files

[642] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_07dly.c with mode 2: Too many open files

[643] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_literals.h with mode 2: Too many open files

[644] 11:13:06 Translation Errore
Template error: A template call failed (C:\Program Files\OpenModelica1.20.0-64bit\bin\OMEdit.exe: [unknown function name]). One possible reason could be that a template imported function call failed (which should not happen for functions called from within template code; templates assert pure 'match'/non-failing semantics).

[645] 11:13:06 Errore
File.open: Failed to open file Camera_ABCD_final_init.xml with mode 2: Too many open files

[646] 11:13:06 Translation Errore
[C:/OM120/OM64bit/OMCompiler/Compiler/SimCode/SimCodeMain.mo: 528:7-528:78]: Internal error C:\Program Files\OpenModelica1.20.0-64bit\bin\OMEdit.exe: [unknown function name] failed
`
```

To read parameters from StartParameters.txt i use the following line (there are multiple parameters to be read, for a total of 26 parameters):
```
 parameter String file = Modelica.Utilities.Files.loadResource("./StartParameters.txt") "File on which data is present" annotation(
    Dialog(loadSelector(filter = "Text files (*.txt)", caption = "Open text file to read parameters of the form \"name = value\"")));
parameter Modelica.Units.SI.HeatFlowRate SiPMpower = Modelica.Utilities.Examples.readRealParameter(file, "SiPMpower") "heat power on the 37 SiPM boards";
```

The txt file is present on the working directory.
How can I work with this model? Should I forget of the 1.20.0 and use only the 1.14.1 version of OMEdit? Moreover, since I've installed the 1.20.0 I cannot install the 1.14.1 anymore, It installs normally but after that it fails to start when I run the program, thus I would need to use another PC.

Thank you to anyone who has the time to look into this,

Alessandro

**Comment by casella** [comment]
@acolov OMC 1.14.1 is paleolithic, for sure you cannot remain stuck to that. BTW, I would expect the compile time with 1.20.0 to be significantly faster than 3 hrs.

`Modelica.Utilities.Examples.readRealParameter` calls `Modelica.Utilities.Streams.readLine`. The documentation of that function reads:
> Function readLine(..) opens the given file, reads enough of the content to get the requested line, and returns the line as a string. Lines are separated by LF or CR-LF; the returned string does not contain the line separator. _The file might remain open after the call_.

Looks like the same file is opened multiple times and OMC doesn't like it to be done 26 times for some reason. @mahge, maybe you have some clue why this is the case. Not sure if it's an easy fix, looks pretty low-level stuff.

@acolov one way to fix this at the Modelica source code level is the following:
- read the whole parameter file at once with `Modelica.Utilities.Streams.readFile` into a String array
- adapt function `Modelica.Utilities.Examples.readRealParameter` so that it reads the strings from the array instead of reading them from the file one by one using `readLine`

That should be rather straightforward.

**Comment by acolov** [comment]
thx @casella that was very useful! I'll try to read the whole file and then pass the array to the readRealParameter to avoid opening too many files.

**Comment by mahge** [comment]
> Looks like the same file is opened multiple times and OMC doesn't like it to be done 26 times for some reason. 

26 is probably the times it failed to open. It seems the _default_ max number of open files **per process** on Windows is 512. So it opened it 512 times and then started failing and reporting errors. Out of which, 26 are reported here.

I think you are right in the suggestion that _Modelica.Utilities.Streams.readLine_ does not close the file after reading. Looking at the ModelicaExternalC sources confirms that. You need to explicitly call [Modelica.Utilities.Streams.close](https://doc.modelica.org/om/Modelica.Utilities.Streams.close.html) after each _readLine_ call.  

@acolov  I think @casella's alternative is probably the correct way to do this anyway.
