### ISSUE TITLE
[OMPlot] Wrong time information when hovering a signal

### ISSUE THREAD

**Issue by hkiel** [OpenModelica/OpenModelica#9973]
### Description
The wrong point-in-time is shown in OMPlot when analysing a signal. The axis however is drawn correctly.

### Steps to Reproduce

Build a simple model, simulate(modelName, stopTime=**50**) and plot a variable. Hover the graph of the variable and look at the tooltip showing value and time. The time information is wrong ( "at #.## s" ). It seems to be in the range of 0 to 5 in this case.
Looks like maximum time value is taken and all trailing zeros removed to have the full scale (try with e.g. stopTime=800).

**Comment by casella** [comment]
@hkiel, same as #9950?

**Comment by hkiel** [comment]
Yes, this is a duplicate. Sorry for that - I did search existing issues, but did not look close enough. We can close this in favour of #9950.
