### ISSUE TITLE
dummy ticket

### ISSUE THREAD

**Issue by OpenModelica-TracImporter** [OpenModelica/OpenModelica#999]

**Comment by Kezii** [comment]
dummy comment

**Comment by adrpo** [comment]
We want to port all the Trac tickets to github, that's why we have these dummy tickets so that the Trac number and github numbers map one to one. This is work in progress.

**Comment by bilderbuchi** [comment]
This is a dummy ticket even in [trac](https://trac.openmodelica.org/OpenModelica/ticket/999), so I think it can be safely closed. :P
