### ISSUE TITLE
ScalableTestSuite TransmissionLineEquations models fail during NBResolveSingularities.balanceInitialization

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9997]
Please check [ScalableTestSuite.Electrical.TransmissionLine.ScaledExperiments.TransmissionLineEquations_N_10](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Electrical.TransmissionLine.ScaledExperiments.TransmissionLineEquations_N_10.err). The NB fails with
```
Error: Internal error NBResolveSingularities.balanceInitialization failed because following non-fixable
variables could not be solved:
        [DER-] (10) Real[10] $DER.cur
```

**Comment by kabdelhak** [comment]
Looking at this model it looks like it is the same problem as described in #9414.

The variable `cur` is only a state from index 1-9. The last one seems to be algebraic and solved in ` vol[10] = cur[10] * RL;`, as already described the NB currently is not able to handle this. Creating an artificial alias variable representing this state slice should solve the problem.

I could create those in the backend, but there will be future problems regarding index reduction and certain irregular state slicing. I want to come up with a good solution before implementing something half baked, posing problems in the future.

**Comment by casella** [comment]
Ops, I missed that, sorry. At the end of the day, these are all finite volumes approximations of 1D PDEs, so the story is more or less the same everywhere. I agree that we should avoid half-baked solutions here, I'll fix the library ASAP. Thanks!

**Comment by casella** [comment]
In the meantime, it would be nice if we could get some simple diagnostics of all these cases with slices of states, instead of getting weird errors. I'm not sure if this is a trivial task or a difficult one.

**Comment by kabdelhak** [comment]
> In the meantime, it would be nice if we could get some simple diagnostics of all these cases with slices of states, instead of getting weird errors. I'm not sure if this is a trivial task or a difficult one.

I guess i could do something like that. I would need to update the state detection algorithm, but i probably need to do that in the future anyway. I will try to come up with a clean way to do so, such that i can use it later on.

**Comment by casella** [comment]
Anyway, this is not urgent, at the moment the new backend is still experimental, and that's OK.

**Comment by casella** [comment]
The updated model now [passes the code generation phase successfully](https://libraries.openmodelica.org/branches/newInst-newBackend/ScalableTestSuite_noopt/files/ScalableTestSuite_noopt_ScalableTestSuite.Electrical.TransmissionLine.ScaledExperiments.TransmissionLineEquations_N_10.err), then it has issues with the generated C-code, but this is another story.
